### ISSUE TITLE
Keep viability for compilation to WebAssembly or transpilation via Emscripten in mind

### ISSUE THREAD

**Issue by grorg** [gpuweb/gpuweb#1]
This is migrating the gpuweb/admin#2 issue. Originally from @thokra1

First off, something on the status-quo as I perceive it. My major gripe with WebGL is its horribly slow adoption rate and the fact that WebGL2 will be outdated as soon as it is ratified compared to GLES3.2 and OpenGL 4.5 certainly does not help. I currently find myself implementing an OpenGL 4.5/GLES2 based rendering framework for a special purpose (so Unity and Unreal are currently intentionally out of the picture). While being able to (de-facto) seemlessly transpile the GLES codepath to WebGL, it is very disconcerting having to drop all the goodness we have come to expect from OpenGL 4.5 (including but not limited to the AZDO paradigm). I imagine Unity and Unreal developers feel the same way. Frankly, as a developer mainly dabbling in stuff on the desktop, it is beyond me why exposing desktop OpenGL in a browser and on mobile devices should not be possible today - current hardware certainly should not pose much of a problem (please correct me if I'm wrong there).

Despite that major problem, having a single code base, for instance in C++, which can be compiled for different targets like x86_64 and ARM and (at this time) transpiled to JavaScript is pretty sweet. As a developer working primarily on and for the desktop, I'd like to be able to reuse my C++ code wherever possible. IIUC, the formalization of WebAssembly and the possibility to let your compiler spit out the IR will only make this more convenient - which is also a major step in the right direction. Even though my knowledge of the Web as a platform is limited, step-by-step elimination of hurdles for multi-platform deployment and consistent user experience is what I consider one of the most important mid- or long-term goals.

This also applies to the WebGPU proposal. For example, I'd like to be able to write something on the desktop and deploy it on all relevant platforms - ideally using the same set of features. Having a close or even one-to-one API correspondence currently enables me to do that when I limit myself to GLES2 and WebGL. I urge you to keep that in mind when specifying a WebGPU API - I don't care how this is achieved, but I desperately want it and I think we all need it. Ideally, I imagine a unified approach to all platforms which currently can be (at least to a degree) achieved with the help of Emscripten and frameworks like electron.

This immediately impacts certain choices currently made for the proposal which I find highly debatable, including the choice of shading language. Being forced to deploy shaders written in two different languages unnecessarily increases complexity. Also, why would you demand that developers learn a fringe shading language and why would you define another IR for something that is already in place with e.g. SPIR-V? I can see some of the benefits of the Metal SL (like being able to modularize properly without having to employ a de-factor VFS with GL_ARB_shading_language_include). I also understand that for something that comes out of Apple, it makes sense to advertise in-house technology, but I think we all might be better off if you just turn to your fellow Khronos members and handle this business with all members of the industry participating. Just improve GLSL or define something new as a concerted industry effort (unless you want the Metal SL to be just that, in which case I want you to provide a SPIR-V compiler).

Something on which I'd like to have some clarification is the fact that OpenGL and Vulkan, while usable to achieve the same observable result, they are very different APIs which both exist in their own right. I can see a ton of scenarios where implementing a Vulkan renderer is not necessary. On the other hand, OpenGL carries some historically based design flaws which can be properly handled with Vulkan (e.g. multi-threaded command buffer submission) and, by design and due to resulting implementations, is (supposedly) not able to outmatch Vulkan in regards to performance.

While the WebGPU proposal addresses the necessity to expose something akin to Vulkan in the browser, this does not solve any problems for people wanting to use the latest GPU features through OpenGL - unless someone comes up with an implementation of OpenGL atop WebGPU. I don't want to be forced to use either technology - I want to be enabled to choose the API according to necessity. Do you think this is possible and something to strive for?

**Comment by grorg** [comment]
Note there are a couple of comments in the original issue that I haven't copied. Please follow the link if the authors don't repost them.

**Comment by thokra1** [comment]
@grorg: TY for moving this!

**Comment by othermaciej** [comment]
This is an important feature, but it's worth noting that WebAssembly doesn't yet have a defined way to expose APIs to it directly. This group will likely have to collaborate with the WebAssembly CG to make sure it gains the right features.

**Comment by devshgraphicsprogramming** [comment]
It would be very nice to either:
1. Have a WebGPU library/binding for C that can be used to prototype desktop apps that are about to be ported
2. Provide headers that will allow us to use the webGPU functions explicitly (like emscripten currently does only with the context creation) as opposed to the current approach of magically translating OpenGL and ES function calls into webGL

I think this is required because the difference between webGPU and any other of the 3 APIs (Vulkan/D3D12/Metal) will be rather profound, barring a 1:1 mapping between API functions.

**Comment by kainino0x** [comment]
Dawn has this as a primary goal. Its native interface will match as closely as possible to the real WebGPU interface. We intend for the porting steps to be:
  - Get C/C++ native app linking with Dawn
  - Include WebGPU C headers (and probably link Dawn's C++-on-C layer)
  - Get native app working with Dawn as a graphics backend
  - Build with Emscripten and unlink Dawn: application links against Emscripten's implementation of the same C headers (a thin translation layer to WebGPU)

There has been talk of a Vulkan Portability implementation on top of WebGPU, but it's a larger effort.

**Comment by devshgraphicsprogramming** [comment]
@Kangz pointed out Dawn to me, I like the Emscripten workflow... maybe I could have a port of my engine running from day 0 of webGPU 1.0 (as long as Emscripten supports the unlinking by then).

**Comment by kainino0x** [comment]
[cleanup] I don't think we need this issue open to keep this in mind. I'm certain that we will do our due diligence to make sure the API works well with WebAssembly and Emscripten before shipping it.
