### ISSUE TITLE
develop webvulkan , adopt webgpu or continue with webgl ?

### ISSUE THREAD

**Issue by diegor8** [gpuweb/gpuweb#10]
https://github.com/KhronosGroup/Vulkan-Docs/issues/451

**Comment by kvark** [comment]
The issue makes little sense. If you want webvulkan, you'll need to make a proposal. WebGPU is already proposed, and continue with WebGL is your choice outside of the scope of this group. I suggest this to be closed.

**Comment by Brynyard** [comment]
There you go:
https://github.com/kvark/WebGLNext-Proposals/tree/obsidian

**Comment by kvark** [comment]
@Brynyard better link to the submitted proposal than my personal branch:
https://github.com/KhronosGroup/WebGLNext-Proposals/tree/master/Obsidian-Mozilla
