### ISSUE TITLE
WGSL should require uniform storage class variables to be [[block]] decorated.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1004]
The uniform storage class should be restricted to [[block]] decorated types (structs). This matches what Vulkan requires.

**Comment by kvark** [comment]
Is there a choice here that the user makes (wrt placing `[[block]]`)?

**Comment by dj2** [comment]
Not currently. Currently structs are always typedef'd. This is more to restrict so you can't say:

```
var<uniform> b : f32;
```

but have to say something like:
```
type Uniforms = [[block]] struct {
  [[offset 0]] b : f32;
}
var<uniform> b : Uniforms;
```

**Comment by dj2** [comment]
This is also the case for storage buffers. In vulkan they must be block decorated, so I believe we have the same restriction in WGSL. So, the requirement to have [[block]] decorated type is for both uniform and storage_buffer storage classes.

**Comment by kvark** [comment]
The argument voiced on the call (by @jdashg IIRC) was that `[[block]]` would also mean you can't embed this structure into another structure. This means it's useful signalling, and if we try to automatically derive it, it may be tricky to specify, i.e. "if there is any binding to this structure type statically used by the current entry point, then it can't be used as a field in another structure that is also statically used by the current entry point".... yikes!.

**Comment by grorg** [comment]
Discussed at the [2020-08-18 meeting](https://docs.google.com/document/d/1P7XNQ760P5yONHTkhGAlP-AA2VpggNDGMGHaGAE2tn0/edit#).

Resolution: a uniform variable must be a `[[block]]` decorated structure. Follow-up issue raised above about making them optional #1008.
