### ISSUE TITLE
In types, default to f32 when no templates are present

### ISSUE THREAD

**Issue by lachlansneff** [gpuweb/gpuweb#1012]
I think there's been discussion on this in the past, but I'm not sure if it was resolved or not.

WGSL has several of types with a generic type argument, see `vec2<f32>`, `mat2x3<f32>`. For ergonomic reasons, I propose that these types should default to an `f32` type argument when one is not present.

That's it. If this has been resolved elsewhere, let me know :)

Edit: Oh, an `mat3x3` could have an alias of `mat3`, but that's a separate issue.

**Comment by dj2** [comment]
Other than slightly less typing, I find this makes the code harder to read. Having the type (and both matrix dimensions) spelled out makes it a lot more obvious when looking at a shader what the types are.

Is there a benefit to this that I'm not seeing?

**Comment by lachlansneff** [comment]
@dj2 Nope, that's it. There aren't any other benefits other than less typing and maybe slightly shorter lines of code. 

As an example:
```glsl
[[builtin position]] var<out> o_position : vec4<f32>;

fn main() -> void {
  o_position = vec4<f32>(1);
  return;
}
entry_point vertex as "main" = main;
```

would become

```glsl
[[builtin position]] var<out> o_position : vec4;

fn main() -> void {
  o_position = vec4(1);
  return;
}
entry_point vertex as "main" = main;

```

**Comment by kainino0x** [comment]
As discussed in Slack, the proposal in https://github.com/gpuweb/gpuweb/issues/736#issuecomment-634217336 should make this not necessary (it allows you to opt-in to `fvec4` etc. shorthands).
