### ISSUE TITLE
Validate that [[builtin fragDepth]] can't be written if depthWriteEnabled = false?

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1013]
It is possible to write the depth of a fragment by using the `[[builtin fragDepth]]` but on some drivers (Intel Vulkan Mesa) this doesn't work if the `GPURenderPipeline` was created with `depthWriteEnabled = false`. Should we validate this out and only allow writing the fragment depth is depth-writing is enabled?

Same question, should we allow reading `[[builtin fragDepth]]` if there is no depth attachment format specified? Are there other builtins that need such validation?

**Comment by kvark** [comment]
This needs an investigation wrt support in the backend APIs. Technically, drivers could see the builtin output, and enable the late depth test based on the modified depth of a fragment.

**Comment by Kangz** [comment]
Ah, good point, so writing `[[buitin fragDepth]]` with `depthWriteEnabled=false` could still perform the late depth check but skip the late depth write. We'll need to see how these things are specified in various APIs.

**Comment by kainino0x** [comment]
It seems very likely to me that developers will expect this to work. IIRC it's normally possible to depth-test without writing depth, so it would be surprising and likely problematic if writing frag_depth broke that.

We should check specs and then write tests that ensure the behavior is consistent in backends.

**Comment by kainino0x** [comment]
> on some drivers (Intel Vulkan Mesa) this doesn't work if the `GPURenderPipeline` was created with `depthWriteEnabled = false`.

Oh, I forgot about this problem. Hopefully we can find something in the Vulkan spec that explains this.

**Comment by kainino0x** [comment]
So far I haven't found any carveouts in Vulkan. At first glance it seems pretty straightforward:

> Writing to the [`FragDepth`](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap15.html#interfaces-builtin-variables-fragdepth) built-in will replace the fragment's calculated depth values for each sample in the input `SampleMask`. [Depth testing](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap26.html#fragops-depth) performed after the fragment shader for this fragment will use this new value as z<sub>f</sub>.

> If depth writes are enabled, as specified by [VkPipelineDepthStencilStateCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap26.html#VkPipelineDepthStencilStateCreateInfo)::`depthWriteEnable`, and the comparison evaluated to true, the depth attachment value z<sub>a</sub> is set to the sample's depth value z<sub>f</sub>. If there is no depth attachment, no value is written.

**Comment by kainino0x** [comment]
FTR here's the Dawn bug about the Intel driver issue: https://crbug.com/dawn/821

**Comment by Kangz** [comment]
@Jiawei-Shao can you confirm that this is an Intel driver issue and the spec doesn't need a change?

**Comment by Jiawei-Shao** [comment]
Hi @Kangz, 

This is an old [Intel Mesa driver issue](https://gitlab.freedesktop.org/drm/intel/-/issues/2585) (reproduceable on Mesa 19.0.2), and it cannot be reproduced on Mesa 20.0.8 (used by Ubuntu 18.0.6 LTS) and latest Mesa (Mesa 22.1.0-develgit-).

**Comment by Kangz** [comment]
Thanks for checking. Since this is a driver bug I'll close the issue as something that doesn't need to be fixed in the spec.
