### ISSUE TITLE
Move texture methods into an import?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1018]
Currently the texture methods are dropped into the global namespace. They feel like they should move behind an import and you'd then do something like:

```
import "textures.wgsl.1" as tex;

tex::texture_load(...);
```

instead of having them directly accessible.

**Comment by kvark** [comment]
What's the motivation here? It's not in a namespace in any of the APIs, as far as I understand, and it's not like people can really poly-fill these functions themselves in user-space.

**Comment by kainino0x** [comment]
One nice thing is that, as discussed on #600, it allows adding new identifiers without technically-breaking changes.

**Comment by kvark** [comment]
We could also have them as methods on the types, in which case it's forward-compatible. I.e. `texture.sample()` and so on.

**Comment by kvark** [comment]
I agree that moving texture sampling into methods wouldn't address a more general problem of name collisions. So we should figure out the namespaces for these functions, as you originally attempted in this issue.

If we have a namespace dedicated to texture ops, i.e. `tex`, would we still need to have `texture_` prefix on all the functions?
I wonder if we should go for `tex::load` instead, and so on.

**Comment by dj2** [comment]
We probably don't need the `texture_` prefix, so I think it could be dropped.  That means we'd end up with, essentially:

```
Module texture.wgsl.1 {
  vec4<type> load(texture_ro, i32 coords, i32 level_of_detail)
  vec4<type> load(texture_ro, vec2<i32> coords, i32 level_of_detail)
  vec4<type> load(texture_ro, vec3<i32> coords, i32 level_of_detail)

  vec4<type> sample(texture_sampled, sampler, f32 coords)
  vec4<type> sample(texture_sampled, sampler, vec2<f32> coords)
  vec4<type> sample(texture_sampled, sampler, vec3<f32> coords)
  vec4<type> sample(texture_sampled, sampler, vec4<f32> coords)

  vec4<type> sample_level(texture_sampled, sampler, f32 coords, f32 lod)
  vec4<type> sample_level(texture_sampled, sampler, vec2<f32> coords, f32 lod)
  vec4<type> sample_level(texture_sampled, sampler, vec3<f32> coords, f32 lod)
  vec4<type> sample_level(texture_sampled, sampler, vec4<f32> coords, f32 lod)

  vec4<type> sample_bias(texture_sampled, sampler, f32 coords, f32 bias)
  vec4<type> sample_bias(texture_sampled, sampler, vec2<f32> coords, f32 bias)
  vec4<type> sample_bias(texture_sampled, sampler, vec3<f32> coords, f32 bias)
  vec4<type> sample_bias(texture_sampled, sampler, vec4<f32> coords, f32 bias)
  
  f32 sample_compare(texture_depth, sampler_comparison, f32 coords, f32 depth_reference)
  f32 sample_compare(texture_depth, sampler_comparison, vec2<f32> coords, f32 depth_reference)
  f32 sample_compare(texture_depth, sampler_comparison, vec3<f32> coords, f32 depth_reference)
}
```

`import "texture.wgsl.1" as tex;` and the shortned usage of `tex::load`.

**Comment by jdashg** [comment]
In today's meeting we moved towards:
`import std`
`import * from std`
`import texture_load, texture_store from std`
`import std as s`

The major win for having a std namespace is it's a flexible way to reserve names for future builtins. By reserving (or forbidding additions to) some std namespace, we prevent someone adding e.g. atan2 before we get around to it, which could cause our addition of a standard atan2 to break existing content.

I'm not sold on having e.g. std.tex.load nested namespaces, but at least one non-user-writable namespace seems like the rough consensus.

**Comment by jdashg** [comment]
Also noted that "l.1" in "wgsl.1" is less than ideally legible.

**Comment by kainino0x** [comment]
The consensus from #600 was to only have `import std`/`import std as s` but not `import ... from std` for MVP; has the thinking changed?

**Comment by dj2** [comment]
My preference would be to leave `import s` out of MVP as well and see if there is demand for it.

**Comment by grorg** [comment]
Meeting discussion is here for reference [2020-08-25 meeting](https://docs.google.com/document/d/13lWCWtooVE1kT6TGta16gM-dDXjRdUKt9KG_9cTcTkY/edit?usp=sharing).

**Comment by grorg** [comment]
I believe the resolution from the meeting was that we'd use `wgsl::` not `std::`.

**Comment by dj2** [comment]
The name used `wgsl::` vs `std::` is up to the author when they do the import. The important bit was we're moving `texture` methods inside the import. We'll have one import. It will be "WGSL" instead of "GLSL.std.450"

**Comment by dj2** [comment]
I'm marking this as fixed for now. We decided in the most recent meeting to hold off on this to see just how large the stdlib ends up being.
