### ISSUE TITLE
Are entryPoints namespaces per module or per stage per module?

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1023]
When writing WGSL it is possible to define multiple entrypoints in a single module. However what's the constraint on entry point names? Obviously two entry points for the same stage can't have the same name, but are entry points allowed to have the same name when they are for different stages.

I think it would make sense to have a namespace per stage, WDYT?

**Comment by dj2** [comment]
I think we should restrict the API and WGSL to require different names per stage. So, essentially, names in a module must be unique. This is because for HLSL we just output the functions, and having multiple functions with the same name is going to be troublesome.

**Comment by kvark** [comment]
In SPIR-V they are namespaced per stage.

> I think we should restrict the API and WGSL to require different names per stage. So, essentially, names in a module must be unique. This is because for HLSL we just output the functions, and having multiple functions with the same name is going to be troublesome.

If the HLSL backend needs to rename a few functions internally, this is no big deal, and totally transparent from the user.

However, if we force the names to be unique, converting from SPIR-V will not work for some of the modules.

**Comment by dj2** [comment]
Good point, filed a bug in Tint to do the renaming in the HLSL backend.

**Comment by dneto0** [comment]
Discussed [2020-09-22](https://docs.google.com/document/d/1CFkoT9Iqdwej_OW5TXbOHSMVxfMnrWKwf7bOuXgPx2U/edit#)

- Decided to use the most restrictive rule:  entry point names are in the same namespace as everything else. 
- We can revisit and relax this later if we like.

**Comment by dj2** [comment]
Going to close this as I believe it just falls under the general function names must be unique rule so there is nothing to change here.
