### ISSUE TITLE
WGSL should use `thread` instead of `invocation`

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#1031]
Host specification for WebGPU [uses](https://gpuweb.github.io/gpuweb/#security-uninitialized) _thread_ instead of _invocation_, and accordingly, for consistency, corresponding WGSL entries should adopt _thread_ naming too (say, instead of `local_invocation_idx`). Metal does a great job at this (and matches with its usage of grid, which is the case in WebGPU host specification too): `thread_position_in_grid`, `threadgroup_position_in_grid`, `thread_index_in_threadgroup`, `thread_index_in_simdgroup`, ...

**Comment by dj2** [comment]
It seems to use both with the `GPUPipelineStatisticName` listing invocations.

**Comment by mehmetoguzderin** [comment]
> It seems to use both with the `GPUPipelineStatisticName` listing invocations.

AFAIK, all uses of `invocation` is in statistics, which is consistent with all APIs (see [DirectX](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_query_data_pipeline_statistics) [Metal](https://developer.apple.com/documentation/metal/mtlcommoncounter) and contrast their usage of `thread`), but it is important to note that these do not refer to compute kernels.

**Comment by johnkslang** [comment]
FYI, other APIs and GPU languages chose invocation because thread was one of the various platform-dependent words getting used to describe how their systems worked.  Invocation carried less baggage and hence could more easily carry a precise definition.

**Comment by mehmetoguzderin** [comment]
> FYI, other APIs and GPU languages chose invocation because thread was one of the various platform-dependent words getting used to describe how their systems worked.  Invocation carried less baggage and hence could more easily carry a precise definition.

@johnkslang That sounds like a possible background for the SPIR-V case. However, I didn't open the issue for a naming discussion but instead **for consistency across WebGPU**. And it seems like the majority of API providers and GPU ISA authors find `thread` non-ambiguous enough.

**Comment by Kangz** [comment]
+1 as to what @johnkslang said about invocation having less baggage. Thread is heavily used in CPU land where any two threads are completely independent. Invocation just says that the entryPoint is called but doesn't tie to any other semantic. 

Likewise SIMD group is an implementation detail of most recent GPUs, but for example NVIDIA's Ampere architecture has a program counter per invocation so SIMD isn't good naming anymore. Subgroup isn't super great either, maybe D3D12's "wave" naming makes the most sense in that it is novel too.

**Comment by mehmetoguzderin** [comment]
> +1 as to what @johnkslang said about invocation having less baggage. Thread is heavily used in CPU land where any two threads are completely independent. Invocation just says that the entryPoint is called but doesn't tie to any other semantic. 
> 
> 
> 
> Likewise SIMD group is an implementation detail of most recent GPUs, but for example NVIDIA's Ampere architecture has a program counter per invocation so SIMD isn't good naming anymore. Subgroup isn't super great either, maybe D3D12's "wave" naming makes the most sense in that it is novel too.

@Kangz AMD uses wave for collection of SIMD units (in GCN, a wavefront is a grouping of four SIMD16 and in RDNA, a wavefront is either a Wave32 from one SIMD32 or a Wave64 from two SIMD32 units), and I also like wave naming but SIMD is still a valid analogy (very subjective). But I think this discussion would better take place in SIMD PR because the SIMD examples I put in OP is just for demonstrating generalization of the naming convention in MSL.

**Comment by mehmetoguzderin** [comment]
FYI, since this is popping up repeatedly, the formal name is not "program counter per invocation" but is ["per-thread program counter"](https://images.nvidia.com/content/volta-architecture/pdf/volta-architecture-whitepaper.pdf#page32) and is available since Volta, not new in Ampere.

**Comment by dneto0** [comment]
Threads on the API side are different from invocations/threads in the shader.

There *should* be an expectation that behaviours can be different, e.g. around forward progress.  The analogy to CPU threads misleads.

**Comment by kainino0x** [comment]
I think Oguz is talking about references to shader threads in the API spec, not CPU threads. Like "X dimension of the grid of thread groups to dispatch."

**Comment by mehmetoguzderin** [comment]
As @kainino0x pointed out, the host specification section OP cites ([Uninitialized data](https://gpuweb.github.io/gpuweb/#security-uninitialized), please refer to the second paragraph) talks about "GPU threads" when saying `thread`. And calls the sections of the dispatch grid as thread group.

**Comment by mehmetoguzderin** [comment]
Adressed by https://github.com/gpuweb/gpuweb/pull/1095
