### ISSUE TITLE
Bit preserving floating point conversion expressions

### ISSUE THREAD

**Issue by MatusT** [gpuweb/gpuweb#1035]
Hello,

In [Naga](https://github.com/gfx-rs/naga) we would like to implement OpBitcast instruction for WGSL. 

However, the spec at https://gpuweb.github.io/gpuweb/wgsl.html#conversion-expr is missing bit preserving conversions for floating points. Here is a table of bit preserving conversions for every shading language:

| Result type | Type of variable |    WGSL    |    GLSL                     |     HLSL     | MSL |
| ------------ | ----------------- | ----------- | ----------------------| ----------- | - |
| i32              | u32                    |  ```i32(v)```       | ```int(v)```                        | ```asint(v)```      | ```as_type<int>(v)``` |
| u32              | i32                     |  ```u32(v)```      | ```uint(v)```                     | ```asuint(v)```    | ```as_type<uint>(v)``` |
| i32              | f32                     |  ?              | ```floatBitsToInt(v) ```      | ```asint(v)```      | ```as_type<int>(v)``` |
| u32             | f32                     |  ?              | ```floatBitsToUInt(v) ```   | ```asuint(v)```    | ```as_type<uint>(v)``` |
| f32              | i32                     |  ?              | ```intBitsToFloat(v)```      | ```asfloat(v)```  | ```as_type<float>(v)``` |
| f32              | u32                    |  ?              |``` untBitsToFloat(v)```     | ```asfloat(v)```   | ```as_type<float>(v)``` |

The current spec leads to inconsistent handling as in GLSL.

As there are no proposal that I am aware of, I propose to steer away from the current way in the spec and follow consistency set by HLSL and MSL.

My proposal is one set of functions for numerical conversions and one set for bit preserving. They could look like:
Numerical: ```i32(v)```
Bit-preserving: ```bits_to_i32(v)```

The numerical ones could also be used for truncating/extending *Convert instructions ```i16(i32)``` -> ```OpSConvert```.

**Comment by dj2** [comment]
This exists in WGSL now, see the `as` keyword. This converts to `OpBitcast` in SPIR-V. The numerical conversions all fall under the `cast` operator which convert to various SPIR-V opcodes.

**Comment by dj2** [comment]
The spec text for `cast` and `as` hasn't been flushed out yet, which is why it's marked as TODO.

**Comment by kvark** [comment]
Isn't it specced backwards today? The "cast" corresponds to SPIR-V conversion opcodes, and "as" corresponds to bitcast?

**Comment by dj2** [comment]
I don't think so? For me, take this thing `as` this other thing without conversion. Vs `cast` (convert) this thing to this other thing.

**Comment by kvark** [comment]
So you are fine with WGSL's "cast" meaning an opposite thing from SPIR-V's "bitcast"?
In Rust, `as` is the conversion operator, not a bitwise reinterpretation. And it looks like SPIR-V agrees that "cast" should mean reinterpretation. I don't see why WGSL should be different.

**Comment by dj2** [comment]
Sure, `cast` isn't `bitcast`. The cast is converting one type to another which is the meaning I've always seen for `cast`. Changing the name to `bitcast` is a different word with a different meaning.

**Comment by dneto0** [comment]
Our (my) intent was to follow the example of OpenCL C.  There the as_BLAH is a reinterpretation-of-bits operation.

https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_C.html

> Reinterpreting Types Using as_type() and as_typen()
All data types described in Built-in Scalar Data Types and Built-in Vector Data Types (except bool, half12 and void) may be also reinterpreted as another data type of the same size using the as_type() operator for scalar data types and the as_typen() operator13 for vector data types. When the operand and result type contain the same number of elements, the bits in the operand shall be returned directly without modification as the new type. The usual type promotion for function arguments shall not be performed.

...

> For example, as_float(0x3f800000) returns 1.0f, which is the value that the bit pattern 0x3f800000 has if viewed as an IEEE-754 single precision value.


This functionality was in OpenCL 1.0.

For value-conversion, OpenCL C has a big matrix of convert_DESTTYPE(SRCTYPE) functions. 
See "6.2.3. Explicit Conversions".  The ones that convert from floating point to integral types also have variations for saturation and \ rounding mode.  For example convert_uint_sat_rte(1.5f) yields  2u.

**Comment by kvark** [comment]
Looks like everybody likes to call these things differently :/
The OpenCL argument is convincing. I'm fine with leaving this decision to WGSL editors to figure out.

**Comment by dneto0** [comment]
I can see an argument about whether a `convert` is a better name than `cast`.  `cast` is overloaded; C++ has four kinds of casts!

**Comment by kvark** [comment]
Convert is surely least ambiguous (and matches SPIR-V).

**Comment by johnkslang** [comment]
Note that GLSL intBitsToFloat() is not a bit-preserving bitcast.  Things like NaN and denorm might effect the result.

**Comment by MatusT** [comment]
> Note that GLSL intBitsToFloat() is not a bit-preserving bitcast. Things like NaN and denorm might effect the result.

Which is fun because glslang translates intBitsToFloat directly to OpBitcast http://shader-playground.timjones.io/503980c58269291a0bde3ed434fdaddc and SPIR-V spec doesn't say anything NaN like the glsl spec does.

**Comment by johnkslang** [comment]
Oh, too fun.   The original SPIR-V (0.99) had these in the GLSL extended instruction set, and the group decided to remove them in favor of bitcast, which was perhaps a mistake?  It may just be a matter of efficiency.  

But, then, the denorm issue is new, and unresolved, not something considered back then.

It might be worth being aware if pure bitcast of int to float is really needed:

- if the very next thing done with the float is "floatish", then the denorm and NaN will come into play anyway
- if the very next thing done with the float is not "floatish", then perhaps the bitcast was not called for to begin with

**Comment by johnkslang** [comment]
How are you handling hardware differences in general with denorms?  And are you really totally locking down NaN bit patterns?  (I'm skeptical that this is a novel aspect of this issue.)

**Comment by johnkslang** [comment]
I guess my main point is this:  It is okay to have something called `intBitsToFloat` and/or use constructors, to have a place to describe (possibly imperfect) semantics rather than have generic bit casting syntax.

Or, more generically, it's all function-calling syntax, with names that can each have their own semantics, with no casting syntax that brings ambiguities and/or forced generalizations.

**Comment by dj2** [comment]
That's, effectively, what we have. We just called it `as<>`. We have a TODO to write the semantics of what `as` does.

**Comment by grorg** [comment]
Discussed at [2020-09-01 meeting](https://docs.google.com/document/d/1oss59oRXn0XyCe-xe9-Wkud8dwfmET70VuMDdOou2t0/).

Resolution: Delete ‘cast’ and rename ‘as’ to ‘bitCast’.
