### ISSUE TITLE
Compatible usage rules are unimplementable in D3D12

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1044]
(without pipeline recompilation)

When compiling a pipeline against layout using a `readonly-storage-buffer` binding type, we need to make a choice in D3D12: make it use a `u` UAV register or a `s` SRV register.

 - If we're using a `u` register, then the buffer must be in the `D3D12_RESOURCE_STATE_UNORDERED_ACCESS` state which isn't allowed to be used with readonly states, and conflicts with this compatible usage set: *"Each usage in U is input, constant, storage-read, or attachment-read."*
 - If we're using a `s` register, then the buffer must be in  either the `D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE` or
`D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE`
 state which isn't allowed to be used with read/write states, and conflicts with this compatible usage set: *"Each usage in U is storage or storage-read."*

@RafaelCintron @damyanp is there any way around this? It's pretty restrictive considering buffers always have a linear layout.

Otherwise I think we should remove *"Each usage in U is storage or storage-read."* from the list as the purpose of `readonly-storage-buffer` is that it can be used at the same time as other readonly states.

**Comment by damyanp** [comment]
I'm not sure why you'd want to use a UAV register for readonly-storage-buffer - unless there's a good reason, my initial reaction would be to always use SRVs for these and figure out how to make that work.

I'm trying to understand what this part of the spec is trying to say.  Why can't the subresource be transitioned to the appropriate *_SHADER_RESOURCE state before the draw/dispatch?

**Comment by magcius** [comment]
I expect readonly storage buffers to be equivalent to ByteAddressBuffer / StructuredBuffer, and storage-readonly to map to `D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE | D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE`, aka the "read-only resource" state.
