### ISSUE TITLE
Compute dispatch sizes must be positive in each dimension

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1045]
There are two ways to launch compute shaders:
* Scheduled via GPUComputePassEncoder.dispatch(sizex, sizey, sizez)
* Scheduled via GPUComputePassEncoder.dispatchIndirect  (where the sizes are written to memory)

The compute grid must have positive size in each of the x, y, and z dimensions.  This can be checked directly by  the dispatch(...) method.  I think the dispatch should fail if any dimension is zero.

For the dispatchIndirect command, the sizes are read from memory.  So:

1.  When does that occur?  It's later than the time you record the command. How late can it be? Just before the command executes?

2. What happens if one of the dimensions is zero. (It's already unsigned).  I think we have two options that are well defined and sensible: assume it's 1, or don't execute the compute shader at all (i.e. the shader has no effect, but synchronization actions around the command still occur).  I would prefer the no-effect shader behaviour.

This crosses the boundary between the API and the shader language.  Depending on when the indirect dispatch sizes are read, we might have to modify shader code to do an early exit.

**Comment by kvark** [comment]
I think a bit of investigation on the native APIs is missing here. Are any of the APIs treat 0 as invalid use?

**Comment by dneto0** [comment]
Hmmm.

Reading Vulkan's description of vkCmdDispatch, it says

> When the command is executed, a global workgroup consisting of groupCountX × groupCountY × groupCountZ local workgroups is assembled.

The zero case sounds like it falls out naturally as "no workgroups will be executed".  So maybe it's not a special case at all.

**Comment by dneto0** [comment]
Metal's dispatchThreadGroups says

> Metal calculates the number of threads in a grid by multiplying the size of a threadgroup (threadsPerThreadgroup) by the number of threadgroups (threadgroupsPerGrid).

So again, the zero case should fall out as "execute no threads".

Maybe this issue turns into a request to test this in CTS.

**Comment by dneto0** [comment]
DX12 Dispatch reads the same way to me.  https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-dispatch

**Comment by kvark** [comment]
I call it a win :)

**Comment by kainino0x** [comment]
I was going to move this to "Needs Testing" but it's already in the test plan:
https://hackmd.io/JlotfD3PSB2Ja4XAA27axg#encodingcmdscompute_passspects

So I think we can close this (unless testing reveals there's a problem, and we can't just paper over it).
