### ISSUE TITLE
BindGroup model amenable to GC garbage every frame

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#105]
Hi. I'm writing a [WebGPU-inspired rendering API](https://github.com/magcius/model-viewer/blob/master/src/gfx/platform/GfxPlatform.ts) currently backed by WebGL2 in my project in hopes of making it portable when the WebGPU prototype arrives. One of my goals for this project overall is little-to-minimal garbage or GC pressure, since GC pauses are still too expensive for real-time 60fps playback.

Currently, I notice that to bind a different UBO or texture every frame (for something like texture animation, or sampling a render target which might ping/pong between different backing storages every frame) requires a new call to `WebGPUDevice.createBindGroup`. All of the native APIs have some way of updating these bindings from a command buffer (e.g. Vulkan has vkCmdPushDescriptorSet).

One possibility to prevent this garbage would be to have `WebGPUProgrammablePassEncoder.updateBindGroup(WebGPUBindGroup, WebGPUBindGroupDescriptor)`. This would be a CommandBuffer method that would update the bind group with the new items and synchronize if necessary. It should be possible to implement on every backend pretty easily without too much complexity.

**Comment by Kangz** [comment]
That's pretty cool, a WebGPU.js that translates to WebGL would be very useful.

We have been discussing adding support for "dynamic buffer offsets" where the offset at which a UBO is bound is left TBD until `SetBindGroup`. This should solve your problem. `updateBindGroup` wouldn't work on Vulkan 1.0 though unless it created a new bindgroup in the implementation. (like the difference between virtual and physical registers in modern processors).

Another option if we have push constants, is to have UBOs bind whole arrays of the same uniform data and have an index stored in push constants.

**Comment by magcius** [comment]
That wouldn't handle sampler/texture view rebinding, would it?

**Comment by Kangz** [comment]
Ah sorry, I skipped over the texture ping-ponging. I don't think we'll have a solution to this in the very short-term, however can't you just create a bindgroup for each texture at startup and use that?

**Comment by magcius** [comment]
The difficulty there is that it might not match my BindGroup layouts -- e.g. sometimes I want to have 8 textures in a BindGroup layout. I could just make each texture in its own bind group, I guess. Was told by others that that's not a great idea though. For now I'll probably opt to cache WebGPUBindings (or equiv.) and update when something changes.

From talking with people it sounds like push descriptors aren't that well-liked as a concept by GPUs so it might be better to omit them. An ability to update descriptor heaps outside of a command buffer might be nice but it needs to be safe to ensure that nothing is in use. I don't know what our lifetime model is in WebGPU, considering a need to remote the whole thing.

Someone also suggested making a giant global view of texture descriptors and indexing them through a push constant to build something similar to bindless... but that's quite uncomfortable until VK_EXT_descriptor_indexing can arrive on the scene.

**Comment by Kangz** [comment]
Don't put each texture in its own BindGroup because WebGPU will only require support for 4 BindGroups in a PipelineLayout. You should know how many texture the pipeline needs upfront so can't you just create a BindGroupLayout with the right number of textures?
