### ISSUE TITLE
read-only image storage type declarations: examples inconsistent with grammar

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1056]
Thanks @ponitka for finding this.

The examples in https://gpuweb.github.io/gpuweb/wgsl.html#texture-ro use first template parameter 'type' of i32, u32, or f32. This is inconsistent with the grammar summary at https://gpuweb.github.io/gpuweb/wgsl.html#texture-types-grammar

These scalar types are redundant with the image format: they can and should be deduced from the image format template parameter, which comes immediately afterward.

**Comment by dneto0** [comment]
Confirmed this is still an issue.  I think this is "just a bug" and needs a PR.

**Comment by kvark** [comment]
Is this still an issue? I'd think that #1089 resolved this.

**Comment by dneto0** [comment]
I agree #1089 fixed this.
