### ISSUE TITLE
Number.MAX_VALUE is not valid WebIDL

### ISSUE THREAD

**Issue by darknoon** [gpuweb/gpuweb#106]
I was taking a look at (https://github.com/gpuweb/gpuweb/issues/87) and ran into the problem that
`Number.MAX_VALUE` is not valid WebIDL according to [the spec](https://www.w3.org/TR/WebIDL-1/#prod-float) , yet it is used in the `sketch.webidl` [here](https://github.com/gpuweb/gpuweb/blob/master/design/sketch.webidl#L192)

Not sure if there is a better solution, just wanted to flag this since it prevents running validation.

**Comment by magcius** [comment]
We should just be able to pick some unreasonably high limit for now like 100, since our LOD levels directly map to mip levels (these limits are post-bias I believe)
