### ISSUE TITLE
Determine the syntax for attributes

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1067]
The discussion started here:
https://github.com/gpuweb/gpuweb/pull/1046#issuecomment-689078111

**Comment by kainino0x** [comment]
jdashg:

> * `[[workgroup_size N N N]] [[foo bar]]` "LISPish"
> * `[[workgroup_size N N N, foo bar]]` "comma-delimited list"
> * `[[workgroup_size (N N N), foo bar]]` "paren-tuples"
>   
>   * Is `[[foo (bar)]]` valid?
> * `[[workgroup_size [N N N], foo bar]]` "square-bracket-tuples"
>   
>   * `[N,N,N]` feels like an array, but what if it were `[N, cw|ccw]`? Paren-tuples are more flexible, even if we don't have them elsewhere in the language yet.
>   * Also `[[workgroup_size [N N N]]]` is gross, even if we can manage to parse it.
> * `[[workgroup size(N N N), foo bar]]` "pseudo-function attribute values"

dneto0:

> On the "how to I write many attributes" front, early on we at Google decided that [[attr, attr2]] was better than [[attr]] [[attr2]]. It was less fussy and less typing.

johnkslang:

> I recommend reading through https://en.cppreference.com/w/cpp/language/attributes and fully understanding its power before spending time trying to invent new syntax that might not work as well. Especially where both space and parenthesis have their own meaning.
> 
> For HLSL, we discussed this and chose `[[vk::binding(3, 2)]]`, where the arguments are required binding followed by optional set.
> 
> Really seems worth following precedence here in C++, GLSL, HLSL, probably many others, and saving time as well.

kainino0x:

> `[[workgroup_size somesyntaxhere]] [[foo bar]]`
> `[[workgroup_size(x, y, z), foo(bar)]]`
> `@workgroup_size(x, y, z) @foo(bar)`
> I'm in favor of using the C++ style (or a similar style from another language) and making it work nicely for what we have already (e.g. `[[position]]` or `[[builtin::position]]`, but not `[[builtin(position)]]`).

**Comment by kvark** [comment]
`[[workgroup_size(x, y, z), foo(bar)]]` is my preference :)

**Comment by dj2** [comment]
`[[workgroup_size N N N, foo bar]] "comma-delimited list"` would be my preference.

**Comment by dj2** [comment]
Too many places referring to the same thing. I've changed to preferring the `[[workgroup_size(1, 2, 3), stage(compute)]]` format as well after seeing the `[[stage compute, workgroup_size 8 1 1]]` example in the entry point CL. I find the second harder to read.

**Comment by dneto0** [comment]
I'm fine with function-style syntax, taking the lead from C++.
Basically, I buy the [arguments](https://github.com/gpuweb/gpuweb/pull/1046#issuecomment-691184109) from @johnkslang.
E.g. it leaves an open path for namespaces.

**Comment by kainino0x** [comment]
Resolution: Use the C++ style. Allow both `[[attr(x, y), attr(z)]]` and `[[attr(x, y)]] [[attr(z)]]`. (No namespacing for now.)
