### ISSUE TITLE
Query API: Disallow resolve the unused queries or resolve them to 0?

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#1072]
```
encoder.WriteTimestamp(querySet, 0 /*queryIndex*/); 
encoder.WriteTimestamp(querySet, 2 /*queryIndex*/);
encoder.ResolveQuerySet(querySet, 0 /*firstQuery*/, 3 /*queryCount*/, destination, 0);
```

Vulkan spec says:
> If VK_QUERY_RESULT_WAIT_BIT is set, the implementation will wait for each query’s status to be in the available state before retrieving the numerical results for that query.
If the query does not become available in a finite amount of time (e.g. due to not issuing a query since the last reset), a VK_ERROR_DEVICE_LOST error may occur.

It requires that the queries between [**firstQuery**, **firstQuery** + **queryCount** - 1] must be available (written by query operations: begin/end query, write timestamp), otherwise the validation error is thrown when resolving queries. But  on D3D12 and Metal, the unused queries between [**firstQuery**, **firstQuery** + **queryCount** - 1] will be resolved to 0. 

> After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.

Vulkan also requires that each queries in query set must be reset (call **vkCmdResetQueryPool**) before each use and only can reset them outside the render pass.  So we need to record the used indexes in command encoder, render encoder, compute encoder when encoding commands, parse the recorded indexes to get the their intervals, then reset the queries in the intervals when creating command buffer and begin render/compute pass. 

So there is a workaround for Vulkan backend if we want to resolve unused queries to 0: 
When resolving the queries, call resolve commands based on each interval of the recorded indexes, first query is the first query index in each interval, query count is the number of the queries in each interval. For the left memory in destination buffer which not written values, write with 0.

We haven't decided whether to disallow resolve unused queries or follow D3D12/Metal behavior, so open it here for further discussion.

**Comment by Kangz** [comment]
@haoxli could you quote the relevant part of the specification?

**Comment by haoxli** [comment]
OK, I update it in the description.

**Comment by Kangz** [comment]
Thanks, I think either disallowing the resolve for unused queries, or making them default to 0 is fine. Disallowing to 0 is slightly better because it makes less error cases and is relatively simple for WebGPU implementations to do. What do others think?

**Comment by kvark** [comment]
Does the implementation have to track, which queries are active, and which aren't? I assume it does.
Next question: supposing we have some sort of begin/end for queries, (e.g. occlusion queries as investigated in #614), what would we want to do for the `resolve()` call that's in the middle of begin/end? I assume we want to treat this as an error.

In this case, it wouldn't make much sense to try to cover a few non-meaningful cases (e.g. when no timestamp was written, or no query begun) with the default 0, if there are cases, which we are going to be treating as errors anyway (e.g. when there was begin() but without an end()). We should just treat it as an error all the way then.

**Comment by kainino0x** [comment]
Only occlusion and pipeline statistics queries have begin/end, and those are inside a pass, so you can't resolve inside of it. The GPURenderPassDescriptor has .occlusionQuerySet so effectively a whole render pass can be seen as writing entries into a query set.

**Comment by haoxli** [comment]
Yes, we cannot resolve queries between begin and end operations, resolve must be called outside a pass, and also cannot resolve queries only written by begin or end.

**Comment by kvark** [comment]
Ok then, it sounds like the implementation can zero out unused queries with little effort then.

**Comment by haoxli** [comment]
Regardless of whether disallow resolve unused queries or resolve them to 0, it is necessary to track the status of the queries used in a encoder, because we also need to validate their status if disallow resolve unused queries. 

For resolve unused queries to 0, the extra effort is to calculate the intervals of queries used on each pass in order to call resolve method in each interval. For a large number of queries, if we only use a small part, I think this calculation will take some time, for example we create query set with the size of maximum value of uint32, but only write timestamp to the first query and last query, we also need to go through all the queries, although this is a corner case, it is allowed. 

Personally, I prefer to disable resolve unused queries to make the implementation simpler if there is no special usage.  If the users want to write timestamp discretely, they can resolve multiple times at intervals by themselves.

**Comment by kvark** [comment]
Do we have an investigation on what query pool sizes are supported on the native APIs?

**Comment by haoxli** [comment]
There is no clear limit on the query heap/pool sizes in D3D12 and Vulkan specifications, I test that they can create  the maximum size with UINT32_MAX/32  on my Intel HD Graphics 630 at least (Fail to create the size with UINT32_MAX/16). 

On Metal, we have two types buffers for query API: visibilityResultBuffer (MTLBuffer ) for occlusion query and MTLCounterSampleBuffer for pipeline statistic and timestamp queries.  The maximum size of visibilityResultBuffer  is 256KB.  For MTLCounterSampleBuffer, there is no limitation, but the maximum size of MTLBuffer is 256MB, I'm not sure if it's same with MTLBuffer.

**Comment by kvark** [comment]
It seems tempting to just have a limit for the maximum query pool size, which is 64K as the baseline (to fit the visibility buffer size restriction on Metal).

**Comment by kainino0x** [comment]
I think we should set a hard limit, but not expose it through GPULimits until there's evidence someone actually needs to be able to request a larger limit.

**Comment by kainino0x** [comment]
Resolution from today's meeting was to resolve unused queries to 0.

**Comment by haoxli** [comment]
Got  it. Thanks!
