### ISSUE TITLE
Should texture_sampled_2d_ms and texture_sampled_2d_ms_array be removed?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1075]
We added a `texture_multisampled_2d` to handle the multisample case but we still have both `texture_sampled_2d_ms` and `texture_sampled_2d_ms_array`. Should the sampled MS variants be removed so we just have `texture_multisampled_2d` to handle the multisample case?

**Comment by kvark** [comment]
yes, we should remove `texture_sampled_2d_ms` and `texture_sampled_2d_ms_array`. They are named as if they are just kinds of sampled textures, but you can't sample them, so this was confusing, and what the `texture_multisampled_2d` addressed.
