### ISSUE TITLE
Investigate remaining GLSL.std.450 methods for inclusion.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1087]
I wasn't able to find a direct translation either HLSL or MSL for the following set of methods from GLSL.std.450. We should decide if we want to include them as emulated in those languages.
```
RoundEven
Sign
Radians
Degrees
Asinh
Atanh
Acosh
MatrixInverse
ModfStruct
FrexpStruct
Refract
FindILsb
FindUMsb
FindSMsb
InterpolateAtCentroid
InterpolateAtSample
InterpolateAtOffset
```

I haven't looked to see if there is a translation for the following, they maybe easy inclusions, just have to look up if they translate to MSL and HLSL.
```
PackDouble2x32
PackHalf2x16
PackSnorm4x8
PackSnorm2x16
PackUnorm4x8
PackUnorm2x16
UnpackDouble2x32
UnpackHalf2x16
UnpackSnorm4x8
UnpackSnorm2x16
UnpackUnorm4x8
UnpackUnorm2x16
```

**Comment by johnkslang** [comment]
Not sure I understand.  HLSL has support for many of these.

If you are looking for HLSL mappings to SPIR-V operators, it's pretty easy to find such mappings in glslang, where the AST uses very similar names to SPIR-V.  E.g., from `hlslParseables.cpp`:

```
    symbolTable.relateToOperator("round",                       EOpRoundEven);
    symbolTable.relateToOperator("radians",                     EOpRadians);
    symbolTable.relateToOperator("degrees",                     EOpDegrees);
    symbolTable.relateToOperator("sign",                        EOpSign);
    symbolTable.relateToOperator("EvaluateAttributeAtCentroid", EOpInterpolateAtCentroid);
    symbolTable.relateToOperator("EvaluateAttributeAtSample",   EOpInterpolateAtSample);
    symbolTable.relateToOperator("EvaluateAttributeSnapped",    EOpEvaluateAttributeSnapped);
```

Many others might also have mappings, I just did a fast random sampling from your list.  I think it's true that the arc-hyperbolics are missing.

**Comment by dj2** [comment]
Yes, some of them exist in HLSL but not MSL and the other way around (MSL has the arc-hyperbolics for instance). I need them to exist in HLSL, MSL and SPIR-V. It's also possible for some I just missed if the name was sufficiently different

**Comment by dj2** [comment]
If they exist in one, they obviously wouldn't need to be polyfilled in that language.

**Comment by kvark** [comment]
`Refract` was requested by one of the users. We need a mini-investigation on how this would be mapped.

**Comment by jzm-intel** [comment]
> `Refract` was requested by one of the users. We need a mini-investigation on how this would be mapped.

It seems that the `Refract` in GLSL.std.450 can be directly mapped into HLSL and MSL.

| Shader<br>Language |      Function definition      | Description                                                                                                                                                                                                                                                                                                                                                                  | Documentation                                                                                                                                                                                                                    |
|:------------------:|:-----------------------------:|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        GLSL        |      `Refract(I, N, eta)`     | The input parameters for the incident vector `I` and the surface normal `N` must already be normalized to get the desired results. The type of `I` and `N` must be a scalar or vector with a floating-point component type. The type of `eta` must be a 16-bit or 32-bit floating-point scalar. Result Type, the type of `I`, and the type of `N` must all be the same type. | [GLSL.std.450 extended instruction set](https://www.khronos.org/registry/spir-v/specs/1.0/GLSL.std.450.html)                                                                                                                     |
|        HLSL        |     `ret refract(i, n, ?)`    | Ray direction vector `i` and surface normal vector `n` are float vector of any size, and refraction index scalar `?` is a float scalar.<br>Return value is a floating-point, refraction vector. If the angle between the entering ray `i` and the surface normal `n` is too great for a given refraction index `?`, the return value is (0,0,0).                             | [https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-refract](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-refract)                                                     |
|         MSL        | `T refract(T I, T N, Ts eta)` | For the incident vector `I` and surface normal `N`, and the ratio of indices of refraction `eta`, return the refraction vector. <br>The input parameters for the incident vector `I` and the surface normal `N` must already be normalized to get the desired results.                                                                                                       | [https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) Table 6.10. Geometric functions in the Metal standard library, Page 151 |

**Comment by dneto0** [comment]
Already supported:
* pack/unpack builtins were added in #1196
* RoundEven -> round
* Sign -> sign
* Refract -> refract
* ModfStruct -> modf
* FrexpStruct -> frexp

Remaining
* Asinh, Atanh, Acosh. See #1622
* FindILsb, FindUMsb, FindSMsb.  See #2130
* MatrixInverse
* InterpolateAtCentroid
* InterpolateAtSample
* InterpolateAtOffset

**Comment by kdashg** [comment]
MatrixInverse: https://github.com/gpuweb/gpuweb/issues/2580
