### ISSUE TITLE
define the term "statically reachable" 

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1091]
Define the term "statically reachable" in one place, and use it where needed.

This is from feedback:
https://github.com/gpuweb/gpuweb/pull/1046#discussion_r489512391

**Comment by dneto0** [comment]
PR #1133 has proposed text for when a _variable_ is "statically accessed".   So far that is the only usage I need.  The draft spec already has "functions in a shader stage" which has ad hoc text for a function that is  in the static call graph (but not using that phrasing).

**Comment by Kangz** [comment]
Closing. This is well specced now.
