### ISSUE TITLE
Better specified context events

### ISSUE THREAD

**Issue by dmikis** [gpuweb/gpuweb#11]
WebGL has events for loss and restoration of a context and creation failure error. However, there's a problem with them: sometimes they're not very helpful.

For instance, `webglcontextlost` event. Since it doesn't give the reason why we've lost the context, it's not clear what to do: show our user an error message or wait for restore event. I actually tried to log `statusMessage` property of event objects and it was empty.

It'd be good to have better specified context events.

**Comment by kainino0x** [comment]
Assigning myself since I did the error handling doc.

I agree that we should do this. Maybe we can split the context-lost into context-lost-recoverable and context-lost-unrecoverable or something.
