### ISSUE TITLE
[wgsl] Allow identity conversion of vectors.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1103]
Currently we allow saying `f32(1.f)` and `b = f32(1.f); a = f32(b)`. This maps to `OpCopyObject` in SPIR-V. The spec currently does not allow `vec2<f32>(vec2<f32>(1., 2.))` or the `a = vec3<f32>(1., 2., 3.); b = vec2<f32>(a.xx)` conversions.

These should be added and map to OpCopyObject in function scope and just returning the inner ID at module scope in SPIR-V.

Edited to fix OpCopyObject and fix floats

**Comment by dneto0** [comment]
I think inside a function it's OpCopyObject (typo in the description above?)

**Comment by dneto0** [comment]
Also the second example should have floating point constants to construct 'a'.

**Comment by litherum** [comment]
Discussed on 2020-10-13 https://docs.google.com/document/d/16vNf_rmJ566SoI-iOGGr-UqTGZ32SHKW2_qizoB4HxU/edit#heading=h.adg7rbull6x8

Resolved to accept this
