### ISSUE TITLE
Which storage classes do we need?

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1105]
Spawned from https://github.com/gpuweb/gpuweb/pull/1093#discussion_r493058749

I understand that this might be related to the memory model, the section for which is currently TODO in WGSL.
I find the distinction between "uniform", "uniform-constant", "storage-buffer", and "texture" unclear.

**Comment by dj2** [comment]
What's the alternative? I assume you aren't talking about `input` or `output` just the 4 you mentioned. I think `uniform-constant` could go away and just become part of `uniform` where the `type` is a `sampler` or `texture`. I'm not sure how `texture` relates to things?

@dneto0

**Comment by kvark** [comment]
>  I'm not sure how texture relates to things?

It is "image" in SPIR-V, and "texture" in #1093 

> What's the alternative? I assume you aren't talking about input or output

Right, "input" and "output" make perfect intuitive sense. "private" and "workgroup" also make sense. Finally, there's got to be at least one for uniform and storage things. So I suppose the question here is about these in particular, not all the storage classes.

**Comment by dneto0** [comment]
I'll describe how it works in SPIR-V/Vulkan.

- Image storage class
    - This is for pointers into texture storage, for storage buffers.   But this is only used for image atomics. The code sequence is:   Use OpImageTexelPointer to map an (image,coordinate,possibly sample) into a pointer-to-image. Then that is fed into an OpAtomic* instruction.   E.g. the description in OpImageTexelPointer says "Use of such a pointer is limited to atomic operations."
    - We've learned that WebGPU/WGSL won't be supporting image atomics (See https://github.com/gpuweb/gpuweb/issues/728#issuecomment-696896462 )
    - So **WGSL should not have a texture or image storage class**.  I'll update the PR to remove it.

- Uniform - used for UBOs
      - readonly data
      - (block-decorated) struct type
      - specific layout constraints, more strict than for SSBOs
             - (Basically, std140; has evolved with extensions to be more relaxed, but those are not widely supported.)
      - each variable is visible / shared among all invocations in the shader stage

- StorageBuffer - used for SSBOs
     - read-write data
     - (block-decorated) struct type
              - the last member may be a runtime-sized array;  this is the only place where one of these can be used.
      -specific layout constraints
              - (Basically, std430, but has evolved with extensions to be more relaxed)
     - each variable is visible / shared among all invocations in the shader stage.
     - normally, one variable maps to one resource descriptor(binding) 
               - arrays of storage buffers are supported, one element per binding.

- UniformConstant
     -  this stores opaque handles to images, samplers, raytracing acceleration structures.  
            - the handles are immutable, but the data they point to might not be (e.g. for storage image)
      - each variable is visible / shared among all invocations in the shader stage
     - normally, one variable maps to one resource descriptor(binding)
            - arrays of images are supported, where each element occupies a binding

- PushConstant - not used by WGSL

**Comment by dneto0** [comment]
One more thing:
  - In the above I described the more modern and recommended way of modeling SSBOs.  Vulkan 1.0 and SPIR-V 1.0 had a different way, which is still supported but not recommended.  That is: an SSBO could be a variable in  Uniform storage class where the struct was decorated with BufferBlock.   This is still supported, so you'll see both ways documented in SPIR-V and Vulkan.


Ok, that said, I think it's useful to have the distinction between the three of Uniform, StorageBuffer, UniformConstant. They differ as follows:
   - whether the data is read/write
   - whether the stored objects are opaque, or whether you can form pointers into the interior of those objects
   - when you can form a pointer, the layout rules that apply when you can form those interior pointers
   -  I didn't cover it above, but in the Vulkan memory model, synchronization-related operations need to be annotated as to whether (colloquially) they flush or invalidate caches based on storage class.   Image memory and storage-buffer memory are distinct for this.
  - also not covered above:  limitations on passing pointers to those storage classes into functions.  (You can for UniformConstant, and without extensions, cannot for StorageBuffer or Uniform)
   - UBOs might have smaller upper bound sizes, vs. SSBO

Now, the names that SPIR-V uses are not great, IMHO.  I could be convinced to go with:
   - `handle` for UniformConstant
   - `buffer` for StorageBuffer
   - ` buffer_ro` for Uniform, to capture the read-only-ness of it, as that's the most important thing about it

**Comment by kvark** [comment]
Thank you @dneto0 for describing this! That's the best info I could hoped for :heart: 
What I'm thinking is - which of them do we really need?

Let's look at samplers to start. What value does it bring to have `var<UniformConstant> sampler: Sampler`? isn't `UniformConstant` totally redundant in this case? We don't have any pointers to samplers either, so nowhere else it would be needed, it seems (in the context of samplers).

Next, textures. We have separate types for storage vs non-storage textures. What extra value does putting `UniformConstant` bring to the table?

Finally, buffers. These are most unclear today. We haven't decided if the read-only/read-write qualifiers need to be on the global variables, or on the types themselves (like for textures) - #1120 . I think it would make sense to have the user be explicit about "ro" versus "rw" when working with storage buffers. In this case, no qualifiers = uniform, "read_only" = read-only storage, and "read_write" means read-write storage. So even for buffers it seems that we don't need the storage classes at *declaration* point. I suppose we still need them for the pointers, right?

**Comment by dneto0** [comment]
Right. Strictly speaking the sampler type and texture type completely determine the (UniformConstant) storage class.
So adding the storage class on the variable declaration is redundant.  
But so far we've decided to be very explicit about the storage classes for module-scope variables.

The value will still "exist" in a storage location. 
Many uses won't see or care about that. But it is possible to pass a reference to an image or a sampler down into a helper function.
(In SPIR-V, see the [universal validation rules](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_universal_validation_rules), where it says that a logical pointer to the UniformConstant storage class can be an operand to a function call.)

I'd like to model that as, for example:

         # module scope declaration
         var<handle> im : texture_ro<r32float> ;  # Using "handle" here as nicer than UniformConstant

        fn helper( img_ref : ptr<handle,texture_ro<r32float>> ) -> f32 {
                 return textureLoad<f32>(img_ref, 0).x;  # pointer to image is dereferenced implicitly.         
        }
    
Keeping things expressed in explicit storage classes lets me later describe the shader interface in terms of storage classes.
E.g. in this [gist for a later WIP PR](https://gistpreview.github.io/?78f0b4762fa0a69feb72e6f07ec1524f#shader-interface):

> More precisely, the interface of a shader stage is the set of module-scope variables statically accessed by functions in the shader stage, and which are in storage classes in, out, uniform, storage_buffer, or uniform_constant.

**Comment by kvark** [comment]
> fn helper( img_ref : ptr<handle,texture_ro<r32float>> ) -> f32 {

I recall when we discussed https://github.com/gpuweb/gpuweb/issues/889#issuecomment-654370178 it was concluded that we aren't going to pass textures by value/pointer anywhere, hence declaring them as arguments to an entry point function was not considered.

Also, if you want to do that, what does `handle` do there? Seeing `ptr<texture_ro<r32float>>` would be unambiguous as well.

Notably, if we *do* end up keeping these classes, `handle` sounds cleaner than "UniformConstant" :)

**Comment by dneto0** [comment]
Today we have the various texture types, and a sampler type.
I fully expect we'll be adding read-write textures.
Eventually we'll probably have acceleration structures.

Each of these things shares key properties about how to refer to these objects.  It's good to have a name for the category, as it streamlines the spec but more importantly streamlines the developer's thinking about them.   That's why I want to keep a "handle" storage class.

**Comment by dneto0** [comment]
Discussed in the [2020-10-06](https://docs.google.com/document/d/11Uzxv2djFw1HVSTT6UtOBatW9J8cyoz_GDKtKFVUnJg/edit#heading=h.viw9ska7isa4) meeting

The direction is:
- the storage class annotation for declarations of textures and samplers (handle-like things) are redundant; the redundancy is a cost that doesn't help much (or enough).  So remove it.
- the storage class annotation for UBO and SSBO is still useful.  The group is open to renaming them;  the UBO storage class has traditionally bad names.

**Comment by kvark** [comment]
I think this is mostly resolved. We don't need the "handle", and we can remove "in"/"out" as in #1437
