### ISSUE TITLE
MSL only supports 1-dimensional storage textures

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1108]
I assume the read-only and write-only storage textures in WGSL (e.g. texture_ro_1d, ... texture_wo_3d) are supposed to map to MSL "Texture buffers", from section 2.8.1

However, MSL texture buffers are only 1-dimensional.

I presume that means we have to remove:

* texture_ro_1d_array
* texture_ro_2d
* texture_ro_2d_array
* texture_ro_3d
* texture_wo_1d_array
* texture_wo_2d
* texture_wo_2d_array
* texture_wo_3d

**Comment by kvark** [comment]
No, our storage textures have nothing to do with "texture buffers". You are thinking about #162
Storage textures are just regular MSL textures with appropriate access, e.g. `texture2d<float,access::write>`.
