### ISSUE TITLE
what does ...snorm mean, exactly

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1114]
I'm filing this as a detail to be followed up when describing texel channel formats.

Certain image formats use signed-int-normalized formats, e.g. rgba8snorm, which is 4 channels of 8 bit snorm values.  Each 8bit snorm value is *first* assumed to be in twos-complement format, then normalized to -1.0 to 1.0.  In the first step we have values -128 to 127 inclusive.  In the second step, the platform APIs have gaps or inconsistencies in their documentation.

D3D*
====

D3D*.  From [this link](https://docs.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format#format-modifiers):

> Signed normalized integer; which is interpreted in a resource as a signed integer, and is interpreted in a shader as a signed normalized floating-point value in the range [-1, 1]. For an 2's complement number, the maximum value is 1.0f (a 5-bit value 01111 maps to 1.0f), and the minimum value is -1.0f (a 5-bit value 10000 maps to -1.0f). In addition, the second-minimum number maps to -1.0f (a 5-bit value 10001 maps to -1.0f). The resulting integer representations are evenly spaced floating-point values in the range (-1.0f...0.0f), and also a complementary set of representations for numbers in the range (0.0f...1.0f).

So, with a tiny bit of filling in the blanks, if  *raw* is the signed 8-bit in, then the normalized value is     max(-1.0,  *raw* / 127.0)

Vulkan
=====

Vulkan is almost the same. From [this link](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#fundamentals-fixedfpconv)

> Signed normalized fixed-point integers represent numbers in the range [-1,1]. The conversion from a signed normalized fixed-point value c to the corresponding floating-point value f is performed using

> f = max( c / (2**(b-1) - 1), -1.0)

Confusingly, it then says 

> For example, if b = 8, then the integer value -127 corresponds to -1.0 and the value 127 corresponds to 1.0. Note that while zero is exactly expressible in this representation, one value (-128 in the example) is outside the representable range, and **must** be clamped before use.

I'm following up to make sure that *must* is an obligation of the implementation, and that -128 (in this case) is certain to map to -1.

Metal
====

Metal is the least prescriptive about the conversion.  The best I could find is at https://developer.apple.com/documentation/metal/mtlpixelformat : 

> For normalized signed integer formats (Snorm), component values in the range [-1.0, 1.0] are stored as [MIN_INT, MAX_INT], where MIN_INT is the greatest negative integer and MAX_INT is the greatest positive integer that can be stored, given the bit size of the component. For normalized unsigned integer formats (Unorm), component values in the range [0.0, 1.0] are stored as [0, MAX_UINT], where MAX_UINT is the greatest unsigned integer that can be stored, given the bit size of the component.

That doesn't describe the actual conversion, and certainly doesn't capture the symmetry around 0.

**Comment by magcius** [comment]
The Direct3D SDK used to ship this file, D3DX_DXGIFormatConvert.inl, which was maintained by Microsoft and had spec-accurate versions of all conversion procedures. It contains conversion both to and from SNORM formats, including the details of rounding behavior.

https://github.com/apitrace/dxsdk/blob/master/Include/d3dx_dxgiformatconvert.inl

**Comment by Kangz** [comment]
I improved [Dawn's Snorm tests a bit](https://dawn-review.googlesource.com/c/dawn/+/29060) and they pass on all backends on multiple GPUs each:
```cpp
// These encodings (T is int8_t, int16_t, int32_t)
std::vector<T> encoding = {0, 1, -1, maxValue, minValue, T(minValue + 1), 0, 0};
// Give these float values when sampled
std::vector<float> sampledValue = {0.0f, 1.0f / maxValue, -1.0f / maxValue, 1.0f, -1.0f, -1.0f, 0.0f, 0.0f};
```

So it seems that `f = max( c / (2**(b-1) - 1), -1.0)` is correct and portable.

**Comment by dneto0** [comment]
I filed a documentation bugs:

- to Apple.  https://feedbackassistant.apple.com/feedback/8754026   I don't know if others can see this.
- to Vulkan, to clarify the "must" statement:  https://gitlab.khronos.org/vulkan/vulkan/-/issues/2367 (internal link)

**Comment by Kangz** [comment]
Can we close this? `rgba8snorm` is specced in the WGSL spec now.
