### ISSUE TITLE
what is the initial value of a workgroup variable?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1137]
What should the WGSL spec say about the initial value of workgroup variables?

Workgroup variables must not have an initializer.

But to avoid leaking data across shader invocations, the implementation must clear out workgroup storage before the shader begins (and probably after too).

Should we guarantee that the value is the zero value? That is portable.
The type must be _storable_, so there's always a well-defined zero for the store type.

-----
Edited:  workgroup variables must *not* have an initializer in Vulkan land.

**Comment by dj2** [comment]
I'm not sure I understand how this leaks? Each shader needs to initialize that value in the constructor, how would you ever read it out?

Would this mean we have to inject a postamble into each shader that sets each workgroup variable to some value?

**Comment by kainino0x** [comment]
> it's another opportunity to take advantage of a `GPUComputePass` and say it's only initialized at the start of the pass

How would this benefit implementations? I don't think the APIs give us any way to fully clear all workgroup memory registers on the chip so we'd have to do it for each dispatch (or MAYBE each pipeline change) anyway, since each dispatch could use different workgroup memory registers than the last.

**Comment by kvark** [comment]
@kainino0x yeah, I stand corrected. I suppose Vulkan and friends can't guarantee any state of those registers even between two dispatches...

**Comment by dneto0** [comment]
I'm very sorry, I missed a "NOT"

In Vulkan a Workgroup variable must *NOT* have an initializer. (otherwise the issue doesn't make sense)

**Comment by dneto0** [comment]
Discussed in virtual F2F [2020-10-23](https://docs.google.com/document/d/1p1jREMgonZszFJ8eastnnDb36rKKm7xnDYnMjC6zj5c/edit#)

* Agreed to initialize to 0.
* Reviewed ANGLE and WebGL history that zeroing quickly was nontrivial
* Discussed 0 can be an easier fast path because the bit representation is the same across types.
* Discussed that eventually it would be nice to allow a const-expr value other than 0. But not in MVP.
