### ISSUE TITLE
Restrictions on function parameters

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1139]
What are the restrictions on function parameters?

We can have different rules between builtin functions and user-written functions.

Regarding pointer arguments:

In SPIR-V for Vulkan, a pointer operand to a function must be into one of the following storage classes:  UniformConstant, Function, Private, Workgroup.  So no UBO or SSBO pointers are allowed.

In [recent discussion](https://github.com/gpuweb/gpuweb/issues/1105#issuecomment-703933268) @kvark recalled that we had already decided to disallow passing textures and samplers as function parameters (and also pointers-to-these-things).

GLSL allows opaque types to be "in" parameters to functions.  However, I've found some concerning behaviour (a.k.a. a bug?) for passing a formatted write-only storage image into a user-defined helper function.  See https://github.com/KhronosGroup/glslang/issues/2415 
I want to avoid any workaround that requires inlining the called function.

So I would much prefer for WGSL to disallow textures and samplers (or pointers to them) to be passed into user-defined functions.

**Comment by johnkslang** [comment]
The write-only image-without-format thing is like .01% of what is important for passing textures/samplers to user functions, so that one corner case should probably not be deciding what to do for the rest of the 99.99% of this space.

Are you really suggesting users cannot write a function to operate on a texture/image/sampler chosen at a call site?  That's quite a step backward in functionality that's existed since 2003 in GLSL.  Maybe I'm not understanding.

**Comment by dneto0** [comment]
FYI @johnkslang pointed me at https://github.com/KhronosGroup/GLSL/issues/57 which covers this formatted-vs-unformated issue pretty thoroughly from the GLSL spec perspective.

> Are you really suggesting users cannot write a function to operate on a texture/image/sampler chosen at a call site? That's quite a step backward in functionality that's existed since 2003 in GLSL. Maybe I'm not understanding.

That would be the conservative choice. I'm not claiming that's a great solution.

Working through this some more, in a slightly different context:  SPIR-V for Vulkan *does* permit pointer-to-texture/sampler to be passed into helper functions.  In this case the format (including Unknown) is part of the parameter type.  If the driver supports it well, then we're done. If not, then the browser can modify the SPIR-V to inline the offending functions as needed.

Now, in past we've had a principle of not requiring inlining for shader translations from WGSL to underlying platform shader languages. So this path comes close to that line: the inlining is only required if the driver has a bug, essentially.

**Comment by dneto0** [comment]
Stepping back a little bit:

- I have assumed so far that the formal parameter type must be the same as the formal argument type (modulo WGSL type aliasing).  That is, no implicit conversions are performed at function call boundary.
- Also, I assume that for storage textures, the storage texture type is parameterized by the texel format.  (E.g. when you have a different texel format, then you have a different type.)  (This is the case for SPIR-V, but not the case for GLSL.)

That said, for SPIR-V and Vulkan, for pointer arguments:
- a pointer-to-storage-texture is ok as a function parameter, as argued above.
- a pointer-to-sampled-texture is ok as a function parameter:   Sampled images types in SPIR-V are not parameterized by a texel format. They are parameterized by the sampled type, one of f32, i32, or u32.  And as JohnK said this is functionality that has long support
- assuming base functionality, we *don't* have VariablePointers or VariablePointerStorageBuffer capability, and so all pointers are "logical pointers", and from [universal validation rules](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_universal_validation_rules) we have:
    - a pointer operand to a function call must be in one of the UniformConstant (handle), Function, Private, Workgroup storage classes.  (AtomicCounter doesn't exist in Vulkan; it's for OpenGL)   Note this means no function parameters that are pointers to UBO or SSBO. (Note!) 
    - a pointer operand to a function call must be either:
            - a "memory object declaration", i.e. the pointer for the base of a variable, or a function parameter that itself is a pointer value.
            - or the pointer to an element of an array of textures or samplers, where the base pointer of the array itself is a memory object declaration.  WGSL doesn't yet have arrays of textures or samplers, but I expect this will come in the future.

**Comment by grorg** [comment]
Discussed at the [2020-10-19 Virtual F2F](https://docs.google.com/document/d/1NejOIbytIBVw_fgMmGdX6ZL7Owz_X72xzZf9nZ-0aaE/)

**Comment by grorg** [comment]
Current resolution is to allow texture parameters to functions via `ptr<>`, assuming that Microsoft is ok with it (i.e. is it supported in HLSL?). @pow2clk

**Comment by kvark** [comment]
I don't think `ptr<>` is either helpful or necessary there, fwiw. I believe @litherum expressed a similar concern.

**Comment by dneto0** [comment]
Discussion, and resolution so far.
- SPIR-V / Vulkan allows pointer-to-texture and pointer-to-sampler as function arguments.   Other storage classes don't have that freedom (e.g. pointer to SSBO and pointer to UBO are not permitted as function parameters.)
- Don't know if HLSL permits this. Need Microsoft's input.
- Discussion about what the texture+sampler parameters look like.  In SPIR-V the parameter is pointer-to-  and the load is done at the point of use in the texture builtin /  instruction.
- Keep the decision that texture/sampler resources are declared at module scope.

**Comment by pow2clk** [comment]
Textures and samplers can be passed into user functions. A very common way to enable old-style HLSL code that uses `Tex2D` is to define a user function for it: 

```hlsl
float4 Tex2D(Texture2D<float4> t,
  SamplerState s, float2 c) {
  return t.Sample(s, c);
}
```

I don't know what the ptr<> business is for. Do you want to be able to modify the texture or sampler by reference?

**Comment by grorg** [comment]
Discussed at the [2020-11-10 meeting](https://docs.google.com/document/d/1QFWUKpCcoLCMGHfJQWJurSPk-9PDcJ1Gc51FSg3_Fr8/).

**Comment by dneto0** [comment]
I'll take this to make a concrete proposal.

**Comment by dneto0** [comment]
The MSL manual section "5.2 Function Arguments and Variables" lists what can be a function argument.
That will constrain what we can do in WGSL.

**Comment by dneto0** [comment]
SPIR-V 2.16.1 Universal Validation Rules say that, if we don't have a variablepointers capability, then for logical pointer types (which is all we'll have right now in WGSL):

>  Any pointer operand to an OpFunctionCall must be

> * a memory object declaration, or

> * a pointer to an element in an array that is a memory object declaration, where the element type is OpTypeSampler or OpTypeImage.

A [memory object declaration](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#MemoryObjectDeclaration) is either an OpVariable, or an OpFunctionParameter of pointer type (or other cases for physical storage buffer extension).

So by applying induction (ok, just think about tracing), a pointer argument must ultimately refer to the storage for a whole variable.

**Comment by jdashg** [comment]
@dneto0 Is there more to be done here post-#1674?

**Comment by dneto0** [comment]
this is all done.  Closing.
