### ISSUE TITLE
T2B/B2T copies should require whole-subresource copies for depth/stencil

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1140]
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-copytextureregion

> Note that for a depth-stencil buffer, the depth and stencil planes are separate subresources within the buffer.
> 
> To copy an entire resource, rather than just a region of a subresource, we recommend to use CopyResource instead.
> 
> Note  If you use CopyTextureRegion with a depth-stencil buffer or a multisampled resource, you must copy the entire subresource rectangle.

I thought we had this validation in our spec but I can't find it.

**Comment by Kangz** [comment]
We have it in the [validation of `copyTextureToTexture`](https://gpuweb.github.io/gpuweb/#dom-gpucommandencoder-copytexturetotexture)

> If source.texture.[[format]] is a depth-stencil format:
> - The copy with source, destination and copySize is a copy of the whole subresource.

We should put it in a place common with `copyTextureToBuffer` and `copyBufferToTexture`.

**Comment by kainino0x** [comment]
We can probably move the validation for sampleCount=1 into a common place as well.

**Comment by kainino0x** [comment]
This is covered by https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuimagecopytexture

> The imageCopyTexture subresource size of imageCopyTexture is equal to copySize if either of the following conditions is true:
> - imageCopyTexture.texture.[[format]] is a depth-stencil format.
> - imageCopyTexture.texture.[[sampleCount]] is greater than 1.
