### ISSUE TITLE
Questions: WGSL JSON, When can I start learning WGSL?, WAT Fluff

### ISSUE THREAD

**Issue by KooIaIa** [gpuweb/gpuweb#1148]
1. Will WGSL logically and efficiently be able to be represented as JSON? Is SPIR-V like this?

2. When would be a good time to start learning the language? I want to start early because it will have less to learn, but not too early if things will change. Would I want to get started?

3. Is WGSL spiritually similar to what WAT is to WASM? I have major respect for WebAssembly Text. WAT is S-Expressions. What is WGSL? JSON?

Thanks!

**Comment by kvark** [comment]
Check the boids example in Tint repository to get a sense of it - https://dawn.googlesource.com/tint/+/refs/heads/main/test/compute_boids.wgsl
WIP specification is in https://gpuweb.github.io/gpuweb/wgsl.html

Unofficial Matrix chat where it's easier to ask questions - "#WebGPU:matrix.org"
