### ISSUE TITLE
CopyImageBitmapToTexture: Texture usage of the dest texture may prevent blit using internal shaders.

### ISSUE THREAD

**Issue by shaoboyan** [gpuweb/gpuweb#1150]
One of the optimization for CopyImageBitmapToTexture is using internal pipelines to do the blit to handle the case which cannot do direct T2T copy.  

For example, if the source imageBitmap has different texture format from dest texture, instead of download the content to CPU , do some changes and do B2T copy, we can use a internal pipeline to handle it to make the data stays in GPU. 

With the help of internal pipeline, the GPU uploading path will be hit in great chance.

But in the case user provides the dest texture without usage outputAttachment (e.g. only have CopyDst | sAMPLED usage), the internal pipeline is hard to help.

The rough idea to solve it could be:
- Either we create a intermediate texture with correct texture usage and use internal pipeline to do blit. And then copy the content from intermediate texture to the dest texture. (Suffer an extra copy)
- Or, we suggest the developer provide the dest texture with flags outputAttachment. (A weired request)

Both solutions seems not ideal, do you have any suggestions on this issue?

**Comment by kainino0x** [comment]
If I understand the problem correctly, we wouldn't know until we have the actual ImageBitmap object which copy path we're going to use. So an `IMAGE_COPY_DST` usage would probably internally add both `OUTPUT_ATTACHMENT` and `COPY_DST`.

This seems like a good possible solution to me. WDYT @shaoboyan?

**Comment by shaoboyan** [comment]
@kvark @kainino0x  Your understanding is correct and IMAGE_COPY_DST seems a good solution for now. So + 1 from me.

**Comment by Kangz** [comment]
Uh, adding `OUTPUT_ATTACHMENT` can be expensive (compared to `COPY_SRC` which is almost always free). Maybe #1154 solves this in another way?

**Comment by Kangz** [comment]
This has been resolved by requiring `RENDER_ATTACHMENT`
