### ISSUE TITLE
Reconsider the name `OUTPUT_ATTACHMENT`

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1153]
`OUTPUT_ATTACHMENT` was an [artefact](https://github.com/gpuweb/gpuweb/pull/47/files#diff-ece944f08dce92dd3a48997d25047499b58b170cdece995ba073f8607a9747a0R64) of the initial import+rewrite of NXT's interface because NXT tried to have Vulkan-like render passes with sub-passes. It doesn't seem like WebGPU will have `INPUT_ATTACHMENT` in the near future, so maybe `OUTPUT_ATTACHMENT` should be renamed to `RENDER_TARGET` or an other name open to bikeshedding?

**Comment by kvark** [comment]
I think `RENDER_TARGET` is cleaner. It does however has a downside that generally people assume "color" targets. `OUTPUT_ATTACHMENT` doesn't have this problem, and it matches with the current names of other structs, such as `GPURenderPassColorAttachmentDescriptor`.

**Comment by Kangz** [comment]
That's a good point, maybe it could be `RENDER_ATTACHMENT`?

**Comment by kainino0x** [comment]
Resolution: "Resounding silent agreement"

**Comment by kvark** [comment]
Fixed by #1168
