### ISSUE TITLE
Remove return requirement

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1156]
Currently return is always required in a function, even if it returns `void`. This comes from the original conversion from SPIR-V which requires a terminator at the end of  every block.

This becomes quite frustrating when writing WGSL as it's sufficiently different from other programming languages.

Propose we remove this restriction in the case a function returns `void` and make the final `return` optional.

**Comment by jdashg** [comment]
Optional is ok by me.

**Comment by litherum** [comment]
+1
