### ISSUE TITLE
Migrate CI to github actions?

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1166]
Travis seems to be really slow lately...

**Comment by kainino0x** [comment]
+1. @beaufortfrancois @pjoe just in case either of you would be interested in helping out with this :)

**Comment by dj2** [comment]
Related to #563 as we'd like to get auto-rendering setup for WGSL but the current system only allows a single spec to be rendered.

**Comment by pjoe** [comment]
Sounds like a good challenge, have been working with GH actions on a number of other projects (and at day job), so have some experience by now :)

**Comment by kvark** [comment]
Fixed by #1170
