### ISSUE TITLE
WGSL: function parameters act like const declarations, not var declarations

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1171]
Example:
```
fn f(a: f32) -> f32 {
    // This should treat 'a' as if it were a const declaration, where its value is taken to be the argument value provided
    // at runtime by the caller.
    // In particular, you assign to 'a'.
  var b : f32 = a;  //  this is fine
  a = 12.0;  /// this should be invalid.
  return a;
}
```

One reason this is required is that we need to support formal arguments that are pointers.  But  a pointer is not _storable_, and so it can't go into a 'var'.   But a const can hold a pointer value.

**Comment by kvark** [comment]
Just wanted to note that his is contrary to how arguments work in most languages.
But I like it! Following this route would get us closer to passing pipeline inputs in arguments to entry point functions.

**Comment by kainino0x** [comment]
Agree this is contrary to most languages, but I also think it's a mistake that most languages don't at least allow you to make arguments const if you want to. I like this direction.

**Comment by grorg** [comment]
Discussed at the [2020-11-10 meeting](https://docs.google.com/document/d/1QFWUKpCcoLCMGHfJQWJurSPk-9PDcJ1Gc51FSg3_Fr8/).

Resolved: Accepted.

**Comment by dneto0** [comment]
This was already fixed by 
* #1516:  defines formal parameter as a name for a value (of the type specified)
* #1651:  describes function call behaviour, matching argument values to formal parameters
