### ISSUE TITLE
Investigation: Stencil Test

### ISSUE THREAD

**Issue by Richard-Yunchao** [gpuweb/gpuweb#118]
# Introduction
Stencil test is a stage in render pass after fragment shading. It can affect whether and how the pixels will be written into render target. The basic logic is that:
```cpp
if(compareOp(StencilRef & StencilReadMask, Value & StencilReadMask ))
    accept pixel and do stencilPassOp, considering StencilWriteMask
else 
    reject pixel and do stencilFailOp, considering StencilWriteMask
```
Stencil test is supported by Metal, D3D12 and Vulkan. It has already been added in WebGPU idl, but with a few features left. This document attempts to describe stencil test among these three native graphics API sets, in order to discuss missing features. 

# Native APIs
## Vulkan
Vulkan can set almost every feature including `depthFailOp`, `stencilFailOp`, `passOp`, `compare`, `stencilReadMask`(compareMask), `stencilWriteMask` and `reference` for front face and back face separately for stencil test via [VkStencilOpState](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#VkStencilOpState).
```cpp
typedef struct VkStencilOpState {
    VkStencilOp    failOp;
    VkStencilOp    passOp;
    VkStencilOp    depthFailOp;
    VkCompareOp    compareOp;
    uint32_t       compareMask;
    uint32_t       writeMask;
    uint32_t       reference;
} VkStencilOpState;
```

The only one exception is `stencilTestEnable`, which is used for both front and back faces. `stencilTestEnable` is in [VkPipelineDepthStencilStateCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#VkPipelineDepthStencilStateCreateInfo), together with two instances of `VkStencilOpState` for front and back faces separately for stencil test. 
```cpp
typedef struct VkPipelineDepthStencilStateCreateInfo {
    ...   
    VkBool32                                  stencilTestEnable;
    VkStencilOpState                          front;
    VkStencilOpState                          back;
     ...
} VkPipelineDepthStencilStateCreateInfo; 
```

In addition, Vulkan can set stencil read mask (compare mask), write mask and reference value for front and back faces separately via `vkCmdSetStencilCompareMask`, `vkCmdSetStencilWriteMask`, `vkCmdSetStencilReference` as follows:
[vkCmdSetStencilCompareMask](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#vkCmdSetStencilCompareMask)
```cpp
void vkCmdSetStencilCompareMask(
    VkCommandBuffer                             commandBuffer,
    VkStencilFaceFlags                          faceMask,
    uint32_t                                    compareMask);
```
[vkCmdSetStencilWriteMask](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#vkCmdSetStencilWriteMask)
```cpp
void vkCmdSetStencilWriteMask(
    VkCommandBuffer                             commandBuffer,
    VkStencilFaceFlags                          faceMask,
    uint32_t                                    writeMask);
```
[vkCmdSetStencilReference](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#vkCmdSetStencilReference)
```cpp
void vkCmdSetStencilReference(
    VkCommandBuffer                             commandBuffer,
    VkStencilFaceFlags                          faceMask,
    uint32_t                                    reference);
```

## D3D12
D3D12 can set `depthFailOp`, `stencilFailOp`, `passOp` and `compare` for front and back faces separately via [D3D12_DEPTH_STENCILOP_DESC](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_depth_stencilop_desc). `stencilReadMask` and `stencilWriteMask` can be set for both front and back faces via [D3D12_DEPTH_STENCIL_DESC](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_depth_stencil_desc), together with `stencilTestEnable` and two instances of `D3D12_DEPTH_STENCILOP_DESC` for front and back faces for stencil test. 

`reference`  is not in any descriptor/state at all. 

D3D12 can set reference value for both front and back faces via [ID3D12GraphicsCommandList::OMSetStencilRef](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/nf-d3d12-id3d12graphicscommandlist-omsetstencilref). It can't set reference value for front and back faces separately. D3D12 can't set `stencilReadMask` or `stencilWriteMask` via a function. 

## Metal
Metal can set `depthFailOp`, `stencilFailOp`, `passOp`, `compare` and `stencilReadMask` and `stencilWriteMask` for front and back faces separately via [MTLStencilDescriptor](https://developer.apple.com/documentation/metal/mtlstencildescriptor). Two instances of `MTLStencilDescriptor` for front and back faces for stencil test are included in [MTLDepthStencilDescriptor](https://developer.apple.com/documentation/metal/mtldepthstencildescriptor). 

Metal doesn't have `stencilTestEnable` in `MTLDepthStencilDescriptor`. However, we can disable stencil test via setting MTLStencilDescriptor to nil for each face separately! (Please correct me if I am incorrect, @litherum and @grorg ).

Metal can set reference value for both front and back faces via [setStencilReferenceValue](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515697-setstencilreferencevalue), or for front and back faces separately via [setStencilReferenceValues](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515522-setstencilreferencevalues). Metal can not set `stencilReadMask` or `stencilWriteMask` via a function. 

# Conclusion and Proposal
1. Metal, D3D12 and Vulkan can set `depthFailOp`, `stencilFailOp`, `passOp`, and `compare` for front and back faces separately for stencil test. As a result, we have `WebGPUStencilStateFaceDescriptor` to include these 4 parameters in WebGPU idl. 
2. `stencilReadMask` and `stencilWriteMask` are in the stencilOpState/stencilDescriptor for front and back faces separately for stencil test in Metal and Vulkan, but D3D12 can only have one value for both front and back faces. So we have these two parameters in `WebGPUDepthStencilStateDescriptor`, together with two instances of `WebGPUStencilStateFaceDescriptor` for front and back face separately. 
3. `stencilTestEnable` is included in DepthStencilDescriptor/DepthStencilState in D3D12 and Vulkan for both front and back faces. But Metal doesn't include this parameter in its descriptor. However, Metal can set anyone or both of the two instances of `MTLStencilDescriptor` to nil to disable stencil test for one face or both faces. Currently, WebGPU doesn't include this parameter. I am not sure whether this is a good design.  If we want to disable stencil test or switch between enabling and disabling, we can definitely set stencil test related parameters to some default values (or construct a new descriptor with default values) and make stencil test pass. It acts like that stencil test is disabled. But I either doubt that its performance is as good as disabling stencil test directly via a explicit parameter like `stencilTestEnable` in descriptor in D3D12 and Vulkan, or think that it's inconvenient for web developers. I prefer to add `stencilTestEnable` parameter to `DepthStencilDescriptor` in WebGPU. It is much straight forward to disable stencil test. **I'd like to hear your thoughts about this**.    
4. `reference` is in stencilOpState for front and back faces separately in Vulkan, but Metal and D3D12 can't support this parameter in its descriptor. So WebGPU doesn't include reference value in stencil descriptor, although it's doable at WebGPU side because we have to set this value via a function (see item 5). 
5. Metal and Vulkan can set `reference` via a function for front and back faces separately, but D3D12 can only set one reference value for both faces via a function. Because reference value is a must for stencil test, I propose to add a function `setStencilReference` into **WebGPURenderPassEncoder** to set one reference value for both faces because of D3D12's limitation. see the pr at https://github.com/gpuweb/gpuweb/pull/114. 
6. Only Vulkan can set `stencilReadMask` and `stencilWriteMask` via some functions. So we might don't expose these two functions in WebGPU. If web developers do want to change read/write mask for stencil test, they can construct another `WebGPUDepthStencilStateDescriptor`. 

# Related things:
1. The operation type of `depthFailOp`, `stencilFailOp` and `passOp` need to obey to **StencilOperation**. Metal, D3D12 and Vulkan have the same enumerations for StencilOperation. In addition, the type of `compare` obeys to **CompareFunction**. Metal, D3D12 and Vulkan also have the same enumerations for CompareFunction. WebGPU also exposes these types for StencilOperation and CompareFunction in its idl. 
2. **TODO: set the default values for parameters in WebGPUStencilStateFaceDescriptor and WebGPUDepthStencilStateDescriptor**. But I didn't find statements about default values for some parameters in Vulkan spec.

**Comment by Richard-Yunchao** [comment]
@kvark , just as you said, It's better to have some investigation for a pr to webgpu idl. Here it is. 

PTAL when you have time. You might be busy to discuss some important/urgent features, but this feature is quite consistent among Metal, D3D12 and Vulkan. It will not take you much time to review if you want to take a look.

**Comment by kvark** [comment]
Thank you for writing this down @Richard-Yunchao !
It looks good to me, the only non-clear concern is whether to have a flag for depth/stencil or just use the `nil`.

**Comment by grovesNL** [comment]
It might be worth mentioning that Metal also requires the application to convert the descriptor into state using [`newDepthStencilStateWithDescriptor`](https://developer.apple.com/documentation/metal/mtldevice/1433412-newdepthstencilstatewithdescript?language=objc). Currently we cache cache the created states so we can reuse various combinations of depth stencil state.

In Vulkan, we can set dynamic stencil references values and read/write masks through commands. Metal also allows dynamic stencil state through commands. Metal allows dynamic stencil reference values with [`setStencilFrontReferenceValue`](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515522-setstencilfrontreferencevalue?language=objc) to be set through the encoder (as @Richard-Yunchao mentioned above). However to set read/write masks dynamically in Metal would require a full `MTLDepthStencilState` (containing the updated masks) to be set through the encoder with [`setDepthStencilState`](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1516119-setdepthstencilstate?language=objc).

So there could be a slight performance cliff on Metal if we have to generate many combinations of depth stencil states rapidly because of changing read/write masks.

**Comment by Richard-Yunchao** [comment]
Thanks for your info, @grovesNL . In addition, D3D12 and Vulkan set depth stencil state into its graphics pipeline state. The graphics pipeline state in D3D and Vulkan includes almost everything that can be configured during different stages in graphics pipeline. However, Metal set depth stencil state separately from any pipeline state. And the graphics pipeline state of Metal is much smaller. It doesn't include many things like depth stencil state, blend, scissor rect, viewport, etc.

**Comment by Jasper-Bekkers** [comment]
FWIW, this investigation seems to have missed
`VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK`, `VK_DYNAMIC_STATE_STENCIL_WRITE_MASK` and `VK_DYNAMIC_STATE_STENCIL_REFERENCE` making it optional for these values to be specified in the pipeline descriptor.

Having this state be dynamic (and not requiring PSO recompilation every time stencil state changes) is crucial for AAA games.

**Comment by kvark** [comment]
> Only Vulkan can set stencilReadMask and stencilWriteMask via some functions. So we might don't expose these two functions in WebGPU. If web developers do want to change read/write mask for stencil test, they can construct another WebGPUDepthStencilStateDescriptor.

^ there is no option for us to make the read/write masks dynamic

As for the reference, it's always dynamic as suggested here.

**Comment by Kangz** [comment]
Closing. The stencil state has been fully added to WebGPU for a while now.
