### ISSUE TITLE
How to render point list with WebGPU

### ISSUE THREAD

**Issue by AshleyScirra** [gpuweb/gpuweb#1190]
We're working on a prototype WebGPU renderer for our web game engine to replace our existing WebGL renderer.

One thing I've come across is we render points for particle effects. In short this means using `gl.drawArrays(gl.POINTS, ...` with a shader that writes to both `gl_Position` and `gl_PointSize`.

In WebGPU you can specify `primitiveTopology: "point-list"` for a pipeline, which presumably is equivalent to specifying `gl.POINTS`. In WGSL you can also use `[[builtin(position)]]` as an equivalent to `gl_Position`. However I can't seem to find any equivalent to `gl_PointSize`.

Is this an oversight, is there another way to do this, or maybe is WebGPU not supporting points? (It does seem to be a bit of an odd fixed function feature after all.)

**Comment by austinEng** [comment]
Please see #332, PointSize doesn't exist in HLSL and would require complex emulation.

**Comment by Kangz** [comment]
+1 to what @austinEng said, and even on APIs that support point-size, the clipping behavior is undefined: the point can be either when it is completely outside of the viewport (nice behavior) or when its center gets out if the viewport (yikes, causes popping in and out artifacts).

**Comment by AshleyScirra** [comment]
OK, we can use quads and possibly some kind of instancing, that shouldn't be a problem.

That does leave me wondering though - what is `primitiveTopology: "point-list"` for then?

**Comment by Kangz** [comment]
They're for 1 pixel points and completeness compared to other APIs, but it's true they aren't super useful. We've used it a couple times in tests, and could they could be used in niche cases. For particles you're probably better off doing instancing and triangles / quads with discard for fragments outside the particle.

**Comment by kvark** [comment]
It's still nice to have something to draw *points* without trying to figure out if your small polygon will touch a pixel center or not.

**Comment by AshleyScirra** [comment]
I've prototyped instancing in WebGPU as a replacement for point rendering in WebGL, and it works well - the code actually works out better and I think it's something like ~10% faster in Chrome Canary in WebGPU vs. WebGL. (In our engine it tends to be CPU-bottlenecked, so this represents an improvement on the CPU side - GPU usage isn't such a big concern for us.) So looks like an all-round win for us. Thanks for the advice! (Happy for this to be closed now as an answered question if that's what happens to question-issues)

Going off topic a bit: `"point-list"` being limited to 1px seems weird, especially since due to different display pixel densities a fixed 1px size does not actually guarantee the same physical size. To get a consistent 1px size, equivalent to one CSS pixel, you'd still have to use instancing and implement variable point sizes. But IDK, maybe there's some other use case in 3D where you do really want that 🤷‍♂️

**Comment by Kangz** [comment]
It's great to read that you have gains even on an early WebGPU implementation!

> Going off topic a bit: "point-list" being limited to 1px seems weird, especially since due to different display pixel densities a fixed 1px size does not actually guarantee the same physical size. To get a consistent 1px size, equivalent to one CSS pixel, you'd still have to use instancing and implement variable point sizes. But IDK, maybe there's some other use case in 3D where you do really want that 🤷‍♂️

I believe you can control that with the pixel ratio of the canvas? Maybe?

**Comment by AshleyScirra** [comment]
> I believe you can control that with the pixel ratio of the canvas? Maybe?

You can create a low-dpi canvas, but that reduces the quality of all the contents of the canvas. Everything will look slightly blurry. I don't believe any major canvas-based engine does that - if you have a high-dpi screen then it should render high-dpi content. Which is why drawing 1px sized points doesn't seem very useful - it means you can only draw a density-dependent sized point. Who needs that?

**Comment by greggman** [comment]
Posting this here as this thread came up early on a search for WebGPU Points

https://webgpufundamentals.org/webgpu/lessons/webgpu-points.html
