### ISSUE TITLE
sized arrays must have at least one element

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1195]
This goes along with being able to easily and safely clamp indices.

**Comment by grorg** [comment]
Discussed at [2020-11-03 meeting](https://docs.google.com/document/d/1oV6pmwFOcomeuInQRl-erFt6ZiQfApXYSjoJis7zetA/).

Resolution: Yes, they should.

**Comment by Kangz** [comment]
This is done: the WGSL spec says of sized array sizes `evaluate to an integer scalar with value greater than zero.`
