### ISSUE TITLE
CUDA for Web?

### ISSUE THREAD

**Issue by acterhd** [gpuweb/gpuweb#12]
Hello. Will cuda-like support in gpuweb? 
As I know, CUDA have multiple-gpu (and Nvidia-only) compute. 

So would be cool to see these features: 
- Compute shaders with (or even CUDA-like programs) SSBO, UBO, TBO, etc.
- Atomic operations and counters
- Local, global invocations, and warp operations
- Limited cycles with big number, but with possible to break in defined value

Also, I had idea for WebRL, that adds ray tracing API to Web, that unifies OpenRT, OpenRL, OptiX, RadeonRays, Embree...

**Comment by dmikis** [comment]
JFYI https://www.khronos.org/webcl/. Unfortunately, it didn't get enough attention.

**Comment by acterhd** [comment]
Also, I want ask another question... Will support for Electron and Node.js?

**Comment by dmikis** [comment]
This is an effort to create a new standard. Once it's done, implementations'll come along.

**Comment by VizIT** [comment]
OpenCL and compute shaders have similar capabilities, but they address different use cases. OpenCL targets the case where computations are dominant, or even the sole component. Compute shaders fit in when when the computations are closely coupled with graphics or visualizations, and are present as part of the graphics system. 

This has a number of consequences
- OpenCL requires a separate install
- OpenCL is more difficult to incorporate into the graphics production flow (think writing to a texture)
- Compute shaders use GLSL, an idiom familiar to graphics programmers.

OpenCL is great for applications such as machine learning, and real world complex simulations. Compute shaders are better suited to in game smoke cloud evolution, watter effects, or flying projectiles. Compute shaders are especially well suited for instructional simulations, where the simulations are often simplified, where the continual display of the system state is important, and the simulation can readily be incorporated into existing content. I do this a lot with physics simulations and instructions and the inclusion of compute shaders is definitely valuable to the instructional design community, along with other features such as geometry shaders and transform feedback that help streamline the compute <=> display cycle.

**Comment by litherum** [comment]
What can you do in OpenCL that you can't do in HLSL, SPIR-V, or Metal Shading Language?

**Comment by Kangz** [comment]
Looking at the [OpenCL 2.2 Reference guide](https://www.khronos.org/files/opencl22-reference-guide.pdf) there seems to be:

 - Builtin "pipes" that are opaque FIFO objects.
 - Shared virtual memory so that the CPU and GPU can both use the same pointer.
 - Dispatches can be added from compute kernels.

**Comment by litherum** [comment]
Seems like pipes are implementable on top of existing facilities in each of the three APIs, so it's best to leave that functionality to third-party JavaScript or WebAssembly libraries.

Raw pointer access (on either the CPU or GPU) is inherently insecure and is incompatible with the security model of the Web.

All three platform APIs (Metal, D3D12, and Vulkan) support some form of indirect dispatch which is sufficient for this kind of use case. We haven't explicitly stated that indirect dispatch is part of the goals of this group, but it's likely we will at least discuss the idea and perhaps add it to the specification we are creating.

**Comment by kainino0x** [comment]
Compute is a core part of WebGPU. As more functionality is added to the underlying native platforms, WebGPU will continue to develop new functionality as well.
