### ISSUE TITLE
Texture dimensions should be required to be >=1 (forbid zero-sized textures)

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#1200]
We need at least one pixel in each dimension in order to clamp for e.g. sampling.
This is consistent with our approaches to unsized arrays, and soon for sized arrays (#1195).

We resolved to do this on the [2020-11-03 call](https://docs.google.com/document/d/1oV6pmwFOcomeuInQRl-erFt6ZiQfApXYSjoJis7zetA).

**Comment by Kangz** [comment]
The WIP createTexture PR in #799 adds that, but it's been stalled for a while.

**Comment by Kangz** [comment]
This has been done in the spec.
