### ISSUE TITLE
Publish WebGPU as First Public Working Draft

### ISSUE THREAD

**Issue by tidoust** [gpuweb/gpuweb#1210]
As the work progresses on the WebGPU specification, the group should look into initiating its journey on the Recommendation track. This all starts with publishing the specification as a [First Public Working Draft](https://www.w3.org/2020/Process-20200915/#RecsWD) (FPWD).

It may be tempting to wait until the specification gets closer to MVP. However, publication as FPWD triggers a [call for exclusion](https://www.w3.org/Consortium/Patent-Policy-20200915/#sec-Exclusion) of essential claims, which is something that you should initiate sooner rather than later. For this call for exclusions to be useful, the draft specification should ideally roughly cover its expected final scope, even though many features may still need to be worked upon.

The current WebGPU draft seems to be advanced enough for publication as FPWD. The document and the repository also document outstanding issues.

What about it?

Also note that publication as FPWD is also the time when the group can choose the shortname of the specification, that is the one used in `https://www.w3.org/TR/[shortname]/`, and which is also going to be used across tools to reference the specification. `webgpu` seems like a good shortname, although perhaps `gpuweb` would be more consistent with the naming of the repository.

**Comment by Kangz** [comment]
The FPWD has been published! Closing.
