### ISSUE TITLE
Are implementations allowed to crush DOMString labels down to ASCII?

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#1211]
It might not be testable with our current API, but how hard should we work to preserve non-ASCII strings when passing down to our underlying APIs?

**Comment by Kangz** [comment]
For a good developer experience I'd assume implementation should carry these strings with a representation that matches the DOMString as much as it can. Of course if a native API's equivalent only supports ASCII then I'd imagine converting is fine

**Comment by kainino0x** [comment]
The value passed down to the underlying API shouldn't be observable to the web platform. So for error messages produced in our own implementations (that is, e.g. Dawn code), we should preserve the name, but values passed to the underlying API should probably be sanitized in some way (at least the length should be truncated to a smallish length).

**Comment by kainino0x** [comment]
Meeting: Agreed this is an implementation choice.

**Comment by jdashg** [comment]
> JG: This issue is about when passing it down to the driver. Seems like more of an implementation decision.
