### ISSUE TITLE
Considering making `ARROW function_type_decl` optional for void functions

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1219]
This would allow changing the following:

```
fn main() -> void {
}
```

into:

```
fn main() {
}
```

**Comment by kvark** [comment]
We could go one step further and just remove `void` altogether from the spec.

**Comment by kainino0x** [comment]
The most common usecase of `-> void` is probably entry points. Return values for entry points don't make sense anyway. Could we keep `-> void` required for most functions (to leave syntax open for return inference later), but make it optional or even disallowed for entry points? Though it diverges the entry point syntax from functions.

**Comment by kainino0x** [comment]
I think(?) both options (removing, or making optional) are compatible with a future where we add return type inference (any function that returns void should also infer that it returns void).

**Comment by grorg** [comment]
Resolution from the [2020-11-30 Meeting](https://docs.google.com/document/d/1z56cKIC5nmOkiHqXUEftdJIQV9m1q6SDlgEzRfFrxag/) was to accept this proposal. `-> void` is optional.

In the future we may remove the `void` type altogether.

**Comment by kainino0x** [comment]
^ Unless anyone would prefer to give entry points different rules, in which case we should consider it a little more.

**Comment by dj2** [comment]
Consider which a bit more, making `-> void` optional, or potentially removing `void`?

**Comment by kainino0x** [comment]
For either option, we could make the change just for entry points, instead of for all functions. I'm not particularly advocating this, it's just an idea.

**Comment by kainino0x** [comment]
I thought @jdashg had a concern that making `-> void` optional was not going to be futureproof?

**Comment by Kangz** [comment]
It was mostly resolved at the end of the meeting I believe.

**Comment by litherum** [comment]
> making `ARROW function_type_decl` optional for void functions

This is a good idea, I suggested the exact same thing during today's office hours call.

**Comment by dneto0** [comment]
@jdashg said during the 2020-11-30 meeting (from the notes)

> JG: Need more thought if we want to  remove void. Especially into generics, want to be able to talk about this. Huge pain in c++ is working with functions which return void or not. I think there is potential risk

and later...

> JG: Worried it becomes invisible. Feel like we’re likely to have generics, and if so shouldn’t make things harder. Could be convinced here. If others aren’t worried that’s good. I’ll add my worry to the issue.

And then the last status was:

> DJ: We’ll tentatively agree to make ` -> void` optional.

I'm still ok with making it optional.  I wanted to record Jeff's concern, even if it was lightly held.

I'll also note that in golang, the return-type part of a function signature is optional. (And it also appears to the right of the formal parameter list.)

**Comment by litherum** [comment]
In Swift, saying `-> Void` is either optional or forbidden - I don't actually know which, because nobody writes it. Whenever anyone writes a void function, they just don't write the `->`.

**Comment by kvark** [comment]
We can come back to this when we have generics, and armed with more concrete use cases where generic code would benefit from this. So far it's too far-fetched and too vague. We can always follow-up an say, for example, that having no return type is equivalent to having `-> ()`.
