### ISSUE TITLE
Primitive cut values for non-strip topologies

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1220]
Originally, we requited the index format be provided at pipeline creation, and not in `setIndexBuffer`. Then #943 and #940 changed this to be only required for strip topologies, and in addition `setIndexBuffer` got this as an argument.

However, a concern recently got brought up by @Kangz that [Metal forces](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515520-drawindexedprimitives?language=objc) the primitive cut value to be effective even for non-strip topologies:
> Primitive restart functionality is enabled with the largest unsigned integer index value, relative to indexType (0xFFFF for MTLIndexTypeUInt16 or 0xFFFFFFFF for MTLIndexTypeUInt32). This feature finishes drawing the current primitive at the specified index and starts drawing a new one with the next index.

I did a bit of investigation on other backends as well. [Vulkan appears to specify](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineInputAssemblyStateCreateInfo.html) the cut value independent of the topology as well:
> `primitiveRestartEnable` controls whether a special vertex index value is treated as restarting the assembly of primitives. This enable only applies to indexed draws

Finally, D3D12 isn't specifying exactly what happens for non-strip topologies. It [only says](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_index_buffer_strip_cut_value) what happens for strip ones. I reached out to Microsoft on discord, and got pointed to [D3D11 functional spec](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm), which does specify the same behaviour as Vulkan:
> Even if the current Primitive Topology is not a strip, then the cut index value still takes effect, potentially resulting in an incomplete primitive (see next section). Thus, handling of the cut is kept orthogonal to primitive topology, even though it is not useful for some of them.
> Note that providing a behavior for the cut value when used with a non-strip topology is a way of saying that the behavior is defined, allowing hardware to keep the cut behavior always enabled. In practice though, using cut for a list topology is obviously not a "feature" that it would ever make sense for an application to author to.

With that in mind, I suggest to simply revert #940 and #943 to the old semantics, which appears to be portable across the APIs. Primitive cut values will therefore always be enabled by the WebGPU implementations, to match Metal restrictions.

**Comment by magcius** [comment]
Have we tested whether the primitive restart index is applied in Metal for non-strip topologies? Based on conversations I've had in the past, they've expressed that strip topologies are more expensive *because* of the primitive restart index requires a linear scan, rather than being able to just chunk the index stream and pass different parts off. That implies that non-strip topologies don't have this linear scan process.

This shouldn't be too difficult to empirically test, based on my understanding: if someone renders two triangles with the index buffer `0 FFFF 1 2 3`, do we see 0,FFFF,1 as a triangle, or 1,2,3?

**Comment by kvark** [comment]
I did a bit of experimenting on Metal to find out how it works. It looks like the primitive restart does *not* work for regular `MTLPrimitiveTypeTriangle` topology (but it works for `MTLPrimitiveTypeTriangleStrip` as expected).

Here is the test case:
[HelloTriangle-primitive-restart.zip](https://github.com/gpuweb/gpuweb/files/5585118/HelloTriangle-primitive-restart.zip)

What it does is - rendering with index values of `{0, -1, 2, 0, 1}`. The vertex shader hooks up to a storage buffer in shared memory, only to atomically add the vertex index to it. I.e. for a normal triangle with indices `{0,1,2}` the output in that storage buffer is `7 = 2^0 + 2^1 + 2^2`. The fragment shader also hooks up to an atomic integer, simply bumping it for each fragment.

Here is what I expect this code to do, according to the spec. The `{0, -1}` part to be skipped. Then `{2, 0, 1}` triangle rendered. This is equivalent to changing the draw call to have `indexCount: 3` and `indexBufferOffset: 4`. Buffer values would then be reported as:
> data: 7 62500

Here is the output I actually get on "Intel Iris Graphics 550" with os version 11.1 Beta:
> data: -2147483643 15625

The negative first value means that index `0xFFFF` was processed as usual, and the vertex shader was run, the primitive was not discarded.

Is my test flawed? Is the  Intel 550 GPU just having a driver bug? Or maybe it's a documentation issue in the API? cc @grorg

**Comment by kainino0x** [comment]
The documentation is almost certainly incorrect. See also:

> [jasperrlz](https://matrix.to/#/!MFogdGJfnZLrDmgkBN:matrix.org/$miMcqgGi3StrXB6uD7e7Z4dKK2BRmtJ38PIUww2h4Wc?via=matrix.org&via=feneas.org&via=matrix.fidonet.io)
> An Apple contact has confirmed to me that primitive restart only applies to LineStrip / TriangleStrip, and a bug has been filed to fix the doucmentation.
