### ISSUE TITLE
Disallow implicit LOD texture methods in Compute shaders.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1221]
Using an implicit LOD in a compute shader in SPIR-V causes shader validation errors as it requires extra capabilities.

```
[[stage(compute)]] fn main() -> void { 
  result0.value = textureSample(tex0, samp, vec2<f32>(0.5, 0.5)).x;
  result1.value = textureLoad(tex1, vec2<i32>(0, 0), 0).x;
  return;
}
```

```
error: line 61: OpEntryPoint Entry Point <id> '20[%main]'s callgraph contains function <id> 20[%main], which cannot be used with the current execution modes:
ImplicitLod instructions require DerivativeGroupQuadsNV or DerivativeGroupLinearNV execution mode for GLCompute execution model: ImageSampleImplicitLod
```

Given the extra capabilities required, I think we should disallow the use of the implicit LOD texture methods in compute shaders.

**Comment by dj2** [comment]
@dneto0 @ben-clayton

**Comment by pow2clk** [comment]
HLSL has similar limitations. I had assumed that this was already disallowed.

**Comment by kvark** [comment]
Implicit LOD should only be allowed in fragment shaders.
I.e. vertex shaders are also in the same group as compute.

**Comment by Kangz** [comment]
Closing. The spec has restrictions that texture builtins with implicit LOD and derivative functions must only be called in fragment shaders and with uniform control flow.
