### ISSUE TITLE
should empty structs be permitted?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1222]
The SPIR-V spec permits them.

And people want to use them. E.g. See this attempt to use them to help support for base classes in a mostly-C++ source language: 
 https://github.com/seanbaxter/segfault_nvidia2

cc: @seanbaxter

**Comment by dj2** [comment]
Given that is talking about the possibility it crashes drivers, it doesn't seem like something we'd want to add at this point?

**Comment by kvark** [comment]
Maybe allow them as long as they are not host-shareable?

**Comment by seanbaxter** [comment]
In C++ they only occur as base classes, or with C++20's [[no_unique_address]] attribute, as empty data members. So it's not like the host will ever expose a 0-sized object to a shader. It's just a matter of bringing the shader's data model into alignment with the C++ data model.

**Comment by dj2** [comment]
What is the use of an empty struct in a shader? Where would they be used? If they aren't useful in a shader, I don't think it's worth adding support.

**Comment by seanbaxter** [comment]
C++ generates them all the time. std::pair generates empty structs in libstdc++. The point is to allow non-GLSL frontends.

**Comment by dj2** [comment]
WGSL isn't GLSL so I'm not sure I understand the statement? If they can't be used in a shader, I'm not sure why it's relevant, even if c++ generates them?

**Comment by johnkslang** [comment]
Empty structs can also show up with `#ifdef` stuff on struct contents.

If a front ends can naturally generate them, for which ever reason, it is a bit of an ask to have them delete them.  It's a real transform that can change the number of parameters to functions, etc.

So, it's much more natural for a front end to be able to generate empty structs.  Given that SPIR-V is *lower level* and still supports them, and that that matches what front ends might naturally do, it's a bit of an artificial thing to toss in to require that the bijective text version of SPIR-V cannot have them.

**Comment by dj2** [comment]
WGSL doesn't have `#ifdef` so you can't generate empty structs that way. I'm not sure I understand the transform statement, are you referring to the `#ifdef` of a struct, or having empty structs? How does that change the number of parameters to a function?

WGSL is focused on what we need for WebGPU at this point. At some point in the future we may end up relaxing it to cover more of SPIR-V, but, why do we need this for WebGPU?

**Comment by kainino0x** [comment]
WGSL doesn't have an `#ifdef` because we want people to do preprocessing in userspace. It's easy to imagine a preprocessor or code generator generating an empty struct.

I think what John means is: If empty structs aren't valid, then such a code generator or preprocessor would have to, for an empty struct, either (a) put a dummy member in it, or (b) delete the struct declaration *and* delete every place where it's used (e.g. consts, vars, function parameters, everywhere that calls those functions, ...).

**Comment by johnkslang** [comment]
Yes to what @kainino0x said.

> WGSL is focused on what we need for WebGPU at this point.

The goal does seem to float around a bit.  Yes, of course it needs to support WebGPU functionality, and doesn't need to expose graphical features not in WebGPU, but it is also a language, not just a GPU exposer.  As such, it also needs to be clear about it's language goals:

- is it meant to be a good target for a typical front end (e.g., lacking transforms)?
- is it meant to be bijective with SPIR-V?  (Modulo simple normalizing transforms @dneto0 has discussed.)
- is it meant to be a good high-level programming language on par with GLSL/HLSL/etc?

(And, is the answer the same for other issues that come up?)

**Comment by grorg** [comment]
This was resolved at the [2020-12-01 meeting](https://docs.google.com/document/d/1BGljZlq1ZY1DTZS_MHxTxfu6rF0j87uUrPL7RHArpLA/).

> DS: My question here is “are these useful?”. I kind of get Kai’s point. So I’m ok with having them.
> DS: As long as there is no issue with generating them in SPIR-V. I don’t know if it is possible. This came up because it crashed on NVIDIA.
> DM: Is it going to be a problem with the host size? Doesn’t it require us to support zero-sized bindings?
> DS: So it is restricted to only between shader stages. Not host sharable.
> Resolved: As above.

**Comment by kainino0x** [comment]
To correct Dan's attribution in the meeting, the point came from John, not me.

**Comment by alan-baker** [comment]
The spec is currently contradictory on this point.

`struct<T1,...,TN>` where `N` is greater than zero, but the grammar has:

>struct_body_decl
  : BRACE_LEFT struct_member* BRACE_RIGHT

**Comment by dj2** [comment]
The spec is more restrictive than the grammar in a few places. So, while the grammar allows empty structs, the spec specifically disallows them which takes priority.

**Comment by dneto0** [comment]
If WGSL supports empty structures, someone would have to check the layout rules still make sense, or update them.
