### ISSUE TITLE
Consider storage-texture "read"/"write" methods instead of "load"/"store"

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1228]
Given that our access qualifiers are called read/write, it seems more consistent to have the texture functions named the same.

**Comment by dneto0** [comment]
Sounds good to me.

**Comment by kainino0x** [comment]
Not sure if this applies to textures but if it does, we should be careful with the terminology around "read"/"load"/"fetch"/"sample". E.g. "readable" could mean you can both load a texel and sample with filtering.

We should come up with a terminology (and try to base it on something that exists already) where we have specific words for "fetch" and "sample" but a general word that includes both types of "read" operation.

**Comment by kvark** [comment]
@kainino0x this issue only applies to textures. The access qualifiers are only on storage textures, so "sample with filtering" doesn't apply.

**Comment by dneto0** [comment]
SPIR-V has:
 - OpImageFetch : read texel from a sampled image, with integral coordinates
 - OpImageRead :  read texel from storage image, with integral coordinates
 - OpImageWrite : write texel to storage image, with integral coordinates
 - OpImageSample*  : sample with filtering
About naming: "image" is used for both sampled textures and storage textures.


GLSL has:
 - imageLoad - like OpImageRead
 - imageStore - like OpImageWrite
 - texelFetch  - like OpImageFetch.
If I understand correctly,  "texture" is always used for sampled textures, and "image" is used for storage textures.

HLSL has (as far as I can tell)
-  .Load   method   (here it is in shader model 4. https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-to-load )
-  []  accessor to get you an l-value to write.  (See https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-texture2d-operatorindex )

**Comment by kvark** [comment]
MSL has:
- `texture.read()` = `OpImageFetch` | `OpImageRead`
- `texture.write()` = `OpImageWrite`
- `texture.sample()` = `OpImageSample`

**Comment by grorg** [comment]
Discussed at the [2020-11-30 meeting](https://docs.google.com/document/d/1z56cKIC5nmOkiHqXUEftdJIQV9m1q6SDlgEzRfFrxag/).

Resolution was to *not* accept this proposal.
