### ISSUE TITLE
Open questions about swap chain formats

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1231]
- [x] 1. How sRGB works exactly (can browser always choose between non-srgb and srgb formats? does the app get to have a say; e.g. if they really want srgb, but they want to choose the most optimal between rgba8-srgb and bgra8-srgb, can they?)
- [x] 2. HDR and float16 etc
- [x] 3. getSwapChainPreferredFormat with a list of "formats the app can understand"
- [x] 4. How this interacts with CanvasColorEncodingEnum, if we expose both
- [ ] 5. How to expose display-specific preferred formats that could change when a window is moved between displays

_Originally posted by @kainino0x in https://github.com/gpuweb/gpuweb/issues/1185#issuecomment-729294760_

**Comment by kainino0x** [comment]
Assigning to @jdashg who took an action item to look at 3, which implicitly should solve 1. Then we can worry about the rest afterward.

**Comment by kainino0x** [comment]
It just occurred to me that if an app wants to output linear values into the swapchain texture, then all they need is for the swapchain bgra8unorm to be createView-able as bgra8unorm-srgb..? I'm probably misunderstanding something about what's needed though.

**Comment by kvark** [comment]
@kainino0x that's how it works in D3D/DXGI, at least. Swapchains can not be created with SRGB formats, so users are expected to create an SRGB view into them. That's what gfx-backend-dx11 and gfx-backend-dx12 and do.

**Comment by kainino0x** [comment]
Ok, then I'm pretty sure there should be no srgb formats in our swapchain creation. We just need to make sure -srgb is a valid view format for the swapchain textures (by default or configurable).

**Comment by kainino0x** [comment]
It (correctly) makes the question of linear-space interpolation and blending of canvases purely a CSS concern.

**Comment by kainino0x** [comment]
My **proposed answers** to the questions so far:

> * [ ]  1. How sRGB works exactly (can browser always choose between non-srgb and srgb formats? does the app get to have a say; e.g. if they really want srgb, but they want to choose the most optimal between rgba8-srgb and bgra8-srgb, can they?)

`srgb` formats aren't allowed as canvas texture formats. Instead, the texture view needs to reinterpret the format as the `srgb` equivalent. #2336

> * [ ]  2. HDR and float16 etc

HDR is orthogonal and work is ongoing here: https://github.com/w3c/ColorWeb-CG/blob/master/hdr_html_canvas_element.md
If HDR isn't explicitly enabled, luminance may not exceed the SDR max luminance. If the luminance would exceed that, it is clamped.

Float16 can be used to describe colors that are outside of the gamut of `colorSpace`, e.g. a Display-P3 (1,0,0) red can be represented using extended "srgb" coordinates - this is in fact already written in the spec, even though it doesn't have float16 canvas (because the same language also applies to conversions to f32 in external textures).

If the color (chrominance) is outside of the canvas's configured gamut, it should be preserved (not clamped) - the behavior is the same as if the color were described in a larger-gamut colorSpace and the canvas were configured with that larger colorSpace.

The browser/system should display the canvas as it would [any other image with a wider colorSpace](https://webkit.org/blog-files/color-gamut/) (probably by clamping to the display's gamut).

> * [ ]  3. getSwapChainPreferredFormat with a list of "formats the app can understand"

I'm not sure how this should work. Probably one of two options:

- Application passes a list of formats to getPreferredFormat (defaulting to rgba8unorm, bgra8unorm). We return one from this list. Applications would typically pass either nothing (the default), or `['rgba16float', 'rgb10a2unorm']` I think.
- Simplify things and simply let the application choose either 8-bit (rgba8unorm or bgra8unorm) or &ge;rgb10a2 color depth (rgb10a2unorm or rgba16float). (If they specifically want rgba16float then they just specify that without asking for a preferred format.)

This may also just not matter until we have HDR. I'm not sure whether 10-bit color depth matters just for wide color gamut in SDR.

> * [ ]  4. How this interacts with CanvasColorEncodingEnum, if we expose both

If GPUCanvasConfiguration.colorSpace is "srgb" (the default), the canvas bytes are interpreted as sRGB (with gamma).
If it is ["srgb-linear"](https://drafts.csswg.org/css-color-4/#valdef-color-srgb-linear), the canvas bytes are interpreted as srgb-linear.

Since the canvas can't have an `-srgb` texture format, there's no ambiguity in whether the values are converted when read.

> * [ ]  5. How to expose display-specific preferred formats that could change when a window is moved between displays

I'm guessing this only matters when moving between an HDR and non-HDR display. That's a bigger change for applications to handle (e.g. they would probably switch color depth and likely change the rendering to account for tonemapping). I don't think switching displays would ever change rgba8unorm<->bgra8unorm or rgba16float<->rgb10a2unorm.

I think we need to let this problem be solved much more generally. I would expect people to do this by detecting a change in the [`dynamic-range` media query](https://drafts.csswg.org/mediaqueries-5/#dynamic-range) (see https://w3c.github.io/ColorWeb-CG/#css-media-queries). (Side note, I don't know if canvases would be able to use `video-dynamic-range` or would be stuck with `dynamic-range`).

**Comment by Kangz** [comment]
> Don't allow -srgb formats as canvas texture formats. Instead, the texture view needs to reinterpret the format as the -srgb equivalent. #2336

Does this mean that we need an additional flag when configuring `GPUCanvasContext` to allow the reinterpretation or do we always assume it is present? (swapchain textures are special so maybe the flag isn't needed and they are always slower on Intel Gen 9?)

**Comment by kainino0x** [comment]
> Does this mean that we need an additional flag when configuring `GPUCanvasContext` to allow the reinterpretation

Yes, I updated #2336 while I was writing this comment to update GPUCanvasConfiguration to match GPUTextureDescriptor (missing that was just an oversight).

Although maybe we could enable it by default? I don't know.

**Comment by kainino0x** [comment]
Note https://github.com/gpuweb/gpuweb/pull/2336 removes the -srgb formats from this list.

**Comment by kainino0x** [comment]
> This may also just not matter until we have HDR. I'm not sure whether 10-bit color depth matters just for wide color gamut in SDR.

Ideally we would know the answer to this before adding rgba16float and rgb10a2unorm but I don't think it's strictly necessary.

**Comment by kainino0x** [comment]
> Ideally we would know the answer to this before adding rgba16float and rgb10a2unorm but I don't think it's strictly necessary.

I remembered that https://github.com/KhronosGroup/WebGL/pull/3222 adds float16 support without HDR so I assume it's proven useful.

It doesn't add rgb10a2 so I'd be curious to have implementation experience to make sure it works, but it would be fine to add it to the spec and remove it later if we run into problems. Just need to make sure to test it well! :)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-01-19#swapchain-formats-(srgb-and-float16)-1231">WGSL meeting minutes 2022-01-19</a></summary>



* Current formats in Spec: brga8unorm, rgba8unorm, brga8unorm-srgb, rgba8unorm-srgb
    * “-srgb” formats are not needed?
    * Add rgba16float for HDR? What about rgb10a2unorm?
* JC: don't need the sRGB formats?
* KN: blocked on the view formats discussion. Don't need the formats here if you can view non-sRGB formats as sRGB when you render them.
    * I'm confident we can, just don't know the API surface yet.
    * In the PR I removed the sRGB format from swapchain formats because I don't think they're needed any more.
* JC: Only have 2 formats needed then.
* In Chrome, bgra8unorm format's only supported ont.
* rgba8unorm is needed - directly writable in compute shader. Trying to lift restrictions on support of this format.
* KN: Chrome bug. Red/Blue flip on some platforms. We just need to implement it.
* JC: viz supported rgba16float.
* KN: we do want this format. HDR itself's blocked on canvas figuring it out. We still want these formats even without HDR because you can use them for wide-color gamut which is well understood now. Think we should just addd it - maybe both formats.
* KN: if we had both of these - how would browser tell you which is better on a given OS? haven't figured that out. Have a large comment in there that suggests answers.
* JC: assumed we want rgba16float and rgb10a2unorm?
* KN: will probably want both of them, even for SDR wide color gamut.
* MM: when you say add this or add them, what are we considering adding them to?
* KN: list of allowed canvas configuration formats. There are 4 now, we're removing the sRGB formats so there'll be 2 left, and then considering adding more.
* MM: official name of that enum?
* KN: “supported context formats”. [https://www.w3.org/TR/webgpu/#supported-context-formats](https://www.w3.org/TR/webgpu/#supported-context-formats) 
* KN: probably someone just needs to add these formats to the list. Can discuss more in that proposal.
* KG: if someone could write the proposal that'd be great.


</details>

**Comment by kainino0x** [comment]
Oops I want to leave this open because it still may have an open question about getSwapChainPreferredFormat if we add rgb10a2unorm

**Comment by kainino0x** [comment]
Moving to post-v1 though because we may not need rgb10a2unorm for v1.

**Comment by kainino0x** [comment]
item 3 and the HDR questions ~resolved with #2747, now closing.
