### ISSUE TITLE
Consider whether to allow trailing commas

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1243]
A common usability enhancement in programming languages is to allow trailing commas when defining data structures. This doesn't work in WGSL and the code below is invalid.

```
var pos : array<vec2<f32>, 3> = array<vec2<f32>, 3>(
  vec2<f32>(-1.0, -1.0),
  vec2<f32>( 1.0, -1.0),
  vec2<f32>(-1.0,  1.0),
);
```

Could we consider allowing trailing commas so that copy pasting lines like this works as expected and matches other languages? Having the function-like constructors might make this awkward though.

**Comment by jdashg** [comment]
100% yes to trailing commas

**Comment by kainino0x** [comment]
> Having the function-like constructors might make this awkward though.

Seems fine if we allow trailing commas in functions too.

**Comment by jdashg** [comment]
It's unorthodox but I would love to have 
```
foo(
  list,
  of,
  args,
);
```

**Comment by kainino0x** [comment]
FWIW many languages do allow it, like Rust and JavaScript. Others allow trailing commas in some places (e.g. arrays) but not for function calls, and personally I think that's silly.

**Comment by dj2** [comment]
I think if we do it, we should do it consistently. So, constructors, functions, decorations, etc.

**Comment by jdashg** [comment]
Wow I didn't know JS could do `Math.max(1,2,)`, but it's fine! Awesome, let's ship it.

**Comment by grorg** [comment]
Discussed at the [2020-12-01 meeting](https://docs.google.com/document/d/1BGljZlq1ZY1DTZS_MHxTxfu6rF0j87uUrPL7RHArpLA/). 

Resolved: Accepted.
