### ISSUE TITLE
Parsing of an array fails if no space before the equal sign

### ISSUE THREAD

**Issue by Popov72** [gpuweb/gpuweb#1249]
Is it expected that this fails with "**expected '>' for array declaration**" (Tint from latest Chrome Canary):
```javascript
const pos : array<vec2<f32>, 4>= array<vec2<f32>, 4>(
    vec2<f32>(-1.0, 1.0),
    vec2<f32>(1.0, 1.0),
    vec2<f32>(-1.0, -1.0),
    vec2<f32>(1.0, -1.0)
);
```
?

It fails because there's no space between `>` and `=` in `const pos : array<vec2<f32>, 4>= array<vec2<f32>, 4>(`.
Adding a space make it work:
```javascript
const pos : array<vec2<f32>, 4> = array<vec2<f32>, 4>(
    vec2<f32>(-1.0, 1.0),
    vec2<f32>(1.0, 1.0),
    vec2<f32>(-1.0, -1.0),
    vec2<f32>(1.0, -1.0)
);
```

**Comment by dj2** [comment]
This is a bug in the Tint parser. We're seeing a >= and not dealing with it also possibly being a '>' and '='. Can you please file this issue in https://crbug.com/tint?

**Comment by Kangz** [comment]
Note that `>>` will also be an issue, we don't want to have the same weird restrictions as C++98 ^^.

**Comment by Popov72** [comment]
Filed: https://bugs.chromium.org/p/tint/issues/detail?id=359
