### ISSUE TITLE
Using unsigned integers for `textureLoad` and friends?

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1257]
Currently the `textureLoad` family of function use signed integer for coordinates, for example this is one of the overloads:

```
vec4<type> textureLoad(texture_1d , i32 coords, i32 level_of_detail)
```

My understanding is that if any of the components of `coords` is negative or if `level_of_detail` is negative, then the access is an out-of-bounds access that will need some form of handling. In a similar spirit to making array indices unsigned because it saves a comparison, what do you think of making any texture coordinate that can cause OOB an unsigned integer?

**Comment by dj2** [comment]
When the text gets written up it will be spec as a non-negative number. We use i32 as the value so you don't have to do `1u`. I believe those are on Ben's TODO list.

**Comment by Kangz** [comment]
I'm not sure I understand, you say it will be specced as a non-negative number but also that we use `i32`?

**Comment by dj2** [comment]
Yes, that's the same pattern we've used for things like `location` and `binding`. If we spec as `u32` then you'd have to write `location(1u)` instead of `location(1)`. So, they're non-negative `i32` values.

**Comment by Kangz** [comment]
The difference is that the parameters here aren't compile time constants but runtime values that we will need to clamp in implementations. Having them unsigned means the clamping is a `min` operations instead of a more expensive `clamp` operation.

**Comment by dj2** [comment]
The values could be either compile time or runtime, depending on what you do. We can still do a `min` either way, we'll just have a cast before hand to `u32`.

For reference @kvark suggested `i32` originally in https://github.com/gpuweb/gpuweb/pull/909#discussion_r451009439

**Comment by Kangz** [comment]
IMHO we shouldn't optimize for compile time constants here, it's going to be pretty rare compared to all the cases where the coordinates are computed from some non-uniform value.

**Comment by dj2** [comment]
I'm not sure I understand, I'm not optimizing for compile-time constants. In either case, you need to do the `min`, the only difference is if you have the cast?

We can change to `u32` but need to note that that will be different from how integer vs unsigned integer are used in other builtins.

**Comment by Kangz** [comment]
I think there's a misunderstanding and we're talking about different things. Let's come back to it later.

**Comment by kvark** [comment]
> In a similar spirit to making array indices unsigned because it saves a comparison

Does it really save us anything? My understanding was that casting an integer as unsigned is basically free, since it's reinterpretation of the same data.

> what do you think of making any texture coordinate that can cause OOB an unsigned integer?

It's not obvious, but I don't think we should do it for the coordinates. A you mentioned, they are typically computed, and integer is just a more flexible result of that computation. From the point of view of whoever is computing this, `-1` is as bad as `width+1` value.

> If we spec as u32 then you'd have to write location(1u) instead of location(1)

Eventually we were planning to have the integral types inferred, anyway, so both int and uint would be possible with just passing `1`.

**Comment by Kangz** [comment]
Thanks everyone for the explanations and sorry I haven't been following the WGSL discussions closely enough. Closing this as concern resolved.
