### ISSUE TITLE
What's the reasoning behind using '#' for comments?

### ISSUE THREAD

**Issue by jespertheend** [gpuweb/gpuweb#1262]
Since wgsl is mostly based on rust, which uses `//` for comments. And since javascript, glsl, msl and hlsl all use `//` for comments. I was wondering what the reasoning is behind using `#`. Unless there's a clear parsing advantage to using `#`, it seems like `//` makes more sense to me.

**Comment by potree** [comment]
Was just thinking the same thing today. It's a bit irritating working with // all the time in JS, then having to switch to # for the shaders. Always catches me off-guard, and also doesn't play well with keyboard shortcuts for comments in vscode. 

In spirit of #1234

**Comment by jespertheend** [comment]
Syntax highlighting and shortcuts in sublime text was also what caused me to wonder about this.

**Comment by kvark** [comment]
I believe `//` would work better. @dj2 it would be good to raise this concern on a call quickly.

**Comment by dj2** [comment]
I prefer `#` but won't argue over it if the group wants to changes.

**Comment by Kangz** [comment]
However I'd vote against supporting `/**/` at least until MVP, because it raises question about what happens with nested `/**/`s, etc.

**Comment by johnkslang** [comment]
`#` also has at least cognitive issues when thinking through front-ends that add preprocessor support, even if they are illusions.

`/*` is also ambiguous in things like

```
int y, *x;
y/*x
```

But, it is useful for removing part of a line, so a minor loss there.  But, overall, a net win to just use `//`.

**Comment by jdashg** [comment]
There's a trivial parsing advantage of the one-char '#' instead of the multi-char '//' for comments, particularly since it happens so early in parsing. (it's effectively preprocessed away)

I think we should tend towards JS-like comments, absent other pressures.

**Comment by dj2** [comment]
We discussed this quickly at the meeting today. Consensus is to change from `#` to `//`. Spec change needs a PR.

**Comment by bobbyconnolly** [comment]
Oh god, please just allow both

**Comment by dj2** [comment]
When `//` is added we'll remove `#` from the spec. Supporting both doesn't seem worth the added effort.

**Comment by ben-clayton** [comment]
As @johnkslang points out, supporting both would also cause problems if we ever wanted to support preprocessor statements (in particular `#include`)
