### ISSUE TITLE
Destroying pipelines

### ISSUE THREAD

**Issue by jespertheend** [gpuweb/gpuweb#1263]
Similar to `GPUBuffer.destroy()` and `GPUTexture.destroy()`, should it also be possible to release pipeline resources with more control, rather than relying solely on the garbage collector?

**Comment by Kangz** [comment]
We have tended to only add .destroy() to things that can hold to lots of memory (like textures and buffer can hold > 100MB). One concern is that each new thing we add a `.destroy()` on will need to be validated as not destroyed in `GPUQueue.submit`. We could consider adding it for pipelines too though. What do others think?

**Comment by kvark** [comment]
I don't think this is necessary. Having an early `destroy` function has an implementation cost (as well as specification), so it has to be weighted towards the benefit it provides. With physical resources, it's clear that you can run out of memory if not destroying the resources under specific use cases. With pipelines, it's not clear what's the worst thing that may happen.

**Comment by jespertheend** [comment]
Sounds good. I don’t think this is necessary for MVP. The only reason why I was “missing” this was because I’m used to calling `glDeleteShader` and `vkDestroyPipeline` etc.

**Comment by jdashg** [comment]
We discussed this on the call today and we think that unless we see real issues with waiting for the GC to destroy these, we should leave this without an early destroy option. If we see issues we can reopen this!
Thanks for filing this idea!

**Comment by grorg** [comment]
Discussed at the [2020-12-07 meeting](https://docs.google.com/document/d/11VNsaOHObp5zmQ6E4DIZrQmYZdSJnwQ_JHhqEkYeFUg/edit).
