### ISSUE TITLE
Conversion when the format of input state does not match what's in the shader

### ISSUE THREAD

**Issue by Popov72** [gpuweb/gpuweb#1264]
Currently there's no conversion (at last for the D3D11/12 backend), so if for eg the input state is declaring a int4 for position and the shader is taking a vec4<f32> it does not work.

Should the conversion be done automatically? That's what happens in WebGL (in Angle: https://source.chromium.org/chromium/chromium/src/+/master:third_party/angle/src/libANGLE/renderer/d3d/DynamicHLSL.cpp;l=1202)

[EDIT] Note however that it does work when the data in the buffer are flagged as normalized (so there must be a conversion path somewhere already existing - still speaking about D3D11/12 backend) [/EDIT]

**Comment by kvark** [comment]
Specification defines normalized formats for vertex attributes, see https://gpuweb.github.io/gpuweb/#vertex-formats
It's explicit (and I believe in WebGL it's also explicit). If you have an integer (non-normalized) vertex coordinate that's seen as `vec4` by the shader, that's a validation error.

**Comment by Kangz** [comment]
Reopening: I don't see the validation error in the spec, but maybe I'm not looking in the right place?

**Comment by Kangz** [comment]
More specifically the following validation seems the most related but it doesn't seem to make sense (as in grammatically incorrect english):

> For every vertex attribute in the shader reflection of vertexStage.module that is know to be statically used by vertexStage.entryPoint, there is a corresponding at element of descriptor.attributes that:
>
> - The shader format is at.format.
>
> - The shader location is at.shaderLocation.

**Comment by kvark** [comment]
We have a sketch of that in:
> For every vertex attribute in the shader reflection of vertexStage.module that is know to be statically used by vertexStage.entryPoint, there is a corresponding at element of descriptor.attributes that:
   1. The shader format is at.format.
   2. The shader location is at.shaderLocation.

What it's missing is a description of how the normalized formats are converted.

To clarify: I closed the issue because it was a question about the implicit conversion. And the answer to that is "no".

**Comment by Kangz** [comment]
I can't find where we decided that there would be no implicit conversion. It can be well defined, for example like in OpenGL.

Not arguing that we should have them, but we need clarity in the spec and I think that would need an investigation and a tiny discussion in the group.

**Comment by kvark** [comment]
OpenGL is *not* implicit here, it just has an explicit way of providing non-normalized integers as floats.

**Comment by jdashg** [comment]
Specifically, OpenGL is reads-undefined-values if the shader reads the wrong one of [float-ish, int, uint], where 'float-ish' includes both FLOAT and e.g. UNSIGNED_BYTE+normalized:true. (via e.g. vertexAttribPointer)

**Comment by grorg** [comment]
Discussed at the [2020-12-07 meeting](https://docs.google.com/document/d/11VNsaOHObp5zmQ6E4DIZrQmYZdSJnwQ_JHhqEkYeFUg/edit).

**Comment by jdashg** [comment]
Oh I see now, this is about normalized:false, which does work there as vertexAttribPointer normalized:false INT: 4 => floatish: 4.0, whereas if you want int in the shader, you use vertexAttribIPointer.

**Comment by jdashg** [comment]
I agree with kvark that we already have this. We can reopen if we're wrong!
