### ISSUE TITLE
Post-comparison-filterable depth formats

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1266]
In Vulkan, some depth formats can be filtered post-comparison. This is supposed to be used for percentage-closer filtering (PCF). We currently do not support this.

However, @kvark points out that there is a format feature flag, but it only exposes whether the format can be filtered *without* comparison. Filtering *with* comparison is always supported, regardless of the bit, **but** the results are completely implementation-defined (spec only says "should").

> -   `VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT` specifies that if `VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT` is also set, an image view **can** be used with a sampler that has either of `magFilter` or `minFilter` set to `VK_FILTER_LINEAR`, or `mipmapMode` set to `VK_SAMPLER_MIPMAP_MODE_LINEAR`. If `VK_FORMAT_FEATURE_BLIT_SRC_BIT` is also set, an image can be used as the `srcImage` to `vkCmdBlitImage` with a `filter` of `VK_FILTER_LINEAR`. This bit **must** only be exposed for formats that also support the `VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT` or `VK_FORMAT_FEATURE_BLIT_SRC_BIT`.
> 
>     If the format being queried is a depth/stencil format, this bit only specifies that the depth aspect (not the stencil aspect) of an image of this format supports linear filtering, and that linear filtering of the depth aspect is supported whether depth compare is enabled in the sampler or not. If this bit is not present, linear filtering with depth compare disabled is unsupported and linear filtering with depth compare enabled is supported, but **may** compute the filtered value in an implementation-dependent manner which differs from the normal rules of linear filtering. The resulting value **must** be in the range [0,1] and **should** be proportional to, or a weighted average of, the number of comparison passes or failures.

I'm not clear on whether the bit is supposed to say anything about comparison+filtering. It *almost* sounds like it's saying it's *only* implementation-defined if the bit is unset, but I think that's just poor wording, and it means to say it's always implementation-defined.

See also:
https://docs.google.com/spreadsheets/d/12u6g6-dUGxuwgaNVRDdZVZ0u2zb9kotqEO3_ZA-1930/edit?usp=sharing

**Comment by kainino0x** [comment]
Vulkan is most likely the same as OpenGL in this respect, and OpenGL also makes no commitments about the result of compare+filter (and afaik has no feature flag like this).

**Comment by Kangz** [comment]
OpenGL ES says the following:

> If the value of TEXTURE_MAG_FILTER is not NEAREST, or the value of
TEXTURE_MIN_FILTER is not NEAREST or NEAREST_MIPMAP_NEAREST, then r
may be computed by comparing more than one depth texture value to the texture
reference value. The details of this are implementation-dependent, but r should
be a value in the range [0, 1] which is proportional to the number of comparison
passes or failures.

The intent seems pretty clear, just that they couldn't formalize the exact algorithm due to existing hardware differences. We should be able to rely on depth-comparison filtering.

**Comment by kainino0x** [comment]
I think we've resolved to make no guarantees about the result (like underlying specs) but we should document in the spec exactly what can be done with each format (e.g. do we have non-comparison filtering at all?)

**Comment by kainino0x** [comment]
If I'm reading correctly, Vulkan doesn't guarantee filtering depth formats without comparison, and D3D12 (FL11_0/FL11_1) doesn't even allow it.

https://www.khronos.org/registry/vulkan/specs/1.2/html/chap33.html#formats-mandatory-features-depth-stencil
https://drive.google.com/drive/folders/1rGOgzzVhThGtBX60bQ53rGIAclbPS0IT?usp=sharing

**Comment by kainino0x** [comment]
Oh, I guess d3d12 doesn't even allow comparison filtering on depth, you have to reinterpret as R.

I guess for Vulkan we'd have to look at gpuinfo.org data.

On metal, only some formats always support filtering - depth32float/depth32float-stencil8 don't on Apple GPUs.
I'm guessing this is for non-comparison filtering, and comparison filtering is always available.
https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf

**Comment by kainino0x** [comment]
A quick query against the gpuinfo.org data shows even D16_UNORM doesn't have SAMPLED_IMAGE_FILTER_LINEAR on a ton of devices (Intel/AMD/Qualcomm) even though Metal shows Depth16Unorm as universally supporting the "Filter" capability.
