### ISSUE TITLE
Should maxAnisotropy have [EnforceRange]?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1269]
And if so, should be a typedef involved?

See: #864, #696, #202

**Comment by kainino0x** [comment]
We definitely don't want the default behavior (`value % 65536`), but `[Clamp]` may well make more sense in this case than `[EnforceRange]`.

**Comment by kainino0x** [comment]
Related, should we have any validation that maxAnisotropy isn't larger than a particular value?
(On the IDL side, we could probably even use `octet` which would limit it to 0-255, but it really doesn't matter.)

Is maxAnisotropy a normative limit on how much anisotropy is applied? i.e. can we write a test to make sure that no *more* than maxAnisotropy samples are actually used to compute anisotropic filtering results? I would think yes, though I think this is one of those things that graphics drivers let you force-override in GL/DX.

**Comment by kvark** [comment]
Not sure you can even have tests on anisotropy, given how much leeway the spec leaves to the driver.
