### ISSUE TITLE
I Need Help!!!

### ISSUE THREAD

**Issue by INeedHelp1225** [gpuweb/gpuweb#1287]
I'm Sorry for being annoying.

So I'm a student and I'm doing remote learning.
I wanna use the google meet background, and I have the new updates and everything. But there's only one problem.
I Go On WebGL Report and my Major Performance Caveat is at yes. And in order for me to use the google meet background. I need to have the Major Performance Caveat at no. My browser does support both WebGL 1 and WebGL 2.
If any of yall can help then that will be amazing!!!

**Comment by INeedHelp1225** [comment]
> I'm Sorry for being annoying.
> 
> So I'm a student and I'm doing remote learning.
> I wanna use the google meet background, and I have the new updates and everything. But there's only one problem.
> I Go On WebGL Report and my Major Performance Caveat is at yes. And in order for me to use the google meet background. I need to have the Major Performance Caveat at no. My browser does support both WebGL 1 and WebGL 2.
> If any of yall can help then that will be amazing!!!

**Comment by Kangz** [comment]
I'm sorry but this is not the correct place to ask about WebGL or Google Meet or tech support for them. You can use Meet's support or file a Chromium bug about your GPU being blocklisted for WebGL (and if you do, attach the content of your about:gpu page to the bug).
