### ISSUE TITLE
shader binding validation for multisampled texture seems weird/wrong

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1291]
If the binding member entry is texture, and entry.texture.mutisampled is:

* *true*: The binding is a sampled texture with a sample count of 1.
* *false* then "the binding is a multisampled texture"

That seems wrong ?

**Comment by Kangz** [comment]
Yep that's inverted. @toji can you TAL?

**Comment by toji** [comment]
On it!
