### ISSUE TITLE
Clarify the states and lifetime of GPUCommandBuffer

### ISSUE THREAD

**Issue by ajihyf** [gpuweb/gpuweb#1294]
Currently, the spec says `GPUCommandEncoder` has [four states](https://gpuweb.github.io/gpuweb/#enumdef-encoder-state) and described the transition between these states. However, it doesn't clarify the states and lifetime of `GPUCommandBuffer`. I've found these comments in the [design doc](https://github.com/gpuweb/gpuweb/blob/main/design/CommandSubmission.md#detailed-model)

> If the submission is successful, then at some point in time the GPU will be done processing it. The WebGPU implementation takes the responsibility to detect this moment and gracefully recycle/destroy this command buffer, when it's safe to do so.

The design doc is somewhat outdated since it doesn't have separated abstraction for `GPUCommandEncoder` and `GPUCommandBuffer`.  But I think the principle '`GPUCommandBuffer` is moved after submission' still the same. Also, I've found it's illegal to destroy `GPUCommandBuffer` after submission in some webgpu implementation(like wgpu). Maybe it's better to clarify this in the spec?

**Comment by Kangz** [comment]
Yes, the `GPUCommandBuffer` is consumed by `GPUQueue.submit` and cannot be used again afterwards. The GC can trigger any time in JavaScript so the `GPUCommandBuffer` can be destroyed anytime after it is no longer reachable. In native implementations this would mean that you can destroy it whenever you want although the spec developed in this repo doesn't talk about that.

**Comment by kainino0x** [comment]
I'll most likely fix this along with #1270 and #2312.
