### ISSUE TITLE
The default values of GPUSamplerDescriptor.addressMode{U, V, W} are different from the ones in WebGL

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#1296]
In current WebGPU SPEC the default value of GPUSamplerDescriptor.addressMode{U, V, W} are all "[clamp-to-edge](https://gpuweb.github.io/gpuweb/#GPUSamplerDescriptor)", while in [WebGL 1.0](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texParameter) and [OpenGL ES 2.0 SPEC (chapter 3.7.6)](https://www.khronos.org/registry/OpenGL/specs/es/2.0/es_full_spec_2.0.pdf#nameddest=section-3.7.6), the default value of TEXTURE_WRAP_S and TEXTURE_WRAP_T are both GL_REPEAT. Is it intended to introduce such difference?

**Comment by Kangz** [comment]
I don't think the group even considered the default of WebGL we choosing the defaults for `GPUSamplerDescriptor`. In general the idea was to choose the state that's the cheapest but maybe we can talk about this piece of state again.

**Comment by kvark** [comment]
Briefly checking D3D12 and Vulkan, wrap/repeat indeed appears to have the value of 0, which is the default in C-initialized structs. I think we should follow the suggestion and change the default to match WebGL.

**Comment by kainino0x** [comment]
- GL: Defaults to repeat
- Vulkan: No default but repeat is index 0
- D3D12: No default but repeat is index 0
- Metal: Defaults to clamp-to-edge

I have no opinion at all about which should be default. Out of principle I wish we could make the default clamp-to-border-color; alas, #235 says we can't have that.

**Comment by jdashg** [comment]
I am grateful that Metal bucked the trend and went with clamp-to-edge default, because that's what you want 90% of the time, and if I could wave a magic wand and not break content, I would change the default in webgl. Most textures are not designed to repeat, so the ideal default for most textures would be to clamp-to-edge.
Let's stay clamp-to-edge.

**Comment by jdashg** [comment]
I suppose the counter-argument there is that most textures are really not designed to be sampled out-of-bounds anyway, and that of the wrap modes that people might actually want, wanting repeat is probably more common than *relying* on clamp-to-edge?

**Comment by Jiawei-Shao** [comment]
I met this issue when I was porting a WebGL application into a WebGPU one, so when we set the default values in WebGPU, shall we consider such portability issue from WebGL?

**Comment by kainino0x** [comment]
Today we we resolved we would probably keep defaulting to clamp-to-edge, but consider changing the default to clamp-to-border: #1305

**Comment by Jiawei-Shao** [comment]
I think "repeat" just means "always sampling at the fractional part of the texture coordinates", which should also not be very hard to implement  in the hardware?

**Comment by kainino0x** [comment]
I agree, I don't think there's a cost difference between them.
