### ISSUE TITLE
404 Link on https://github.com/gpuweb/gpuweb/wiki/Proposals---Experiments

### ISSUE THREAD

**Issue by jonobr1** [gpuweb/gpuweb#13]
On the Proposals Experiments the [Apple Proposal](https://github.com/gpuweb/proposals/WebGPU-Apple) resolves to a github 404.

**Comment by legion80** [comment]
Fixed

**Comment by grorg** [comment]
Fixed in https://github.com/gpuweb/gpuweb/wiki/Proposals---Experiments/86b28821db87943b8f7b96e415e8e30d60a7e62e
