### ISSUE TITLE
Vertex attribute defaults - add GPUInputStepMode "constant"?

### ISSUE THREAD

**Issue by jespertheend** [gpuweb/gpuweb#1304]
If I understand correctly, in a scenario where a mesh is missing uv or vertex color data for instance, shader code would need to be modified in order to account for this missing data.
I think it could be useful to provide a way to configure default values for vertex attributes for when data is not available. This way shader code can be reused between meshes with different formats.

I don't know much about the internal workings of gpus, so what I'm proposing here might not be a performance gain at all. But it seems to me like having to modify shader code and replace certain vertex attributes with default values is less efficient than if you were able to reuse shader modules in a new pipeline. The new pipeline could have these defaults configured in their vertexState for instance.

I'm not sure to what extent this would be feasible with the current apis though. If a system like this requires the browser to modify and compile new shadercode behind the scenes I don't think there's much to be gained from this. In that case applications might as well do this themselves.

**Comment by kainino0x** [comment]
I think we originally hoped the way would do this is a `GPUInputStepMode` of `"constant"`, which you could then point at a one-vertex-element-sized array. Unfortunately I know we couldn't add it for some reason (looks like D3D12 probably doesn't have it? https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_input_classification).

**Comment by magcius** [comment]
You should be able to do it in D3D12 by setting StrideInBytes to 0 when filling in the VertexBufferView: https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_vertex_buffer_view

**Comment by kainino0x** [comment]
Right, I should have remembered that (it's been like 3 years...). That's probably not the API that was a limiting factor then.

**Comment by kainino0x** [comment]
I can't find an issue. Thought we would have one, but maybe it even predates this group.

- D3D12: StrideInBytes 0?
- Metal: MTLVertexStepFunctionConstant (available on all hardware/api versions)
- Vulkan: Not sure how to do it or if it's possible, offhand.

**Comment by Kangz** [comment]
You can set the stride to 0 on Vulkan on pipeline creation. Dawn has tests for this and it works everywhere.

**Comment by kainino0x** [comment]
(... revisiting.) Right. We don't need a GPUInputStepMode "constant" because we the API can already support it by setting arrayStride to 0.

E.g. in Metal: https://source.chromium.org/chromium/chromium/src/+/master:third_party/dawn/src/dawn_native/metal/RenderPipelineMTL.mm;l=464;drc=0055d95fa7c03751a3b896582772f4ff7ee1c3a5
