### ISSUE TITLE
add sample_index and sample_mask builtin variables

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1317]
WebGPU supports modifying the sample mask in the fragment shader.  See https://gpuweb.github.io/gpuweb/#sample-masking 
There's an open issue to link to the "SV_SampleIndex" and "SV_Coverage" semantics in WGSL.

Across languages:

sample_index, input:

- SPIR-V:  SampleId variable, array of 32-bit integer scalar values, input only.
- GLSL: in int gl_SampleID;
- [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics): uint SV_SampleIndex, input or output
- MSL: uint sample_id input

sample_mask:

- SPIR-V:  SampleMask variable, with 32-bit integer array, input or output.   Number of elements of in the array is bounded above by max num samples supported by the implementation. (1 if at most 32 samples, 2 if at most 64 samples.)
- GLSL: in int gl_SampleMask[];
- [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics): uint SV_SampleMask, input or output
- MSL: uint sample_mask input or output

Proposal:  Add builtin variables  sample_index with u32 value, sample_mask with u32 value.

**Comment by dneto0** [comment]
I should have linked to:
- The original investigation: https://github.com/gpuweb/gpuweb/issues/267 
- https://github.com/gpuweb/gpuweb/issues/959 question about Metal's implementation

**Comment by dneto0** [comment]
Correction:
GLSL has gl_SampleMaskIn for input, and gl_SampleMask for output.

I propose we have:    sample_mask_in, sample_mask, and sample_index

**Comment by kvark** [comment]
Thank you for filing this! We definitely need those :)

> uint SV_SampleIndex, input or output

The "output" part here doesn't make sense to me. Any idea what the semantics of "writing from fragment shaders" for this would be? Perhaps, it's just a documentation error.

Note: distinct `_in` suffix will not be needed if we go with #1315

**Comment by dneto0** [comment]
> The "output" part here doesn't make sense to me. Any idea what the semantics of "writing from fragment shaders" for this would be? Perhaps, it's just a documentation error.

The HLSL reference page describes SV_SampleIndex as "Sample frequency index data. Available to be read **or written to** by the pixel shader only." (emphasis added)

I agree, I don't know what writing it would be.  I didn't look too far because the other APIs don't support it.

I agree, it's probably a documentation error.  cc: @pow2clk 

> Note: distinct _in suffix will not be needed if we go with #1315

Right, but that isn't plan of record yet.  I'll treat that separately.

**Comment by dneto0** [comment]
> Note: distinct _in suffix will not be needed if we go with #1315

Actually, we don't strictly need it here either because we can distinguish them by storage class.  I used different names for clarity.

**Comment by kvark** [comment]
@dneto0 wouldn't that contradict the validation?
> v-0001: A declaration must not introduce a name when that name is already in scope at the start of the declaration.

If you want the storage classes to form name spaces, we need to change the spec accordingly

**Comment by dj2** [comment]
I don't think that's what he's saying. The variables still need different names, but we don't have to have two builtin names.

```
[[builtin(sample_mask)]] var<in> mask_in : u32;
[[builtin(sample_mask)]] var<out> mask_out : u32;
```

So, same builtin, but we know if it's in or out based on storage class. The declarations still have unique names.

**Comment by kvark** [comment]
Ah yes, of course. We don't have to have a different name. Was just thinking that it could be beneficial to associate each built-in with a particular storage class. First, because it's easier to specify (i.e. a table where each built-in has a concrete storage class). Secondly, because it opens up an option for us to omit the storage class for built-ins altogether.
