### ISSUE TITLE
Expose whether WebGPU is supported or not

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#132]
How do we expose the fact that WebGPU is supported/available or not?

Shall we add a boolean attribute to `gpu` namespace **or** simply reject with a specific error when calling `requestAdapter()`?
One other idea would be to always resolve with `requestAdapter()` but rejects when asking for `low-power` or `high-performance` adapter in `requestAdapter()`.

What do you think about this?

**Comment by devshgraphicsprogramming** [comment]
Am I correct in assuming Adapter == Device?

Then I think that it will be hard for you choose any device other to the one that the browser has already chosen by the time it's started, i.e. you will only be able to render straight (use it with the same semantics as a swapchain) into a texture/image prepared for you (you and the browser can share it) by the browser tab if either:
1. WebGPU is using the same backend API+device as the browser tab
2. The browser is using an API that has interop with the native API device that WebGPU will run on
3. The device you want to choose for webGPU is a part of a sub-group which itself is part of the same device-group as the device-group of the device sub-group used by the browser tab (i.e. different GPUs but linked with CrossFire/SLI)

A set-up where the above is not possible would require you to make copies via the CPU with two format conversions (necessary even in UMA systems, rendertargets and textures have unspecified tiling/memory layout) from the webGPU app's device to the browser tab's device on every swapchain image swap.

Its feasible (but still slow) on systems with Unified Memory, but on systems where the GPU is a PCIe adapter it will be a performance killer (even with PCIe 3.0 16x this will take 4ms for only half of the journey for a 4k HDR image) and even more gravely... instil a massive latency penalty.

P.S. You will not get away with the aforementioned copy on mobile devices where a 4GB/s DDR speed is considered fast and resolutions >FullHD are common.

**Comment by Kangz** [comment]
> Am I correct in assuming Adapter == Device?

Kind of, think of them a bit like VkPhysicalDevice and VkDevice: the adapter is for discovery and querying features and the device is a connection to that device where you can actually do stuff.

> Then I think that it will be hard for you choose any device other to the one that the browser has already chosen by the time it's started

This is already not true for WebGL: you can use the power preference option to choose whether the integrated GPU or the discrete one is used and the browser compositor makes everything appear on the screen via OS-specific mechanisms (DirectComposition on Win10, IOSurfaces on macOS, etc.)

**Comment by devshgraphicsprogramming** [comment]
Thanks for clearing up the webGPU apdapter vs. device.

>  integrated GPU or the discrete one is used and the browser compositor makes everything appear on the screen via OS-specific mechanisms

True, I wasn't saying it was impossible, just inefficient.

Also Vulkan will report far more devices (not connected to a screen, not compostable) than WebGL would have had the freedom to create contexts on.

I believe the composting scenario (Nvidia GPU writing into Intel GPU framebuffer as it does on laptops) is a kind-of extension of caveat no. 3

**Comment by kvark** [comment]
The low-power/high-performance are just the hints. So if you as an application get `requestAdapter` failing, that exactly means that WebGPU is not supported.

**Comment by devshgraphicsprogramming** [comment]
Why don't you return a list of adapter prototypes that can be used from `requestAdapters`, expose information about them and let them be used as the argument to your instance creation function?

That way you do away with OpenGL style non-binding hints.

Obviously first adapter in the list could be the default you'd want the user to use.

**Comment by Kangz** [comment]
> Why don't you return a list of adapter prototypes that can be used from requestAdapters, expose information about them and let them be used as the argument to your instance creation function?

That's almost what we're doing (except that the function is on the adapter itself). However exposing all the adapters directly would cause fingerprinting issues. That's why we settled on the hint for now, it isn't perfect but helps a little bit against fingerprinting.

I think @kvark's idea would work, with a caveat that we also need the application to know whether they are using a real GPU or a software fallback (like Dawn on Vulkan on Swiftshader).

**Comment by kainino0x** [comment]
If the hints could express it, we could even allow the application to choose software rendering when a GPU is available.

Another thing we might want to add to WebGPUAdapterDescriptor, just like in WebGL, is `failIfMajorPerformanceCaveat` (~= fail if only software rendering is available). Applications could get an adapter then check the adapter's properties for whether it's software rendering, but `failIfMajorPerformanceCaveat` is more obvious and developers are more likely to remember to use it (IMO).

**Comment by Kangz** [comment]
We are not planning to have multi-GPU support for now.

It's not clear that we'll expose VENDOR_IDs and I don't think we'll have vendor specific extensions if by that you mean NV_ray_tracing. We do plan on having extensions to expose things beyond the core WebGPU spec, for example texture compression.

**Comment by devshgraphicsprogramming** [comment]
> if by that you mean NV_ray_tracing.

No I mean any of the following:
```
// things common with GLSL
AMD_gcn_shader
AMD_gpu_shader_half_float
AMD_gpu_shader_half_float_fetch
AMD_gpu_shader_int16
AMD_shader_ballot
AMD_shader_explicit_vertex_parameter
AMD_shader_fragment_mask
AMD_shader_image_load_store_lod
AMD_shader_trinary_minmax
AMD_texture_gather_bias_lod

NVX_multiview_per_view_attributes
NV_viewport_array2
NV_stereo_view_rendering
NV_sample_mask_override_coverage
NV_geometry_shader_passthrough
NV_shader_subgroup_partitioned
NVX_raytracing
NV_compute_shader_derivatives
NV_fragment_shader_barycentric
NV_mesh_shader
NV_shader_image_footprint
NV_shading_rate_image



SPV_EXT_descriptor_indexing
SPV_EXT_fragment_fully_covered
SPV_EXT_shader_stencil_export
SPV_EXT_shader_viewport_index_layer
SPV_GOOGLE_decorate_string


// GLSL only extensions
GL_AMD_shader_stencil_export
GL_AMD_vertex_shader_viewport_index
GL_AMD_vertex_shader_layer
GL_NV_bindless_texture
GL_NV_shader_atomic_float
GL_AMD_sparse_texture
GL_EXT_shader_integer_mix
GL_INTEL_fragment_shader_ordering
GL_AMD_shader_stencil_value_export
GL_NV_shader_thread_group
GL_NV_shader_thread_shuffle
GL_EXT_shader_image_load_formatted
GL_AMD_gpu_shader_int64
GL_NV_shader_atomic_int64
GL_EXT_post_depth_coverage
GL_EXT_sparse_texture2
GL_NV_fragment_shader_interlock
GL_NV_geometry_shader_passthrough
GL_NV_sample_locations
GL_NV_shader_atomic_fp16_vector
GL_NV_command_list
GL_OVR_multiview
GL_OVR_multiview2
GL_NV_shader_atomic_float64
GL_INTEL_conservative_rasterization
GL_NV_conservative_raster_pre_snap
GL_EXT_shader_framebuffer_fetch 
GL_EXT_shader_framebuffer_fetch_non_coherent
GL_INTEL_blackhole_render
GL_NV_shader_texture_footprint


// Vulkan and OpenGL common extensions (for now only Nvidia)
NV_clip_space_w_scaling
NV_corner_sampled_image
NV_fill_rectangle
NV_fragment_coverage_to_color
NV_framebuffer_mixed_samples
NV_representative_fragment_test
NV_scissor_exclusive
NV_viewport_swizzle


// Vulkan only non-Khronos API extensions
VK_EXT_acquire_xlib_display
VK_EXT_astc_decode_mode
VK_EXT_blend_operation_advanced
VK_EXT_conservative_rasterization
VK_EXT_debug_utils
VK_EXT_depth_range_unrestricted
VK_EXT_direct_mode_display
VK_EXT_discard_rectangles
VK_EXT_display_control
VK_EXT_display_surface_counter
VK_EXT_external_memory_dma_buf
VK_EXT_external_memory_host
VK_EXT_global_priority
VK_EXT_hdr_metadata
VK_EXT_inline_uniform_block
VK_EXT_queue_family_foreign
VK_EXT_sample_locations
VK_EXT_sampler_filter_minmax
VK_EXT_swapchain_colorspace
VK_EXT_validation_cache
VK_EXT_validation_flags
VK_EXT_vertex_attribute_divisor

VK_AMD_buffer_marker
VK_AMD_mixed_attachment_samples
VK_AMD_rasterization_order
VK_AMD_shader_core_properties
VK_AMD_shader_info

VK_ANDROID_external_memory_android_hardware_buffer
VK_GOOGLE_display_timing
VK_IMG_filter_cubic
VK_IMG_format_pvrtc
VK_MVK_ios_surface
VK_MVK_macos_surface
VK_NN_vi_surface

VK_NV_device_diagnostic_checkpoints
VK_NVX_device_generated_commands


GLX_EXT_visual_info
GLX_EXT_visual_rating
GLX_SGIX_fbconfig
WGL_EXT_swap_control
WGL_EXT_depth_float
GLX_SGIX_visual_select_group
GL_MESA_resize_buffers
GLX_MESA_release_buffers
GL_NV_texture_compression_vtc
GL_MESA_pack_invert
GLX_EXT_fbconfig_packed_float 
WGL_EXT_pixel_format_packed_float
GL_EXT_texture_compression_latc
GLX_NV_swap_group
WGL_NV_swap_group
GL_EXT_direct_state_access
WGL_NV_gpu_affinity
GL_ATI_meminfo
GL_AMD_performance_monitor
WGL_AMD_gpu_association
GL_EXT_swap_control
GL_NV_vertex_buffer_unified_memory
GL_NV_texture_barrier
GLX_INTEL_swap_event
GL_NV_vertex_attrib_integer_64bit
GL_NV_vdpau_interop
GLX_AMD_gpu_association
GL_AMD_depth_clamp_separate
GL_AMD_blend_minmax_factor
GL_AMD_sample_positions
GL_EXT_x11_sync_object
GL_EXT_framebuffer_multisample_blit_scaled
GL_NV_path_rendering
GL_AMD_pinned_memory
GL_AMD_stencil_operation_extended
GLX_EXT_swap_control_tear
WGL_EXT_swap_control_tear
GL_AMD_query_buffer_object
GL_NV_deep_texture3D
GLX_EXT_buffer_age
GL_AMD_interleaved_elements
GL_NV_bindless_multi_draw_indirect
GL_NV_blend_equation_advanced 
GL_NV_blend_equation_advanced_coherent
WGL_NV_delay_before_swap
GL_NVX_gpu_memory_info
GL_EXT_debug_label
GL_EXT_debug_marker
GL_INTEL_performance_query
GLX_NV_delay_before_swap
GLX_MESA_query_renderer
GLX_EXT_stereo_tree
GL_AMD_framebuffer_sample_positions
GL_NV_bindless_multi_draw_indirect_count
GLX_NV_copy_buffer
GL_NV_uniform_buffer_unified_memory
GL_EXT_polygon_offset_clamp
GL_EXT_raster_multisample
GL_EXT_texture_filter_minmax
GL_NV_conservative_raster
GL_NV_path_rendering_shared_edge
GL_NV_internalformat_sample_query
GL_NV_conservative_raster_dilate
GL_INTEL_framebuffer_CMAA
GLX_EXT_libglvnd
GL_NV_robustness_video_memory_purge
GL_NV_conservative_raster_pre_snap_triangles
GL_EXT_window_rectangles
GL_NVX_blend_equation_advanced_multi_draw_buffers
GL_NVX_linked_gpu_multicast
GL_NV_gpu_multicast
WGL_EXT_colorspace
GL_NV_alpha_to_coverage_dither_control
GL_NV_draw_vulkan_image
GL_EXT_memory_object 
GL_EXT_semaphore
GL_EXT_memory_object_fd 
GL_EXT_semaphore_fd
GL_EXT_memory_object_win32 
GL_EXT_semaphore_win32
GL_EXT_external_buffer
GL_NV_blend_minmax_factor
GL_NV_query_resource
GL_NV_query_resource_tag
GLX_MESA_swap_control
GL_NV_conservative_raster_pre_snap
GL_AMD_framebuffer_multisample_advanced
GL_NV_memory_attachment
```

Some like `_fragment_shader_ordering` are very essential.

**Comment by Kangz** [comment]
The majority of these extensions don't have wide-enough support to be exposed by WebGPU or folks (at least on our side) working to specify corresponding WebGPU extensions. WebGPU isn't meant to give access to all the GPU features present on a system, it is meant to provide to extremely widely supported GPU features.

Maybe some of the `VK_EXT` you listed would fit that criteria.

**Comment by devshgraphicsprogramming** [comment]
Ok let me prune down this list of extensions to just Vendor specific and a few sets that are essential for various rendering methods and tasks.

Wave Intrinsics (PS4 and Xbox programmers are really really used to these)
```
GL_NV_shader_thread_group
GL_NV_shader_thread_shuffle
NV_shader_subgroup_partitioned
NV_compute_shader_derivatives
AMD_shader_ballot
```

Fastest Order-Independent-Transparency or Programmable Blending
```
GL_INTEL_fragment_shader_ordering
GL_NV_fragment_shader_interlock
```

Render/Raster Optimization
```
VK_AMD_rasterization_order
NV_mesh_shader
```

Advanced Anti-Aliasing (any AA mode that is not MSAA)
```
GL_AMD_shader_stencil_value_export
AMD_shader_fragment_mask
NV_sample_mask_override_coverage
GL_AMD_shader_stencil_export
NV_fragment_coverage_to_color
NV_framebuffer_mixed_samples
NV_representative_fragment_test
VK_AMD_mixed_attachment_samples
GL_AMD_stencil_operation_extended
GL_INTEL_framebuffer_CMAA
GL_NV_alpha_to_coverage_dither_control
```

Wolfgang Engel's Deferred+, a.k.a. Visibility Buffer, a.k.a. Full Deferred Shading+Texturing
(not necessary but a huge improvement in barycentric coord calculation)
```
AMD_gcn_shader
NV_fragment_shader_barycentric
GL_NV_bindless_texture
NV_bindless*
EXT_descriptor_indexing
```

Virtual Reality and Multiview Rendering
```
GL_OVR_multiview
GL_OVR_multiview2
NV_clip_space_w_scaling
NV_scissor_exclusive
NV_viewport_swizzle
NVX_multiview_per_view_attributes
NV_stereo_view_rendering
NV_shading_rate_image
```

Voxelization (VXGI, SDF generation etc.)
```
GL_INTEL_conservative_rasterization
GL_NV_conservative_raster_pre_snap
GL_NV_conservative_raster
GL_NV_conservative_raster_dilate
GL_NV_conservative_raster_pre_snap_triangles
```

Layered/Multiview Rendering (drawing all faces of many cubemaps at once, or updating multiple environment maps)
```
GL_AMD_vertex_shader_viewport_index
GL_AMD_vertex_shader_layer
NV_viewport_array2
NV_geometry_shader_passthrough
```

Half floats and shorts in shaders
```
AMD_gpu_shader_half_float
AMD_gpu_shader_half_float_fetch
AMD_gpu_shader_int16
GL_NV_shader_atomic_fp16_vector
```

Advanced Texturing
```
AMD_shader_image_load_store_lod
AMD_texture_gather_bias_lod
VK_IMG_filter_cubic
VK_IMG_format_pvrtc
GL_NV_shader_texture_footprint
NV_shader_image_footprint
```

64bit data-types support in shaders
```
GL_AMD_gpu_shader_int64
GL_NV_vertex_attrib_integer_64bit
GL_NV_shader_atomic_float64
GL_NV_shader_atomic_int64
```

Raster Graphics Rendering
```
GL_NV_path_rendering
GL_NV_path_rendering_shared_edge
```

Note I'm not asking/demanding any of these  be implemented in MVP, or even in ver 1.0 but you should think about how vendor specific features/extensions will be exposed and make appropriate provisions for them (and not listing adapters or extensions would definitely hinder that).

**Comment by kvark** [comment]
This is a good breakdown, thanks @devshgraphicsprogramming !
If there is more to this discussion (which I don't think is the case at this stage in development), we should continue it in a dedicated issue. Looks like we are steering too far from the original subject here.

**Comment by devshgraphicsprogramming** [comment]
my main point was that webGPU should list adapters and their webGPU extensions, rather than operate on annoying hints because as a developer I want the device with the featureset and performance my app requires.

A simple low-perf/high-perf hint won't do.

**Comment by missmah** [comment]
Agreed with @devshgraphicsprogramming - WebGPU should not wait until say version 2.0 to properly enumerate devices on the system to the user. Seems to me like WebGPU extensions should be a part of device enumeration from the beginning (even if the supported extension list is empty at first)...

**Comment by kainino0x** [comment]
Extensions will definitely be supported. The other issue isn't totally solved yet - we haven't decided whether the list of available adapters will be exposed. (One reason: it could make it easier to accidentally write code that isn't portable across hardware by default.)

**Comment by h1z1** [comment]
> Denying developers the use of such, on account of preventing fingerprinting, would be a hindrance.

Allowing developers to do so blindly would violate the privacy of millions.  It should not be up to developers to decide certainly not at a spec level.   While your extension summary is quite informative it misses one very key distinction that is the interface in which those are exposed.

**Comment by litherum** [comment]
@kainino0x is totally correct: coding to one specific device is an anti-pattern on the Web. The Web is portable by default, and it is our job, as designers of Web APIs, to preserve that property. This task is more difficult with WebGPU than with other Web APIs, but that doesn't absolve us of the responsibility.

@h1z1 is also totally correct: The Web has much stricter privacy requirements than platform APIs. 

Regarding the philosophy of which extensions to create in WebGPU, we should be use-case driven, like the rest of the Web Platform. The fact that an extension exists in one of the three platform APIs is not sufficient to add it to the Web. Instead, requests should be handled on a case-by-case basis, and should be motivated by problems or potential improvements in user experience in the current API. That way, the WebGPU community can design the best solution to the problem within the constraints of the Web, which may or may not look anything like a particular extension of a particular API.

We aren't designing WebVulkan, WebD3D, or WebMetal here.

**Comment by munrocket** [comment]
Float64 can be useful for machine learning, don’t you think about that? Right now they use CUDA for training, but WebGPU can gain same performance and accuracy.

**Comment by kainino0x** [comment]
It won't be available in core because it's impossible to support on a lot of hardware. But it is definitely a candidate extension (or set of extensions).

**Comment by munrocket** [comment]
Yes, f64 extension can be useful for training ML models on PCs that without CUDA. This PCs support only WASM/JS/Python backends to get precise results.

**Comment by kainino0x** [comment]
Closing this as the original question has been long answered: requestAdapter(s) won't return adapter(s) if there are none supported.
