### ISSUE TITLE
Query API: Maximum limit on query count

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#1324]
Currently we restrict the maximum query count to 8192 for **all types** of query set in [WebGPU Spec](https://github.com/gpuweb/gpuweb/blob/main/spec/index.bs#L6897), there are two  reasons for the limitation to 8192 (discussed in #1072):
	1)  When resolving sparse queries in a query set, we need to traverse the available array (same size with the query count of the query set) to calculate the intervals of queries used in command encoder, then resolve them separately. If we create the query set with a large query count (for example UINT32_MAX/32), it will take time to do the calculation. 
	2) For occlusion query,  the maximum size of `visibilityResultBuffer` (used as occlusion query set) is 256KB on Metal, to fit the restriction, we decided to limit the maximum size of query set to 64KB. Because the size of a occlusion query result is 8-bytes, the maximum query count is 64 * 1024 / 8.

For other types of query set, there is no limit statement on the maximum size in D3D12/Vulkan/Metal specifications. 
I test some values on my local machine, and get different results for each backend and query type.

Query Type | Max count on D3D12 | Max count on Vulkan | Max count on Metal
-------------| ------------------------| -------------------------|----------------------
Pipeline Statistics | UINT32_MAX/17 | UINT32_MAX | UINT32_MAX / (sizeof(MTLCounterResultStatistic) * 2)
Timestamp |UINT32_MAX/17 | UINT32_MAX  | UINT32_MAX / (sizeof(MTLCounterResultTimestamp) * 2)

If exceed the max count, out of memory error is thrown. 

Do we need to add another maximum count limit larger than 8192 for pipeline statistics and timestamp queries, or keep them consistent with occlusion query?

**Comment by litherum** [comment]
Resolved: blanket limit of 8192 on every type of query.

**Comment by haoxli** [comment]
Thanks! Close this issue.

**Comment by kvark** [comment]
Interesting, thanks for the link @alecazam !
I wonder what happens if you use more than 512. I don't see a limit on the active number of queries in Vulkan.

**Comment by BlurryLight** [comment]
> @kvark I'm using Vulkan on Android on snapdragon 8gen2/865/870 and found no problem(like device lost) if using more than 512 occlusion queries every frame(in my case, I use almost 1000 queries).

I believe there are some vendor restrictions on the Occlusion Queries active on Adreno platforms. In my case, I have a complex scene (maybe 3000-4000 occlusion queries, I don't count it precisesly but estimate it by number of actors) and on a vivo phone with 8 Gen1,  vkGetQueryPoolResults may stall for more than 1s or even worse it may crash the whole game.  There are some similar reports on Epic UDN in Unreal Engine about the issue so it's not a rare case on adreno platforms.  It's not that reliable if use heavily, both in stability and performance

**Comment by leozzyzheng** [comment]
> > @kvark I'm using Vulkan on Android on snapdragon 8gen2/865/870 and found no problem(like device lost) if using more than 512 occlusion queries every frame(in my case, I use almost 1000 queries).
> 
> I believe there are some vendor restrictions on the Occlusion Queries active on Adreno platforms. In my case, I have a complex scene (maybe 3000-4000 occlusion queries, I don't count it precisesly but estimate it by number of actors) and on a vivo phone with 8 Gen1, vkGetQueryPoolResults may stall for more than 1s or even worse it may crash the whole game. There are some similar reports on Epic UDN in Unreal Engine about the issue so it's not a rare case on adreno platforms. It's not that reliable if use heavily, both in stability and performance

We found the device lost is caused by wrong usage of occlusion queries, begin end end query should be inside the same render pass, the validation layer doesn't check this and it randomly cause device lost, after I fixed it, there is no device lost anymore with me, at least with 1000 queries.

**Comment by kainino0x** [comment]
That's very useful to know, thank you for reporting back!
