### ISSUE TITLE
arrayLength should operate on pointer-to-runtime-sized-array instead of runtime-array

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1329]
The arrayLength builtin must have access to the enclosing pointer-to-structure.  Since we won't be able to do much with pointers, we will always be able to start with pointer-to-runtime-sized-array and trace backward to find the originating buffer varible.

Also, we have a restriction for runtime-sized arrays.  "The type of an expression must not be a runtime-sized array type."

Where we currently have a type rule:

```
Precondition:
    e : array<E>
Conclusion:
    arrayLength(e) : u32
```

we need to change it to:

```
Precondition:
    e : ptr<stroage,array<E>>
Conclusion:
    arrayLength(e) : u32
```

(I would argue that array indexing is signed, so it should yield i32, but I'll track that separately)

**Comment by kvark** [comment]
Is this actually necessary? I.e. would we need to support `arrayLength()` on pointers that we don't statically know about (when variable pointers are enabled) down the road?

> Also, we have a restriction for runtime-sized arrays. "The type of an expression must not be a runtime-sized array type."

If I understand correctly, the restriction equally holds for the expression that takes a pointer ("&xxx"), which is needed now to be passed into the function.

**Comment by dneto0** [comment]
If we're looking forward to supporting variable-pointers, then even pointer-to-runtime-sized-array is not sufficient.

SPIR-V / Vulkan requires the pointer to the enclosing struct (and the index of the runtime-sized-array member).

The array length is a hidden field somewhere, or derived from other data.  Having only a runtime-sized array *value* isn't enough information even for baseline WGSL.
But having the pointer to the runtime array is sufficient for baseline WGSL, because an implementation can implement it in a couple of sensible ways:
-  e.g. think of it as "member -1" in the struct, i.e. stored before the first member, at offset -4 bytes. Then knowing the struct type we can load the word before the start of the struct.
- or it's derived from the total physical size of the buffer:     num_elements = (total_size - offset_of_last_member) / stride_of_the_runtime_array_type


> If I understand correctly, the restriction equally holds for the expression that takes a pointer ("&xxx"), which is needed now to be passed into the function.

There is no address-of operator.   The primitive type of a variable's identifier expression is pointer-to-its-storage. We are meant to delay dereferencing as long as possible until absolutely required to correctly type the program.  (A rule which hasn't been spec'd!)

Taking @dj2's example:

```
struct S {
  a : array<i32>;
}
[[group(0), set(0)]] var<storage> c : S;

fn vtx() -> void {
  var b : u32 = arrayLength(c.a);
}
```

The type of `c` is   `ptr<storage,S>`
The type of `c.a` is `ptr<storage,array<i32>>`   // ignoring lack of array stride

**Comment by dj2** [comment]
Maybe:

```
Precondition:
    e : ptr<stroage,array<E>>
Conclusion:
    arrayLength(e) : u32
```

is better stated as:

```
Precondition
   e : ptr<storage, array<E>> OR <some words to say the runtime array member of a struct
Conclustion:
  arrayLength(e) : u32
```

because the first way makes me think you can't pass in the struct member because it doesn't look like a pointer (unless you know that var is a pretend pointer)

**Comment by dneto0** [comment]
Agreed, I'm very much relying on stuff that hasn't been spec'd.

**Comment by dneto0** [comment]
Maybe the right thing is to have the parameter be the pointer-to-the struct.  Then in practice you'll always see just the buffer variable name.


```
struct S {
  a : array<i32>;
}
[[group(0), set(0)]] var<storage> c : S;

fn vtx() -> void {
  var b : u32 = arrayLength(c); //   provide the buffer variable name.
}
```


If we go this way, then we should change the name of the builtin function, e.g. to `bufferArrayLength`, e.g.:
```
Precondition:
    bufferArrayLength( e)
       e :  ptr<storage,S> and
       S is a structure type whose last element is a runtime-sized array
Conclusion:
     bufferArrayLength(e) : u32
Description:
    Evaluates to the number of elements in the runtime-sized array at the end of a storage buffer. 
    Only applies to buffers whose last element is a runtime-sized array.
```

**Comment by dj2** [comment]
That's a nice solution.

**Comment by kvark** [comment]
> There is no address-of operator. The primitive type of a variable's identifier expression is pointer-to-its-storage. We are meant to delay dereferencing as long as possible until absolutely required to correctly type the program. (A rule which hasn't been spec'd!)

Ok, then it's good. I wasn't sure what the user code would look like from this issue :)

> Maybe the right thing is to have the parameter be the pointer-to-the struct. Then in practice you'll always see just the buffer variable name.

I don't think it's the best. First, it's called `arrayLength` but takes a whole buffer as an argument, which is already a bit confusing. Secondly, it would prevent us to extend this function to non-dynamically-sized arrays. Being able to call `arrayLength(some_other_fixed_size_array)` in the future would be nice.

**Comment by jdashg** [comment]
Already done!
