### ISSUE TITLE
[wgsl] Consider using multiple scalars to construct matrix.

### ISSUE THREAD

**Issue by shaoboyan** [gpuweb/gpuweb#1342]
In current wgsl spec, the only way to construct a matrix is by providing vectors. 

But for [glsl](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Matrix_constructors), [hlsl](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-per-component-math#the-matrix-type) and [msl](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) (from metal 2.0), the matrix constructor also accpets multiple scalars.

Is it possible for wgsl to also have the matrix constructor which accpets multiple scalars?

**Comment by litherum** [comment]
+1

**Comment by dneto0** [comment]
Do you propose row major or column major?  If we add a builtin for this, the majorness should be mentioned in the name.

**Comment by dj2** [comment]
We only have one major-ness, so wouldn't it just be that one?

**Comment by shaoboyan** [comment]
I think column major constructor is my proposal. Because wgsl construct matrix column by column. And for glsl and msl, they all choose the scalar constructor the column major one.

**Comment by dneto0** [comment]
Approved the idea in [2021-01-19 meeting](https://docs.google.com/document/d/1xgCv1_xzo6kRmCfwOtnPd2j_T4unot71BOnlF-gOlIE/edit#heading=h.7x4nlgbz5r3s)

**Comment by dneto0** [comment]
This landed with https://github.com/gpuweb/gpuweb/pull/2305
