### ISSUE TITLE
Remove offset.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1349]
After the `span`, `offset` and `align` discussion I wonder if the right idea is to just remove offset.

# Proposal
We spec the alignment and span of each type that can be put in a buffer, this is partially done already with the `Alignment` table in the spec. So, we spec something along the lines of:

```
| type | align | span |
| vec2 | 8     | 8    |
| vec3 | 16    | 16   |
| vec4 | 16    | 16   |
| f32   | 4    | 4    |
| ... |
```

We can then, if desired, update the various compilers to dump out the offsets for a given struct to make matching up to the API side easier (would this be useful as a reflection API?)

# Future
If, in the future, we want packed types, we add a `[[packed]]` decoration to structs, at that point, all members of the struct would be tightly packed they'd all have a span of their exact type size (so vec3 spans 12) and there would be no padding injected between them.

**Comment by dneto0** [comment]
The 'span' concept above is in the spec today as 'Extent', except that Extent is dependent on the storage class (storage v.s. uniform).
The dependency matters for array and struct types.   We still have stride so that can be explicit: great.  The alignment of a struct ends up being nontrivially dependent (rounds up to 16).

**Comment by dneto0** [comment]
DXC's DX12 buffer layout rules are here, as far as understand:  https://github.com/microsoft/DirectXShaderCompiler/wiki/Buffer-Packing

**Comment by kvark** [comment]
This proposal is very similar to #1361. We should discuss it and/or figure out what the next steps are.

**Comment by kainino0x** [comment]
Superceded by #1393.
