### ISSUE TITLE
GPUVertexAttributeDescriptor.offset validation

### ISSUE THREAD

**Issue by andrewvarga** [gpuweb/gpuweb#1357]
I understand that there is a constraint according to the spec: `GPUVertexAttributeDescriptor.offset + sizeOf(format) <= arrayStride`.
https://gpuweb.github.io/gpuweb/#dom-gpuvertexattributedescriptor-offset

My question is why this constraint exists and how it could be worked around.
I'm building WebGPU support for [gltfeditor.com](https://gltfeditor.com) and among others there is a simple glTF model that looks like this:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Box/glTF/Box.gltf

Basically there are 2 bufferviews: one for the indexbuffer and one for the vertexbuffer, the latter being an interleaved array, but instead of having truly interleaved data like this: 
`normal1.x,y,z | pos1.x,y,z | normal2.x,y,z | etc...` 
the data looks like this (ie. all normal data first, then all position data after):
`normal1.x,y,zz | normal2.x,y,z | ... | pos1.x,y,z | pos2.x,y,z...`

you can see that the `byteOffset` property of the position accessor is therefore set to be `288` so that it starts after the normals (24 normals, each having 3 components, each component being 4 bytes -> 24 * 3 * 4 = 288).

In WebGL this is no problem, because `vertexAttribPointer` accepts 288 for its `offset` parameter, but `GPUVertexAttributeDescriptor.offset` doesn't.

What I can do in this case is detect that the given attributes are not really interleaved, break them up into 2 separate gpu buffers and then the offset validation will pass..but I wanted to see why this limitation is imposed and if there's anything else to consider here.

**Comment by kvark** [comment]
The restriction comes from Metal, last mentioned in https://github.com/gpuweb/gpuweb/issues/693#issuecomment-610984010 

What you have is not really "interleaved array". There is simply no interleaving. You have one array following another array, so it should be registered as such: the pipeline should expect separate vertex buffer bindings for positions and normals.

Now, that doesn't mean you have to have separate buffers. You can read it all in a single buffer, and just specify a different offset on binding:
```js
const vertexBuffer = device.createBuffer(...);
...
pass.setVertexBuffer(0, vertexBuffer, 0); //normals
pass.setVertexBuffer(1, vertexBuffer, 288); //positions
```

**Comment by kainino0x** [comment]
+1, that should be the way to do it. Closing for now but feel free to follow-up with any issues!

**Comment by andrewvarga** [comment]
Thank you, that makes sense!

**Comment by andrewvarga** [comment]
I have a follow-up question actually: it seems to me I can use `pass.setVertexBuffer`'s `offset` argument for interleaved arrays too instead of setting `GPUVertexAttributeDescriptor.offset` at pipeline creation time.
Is there any disadvantage to doing this, maybe performance wise?
If not, it looks redundant that it's possible to set the attribute offset in 2 different ways.

**Comment by kvark** [comment]
The `setVertexBuffer` offset applies to all attributes within the buffer. The `GPUVertexAttributeDescriptor.offset` applies to this attribute only, and it has to be within the stride. So it's not redundant as there is no way we could derive one from the set of others.

**Comment by andrewvarga** [comment]
What do you mean when you say "offset applies to all attributes within the buffer", doesn't it apply only to the given slot? In case of the example you gave earlier the same buffer is set for 2 slots with a different offset for each slot.

The same could be done for an interleaved array:
```
pass.setVertexBuffer(0, vertexBuffer, 0);  // normals
pass.setVertexBuffer(1, vertexBuffer, 12); // positions
// with a pipeline:
vertexBuffers: [
   {
      arrayStride: 24,
      attributes: [
         {
            shaderLocation: 0,
            format: "float3",
            offset: 0,
         },
         {
            shaderLocation: 1,
            format: "float3",
            offset: 0, // instead of 12
         },
     ]
  }
]
```

Does this not result in the same behaviour as this?
```
pass.setVertexBuffer(0, vertexBuffer, 0); // normals
pass.setVertexBuffer(1, vertexBuffer, 0); // positions
// with a pipeline:
vertexBuffers: [
   {
      arrayStride: 24,
      attributes: [
         {
            shaderLocation: 0,
            format: "float3",
            offset: 0
         },
         {
            shaderLocation: 1,
            format: "float3",
            offset: 12 // setting offset here instead of in the setVertexBuffer call
         },
     ]
  }
]
```

**Comment by kvark** [comment]
Looks like you are confusing the `shaderLocation` with vertex buffer layouts. The shader location is to match the shader, and nothing else.
For the interleaved layout, your could would look like this:
```js
pass.setVertexBuffer(0, vertexBuffer, 0); // normals and positions
// with a pipeline:
vertexBuffers: [
   {
      arrayStride: 24,
      attributes: [
         {
            shaderLocation: 0,
            format: "float3",
            offset: 0
         },
         {
            shaderLocation: 1,
            format: "float3",
            offset: 12,
         },
     ]
  }
]
```
For non-interleaved (like the ones you got from glTF), it would look like this:
```js
pass.setVertexBuffer(0, vertexBuffer, 0); // normals
pass.setVertexBuffer(0, vertexBuffer, 3 * 4 * normalCount); // positions
// with a pipeline:
vertexBuffers: [
   {
      arrayStride: 12,
      attributes: [
         {
            shaderLocation: 0,
            format: "float3",
            offset: 0
         },
      ],
   },
   {
      arrayStride: 12,
      attributes: [
         {
            shaderLocation: 0,
            format: "float3",
            offset: 0
         },
      ],
   },
]
```

**Comment by andrewvarga** [comment]
Ah yes, I thought the slot referred to `shaderLocation`, I see it's the index of the buffer in the pipeline's vertexBuffer definition. It makes sense now, thank you for explaining!
A small typo: I assume you meant to set slot = 1 in the second code block, like this:
```javascript
pass.setVertexBuffer(1, vertexBuffer, 3 * 4 * normalCount); // positions
```

**Comment by kvark** [comment]
Yes, thanks for pointing the typo! Edited the comment now.

**Comment by kainino0x** [comment]
I suspect this might produce the same behavior (though I still wouldn't call the two redundant):
```ts
pass.setVertexBuffer(0, vertexBuffer, 0); // normals
pass.setVertexBuffer(1, vertexBuffer, 12); // positions
// with a pipeline:
vertexBuffers: [
   {
      arrayStride: 24,
      attributes: [
         {
            shaderLocation: 0,
            format: "float3",
            offset: 0
         },
      ],
   },
   {
      arrayStride: 24,
      attributes: [
         {
            shaderLocation: 1,
            format: "float3",
            offset: 0
         },
      ],
   },
]
```
Not 100% sure it's valid. It definitely might have degraded performance on a lot of systems.

**Comment by andrewvarga** [comment]
@kainino0x that's a good point, thank you. It would make the renderer easier to implement by simply creating a buffer slot for each attribute, especially since glTF is very flexible in terms of the attributes it allows, but it doesn't seem complicated to properly detect and use interleaved arrays with a single slot, so I will go down that road, especially if there can be performance problems otherwise.
