### ISSUE TITLE
beginRenderPass should validate that the attachment don't alias

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1358]
Currently the specification allows using the same view for multiple attachments of a render pass. This seems like an issue, for example what does it mean if the same view is `loadValue: "load"` and `loadOp: [1.0, 0.0, 0.0, 1.0]`?

**Comment by kvark** [comment]
This is actually covered formally right now:
> 1. The [=texture subresource=] seen by |colorAttachment|.{{GPURenderPassColorAttachmentDescriptor/attachment}}
                        is considered to be used as [=internal usage/attachment=] for the
                        duration of the render pass.

Then:
> During command encoding, every usage of a subresource is recorded in one of the
[=usage scopes=] in the command buffer.
For each [=usage scope=], the implementation performs
<dfn dfn>usage scope validation</dfn> by composing the list of all
[=internal usage=] flags of each [=subresource=] used in the [=usage scope=].
If any of those lists is not a [=compatible usage list=],
{{GPUCommandEncoder/finish()|GPUCommandEncoder.finish()}}
generates a {{GPUValidationError}} in the current error scope.

And finally in the compatible usage lists:
> - |U| contains exactly one element: [=internal usage/attachment=].

However, I do believe that we should state that clearly in `beginRenderPass`. Better be redundant than confusing :)

**Comment by Kangz** [comment]
Wow that's quite deep indeed. I always considered `U` as a set so the duplicate `attachment`s would be a single one. Yeah it would be good to call it out.
