### ISSUE TITLE
Question: shall we set default values for parameters of descriptors

### ISSUE THREAD

**Issue by Richard-Yunchao** [gpuweb/gpuweb#136]
You know, there are a lot of states/descriptors in WebGPU, especially for render pass and render pipeline. I don't know whether you have discussed that whether we will set default values for these descriptors. But I didn't find any statement about the consensus for this question from WebGPU community. 

Actually there might be two questions: 
1. Shall we set default values for parameters of descriptors in WebGPU? 
2. If the answer is "Yes", shall we do this in MVP? If the answer is "No", shall we report an error if developers don't set values for any states/descriptors?  

AFAIK, D3D12 and Metal have default values for many states/descriptors. Vulkan doesn't have default values for most states.

**Comment by Richard-Yunchao** [comment]
@Kangz , @kainino0x , @kvark , @RafaelCintron , @litherum, WDYT?

**Comment by Kangz** [comment]
I think we should have defaults and in general strive to have them be either the value most people are going to use, or the values that are the most performant (e.g. disabling stencil writes by default).

That said there's also a number of places where defaults don't make sense, such as WebGPUBinding bindingType because we really want developers to not forget to set (and think) about the value. So it's a bit of a case-by-case basis.

**Comment by kvark** [comment]
I'd say the criterion for a default is that it should carry **minimal information**. Say, we are talking about backface culling:
  - "most people are going to use" -> CULL_BACK
  - "most performant" -> CULL_FRONT_AND_BACK :P
  - "minimal information" -> CULL_NONE

Never mind the fact that we don't have `CULL_FRONT_AND_BACK`, it's just an example to show how the criteria can be conflicting.

A more realistic example - for the depth states:
  - "most people are going to use" -> LESS_EQUAL test + write
  - "most performant" -> NEVER
  - "minimal information" -> ALWAYS, no write

So with this criterion agreed upon, I'm totally for default states, with the exception of things that just don't make sense as defaults (e.g. the binding type that @Kangz brought up).

**Comment by Richard-Yunchao** [comment]
Thanks for your feedback, @Kangz and @kvark . So you agreed that we need default values if the default values make sense for that state/descriptor. However, we might need a criterion: minimal information, or most performant, or most people are going to use. Dzmitry voted for **minimal information**. 

I'd like to hear thoughts from other guys on this. At the same time, maybe we can have more investigations about default values for concrete descriptors we have already had and then discuss the criterion at weekly meeting later.

**Comment by litherum** [comment]
I don’t quite understand what @kvark is saying about “minimal information.”

If we add new descriptors to these objects in a v2 of the API, the new default values will have to be consistent with how people are already using the API (so existing code doesn’t break). It would be unfortunate for new defaults and old defaults to work differently in this regard.

We also don’t want this API to be difficult to use. An author shouldn’t have to fill out a ton of forms just to get a single triangle on the screen.

**Comment by kvark** [comment]
> If we add new descriptors to these objects in a v2 of the API, the new default values will have to be consistent with how people are already using the API (so existing code doesn’t break).

I agree, and that's a downside of bottom-up approach to building the API (while preserving backward compatibility) versus top-down.

>We also don’t want this API to be difficult to use. An author shouldn’t have to fill out a ton of forms just to get a single triangle on the screen.

I agree that it's nice to reduce the boilerplate written by the authors, but I strongly believe this should be the *least* of our priorities when building the API. It's better to have an API you can reason about by reading the source than one that mostly magically works.

**Comment by kvark** [comment]
Here is a bit of investigation on what the underlying native API consider to be defaults for `CullMode`:
  - Vulkan is a C API, so structures can be initialized to zero, i.e. `VkPipelineRasterizationStateCreateInfo rasterState = {};`. This corresponds to `CullMode::none`.
  - D3D12 is a C++ COM API, although structures passed in object creation are [regular C structures](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_rasterizer_desc), which can be initialized to zero, i.e. `D3D12_RASTERIZER_DESC rasterDesc = {};`. This corresponds to `CullMode::none`.
  - Metal is an ObjC/Swift API with "The default value is MTLCullMode.none"

We can see how all the native APIs agree on the default value here, and it's most closely aligned with "minimal information" criterion I described earlier.

**Comment by magcius** [comment]
"Minimal information" makes the most sense to me. When reading code, I do not want to have to go look up the defaults for different fields like I have to do for OpenGL (which are sometimes surprisingly hard to find). D3D11, for instance, uses LEQUAL depth test mode by default, which was widely considered an API mistake.

**Comment by Kangz** [comment]
Closing. We added a lot of default to descriptors and additional requests for defaults (or removal / change of defaults) can go in new issues.
