### ISSUE TITLE
Reconsider GPULoadOp "clear"/"zero"

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1377]
It was decided in #283 not to duplicate the functionality of `loadValue: [0, 0, 0, 0]` with a `loadValue: "zero"` or similar.

However, in the time since then, I've seen numerous users trip up on this, using `loadValue: "load"` when it's not necessary, because doing the simpler thing seems like it should be the "better" thing.
Of course, [EDIT: **if** in the same command buffer or on a late-recording implementation] `loadValue: "load"` gets replaced with `loadValue: [0, 0, 0, 0]` if the render target happened to be in an uninitialized state before the render pass, so in many cases it's not actually a pessimization. But I think we should make the "fast" option more accessible.

**Comment by magcius** [comment]
It might be worth supporting fast-clears? Usually, you can register a special clear value with the texture / resource when it is created, and then you clear to that. Perhaps you can set the clear color in the texture description upon creation, and then say `loadValue: "clear"`. For many cases, clear values are known up-front, so that would be the best (and fastest!) approach.

**Comment by kainino0x** [comment]
I know we discussed this a few times in the past (could dig it up). I seem to recall someone (likely the D3D team?) told us that hardware that needs that optimization (older AMD maybe?) is going away, making dynamic clear values just as good.

**Comment by Kangz** [comment]
Yes feedback from the D3D team was very clear that fast-clear values are not a valuable thing to have in the API. It's useful only for one old architecture and confuses everyone.

**Comment by magcius** [comment]
Huh, bizarre. The GPU architectures I have worked with really liked fast-clears. If the clear value was in one of the specific clear values (usually in a global table somewhere), then framebuffer compression could take care of the rest, and it was effectively a free clear, saving on a bunch of memory bandwidth. Maybe it's possible for the runtime / driver to do this clear value tracking now, or maybe framebuffer compression just stores a complete clear value for the full surface and there's no need to pre-register now.

I'd be interested to hear what the D3D team has to say. I do somewhat like the ergonomics of `"clear"` as a string value.

**Comment by jdashg** [comment]
So the proposal is to add `loadOp: "clear"` which is shorthand for `loadOp: [0,0,0,0]`?

**Comment by kainino0x** [comment]
> So the proposal is to add `loadOp: "clear"` which is shorthand for `loadOp: [0,0,0,0]`?

Yes, `loadValue: "clear"` (or `loadValue: "zero"` if we want to be more precise about what it's clearing to - we could add `loadValue: "clear"` later if we somehow ended up with a fixed-fast-clear feature).

**Comment by kvark** [comment]
Mmm, `loadValue: "zero"` actually sounds fine. At least there is no confusion about "what does it clear to?"

**Comment by kainino0x** [comment]
I also prefer `"zero"`.

**Comment by Kangz** [comment]
I think the consensus in the meeting was to put this off for later?

**Comment by kainino0x** [comment]
Discussed in https://github.com/gpuweb/gpuweb/wiki/Minutes-2021-02-08

**Comment by kainino0x** [comment]
> Of course, `loadValue: "load"` gets replaced with `loadValue: [0, 0, 0, 0]` if the render target happened to be in an uninitialized state before the render pass, so in many cases it's not actually a pessimization.

Note: Actually for implementations using ahead-of-time recording of the backend command buffer (wgpu), I think this is only true if it is _locally_ known (within the command buffer) to be in an uninitialized state. Otherwise you can't know until submit time.
