### ISSUE TITLE
Support boolean varyings

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1379]
Spawned from #1246

The grammar of WGSL already allows booleans on in/out storage classes, since there are built-ins we have to support. This issue is about supporting booleans for user varyings as well:
```rust
var<out> myBoolOut: bool;
var<in> myBoolIn: bool;
```

Implementation-wise, it requires a bit of plumbing on SPIR-V side. The booleans on in/out need to be replaced by integers, since SPIR-V doesn't like user varyings there.

**Comment by kdashg** [comment]
I believe this is the same as #1268?
