### ISSUE TITLE
Define how .5 rounds when using the `round` method.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1381]
Currently we've spec'd `round` as converting to `GLSLstd450Round` which leaves the rounding of .5 implementation defined. I think we should change this to `GLSLstd450RoundEven` which states `A fractional part of 0.5 will round toward the nearest even whole number`.

This would then match the `round` method in HLSL which states: `Halfway cases are rounded to the nearest even.`. 

This would mean using `rint` in MSL instead of `round`:  `using round to nearest even rounding mode in floating-point format`

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-02-02-Minutes#define-how-5-rounds-when-using-the-round-method--issue-1381--gpuwebgpuweb">WGSL meeting minutes 2021-02-02</a></summary>

*   JG: General proposal to round even
*   RM: Looks reasonable. See that it requires a different OPCode in Metal, would like some perf testing; don’t expect any kind of issue just want to make sure there are no surprises
*   MM: Can we do that asynchronously.
*   JG: Propose we take the RoundEven functionality and we find later we revisit.
*   RM: Agree with that
*   MM: Metal has multiple rounding with different behaviour?
*   JG: Covered by top comment
*   DS: SPIR-V Round and RoundEvent, MSL rint and round, HLSL round (as round even)
*   MM: Could do it in software, but go with the simple option of RoundEven and can come back later if needed.
*   JG: Works for me. Needs spec.
</details>
