### ISSUE TITLE
WGSL type rules need to say something about aliases, and about attributes

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1387]
The "Type Aliases" section needs to be expanded. 

For example:
* A type alias introduces a name for the type on the right hand side.
* They are different spellings for the _same type_.   (Like `using` in C++ if I have that right)
* Therefore the LHS and the RHS of the type alias declaration are interchangeable for a type variable in a type rule.

About attributes on types:
* We may have cases where an attribute on a type is ignored for the purposes of certain type rules.  We would have to spell this out.
    * Example: We have agreed that the `stride` attribute on an array type only takes effect when the array is in host-shareable memory. This has to be formalized.

Example combining the two.   Some of us are discussing allowing a `size` or `align` attribute for primitive types like `i32`, e.g. 

```rust
type my_i32 = [[align(16)]] i32;
struct Inner { ba: f32; bb: f32; };
type aligned_inner = [[align(32)]] Inner;  
[[block]] struct S {
    a : my_i32;   // gets the align(16) property.
    b : aligned_inner; // gets the align(32) property.
};
[[group(0), binding(0)]] var<storage> buf: S;
```
Then when loading an S.a value from a storage buffer, the align property is either dropped or ignored for later operations.
```rust
fn main() -> void {
   const sum : i32 = buf.a + buf.a;  // need to be able to apply `+` over i32.

   // store type is aligned_inner.  What does the layout mean in Function storage? Is this ok?
   var loadedstruct: aligned_inner = buf.b; 
}
```
What justifies the ability to do the integer sum? 

- One option is to we drop the layout attributes upon loading. 
    - This natural for numeric types.  
    - But what if we loaded an entire sub-structure, for the `loadedstruct` variable.  We would want to reuse the same structure to define the buffer, but also to declare function-scope variables.
- Another option is to say we ignore layout attributes in certain contexts, e.g. for arithmetic matching.
- Or a hybrid:  use option 1 for scalars, vectors, matrices;   use option 2 for arrays and structs

**Comment by kdashg** [comment]
https://www.w3.org/TR/WGSL/#type-aliases
