### ISSUE TITLE
Enforce calling GPUSwapChain.getCurrentTexture() should return the same binding within same event callback

### ISSUE THREAD

**Issue by juj** [gpuweb/gpuweb#1388]
When implementing WebGPU bindings to Wasm, it is awkward to deal with needing to release references to JS objects from Wasm side. The special GPUTexture returned by `GPUSwapChain.getCurrentTexture()` makes reference management more complex, as the bindings layer must recognize that after the callback is over, the GPUTexture is invalid, and it should drop references to it.

An application might call `GPUSwapChain.getCurrentTexture()` two or more times inside a callback. In current implementation in Chrome, each call returns a new binding object to the GPUTexture, which causes a JS<->Wasm binding library to treat each call as a new/independent texture when in actuality they are bindings to the same swap chain texture for that particular frame. Then a number of odd corner cases can ensue. E.g. if user then calls `.destroy()` on one of these textures, it would invalidate the swap chain texture for that frame, but in JS<->Wasm bindings, the other texture binding would still exist and not be aware of that.

To avoid corner cases, if the spec could enforce that if one calls `GPUSwapChain.getCurrentTexture()` multiple times within a single callback, the same binding object should be returned; then a WebGPU JS<->Wasm binding layer would be able to assign a `.id` field to this texture to recognize it during the frame, and subsequent calls would identify and refcount the same texture. I.e. something like

```js
var t = myGpuSwapChain.getCurrentTexture();
if (!t.id) t.id = getNewId();
// ... later in the same callback
var t2 = myGpuSwapChain.getCurrentTexture();
if (!t2.id) t2.id = getNewId(); // Would not trigger, as we already had assigned an .id member to the swap chain texture for this frame, and will use the same binding slot.
```

After the callback exits, the binding object would be free to change to represent a new frame/new texture, and a JS<->Wasm binding layer would generate a new id for the next frame.

Would this be a reasonable invariant to enforce?

**Comment by kainino0x** [comment]
I do think this would make sense. However, I don't think there are actually ergonomic issues with returning a new texture for each getCurrentTexture call.

> E.g. if user then calls `.destroy()` on one of these textures, it would invalidate the swap chain texture for that frame, but in JS<->Wasm bindings, the other texture binding would still exist and not be aware of that.

This actually shouldn't be the case. If each getCurrentTexture call returns a new GPUTexture, then they should actually behave like totally independent textures, i.e. each one can be destroyed separately. If that's not the case in Chrome, it's a Chrome bug.

Of course, .destroy() on a swap chain texture should be unusual to begin with, as it doesn't really do anything. `destroy()` is supposed to free the GPU resource (which is impossible for a swap chain texture) and have no effect on CPU-side object allocations or cross references (which in JS are entirely handled by GC).

I'm not even sure we should allow `destroy()` on swap chain textures - maybe it should throw an exception, at least for now. It could perhaps signal to the browser that rendering is done early... but that's only possible if we return the same GPUTexture object with each getCurrentTexture call.

**Comment by Kangz** [comment]
I'm pretty sure the intent of the specification was that the same `GPUTexture` would be returned between two "update the rendering [of the] Document" of the HTML spec. (basically the current one would be invalidated at the end of RAF). This is pretty clear from the name "getCurrentTexture", you're getting the one that's current now, and not a new `GPUTexture`. This should be clarified in the specification and if Chromium isn't up to spec it should be fixed (although I thought it had the correct behavior? weird).

It's kinda nice to keep `destroy()` because it doesn't cost anything and doesn't require special casing swapchain textures but that's less important imho.

**Comment by toji** [comment]
It would be very surprising to me as a developer if `getCurrentTexture()` returned two different textures within the same callback. That's not what I would expect based on the name nor everything I know about swap chains. The exception would be if we had added an explicit `swap()` call, at which point I would expect the "current" texture to change after that call.

Additionally, in the case of rAF calls, I would probably expect that the same texture is returned for every callback processed as part of the same frame.

Thinking about this from a tooling point of view, I can imagine developers wanting to build tools that are as independent as possible from the rest of the app. Simple example: An FPS counter. If the swap chain returns the same texture within a single call then I can stack a bunch of "overlays" like that on top of my render loop and they don't even need to be explicitly called as frame loop. They can install their own callbacks and run in isolated loops and the only thing they need to share is the swap chain object (and probably canvas).

**Comment by juj** [comment]
> I'm pretty sure the intent of the specification was that the same `GPUTexture` would be returned between two "update the rendering [of the] Document" of the HTML spec. (basically the current one would be invalidated at the end of RAF). This is pretty clear from the name "getCurrentTexture", you're getting the one that's current now, and not a new `GPUTexture`. This should be clarified in the specification and if Chromium isn't up to spec it should be fixed (although I thought it had the correct behavior? weird).

Right - the question is not only about what the current impl is, but also what does the spec guarantee to us that should happen. (behavior enforced via unit tests?) Sounds all good that the thinking is along the same lines from everyone.

> That's not what I would expect based on the name nor everything I know about swap chains.

Actually, about that.. I thought I knew about swap chains, so I assumed that if I call `getCurrentTexture()` in three subsequent rAFs, and the third call returns the same value as the first call, then I am double-buffering; and if I call `getCurrentTexture()` in four subsequent rAFs, and the fourth call returns the same values as the first call, then I am triple-buffering. But @kainino0x pointed out that there are no facilities to control swap chain length, nor to choose double vs triple buffering, but it is up to the implementation. The spec in `getCurrentTexture()` is intended to show up like "infinite buffering", i.e. on subsequent rAFs, one will always get a different texture binding than all previous calls (and no way to distinguish what the GPU resource that is pointed to is)

That does not sound like a swap chain. There is no texture chain like in native APIs, and there's also no functionality to do any swapping, so `GPUSwapChain` is more like a `GPUSwapChainButDoesNotSwapAndNotAChain` :)

Although that does not really matter for me, I am just being cheeky here. On that note though, I would love access to control double vs triple buffering, as there are distinct Tekken-low-latency vs most-FPS+smoothest-rendering groups out there.

**Comment by Kangz** [comment]
Agreed that `GPUSwapChain` isn't exactly like the native swapchains but it's close enough to the same concept that I don't think we should bother bikeshedding the perfect name for it (if there's one).

I think you should be able to control double vs. triple (or more in browsers) buffering with things like <canvas> `desynchronized: true`.

**Comment by kainino0x** [comment]
I'm going to say this "Needs Specification" to make sure the same GPUTexture object reference is always returned in the same frame (note: not just in the same callback)
