### ISSUE TITLE
Require [[block]] on nested structures in WGSL

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1398]
Let's talk about this code:
```rust
struct Particle {
  [[offset(0)]] pos: vec2<f32>;
  [[offset(8)]] vel: vec2<f32>;
};

[[block]]
struct ParticleBuf {
  [[offset(0)]] particles: array<Particle>;
};

[[group(0), binding(1)]]
var<storage> buf: [[read]] ParticleBuf;
```

Question: what does the `[[block]]` mean there, and why do we need it?

The original intention for the `[[block]]`, if I understand correctly, was to match the "Block" decoration in SPIR-V. However, that's not what the shader writer is interested in (and in fact it can be figured out by looking at the global variable declaration).

From the shader writer view, the `[[block]]` would make sense if it would be a heads up to the compiler that this structure is host-shareable. This means, it has to have the offset decorations (defined layout). I.e. it would make sense as a declaration of intent "I want to use this in host-shared buffers". From this point of view, we should be enforcing it on `struct Particle` in the example above, but currently the spec doesn't do that.

Also note that this would be naturally solved by #1361

**Comment by litherum** [comment]
+1

+100000000

**Comment by dneto0** [comment]
The WGSL spec currently says:

> Attribute block ...
Applies to a structure type.
Indicates this structure type represents the contents of a buffer resource occupying a single binding slot in the shader’s resource interface. The block attribute must be applied to a structure type used as the store type of a uniform buffer or storage buffer variable.

And later (links and bold not copied here....):

> A variable in the uniform storage class is a uniform buffer variable. Its store type must be a host-shareable structure type with block attribute, satisfying the uniform buffer layout rules.

> A variable in the storage storage class is a storage buffer variable. Its store type must be a host-shareable structure type with block attribute, satisfying the storage buffer layout rules.

I had hoped that was fully specified.  If not, then I would appreciate feedback or a PR to fix that.


Now about what it means.
It does not mean "this thing needs layout".   It's more specific than that.

It's forward looking:   WGSL will soon have to express arrays of buffers (e.g. for bindless style). And we need a way to indicate at what level you are indexing over descriptors vs. what level reaches within the buffer in a single descriptor.
There are differing constraints about uniformity, for example.  (Basic functionality is that indexing over descriptors must be uniform, but that's not so within a block.)

**Comment by kvark** [comment]
@dneto0 thank you for explaining!
I want to clarify that I do see `[[block]]` specified in WGSL, I'm not saying that there is anything wrong with the spec per se. I'm saying that this construct, conceptually, isn't useful to either users or the implementations.
So until we have a case for it (like the bindless logic you mentioned), we should probably just remove it from the spec.

**Comment by dneto0** [comment]
> we should probably just remove it from the spec.

To avoid special cases in the future, I'd like to see a proposal for how bindless would look in a post-V1 world.

**Comment by kvark** [comment]
The action item from the last call was on @dneto0 to provide more insight into why `[[block]]` is going to be needed in the future, and why it could be beneficial to have it right now (as opposed to introducing when we need it).

**Comment by kvark** [comment]
Related to #1008
