### ISSUE TITLE
`MissingBlockDecoration` in a glsl shader. What does that mean?

### ISSUE THREAD

**Issue by nikitablack** [gpuweb/gpuweb#1401]
I have the following shader:
```
#version 450

struct Vertex
{
    vec4 pos;
};

layout(std430, set = 0, binding = 0) readonly buffer VertexBuffer
{
    Vertex data[];
} vertexBuffer;

void main(){
    Vertex v = vertexBuffer.data[gl_VertexIndex];
    gl_Position = v.pos;
}
```
I compiled it with `shaderc` as well as with `glslangValidator`. It compiles without errors but at runtime, I receive a validation error in `device.create_shader_module(&wgpu::include_spirv!("../shaders/shader.vert.spv"));`:
```
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `../shaders/shader.vert.spv`
    Type Handle(4) 'Vertex' is invalid: MissingBlockDecoration
```

I do not understand what does that means, where this validation error comes from (this is definitely not from a Vulkan Validation Layer) and which decoration should I apply, and where.

**Comment by Kangz** [comment]
This is a wgpu-specific error, WebGPU (the standard as opposed to the library) doesn't support GLSL or SPIRV.

Closing this, can you open it on wgpu-rs or related repository instead?
