### ISSUE TITLE
pr-preview doesn't run for WGSL spec PRs

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#1405]

**Comment by jdashg** [comment]
Upstream I think this is https://github.com/tobie/pr-preview/issues/18

**Comment by kainino0x** [comment]
That's the correct issue.

Thanks to @mehmetoguzderin we already have infrastructure in place to preview the WGSL spec. Unfortunately, despite using a recipe from a Firebase official source, we're running into quota issues that I don't understand. (You can see this here: https://github.com/gpuweb/gpuweb/actions/runs/531894462)

**Comment by kainino0x** [comment]
I spoke with the Firebase engineer responsible for the recipe a while back; it should have been fixed, but we're still seeing the problem.

**Comment by Kangz** [comment]
Is this fixed?
