### ISSUE TITLE
WGSL: limit types that can go into arrays and structs

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1409]
We don't want a pointer, texture, or sampler to exist in a structure or array.  (In the future we'll want arrays of textures.)

Currently that's not captured.

Because of the recursive nature of these types, we can't just define a new class of types similar to host-shareable or IO-shareable. That would introduce circularity.

**Comment by kvark** [comment]
> Because of the recursive nature of these types, we can't just define a new class of types similar to host-shareable or IO-shareable. That would introduce circularity.

Could you elaborate on this, please?
