### ISSUE TITLE
call_statement: should only be able to call a function that yields void?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1413]
That can catch some programming errors.

If you really want to call a value-producing function at statement level, only for its side effects, then you can always capture its result in a const-declaration.

      const toss_it: T = CallForSideEffects();

Or 

      const _ := CallForSideEffects();  // if we have type deduction

      _  := CallForSideEffects();  // even more aggressive throwaway with type deduction
 
      // Invent a void-constructor  explicitly for this purpose. 
      // It's a sink for values, producing void.
      void(CallForSideEffects());

**Comment by dneto0** [comment]
#1412  is a somewhat related grammar change.

**Comment by kvark** [comment]
Played with this in Naga, and I'm strongly in favor of this. 🚀

**Comment by dneto0** [comment]
I propose adding a void constructor builtin function:

        void(sink:T) -> void;

A call to the `void` function can appear as a statement in a function body. It evaluates its argument, and yields no value.

**Comment by kvark** [comment]
Let's not mix this into the `void(sink)` suggestion, please file it separately?
I don't see why it's needed. Users can always just declare a constant to get a result of anything.

**Comment by ben-clayton** [comment]
> I don't see why it's needed. Users can always just declare a constant to get a result of anything.

It's not uncommon to have compilers warn about unused variables. `(void) expr` is the typical way to tell a C++ compiler that an expression is intentionally unused.

**Comment by kvark** [comment]
Ok, we can add `void(sink:T)` once we agree on the warnings. It doesn't require `void` type anyway.

Btw, since https://github.com/gpuweb/gpuweb/issues/1413#issuecomment-774409478 was written I've remade the support for function calling in Naga, and now this proposal doesn't give us anything at all. We are now totally cool to support:
```
my_function();
```

**Comment by dneto0** [comment]
> Let's not mix this into the void(sink) suggestion, please file it separately?

I filed #1499 for the void constructor idea.

**Comment by dneto0** [comment]
Discussed [2021-03-09](https://docs.google.com/document/d/1IQLS_nypwJLjaMZlejMSMC_vP7D2pm0EH1NtZ1TIvs0/edit#heading=h.a0fpht4tpxjd)

**Comment by dneto0** [comment]
Hey @jdashg you marked this as resolved-needs spec.  But reading the notes, I'm not clear there was consensus to make this an error.  I don't know what the consensus is.

**Comment by kvark** [comment]
I read the consensus as:
  - don't allow the statement calls into functions with return types
  - follow-up with the `ignore` function at some point

**Comment by kdashg** [comment]
I think this is closed by #2138.
