### ISSUE TITLE
How to convert mat3(mvi) in GLSL into WGSL? 

### ISSUE THREAD

**Issue by jack1232** [gpuweb/gpuweb#1417]
I have the following GLSL code in the fragment shader when doing lighting:

mat4 mvi = transpose(inverse(modelViewMatrix));
vec3 my_normal = mat3(mvi) * normal;

How to convert  this code into WGSL code?

**Comment by kvark** [comment]
Note that there isn't any `inverse` today - https://gpuweb.github.io/gpuweb/wgsl.html#matrix-builtin-functions

**Comment by kainino0x** [comment]
Consider uploading the inverse matrix separately. Converting the inverse in-shader is costly and unnecessarily happens once in every shader invocation.
