### ISSUE TITLE
Are values in GPUVertexAttribute.shaderLocation arbitrary?

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1418]
When creating a render pipelines, can the `shaderLocation` of the attributes be arbitrary or should they be in `[0, maxVertexAttributes)`? Right now in the specification they are arbitrary but we should make sure this is an conscious choice.

**Comment by kainino0x** [comment]
Are there constraints in the backend apis? Or is repacking possible?

**Comment by Kangz** [comment]
Repacking is always possible. I'm not sure for D3D12 but both Metal and Vulkan constrain the value: it has to be one of the "vertex buffer" (uniform / ssbo / vertex combined table) so less than 32 in Metal, and less then `maxVertexAttributes` in Vulkan.

**Comment by kvark** [comment]
Relevant VU:
> VUID-VkVertexInputAttributeDescription-location-00620
location must be less than VkPhysicalDeviceLimits::maxVertexInputAttributes

Since we want to be able to generate SPIR-V at shader module time, we don't have the luxury of remapping the locations.

I suggest we enforce the same constraint in WebGPU.

**Comment by Kangz** [comment]
> Since we want to be able to generate SPIR-V at shader module time, we don't have the luxury of remapping the locations.

That doesn't have to be a hard constraint but also you can easily remap in the shadermodule and use that remapping in the creation of VkRenderPipeline.

**Comment by kvark** [comment]
You can remap the shader module only if you require that each VS output has to have a corresponding FS input. Do we require this? IIRC only DX12 needs this, for we are going to need to patch it at pipelinecreation anyway, so we can insert the missing input locations at that stage, as an implementation detail.

**Comment by kainino0x** [comment]
This issue is about VS inputs, what do VS outputs have to do with it? Do they share a numbering namespace?

**Comment by Kangz** [comment]
As usual, I think we might want to start restricted (to `maxVertexAttributes`) and later allow arbitrary numbers if people ask for it. I doubt they will given it's already a constraint in other APIs. I'll make a PR for that unless you have strong concerns.

**Comment by litherum** [comment]
Thinking about this, I'm not actually sure that repacking vertex inputs is always possible, because the set of inputs in the vertex shader might not exactly match the set of vertex inputs in the pipeline state. (Unless we added a rule that said they always had to exactly match...)

**Comment by litherum** [comment]
If we do repacking, what about a program that is something like
```
encoder.setVertexBuffer(3, myVertexBuffer, ...);
encoder.setPipeline(myPipeline1);
encoder.draw(...);
encoder.setPipeline(myPipeline2);
encoder.draw(...);
```
If we do vertex attribute repacking, presumably the `setPipeline()` calls will internally have to issue a collection of `setVertexBuffer()` calls inside them, because index 3 might map to a differently mapped index for those two pipelines.

**Comment by kvark** [comment]
We aren't going to be re-packing the vertex *buffer* indices, but only the attribute locations. All the data bound in this `encoder.setVertexBuffer(3, myVertexBuffer, ...);` will be equally valid with or without re-packing. What the re-packing would change is how the shader communicates with the pipeline, internally, without affecting anything the user can see.

**Comment by kainino0x** [comment]
Right, repacking vertex buffer indices would require repacking in encoders, while repacking vertex attribute locations requires repacking in createRenderPipeline.

Regardless, unless there are objections, we can resolve not to do any repacking yet, and it's unlikely we will need to add it in the future.

**Comment by Kangz** [comment]
The spec change has already landed, closing.

**Comment by kainino0x** [comment]
For the record it was #1423
