### ISSUE TITLE
getCurrentTexture has side effects but doesn't sound like it

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1424]
> I would argue that there's not much point to calling `getCurrentTexture()` unless you're planning on rendering, so that seems like a perfect, low-impact point at which to flag that the canvas has been invalidated.

> +1, I completely agree that getCurrentTexture in a new frame should be what clears the canvas.

The name "getCurrentTexture()" implies to any reader a const/immutable and idempotent function. If this starts to have active logic tied to it, the name would be good to change? Maybe `acquireNextTexture()` or something similar? Having a "getter" that has active behavior is brittle.

The reasoning that there is no much point to calling `getCurrentTexture()` unless you're planning on rendering does make sense, but as projects grow more complex, as does logic, and given the innocent name, people can think "well there's no harm calling that getter function when I'm not rendering, since it oughta be fast anyway", and do not realize they need to optimize away calls to it to keep the previous frame visible.

_Originally posted by @juj in https://github.com/gpuweb/gpuweb/pull/1408#discussion_r571708439_

**Comment by kainino0x** [comment]
Talked about this in the editors meeting, we're going to propose to the group replacing `getCurrentTexture()` with an `acquireNextTexture()` which can only be called once per frame (throws error if called again in the same frame).

Thinking about it a little more now, we need to think about whether it could end up being fragile. E.g. rendering is done off mouse events instead of rAF, and you get more than one mouse event in a frame (it can happen!)

Some old minutes links
[2019-02-04](https://docs.google.com/document/d/1HXmaPNE7zzp-mzjbZRHLz_sXjpwS78IYovqNLGaS_wY/edit#heading=h.dpg974h3hno4) talking about getNextTexture+present -> getCurrentTexture
[2019-05-16 F2F Mountain View](https://docs.google.com/document/d/1HR9vPk48-lhzHAsyF57QzjKMmi0gQHfSXMmyqZuFWkc/edit#heading=h.3sus85csnbov) talking about imagebitmap swap chain
I thought we discussed in San Diego (misspoke as Seattle) but doesn't appear so.

**Comment by toji** [comment]
The mouse event thing is a good point. In theory the behavior should be fairly predictable but I think that for many users it'll feel pretty black-box whether or not input events happen prior to frame callbacks, etc.

Maybe we can keep the current behavior but make the name something like `acquireCurrentTexture()` or `aquireFrameTexture()` so that we don't imply that we're incrementing the texture each time?

**Comment by kainino0x** [comment]
acquireCurrentTexture with current semantics would be fine with me

**Comment by juj** [comment]
> acquireCurrentTexture with current semantics would be fine with me

`acquireCurrentTexture` sounds fine to me as well + the docs for that function will have a paragraph explaining the active swap behavior in detail?

**Comment by Kangz** [comment]
I have concerns about `acquireCurrentTexture`, that sounds a lot like C++ move semantics where you can only acquire a thing once (before a new one is produced). IMHO the `current` in `getCurrentTexture` makes it clear that the texture you get changes overtime.

**Comment by kvark** [comment]
I'm not seeing this strongly related to C++ semantics. We have things that can only be done once at a time. Say, buffer mapping. This isn't any weirder, and it makes the act of acquiring the image explicit, which is a big plus.

**Comment by kainino0x** [comment]
With a rename I think we should keep the current semantics: you can get it more than once in a frame, and it returns the same object, but the first time you get it it ALSO invalidates the canvas. And I feel that acquireCurrentTexture is an okay name for that even though it can be called multiple times in a frame. Hard to come up with something more precise that doesn't make it sound like it clears every frame ('clearAndGetCurrentTexture', 'invalidateAndGetCurrentTexture').

**Comment by Kangz** [comment]
Changing the semantics so that it is an only once operation would be a bit unfortunate IMHO because of the mouseevent thing that Kai mentioned. If we keep the current semantics I don't see the value in changing the names. Both are slightly imprecise and it feel like churning names gratuitously.

`getCurrentTexture` would be a much better name if we had explicit present, but that's not the case at the moment.

**Comment by juj** [comment]
+1 for explicit present.

**Comment by Kangz** [comment]
> +1 for explicit present.

That boat has sailed unfortunately. Except maybe for OffscreenCanvas.

**Comment by juj** [comment]
> That boat has sailed unfortunately. Except maybe for OffscreenCanvas.

Sorry. I have advocated for an explicit present close to a decade now. I do not accept the argument that "if you had raised this earlier, maybe it could have happened". There are probably valid reasons why it did not happen, but this is not one of them.

**Comment by juj** [comment]
OffscreenCanvas briefly had an explicit commit (which got somehow turned into a synchronous commit), but it was retroactively removed. (also communication around OffscreenCanvas spec state got into somehow odd "Chrome: it is stable and done and shipped" vs "Firefox: there is no final spec yet" mixed signal state.) The .commit() function still lives in the spec (search for "commit" in https://html.spec.whatwg.org/multipage/canvas.html#the-offscreencanvas-interface), but last when I asked Chrome about this maybe a year ago(?), they said the spec is out of date. Weird. (some discussion on .commit() here https://github.com/w3ctag/design-reviews/issues/288 )

**Comment by Kangz** [comment]
> Sorry. I have advocated for an explicit present close to a decade now. I do not accept the argument that "if you had raised this earlier, maybe it could have happened". There are probably valid reasons why it did not happen, but this is not one of them.

That's not the reason, but it has been talked about at great length (like several times, each times waayyy too long) and I can't replay the debate here (in part because I don't understand all of it).

**Comment by kvark** [comment]
FWIW, wgpu-rs contributors are very often confused by implicit present and have been requesting making it explicit for a while - https://github.com/gfx-rs/wgpu-rs/issues/558.
I also recall @jdashg advocating for an ability for applications to signal to WebGPU that the frame is ready before the end of RAF.

**Comment by litherum** [comment]
Why not specify it as "each 'update the rendering' step in the HTML5 event loop causes a new texture to be 'current', and if you want the current texture, call `getCurrentTexture()`"? If the internals of `getCurrentTexture()` actually gets a new texture the first time it's called in the current frame, such a behavior would be consistent with this kind of definition, in an "as-if" kind of way.

I think it will be valuable to be able to call `getCurrentTexture()` multiple times within a single frame and have it return the same object. I don't think we should give that up.

**Comment by kvark** [comment]
> I think it will be valuable to be able to call getCurrentTexture() multiple times within a single frame and have it return the same object. I don't think we should give that up.

To get more context on the editor discussion here, the problem is in the bold line between requesting it 0 times (the image stays untouched) versus non-0 times (the image gets cleared). `getCurrentTexture` is not composable because of this discontinuity: for example, a HUD layer may decide that it wants to draw the HUD, while the game rendering didn't draw anything, so the user would get a black screen with HUD on top. The only viable solution we see is to make this call valid only once.

**Comment by litherum** [comment]
I see. That's a convincing argument.

**Comment by Kangz** [comment]
I thought `acquireTexture()` could trip developers if it threw and exception after the first call in the same frame because it's a bit opaque to developers when a frame happens, but that's very similar to WebGL's `preserveDrawingBuffer:false` so it's probably fine.

**Comment by juj** [comment]
> To get more context on the editor discussion here, the problem is in the bold line between requesting it 0 times (the image stays untouched) versus non-0 times (the image gets cleared). `getCurrentTexture` is not composable because of this discontinuity: for example, a HUD layer may decide that it wants to draw the HUD, while the game rendering didn't draw anything, so the user would get a black screen with HUD on top. The only viable solution we see is to make this call valid only once.

By this example, do you mean an application would be drawing from multiple callbacks within a single frame, or from multiple functions inside a single callback?

E.g.

```js
function drawGame() {
   ... swapChain.getCurrentTexture();
}

function drawHUD() {
   ... swapChain.getCurrentTexture();
}

function rAF() {
  drawGame();
  drawHUD();
}
```
is that somehow problematic and should not be supported?

**Comment by kvark** [comment]
@juj not sure what "multiple callbacks within a single frame" refers to. If I understand correctly, one frame = one RAF call back.
> is that somehow problematic and should not be supported?

I do believe this case is *slightly* problematic.
The drawHUD has to only be done if the main game is rendered, or otherwise it's going to be drawing over black screen. Expressing this dependency explicitly would therefore be better:
```js
function rAF() {
  let frame = swapChain.getCurrentTexture();
  drawGame(frame);
  drawHUD(frame);
}
```
Another problem here is that for efficiency it would be better if both the game and the HUD were drawn in the same render pass to the swapchain frame. This would save VRAM bandwidth on mobile GPUs. So really this could look like:
```js
function drawGame(commandEncoder, frame) {
   let pass = commandEncoder.beginRenderPass(frame);
   ...
   return pass;
}
function drawHUD(pass) {
   ... render to the pass
   
}
function rAF() {
  let frame = swapChain.getCurrentTexture();
  let commandEncoder = device.createCommandEncoder();
  let pass = drawGame(commandEncoder, frame);
  drawHUD(pass);
  pass.end();
  device.queue.submit([commandEncoder.finish()]);
}
```

**Comment by juj** [comment]
> @juj not sure what "multiple callbacks within a single frame" refers to.

Multiple callbacks within a single frame occurs when one calls a combination of `requestAnimationFrame()` (and/or `setTimeout()`) functions several times, e.g.

```js
function render1() {
  ... swapChain.getCurrentTexture();
  requestAnimationFrame(render1);
}

function render2() {
  ... swapChain.getCurrentTexture();
  requestAnimationFrame(render2);
}

requestAnimationFrame(render1);
requestAnimationFrame(render2);
```

In the above code, `render1` and `render2` will not fire at different/alternating frames, but they will fire back-to-back once each frame.

> The drawHUD has to only be done if the main game is rendered, or otherwise it's going to be drawing over black screen.

Whether that is desired or not is a function of the application in question, not something for WebGPU to say? You could imagine the HUD to be something like Spector.js is, a rendering performance debugger, or some other graphics library code that someone else wrote. The two pieces of code may not be aware of each other, but would still like to render independently on screen, with the only coordination being to share `(GPUDevice, GPUSwapChain)` data structures at init time, and the general/global render order.

Restricting `getCurrentTexture()` to be callable only once per frame changes this data structure sharing from startup time to need to occur per-frame, as one needs to ensure coordinated flow of this special GPUTexture each frame across all different rendering libraries. I don't think that restriction particularly wins anything, but makes encapsulation harder.

> Another problem here is that for efficiency it would be better if both the game and the HUD were drawn in the same render pass to the swapchain frame.

Is the real intended guard to be made here that one should only be allowed to run a single render pass against the default swap chain texture per frame?

**Comment by kvark** [comment]
@juj thank you for feedback!
We discussed this some more in the editors call, and we decided that it's fine to keep the current semantics. It's not the best, obviously, and we'll be keeping an eye on it, but `acquire` would introduce more state, and make apps less comfortable, so it would have the cost comparable to the potential benefit.
