### ISSUE TITLE
Float literal scientific notation?

### ISSUE THREAD

**Issue by kdashg** [gpuweb/gpuweb#1432]
`const c = 3e8`
`const avogadro = 6.022e23`

Probably good to have.

**Comment by dneto0** [comment]
This is already in the FLOAT_LITERAL grammar.

Mind you, we don't *explain* how to interpret those literals.

**Comment by jdashg** [comment]
Sounds like all we need is more spec details?

**Comment by Kangz** [comment]
The definition of `decimal_float_literal` supports scientific notation. Closing this.
