### ISSUE TITLE
Using x1 in vertex format variants

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1434]
#1322 introduced the following variants that are controversial:
- `float32x1`
- `uint32x1`
- `sint32x1`

This is a follow-up to see if we need to do anything about it.

**Comment by Kangz** [comment]
Can we remove them ? :)

**Comment by litherum** [comment]
x1 🤮

**Comment by kainino0x** [comment]
I think we should go ahead and remove them, sounds like the opposition is stronger than the support.
