### ISSUE TITLE
Proposal: `GPUAdapter.gpuApiPreferenceRating`

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#1439]
Be warned: this is a very worse-is-better, the-perfect-is-enemy-of-the-good proposal!

There are three possibilities on any given user's machine: 
1. Hardware WebGPU with hardware WebGL2
2. Software WebGPU with hardware WebGL2
3. Software WebGPU with software WebGL2

This also applies for WebGL2 vs WebGL1 respectively. (WebGL1 vs Canvas2D can additionally have hardware webgl but software canvas2d)

For (1) we generally recommend WebGPU, but for (2) we definitely recommend WebGL2. (some apps without webgl1/2 backends may want/need to use software webgpu even if webgl1/2 have hardware therefore strictly more ideal)
For (3) though, we probably recommend using WebGPU again!

Originally, in the spirit of very literally designing a solution to match our user story, I considered `GPUAdapter.preferWebGL2` but I feel like this approach (with `WebGL2RenderingContext.preferWebGL1` and `WebGLRenderingContext.preferCanvas2D`) becomes unwieldy.

Instead, I think it might be easier to use if we just **offer a totally qualitative [0.0-1.0] preference rating for each API (adapter?) that a user has**, generally based on relative performance between that user's API choices. Yes this feels unsatisfyingly vague but we're not promising an API for comparing different users in absolute terms, but rather just a weighted recommendation between the choices on a single user's machine.

I think this also leaves room for users to reasonably choose modifications here via UA customization, as well as letting UAs generally provide (very) rough recommendations to websites about which backend to choose for that user.

---

This also leaves the door open for sorting and/or filtering for more complicated combinations.

**Example A**:
Imagine a system with software webgpu and webgl2, hardware webgl1 and canvas2d, with the recommendations 0.0/0.0/1.0/0.9. Here there's a preference for webgl1 over canvas2d, but also with canvas2d preferred above webgl2 or webgpu, the which are roughly equally slow/inefficient.

**Example B**:
Imagine a system with software webgpu, hardware webgl2/webgl1, and software canvas2d, with the recommendations 0.0/1.0/0.9/0.1. Clear preference for webgl1, but also a preference here for canvas2d over having to compile website shaders for the CPU, where we might expect canvas2d's fixed function SIMD operations to be better.

**Example C**:
Imagine a system with hardware webgl1+2, software canvas2d, and webgpu-emulated-on-webgl2ish-hardware, for which the webgpu/webgl2/webgl1/canvas2d ratings might be 0.9/1.0/0.8/0.0. (0.9 because maybe you expect overhead when e.g. a d3d11 webgpu implementation is given webgpu commands designed to take advantage of e.g. d3d12 features. (We expect this may be a fairly common configuration that Firefox runs in) You can tell these are well-ordered, and express the most likely preference for which API to choose. However, there's nuance in that if your website's webgl2 and webgpu backends are generally at parity with each other, the recommendation is to use webgl2 instead. Definitely avoid canvas2d on this machine.

---

While this API can feel unsatisfyingly vague, it offers the website a potentially-ordered set of recommendations for how to choose an API on a user's machine. Also, it's an easy-to-explain way to express this, such that it's even viable for users to reconfigure their UAs based on the user's preference for that machine. (Maybe they guess better than our UA's heuristics!)

**Comment by kvark** [comment]
Some quick feedback from the first read:
  - How do we get the "api preference rating of" WebGL/Canvas2D to compare to the potential WebGPU one?
  - Aren't we ending up with basically 0/1, i.e. one bit of information there? (which is basically a "software" bit)

**Comment by litherum** [comment]
I think there's another option: Don't offer software WebGPU anywhere. If the website is going to be trying to draw stuff in software, I'm not sure that software WebGPU is all that much better than software WebGL. Even for compute-only workloads - there are other options like SIMD.js, WebAssembly, and Web Workers - and it's reasonable to expect websites with compute-only workloads would already have a software fallback if they're interested in older machines.

**Comment by litherum** [comment]
(nit: you have two "Example A"s and no "Example B")

**Comment by litherum** [comment]
> offer a totally qualitative [0.0-1.0] preference rating for each API (adapter?) that a **user** has

> I think this also leaves room for **users** to reasonably choose modifications here via UA customization

(emphasis mine)

I think it's unreasonable to assume most users would actually do this, and I also think it's unreasonable to expect UAs to add a preference in their preferences for fallback. For example, there's no browser UI in any browser, as far as I know, for customizing the return of [`HTMLMediaElement.canPlayType()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType). I think we have to operate under the assumption that, for almost all pageloads, the fallback will be done by the browser or by the page, and not by user intervention.

I also think there's an argument here that the proposed API could (would?) actually be _more_ valuable for fingerprinters than it would be for legitimate graphics sites.

**Comment by kvark** [comment]
I think there are at least two kinds of applications: ones that can fall-back (to workers/WebGL/whatever else), and other that can't. For the former, it would be good to either have an option, or to just forbid software entirely, like @litherum suggested.
However, for the latter group, they just want to have stuff running, so having an option (i.e. "allowSoftware" that they can flip to `true`) is helpful.

**Comment by kainino0x** [comment]
I think numeric values as originally proposed will just end up with a lot of users depending on the exact values that the browser returns. IMO we should either make it an enum with specific values, or find an alternative.

How about the user just passes us an ordered list of their backends like `['webgpu', 'webgl2', 'webgl']` and we return the first one with hardware support?
`['webgpu', 'webgl2', 'webgl']` -> `'webgl2'`

Or we return them as a list `[...backends with hardware support, ...backends with software support`:
`['webgpu', 'webgl2', 'webgl']` -> `['webgl2', 'webgl', 'webgpu']`

The latter has the benefit that if they look at hardware webgl2 and find it's missing some extensions they need, they can still go on to check whether they can use the available webgl1, then whether they can use the available webgpu.

As an aside, there isn't actually a total ordering between hardware and software implementations - software implementations could have better extension support. Today in WebGL there's no way to specify "I REALLY want these extensions, even if it kicks my whole app down to software", but `requestAdapters` would give WebGPU that capability. I don't know if anyone has actually wanted this, but I could certainly imagine it being useful.... Say, (in a hypothetical where webgpu/webgl had porter-duff blend modes) the drawing area of a paint app which always needs porter-duff support (but can't use canvas2d for some reason).

**Comment by kainino0x** [comment]
Tentatively closing in favor of an allowSoftware-like thing, but there's a chance we'd eventually want to provide an API like one of these. In the mean time apps can use the usual "try webgpu hardware, then webgl hardware, then webgpu software, then webgl software"
