### ISSUE TITLE
Does this work on Linux because I can't really get it to work

### ISSUE THREAD

**Issue by romulasry** [gpuweb/gpuweb#1443]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1693398

**Comment by dneto0** [comment]
See https://github.com/gpuweb/gpuweb/wiki/Implementation-Status#firefox-and-servo

**Comment by romulasry** [comment]
Ping me when that gets a check-mark for Linux, thanks.

**Comment by dneto0** [comment]
The Mozilla bug-tracker seems to be the more appropriate channel to get your issue fixed.
