### ISSUE TITLE
Relationship between setVertexBuffers() and setBindGroup() is unclear

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#145]
The IDL has:

```idl
interface WebGPUProgrammablePassEncoder {
    ...
    void setBindGroup(u32 index, WebGPUBindGroup bindGroup);
}
...

interface WebGPURenderPassEncoder : WebGPUProgrammablePassEncoder {
    ...
    void setIndexBuffer(WebGPUBuffer buffer, u32 offset);
    void setVertexBuffers(u32 startSlot, sequence<WebGPUBuffer> buffers, sequence<u32> offsets);
    ...
}
```

But it's unclear what the relationship between the arguments to `setIndexBuffer()` and `setVertexBuffers()` are to the bind groups. What does `startSlot` mean? Does `startSlot` refer to a bind group index? Or are the vertex/index buffers in a different conceptual namespace than the buffers inside bind groups?

**Comment by litherum** [comment]
Similarly, what does `inputSlot` in `WebGPUVertexInputDescriptor` refer to?

**Comment by magcius** [comment]
Bind groups are unrelated to the vertex input. Bind groups contain shader resources like uniform buffers and textures/samplers, while vertex input contain the inputs to the vertex shader.

There's a small piece of indirection here in that multiple attributes can share a buffer. I believe the buffer index that a `WebGPUVertexAttributeDescriptor` uses is called its inputSlot. So you can have position/bone weights as one buffer, and normals/texture coordinates as a separate buffer. Four `WebGPUVertexAttributeDescriptors`, two `WebGPUVertexInputDescriptors`. You can set these buffers with the `setVertexBuffers` command, where you can choose the starting index for your buffers. So you could set the vertex buffer for normals/texture coordinates independently from the one that contains positions/bone weights if desired.

Part of building this model is that you need to explicitly determine which buffers go where. So with our above mapping, our engine might also have a vertex input for vertex colors, which might be in buffer slot 1. So positions/bone weights in buffer slot 0, vertex colors in buffer slot 1, normals/texture coordinates  in slot 2. But not every draw would use slot 1, so we'd have two `WebGPUVertexInputDescriptors` that have slots 0 and 2, respectively.

**Comment by kainino0x** [comment]
Thanks @magcius for your great response. I'll just add one thing:

Indeed, the vertex/index buffers are in a different conceptual namespace. The vertex slots are also in a different physical namespace: The "slots" for the vertex buffers [correspond](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#fxvertex-attrib) to GLSL's `layout (location=N)`/ SPIR-V's `OpDecorate _ Location N`.

I think I came up with "slot" semi-arbitrarily while doing the initial vertex input implementation early on in NXT (Dawn) development. It could probably be renamed to "location".

**Comment by kainino0x** [comment]
Wait, that's not quite right. I didn't reread what I said. Updating comment.

**Comment by litherum** [comment]
It seems like `inputSlot` is conceptually a name for the slot. Therefore, it seems like these can be arbitrary: I could have a `WebGPUInputStateDescriptor` with two `WebGPUVertexInputDescriptor`s, one with `inputSlot`=17 and one with `inputSlot`=538. This makes `void setVertexBuffers(u32 startSlot, sequence<WebGPUBuffer> buffers, sequence<u32> offsets)` confusing because it will fill a sequential series of slots, but the slot IDs are arbitrary and random. Not to mention the fact that two distinct `WebGPUVertexInputDescriptor`s may have the same `inputSlot`.

Why don't we remove the `inputSlot` field from `WebGPUVertexInputDescriptor` and use its position in the sequence of `inputs` in the `WebGPUInputStateDescriptor` instead?

**Comment by kainino0x** [comment]
Offhand, that sounds ok to me.

**Comment by magcius** [comment]
No, we can't do that, as I mentioned above, if we want to be able to allow apps to specify "holes", as in the vertex color case.

**Comment by kainino0x** [comment]
https://github.com/gpuweb/gpuweb/pull/146#discussion_r239918329

**Comment by kvark** [comment]
I do buy @litherum 's  point that since `setVertexBuffers` fills up a sequential range, we should be assuming that the holes are rare. And I like @kainino0x 's proposal to just use null-ability (or option/maybe) to express that instead of a separate arbitrary integer index.

**Comment by litherum** [comment]
Yes, +1 to using sparse arrays.

**Comment by grovesNL** [comment]
I think it’s an interesting idea, but I’m not sure there’s precedent for using sparse JS arrays in an API like this. Working with sparse arrays is a bit tricky to developers too (i.e. how holes are treated in comparison with `undefined` values).

**Comment by kainino0x** [comment]
That's a good point. I think it would be reasonable for us to spec that holes, undefined, and null are all treated the same way.

**Comment by magcius** [comment]
Does a undefined/null/a hole mean "unbound/unused for current draw" or "unchanged"?

**Comment by kainino0x** [comment]
I was thinking about `WebGPUInputStateDescriptor.vertexBuffers` having holes. I guess we didn't explicitly talk about whether `setVertexBuffers` takes a sparse array.

If `setVertexBuffers` still takes `sequence<WebGPUBuffer>` etc, I don't think a sparse array is valid here (would have to be `sequence<WebGPUBuffer?>` etc, I think).

We *could* make it take a sparse array, in which case I'm not sure which of those two semantics I would choose. They both seem fairly reasonable. I think "unbound/unused" would be less surprising.

**Comment by baptistemanson** [comment]
I apologize if I derail the convo.
I was trying to figure out why slot = 0 here:
https://github.com/austinEng/webgpu-samples/blob/master/src/examples/rotatingCube.ts#L189
```typescript
passEncoder.setVertexBuffer(0, verticesBuffer);
```
Is the slot = 0 coming from the index in pipeline > vertexState > vertexBuffers[] array?
So `slot === vertexBuffersIndex in pipeline`? Or is it a default value when we don't provide an id for a given buffer?

I am confused because it sounds like an id, but it cannot be attached/declared to any objecs associated with the vertices in the specs, I think. It may just be a naming issue, or extra documentation in the specs.
Thanks for your time.

**Comment by kvark** [comment]
> Is the slot = 0 coming from the index in pipeline > vertexState > vertexBuffers[] array?

Yes.
In the future, asking on #WebGPU:matrix.org would be easier.
