### ISSUE TITLE
[wgsl] Intra-scope shadowing?

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#1473]
#1472 might add the super-common inter-scope shadowing case.

Most languages don't support intra-scope shadowing, but there are times when it can be useful to effectively change the type (or modifiers) of an identifier.
```
  var sum = 0;
  for (var i = 0; i < N; i+=1) {
    sum += data[i];
  }
  const sum = sum;
```

This seems fairly straight-forward to support, though I expect some will feel that "we shouldn't support something no one should ever do", for some personal conviction of "should".

I desire this in other programming languages, and I would be happy if it were possible (and obviously not mandatory) in WGSL.
I don't think this is important, but some people feel this would be nice to have.

**Comment by kvark** [comment]
For implementation simplicity, it would be nice to *not* support this, at least for MVP. Variable shadowing is present in the text languages, but it's not required to do anything useful, and it's not there without [controversy](https://rust-lang.github.io/rust-clippy/master/#shadow_unrelated):
> Name shadowing can hurt readability, especially in large code bases, because it is easy to lose track of the active binding at any place in the code. This can be alleviated by either giving more specific names to bindings or introducing more scopes to contain the bindings.

**Comment by alan-baker** [comment]
Echoing Dan's statement from the VF2F which I agree with. It would be very odd to me to see a `const` get updated to be a new value.

**Comment by jdashg** [comment]
Ok! No appetite for this is fine!
