### ISSUE TITLE
Is the existence of the WGSL legitimate?

### ISSUE THREAD

**Issue by rafaelcout** [gpuweb/gpuweb#1475]
Is there a good reason for the existence of WGSL when there are already so many shaders ready to use in SPIR-V? Why does anyone directly involved with the project clearly explain the reason for the existence of this new language? Will developers have to pay the price for an apparently meaningless decision?

**Comment by mehmetoguzderin** [comment]
Please see: https://github.com/gpuweb/gpuweb/issues/610#issuecomment-699753812

**Comment by kainino0x** [comment]
Indeed, this has been discussed in depth elsewhere.
