### ISSUE TITLE
Document optional depth/stencil formats

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1479]
Follow-ups to #1463

- Expand https://gpuweb.github.io/gpuweb/#depth-formats with extension formats
- Clarify wording in that section that says "depth" when it really means "depth and/or stencil"?
- ~~Consider explicitly documenting that T2T copies with matching format is always valid (all formats, not just D/S)~~ #1464

**Comment by Kangz** [comment]
This seems very related to https://github.com/gpuweb/gpuweb/issues/1464 and https://github.com/gpuweb/gpuweb/issues/1692

Can the issues be deduplicated?

**Comment by kainino0x** [comment]
Editing this issue to make it not overlap with those.
