### ISSUE TITLE
Multi-level errors

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1481]
Our [ErrorHandling](https://github.com/gpuweb/gpuweb/blob/main/design/ErrorHandling.md) document mentions this:

> To help developers, should GPUUncapturedErrorEvent.message contain some sort of "stack trace" taking advantage of object debug labels? For example:
```
<myQueue>.submit failed:
- commands[0] (<mainColorPass>) was invalid:
- in setIndexBuffer, indexBuffer (<mesh3.indices>) was invalid:
- in createBuffer, desc.usage was invalid (0x89)
```

I think it makes sense to report errors this way. This is also how we internally represent errors: in Rust, an `Error` often links to [the source error](https://doc.rust-lang.org/std/error/trait.Error.html#method.source), forming a list, or a stack trace.

**Comment by kainino0x** [comment]
I think this is purely a user-agent enhancement, but we may want to provide non-normative examples in the spec showing what we expect to be possible.

**Comment by kvark** [comment]
The API right now has a single `DOMString message`. Is there an idiomatic way of communicate the stack trace through it? Putting "\n" in there doesn't seem to work.

**Comment by kainino0x** [comment]
Sorry, confused. Why doesn't \n work? It's just an arbitrary string.

**Comment by kvark** [comment]
I need to play with this more. Just tried to see how the messages get debug-printed in the Web Console, and it appeared that everything is escaped.

**Comment by Kangz** [comment]
That seems like a Firefox bug/improvement, maybe this can be closed?
