### ISSUE TITLE
GPUAdapterLimits uses GPUSize32 for read only attributes 

### ISSUE THREAD

**Issue by smaug----** [gpuweb/gpuweb#1484]
typedef [EnforceRange] unsigned long GPUSize32;

But https://heycam.github.io/webidl/#EnforceRange
"A type annotated with the [EnforceRange] extended attribute must not appear in a read only attribute."

**Comment by kainino0x** [comment]
Thanks for filing!

This was my bad; I'll go ahead and submit a quick fix now.

**Comment by Kangz** [comment]
Are you using a script to validate this? Maybe we could run it on CI?

**Comment by kvark** [comment]
Having a standalone webidl validator would be amazing.

**Comment by kainino0x** [comment]
There is one, but it isn't very strict and usually doesn't catch things like this, unfortunately.
