### ISSUE TITLE
[WGSL]: Spec should state that decorations MUST only be applied once

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#1488]
Applying the same decoration multiple times is ambiguous (e.g. `[[stride(16)]] [[stride(4)]] array<f32>`)

I'm not aware of any decoration type which would make sense to be applied more than once.

As far as I can tell, the spec does not explicitly forbid this. It probably should.

**Comment by dneto0** [comment]
Discussed [2021-03-09](https://docs.google.com/document/d/1IQLS_nypwJLjaMZlejMSMC_vP7D2pm0EH1NtZ1TIvs0/edit#heading=h.a0fpht4tpxjd)
