### ISSUE TITLE
WGSL: add     fn void(sink:T) -> void builtin function

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1499]
Proposal:  Add a "void constructor" (or builtin):

    precondition:  e: T,  where T is any non-void type that can be returned from a function
    conclusion:     void(e) :  void
    Description:    A call to the void function can appear as a statement in a function body. It evaluates its argument, and yields no value.

The purpose of the void constructor is to _purposefully_ discard the value resulting from the evaluation of its argument.
See #1413

**Comment by dneto0** [comment]
I put this in MVP so we would triage it.

**Comment by kvark** [comment]
I agree this is a good addition to the language. Is there a point in making it a builtin? Sounds like it could be just a standard library function.

**Comment by dneto0** [comment]
>  Is there a point in making it a builtin? Sounds like it could be just a standard library function.

I don't understand the distinction.

Also, it could have been called a type-constructor.

**Comment by kvark** [comment]
> I don't understand the distinction.

That's be cause there is none currently in WGSL :) I thought there is a difference, given that we were talking about standard library functions being versioned, etc, but that's not the case today.

> Also, it could have been called a type-constructor.

A desperate attempt to save the Void! 😆 
Seriously though, we aren't constructing anything, no need to hold the last straw of void here.

**Comment by dneto0** [comment]
Discussed [2021-03-09](https://docs.google.com/document/d/1IQLS_nypwJLjaMZlejMSMC_vP7D2pm0EH1NtZ1TIvs0/edit#heading=h.a0fpht4tpxjd)

**Comment by jdashg** [comment]
There's consensus towards `unused(T)` instead of `void(T)`.

**Comment by dneto0** [comment]
Thinking about this a bit more, [Google house style for function comments](https://google.github.io/styleguide/cppguide.html#Function_Comments) say

> comments at the definition of a function describe operation.

and

> Almost every function declaration should have comments immediately preceding it that describe what the function does and how to use it.

If you'll only have one, the name should say what it *does* not why you'd use it.

So I'd prefer to call this:  `ignore` rather than `unused`.
