### ISSUE TITLE
Optional tesselation support in GpuWeb!

### ISSUE THREAD

**Issue by oscarbg** [gpuweb/gpuweb#15]
Hi,
seeing two current proposals (Apple one based on Webkit, and Google's Chromium based one) they add compute support which is nice but seems there is no exposure of the tesselation stage.. 
Notice not asking about geometry shaders support which came even earlier on Desktops (OpenGL 3.2) because on mobile they haven't get much successs for ex. current Apple Metal API doesnt' support it..
any way tesselation shaders is supported everywhere on next gen APIs (D3D12 has it, Metal since IOS10/Macos 10.12 and recent iDevices and Vulkan as optional feature)..
Seeing all three APIs seems tesselation should be exposed as an optional capability as Vulkan does..
Just saying hope tesselation is incorporated in WebGPU spec from start and not as an afterthought!!

Thanks..

**Comment by Kangz** [comment]
Tessellation is an optional feature in Vulkan and isn't supported on some mobile GPUs so it would probably have to be an optional feature of the API too.

I'm not too knowledgeable about it but from what I understand, tessellation in Metal is very different from tessellation in D3D12 and Vulkan (1 shader stage vs. 2) so it might not be possible to come up with an API that works efficiently in a portable manner.

**Comment by oscarbg** [comment]
Well no problem that is an optional feature..
Regarding tess on Metal yes seems very different but seems some projects can generate Metal tess shaders from various other sources like HLSL, SPIR-V or will very soon:
1)Unreal 4.15 supports metal tess shaders and this are generated from HLSL tesselation shaders via his HLSL compiler.. it's open source so "inspiration" can be gained reading sources..
2)Unity in 2017 is supposed to come with Metal tesselation support too.. 
path will be via HLSL DXBC using https://github.com/Unity-Technologies/HLSLcc which will add Metal tess support presumably in H1 2017
3)finally MoltenVk (Vulkan->Metal) will support metal tess soon:
https://github.com/KhronosGroup/SPIRV-Cross/issues/120
and SPIRV-Cross project will be updated to support Metal tess output from SPIR-V tess shaders..

so briefly seems any "serious" project is able to gain Metal tesselation support.. don't see why WebGPU couldn't support that if for example using SPIR-V shaders as shader representation and using SPIR-V Cross to generate Metal tesselation shaders..

**Comment by litherum** [comment]
I think we are discussing this in https://github.com/gpuweb/gpuweb/issues/445. I'll close this issue and redirect people to look at that one instead. If you think this is an error, please don't hesitate to re-open this issue.
