### ISSUE TITLE
Characterize the performance benefit of GPUBufferUsage and GPUTextureUsage

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#150]
The drawback is obvious - they restrict how developers can use their resources.

We should determine how much the performance will suffer if all buffers/textures implicitly get all usages.

**Comment by Kangz** [comment]
This is very linked to #37 and [this comment](https://github.com/gpuweb/gpuweb/issues/37#issuecomment-341550104) gave examples of driver code that shows why declaring capabilities is important.

The API would definitely be nicer to use without having to declare the usage of resources, but either the WebGPU implementation will have to do magic to add usage to existing resources (which would involve whole-resource copies) or resources would need to use more memory than necessary and be constrained to live in smaller memory pools.

**Comment by kvark** [comment]
I think removing those would bring more trouble than benefit, as explained by @Kangz. Specifying the usage at creation time is hardly a burden to the user, and any errors in doing so are expected to show up early in testing (i.e. not obscure rarely happening errors).

> they restrict how developers can use their resources

I'd say it's not about restricting the developers, rather - it's about specifying the up-front contract on what the resource is used for. It's perfectly in line with how we declare pipeline and resource group layouts right now.

**Comment by Kangz** [comment]
Tentatively closing this issue: this part of the API has been stable for a long time. We can reopen if it still needs to be discussed.
