### ISSUE TITLE
Spec should use [=map/exists=] for optional dictionary members

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1512]
Today we're kind of handwavy, I think in some cases we use "is defined/undefined" or "is specified/unspecified" because we didn't know how to write it.

I just remembered that IDL dictionaries are [=ordered maps=] which means we should probably use [=map/exists=] on them.
https://infra.spec.whatwg.org/#map-exists

**Comment by toji** [comment]
Looking at this one, and I'm noticing that we have a lot of validation along the lines of: `If descriptor.format is undefined set it to some default`. If we change that to `If descriptor.format does not [=map/exist=]...` that seems to me to change the semantics, since `exists` is only concerned about the presence of the key in the dictionary. As such in the following dictionary:

```js
{
  format: undefined
}
```

`format` is considered to `exist` but is still set to `undefined`. If we change the logic to test exclusively for the existence of the key that could make it difficult for some libraries to fall back to defaults. Consider:

```js
helperFunction(format = undefined) {
  device.doAThing({ format });
}
```

**Comment by kainino0x** [comment]
JS objects are converted into IDL dictionary objects before our spec receives them. My understanding of the IDL ecmascript binding spec: https://heycam.github.io/webidl/#es-dictionary (steps 4.1.3 - 4.1.5)
is that both `{}` and `{format: undefined}` will result in an ES dictionary for which `descriptor['format']` "does not [=map/exist=]"

**Comment by toji** [comment]
Oh, I didn't realize that! That suggests that `{format: null}` also results in a dictionary for which `descriptor['format']` doesn't `exist`. Interesting! That would both simplify and make more consistent several of our validation rules.

**Comment by kainino0x** [comment]
Actually I don't think so, this algorithm is very confusing to read but my understanding is that `descriptor = null` results in `descriptor['format']` not existing. `descriptor = { format: null }` would result in the Get() call in step 4.1.2 returning `null`, and step 4.1.3 triggering since `null` "is not undefined".

**Comment by toji** [comment]
I'm confused... I feel like your last comment is saying contradictory things.

In 4.1.2 the switch statement indicates that both `undefined` and `null` result in `esMemberValue` being set to `undefined`, whereas anything else triggers the `Get()` call, which in turn results in 4.1.4 or 4.1.5 triggering. Am I wrong?

![Screenshot 2021-06-04 3 38 50 PM](https://user-images.githubusercontent.com/805273/120869348-1f1ac800-c54b-11eb-9a8b-30e0b502c2d4.png)

**Comment by kainino0x** [comment]
This threw me for a loop the first, like, ten times I read this algorithm.

IDL defines all of these conversions:
- JS null -> IDL dictionary
- JS undefined -> IDL dictionary
- JS object -> IDL dictionary

In 4.1.2, the It depends on `Type(esDict)`, not `Type(esMemberValue)`. So essentially what this is saying is, if the esDict is null or undefined, esDict defaults to an empty object `{}`. Then you access `esDict[key]`.

**Comment by toji** [comment]
😶

Holy crap. Well THAT'S not confusing...

Okay, so, to make sure we're all on the same page then for the following dictionary (assuming none of these have defaults):

```js
{
  a: undefined,
  b: null,
  // c is omitted
  d: 1
}
```

We get:

| key | exists | value |
|-----|--------|-------|
| a | false | undefined |
| b | true | null |
| c | false | undefined |
| d | true | 1 |

Which means if we have any cases that explicitly handle both `null` and `undefined` then we should convert them to test `if dict[key] exists or dict[key] is null`. (Which means I need to update my PR next week.)

**Comment by kainino0x** [comment]
> Which means if we have any cases that explicitly handle both `null` and `undefined` then we should convert them

I don't think we do, or at least very few if any. #1400 was to add them but we're not doing that yet.

**Comment by toji** [comment]
There was one instance of it that I had removed #1812 that I've added back in. I thought I remembered a couple more but apparently it was just the one.
