### ISSUE TITLE
Frag output uniformity requirements?

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#1515]
How uniform do they have to be? Can we dynamically index into e.g. an output array?

**Comment by dneto0** [comment]
Vulkan/SPIR-V does not require that to be dynamically uniform.  Look for "dynamically uniform" in the Vulkan spec.
The dynamically uniform constraint applies to:
 - indexing into an array of descriptors (buffer, sampler, texture of various kinds)
 - indexing into an array the push-constant space
 - theres a case with broadcasting within a quad.
 - and looks like for some operands of image instructions (which I didn't dig up)
 
Note that the min (across implementations) max number of fragment output colour attachments is 4.  See maxFragmentOutputAttachments

**Comment by litherum** [comment]
Frag outputs use Imagebuffers on Metal, which is tile memory. No special restrictions.
