### ISSUE TITLE
Validation rules and issues of createTexture

### ISSUE THREAD

**Issue by Richard-Yunchao** [gpuweb/gpuweb#1522]
Texture creation is one of the most basic and most important function in WebGPU. But we don't have validation rules for createTexture, we have a couple trials though. For example #799 and #1237.

 Recently I rewrote validation tests for createTexture. I'd like to summarize the 
- validation rules (which are clear and determined per my understanding, but I may misunderstood something and made mistakes), and 
- issues (which are not very clear to me). 

I will continue my investigation and try to figure out the issues left, but your comments/insights are very welcome. 

I put my answers (and reasons) to the issues but the answers may not be reliable because I haven't done thorough investigation. 

I will update the status of issues and mark them as clarified if we get consensus via discussion. 

## TextureDescriptor
Texture creation depends on TextureDescriptor. Its definition is listed as follows: 
```
dictionary GPUTextureDescriptor : GPUObjectDescriptorBase {
    required GPUExtent3D size;
    GPUIntegerCoordinate mipLevelCount = 1;
    GPUSize32 sampleCount = 1;
    GPUTextureDimension dimension = "2d";
    required GPUTextureFormat format;
    required GPUTextureUsageFlags usage;
};
```

I will go through each parameter in the next section. Note that `texture formats` impact every other parameter. So I discuss `formats` in the parameter where they impact. I don't put these validation rules and issues under the category of `format`.

### Dimensions (size) and dimension types (1D/2D/3D):
These two parameters impact each other. So I put them together.
#### validation rules
- Dimensions (width, height, depthOrArrayLayers) should not be 0 (should be equal or greater than 1).
- If Dimension is `1d`, size.height should be 1.
- If Dimension is `1d`, size.depthOrArrayLayers should be 1.
There is no 1D-array texture view, do we support 1D-array texture (if not, depthOrArrayLayers > 1 is invalid for 1D texture)? 
I think we should not support 1D-array texture. So size.depthOrArrayLayers should be 1.
- Don’t exceed the dimension limit on every dimension (maxDimensionTexture{1D, 2D, 3D}, maxDimensionArrayLayers, etc. Note that cubemap limit equals to maxDimensionArrayLayers?)
- Make sure that texture width/height are aligned with blockWidth/ blockHeight for compressed texture formats
- All formats can be supported for `2d` texture if the validation rules for other parameters are fulfilled.
#### issues - clarified
- Are compressed formats allowed for 1D/3D textures?
Compressed formats for 1D/3D textures are complicated (for copy, etc). In addition, compressed 1D/3D textures are not as useful as 2D compressed texture. So I tend to say we don't support compressed texture for 1D/3D in WebGPU MVP/v1. We can add it if needed in later version.  
  - Conclusion: we will not support 1D/3D compressed textures unless somebody comes up with a strong case. 
- Any total size limit (width * height * depthOrArrayLayers)? Note that if we create a 2D array texture with size = [maxDimensionTexture2D, maxDimensionTexture2D, maxDimensionArrayLayers], it will lead to out-of-memory failure. 
  - Conclusion: Just let it be. OOM is a fine reaction. We got the conclusion for buffer size limit. Let's follow the same rule. 
- Some formats are not valid for 1D/3D textures.
  - Conclusion: in addition to compressed formats invalid for 1D/3D textures, depth/stencil formats are invalid for 1D/3D textures.
    - Depth/stencil formats are invalid for 3D on D3D12. [This link](https://github.com/microsoft/DirectX-Specs/blob/master/d3d/archive/images/d3d11/D3D11_3_Formats_FL10_0.xls) lists all formats' capability (including 1D/2D/3D texture support) on FeatureLevel_11_0 for D3D. Note that D3D12 can be supported from FeatureLevel_11_0. 
    - [CTS testing](https://bugs.chromium.org/p/dawn/issues/detail?id=730) on Metal indicates that Metal has this requirement: depth/stencil formats are valid only for 2D (including 2D array textures, 2D cube textures).

#### validation rules
- mipLevelCount should not be 0
 - mipLevelCount should not be larger than the max values allowed (can be calculated according to its dimensions and dimension types)
- mipLevelCount should be less than integer bit width
- mipLevelCount can be any value between 1 and max allowed values, even for compressed formats. 
#### issues - clarrified
- Are there any formats that can't support mipmap? compressed texture formats are valid for mipmaps (at least for 2D texture), what about depth/stencil formats?  
  - According to my investigation about [texture formats in D3D12](https://docs.google.com/spreadsheets/d/1ALlgyOA5BXXhJDZXPyEQ-vXV_E8IKZfe1xcNmhIM4Mw/edit#gid=1384276076) (and [GLES 3.2](https://www.khronos.org/registry/OpenGL/specs/es/3.2/es_spec_3.2.pdf)), I didn't find any limitation about mipmap support for any formats. Let's assume there are no additional limits for now.
    - Some formats cannot support mipmap in D3D12, but WebGPU didn't support those formats. For example, YUV, NV12, etc.   
    - In GLES, there are some limits about how to sample mipmap: some depth/stencil formats can only support mipmap_nearest, while the majority of texture formats can support both mipmap_nearest and mipmap_linear. This indicates that depth/stencil formats (and other formats) can support mipmap.  

#### validation rules
- Valid sample count are 1 (single-sample) and 4 (multi-sample). All other values are invalid.
- If we support multisample (sampleCount is 4), then
  - Its dimension type should be 2D only. 1D and 3D multisample texture are not supported in [Metal]( https://developer.apple.com/documentation/metal/mtltexturetype). Note that there are no 1DMultisample or 3DMultisample texture types.
    - This also means that sampleCount for 1D/3D textures should be 1.  
  - mipLevelCount should be 1 
  - Its usage should not include TextureUsage.STORAGE.
  - Compressed formats are invalid. 
#### issues - clarified
- Except for compressed formats, are there any other formats that are invalid for multisample? 
  - Conclusion: formats which can be used as RENDER_ATTACHMENT or Depth/Stencil can support multisample. Other formats can't. 
- Can we support 2D array multisample texture (if not, arrayLayerCount should be 1 for 2D texture) ? 
Currently we disallow this in CTS, but it looks like 2D array multisample textures can be supported in D3D12/Metal/Vulkan. 
  - Conclusion: we can't support 2D array multisample. Metal can support 2D array multisample only on MacOS 10.14+ and iOS 14.0+, see [this link](https://developer.apple.com/documentation/metal/mtltexturetype/type2dmultisamplearray)

#### validation rules
- All formats can be used as TextureUsage.SAMPLED
- Some formats are not renderable (say compressed formats, rgb9e5, rgb19a2, etc). Those formats should not include TextureUsage.RENDER_ATTACHMENT
TODO: list these formats
- Some formats can not be used as storage (say compressed formats, depth/stencil formats, etc). Those formats should not include TextureUsage.STORAGE
TODO: list these formats.
- What about format validation upon TextureUsage.COPY_SRC and TextureUsage.Copy_DST?
I think all formats are valid for TextureUsage.COPY_SRC and TextureUsage.Copy_DST. But we need to consider depth/stencil formats used as Copy_SRC/COPY_DST, and the complexity to copy operation. 
#### issues - clarified
- Any usage combination conflict? 
Looks like the answer is no. 
  - Conclusion: no conflict.
- Is there any usage that is not allowed for 1D/3D textures?
Looks like the answer is no. 
  - Conclusion: no. All usages are allowed for 1D/3D textures.

#### validation rules
- Some formats need extension support (compressed formats, etc.). Otherwise texture creation will fail. 
  - [TextureFormat in WebGPU spec](https://gpuweb.github.io/gpuweb/#enumdef-gputextureformat) has already listed the required extension for each format if it needs an extension.

Some validation rules and issues might be missing...

**Comment by Richard-Yunchao** [comment]
@kainino0x , @Kangz , and @austinEng , I promised to create an issue and write down the open questions which are not clear to me for createTexture (when I wrote validation tests for createTexture). Here it is. FYI @RafaelCintron and @bbernhar .

**Comment by kvark** [comment]
I'll try to answer some:
> Are compressed formats allowed for 1D/3D textures?

Your suggestion to postpone this sounds good to me, unless somebody comes up with a strong case.

> Any total size limit (width * height * depthOrArrayLayers)? Note that if we create a 2D array texture with size ..., it will lead to out-of-memory failure.

When we discussed the buffer size limits last time, it was concluded that OOM is a fine reaction. So I suppose we can OOM here as well.

> are there any formats that can't support mipmap?

I think we want to restrict the MSAA textures to not have mipmaps. But we likely want to allow mipmaps for storage and depth textures, although I'm not able to find an investigation where we have that info. Vulkan returns the available number of mipmaps in `VkImageFormatProperties::maxMipLevels`, but the specification has a bit loose guarantees about which configurations are required to have mipmaps:
```
maxMipLevels is the maximum number of mipmap levels. maxMipLevels must be equal to the number of levels in the complete mipmap chain based on the maxExtent.width, maxExtent.height, and maxExtent.depth, except when one of the following conditions is true, in which case it may instead be 1:

    vkGetPhysicalDeviceImageFormatProperties::tiling was VK_IMAGE_TILING_LINEAR

    VkPhysicalDeviceImageFormatInfo2::tiling was VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT

    the VkPhysicalDeviceImageFormatInfo2::pNext chain included a VkPhysicalDeviceExternalImageFormatInfo structure with a handle type included in the handleTypes member for which mipmap image support is not required

    image format is one of those listed in Formats requiring sampler Y′CBCR conversion for VK_IMAGE_ASPECT_COLOR_BIT image views

    flags contains VK_IMAGE_CREATE_SUBSAMPLED_BIT_EXT
```

Looks like we need more investigation here.

> Except for compressed formats, are there any other formats that are invalid for multisample?

Vulkan lists the following requirements:
```
sampleCounts will be set to VK_SAMPLE_COUNT_1_BIT if at least one of the following conditions is true:

    tiling is VK_IMAGE_TILING_LINEAR

    type is not VK_IMAGE_TYPE_2D

    flags contains VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT

    Neither the VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT flag nor the VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT flag in VkFormatProperties::optimalTilingFeatures returned by vkGetPhysicalDeviceFormatProperties is set

    VkPhysicalDeviceExternalImageFormatInfo::handleType is an external handle type for which multisampled image support is not required.

    format is one of those listed in Formats requiring sampler Y′CBCR conversion for VK_IMAGE_ASPECT_COLOR_BIT image views

    usage contains VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR

    usage contains VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT

Otherwise, the bits set in sampleCounts will be the sample counts supported for the specified values of usage and format. For each bit set in usage, the supported sample counts relate to the limits in VkPhysicalDeviceLimits as follows:
```

> Can we support 2D array multisample texture

I don't see why not :)

> Any usage combination conflict?

No, looks like we are clear from conflicts.

> Is there any usage that is not allowed for 1D/3D textures?

I can't think of any restriction there.

**Comment by Kangz** [comment]
+1 to what @kvark said with the following additions:

> Vulkan returns the available number of mipmaps in VkImageFormatProperties::maxMipLevels, but the specification has a bit loose guarantees about which configurations are required to have mipmaps:

IIRC if you can create an image as LINEAR you can also create it with an opaque swizzled layout. This means that all WebGPU textures can be created in such a way that they don't match any of the items in the list. So you can create them with full mipmaps.

> Except for compressed formats, are there any other formats that are invalid for multisample?

As soon as the format is renderable it should be multisamplable given the Vulkan restrictions @kvark quoted. That should be a restriction in WebGPU.

> Can we support 2D array multisample texture

In Metal they are only available starting from macOS 10.14 and they aren't available on iOS.

> Some formats are not valid for 1D/3D textures.

Except compressed formats they should all be valid.

@Richard-Yunchao are you interested in making the spec PR for that (based off #799 maybe?) or would you rather have someone else take it?

**Comment by Richard-Yunchao** [comment]
Thanks for your input, @kvark and @Kangz .  I can try to write the spec. 

Many TODOs are related to texture format capability. I feel like that we need a table to list texture format's capability (like renderable, storage support, mipmap support, multisample support, etc.), just as the table in CTS. It can be either in the spec or in a separate webpage in gpuweb project. WDYT?

**Comment by Kangz** [comment]
There's [this table](https://gpuweb.github.io/gpuweb/#texture-format-caps) but it seems only renderable and storage caps are needed: mipmap is always allowed and multisample should be the same as renderable. So it should be good already.

**Comment by Richard-Yunchao** [comment]
Oops. I didn't notice that table. I will add columns if needed in addition to renderable and storage caps.

**Comment by Kangz** [comment]
Testing all combinations of texture creation in the WebGPU CTS / Dawn we [found](https://bugs.chromium.org/p/dawn/issues/detail?id=730) that depth-stencil textures are required to be 2D on Metal. Otherwise the debug device complains about the following:

> -[MTLTextureDescriptorInternal validateWithDevice:]:1402: failed assertion `MTLTextureDescriptor: depth/stencil pixel formats require texture type of MTLTextureType2D[Array] or MTLTextureTypeCube[Array].'

**Comment by Richard-Yunchao** [comment]
Just FYI. I updated this document according to your comments and my investigation. Now all issues I listed are being clarified. I will start to write the spec for texture creation soon, which will be based on Myles' PR and discussions here. Stay tuned.

**Comment by Richard-Yunchao** [comment]
Thanks to Kai and Dzmitry's review, the PR to add validation rules for texture creation (which is based on this issue) has been merged. Closing this issue now.
