### ISSUE TITLE
Pointer chaining in WGSL

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1530]
This is a follow-up to #1456.

The discussion hit a point where we had 2 proposals for how pointer operations would work, and we agreed to proceed with an intersection. This means, `.` and `[]` are not defined on pointers. This issue is about providing this ability to get a pointer from an element of a composite type, given a pointer to the composite. Suggested syntax:
```rust
struct Bar {
  unused: vec4<f32>;
};
struct Foo {
  x: array<i32, 5>;
  y: Bar;
};

fn foo(ps: pointer<Bar, Private>) {
  const px: pointer<array<i32, 5>, Private> = ps.x;
  const py: pointer<i32, 5, Private> = px[3]; // same as `ps.x[3]`.
  *py = 4; // store
  *ps.x[0] = 1; // also store. The "." has a precedence over "*"
  const py: pointer<vec4<f32>> = ps.y.unused;
  *py = vec4<f32>(0.0);
}
```

Currently, if I understand correctly, taking a pointer to a member would look like this: `&(*ps).x`. The new semantic of "." and "[]" in this proposal would match `OpAccessChain` SPIR-V instruction, which operates on pointers and supports a chain of jumps.
@dneto0 please feel free to edit the issue if I expressed it incorrectly or unclear

**Comment by dneto0** [comment]
Right, thanks!

The idea is that we already have operations on reference-types (think l-value in C/C++):
*   `s.field`  gets from an l-value struct `s` to an l-value of its `field` member
* `a[i]` gets from an l-value array `a` to an l-value of its `i`'th element.

Pointers and reference duals of each other: They are both "references to storage locations for holding a value of a particular storable type".  
The only difference is the operations that you can do on references vs. pointers.
* You can do unary `*` on a pointer to get the corresponding reference.  _Can't_ do unary `*` on reference.
* You can do unary `&` on a reference to get the corresponding pointer.  _Can't_ do unary `&` on pointer.

But pointers and references are two ways of looking at the same storage, and so they should share the same operations spelled the same way _when those operations reflect that essential sameness._ 

Therefore, WGSL should support these operations on pointers:
*  `p.field`  gets from a pointer-to-struct `s` to a pointer of the storage for that `field` member of `s`
* `a[i]` gets from pointer-to-array `a` to a pointer for the of its `i`'th element.

Fixing syntax in the example (as per current spellings, modulo the proposal here), and adding some commentary:
```rust
struct Bar {
  unused: vec4<f32>;
};
struct Foo {
  x: array<i32, 5>;
  y: Bar;
};

fn foo(ps: ptr<private, Bar>) {
  const px: ptr<private, array<i32, 5>> = ps.x;  // Field selection on a pointer, yielding a pointer.
  const py: ptr<private, i32> = px[3];  // same as `ps.x[3]`.  Array element selection on pointer, yielding pointer.
  *py = 4; // store
  *ps.x[0] = 1; // also store. The "." has a precedence over "*".  Yes!
  const py: ptr<private, vec4<f32>> = ps.y.unused;
  *py = vec4<f32>(0.0);
}
```

Note: the stated compromise from #1456 loses expressibility already available in the original pointers-only proposal of #1368. 


Thanks so much for driving this @kvark

**Comment by dneto0** [comment]
Note, this proposal still plays very nicely with a future with type derivation for var and const declarations.
That was something that the original #1368 did not have.  So that's great too!

**Comment by dneto0** [comment]
I forgot to mention another difference between references and pointers:

* The LHS of an assignment statement must be a reference.

**Comment by kvark** [comment]
@litherum to clarify, I think we should take either this proposal ((1) - pointer chaining), or the "->" (2), or the "auto-deref" one ((3) - that I mentioned but we don't have written down). But taking both (1) and (2) would end up with a messy API. They both appear to be solving the same problem in different ways, and we've got to have a really good reason to introduce these multiple ways (`*p.a = 1` vs `p->a = 1`).

**Comment by dneto0** [comment]
Discussed in meeting of [2021-03-23](https://docs.google.com/document/d/19inX49uQBMkWx1lSuPkFWJ8fGRJUGMNXmkUj5TJWnwY/edit#)

* Consensus on accepting this proposal.
* Strongly consider adding -> as convenience / syntactic sugar. 
    * Proposed by Apple, acceptable to Google (but prioritized after this proposal, due to workload), and objected by some.

**Comment by kvark** [comment]
It doesn't switch the precedence. The C rules put "." to be higher priority than "*". What this issue does is just defining what happens if you put "." on a pointer.
