### ISSUE TITLE
Queries spec inconsistent with ErrorConventions.md

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1532]
The queries spec currently says (error-scope) validation errors occur if you use query types whose `features` are not enabled.

ErrorConventions.md says these errors should be JS exceptions instead. This makes it look identical to what would happen in a browser that doesn't know anything about the relevant `features` in the first place.

We need to choose from:
- Leave as is, change ErrorConventions.md to allow that difference
- Change the spec to force an exception here. Note implementations will have to implement this checking on their client-side.
- Do the opposite and change all of the IDL that takes extensible enums to `string`, and always make them error-scope validation errors. (ew)

**Comment by Kangz** [comment]
Unless we have good reasons we should go with the semantics we agreed upon previously so that would be:

> Change the spec to force an exception here. Note implementations will have to implement this checking on their client-side.

**Comment by kvark** [comment]
@Kangz do you happen to have links to these previous conversations?

**Comment by kainino0x** [comment]
Editors: most likely will update the spec to use exceptions but tbd still

@kvark also noticed that ErrorConventions describes something we can't implement: "If any object in A contains any key that is not core or part of an enabled feature: Error must be synchronous."
so we should fix that.

**Comment by Kangz** [comment]
> @Kangz do you happen to have links to these previous conversations?

Just what's recorded in ErrorConventions.md If we had to dig for notes, then it would be around 2017/18 that we agreed on this stuff.
