### ISSUE TITLE
editorial: do we need a definition of "object"?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1538]
We haven't formally defined "object".
It's used as follows:

- The [definition of "declaration"](https://gpuweb.github.io/gpuweb/wgsl.html#declaration) lists specific things as objects, including "type".
- when defining shader interface
- describing resource interface (same meaning as shader interface)
- PR #1542 that refactors the descriptions of attributes in the spec, uses the phrase "object or type".  See https://github.com/gpuweb/gpuweb/pull/1524/files#diff-709b5c343d59ae10cbabe69f9df1eee9e2dbb6e9d848632fa94357083d6e0a34R181

**Comment by kdashg** [comment]
@dneto0 Do we still need this? In M0?
