### ISSUE TITLE
var: infer type from initializer

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1550]
This is like #1529, but for var.

Allow a var declaration that has an initializer to have no store type specified.  In that case the store type is taken to be the same as the type of the initializer value.

e.g.
       var a : i32 = 12;
       var anotherA = 12;  // same effect different identifier

or at module scope

       var<private> b : u32 = 12u;
       var<private> anotherB = 12u;

**Comment by kvark** [comment]
Do we really need to have that at module scope? It would only affect the `private` storage class, anyway.

**Comment by dneto0** [comment]
Yes, for consistency and generality.  Why add a usage cliff to the rule?  

The private-storage class variable is the only way to have a complex constant, like scientific parameters, or a rotation matrix, embedded as static data in the shader.  So the argument is quite strong to allow it at module scope.

**Comment by kvark** [comment]
> The private-storage class variable is the only way to have a complex constant, like scientific parameters, or a rotation matrix, embedded as static data in the shader. So the argument is quite strong to allow it at module scope.

Could you elaborate? If you have an initializer, and it's constant data, why not use `const` in the first place?

**Comment by kvark** [comment]
> Yes, for consistency and generality. Why add a usage cliff to the rule?

Well, it depends on what angle you see these things under. I'm all for consistency and generality!
I think it would be nicely consistent if all module-scoped declarations required types :)

**Comment by dneto0** [comment]
Discussed in [2021-05-18 meeting](https://docs.google.com/document/d/1A_NOHjqHGTQryVqZEPoIWJLSqBa_JVwhyutJJ9206aY/edit#).

Agreed to infer for var in function scope (not module scope).

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-05-18-Minutes#var-infer-type-from-initializer-1550">WGSL meeting minutes 2021-05-18</a></summary>



*   DN: Can live with everywhere but module scope (as DM wants)
*   RM: Can live with that.  Don’t know why module scope is special.
*   DM: Rust has inference only for local scope.
*   JB: Languages that do inference at module scope:  users suffer
*   _Consensus to go with DM’s proposal._


</details>
