### ISSUE TITLE
Uniform structure sizes have to be aligned to 16 bytes?

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1558]
We have this currently:
> The uniform storage class also requires that:
    Array elements are aligned to 16 byte boundaries.
    Structures must have a size that is divisible by 16 bytes.

It appears to fail even on Tint's own example of [compute boids](https://dawn.googlesource.com/tint/+/refs/heads/main/test/compute_boids.wgsl#45):
```
[[block]]
struct SimParams {
  deltaT : f32;
  rule1Distance : f32;
  rule2Distance : f32;
  rule3Distance : f32;
  rule1Scale : f32;
  rule2Scale : f32;
  rule3Scale : f32;
};
```
The size of this structure is 7 * 4 = 28 bytes.

Is this validation rule correct? I imagine there be a lot of real-world use cases hitting this, and annoyed a great deal about it.

**Comment by alan-baker** [comment]
I think the size requirement is a simplification of a requirement on nested structures. In Vulkan, you can't pack data between the end of an array or structure and the offset and the next multiple of alignment of the array/struct. So the block-decorated struct itself doesn't need to be a multiple of 16 bytes in size.

**Comment by dneto0** [comment]
If you made an array of SimParams in uniform  memory, then the stride would be a multiple of 16.
There would be 4 inaccessible bytes from the end of rule3Scale and the start of the deltaT of the next element.

**Comment by dneto0** [comment]
(oh, it's block-decorated in this case.  so you can't make an array of them.  I answerd this case:

```
[[block]] SimParamsArray {
    data : array<SimParams,2>; //  the stride is 32 because of that extra padding. 
}
```
Maybe that's not what you're asking?

**Comment by kvark** [comment]
I'm not asking about a hypothetical use case, I'm asking about the Boids example specifically.
I think @alan-baker answered this, and we should fix the spec to allow the block structure sizes not aligned to 16 bytes

**Comment by ben-clayton** [comment]
I think Alan's proposed relaxation on this rule is fine.

> It appears to fail even on Tint's own example of compute boids:

Thanks for finding and alerting us to this. Tint has landed the changes to migrate from `[[offset]]` to the new default structure layout, but storage and uniform layout validation has not begun yet. We intend to start this in the next couple of weeks, and would have hit this.

**Comment by kvark** [comment]
This appears to contradict #425 with Metal alignment requirements:
> As the largest alignment of the attribute (float4) is 16 bytes, the actual size of uBuffer is 32 bytes, so when we bind a buffer with 20 bytes in bind group, the Metal validation layer will report the following validation error:
>> Fragment Function(main0): argument uBuffer[0] from buffer(0) with offset(0) and length(20) has space for 20 bytes, but argument has a length(32)
