### ISSUE TITLE
Removing the need "non-filtering" samplers

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1562]
This came up in a discussion with @ben-clayton about `GPUBindGroupLayoutEntry` (mostly his idea really). I kinda recall @kvark suggested something similar in the past too.

Right now we have the concept of non-filtering samplers but it isn't exposed in WGSL. The idea is that since there are non-filterable float formats, we should check at pipeline compilation time that there aren't any texture binding with "unfilterable-float" sample type statically used by a "filtering" sampler.

What if instead we disallowed "unfilterable-float" from being used with a sampler at all in the shader. This would mean that at pipeline creation time we would check that none of the  "unfilterable-float" textures are used with one of the `textureSample*` builtin functions. This makes the validation more tractable and much less error prone.

**Comment by kvark** [comment]
A sampler does more than just filtering. There are also addressing modes and LOD clamps.
If we follow the suggestion, we'd basically lose the ability to apply addressing modes on formats like `R32Float`. This would be a real restriction that isn't based on any low-level limitation (or portability concerns).

**Comment by Kangz** [comment]
Correct, but you keep `textureLoad` and `textureStore`. It's not clear that non-filterable float formats are used with samplers in practice. Note that adding back the non-filtering samplers is a non-breaking change.

**Comment by kvark** [comment]
Well, this is a suggestion to remove something that is already specified, thought through, and mapped well to all native backends (so it enables the users to do more). It's not a kind of feature that we generally postpone to after MVP.
it's unclear what savings this would give us. On validation side, you still need to gather the texture/sampler pairs. So changing a condition from "this can be used with a non-filterable sampler" to "this can't be used with a sampler" doesn't make it any simpler.

**Comment by Kangz** [comment]
The saving it give us is that instead of needing to validate the full interference matrix between textures and samplers, we only need to know if a texture is used with a sampler at all. From an implementation PoV in Naga, how much would it help you?

**Comment by kvark** [comment]
Removing this ability would not make our (wgpu/naga) implementation any easier.
When you say "full interface matrix", this is misleading. You have to scan the texture-sampler pairs anyway. The non-filtering sampler would just add 1 condition to the code.

**Comment by Kangz** [comment]
Why do you need to scan all the texture-sampler pairs at the moment? Also +CC @ben-clayton

**Comment by kvark** [comment]
Hm, maybe we don't have to do this... In any case, we need more data to prove or disprove this:
> It's not clear that non-filterable float formats are used with samplers in practice.

**Comment by Kangz** [comment]
I don't have data, but the intuition that since it is only for address-sampling, it might not be very used. It is backwards-compatible to add address-sampling of non-filterable float textures if it turns out it is needed. Personally I'm happy for this to go either way but @ben-clayton might have some more concerns from the shader reflection implementation side.

**Comment by kvark** [comment]
If we are talking about having the draw-call validation that iterates all texture/sampler pairs versus not having it, at least for MVP, then it's definitely tempting to do. It would be good to get some information from ISVs though.

**Comment by Kangz** [comment]
I think it would be pipeline compilation though. You know all the required info at pipeline compilation time.

**Comment by kvark** [comment]
I assume the idea is that if we remove "non-filtering" sampler, we also do something with "non-filterable" sampled textures. Either it needs to be removed, or changed to something "non-sampleable". In the latter case, we'd also allow integer textures to be in this category, so that sounds compelling.

**Comment by kvark** [comment]
@Kangz thinking about this some more, the idea to get integer textures back to the sampling binding sounds very appealing to me. I think we should do what this issues suggests (with integer textures in mind!).

**Comment by kainino0x** [comment]
From editors meeting: this change would also:
- prevent using wrap modes on these formats
- require the caller to know the dimensions of the texture for texelFetch

**Comment by Kangz** [comment]
The effort looks tractable in Dawn / Tint so we're happy to keep the current semantic.

**Comment by kvark** [comment]
@kainino0x in addition, such a change would prevent getting the implicit LOD selection during sampling. Non-filtered textures in Vulkan and friends can still get implicit LOD selection if no filtering between LODs is requested.
