### ISSUE TITLE
[proposal] Interface Matching

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#1563]
We discussed interface matching on an office hours call previously, but here is a formal proposal.

# Proposal

Built-in variables do not participate in interface matching. For each, user-defined vertex output and fragment input there must be a corresponding fragment input or vertex output respectively that matches both the type and location assignment.

I would describe this as the MVP requirement. In the future, restrictions could be relaxed.

## Extensions

If the group wishes to extend this to allow subsetting outputs, consideration should be given to adding a rule that prevents gaps in locations assignment (e.g. locations must fill a contiguous space). This makes mapping to HLSL easier, as it avoids type mismatches from sparse location spaces.

# Survey

WGSL has the following builtins that vertex outputs or fragment inputs:

| Built-in | Vertex | Fragment | Should Match? | Notes |
|--------|--------|-----------|----------------|-------|
| position | Yes | Yes | No | Different coordinate spaces |
| front_facing | No | Yes | No | One-sided interface |
| sample_index | No | Yes | No | One-sided interface |
| sample_mask | No | Yes | No | One-sided interface |

Based on the table, it seems reasonable that built-ins not participate in interface matching.

## Metal

Interface matching is determined based on the `[[stage_in]]` parameter of the fragment shader and the return type of the vertex shader. The fragment shader’s stage inputs must be one of: a color attachment (not in WGSL), a user-defined value or a builtin. Builtins can optionally be passed as separate parameters too. Builtins do not need to match. For user-defined data, if a `[[user(name)]]` attribute is specified the name and type must match in the vertex output, otherwise the argument name and type must match a member in the vertex output.

## HLSL

The inputs must be a strict subset of the outputs (matching argument type and order). This means that position can contribute to failed interface matching.

```
struct VS_OUT {
  float4 pos : SV_Position;
  float3 normal : Normal
  float2 coord : Texcoord0;
};

// coord isn't necessary to be present and pos and normal match.
struct PS_IN_Good {
  float4 pos : SV_Position;
  float3 normal : Normal;
};

// Ordering doesn't match.
struct PS_IN_Bad {
  float3 normal : Normal;
  float4 pos : SV_Position;
};
```

## SPIR-V

Vulkan doesn’t require builtins to match **unless** they are in a block-decorated struct (which is tacitly only acceptable for gl_PerVertex builtins), however, the inputs may be a subset of the outputs.

User-defined IO must match location, component (not exposed in WGSL), decoration (except interpolation and other not exposed in WGSL) and type. There is one exception for type matching: vectors and scalars match if the decorations match and the output has more components than the input and the component type matches. That is, a vec4 output can match a vec3 (or vec2 or float) input.

**Comment by kvark** [comment]
Thank you for writing this down!

> For each, user-defined vertex output and fragment input there must be a corresponding fragment input or vertex output respectively that matches both the type and location assignment.

Are we intentionally excluding the vertex attributes and color targets from the interface matching rules?

> WGSL has the following builtins that vertex outputs or fragment inputs:

The table needs another column to say if it's an input or an output.

**Comment by alan-baker** [comment]
This is only for interfacing between vertex and fragment shaders. So the table only covers vertex outputs and fragment inputs. The rules for vertex inputs and fragment outputs belong in the API in my opinion.

**Comment by alan-baker** [comment]
I could also see deferring this requirement to the WebGPU API spec and covering all the requirements there instead.

**Comment by Kangz** [comment]
Agreed, this should probably live in the WebGPU API spec and use WGSL "reflection" to define the validation rule.

**Comment by kvark** [comment]
Ok, sounds fine. We can move stuff around if needed.
also nit: `sample_mask` is not "One-sided", it's two-sided (FS input and FS output).
