### ISSUE TITLE
Require that vertex shaders return a position?

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#1567]
MSL requires that if a vertex shader does not return void, then it must at least return the position builtin. We should consider whether WGSL should impose the same requirement, and also whether it should be valid for a vertex shader to return `void`.

I'd like to propose that WGSL should require vertex shader return types to include `[[builtin(position)]]` if they are not `void`. I do not have a strong opinion on whether or not we should allow a return type of `void`.

**Comment by kvark** [comment]
I don't understand why we'd want vertex shaders without return types, and if we find a use for it, we can always relax this later. For now, I agree, let's just require the `position` to be there.

**Comment by kainino0x** [comment]
I think I recall that in WebGPU today, even though the fragment shader is optional, rasterization is _not_. Which means we always need a position. Definitely +1 to making it more restrictive now and adding void-returning vertex shaders when we need it.

**Comment by kvark** [comment]
I think MSL requires this.

**Comment by jimblandy** [comment]
I was looking at this recently. In the Metal Shading Language Specification, Version 2.3:

§5.1.1, "Vertex Functions", says:
> For a vertex function, the return type identifies whether the output generated by the function. If the vertex function does not generate output, it shall return void and can only be used in a render pipeline with rasterization disabled.

If WebGPU requires rasterization, then our MSL vertex shaders can't return void.

§5.2.3.3, "Vertex Function Output Attributes", says:
> If the return type of a vertex function is not void , it must include the vertex position. If the vertex return type is `float4`, then it always refers to the vertex position, and the `[[position]]` attribute must not be specified. If the vertex return type is a structure, it must include an element declared with the `[[position]]` attribute.

So if our MSL vertex shaders can't return void, they're going to have to return the position somewhere, as @jrprice said.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-20-Minutes#require-that-vertex-shaders-return-a-position-1567">WGSL meeting minutes 2021-04-20</a></summary>



*   MM: Makes sense to start this direction, can add flexibility later. No one’s begging for it, let’s be strict for now.


</details>
