### ISSUE TITLE
Should texture coords (sampler address modes) be u,v,w or s,t,r?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#157]
s,t,r goes out of order (alphabetically), whereas u,v,w does not. For that reason I prefer u,v,w. Especially in the IDL and autocomplete where they will appear as rAddressMode, sAddressMode, tAddressMode (z, x, y).

* s,t,r: Metal, OpenGL
* u,v,w: D3D12, Vulkan

cc #73

**Comment by Kangz** [comment]
UVW gets my vote because it is in order alphabetically :)

**Comment by RafaelCintron** [comment]
I vote for U,V,W with 0,0 being in the top, left of the texture.

**Comment by devshgraphicsprogramming** [comment]
I vote for 0,0 being the same as Vulkan and D3D12

**Comment by kvark** [comment]
To clarify, `same as Vulkan and D3D12` is equivalent to "top, left of the texture", and I agree on UVW.
