### ISSUE TITLE
WebGPU should validate that storageTexture bindings have a single mip level.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1576]
For example this `textureLoad` overload doesn't have a `level` parameter:

```rust
textureLoad(t : [[access(read)]] texture_storage_2d<F>, coords : vec2<i32>) -> vec4<T>
```

Shouldn't it instead be:

```rust
textureLoad(t : [[access(read)]] texture_storage_2d<F>, coords : vec2<i32>, level : i32) -> vec4<T>
```

Looking at the Vulkan and SPIRV specifications I don't see anything that would prevent this. This was discussed in https://github.com/gpuweb/gpuweb/pull/1032 where folks seemed to read the SPIRV spec as disallowing the `LOD` image operand for `OpImageRead` but that doesn't seem to be the case.

**Comment by alan-baker** [comment]
Metal has several restrictions which prevent this. For example, texture writes on 2D textures must use a lod of 0 on macOS according to the spec.

**Comment by Kangz** [comment]
Ok thanks for the clarification! This means that in the WebGPU specification we should validate at `GPUBindGroup` create that storage texture bindings contain a single mip level. Changing the title to reflect this.

**Comment by kvark** [comment]
@Kangz alternatively, we'd specify WGSL to say that only `level = 0` is permitted at this time, while leaving the BGL spec as is.

**Comment by Kangz** [comment]
So the argument would be added but  would have to be a "constexpr 0"?

**Comment by kvark** [comment]
I don't think it has to be "constexpr". This is no different than doing a `textureLoad` from a regular texture and specifying the level that the texture doesn't have. We have to handle this anyway. one way or another.

**Comment by Kangz** [comment]
My understanding wast that for `textureLoad` and `textureStore` we would rely on the robust access behavior defined in the various graphics APIs. This means that we must require that the view has 1 mip level or require a constexpr 0, otherwise the robust access would allow access to the other levels.

**Comment by kvark** [comment]
@Kangz do we have any investigation about robust texture loads in the native API? The RBA feature doesn't cover textures.

**Comment by Kangz** [comment]
I thought I saw one before that mentioned Vulkan's invalid texels and [texel replacement](https://www.khronos.org/registry/vulkan/specs/1.2/html/vkspec.html#textures-texel-replacement) but can't find it. @alan-baker or @ben-clayton was it an investigation that one of you produced?

**Comment by Kangz** [comment]
Upping this, @ben-clayton I vaguely remember you did a texture robustness investigation when building the proposal for texture builtins. Do you have it somewhere?

**Comment by ben-clayton** [comment]
Afraid not - I put together [this document](https://github.com/ben-clayton/misc/blob/main/shader-texture-functions.md) that mapped the backend texture intrinsics, but I didn't get as far as robustness.

**Comment by Kangz** [comment]
Robustness discussions is being added by @alan-baker in #1906.

Looking at the UAV DESC in D3D12, there is no way to describe a mip level range, only a single mip level to use:

```c
typedef struct D3D12_TEX3D_UAV {
  UINT MipSlice;
  UINT FirstWSlice;
  UINT WSize;
} D3D12_TEX3D_UAV;

typedef struct D3D12_TEX2D_ARRAY_UAV {
  UINT MipSlice;
  UINT FirstArraySlice;
  UINT ArraySize;
  UINT PlaneSlice;
} D3D12_TEX2D_ARRAY_UAV;
```

Contrast this with SRVs that have a `MostDetailedMip` member in the desc:

```c
typedef struct D3D12_TEX3D_SRV {
  UINT  MostDetailedMip;
  UINT  MipLevels;
  FLOAT ResourceMinLODClamp;
} D3D12_TEX3D_SRV;

typedef struct D3D12_TEX2D_ARRAY_SRV {
  UINT  MostDetailedMip;
  UINT  MipLevels;
  UINT  FirstArraySlice;
  UINT  ArraySize;
  UINT  PlaneSlice;
  FLOAT ResourceMinLODClamp;
} D3D12_TEX2D_ARRAY_SRV;
```

I think we should add validation in the WebGPU API, but have no opinion for the WGSL change.
