### ISSUE TITLE
Replace the arrow token for functions with a colon

### ISSUE THREAD

**Issue by jespertheend** [gpuweb/gpuweb#1577]
This would change the following:
```
fn main() -> void {

}
```
into the following:
```
fn main() : void {

}
```

I'm not sure if this has been discussed elsewhere, perhaps there's a good reason why arrows work better here. Parsing might get more difficult because of clashes with `var` and `const` types maybe?

But `->` feels a bit out of place to me. Since colons are already used for `var` and `const` types, it seems like a better fit. And this would make the sytax similar to typescript.

**Comment by jespertheend** [comment]
Ah thanks, I wasn't  aware of that issue. Those are some good points. `->` seems like the way to go.

**Comment by dneto0** [comment]
Right.  Additionally, the WGSL spec uses

> *e* : *T*

Syntax as a type assertion, i.e. a fact that expression e is in type T.

See https://gpuweb.github.io/gpuweb/wgsl.html#type-assertion

If we used colon in the way suggested, that would confuse the return type of a function with type of the function itself.  That would be confusing.

Thanks for the suggestion, though
