### ISSUE TITLE
Support mix(vec, vec, f32)

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1588]
Spawned from https://github.com/gpuweb/gpuweb/issues/1520#issuecomment-809908102
In GLSL, you can say `mix(vec4(), vec4(), 0.5)`. Do we want WGSL to support this?

**Comment by dneto0** [comment]
HLSL has [lerp](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-lerp), which requires the three operands have the same type, which also determines the result type.

I don't think we need this.

**Comment by ben-clayton** [comment]
> HLSL has lerp, which requires the three operands have the same type, which also determines the result type.

Actually HLSL is like mix, where the interpolant can be a scalar:
http://shader-playground.timjones.io/3f3fce907ade01a5443e9ec6b95104b1

In my experience as a graphics programmer, this is an extremely common usage pattern, and I'd strongly vote for supporting this.

**Comment by dneto0** [comment]
Oof.   "What the implementation supports" > "What the documentation says".

Okeydokey, I'm fine adding it.

**Comment by magcius** [comment]
That's simply because scalars can be implicitly cast to vectors in HLSL. e.g. `float3 foo = 1.5;` is equivalent to `float3 foo = float3(1.5, 1.5, 1.5);`

If we don't that rule in HLSL, then I'd add a scalar override to `lerp`.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-20-Minutes#-support-mixvec-vec-f32-1588-">WGSL meeting minutes 2021-04-20</a></summary>



*   Yes, add this overload


</details>
