### ISSUE TITLE
DepthStencilStateDescriptor doesn't specify that "back" and "front" are for stencil

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#159]
It's weird that `depthStencilStateDescriptor.back.compare` doesn't specify that it's for stencil. It should probably be `.stencilBack.compare` (or maybe `.back.stencilCompare`).

current:
- WebGPUDepthStencilStateDescriptor
  - depthWriteEnabled
  - depthCompare
  - front
    - compare
    - stencilFailOp
    - depthFailOp
    - passOp
  - back
    - compare
    - stencilFailOp
    - depthFailOp
    - passOp
  - stencilReadMask
  - stencilWriteMask

proposal: `front` -> `stencilFront`, `back` -> `stencilBack`.

An alternative would be to split even further, but probably goes too far:
- WebGPUDepthStencilStateDescriptor
  - depth
    - writeEnabled
    - compare
  - stencil
    - front
      - compare
      - stencilFailOp
      - depthFailOp
      - passOp
    - back
      - compare
      - stencilFailOp
      - depthFailOp
      - passOp
    - readMask
    - writeMask

**Comment by devshgraphicsprogramming** [comment]
I think there also exist configurable stencil reference values too.

**Comment by Richard-Yunchao** [comment]
> I think there also exist configurable stencil reference values too.

We have already had setStencilReference() API in WebGPURenderPassEncoder. See the investigation at https://github.com/gpuweb/gpuweb/issues/118.

**Comment by kvark** [comment]
This would be good!
Also, if we do have "stencil" in the context of operations, we should rename "stencilFailOp" -> "failOp", which would make it match both Vk and D3D12 (at least)
