### ISSUE TITLE
"workgroup_size" builtin is not supported on some Apple platforms

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1590]
The builtin translates to `dispatch_threads_per_threadgroup`, which is available on "All OS: Since Metal 1.0" according to the Metal language spec. However, actually using it gives me the following error:
> <stdin>:12:19: error: 'dispatch_threads_per_threadgroup' attribute requires Metal language standard macos-metal2.0 or higher
, type2 wg_size [[dispatch_threads_per_threadgroup]]

**Comment by dneto0** [comment]
I'm curious.  Can you try [reqd_work_group_size](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/functionQualifiers.html) ?

**Comment by jrprice** [comment]
We already have to polyfill this for HLSL, so doing it for MSL as welll to avoid this issue doesn't seem particularly onerous.

That said, I'm not convinced that this builtin should exist in WGSL at all. The shader author has already specified the workgroup size inside their shader as arguments to the `workgroup_size` attribute (either as literals or named constants), so they could just use those values directly, which in many cases reads better than using this builtin.

**Comment by kvark** [comment]
Right, we could just use this constant value for the workgroup size instead of taking it as a built-in. Having built-ins as arguments to EP functions really helps here.

**Comment by kvark** [comment]
I suppose we can indeed remove it then. I was concerned about the SPIRV to WGSL path in the absence of this built-in, but I think it's going to be doable.

**Comment by jdashg** [comment]
Closed by #1771.
