### ISSUE TITLE
GPUCompilationMessage: Specify linePos units, consider span

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1597]
- The units of linePos should be defined (this may be implicit from how WGSL parses characters, but should be mentioned here too) - i.e. bytes, codepoints, grapheme clusters, etc.
- Should there be a span (linePosStart/linePosEnd or linePos/spanLength) for the error?

For reference, GPUCompilationMessage was added in #646.

**Comment by kainino0x** [comment]
units: Most likely should be the same units JavaScript uses for indexing (which I _think_ is codepoints)

span: Could be any of:
- (startLineNum/startLinePos) to (endLineNum/endLinePos)
- startPos to endPos (no line numbers, just offsets)
- (startLineNum/startLinePos) to (that + spanLength)

**Comment by kainino0x** [comment]
An argument I just came up with in favor of `startPos` and `endPos`: sidesteps any ambiguity about the meaning of "line number", e.g. "what line is `B` on?", in `A\nB`, `A\rB`, `A\r\nB`, `A\n\rB`, etc. There is no ambiguity if you use character offsets as they're offsets into an array, e.g.

```
> Array.from('\r\n \r\n')
[ '\r', '\n', ' ', '\r', '\n' ]
```

**Comment by Kangz** [comment]
What's a bit unfortunate is that it requires a bunch more work from users of the API to either remember the places of all the newlines in the sources, or walk it on each compilation message to find it. Because the position and content of messages is very non-normative, maybe it's ok if there's some slight ambiguity in what the positions are.

**Comment by kainino0x** [comment]
I think that depends a lot on the app. For example if I just have the raw shader string it's easier to extract the span with offsets than it is with lines. (`source.slice(start, end)` vs e.g. `const lines = source.split(/\r?\n/);`, take part of the first line, all of the intermediate lines, and part of the last line, and concatenate them back together)

**Comment by kainino0x** [comment]
> units: Most likely should be the same units JavaScript uses for indexing (which I _think_ is codepoints)

`String.prototype[@@iterator]()` (i.e. what you get if you iterate or use `Array.from()`) iterates over _codepoints_. In the case of surrogate pairs, you get one item for the pair. In the case of unpaired surrogates, you get one item for the unpaired surrogate. (Surrogates also ["have"](https://en.wikipedia.org/wiki/UTF-16#U+D800_to_U+DFFF) codepoints.)

The indexing operator (and `slice`, `substr`, `substring`, etc.), however, operate in UCS-2 (/UTF-16) code _units_, i.e. surrogate pairs appear as two items.

**Comment by kainino0x** [comment]
WGSL strings cannot have unpaired surrogates because it the IDL defines it as a [USVString](https://heycam.github.io/webidl/#idl-USVString).

**Comment by kainino0x** [comment]
Resolution:
- provide both line/linepos and absolute pos, applications can pick which they want.
- provide "length" to indicate the distance to the end of the span (can be 0, and can end up spanning multiple lines).
- Units should be code units, because they're random-access (doesn't require iterating like code points) and people usually use slice/substr/substring.

**Comment by kainino0x** [comment]
Closed in #1643
