### ISSUE TITLE
Request to Apple open sourcing Metal shader compiler for WebGPU..

### ISSUE THREAD

**Issue by oscarbg** [gpuweb/gpuweb#16]
Hi,
interesting that current gpuweb WebKit patch uses metal shaders.
For me this might be even a good shader language to use in WebGPU, but then will be time for requesting Apple to open source Metal shader compiler stack like Microsoft has done recently with current HLSL shader compiler that translates to his new intermediate format DXIL.. the new Microsoft compiler uses LLVM/Clang stack and seems Apple Metal shader compiler too.. 

So briefly here (may be not the current best place to ask), with Khronos LLVM IR<->SPIR-V translator and DXIL open source only modern shader language compiler not open source is Metal and would make sense to open source it for WebGPU implementations on other OSes and even make easier porting modern macos/IOS games using Metal to other OSes..
Makes sense?
thanks..

**Comment by Kangz** [comment]
This is a request to Apple, not to the W3C community group so it would be better to file it to Apple directly. A link that was mentioned in another issue is [bugreporter.apple.com](bugreporter.apple.com).

**Comment by grorg** [comment]
+1 to @Kangz's comment - please file at bugreporter.apple.com

I'll also note that there are some open source tools that do translations between shaders in different languages. This group might also start work on its own tool. But in that case it's likely it would be outputting Metal Shading Language, and/or GLSL, HLSL, SPIR-V, DIXL, etc, whereas you mentioned accepting Metal Shading Language.
