### ISSUE TITLE
Use the same interface for both GPUAdapter features and GPUDevice features

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#1613]
From https://gpuweb.github.io/gpuweb/#issue-414eeb44

In https://github.com/gpuweb/gpuweb/pull/1098 `GPUAdapter.features` was converted to use a `setlike` interface in order to allow privacy budget tracking. `GPUDevice.features` doesn't need the same privacy budget monitoring, because it can only contain feature names that the developer explicitly reqested, but it may still be preferable from an ergonomics standpoint to use the same interface in both places.

As it stands today, you have an odd disconnected in how you access the two interfaces:

```js
if(adapter.features.has("feature-name")) {
  // ...
}

if (device.features.indexOf("feature-name") != -1) {
  // ...
}
```

If we were to make both of these use the same interface, it would probably be a good idea to rename the interface from `GPUAdapterFeatures` to something more generic. The spec issue suggests `GPUSupportedFeatures`, which sounds fine to me.

**Comment by kvark** [comment]
> it may still be preferable from an ergonomics standpoint to use the same interface in both places.

This needs some clarification. I don't think there is going to be code that expects adapter features and device features to be the same.
