### ISSUE TITLE
Should WGSL expose the concept of coherent buffers?

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#1621]
Vulkan SPIR-V and HLSL both support marking buffers as coherent. In SPIR-V, the `Coherent` decoration can be applied to variables or structure members. In HLSL the `globallycoherent` modifier can be applied to some buffer declarations.

In the Vulkan memory model, coherent is replaced by private and non-private memory accesses. Non-atomic memory accesses are private by default. This mean they cannot be location ordered with a system-synchronizes-with operation. That boils down to private memory operations not being visible during the operation of a shader between different invocations. Workgroup memory operations are implicitly coherent.

I think we probably expect that read/write storage buffers should be capable of being synchronized between invocations so I would expect we want to say that something to the effect that memory operations are "non-private" (in whatever terms WGSL ends up using) and that translations to SPIR-V and HLSL should mark read/write storage buffers as coherent. Given MSL's inheritance from C++, I would expect MSL to default to coherent buffers, but I have not tested this.

**Comment by alan-baker** [comment]
Implementations could optimize adding the coherent qualifiers if shader does not contain any barriers since they would be necessary to perform the required synchronization (since WGSL only has relaxed atomics).

**Comment by kvark** [comment]
What about storage images? SPIR-V's Coherent also applies to them.

> Implementations could optimize adding the coherent qualifiers if shader does not contain any barriers since they would be necessary to perform the required synchronization (since WGSL only has relaxed atomics).

So this means all storage buffers in VS and FS stages are guaranteed to be coherent?
Is there an associated performance cost to this?

**Comment by alan-baker** [comment]
Given that we can't promise image synchronization using barriers currently, I would think there wouldn't be a point yet in marking write only storage images as coherent.

There is a potential cost to coherence. That's why we should consider whether we want something to be always coherent or exposing the ability to mark which buffers (and in the future, images) as coherent. Also the coherent decoration does not guarantee coherence between different shader stages. That is left to the API (e.g. a domain operation in Vulkan). So the API needs to have a stance about that aspect of visibility of memory and whether it should be exposed of explicitly or implicitly.

**Comment by kvark** [comment]
Ok, it sounds to me that we don't have to have this, but can follow up with a `[[coherent]]` attribute at some point.

**Comment by dneto0** [comment]
> "Those writes are visible to other threads via the usual memory consistency and coherency rules (at present, only atomics
will be coherent, and only relaxed consistency is supported)."

I think that's too thin evidence to go on.  In my experience the word "coherent" is used for too many different specific meanings.  To me that snippet reads like it is a statement about a single operation providing specific guarantees; without the need for other operations; that is "self-coherence" if you will.

> My read on this is that to emulate the GLSL coherent buffer qualifier, all loads and stores (ie through array indexing) should be translated into atomic load and store functions in Metal. 

I would be surprised if this were necessary.

I share @alan-baker's expectation that for MSL shared data areas, the operations are always non-private (in Vulkan memory model terms). So you don't have to annotate or mark up anything in order for data to be available and visible after you have done the necessary barrier synchronization, or allowed the shader to terminate (and have the writes complete).

**Comment by litherum** [comment]
Marking as V1 because V1 will have barriers, so we need to determine whether buffers are coherent-by-default or are coherenty-by-opt-in.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-16-Minutes#should-wgsl-expose-the-concept-of-coherent-buffers--issue-1621">WGSL meeting minutes 2021-11-16</a></summary>



* Related to #2055?
* AB**: **Indirectly related to 2055.  The way the mapping works, is all buffers are “coherent” by default. (Tint doesn’t implement that yet).  Question: do we want option to be non-coherent buffers, which is the default in OpenGL and D3D.
* AB: I think Metal is always coherent?
* MM: Discussed with Metal team. It’s maybe exactly correct to say that buffers are always coherent. Don’t need atomics to pass info within a workgroup..  Correct prog without atomics to do normal writes to device buffer and workgroup memory, then do a barrier with correct flags.
* AB: That matches what mapping says now.  And later fix says you can’t do inter-workgroup communication.
* MM: That’s correct for Metal.
* AB: GL and D3D make it optional for “coherent” to be specified, as there is some cost to it.  Coherent by default does match programmer expectation, but it’s up to us whether it’s optional.
* MM: coherent by default is the right design for WebGPU for now.  Could consider extension to allow non-coherent for buffers. But not make the cut for MVP.
* JG: Would want to have to go out of your way to declare it as not coherent. (likes “incoherent” , haha.)
* AB: Could call it “private?
* **JG: sounds like consensus: coherent by default, and consider late an extension to allow non-coherent.**


</details>

**Comment by devshgraphicsprogramming** [comment]
> Workgroup memory operations are implicitly coherent.

Only `shared` memory operations, if you do reads/writes to SSBO you need a memory barrier (`memoryBarrierBuffer` or `groupMemoryBarrier`) to ensure **invocations from the same workgroup** see each other's operation.

**Comment by devshgraphicsprogramming** [comment]
> Marking as V1 because V1 will have barriers, so we need to determine whether buffers are coherent-by-default or are coherent-by-opt-in.

Marking buffers/variables as `coherent` will disable caching/write combining (if they exist/are implemented by underlying driver).

**Comment by devshgraphicsprogramming** [comment]
Btw, while GLSL doesn't support marking individual accesses/variables as coherent and others as not, SPIR-V kinda does.

**Comment by alan-baker** [comment]
https://gpuweb.github.io/gpuweb/wgsl/#private-vs-non-private makes both read and write accesses NonPrivate which effectively means coherent.
