### ISSUE TITLE
consider adding: acosh, asinh, atanh

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1622]
These are functions of float scalar or vector.
* SPIR-V has GLSL extended instructions for these, e.g. GLSLstd450Acosh
* MSL has acosh, asinch, atanh
* HLSL and DXIL do not support these directly.

I expect WGSL won't support these, but would like an affirmative judgement of that.

**Comment by kvark** [comment]
Having this on 2/3 backends, while having a path to polyfill, seems rather compelling.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-13-Minutes#consider-adding-acosh-asinh-atanh-1622">WGSL meeting minutes 2021-04-13</a></summary>




*   AB: Polyfill would need care about precision
*   TR: +1 for builtin, might be opportunities in the future
*   JG: Let’s speculatively spec this



</details>

**Comment by litherum** [comment]
What’s the polyfill path?

**Comment by kvark** [comment]
For `acosh`, for example, https://mathworld.wolfram.com/InverseHyperbolicCosine.html gives a few equations.

**Comment by dneto0** [comment]
I also found this reference:  https://www.johndcook.com/blog/2021/01/05/bootstrapping-math-library/ 

It has a different formulation for arccosh specifically.  I'm not up to speed on whether one is better than the other in terms of error properties, speed, or whatever.

**Comment by dneto0** [comment]
Vulkan says their errors are "inherited from" specific polyfills. (!)



asinh(x)  Inherited from log(x+sqrt(x×x+1.0)).
acosh(x)  Inherited from log(x+sqrt(x×x−1.0)).
atanh(x)  Inherited from log(1.0−x1.0+x​)×0.5.
