### ISSUE TITLE
consider adding matrix determinant

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1623]
The determinant function acts on any square matrix.

There is common support for square matrices over f32 components:
* SPIR-V: Use extended instruction GLSL.std.450 Determinant
* MSL has determinant standard library function
* HLSL has determinant builtin function.
* DXIL does not have direct support.  I expect a simple polyfill is sufficient.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-13-Minutes#consider-adding-matrix-determinant-1623">WGSL meeting minutes 2021-04-13</a></summary>




*   (yes, add it)



</details>

**Comment by alan-baker** [comment]
https://gpuweb.github.io/gpuweb/wgsl/#matrix-builtin-functions already lists it. Suggest we close this issue.

**Comment by dneto0** [comment]
It's been added.
