### ISSUE TITLE
Add transpose() builtin

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1625]
It's mentioned in #667, and I think all the backend languages support this. Can we have it in WGSL?
Also see https://github.com/gpuweb/gpuweb/pull/1611#discussion_r610833584

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-20-Minutes#add-transpose-builtin-1625">WGSL meeting minutes 2021-04-20</a></summary>



*   MM: yes, please
*   JG: agreed


</details>
