### ISSUE TITLE
What image formats are supported? What sampling options?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#163]
WebGPU needs to pin down the list of supported image formats and sampling configurations.

Somewhat related, but not quite the same:

- #66 : 3 channel formats (closed)
- #79 : Investigation: Texture View

**Comment by dneto0** [comment]
If image writes will not be supported, then the shader programming model does not need a texture fence (OpMemoryBarrier in SPIR-V with Image memory access).  See #232

**Comment by dneto0** [comment]
Discussed in MountainView F2F that read-write images are required.

Minutes: https://docs.google.com/document/d/1HR9vPk48-lhzHAsyF57QzjKMmi0gQHfSXMmyqZuFWkc/edit#heading=h.hp3f2zbslxr9

**Comment by Kangz** [comment]
The list of image formats and their capabilities has been added to the spec.
