### ISSUE TITLE
Reduce blocking on shader compilation

### ISSUE THREAD

**Issue by jdarpinian** [gpuweb/gpuweb#1641]
The non-async version of createRenderPipeline may cause rendering to block on shader compilation. It makes sense that WebGPU rendering would block, but it will also end up blocking rendering of *all* DOM updates, other canvases, and requestAnimationFrame at least, possibly more.

Perhaps we could reduce the amount of blocking by specifying that the use of non-async createRenderPipeline may cause the synchronization of WebGPU rendering and DOM updates to be temporarily broken, so DOM updates can continue to be rendered as shaders compile.

We can keep calling requestAnimationFrame to update other JS-driven animation, though we would need some kind of backpressure mechanism to keep applications from queueing dozens of frames while rendering is blocked. For example, we could make GPUSwapChain.getCurrentTexture fallible.

**Comment by kainino0x** [comment]
I love this idea, it could remove a major source of jank for users without sites having to use desynchronized methods like transferControlToOffscreen. @RafaelCintron @jdashg in particular for feedback.

**Comment by jdarpinian** [comment]
Consensus seems to be that this is too hard to implement and that apps should just use the async options that exist when it matters. Also we can always revisit this later if necessary.
