### ISSUE TITLE
GPUImageCopyTexture misses arrayLayer

### ISSUE THREAD

**Issue by Reon90** [gpuweb/gpuweb#1642]
Nowadays there is no opportunities of rendering to 3D, Cube or Array textures.
It means, such issue blocks a lot of rendering techniques such as IBL, etc.

**Comment by Kangz** [comment]
The notion of "depth" and "arrayLayer" is merged in `GPUOrigin3D/GPUExtent3D`. When copying from / to images you can specify the array layer in `GPUImageCopy.origin.z`.

**Comment by Reon90** [comment]
@Kangz thank you, it's enough.
