### ISSUE TITLE
determine data layout rules inside buffers

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#166]
HLSL has several kinds of buffers, with different tradeoffs.  So does Vulkan.

HLSL exposes ConstantBuffer, StructuredBuffer, and RWStructuredBuffer and others.

From https://github.com/gpuweb/WHLSL/issues/293   :

> DXC's SPIR-V backend maps ConstantBuffers to Vulkan's uniform buffer object (UBO), and maps StructuredBuffer to Vulkan's storage buffer (SSBO = shader storage buffer object, the name from OpenGL). Compared to SSBOs, UBOs are faster, smaller, and have more restrictive layout rules.

> For traditional graphics environments, that's an important tradeoff that had to be exposed at the shader language level.

Also UBOs are read-only but SSBOs are read-write.

WebGPU has to decide:
- are the performance and flexibility tradeoffs big enough that WebGPU developers will need to deal with the distinction?  That is, should the difference between UBOs and SSBOs be exposed at the WebGPU shader programming model?
- related question:  what are the layout rules for inside of a buffer (of either variety)

The layout rules in Vulkan have several variations, which reflect (1) evolution of hardware capabilities and tradeoffs over time, and (2) a willingness to relax the rules as applications demand it but with performance tradeoffs.
First there was essentially std140 and std430 from GL days.  Then there was a demand for "relaxed block layout" (see VK_EXT_relaxed_block_layout in https://github.com/KhronosGroup/Vulkan-Docs/blob/master/chapters/interfaces.txt ).  And now there is the even more relaxed "scalar block layout" (see in same interface.txt file).

WebGPU has to pick a set of rules, cognizant of the tradeoffs: performance vs. flexibility vs. complexity vs. installed base.

Note: 
- In WebGPU execution env for SPIR-V I took a guess as to what we'd decide.  See https://github.com/gpuweb/spirv-execution-env/blob/master/execution-env.md#layout 
- WHLSL has not yet addressed layout.  https://github.com/gpuweb/WHLSL/issues/8

**Comment by devshgraphicsprogramming** [comment]
AFAIK WebGPU will either accept SPIR-V or WHLSL or both.

You'll most probably have to stick to std140 for uniforms/constants though.
Because I'd imagine the WebGPU group would want to keep large compatibility, I doubt adopting scalar layouts as the core behaviour will happen.

**Comment by magcius** [comment]
Is there anything that cannot support scalar layout at this point, except for Broadcom? I thought they were the only vendor without support.

**Comment by Kangz** [comment]
@dneto0 I think this issue can be closed now since the data layout discussion has evolved and landed in the WGSL spec.
