### ISSUE TITLE
wgsl: an entry point must not be the target of a function call

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1663]
I think this is justified: the special behaviours / annotations of pipeline inputs and outputs would get very confused, I think.

**Comment by kvark** [comment]
Fully agree. The `[[stage]]` on functions should be similar to `[[block]]` on structures, making them top-level in the function and type hierarchies respectively.

**Comment by litherum** [comment]
Agreed.

**Comment by dneto0** [comment]
@alan-baker fixed this with #1674
