### ISSUE TITLE
Support NumWorkgroups builtin

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1671]
Does it make sense to support this? Some of the SPIR-V shaders rely on it.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-04-27-Minutes#support-numworkgroups-builtin-1671">WGSL meeting minutes 2021-04-27</a></summary>



*   DM: It is in SPIRV, is it also in MSL?
*   MM: yes
*   AB: Also in HLSL WorkgroupID 
*   DM: Related: [https://github.com/gpuweb/gpuweb/issues/1590](https://github.com/gpuweb/gpuweb/issues/1590) 
*   DN: Interested in finding out more about status here
*   MM: No strong pref, emulation would be fine
*   DM: Think should keep it, but need clarification from apple on when+where this is available
*   GR: (spirv-cross polyfills this on hlsl)
*   MM: Should we implement this or require users to? It seems like as a builtin, it would be at least as fast as a user polyfill
*   DM: Does the system ever decide this?
*   MM: Not today, but we might (probably will) want to add something like this in the future
*   KN: From tensorflow.js, originally did 1x1x1 and expected compiler to batch them, but it doesn’t do it automatically. Would be good to help users out here, even if we can tell them “oh just use 8, 8 is good”
*   DM: Don’t know how they’re using workgroup memory, but we can estimate based on register usage
*   AB: Not sure how you’d estimate reg usage. Could poll vulkan and offer something to authors, e.g. make it a multiple of subgroup size.


</details>

**Comment by kvark** [comment]
Also found #920
