### ISSUE TITLE
Define a MIME type

### ISSUE THREAD

**Issue by annevk** [gpuweb/gpuweb#1682]
As mentioned by Maciej in #565, a MIME type needs to be minted as well. Presumably something like `application/wgsl` or perhaps `text/wgsl`.

**Comment by dneto0** [comment]
I'm really not authoritative on this.  But I think it should be `application/wgsl` in analogy to `application/javascript`.

**Comment by litherum** [comment]
Do we know what GLSL's mime type is?

**Comment by kainino0x** [comment]
There is not one. `text/plain` is suitable; sometimes people use things like `<script type="x-shader/x-vertex">`.

**Comment by annevk** [comment]
Note that JavaScript is `text/javascript` unlike what is stated above. See HTML and the upcoming https://datatracker.ietf.org/doc/html/draft-ietf-dispatch-javascript-mjs.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-10-05-Minutes#define-a-mime-type-1682">WGSL meeting minutes 2021-10-05</a></summary>



* DN: I looked at the registry [https://www.iana.org/assignments/media-types/media-types.xhtml](https://www.iana.org/assignments/media-types/media-types.xhtml) and could not find GLSL, C, or many other languages. CLosest I could find was application/javascript.  That’s a close enough analog to suggest application/wgsl.  But I’m no expert.
* **JG: Let’s do application/wgsl until someone says we’re wrong.**


</details>

**Comment by annevk** [comment]
If you want to follow JavaScript, definitely go with `text/wgsl`. The 2006 RFC will be replaced by the draft I mentioned in due course. Hopefully soon.

And unlike JavaScript, require everyone use UTF-8 for interchange from the start to avoid pain later.

Happy to help fill out the template if there's anything unclear. Note that you can attach this to your document (see, e.g., https://html.spec.whatwg.org/#application/microdata+json), but you'll still need to email IANA to make it so.

**Comment by dneto0** [comment]
Following the procedures in  https://datatracker.ietf.org/doc/html/rfc6838, I created a *draft* of the Media Type Registration, with my best estimation of what should go in it.

Next steps:
1. Review by the W3C WebGPU community group
2. Send the draft to media-types@iana.org  for preliminary feedback.  This is a strongly recommended step.
3. After initial review passes, send the registration to  iana@iana.org or file it via the form at https://www.iana.org/form/media-types

**Comment by dneto0** [comment]
As of November 1, my email to media-types@iana.org is awaiting moderator approval.  (I'm not a member of the list, and so my message needs moderator approval)

**Comment by annevk** [comment]
Note that you can fill out https://www.iana.org/form/media-types as well, but perhaps better to await the results of the email submission now.

**Comment by dneto0** [comment]
I've joined the meda-types@iana.org mailing list, and sent the request for review again.  Hopefully this time it will get through to the list.

**Comment by mehmetoguzderin** [comment]
@dneto0 The W3C document's suggested mailing list registration link's top says:

> This list has been replaced by media-types@ietf.org.

Which can be found https://www.ietf.org/mailman/listinfo/media-types here.

I am not sure but the domain is ietf.org instead of iana.org compared to the document. Maybe sending to media-types@ietf.org email would be more direct?

**Comment by mehmetoguzderin** [comment]
(and when I check the document provided mailing list archives, there are not updates since 2019, whereas the newer mailing list has very recent updates)

**Comment by dneto0** [comment]
I got some reivew feedback..

>  Should we add "For privacy considerations, see [WebGPU] Section 2.2 Privacy Considerations" to the end of the security considerations section?

I'll do that.
