### ISSUE TITLE
Should we be able to pass textures and samplers as function parameters?

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#1695]
This was discussed in the 2021-04-28 office hours and relates to #1674.

An implementation needs to know which samplers could be used with which textures in order to validate a pipeline. It would be useful for shader authors to be able to pass samplers and textures as function parameters, but doing so would require analyzing the program to determine the possible pairings. So there are two main options: disallow handle parameters or analysis the usage and validate it.

The analysis looks at functions in topological order (currently equivalent to program order). For each texture sampling built-in function, trace the texture and sampler arguments to global variables or function parameters and record the pair for the function. For each function call in the function, if there are records for texture/sampler pairs, trace the corresponding parameters back to global variables or function parameters. When the analysis arrives at an entry point, the all function parameters can be fully resolved to global variables. These pairs can be reflected to the API and analyzed at pipeline creation to validate the correct usage.

Example:
```
// Each call to foo, adds a pair for (t, s).
fn bar(texture2d<f32> t, sampler s) -> vec4<f32> {
  return textureSample(t, s, vec2<f32>(0.0, 0.0));
}

// Each call to bar adds the following pairs:
//  * (t1, s1)
//  * (t2, s2)
//  * (t1, s2)
fn foo(texture2d<f32> t1, texture2d<f32> t2, sampler s1, sampler s2) -> vec4<f32> {
  var ret : vec4<f32>;
  // ...
  if (c1) {
    ret = bar(t1, s1);
  } elseif(c2) {
    ret = bar(t2, s2);
  } else {
    ret = bar(t1, s2);
  } 

  return ret;
}

[[group(0), binding(0)]] var tex1 : texture2d<f32>;
[[group(0), binding(1)]] var tex2 : texture2d<f32>;
[[group(0), binding(2)]] var samp1 : sampler;
[[group(0), binding(3)]] var samp2 : sampler;

// frag1 utilizes the following pairs:
//  * (tex1, samp1)
//  * (tex2, samp2)
//  * (tex1, samp2)
[[stage(fragment)]]
fn frag1() {
  bar(tex1, tex2, samp1, samp2);
}

// frag2 utilizes the following pairs:
//  * (tex1, samp1)
//  * (tex2, samp2)
//  * (tex2, samp1)
[[stage(fragment)]]
fn frag2() {
  // ...
  if (cond) {
   bar(tex1, tex1, samp1, samp1);
  } else {
   bar(tex2, tex1, samp2, samp1);
  }
}
```

**Comment by dneto0** [comment]
To be concrete about the requirement:
- some texture formats are not filterable
      -  e.g. those with 32-bit float component are not filterable on Vulkan.  See VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT
- a sampler either filters or it does not.  GPUFilterMode is "nearest" or "linear"

That part of sampler and texture configuration is specified in the bind group layout.

Pipeline creation must fail if a shader statically suses non-filterable sampled texture with a filtering sampler.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-05-04-Minutes#should-we-be-able-to-pass-textures-and-samplers-as-function-parameters-1695">WGSL meeting minutes 2021-05-04</a></summary>



*   AB: Do we forbid it, or require a conservative uniformity-analysis-like pass?
*   MM: Leaning towards doing the analysis.
*   MM: Tangent: What would this look like with Modules? Having two shaders that use the same helper function, and have that code only appear in the binary/memory once.
*   JB: Another benefit of analysis is that it’s nice from a user perspective. There may be good reasons to make modules even if it’s just for users
*   MM: We can talk about modules more in the future.
*   DN: Wondered, what the runtime complexity would be here. I think the analysis complexity is feasible given what the limits on resources here are.
*   MM: Like what limits?
*   DN: E.g. 64 texture bind points. If we deal with arrays of these later, could treat each array conservatively as having the same constraints/usages.
*   JG: If we allow conservative analysis, we allow some people (maybe) to footgun, but if we didn’t allow analysis they would have to rewrite their program to make it work. This rewrite would still work with conservative analysis.
*   MM: What would the pessimal program look like? I think it’s not that bad
*   Let’s try for it: Resolved needs spec


</details>

**Comment by litherum** [comment]
This seems worth trying.

**Comment by maierfelix** [comment]
This would be really great to have! Currently I have to do a lot of copy pasting, since I can't really make generalized functions for the filtering of textures

**Comment by ben-clayton** [comment]
Answer: Yes you can.

Updating Alan's code from above to latest WGSL, the following compiles with Tint:

```ts
// Each call to foo, adds a pair for (t, s).
fn bar(t : texture_2d<f32>, s : sampler) -> vec4<f32> {
  return textureSample(t, s, vec2<f32>(0.0, 0.0));
}

// Each call to bar adds the following pairs:
//  * (t1, s1)
//  * (t2, s2)
//  * (t1, s2)
fn foo(t1 : texture_2d<f32>, t2 : texture_2d<f32>, s1 : sampler, s2 : sampler) -> vec4<f32> {
  var ret : vec4<f32>;
  var c1 = false;
  var c2 = false;
  // ...
  if (c1) {
    ret = bar(t1, s1);
  } else if(c2) {
    ret = bar(t2, s2);
  } else {
    ret = bar(t1, s2);
  }

  return ret;
}

@group(0) @binding(0) var tex1 : texture_2d<f32>;
@group(0) @binding(1) var tex2 : texture_2d<f32>;
@group(0) @binding(2) var samp1 : sampler;
@group(0) @binding(3) var samp2 : sampler;

// frag1 utilizes the following pairs:
//  * (tex1, samp1)
//  * (tex2, samp2)
//  * (tex1, samp2)
@fragment
fn frag1() {
  foo(tex1, tex2, samp1, samp2);
}

// frag2 utilizes the following pairs:
//  * (tex1, samp1)
//  * (tex2, samp2)
//  * (tex2, samp1)
@fragment
fn frag2() {
  // ...
  var cond = false;
  if (cond) {
   foo(tex1, tex1, samp1, samp1);
  } else {
   foo(tex2, tex1, samp2, samp1);
  }
}
```

I believe this issue can be closed.
