### ISSUE TITLE
FMod vs FRem semantics

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1696]
WGSL currently has `x % x` described as `OpFMod`.
SPIR-V semantics for OpFMod this is `x - y * floor(x / y)`
Metal semantics for `fmod` is `x - y * trunc(x / y)`, which matches HLSL semantics for `%`, and also SPIR-V semantics for `OpFRem`.

Given the mostly consensus here among the APIs, I suggest we change the semantics of `%` to match. Thus, it should be described as `OpFRem` in SPIR-V.

Thanks @expenses for raising this in https://github.com/gfx-rs/naga/issues/802

**Comment by dneto0** [comment]
Good point.   Looking closer, both MSL and GLSL have % only operating on integer scalars and vectors.
My instinct is to remove % for floating point, and replace it with frem and fmod.

(I haven't worked it out again, but I recall the difference is how to handle mixed signedness of the operands.)

**Comment by dneto0** [comment]
Well there you go:
OpFRem "The floating-point remainder whose sign matches the sign of Operand 1."
OpFMod "The floating-point remainder whose sign matches the sign of Operand 2."

**Comment by dneto0** [comment]
I found this clarifying:

x | y | floor(x/y) | x-y*(floor(x/y)) | OpFMod | trunc(x/y) | x-y*trunc(x/y) | OpFRem
-- | -- | -- | -- | -- | -- | -- | --
5 | 2 | 2 | 1 | 1 | 2 | 1 | 1
5 | -2 | -3 | -1 | -1 | -2 | 1 | 1
-5 | 2 | -3 | 1 | 1 | -2 | -1 | -1
-5 | -2 | 2 | -1 | -1 | 2 | -1 | -1

**Comment by dneto0** [comment]
And what we're left with is a naming mess.

**Comment by dneto0** [comment]
Looks like fmod is in the standard C99 library.  https://en.cppreference.com/w/c/numeric/math/fmod 
And MSL matches that. For fmod(x,y) "The returned value has the **same sign as x** and is less or equal to y in magnitude."

**Comment by dneto0** [comment]
Using different numbers (so it's more clear what's going on)


x | y | floor(x/y) | x-y*(floor(x/y)) | OpFMod | trunc(x/y) | x-y*trunc(x/y) | OpFRem
-- | -- | -- | -- | -- | -- | -- | --
15 | 4 | 3 | 3 | 3 | 3 | 3 | 3
15 | -4 | -4 | -1 | -1 | -3 | 3 | 3
-15 | 4 | -4 | 1 | 1 | -3 | -3 | -3
-15 | -4 | 3 | -3 | -3 | 3 | -3 | -3

**Comment by RobinMorisset** [comment]
btw, JS seems to match HLSL/MSL/C++ here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder (it is FRem).

I would also be ok with David's suggestion to not have '%' and just have two functions with explicit names.

**Comment by litherum** [comment]
So I thiiiiiiink where we ended up in the call today is:

1) Add a function named `fmod()` that has the same semantics as `OpFRem` in SPIR-V. It accepts scalar floats and vectors of floats. Nothing else.
2) Add the `%` operator which only operates on signed and unsigned ints, which has the same behavior regarding negative numbers as `fmod()` does.

**Comment by kvark** [comment]
@litherum MSL, SPIRV (and I think HLSL?) allow `%`/`OpSrem` on vectors of integers. Any reason we don't want this?

**Comment by dneto0** [comment]
* https://gpuweb.github.io/gpuweb/wgsl/#arithmetic-expr already has % for scalars i32, u32, f32, and vectors over i32, u32, f32.  I think the change here is to remove the f32 and vec-of-f32 versions of %, and to add fmod instead.

* Separately, @alan-baker pointed out we should check the semantics of % over signed integral.
Make sure we pick the "right" one.

* In the meeting @pow2clk said (if I recall correctly), that the C standard pins down the behaviour for signs.
I found this note at https://en.cppreference.com/w/cpp/language/operator_arithmetic#Multiplicative_operators

> Note: Until C++11, if one or both operands to binary operator % were negative, the sign of the remainder was implementation-defined, as it depends on the rounding direction of integer division. The function std::div provided well-defined behavior in that case.

**Comment by dneto0** [comment]
Also from [cppreference](https://en.cppreference.com/w/cpp/language/operator_arithmetic#Multiplicative_operators). Since C++11, for integer division `/`:

The quotient is truncated towards zero (fractional part is discarded)."

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-05-04-Minutes#fmod-vs-frem-semantics-1696">WGSL meeting minutes 2021-05-04</a></summary>



*   (To specify is human. To test is divine)
*   We will do an investigation into builtins in MSL and HLSL, and come back to this
*   DN: Because they are sort of named backwards in SPIR-V, I wish I could go back in time to swap them
*   AB: We sometimes choose to polyfill, and these would be easy
*   JG: But is the polyfill that useful?
*   MM: If we only have one of these supported, seems like we should just pick that one
*   TR: HLSL has mod(s) but DXIL doesn’t have builtins for it
*   MM: Proposal: Both `%` and the builtin, which allows us to add both later maybe
*   DN: And that it would be C99 fmod, spir-v OpFRem
*   DM: Why operator? (taste)
*   DN: Weak against float%float because e.g. C doesn’t support that anyway, but not strong feeling.
*   MM: So fmod(floats), and uint/sint %-operator
*   MM to write PR


</details>

**Comment by alan-baker** [comment]
To follow up up on OpSRem and OpSMod, the spec currently says it is OpSMod, but probably shouldn't. Worse than that is that Vulkan specifically says OpSRem and OpSMod with any negative input is undefined.
>For the OpSRem and OpSMod instructions, if either operand is negative the result is undefined.

**Comment by kvark** [comment]
> Worse than that is that Vulkan specifically says OpSRem and OpSMod with any negative input is undefined.

That's fun! We can technically express this in WGSL type system by definining `%` only on unsigned integer types (in addition to floats, perhaps).

**Comment by dneto0** [comment]
#1763 1763 takes @kvark's suggestion to remove % for signed integral.

**Comment by ben-clayton** [comment]
I just tried implementing `%` for floats, and I'm uncertain what the WG has settled on.
Are we keeping `%` for float?

Looking at the meeting notes:
> MM: So fmod(floats), and uint/sint %-operator
> MM to write PR

So operator `%` for two floats is `x - y * floor(x / y)`
This appears to match the current wording of the spec (`OpFMod`). Is this what we've agreed on?

**Comment by ben-clayton** [comment]
@jrprice thinks we've instead settled on removing the `%` operator for floats, and instead we want to add the builtins:

```
fn fmod(f32, f32) -> f32
fn fmod(vecN<f32>, vecN<f32>) -> vecN<f32>
```

Is that right?

If so, I'll draft a PR tomorrow.

**Comment by ben-clayton** [comment]
Moved back from resolved -> to needs discussion, as it's clear we don't agree what the resolved decision was.
@jdashg - Any chance of getting this added to today's Agenda?

**Comment by dneto0** [comment]
From the original report:

> Metal semantics for fmod is x - y * trunc(x / y), which matches HLSL semantics for %,

HLSL does not define the semantics of % when the operands have different sign.   See [here](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-operators#additive-and-multiplicative-operators):

> The % operator is defined only in cases where either both sides are positive or both sides are negative. Unlike C, it also operates on floating-point data types, as well as integers.

But, we have evidence of people using % in the field, getting unexpected results.  So they're using the operator out of spec.    



Fun fact, LLVM's [frem](https://llvm.org/docs/LangRef.html#frem-instruction) instruction matches OpFRem, and says 

> The value produced is the floating-point remainder of the two operands. This is the same output as a libm ‘fmod’ function, but without any possibility of setting `errno`. 

Wikipedia has a table showing how many various programming languages define modulus.  See https://en.wikipedia.org/wiki/Modulo_operation#In_programming_languages 

Notable examples from the table.
* WebAssembly defines a remainder only on integers, and uses truncated quotient always.
* Python defines % for floating point, and uses floored quotient

I'd be fine with having % defined however you want (probably with truncated quotient), but I would prefer to also have two builtins that define the two semantics.

**Comment by ben-clayton** [comment]
Reopening, as @dneto0 has expressed interest in also having `fmod()` and `frem()` builtins.

**Comment by kvark** [comment]
@dneto0 why would we need to expose `OpFMod`?
What I see is - this is an operation that's only available on 1/3 backends. Unless it's actually used/desired by ISVs (1) and it has any performance benefit versus the polyfill (2), it seems straightforward to me that we'd just skip it.

For (1) - since people don't write SPIR-V, and instead write GLSL/HLSL, which do *not* have an analogue to `OpFMod`, their programs aren't expected to use this instruction. I did a quick check on the shader playground, and `%` translates to `OpFRem`, as expected.
For (2) we don't have any data.

**Comment by kainino0x** [comment]
munrocket:
> ![comparison of OpFMod vs OpFRem](https://camo.githubusercontent.com/f7712f4c29953f72340a5b4c06c3fe22fc4fa693520a74b06c9406a0a9a31bf7/68747470733a2f2f692e696d6775722e636f6d2f6f7472766e61322e706e67)
> (from https://en.wikipedia.org/wiki/Modulo_operation#Variants_of_the_definition)

axinging:
> We are working on converting glsl to wgsl in TFJS. In order to convert glsl mod to wgsl, we first use %, but it not work. Then we implement mod as below:
> 
> ```
>   // From https://github.com/tensorflow/tfjs/pull/5589/files
>   fn mod(a : f32, b : f32) -> f32 {
>     return a - b * floor(a/b);
>   }
>   fn modVec4(a : vec4<f32>, b : vec4<f32>) -> vec4<f32> {
>     return a - b * floor(a/b);
>   }
> ```
> 
> Based on our experience, it's straightforward to use % as mod. So we strongly agree % should have its conventional OpFMod behavior

@axinging What was the original GLSL using - `mod()`, I assume? It seems GLSL doesn't define `%` for floats.

Also can you give some info about why you rely on the OpFMod behavior specifically? Is it just generally because you want to port code more directly from GLSL?

**Comment by kainino0x** [comment]
Reopening for discussion

**Comment by axinging** [comment]
> axinging:
> 
> > We are working on converting glsl to wgsl in TFJS. In order to convert glsl mod to wgsl, we first use %, but it not work. Then we implement mod as below:
> > ```
> >   // From https://github.com/tensorflow/tfjs/pull/5589/files
> >   fn mod(a : f32, b : f32) -> f32 {
> >     return a - b * floor(a/b);
> >   }
> >   fn modVec4(a : vec4<f32>, b : vec4<f32>) -> vec4<f32> {
> >     return a - b * floor(a/b);
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Based on our experience, it's straightforward to use % as mod. So we strongly agree % should have its conventional OpFMod behavior
> 
> @axinging What was the original GLSL using - `mod()`, I assume? It seems GLSL doesn't define `%` for floats.
> 
> Also can you give some info about why you rely on the OpFMod behavior specifically? Is it just generally because you want to port code more directly from GLSL?

Yes, if mod and % behave the same, we can port code from GLSL to WGSL more directly.
Below is the use case (Note: the mod in WGSL is implemented by us, to make it the same as GLSL mod):
```
const POW = `
  if(a < 0.0 && floor(b) < b) {
    return NAN;
  }
  if (b == 0.0) {
    return 1.0;
  }
  // For GLSL, use mod.
  return (round(mod(b, 2.0)) != 1) ?
      pow(abs(a), b) : sign(a) * pow(abs(a), b);
  `;
```

```
const POW_WGSL = `
  if(a < 0.0 && floor(b) < b) {
    return f32(uniforms.NAN);
  }
  if (b == 0.0) {
    return 1.0;
  }
  // For WGSL, use mod implemented by us
  if (i32(round(mod(b, 2.0))) != 1) {
    return pow(abs(a), b);
  }
  return sign(a) * pow(abs(a), b);
  `;
```

**Comment by munrocket** [comment]
@axinging I believe it can be fixed like this
```rs
if (i32(round(mod(b, 2.0))) != 1) { // before
if (round(abs(b)) % 2.0 != 1.0) { // after
```

Also I will share my fixes
```rs
// hsv2rgb
mod(c.x * 6.0 + vec3(0.0, 4.0, 2.0), 6.0) // before
fract(vec3<f32>(c.x, c.x + 2./3., c.x + 1./3.)) * 6. // after
```
```rs
return (p + 0.5 * c % c) - 0.5 * c; // before
return p - c * round(p / c); // after
```
```rs
let bn = (atan2(p.x, p.y) % (2. * an)) - an; // before
let bn = (atan2(abs(p.x), p.y) % (2. * an)) - an; // after
```

**Comment by munrocket** [comment]
How this functions disassembles in MSL and HLSL? Should we be restricted by OpFRem semantic because this function exist on hardware level? Seems current specification mixing different conventions for int's and float's.

**Comment by ben-clayton** [comment]
> How this functions disassembles in MSL and HLSL?

See the top of this issue and https://github.com/gpuweb/gpuweb/pull/1913#issuecomment-880112573.
HLSL and MSL have intrinsics that map to `OpFRem`, which is why we went with it.
GLSL is the odd one out here.

**Comment by munrocket** [comment]
Nice to hear it, thanks! So we can count each FLOP just by using current spec. GLSL mod polyfill in WGSL will not give that possibility.

**Comment by kvark** [comment]
> Seems current specification mixing different conventions for int's and float's.

I specifically wanted us to have the *same* behavior for ints and floats. Both should be `OpFRem` today. What is different?

**Comment by munrocket** [comment]
Current spec:
T is i32 or vecN<i32> -> OpSMod -> sign matches the sign of Operand 2
T is u32 or vecN<u32> -> OpUMod -> sign matches the sign of Operand 2
T is f32 or vecN<f32> -> OpFRem -> sign matches the sign of Operand 1
Result sign matches to another operand for floats. Better to create fmod() for consistency.

Also I checked HLSL output in DXBC, seems that fmod just a syntax sugar there and gives 3 vectorised FLOP. Metal IR have such thing as fast_fmod, but I can imagine world when this IR become 3 FLOP eventually.

OpFMod is periodic function which is a good property, also expression `let uv = (xy % vec2<f32>(10.));` gives you tiled texture if you using OpFMod. So in the wild even HLSL/MSL programmers create `#define mod(x, y) (x - y * floor(x / y))` helper sometimes.

**Comment by kvark** [comment]
@munrocket the current spec doesn't reflect the group consensus on integer division. #1830 does, instead.
@dneto0 I think we should just land it.

**Comment by munrocket** [comment]
> the current spec doesn't reflect the group consensus on integer division.

I didn't know that, I am simple man that fixing my WGSL according to spec.
