### ISSUE TITLE
WebGL - WebGPU interop: WebGPU computation API with existing WebGL

### ISSUE THREAD

**Issue by astojilj** [gpuweb/gpuweb#17]
Combining WebGL with WebGPU compute shaders is a specific use case of #18 [WebGL - WebGPU interoperability](https://github.com/gpuweb/gpuweb/issues/18).
It would enable access to general computation API from existing WebGL apps.

**Comment by Kangz** [comment]
This is a bit of a side note. Compute functionalities may also be added directly to WebGL: ANGLE is working towards GLES 3.1 on D3D11 support which a major stepping stone to expose OpenGL ES compute functionality to the Web.

**Comment by grovesNL** [comment]
Interop would be nice to have longer term although I'm not sure it should be required for the MVP.

I think it would be preferable to add compute functionality directly to WebGL through the path @Kangz mentioned, assuming it's feasible in the short to mid term. Sometimes it would be preferable to use WebGL compute functionality even after WebGPU becomes available (i.e. engines that would like to target ES 3.1 as well as WebAssembly compilation).

**Comment by Kangz** [comment]
Closing. We discussed this with the group previously and added copy-interop through canvas. Further proposals can be in new issues.
