### ISSUE TITLE
Attaching the same resource twice

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#170]
If you're able to attach the same resource to the shader to two distinct bind points, you could potentially attach it to two points with different types (e.g. a `Texture2D` and a `RWTexture2D`) at the same time. This could lead to surprising results. We should probably forbid this.

**Comment by Kangz** [comment]
Yes, that's covered by the [usage validation rules](https://github.com/gpuweb/gpuweb/blob/master/design/UsageValidationRules.md) that say that in a render pass a given texture subresource can only be used either as `STORAGE` or a combination of read-only usage.

**Comment by kvark** [comment]
That is to say, we don't have to forbid the same resource to be used as a vertex buffer and a UBO, for example. I think we should just stick to the validation rules and allow the rest.

**Comment by kvark** [comment]
@devshgraphicsprogramming as we've been saying, you have to draw the line *somewhere*. Putting that line into the compute shader code is just much less reasonable (or possible at all) than saying that we at least care about bindings and usage to be correct at the pass/draw granularity.

**Comment by devshgraphicsprogramming** [comment]
My slight contention is that you may hinder programmable blending in this case (unless you have subpass inputs).

**Comment by Kangz** [comment]
Assuming this is resolved, please reopen if it isn't.
