### ISSUE TITLE
WGSL says [[block]] structs can't be members of other structs, but shows an example of this

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#1702]
§4.3.6.2, "Structure Layout Rules", shows an example in which a `[[block]]` struct `A` is used in `[[block]]` struct `B`, as the type of member `e`, and as the element type of an array for member `g`. But the definition of the `block` attribute says, "A structure type with the block attribute must not be: • the element type of an array type • the member type in another structure". (If you're gonna break a rule, break 'em all!)

I think the fix is just to remove the `[[block]]` from `A`.

The next code example has the same issue.

**Comment by ben-clayton** [comment]
You are correct. This was a silly mistake propagated all the way from my initial proposal. We just need to remove `[[block]]` from the inner structure, as you suggested.
