### ISSUE TITLE
Automate publication of WebGPU / WGSL to /TR

### ISSUE THREAD

**Issue by tidoust** [gpuweb/gpuweb#1710]
Raising this issue to track work in this area per https://github.com/gpuweb/gpuweb/pull/1706#issuecomment-832002782

The group resolved to publish specification updates to /TR automatically. To enable this, the deploy workflow needs to be updated. There are multiple ways to do that. I believe that the easiest approach is use the [w3c/spec-prod](https://github.com/w3c/spec-prod/#spec-prod) action that will take care of most steps, including:

- Generation with Bikeshed
- HTML markup validation
- Deployment to GitHub page branch
- and of course publication to /TR

The repo contains two specs, and support for multi-spec repos is still somewhat nascent in spec-prod. We may bump into bugs once in a while.

Deployment to GitHub page branch will need to be completed to cover static and other generated files.

I'll prepare a PR once the documents have been published as First Public Working Drafts.

By the way, I see that the group maintains a script to extract and publish the WebIDL defined in the WebGPU spec:
https://github.com/gpuweb/gpuweb/blob/gh-pages/webgpu.idl

I note that there are tools, integrated with Web Platform Tests, that process specs every 6 hours and that do the same thing:
https://github.com/w3c/webref/blob/master/ed/idl/gpuweb.idl

**Comment by Kangz** [comment]
Nice, thanks for pushing through!
