### ISSUE TITLE
specify behaviour of floating point operations on NaNs

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1711]
For example, builtins like max, min, and clamp have specific behaviour on NaN inputs.
Those should be spelled out.

**Comment by alan-baker** [comment]
Vulkan is quite relaxed by default and says:
>By default, the implementation may perform optimizations on half, single, or double-precision floating-point instructions that ignore sign of a zero, or assume that arguments and results are not NaNs or infinities.

It has entry point wide controls for signed zero, infinity and nan preservation (through shader float controls which I would consider outside the scope of MVP), but they only affect a rather small subset of instructions (notably missing any extended instructions like NMax). My previous experience with empirical testing of Vulkan implementations presents a more optimistic view of what is actually implemented, but it cannot be relied upon according to the spec.

Metal defaults to fast relaxed math (which needn't preserve nans), but that can be disabled as a compiler option.

HLSL [appears to preserve nans](https://docs.microsoft.com/en-us/windows/win32/direct3d11/floating-point-rules), but has a slight deviation from IEEE-754 for min and max.

It seems likely that WGSL should say nans (and denorms) may not be preserved for MVP.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-03-minutes#specify-behaviour-of-floating-point-operations-on-nans-1711">WGSL meeting minutes 2022-05-03</a></summary>



* KG: Recommendation from a year ago was to say NaNs and denorms may not be maintained
* AB: Have that in spec
* KG: Then done i think.


</details>
