### ISSUE TITLE
What binding numbers are used by an external texture binding?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1721]
https://github.com/gpuweb/gpuweb/pull/1666#pullrequestreview-656218712
> The question in my mind is on the API side: if an external texture uses up multiple bindings, then how do I know what binding numbers are occupied? I presume they are in the same bindgroup.

**Comment by kainino0x** [comment]
> I'm not precisely sure how to address this, but I think that in implementations we can hide the fact that multiple binding indices are used. IIRC in Dawn at least, we re-pack the bindings into a small range near 0 anyway, so this problem would disappear in that. However for the sake of alternate implementations we might want to reserve half of the binding index space for internal bindings, or something?

**Comment by kainino0x** [comment]
ah, I forgot that was written down. I think that addresses it, yes. We should briefly discuss to get confirmation from other implementations

**Comment by Kangz** [comment]
Exactly. At the latest at pipeline creation (or with the layout info at shader module creation if you implementation is able to do that) you can do the remapping and never change the shader again.

**Comment by kvark** [comment]
Filed #1733 as promised on the call

**Comment by kvark** [comment]
Our current position is - ready to accept this if #1783 is accepted, as a suitable path forward for us.

**Comment by kainino0x** [comment]
resolution: #1783 accepted, external textures take only one binding.

The latter is already consistent with the spec as written, so closing.
