### ISSUE TITLE
Errant reference to `break if` in WGSL spec

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#1745]
There is a  `break if (i == 5);` in the spec but I don't see it referenced anywhere else inside `EXAMPLE: VARIABLE INITIAL VALUES`.

**Comment by dneto0** [comment]
I saw that. I have a drive-by fix for this as part of #1735 
See https://github.com/gpuweb/gpuweb/pull/1735/files#diff-709b5c343d59ae10cbabe69f9df1eee9e2dbb6e9d848632fa94357083d6e0a34R2822

**Comment by dneto0** [comment]
#1735 landed, and there are no more uses of "break if".
Closing.
