### ISSUE TITLE
Why is `block` the only keyword attribute?

### ISSUE THREAD

**Issue by elijaharita** [gpuweb/gpuweb#1752]
Hello everyone. I'm writing a syntax highlighter for vscode based on the spec, and was curious about `block` being the only attribute listed as a keyword, meaning it's the only attribute not intended to be usable as an identifier. (And `workgroup`, but I assume that's listed as the storage class, not attribute).

What makes `block` special? Are all other attributes supposed to be legal as keywords?

**Comment by dneto0** [comment]
It's an accident, basically.

**Comment by jdashg** [comment]
Please reopen if there's more to discuss here!
