### ISSUE TITLE
Reconsider the name of storeOp: "clear"

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1761]
In #358 it was decided that we would use the enum value `"clear"` so that the as-if semantics of `storeOp: "clear"` would be self-explanatory.

However I've seen issues or gotten feedback from multiple developers where it wasn't obvious to them that `"clear"` is a lazy operation, and therefore can be considerably cheaper than `"store"`. Put another way, when a developer needs to choose between `"clear"` and `"store"`, there is no apparent reason why they should ever bother to choose `"clear"`, and so by default may just pick `"store"`.

I think we should simply rename it to `"discard"`, though `"discard-to-zero"` was also fine. (It has also been suggested to allow both `"clear"` and `"discard"`, though there would be no difference except in unsafe native applications.) It is already the case that any resource that hasn't been initialized is cleared to zero. In the mental model I think it is apparent that `"discard"` behaves the same way.

**Comment by kvark** [comment]
Fully agree. We already have the spec saying that uninitialized resource contents are zero. So "discard" just needs to be specified as an operation that brings the subresources back to uninitialized state.

**Comment by kainino0x** [comment]
Resolution: accepted, but editors to do our homework and make sure we're not forgetting about a good reason we called it `"clear"` before.

**Comment by kainino0x** [comment]
Editors: Homework done, all clear on `"discard"`

It was decided in the meeting on [2019-07-22](https://docs.google.com/document/d/1_6g2UT411o0FjIAkdndAYw7LD6cCeWlTfxp1iRIxQwg/edit#heading=h.jjene1pdr6xy). Summary:
- Desire to potentially have a way to expose actual safe-but-uninitialized data in the future (e.g. from a previous allocation on the same device), or an option which _validates_ that uninitialized subresources are never read (or partially-initialized). Editors: we can come up with another more explicit name if we ever add something like that (e.g. "discard-uninitialized" or something).
- If we did the validation above, it would require a lot of state tracking in the spec (bit for each subresource). Editors: Since implementations have this anyway it wouldn't be a big deal.
