### ISSUE TITLE
Need to define alpha premultiplication for external images

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1762]
For both copyExternalImageToTexture and importExternalTexture, we need to define whether the results you get are premultiplied or not.

For copyExternalImageToTexture I think we want unpremultiplied, though we could add a configuration option to provide premultiplied data.

For importExternalTexture we probably also want unpremultiplied, though this could mean doing an extra three divisions (.rgb/.a) in the injected shader code.

**Comment by shaoboyan** [comment]
From impl view, different alpha premultiplication config with origin content may cause extra ops(could be taken as a copy) or downloading gpu resource to cpu. 
So I'm not quite sure whether there is attributes(or have plan to add this attribute in future in spec) for all ExternalImage elements, especially for HTMLCanvasElement and OffscreenCanvasElement , to let js develepers got the default alpha attribute.

**Comment by kainino0x** [comment]
Per spec the following are:
- premultiplied:
  - [2d canvas](https://html.spec.whatwg.org/multipage/canvas.html#premultiplied-alpha-and-the-2d-rendering-context)
  - webgl/2 HTMLCanvasElement/OffscreenCanvas with premultipliedAlpha: true (default)
  - [createImageBitmap](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#cropped-to-the-source-rectangle-with-formatting) with premultiplyAlpha: "premultiply"
- not premultiplied:
  - webgl/2 HTMLCanvasElement/OffscreenCanvas with premultipliedAlpha: false
  - createImageBitmap with premultiplyAlpha: "none"
- either premultiplied or not:
  - createImageBitmap with premultiplyAlpha: "default" (default)

In Chromium at least, my understanding is that HTMLImageElement is also always premultiplied, but I'm guessing the spec may not care. I'm not sure about HTMLVideoElement/VideoFrame.

**Comment by kainino0x** [comment]
Shaobo raises the point that unpremultiplying everything (which I *think* is the WebGL behavior) has an extra conversion cost. We might want to make this configurable so that applications can avoid the conversion cost and handle premultiplied data internally.

**Comment by kainino0x** [comment]
> We might want to make this configurable so that applications can avoid the conversion cost and handle premultiplied data internally.

I had forgotten, but was reminded that WebGL *does* provide control over this, with `UNPACK_PREMULTIPLY_ALPHA_WEBGL`.
