### ISSUE TITLE
SPIR-V doesn't grant reconvergence for multiple returns

### ISSUE THREAD

**Issue by kdashg** [gpuweb/gpuweb#1770]
```rust
fn bar(i: i32) {
  if (!i) return;
  // ...
  return;
}

fn foo1(i: i32) {
  // assuming UCF here
  bar(i);
  const x = dpdx(i); // [1] Is this in UCF? (not in spir-v)
}

fn foo2(i: i32) {
  // assuming UCF here
  while (true) {
    bar(i);
    break;
  }
  const x = dpdx(i); // [2] Is this in UCF? (yes in spir-v)
}
```

In the above (written as WGSL), is [1] in UCF?
* SPIR-V says no.
* GLSL seems to say no. (reconverge after "selection or loop")
* MSL doesn't seem to say.
* HLSL doesn't seem to say.

This is generally surprising to people. One way to think of this is that the divergence (thus non-uniformity) is inlined, ignoring function boundaries.

[2] is probably UCF for everyone, but it's good to double-check while we're asking about [1].

@dneto0, please check my work and wording.
@pow2clk, can you give us a read on this for HLSL? (And if DXIL is any different?)
@litherum and @RobinMorisset will check for MSL.

**Comment by jdashg** [comment]
Because this is surprising to people, there was a proposal to make this reconvergence guarantee in WGSL, and translate/transform accordingly.

One such transform might be:
```rust
fn bar(i: i32) {
  if (!i) return;
  // ...
  return;
}

fn bar_reconv(i: i32) {
  while (true) {
    bar(i);
    break;
  }
}

fn foo3(i: i32) {
  // assuming UCF here
  bar_reconv(i);
  const x = dpdx(i); // [3] should be UCF
}
```

It sounds like it's survivable to make this guarantee and transform for SPIR-V.
However, I don't think we have as much pressure to match intuition here, since we do validate UCF, and we will reject `foo1` above, and authors will be forced to handle it themselves. (Such as by writing `bar_reconv`)

**Comment by kainino0x** [comment]
Since we validate uniformity, making this change later should be non-breaking, right? (Making this change should allow strictly more valid programs)

**Comment by jdashg** [comment]
Yes, it can be changed later.

**Comment by dneto0** [comment]
> @dneto0, please check my work and wording.

Yes, the problem statement is correct.

As an aid to intuition, it's very common for graphics shaders to be fully inlined by the driver, before other significant processing. That's why the non-convergence leaks across function boundaries: because there's no boundary there, essentially.

**Comment by litherum** [comment]
> In the above (written as WGSL), is [1] in UCF?

If you naively transcribed the program into MSL, [1] would be in UCF.

**Comment by kvark** [comment]
@dneto0 could you clarify, please. If SPIR-V driver is inlining this function, would it look different from the `while/break` construct that is suggested here?

**Comment by RobinMorisset** [comment]
@alan-baker and @dneto0 discussed this with me earlier today, it is pretty much the last issue blocking the landing of the uniformity PR.
I think that the following should work (I still have to test it carefully on a large collection of examples):
Make the "singleton rule" of the uniformity analysis only apply when the behavior is {Next}, and only when the statement is one of the following:
- if
- switch
- loop
- (no need to do it explicitly for || and &&, as the behaviors of expressions are quite limited).

Pros:
- it only requires modifying the uniformity analysis and nothing else
- it is just a few lines of spec text
- it matches my (new) intuition of where divergence/reconvergence happens in SPIRV
Cons:
- ??

**Comment by dneto0** [comment]
Yes, that seems right to me.
Thanks!

**Comment by RobinMorisset** [comment]
The uniformity PR landed with that change, so I am closing this.
