### ISSUE TITLE
Allow read-write storage on selected texture formats

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1772]
Based on the investigation of #513, we should consider adding a read-write variant of `GPUStorageTextureAccess`, which is to be allowed on R32 float/sint/uint formats (only). This appears to be guaranteed on D3D12, Vulkan, and requires a certain Apple OS version (macOS 10.13, iOS 11). The expectation is that prior Apple OSes would not have WebGPU exposed.

**Comment by kainino0x** [comment]
It also has hardware requirements, but the [Metal Feature Set Tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) defer on actually saying what the hardware requirements are. It seems that they are not strictly tied to particular Feature Sets. Instead, Metal requires a runtime check. In this case, `readWriteTextureSupport` must be at least `MTLReadWriteTextureTier1`.

> Read-write textures are available in some feature sets,
where the texture can be both read from and written to by
the same function. Query the readWriteTextureSupport
property of MTLDevice to determine support.

**Comment by kainino0x** [comment]
Also if we decide to drop 10.12, we should update #1069.

**Comment by kainino0x** [comment]
Meeting:
We need telemetry data to determine whether this can be in core.

Until then, we can spec this as optional feature, and perhaps make it non-optional (take out the feature name) later.

**Comment by apbodnar** [comment]
As a noob to the WebGPU standards process, does optional mean "available through an extension" in this case?  Losing read/write for storage images would be a bummer for a handful of compute use-cases.

**Comment by kainino0x** [comment]
Yeah, optional means the hardware and browser have to support it, and if so then you can enable it.
https://gpuweb.github.io/gpuweb/#features

**Comment by teoxoy** [comment]
Related to https://github.com/gpuweb/gpuweb/issues/3893; OOB writes to storage textures are always ignored on all target APIs.

References:

### Metal

> For all texture types, an out-of-bounds write to a texture is ignored.

_from page 184 of [Metal Shading Language Specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf)_

### Vulkan

> The integer texel coordinates are validated according to the same rules as for texel input [coordinate validation](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap16.html#textures-integer-coordinate-validation).
> If the texel fails integer texel coordinate validation, then the write has no effect.

_from [16.4.2. Integer Texel Coordinate Validation](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap16.html#textures-output-coordinate-validation)_

### D3D

> Out of bounds addressing means nothing gets written to memory.

_from [direct3dhlsl docs](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/store-uav-typed--sm5---asm-#remarks)_

**Comment by etang-cw** [comment]
Small heads up from an issue I recently hit in MoltenVK (https://github.com/KhronosGroup/SPIRV-Cross/pull/2153)

Metal's rw textures don't guarantee that reads see the result of writes made earlier in the same thread without calling explicit barrier functions, so any WGSL → MSL compilers will need to keep this in mind.

**Comment by jimblandy** [comment]
Closing this issue, as important discussion of this has moved over to #3838.
