### ISSUE TITLE
Define behavior of reading from WebGPU canvases using other Web APIs

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1781]
We need to define the behavior of reading from WebGPU canvases using other Web APIs.
Most of these are "peek" operations that have no effect on the canvas contents:
- `CanvasRenderingContext2D.drawImage()`
- `WebGLRenderingContext.texImage2D()` et al.
- `HTMLCanvasElement.toDataURL()`/`.toBlob()`/`OffscreenCanvas.convertToBlob()` (#1548)

There is also a "swap" operation:
- `OffscreenCanvas.transferToImageBitmap()`

And "peek" operations that are done by the _user_ (not by the page):
- Printing (to paper/pdf)
- Copy to clipboard
- "Save Image As"

Historically, the interaction between drawing operations inside the context and read operations outside the context is very "immediate" - in a way, all drawing operations on a page could be considered to happen on the same `GPUQueue`, so drawing operations are always available immediately. This results in some complications, especially regarding:
- Interaction with end-of-frame document compositing ("animation frame"), especially in WebGL with `preserveDrawingBuffer: false`.
- Relationship between user operations like printing and `preserveDrawingBuffer` - we previously agreed to avoid this in WebGPU.
- Resource synchronization inside implementations, e.g. transitioning the `[[currentTexture]]` from WebGPU-writable, to WebGL-readable, back to WebGPU-writable.

We previously discussed "explicit" presentation APIs that would have e.g. required a `swapChain.present()` call in order for a frame to be submitted to the compositor. However this was rejected in favor of behavior that meshed better with the Web platform:
- Implicit destruction of the current swap chain texture on animation frame for `HTMLCanvasElement`s in the DOM and `OffscreenCanvas`es created via `transferControlToOffscreen` (I'm not sure about `HTMLCanvasElement`s which are _not_ in the DOM - should match WebGL).
- I don't think we agreed on specific semantics for `OffscreenCanvas`es created via `new OffscreenCanvas()`.

## Proposals

These proposals straddles the boundary between the current mostly-implicit semantics and the earlier very explicit semantics, while preserving the properties (round-robin ordering) that are needed for implementations to be able to optimize using native swap chains.

<details><summary>Proposal 1</summary>

- Define "destroy" on canvas-presentation textures as an "early commit"<sup>1</sup>: the WebGPU device loses access, and the texture contents are preserved but **become immutable**.
- On (a) animation frame (for presented canvases), or (b) inside `OffscreenCanvas.transferToImageBitmap()`:
    - Call `destroy()` on the `[[currentTexture]]` (defined above).
    - "Pop" the `[[currentTexture]]` slot (leaving `null`).
    - Hand off the preserved, now-immutable texture contents: to (a) the compositor, or (b) a new `ImageBitmap`.
- Inside user-initiated "peek" operations:
    - `[[currentTexture]]` is ignored. Instead, use whatever contents are currently held by the compositor.<sup>2</sup>
- Inside programmatic "peek" operations:
    - Throw if `[[currentTexture]]` is `null`.
    - Throw if `[[currentTexture]]` **is not already "destroyed"** (defined above).
    - Possibly throw if the WebGPU canvas is desynchronized (either using `desynchronized: true` or `transferControlToOffscreen()`).<sup>3</sup>
    - Copy the contents out of the texture.

Notes:
- <sup>1</sup> Despite having "early commit", it is still not possible to advance the "swap chain" more quickly than rAF: `destroy()` doesn't affect `[[currentTexture]]`, so `getCurrentTexture()` in the same frame will still return the same (destroyed) texture. Of course, people always ask to be able to do this, but I think a solution to that problem would be different (e.g. `swapChain.discardCurrentTextureIfAny()`, or present using `transferToImageBitmap()`+`ImageBitmapRenderingContext`).<sup>5</sup>

</details>

<details><summary>Proposal 2</summary>

An alternative that replaces validation with either extra copies or extra synchronization (implementer's choice).

- Define "destroy" on swap chain textures as a "discard"<sup>4</sup>, destroying the texture as usual and also setting `[[currentTexture]]` to null.
    - Note this means there will never be a `[[currentTexture]]` that is in the `destroyed` state.
    - Also note if this happens, the currently-presented frame will _not_ be replaced, so this effectively "cancels" presentation.<sup>5</sup>
- In (a) `present the presentation context content to the canvas`, or (b) `OffscreenCanvas.transferToImageBitmap()`:
    - If `[[currentTexture]]` is non-null:
        - "Pop" the `[[currentTexture]]` slot (leaving `null`).
        - "Move" the contents of the canvas out of the texture, marking it as `destroyed` so the app can't use it.
        - Hand off the contents: to (a) the compositor, or (b) a new `ImageBitmap`.
- Inside user-initiated "peek" operations:
    - `[[currentTexture]]` is ignored. Instead, use whatever contents are currently held by the compositor.<sup>2</sup>
- Inside programmatic "peek" operations:
    - Throw if `[[currentTexture]]` is `null`.
    - Possibly throw if the WebGPU canvas is desynchronized (either using `desynchronized: true` or `transferControlToOffscreen()`).<sup>3</sup>
    - Copy the contents out of the texture. (Requires synchronization to make sure that later writes from WebGPU are not seen. Implementations may instead simply copy the data out to a staging resource using a `copyTextureToTexture` command here to easily ensure this.)

</details>

<details open><summary>Proposal 3 (my current recommendation)</summary>

Slight refinement of proposal 2.

- In `getCurrentTexture`, replace "if [[currentTexture]] is null" with "if [[currentTexture]] is null or destroyed".<sup>4</sup>
- In (a) `present the presentation context content to the canvas`, or (b) `OffscreenCanvas.transferToImageBitmap()`:
    - If `[[currentTexture]]` is not `null` **and** not destroyed:
        - "Move" the contents of the canvas out of the texture, marking it as `destroyed` so the app can't use it.
        - Hand off the contents: to (a) the compositor, or (b) a new `ImageBitmap`.
    - Note if the app destroyed the texture, the currently-presented frame will _not_ be replaced, so this effectively "cancels" presentation.
- Inside user-initiated "peek" operations:
    - `[[currentTexture]]` is ignored. Instead, use whatever contents are currently held by the compositor.<sup>2</sup>
- Inside programmatic "peek" operations:
    - Fail if `[[currentTexture]]` is `null` or destroyed.
        - Need to decide whether this throws an exception, or returns a blank image (to avoid adding special cases to other APIs).
    - Possibly fail if the WebGPU canvas is desynchronized (either using `desynchronized: true` or `transferControlToOffscreen()`).<sup>3</sup>
    - Copy the contents out of the texture. (Requires synchronization to make sure that later writes from WebGPU are not seen. Implementations may instead simply copy the data out to a staging resource using a `copyTextureToTexture` command here to easily ensure this.)

</details>

Notes:
- <sup>2</sup> There still may be some cases where the compositor-owned contents cannot be read - e.g. a native swap chain is in use because the canvas is marked as `desynchronized` or uses `transferControlToOffscreen` - but I'm not sure whether we can solve this. If we can't, we should consider trying to spec and test exact behavior in these cases, like that it's always blank.
    - In WebGL today: https://codepen.io/kainino0x/pen/jOBXqNV
- <sup>3</sup> We could require a specific, explicit flag in `GPUPresentationConfiguration` to say "I want to be able to read from this canvas", and reading works IFF that is set. Can then be _validated_ not to conflict with `desynchronized: true`/`transferControlToOffscreen()` as mentioned above. This also lets us safely make validation more lenient later on, rather than specifying the "always blank" behavior.
- <sup>4</sup> This _does_ allow advancing the swap chain more quickly than rAF.
    - This isn't necessary for outputting multiple images per frame (an important use case) - a clear could be used instead - but we have to define `destroy()` behavior anyway.<sup>5</sup>
- <details>
    <summary><sup>5</sup> Triple buffering</summary>
    Developers have expressed interest in "triple buffered" style rendering, rendering as fast as possible and having the latest result be displayed to the screen. I believe this is not feasible on the main thread, because it would fool the scheduler into thinking each frame is very expensive. However, this could be done on a background thread <strong>if</strong> there were a way to submit a frame and then start a new frame. <code>destroy()</code> <em>could</em> be a way to do that, but more likely either the <code>GPUPresentationContext</code> would have a new method for that, or it would be done with <code>transferToImageBitmap()</code>+<code>ImageBitmapRenderingContext</code>.<sup>1</sup>
    </details>

**Comment by Kangz** [comment]
What happens for desynchronized canvas with WebGL at the moment? Do we get an blank <canvas>? Also it seems a bit unfortunate that calling a programmatic "peek" detaches the texture so you have to re-render if you want to use the same texture for a different peek, or to present on the screen. Maybe it's ok if there's an additional copy happening in browsers to allow that. WDYT?

> Throw if [[currentTexture]] is not already "destroyed" (defined above).

nit: Throw if it is already "destroyed" (and maybe also call it detached?)

**Comment by kainino0x** [comment]
> > * Throw if `[[currentTexture]]` **is not already "destroyed"** (defined above).

This was intended. Peek operations require that the caller have already terminated its own access to the texture before asking something else to access it.

> Maybe it's ok if there's an additional copy happening in browsers to allow that. WDYT?

I think I can come up with an alternative design that requires _either_ an additional copy _or_ more complex synchronization. This reflects the experience we currently have implementing prototypes in Chromium.

**Comment by Kangz** [comment]
Ah I didn't realize this adds `GPUSwapChain.destroy()` as something accessible to JS.

**Comment by kainino0x** [comment]
It doesn't, it's just `GPUTexture.destroy()`:

> * Define "destroy" on swap chain textures as an "early commit"1: the WebGPU device loses access, and the texture contents are preserved but **become immutable**.

Separately, with different semantics:

> (...) `destroy()` doesn't affect `[[currentTexture]]`, so `getCurrentTexture()` in the same frame will still return the same (destroyed) texture. (...) `swapChain.discardCurrentTextureIfAny()`

**Comment by kainino0x** [comment]
I've put up "Proposal 2" in the issue summary; PTAL.

**Comment by kvark** [comment]
The part where `currentTexture` becomes NULL is a bit iffy. I don't think it matches any other operations we do in the API? Generally, if I call something on X, I expected only X to change.

**Comment by kainino0x** [comment]
I thought so too. How about one of the following options?
- `[[currentTexture]]` is _not_ nullable. Instead, what we represent now as `null` would be represented by a destroyed texture.
- Put a `discardCurrentTexture()` method on the swap chain object, and perhaps don't have a `destroy()` method on swap chain textures.

**Comment by RafaelCintron** [comment]
I like proposal 2 because it lets you draw a WebGPU canvas to a 2D canvas multiple times in a frame and prevents user-initiated "peaks" from being detectable by the web developer.   

> @kvark says: The part where currentTexture becomes NULL is a bit iffy.

The current WebGPU spec already has a [[currentTexture]] internal slot which can be nullable.  @kvark are you saying the existing spec language should change? I, personally, am fine with [[currentTexture]] being nullable.  

> Put a discardCurrentTexture() method on the swap chain object, and perhaps don't have a destroy() method on swap chain textures.

WebGPU swap chain textures are normal WebGPU textures. Seems weird for them to be special and have IDL methods that are completely missing.  

I can't think of good reason to spec and implement a `discardCurrentTexture` method essentially telling the browser "just kidding, nevermind all of that" on everything they've rendered thus far.  I think calling `destroy` on a swap chain texture would be a better place to have that behavior.

**Comment by kainino0x** [comment]
> The current WebGPU spec already has a [[currentTexture]] internal slot which can be nullable. @kvark are you saying the existing spec language should change? I, personally, am fine with [[currentTexture]] being nullable.

No, the problem is that texture.destroy() changes the internal state of another unmentioned object (the GPUSwapChain the texture was created from).

**Comment by kainino0x** [comment]
Editors: Tentatively, in places where it currently says "if [[currentTexture]] is null", say "if [[currentTexture]] is null or destroyed".
