### ISSUE TITLE
Limit the binding number for resources

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1783]
Following #1721, there is an issue uncovered that making the binding numbers implicit would effectively require all the implementations to do binding re-mapping. This re-mapping can only be done at pipeline creation time, and thus precludes creating SPIR-V shader modules earlier.

Thinking about a compromise, we could say that binding numbers are limited to 65535 (similar to the overridable constant indices). This should allow a non-remapping implementation to reason about binding numbers at shader module creation time.

**Comment by Kangz** [comment]
This seems fine, as in it helps your implementation and doesn't lose developer flexiblity. (and we can reduce some u32 to u16 in implementations too :))

**Comment by kvark** [comment]
There are still details to be figured out, like what binding indices would be assigned. Maybe if the external texture binding is `x`, then the associated textures would be `x + 0x10000`, `x + 0x20000`, etc. Seems doable, but we'll probably have to keep `u32` :)

**Comment by kainino0x** [comment]
Resolution: accept. Easy to lift the restriction later if it ultimately turns out not to be necessary. Firefox to see whether it turns out to be unnecessary (e.g. because passing sparse layouts to the driver turns out to be slow).

**Comment by Kangz** [comment]
This restriction hasn't been added in the spec yet, and the WGSL spec still says "non-negative i32 literal".
