### ISSUE TITLE
xor doesn't work for vec

### ISSUE THREAD

**Issue by Ciebiada** [gpuweb/gpuweb#1784]
I'm getting this error
```
Tint WGSL reader failure:
Parser: 39:11 error: Binary expression operand types are invalid for this operation: vec2<u32> xor vec2<u32>
  v1= v ^ vec2<u32>(10u, 10u);
```
Documentation says it should work for `i32` and `u32` vec types.

Am I doing something wrong?

**Comment by jrprice** [comment]
Your code is fine; this is a bug in Tint. It's tracked in the Tint bug tracker here: crbug.com/tint/768

Closing this as there is no WGSL spec issue here.

**Comment by Ciebiada** [comment]
Thank you. Unfortunately I can't see the ticket itself. Is there a workaround?

**Comment by jrprice** [comment]
Fixed the link, sorry about that.

I think the only workaround for Tint right now would be to do the xor element-wise, e.g.:
```
v1 = vec2<u32>(v.x ^ 10u, v.y ^ 10u);
```
