### ISSUE TITLE
"Sampled" is ambiguous in the spec

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1785]
In the texture usage, `SAMPLED` merely means that a shader can read from the texture. It doesn't actually mean that the shader can use it with a sampler (which is another meaning for "sampled").

**Comment by Kangz** [comment]
A good alternative is `SHADER_READ` which I think is a usage lag in Metal too. However textures with that used couldn't be used as readonly storage textures, which is confusing too.

**Comment by kvark** [comment]
Discussed with the editors. An interesting fact here is that of all the 3 target APIs, only Vulkan has such a concept as read-only storage texture. This prompts us to consider getting the "SampledTexture" binding type and merging it with "StorageTexture { readonly: true }". If such a merge is possible to implement efficiently on Vulkan backend, then our usages will become `SHADER_READ` and `SHADER_WRITE`, solving the ambiguity (and even simplifying the binding model a bit). I'm taking an action item to investigate this.

**Comment by Kangz** [comment]
This merge isn't possible because it wouldn't be clear which SPIRV instruction to emit:

 - SPIR-V requires the operand of `OpImageFetch` to be `Sampled=1`
 - SPIR-V requires the operand of `OpImageRead` to be `Sampled=2`
 - Vulkan sampled image bindings must match an `OpTypeImage` with `Sampled=1`
 - Vulkan storage image bindings must match an `OpTypeImage` with `Sampled=2`

**Comment by kvark** [comment]
@Kangz every Vulkan format that supports STORAGE also has to support SAMPLED, at least according to the "Required Format Support" section. So there comes the question: if we were designing it from the ground up, why would we ever use a storage texture on vulkan with read-only mode?

I.e. it seems to me that in all cases where users have a read-only storage texture in WGSL today, they can just switch them to be regular sampled textures, and load from them in exactly the same way. So if we just throw the read-only storage out from the spec, we aren't going to limit any of the use cases. But then we'd be able to use `SHADER_READ` and `SHADER_WRITE` flags, and fix the naming.

I might be missing something here, but if I'm not - the path to a solution is revealed.

**Comment by Kangz** [comment]
That solution might lose developer control of which hardware path is used to access the texture: texture unit or direct memory access (and different cache hierarchies in some cases). But the bigger problem is that when in the future WebGPU supports `storage-texture` bindings (so very soon), then we lose flexibility.

With storage buffers you can have a `var<storage, read>` (excuse the incorrect WGSL, I'm not up to date) that corresponds either to a `readonly-storage-buffer` binding in the `GPUPipelineLayout` or a `storage-buffer`. If we get rid of of `readonly-storage-texture` then it means that the shader will have to either force the resource to be used as writable for the synchronization scope, or force it to always be readonly. Deferring the choice helps composability of shader snippets when used in different pipelines.

**Comment by kvark** [comment]
> That solution might lose developer control of which hardware path is used to access the texture: texture unit or direct memory access (and different cache hierarchies in some cases)

Do we have any idea of the perf difference? It's not clear to me how a storage texture could have better caching than a sampled texture, theoretically.

> But the bigger problem is that when in the future WebGPU supports storage-texture bindings (so very soon), then we lose flexibility

Do you mean read-write storage textures? I don't understand this argument.

> If we get rid of of readonly-storage-texture then it means that the shader will have to either force the resource to be used as writable for the synchronization scope, or force it to always be readonly. Deferring the choice helps composability of shader snippets when used in different pipelines.

This is already the case today. Check the [compatible-usage-list](https://gpuweb.github.io/gpuweb/#compatible-usage-list) section. You can't mix and match read-only storage with writable storage (internal usages) in the same scope. So removing read-only storage isn't going to make this any stricter.

**Comment by Kangz** [comment]
> Do you mean read-write storage textures? I don't understand this argument.

Correct I meant `read-write-storage-texture` bindings which will likely be called `storage-texture` (see `storage-buffer`).

> This is already the case today. Check the compatible-usage-list section. You can't mix and match read-only storage with writable storage (internal usages) in the same scope. So removing read-only storage isn't going to make this any stricter.

But in the shader if you declare `var<storage, read>` then the decision of wither this goes in the `read-only` or `writable` compatible usage is deferred to the `GPUPipelineLayout` so your shader is agnostic to it. This helps when you have a piece of shader code that can use read-only storage so that it doesn't for read-only or writable on the rest of the code.

**Comment by kvark** [comment]
I see. Theoretically, this is a use case that would be denied. I think it's a bit of a weird one. From the shader perspective, you'd see a read-only resource, which is changed behind your back. So you'd do multiple consecutive `textureLoad` from the same coordinate and get different results. Could be very confusing... maybe it's a good thing to deny this.

**Comment by Kangz** [comment]
This is somewhat related to #287

**Comment by dneto0** [comment]
> So you'd do multiple consecutive textureLoad from the same coordinate and get different results. 

That's a data race.   You wouldn't use textureLoad  (OpImageFetch or OpImageRead) for that.

In Vulkan storage textures can have atomics on them. If you want that usage to be non-racy, then use atomics.  (Use OpImageTexelPointer to translate a coordinate to a pointer, then use the pointer with the atomic instruction).

**Comment by kvark** [comment]
@dneto0 yes, and this kind of data races we probably don't need to allow. It's just confusing from the shader (and shader author) perspective.
I don't see how atomics would change this. You'd do 2 atomic loads instead of 2 regular loads, but the value could still change in-between them (i.e. coming from another draw call/pipeline).

**Comment by dneto0** [comment]
> I don't see how atomics would change this. You'd do 2 atomic loads instead of 2 regular loads, but the value could still change in-between them (i.e. coming from another draw call/pipeline).

Agreed.   You'd want that to be a read-write storage texture anyway.
