### ISSUE TITLE
WGSL grammar needs update for var type inference

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#1805]
PR #1756 allowed type inference for non-global `var` statements, but the grammar needs to be updated to account for this.

**Comment by kdashg** [comment]
Did this happen?

**Comment by jrprice** [comment]
Yes, this has been done.

The grammar updates also now allow for module-scope variables to use type inference too, e.g.:
```
var<private> foo = 42;
```
I /think/ we agreed that this was fine in the end? The prose for module-scope variables doesn't say either way though, so that may be worth clarifying.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-03-minutes#wgsl-grammar-needs-update-for-var-type-inference-1805">WGSL meeting minutes 2022-05-03</a></summary>



* KG: Similar, closing.
* JP: Just check grammar now allows type inference at module scope. Prose doesn’t say how. Think we later changed our minds?
* MM: If we do inference at function scope, we should do at global scope.
* AB: Pretty sure with const we did it.** Should say if it doesn’t. Can clarify**.


</details>
