### ISSUE TITLE
why postMessage GPUDevice to worker cause DataCloneError when cross-origin isolated capability is true?

### ISSUE THREAD

**Issue by yyc-git** [gpuweb/gpuweb#1817]
Hello, Thanks for your reading~

I want to write a WebGPU Multi-Threading (JavaScript) Demo!

I want to send GPUDevice from main thread to Dedicated worker by postMessage, and I already set the http header, but it still cause DataCloneError!

# Code

the code of the file(/test/multi_thread/webgpu/index.html) in the main thread is here:
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title></title>
</head>

<body>
  <canvas id="webgpu"></canvas>
  <script>
    let main = async () => {
      let worker = new Worker("./src/worker/Main.js");

      const canvas = document.querySelector("#webgpu");
      const gpuContext = canvas.getContext('gpupresent');

      let adaper = await navigator.gpu.requestAdapter();

      let device = await adaper.requestDevice();

      console.log(
        self.crossOriginIsolated
      )

      worker.postMessage({
        device: device
      });
    }

    window.addEventListener('DOMContentLoaded', main);
  </script>
</body>

</html>
```

the code of the worker file(/test/multi_thread/webgpu/src/worker/Main.js) is here:
```js
console.log(
    self.crossOriginIsolated
);

self.onmessage = (event) => {
    console.log(event.data.device);
};
```

the code of the server file(/server.js) is here:
```js
const path = require('path')
const express = require('express')

async function createServer() {
    const app = express()

    app.use('*', function (req, res, next) {
        res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
        res.setHeader("Cross-Origin-Opener-Policy", "same-origin");

        next();
    });

    app.use(express.static(path.join(__dirname)));

    app.get('/test/multi_thread/webgpu/index.html', (req, res) => {
        res.sendFile(path.join(__dirname, "/test/multi_thread/webgpu/index.html"));
    });


    app.listen(8000)

    console.log("success!");
}

createServer()
```

# Run the code

1.start the server in the project root dir:
```js
node server.js
```
2.open http://localhost:8000/test/multi_thread/webgpu/index.html in Chrome Canary(version 93.0.4536.0 canary （64 bit）) in Windows 10

**Result**
the dev tool->Console is:
![](https://img2020.cnblogs.com/blog/419321/202106/419321-20210608160207192-1782435236.png)

the self.crossOriginIsolated in main thread and worker are already true!

the dev tool->Network shows that the Response Headers of index.html and Main.js is:
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

# Question

So Why the postMessage in main thread cause the Error: "GPUDevice object could not be cloned" ??? How to solve it???
Thanks very much~

**Comment by Kangz** [comment]
At the moment WebGPU doesn't support sending objects to workers. There are a lot of ideas of how this would work, but also some subtle implications so we're looking to do that as a second step. That's why you're getting a `DataCloneError` in Chromium. Instead you can create the device in the worker directly by doing `navigator.gpu.requestAdapter` there (not 100% if it is `navigator` or something else though).

**Comment by yyc-git** [comment]
> At the moment WebGPU doesn't support sending objects to workers. There are a lot of ideas of how this would work, but also some subtle implications so we're looking to do that as a second step. That's why you're getting a `DataCloneError` in Chromium. Instead you can create the device in the worker directly by doing `navigator.gpu.requestAdapter` there (not 100% if it is `navigator` or something else though).

Thanks for your reply!

So can I move the render task from the main thread to a Dedicated worker now?
It means I should transfer canvas from the main thread to a Dedicated worker by using offscreenCanvas.

**Comment by Kangz** [comment]
Probably not before v1 to make it easier and faster to get to a v1, but probably soon after.

**Comment by yyc-git** [comment]
Thanks.

So before v1, We can only use one main thread and one render worker...We can't use more than one render worker because we can't commit command buffers in different worker???

**Comment by Kangz** [comment]
Correct

**Comment by yyc-git** [comment]
Thanks very much~
