### ISSUE TITLE
What is the purpose of WebGPUSwapChain.present()?

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#182]
We have agreed to maintain the invariant that nothing should show up on the screen until the end of a rAF(). That begs the question why the present() call exists in the first place. In WebGL, there is no present() call, and the results show up at the end of rAF().

This matters regarding GPUSwapChain.getNextTexture(). Do you get the same texture if you call this twice in the same rAF()?

**Comment by kvark** [comment]
I totally missed the part of the discussion where we bound swapchain image lifetimes to rAF. Could you specify the references to minutes/issues, please?

**Comment by kainino0x** [comment]
I think it was during a break. We will have to discuss this (present/scheduling) in more detail.

I think acquireNextTexture should be allowed once per "frame" (i.e. the animation frame event puts one image on the swapchain), and it should fail beyond that. Need to think further about present, but likely not needed - we can continue using the same mechanism WebGL uses.

The OffscreenCanvas commit API is closely related, so, for workers, the design there should apply to WebGPU too.

**Comment by Kangz** [comment]
@dmikis early present is a good idea. Present shouldn't be a queue operation because it isn't clear which queue should own presentation. In Vulkan the present queue could depend on whether we present to the screen or are just sampling from the WebGPU texture in the browser compositor.

@RafaelCintron do you mean that you'd like `getNextTexture` to return a `GPUTexture?` and only return a valid texture the first time it is called in the RAF? That would work for me. Care to make a PR?

**Comment by dmikis** [comment]
How will an implementation know after which commands to do present? As far as I can tell, all three native APIs have present as a command: [Metal](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443029-presentdrawable?language=objc), [Vulkan](https://www.khronos.org/registry/vulkan/specs/1.1-khr-extensions/html/chap29.html#vkQueuePresentKHR), and D3D12 has a separate state, that requires a barrier to trasition a target to it (if I understand correctly). So one way or the other, in those APIs presenting is done by scheduling it on a queue.

**Comment by Kangz** [comment]
The WebGPU implementation will present the texture "as if" all previous operations are completed.

**Comment by RafaelCintron** [comment]
#207

**Comment by RafaelCintron** [comment]
#207
