### ISSUE TITLE
Storage buffer access: compatibility with the pipeline layout

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1837]
This is a follow-up to #287, specifically about storage buffers.
In particular, the following questions need to be answered:
  1. given a buffer that's used as read-only storage in WGSL, is it compatible with a `GPUBindGroupLayoutEntry` that is read-write? I don't think the spec has clear rules for this.
  2. are multiple read-write storage bindings be compatible within the same usage scope? Currently, this is allowed by the spec.
  3. is read-only storage usage compatible with read-write storage usage? Currently the spec says no.

**Comment by kvark** [comment]
Personally, I feel rather strongly that (2) and (3) are currently well specified and do not need changes.

As to (1), it's more subtle. I have a concern about the user-authored code. If I'm writing a shader that has a read-only storage buffer, I don't expect the data to change:
```rust
struct Instance {
  position: vec4<f32>,
};
var<storage, read> intances: array<Instance>;
...
const pos = intances[instance_index].position;
// this may end up producing different positions for different vertices of the same instance
```

I believe we should just say that the shader declarations need to match the bindings exactly, at least for MVP, and then consider relaxing it more if it's desired.

**Comment by Kangz** [comment]
Thank you for the explanation.

I was definitely very confused in yesterday's call and forgot that readonly storage buffers had to work at the same time as other readonly usages. This means they have to be SRVs in D3D12 and can't be used as read write storage since that would be UAV. Plus like you said, it would be confusing for user-authored code.

Happy to close this issue as won't fix.

**Comment by Kangz** [comment]
Actually 1) is interesting. ["validate shader binding"](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-shader-binding) asks that a readonly storage buffer in the shader matches with a readonly storage buffer in the layout. However [Default pipeline layout](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-shader-binding) automatically promotes a readonly storage buffer to storage buffer if needed. One of these two should be changed to match the other.

As a side note, Dawn doesn't do "validate shader binding" as specced at the moment, but does layout defaulting as specced.

**Comment by kvark** [comment]
Interesting. Yeah, I think we should just change the Default pipeline layout to be strict.

**Comment by Kangz** [comment]
I think we can resolve this: for 1) and 3) the spec is clear that the layout's binding must match the readonlyness of the WGSL declaration (in [validating shader binding](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-shader-binding)):

> If entry.buffer.type is:
>
> - "uniform": variable is declared with the storage class uniform.
> - "storage": variable is declared with the storage class storage and access mode read_write.
> - "read-only-storage": variable is declared with the storage class storage and access mode read.

2) is clearly something we want, but #2065 is still open.

So the only thing left is to fix the default layout algorithm.

**Comment by Kangz** [comment]
Actually the default layout is already fixed. Closing this issue.
