### ISSUE TITLE
Add extent/origin/color "reification" step

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1838]
We should make the sequence overloads of these types strictly verify the number of elements in the input sequence.

GPUExtent3D: 1-3 elements
GPUOrigin3D: 0-3 elements
GPUOrigin2D: 0-2 elements
GPUColor: exactly 4 elements

Will be a little bit of work to go through and change usages of GPUExtent3D.

What we would do is change Extent3D from being a "magic" interface wrapping GPUExtent3D, to a real object that is explicitly created from a "reify GPUExtent3D" algorithm in the spec.

_Originally posted by @kainino0x in https://github.com/gpuweb/gpuweb/issues/1712#issuecomment-861028230_

**Comment by kainino0x** [comment]
tacit resolution candidate to add the validation. This becomes editorial once we either agree to validate or agree to not validate.

**Comment by kainino0x** [comment]
From a discussion between Brandon and myself. The options here are:

1. No validation. Benefit: Users never have to create a copy of their source just because the validation demands it. Pretty rare case though, because you can't provide an array offset. Main use case would be that you can reuse an array object, but you can still do this, just set `.length = 4` (or whatever).
   1. Implementation doesn't do anything special. Likely to have poor performance because it converts the whole sequence instead of just the relevant elements.
   1. Implementation issues a warning message. This is not much better than an error, because you can't silence the warning in any way that wouldn't silence the error too.
   1. Implementation adds custom bindings code to convert only the relevant elements. This is entirely doable, but it has an implementation cost for a very minor benefit.
1. Add validation. Benefit: Users stay away from the path that would potentially require implementations to do special optimization work, so we don't have to.

Given this we're both in favor of adding the validation.

**Comment by Kangz** [comment]
Since adding validation was also @litherum's opinion IIRC, putting this on the tacit resolution queue to add the validation.

**Comment by kainino0x** [comment]
Filed https://github.com/gpuweb/cts/issues/2225, we should really get this tested

**Comment by kainino0x** [comment]
I guess we haven't decided if this should be RangeError or TypeError.

**Comment by kainino0x** [comment]
TypeError makes more sense to me. If you use a GPUColor dict but are missing a key, that's a TypeError. There's no dict error for providing _too many_ keys (that's just plain valid), but it would be silly for the two errors to be different.
