### ISSUE TITLE
[wgsl]: `atomic` missing from keywords and grammar

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#1840]
`atomic<T>` has no entry in [14.1. Keyword Summary](https://www.w3.org/TR/WGSL/#keyword-summary), nor an entry in [4.7. Type Declaration Grammar](https://www.w3.org/TR/WGSL/#type-declarations).

**Comment by dneto0** [comment]
Fixed by https://github.com/gpuweb/gpuweb/pull/1841
