### ISSUE TITLE
Should the alignment of destinationOffset in resolveQuerySet be 256 on Metal?

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#1845]
On macOS 11.0+, [[MTLBlitCommandEncoder resolveCounters:inRange:destinationBuffer:destinationOffset:]](https://developer.apple.com/documentation/metal/mtlblitcommandencoder/3194347-resolvecounters?language=objc) requires the `destinationOffset` to be a multiple of 256 when Metal API validation is enabled, that means we need to change the `destinationOffset` alignment from 8 to 256 in `resolveQuerySet`.

But,
- `[MTLBlitCommandEncoder resolveCounters]` is supported since macOS 10.15, and has no such restriction on macOS 10.15.
- Apple [document](https://developer.apple.com/documentation/metal/mtlblitcommandencoder/3194347-resolvecounters?language=objc) does not say the `destinationOffset` must be a multiple of 256.
- The data type in `destinationBuffer` are `uint64_t`, it doesn't make sense to request the `distinationOffset` to be a multiple of 256, the alignment of 8 should be reasonable.

Is it a real restruction newly added on macOS 11.0 for some reason or a bug in the `MTLDebugBlitCommandEncoder`?

**Comment by litherum** [comment]
The limit comes from the row in the [Metal Feature Set Tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) labeled "Minimum buffer offset alignment". The alignment requirements are 4B everywhere except macOS, which requires 256B.

So, yes, I do think we need to require WebGPU's query destination offset alignment to be 256B.

**Comment by kainino0x** [comment]
It's not intuitive that that limit applies here - thanks for the info!

**Comment by haoxli** [comment]
@litherum, thanks for your confirmation!

**Comment by kainino0x** [comment]
Sounds like this needs to be updated in the spec then.
