### ISSUE TITLE
Does compositingAlphaMode affect using the canvas as an image source?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#1847]
In #1839 we spec the behavior of reading from WebGPU canvases from other APIs, but we need to clarify whether compositingAlphaMode affects those.

1. If compositingAlphaMode is "opaque" does that mean e.g. drawImage reads opaque values?
2. If we add compositingAlphaMode "unpremultiplied" would that mean e.g. texImage2D sees it as an unpremultiplied source?

~~My initial feeling is that the answers to both should be yes. In that case we should also probably rename compositingAlphaMode to something like canvasAlphaMode.~~

**Comment by kainino0x** [comment]
Actually I'm not sure which makes more sense.
1. Reading opaque values seems unnecessary, and may cause complications for implementations which only do premultiply/unpremultiply conversions now, and not "opaquification" conversions.
2. I think the answer to this would need to be yes, though it only matters if we actually add that mode (which we are hoping not to do). Still, the possibility _may_ warrant changing this from `compositingAlphaMode` to `canvasOutputAlphaMode` or something.

**Comment by kainino0x** [comment]
Or two separate flags, `compositeAsOpaque` (which doesn't affect using it as an image source) and `alphaPremultiplied` (which affects both compositing and using it as an image source).

**Comment by kainino0x** [comment]
Another side note: recent [additions](https://gpuweb.github.io/gpuweb/#abstract-opdef-get-a-copy-of-the-image-contents-of-a-presentation-context) to the spec mean that webgpu canvases can't be both composited and used as image sources at the same time. So on macOS, where we have to clear the alpha channel to get the "opaque" compositing behavior, we _do_ have the opportunity to do so without affecting `drawImage` et al.)

**Comment by kainino0x** [comment]
Meeting: This should be blocked on #1988

**Comment by Kangz** [comment]
#1988 is post-V1. What is the tacit resolution candidate for this?

**Comment by kainino0x** [comment]
We don't have a proposal yet, I just put that label to indicate that editors should discuss and look for a solution we can propose. Specifically, one that is not blocked on #1988, just defines the behavior and keeps the API open for future improvements.

**Comment by kainino0x** [comment]
_More_ specifically, the spec actually says you can't use already-composited results as an image source:
- [get a copy of the image contents of a context](https://gpuweb.github.io/gpuweb/#abstract-opdef-get-a-copy-of-the-image-contents-of-a-context) returns the contents of `[[currentTexture]]`
- [present the context to the canvas](https://gpuweb.github.io/gpuweb/#abstract-opdef-present-the-context-content-to-the-canvas) removes the `[[currentTexture]]`

and we need to make sure that's OK because I'm pretty sure it resolves this issue.

**Comment by kainino0x** [comment]
If we add a way to read back the "display buffer" (presented image), then compositingAlphaMode would need to affect the result of that readback (on all platforms for consistency) because some platforms have to clear the alpha channel to 1.0 for presentation.
https://github.com/gpuweb/gpuweb/issues/2743#issuecomment-1093584347

**Comment by shaoboyan** [comment]
I think we have conclusion in this issue that we don't apply `compositingAlphaMode ` to the `drawing buffer` content. Can we close this issue?

**Comment by kainino0x** [comment]
It's not concluded yet because I need to make a proposal for #2743. I think the solution there is going to necessitate compositingAlphaMode affecting drawImage/toDataURL/etc.
