### ISSUE TITLE
roadmap question

### ISSUE THREAD

**Issue by sylvaincordiere** [gpuweb/gpuweb#185]
Hi 
last year @Kangz give us this road map with his hope of mvp shipping in early 2019

![gdg](https://user-images.githubusercontent.com/39384609/51792016-22982a80-21ac-11e9-8413-f6899ebabe10.png) 

Is there any change in webgpu mvp shipping ?

**Comment by Kangz** [comment]
@sylvaincordiere look at the slide title, this was meant as "not before" timeline and is obviously wrong :). That said the group is trying to snapshot a first version of the IDL "soon" so browser can start working on semi-interoperable implementations. We are roughly at the start of "implement MVP" which means we are at least 6 months behind.

**Comment by litherum** [comment]
Given that the question has been answered, can we close this issue?
