### ISSUE TITLE
wgsl: fix contradiction between  function pointer argument rules and builtin functions

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1850]
Pointer arguments to functions are limited, e.g. to certain storage classes: function, private, and workgroup
But arrayLength and the atomics take pointers to the storage storage class.
This contradiction should be fixed.

**Comment by ben-clayton** [comment]
Related: https://github.com/gpuweb/gpuweb/issues/1846

**Comment by alan-baker** [comment]
I think it's ok that the restrictions defined in function restrictions only apply to user-defined functions. Maybe just changing the section title to `User-defined Function Restrictions` is enough.
