### ISSUE TITLE
Spec doesn't compile

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1852]
After a `bikeshed update` running `bikeshed spec index.bs` produces the following error:

```
LINK ERROR: No 'idl' refs found for 'PredefinedColorSpace'.
{{PredefinedColorSpace}}
LINE ~5558: Couldn't find section '#premultiplied-alpha-and-the-2d-rendering-context' in spec 'html':
[[html#premultiplied-alpha-and-the-2d-rendering-context|always premultiplied]]
```

I know how to fix the first one but I don't know which HTML spec Bikeshed is using to check the second link. @kainino0x do you know?

**Comment by kainino0x** [comment]
At least PredefinedColorSpace was added very recently, I think you need to `bikeshed update` to get the refs into your local bikeshed database.

**Comment by Kangz** [comment]
I still get this even with a fresh bikeshed update:

```
[cwallez@cwallez-macbookpro2:~/dev/gpuweb]%bikeshed update
Updating via manifest...
Deleted 136 old data files.
Updating 1145 files...
Done!
[cwallez@cwallez-macbookpro2:~/dev/gpuweb]%make -C spec
bikeshed --die-on=everything spec index.bs
LINK ERROR: No 'idl' refs found for 'PredefinedColorSpace'.
{{PredefinedColorSpace}}
 ✘  Did not generate, due to fatal errors
make: *** [index.html] Error 2
```

**Comment by Kangz** [comment]
Ah but the issue below disappeared. I know how to make a fix for the PredefinedColorSpace one if you want me to do it.

```
LINE ~5558: Couldn't find section '#premultiplied-alpha-and-the-2d-rendering-context' in spec 'html':
[[html#premultiplied-alpha-and-the-2d-rendering-context|always premultiplied]]
```

**Comment by Kangz** [comment]
Turns out I was having a stray directory in my `PATH` that made me use an old bikeshed version.

**Comment by kainino0x** [comment]
For reference:
```sh
pip install --upgrade bikeshed
bikeshed update
```
