### ISSUE TITLE
The semicolons are an attempt to better separate the conditions.  These complex rule sets are visually crammed in a narrow box.

### ISSUE THREAD

**Issue by hmarsanch1** [gpuweb/gpuweb#1856]
The semicolons are an attempt to better separate the conditions.  These complex rule sets are visually crammed in a narrow box.

_Originally posted by @dneto0 in https://github.com/gpuweb/gpuweb/pull/1851#r653711227_

**Comment by kainino0x** [comment]
Appears to be spam or accidental.
