### ISSUE TITLE
Rules about "break" inside "continuing" are strange

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1867]
This is a very elaborate set of rules:
```
When a break statement is placed such that it would exit from a loop’s § 7.3.8 Continuing Statement, then:
    The break statement must appear as either:
        The only statement in the if clause of an if statement that has:
            no else clause or an empty else clause
            no elseif clauses
        The only statement in the else clause of an if statement that has an empty if clause and no elseif clauses.
    That if statement must appear last in the continuing clause.
```

It's basically "no `break` inside `continue`, unless at the very end behind an `if`".

Would it make sense to express this via language syntax instead?
```rust
var a: i32 = 2;
var i: i32 = 0;
loop {
  let step: i32 = 1;
  if (i % 2 == 0) { continue; }
  a = a * 2;
  continuing {
    i = i + step;
  } unless (i>=4);  // <--- HERE
}
```

**Comment by dneto0** [comment]
What this is trying to allow is that only the last node in the CFG of the continuing region is allowed to escape the loop. But it also has to have the backedge to the top of the loop. (That's implicit in WGSL but explicit in SPIR-V).

My original proposal was to allow a conditional break as the last statement

    break if i>=4;

or 

    break unless i < 4;

If we have that the rule is much simpler:

     >  ... then the break must appear last, and must be a conditional break.

But conditional-break was removed after a long argument.

**Comment by kvark** [comment]
I don't think the conditional break would address this nearly as good as the specific `unless` syntax. With conditional break, you'd still have this restriction written down, just simpler (as you wrote it). With specific syntax, it would be a part of the grammar.

**Comment by jimblandy** [comment]
I found the restrictions on `break` statements in `continuing` blocks difficult to rationalize, until I finally understood that the SPIR-V looping restrictions permit that final back edge to be a _conditional_ branch. It's an awfully strange rule.

C's do-while loops provide an established notation for a conditional back edge. Perhaps they could be adapted to WGSL like this:

```
loop {
    ... body ...
    continuing {
        ... restricted statements ...
    }
} while (condition);
```

**Comment by jimblandy** [comment]
The weird thing is that, the loop's variables would need to be in scope for the `condition` expression.

**Comment by dneto0** [comment]
> The weird thing is that, the loop's variables would need to be in scope for the condition expression [edit] including variables introduced in the continuing clause.

Right.  

If we place the new clause as @kvark proposed:

```
loop {
    ... body ...
    continuing {
        ... restricted statements ...
    }
    while (condition);
}
```
Then then the condition can access the identifiers declared in the loop body.  We'd modify the scope rule for the identifiers introduced in the continuing clause to say their scope extends to the end brace of the enclosing loop.

Quibble: For the negated condition case I've seen `until` (hmm. Visual Basic...) instead of `unless`.   But unless has broader potential usage.

**Comment by dneto0** [comment]
I just realized that placing

```
     while(condition);
```
is exactly the same as if we allowed a _new_ statement between the continuing clause and the loop end:
```
     break unless (condition);
```
It's just spelled differently.   :-)

**Comment by Kangz** [comment]
I believe the spec was fixed here. Can someone check and close this issue?

**Comment by kvark** [comment]
The spec spells out the rule, but it doesn't become less strange.
I think a proposal is needed for an alternative syntax. Back when we discussed this, I recall @jimblandy interested in pursuing this, so we'll discuss it again.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-vf2f-2022-02-08,09-minutes#burndown-of-httpsgithubcomorgsgpuwebprojects2">WGSL meeting minutes 2022-02-08</a></summary>

    * DM to comment and close

</details>

**Comment by kvark** [comment]
Just a heads up that we are still likely going to come back with a proposal here, contrary to what I said on the last meeting.
Sorry about the delay!

**Comment by dneto0** [comment]
Well, the original idea was to support

       break if condition;   // where condition is a boolean expression

**Comment by jimblandy** [comment]
Syntaxes like this seem good:

```
loop {
    ...
    continuing {
        ...
        break if (expr);
    }
}
```

and

```
loop {
    ...
    break if (expr);
}


```

Like the current spec, and unlike many of the other proposals, it's clear that variables declared in the `loop` and `continuing` blocks are still in scope in `condition`.

There's no need to make `break if` a generally available syntax. It could be restricted to appear only at the end of a `continuing` block or a `loop` without a `continuing` block, as shown.

These constraints could be easily captured in the grammar, which several people have expressed a wish for.

**Comment by dneto0** [comment]
FYI. The current rules (and a few examples) were introduced in #837

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-02-22-minutes#rules-about-break-inside-continuing-are-strange--issue-1867-">WGSL meeting minutes 2022-02-22</a></summary>



* DN: Don’t need parentheses.
* MM: So just `break if` in `continuing`?
* JB: Or at the end of a `loop` with no `continuing`
* MM: But if it’s supposed to just be for `continuing`
* JB: SPIR-V requires a `continuing`, but we let wgsl omit it.
* **Resolve: `break if` allowed as final statement in `continuing`, but not elsewhere.**


</details>
