### ISSUE TITLE
Structs vs out params

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#1870]
We have some functions in the standard library which (conceptually) produce 2 values. We could represent these in two ways:

# Options

(please excuse my pseudocode)

### Option 1
```
struct Output {
    output1;
    output2;
}
theFunction(input) -> Output;
```

### Option 2:
```
theFunction(input, ptr<output2>) -> output1;
```

# Arguments

Arguments in favor of option 1:

1. It's conceptually cleaner and more intuitive. The input goes inside the `()` and the output goes after the `->`. It's easier to read.

Arguments in favor of option 2:

1. It you want `output1` or `output2` in a particular place (like in a buffer or something, or maybe passing as adjacent arguments to a function) you have to store them in a temporary, and write more lines of code to copy them to wherever they need to go.
2. Depending on the ABI, we might not be able to return `output2` in a register if we're using structs
3. If you don't want `output2`, you can pass null (maybe)
3. The function signatures match C (this may actually be a detriment, though)
4. Naming the structs is vaguely somewhat difficult

## Other consideration: Tuples

If we go with the structs, we should make sure it's forward compatible if we want to add auto-unwrapping of tuples in the future. If we add tuples, it should also be valid to say

```
let (output1, output2) = theFunction(input);
```

Or maybe even
```
let (_, output2) = theFunction(input);
```

If we go with option 1, and if we add tuples in the future, that may mean that we either:
- Add more overloads of `theFunction()` to have an overload that returns a tuple, and specify calling rules which make it possible to determine which overload you're calling when the only difference is the return type, or
- Not add overloads, but make _all_ structs auto unwrap into tuples. These new structs would behave just like any other structs.

**Comment by ben-clayton** [comment]
Related: https://github.com/gpuweb/gpuweb/issues/1480

**Comment by litherum** [comment]
I grepped for "ptr" in section 16 of the spec, and only found 2 places where we have out params:

```
frexp(e1: T ,e2: ptr<SC,I,A> ) -> T
```
> T is f32 or vecN<f32>
> 
> I is i32 or vecN<i32>, where I is a scalar if T is a scalar, or a vector when T is a vector

and

```
modf(e1: T ,e2: ptr<SC,T,A> ) -> T
```
> T is f32 or vecN<f32>

**Comment by litherum** [comment]
> Related: #1480

Oh, this totally looks like a dup.
