### ISSUE TITLE
can pipeline creation fail in the driver compiler?  particularly due to shader compilation failure

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1872]
Raised during the [2021-06-22 WGSL meeting](https://docs.google.com/document/d/1B1AOef5rhXVNMiv5Ua31QJ0vTGf0wA4jq7tDbUCTY30/edit)

Can the following happen:
- shader modules created successfully
- pipeline creation parameters pass validation
- but pipeline creation fails in the underlying (platform) driver anyway.

# Context: checking workgroup memory exhaustion.

The context where this was raised is where pipeline-overridable constants are used to size variables in workgroup storage, and that somehow exhausts the workgroup storage.  

In this particular case, the browser might check for exhaustion in advance because, for example:

## Metal limits for threadgroup memory

Metal feature set tables list "maximum total threadgroup memory allocation" in [feature set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf)

  Note there is also a "threadgroup memory length alignment" of 16B, which sounds like an alignment reuqirement on each threadgroup variable.

## Vulkan limits for workgroup memory
 Vulkan can report a device limit maxComputeSharedMemorySize in [VkPhysicalDeviceLimits](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkPhysicalDeviceLimits). 

Ignoring extensions, the size (and layout) of values in workgroup memory is implementation-defined, but the total size can be bounded: From the description of maxComputeSharedMemorySize:

> The amount of storage consumed by the non-Block variables declared with the Workgroup storage class is implementation-dependent. However, the amount of storage consumed may not exceed the largest block size that would be obtained if all active non-Block variables declared with Workgroup storage class were assigned offsets in an arbitrary order by successively taking the smallest valid offset according to the Standard Storage Buffer Layout rules. (This is equivalent to using the GLSL std430 layout rules.)

# Other cases

The other case I mentioned is: if the shader is too complex, then compilation could fail.
Some people really do push boundaries in unusual ways, e.g. with machine-generated code.  SPIR-V has a set of limits to draw the line somewhere.  https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Limits
These limits protects some limit in an implementation detail of underlying driver compilers.

**Comment by alan-baker** [comment]
I have seen enough bugs in drivers that I think we have to accept pipeline creation failing due to shader compilation as a possibility. I have seen drivers crash or return invalid result codes. Theoretically, pipeline creation in Vulkan cannot fail, but in practice this is not the case.

**Comment by dneto0** [comment]
My view is:

* Pipeline creation can fail. The API design allows for failure, because the application could violate a rule.
* But it can also fail for reasons the browser can't anticipate. See what @alan-baker  said.  For example, you exhaust memory in the compiler itself, or compilation is happening in another process that gets killed, or across a network.

**Comment by dneto0** [comment]
The browser should check as much as it can before invoking the driver's pipeline compiler, so it can generate good diagnostics in most cases, and guide the developer on how to fix the problem. 

Ultimately it's an implementation detail as to why a failure occurs.  This goes along with the group's prevailing attitude about *not* standardizing error codes or error reasons.

**Comment by kvark** [comment]
@dneto0 thank you for filing this!

> Pipeline creation can fail. The API design allows for failure, because the application could violate a rule.
> But it can also fail for reasons the browser can't anticipate. See what @alan-baker said. For example, you exhaust memory in the compiler itself, or compilation is happening in another process that gets killed, or across a network.

There is a big difference between these failures. First one can be anticipated by the user. I.e. a careful user should be able to ask for pipeline creation in a way that does not fail, based on the valid usage of our API. It's not an accidental failure.

The second class of failures are fatal. It's basically "device lost". It can't be anticipated, and there is no point to continue trying to do anything in this case. This is also within the spec.

The real problem here is the third case:
> The other case I mentioned is: if the shader is too complex, then compilation could fail.

It's a problem because it can neither be anticipated, or is fatal. WebGPU API has no means of handling it.

**Comment by Kangz** [comment]
> It's a problem because it can neither be anticipated, or is fatal. WebGPU API has no means of handling it.

The pipeline compilation would fail and you'd get an error object. This is opaque, unless you use `createPipelineAsync`. Maybe we could add some metadata on `createPipelineAsync` to tell you if it is a validation error or just that the compiler failed for another unknown reason.

**Comment by dneto0** [comment]
> Maybe we could add some metadata on createPipelineAsync to tell you if it is a validation error or just that the compiler failed for another unknown reason.

+1 to adding some amount of detail. It's very frustrating to get an unexplained failure. (I shake my fist at VK_INCOMPLETE!)   I don't know that we can pin down or structure that detail.

Hopefully a validation failure would be considered a bug in the browser.  But a resource exhaustion may be unavoidable.
(E.g. in OpenCL I've seen a lot of kinds of errors fall back on reporting CL_OUT_OF_HOST_MEMORY, which ends up as the miscellaneous bucket.)

Here's another "too complex" kind of case:
 - You set a compute shader required workgroup size at little on the high side.
 - Then it's very easy to write just a little too much shader code that causes a register budget to overflow.  The driver compiler can't recover, and errors out.

I point this out explicitly because 

1. The shader doesn't have to get too complex for this to happen.  
2. Applications will autotune around the failure case: they try to get maximum parallelism by probing for the maximum workgroup size _that still compiles_.

So it will be a common and intended case.

**Comment by kvark** [comment]
> Then it's very easy to write just a little too much shader code that causes a register budget to overflow. The driver compiler can't recover, and errors out.

Theoretically speaking, aren't the drivers required to cope with this by spilling registers? I.e. the Vulkan spec lists only the following return codes allowed:
        - VK_ERROR_OUT_OF_HOST_MEMORY
        - VK_ERROR_OUT_OF_DEVICE_MEMORY
        - VK_ERROR_INVALID_SHADER_NV

So one could say that a driver failing for any other reason is non-conformant and should not be exposed to WebGPU.

**Comment by dneto0** [comment]
> So one could say that a driver failing for any other reason is non-conformant and should not be exposed to WebGPU.

In practice what you'll get is probably ...OUT_OF_DEVICE_MEMORY.  And it wouldn't be wrong.  It's just a different bucket/form of memory than you expected (which is probably buffer memory).

There will always be ways to stimulate a failure that you can't anticipate.  Shader compilation is a leaky abstraction.

**Comment by dneto0** [comment]
This workgroup-sizing issue came up in code review in Tint.
See https://dawn-review.googlesource.com/c/tint/+/57740/comments/9dbd4dad_11d79f9e 
Metal and Vulkan provide sufficient guidance, but D3D seems a bit wobbly to me (no guidance on packing or alignment).

**Comment by kvark** [comment]
If we are talking about OOM, then there is nothing to do here. OOMs are already handled by the spec.

**Comment by dneto0** [comment]
I'm asserting there will be failure cases which can't be well anticipated.  It can't always be averted by doing a calculation of total memory demand and checking that against some driver limit.

> If we are talking about OOM, then there is nothing to do here. OOMs are already handled by the spec.

A failure of any kind can be _reported_ as an OOM, but that might be misleading.

Processing on the shader still occurs up to pipeline creation.  I finally looked at the error possibilities for creating compute and render pipelines.   The async forms return a promise that can fail. That's great.  The synchronous forms can fail only for specified reasons, and return a GPUValidationError. 

I'm arguing that the synchronous versions should have a "unknown failure" reason to account for the driver compiler errors that the browser can't anticipate.  GPUValidationError has a message field to carry details.  The fact it's called _validation_ is kind of wrong, but we can add a note to explain the difference. Alternately, make a separate GPUUnknownError class.

**Comment by dneto0** [comment]
(Another way to say this is that pipeline creation is or is forced to be a [leaky abstraction](https://en.wikipedia.org/wiki/Leaky_abstraction). )

**Comment by Kangz** [comment]
Tentatively closing since there is now a concept of "spurious" failures.
