### ISSUE TITLE
Remove the requirement for Vulkan's drawIndirectFirstInstance feature.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1878]
This feature is implicitly required by the WebGPU specification but it has relatively low coverage on Android with 60% of devices supporting it. I think we should remove it from the spec and ask that the firstInstance arguments to `DrawIndirect` and `DrawIndexedIndirect` be 0, otherwise the drawcall is nooped.

**Comment by kainino0x** [comment]
I think you meant `drawIndirect` and `drawIndexedIndirect` as those appear to be the ones affected by Vulkan's `drawIndirectFirstInstance` feature

**Comment by Kangz** [comment]
Indeed :) Edited the comment.

**Comment by mrshannon** [comment]
Since WebGPU does not have push constants like Vulkan, being able to set `firstInstance` to arbitrary values was the only way to pass an object id without a rebind.  So while Vulkan can get by with `firstInstance = 0` I am not sure WebGPU can.

**Comment by kvark** [comment]
@mrshannon passing `firstInstance` without rebinding is only beneficial for direct draw calls. Here, we are talking about indirect calls. So some shader writes the indirect data into a buffer, it may as well write any other parameters into another buffer, which is then seen as, say uniform by the draw call. So I don't think push constants are relevant here.

**Comment by mrshannon** [comment]
Good point, this does not effect `drawIndexed`.

**Comment by kainino0x** [comment]
Resolution:
Add this restriction to the spec.

Later, consider the whole matrix of optional features together: drawIndirectFirstInstance, multiDrawIndirect, drawIndirectCount, (...?)
