### ISSUE TITLE
Operations happening in GPUVertexState are underspecified

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#1880]
Noticed this during a discussion with @ben-clayton about how to implement programmable vertex pulling in Metal.

A lot of things should be detailed on how `GPUVertexState` operates. We discussed some of these issues in the past but needed and investigation. I wrote pretty detailed CTS operation tests that pass on all systems and confirmed a lot of contraints / behavior of the APIs.

 - [ ] `GPUVertexFormat` and shader input variable matching rules (confirmed that only the base type needs to match)
 - [ ] what happens when the number of components of `GPUVertexFormat` and the shader input variable don't match (confirmed either drops components, or fills unspecified components with y->0 z->0 w->1).
 - [ ] what input variables are considered, currently the spec still mentions static use, which is outdated with the new IO entrypoints.
 - [ ] what is the packing of vertex formats in memory (confirmed it is x, y, z, w in that order in memory)
 - [ ] how are each of the `GPUVertexFormat` interpreted? (confirmed the corner case that snorm gets clamped to [-1, 1])
 - [ ] other stuff I'm missing?

We should improve the specification in that area.

**Comment by kainino0x** [comment]
> * how are each of the `GPUVertexFormat` interpreted? (confirmed the corner case that snorm gets clamped to [-1, 1])

To clarify, by this you mean e.g. snorm8 values of -127 and -128 both map to -1.0?

**Comment by Kangz** [comment]
That's correct (and experimentally it is what happens on all APIs)

**Comment by kvark** [comment]
Fixed by #1908
