### ISSUE TITLE
API should be exposed to DedicatedWorker

### ISSUE THREAD

**Issue by Kaiido** [gpuweb/gpuweb#1882]
Currently the [GPUPresentationContext](https://gpuweb.github.io/gpuweb/#gpupresentationcontext) interface is only exposed to Window contexts, certainly it should also be exposed to DedicatedWorkers (according to what was said in #403).

```webidl
[Exposed=(Window,, DedicatedWorker)]
```
and related, while in multiple places it's said `[[canvas]]` can be an `OffscreenCanvas`, [its definition](https://gpuweb.github.io/gpuweb/#dom-gpupresentationcontext-canvas-slot) states 

> `[[canvas]]` of type [HTMLCanvasElement](https://html.spec.whatwg.org/multipage/canvas.html#htmlcanvaselement). 

[OffscreenCanvas](https://html.spec.whatwg.org/multipage/canvas.html#the-offscreencanvas-interface) should be added, though I'm not sure of the nomenclature here.

**Comment by kainino0x** [comment]
We're currently missing the `[Exposed]` attributes for the almost the entire WebGPU API, and that's partly because we haven't worked through editorial details yet for sharing between threads. However, allowing single-threaded access from workers is not complicated, and also requires us to do this.

**Comment by jdashg** [comment]
I think we should discuss where this should happen on our roadmap to release, since it may impede implementation progress.
