### ISSUE TITLE
Does visibility affect BindGroupLayoutBinding identity?

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#189]
Is the following a valid BindGroupLayoutDescriptor?

```JS
[{binding: 0, visibility: GPUShaderStageBit.VERTEX, type: "uniform-buffer"},
 {binding: 0, visibility: GPUShaderStageBit.FRAGMENT, type: "uniform-buffer"}]
```

I propose no, because it makes the implementation simpler.

**Comment by magcius** [comment]
The question here is whether we have per-stage bindings.

D3D11 HLSL supports per-stage bindings through the `register(ps, r0)` syntax, and resources in D3D11 have to be bound separately for each shader stage.

D3D12's root descriptors are also global to the PSO.

Metal has per-stage bindings as well (setVertexBuffer, setFragmentBuffer).

Vulkan bindings are global to the pipeline, so it does not support this out of the box, but you can emulate this by picking some offset and putting the individual stage bindings there.

**Comment by kainino0x** [comment]
Sorry, I checked to make sure you hadn't posted an issue already when I went to make #192, but I clearly missed it.

**Comment by kainino0x** [comment]
Anyway, I think the intent was this would be invalid. I'm pretty sure it is invalid in Dawn.

**Comment by Kangz** [comment]
Agreed that this should be invalid: this way a bindgroup binding corresponds to a single hardware descriptor. Hardware that has per-stage descriptor (most of them?) will split the bindgroup in two descriptor tables so the stage mask helps it prune unused descriptors from a stage's descriptor table.

**Comment by Kangz** [comment]
Seems everyone agrees that the snippet in the first comment should be invalid.
