### ISSUE TITLE
WGSL: Support type conversion from bool to int/uint/float

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#1910]
Current WGSL SPEC only [defines the type conversion froms `int`/`uint`/`float` to `bool`](https://gpuweb.github.io/gpuweb/wgsl/#conversion-expr)  but misses the type conversions from `bool` to `int`/`uint`/`float`.

In [GLSL 4.5 (Chapter 5.4.1)](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.50.pdf), [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3d9/casting-and-conversion) and [Metal Shading Language (Chapter 2.19)](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf), `false` is always converted to `0` and `true` is always converted to `1`, so in WGSL SPEC we should have below type conversion rules:

```
i32(true) == 1
u32(true) == 1u
f32(true) == 1.0
i32(false) == 0
u32(false) == 0u
f32(false) == 0.0
```

**Comment by dneto0** [comment]
This seems reasonable and is not too disruptive.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-07-13-Minutes#wgsl-support-type-conversion-from-bool-to-intuintfloat-1910">WGSL meeting minutes 2021-07-13</a></summary>



* DN: What about vector versions? 
* DM: Needs investigation?
* DN: Let’s take scalars for now and look at vectors separately.
* (-> Needs spec, DN to take)


</details>

**Comment by dneto0** [comment]
Investigation of the vector case.

The summary is that graphics shader languages act component-wise.  OpenCL is different.

I recommend we implement that component-wise consensus.


## MSL.

In  2.19 Type Conversions.
> The `static_cast` operator is used to convert from a scalar or vector type to another scalar or
vector type with no saturation and with a default rounding mode. 

...

>  If the source type is a
scalar or vector Boolean, the value false is converted to zero and the value true is converted
to one.

## HLSL

I couldn't find definitive documentation but constructor-syntax converts component-wise.

         float4 f = float4(bool4(false,false,true,true));

(see http://shader-playground.timjones.io/1be3c0da22e7521174f3f8d71bbdb649)

And C-style cast works component-wise too:

	float4 f = (float4)bool4(false,false,true,true);

(see http://shader-playground.timjones.io/8d16c42b9d4fd07a1e0513c271023b02)


## SPIR-V

When the Condition operand of the OpSelect instruction is a boolean vector, the result is computed component-wise. So component-wise is directly supported.

## GLSL
References are to [GLSL 4.5](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.50.pdf)

For the scalar case, see 5.4.1:

> When a constructor is used to convert a bool to any
integer or floating-point type, false is converted to 0 or 0.0, and true is converted to 1 or 1.0. 

For the vector case, see 5.4.2:

> If the basic type (bool, int, float, or double) of a parameter to a constructor does not match the basic type
of the object being constructed, the scalar construction rules (above) are used to convert the parameters.

I also confirmed the component-wise behaviour by compiling simple GLSL to SPIR-V.


## OpenCL C

For the scalar case, see the table at [6.3.1 Built-in Scalar Data Types](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#built-in-scalar-data-types):

> The value true expands to the integer constant 1 and the value false expands to the integer constant 0.

For the vector case:  [6.4.2 Explicit Casts](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#explicit-casts)
 says:

>  When casting a bool to a vector integer data type, the vector components will be set to -1 (i.e. all bits set) if the bool value is true and 0 otherwise.

That's what I remembedr d it makes  OpenCL the  oddball.
