### ISSUE TITLE
Consider passing the stride as an argument to `setVertexBuffer`

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1921]
I know it's a bit late for API changes, but perhaps not too late to consider something as small as this.
(Rest of prelude is moved to #1925)

## Issue

Metal and Vulkan have the vertex buffer stride as a part of the pipeline state.

DX12 however gets the stride from `IASetVertexBuffers` call, so at the time of binding. It's not a part of the pipeline state. Therefore, `setVertexBuffer` can not be mapped to DX12 directly. Given that it's potentially a very high-frequency call (vertex buffer can change per mesh), I believe it's important to have the direct mapping for the target backends of WebGPU.

## Specification

Here is a strawman proposal. Change the function signature to the following:
```js
undefined setVertexBuffer(GPUIndex32 slot, GPUBuffer buffer, GPUSize32 stride, optional GPUSize64 offset = 0, optional GPUSize64 size);
```

There is a new `stride` parameter. We'd write the validation in the following way:
> at draw call, the stride for the `GPUVertexBufferLayout` specified in the active `GPURenderPipeline` has to be equal to the `stride` passed in parameter to `setVertexBuffer` at this slot.

## Analysis

This change would have the stride specified twice. This is:
  - mildly annoying
  - similar to setting the index format, which we also require to be specified twice, but only for strip topologies
  - unlikely limiting to any workloads. I don't expect the same buffer data to ever need to be reinterpret under different strides (this is what currently happens if you bind a different render pipeline that has different strides)
  - allowing D3D12 implementation to be simpler, more predictable, and slightly faster

**Comment by austinEng** [comment]
> allowing D3D12 implementation to be simpler, more predictable, and slightly faster

to be clear, this is the difference I see:
Today, the implementation has to lazily apply IASetVertexBuffers because the pipeline might change. So the implementation needs cache to track one bit of information - the "active" pipeline, and make sure IASetVertexBuffers is done sometime before `draw`.

In your strawman proposal, we have to add extra validation. BUT this extra validation is subject to the same requirement to track changes to the pipeline because it applies to the vertex buffers and pipeline currently bound.

So given the implementation has to do some kind of tracking like this anyway, I'm not sure I see why this proposal makes the D3D12 implementation slightly faster.

**Comment by magcius** [comment]
This seems to make the API a lot more awkward to solve some minor implementation friction. Not to mention that the use case we're supposedly making faster here (not rebinding vertex buffers, but are rebinding a new pipeline that uses different strides) does not seem like an important use case to improve.

Looking at how Vulkan is implemented in drivers, it seems like this also handles the rebinding of pipelines with different strides through an "implicit rebind" [0], so I think it's acceptable for the WebGPU implementation to do this as well.

[0] https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/amd/vulkan/radv_cmd_buffer.c#L2856

**Comment by kvark** [comment]
These are fair points, thank you for feedback! It is true that both the validation needs to match the pipeline against the buffers, and that drivers internally already have lazy state to resolve at draw call. So changing the API to make D3D12 path more straightforward is not going to drastically change this situation at large.

It seems a bit unfortunate that D3D12 is the only backend so far that has to do lazy rebinding, but it's acceptable. Unless there are objections, I'm closing this.
