### ISSUE TITLE
[meta] DX12 implementation friction

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1925]
I think some of our API decisions are not sufficiently well informed (which doesn't necessarily mean they are wrong). For D3D12, wgpu used to route it via Vulkan API, so we were happy as long as WebGPU was aligned to Vulkan, and thus we didn't evaluate how good the API actually is for what the group wants to achieve. The only other implementation was in Dawn. So we had roughly 1.5 implementations that seriously considered D3D12 and Metal backend work.

Now that I re-implemented Metal (which works very well!). I'm currently working on the new D3D12 backend for wgpu, so I start to see things under new light. Here is a growing list of issues:

- [x] #1921
- [x] #1926
- [x] #1961

**Comment by Kangz** [comment]
Both issues are closed, maybe we can close this one too?

**Comment by kvark** [comment]
I can re-open this if more things show up.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-01-19#triage-the-issues-without-milestones-timebox-15m">WGSL meeting minutes 2022-01-19</a></summary>



* #1925 DX12 impl friction
    * Closed last year, reopened.
    * KG: marking post-V1.
    * MM: wish these were Wiki articles rather than issues.


</details>

**Comment by kainino0x** [comment]
I think #1961 was the only thing here; closing.
