### ISSUE TITLE
GPUShaderStageBit.NONE seems useless

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#193]
```JS
{binding: 0, visibility: GPUShaderStageBit.NONE, type: "uniform-buffer"}
```

GPUShaderStageBit is only used in one place. Using it in that place seems useless.

Or: Is there a difference between making a resource bound with GPUShaderStageBit.NONE and not having anything bound?

**Comment by kvark** [comment]
I agree that it isn't directly useful. I see this more of a question in general: do we provide NONE consistently for all the bitflag types, or do it on a case by case basis?

**Comment by kainino0x** [comment]
There might be validation here too; it could go either way, IMO: either allow-but-noop the NONE case, or disallow it.

But even if it's invalid to put NONE there, you could imagine an application doing:
```js
let vis = GPUShaderStageBit.NONE;
if (...) vis |= GPUShaderStageBit.VERTEX;
if (...) vis |= GPUShaderStageBit.FRAGMENT;
if (vis) addBinding(vis, ...);
```
so it isn't necessarily good to remove it.

(Tangentially, we could declare that all `NONE`s should be spelled as `0` by applications, and remove all of them.)

**Comment by beaufortfrancois** [comment]
I think we can close this issue with https://github.com/gpuweb/gpuweb/pull/461 merged.
