### ISSUE TITLE
Invalid Web IDL: maxComputeWorkgroupSize cannot be a dictionary type

### ISSUE THREAD

**Issue by tidoust** [gpuweb/gpuweb#1936]
#1898 introduced `maxComputeWorkgroupSize` of type `GPUExtent3D`, which is a dictionary:
https://github.com/gpuweb/gpuweb/blob/main/spec/index.bs#L1291

But the type of an attribute cannot resolve to a dictionary type in Web IDL (see https://heycam.github.io/webidl/#idl-attributes). The Web IDL parser chokes on this construct as a result.

Main reason why Web IDL forbids that is that there would then be no easy way to enforce that the same object would be returned when the attribute gets accessed multiple times (i.e. that `obj.maxComputeWorkgroupSize === obj.maxComputeWorkgroupSize`), which is what developers expect with attributes, see [Attributes should behave like data properties](https://w3ctag.github.io/design-principles/#attributes-like-data) in the TAG's design principles.

Main alternatives would be to use a method or to go to one level deeper with properties such as `maxComputeWorkgroupSizeWidth`, `maxComputeWorkgroupSizeHeight`, `maxComputeWorkgroupDepthOrArrayLayers`.

**Comment by kvark** [comment]
That's a wonderful issue. I think it strikes both concerns that we had at once:
  1. that `maxComputeWorkgroupSizeWidth` and `maxComputeWorkgroupSizeHeight` are not very useful right now
  2. that `GPUExtent3D` in that place is confusing, because it's referring to depth or array layers (of textures)

**Comment by Kangz** [comment]
Should we just use `sequence<unsigned long>`?

**Comment by kainino0x** [comment]
I think so yes.

**Comment by kainino0x** [comment]
Editors: change it to a sequence.

**Comment by kainino0x** [comment]
Actually it might need to be FrozenArray. Hopefully we can check this with the IDL validator.
