### ISSUE TITLE
Disable merge commits and rebase merging?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#194]
I'd like to require all PRs in this repo to be merged via the "squash" method, so that every PR == one commit, and every commit links to its PR.

I can do this, but are there any objections?

**Comment by kvark** [comment]
Every github commit references the PR regardless of whether it was squashed or not, i.e. https://github.com/gpuweb/gpuweb/commit/0644a1c605db2353b704859f0c97a019ab467298 clearly states "master (#191)" with a link to the PR.

That being said, I don't mind squashing everything, but I also don't think it's necessary. Quite often a PR can be structured in such a way that it's represented by a sequence of standalone steps. There should be no need to squash them together. Just rebasing is sufficient.

**Comment by kainino0x** [comment]
I'm happy to keep the rebase option and turn off merge-commit.

**Comment by Kangz** [comment]
No objections here. Merge commits are ugly when they can be avoided.

**Comment by kainino0x** [comment]
3 reviews (including litherum's reaction), so I'm going to go ahead and do this.
