### ISSUE TITLE
Document cubemap face orientation

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1946]
We need to define the association of array layers with the faces of the cube.

**Comment by magcius** [comment]
From experimentation, it's +X, -X, +Y, -Y, +Z, -Z.

**Comment by kainino0x** [comment]
Vulkan: https://www.khronos.org/registry/vulkan/specs/1.2/html/chap16.html#_cube_map_face_selection
D3D (9, but it shouldn't matter): https://docs.microsoft.com/en-us/windows/win32/direct3d9/cubic-environment-mapping

**Comment by kainino0x** [comment]
Metal: https://developer.apple.com/documentation/metal/mtltexturetype?language=objc

All seem to agree.

**Comment by Kangz** [comment]
IIRC we have tests for this in Dawn and found that all backends agree on the cubemap face orientation so it must be what @magcius found.
