### ISSUE TITLE
Clarify the vertex stage output / fragment stage input matching rules 

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#1953]
We need to clarify the vertex stage output / fragment stage input matching rules as currently they are confusing in WebGPU and WGSL SPEC.

- In [WebGPU SPEC](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpurenderpipelinedescriptor): 
  - For each user-defined output of descriptor.vertex there must be a user-defined input of descriptor.fragment that matches the location, type, and interpolation of the output.
  - For each user-defined input of descriptor.fragment there must be a user-defined output of descriptor.vertex that location, type, and interpolation of the input.

- In [WGSL SPEC](https://gpuweb.github.io/gpuweb/wgsl/#pipeline-compatibility):
  - user data inputs of fragment stage must be subset of user data outputs of vertex stage

**Comment by Kangz** [comment]
I think the WebGP specification is the up-to-date one and we should fix the WGSL spec. But maybe we could completely remove that part from WGSL since it is the embedder (WebGPU) that decides of interface matching rules.

**Comment by alan-baker** [comment]
> I think the WebGP specification is the up-to-date one and we should fix the WGSL spec. But maybe we could completely remove that part from WGSL since it is the embedder (WebGPU) that decides of interface matching rules.

Consider that TODO in the WGSL spec as a hold over. I agree interface matching makes more sense in the API spec than the language spec.

**Comment by Jiawei-Shao** [comment]
I think we can close this issue as the section "pipeline-compatibility" has been removed from WGSL SPEC in https://github.com/gpuweb/gpuweb/pull/2206.
