### ISSUE TITLE
Is Timestamp Query not supported on Apple M1?

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#1956]
Timestamp query run with the error on Apple M1 with macOS 11.4:

> -[AGXM1FamilyBlitContext sampleCountersInBuffer:atSampleIndex:withBarrier:]:325: failed assertion `MTLBlitCommandEncoder:sampleCountersInBuffer:atSampleIndex:withBarrier not supported on this device'

By [Checking for GPU Counter Support](https://developer.apple.com/documentation/metal/counter_sampling/checking_for_gpu_counter_support?language=objc), we can get that `MTLCommonCounterSetTimestamp` is supported. 

But checking [supportsCounterSampling](https://developer.apple.com/documentation/metal/mtldevice/3564459-supportscountersampling?language=objc) on `MTLDevice`, we get that:
`MTLCounterSamplingPointAtBlitBoundary` is unsupported,
`MTLCounterSamplingPointAtDispatchBoundary` is unsupported,
`MTLCounterSamplingPointAtDrawBoundary`  is unsupported,
`MTLCounterSamplingPointAtStageBoundary` is **supported**,
`MTLCounterSamplingPointAtTileDispatchBoundary` is unsupported.

Does it mean we just can sample the supported counter at stage boundary (the start and end of a render pass’s vertex and fragment stages, and the start and end of compute and blit passes) on Apple M1?

**Comment by haoxli** [comment]
@litherum Would you like to check if the timestamp query is really not supported on M1?

**Comment by Kangz** [comment]
MTLCounterSamplingPointAtStageBoundary means:

> Counter sampling is allowed at the start and end of a render pass’s vertex and fragment stages, and at the start and end of compute and blit passes.

So technically a WebGPU implementation could choose to split encoders at these points (and push timestamps in render passes at the start or end of the pass). But it could also choose to not bother and not expose the extension on such hardware.

**Comment by kvark** [comment]
Please no splitting encoders PLEASE

**Comment by Kangz** [comment]
Why ? Splitting encoders other than render encoders is okay-ish. And
implementations can just choose to not support the extension if they think
it's not worth it.

**Comment by kvark** [comment]
Ah we aren't talking about render encoders, phew!

**Comment by haoxli** [comment]
Spliting encoders at these points may works, but how do we define whether the extension is supported? On other GPUs, the counter sampling may be allowed at blit boundary, draw boundary and dispatch boundary, but disallowed at stage boundary. We need to tell users which points it supports.

**Comment by Kangz** [comment]
The `timestamp-query` has no guarantee that the values returned are exact (sampling timestamps inside render passes doesn't mean much for tiler GPUs anyway) so I think it's ok for implementations to make choices.

**Comment by haoxli** [comment]
OK, let's disable timestamp query on Apple M1.

**Comment by Kangz** [comment]
Closing in favor of #2046
