### ISSUE TITLE
[wgsl] Limit number of function parameters to 255

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#1959]
This is a bit of a uncommon case, but was found by our fuzzers:

```
Unexpected spirv-val error:
1:1: OpTypeFunction may not take more than 255 arguments. OpTypeFunction <id> '5[%5]' has 256 arguments.
```

Sure enough, the [SPIR-V spec requires the number of parameters and arguments to be &le; 255](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Limits).

I guess we need to bubble up this restriction to WGSL.

**Comment by dneto0** [comment]
SPIR-V has a few [universal limits](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_limits_a_universal_limits) that would clearly translate to the WGSL level.

They adjudicate between "author problem vs. implementation bug".  It's a way to cut off useless arguing over non-pragmatic cases.

Other ones that would translate:
- 255 nesting level on composites.  (This would cover the "structure nesting" and also the access-chain indices).
- about half a million function-scope variables (per function)
- 16383 distinct switch case values/targets per switch.
- 16383 members per struct.

On the other hand failures in this area could be punted to a generic "too complex", as per #1872.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-07-27-Minutes#wgsl-limit-number-of-function-parameters-to-255-1959">WGSL meeting minutes 2021-07-27</a></summary>



* DN: We have fuzzers which hit this limit. There are going to be cases that are easy to spec a rule that says XYZ is definitely invalid for tooling reasons. We want this to be a common limit and put it in the spec. There may be other limits (number of structure members, etc.). We could put the limit in the spec, or not
* RM: We should put it in the spec, if it’s required by the backends. For portability. It’s a common thing, like for web specs
* MM: Two classes.
    * Imagine we put a limit in the spec. Could live in a world where most implementations will succeed if the user program satisfies the limit requirement. Authors will want to know the boundary.
    * Second class.  Limit where almost every implementation will have a de facto limit which is smaller than the limit in the spec. E.g. instead of 255, then have 4B. E.g. every Vulkan device will fail in that case.  So putting that number in the spec is misleading to what will be generally expected to work.
* AB: For the ones David listed, can you review to see what strikes you as reasonable.
* MM: nesting level, switch cases, members per struct; these seem reasonable. Not sure about # function-scope variables (per function); want to consult with the Metal team on that one.
* AB: Another that may map well, is the number of entry points.  First step is to collect candidates.
* JG: Limits are the combo of “thou shalt not write a program with more than this” but are we guaranteeing that if you 255 WGSL function arguments, that we will always be able to compile that?
* AB: No. There can be other issues with your shader.
* MM: It is an indicate of roughly what authors should expect to be able to use
* DN: The half-million limit is wobbly enough that authors won’t get useful information out of the spec. Given that compilation can fail for weird reasons. I’d rather just withdraw that particular limit.
* JG: Resolved: specification needed:
    * 255 nesting level on composites. (This would cover the "structure nesting" and also the access-chain indices).
    * 16383 distinct switch case values/targets per switch.
    * 16383 members per struct.
    * 255 function parameters
* 


</details>

**Comment by dneto0** [comment]
PR #1957 adds the 4 limits discussed in today's meeting.

We can open new issues to add other limits the group may agree on.

**Comment by kainino0x** [comment]
#1997?

**Comment by Kangz** [comment]
Should this be closed now that we have "spurious" errors?

**Comment by kdashg** [comment]
Yeah I think this is done!
