### ISSUE TITLE
Using structured buffers in HLSL

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1961]
If we consider the backend mapping of WGSL's storage buffers to HLSL, then [structured buffers](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-structuredbuffer) appear to be almost an exact hit. The only missing piece to get that mapping to work would be a bit of extra information from the user:
  - whether or not a particular storage buffer has an unsized array part
  - the stride of that unsized array

This could be communicated by adding a field to `GPUBufferBinding`:
```js
dictionary GPUBufferBindingLayout {
    GPUBufferBindingType type = "uniform";
    boolean hasDynamicOffset = false;
    GPUSize64 minBindingSize = 0;
    GPUSize32 unsizedArrayStride; // nullable
};
```

The validation logic would work as follows: if the shader contains an unsized array, then the binding layout has to have `unsizedArrayStride` matching the shader-derived stride (i.e. one from `[[stride(xxx)]]` or computed automatically).

This extra information is needed (even though the shader knows about it) because it affects binding creation at `createBindGroup`: we'd have to fill out the `StructureByteStride` member of [D3D12_BUFFER_SRV](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_buffer_srv) structure.

---

If I understand correctly, both SPIRV-Cross and Tint are currently backing storage buffers with HLSL byte address buffers. Has anybody done an investigation of pros and cons of this approach? It appears to me that using structured buffers would be much more straightforward (thus, easier to implement), and will have a much better developer experience in debugging shaders.

**Comment by ben-clayton** [comment]
> If I understand correctly, both SPIRV-Cross and Tint are currently backing storage buffers with HLSL byte address buffers. Has anybody done an investigation of pros and cons of this approach?

Tint's decision to use `ByteAddressBuffer` predates me joining the team. Maybe @dneto0 or @dj2 can provide some context on why this was picked. It's possible that this just made a lot more sense back when `[[offset]]` existed, and we didn't think to revisit this code.

That said, translating WGSL's structure layout to another language's structure layout rules can be a bit fiddly, and with `ByteAddressBuffer` we eliminate a the complexity of mapping structure layouts (like insertion of padding fields).

**Comment by ben-clayton** [comment]
I have to say though, I'm not keen on having to specify the runtime array stride in both the shader and the `GPUBufferBindingLayout`, especially as we have a viable solution that does not require it.

**Comment by Kangz** [comment]
The problem with `StructuredBuffer` is that it can only represent an unsized array, but WGSL, like GLSL, MSL and SPIRV, allows having a first sized part followed by an unsized array.

At most, what `GPUBufferBindingLayout. unsizedArrayStride` would achieve is that you could sometimes opportunistically translate storage buffer bindings in WGSL to `StructuredBuffer` but not always. It's not clear that you want to support two code paths, and from an implementability POV, `ByteAddressBuffer` is sufficient for the current specs so there's no need to change them. It fine to have some parts of the implementation that are a bit complex.

**Comment by kvark** [comment]
It's not clear to me if `StructuredBuffer` can be used to represent a non-array portion as well. As such, what I was thinking would be to translate this:
```rust
struct Bar {
  x: u32;
};
struct Foo {
  a: i32;
  b: vec4<f32>;
  c: array<Bar>;
};
```
... given the extra `unsizedArrayStride` information, into this:
```cpp
struct Foo {
  int a;
  float4 b;
};
struct Bar {
  unsigned x;
};
StructuredBuffer<Foo> fuu_base: register(t0);
StructuredBuffer<Bar> fuu_array: register(t1);
```

So basically the logic could be: if there is an `unsizedArrayStride`, assume the binding takes 2 slots (base and array).

The only thing that would prevent us from doing this is a stride constraint - it can't exceed 2048 in D3D12. So my sub-question is whether there is a way in HLSL to represent a structured buffer that's not meant to be repeating. I.e. maybe specifying the stride of 0, or any other value. Does it even matter? Maybe D3D12 doesn't care, in which case this isn't a problem for WebGPU implementations.

**Comment by kvark** [comment]
I [checked this](http://shader-playground.timjones.io/5319aadb7991c465c7ccce3dc7bd7578), and it appears that D3D12 *does* care. We can't use the sized portion larger than 2K (as a structured buffer), it's is a pretty low limit. Maybe we can use the constant buffer view of the sized portion, instead?

**Comment by dj2** [comment]
What's the benefit? You're making the translation a little easer by adding burden to the developer by having to pass more information and know that the binding is now multiple slots?

**Comment by kvark** [comment]
> having to pass more information

This is a bit unfortunate, but that's what D3D12 requires for structured buffers, and we are technically using an array of structures, so it makes sense. I do wonder if it can be faster on some platforms because of the AoS -> SoA transformation that the drivers can do internally, based on the stride. Perhaps, @pow2clk can shed some light.

The other downside of this approach is having the size restrictions on both the sized part of storage buffers and the stride of the array structure. These can be annoying, but it's hard to tell for sure.

> know that the binding is now multiple slots

this is internal detail that the developers don't technically need to know about

> What's the benefit?

This is an exploratory issue. I'm mildly annoyed that we are approaching this from the "what's the benefit of A", as if we previously agreed that byte address buffers are the way to go. Nobody discussed this, there was no investigation done or shared anywhere. This is not the way the group operates. What we do generally is:
  1. do an investigation, collect approaches
  2. list the trade-offs for each of the approaches
  3. make a decision and/or recommendation

This process wasn't done for storage buffers on HLSL.

**Comment by Kangz** [comment]
> This is an exploratory issue. I'm mildly annoyed that we are approaching this from the "what's the benefit of A", as if we previously agreed that byte address buffers are the way to go. Nobody discussed this, there was no investigation done or shared anywhere.

ByteAddressBuffers have been mentioned multiple times in the past, although it's true there wasn't an actual investigation-style issue for it. Since WGSL has a sized part and an unsized part in storage buffers, it seems natural to go with `ByteAddressBuffer` although that's an implementation detail. Given that WGSL has been in development for more than a year and that's been part of the initial spec, I'm surprised that it's only now that we're challenging such a core aspect of how WGSL would translate to HLSL.

**Comment by kvark** [comment]
> I'm surprised that it's only now that we're challenging such a core aspect of how WGSL would translate to HLSL.

A good spec needs multiple implementations to ensure that the spec is right. As Noted in #1925, we had 1.5 implementations on DX12 and correspondingly HLSL. The SPIRV-Cross implementation counts as 0.5 because it doesn't care about WebGPU or WGSL, and it can't possibly consider API changes to make the translation nicer (but we can!).

Mentioning `ByteAddressBuffers` many times didn't make it more valid. It was just an indication of the "status quo", which isn't actually great for the spec.

**Comment by Kangz** [comment]
Let's take this on Matrix.

**Comment by kvark** [comment]
We've changed our implementation to use byte address buffers - https://github.com/gfx-rs/naga/pull/1136. I still think a proper investigation or at least a final report is due.
