### ISSUE TITLE
Matrix initialization

### ISSUE THREAD

**Issue by munrocket** [gpuweb/gpuweb#1964]
Thank you for working on new standard. As I know we need to initialise matrices inside shader with columns
```rs
let m = mat3x3<f32>(vec3<f32>(1.,0.,0.), vec3<f32>(0.,1.,0.), vec3<f32>(0.,0.,1.)); 
```
All was pretty good before I tried to port this piece of code in GLSL that calculating predefined nn
```glsl
float bunny(vec3 p) {
  if (dot(p, p) > 1.) { return length(p)-.8; }
  vec4 f00=sin(p.z*vec4(-3.02,1.95,-3.42,-.60)+p.y*vec4(3.08,.85,-2.25,-.24)
                         -p.x*vec4(-.29,1.16,-3.74,2.89)+vec4(-.71,4.50,-3.24,-3.50));
  vec4 f01=sin(p.z*vec4(-.40,-3.61,3.23,-.14)+p.y*vec4(-.36,3.64,-3.91,2.66)
                         -p.x*vec4(2.90,-.54,-2.75,2.71)+vec4(7.02,-5.41,-1.12,-7.41));
  vec4 f02=sin(p.z*vec4(-1.77,-1.28,-4.29,-3.20)+p.y*vec4(-3.49,-2.81,-.64,2.79)
                         -p.x*vec4(3.15,2.14,-3.85,1.83)+vec4(-2.07,4.49,5.33,-2.17));
  vec4 f03=sin(p.z*vec4(-.49,.68,3.05,.42)+p.y*vec4(-2.87,.78,3.78,-3.41)
                         -p.x*vec4(-2.65,.33,.07,-.64)+vec4(-3.24,-5.90,1.14,-4.71));
  vec4 f10=sin(mat4(-.34,.06,-.59,-.76,.10,-.19,-.12,.44,.64,-.02,-.26,.15,-.16,.21,.91,.15)*f00+
      mat4(.01,.54,-.77,.11,.06,-.14,.43,.51,-.18,.08,.39,.20,.33,-.49,-.10,.19)*f01+
      mat4(.27,.22,.43,.53,.18,-.17,.23,-.64,-.14,.02,-.10,.16,-.13,-.06,-.04,-.36)*f02+
      mat4(-.13,.29,-.29,.08,1.13,.02,-.83,.32,-.32,.04,-.31,-.16,.14,-.03,-.20,.39)*f03+
      vec4(.73,-4.28,-1.56,-1.80))/1.0+f00;
  vec4 f11=sin(mat4(-1.11,.55,-.12,-1.00,.16,.15,-.30,.31,-.01,.01,.31,-.42,-.29,.38,-.04,.71)*f00+
      mat4(.96,-.02,.86,.52,-.14,.60,.44,.43,.02,-.15,-.49,-.05,-.06,-.25,-.03,-.22)*f01+
      mat4(.52,.44,-.05,-.11,-.56,-.10,-.61,-.40,-.04,.55,.32,-.07,-.02,.28,.26,-.49)*f02+
      mat4(.02,-.32,.06,-.17,-.59,.00,-.24,.60,-.06,.13,-.21,-.27,-.12,-.14,.58,-.55)*f03+
      vec4(-2.24,-3.48,-.80,1.41))/1.0+f01;
  vec4 f12=sin(mat4(.44,-.06,-.79,-.46,.05,-.60,.30,.36,.35,.12,.02,.12,.40,-.26,.63,-.21)*f00+
      mat4(-.48,.43,-.73,-.40,.11,-.01,.71,.05,-.25,.25,-.28,-.20,.32,-.02,-.84,.16)*f01+
      mat4(.39,-.07,.90,.36,-.38,-.27,-1.86,-.39,.48,-.20,-.05,.10,-.00,-.21,.29,.63)*f02+
      mat4(.46,-.32,.06,.09,.72,-.47,.81,.78,.90,.02,-.21,.08,-.16,.22,.32,-.13)*f03+
      vec4(3.38,1.20,.84,1.41))/1.0+f02;
  vec4 f13=sin(mat4(-.41,-.24,-.71,-.25,-.24,-.75,-.09,.02,-.27,-.42,.02,.03,-.01,.51,-.12,-1.24)*f00+
      mat4(.64,.31,-1.36,.61,-.34,.11,.14,.79,.22,-.16,-.29,-.70,.02,-.37,.49,.39)*f01+
      mat4(.79,.47,.54,-.47,-1.13,-.35,-1.03,-.22,-.67,-.26,.10,.21,-.07,-.73,-.11,.72)*f02+
      mat4(.43,-.23,.13,.09,1.38,-.63,1.57,-.20,.39,-.14,.42,.13,-.57,-.08,-.21,.21)*f03+
      vec4(-.34,-3.28,.43,-.52))/1.0+f03;
  f00=sin(mat4(-.72,.23,-.89,.52,.38,.19,-.16,-.88,.26,-.37,.09,.63,.29,-.72,.30,-.95)*f10+
      mat4(-.22,-.51,-.42,-.73,-.32,.00,-1.03,1.17,-.20,-.03,-.13,-.16,-.41,.09,.36,-.84)*f11+
      mat4(-.21,.01,.33,.47,.05,.20,-.44,-1.04,.13,.12,-.13,.31,.01,-.34,.41,-.34)*f12+
      mat4(-.13,-.06,-.39,-.22,.48,.25,.24,-.97,-.34,.14,.42,-.00,-.44,.05,.09,-.95)*f13+
      vec4(.48,.87,-.87,-2.06))/1.4+f10;
  f01=sin(mat4(-.27,.29,-.21,.15,.34,-.23,.85,-.09,-1.15,-.24,-.05,-.25,-.12,-.73,-.17,-.37)*f10+
      mat4(-1.11,.35,-.93,-.06,-.79,-.03,-.46,-.37,.60,-.37,-.14,.45,-.03,-.21,.02,.59)*f11+
      mat4(-.92,-.17,-.58,-.18,.58,.60,.83,-1.04,-.80,-.16,.23,-.11,.08,.16,.76,.61)*f12+
      mat4(.29,.45,.30,.39,-.91,.66,-.35,-.35,.21,.16,-.54,-.63,1.10,-.38,.20,.15)*f13+
      vec4(-1.72,-.14,1.92,2.08))/1.4+f11;
  f02=sin(mat4(1.00,.66,1.30,-.51,.88,.25,-.67,.03,-.68,-.08,-.12,-.14,.46,1.15,.38,-.10)*f10+
      mat4(.51,-.57,.41,-.09,.68,-.50,-.04,-1.01,.20,.44,-.60,.46,-.09,-.37,-1.30,.04)*f11+
      mat4(.14,.29,-.45,-.06,-.65,.33,-.37,-.95,.71,-.07,1.00,-.60,-1.68,-.20,-.00,-.70)*f12+
      mat4(-.31,.69,.56,.13,.95,.36,.56,.59,-.63,.52,-.30,.17,1.23,.72,.95,.75)*f13+
      vec4(-.90,-3.26,-.44,-3.11))/1.4+f12;
  f03=sin(mat4(.51,-.98,-.28,.16,-.22,-.17,-1.03,.22,.70,-.15,.12,.43,.78,.67,-.85,-.25)*f10+
      mat4(.81,.60,-.89,.61,-1.03,-.33,.60,-.11,-.06,.01,-.02,-.44,.73,.69,1.02,.62)*f11+
      mat4(-.10,.52,.80,-.65,.40,-.75,.47,1.56,.03,.05,.08,.31,-.03,.22,-1.63,.07)*f12+
      mat4(-.18,-.07,-1.22,.48,-.01,.56,.07,.15,.24,.25,-.09,-.54,.23,-.08,.20,.36)*f13+
      vec4(-1.11,-4.28,1.02,-.23))/1.4+f13;
  return dot(f00,vec4(.09,.12,-.07,-.03))+dot(f01,vec4(-.04,.07,-.08,.05))+
      dot(f02,vec4(-.01,.06,-.02,.07))+dot(f03,vec4(-.05,.07,.03,.04))-0.16;
}
```
here what I get 
```rs
fn bunny(p: vec3<f32>) -> f32 {
  if (dot(p, p) > 1.) { return length(p) - 0.8; }
  var f00:vec4<f32>=sin(p.x*vec4<f32>(-3.02,1.95,-3.42,-.60)+p.y*vec4<f32>(3.08,.85,-2.25,-.24)
                        +p.z*vec4<f32>(-.29,1.16,-3.74,2.89)+vec4<f32>(-.71,4.5,-3.24,-3.5));
  var f01:vec4<f32>=sin(p.x*vec4<f32>(-.4,-3.61,3.23,-.14)+p.y*vec4<f32>(-.36,3.64,-3.91,2.66)
                        +p.z*vec4<f32>(2.9,-.54,-2.75,2.71)+vec4<f32>(7.02,-5.41,-1.12,-7.41));
  var f02:vec4<f32>=sin(p.x*vec4<f32>(-1.77,-1.28,-4.29,-3.2)+p.y*vec4<f32>(-3.49,-2.81,-.64,2.79)
                        +p.z*vec4<f32>(3.15,2.14,-3.85,1.83)+vec4<f32>(-2.07,4.49,5.33,-2.17));
  var f03:vec4<f32>=sin(p.x*vec4<f32>(-.49,.68,3.05,.42)+p.y*vec4<f32>(-2.87,.78,3.78,-3.41)
                        +p.z*vec4<f32>(-2.65,.33,.07,-.64)+vec4<f32>(-3.24,-5.9,1.14,-4.71));
  let f10=sin(mat4x4<f32>(vec4<f32>(-.34,.06,-.59,-.76),vec4<f32>(.1,-.19,-.12,.44),
                          vec4<f32>(.64,-.02,-.26,.15),vec4<f32>(-.16,.21,.91,.15))*f00+
              mat4x4<f32>(vec4<f32>(.01,.54,-.77,.11),vec4<f32>(.06,-.14,.43,.51),
                          vec4<f32>(-.18,.08,.39,.2),vec4<f32>(.33,-.49,-.1,.19))*f01+
              mat4x4<f32>(vec4<f32>(.27,.22,.43,.53),vec4<f32>(.18,-.17,.23,-.64),
                          vec4<f32>(-.14,.02,-.1,.16),vec4<f32>(-.13,-.06,-.04,-.36))*f02+
              mat4x4<f32>(vec4<f32>(-.13,.29,-.29,.08),vec4<f32>(1.13,.02,-.83,.32),
                          vec4<f32>(-.32,.04,-.31,-.16),vec4<f32>(.14,-.03,-.2,.39))*f03+
              vec4<f32>(.73,-4.28,-1.56,-1.8))+vec4<f32>(f00);
  let f11=sin(mat4x4<f32>(vec4<f32>(-1.11,.55,-.12,-1.0),vec4<f32>(.16,.15,-.3,.31),
                          vec4<f32>(-.01,.01,.31,-.42),vec4<f32>(-.29,.38,-.04,.71))*f00+
              mat4x4<f32>(vec4<f32>(.96,-.02,.86,.52),vec4<f32>(-.14,.6,.44,.43),
                          vec4<f32>(.02,-.15,-.49,-.05),vec4<f32>(-.06,-.25,-.03,-.22))*f01+
              mat4x4<f32>(vec4<f32>(.52,.44,-.05,-.11),vec4<f32>(-.56,-.1,-.61,-.4),
                          vec4<f32>(-.04,.55,.32,-.07),vec4<f32>(-.02,.28,.26,-.49))*f02+
              mat4x4<f32>(vec4<f32>(.02,-.32,.06,-.17),vec4<f32>(-.59,.0,-.24,.6),
                          vec4<f32>(-.06,.13,-.21,-.27),vec4<f32>(-.12,-.14,.58,-.55))*f03+
              vec4<f32>(-2.24,-3.48,-.8,1.41))+vec4<f32>(f01);
  let f12=sin(mat4x4<f32>(vec4<f32>(.44,-.06,-.79,-.46),vec4<f32>(.05,-.6,.3,.36),
                          vec4<f32>(.35,.12,.02,.12),vec4<f32>(.4,-.26,.63,-.21))*f00+
              mat4x4<f32>(vec4<f32>(-.48,.43,-.73,-.4),vec4<f32>(.11,-.01,.71,.05),
                          vec4<f32>(-.25,.25,-.28,-.2),vec4<f32>(.32,-.02,-.84,.16))*f01+
              mat4x4<f32>(vec4<f32>(.39,-.07,.9,.36),vec4<f32>(-.38,-.27,-1.86,-.39),
                          vec4<f32>(.48,-.2,-.05,.1),vec4<f32>(-.0,-.21,.29,.63))*f02+
              mat4x4<f32>(vec4<f32>(.46,-.32,.06,.09),vec4<f32>(.72,-.47,.81,.78),
                          vec4<f32>(.9,.02,-.21,.08),vec4<f32>(-.16,.22,.32,-.13))*f03+
              vec4<f32>(3.38,1.2,.84,1.41))+vec4<f32>(f02);
  let f13=sin(mat4x4<f32>(vec4<f32>(-.41,-.24,-.71,-.25),vec4<f32>(-.24,-.75,-.09,.02),
                          vec4<f32>(-.27,-.42,.02,.03),vec4<f32>(-.01,.51,-.12,-1.24))*f00+
              mat4x4<f32>(vec4<f32>(.64,.31,-1.36,.61),vec4<f32>(-.34,.11,.14,.79),
                          vec4<f32>(.22,-.16,-.29,-.7),vec4<f32>(.02,-.37,.49,.39))*f01+
              mat4x4<f32>(vec4<f32>(.79,.47,.54,-.47),vec4<f32>(-1.13,-.35,-1.03,-.22),
                          vec4<f32>(-.67,-.26,.1,.21),vec4<f32>(-.07,-.73,-.11,.72))*f02+
              mat4x4<f32>(vec4<f32>(.43,-.23,.13,.09),vec4<f32>(1.38,-.63,1.57,-.2),
                          vec4<f32>(.39,-.14,.42,.13),vec4<f32>(-.57,-.08,-.21,.21))*f03+
              vec4<f32>(-.34,-3.28,.43,-.52))+vec4<f32>(f03);
  f00=sin(mat4x4<f32>(vec4<f32>(-.72,.23,-.89,.52),vec4<f32>(.38,.19,-.16,-.88),
                          vec4<f32>(.26,-.37,.09,.63),vec4<f32>(.29,-.72,.3,-.95))*f10+
              mat4x4<f32>(vec4<f32>(-.22,-.51,-.42,-.73),vec4<f32>(-.32,.0,-1.03,1.17),
                          vec4<f32>(-.2,-.03,-.13,-.16),vec4<f32>(-.41,.09,.36,-.84))*f11+
              mat4x4<f32>(vec4<f32>(-.21,.01,.33,.47),vec4<f32>(.05,.2,-.44,-1.04),
                          vec4<f32>(.13,.12,-.13,.31),vec4<f32>(.01,-.34,.41,-.34))*f12+
              mat4x4<f32>(vec4<f32>(-.13,-.06,-.39,-.22),vec4<f32>(.48,.25,.24,-.97),
                          vec4<f32>(-.34,.14,.42,-.0),vec4<f32>(-.44,.05,.09,-.95))*f13+
              vec4<f32>(.48,.87,-.87,-2.06))/1.4+vec4<f32>(f10);
  f01=sin(mat4x4<f32>(vec4<f32>(-.27,.29,-.21,.15),vec4<f32>(.34,-.23,.85,-.09),
                          vec4<f32>(-1.15,-.24,-.05,-.25),vec4<f32>(-.12,-.73,-.17,-.37))*f10+
              mat4x4<f32>(vec4<f32>(-1.11,.35,-.93,-.06),vec4<f32>(-.79,-.03,-.46,-.37),
                          vec4<f32>(.6,-.37,-.14,.45),vec4<f32>(-.03,-.21,.02,.59))*f11+
              mat4x4<f32>(vec4<f32>(-.92,-.17,-.58,-.18),vec4<f32>(.58,.6,.83,-1.04),
                          vec4<f32>(-.8,-.16,.23,-.11),vec4<f32>(.08,.16,.76,.61))*f12+
              mat4x4<f32>(vec4<f32>(.29,.45,.3,.39),vec4<f32>(-.91,.66,-.35,-.35),
                          vec4<f32>(.21,.16,-.54,-.63),vec4<f32>(1.1,-.38,.2,.15))*f13+
              vec4<f32>(-1.72,-.14,1.92,2.08))/1.4+vec4<f32>(f11);
  f02=sin(mat4x4<f32>(vec4<f32>(1.0,.66,1.3,-.51),vec4<f32>(.88,.25,-.67,.03),
                          vec4<f32>(-.68,-.08,-.12,-.14),vec4<f32>(.46,1.15,.38,-.1))*f10+
              mat4x4<f32>(vec4<f32>(.51,-.57,.41,-.09),vec4<f32>(.68,-.5,-.04,-1.01),
                          vec4<f32>(.2,.44,-.6,.46),vec4<f32>(-.09,-.37,-1.3,.04))*f11+
              mat4x4<f32>(vec4<f32>(.14,.29,-.45,-.06),vec4<f32>(-.65,.33,-.37,-.95),
                          vec4<f32>(.71,-.07,1.0,-.6),vec4<f32>(-1.68,-.2,-.0,-.7))*f12+
              mat4x4<f32>(vec4<f32>(-.31,.69,.56,.13),vec4<f32>(.95,.36,.56,.59),
                          vec4<f32>(-.63,.52,-.3,.17),vec4<f32>(1.23,.72,.95,.75))*f13+
              vec4<f32>(-.9,-3.26,-.44,-3.11))/1.4+vec4<f32>(f12);
  f03=sin(mat4x4<f32>(vec4<f32>(.51,-.98,-.28,.16),vec4<f32>(-.22,-.17,-1.03,.22),
                          vec4<f32>(.7,-.15,.12,.43),vec4<f32>(.78,.67,-.85,-.25))*f10+
              mat4x4<f32>(vec4<f32>(.81,.6,-.89,.61),vec4<f32>(-1.03,-.33,.6,-.11),
                          vec4<f32>(-.06,.01,-.02,-.44),vec4<f32>(.73,.69,1.02,.62))*f11+
              mat4x4<f32>(vec4<f32>(-.1,.52,.8,-.65),vec4<f32>(.4,-.75,.47,1.56),
                          vec4<f32>(.03,.05,.08,.31),vec4<f32>(-.03,.22,-1.63,.07))*f12+
              mat4x4<f32>(vec4<f32>(-.18,-.07,-1.22,.48),vec4<f32>(-.01,.56,.07,.15),
                          vec4<f32>(.24,.25,-.09,-.54),vec4<f32>(.23,-.08,.2,.36))*f13+
              vec4<f32>(-1.11,-4.28,1.02,-.23))/1.4+vec4<f32>(f13);
  return dot(f00,vec4<f32>(.09,.12,-.07,-.03))+dot(f01,vec4<f32>(-.04,.07,-.08,.05))+
         dot(f02,vec4<f32>(-.01,.06,-.02,.07))+dot(f03,vec4<f32>(-.05,.07,.03,.04))- 0.16;
}
```
Same code become bigger in two times. It feels like here WGSL is still too verbose and can be simpler since we know matrix size explicitly. It will be cool if we will be able to initialise it only with components like that.
```rs
let m = mat3x3<f32>(1.,0.,0.,0.,1.,0.,0.,0.,1.); 
```
Am I right that we can't do it in current specification?

**Comment by Kangz** [comment]
That's correct, but to make it look nicer you can make a helper function called `mat4` ^^

**Comment by munrocket** [comment]
Ah ok :D
Ufff

**Comment by Kangz** [comment]
Though point taken that it is very verbose, maybe someone working more closely on the WGSL spec can comment if we have future plans.

**Comment by alan-baker** [comment]
We could consider adding type constructors for matrix that are specified using the vector element type. I'll move this to needs discussion.

**Comment by munrocket** [comment]
With init function that code become almost the same
```rs
fn fmat4init(a1: f32, a2: f32, a3: f32, a4: f32, b1: f32, b2: f32, b3: f32, b4: f32,
             c1: f32, c2: f32, c3: f32, c4: f32, d1: f32, d2: f32, d3: f32, d4: f32) -> mat4x4<f32> {
  return mat4x4<f32>(vec4<f32>(a1, a2, a3, a4), vec4<f32>(b1, b2, b3, b4),
                     vec4<f32>(c1, c2, c3, c4), vec4<f32>(d1, d2, d3, d4));
}
```

**Comment by litherum** [comment]
We should add such a function/constructor to the standard library. You're almost certainly not the only one who would benefit from it.

**Comment by kainino0x** [comment]
It is a very handy function to have, though these constructors always have the issue that if you write:

```glsl
mat2(a11, a12,
     a21, a22)
```

i.e., in memory-linear order, then it will visually be transposed from how it's written on paper (though of course it's the same with the mat(vec, vec) constructor too).

More than once I've written helpers so I could write the matrix in visually-correct order. Could be something to consider, at least in the naming of of a helper for this, so it's clear which majorness is used.

**Comment by jdashg** [comment]
One thing we talked about in office hours was `mat2x2_by_cols(A, B, C, D)` == `mat2x2(vec2(A,B), vec2(C,D))` == `mat2x2_by_rows(A, C, B, D)`.

Another option is just to have `mat2x2(A, B, C, D)` == `mat2x2(vec2(A,B), vec2(C,D))`, and if you want by-rows you do `transpose(mat2x2(A, C, B, D))`.

I don't think it's worth adding a standard helper when authors can write their own with their own ergonomic choices, but I would not stand in the way of one being added.

**Comment by kainino0x** [comment]
It could be worth calling it something like mat2x2_by_cols even if we don't also add mat2x2_by_rows.

**Comment by munrocket** [comment]
GLSL: has constructor overload
MSL: has constructor overload
HLSL: has constructor overload
SpirV: has constructor overload

GLSL: [column-major](https://www.opengl.org/archives/resources/faq/technical/transformations.htm)
MSL: [column-major](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf)
HLSL: [column-major](https://docs.microsoft.com/en-gb/windows/win32/direct3dhlsl/dx-graphics-hlsl-per-component-math?redirectedfrom=MSDN), but can be changed
SpirV: [no preference](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html), but usually like in GLSL

If someone want to use row-major he can switch an order of multiplication instead of transpose operation because
```js
u = v * (A)ᵀ * (B)ᵀ = (B * (v * (A)ᵀ)ᵀ)ᵀ = (B * A * vᵀ)ᵀ = (uᵀ)ᵀ
u ≈ uᵀ = B * A * vᵀ
```
but I am not sure about multiplication performance between matrix and vector when column-major matrix at left.

Anyway constructor overloading operation is mapped perfectly to existed languages at least for mat2x2, mat3x3, mat4x4.

**Comment by kainino0x** [comment]
Thank you for checking the other languages!

Switching the order of the multiplication doesn't fix the problem with the visual order in the code being transposed relative to how you would write it on paper - it doesn't cancel out.

I would expect the performance to be the same, but I don't know.

**Comment by litherum** [comment]
> visual order in the code being transposed

If it's good enough for every other shading language, it's aught to be good enough for us.

**Comment by pow2clk** [comment]
Unfortunately, in shader initialization of HLSL matrices is not in column major order. HLSL matrices are always row-major though there is a qualifier that changes the memory layout for purposes of interface with the API.

`transpose()` can be used to initialize matrices in column major order: 

```float4x4 mat = transpose(float4x4(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16)); ```

 However, whenever you apply a single index to a matrix, you will get the row, not the column unless you apply a transform to it:

``` transpose(mat)[0] == float4(1,2,3,4)```

This is true even if you apply the `column_major` qualifier to float4x4.

**Comment by kvark** [comment]
Right, so that matches the concern I expressed on the call. This is kind of a problem. All this code would need to be somewhat non-trivially perturbed, and there is no error on forgetting to change the order of the arguments. just broken rendering. If we don't allow this kind of initialization, then at least the user sees an error and has to figure out what columns to pass.

Another issue here is how are we going to take a pointer to a matrix column in HLSL? Maybe we should just forbid this in WGSL?

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-07-27-Minutes#matrix-initialization-1964">WGSL meeting minutes 2021-07-27</a></summary>



* JG: A user of the API said this code is ugly. They don’t want to construct a matrix out of the columns. And they have to initialize them with vec4s. So making mat4(vec4(), vec4(), vec4(), vec4()) is ugly
* JG: But this code is machine generated.
* JG: The reporter did research. Everyone has constructor overloads for these. You can do it by columns or by element. Seems like we should just allow overloads by elements.
* AB: Should this be a library function or a type constructor?
* JG: Type constructor
* JG: Resolved.
* DM: HLSL has row-major order, not column major order. This is unfortunate.
* DM: If people use their code straight from HLSL, they will be surprised
* AB: Does that mean we don’t want to help non-HLSL people?
* JG: HLSL is the most common language.
* JG: One idea that would fix this is to have an explicit builtin. mat4x4_colmajor(). It’s clear what’s going on. No one is ever confused.
* JG: But people already have to remember that mat4(vec4, vec4, vec4, vec4) is column major
* GR: HLSL accepts a qualifier to change the majorness of a matrix
* DM: Is the qualifier on the type or on the field?
* GR: It’s on the type.
* DM: Is it attached to the type? I can have 2 different float4x4s, one is column-major, and one is row-major
* MM: Isn’t it the same in GLSL too?
* JG: No. Those are binding-point differences, not shading language differences in GLSL
* GR: You can initialize with vectors
* DM: How does one initialize a column-major matrix in HLSL?
* ACTION: GR write something that does this ^^^ 
* RESOLVED: This is not resolved.
* GR (Addendum): I was mistaken about the effect of column_major. However, transpose() can be used to initialize matrices in column major order: float4x4 mat = transpose(float4x4(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16));  However, whenever you apply a single index to a matrix, you will get the row, not the column unless you apply a transform to it: transpose(mat)[0] == float4(1,2,3,4)


</details>

**Comment by dneto0** [comment]
> Another issue here is how are we going to take a pointer to a matrix column in HLSL? Maybe we should just forbid this in WGSL?

That's different, I think. What we're talking about here are syntaxes for creating a matrix *value*.  No matter what the value is, conceptually the resulting value is "column major", so that m[1] is *column* 1.    But whether it "actually is" column major or row major is undetectable.    Pointers are about memory, and are a kind of memory view; and yes  &m[1] would always be a pointer to *column* 1 in memory, and that would be a contiguous sequence of scalars.

**Comment by munrocket** [comment]
Documentation says that HLSL itself is [column-major](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-appendix-pre-pragma-pack-matrix) (by default) but CPU library DirectXMath is [row-major](https://docs.microsoft.com/en-gb/windows/win32/dxmath/pg-xnamath-getting-started?redirectedfrom=MSDN#matrix_convention) and converts it to column-major behind the scenes before sending to GPU (according to this [discussion](https://stackoverflow.com/a/20438735)).

>  What we're talking about here are syntaxes for creating a matrix value. No matter what the value is, conceptually the resulting value is "column major", so that m[1] is column 1. But whether it "actually is" column major or row major is undetectable.

Agree, we just want to simplify some of the user code.

**Comment by kainino0x** [comment]
> Documentation says that HLSL itself is [column-major](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-appendix-pre-pragma-pack-matrix) (by default)

This documentation is just about the memory layout (which is configurable), not the order of arguments to the constructor (which appears to be unconfigurable). This page shows the order of arguments being row-major as pow2clk said:
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-matrix

**Comment by munrocket** [comment]
Interesting, sorry not familiar with HLSL.

**Comment by kvark** [comment]
@dneto0 I know it's different. But it does show up here, and it's related.
> and yes &m[1] would always be a pointer to column 1 in memory

How would you do this on HLSL, where matrix indexing gives you rows instead of columns?

**Comment by munrocket** [comment]
> Another issue here is how are we going to take a pointer to a matrix column in HLSL? Maybe we should just forbid this in WGSL?

If a target language is row-major (like HLSL), WGSL -> HLSL translation can do this trick below, after that pointers and math operations will gives _exactly_ the same result.
| WGSL | HLSL |
|-------|------|
| &M[I] | &Mᵀ[i] |
| M⨷v | v⨷Mᵀ |
| M₁⨷M₂ | M₂ᵀ⨷M₁ᵀ |
| M₁+M₂ | M₁ᵀ+M₂ᵀ |
| v₁+v₂ | v₁+v₂ |

Here ⨷ is multiplication where vector at left always a row-vector and vector at right always a column-vector.

**Comment by dneto0** [comment]
> Another issue here is how are we going to take a pointer to a matrix column in HLSL? Maybe we should just forbid this in WGSL?

Right, we have to tread carefully here.

But a matrix in storage in WGSL doesn't have to map directly to a matrix in HLSL. What matters is that WGSL's layout rules are followed.

Example WGSL:
```
[[block]] struct B {
  m0: mat4x4<f32>;
  m1: mat4x4<f32>;
};

[[group(0), binding(0)]]
var<storage,read_write> b: B;


[[stage(fragment)]]
fn main(
) -> [[location(0)]] vec4<f32> {
   let p = &b.m0[3];
   *p = vec4<f32>(10.0,11.0,12.0,13.0);
   return b.m1[0];
}
```

Tint translates that to:
```
RWByteAddressBuffer b : register(u0, space0);

struct tint_symbol {
  float4 value : SV_Target0;
};

float4 main_inner() {
  b.Store4(48u, asuint(float4(10.0f, 11.0f, 12.0f, 13.0f)));  // This is the store through *p.
  return asfloat(b.Load4((64u + (16u * uint(0)))));
}

tint_symbol main() {
  const float4 inner_result = main_inner();
  tint_symbol wrapper_result = (tint_symbol)0;
  wrapper_result.value = inner_result;
  return wrapper_result;
}
```
Note that the store through *p ends up implementing the column-major write.

**Comment by dneto0** [comment]
For arithmetic (like vector-matrix multiply), Tint implements the implicit transpositions and order swapping.

```
[[block]] struct B {
  v0: vec4<f32>;
  m1: mat4x4<f32>;
  m2: mat4x4<f32>;
};

[[group(0), binding(0)]]
var<storage,read_write> b: B;


[[stage(fragment)]]
fn main() -> [[location(0)]] vec4<f32> {
   let m = b.m1 * b.m2;
   return b.v0 * m;
}
```
Translates as:

```
RWByteAddressBuffer b : register(u0, space0);

struct tint_symbol {
  float4 value : SV_Target0;
};

float4x4 tint_symbol_1(RWByteAddressBuffer buffer, uint offset) {
  return float4x4(asfloat(buffer.Load4((offset + 0u))), asfloat(buffer.Load4((offset + 16u))), asfloat(buffer.Load4((offset + 32u))), asfloat(buffer.Load4((offset + 48u))));
}

float4 main_inner() {
  const float4x4 m = mul(tint_symbol_1(b, 80u), tint_symbol_1(b, 16u));  //Note order swap vs. WGSL.
  return mul(m, asfloat(b.Load4(0u))); // Note the order swap vs. WGSL
}

tint_symbol main() {
  const float4 inner_result = main_inner();
  tint_symbol wrapper_result = (tint_symbol)0;
  wrapper_result.value = inner_result;
  return wrapper_result;
}

```

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-08-03-Minutes#matrix-initialization-1964">WGSL meeting minutes 2021-08-03</a></summary>



* rowMajorMatMxN?
* JG: Maybe it’s useful to have the mat4 that’s implicitly col-major, and then an explicit builtin mat4x4_row_major()?
* DM: Do we actually want that? If we had row-major functions, people would ask for column-major functions. So, 2 constructors for each matrix.
* DM: We can construct a matrix from elements or vectors. Each matrix would need 2 additional functions, one for vectors and one for elements. That’s a lot of functions. Maybe we don’t need them.
* AB: We don’t need one for elements at all? Or just row major?
* DM: We could get away without row major, for MVP
* AB: I thought you wanted row major
* JG: We’re debugging people coming from HLSL and getting it wrong.
* DM: Wasn’t the argument that they have to make a bunch of fixes anyway? If they have matrix[1], they will have to fix that as well.
* AB: we’re not supporting row major matrix, in terms of access operations
* JG: Let’s add the scalar constructor. it will be column major
* RESOLVED: Add column-major element constructor for matrices


</details>

**Comment by munrocket** [comment]
> Another issue here is how are we going to take a pointer to a matrix column in HLSL? Maybe we should just forbid this in WGSL?

This trick with matrix transposition can lead to additional work with buffer bindings in HLSL. Because right now mat2x3 and mat3x2 have different size: 16 vs 8 bytes.

**Comment by ben-clayton** [comment]
> This trick with matrix transposition can lead to additional work with buffer bindings in HLSL. Because right now mat2x3 and mat3x2 have different size: 16 vs 8 bytes.

I'm not sure I follow. I'm moderately confident the transpose approach works as expected. [We have tests in place](https://dawn.googlesource.com/dawn/+/refs/heads/main/src/tests/end2end/ComputeLayoutMemoryBufferTests.cpp) that ensure that memory layout for SSBO and UBOs are correct for all backends.
