### ISSUE TITLE
[editorial] Make object creation to respect the device timeline

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#1970]
Currently, our object creation is *mostly* specified to happen on the device timeline, from where the result is returned.
We need to refactor the spec in a way that creates objects on the content timeline and returns them, while populating the data on device timeline.

**Comment by kvark** [comment]
Just discovered that the pipeline creation is written in the right way. That's a good start :)

**Comment by kainino0x** [comment]
I think this is done by #3322
