### ISSUE TITLE
Add to text: Global vars/consts declaration initializers must be const_expr

### ISSUE THREAD

**Issue by sarahM0** [gpuweb/gpuweb#1975]
Global variables/constants declaration initializers must be const_expression. ie. the following is invalid:
> let s: i32 = 0;
> let a: i32 = s;

This can be deducted from grammar rules. We would suggest the section on module-scope vars/const to describe this with actual words.

**Comment by munrocket** [comment]
This is a thing.

**Comment by alan-baker** [comment]
* const-decls require a const-expression (from https://gpuweb.github.io/gpuweb/wgsl/#const-decls)
* override-decls require an override-expression (from https://gpuweb.github.io/gpuweb/wgsl/#override-decls)
* function-scope var-decls allow any expression (from https://gpuweb.github.io/gpuweb/wgsl/#let-decls)
* module-scope var-decls in private allow override-expression (from https://gpuweb.github.io/gpuweb/wgsl/#var-decls)
* module-scope var-decls in other address spaces are uninitailized (from https://gpuweb.github.io/gpuweb/wgsl/#var-decls)
