### ISSUE TITLE
Do we have a plan for non-32bit literals?

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#1986]
Currently in WGSL every literal maps directly to a single WGSL type:
* `123` → `i32`
* `123u` → `u32`
* `1.23` → `f32`
* `true` → `bool`

I'm curious to know if we have a strategy for non-32bit literals?

Golang's solution is to have literals start of untyped, with arbitrary precision. To quote from [the Golang spec](https://golang.org/ref/spec#Constants):

> A constant may be given a type explicitly by a constant declaration or conversion, or implicitly when used in a variable declaration or an assignment or as an operand in an expression. It is an error if the constant value cannot be represented as a value of the respective type.
> 
> An untyped constant has a default type which is the type to which the constant is implicitly converted in contexts where a typed value is required, for instance, in a short variable declaration such as i := 0 where there is no explicit type. The default type of an untyped constant is bool, rune, int, float64, complex128 or string respectively, depending on whether it is a boolean, rune, integer, floating-point, complex, or string constant.
> 
> Implementation restriction: Although numeric constants have arbitrary precision in the language, a compiler may implement them using an internal representation with limited precision. That said, every implementation must:
> 
> * Represent integer constants with at least 256 bits.
> * Represent floating-point constants, including the parts of a complex constant, with a mantissa of at least 256 bits and a signed binary exponent of at least 16 bits.
> * Give an error if unable to represent an integer constant precisely.
> * Give an error if unable to represent a floating-point or complex constant due to overflow.
> * Round to the nearest representable constant if unable to represent a floating-point or complex constant due to limits on precision.
> These requirements apply both to literal constants and to the result of evaluating constant expressions.

I like this approach as it allows literals to remain backwards compatible with what we have now, while also supporting future `f16`, `f64`, `i8`, types, all without introducing a whole lot of messy suffixes. The lack of `f` suffix on float literals will already make the suffix approach confusing if/when we support `f64`.

Thoughts?

Related to https://github.com/gpuweb/gpuweb/issues/1272.

**Comment by kvark** [comment]
Much related to #723. Our discussion so far was that all of the expressions must have known types, except for literals in the future (after MVP), which would be inferred to their immediate context.
With this mechanics, the parser always knows exactly, which type to expect, so it doesn't have to support 256-bit integers, for example.

Interestingly, if we have that limited inference for literals, we don't need any literal type suffixes. So it sounds like a win.

However, it also comes with complexity and a range of issues. I.e. how do you infer a type of a literal that's passed to a built-in that is overloaded between  `i32` and `u32`?..

With this in mind, I think we should just continue shipping 32-bit only with the short suffixes, and then explore the space for literal type inference right after MVP (and preferably before f16/f64/u8/etc).

**Comment by kainino0x** [comment]
I think the possibility of unsized literal types, like in Go, was exactly one of the reasons we wanted to start out with the very strict system we have now: it allows us to add that later, even after we add more types like i16 or i64, because it's non-breaking.

I think if you did something like `let x = 999999999999999999999999999999;`, the literal itself would have this unsized type, but `x` would unconditionally have the type `i32` (without inference from any users of `x`). (Hence in this case there probably would be an error from trying to narrow that literal into i32.)

**Comment by dneto0** [comment]
Addressed by #2227 and #2668
