### ISSUE TITLE
wsgl:editorial: missing access mode in a few descriptions

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#1992]
- at definition of variable
- in "Component reference from a vector reference" table
- in "Getting a reference to a colun vector from a reference to a matrix"
- in "Getting a reference to an array element from a reference to an array"
- in "Getting a reference to a structure member from a reference to a structure"
- in "getting a reference from a variable name"

**Comment by alan-baker** [comment]
This has been addressed.
