### ISSUE TITLE
Shimming for upgrades, a la database versions

### ISSUE THREAD

**Issue by web3d0** [gpuweb/gpuweb#20]
In the same way that databases are updated from one version to the next with scripts that migrate how the data is stored, and in the same way that future versions of web features are shimmed with polyfills, should WebGPU have shims for updating?

This is not a proposal that old code needs to be supported forever with no effort, but a halfway point where old code needs to at least update to include a shim for their old code. New code will need to include a shim, and old code will need to include it.

This is a bit of a shot in the dark, so this issue is raised for discussion rather than resolution. Is there a median point where new code can be proposed and implemented with a shim in the same way as today's polyfills, while old code needs to remain minimally aware of what is going on and do the minimum needed without a rewrite?

**Comment by grovesNL** [comment]
I don't think this should be a part of a specification or deliverable from this group. If there were breaking API changes, an external library could attempt to mitigate the changes between versions of the specification. However I wouldn't expect major breaking changes to be very common after WebGPU is released.

Is there a specific example you had in mind?

**Comment by web3d0** [comment]
That is correct, the shim would be an external library that mitigates the change and the original code would be required to update to include the shim instead of being abandonware.

**Comment by kainino0x** [comment]
As with all other web APIs including WebGL, backward compatibility should never be broken except in extenuating circumstances (like a security issue requiring a specification change). Those circumstances should not warrant a compatibility layer and I agree that it shouldn't be a deliverable of this group.

I don't know anything about the issue you mentioned (on email) about old WebGL content not working. AFAIK if old WebGL content breaks, it's because it relied on a pre-release version (experimental-webgl), old spec bugs like undefined behavior that's since been defined, old driver bugs, or something similar. These kinds of breakage are extremely hard to shim as each app may expect a different behavior from the API.

**Comment by web3d0** [comment]
That is the exact issue this is raising. Everything being done now is pre-release, and there were many webgl examples that broke in later releases. The day to day experience was an increasing number of webgl examples that didn't work, which could have been offset if only those old webgl examples had minimal upgrade paths (eg, including a shim) instead of just being abandoned. This proposal is to try and create non-deliverable and optional shims that can be included by examples that used to work, and should still work except for a simple change here and there. Absolutely not part of the standard, that's why it's an offline non-deliverable shim... but makes all the difference for user experience.

**Comment by kainino0x** [comment]
Ah, I see. Any developer using the API prior to its release is making an implicit promise that they'll update, at least once to the released version of the API. Perhaps with WebGPU we can mitigate this issue by stabilizing the API _before_ making it generally available. AFAIU, WebVR in Chrome has been using Chrome's origin trial feature to prevent a pre-release version of the API from getting widespread use from developers who won't update.

Perhaps others who have been working on the WebGL implementations for longer than I have can comment, but it seems to me that if we have to add a new a emulation method to the shim for _every_ change to the spec after the first pre-release, as well as support _every_ pre-release version, it's going to add too much overhead to the API development and the complexity of the shim is going to grow very rapidly.

**Comment by web3d0** [comment]
I do agree with your point, but every fixed public release can slough off the complexity of previous releases. When it gets to a point release, the shim goes to zero. Intermediate releases have that helper, until the next point release. The WebGL experience was that daily releases would break stuff, so this proposal is a minimal "let's just break to point releases, not every day!".

**Comment by greggman** [comment]
I'd be curious what the actual WebGL issues were. [Here's a page of WebGL demos that shipped in 2010](http://webglsamples.org/). They all still work.

**Comment by web3d0** [comment]
I'm thinking of when I used to help Giles write his learningwebgl lessons, and there was a painful changeover period while people had a mix of old and new browsers. The updates to the lessons are detailed here: http://learningwebgl.com/blog/?p=2507

**Comment by greggman** [comment]
Ok, that seems like a solved issue though. Those tutorials were created before the spec was done. WebGL didn't ship without a flag with those issues so those issued were entirely on the authors for starting before the spec was done. WebGL was entirely behind flags when any version of WebGL had those features.

**Comment by web3d0** [comment]
OK, no worries. Happy for anyone else to comment, then this issue can be closed.
