### ISSUE TITLE
Fix Y2K bugs in WebGPU

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2000]
It's a big API; surely someplace in the API handles a year number as a 2-digit string.

**Comment by Kangz** [comment]
If we expanded the digits to cover more than just 0-9, for example 0-11 instead, we could go all the way to `143` instead of `99` and beat the Y2k38 problem. I think we should suggest adding two new digits to the unicode standards body.

**Comment by dneto0** [comment]
Kids these days.

**Comment by juj** [comment]
Just ordered a stack of these stickers https://www.ebay.com/itm/114550588816 to place on all WebGPU-enabled devices. So we will not be blocked on this issue at least.
