### ISSUE TITLE
Restrictions on range of zeroing-out-buffer method?

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2009]
In #1968, we resolved to add a please-zero-out-this-range-of-this-buffer method.

We might need to restrict the offset / length to be multiples of 4, because of Vulkan or D3D. We should investigate whether or not we need it.

**Comment by kvark** [comment]
Since we implement it via copies on some of the backends, the same restrictions should apply as for `copyBufferToBuffer`.

**Comment by Kangz** [comment]
Deduplicated in #1968
