### ISSUE TITLE
WGSL spec is not clear on whether array size can be an unsigned literal

### ISSUE THREAD

**Issue by afd** [gpuweb/gpuweb#2012]
I have been cross-checking the naga and tint shader converters against one another.

Naga produces code with declarations such as:

```
    var local: array<u32,2u> = array<u32,2u>(1u, 2u);
```

Tint then complains with:

```
error: expected signed integer literal for array size
```

The section in the WGSL spec on [array types](https://www.w3.org/TR/WGSL/#array-types) says that the size N "must be 1 or larger", but does not say anything about whether an unsigned literal such as `2u` is acceptable.

The spec should be clarified so that either naga or tint can be fixed.

**Comment by kvark** [comment]
IIRC, the consensus so far is to allow both signed and unsigned literals for array sizes, just like #1135 describes the indices to be either signed or unsigned. So this looks like a Tint bug.

**Comment by jdashg** [comment]
The grammar allows unsigned as of #1942.
