### ISSUE TITLE
Fragment output <-> attachment interface matching rules def

### ISSUE THREAD

**Issue by shrekshao** [gpuweb/gpuweb#2013]
Right now the WebGPU spec and WGSL spec are vague about the fragment output and attachment interface matching rules.

https://www.w3.org/TR/webgpu/#fragment-state
> The pipeline output type must be compatible with colorState.format.

The rule should have two parts.
* For BaseType: The scalar type (`f32`, `i32`, or `u32`) must match the sample type of the format. (Pretty clear). 
* For componentCounts: here are results shown by some tests (when the component count of output and channel count of fragment color attachment don't match)

|       |  Metal  |  D3D12 |  Vulkan(Win) |
|-----|---------|---------|----------------|
|  `vec4<f32>` <-> `R8Unorm` |   ✔️   |  ✔️  |  ✔️  |
| `f32` <-> `RGBA8Unorm` | ❌Error |  ❌ Undefined value for unwritten channels (Error with backend validation) | ❌ Undefined value ~~✔️(seems happy, pad with 0)~~ |

Here are some related spec text I found (please help add refs)
* https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx9-graphics-reference-asm-ps-registers-output-color (This is hlsl for dx9 though)
* https://www.khronos.org/registry/vulkan/specs/1.1/html/chap15.html#interfaces-fragmentoutput

We have 2 options here:
* State in the spec that component count of the fragment color output should be equal or bigger than the channel count of the `colorState.format`. The extra components are discarded. Otherwise there would be a validation error.
* Do a transform of the user-input WGSL shader in our implementations to make sure the output is always expanded to `vec4<T>`, without validating the componentCount.

WDYT

**Comment by kainino0x** [comment]
FWIW, reading the Vulkan spec I just realized why it's always allowed to output too many components: fragment outputs don't go directly into the attachment, they go to the blending unit. The blending unit may use the output alpha value even if the attachment doesn't have an alpha channel.

We need to determine what the blending unit sees in the alpha channel if the shader doesn't output it. If it's an undefined value, I think we have to choose one of these options:

2. Pad all outputs to vec4 (on such backends)
3. Validate outputs are vec4
4. Validate outputs are vec4 if they use blending
5. Validate outputs are vec4 if they use blending modes that read the alpha channel

If it's defined, then option 1 (the first option Shrek posted) is additionally still valid.

---

Aside: I found this in the Vulkan spec section you linked:

> Any value that cannot be represented in the attachment’s format is undefined.

I guess this means there are technically undefined values if you write outside of the range of a unorm/snorm attachment type. That seems like a pretty minor hazard but I'm surprised by it.

**Comment by kainino0x** [comment]
Oh, finally found the relevant sentence in Vulkan:

> The input values to blending or color attachment writes are undefined for components which do not correspond to a fragment shader output.

**Comment by kvark** [comment]
Injecting shader code is always extra work, and also incompatible with the idea of generating `MTLLibrary` ahead of time. So we should play safe and say that for now the shader output has to:
  1. have at least as many components as the target format
  2. be a `vec4` if any of the blend factors for this attachment include one of the following:
    - "src-alpha"
    - "one-minus-src-alpha"
    - "src-alpha-saturated"

**Comment by kainino0x** [comment]
I don't think it's incompatible with generating ahead of time. We don't have to pad to the size of the format, we can _always_ pad to vec4 unconditionally.

**Comment by kainino0x** [comment]
Resolution: Add the precise validation rules (option 5, the one kvark described just above)

**Comment by kainino0x** [comment]
Adding to editor agenda to clarify a corner case

**Comment by kainino0x** [comment]
Editors: That should also be valid. Unless the validation layers complain about that.

Buuut then what if the write mask prevents any actual undefined values? Then we should also allow that. Unless the validation layers complain about _that_. @shrekshao do you have things set up so you could check what the Metal and d3d12 debug layers think about these things?

**Comment by shrekshao** [comment]
With fragment output set to `f32`, attachment format `RGBA8Unorm`, wrtieMask `GPUColorWrite::Red`, D3D12 still treats it as invalid.

So seems that we don't have to consider write mask state at validation

**Comment by kainino0x** [comment]
Good to know! Could you also check if D3D12 considers the blend factors in its debug layer?

**Comment by shrekshao** [comment]
For blending, at least D3D12 doesn't care if blending is null, or enabled but srcFactor/dstFactor doesn't include `src-alpha`, when writeing `vec3<f32>` to `RGBA8Unorm`. It simply said it's unmatched. This actually makes implementing the validation a bit easier.
```
ID3D12Device::CreateGraphicsPipelineState: Pixel Shader output 'SV_Target0' is writing to 3 components, while the corresponding RenderTarget slot [0] has format (R8G8B8A8_UNORM) with 4 component(s). This results in undefined contents in the unwritten channels of the render target. [ STATE_CREATION WARNING #974: CREATEGRAPHICSPIPELINESTATE_PS_OUTPUT_RT_OUTPUT_MISMATCH]
```

**Comment by kainino0x** [comment]
Hmm, that seems like there might be a deficiency in the D3D12 debug layer. Am I correct in understanding it allows the following case? Which should be invalid.
- output `vec3`
- attachment format is `rg`
- blending is enabled, factors include `src-alpha`

In any case, we will make that invalid, because it's undefined according to the Vulkan spec. So I think the rules might be:

> 1. have at least as many components as the target format
> 2. be a `vec4` if any of the [**color**] blend factors for this attachment include one of the following:
>     - "src-alpha"
>     - "one-minus-src-alpha"
>     - "src-alpha-saturated"

3. be a `vec4` if:
    - the target format has alpha, _and_
    - any of the **alpha** blend factors for this attachment include `src` or `src-alpha`.

Plus whatever is needed for #2025.

**Comment by shrekshao** [comment]
(Sorry I misunderstood here. I tested against attachment format `rgba` first)

For 
> * output `vec3`
> * attachment format is `rg`
> * blending is enabled, factors include `src-alpha`

D3D12 debug layer (--enable-backend-validation in dawn) let it passed. We should validate this since the alpha channel would be undefined value.


The conclusion seems good.

**Comment by kainino0x** [comment]
> (Sorry I misunderstood here. I tested against attachment format `rgba` first)

No misunderstanding, I just thought of this when I read your latest result at the time. :)

**Comment by kainino0x** [comment]
> * any of the **alpha** blend factors for this attachment include `src` or `src-alpha`.

Realized this is wrong, I think it should say

> * the `.alpha.srcFactor` is not `'zero'` OR the `.alpha.dstFactor` includes `src` or `src-alpha`

**Comment by kainino0x** [comment]
> * the `.alpha.srcFactor` is not `'zero'`

reading/thinking about this YET FURTHER, this may also be wrong. If src.alpha is undefined, then multiplying it by zero could still be undefined, e.g. if src.alpha was NaN.

Unfortunately I can't find a concrete answer to this (or #2025) in the D3D11 functional spec - all language seems to ignore the possibility that the blend _factor_ uses an alpha value that wasn't output by the shader. However I did find some interesting sections that very explicitly call out the use of write masks to protect against undefined results:

https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#17.15%20Output%20Write%20Masks
> Failure to provide sufficient data to the Output Merger for all of the RenderTarget(s)/component(s) enabled with the write masks results in undefined values being written out.

https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#OutputWrites
> Partial writes to a given o# output register (writing a nonempty proper subset of the declared components) will produce undefined results in the unwritten component(s) that were declared for output. i.e. Declaring o0.rga but only writing o0.r means the RenderTarget location for o0.ga will be written with undefined values. However the application can take advantage of the write-enable masks to prevent undefined values from being written out and thus vary outputs with flow control in a Shader, as long as the condition doesn't vary within a given Draw*() (since the write-enable masks can only be updated between Draw*() calls).

**Comment by kainino0x** [comment]
Ahh the addition I made to the rules earlier (rule 3) is actually redundant: For any format that has an alpha channel, the shader must output vec4 anyway due to rule 1. So the original 2 rules were correct, but revising here for generality/preciseness:

Shader output must:

1. have a superset of the components of the target format
2. be a `vec4` if any of the color blend factors for this attachment include one of the following:
    * "src-alpha"
    * "one-minus-src-alpha"
    * "src-alpha-saturated"

**Comment by shrekshao** [comment]
Does the revised rule without rule 3 covers this case:
fragment output: `vec3<f32>`
attachemnt format: `rg8unorm`
blending:
alpha.dstFactor: `src-alpha`

The attachment doesn't actually have an alpha channel, so the `src-alpha` although reading from something undefined but the value is discarded anyway.

So seems the revised rule is correct...

**Comment by kainino0x** [comment]
Ohh yes sorry, the revised rules I posted aren't actually the original 2 rules. They are still changed to say "color blend factors" instead of "blend factors"

**Comment by Kangz** [comment]
What still needs to happen to be able to close this issue?

**Comment by kainino0x** [comment]
I think we figured out what the spec needs to say, so just spec work.
