### ISSUE TITLE
Interpolate attribute clarification

### ISSUE THREAD

**Issue by sarahM0** [gpuweb/gpuweb#2017]
What are the rules of applying [[interpolate]] to non user-defined variables?

1. When is applied to entry point function parameters or entry point return type:
As entry point function parameters and return type are decorated with a builtin or [[location]]. The question is if we want to allow, [[builtin(...), interplate(...)]], eg.
```
[[stage(fragment)]]
fn frag_main([[interpolate(flat), builtin(position)]] input : vec4<f32>) {}
```

ps. it cannot directly apply to a vertex shader return type since vertex shader return type must include [[builtin(position)]].

2. When applied to a member of a structure type:
Do we allow these?
```
struct S {
  [[interpolate(flat), builtin(position)]] m : vec4<f32>; 
  [[interpolate(flat)]] n : vec4<f32>; 
};
```

How about when it is used?
```
struct Out {
  [[interpolate(flat), builtin(position)]] m : vec4<f32>; 
};

[[stage(vertex)]]
fn vtx_main([[location(0)]] input : vec4<f32>) -> Out 
{
  return Out();
}
```

All these will be clarified if spec says: "Must only be applied to user-defined IO".

**Comment by kvark** [comment]
Interpolation specified without either `location` or `builtin`: I don't think it makes sense to allow. There is no valid use case.

Interpolation on builtins: I think we need a mini-investigation, and the spec would spell out explicitly what kind of interpolation is required for each builtin, if any.

> it cannot directly apply to a vertex shader return type since vertex shader return type must include [[builtin(position)]].

What do you mean? One can write:
```
[[stage(vertex)]]
fn main() -> [[interpolate(flat), builtin(position)]] vec4<f32> {
...
}
```

**Comment by sarahM0** [comment]
> think we need a mini-investigation, and the spec would spell out explicitly what kind of interpolation is required for each builtin, if any.

Because of 
```
Authors can control how user-defined IO data is interpolated through the use of the interpolate attribute. 
```
I assumed interpolation is only defined for use-defined IO and we have no use for [[interpolate(...), builtin(...)]]. 

> What do you mean? One can write:

To specify a user-defined vertex output, one has to write  [[interpolate(...), location(...)]] and vertex output has to include [[builtin(position)]] so:
```
[[stage(vertex)]]
fn vtx_main([[location(0)]] input : vec4<f32>) 
-> [[interpolate(...), location(...), builtin(position)]] vec4<f32>
{ return Out(); }
```
[[interpolate(...), location(...), builtin(position)]] is invalid, it has multiple IO attributes.

So interpolate has to apply to a struct member.
```
struct Out {
  [[builtin(position)]] p: vec4<f32>;
  [[interpolate(flat), location(0)]] m : vec4<f32>; 
};

[[stage(vertex)]]
fn vtx_main([[location(0)]] input : vec4<f32>) -> Out 
{
  return Out();
}
```

**Comment by kvark** [comment]
> I assumed interpolation is only defined for use-defined IO and we have no use for [[interpolate(...), builtin(...)]].

I can't speak for all builtins. As I said, a mini-investigation is needed. But at least for `position` it should be possible to specify *some* interpolation modes. For example, HLSL is happy with "noperspective"/"linear"/"centroid","sample", but not happy with "nointerpolation": http://shader-playground.timjones.io/8f8501ade6d8821f8c8b7f9b1b3fd6e8

After we investigate, we'll need to change the spec to allow interpolation on some of the builtins.

**Comment by jrprice** [comment]
> But at least for `position` it should be possible to specify _some_ interpolation modes. For example, HLSL is happy with "noperspective"/"linear"/"centroid","sample", but not happy with "nointerpolation"

Metal doesn't allow any interpolation modes on any builtins though. Are there enough compelling use cases in HLSL to warrant emulating this functionality in Metal?

**Comment by kvark** [comment]
Well, I said an investigation is needed. Your claim about Metal is not entirely correct: it supports *some* interpolation modes on *some* built-ins. For example `[[barycentric_coord]]` can be used with either `center_perspective` or `center_no_perspective`. But for `[[position]]` specifically, you are right, and that's a good point. So we can say that at least for now, WGSL built-ins don't need any configurable interpolation. That is to say, I don't think the grammar needs to enforce this, since we may want to enable this in future extensions for some built-ins.

**Comment by dneto0** [comment]
> Well, I said an investigation is needed. 

I'd like to see a table listing what each intended target API allows/requires here.

**Comment by jrprice** [comment]
D3D
===
For the `SV_Position` builtin, both FXC and DXC:
- accept `sample`, `centroid`, `linear`, and `noperspective`
- reject `nointerpolation`

In the DXBC generated by FXC, the shader-input register declaration always includes `linear noperspective`, with additional interpolation modes just being appended to this. This suggests that these other interpolation modes are essentially ignored.

Metal
====
For the `[[position]]` builtin, Metal:
- accepts `center_no_perspective`
- rejects everything else

For the `[[barycentric_coord]]` builtin, Metal:
- accepts `center_perspective` and `center_no_perspective`
- rejects everything else

We do not currently have an equivalent to `[[barycentric_coord]]` in WGSL.

Vulkan/SPIR-V/GLSL
===============
SPIR-V accepts all interpolation decorations on built-in variables.
GLSL, however, does not have any way to apply such qualifiers to built-in variables.
