### ISSUE TITLE
Handling limits which are not unsigned longs.

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#2018]
Currently the [`GPUSupportedLimits` interface](https://gpuweb.github.io/gpuweb/#gpusupportedlimits) consists mostly of `unsigned long` values, but some of the limits which are expected to possibly allow larger values have been changed to `unsigned long long` and one limit is expressed in terms of a `GPUExtent3D`. 

On the other side of things, `GPUDeviceDescriptor` expressed the `requiredLimits` as a `record<DOMString, GPUSize32>` , primarily so that unrecognized keys can be detected and cause the call to reject.

This causes several problems, given how the spec is currently written:

 - The full range of the `unsigned long long` (64 bit) limits can't be expressed as a `GPUSize32`.
 - A `GPUExtent3D` can't be passed as part of the `record`, making it impossible to request a larger `maxComputeWorkgroupSize`.
 - The interface should not contain a `GPUExtent3D` as an attribute, since that's the union type and could technically be returned as a `GPUExtent3DDict` or a sequence of 3 numbers.
   - Furthermore, there's a general sentiment among web platform folks that we should prefer consuming dictionaries and returning interfaces, so merely changing it to a `GPUExtent3DDict` is probably not the right answer.
   - This was apparently already discussed in https://github.com/gpuweb/gpuweb/issues/1936, where the resolution was to return a FrozenArray instead, but that still feels awkward.
 - As a stylistic nit: We should be consistent about expressing our types in either the WebIDL form (`unsigned long`) or our own typedefs (`GPUSize32`). The fact that we mix them here is a bit confusing.

There's a few ways we could approach this. We could change the `requiredLimits` type to `record<DOMString, any>`, which would then require the spec to be a lot more exact about how it validates the values passed and would probably be more of a pain for implementers as well. Alternatively @kainino0x mentioned on Matrix that we could use an [`object`](https://heycam.github.io/webidl/#idl-object) instead of the `record` but that would largely suffer the same concerns about increased spec and implementation work while providing even less "default" validation.

My preference would be to instead change `requiredLimits` to a `record<DOMString, double>` and require that all limits be expressed as an appropriately sized scalar value in the future (looking at [`VkPhysicalDeviceLimits`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceLimits.html) I can see how floating point or negative limits could be useful someday). For `maxComputeWorkgroupSize` we would instead report `maxComputeWorkgroupWidth`, `maxComputeWorkgroupHeight`, and `maxComputeWorkgroupDepth` as separate limits. (Or `maxComputeWorkgroupX/Y/Z` if you prefer.) This simplifies how limits are specced, implemented, and interacted with, and the only people whom it affects adversely are users who _really_ wanted to call `computePass.dispatch(...device.limits.maxComputeWorkgroupSize)`. I'm comfortable making them do ever-so-slightly more typing. 😉

Use of a double when specifying limits may cause us minor heartache if we suspect that GPUs may one day ship with more than 9 million GB of addressable memory. Feel free to make a fuss if this limit directly impacts your use case.

So, the TL;DR is that I propose we update to something like the following IDL:

```webidl
interface GPUSupportedLimits {
    readonly attribute GPUSize32 maxTextureDimension1D;
    readonly attribute GPUSize32 maxTextureDimension2D;
    readonly attribute GPUSize32 maxTextureDimension3D;
    readonly attribute GPUSize32 maxTextureArrayLayers;
    readonly attribute GPUSize32 maxBindGroups;
    readonly attribute GPUSize32 maxDynamicUniformBuffersPerPipelineLayout;
    readonly attribute GPUSize32 maxDynamicStorageBuffersPerPipelineLayout;
    readonly attribute GPUSize32 maxSampledTexturesPerShaderStage;
    readonly attribute GPUSize32 maxSamplersPerShaderStage;
    readonly attribute GPUSize32 maxStorageBuffersPerShaderStage;
    readonly attribute GPUSize32 maxStorageTexturesPerShaderStage;
    readonly attribute GPUSize32 maxUniformBuffersPerShaderStage;
    readonly attribute GPUSize64 maxUniformBufferBindingSize;
    readonly attribute GPUSize64 maxStorageBufferBindingSize;
    readonly attribute GPUSize32 minUniformBufferOffsetAlignment;
    readonly attribute GPUSize32 minStorageBufferOffsetAlignment;
    readonly attribute GPUSize32 maxVertexBuffers;
    readonly attribute GPUSize32 maxVertexAttributes;
    readonly attribute GPUSize32 maxVertexBufferArrayStride;
    readonly attribute GPUSize32 maxInterStageShaderComponents;
    readonly attribute GPUSize32 maxComputeWorkgroupStorageSize;
    readonly attribute GPUSize32 maxComputeWorkgroupInvocations;
    readonly attribute GPUSize32 maxComputeWorkgroupWidth;
    readonly attribute GPUSize32 maxComputeWorkgroupHeight;
    readonly attribute GPUSize32 maxComputeWorkgroupDepth;
    readonly attribute GPUSize32 maxComputePerDimensionDispatchSize;
};

typedef double GPULimitValue; // Same as how we handle GPUPipelineConstantValue
dictionary GPUDeviceDescriptor : GPUObjectDescriptorBase {
    sequence<GPUFeatureName> requiredFeatures = [];
    record<DOMString, GPULimitValue> requiredLimits = {};
};
```

**Comment by kvark** [comment]
>  can see how floating point or negative limits could be useful someday

It's not clear to me how these would be useful. Does Vulkan or any other API with experimental extensions have floating point or negative limits that are actually useful?

Other than this, your proposal sounds fine. Let's just use `GPUSize64` instead of `double`.

**Comment by toji** [comment]
> It's not clear to me how these would be useful. Does Vulkan or any other API with experimental extensions have floating point or negative limits that are actually useful?

To be honest, I don't really have a sense of how often some of the limits Vulkan advertises are actually useful, or if they would be appropriate to surface to the web. I based my statement on a couple of things:

 * We have said we want to expose some non-configurable limits, so I anticipate some things that may be purely informational showing up in the struct.
 * Vulkan reports values like `float maxSamplerLodBias;` and `int32_t minTexelOffset;` that seem logical enough at first glance. Again, I don't have insight into the actual utility of said values.

If we don't expect that we'll ever surface values like that (or, alternatively, that we might in the future but they'll never be configurable) then great!  Using `GPUSize64` rather than a `double` would be fine by me!

**Comment by toji** [comment]
Put together pull request #2020, assuming this is the direction we want to go.

**Comment by kainino0x** [comment]
I definitely could see there being float values, the main ones that come to mind are lod bias (as mentioned) and maybe viewport sizes. But we can easily change this later.
