### ISSUE TITLE
Missing atomicSub function

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2019]
Is there any reason that we don't have `atomicSub` in the spec?
I see that both MSL (`atomic_fetch_sub_explicit`) and SPIR-V (`OpAtomicISub`) support it, at least.

**Comment by alan-baker** [comment]
Back when I wrote the atomics proposal, I thought it was desirable to have fewer polyfills. HLSL doesn't expose a subtraction atomic. If you think it's valuable we could polyfill it on D3D with negation and bitcasts.

**Comment by kvark** [comment]
I see that both MSL and SPIR-V support this, so that makes a majority. Plus, it's trivial to polyfill. So I think we should have it.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-08-24-Minutes#-missing-atomicsub-function-2019-">WGSL meeting minutes 2021-08-24</a></summary>


* DN: We were avoiding polyfills here, but everyone has it but hlsl, so let’s just polyfill there?
* MM: Sounds good, browsers’ polyfill would be just as good as the authors’.
* Consensus: Needs spec!

</details>
