### ISSUE TITLE
Consider adding a 32- by 32-bit multiplication function resulting in two u32s, high and low

### ISSUE THREAD

**Issue by hcsch** [gpuweb/gpuweb#2023]
## Platform support
Platforms for which I could find a native `umul` instruction / function:
- [SPIR-V](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpUMulExtended)
- [Shader Model 4 Assembly (DirectX HLSL)](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/umul--sm4---asm-)
  (Is this enough for `umul` to work with HLSL for WGSL? I couldn't find a `umul` function for HLSL, only this assembly instruction)
- [DXIL](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst#umul)

[MSL](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#page=142) has a `mulhi` function that returns the high 32bits of a 32x32 multipliction, but does not seem to have a `umul` function (probably requiring some polyfilling).

## Motivation
I'm fiddling around with a compute shader that I want to generate a [Buddhabrot](https://en.wikipedia.org/wiki/Buddhabrot) with.
For this I need pseudo-randum number generation on the GPU.
In GLSL I have found, that a port of the [Random123 Philox2x32](https://github.com/quinoacomputing/Random123) algorithm works quite well for me as a PRNG ([CBRNG](https://en.wikipedia.org/wiki/Counter-based_random_number_generator_(CBRNG)) to be more specific).
This method of PRNG requires a `umul` (the Random123 devs called theirs `mulhilo`) function (or a temporary `u64`) for a part of the algorithm involving multiplication with a "magic" number (here the relevant snippet of my ported GLSL):
```glsl
uint[2] _philox2x32round(uint[2] ctr, uint key) {
    uint hi;
    uint lo;
    umulExtended(PHILOX_M2x32_0, ctr[0], /* out */ hi, /* out */ lo);
    uint[2] result = {hi ^ key ^ ctr[1], lo};
    return result;
}
```

How this function with two returned values would be idiomatically implemented in WGSL I'm not sure (maybe a `HiLo` struct, an `array<u32, 2>` or a `vec2<u32>`).
This is especially so, since I'm still pretty unfamiliar with WGSL and come here mostly due to [`wgpu`](https://github.com/gfx-rs/wgpu) switching to WGSL for the examples and (to me) seemingly aiming to use WGSL mainly.

I'd understand if this is considered to niche for now. Maybe I just need to find a different PRNG algorithm for GPGPU programming.

**Comment by dneto0** [comment]
Related to #1565

**Comment by hcsch** [comment]
Right, should I close this one and add a comment to #1565? I sadly forgot to search for `mulhi` or generic multiplication related issue apparently.

**Comment by jdashg** [comment]
Yeah it sounds like this is covered in #1565. Thanks for filing this though!
