### ISSUE TITLE
Do pipeline blend states need to be validated against the pipline render targets?

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#2025]
Given the findings in #2013, it seems like we should do some investigation to determine if validation is needed to ensure compatibility between a pipeline's render target formats and the blend state used. For example: Is it valid to use a blend state of `dst-alpha` with a target state format of `rg8unorm`, since that format ostensibly doesn't have an alpha channel to sample from? 

Ideally the underlying implementation would treat the missing alpha channel as `1`, but we should verify that this is the case and if cross-platform differences are found some validation should be added to avoid differences in behavior across devices.

**Comment by kainino0x** [comment]
cc @shrekshao maybe you can test this as well

**Comment by shrekshao** [comment]
For the case of 
- shader output `vec3<f32>(0.49804, 0, 0)`
- attachment format is `rg8unorm`
- blending enabled, srcFactor: `dst-alpha`, dstFactor: `zero`. operation: `add`

Turns out Metal, D3D12, Vulkan (Win) all have expected result. (127, 0, 0) (assuming alpha being 1)

**Comment by kainino0x** [comment]
Thanks for checking! If the validation layers don't report anything then we should probably dig into specs to see whether they allow this. I tried to find it in the "Blending" section of the vulkan spec, but everything there just assumes that the destination texture has 4 components, e.g.

> Rd,Gd,Bd and Ad represent the R, G, B, and A components of the destination color. That is, the color currently in the corresponding color attachment for this fragment/sample.

**Comment by kainino0x** [comment]
Preliminary results show this might be an issue on D3D12, haven't dug into the failure fully yet.
https://ci.chromium.org/ui/p/chromium/builders/try/dawn-win10-x64-deps-rel/b8839142196304837424/test-results?q=ExactID%3Aninja%3A%2F%2F%3Awebgpu_blink_web_tests%2Fwpt_internal%2Fwebgpu%2Fcts.html%3Fq%3Dwebgpu%3Aapi%2Coperation%2Crender_pipeline%2Cpipeline_output_targets%3Acolor%2Ccomponent_count%2Cblend%3A*+VHash%3A53f13870d4596c3e

**Comment by kainino0x** [comment]
I failed to find anything in the D3D11 functional spec about this. Relevant links:
https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#17.15%20Output%20Write%20Masks
https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#OutputWrites

**Comment by shrekshao** [comment]
For the D3D12 Intel failure
inputs:
```
dst color [1, 0, 0, 1]
output: [0, 1],
colorSrcFactor: 'dst-alpha',
colorDstFactor: 'zero',
alphaSrcFactor: 'zero',
alphaDstFactor: 'zero',

expecting: [0, 1],
actual: [1, 0]
```
So here the driver is not reading from an assumed src-alpha channel. The blending op looks well defined. So it's a D3D Intel specific issue?

**Comment by kainino0x** [comment]
My suspicion is that it's reading from an undefined **dst**-alpha channel. The format here is rg8unorm so dst-alpha doesn't exist but is used in colorSrcFactor.

**Comment by kainino0x** [comment]
@RafaelCintron @litherum maybe you can help figure out whether this is indeed giving us uninitialized data in D3D12 or Metal? (We only need one backend to give uninitialized data to resolve this.)

I strongly suspect it is, based on the fact that I could find nothing in D3D12's documentation or the Vulkan spec.
So I think we will end up adding this validation.

(An alternate approach was suggested: make it appear to always be one or zero by tweaking the blend state. But it's a bit more complicated and probably isn't very helpful.)

**Comment by RafaelCintron** [comment]
The [Defaults for Missing Components](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#DefaultsForMissingComponents) section of the D3D11 functional spec apply here.

I've copied it below:
> 19.1.3.3 Defaults for Missing Components
> The default value for missing components in an Element format is "0" for any component except A, which gets "1". The way "1" appears in the Shader depends on the Element format, in that it takes the specified data interpretation of the first typed component that is actually present in the format (starting from the left in RGBA order). If this interpretation is UNORM or FLOAT, then 1.0f is used for missing components. If the interpretation is SINT or UINT, then 0x1 is used.

> For example, when the format DXGI_FORMAT_R24_UNORM_X8_TYPELESS is read into a Shader, the values for G and B are 0, and A is 1.0f. For DXGI_FORMAT_R16G16_UINT, the B gets 0 and A gets 0x00000001. DXGI_FORMAT_R16_SINT provides 0 for G and B, and 0x00000001 for A.

**Comment by kainino0x** [comment]
Thanks @RafaelCintron!

This section strongly appears to be worded with only shader loads in mind:

> The way "1" appears in the Shader depends on the Element format

Is there any language which actually confirms that this section applies to blending inputs?

(BTW, there is an equivalent section in Vulkan, but I can't find any indication at all that it's used for blending.)

**Comment by litherum** [comment]
From the Metal team: Metal blending always operates on `float4`s, and the rules for promoting to `float4`s for blending adheres to the same rules as the MSL spec describes about texture read promotions.

I also wrote a test and ran it on a variety of hardware, and they all follow these rules, in practice:

- Apple M1
- AMD Radeon Pro Vega 56
- AMD Radeon RX 570
- AMD Radeon Pro 560
- Intel Iris Pro Graphics
- Intel(R) HD Graphics 630
- NVIDIA GeForce GT 750M

**Comment by Kangz** [comment]
@litherum My understanding of texture read promotion is that the rest of the texture is filled as `0, 0, 1`, is this the case that alpha is treated as if it is one in the test you ran?

**Comment by RafaelCintron** [comment]
@kainino0x the section I quoted also applies to destination blending as well.

**Comment by kainino0x** [comment]
Resolution: Confirmation from Metal and D3D12 is enough to move forward. We will also make sure this is tested well so we can detect if it's not true on any system.<sup>1</sup>
Most likely Vulkan will amend the spec to clarify the same thing, but TBD (https://github.com/KhronosGroup/Vulkan-Docs/issues/1614). If not, we can paper over this by just replacing `dst-alpha` with `one` and `one-minus-dst-alpha` with `zero` in the render pipeline.

<sup>1</sup> I think this is already covered by @shrekshao's operation tests in https://github.com/gpuweb/cts/pull/676

BTW, I dug into the D3D12/Intel failure above, and [realized](https://bugs.chromium.org/p/dawn/issues/detail?id=1074#c6) it couldn't just be from dst-alpha producing the wrong value. It seems like a driver issue, but I don't know what.

> And the symptom, upon closer inspection, actually looks like the draw call didn't work at all, not just like dst-alpha loaded the wrong value.

**Comment by Kangz** [comment]
@kainino0x can this be closed or does the spec need fixing?

**Comment by Kangz** [comment]
Up!

**Comment by kainino0x** [comment]
The section which defines blending hasn't been written yet. But I think we can just close this since we've figured out we don't need to add validation.
