### ISSUE TITLE
Rename forceSoftware and isSoftware

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2030]
This issue is just about renaming these fields, not about changing their meaning or semantics.

There are two reasons:

1. There may be IP concerns about the WebGPU API if these names are left as-is.
2. These names describe a "how" but not a "what." They don't describe behavior or performance or anything measurable/observable.

We don't have any particular requests for what the name should be changed _to_, but it's fairly important to us that the name not be left including the word "software."

Ideas:
- `optimizedForHostTransfers`
- `optimizedForShaderBranching`

Our intention is not to muddle the meaning of these variables. It's totally fine to have normative prose for these values which says that the performance of these adapters is expected to match the performance of WebAssembly / JavaScript.

**Comment by toji** [comment]
> There may be IP concerns about the WebGPU API if these names are left as-is.

> it's fairly important to us that the name not be left including the word "software."

Sorry, but I think a lot of us a lacking context here. Could you better explain the potential IP concerns regarding the word "Software" so that we can better avoid whatever that particular issue is? I'm not opposed to a name change if necessary, but I'd like to understand why it's needed.

**Comment by toji** [comment]
Expanding on this slightly:
```
 - optimizedForHostTransfers
 - optimizedForShaderBranching
```

Neither of these names communicate to me the thing that we intended to use the flag for, nor do I feel like developers would intuit the ramifications of using flags with those names. Something like `isHardwareAccelerated` seems like it would be more intuitive from a developers point of view, but it's unclear to me from the initial request if that name would also run into whatever concerns prompted this request in the first place. (i.e.: Is it specifically the word "software" that you are trying to avoid, or the concept of the API being executed on something other than GPU hardware?)

**Comment by litherum** [comment]
Unfortunately, "hardware" poses the same problems as "software." Let's try to come up with "what" names rather than "how" names.

**Comment by kainino0x** [comment]
"Hardware" is a "what" name. WebGPU is not a 3d rendering API, it's a GPU hardware API.

**Comment by litherum** [comment]
"Hardware" does not describe behavior. It describes how to achieve that behavior.

**Comment by kainino0x** [comment]
I guess this is subjective. To me WebGPU is a hardware abstraction layer, not a box that takes commands in and puts pictures/results out, but I can see how both are valid views.

**Comment by kvark** [comment]
We have a lot of behaviors that are essentially defined as "this is how the hardware works"/"this is what hardware does". For example, requirements for the texel offsets to be literals, or the semantics of MSAA resolves.

Our chapter says:
> The mission of the GPU for the Web Community Group is to provide an interface between the Web Platform and modern 3D graphics and computation capabilities present on native system platforms. 

WebGPU is a layered API on top of the native system capabilities, and has been from the start. It defines the design space for us. If we remove the basis of this design space (after 5 years of living it it), then it's not clear why/how the API decisions where made.

**Comment by kainino0x** [comment]
After further discussion we're considering terms like:

- "slow"
- "low efficiency"
- "major performance caveat"

**Comment by toji** [comment]
I have a mild preference for "major performance caveat", simply because we've already established it's use with WebGL. We'd have to think carefully about how to apply it, though. The "force" pattern was intentional, and avoids some of the concerns raised from using an "allow" pattern, but "forceSoftware" has a very different connotation to "forceMajorPerformanceCaveat".

**Comment by kainino0x** [comment]
forceSoftware is supposed to return null if no software implementation is available, and vendors are supposed to all implement that.

forceFallbackImplementation? unsure if this name would solve the original concerns, but potentially OK because it says nothing about what the usual and fallback implementations _are_.

**Comment by sminnee** [comment]
Is an important difference whether it runs on the GPU or the CPU? Is that less problematic than hardware/software? Could that be used as the basis of the naming? Eg `forceCPU` or `avoidGPU`?

**Comment by toji** [comment]
I would assume that, given #2029, Apple is trying to avoid explicitly mentioning GPU/CPU as well (though the scope of that request wasn't really made clear in that PR.)

**Comment by kainino0x** [comment]
Resolution: open a PR to propose forceFallbackAdapter and isFallbackAdapter or isFallback
