### ISSUE TITLE
Creating arrays/structs in expressions

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2045]
https://github.com/gpuweb/gpuweb/issues/1272#issuecomment-900706631 brought up a useful feature - the ability to create arrays and structs in expressions, rather than as a statement. This would allow them to be meaningfully used at module scope.

In the HLSL corpus I gathered a few years ago from various GitHub projects, about 9.1% of the files use HLSL's facility to do this. Of the files which use it, it is used an average of 7 times per file. So this is something that people do.

A few options:

1. Do it like HLSL: `let myArray: array<i32, 5> = {1, 2, 3, 4, 5};`
2. Do it like C++: `let myArray = array<i32, 5> {1, 2, 3, 4, 5};`
3. Generate implicit constructors at compile time: `let myArray = array<i32, 5>(1, 2, 3, 4, 5);`
4. Maybe other options?

**Comment by jrprice** [comment]
WGSL has type constructors for arrays and structs, so your option 3 is already valid. I don't see anything prohibiting these constructors from being used at module scope either.

What is it that you are proposing that we add beyond this?

**Comment by alan-baker** [comment]
What's worth checking is whether those HLSL files also use dynamic indexing into the array. That is currently disallowed in WGSL.

**Comment by litherum** [comment]
> WGSL has type constructors for arrays and structs

Oh, I totally didn't realize this! Thanks!

**Comment by litherum** [comment]
I do think it's worth revisiting why we can't dynamically index into `let` arrays/matrices (in general, not just for constexpr). It's clearly something that authors want to do, it is implementable on SPIR-V (albeit not directly) and it hasn't been demonstrated to cause any performance penalties. It's silly to disallow it.

**Comment by jdashg** [comment]
I would not describe it as "silly" to disallow it. It's a choice with reasoning behind it, even if you don't like the reasoning.
