### ISSUE TITLE
Brain dump on all things wrong with WGSL

### ISSUE THREAD

**Issue by morganbarrett** [gpuweb/gpuweb#2048]
So WGSL is meant to be the de facto shader language for the web, designed solely for the needs of the web. The cpu equivalent of this is Javascript which is obviously what WGSL is used with. So my main question would be why it takes inspiration (in terms of purely syntactical sugar) from everything but Javascript and its influencers. Below are all the idiosyncrasies that annoy me and are sure to cause trouble for anyone starting out in the future.

### Loop
I don't understand what is to be gained by `loop {...if(cond){ break; }...}`, why not `while` and `do while`, it is trivial to translate.

### (De)increment
Like this is an easy one, no? The prefix version at least.

### Let 
I don't even need to explain this one, `let` should be `const`.

### Fn
Same goes as above, this should be `function` surely?

### Vec3\<f32>
I've seen this one mentioned already, I'm assuming one can't make a vector of a custom structure, if so the abstract type thing really doesn't make sense and is a pain in the ass to write. `vec4f` `vec2i` `vec3u` this sort of thing?

### ->
The type hinting already very closely resembles typescript/flow, so it might make more sense to take inspiration from here for return types. Instead of `fn test(i: u32) -> u32 {` would be better as `function test(i: u32): u32 {`.

### std
I've seen the standard library mentioned as well and for the sake of learning curve, code completion and coming from js, would work better modularised e.g `Math.cos(x)` `Vector.dot(x, y)` `Array.length(arr)`.

### [[block]]
The double bracket expressions would be more familiar as @ expressions.

### Blockless ifs
`if(true) hi();`

### 420u
I think unsigned ints should be un postfixed and signed ints should start with +/-.

### Storage
`var<uniform> blah` do something, anything, differently.

**Comment by kainino0x** [comment]
> I don't understand what is to be gained by `loop {...if(cond){ break; }...}`, why not `while` and `do while`, it is trivial to translate.

WGSL has `for` loops.

> I don't even need to explain this one, `let` should be `const`.

Calling it `const` is a javascriptism, but in fact it does not match the semantics of javascript `const` anyway as it refers to a constant value, not a constant variable reference to a mutable value.

> I've seen this one mentioned already, I'm assuming one can't make a vector of a custom structure, if so the abstract type thing really doesn't make sense and is a pain in the ass to write. `vec4f` `vec2i` `vec3u` this sort of thing?

There will be types like f64, f16, i8, u16, etc. in the future.

> The double bracket expressions would be more familiar as @ expressions.

The syntax is adopted from C++.

> I think unsigned ints should be un postfixed and signed ints should start with +/-.

This would be quite weird, I've never seen precedent for this.

> `var<uniform> blah` do something, anything, differently.

Why? Do you have a proposal? A lot of design work went into this and I think we're pretty confident about it now (though there are some related things that may change soon).

**Comment by morganbarrett** [comment]
> WGSL has for loops.

But not while or do while loops.

> Calling it const is a javascriptism, but in fact it does not match the semantics of javascript const anyway as it refers to a constant value, not a constant variable reference to a mutable value.

But why let?  I think it's a bad choice.

> There will be types like f64, f16, i8, u16, etc. in the future.

I quite like the Uint8Array style of js, maybe Uint8Vec3?

> The syntax is adopted from C++.

Fair enough, that one is not too bad.

> This would be quite weird, I've never seen precedent for this.

Weird... or cool?

> Why? Do you have a proposal? A lot of design work went into this and I think we're pretty confident about it now (though there are some related things that may change soon).

No, this is the least of my issues with this, but I don't like how it is after the var.

**Comment by kainino0x** [comment]
> But why let? I think it's a bad choice.

Precedent from mathematics and functional programming languages.

(Sorry I haven't replied to everything, anything I didn't reply on I just didn't have anything in particular to say about)

**Comment by morganbarrett** [comment]
No worries, I appreciate your answers, without any insight it just seems like a mismatch of randomness. I just worry some of the issues such at `let` will lead to a really frustrating workflow when going between js and wgsl, it reminds me of going back and forth between php and js, absolute hell.

**Comment by Kylebrown9** [comment]
Isn't the CPU equivalent WASM?
> The cpu equivalent of this is Javascript...

**Comment by munrocket** [comment]
>Loop, let, fn, vec3<f32>, ->

WGSL inspired by Rust. It looks pretty good if you think of it like a Rust'y version of GLSL.

> let vs var is confusing javascript comunity

Agree that this looks weird for web developers. Maybe rename var -> mut and make WGSL even more Rust'y?

> Storage

I guess this is similar to #1975

**Comment by morganbarrett** [comment]
Yeah, I think if it was all very "Rust'y" it wouldn't be as bad (yet still confusing). I've decided to just write a babel plugin, so I can use ordinary js and transpile it to wgsl, in a similar vein to gpujs. With added benefits of being able to reuse the functions on cpu and automatic configuration of buffers inferred from use.

**Comment by jdashg** [comment]
Thanks for the feedback!
Let's open individual issues for any of these points that you want to continue discussing, please!
