### ISSUE TITLE
Missing clarification on malicious use of GPU resources (e.g. mining) against intent of browser user

### ISSUE THREAD

**Issue by Kylebrown9** [gpuweb/gpuweb#2049]
WebGPU will allow code to have more access to GPU resources. Some malicious code authors may use this access to perform computation on their behalf (e.g. mining cryptocurrency) which does not benefit and is not desired by the browser user.
This risk should be addressed in [Section 2. Malicious use considerations](https://www.w3.org/TR/webgpu/#malicious-use) to clarify the view of WebGPU authors on this issue.

**Comment by kvark** [comment]
Technically, code authors can already use the GPUs for mining via WebGL. Introduction of WebGPU doesn't change this.
I agree that it would make sense to have this mentioned in the considerations section.

**Comment by kuro68k** [comment]
WebGL has been a bit of a disaster for users, facilitating the theft of their compute resources for crypto mining.

I would suggest per-site permission to use WebGPU be mandatory, with it defaulting to off. This works well for other resources such as sound input/output and cameras. Unfortunately lowering the default limits is unlikely to prevent abuse, unless they are lowered so far that they become useless to most legitimate applications.

**Comment by aminick** [comment]
Well, it could be "un-malicious" too. This technology will enable more decentralized/accesssible blockchains. But of cause, the user has to opt-in.
