### ISSUE TITLE
Should depth-stencil render attachments require views to have aspect = "all" for combined depth-stencil formats?

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#2062]
The WebGPU API allows creating a texture view which selects a single aspect of a combined depth stencil texture using aspect "depth-only" or "stencil-only".
Such a view can be set as the depthStencilAttachment of GPURenderPassEncoder.

The expectation would be that the render pass would execute as-if there were depth attachment if the view were stencil-only, or as-if there were no stencil attachment if the view were depth-only.

This is not directly implementable on Vulkan and D3D12.

On Vulkan, an image view can be created of a VKImage with a particular aspectMask, but the aspectMask is ignored for depth-stencil attachments.
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkImageSubresourceRange.html
> When an image view of a depth/stencil image is used as a depth/stencil framebuffer attachment, the aspectMask is ignored and both depth and stencil image subresources are used.

On D3D12, [`D3D12_DEPTH_STENCIL_VIEW_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_depth_stencil_view_desc), does not contain any members to select just the depth or the stencil aspect.

The consequence of the limitation means that the depth/stencil data is still both readable and writable by the depth/stencil loadOp and storeOp, and by any depth/stencil test on Vulkan/D3D12.

I think there are at least two possible options: 
 1. Disallow depth stencil attachments unless they select all of the texture aspects. This would be a validation error on beginRenderPass
 2. Have a single aspect depth-stencil view imply depthReadOnly/stencilReadOnly=true for the other unselected aspect, AND require the pipeline does not read or write the aspect (the depth/stencil test is disabled). This would be additional validation on setPipeline, similar to validation that we have for depthReadOnly/stencilReadOnly.

**Comment by kvark** [comment]
Can't we technically make it, as far as the user is concerned, so that the depth-stencil texture viewed as depth-only *does* behave as a depth-only texture. That would only mean that we validate the depth and stencil load/store ops, if I understand correctly.

**Comment by austinEng** [comment]
When I first wrote this, I thought it would not be possible because we would need to recompile pipelines to disable the depth/stencil test. However, I think I forgot about validation between the render pipeline and the render pass attachment state, so you may be right.

[validating GPUDepthStencilState](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpudepthstencilstate) checks that if stencil testing is enabled, the format has a stencil aspect, and if depth testing is enabled, the format has a depth aspect. So there, GPUDepthStencilState.format can't, for example, be depth24plus but have the stencil test enabled.

[derive render targets layout from pass](https://gpuweb.github.io/gpuweb/#abstract-opdef-derive-render-targets-layout-from-pass) and [derive render targets layout from pipeline](https://gpuweb.github.io/gpuweb/#abstract-opdef-derive-render-targets-layout-from-pipeline) probably need language about selecting the particular aspect of the depth-stencil attachment's format. But this should be sufficient to make sure that the aspects visible in the render pass are exactly the same as the ones the render pipeline uses?

**Comment by Kangz** [comment]
Just so I understand, is the suggestion to make the following attachment format + aspect combination match the render pipeline format:

 - `depth24plus-stencil8` + `depth-only` matches `depth24plus`
 - `depth24plus-stencil8` + `stencil-only` matches `stencil8`
 - `depth24unorm-stencil8` + `depth-only` matches `depth24unorm`
 - `depth24unorm-stencil8` + `stencil-only` matches `stencil8`
 - `depth32float-stencil8` + `depth-only` matches `depth32float`
 - `depth32float-stencil8` + `stencil-only` matches `stencil8`

Then in the backends we:

 - On Vulkan select only the correct aspect of the attachment, and hopefully the Vulkan spec allows that and doesn't touch the other attachments.
 - On D3D12 use `loadOp = "load"` and `storeOp = "store"` for the unused aspect so that aspect stays "untouched"
 - Same thing on Metal and hope it works.

If this works it would be ideal but I'm not sure all the backend APIs will do the correct thing. Maybe worth implementing and testing it works before making a decision. @kvark is this something that already is supposed to work in wgpu?

---

But actually, Vulkan render pass compatibility requires that the formats of the pipeline's `VkRenderPass` matches the format of the `VkFrameBuffer`'s `VkRenderPass`, and then the `VkFrameBuffer` requires that:

> VUID-VkFramebufferCreateInfo-pAttachments-00880
> If flags does not include VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of pAttachments must have been created with a VkFormat value that matches the VkFormat specified by the corresponding VkAttachmentDescription in renderPass

(and depth formats aren't view-compatible with their depth-stencil equivalent)

So I think the Vulkan spec force the issue here, and depth-stencil attachments must be created with `"all"`

**Comment by kvark** [comment]
I don't think there is anything in conflict about Vulkan RP compatibility. We aren't trying to change any format here. The format still has to match between the pipeline and a render pass.
I think this is purely validation business: if the D/S view selects the depth-only component, we validate the whole render pass as if it only has the depth. I.e. pipelines that modify stencil are not allowed. Clearing load/store ops are not allowed. You got the idea.

**Comment by Kangz** [comment]
That's not what I thought the intent of the issue was, but that's definitely an option too!

**Comment by kvark** [comment]
That would probably be fine as well. It could be annoying if people want to use the same view for rendering into and reading from, since reading requires non-"all", and rendering would require "all", effectively demanding separate views (even though conceptually they are seeing the same thing).

**Comment by kainino0x** [comment]
It should be fine if the format is depth-only or stencil-only (where "all" is equivalent to one of the other options). In other cases yeah, but in those cases they're completely ignoring one plane of the texture so it's not that weird that it's a bit clumsy.

**Comment by austinEng** [comment]
One reason that requiring "all" may be better is that we cannot validate`GPURenderBundleEncoder.setPipeline` against the view at encoding time, because we don't know the attachments. GPURenderBundleEncoderDescriptor and GPURenderPassLayout only contain the format and depthReadOnly / stencilReadOnly. We would need to add additional booleans like depthAspectAvailable and stencilAspectAvailable.

**Comment by kvark** [comment]
Good point! Perhaps we could naturally extend this:
```js
enum GPURenderBundleDepthStencilAspect {
  "unused",
  "used",
  "read-only",
}

dictionary GPURenderBundleEncoderDescriptor {
  ...
  GPURenderBundleDepthStencilAspect depth = "unused";
  GPURenderBundleDepthStencilAspect stencil = "unused";
}
```

Right now the semantics of `depthReadOnly` is a bit wonky anyway. It's nice to have a dedicated "I don't have depth" signal, instead.

**Comment by kainino0x** [comment]
Needs 2 new issues: one for the comment just above, and one about loosening the validation to allow depth-only/stencil-only views to be used as attachments if the pass is known not to use the other attachment.
