### ISSUE TITLE
Implicit GPUTextureSampleType for texture_2d<f32>

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#2064]
In order to construct the implicit GPUBindGroupLayout, the implementation needs to choose the GPUTextureSampleType for texture_2d\<f32\> bindings. This type may either be `"float"` or "`unfilterable-float`".

Currently the spec says, "Set textureLayout.sampleType to resource’s component type." with a TODO "Detail how the sampleType is chosen from the binding."

At least a few options:
1. Always use "float"
2. Always use "unfilterable-float"
3. Determine the type based on static analysis of the shader

I think implementing some sort of analysis in (3) would be the least bad solution, though still prone to some fragility.
Here is one possible analysis:
 - The sampleType for f32 textures defaults to "unfilterable-float"
 - If the texture binding is statically used with one of the WGSL `textureSample*` calls in any of the GPUProgrammableStages, the sampleType is promoted to "float"

The reasoning behind this analysis is that the "unfilterable-float" GPUTextureSampleType is compatible with all floating-point textures. Floating-point textures are either strictly "unfilterable-float" or include both "unfilterable-float" and "float" as compatible sample types.

However, if the texture is statically used with a `textureSample*` call in the WGSL shader,  we promote it to "float". This is because "float" texture bindings are compatible with both filtering and non-filtering samplers.

This is one example where the analysis fails to do what a developer might intend:
It would be otherwise valid for a shader to perform textureSample(tex, samp, coord) using a strictly unfilterable-float texture ("r32float", "rg32float", and "rgba32float"), and with a non-filtering sampler. However, in this situation, the analysis will unconditionally choose "float" as the sampleType of the texture binding (the type of the sampler is unknown during pipeline compilation).

**Comment by kvark** [comment]
When we are considering (3), I don't think of any *additional* analysis. A WGSL program/entry point already has to derive this information in order to validate if the BGL entry is valid. So we have all the information here, passing it to the implicit BGL seems trivial.

> This analysis fails to do something valid if the developer uses textureSample* on a texture_2d with a format that is only compatible with "unfilterable-float" ("r32float", "rg32float", and "rgba32float"). Then, the sampleType will default to "float" which is incompatible with the texture format.

I don't understand this bit. If the shader code requires filterable floats but the user provides non-fiterable, that's a hard error. What's the "fails to do something valid" about?

**Comment by austinEng** [comment]
> I don't understand this bit. If the shader code requires filterable floats but the user provides non-fiterable, that's a hard error. What's the "fails to do something valid" about?

textureSample can be used with a non-filtering sampler, in which case it is valid. So the developer could be expressing something that *could* be valid, but the defaulting behavior I described here will always hit a validation error.

I will update the text to say:
> This is one example where the analysis fails to do what a developer might intend:
It would be otherwise valid for a shader to perform `textureSample(tex, samp, coord)` using a strictly unfilterable-float texture ("r32float", "rg32float", and "rgba32float"), and with a non-filtering sampler. However, in this situation, the analysis will unconditionally choose "float" as the sampleType of the texture binding (the type of the sampler is unknown during pipeline compilation).

**Comment by kvark** [comment]
Ok, in any way, my main point stands: we already know all of this information for the purposes of validation.

**Comment by kainino0x** [comment]
IIUC the "failure" of the analysis is a direct consequence of fact that _sampler_ binding layouts default to "filtering". In an explicit BGL samplers default to filtering (by IDL rules), and in an implicit BGL they still default to filtering (which is consistent). Therefore when computing the default pipeline layout, all sampler (bindings) _are_ filtering, and therefore all textures used with them _must_ be filterable. So I don't consider it a failure at all.

**Comment by kainino0x** [comment]
(I'm in support of option 3 as well.)

**Comment by kvark** [comment]
Oh right, thanks @kainino0x , I was missing this. So we indeed have a big problem here with implicit BGLs.
If we see this code
```
textureSample(myTexture, mySampler);
```
We don't know if this should be a non-filtering sampler with non-filterable texture, or a non-filtering sampler with a filterable texture, or a filtering sampler with filterable texture...

**Comment by kvark** [comment]
@fintelia we considered this originally, and decided to not differentiate this at the type level, because:
  - that would also require the samplers to be split into filtering/non-filtering
  - would make any translation into WGSL significantly more complicated, since none of the existing languages have this distinction
  - would reduce the ability to re-use the shaders. I.e. today I can have `texture_2d<f32>` which is used as filtered by one entry point and non-filtered by another.

All of the related mismatches are detected at pipeline creation time.
