### ISSUE TITLE
[meta] Wiki Matrix link is outdated?

### ISSUE THREAD

**Issue by ShadowJonathan** [gpuweb/gpuweb#2070]
> `You can also join the chat [on Matrix](https://matrix.to/#/+webgraphics:matrix.org).`

(in [Implementation Status](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status))

Matrix/Element is moving away from "Communities", and onto ["Spaces"](https://element.io/blog/spaces-the-next-frontier/), with communities being a non-specced and single-implementation-propriatary feature anyways, Spaces is being pushed forward, has been specced, and will soon be out of Element's "Beta".

That link (starting with the `+` sigil, signalling a "community") is therefore kinda outdated, I recommend setting up a space, or linking to the existing one in that wiki page.

**Comment by kvark** [comment]
@kainino0x why not use https://matrix.to/#/#WebGPU:matrix.org ?

**Comment by ShadowJonathan** [comment]
@kvark that's the WebGPU room specifically, `#webgraphics:matrix.org` represents a much broader slice of the community;
![image](https://user-images.githubusercontent.com/22740616/131534543-bc8f678b-3de5-4fe1-b3ca-7afc5efebe9d.png)

You can see wgpu and Dawn in there too, alongside some more other technical rooms.

**Comment by kvark** [comment]
Can the space be named `WebGPU`? or will there be a collision with the room name?
Element's UI for managing spaces is quite sad.

**Comment by kainino0x** [comment]
> @kainino0x why not use https://matrix.to/#/#WebGPU:matrix.org ?

I linked both.

> Can the space be named `WebGPU`? or will there be a collision with the room name?

The `#webgraphics` name appears to be in the same namespace with `#webgpu`. My intent with the Space is people can find the list of channels, join all the ones they're looking for, and then forget about it until next time they want to find the other channels.
