### ISSUE TITLE
Fake transfers for getMappedRange-created ArrayBuffers?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2072]
_Originally posted by @kainino0x in https://github.com/gpuweb/gpuweb/issues/747#issuecomment-907489195_

> > * Non-transferable ArrayBuffers (mapped ArrayBuffers shouldn't be transferable to other threads). (We can do this without JS changes by faking transfers, by making them actually copies instead.)
> 
> We might be able to make this work entirely within our spec instead of having to go change the behavior of ArrayBuffer. In more detail:
> 
> If you tried to transfer a getMappedRange-created ArrayBuffer, it would appear to work entirely normally - old ArrayBuffer would get detached - except the underlying data would get copied into a new, run-of-the-mill ArrayBuffer, which means that any writes to the new ArrayBuffer would *not* appear in the GPUBuffer upon unmap().

**Comment by pythonesque** [comment]
Using SharedArrayBuffers would also be a considerable hit from an optimization perspective, I suspect (whether in JavaScript or not).  In Rust, it would require treating each access to an element as an atomic which disables lots of useful optimizations and is generally very unpleasant to use (for example, safe transmute operations that treat a bag of bytes as a bag of plain old data types of other sizes or structures are not generally sound for atomics).

**Comment by kainino0x** [comment]
JavaScript provides [atomics](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics), but allows racy access to SharedArrayBuffer without them.

I don't think we would change *all* mappings to return SharedArrayBuffer, it would probably be opt-in.

**Comment by pythonesque** [comment]
I think that if you allow racy accesses at all, the optimizer must still treat them as something like "Relaxed" or "unordered" LLVM intrinsics in order to ensure there are no unsafe optimizations (such as assuming  an in-bounds index stored and then loaded from an array slot is still in bounds).  Similarly, I think if there are *any* APIs that allow returning non-SharedArrayBuffer mappings, then we still need one of the other proposed solutions to figure out the `unmap` story.  Of course if that's done, then opt-in SharedArrayBuffer could be nice :)

**Comment by kainino0x** [comment]
_Originally posted by @pythonesque in https://github.com/gpuweb/gpuweb/issues/747#issuecomment-907516222_
> AFAIK, what you're describing *is* the behavior for non-transferable objects, though?  Minus the fake detach, that is.  I guess the point is that this wouldn't be an observable behavior change compared to the usual behavior (except in the context of WebGPU memory mapping, which isn't specified by TC39)?

Exactly. The only surprising thing would be that writes to the new ArrayBuffer wouldn't propagate to the GPUBuffer. Which isn't that weird, because the ArrayBuffer is no longer on the thread that issues the unmap() (which propagates the changes) anyway.

**Comment by pythonesque** [comment]
> Exactly. The only surprising thing would be that writes to the new ArrayBuffer wouldn't propagate to the GPUBuffer. Which isn't that weird, because the ArrayBuffer is no longer on the thread that issues the unmap() (which propagates the changes) anyway.

Well, I suspect "isn't that weird if you know how unmap is implemented" doesn't mean it wouldn't be confusing to people... but at least as a stopgap solution it seems fine, and it's certainly better than crashing the process.

**Comment by m-schuetz** [comment]
Instead of doing this silently, could you throw a one-time warning when a transfer does a copy instead? This seems like something you'd implement to reduce copies, but then you'd end up copying things anyway without knowing.

**Comment by kainino0x** [comment]
Yes it could definitely come with a console warning.

**Comment by kainino0x** [comment]
Editors agreed to go with this direction.

**Comment by erights** [comment]
Please see https://github.com/tc39/proposal-immutable-arraybuffer which proposes Immutable ArrayBuffers, is at Stage 2 of the tc39 process, has enthusiastic support from some implementations, and not (yet?) any serious objections. How applicable would this be to the concerns expressed above?

**Comment by kainino0x** [comment]
^ I've replied on https://github.com/gpuweb/gpuweb/issues/747#issuecomment-2560254816 (the need for read-only ArrayBuffers there is the same root issue)
