### ISSUE TITLE
Spec the texture-compression-etc and texture-compression-astc extensions

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2083]
This extensions are required for V1 because we agreed that the spec would require that implementation must always expose `BC || (ETC && ASTC)`.

**Comment by kainino0x** [comment]
Initial spec landed in #2180

**Comment by lokokung** [comment]
Re-opening because the landed spec PR does not add the necessary `BC || (ETC && ASTC)` requirement explicitly to the spec.
