### ISSUE TITLE
Consider improving variable array indexing for 'let' arrays

### ISSUE THREAD

**Issue by brendan-duncan** [gpuweb/gpuweb#2086]
Currently you can only use a variable to index an array if the array is a 'var' and not a 'let'. This is because of the memory design of SPIR-V. The current tint error messaging about this is confusing, and the spec doesn't make it really obvious this is a restriction, causing some confusion about how to fix a shader that's not compiling.

For example, this works:
```
var<private> tex: array<vec2<f32>, 4> = array<vec2<f32>, 4>(
    vec2<f32>(0.0, 0.0),
    vec2<f32>(1.0, 0.0),
    vec2<f32>(0.0, 1.0),
    vec2<f32>(1.0, 1.0));
//...    
output.v_uv = tex[input.vertexIndex];
```
But this does not:
```
let tex: array<vec2<f32>, 4> = array<vec2<f32>, 4>(
    vec2<f32>(0.0, 0.0),
    vec2<f32>(1.0, 0.0),
    vec2<f32>(0.0, 1.0),
    vec2<f32>(1.0, 1.0));
//...    
output.v_uv = tex[input.vertexIndex];
```
and produces the following error that makes it not obvious what the issue is:
**Tint WGSL reader failure, index must be signed or unsigned integer literal**

Perhaps if the array is indexed by a variable, and the array was defined by as a 'let', it could be promoted to the 'var' memory model by the shader compiler?

In the very least the spec and error messaging can be improved to make it more clear the difference between var and let arrays, and when a variable is used to index a let array that it can be fixed by making it a var.

**Comment by Kangz** [comment]
Thank you for filing this! We have seen many other developers confused by this restriction, in the Naga/wgpu Matrix chatroom, Babylon.js devs, etc.

**Comment by kvark** [comment]
My reading is that this is more of a confusion about Tint error messages than about the spec itself. If Tint error was clear, the user would know where to look in the spec. Therefore, I think this should be moved to Tint bug tracker.

**Comment by Kangz** [comment]
@kvark I've had to answer questions about this specific issue in the wgpu or Naga chatroom at least twice. This is not just Tint but a general issue with this piece of validation.

**Comment by jrprice** [comment]
> I think this should be moved to Tint bug tracker.

We have [a Tint issue for improving the error message](https://bugs.chromium.org/p/tint/issues/detail?id=1156&q=&can=2) already.

I think this issue is still valid here, as this is a frequent complaint and therefore a good place to collect this feedback.

**Comment by ben-clayton** [comment]
I will also add there has been a lot of confusion with this rule with users of WGSL internal to Google. Feedback is that this is unnecessarily restrictive, and users wish the compiler just promoted the array to storage automatically.

**Comment by kvark** [comment]
I'm afraid that such automatic promotion opens a whole can of worms. Such as - ruins the equivalence of WGSL and SPIR-V constructs, stands in the way of reasoning about the generated code, then leads to more general questions of "why do we need `let` again?" etc.
The scheme we have today is a good local maxima, oriented towards explicitness, and that's what I value in it.

@Kangz I don't think it really matters that much that people stumble on this, as long as the solution is trivial. Once they see a clear error message, it's a matter of a 3 symbol change to make this work.
And yes, Naga's errors aren't polished yet either. This doesn't mean that the language is wrong.

**Comment by litherum** [comment]
I think this is a dup of https://github.com/gpuweb/gpuweb/issues/1782
