### ISSUE TITLE
context-aware tokenization: Sometimes >> is better parsed as two copies of >  (similar for  ]] )

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2092]
Example for the `>>` case:

```
[[block]] struct B { a:  array<array<i32,2>>; } 
// That >> should two copies of GREATER_THAN, not one copy of SHIFT_RIGHT
```

Example for the `]]` case:
```
fn foo() {
  var a : array<i32,10>;
  let v = a[a[0]]; // That ]] should be two copies of BRACKET_RIGHT instead of ATTR_RIGHT.
}
```

Tint parses these provisionally as the longer token, then backtracks to split them if needed.

I think the group has already discussed this but I can't find the tracking issue.

Related: #1063 validating the grammar is unambiguous

**Comment by jdashg** [comment]
Isn't one solution to not tokenize as e.g. `]]` but instead `]` `]`?

**Comment by dneto0** [comment]
> Isn't one solution to not tokenize as e.g. `]]` but instead `]` `]`?

Yes. The unfortunate part of that is then under current rules you also have to accept those two tokens as separated by blankspace or a comment.

**Comment by dneto0** [comment]
C++14 solves this problem by saying tokenization is context-dependent.

2.2 Phases of translation, paragraph 1 step 3, says in part:

> 3. The source file is dcomposed into processing tokens (2.5) and sequences of white-space characters (including comments). 

and then

> The process of dividing a source file’s characters into preprocessing tokens is context-dependent. [ Example: see the handling of < within a #include preprocessing directive. — end example ]

Then step 7 says (emphasis added)

> 7. White-space characters separating tokens are no longer significant. Each preprocessing token is converted into a token. (2.7). The resulting tokens are syntactically and semantically analyzed and translated as a translation unit. [ Note: **The process of analyzing and translating the tokens may occasionally result in one token being replaced by a sequence of other tokens (14.2).**  — end note ]

And 14.2 is "Names of template specializations" which handles the special `>>` cases. The text there is quite detailed.




>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-vf2f-2022-02-08,09-minutes#burndown-of-httpsgithubcomorgsgpuwebprojects2">WGSL meeting minutes 2022-02-08</a></summary>



    * MM: Can we…have a builtin instead?
    * RM: I think it’s better to have C-style compat here, and that we should try to fix it, and only punt if we fail to do it reasonably well.

</details>

**Comment by kdashg** [comment]
Is this editorial?

**Comment by litherum** [comment]
Resolved: option 4. Replace `<<` with a function, and replace `>>` with a (single) function.

Names for functions forthcoming.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-03-29-minutes#context-aware-tokenization-sometimes--is-better-parsed-as-two-copies-of--similar-for----issue-2092--gpuwebgpuweb--github-">WGSL meeting minutes 2022-03-29</a></summary>



* MM: Spelled out 4 options in the issue
* AB: Like 1 better than 2.
* RM: Don’t like option 1.  C++ had option 2 for a long time then used option3 . Which is more usable. Both are fine.  Option 4 goes completely around the issue.  Option 1 reads weirdly.
* AB: Don’t think the grammar is the place to enforce clean-looking code.  If 1 is the easiest, then in favour of that.
* MM: 3 is what programmers are used to. Give them that if possible. 4 is also good.  Benefit is it makes order of operations explicit.
* DN: Really don’t like 2.  If I had to solve it quickly 1 is fine with me.  Somem time ago experimented with 3 and got stuck.
* AB: Given constexpr is coming up, want constexpr as array element count, and make sure it’s not ambiguous there.
* MM: There’s no ambiguity, just about layering.
* JB: How far ahead do you look to decide if it’s one or the other.  E.g. array length could be 4 >> 2.
    * Let a: array&lt;array&lt;f32,4>>2>> = ….;
* KG: Pushes me to 4.  Life gets a lot easier when you make your nesting syntax distinct from other syntax.
* JB: It’s fun to know operator precedence, but it’s probably not good practice to depend on it. [i.e. using a builtin function makes order explicit]
* RM: That example convinces me that 4 is good.
* MM: Make it symmetric: do all the shifts as functions.
* AB: If you make it words, you can be clear about sign extension or not.
* _Consensus: replace all shift and compound shift operators with explicit function builtins._
    * _Possibly named shiftRight, shiftLeft_
    * _Or rightShift, leftShift_
    * _Or shl shr_
    * _Or lshr ashr shl_


</details>

**Comment by dneto0** [comment]
Removing this was quite unpopular.
The argument: if a shader language has integers, you'll want to do bit shifts, usually within quite complex expressions that also have masks and bitwise-ors. Using a function obscures readability.

**Comment by dneto0** [comment]
Thanks @litherum  for the really useful taxonomy of potential solutions.

I experimented with "1. Don't have a token in the language that represents >>."  When I did that I got some ugly parse conflicts from Treesitter:

```
Unresolved conflict for symbol sequence:

  variable_decl  equal  unary_expression  •  greater_than  …

Possible interpretations:

  1:  variable_decl  equal  (multiplicative_expression  unary_expression)  •  greater_than  …
  2:  variable_decl  equal  (shift_expression  unary_expression  •  shift_right  unary_expression)

Possible resolutions:

  1:  Specify a higher precedence in `shift_expression` than in the other rules.
  2:  Specify a higher precedence in `multiplicative_expression` than in the other rules.
  3:  Specify a left or right associativity in `multiplicative_expression`
  4:  Add a conflict for these rules: `multiplicative_expression`, `shift_expression`
```

Example I made up to illustrate:

   var x = 1 > 5;

Ambiguity with parsing 1 > 5:
```
option 1:
      relational_expression
        a.k.a.  shift_expression > shift_expression
          a.k.a.  additive_expression > shift_expression
            a.k.a.  multiplicative_expression > shift_expression
              a.k.a.  unary_expression > shift_expression

option 2:
      relational_expression
        a.k.a.  shift_expression
          a.k.a.  unary_expression greater_than unary_expression
            a.k.a.  unary_expression > > unary_expression
```

The message from Treesitters says that you would need more than one token lookahead to distinguish the two options, but they're down two different arms of the relational_expression rule.  Either that or use backtracking, which breaks the spirit and rule of LR parsing.

**Comment by dneto0** [comment]
For 3.  It turns out that WGSL parsing _already_ relies on context-aware tokenization even if you remove the shift tokens.
I filed #2717 with an example showing how.

It turns out that Treesitter uses some clever techniques that go beyond textbook LR(1) or LALR(1) parsing.   The strict separation of tokenization vs. parsing described by the WGSL spec currently is actually not accurate and can't work with the current grammar and tokens listed in the spec.  Let's leave that for #2717 

If we assume relatively simple context-aware tokenization (assuming #2717 is fixed favourably), then requiring parentheses around shift operators can save the day, even after adding creation-time expressions, and creation-time expressions for array sizes. (See #2668)

e.g. this spec diff make the parser ambiguity go away:

```

-    | [=syntax/unary_expression=] [=syntax/shift_left=] [=syntax/unary_expression=]
+    | [=syntax/paren_left=] [=syntax/unary_expression=] [=syntax/shift_left=] [=syntax/unary_expression=] [=syntax/paren_right=]

-    | [=syntax/unary_expression=] [=syntax/shift_right=] [=syntax/unary_expression=]
+    | [=syntax/paren_left=] [=syntax/unary_expression=] [=syntax/shift_right=] [=syntax/unary_expression=] [=syntax/paren_right=]
```


So any time you have a shift operator, you would need to parenthesize it:  `let s = (8>>3); // like let s = 1;`
For example,   `let a: array<i32,(8>>3)>= array<i32,1>(1);` would parse. 
I've tried a version of the spec where that statement is in an example that checked by the treesitter CI.

I think I have all that correct. (Cross my fingers...)

**Comment by litherum** [comment]
> any time you have a shift operator, you would need to parenthesize it

_Any time_?? It would be illegal to write `let s = 8 >> 3;`?

I thought other places where we require parentheses for operators were only if it was unclear what the order of operations would be. In this example, it is super clear what the order of operations is, because there's only one operation.

**Comment by litherum** [comment]
Just so it's written down: one of the helpful examples listed during the last call was something like this (thanks @jimblandy!!):

```
let x : array<i32, 13 >> 2>;
```

When the compiler encounters that first `>` it may have to look ahead to see whether it's closing the array type or whether it's part of a shift.

**Comment by dj2** [comment]
Is the concern for `array<i32, 13 >> 2>` for a future with constexpr? Currently doing that shift wouldn't work because it doesn't match an `element_count_expression`. For a future with constexpr, if you wanted a shift in that position could we just require you to do `array<i32, (13 >> 2)>` to make it clear?

**Comment by ben-clayton** [comment]
> For a future with constexpr, if you wanted a shift in that position could we just require you to do array<i32, (13 >> 2)> to make it clear?

This is what the WG have been discussing. I think we're mostly on board with this (for this particular case), but as @litherum points out above, it would be unfortunate to **always** require the parentheses:

```
let x = (1 << 3); // requiring parentheses here is unfortunate
```

An ideal would be to only require the parentheses if there were ambiguity, but that might be hard to describe in the grammar.

**Comment by dj2** [comment]
Right, I was saying the same thing. Wasn't thinking about encoding it in the grammar per say, just noting that there are cases where parsing can be ambiguous and `()` is needed.

I guess the question would be, are there cases where we'd incorrrectly compile due to parsing this the wrong way? Or would it always fail with a parse error? If it could compile incorrectly that would be an issue.

**Comment by dneto0** [comment]
> e.g. this spec diff make the parser ambiguity go away:

I found that during an office hour discussion in real time. I'm not holding strongly to it.

> An ideal would be to only require the parentheses if there were ambiguity, but that might be hard to describe in the grammar.

I think this is worth pursuing.   It's probably not too hard to do.  Treesitter can check the ambiguity pretty quickly, and we can embed any samples we're concerned about in the spec, to make sure they're checked by CI.

Off the top of my head, interesting cases include

* `let x : array<i32, 13 >> 2>;`  // Jim's case
* `let x : vec2<i32, 2>= vec2(1,2);` //   bad `>=`

From the analysis behind #2735, the only concern is when one valid lookahead token is a prefix of some other token.  We should be able to generate the list of cases mechanically or by inspection.

**Comment by dneto0** [comment]
In today's WGSL meeting @alan-baker and @jimblandy were talking about jumping down low enough in the expression precedence so that you'd avoid that problem. I think I only fully understood after the meeting ended, once I looked at the expression grammar hierarchy.

Currently, the top-level expression rule has:
* three rules that are relational_expression, and short-circuiting expressions over relational expressions
* three rules that are bitwise expressions.

@alan-baker's #2668 updates the `element_count_expression` grammar rule to expand to either `additive_expression` or `bitwise_expression` (where the latter is the three bitwise expressions you'd think they are).   This avoids the relational operators.

The insight is:
* The problematic case is the expression that appears before the `>` that ends type-parameterization.
* That would only occur for relational operators `>=` and `>`.
* So use the grammar to steer that problematic expression away from those relational operators.

We can add the `>>` shift operator again.  For that problematic spot, it _still can't appear directly_ within `element_count_expression`, but it can always be added within parenthesized expressions.

That's pretty slick.  It means

*  let x : array<i32, 13 >> 2>; // Jim's case.  Would not parse.
*  let x : array<i32, (13 >> 2)>; // Parentheses makes this parse.

Even if we added ternary expressions, the would be not allowed directly by the grammar rule we'd use, so:

* let x: array<i32,  4>=3 ? 2 : 1 > = foo(); // would not parse
* * let x: array<i32,  (4>=3 ? 2 : 1) > = foo(); // would parse

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-05-minutes-(apac)#context-aware-tokenization-sometimes--is-better-parsed-as-two-copies-of--similar-for----issue-2092">WGSL meeting minutes 2022-04-05</a></summary>



* Offline:
    * Backlash against removing shift tokens.
    * David: Reconsider option 3, since #2717 shows we already rely on context-aware tokenization.  Think of a simple fix:   Require parentheses around any shift expression.
* MM: This is the same as #2717.
* DN: I don’t think we need more discussion here, since we have consensus on #2717.
* MM: What was the pushback?
* DN: Programmers really didn’t like having to use builtins instead of symbols.
* MM: Ah, the popularity argument :)
* DN: Since we have to fix tokenization anyway, let’s just fix that instead of switching builtins.
* DS: Should we revert it?
* KG: **Let’s keep it for now**, fine with having the revolt stew while we try to get the real fix.
* MOD: Would be nice not to thrash things while i18n review is happening.


</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-24-minutes#context-aware-tokenization-sometimes--is-better-parsed-as-two-copies-of--similar-for----issue-2092">WGSL meeting minutes 2022-05-24</a></summary>



* Dup?
* DN: We’d removed the >> ops, think we’re getting to the point where we should revert and put back in. Problem already present in >= so we’re in a not-fully justified state. So, revert now and hope get to good spot
* KG: Was in place we said was weird and we’d change and back and hadn’t changed back until we were sure.


</details>
