### ISSUE TITLE
GPUExternalTexture: Deal with Chroma Reconstruction

### ISSUE THREAD

**Issue by shaoboyan** [gpuweb/gpuweb#2098]
Chroma Reconstruction is the step to scale the Chroma Planes into the same size as Luminance Plane. This step ensures user fetch correct  texel value from downsampled Chroma plane with Luminance sample position. Poor Chroma Reconstruction step will cause artifacts (e.g. [this article](https://www.videoartifact.com/tips/chroma-reconstruction-internals/) presents visual difference between different Chroma Reconstruction methods).

### Chroma Reconstruction in Vulkan spec
[Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap16.html#textures-chroma-reconstruction) provides details about Chroma Reconstructions for `VkSamplerYcbcrConversion` .  Vulkan spec defines x-y offsets on chroma plane and provide two configs: `VK_CHROMA_LOCATION_COSITED_EVEN ` and `VK_CHROMA_LOCATION_MIDPOINT `.
- VK_CHROMA_LOCATION_COSITED_EVEN specifies that downsampled chroma samples are aligned with luma samples with even coordinates.
- VK_CHROMA_LOCATION_MIDPOINT specifies that downsampled chroma samples are located half way between each even luma sample and the nearest higher odd luma sample.

The following two diagrams from Vulkan spec show the relationship between unnormalized (u,v) coordinates and (i,j) integer texel positions in the luma channel (shown in black, with circles showing integer sample positions) and the texel coordinates of reduced-resolution chroma channels, shown as crosses in red.
<img width="1101" alt="COSITED_EVEN" src="https://user-images.githubusercontent.com/8126135/132790921-fa4eabe2-523c-452f-92e7-fc478bf6dc58.PNG">
<img width="1097" alt="MIDPOINT" src="https://user-images.githubusercontent.com/8126135/132791057-dec1f96e-753b-484d-9a22-697c498213d6.PNG">

Vulkan spec also defines two reconstruction method: [Explicit Reconstruction](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap16.html#textures-explicit-reconstruction) and [Implicit Reconstruction](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap16.html#textures-implict-reconstruction) with `ChromaFilter`(could be `LINEAR` or `NEAREST`):
- Explicit Reconstruction is performed as an explicit step independent of filtering.
- Implicit Reconstruction is performed as an implicit part of filtering prior to color model conversion, with no separate post-conversion texel filtering step. It takes place by the samples being interpolated, as required by the filter settings of the sampler, except that chromaFilter takes precedence for the chroma samples.

According to Vulkan spec, texel values in Chroma planes after Chroma Reconstruction step are decided by x-y chroma offsets, `ChromaFilter`, and reconstruction methods. 
There is one special case:
- x-y chroma offsets has no effect when value of `ChromaFilter` is `NEAREST`.

### WebGPU GPUExternalTexture
My understanding of the 0-copy path for GPUExternalTexture with `textureSampleLevel` will generate codes(e.g. handling 420 formats) like this:
```
[[binding(x), group(y)]] var SamplerLuma: sampler;
[[binding(x+1), group(y)]] var TexLuma: texture_2d<f32>;
[[binding(x+2), group(y)]] var SamplerCbCr sampler;
[[binding(x+3), group(y)]] var TexCbCr: texture_2d<f32>;
[[stage(fragment)]] fn fs_main(
                [[location(0)]] texcoord : vec2<f32>
            ) -> [[location(0)]] vec4<f32> {
   var luma = textureSample(TexLuma, SamplerLuma, texcoord);
   var chroma = textureSample(TexCbCr, SamplerCbCr, texcoord);
   var yuv = vec3<f32>(luma.r, chroma.rg);
   if (expand_TV_yuv_to_PC_yuv) {
      yuv = rescale_yuv(yuv);
   }
   var rgb = ConvertYUVToRGB(yuv, matrix);
}
```
In Vulkan spec the texel values after implicit Chroma Reconstructions are calculated by :

<img width="523" alt="Implicit" src="https://user-images.githubusercontent.com/8126135/132802841-6115bbfe-d6ea-42ed-b089-e5fdeb72d760.PNG">

So I think we handle Chroma Reconstruction correctly with above shader code in the case:
- x-y chromaOffsets are all `VK_CHROMA_LOCATION_MIDPOINT `,
- And reconstruction method is implicit (support all `ChromaFilter` configs).

Raise several questions for other Chroma Reconstruction cases.

### Questions
- **How to deal with explicit reconstructions?**
    - Option: Don't commit to support it. 
        - The difference between implicit reconstruction and explicit reconstruction is similar to pre-filter and post-filter the community has been discussed in [meeting-mintes-2021-05-03](https://github.com/gpuweb/gpuweb/wiki/Minutes-2021-05-03#gpuexternaltexture-api-for-video-wgsl-type-and-functions-1666).  Explicit reconstruction could be achieved through blits. (e.g. through `VideoProcessBlt` or the blit shaders). But it is not 0-copy anymore. The cost of correctness would be performance.
        - Reconstruction method is not related to video frame info. It is chosen by users. Browser could make its own strategy.(Not True, see comments https://github.com/gpuweb/gpuweb/issues/2098#issuecomment-916685928)
      
- **How to deal with `VK_CHROMA_LOCATION_COSITED_EVEN` offset?**
I think we should support it because some frames like [4:2:0-MPEG2 in Microsoft doc](https://docs.microsoft.com/en-us/windows/win32/medfound/recommended-8-bit-yuv-formats-for-video-rendering#yuv-sampling) use this offset. Possible to deal with it through coords calculation (for implicit reconstruction method). At least we could fallback to 1-copy path to handle it.
<img width="400" alt="Microsoft" src="https://user-images.githubusercontent.com/8126135/132806274-be5d1229-d5f7-4e6c-9b95-3cf789b12b55.PNG">

- **Do we need to add words about chroma reconstructions in spec ?** 
For example, if community decides not commit to support explicit reconstructions, WebGPU or WGSL spec could add words "using `textureSamplerLevel` function to read values from `external_texture` tend to have implicit chroma reconstructions".

**Comment by kainino0x** [comment]
> My understanding of the 0-copy path for GPUExternalTexture with `textureSampleLevel` will generate codes(e.g. handling 420 formats) like this:

This looks about right, but GPUExternalTexture does not bundle its own samplers for the video planes; it uses the user-provided sampler (same sampler for both planes).

However perhaps we need the filtering info to be part of the GPUExternalTexture instead of a user-provided sampler, in order to support explicit reconstruction inside the shader? (If that's possible? I don't really understand yet what explicit reconstruction does.)

> * Reconstruction method is not related to video frame info. It is chosen by users. Browser could make its own strategy.

I don't totally understand this, but Vulkan seems to say it is related to the video frame info:

> If the format of the image that is to be sampled sets VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT (...), reconstruction is performed as an explicit step independent of filtering, described in the Explicit Reconstruction section.

So certain formats do seem to force explicit reconstruction. However I don't understand why explicit reconstruction is important so I don't know how critical it is that we support it.

**Comment by kainino0x** [comment]
BTW this is a great find, thanks for doing the research!

**Comment by shaoboyan** [comment]
> (If that's possible? I don't really understand yet what explicit reconstruction does.)

My understanding for explicit reconstruction is that: user could provide a different filter, says `NEAREST`, for the Chroma Reconstruction. And user could use the sampler configs, says, min and mag to `LINEAR`, to sample from planes.
And I think that's why Vulkan doesn't care about `ChromaFilter` values for implicit reconstruction.(I think set `ChromaFilter` to `LINEAR` or `NEAREST` doesn't affect the final result, but not true for explicit reconstruction).

> So certain formats do seem to force explicit reconstruction. However I don't understand why explicit reconstruction is important so I don't know how critical it is that we support it.

My understanding is that both the VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT bit or the flag is set by user. If they don't set it, Vulkan won't do explicit reconstruction. (But some formats may not support VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT )

**Comment by kainino0x** [comment]
Hm, my reading was the opposite: implicit reconstruction is used only if `(!has EXPLICIT_BIT && !forceExplicitReconstruction)`. I'm pretty sure the presence of EXPLICIT_BIT is defined by the implementation (not by the user).

 > -   `VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT` specifies that reconstruction is explicit, as described in <https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#textures-chroma-reconstruction>. If this bit is not present, reconstruction is implicit by default.
> 
> -   `VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT` specifies that reconstruction **can** be forcibly made explicit by setting [VkSamplerYcbcrConversionCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkSamplerYcbcrConversionCreateInfo.html)::`forceExplicitReconstruction` to `VK_TRUE`. If the format being queried supports `VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT` it **must** also support `VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT`.

**Comment by shaoboyan** [comment]
@kainino0x  You're right about the `EXPLICIT_BIT`. I misunderstand this bit with `forceExplicitReconstruction`. So it seems that browser has the info to know how to handle "Chroma Recsonstructions" in the best way.

**Comment by bjjones** [comment]
>How to deal with explicit reconstructions?
Option: Don't commit to support it.

One aspect of `GPUExternalTexture` that's unclear to me is the story around who is expected to use it. At the moment I think it's the only interface available to use an `HTMLVideoElement`, but it may not stay that way. Right now GPUExternalTexture seems like it's trying to balance performance, correctness, and ease of implementation - but I think it could end up being something that either nobody wants to implement or nobody wants to use.

Right now, `GPUExternalTexture` will have less-than-100%-correct conversion for YUV formats by doing only pre-conversion filtering. I've heard anecdotally that this produces acceptable quality, but I speculate that there are users out there who do want the 100% correct conversion without having to write their own post-conversion filter. In order to get that 100% correct image, the implementation complexity goes up a lot when doing conversions in the shader.

So I'm wondering what the story is exactly for `GPUExternalTexture` - is it meant to be the end-all solution to interfacing with an `HTMLVideoElement` in WebGPU? If yes, then I suspect we'd need to support explicit reconstruction.

Alternatively, I wonder if a better plan is to label `GPUExternalTexture` as the performant, acceptable quality option and have something different for people requiring 100% accuracy. In my mind, this would be an `HTMLVideoElement` overload for `copyExternalImageToTexture`. It could use native blit functions, which would be accurate and nobody would need to get into the mess of strict YUV->RGB conversion.

**Comment by litherum** [comment]
For the uninitiated: what is explicit about explicit reconstruction? https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap16.html#textures-explicit-reconstruction doesn't seem to explain this.

**Comment by shaoboyan** [comment]
@litherum My understanding is that it is a standalone scale pass. The filter config could be different from the one samples texels in users shader.  For example, the filter uses for explicit reconstruction is "NEAREST" and user provided sampler config Min and Mag to "LINEAR".

**Comment by litherum** [comment]
> How to deal with VK_CHROMA_LOCATION_COSITED_EVEN offset?

Can't we handle this by emitting more code in the shader inside the implementation of the WGSL `sample()` call? Every external texture could include an extra value, passed to the shader in some invisible resource, which determines which offsets we should be using. (This would be conceptually similar to passing buffer lengths to the shader as extra values in an invisible resource.) The sample code listed in the top post (`fs_main()`) already includes 2 samples and a branch, so it would be surprising if adding one more branch would affect performance once.

**Comment by shaoboyan** [comment]
> Alternatively, I wonder if a better plan is to label GPUExternalTexture as the performant, acceptable quality option and have something different for people requiring 100% accuracy. 

For `HTMLVideoElement`, I think it is true. User using `HTMLVideoElement` don't have enough info to know what is 100% accurate(TBH, 100% accurate is an unclear concept). I tend  to understand their expectation should be limited to get the result that browser might do to present `HTMLVideoElement`(And, it is not accurate).  But not sure whether spec should touch it.

> Alternatively, I wonder if a better plan is to label GPUExternalTexture as the performant, acceptable quality option and have something different for people requiring 100% accuracy. In my mind, this would be an HTMLVideoElement overload for copyExternalImageToTexture.

That's an interesting proposal. Quality means no performance.  But that raises a question, shall we introduce 'quality' concept for video uploading in WebGPU spec?

**Comment by shaoboyan** [comment]
> Can't we handle this by emitting more code in the shader inside the implementation of the WGSL sample() call? 

Not 100% sure we could do this.  As I said maybe we could do this by calculating the sampling coords on Chroma plane to resolve it. I've refered Mesa's implementation, and it seems they're doing [IR level coords change](https://github.com/mesa3d/mesa/blob/main/src/intel/vulkan/anv_nir_lower_ycbcr_textures.c#L128) for this. Still double check this with Mesa team.

**Comment by kainino0x** [comment]
I agree with @jdashg. What we want in the end is to provide the shader with RGB values that are about the same as what one could get by webgl, or by putting a video element on the screen.

However I think this is still interesting to know about. For example, IIUC explicit reconstruction doesn't make sense with opaque user-provided, regular-ol' GPUSamplers. We also know that we can't do post-conversion filtering with GPUSamplers either because their parameters aren't introspectable. So, we've found two cases where it could make sense do something like merge the sampler(s) into GPUExternalTexture, so that we can (in the future) provide precision options (like "do filtering after conversion" and "use explicit reconstruction with these filters and chroma offsets" or whatever). Maybe we should consider that.

FWIW I don't think the constraints of the underlying APIs matter to us. I don't think we need to make sure we can implement GPUExternalTexture on top of Vulkan's YCbCr images. I could be wrong, but I think browser video stacks are unlikely to be (or become) compatible with Vulkan YCbCr. They're quite custom.

**Comment by shaoboyan** [comment]
> GPUExternalTexture is supposed to be "fast enough", and "as accurate as anything else" (e.g. WebGL).
> I could imagine later adding a [[precise]] annotation or similar to GPUExternalTexture samplers, or some other way to opt in to > more-correct-less-fast.

@jdashg I like the word "as accurate as anything else" (e.g. WebGL).  And I think that's my thoughts on the expectation that user use GPUExternalTexture with HTMLVideoElement (And if any artifacts, Browser will have the same bug report on presenting HTMLVideoElement too). But do we need to add sentence for it in spec to make it clear about this expectation? (e.g. Sampling from GPUExternalTexture with `tetureSampleLevel` will get texels that browser tends to use to present HTMLVideoElement on screen).


>I don't think we need to make sure we can implement GPUExternalTexture on top of Vulkan's YCbCr images.

@kainino0x Agree with that. At least it is something seems like an opt but not must.
But still worth to refer how driver implements  the conversion sample. Per my view, we tend to solve similar issues (with different constraints).

**Comment by shaoboyan** [comment]
Updates after talking with our driver team:

- **Explicit Reconstruction and Implicit Reconstruction**
    - Explicit Reconstructions is optional and the implementation is costlier. So Mesa driver doesn't support explicit chroma reconstructions.
    - Implicit Reconstruction relies on HW samplers but use individual sampler configs to ensure the correctness.
        - Because `VkSamplerYcbcrConversion ` allows user to config the `ChromaFilter`.
    - There is always a more "correct" way to reconstruct RGB values from YUV, but for that you need to know how YUV data was captured.
      
- **Deal with `VK_CHROMA_LOCATION_COSITED_EVEN` offset**
    - For Implicit Reconstruction, it could be handled by calculating a chroma uv coords bases on luma coords. 

- Using single pass to handle YCbCr->RGB is preferred by our driver team. And costlier methods are not supported by default.

My take away from the comments are:
- Implicit Reconstruction could be the default way to handle chroma reconstruction.
- All chroma offsets could be supported with injected shader in Implicit Reconstruction
- YCbCr->RGB conversion should be lightweight.

**Comment by kainino0x** [comment]
Thanks for the info! Sounds like most of the issues are resolved then.

Do you think it's important that we support separate luma and chroma filters modes?

**Comment by shaoboyan** [comment]
> Do you think it's important that we support separate luma and chroma filters modes?

My thoughts is that we'll have implicit samplers. They're not configurable by user but will occupied 1-2 binding points.  Browser will decide the filter mode for chromas.

**Comment by shaoboyan** [comment]
One thing remains:
Should spec add expectation words for `GPUExternalTexture` and `textureSampleLevel`? e.g. Sampling from GPUExternalTexture with tetureSampleLevel will get texels that browser tends to use to present HTMLVideoElement on screen

**Comment by kainino0x** [comment]
> My thoughts is that we'll have implicit samplers. They're not configurable by user but will occupied 1-2 binding points. Browser will decide the filter mode for chromas.

In the current API we don't reserve space for implicit samplers in the bindings: https://gpuweb.github.io/gpuweb/#gpu-external-texture . Instead, we use a user provided sampler for both planes.

If we bundled the sampler(s) into the GPUExternalTexture, I still think we should have a way to configure it - apps will have use-cases for both linear and nearest filtering (e.g. 3d video might use linear, whereas if the canvas and video are 1:1 in size, would use nearest).

> Should spec add expectation words for `GPUExternalTexture` and `textureSampleLevel`? e.g. Sampling from GPUExternalTexture with tetureSampleLevel will get texels that browser tends to use to present HTMLVideoElement on screen

I don't think it's possible to very tightly specify this, but a non-normative `Note:` would help set the expectation for developers/implementers.

**Comment by Kangz** [comment]
I think in terms of spec everything is good? I'm not sure I understand the discussion around Chroma-specific samplers. Can't we do everything in the injected code?

**Comment by bjjones** [comment]
> I think in terms of spec everything is good?

I think it's fine. This topic originated from some concerns internally at Intel about the quality of chroma reconstruction. Intel's media engine performs more sophisticated interpolation for chroma reconstruction than the method used for ImportExternalTexture, which is what caused the concern. After implementing the conversion, I think @jdashg's previous comment characterizes my opinion:

 > I think we should not worry too much about something that nothing else in the web platform standardizes
-------------------

> Can't we do everything in the injected code?

We _could_ inject post-conversion filtering, but also I don't know what amount of filtering would be "correct". Developers are of course able to implement their own filtering if they desire.

Here's an example result of doing the conversion with only pre-conversion linear sampling via [Rec. BT.709](https://en.wikipedia.org/wiki/YCbCr#ITU-R_BT.709_conversion):

![1x Conversion Comparison](https://user-images.githubusercontent.com/13422847/146055155-e8262f39-3d93-405d-99e9-2bcc67014c07.png)

And when magnifying in the Windows Photos app by 7x (left is original, right is post-conversion):

![1x Resolution Shader Converted 7x Detail (Linear) (Left is original)](https://user-images.githubusercontent.com/13422847/146056284-fbc8d0f2-bad0-4cb4-8ced-ba7a3b63ef42.png)


The code I'm injecting into the shader to achieve this result is: 

```
fn textureSampleExternal(plane0 : texture_2d<f32>, plane1 : texture_2d<f32>, smp : sampler, coord : vec2<f32>, params : ExternalTextureParams) -> vec4<f32> {
  if ((params.numPlanes == 1u)) {
    return textureSampleLevel(plane0, smp, coord, 0.0);
  }
  let y = (textureSampleLevel(plane0, smp, coord, 0.0).r - 0.0625);
  let uv = (textureSampleLevel(plane1, smp, coord, 0.0).rg - 0.5);
  let u = uv.x;
  let v = uv.y;
  let r = ((1.164000034 * y) + (params.vr * v));
  let g = (((1.164000034 * y) - (params.ug * u)) - (params.vg * v));
  let b = ((1.164000034 * y) + (params.ub * u));
  return vec4<f32>(r, g, b, 1.0);
}

// With:
// params.vr = 1.793;
// params.vg = 0.392;
// params.ub = 0.813;
// params.ug = 2.017;
```

**Comment by shaoboyan** [comment]
@Kangz  Yes, I think the spec part there is Ok. And from our driver teams' input, they've adopted implicit chroma reconstruction for such 1-pass conversion. If there is no mid-point position modification, no additional injection codes to address chroma reconstructions, I think.

**Comment by Kangz** [comment]
Great, thanks for the confirmation!
