### ISSUE TITLE
Support arrays of top-level structures in storage buffers

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2102]
```rust
[[block]]
struct Foo {
  foo: u32,
};

var<storage> foo: array<Foo>;
```

This is something people try to do, and it's hard to explain to them why it's not possible.
Currently, the rules for `[[block]]` prevent this case to work.
Should it be possible?

**Comment by kainino0x** [comment]
Is this a single binding to a linear-memory array of structs, or is it an array of bindings?

**Comment by kvark** [comment]
That's a great question! So we can say that `array` is reserved for cases where we have arrays of bindings. I'd be cool with this.

**Comment by dneto0** [comment]
> That's a great question! So we can say that array is reserved for cases where we have arrays of bindings. I'd be cool with this.

Yes, that's the intent.  We've been sketching what actual arrays-of-bindings could/should look like.  I'll post that.

**Comment by Kangz** [comment]
IMHO it would be nice to have a way to declare a single binding that's a pointer to an array in storage class, but that kinda conflicts with an array of bindings.

**Comment by kainino0x** [comment]
#2105
