### ISSUE TITLE
Inquiry about force running on NIVIDA GPU not on built-in one of motherboard

### ISSUE THREAD

**Issue by supcn** [gpuweb/gpuweb#2107]
Hi all, 
I'm experiencing an issue with request adapter, by using this <powerPreference:"high-performance"> option, it gives the built-in all the time,

 const adapter = await navigator.gpu.requestAdapter({powerPreference:"high-performance"});

Is it a problem related to windows operating system ?
I need to use the external GPU instead of built-in one ? any suggestions ?

thank you.

**Comment by kvark** [comment]
This isn't a spec question, it's an implementation question. And it's not even a bug, necessarily: an implementation doesn't have to expose all of the system adapters. Please file a bug on the implementation you are using:
  - https://dawn.googlesource.com/dawn
  - https://github.com/gfx-rs/wgpu

**Comment by Jiawei-Shao** [comment]
Hi @supcn,

Currently in Chromium only [the DXGI Adapter being used by other rendering components  (ANGLE) will be available for WebGPU applications](https://source.chromium.org/chromium/chromium/src/+/main:gpu/command_buffer/service/webgpu_decoder_impl.cc;l=672). I believe it will be improved in the future.

**Comment by supcn** [comment]
Hi Jiawei, thanks for your response. 

My current case, there is two adapters 
-  built-in Intel UHD graphics 630
- NVIDIA GeForce MX150

so do you mean currently in webgpu can't really use NIVDIA MX150.

**Comment by Kangz** [comment]
Yes it is a known issue and listed in the [caveats](https://hackmd.io/QcdsK_g7RVKRCIIBqgs5Hw) for the current WebGPU implementation in Chromium. If you need further support please reach out on the [Dawn matrix channel](https://matrix.to/#/#webgpu-dawn:matrix.org) or on https://crbug.com/dawn since this isn't a spec issue.

**Comment by Jiawei-Shao** [comment]
Hi @supcn,

Unfortunately yes. To let Chrome use dGPU you can set the "Graphics Performance Preference" to be "High Performance" and relaunch Chrome, then Chrome will always do rendering with dGPU.
