### ISSUE TITLE
Compute shader piplelines are not cached

### ISSUE THREAD

**Issue by qjia7** [gpuweb/gpuweb#2111]
I am working on the [TFJS WebGPU backend](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-webgpu). Currently, webgpu has a long long first inference time compared with webgl backend after we refresh the web page. Every time we refresh the page, all shaders will be re-compiled. It seems that the compute pipeline objects are not cached in the browser. So we hope you can consider this scenario and provide a cache mechanism in browser.
This issue was raised in [GPU Web meeting 2021-09-13](https://docs.google.com/document/d/1VUX3jIXK52QC8yLGxkVnlpM_GeIYviTNoKCG1jdXjFw/edit#heading=h.wirq27z13n5f).

**Comment by Kangz** [comment]
It seems to be mostly a Chromium implementation issue, however I think it would be worth having a non-normative not in the spec to say that browsers are expected to cache the result of compiling pipelines (and shader modules) to speed up warmup of pages.

**Comment by Kangz** [comment]
Since this is only a non-normative note, I'll close this issue in favor of [dawn:549](https://bugs.chromium.org/p/dawn/issues/detail?id=549) for Chromium (I don't know the respective issue in other browsers).

**Comment by juj** [comment]
Hmm, this reads a bit disappointing in philosophy. Performance-related behavior should not be non-normative, but they should be explicit and guaranteed?
