### ISSUE TITLE
Writing to different components of a vector from different invocations

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#2112]
Consider this WGSL program where different invocations within a workgroup write to different components of the same vector concurrently:
```
[[block]] struct Dst {
  value : vec4<f32>;
};

[[group(0), binding(0)]] var<storage, write> dst : Dst;

var<workgroup> tmp : vec4<f32>;

[[stage(compute], workgroup(4)]
fn main([[builtin(local_invocation_index)]] index)  {
  tmp[idx] = f32(index);
 
  workgroupBarrier();

  if (index == 0u) {
    dst.value = tmp;
  } 
}
```

This code is producing non-deterministic results in Chrome for both Metal and D3D.

The MSL spec says:

> When assigning a swizzled value to a variable, the GPU may need to read the existing value,
> modify it, and write the result back. [...]. If two threads write to different components of the vector at the same time, the result is undefined.

I haven't found similar text in the HLSL docs yet.

We should add language to the WGSL specification to surface this UB.

**Comment by alan-baker** [comment]
The simplest solution is probably to say something along the lines of "accessing a vector component affects all the memory locations associated with vector, not just the component".
