### ISSUE TITLE
Develop a visual language for the syntactic rules in WGSL specification

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#2114]
The rules in the WGSL specification need to be readable and accessible on various displays, which requires the development of a consistent visual language that can responsively act when expressed in HTML and CSS. A bonus point would be a clear expression that's easy to parse for further CI on it.

**Comment by mehmetoguzderin** [comment]
Some aspects to consider:
- Not every user of WGSL will be familiar with a constituent followed by any of "?" or "+" or "*" (or any other token really) having a meaningful impact on the allowed constructions. A great substitute could be underlying text in a way that automated webpage translators can display to readers in their own (human) language.
- I (personally) find one line with only "|" translating to rule being optional wherever it appears to make it harder for a random person to have solid reading experience.
- However expressed in the background (spec source) itself, it would read multitudes better if spec inlines token characters in a clickable (for rule reference) way.

**Comment by mehmetoguzderin** [comment]
@dneto0 Railroad diagrams sure seem to contain many primitives that can lead to a better visual representation; I will check on the accessibility (and breakability of the diagrams for responsive layout) side (at least for whether the auto-translate feature of browsers can act upon diagram annotations).

**Comment by mehmetoguzderin** [comment]
Although I was planning for screenshotting relevant sections and presenting in a better way, please check these references for possibilities:
- https://en.cppreference.com/w/cpp/language/modules
- https://docs.swift.org/swift-book/ReferenceManual/Declarations.html#grammar_import-declaration
- https://doc.rust-lang.org/reference/items/use-declarations.html
- https://github.com/microsoft/TypeScript/blob/cdebabffdc11b66bb58215ee01acd9ba8b6e7eb0/doc/spec/Grammar.md
- https://tc39.es/ecma262/#sec-tokens

**Comment by mehmetoguzderin** [comment]
(BTW, if anybody finds "syntactic rules" over "syntax rules" a bit clunky, I refer to https://books.google.com/ngrams/graph?content=syntax+rules%2Csyntactic+rules&year_start=1800&year_end=2019&case_insensitive=on&corpus=26&smoothing=3&direct_url=t4%3B%2Csyntax%20rules%3B%2Cc0%3B%2Cs0%3B%3Bsyntax%20rules%3B%2Cc0%3B%3BSyntax%20Rules%3B%2Cc0%3B%3BSyntax%20rules%3B%2Cc0%3B%3BSYNTAX%20RULES%3B%2Cc0%3B%3Bsyntax%20Rules%3B%2Cc0%3B.t4%3B%2Csyntactic%20rules%3B%2Cc0%3B%2Cs0%3B%3Bsyntactic%20rules%3B%2Cc0%3B%3BSyntactic%20rules%3B%2Cc0%3B%3BSyntactic%20Rules%3B%2Cc0 this)

**Comment by dneto0** [comment]
Those examples seem to all use something other than Bikeshed to generate the final result. 
For example, the [Rust Reference ](https://github.com/rust-lang/reference/)says it uses mdbook.

**Comment by dneto0** [comment]
... sorry didn't finish my thought ...

I have a few goals:
- keep to something that is very well integrated with Bikeshed. 
       - (e.g. [Bikeshed includes railroad diagrams](https://tabatkins.github.io/bikeshed/#railroad) already
- allow parts of the grammar to appear in different places (near the text explaining that part)
- there is an easy-to-edit single source of truth for the grammar, and that can easily be extracted by tools.  
       - Railroad diagram syntax is significantly worse for me than what we have now.

**Comment by mehmetoguzderin** [comment]
Pull request https://github.com/gpuweb/gpuweb/pull/2143 tries to establish a baseline for this dialogue without straying much further from our current syntax nor incorporating extra tools (or building an extra one to be a burden on us).
