### ISSUE TITLE
Add magic `_` identifier (and remove `ignore()`)

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#2115]
Previously:
```
ignore(atomicAdd(foo, 3));
```
Consider:
```
_ = atomicAdd(foo, 3);
```

**Comment by dneto0** [comment]
The key thing is that the assignment to `_` absorbs the value, but then that value can't be used.  The `_` is not an identifier denoting a value or storage.

This would make the situation from #2090 less awkward:

      _ = atomicAdd(...);

The `_` token _looks_ like an identifier, but it is not.
It can be modeled as a new kind of statement, or a variant of an assignment statement.

If later WGSL adds multi-value return, then this feature scales better than `ignore`:
 
       var foo, _  = something_returning_a_pair();  // only want the first component
       let _, bar, _  = something_returning_a_tripls();  // ignore multiple components

**Comment by kvark** [comment]
What confuses me here is why `let` is omitted? It seems that in the future you'd want the 
`let _ = something()` to work anyway, so does it give us anything to special-case it when it's a single thing?

I think we should do the following:
  - allow `let _ = something();` in the semantics like @dneto0 described
  - still consider just allowing `atomicXxx` (or other functions) to not capture any result - #2090

Also related to #1310 (cc @kainino0x )

**Comment by kainino0x** [comment]
+1 to `let _ =` as it doesn't look like as exceptional (even though it is still exceptional because it doesn't bind an identifier and can be used multiple times in the same scope)

**Comment by ben-clayton** [comment]
[Golang has `_` - the "blank identifier"](https://golang.org/doc/effective_go#blank) as a throwaway variable, which does not require the `var` (although `var _ int = 1` is also allowed).

I think this is magic enough that the var is entirely unnecessary, but like go, I wouldn't oppose allowing it.

**Comment by kainino0x** [comment]
To me that seems to be because Go allows both `var _ =` and `_ :=` as different (but similar) constructs? In WGSL `_ =` looks like it's assigning to a previously declared thing (like in C).

**Comment by ben-clayton** [comment]
In go, [you can assign to `_` without `:=` or `var _`](https://play.golang.org/p/YtmTMnpy_Ee):

```
func main() {
	_ = 1
}
```

This becomes important if we support multiple return values:

```
var a : i32;
// Some code that uses a
a, _ = blah();
```

If you require `_` to be declared with `var`, then this becomes a lot noisier.

**Comment by kvark** [comment]
I guess that makes sense, from the perspective I didn't consider before. "_" is a variable of any type that can be assigned into. Thus, `let` isn't needed: it's not a declaration statement, it's an assignment.

**Comment by kainino0x** [comment]
Ah, didn't realize that about Go. Both destructuring and Dzmitry's justification make sense to me.

**Comment by magcius** [comment]
Bikeshed contribution: I don't really like the ergonomics of either. Could we consider revisiting the "must use return value" rule instead?

**Comment by m-schuetz** [comment]
That's hardly better than randomly hitting the keyboard to type ```var a33r5 = atomicAdd(...) ```. Is the "must use return value" requirement really a benefit to WGSL, even for write-only operations? If it is, wouldn't it be better to explicitly specify whether a return value must be used in the function signature, [like in Rust](https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute)?

**Comment by ben-clayton** [comment]
See https://github.com/gpuweb/gpuweb/issues/2138.

Even if we remove the rule that return values must be used, we still have a couple of valid use cases for `_`

**Comment by kvark** [comment]
@ben-clayton are you talking about the case where resources are being forcibly used for the matter of deriving a pipeline layout? Please write down the example usage here for clarity.

**Comment by ben-clayton** [comment]
Yes, using `_` to:
* Keep a pipeline binding 'active', even if there are no other uses of the binding.
* FUTURE: Throwing away one or more values when calling a multiple-return value function.

**Comment by kvark** [comment]
How does it look like? Something like this?
```rust
[[group(1), binding(0)]]
var tex: texture_2d<f32>;

fn foo() {
  let _xx = tex;
}
```

**Comment by ben-clayton** [comment]
I was thinking:

```rust
[[group(1), binding(0)]]
var tex: texture_2d<f32>;

fn foo() {
  _ = tex; // Keep 'tex' binding alive, otherwise no-op
  

  var a : i32;
  // Some code that uses a
  a, _ = blah(); // blah() returns two values. We don't have a use for the first.
}

```

**Comment by kvark** [comment]
Ok, `a, _ = blah();` is definitely far-fetched. I'd expect this look like `let (a, _) = blah();` instead as more familiar.
