### ISSUE TITLE
wgsl: limit layout size of a type

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2118]
Example:

             var<private> a : array<f32, 0x40000000>;      // 4 billion-ish byte big.
             
A similar thing can happen with a bigger element type but fewer of them.

Also

           struct S {
                [[size(0xfffffffc)]] a: i32; 
                b: i32;  // byte offset overflows 32-bit
           };

We'd like to be able to reject programs with data structures that are "too big", i.e. have overflowing sizes.

We already visited this somewhat in the max-array-size discussion, and I recall the judgement being "an implementation can reject unreasonably sized arrays", and nothing was added to the spec about that. 

So these are two more cases that may fall into the same case. 

There are at least a couple of options:
* Call things like this a "spurious error" (See #1872), or
* Add another few cases to #1959 (add a limits section)

cc: @ben-clayton

**Comment by ben-clayton** [comment]
Another case to consider:

```rust
var<private> a : [[stride(8)]] array<f32, 0x20000000>; // Also 4 billion-ish byte big.
```

**Comment by kainino0x** [comment]
One reason to specify the behavior is we would be able to conformance-test it, providing security-bug test coverage for all implementations.

**Comment by ben-clayton** [comment]
*ping* - would be good to get added for v1
