### ISSUE TITLE
wgsl: support bitfield insertion and extraction

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2129]
Existing language support:
- GLSL bitfieldExtract, bitfieldInsert, bitfieldExtract (signed and unsigned versions, scalar and vector).  Operate on values, and return values
- SPIR-V: OpBitFieldInsert, OpBitFieldSExtract (signed), OpBitFieldUExtract (unsigned): scalar and vector forms.  Operate on values, return values
- MSL: inherits from C:  bitfields in structs.
- DXBC: bfi (sm5 - asm): is bitfield insertion.

Previous investigation and resolution on out-of-bounds behaviours: https://github.com/gpuweb/gpuweb/issues/288#issuecomment-493191900 

I propose WGSL should incorporate the GLSL functionality.   

Since we already have countOneBits and reverseBits, I propose we name them insertBits and extractBits.  (But I'm persuadable)

> With:
value: T
T is  integral (u32, i32, or vectors of them)
offset: u32
count: u32
newbits: T

    extractBits( value, offset,  count) :  T
              bits 0..count-1 in the result are the bits at offset..offset+count-1 in value
              (and clipping to value's bit width);  other bits are 0. 
              Component-wise when T is a vector type.

    insertBits(value, newbits, offset, count) : T 
              bits offset..offset+count-1 in the result are bits 0..count-1 in newbits 
              and clipping to bit width of 'value'); other bits are copied from value.  
              Component-wise when T is a vector type.

**Comment by dneto0** [comment]
Should these have overloads with signed offset and count?

**Comment by dneto0** [comment]
Ah, MSL has:

> T extract_bits(T x, uint offset, uint bits)
> T insert_bits(T base, T insert, uint offset, uint bits)

All OS since Metal 1.2

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-09-21-Minutes#wgsl-support-bitfield-insertion-and-extraction-2129-">WGSL meeting minutes 2021-09-21</a></summary>



* DN: Came from internal review.  Seems common enough support in underlying languages.
* JG: HLSL would use shifts?
* DN: It’s no worse than what an author would write themselves.
* _Needs spec._
* MM: Would be nice if there were a recipe for developers to follow so they could be reasonably certain that the D3D code will be “good”.


</details>

**Comment by kvark** [comment]
What's the plan for MSL before 1.2 again? Are implementations expected to generate structures with bitfields, reinterpret/copy to them, etc?

**Comment by dneto0** [comment]
> What's the plan for MSL before 1.2 again? Are implementations expected to generate structures with bitfields, reinterpret/copy to them, etc?

The polyfill is to implement with shifts and masks.   As I recall C/C++ rules allow fairly loose packing of bitfields, where the compiler does not have to put adjacent bitfields that *could* fit *actually* into the same byte or word.

**Comment by dneto0** [comment]
The extractBits(value, offset, count)  polyfill is perhaps a bit non-obvious.

Looking at the value word schematically:

         [            <-  gap   ->      |      <- count ->    |   <- offset     ]

Then the result can be computed like this, (assuming count, and offset are within valid ranges):


          ( value << gap ) >> offset

where gap = max(0, w - (offset + gap))

This works for both signed an unsigned variants of value (and the builtin).   In the signed case the right shift clones the sign bit as needed.
