### ISSUE TITLE
wgsl:  finding most-significant bit and least-significant bit

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2130]
T is  u32, i32, or vectors of them.

* GLSL:  findLSB(value T) -> i32 (or vector of i32):  Returns the bit number of the least significant bit set to
                  1 in the binary representation of value. If value is zero, -1 will be returned.
* GLSL: findMSB(value T) -> i32 (or vector of i32):  Returns the bit number of the most significant bit in the
binary representation of value.
For positive integers, the result will be the bit number of
the most significant bit set to 1. For negative integers,
the result will be the bit number of the most significant
bit set to 0. For a value of zero or negative one, -1 will
be returned.

* DXBC firstbit_hi, firstbit_lo, firstbit_shi ([docs](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbit--sm5---asm-))

> This operation returns the integer position of the first bit set in the 32-bit input starting from the LSB for firstbit_lo or MSB for firstbit_hi. For example firstbit_lo on 0x00000001 returns 0. firstbit_hi on 0x10000000 returns 3.

> firstbit_shi (s for signed) returns the first 0 from the MSB if the number is negative; otherwise it returns the first 1 from the MSB.

> All variants of the instruction return ~0 (0xffffffff in 32-bit register) if no match is found.

* HLSL [firstbitlow](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbitlow)
* HLSL  [firstbithigh](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/firstbithigh).   Has signed and unsigned overloads.  
     * But then it says:  "For a signed integer, the first significant bit is zero for a negative number."   That suggests the signed integer case is mapped to firstbit_hi.  But FXC maps it to firstbit_shi.  ([Example](http://shader-playground.timjones.io/3f3b79f0f8cd643a0bb165869ccdaad7))

**Comment by dneto0** [comment]
Dang, I hit submit before I was finished.

I see @RobinMorisset already waded through the semantic differences, as part of WSL development. https://github.com/gpuweb/WSL/issues/337 

To round things out:

* MSL has 
      * ctz: count trailing zeroes.  (Same as firstbitlow  / findLSB)
      * ctlz: count leading zeroes.   Example:  returns 32 on 32-bit 0, for example.

**Comment by dneto0** [comment]
Provisionally put this in v1.0

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-09-21-Minutes#wgsl-finding-most-significant-bit-and-least-significant-bit-2130-">WGSL meeting minutes 2021-09-21</a></summary>



* DN: Similar functionality in all backends. But the clz/findMSB functionality is framed differently. Think we need the functionality, but don’t want to have unproductive fight about it.
* MM: Can see going both ways, but what about the confusion induced in the author.  Which way _should_ I use.
* AB: Don’t need a branch to implement these. Clspv implements both ways.
* DN: Propose adding both styles: the MSL way and the GLSL-ish way.
* MM: Simplicity would be better, but ok.
* _Needs spec._


</details>

**Comment by fintelia** [comment]
Raising an issue brought up in https://github.com/gfx-rs/naga/pull/1473#discussion_r744131884: since these functions haven't yet been finalized, they should ideally **_not_** be named `clz` and `ctz` since those two are very easy to mistake for one another.
