### ISSUE TITLE
Require a render pipeline flag to enable sample-rate shading

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2133]
Rather than just turning it on silently if `[[sample_index]]` (or [`[[sample_position]]`](https://github.com/gpuweb/gpuweb/issues/1994)) is statically used by the entry point.

Suggested by @magcius in https://github.com/gpuweb/gpuweb/issues/1994#issuecomment-922559260

**Comment by Kangz** [comment]
We would need an investigation for this. It isn't immediately obvious how this would translate to Metal and D3D12.

**Comment by kvark** [comment]
Honestly, I don't think this is needed, for the following reasons:
  - you can't "disable" sample-rate shading on D3D12. if your shader uses one of the things that require it, then it will be enabled.
  - if your shader doesn't use one of those things, and it doesn't write to storage buffers, then the behavior of sample rate shading is not observable at all.

**Comment by magcius** [comment]
I meant it more along the lines that it would be a compilation failure if the bool didn't match the shader -- it's possibly "too easy" to turn it on by default, where it can have serious perf implications.

**Comment by magcius** [comment]
That's fair. Maybe this isn't necessary then.

**Comment by kainino0x** [comment]
> We would need an investigation for this. It isn't immediately obvious how this would translate to Metal and D3D12.

It wouldn't translate to any backend; it would just validate that the shader doesn't use features that trigger sample-rate shading.

**Comment by litherum** [comment]
Is there precedent for this in D3D12, Metal, or Vulkan?

**Comment by magcius** [comment]
D3D12 and Vulkan both implicitly enable it when a certain shader attribute is defined. I personally don't like shader attributes having big perf implications, especially when you just declare a given input, but this is not the only time this happens, and I don't believe possible to move all of them to PSO flags.

**Comment by kainino0x** [comment]
Resolution: no particular appetite to add a flag for this.
