### ISSUE TITLE
Make GPUDevice.lost behave like it has [SameObject]

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2147]
[SameObject] is not allowed on promise attributes (see #505 for my understanding of why), but we should still return the same Promise object when we can. This means:
- Put the .lost promise in an internal slot
- Return it from the .lost attribute
- Operate on the internal slot in the [lose the device](https://gpuweb.github.io/gpuweb/#lose-the-device) algorithm

This will return the same Promise object every time _unless_ something goes wrong in accessing the attribute.

**Comment by greggman** [comment]
I know I'm out of the loop but why does this need to return the same promise?

**Comment by kainino0x** [comment]
I don't think it's strictly that important that it return the same object, it just more tightly specifies the behavior that I think implementations are most likely to have anyway, and reduces the risk of weird interoperability issues between browsers doing slightly different things.

Also the spec as written doesn't actually make sense because it says `Resolve GPUDevice.lost with a new GPUDeviceLostInfo` but `GPUDevice.lost` is an accessor for a promise, not an actual promise object. We need to make some spec change to fix this anyway.

**Comment by greggman** [comment]
Would it make sense for `lost` to be a function `lost()` that returns a promise (like [`decode`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode))

**Comment by kainino0x** [comment]
Semantically I think an accessor makes sense. The device can only be lost once, so having just one Promise corresponds to that. (Unlike decode(), there is no operation being initiated by accessing `.lost`.) In principle I agree we could just as well return a new promise each time, but both implementation and spec wise, it would require putting every one of those promises in an internal list of weakrefs so we can resolve ALL of them when the device is lost.

**Comment by greggman** [comment]
FYI: There is no operation for `decode` either. The thing that decodes is setting `img.src`. It decodes whether or not you call  `decode`

**Comment by kainino0x** [comment]
True, I didn't think about that. Although that is still slightly different because setting src again can cause another decode, so it makes sense for decode to give you meaningfully-different results at different times. GPUDevice.lost will always return promise(s) that resolve at the same time regardless.

BTW, there's some prior art in ServiceWorkerContainer.ready helpfully pointed out by one of the editors of that spec, Jungkee, when they were helping out with WebGPU: https://www.w3.org/TR/service-workers/#serviceworkercontainer-interface
