### ISSUE TITLE
Consider removing GPUCommandBuffer.executionTime

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2156]
When we initially discussed timestamp queries for WebGPU there was some concern that they were not implementable on all Metal devices, in particular iOS devices. On these devices the only way to time the execution of commands is `MTLCommandBuffer:: gpuStartTime` and `gpuEndTime`. That's why we added `GPUCommandBuffer.executionTime` to the specification.

Two issues change the basis for this decision a bit.

In https://github.com/gpuweb/gpuweb/issues/2046 the timestamp queries are changed such that they are implementable on a wider range of Metal devices. In particular @litherum noted that they work on semi-recent Apple GPUs, including iPhone ones, meaning that iOS now will at least sometimes get timestamp query support:

>  (Above, when I say "Apple Silicon devices", I'm referring to devices which support querying - I tested and verified iPhone 11, iPhone 12, and M1.)

In https://github.com/gpuweb/gpuweb/issues/1773 @toji raised the issue that some devices (at least Vulkan and maybe also some D3D12 ones) don't expose the functionality required to produce sensible values for `GPUCommandBuffer.executionTime`. It was meant to be the always-available option, but turns out that it isn't always available.

Given that `timestamp-query` will be supported on an extended range of devices and that `executionTime` can't be supported on all device, I don't think we need `executionTime` as the "ubiquitous" time measurement API. So it can be removed.

**Comment by Kangz** [comment]
I assume @kvark meant to reply here instead of #1773:

> I did some investigation on which devices report 0 bits of precision in kainino0x/query-gpuinfo-data#1, and it appears to be Mali-GXX. They seem to otherwise not be filtered out. So the trade-off here is: if we have executionTime, we'll expose the Metal API almost directly, which is useful, and also implementable on most other platforms, except for Mali-G devices. If we don't have this API, we'll force the users to use an optional feature, and in addition they'd have to download the data by mapping the buffer.

`executionTime` is implementable as soon as you have the optional `timestamp-query`, but it can be done just as easily by a user, and the code will written at most once per project. Exposing an API unconditionally while it is not implementable everywhere seems wrong. We could also make `executionTime` an optional feature. I'm happy to write a shim for `executionTime` if you think that's necessary for developer nicety.

**Comment by kvark** [comment]
The API in #2046 requires at least macOS 11 and iOS 14, while gpu start/end times are available on all Apple devices. So if we go this route, there will be a set of Apple devices that could otherwise give you the `executionTime` but would not have a way to expose this.

**Comment by Kangz** [comment]
Why does it require macOS 11? You can implement timestamp queries on previous versions of macOS.

> So if we go this route, there will be a set of Apple devices that could otherwise give you the executionTime but would not have a way to expose this.

I'd happily trade less API surface for tiny missing reach of something like `executionTime` given it cannot be implemented on all of the WebGPU targets anyway (looking at Vulkan on Mali and potentially other chips, but also GLES in the future etc)

**Comment by kvark** [comment]
I was looking at the availability of https://developer.apple.com/documentation/metal/mtldevice/3564459-supportscountersampling?language=objc .

**Comment by Kangz** [comment]
`MTLCounterSets` are supported from macOS 10.15 https://developer.apple.com/documentation/metal/mtldevice/3081739-countersets?language=objc the `supportsCounterSampling` is something that was added in 11.0 as (at least my understanding) a decrease in features because the M1 doesn't support sampling timestamps at all locations previously used mac GPUs can.

**Comment by kainino0x** [comment]
GPUStartTime and GPUEndTime give results in "host time". I'm unclear on whether that means it's timed from the CPU or just converted to host time, but can we possibly paper over those Mali devices by implementing executionTime from the CPU?

**Comment by Kangz** [comment]
I think it means it gives you a timestamp you can compare with other CPU timestamps, but I don't think this means that we can do the same thing on Vulkan because we don't get interrupts immediately when works finishes (there can be a lot of latency), nor when it starts.

**Comment by litherum** [comment]
When viewed through the lens of this issue, there are 3 classes Metal devices:
1. Devices which do not support `MTLCommonCounterSet.timestamp`
2. Device which do support `MTLCommonCounterSet.timestamp ` but `MTLDevice.supportsCounterSampling()` only reports true for `MTLCounterSamplingPoint.atStageBoundary`
3. Other devices (aka devices which support `MTLCommonCounterSet.timestamp` and `MTLDevice.supportsCounterSampling()` returns true for other locations)

`GPUCommandBuffer.executionTime` is necessary to get timing information on the first class of devices.

**Comment by litherum** [comment]
> I did some investigation on which devices report 0 bits of precision in kainino0x/query-gpuinfo-data#1, and it appears to be Mali-GXX

How common are these devices? It would be unfortunate if a sizable chunk of devices had to report bogus answers for `GPUCommandBuffer.executionTime`.
