### ISSUE TITLE
Listing all available adapters

### ISSUE THREAD

**Issue by curved-ruler** [gpuweb/gpuweb#2160]
GPU.requestAdapter(opts) has very limited options in my opinion. Why not have instead a lister function which lists all available adapters? Most probably someone will want to address all GPUs.

**Comment by curved-ruler** [comment]
Or is it done via GPUAdapter.requestDevice(descriptor) ?

**Comment by curved-ruler** [comment]
Sorry I was confused about what an adapter was. But I still don't see if there is any way to list all devices.

**Comment by litherum** [comment]
This is intentionally impossible with the WebGPU API. The rationale is listed here: https://w3ctag.github.io/design-principles/#device-enumeration. Listing all devices would expose unnecessary fingerprinting entropy to web trackers, and it isn't actually necessary for WebGPU. We believe we've captured the meaningful decisions that web sites would make with this list by allowing the web site to [ask for](https://gpuweb.github.io/gpuweb/#dictdef-gpurequestadapteroptions) a power preference and whether they want to force a fallback adapter. (And, implementations like node.js don't need to follow the spec here.)

If you feel that there is a different decision you would be making with the list of adapters that isn't already possible via the fields in `GPURequestAdapterOptions`, please re-open this.
