### ISSUE TITLE
wgsl: plural form `attribute_lists` should be explicitly explained somewhere

### ISSUE THREAD

**Issue by cloudhan** [gpuweb/gpuweb#2184]
https://github.com/gpuweb/gpuweb/blob/52c1f0dfe2d4ccb37f700147dbf3951cc10a2fca/wgsl/index.bs#L1187

https://github.com/gpuweb/gpuweb/blob/52c1f0dfe2d4ccb37f700147dbf3951cc10a2fca/wgsl/index.bs#L1244

https://github.com/gpuweb/gpuweb/blob/52c1f0dfe2d4ccb37f700147dbf3951cc10a2fca/wgsl/index.bs#L1254

etc. (9 of them) all link to [attribute_list](https://gpuweb.github.io/gpuweb/wgsl/#syntax-attribute_list). The text of the link should be corrected.

**Comment by mehmetoguzderin** [comment]
@cloudhan yes it does, as follows:

| "Informal" Text | "Formal" Grammar |
|-|-|
| attribute_list | attribute_list |
| attribute_lists | attribute_list+ |
