### ISSUE TITLE
Streaming implementations and indirect draws/dispatches

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2189]
Consider an implementation of WebGPU which is streaming commands one-by-one to the backend API. Imagine the implementation encounters a program like this:

```
let commandEncoder = device.createCommandEncoder();
let computePass = commandEncoder.beginComputePass();
    populateIndirectBuffer(computePass, indirectBuffer);
computePass.endPass();
let renderPass = commandEncoder.beginRenderPass(renderPassDescriptor);
    renderPass.setStuff(...);
    renderPass.drawIndirect(indirectBuffer, 0);
renderPass.endPass();
commandEncoder.finish();
```

If the implementation is streaming commands one-by-one to the backend API, by the time it hits the `dispatchIndirect()` call, there's no place for it to insert the compute shader for the validation checks.

- It has already [been demonstrated](https://github.com/gpuweb/gpuweb/issues/2046#issuecomment-909981545) how silently splitting passes is harmful, so we shouldn't split the render pass to insert the validation compute shader just before the `drawIndirect()` call.
- We can't insert the validation compute shader between the two passes, because we've lost our opportunity - we've already recorded the subsequent commands. We're streaming directly to the platform API; we can't back up and rewind.
- We can't insert the validation compute shader before the entire command buffer (or "command encoder" in WebGPU parlance) because that's too early - the indirect buffer hasn't been populated yet, so there's nothing that can be validated at that point.

I believe we already have requirements saying that an indirect buffer cannot be populated in the same pass that it is consumed. We should strengthen this requirement to say that an indirect buffer cannot be populated in the same command buffer ("command encoder") that it is consumed. That way, validation on any indirect buffers can be done by inserting a command buffer just before the current command buffer is submitted.

**Comment by litherum** [comment]
> This isn't quite a direct comparison

You're right that it's not a direct comparison, but it is historical evidence. It's enough to implement on. Browser drawing code gets transformed into Metal command buffers just like WebGPU drawing code gets transformed into Metal command buffers.

> That performance result is assuming a large number of passes (50), with every single one containing an indirect call. I don't suspect that's very realistic.

I disagree. I think most authors won't put a lot of care into their usage flags, and will end up spraying a bunch of usages on stuff, because that's how to get the implementation to stop throwing errors. If authors put `INDIRECT` on their buffers, every pass will cause a split. It's totally reasonable to have 50 passes in a single command buffer.

> It's conceivable that this proposed restriction would not be very intuitive to developers

After further reflection, I don't think this is that unintuitive compared to usage scopes and usage flags. "A buffer boundary to give the implementation a place to check stuff" doesn't seem significantly more complicated than usage scopes.

**Comment by kainino0x** [comment]
> If authors put `INDIRECT` on their buffers, every pass will cause a split.

Wait, maybe I'm misunderstanding, but shouldn't a split only be needed for render passes that actually contain a draw(Indexed)Indirect call? I don't think it cares about buffers used in any other way.

**Comment by kainino0x** [comment]
> Wait, maybe I'm misunderstanding, but shouldn't a split only be needed for render passes that actually contain a draw(Indexed)Indirect call? I don't think it cares about buffers used in any other way.

FTR: I was misunderstanding, I wasn't fully considering all commands were sent to Metal immediately. Myles was talking about this suggestion:

> * You don't need to split all command encoders, you only need to split before the first render pass since something wrote to a storage buffer that are also indirect buffers. This heavily reduces the number of splits you need to do. (if any)

**Comment by kainino0x** [comment]
Resolution: Investigate solving this by requiring a flag ("uses indirect") to be passed on a render pass in order to use indirect draws. This flag indicates that a command buffer split is needed prior to that pass, IF any buffer with the INDIRECT usage has been written since the last command buffer split.

**Comment by kainino0x** [comment]
Spitball: wonder if we could require that flag ONLY if there's been a write to an INDIRECT buffer. Complicates the validation but means (slightly?) fewer applications would need to worry about the flag. Guessing this would probably not be helpful enough to be worth it (and could be a post-v1 improvement).

**Comment by litherum** [comment]
Thinking about this more: I think there's a similar concern about index buffers. Ideally, we wouldn't eagerly preprocess index buffers every time they were written to. Ideally, we'd only preprocess index buffers if they were actually used as an index buffer. This would solve the problem of an author spraying INDEX usage on all their buffers for no reason.

**Comment by Kangz** [comment]
Can you detail more what preprocessing of Index buffers you plan to do?

**Comment by kainino0x** [comment]
The spec is designed so that no preprocessing is needed on index buffers, but there are several possible implementations some of which use preprocessing:

- Always do vertex pulling on Metal and process indices from the index buffer in the vertex shader. (Dawn does this.)
- Transform all drawIndexed calls into drawIndexedIndirect. Use a compute pre-pass to validation that all values in the index buffer are in the safe range and zero-out the draw call if not. (#320)
- Use a compute pre-pass to make a copy of the index buffer that is clamped to the safe range.

**Comment by kvark** [comment]
There is a lot of interesting thoughts here, and the numbers provided by @litherum are surprising.
I wanted to comment on "spraying" first:
> This would solve the problem of an author spraying INDEX usage on all their buffers for no reason.

I don't think we should design for a world where people ignore the usage flags and spray them unnecessarily. We've discussed previously how texture STORAGE flags can disable color compression for render targets. We have these usage flags precisely so that we can optimize based on what user needs, so lets assume a "good" user here, and take this opportunity to optimize our implementations.

**Comment by kvark** [comment]
@litherum I looked for some answers on why multiple command buffers are slower - https://github.com/gfx-rs/wgpu/issues/2207#issuecomment-976860391.
On Intel GPU, when recording commands, encoder initialization seems to be omitted if there was already an encoder on this command buffer.
And down the line, when executing on actual GPU, multiple encoders from the same command buffer are coalesced together.

It's not clear if these optimizations would make as much difference in a more realistic use-case.

In any way, the proposal to have a "uses indirect" flag on render passes is tentatively 👍 . We can ignore it if we keep doing what we are doing now, but it would be nice to ensure that the validation code for this is sane.

**Comment by austinEng** [comment]
I had an idea for running compute-based validation work before a render pass that doesn't involve splitting command buffers at all. Here's the general idea:

Before every render pass, you create a compute encoder which performs [`[MTLComputeCommandEncoder executeCommandsInBuffer:indirectBuffer:indirectBufferOffset:]`](https://developer.apple.com/documentation/metal/mtlcomputecommandencoder/2967418-executecommandsinbuffer?language=objc). Let's call it `icb` and the MTLBuffer holding the range `icbRange`. Then, end the compute encoder immediately and begin the render pass.

The implementation keeps a separate MTLBuffer around to hold validated indirect buffer commands. Let's call it `validatedIB`. As the implementation encounters `draw*Indirect` calls in the render pass, using a separate "pre-flight" MTLCommandBuffer, it encodes copies of the indirect parameters from the indirect calls into `validatedIB`.

(`icb`, `icbRange`) points initially to nothing, but it expands as needed to handle validation for `draw*Indirect` calls in the render pass. In practice, we need just a single dispatch to validate all of the contents of `validatedIB`. It'll consume an array of index/offset/type information so it knows which parameters to validate from `validatedIB`. So, we don't need to make a MTLIndirectCommandBuffer with a huge maxCommandCount.

No command buffer splitting is necessary, at the additional cost of:
  - one extra pre-flight MTLCommandBuffer submitted first - ok there's kinda a "split" but it's O(1) for N render passes.
  - a potentially empty compute pass before each render pass
  - an indirection though an indirect command buffer for the validation
  - one MTLBuffer to hold the range information and validated indirect parameters. (`icbRange` and `validatedIB` can be the same buffer). Regardless, this is O(1) for N render passes.

**Comment by kdashg** [comment]
I'm reminded of our early discussions about the potential usefulness of optional eager barriers/transitions.
If we supported some `transitionBuffer` to eagerly transition (a portion of) a buffer to an indirect-command usage/state early, that could re-streamline things, assuming that the user doesn't get this wrong, and cause us to have to split to do a late transition/fixup-pass anyway. (Happy to warn in this case, when optional transitions are wrong)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-02-23#streaming-implementations-and-indirect-drawsdispatches-2189">WGSL meeting minutes 2022-02-23</a></summary>



* KR: there's something in ANGLE's Metal backend where it enqueues an empty command buffer and fills it in later. Effectively goes back in time. Would this not work?
* KN: issue - may have to split at the beginning of each render pass. Split one WebGPU cmdbuf into many Metal cmdbufs. Think there's a way to reduce the number of splits - that's the way I'd go. But imp't to Apple.
* KG: if you had a transition that you inserted, converting something writable to being indirect source - happened outside render pass - that's when we would do it.
* KN: yes, force users to split their own cmdbufs.
* KG: or even offer to let them batch these. Goes back to voluntary barriers. Is there a reason we'd want to give people the option to eagerly transition things? This would be an example.
* KN: can be in the command encoder. Switch this buffer from write to read.
* KG: would be cool to put this in the compute pass.
* KN: can happen with draw calls too. Can be in the compute pass, or top-level encoder for render. Maybe going in that direction's worthwhile? A bit breaking, but don't think it's a huge barrier for people.
* KG: breaking API or precedent?
* KN: the API. And introducing a possibly complex concept.
* KG: will try to write this down - it'd be voluntary, wouldn't break the API, just tell you I'll be doing indirect calls from this.
* KR: not to be contrary but if it's optional then most developers won't get it right.
* KN: can imagine some engines would have trouble - wouldn't know they have to do this before starting their render pass. But it's an option. They can always split their command buffers before the render pass so they can insert it.


</details>

**Comment by litherum** [comment]
> Can you detail more what preprocessing of Index buffers you plan to do?

Oh, sure, the idea is just to build a data structure that allows for efficient querying of "what is the maximum value in a particular range." Populating index buffers would probably be less common that using the index buffer, so it would be valuable to have an efficient way of answering the question "if I issued a draw call with this range of this index buffer, would that index off the end of the vertex buffer?"

**Comment by kainino0x** [comment]
Idan proposed one data structure design in the doc linked from #320.

> Here is one potential implementation we believe would benefit from being able to discard these calls: [Google doc](https://docs.google.com/document/d/1Vwlt6tN5-Xc5Es2aOKJSvM7H6ICEXMLf23M4QCKmS4U/)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-03-09#streaming-implementations-and-indirect-drawsdispatches-2189">WebGPU meeting minutes 2022-03-09</a></summary>



* MM: (Recap)
* KG: Reminds me of the optional barriers. Allow stating beforehand that you want to use it as an index buffer, before the render pass starts. However, if a user did get this wrong, we are back to where we are now: We might even have to throw out a partially-recorded command buffer.
* MM: Austin had a fairly genius idea (though not positive it will work yet) where before every render pass you execute an indirect dispatch. At the time you enqueue it, you don’t know what it’s going to do, but decide later during encoding of the render pass. Reason I’m not sure it will work is indirect command buffers for compute don’t exist on all Mac devices. So have to use indirect dispatches. Can I fit it into a predefined set of dispatches?
* **(out of time, continue next time)**


</details>

**Comment by litherum** [comment]
> Before every render pass, you create a compute encoder which performs

Just to restate what I believe the proposal is: let's consider the potential solution where the web app says "please start a render pass now" and the browser responds to that by saying "okay, first I will open a compute command encoder, encode some stuff into it, close it, then open a new render command encoder for you." Importantly, not everything encoded into the compute command encoder needs to be fully-formed at the time it's encoded; e.g. buffers attached to any dispatches may have their contents set later. More details on this are below.

First, a few observations:
1. According to the [Metal Feature Set Tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf), no Macs support compute indirect command buffers. So they definitely can't be required in any solution. This may be okay, though, because regular indirect dispatches may be sufficient.
2. If we want to use indirect dispatches, we have to do it in a way where the _number_ of dispatches is known at the beginning of the render pass we're validating.
3. Similarly, the shader, and the pipeline state we're using has to be fully created at the beginning of the render pass we're validating. (The validation prepass has to call `setComputePipelineState()` with a valid pipeline before encoding any `dispatchThreadgroups(indirectBuffer:)` calls.
4. We can require argument buffers tier 1, but we can't require argument buffers tier 2. This means that if we want to attach a bunch of resources to the validation dispatch, then at the time the render pass starts, we don't need to know _which_ resources the validation dispatch will need, because the contents of the argument buffer can be populated later. We do, however, need to know _how many_ resources will need to be attached, because we need to know A) the allocation size of the argument buffer, and B) the argument buffer's `struct` definition inside the shader needs to say something like `array<device Foo*, 17>`.
5. The only draw calls that need to be validated in this fashion are draw calls which have their index or indirect buffers populated by a previous command in the command buffer. If the draw call uses an index or indirect buffer populated by a different command buffer, then there's no problem; we can just make a second command buffer and encode whatever validation commands we need into it, and submit it just ahead of the command buffer the web app is telling us to record to.

There are a few different use cases that this approach would need to handle:
1. Preprocessing the contents of index buffers, to build a segment tree to accelerate range-based max() queries
2. Validating indexed non-indirect draw calls
3. Validating indirect draw calls (both indexed and non-indexed)

Let's discuss each of these in turn.

1. Preprocessing the contents of index buffers generally involves building a tree - albeit flattened into a buffer. The computation of each node in the tree will depend on the values below it in the tree. Assuming that a single thread will write the value of a single node in the tree, this means that the generation of each level of the tree needs to be surrounded by barriers. The scope of the barriers have to be wider than a threadgroup - e.g. the computation of the root of the tree will require the threadgroup that writes it to wait on the threadgroup that produced its rightmost child. The only way to accomplish this kind of barrier in Metal is to issue another `dispatch()` command - we don't have device-level barriers as instructions in shaders. This means that the number of `dispatch()`es will need to be equal to the number of levels in the tree, which is a function of the size of the index buffer (actually, the index buffer's modification).

Because the number of `dispatch()`es is variable, we can't do it just-in-time lazily. Instead, the only way this would work is if its done eagerly, immediately after the index buffer is modified. So, the way this would have to work is, just after closing a pass that modifies an index buffer, we immediately open a render pass to build the segment tree for that index buffer. (If the work that populated the index buffer was compute work, then the two compute passes can be coalesced.)

One repercussion of this is it means multiple modifications of the same index buffer will cause wasted work. Ideally we'd build up the segment tree just before the index buffer actually gets targeted by a draw. It sort of depends on A) how deliberate applications are with their specification of buffer usages, and B) how often applications populate index buffers without using them in a draw call. We'd have to measure this to see if it would be harmful.

2. Indexed non-indirect draw calls will need to be promoted to indirect draw calls because the code that performs the bounds check needs to run on the GPU, and if the bounds check fails, that GPU code needs to be able to no-op the draw call. The mechanism for this is for the validation compute shader to write a 0 into an indirect buffer.

Every draw call specifies its own index buffer range, so each draw call needs its own validation. If one draw call uses one region of an index buffer, and another draw call uses a different region of the index buffer, and the regions are disjoint, we can't just union the regions into a single large region - there could be indices in between the two regions which would be out of bounds, causing the two valid draw calls to erroneously fail.

One natural way to handle this would be to assign every draw call its own thread. But, at the beginning of the render pass, we don't know how many draw calls there will be, so we don't know how many threads the validation dispatch should use. But that's probably okay - we can just make the validation dispatch _itself_ be indirect. That way, the code that records the render pass can count draw calls, and populate the indirect parameters of the validation dispatch, and set the number of threadgroups to be large enough such that every draw call gets its own thread. So that's cool.

Next, the shader needs to have access to the segment tree which were built for each of the index buffers which were modified earlier in the command buffer. Luckily, we can know how many of these there are (we can just count them). So, we can allocate an argument buffer that holds that many pointers, and set each pointer to point to the index buffers' segment tree. The shader itself needs to have this count baked into it, but this count can be a function constant. Therefore, when the render pass begins, we can specialize the shader to hold an array of the correct number of resource pointers, and then build a new compute pipeline state from the specialized shader. This is something we'd have to measure to determine if it's too slow.

The biggest problem, though, is the validation needs access to the indirect parameters themselves. When we record the draw calls, we can replace them with indirect draws, but those indirect calls have to explicitly state which indirect buffer, and the offset within that buffer, the parameters will lie at. Also, once those buffers are named, they can't be changed. This means that we have to create a temporary buffer to hold all the indirect parameters, but we have no idea how big to make it, because it needs space proportional to the number of draw calls.

If we run out of space, we can allocate more temporary buffers, but now we've violated the requirement where the validation code needs to know _how many_ buffers will be attached to it. No matter what size we pick for our temporary indirect-parameter-holding buffer size, the render pass can issue more draw calls than will fit in it, and now the validation shader has to have access to an unknown number of indirect-parameter-holding buffers. This requires tier 2 argument buffers, which we can't require.

3. If the web application itself directly uses indirect buffers, we need to validate them, and validation requires writing into the indirect buffer. We can't just clobber the data inside the author's indirect buffers, so we have to copy them to our own temporary buffer. We can use the same tricks as above to copy all the parameters, but we still suffer from the same problem as above - when we're recording the render pass, we have to specifically state the temporary buffer, and offset into it, where the indirect parameters will get copied into, but we don't know how big to make that temporary buffer, and we can't allocate a variable number of temporary buffers because of the above concerns.

So, I think this approach will _almost_ work, but it has one problem (variable number of temporary buffers are required) that I think is a dealbreaker.

**Comment by austinEng** [comment]
Brainstorming... Overall, I recognize the variable number of temp buffers is a problem, so I'm thinking about how to fix that.

### Could we use a _render_ indirect command buffer?

Unlike compute, render indirect command buffers are available on MacOS. The huge benefit is that the extra indirection resolves the problem of needing to know the buffers to validate ahead of time. We can just add extra validation commands to it as needed. We can run the validation inside a vertex shader instead of a compute shader and still write zero to the (shadow) indirect storage buffers to zero out any invalid draws calls. But, we need to know how large to make this render indirect command buffer (cause maxCommandCount). And, problem is, there is still a variable number of buffers because there are an unknown variable number of draws. 

Let's see if we can bound the number of buffers. Ultimately, that means we need to bound the number of draw calls. Say we had 1 billion draw calls. drawIndexed has 5 uint32_t parameters, so 5 * 4 * 1 billion = 20 gigabytes. The point of this illustration though is that **even if** we knew the future of all the draws the application would encode, we still need to transform the draws into indirect draws, and so we'll ultimately end up hitting some memory-related cap where the implementation will OOM.
Back to our hypothetical 1 billion draw commands. Let's split these over 1000 indirect MTLBuffers so that each one holds 1 million draws. That's 20Mb per temporary MTLBuffer which seems reasonable. So, that means the number of variable temporary buffers that we have is at most 1000.

And, that means the render indirect command buffer can be sized ahead of time to hold `j*1000` validation commands (where `j` is some other constant which depends on how the validation works). This sounds like a pretty manageable not-too-huge size to me. If we want to use all 128Gb of the unified memory on the M1 ultra to hold the indirect draw parameters, we need about 6x more space - that's about 6000 validation commands (also reasonable).

**Comment by litherum** [comment]
> According to the [Metal Feature Set Tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf), no Macs support compute indirect command buffers.

This isn't quite accurate. Neither the `MTLGPUFamilyMac1` nor `MTLGPUFamilyMac2` column report to support compute indirect command buffers. However, the the `MTLGPUFamilyCommon2` and `MTLGPUFamilyCommon3` columns _do_ report to support compute indirect command buffers. So if a Mac is both `Mac2` and `Common2` then it _will_ support compute indirect command buffers.

If we could use compute indirect command buffers, then we're a little closer to solving the problem, but I don't think we're quite all the way there. We can use [this](https://developer.apple.com/documentation/metal/mtlcomputecommandencoder/2967418-executecommandsinbuffer?language=objc) to say "execute some number of commands from an ICB, and the number of commands to execute is stated in a buffer, which can be filled in later."

But, it doesn't get around the problem of not being able to know how big of an ICB to allocate, just like you say above "But, we need to know how large to make this render indirect command buffer (cause maxCommandCount)." ICBs can't record indirect dispatches inside of them, so the size of the ICB has to be proportional to the number of draw calls inside the render pass.

We could certainly pessimize, as you suggest, but this is pretty scary. We'd have to measure its feasibility. You mention that attaching 1000 buffers to a validation shader is reasonable, and having each of those buffers be 20MB is reasonable. I'm concerned about those numbers - 1000 is quite a large number of resources to bind, and allocating 20MB at a time of _just overhead_ seems like a lot.

The thing that makes me hesitate here is that almost all render passes will use way way fewer draws/resources than that, so we're paying a pretty significant price when it will almost never actually be necessary.

If only the application could actually tell us "we're never going to use more than X draw calls in this render pass" then we could allocate everything accordingly, and it would work out great.

_OR_ if we could say "you're not allowed to populate an index buffer / indirect buffer in the same command buffer where it's consumed" then we could just record 2 (variable-length) command buffers at the same time (one for validation and one for the user's draw calls) and then dispatch them one after another" then that would work out great too.

**Comment by litherum** [comment]
> So, the number of resources that the copy dispatch will need access to is equal to the number of all indirect buffers which are alive, which could be huge.

The more that I think about it, the more scary this is.

**Comment by litherum** [comment]
Resolution: Render pass descriptor will have a new `maxDrawCount` value with a default value of, say, 50 million.
