### ISSUE TITLE
Case for existing GLSL on the Web

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#219]
Current WebGL developers constitute a large part of our target audience. While we've been putting emphasis on the value of supporting existing HLSL shaders (by WHLSL), we haven't nearly considered (except for the last sentence of #44) the value of supporting existing GLSL. I believe we could produce a GLSL extension (by following [GL_KHR_vulkan_glsl](https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt) steps) that modernizes GLSL to the point of being usable with WebGPU:
  - require binding layouts, e.g. `layout(group = 1, binding = 2) uniform texture2DArray t_Shadow;`
  - separate bindings for samplers and textures, joined only at the place where sampling happens, e.g. `sampler2DArrayShadow(t_Shadow, s_Shadow)`
  - carefully define the behavior for out-of-bounds accesses and other sources of confusion

Having the developers rewrite sampler bindings and annotate the uniforms/storage buffers with the explicit group/binding semantic is significantly easier than rewriting all the shader code into the unknown syntax. I imagine, in a lot of cases the porting could be done with just a few preprocessor branches in the header files:
```glsl
#ifdef WEBGPU
layout(group = 1, binding = 2) uniform texture2DArray t_Shadow;
layout(group = 1, binding = 3) uniform samplerShadow s_ShadowImpl;
#define s_Shadow sampler2DArrayShadow(t_Shadow, s_Shadow)
#else
uniform sampler2DShadow s_Shadow;
#endif
```

Imagine ShaderToy as a potential customer of the API. Since they control the bindings, they can technically re-implement the backend in WebGPU without breaking any of the shaders uploaded by the users.

Now, as to how we can support (Web)GLSL. If the implementation digests WHLSL, we'll need some sort of a translation WASM library doing the work. Presumably, we'd have the user providing the extra information on what bind groups and indices the resources are, including the separation of textures and samplers. Would this be on your roadmap to implement for WHSL ecosystem?

If we digest WebSPIRV, then we can have a quick start by using the existing GLSL to SPIRV converters, like [glslang](https://github.com/KhronosGroup/glslang). We'd just host it as a WASM module and make sure that the produced SPIRV is compatible with WebGPU, or otherwise caught by our validation.

**Comment by Kangz** [comment]
Of note @kainino0x made a WASM version of shaderc a while ago that was used to successfully compile GLSL to SPIR-V for demos of our nxt-chromium prototype.

The import was [here](https://github.com/Kangz/nxt-chromium/blob/master/_NXT_demos/webglnext.html#L37) and the calls to the compiler [here](https://github.com/Kangz/nxt-chromium/blob/master/_NXT_demos/webglnext.html#L67).

**Comment by grorg** [comment]
Discussed at the [11 Mar 2019 teleconference](https://docs.google.com/document/d/1SPOtaPHQGInj4va33z2SpvRgVOrrCIHuTDiGKJSFQm8/edit)

**Comment by kvark** [comment]
Closing as we decided to go with WGSL
