### ISSUE TITLE
Removing the COPY* texture usages

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2196]
Following on today's call I took a look at the open source Vulkan drivers to see what's the impact of adding both the `COPY_SRC` and `COPY_DST` usages to all textures unconditionally (so we can remove them from the spec). What I found was that:

 - On Intel `COPY_DST` caused the texture to be allocated as a render target so that it could be rendered into to perform copies.
 - On AMD `COPY_SRC` makes the depth textures "texture color" compatible, which means that the hierarchical Z compression loses a little bit of precision.

IMHO these look like tiny drawbacks and we could take them, although we should check how much worse things get on AMD.

**Comment by jdashg** [comment]
I would prefer we leave these in for V1 and, as time allows, see if we can't make them optional in a revision of the spec.
It's a cool idea that we might not need them, but given that there's signs that point to their value to some APIs, it's most efficient for us to ship conservatively (on the side of perf hints) and iterate.

**Comment by Kangz** [comment]
Ok, it seems there isn't enough support to have this suggestion move forward. Happy to close the issue.

**Comment by Kangz** [comment]
And I just realized this was still under discussion in the group maybe? Feel free to reopen.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-01-19#triage-the-issues-without-milestones-timebox-15m">WGSL meeting minutes 2022-01-19</a></summary>



* #2196 removing copy texture usages
    * KG: I removed these - why?
    * MM: we thought copy usages were free, so could be applied to every buffer and remove it from API surface.
    * MM: are we trying to determine whether this is possible for V1.
    * KG: would be stranger if we needed them after we removed them.
    * MM: I'm saying we should determine result of this issue pre-V1.


</details>

**Comment by kvark** [comment]
We touched on it in the editors meeting and decided to close.
It's clear from the driver code links that this affects performance.
Besides, if we remove them now and re-introduce something like this in the future, then this would be a "reverse" flag with the meaning "I never want to copy into it", this would be inconsistent with all other usage flags.

**Comment by kainino0x** [comment]
https://github.com/gpuweb/gpuweb/wiki/Minutes-2021-11-03#removing-the-copy-texture-usages-2196
