### ISSUE TITLE
Consider validating stripIndexFormat at draw time.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2199]
While using the API during the exploration week, a couple folks run into the fact that `stripIndexFormat` needs to be specified for strip topologies even when the pipeline isn't going to be used for `drawIndexed*`, which was confusing. We could consider making this a draw-time check. Performance-wise it wouldn't be any slower because we already check the index formats match (so an undefined internal format could be used for no additional cost). But it makes errors happen a bit later, at the benefit of being more clear.

**Comment by kainino0x** [comment]
I'm guessing that by far the most common reason for non-indexed tristrips is for drawing quads (a tristrip is natural and lets you draw 4 points instead of 6). Which seems common enough that it would be _nice_ to smooth over.

My only concern with doing this validation at draw time is what if we find ourselves _not_ needing to validate the strip index format matches, but still needing to validate that there is one. Then the validation won't be free anymore. I don't foresee that happening though.

Another solution to this would be to just default `stripIndexFormat` to `"uint32"`. I know we previously decided not to do that, but maybe it's worth the ergonomics in these cases.

**Comment by kvark** [comment]
If there is indeed no perf cost to this, I agree we should move it to draw time. We check the index format at draw time anyway, so trying to enforce the stripIndexFormat early doesn't give us anything.

**Comment by Kangz** [comment]
I think we can resolve offline. @litherum any concerns? If there's none I'll make a PR.

**Comment by litherum** [comment]
It sounds like the proposed change is:

1. Delete this text in [validating GPUPrimitveState](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuprimitivestate):

> If `descriptor.topology` is "line-strip" or "triangle-strip", descriptor.stripIndexFormat is not undefined

2. Change this text in [valid to draw indexed](https://gpuweb.github.io/gpuweb/#abstract-opdef-valid-to-draw-indexed)

from:
> If `stripIndexFormat` is not undefined, `encoder.[[index_format]]` must be `stripIndexFormat`.

to:
> `encoder.[[index_format]]` must be `stripIndexFormat`.

If so, this sounds good to me.

**Comment by litherum** [comment]
Here's the behaviors today, I think:

Pipeline | `Draw()` behavior | `DrawIndexed()` behavior
-|-|-
List with index format | Index format is ignored | Validate index format matches last call to `setIndexBuffer()`
List without index format | A OK | Index format from last call to `setIndexBuffer()` is used
Strip with index format | Index format is ignored | Validate index format matches last call to `setIndexBuffer()`
Strip without index format | Fail at pipeline creation | Fail at pipeline creation

I believe this change would turn this into:

Pipeline | `Draw()` behavior | `DrawIndexed()` behavior
-|-|-
List with index format | Index format is ignored | Validate index format matches last call to `setIndexBuffer()`
List without index format | A OK | **NEW** Fail at draw call time
Strip with index format | Index format is ignored | Validate index format matches last call to `setIndexBuffer()`
Strip without index format | **NEW** A OK | **NEW** Fail at draw call time

**Comment by Kangz** [comment]
Yes, this looks correct.
