### ISSUE TITLE
Literal unification

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#2200]
We think golang has a nice model for literals that WGSL should mostly adopt; however, we don't think we have to get all the way there in one step. This issue is a set of proposals that build on each other. We could stop at any particular proposal and take it and the preceding proposals.

## 1. Drop the requirement for the `u` suffix on unsigned literals

The specification would introduce the concept of literal type classes: integral and floating. Both would be conceptually infinite precision. This step does not provide conversion between type classes like golang (e.g. `var x : i32 = 1.0` is invalid). It would, however, drop the necessity for specifying the `u` suffix on `u32` literals. Instead of the suffix, integral literals would allow for implicit conversion (e.g. `var x : u32 = 1` is valid). The context (e.g. declaration or function parameter) would be used to infer the type. If the inference could be made (e.g. `var x = 1`), the default type inference would "decay" the type to `i32`. Literal value could be used as context in some corner cases if no other information is present (e.g. `var x = 0x80000001` would be `u32`).

For symmetry, introduce `f` and `i` suffices to unambiguously type `f32` and `i32` literals respectively. Use of a suffix would type the literal explicitly (e.g. `var x = 1u` is a `u32` and `var x = 1f` is `f32`).

Remove negation from literal tokenization and introduce a proper unary minus. This allows expressions like `a-5` to be parsed correctly.

## 2. Allow literal arithmetic ops of the same type class

For example, `1 + 1u` is allowed, as is `some_u32 + 1`. Final type inference works as in 1.

## 3. Allow promoting integral literals to floating literals

The type would be based on the use context (e.g. declaration or function parameter). Builtin function overload resolution does not get special logic (e.g. `clamp(some_f32, 0, 1)` is an error).

## 4. Allow builtin overloads to infer the type

Inference logic would not backtrack a promotion to floating, but would try to delay promoting as late as possible. Overloads of builtins would be inferred based on all parameters. For example, `clamp(some_f32, 0, 1)` would be valid, as would `clamp(5, some_f32, 10)`.

## 5. Full implicit conversions of values

We mention this only for completeness sake. Google's position is not to adopt implicit conversions generally.

**Comment by dneto0** [comment]
> Finally, I'd like to see some explanation of how this proposal is different from Myles' earlier proposal: [#739 (comment)](https://github.com/gpuweb/gpuweb/issues/739#issuecomment-634874369) which seems very similar to sections 1 to 4 to me but with much greater level of detail.

Here's another difference (thanks Alan pointing this out):

Consider  `(1  + 1)  + 1u`.
The proposal from #739  would process this as an error, because:
* For `1+1` there is no unique overload for +, so both 1's become i32(1) by defaulting rules.
* Then `i32(1) + 1u` is an error.

With the proposal above (step 2), the idea is it is allowed:
* (1+1) is the integral type class (or IdealInteger from #2227)
* Then that IdealIngeter value unifies with 1u, and produces 3u as a final result.

Compare with `1 + (1+1u)`.  In both proposals, this is valid and gives a 3u answer.

The shader author would be confused (or have to look up grammar details) to understand `1  + 1 + 1u` vs. `(1 + 1) + 1u` vs. `1 + (1 + 1u)`.   We think the shader author should not have to contend with that confusion.

**Comment by litherum** [comment]
https://twitter.com/Litherum/status/1468338649615896580

**Comment by ben-clayton** [comment]
I've created a table comparing various languages, and the two proposals:
https://github.com/ben-clayton/misc/blob/main/literal-comparisons.md

It's also [interesting to see](https://github.com/gpuweb/gpuweb/pull/2306#issuecomment-988251893) that DXC uses `f64` and `i64` as the 'special' type for literals, which I believe perfectly aligns with this proposal.

**Comment by dneto0** [comment]
WGSL floating point operations can be reassociated. 

So if you default literals to f32, then

        var f : f32 = 16777216.0 + 1.0 - 1.0;

can be computed as either:

       var f1 : f32 = (16777216.0f + 1.0f) - 1.0f;  // yielding 16777215.0f   

or as:

       var f2: f32 = 16777216.0f + (1.0f - 1.0f);  // yielding 16777216.0f

**Comment by litherum** [comment]
Yes; I couldn't put that part in the tweet because it wouldn't fit.

**Comment by kvark** [comment]
> Do you want a compiler to use double-precision math at compile time, or match runtime behavior?

I still don't understand the argument for "match runtime behavior". Runtime on GPU is different from runtime on CPU, the floating point math and optimizations are different. We aren't going to "match" it anyway.

**Comment by alan-baker** [comment]
This is complete.

**Comment by alan-baker** [comment]
This is complete.
