### ISSUE TITLE
Parallels between WGSL and SPIR-V don't justify `let`

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#2207]
It's starting to look as if WGSL's `let` is not succeeding at serving the purposes it was intended for, and we should consider changing its meaning or dropping it.

The `let` / `var` dichotomy was originally introduced to WGSL to reflect a similar dichotomy in SPIR-V:

-   A SPIR-V `OpVariable` has an address, and is accessed with `OpLoad` and `OpStore` instructions. It is implied that `Function` class variables live in a stack frame.

-   A SPIR-V result id refers to a value computed by some specific instruction. It is implied that it lives in a register.

Although the two differ in how they treat assignment and addressing, they behave similarly in many ways, and in practice SPIR-V code uses result ids much like local variables.

WGSL's `let` and `var` were intended to allow users to make this distinction in WebGPU shaders too: function scope `var` would suggest a SPIR-V `OpVariable`, and function scope `let` would suggest a SPIR-V result id. This is why `var`-bound identifiers evaluate to references, corresponding to the pointer produced by `OpVariable`, while `let`-bound identifiers are immutable "names for values", corresponding to the value designated directly by a result id.

In #1782, we opted to further the WGSL / SPIR-V correspondence by permitting only constant indices for `let`-bound matrices and arrays, to reflect SPIR-V's lack of instructions for dynamically indexing matrices or arrays held in result ids. Intuitively, `let` suggests 'register', and registers usually aren't dynamically indexable.

However, there are a number of reasons to question the value of preserving the "`let` is to `var` as result id is to `OpVariable`" analogy:

-   Users frequently find `let` confusing (#2086, #1782). They understand `let` bindings as being immutable, not as referring to 'registers', and expect to be able to index arrays dynamically regardless of how they are bound. As dynamic indexing is the primary use case of arrays, arguing with this expectation is awkward.

-   WGSL already breaks this aspect of the correspondence with SPIR-V in several places. SPIR-V `OpPhi` has no analog in WGSL; equivalent data flow must be represented using local variables. Further, WGSL is block-scoped, whereas SPIR-V result ids can be used by any instruction in the function, as long as it is dominated by the id's definition. Here, again, WGSL code must use local variables where SPIR-V would not.

-   The compiler that generates GPU instructions is free to use any faithful translation of the shader code it is given, as long as the visible behavior is preserved. Local variables are often placed in registers, and intermediate results are often spilled to the stack frame. Ultimately, WGSL's `var` / `let` distinction implies a degree of control over these decisions that, in practice, WebGPU implementations simply do not have.

Overall, I think this shows that using `let` as a suggestion of an unstored SPIR-V result id is not serving any of its audiences very well.

The sole exception is that `let` is good at holding pointers. Excluding pointers and references from the 'storable types' category works well in the spec, and `let` bindings neatly provide a way of naming pointer values despite their being unstorable.

Are there any simplifications to be had here?

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-02-Minutes#parallels-between-wgsl-and-spir-v-dont-justify-let--issue-2207">WGSL meeting minutes 2021-11-02</a></summary>



* JB: So I think the consensus is that we should do nothing.
* MM: +1
* GR: but was a pain point for the guy who ported lots of shaders
* JB: The title needs to be read very literally: There may be justifications for `let`, but parallels between WGSL and SPIR-V don’t.
* **Resolved: “Yes”, Closed**

</details>

**Comment by dneto0** [comment]
> What are we gaining by trying to define let in terms of SPIR-V IDs? 

We aren't doing that.

For one thing, 'let' has lexical scoping, and SSA-IDs do not.
