### ISSUE TITLE
Consider not requiring braces in some situations

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2211]
`if (flag) output = sentinel;` is more readable than `if (flag) { output = sentinel; }`.

**Comment by litherum** [comment]
If we have to pick between this or https://github.com/gpuweb/gpuweb/issues/2212, https://github.com/gpuweb/gpuweb/issues/2212 is more important. The strongest argument in favor if requiring braces is that it would have prevented Heartbleed.

**Comment by dneto0** [comment]
I recommend closing this now.   #2212 was fixed instead.

**Comment by kainino0x** [comment]
Many codebases solve problems like goto-fail by enforcing formatting (indentation), but it's worth noting that very few users are going to be enforcing formatting on WGSL code.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-vf2f-2022-02-08,09-minutes#burndown-of-httpsgithubcomorgsgpuwebprojects2">WGSL meeting minutes 2022-02-08</a></summary>



    * MM: We want to close this, to be superceded by #2575

</details>
