### ISSUE TITLE
Considerations for timing attacks using timestamp queries

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2218]
The spec for `performance.now()` says in its "Privacy and Security" [section](https://w3c.github.io/hr-time/#clock-resolution):

> To ensure that the new API does not significantly improve the accuracy or speed of such attacks, the minimum resolution of the DOMHighResTimeStamp type should be inaccurate enough to prevent attacks.
>
> Where necessary, the user agent should set higher resolution values to time resolution in coarsen time's processing model, to address privacy and security concerns due to architecture or software constraints, or other considerations.
>
> In order to mitigate such attacks user agents may deploy any technique they deem necessary. Deployment of those techniques may vary based on the browser's architecture, the user's device, the content and its ability to maliciously read cross-origin data, or other practical considerations.

We should have similar text in our own Privacy and Security section.

**Comment by kvark** [comment]
Here is what we have now
> WebGPU also specifies the "timestamp-query" feature, which provides high precision timing of GPU operations. The feature is optional, and a WebGPU implementation may limit its exposure only to those scenarios that are trusted. Alternatively, the timing query results could be processed by a compute shader and aligned to a lower precision.

**Comment by Kangz** [comment]
@litherum is that text sufficient? If it isn't, can you make a PR?

**Comment by Kangz** [comment]
Ping @litherum? I think this issue can just be closed.

**Comment by Kangz** [comment]
Please reopen if needed..

**Comment by theb1rd** [comment]
Is it possible to use timestamp queries today? Via browser flags maybe? I've tried on intel and nvidia without success, but need them badly.
I appreciate the concern for timing attacks but if an attacker wants to steal the colors of my pixels he can have 'em.

**Comment by gyagp** [comment]
@theb1rd Chrome supports it with flag "--enable-dawn-features=allow_unsafe_apis". We just enabled it in ONNX Runtime and you may refer the PR (https://github.com/microsoft/onnxruntime/pull/18108) for details.

**Comment by theb1rd** [comment]
That worked, thanks gyagp!

(I thought I had been running with that flag, but in fact it was "--disable-dawn-features=disallow_unsafe_apis", what the f)

**Comment by gyagp** [comment]
The flag was changed a while ago :) Glad to know it works!
