### ISSUE TITLE
Clarify the rule about discard in a continuing block

### ISSUE THREAD

**Issue by RobinMorisset** [gpuweb/gpuweb#2219]
The current spec has a rule in section #continuing-statement saying:

> The compound statement must not contain a return or discard statement, at any compound statement nesting level.

It seems to me that this does not forbid calling functions that discard from the continuing block. I do not understand the point of forbidding discard in this purely syntactic way. Should it be forbidden even through function calls (trivial with the behavior analysis), or always allowed; or am I missing something?

**Comment by dneto0** [comment]
> Should it be forbidden even through function calls (trivial with the behavior analysis), or always allowed; or am I missing something?

After internal discussion, we recommend forbidding it (directly or indirectly through function calls).  That way will be consistent as @litherum  suggested.  And it will more play more nicely with broad installed base (FXC).   We can look at being more permissive in the future if there is strong demand.

**Comment by RobinMorisset** [comment]
I'm happy with that result, and it is trivial to spec with my 'behavior analysis' PR.

**Comment by dneto0** [comment]
This will be fixed by #2216

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-02-Minutes#clarify-the-rule-about-discard-in-a-continuing-block-2219">WGSL meeting minutes 2021-11-02</a></summary>



* DN: I think we got consensus offline.
* MM: If we do modules, does this need an extra annotation?
* RM: We need to know this for behavioral analysis anyway
* DN: And `discard` only valid in frag shaders, so we definitely need to know this anyway
* AB: Is RM fixing his PR?
* RM: I was waiting for decision, but I can either have this in the main PR or make a new PR just for this
* **RM to resolve this**


</details>
