### ISSUE TITLE
C-style casts

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2220]
It's pretty natural for shader authors coming from other shading languages to want to say something like

```
output.position.x = (float)(vert.VertexID / 2u) * 4.0 - 1.0;
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-10-minutes#c-style-casts--issue-2220">WGSL meeting minutes 2022-05-10</a></summary>



* KG: Notably, might be better then it used to be, don’t remember timeframe operating under. 
* DN: Commented in october we shouldn't do it and got 10 thumbs up. Don’t think we should do this.
* KG: Sounds like consensus. Closing and saying no.


</details>
