### ISSUE TITLE
[webgpu] Web IDL validation errors

### ISSUE THREAD

**Issue by autokagami** [gpuweb/gpuweb#2223]
🤖 This is an automatic issue report for Web IDL validation error. 🤖

The bot found validation errors but couldn't fix them automatically, since there is no proper autofix for them. Please check the following messages and fix them.

* ```
  Validation error at line 7 in webgpu,50, inside `interface mixin GPUPipelineBase`:
      GPUBindGroupLayout getBindGroupLayout(unsigned long index
                         ^
  ```
  
  > Error: The operation "getBindGroupLayout" has already been defined for the base interface "GPUComputePipeline" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,50, inside `interface mixin GPUPipelineBase`:
      GPUBindGroupLayout getBindGroupLayout(unsigned long index
                         ^
  ```
  
  > Error: The operation "getBindGroupLayout" has already been defined for the base interface "GPURenderPipeline" either in itself or in a mixin
* ```
  Validation error at line 4 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 12 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined pushDebugGroup(USVString groupLabel)
                ^
  ```
  
  > Error: The operation "pushDebugGroup" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 13 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined popDebugGroup();
                ^
  ```
  
  > Error: The operation "popDebugGroup" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 14 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined insertDebugMarker(USVString markerLabel)
                ^
  ```
  
  > Error: The operation "insertDebugMarker" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 4 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 12 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined pushDebugGroup(USVString groupLabel)
                ^
  ```
  
  > Error: The operation "pushDebugGroup" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 13 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined popDebugGroup();
                ^
  ```
  
  > Error: The operation "popDebugGroup" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 14 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined insertDebugMarker(USVString markerLabel)
                ^
  ```
  
  > Error: The operation "insertDebugMarker" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 3 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setPipeline(GPURenderPipeline pipeline)
                ^
  ```
  
  > Error: The operation "setPipeline" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 5 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setIndexBuffer(GPUBuffer buffer,
                ^
  ```
  
  > Error: The operation "setIndexBuffer" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 6 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setVertexBuffer(GPUIndex32 slot,
                ^
  ```
  
  > Error: The operation "setVertexBuffer" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 8 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined draw(GPUSize32 vertexCount,
                ^
  ```
  
  > Error: The operation "draw" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 10 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndexed(GPUSize32 indexCount,
                ^
  ```
  
  > Error: The operation "drawIndexed" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 15 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndirect(GPUBuffer indirectBuffer,
                ^
  ```
  
  > Error: The operation "drawIndirect" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 16 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndexedIndirect(GPUBuffer indirectBuffer,
                ^
  ```
  
  > Error: The operation "drawIndexedIndirect" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 4 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 12 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined pushDebugGroup(USVString groupLabel)
                ^
  ```
  
  > Error: The operation "pushDebugGroup" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 13 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined popDebugGroup();
                ^
  ```
  
  > Error: The operation "popDebugGroup" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 14 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined insertDebugMarker(USVString markerLabel)
                ^
  ```
  
  > Error: The operation "insertDebugMarker" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 3 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setPipeline(GPURenderPipeline pipeline)
                ^
  ```
  
  > Error: The operation "setPipeline" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 5 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setIndexBuffer(GPUBuffer buffer,
                ^
  ```
  
  > Error: The operation "setIndexBuffer" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 6 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setVertexBuffer(GPUIndex32 slot,
                ^
  ```
  
  > Error: The operation "setVertexBuffer" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 8 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined draw(GPUSize32 vertexCount,
                ^
  ```
  
  > Error: The operation "draw" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 10 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndexed(GPUSize32 indexCount,
                ^
  ```
  
  > Error: The operation "drawIndexed" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 15 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndirect(GPUBuffer indirectBuffer,
                ^
  ```
  
  > Error: The operation "drawIndirect" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 16 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndexedIndirect(GPUBuffer indirectBuffer,
                ^
  ```
  
  > Error: The operation "drawIndexedIndirect" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,50, inside `interface mixin GPUPipelineBase`:
      GPUBindGroupLayout getBindGroupLayout(unsigned long index
                         ^
  ```
  
  > Error: The operation "getBindGroupLayout" has already been defined for the base interface "GPUComputePipeline" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,50, inside `interface mixin GPUPipelineBase`:
      GPUBindGroupLayout getBindGroupLayout(unsigned long index
                         ^
  ```
  
  > Error: The operation "getBindGroupLayout" has already been defined for the base interface "GPURenderPipeline" either in itself or in a mixin
* ```
  Validation error at line 4 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 12 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined pushDebugGroup(USVString groupLabel)
                ^
  ```
  
  > Error: The operation "pushDebugGroup" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 13 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined popDebugGroup();
                ^
  ```
  
  > Error: The operation "popDebugGroup" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 14 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined insertDebugMarker(USVString markerLabel)
                ^
  ```
  
  > Error: The operation "insertDebugMarker" has already been defined for the base interface "GPUComputePassEncoder" either in itself or in a mixin
* ```
  Validation error at line 4 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 12 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined pushDebugGroup(USVString groupLabel)
                ^
  ```
  
  > Error: The operation "pushDebugGroup" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 13 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined popDebugGroup();
                ^
  ```
  
  > Error: The operation "popDebugGroup" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 14 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined insertDebugMarker(USVString markerLabel)
                ^
  ```
  
  > Error: The operation "insertDebugMarker" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 3 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setPipeline(GPURenderPipeline pipeline)
                ^
  ```
  
  > Error: The operation "setPipeline" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 5 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setIndexBuffer(GPUBuffer buffer,
                ^
  ```
  
  > Error: The operation "setIndexBuffer" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 6 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setVertexBuffer(GPUIndex32 slot,
                ^
  ```
  
  > Error: The operation "setVertexBuffer" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 8 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined draw(GPUSize32 vertexCount,
                ^
  ```
  
  > Error: The operation "draw" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 10 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndexed(GPUSize32 indexCount,
                ^
  ```
  
  > Error: The operation "drawIndexed" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 15 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndirect(GPUBuffer indirectBuffer,
                ^
  ```
  
  > Error: The operation "drawIndirect" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 16 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndexedIndirect(GPUBuffer indirectBuffer,
                ^
  ```
  
  > Error: The operation "drawIndexedIndirect" has already been defined for the base interface "GPURenderPassEncoder" either in itself or in a mixin
* ```
  Validation error at line 4 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 7 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined setBindGroup(GPUIndex32 index,
                ^
  ```
  
  > Error: The operation "setBindGroup" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 12 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined pushDebugGroup(USVString groupLabel)
                ^
  ```
  
  > Error: The operation "pushDebugGroup" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 13 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined popDebugGroup();
                ^
  ```
  
  > Error: The operation "popDebugGroup" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 14 in webgpu,86, inside `interface mixin GPUProgrammablePassEncoder`:
      undefined insertDebugMarker(USVString markerLabel)
                ^
  ```
  
  > Error: The operation "insertDebugMarker" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 3 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setPipeline(GPURenderPipeline pipeline)
                ^
  ```
  
  > Error: The operation "setPipeline" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 5 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setIndexBuffer(GPUBuffer buffer,
                ^
  ```
  
  > Error: The operation "setIndexBuffer" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 6 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined setVertexBuffer(GPUIndex32 slot,
                ^
  ```
  
  > Error: The operation "setVertexBuffer" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 8 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined draw(GPUSize32 vertexCount,
                ^
  ```
  
  > Error: The operation "draw" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 10 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndexed(GPUSize32 indexCount,
                ^
  ```
  
  > Error: The operation "drawIndexed" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 15 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndirect(GPUBuffer indirectBuffer,
                ^
  ```
  
  > Error: The operation "drawIndirect" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin
* ```
  Validation error at line 16 in webgpu,89, inside `interface mixin GPURenderEncoderBase`:
      undefined drawIndexedIndirect(GPUBuffer indirectBuffer,
                ^
  ```
  
  > Error: The operation "drawIndexedIndirect" has already been defined for the base interface "GPURenderBundleEncoder" either in itself or in a mixin

Please file an issue at https://github.com/saschanaz/webidl-updater/issues/new if you think this is invalid or should be enhanced.

**Comment by kainino0x** [comment]
@saschanaz I'm having a hard time understanding the error here. e.g. AFAICT we only have one IDL definition of getBindGroupLayout and it isn't getting doubly-included in any interfaces. Does this look like a bug in the validator, or are we doing something funny that I don't see?

**Comment by saschanaz** [comment]
Oops, sorry for the confusion, this is indeed an invalid report. It's because of https://github.com/w3c/browser-specs/pull/417 where the list was supposed to give the path to WGSL spec but instead gave WebGPU one, which then was recognized as a pure duplication.

Please keep this issue open for some days until the bug is fixed, since otherwise the bot will immediately reopen it. Sorry again for the inconvenience.

@tidoust, could you trigger a new release so that the bot can stop being confused?

**Comment by saschanaz** [comment]
Actually I mitigated this issue in https://github.com/saschanaz/webidl-updater/commit/8e0ee06975427236283a10a344e5bb3a270bdc10 with a different reason. This should be able to be safely closed now.

**Comment by toji** [comment]
I assume that goes for https://github.com/gpuweb/gpuweb/issues/2224 as well?

**Comment by kainino0x** [comment]
Ah, no worries. Thanks for the explanation! Looks like we can close both, they look the same to me.
