### ISSUE TITLE
support dot(vecN<i32>, vecN<i32>) in WGSL

### ISSUE THREAD

**Issue by axinging** [gpuweb/gpuweb#2231]
According to this https://www.w3.org/TR/WGSL/#vector-builtin-functions, current only dot(vecN<f32>, vecN<f32>) is supported. But i32 as input is also helpful, for example, in TensorFlowJS, dot(vecN<i32>, vecN<i32>) can be used to caculate coordinates.

**Comment by Jiawei-Shao** [comment]
The operator ```dot```
- Supports both ```float``` and ```int``` in [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-dot) and [DXIL]( https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst#dot2)
- Only supports ```float``` in ([SPIR-V](https://www.khronos.org/registry/SPIR-V/specs/1.2/SPIRV.html), ```OpDot```) and ([Metal](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf, "Chapter 6.8 Geometric Functions")).

**Comment by Jiawei-Shao** [comment]
Note that ```dot``` on integers is useful because sometimes converting from integers to floats, then doing computation will bring precision loss compared with doing computations on the integers directly.

For example,

```
    int a = 2147483600;
    int b = 47;
    printf("%d\n", a + b); // 2147483647
    printf("%f\n", (float)a + (float)b); // 2147483648.000000
```

**Comment by bjornbytes** [comment]
SPIR-V has an extension for it, `SPV_KHR_integer_dot_product`

**Comment by ben-clayton** [comment]
This was something I nearly filed a PR for a few weeks ago, but after realising that half the backends didn't have an integer dot instruction / opcode, I decided to not file it.

I agree that this is a useful intrinsic, and If there's hardware support for this, I think we should add this.

**Comment by dneto0** [comment]
> SPIR-V has an extension for it, SPV_KHR_integer_dot_product

When the component types are 32-bit integers, expanding the expression is sufficient.
The key benefit of the SPIR-V extension is for optimized computation of dot products of packed integers with smaller components that are not otherwise supported by the implementation.   e.x. 4x i8

Generally I would support adding this.  I would have to think about overflow cases matching platform behaviour.

**Comment by dneto0** [comment]
FYI:  The [SPV_KHR_integer_dot_product](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_integer_dot_product.html) extension

**Comment by dneto0** [comment]
I checked SPV_KHR_integer_dot_product.  It has pretty direct/unsurprising semantics:
- If the component type is narrower than the result type, then first extend components to the result type width (signed components are sign-extended, unsigned components are zero-extended).
- Then multiply components, pairwise, and add the results.    Use wrapping arithemetic.

WGSL only has one width of integer, so the first step is skipped.  The second step is the same as if the author had written it themselves.

**Comment by dneto0** [comment]
This was approved in the [2021-11-02 meeting](https://docs.google.com/document/d/1o3BrMEZnE3Yat95uLiY06opF2Hmcj5XGlQmBhTT-_dQ/edit#heading=h.74ev765uoxl1)

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-02-Minutes#support-dotvecnlti32-vecnlti32-in-wgsl-2231-">WGSL meeting minutes 2021-11-02</a></summary>



* SY: We have use for this in big-int operations.
* AB: Are you expecting hardware accel, or is emulated ok.
* SY: We hope for hardware, but we’re ok with emulated.  Doing the operation in floating point can lose precision.
* MM: This sounds fine. To us, the barrier to adding functions to the standard library is very low. The main requirement is that if there is hardware support, we need to be sure that we can match the behavior versus the polyfill.
* AB: Spir-v doesn’t really have wide support, and where there is support it’s mostly for smaller ints. So long as we’re fine without hwaccel, I think it’s easy enough to add for convenience. 
* **Resolved yes: Needs spec (Intel to write PR)**


</details>
