### ISSUE TITLE
Describe more clearly who can contribute in README.md

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2237]
For significant contributions potentially containing IP it needs to be WG or CG+FSA.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-01-19#triage-the-issues-without-milestones-timebox-15m">WGSL meeting minutes 2022-01-19</a></summary>



* #2237 who can contribute to README.md?
    * KG: we can figure this out for V1.


</details>
