### ISSUE TITLE
Select operator arguments are in a non-intuitive order

### ISSUE THREAD

**Issue by pow2clk** [gpuweb/gpuweb#2242]
As described here: https://www.construct.net/en/blogs/ashleys-blog-2/porting-webgl-shaders-webgpu-1576

The current select operator has arguments in the order of `select(falsecase, truecase, condition)` which is backwards from nearly all platforms except MSL. 

It would be more familiar to put them in this order: `select(condition, truecase, falsecase)`

**Comment by kainino0x** [comment]
I would guess that one reason for similarity with `mix()` is that in GLSL, IIUC it's idiomatic to use `mix()` as a replacement for `select()` (which doesn't exist).

**Comment by ben-clayton** [comment]
See https://github.com/gpuweb/gpuweb/pull/1957#issue-946062961

**Comment by dneto0** [comment]
> I would guess that one reason for similarity with `mix()` is that in GLSL, IIUC it's idiomatic to use `mix()` as a replacement for `select()` (which doesn't exist).

Yeah, and until there were integers and booleans in shader languages, you represent booleans like:
- false -> 0.0,
-  true -> 1.0, 
- and -> multiply or max
- or -> max
- negation -> 1 minus

**Comment by dneto0** [comment]
This is an unhappy situation.

Maybe add a 'pick' builtin that does it in the intuitive order?
Then when selecting among numeric values, at least the type checker will alert you to the problem. The only unfortunate case that would remain would be selecting/picking among booleans and bool-vectors.

**Comment by kvark** [comment]
I hate to say it, but I think we should consider changing `select` parameter *again*, this time to match SPIR-V's OpSelect, and which also matches the intuitive expectations that at least me and @pow2clk share :)

**Comment by ben-clayton** [comment]
Or we also add a ternary operator, and everyone is happy?

**Comment by kvark** [comment]
Adding another operator is a heavyweight "solution". It doesn't fix `select`, it only introduces more complexity.

**Comment by ben-clayton** [comment]
Okay, well if we're seriously considering reordering the parameters of `select`, I'd hope we'd do the same for `mix` too, as this is effectively the same function, but it takes a `f32` instead of a `bool` for the third parameter.

And if we change the signature of `mix`, I then think we should probably do the same for `smoothStep`, which is (almost) an inverse of `mix`.

**Comment by kainino0x** [comment]
Ternary operator is also not the same as select.
- select's condition can be vec<bool>
- select's arguments are evaluated unconditionally

TBH the ternary operator is really useful and I'd probably enjoy using it someday. But it's not an alternative to select which can be used to vectorize operations like this bit of sRGB-encoding pseudocode I wrote the other day:

```rust
   let linear_part = vec3<f32>(12.92) * v;
   let gamma_part = vec3<f32>(1.055) * pow(v, vec3<f32>(1.0 / 2.4)) - vec3<f32>(0.055);
   return select(gamma_part, linear_part, v < vec<f32>(0.0031308));
```

**Comment by ben-clayton** [comment]
[HLSL's ternary op](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-operators#boolean-math-operators) is just syntactic sugar over a select instruction. It evaluates both sides. It accepts vectors for the conditional.

The reason I mentioned the ternary op, is that aside 
from SPIR-V's `OpSelect`, **all shader languages use `(false, true, cond)` for a select-like function call**, all others have ternary-like ops. [See this table I linked to earlier](https://github.com/gpuweb/gpuweb/pull/1957#issue-946062961).

As people don't tend to write SPIR-V by hand, I'm failing to see why "Select operator arguments are in a non-intuitive order". They're in the order used by everything else. If it's non-intuitive, then your intuition is probably based on the ternary op.

**Comment by ben-clayton** [comment]
> I guess @pow2clk was aware that this was coming down the pipe, hence the issue.

I'm sorry this came across like I was making accusations of bad intent. That wasn't my intention. I made a guess that there had been an internal discussion about the mismatch of HLSL 2021's `select` and WGSL, which at the time, couldn't be discussed publicly. This was not the case, and I shouldn't have made this speculative comment which added nothing to my comment. My sincerest apologies.

**Comment by dneto0** [comment]
Discussed in 2022-01-11 meeting [bookmark](https://docs.google.com/document/d/1CQcjcdDA0anAtw08KyUnSXbhfb6cMYs03X8GZaIyKRQ/edit#bookmark=id.hrjcvabmu8mx)

Agreed no change to be made.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2022-01-11-Minutes#select-operator-arguments-are-in-a-non-intuitive-order--issue-2242">WGSL meeting minutes 2022-01-11</a></summary>



* GR:
* BC: WGSL is not the outlier here vs. other existing shader languages. In issue, linked to a table comparing the prior art.  SPIR-V is the only on that’s different.
    * [on Jul 16, 2021](https://github.com/gpuweb/gpuweb/pull/1957#issue-946062961) ⇐= this is the table
* GR: Reject mix and lerp as being “the same” as select.
* KN:  Before “select” existed, folks would have to use mix to polyfill the behaviour.
* DN: In C and I think GLSL, the ternary operator is short-circuiting, which is different in my mind.
* GR: HLSL’s select() operator is not short-circuiting. HLSL’s ternary operator is.
* **No consensus to change. Leave spec as-is.**


</details>
