### ISSUE TITLE
Are double brackets necessary for attributes?

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#2243]
(Apologies if people discussed this before and I missed it)

Reading monospace font examples, double brackets [[ and ]] seem to horizontally bloat lines a lot. Although I get the double bracket precedent in many other languages for attribute purposes, given the overuse of chars in WGSL, it might be better to adopt a single bracket [ and ] unless it introduces a critical problem.

Comparison of double `[[]]`, single `[]`, `@` by examples: https://github.com/gpuweb/gpuweb/issues/2243#issuecomment-959784446

Tracking comment of `@`: https://github.com/gpuweb/gpuweb/issues/2243#issuecomment-984209391

**Comment by mehmetoguzderin** [comment]
## Example

Double (copy from https://github.com/gpuweb/gpuweb/issues/2238 issue):

```rust
[[stage(compute), workgroup_size(x,y,z)]]
fn main([[builtin(local_invocation_id)]] lid : vec3<u32>) {
```

Single:

```rust
[stage(compute), workgroup_size(x,y,z)]
fn main([builtin(local_invocation_id)] lid : vec3<u32>) {
```

**Comment by dneto0** [comment]
We used the attribute syntax from C++.

**Comment by Kangz** [comment]
C++ is a clear rational.

For completeness there's Python/Java's `@MyAnnotion(X)` and Rust's `#[my_annotation(X)]`

**Comment by mehmetoguzderin** [comment]
Either `@[]` or `#[]` wouldn't attain the benefits of this reduction, and `@` only is incompatible with `,` I guess? (Also, those can maybe become the syntax extension or language version tags that have been discussed before?)

Further:
- Beyond horizontal bloat, these seem easy to typo. There have been missing instances of matching pair even in the spec text itself just recently spotted: https://github.com/gpuweb/gpuweb/pull/2248
- Having a single bracket would also discard the double bracket aspect of this issue (but not other elements): https://github.com/gpuweb/gpuweb/issues/2092
- Per our grammar CI, this did not introduce any ambiguities and parsed well, change works well.
- This was very trivial to implement in Naga: https://github.com/gfx-rs/naga/pull/1512
- If we only and only take a single bracket for ourselves, metaprogramming systems (which the group rendered implicitly desired with the preference of string interpolation over built-in expansion) can take `[[` and `]]`, `#[` and `]`, `@[` and `]`, `![` and `]`, besides the further combination of these syntaxes, for their purposes, akin to how they will probably use `{{` and `}}` for token interpolation, unless spec reserves these for own use.
- Also, these make the authors sometimes feel like there needs to be a space between the identifier and the double brackets (leading to things like `[[ group(?) ]] [[ binding(?) ]]`, or `[[ builtin(global_invocation_id) ]] global_invocation_id : vec3<u32`), obscuring that these are inline attributes that should just read compactly together with the tagged object or type for better reading comprehension.
- (Side: for handwriting, might be teaching or other reasons like accessibility, a single bracket is much less error-prone)

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-09-Minutes#are-double-brackets-necessary-for-attributes-2243">WGSL meeting minutes 2021-11-09</a></summary>



* MOD: Did feasibility study on parser. And were no issues. Some languages successful without them.
* MM: Agree with the goal. Concern with using single brackets specifically as the solution. Correct no ambiguities today but could be tomorrow.  Already use single brackets for array access.
* DN: Don’t want to spend the innovation tokens here. 
* JG: Can follow Rust. (which has something)
* JB: C# has single square brackets.
* MM: Scenario of possible future where we might drop semi-colons.  So can get an ambiguities when features collide, particularly around lexing.
* BC: Haven’t seen the Rust thing before.  
* BC: Hitting the same key twice is low burden.
* JB: JS implementers hate automatic semicolon insertion (JS devs ignore it).
* JG: Seems no great energy.
* JB: We should state that we feel like it shouldn’t be something being written often enough to truly be a hassle.
* **Consensus: No change right now.**


</details>

**Comment by aloucks** [comment]
The repetition is a little confusing as other syntaxes use this to indicate lists or nesting.

For example, in TOML, this would indicate an array of blocks:

```toml
[[block]]
# things here
[[block]]
# things here
```

In Rust, this would be a nested array of `f32` (i.e. a 2x2 matrix)
```rust
[[0.0, 0.0], [0.0, 0.0]]
```

Both Java `@MyAnnotation(x)` and Rust's `#[my_annotation(x)]` attribute syntax are nicer alternatives, imo.

**Comment by mehmetoguzderin** [comment]
@aloucks very valid argument, I'll add that to further listing https://github.com/gpuweb/gpuweb/issues/2243#issuecomment-961469665 above.

**Comment by mehmetoguzderin** [comment]
# Tracking comment for `@attribute_name(input)`

This comment is for noting things tried for `@` alternative. Although the previous comment of https://github.com/gpuweb/gpuweb/issues/2243#issuecomment-959784446 is extended with `@` examples, these notes might be better to keep separate from single attribute tests comment. The benefits of `@` are obvious: three less characters, single way of writing things (as in, `[[stage(), size()]]` and `[[stage()]] [[size()]]` for same idea going away in favor of `@stage() @size()` as a unified way).

- Per our grammar CI, this did not introduce any ambiguities and parsed well, change works well.

**Comment by ben-clayton** [comment]
Reopening as suggested with https://github.com/gpuweb/gpuweb/issues/2471#issuecomment-1004852307

**Comment by RobinMorisset** [comment]
I like a lot the proposal to use `@attribute_name(input)`. Not only is it significantly more concise, but it slightly simplifies lexing/parsing (I think that `[[` is a single token when parsing attributes, but two tokens in some expressions with nested array indexing).

**Comment by aloucks** [comment]
`#[my_annotation(x)]` would be my preference :)

**Comment by litherum** [comment]
Swift uses `@Thing(arguments)` for property wrappers, which are actually kind of similar to what we would be using this syntax for here in WGSL. E.g. `@Environment(\.managedObjectContext) var managedObjectContext` in Swift means "I'm making a variable that reflects the NSManagedObjectContext that is pulled from the environment". Notice how this object doesn't get an initializer, just like how `@id(1300) override gain: f32;` in WGSL wouldn't get an initializer either.

**Comment by dneto0** [comment]
Google's preference is for @foo(blah) syntax, for the same reasons @RobinMorisset gives.

**Comment by dneto0** [comment]
Also, @-based syntax is already common in Python and Java, even though the decorator details are different, the spirit is the same.

**Comment by mehmetoguzderin** [comment]
With new syntax using up to %83 reduced surroundings per attribute, this issue should be ready to close.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-01-18-(apac)-minutes#are-double-brackets-necessary-for-attributes--issue-2243">WGSL meeting minutes 2022-01-18</a></summary>



*  MOD: Less wordy. Was raised again. Helps parsing.
* KG: Seems enough weakly opinionated agreement.
* AB: Also, every attribute is individual. No combined syntax anymore.
* MM: Seems fine.  Had talked about combining makes it more difficult for code generators.
* _Agreed on @-based syntax._
* MOD: I will do the PR.
    * [https://github.com/gpuweb/gpuweb/pull/2517](https://github.com/gpuweb/gpuweb/pull/2517) 


---


</details>

**Comment by munrocket** [comment]
After a while, I like this new clean syntax, thank you!

**Comment by mehmetoguzderin** [comment]
@munrocket Thank you for your positive comment; coincidentally, another friend spoke of the same thought just yesterday!
