### ISSUE TITLE
WGSL should forbid pointers to runtime-sized values as user-defined function parameters

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#2268]
User-defined functions that accept pointers to runtime-sized structures are permitted by WGSL, but are useless, because such pointers cannot be produced. These uncallable functions also happen to be a pain to generate code for. WGSL should just forbid them.

User-defined functions can only accept pointers in the `function`, `private`, or `workgroup` storage classes (WGSL §8.3). Runtime-sized arrays can only appear in the `storage` storage class (§4.2.8). Thus, no pointer to a runtime-sized array or a struct containing one can be passed to a user-defined function.

However, there is nothing in WGSL to prevent one from defining a function that accepts an argument of type `ptr<storage, array<T>, A>` anyway. For example:

```
[[block]]
struct Unsized { data: array<f32>; };
fn acceptable_pointer_to_unsized(arg: ptr<workgroup, Unsized>) -> f32 {
   return (*arg).data[0];
}
```

Tint and Naga cheerfully translate this into SPIR-V. Naga will even emit index bounds checking code for it. But Tint objects if asked to produce MSL with `--transform robustness`:

```
error: no matching call to arrayLength(ptr<workgroup, array<f32>, read_write>)

1 candidate function:
  arrayLength(ptr<storage, array<T>, A>) -> u32
```

I'm working on the equivalent of `--transform robustness` for Naga, and have run into a similar problem generating Metal output.

It would be helpful if translators could avoid having to generate code for such functions. The WGSL spec could simply forbid user-defined functions from accepting pointers whose store type contains a runtime-sized array.

See also: gfx-rs/naga#1513

**Comment by jrprice** [comment]
I think this is already covered by the WGSL spec. We say:

> The last member of the structure type defining the store type for a variable in the storage storage class may be a runtime-sized array.
>
> A runtime-sized array must not be used as the store type or contained within a store type in any other cases.

I think the usage you describe falls with the second bullet, and is therefore disallowed.

I hit this issue in Tint a few weeks ago, and we have a bug filed here: crbug.com/tint/1248

**Comment by jimblandy** [comment]
@jrprice How does that forbid defining the function I showed?

My concern is that the function is permitted, even though anything you could pass to it is forbidden.

**Comment by jimblandy** [comment]
Oh, I see - you're saying, it cannot even appear as the store type of a pointer type.

**Comment by jimblandy** [comment]
But that can't be right, either, because `arrayLength` takes such a pointer as its argument. If you can't even create the pointer within a function, then you can't pass it to `arrayLength`.

**Comment by jrprice** [comment]
Right, the lines I quoted do read like they would forbid pointers to structures containing runtime-sized arrays in *all* storage classes, which breaks the `arrayLength` case. So I think there is indeed some clarification to be made in the spec here in order to make sure that case is allowed.

**Comment by jimblandy** [comment]
Even setting `arrayLength` aside, my understanding is that we also want to let people create a pointer to an element of a runtime-sized array and then use that pointer locally, perhaps using `let` bindings whose type is `ptr<storage, array<T>, A>`. That's what led me to suggest placing the restriction on user-defined function arguments.

**Comment by dneto0** [comment]
Since the last comment, WGSL added the concept of fixed-footprint types: https://gpuweb.github.io/gpuweb/wgsl/#fixed-footprint-types 
That's the spec mechanism for allowing runtime-sized arrays in some places but not others.

For example, the address space table [specifies](https://gpuweb.github.io/gpuweb/wgsl/#ref-for-fixed-footprint%E2%91%A1) that a variable in `workgroup` address space can store "plain type with fixed footprint", and hence can't contain a runtime-sized value.

But @jimblandy is right that that applies to _variables_, but doesn't actually restrict formal parameters (when the  function is  not actually called).

So I think there is something to do here.  For example: you can only name a pointer type when you could also form an expression of that type.  And then add a note giving this motivating case.

**Comment by dneto0** [comment]
FYI.  WGSL has changed, and the updated example is:

```rust



struct Unsized { data: array<f32> };
fn acceptable_pointer_to_unsized(arg: ptr<workgroup, Unsized>) -> f32 {
   return (*arg).data[0];
}
```

Tint now rejects this example:

```
a.wgsl:5:34 error: runtime-sized arrays can only be used in the <storage> storage class
fn acceptable_pointer_to_unsized(arg: ptr<workgroup, Unsized>) -> f32 {
                                 ^^^

a.wgsl:4:18 note: while analysing structure member Unsized.data
struct Unsized { data: array<f32> };
                 ^^^^

a.wgsl:5:34 note: while instantiating parameter arg
fn acceptable_pointer_to_unsized(arg: ptr<workgroup, Unsized>) -> f32 {
                                 ^^^

```

**Comment by jimblandy** [comment]
Resolution: we all agree this function should be forbidden; the only open question is how to phrase it in the spec.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-10-minutes#wgsl-should-forbid-pointers-to-runtime-sized-values-as-user-defined-function-parameters--issue-2268">WGSL meeting minutes 2022-05-10</a></summary>



* JB: Just looking to see spec has changed. Looks, as far as I can tell, that there is no disagreement you can’t actually have a pointer workgroup const argument. Pointer to unsigned struct in workgroup address space. But, there isnt’ any language htat prevents writing such a type and no language which prevents user defined function from have a type. While Tint rejects, thats what I’m aiming for and want Naga to do the same, think Tint is overstepping and the spec doesnt’ support the rejection. If missed something, let me know.
* DN: Came to same conclusion this afternoon. Just a matter of finding good way to say it.
* JB: All agree on what we want, just finding right spec language.
* KG: Marking as; resolved, needs spec.


</details>

**Comment by theb1rd** [comment]
Is it possible to pass a storage buffer to a function?
I have a buffer like this:
`@group(0) @binding(7)  var<storage, read_write> my_buffer : array<u32>;
`

Which I need to pass to a function, but nothing I've tried has compiled successfully, e.g.:
```
fn this_fails(buf : array<u32>) {
    buf[0] = 0u;
}
```
> error: runtime-sized arrays can only be used in the storage address space

```
fn this_also_fails(buf : ptr<storage, array<u32>>) {
    buf[0] = 0u;
}
```
> error: function parameter of pointer type cannot be in 'storage' address space

However, if using a texture rather than a buffer, it's straightforward.
```
fn this_works(tex : texture_storage_3d<r32uint, write>) {
    textureStore(tex, vec3u(0), vec4u(0));
}
```
Passing a UAV buffer to a function is a very mundane thing in hlsl so I assumed it would be possible in wgsl - is that not the case?

**Comment by ben-clayton** [comment]
This is a restriction of WGSL 1. This restriction will be lifted in a future version of WGSL, once https://github.com/gpuweb/gpuweb/issues/3546 is resolved with https://github.com/gpuweb/gpuweb/pull/4323.

**Comment by microaaron** [comment]
> This is a restriction of WGSL 1. This restriction will be lifted in a future version of WGSL, once [#3546](https://github.com/gpuweb/gpuweb/issues/3546) is resolved with [#4323](https://github.com/gpuweb/gpuweb/pull/4323).

> Is it possible to pass a storage buffer to a function?

Is this issue resolved?  There seems to be no way to use a runtime-sized array in a function.

**Comment by microaaron** [comment]
> Is it possible to pass a storage buffer to a function? I have a buffer like this: `@group(0) @binding(7) var<storage, read_write> my_buffer : array<u32>; `
> 
> Which I need to pass to a function, but nothing I've tried has compiled successfully, e.g.:
> 
> ```
> fn this_fails(buf : array<u32>) {
>     buf[0] = 0u;
> }
> ```
> 
> > error: runtime-sized arrays can only be used in the storage address space
> 
This is understandable. The parameter size cannot be determined when compiling the function.



> ```
> fn this_also_fails(buf : ptr<storage, array<u32>>) {
>     buf[0] = 0u;
> }
> ```
> 
> > error: function parameter of pointer type cannot be in 'storage' address space
> 
But I hope that ```ptr<storage, array<T>>``` can be supported as a parameter.

**Comment by jrprice** [comment]
> But I hope that `ptr<storage, array<T>>` can be supported as a parameter.

This is now supported with the `unrestricted_pointer_parameters` language feature.
