### ISSUE TITLE
Ensure extending fillBuffer is feature detectable

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#2278]
In #2208 it's mentioned that `fillBuffer()` may be extended in the future to have a fourth parameter that specifies the value to fill the buffer with, defaulting to zero for backwards compat.

This alone would not be feature detectable in JavaScript, and would silently fail if developers tried to provide a fourth parameter on a browser that hadn't implemented the extended version yet.

```js
// JavaScript ignores all additional function parameters beyond what the signature specifies,
// so in a browser that implements the base spec, these three statements are equivalent and valid:
commandEncoder.fillBuffer(buffer, 0, 16);
commandEncoder.fillBuffer(buffer, 0, 16, 0xff);
commandEncoder.fillBuffer(buffer, 0, 16, 'walrus'); // This would exception only in browsers that implement a 4th param
```

Developers need a way to detect if passing a fourth value will actually have an effect, ideally not by provoking the exception mentioned above. Even better would be a way that was impossible to have silently fail, since that's a recipe for hard-to-catch bugs.

**Proposal 1:**
Separate the zero fill and value fill methods, changing the name of the method currently in the spec to `zeroBuffer` or similar.
```js
commandEncoder.zeroBuffer(buffer, 0, 16);
commandEncoder.fillBuffer(buffer, 0, 16, 0xff);
```

**Proposal 2:**
Add the value now and validate that it's zero (with a default to zero as well?) until we want to extend it. Add a `maxFillBufferValue` limit or similar to indicate what can be passed. This requires more effort to detect, but will at least prevent silent failures.
```js
commandEncoder.fillBuffer(buffer, 0, 16); // Default zero
commandEncoder.fillBuffer(buffer, 0, 16, 0); // Still valid
commandEncoder.fillBuffer(buffer, 0, 16, device.limits.maxFillBufferValue+1); // Validation error
commandEncoder.fillBuffer(buffer, 0, 16, 'crab'); // IDL error
```

**Comment by Kangz** [comment]
**Proposal 3:** allow a non-zero byte value already. It is a bit more implementation work for v1 but it avoids the duplication of proposal 1 and the complexity of proposal 2.

(I don't have a strong opinion on which proposal is best.)

**Comment by kainino0x** [comment]
cc @litherum

**Comment by kainino0x** [comment]
Resolution (Mozilla's input pending): Proposal 3, allow filling with a non-zero byte.

**Comment by litherum** [comment]
Pull request that adds a "value" argument: https://github.com/gpuweb/gpuweb/pull/2290

I made it take an `octet` value since that's 0-255 (https://webidl.spec.whatwg.org/#idl-octet). Unsigned seems more natural for this kind of API.

**Comment by toji** [comment]
Great minds think alike, eh? #2289 😁

**Comment by kvark** [comment]
We discussed this with editors.
My main concern with supporting the `value` parameter is the lack of a clear implementation path on D3D12.
For us in `wgpu` land this isn't going to be "free" to add.
In addition, calling `fillBuffer(myBuffer)` without specifying the value is a strange way to zero it out.
So we should probably separate `clearBuffer()` as a clean function that we have today, and then come back to `fillBuffer()` whenever time allows, possibly exposed via an optional feature.

**Comment by Kangz** [comment]
No concern with just having a `clearBuffer` for now. I'd like to resolve offline. @litherum WDYT? Any other objections to having just `clearBuffer` and revisit with a `fillBuffer` post-v1?

**Comment by kainino0x** [comment]
Meeting: Resolved to change to clearBuffer. #2372 filed as followup.
