### ISSUE TITLE
wgsl: add unary plus?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2279]
The operator precedence and associativity consensus is documented at https://github.com/gpuweb/gpuweb/issues/1146#issuecomment-714721825 

That has a unary plus, but the WGSL spec does not have unary plus.   PR #2267 recently updated the grammar to closer match the consensus, but not in this respect.

It seems fine to me, and is symmetric with unary minus.

**Comment by litherum** [comment]
We generally don't feel that it's worth bothering with. The costs outweigh the benefits.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-16-Minutes#wgsl-add-unary-plus-2279">WGSL meeting minutes 2021-11-16</a></summary>



* MM: Not valuable.
* **Let’s close.**


</details>

**Comment by dneto0** [comment]
Agreed not to add this.
