### ISSUE TITLE
shader int bit widths: restrict to 32 bits

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#229]
In vanilla Vulkan, integer scalars must be 32-bit.  
  shaderInt16  is an optional feature in Vulkan 1.0
  shaderInt64  is an optional feature in Vulkan 1.0
  shaderInt8 is an optional feature introduced by  extension VK_KHR_float16_int8

For widest availability, the WebGPU shader programming model should be restricted to 32-bit ints.

**Comment by dneto0** [comment]
Cc: @RobinMorisset

**Comment by dneto0** [comment]
And now I see WHLSL has an issue for 8bit int types: https://github.com/gpuweb/WHLSL/issues/165 

It looks like the resolution there was to keep 8bit types in WHLSL.

The argument is that WHLSL *can* have 8bit ints, even if you have to promote the operations up to 32bits.  But then a separate reasonable discussion is whether you want to do that extra work to support it.

Not considered in that issue is racing on non-atomic accesses to adjacent bytes in the same word:  e.g. two invocations (work-items / threads) writing adjacent bytes in the same word.

Some HW can't do that with a native non-atomic access.  You'd have to fake it with a loop around atomic compare-exchange. And even then it's not clear that progress guarantees exist to ensure that always works.

There's a sliding scale of just how much emulation you're willing to make an implementation do for the sake of covering for missing architectural features.   At some point you pick a spot on the tradeoff curve.  And if you go for the full emulation, you need to write tests for it and hope you exercised it well enough.

I think this is a worthy discussion to have, at the programming-model level.  We could have separate answers for 8bit and 16bit ints.

**Comment by dneto0** [comment]
I understand that neither FXC or DXC support 8 bit integers.

**Comment by grorg** [comment]
Discussed at the [8 April 2019 meeting](https://docs.google.com/document/d/1UiIZ7G7iruGYntiLSmhc-wRPj1sN1CqNcPdgeG51r1U/edit)

**Comment by grorg** [comment]
Resolution: 32-bit integers only for MVP

Possibly accept extensions post-MVP for other sizes.

**Comment by Kangz** [comment]
Closing since we agreed to only have 32 bit integers. Further request for features can go in new issues.
