### ISSUE TITLE
wgsl: should NUL characters be permitted in source code?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2294]
Right now they are permitted.
I don't know that they have a good use.

**Comment by dneto0** [comment]
FYI.   I read the Treesitter lexer and I believe it signals end-of-input as a single NUL character.   I imagine lots of common code may have the same assumption that input text doesn't contain NULs, because of C-style conventions.

**Comment by RobinMorisset** [comment]
I have a small preference for rejecting Null characters in WGSL programs.
Currently the only place they could be allowed by the grammar is in comments, and I don't really see the point of allowing it.
If banning it saves even a single bug in an implementation, it seems like a win.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-16-Minutes#wgsl-should-nul-characters-be-permitted-in-source-code--issue-2294">WGSL meeting minutes 2021-11-16</a></summary>



* DN: Saw this while reading the treesitter lexer, which uses a null char as a terminal sentinel. Seems not useful?
* **No, needs spec**


</details>
