### ISSUE TITLE
textureLoad with sampled textures.

### ISSUE THREAD

**Issue by mr-ariel** [gpuweb/gpuweb#2299]
From 4.5.2: sampled textures are defined with their Spir-v Sampled = 1 (with sampler), and storage textures with Sampled = 2 (no sampler), for ex:

texture_2d<type>
 //  %1 = OpTypeImage %type 2D 0 0 0 1 Unknown
texture_storage_2d<texel_format,access>
 // %1 = OpTypeImage sampled_type 2D 0 0 0 2 image_format

On the other side, wgsl's textureLoad, described as "reads without sampling or filtering.", I'm assuming it maps to OpImageRead  which requires the image to be either Sampled 0 or 2, and thus would be incompatible with all the sampled textures defined for textureLoad such as:
...
textureLoad(t: texture_1d<T>, coords: i32, level: i32) -> vec4<T>
textureLoad(t: texture_2d<T>, coords: vec2<i32>, level: i32) -> vec4<T>
textureLoad(t: texture_2d_array<T>, coords: vec2<i32>, array_index: i32, level: i32) -> vec4<T>
...

and only allowing for it to be used with texture_storage_x<type>, which oddly, is the only one not defined in the spec.

Is this correct?, is the implementation deciding how to handle these cases?

**Comment by alan-baker** [comment]
`textureLoad` maps to `OpImageFetch` in SPIR-V.

**Comment by mr-ariel** [comment]
Thank you for that!!
Makes perfect sense now!
