### ISSUE TITLE
Should it be possible to create 3D depth textures?

### ISSUE THREAD

**Issue by Wumpf** [gpuweb/gpuweb#2304]
currently there is no limitation on which format are allowed with texture dimension 3d.
E.g. depth texture volumes should not be allowed since they can't  be rendered to (see #2303), copied to or used as storage.

**Comment by Kangz** [comment]
@kvark pointed out on Matrix that you can initialize a 3D depth texture by copying from 2D resources. I don't think we need to write down in the spec that 3D depth textures are disallowed then. They're just awkward to use.

**Comment by kvark** [comment]
If it's not practically usable, I think a cleaner API would tell that to users at `createTexture` time. That is, until we find a way to make them usable. For example, by allowing `writeTexture` to work on depth textures.

**Comment by kainino0x** [comment]
I agree with going ahead and disallowing this. In particular because this is probably a dark corner of driver support (assuming it's supported at all) and I don't want to deal with testing and workarounds for a currently-useless feature.

**Comment by Kangz** [comment]
Turns out that specification already disallows this. So tentatively closing this issue.

**Comment by kainino0x** [comment]
For reference, the text is:

> If descriptor.dimension is:

("1d" or "3d", then)

> descriptor.format must not be a compressed format or depth-or-stencil format.

**Comment by kainino0x** [comment]
and it was added in #1658
