### ISSUE TITLE
Remove isNormal()?

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2309]
In https://github.com/gpuweb/gpuweb/issues/2270, we resolved to remove isInf() and isNan() because they return bogus information in many (all?) situations.

It seems like isNormal will also return bogus information in many (all?) situations. We should determine if we should apply that resolution to isNormal() too.

**Comment by dneto0** [comment]
isNormal is a non-trivial testable function, even with fast math variations.

Normal numbers are any floating point number which is:
 - not infinity
 - not NaN
 - Not zero
 - Not subnormal.

Another way to write it is that the exponent is neither the largest nor smallest exponent for the format.

I've written a [draft CTS test for it](https://github.com/gpuweb/cts/pull/804/files#diff-ae96f7c7a30f88c4e1c1d33af134402576e80e05a7e2d809740775aeb70c8beaR37)

An implementation that cuts the most permissible corners can:
- assume NaNs or infinities don't occur
- can flush denormals to zero, _but only on certain operations_

[§ 12.5 Floating Point Evaluation](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-evaluation) says:

> Implementations may flush denormalized value on the input and/or output of any operation listed in [§ 12.5.1 Floating Point Accuracy](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-accuracy).

> *   Other operations are required to preserve denormalized numbers.

As @alan-baker says, this is a distillation of common functionality in underlying platforms.


Altogether, I think isNormal should stay.

**Comment by dneto0** [comment]
WGSL also has isFinite.   *That* could be removed, by the same argument as removing isNan or isInfinite. #2270

That is, an implementation that cuts as many corners as possible (assumes no infinities and Nans) can reduce it to just returning "false".

**Comment by alan-baker** [comment]
> WGSL also has isFinite. _That_ could be removed, by the same argument as removing isNan or isInfinite. #2270
> 
> That is, an implementation that cuts as many corners as possible (assumes no infinities and Nans) can reduce it to just returning "false".

True you mean.

**Comment by dneto0** [comment]
Reviewing support:

| Language | isFinite | isInfinite | isNan | isNormal |
| --- | --- | --- | --- | --- |
| [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-intrinsic-functions) |  Y | Y | Y | N  |
| [MSL](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) |  Y | Y | Y | Y 
| [GLSL](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.50.pdf) | N | Y | Y | N
| [SPIR-V ](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html)| (in Kernel, not Shader) | Y | Y | (in Kernel, not Shader)
| [DXIL](https://github.com/gpuweb/gpuweb/issues/2309) | Y | Y| Y | Y


Looking at this table, isNormal does not seem critical.  It would probably be weird / not very useful to have *only* isNormal and none of the other three.
