### ISSUE TITLE
Some vertex formats in webgpu idl cannot be supported on all platforms

### ISSUE THREAD

**Issue by shaoboyan** [gpuweb/gpuweb#231]
When I implemented vertex formats based on webgpu idl in dawn, I found some vertex formats cannot be supported on all platforms. 

For metal, some formats only supported on mac OS 10.13+([Metal Vertex Formats Lists](https://developer.apple.com/documentation/metal/mtlvertexformat)). Here are the formats :
[MTLVertexFormatUChar](https://developer.apple.com/documentation/metal/mtlvertexformat/uchar) --> uchar
[MTLVertexFormatChar](https://developer.apple.com/documentation/metal/mtlvertexformat/char) --> char
[MTLVertexFormatUCharNormalized](https://developer.apple.com/documentation/metal/mtlvertexformat/ucharnormalized) --> ucharnorm
[MTLVertexFormatCharNormalized](https://developer.apple.com/documentation/metal/mtlvertexformat/charnormalized) --> charnorm
[MTLVertexFormatUShort](https://developer.apple.com/documentation/metal/mtlvertexformat/ushort) --> ushort
[MTLVertexFormatShort](https://developer.apple.com/documentation/metal/mtlvertexformat/short) --> short
[MTLVertexFormatUShortNormalized](https://developer.apple.com/documentation/metal/mtlvertexformat/ushortnormalized) --> ushortnorm
[MTLVertexFormatShortNormalized](https://developer.apple.com/documentation/metal/mtlvertexformat/shortnormalized) --> shortnorm
[MTLVertexFormatHalf](https://developer.apple.com/documentation/metal/mtlvertexformat/half) --> half
[MTLVertexFormatUChar4Normalized_bgra](https://developer.apple.com/documentation/metal/mtlvertexformat/uchar4normalized_bgra) --> uchar4norm-bgra

For D3D12([DXGI format lists](https://docs.microsoft.com/en-us/windows/desktop/api/dxgiformat/ne-dxgiformat-dxgi_format)), there are some 3-component webgpu formats cannot find native DXGI formats to support it.(e.g. uchar3 should be supported by formats like DXGI_FORMAT_R8G8B8_UINT, but D3D12 doesn't have this format). Here are the formats : 
uchar3, char3, uchar3norm, char3norm, ushort3, short3, ushort3norm, short3norm, half3

For these formats that are not supported on all platforms, I think we shouldn't support them in webgpu.

**Comment by JusSn** [comment]
At least in WebKit, we aren't supporting Web GPU on macOS versions less than 10.13 right now, so the Metal stuff can stay. @litherum, @grorg?

**Comment by kvark** [comment]
Well, I'd like us to support macOS earlier than 10.13, especially if WebKit doesn't :P
Seriously though, the lack of listed formats isn't going to be a showstopper for anyone. It seems relatively straightforward to work around.
