### ISSUE TITLE
Adding invertY and preMultiplyAlpha options to copyExternalImageToTexture

### ISSUE THREAD

**Issue by Popov72** [gpuweb/gpuweb#2324]
It would be very nice to add these options to copyEITT, much in the same way we have them in `ImageBitmap`.

I have read #2110.

From @kenrussell:
> The only other reason control over the vertical flip would be needed is for ImageBitmaps, and it doesn't seem necessary to me to support that; the web app should just not flip its ImageBitmaps when it intends to import them to WebGPU

In Babylon.js we do need to invertY the texture in some cases so that our code works both in WebGL and WebGPU. When we need it (actually it's most of the time), we must do an additional pass to invertY the texture (requiring also a temporary texture), whereas it *seems* it would be very easy to add the options to the copyEITT function (there's already a render pass internally to perform the copy - at least in Dawn) and would be better for perf because the Y inversion would be done at copy time, so would be essentially free.

In Babylon.js we do see a difference in perf between WebGL and WebGPU when using a GUI which is updated each frame (so the source of copyEITT is a canvas) because of this additional render pass.

There's the same case to be made for preMultiplyAlpha, but even if only invertY can get in we would already be very happy!

**Comment by shaoboyan** [comment]
For `premultiplyAlpha`, I think current spec and implementation has already support it. Spec [here](https://gpuweb.github.io/gpuweb/#gpu-image-copy-texture-tagged)

**Comment by kainino0x** [comment]
@Popov72 what kind of canvas are you copying from? Is it rendered upside-down so that it will be right side up in WebGL?

Can you instead render it right-side-up and use `UNPACK_FLIP_Y_WEBGL` in WebGL instead?
As Ken points out, y-flips exist because of WebGL in the first place. So it's ideal if we can keep them confined to WebGL as much as possible (though we do have the concession in ImageBitmapOptions).

**Comment by Popov72** [comment]
The canvas we are using are created with `document.createElement("canvas")` and we use the 2D functions to draw things into it.

We are also accepting the user passing us an already created canvas, so if the canvas must be created/modified in a specific way it will unfortunately be a breaking change that we can't afford.

**Comment by kainino0x** [comment]
Hmm, I think my ideal solution would go through ImageBitmap so we don't have to support it generally here, allow making a y-flipped ImageBitmap from a canvas without async JS. Like a transferToImageBitmap() with a flipY option.

ImageBitmap finds itself in a weird intermediate place where it can (mostly) only be created asynchronously (with createImageBitmap) even though fundamentally the browser could give you an ImageBitmap handle before the async work is completed (just like transferToImageBitmap() or, say, createBuffer() -> GPUBuffer).

> We are also accepting the user passing us an already created canvas, so if the canvas must be created/modified in a specific way it will unfortunately be a breaking change that we can't afford.

If the user is supplying the canvas are they rendering it upside down?

I guess what I'm confused about is, what's the difference between a user providing a canvas vs providing a PNG file or HTMLImageElement? WebGPU should treat both as top-left origin. Is there something distinct about your canvas import path? Or are you using ImageBitmap flipY for images?

**Comment by Popov72** [comment]
The user can supply the canvas but Babylon is the one drawing into it/rendering it.

In WebGL we are using `texImage2D` to copy the canvas into the GPU texture, in WebGPU we are now using `copyExternalImageToTexture` (using the deprecated `copyImageBitmapToTexture` after a `createImageBitmap(canvas, options)` was quite slower than `copyExternalImageToTexture`).

In WebGL we are using the `UNPACK_FLIP_Y_WEBGL` option to invert Y the canvas, whereas in WebGPU we are doing an additional rendering pass.

**Comment by kenrussell** [comment]
@Popov72 , @kainino0x and I still don't understand one thing:

If you `copyExternalImageToTexture` from an `ImageBitmap` created from a `Blob` - without using `imageOrientation: 'flipY'`, it should have the same vertical orientation in your application as copying in an `HTMLCanvasElement`. Is that correct?

If it is, then it seems to me that:

- WebGL should be using `UNPACK_FLIP_Y_WEBGL` all the time, when uploading both `HTMLImageElement` and `HTMLCanvasElement`.
- WebGPU shouldn't need to use `imageOrientation` when creating `ImageBitmaps` for uploading textures, and also shouldn't need to vertically flip during `copyExternalImageToTexture` from `HTMLCanvasElement`. The WebGPU version may need to adjust texture coordinates or its fragment shader to get the correct vertical orientation of textures, but they should be consistent when uploading both images and canvases.

Am I missing something?

Do you have a smaller example more clearly showing the need for a y-flip option to `copyExternalImageToTexture`?

**Comment by Popov72** [comment]
> The WebGPU version may need to adjust texture coordinates or its fragment shader

That's the problem.

The only way we found to have everything working the same in WebGL and in WebGPU is to set `scaleY(-1)` on the canvas and add in all vertex shaders `gl_Position.y *= -1` at the end. Doing so make for a smooth transition to WebGPU as no change is required on the user side, their existing code that works in WebGL will also work in WebGPU. But one of the consequence is that we must invertY when we blit a GUI texture to match what WebGL is doing.

If now we try to get rid of `scaleY(-1)` and the change in the vertex shaders (tried [here](https://github.com/BabylonJS/Babylon.js/pull/10598)), that would (among other things) avoid the Y inversion when blitting the GUI texture but we are not backward compatible anymore, the user may have some changes to perform on their end to account for the change in the origin location of NDC (top left vs bottom left) and we also have a problem with the compressed textures that we need to invertY: we don't invertY in WebGL, so we must invertY in WebGPU but we can't because compressed textures are not renderable (and rendering to a non compressed texture to create an invertedY texture would defeat the purpose to use compressed texture in the first place). A fix would be to locate everywhere compressed textures are used and invert the Y texture lookup but it's just not possible as a user can pass any texture (compressed or not) they want to their/our shaders, so we would need to account for this in all texture lookups.

**Comment by shaoboyan** [comment]
By reading some docs of Babylon.js, I think the problem is that Babylon.js provided [an option named `invertY`](https://doc.babylonjs.com/typedoc/classes/babylon.rawtexture#constructor) when creating some types of `Textures in Babylon.js` which is part of the "Material". Am I right? @Popov72

**Comment by Popov72** [comment]
Indeed, `invertY` is true by default meaning all textures are Y inverted.

**Comment by kenrussell** [comment]
@Popov72 your mention of compressed textures has confused me.

As you mentioned, it is not feasible to y-flip compressed textures: neither at the application level, nor by the browser implementation itself.

Are you saying that `copyExternalImageToTexture` requires the y-flip option in order to treat those textures the same way as compressed textures?

It seems to me that leaving incoming textures alone (not y-flipping them) during `copyExternalImageToTexture` will keep consistent orientations between those textures, and compressed textures.

**Comment by kenrussell** [comment]
(...and, I recognize that WebGL and WebGPU would have differing texture orientations if no vertical flip were done during `copyExternalImageToTexture`. We're trying to understand the balance between maintaining complete compatibility with WebGL, and adding functionality - like vertical flipping during texture upload - which would be undesirable to maintain in the long term.)

**Comment by Popov72** [comment]
> Are you saying that copyExternalImageToTexture requires the y-flip option in order to treat those textures the same way as compressed textures?

No, I was mentioning the compressed textures case to explain we didn't find a mean to remove the canvas vScale(-1) + code injection at the end of vertex shaders without having some help from the user in some cases. In our current state (with vScale(-1) + code injection), compressed textures is not a problem but we do have some Y inversion to perform at runtime (each frame) that could be sped up by having this support directly in `copyExternalImageToTexture`.

**Comment by shaoboyan** [comment]
> Indeed, invertY is true by default meaning all textures are Y inverted.
My understanding is that `invertY default value = true` is for WebGL rendering backend because in Babylon.js y axis points up-side(texture coord) but in WebGL y axis points down-side(texture coord).
But in WebGPU rendering backend, the y axis also point up-side(texture coord). So would it possible that the default value of invertY changes to `false` for WebGPU rendering engine?

**Comment by Popov72** [comment]
> So would it possible that the default value of invertY changes to false for WebGPU rendering engine?

That's what we attempted here https://github.com/BabylonJS/Babylon.js/pull/10598 but we were not able to make it completely transparent for the user.

**Comment by kainino0x** [comment]
Resolution: Add a y-flip option. Several justifications from the folks on the call:

- Desire to ease transition from WebGL as shown by issues encountered by Babylon.js.
- Sometimes it may be slower to _not_flip Y, for example if the source is WebGL, or possibly some kinds of videos etc. Adding this gives control to users to do whatever is fastest. Implementations should consider issuing warnings when the slower path is hit.
- Performance of implementing this in the browser should be no worse than the performance of an application having to implement their own fullscreen-quad-based Y-flip (or similar). Performance warnings would guide people away from using this in lieu of changing their application to not need the Y-flip.

**Comment by kainino0x** [comment]
@kenrussell I know you weren't able to make it to the meeting, curious if you have further input.

@shaoboyan would you be interested in adding this to the spec? It should be a fairly small addition to GPUImageCopyExternalImage.

I'm not sure whether it should be `flipY: true` (more like WebGL), `imageOrigin: 'bottom-left'`, `originBottomLeft: true`, `imageOrientation: 'flipY'` (like ImageBitmapOptions), or what. Maybe a good starting proposal is `originBottomLeft: true`.

**Comment by shaoboyan** [comment]
@kainino0x I'll make a PR for this.

**Comment by shaoboyan** [comment]
BTW, I prefer `originBottomLeft: false` (We're copying from canvas/imageBitmap from the top-left so they could have the same result when rendering on the screen).

**Comment by kainino0x** [comment]
Yes, default value should be originBottomLeft false.

**Comment by kenrussell** [comment]
I trust the community group's conclusion. It's unfortunate that we couldn't simplify the API in this area but it's better for the browser to subsume these complications.
