### ISSUE TITLE
wgsl: support texture gather operations

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2327]
I think we meant to add these all along, but just missed them until now.

I'll follow up with an investigation of the support matrix/constraints. Revisiting @ben-clayton's initial work at https://github.com/ben-clayton/misc/blob/main/shader-texture-functions.md#gather

**Comment by dneto0** [comment]
Texture gather was already contemplated in API  discussions.  See https://github.com/gpuweb/gpuweb/issues/2094#issuecomment-950685343

**Comment by dneto0** [comment]
Investigation, copied from @ben-clayton's page.

## Gather

A gather returns 4 samples of a specified channel (r,g,b,a) for bilinear interpolation.

### Gather - 2D Texture

| Backend | Function                                                                                                                                                            | Comments |
|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| HLSL    | [`Texture2D.Gather[Red,Green,Blue,Alpha](sampler s, float2 coord[, int2 offset])`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texture2d-gatherred) |          |
| MSL     | `Tv texture2d.gather(sampler s, float2 coord[, int2 offset], component c = component::x)`                                                                           |          |
| SPIR-V  | [`OpImageGather <sampled-image> <coord> <component> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageGather)               |          |

### Gather - 2D Texture Array

| Backend | Function                                                                                                                                                                      | Comments                   |
|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|
| HLSL    | [`Texture2DArray.Gather[Red,Green,Blue,Alpha](sampler s, float3 coord[, int2 offset])`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texture2darray-gatherred) | Array index in `coord.z`.  |
| MSL     | `Tv texture2d_array.gather(sampler s, float2 coord, uint array[, int2 offset], component c = component::x)`                                                                   |                            |
| SPIR-V  | [`OpImageGather <sampled-image> <coord> <component> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageGather)                         | Array index in `coord[2]`. |

### Gather - Cube Texture

| Backend | Function                                                                                                                                                 | Comments |
|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| HLSL    | [`TextureCube.Gather[Red,Green,Blue,Alpha](sampler s, float3 coord)`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texturecube-gatherred) |          |
| MSL     | `Tv texturecube.gather(sampler s, float3 coord, component c = component::x)`                                                                             |          |
| SPIR-V  | [`OpImageGather <sampled-image> <coord> <component> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageGather)    |          |

### Gather - Cube Texture Array

| Backend | Function                                                                                                                                                           | Comments                   |
|---------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|
| HLSL    | [`TextureCubeArray.Gather[Red,Green,Blue,Alpha](sampler s, float4 coord)`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texturecubearray-gatherred) | Array index in `coord.w`.  |
| MSL     | `Tv texturecube_array.gather(sampler s, float3 coord, uint array, component c = component::x)`                                                                     |                            |
| SPIR-V  | [`OpImageGather <sampled-image> <coord> <component> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageGather)              | Array index in `coord[3]`. |

### Gather - 2D Depth Texture

| Backend | Function                                                                                                                                              | Comments |
|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| HLSL    | [`Texture2D.Gather(sampler s, float2 coord[, int2 offset])`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texture2d-gather)            |          |
| MSL     | `Tv depth2d.gather(sampler s, float2 coord[, int2 offset])`                                                                                           |          |
| SPIR-V  | [`OpImageGather <sampled-image> <coord> <component> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageGather) |          |

### Gather - 2D Depth Texture Array

| Backend | Function                                                                                                                                              | Comments                   |
|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|
| HLSL    | [`Texture2DArray.Gather(sampler s, float3 coord[, int2 offset])`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texture2darray-gather)  | Array index in `coord.z`.  |
| MSL     | `Tv depth2d_array.gather(sampler s, float2 coord, uint array[, int2 offset])`                                                                         |                            |
| SPIR-V  | [`OpImageGather <sampled-image> <coord> <component> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageGather) | Array index in `coord[2]`. |

### Gather - Cube Depth Texture

| Backend | Function                                                                                                                                              | Comments |
|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| HLSL    | [`TextureCube.Gather(sampler s, float3 coord)`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texturecube-gather)                       |          |
| MSL     | `Tv depthcube.gather(sampler s, float3 coord)`                                                                                                        |          |
| SPIR-V  | [`OpImageGather <sampled-image> <coord> <component> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageGather) |          |

### Gather - Cube Depth Texture Array

| Backend | Function                                                                                                                                              | Comments                   |
|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|
| HLSL    | [`TextureCube.Gather(sampler s, float4 coord)`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texturecube-gather)                       | Array index in `coord.w`.  |
| MSL     | `Tv depthcube_array.gather(sampler s, float3 coord, uint array)`                                                                                      |                            |
| SPIR-V  | [`OpImageGather <sampled-image> <coord> <component> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageGather) | Array index in `coord[3]`. |

## Gather Compare

### Gather Compare - 2D Depth Texture

| Backend | Function                                                                                                                                                              | Comments |
|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| HLSL    | [`Texture2D.GatherCmp(sampler s, float2 coord, float compare_value[, int2 offset])`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texture2d-gathercmp) |          |
| MSL     | `Tv depth2d.gather_compare(sampler s, float2 coord, float compare_value[, int2 offset])`                                                                              |          |
| SPIR-V  | [`OpImageDrefGather <sampled-image> <coord> <compare_value> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageDrefGather)     |          |

### Gather Compare - 2D Depth Texture Array

| Backend | Function                                                                                                                                                                        | Comments                   |
|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|
| HLSL    | [`Texture2DArray.GatherCmp(sampler s, float3 coord, float compare_value[, int2 offset])`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texture2darray-gathercmp) | Array index in `coord.z`.  |
| MSL     | `Tv depth2d_array.gather_compare(sampler s, float2 coord, uint array, float compare_value[, int2 offset])`                                                                      |                            |
| SPIR-V  | [`OpImageDrefGather <sampled-image> <coord> <compare_value> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageDrefGather)               | Array index in `coord[2]`. |

### Gather Compare - Cube Depth Texture

| Backend | Function                                                                                                                                                          | Comments |
|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|
| HLSL    | [`TextureCube.GatherCmp(sampler s, float3 coord, float compare_value)`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texturecube-gathercmp)        |          |
| MSL     | `Tv depthcube.gather_compare(sampler s, float3 coord, float compare_value)`                                                                                       |          |
| SPIR-V  | [`OpImageDrefGather <sampled-image> <coord> <compare_value> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageDrefGather) |          |

### Gather Compare - Cube Depth Texture Array

| Backend | Function                                                                                                                                                          | Comments                   |
|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|
| HLSL    | [`TextureCubeArray.GatherCmp(sampler s, float4 coord, float compare_value)`](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/texturecube-gathercmp)   | Array index in `coord.w`.  |
| MSL     | `Tv depthcube_array.gather_compare(sampler s, float3 coord, uint array, float compare_value)`                                                                     |                            |
| SPIR-V  | [`OpImageDrefGather <sampled-image> <coord> <compare_value> [image-operands...]`](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#OpImageDrefGather) | Array index in `coord[3]`. |

**Comment by dneto0** [comment]
The gather operation collects scalars from a specified component of
4 texels selected as per sampling with linear filtering. It yields a
4-element result vector.

* It always selects from the base level of the image view.
* Texture dimensionality is limited:
    *   Non-depth samples images:
        * texture_2d,
        * texture_2d_array,
        * texture_cube,
        * texture_cube_array
    *   Depth images, treated as only having one component:
        * depth_2d
        * depth_2d_array
        * depth_cube_array
        * depth_cube_array

*  Coordinates are supplied as usual for sampling, including array level when texture is arrayed.
*  Component selection is constexpr. e.g. HLSL embeds component in function name, e.g. 'Red' 'Green' 'Blue'
*  Integer coordinate offset supplied as usual, and optional. Provided as the optional last argument.


The gather-compare operation compares a depth reference value against four texels
in a depth texture, yielding a vec4&lt;f32&gt; with component being 0 when the depth
comparison fails, and 1 when it succeeds.

Operands are as for ordinary sampled textures, except:
* uses depth textures:
   * depth_2d
   * depth_2d_array
   * depth_cube_array
   * depth_cube_array
* uses a sampler_comparison
* don't specify a component, because there's only one component
* uses an f32 depth reference value, supplied after the coordinates



Design choice: provide these key variations:

*   textureGatherComponent: Explicit constexpr exponent. Non-depth textures
*   textureGather: Always selects the 0th component. Deptha and non-depth textures
*   textureGatherCompare: depth-reference sampling for depth textures


Schema for the proposed builtins:
```
textureGatherComponent(
  t: [texture_2d, texture_2d_array, texture_cube, texture_cube_array]
  s: sampler
  coordinate: (depends on t's type)
  array level, if array'd
  constexpr integer component
  optional constexpr offset: (depends on t's type)
) -> vec4<C> where C is the sampled component type

// pick out the 0'th component.
textureGather(
  t: [texture_2d, texture_2d_array, texture_cube, texture_cube_array
     texture_depth_2d texture_depth_2d_array texture_depth_cube texture_depth_cube_array]
  s: sampler
  coordinate: (depends on t's type)
  array level, if array'd
  optional constexpr offset: (depends on t's type)
) -> vec4<C> where C is the sampled component type, or vec4<f32> for depth texture

textureGatherCompare(
  t: [ texture_depth_2d texture_depth_2d_array texture_depth_cube texture_depth_cube_array ]
  s: sampler_comparison
  coordinate: (depends on t's type)
  array level, if array'd
  f32: depth_reference
  optional offset: (depends on t's type) -> vec4<f32>
```

**Comment by kvark** [comment]
The proposed design choices look very reasonable to me. Thank you and @ben-clayton for thinking about this!

**Comment by dneto0** [comment]
I'm in the middle of drafting and am struggling to find authoritative info about how Metal handles edge and corner sampling in cube maps.   I posted a comment at https://github.com/gpuweb/gpuweb/issues/2171#issuecomment-978002607 ; that's the issue trying to pin down seamless cube sampling.

Maybe I'm trying say too much about how sampling works; that probably belongs in the API spec.  But there's an interaction in that I have to write how to map the components from the four texels into the .xyzw components of the result.
