### ISSUE TITLE
shader programming model: signed integer representation

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#233]
Propose integer representation is two's-complement.

Affects the format of data transferred between host app and the shader.

- SPIR-V uses two's-complement
- Even C and  C++ are going this way.  https://twitter.com/jfbastien/status/989242576598327296 

Cc: @RobinMorisset

**Comment by RobinMorisset** [comment]
I am in favor of this proposal, I have not heard of any GPU that is not 2's complement.

**Comment by Kangz** [comment]
+1, every single GPU application out there assumes this representation.

**Comment by grorg** [comment]
Discussed at the [8 April 2019 meeting](https://docs.google.com/document/d/1UiIZ7G7iruGYntiLSmhc-wRPj1sN1CqNcPdgeG51r1U/edit)

**Comment by grorg** [comment]
Resolution was to use two's complement.

**Comment by Kangz** [comment]
Closing since this is resolved.
