### ISSUE TITLE
Module not found: Can't resolve 'stanford-dragon/4'

### ISSUE THREAD

**Issue by yangfangfang1204** [gpuweb/gpuweb#2337]
`Module not found: Can't resolve 'stanford-dragon/4'` 
i run the demo in `https://github.com/austinEng/webgpu-samples` ,first npm install , and npm start ,there is a error `Module not found: Can't resolve 'stanford-dragon/4` ?

**Comment by Jiawei-Shao** [comment]
Hi @yangfangfang1204 , I suggest you raise this issue to https://github.com/austinEng/webgpu-samples instead of here.

**Comment by yangfangfang1204** [comment]
ok ,thanks
