### ISSUE TITLE
Whether webGPU can render Yuv data directly to canvas

### ISSUE THREAD

**Issue by yangfangfang1204** [gpuweb/gpuweb#2338]
i decode the video to the yuv data by wasm ， and next i want to render the yuv data to canvas by WebGPU, so is it supported ? and is there some demo ?

**Comment by shaoboyan** [comment]
@yangfangfang1204  My understanding is that you've already got YUV datas in multiple `ArrayBufferView` and want to use WebGPU to do post-processing, right?
So my suggestion is that:
- Use [`writeTexture`](https://gpuweb.github.io/gpuweb/#dom-gpuqueue-writetexture) to upload your contents from `ArrayBufferView` to `GPUTexture`
- Start `ComputePipeline/RenderPipeline` to do the post-processing.

**Comment by yangfangfang1204** [comment]
Thanks for your reply . my question is not post-processing , just display YUV data on canvas . so is there some demo ?

**Comment by shaoboyan** [comment]
@yangfangfang1204 Sry but I don't know there is online demos. And I believe the steps are the same for rendering to canvas.
You need to do YCbCr->RGB conversion in your wgsl shaders.

If your video source could be presented by `HTMLVideoElement` or could be rendered to `HTMLCanvasElement`, then [`importExternalTexture`](https://gpuweb.github.io/gpuweb/#dom-gpudevice-importexternaltexture) or [`copyExternalImageToTexture`](https://gpuweb.github.io/gpuweb/#dom-gpuqueue-copyexternalimagetotexture) could help.

Sample to use `importExternalTexture` with `HTMLVideoElement`: [https://github.com/austinEng/webgpu-samples/blob/71d987b5b1a1bf8accaf9aa0ff431f60e2319a84/src/pages/samples/videoUploading.ts](https://github.com/austinEng/webgpu-samples/blob/71d987b5b1a1bf8accaf9aa0ff431f60e2319a84/src/pages/samples/videoUploading.ts)

But you still need to write some wgsl shader to render the content to canvas.
