### ISSUE TITLE
shader programming model: use little-endian layouts for scalar data

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#234]
Proposal: Use little-endian data layouts for scalar data

Affects the format of data transferred between host app and the shader.

Rationale:
- little-endian is common, but not universal.

Cc: @RobinMorisset

**Comment by grorg** [comment]
Discussed at the [8 April 2019 meeting](https://docs.google.com/document/d/1UiIZ7G7iruGYntiLSmhc-wRPj1sN1CqNcPdgeG51r1U/edit)

**Comment by grorg** [comment]
Resolution was to restrict to little-endian for now. If this becomes a problem later, we'll consider weakening the restriction.

**Comment by grorg** [comment]
(although @jdashg disagrees with the "less restrictive" comment)

**Comment by Kangz** [comment]
I'm not 100% sure if this has been written down. @dneto can this issue be closed?

**Comment by kdashg** [comment]
We think we are covered: https://gpuweb.github.io/gpuweb/wgsl/#internal-value-layout
