### ISSUE TITLE
wgsl: for texture coordinates, allow array index be appended to the coordinate vector

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2340]
D3D and Vulkan append the array index onto the coordinate vector.  When the coordinates are a floating point type, the integer array index is rounded.

* D3D:
   * Coordinates are always floating point
   * When converting the array index, uses round-to-nearest-even, then clamps the result the valid range. [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-to-sample#calculating-texel-positions) [D3D11 sample](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#inst_SAMPLE) [DXIL sample](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst#sample)
* Vulkan
    * Coordinates are floating point or integer (for with unnormalized samplers, or fetch/read/write)
    * When converting the array index, prefers round-to-nearest-even, but allows floor(x + 0.5) as an alternate.  Then the result is clamped to the valid range. [reference](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#textures-unnormalized-to-integer)

In Metal, the array slice index is supplied as an integer parameter, separate from texture coordinate.

WGSL currently has Metal's way of doing things.

Why does this matter:
* This is a porting barrier when translating existing D3D and Vulkan and OpenGL shaders to WGSL:  the translation has to insert a rounding step for the conversion for the array layer.
* Hardware ISAs seem to expect floating point:
     * [AMD Vega](https://developer.amd.com/wp-content/resources/Vega_Shader_ISA.pdf). 
           * The sampler state UNRM bit sets whether to use normalized (float in range [0,1])/unnormalized coordinates (integer).   Also if A16 bit is set, the address components are 16bits instead of 32 bits, and it explicitly says "Address components are 16-bit uint for image ops without sampler; 16-bit float with sampler"
           *  The x, y, and array "slice" index is supplied to sample and gather instructions (see 8.4 Image opcodes with a sampler) as part of the "body" sub-field (See 8.4.1 VPR Usage).
     * Intel GPUs [e.g. Kaby Lake](https://01.org/linuxgraphics/hardware-specification-prms/2016-intelr-processors-based-kaby-lake-platform).  In the [3DMedia-GPGPU](https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-kbl-vol07-3d_media_gpgpu.pdf) volume, page 133:    
     * > Parameter Types
sample*, LOD, and gather4 messages
For all of the sample*, LOD, and gather4 message types, all parameters are 32-bit floating point, except
the ‘mcs’, ‘offu’, and ‘offv’ parameters...
    * > SURFTYPE_2D: normalized ‘x’ coordinate; normalized ‘y’; coordinate; unnormalized array index
    * Note: mcs = multisample control; offu, offy are the integer texel coordinate offsets

So currently, for example:
```
textureSample(t: texture_2d_array, s: sampler, coords: vec2<f32>, array_index: i32)
```
and in the D3D/Vulkan/HLSL/GLSL/Intel/AMD convention:
```
textureSample(t: texture_2d_array, s: sampler, coords: vec3<f32>)
```

**Comment by kvark** [comment]
Oh no, if this is a concern, I wish we discussed it earlier than now.

> This is a porting barrier when translating existing D3D and Vulkan and OpenGL shaders to WGSL: the translation has to insert a rounding step for the conversion for the array layer.

Translating from GLSL and SPIR-V is indeed a little tricky. Good news is that it doesn't have to be optimal. We care more about conversion into SPIR-V/HLSL, and that's easier.

> Hardware ISAs seem to expect floating point:

This is particularly interesting. Do you expect there to be a noticeable effect on performance from the fact we need to do int->float conversion?

**Comment by ben-clayton** [comment]
I'm sure we discussed this and agreed it was preferable to have an explicit integer array index parameter. This is especially true as you've pointed out a portability hazard with specifying this as a f32:

> * D3D:
>   * When converting the array index, **uses round-to-nearest-even**, then clamps the result the valid range. [HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-to-sample#calculating-texel-positions) [D3D11 sample](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#inst_SAMPLE) [DXIL sample](https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/DXIL.rst#sample)
> * Vulkan
>   * When converting the array index, **prefers round-to-nearest-even, but allows floor(x + 0.5) as an alternate**.  Then the result is clamped to the valid range. [reference](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#textures-unnormalized-to-integer)

So indices with the value of `?.5` may produce different results on different hardware. What we have now avoids this.

> Why does this matter:
> 
> * This is a porting barrier when translating existing D3D and Vulkan and OpenGL shaders to WGSL:  the translation has to insert a rounding step for the conversion for the array layer.

It feels like a minor translation quirk, considering that WGSL is an entirely different syntax to HLSL / GLSL / MSL. If people need to bulk-translate, then they're likely to use a transpiler, in which case, who cares.

> * Hardware ISAs seem to expect floating point:

If we really found that this is a severe performance regression, it seems like something both tint and naga could optimise away for the common case of an explicit `f32` -> `i32` cast. This seems utterly negligible when considering robustness clamping we need to do on most backends.

---

If the proposal here is to change the signature - that's going to break a lot of pre-existing shaders.

If the proposal is to add more overloads - then we'd still have the halfway-between-integer hazard to deal with, and the unpleasantness of many more overloads. The overload concern would be far less severe if we supported named parameters for these builtins.

**Comment by dneto0** [comment]
* This was prompted because I noticed Tint's SPIR-V reader path wasn't doing the rounding. It was only truncating.
     * I fixed it and it now does i32(round(x))
     * Then I wondered how deep and wide it went.
* I don't know if there's a performance issue.  One could argue that 1-2 ALU operations are swamped by the fact you're going through image machinery (like the shared texture sampler on Intel)
* About optimizing it away.  Some compiler somewhere will need to see the pattern about where the value is going (into the last slot of a texture coordinate vector, and the value is type-conversion around rounding.  I suppose someone could write that optimization but I think nobody has done so.

**Comment by litherum** [comment]
I think allowing floating point array indices would mask bugs. It seems more robust to have the author explicitly cast to an integral type, which indicates that they know what they're doing, rather than the implementation silently doing it for them.

There are some places where the language can interpolate between different levels/slices - 3D textures, or mipmapped 2d textures, but arrays aren't one of those places. We should expose this difference in the type system.

**Comment by dneto0** [comment]
Discussed in [2021-11-30 meeting](https://docs.google.com/document/d/1dVE2hu9oYJvy34ASYnBf5B8fRHtq1Njy52k6Oi9N1uQ/edit#heading=h.4lw3n81sfpf2).

Decided to make no spec changes.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-30-Minutes#wgsl-for-texture-coordinates-allow-array-index-be-appended-to-the-coordinate-vector-2340">WGSL meeting minutes 2021-11-30</a></summary>



* DN: This was an offshoot of investigating GPU assembly languages
* DN: Was looking into the origin of the requirement that the texture offsets be integer constants. D3D and Vulkan both allow floats there. Happy to close this with no change as just an investigation.
* TR: D3D does allow integer coordinates, right?
* DN: Yes. WGSL allows only normalized coordinates for sampling operations, and integer (non-normalized) coordinates for texel loads and stores
* **CLOSED: no change**



</details>
