### ISSUE TITLE
describe the "sample footprint"

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2343]
This one of the "issues" in the WebGPU spec.

The textureGather* descriptions in WGSL (#2341 ) could be improved by referencing the concept of a sample footprint from the WebGPU spec.
Currently there's a bunch of distracting words in that PR to try to describe which texels are being gathered from.

**Comment by fintelia** [comment]
The exact details of which texels make up the sample footprint is [more subtle than you might first expect](https://www.reedbeta.com/blog/texture-gathers-and-coordinate-precision).

**Comment by eliemichel** [comment]
Shouldn't there be a builtin function that computes the interpolation weights corresponding to the 4 texels that are gathered, precisely to avoid the kind of crazy trouble reported by @fintelia 's link?

**Comment by kainino0x** [comment]
Generally speaking we only expose functionality we can get from at least some of the underlying languages (GLSL, HLSL, Metal shading language), but don't add "standard library" things that would be purely software additions. I don't know for sure if there is any underlying language for this kind of thing. If you want to discuss further can you file a separate issue? (This one is just to write some text in the spec)
