### ISSUE TITLE
spec: It is useful to allow GPUVertexBufferLayout.arrayStride to be less than offset + sizeof(attrib.format)

### ISSUE THREAD

**Issue by Axiverse** [gpuweb/gpuweb#2349]
There are cases where it is useful for arrayStride to be less than the attribute offset + sizeof(attribute.format). This is used in cases where we want overlap between previous and next elements.

An example use of this would be for line drawing where we may want the current point and the next point. The array stride would then be half the size of all the attributes. This would allow buffer elements [0, 1, 2, 3] to be read into the shader as [0, 1], [1, 2], [2, 3] when drawing three elements with an `arrayStride: 4` in this case. The buffer would have two attributes: `[{offset: 0, format: 'float32'}, {offset: 4, format: 'float32'}]`

In the [spec (ss. 10.3.7.1. Vertex Formats)](https://www.w3.org/TR/webgpu/#dom-gpuvertexbufferlayout-arraystride), this is not allowed due to:

```
Return true, if and only if, all of the following conditions are satisfied:
 - For each attribute attrib in the list descriptor.attributes:
  - attrib.offset + sizeof(attrib.format) ≤ descriptor.arrayStride.
```

Currently the chrome implementation does not allow this displaying error:
```
Attribute offset (32) with format VertexFormat::Float32x4 (size: 16) doesn't fit in the vertex buffer stride (32).
 - While validating attributes[2].
 - While validating buffers[1].
 - While validating vertex state.
 - While calling CreateRenderPipeline([RenderPipelineDescriptor]).
```

**Comment by Axiverse** [comment]
I'm current interested in using this to implement line rendering without duplicating vertices as in https://wwwtyro.net/2019/11/18/instanced-lines.html which is one of the places where this would be useful.

**Comment by Kangz** [comment]
This is basically the same as https://github.com/gpuweb/gpuweb/issues/1357. Unfortunately the restriction comes from Metal and we can't do much about it. However in that issue @kvark details how you can use two vertex buffers to do what you described.

**Comment by kvark** [comment]
Please let us know if you are blocked on this, considering the proposed paths forward!
