### ISSUE TITLE
spec: Last vertex buffer element should not be required to have the full stride size, instead only size of attribs.

### ISSUE THREAD

**Issue by Axiverse** [gpuweb/gpuweb#2359]
Chrome's implementation currently fails validation when the vertex buffer's last element is not the full stride size, even if the elements defined in the pipeline use only part of that stride. I have not yet found any definitions regarding this validation, perhaps there is one. If it's not defined, I propose that it be defined, and if defined to be the current behavior, perhaps we can update it if you agree with my statements here.

Example.

Buffer contains f32: `[1, 0, 2, 0, 3, 0, 4]` (size: 7 * 4 = 28 bytes)
Vertex buffer layout:
```
{
  arrayStride: 8, // 2 f32 elements,
  {
    shaderLocation: 0,
    offset: 0,
    format: 'float32',
  }
}
```

If I draw with 4 elements, the validation fails since the buffer contains less than the `count * arrayStride` (8 * 4 = 32 > 28) even though we have what all the defined attributes in the last element. Instead the validation should be `(count - 1) * arrayStride + max(attribs.map(attrib => attrib.offset + sizeof(attrib.format)))`

**Comment by kvark** [comment]
Looks like we are missing the validation spec for this, thank you for pointing out!
This would be draw-time validation (#1907), and I think what you are asking for is correct. To be 100% sure, we need to try this on the backend APIs and see if anything complains.

**Comment by Kangz** [comment]
If I remember correctly, it was a conscious choice to include the full last stride instead of only the relevant part. This was to simplify validation a bit, to not have to special case vertexCount / instanceCount = 0 and adding more logic in a very hot code path.

**Comment by kvark** [comment]
#1866 is where this was added

**Comment by Axiverse** [comment]
@Kangz if you precalculate the gap = (stride - maxSize) when creating the pipeline, you can only add one op. In the cases where 0 elements are drawn, it may be negative, but then it doesn't matter since there's no draw and the validation would still return true.

If buffers[slot].stepMode is:
"vertex"
(firstVertex + vertexCount) * stride - gap ≤ bufferSize.
"instance"
(firstInstance + instanceCount) * stride - gap ≤ bufferSize.

**Comment by kvark** [comment]
I added the tag to discuss this with the group. Also added the editors label since it was the editors call where we proposed to check it this simplified way, and this decision may need to change now.

**Comment by Axiverse** [comment]
I've also posted this related request. If the validation changes to support the case in this issue, it would make the other requested case possible as well. Based on the context of this bug, it seems that the restriction that stride >= maxSize is due to this simplified validation: https://github.com/gpuweb/gpuweb/issues/2349

**Comment by kainino0x** [comment]
> Also added the editors label since it was the editors call where we proposed to check it this simplified way, and this decision may need to change now.

We also did this explicitly with the thought that we could make it less strict later on without breaking changes. So yeah, let's discuss. (https://github.com/gpuweb/gpuweb/pull/1866#discussion_r656286148)

**Comment by kvark** [comment]
I did some experiments for this in https://github.com/kvark/wgpu/commit/ac05e790b2410509a79a0b0492fcf65a2eb6113b
Running on Metal, D3D12, and Vulkan, doesn't show any validation errors. So I think we should just fix the spec (and the CTS) to allow this.

**Comment by Kangz** [comment]
> @Kangz if you precalculate the gap = (stride - maxSize) when creating the pipeline, you can only add one op. In the cases where 0 elements are drawn, it may be negative, but then it doesn't matter since there's no draw and the validation would still return true.

Buffer sizes are `uint64_t` internally, though I guess we could assume we don't have buffers of size more than 2^63 and use `int64_t` for computations.

**Comment by kainino0x** [comment]
Loosening this is OK with me, I think we can find a way to make it not too costly.
