### ISSUE TITLE
dynamic offsets need to be divisible by 4 because of shader memory model atomicity guarantees

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#236]
```webidl
void setBindGroup(u32 index, GPUBindGroup bindGroup, optional sequence<u64> dynamicOffsets);
```

Those dynamicOffsets need to be divisible by 4 because of the memory model.

I'm just documenting this requirement here until we have a real spec and can start documenting this stuff properly.

**Comment by RobinMorisset** [comment]
A bit more precisely, we suspect they will have to be divisible by 4 to avoid mis-aligned accesses, that are unlikely to be atomic.

**Comment by Kangz** [comment]
I'm pretty sure they need to be divisible by 256 for NVIDIA hardware, see the constraints on `pDynamicOffsets` in the Vulkan spec.

**Comment by kvark** [comment]
To be more precise:
>Each element of pDynamicOffsets which corresponds to a descriptor binding with type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC must be a multiple of VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment

https://vulkan.gpuinfo.org/displaydevicelimit.php?name=minUniformBufferOffsetAlignment

We see a lot of hardware (mentioned NVidia) that wants 256 in there.

**Comment by litherum** [comment]
Does Vulkan place any restrictions on the value of `VkPhysicalDeviceLimits::minUniformBufferOffsetAlignment`? Can some future Vulkan implementation set that field to 7901 if it feels like it?

**Comment by kainino0x** [comment]
Per spec, minUniformBufferOffsetAlignment has a maximum value of 256.

**Comment by grorg** [comment]
Discussed at [18 Mar 2019](https://docs.google.com/document/d/16kKh2JGE-tgOBx61qZUAAB0x4u8rSJus-aSuSyib35Q/) teleconference

Resolution was % 256
