### ISSUE TITLE
Allow copying from any canvas that toDataURL can be called on

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2373]
Resolved in https://github.com/gpuweb/gpuweb/issues/2350#issuecomment-984234209 to expand the allowed sources of copyExternalImageToTexture to include any canvas that can normally be used as a source, i.e. anything that toDataURL() can be called on to get the actual canvas contents.

#2350 will expand it to allow "webgpu" canvases to be copy sources. This issue is to expand it further to be consistent with other types of canvases.

**Comment by kainino0x** [comment]
TBD exactly what sources actually can be used with toDataURL though. @jdashg said it might be unclear in the HTML spec, especially when it comes to "placeholder" canvases. Investigation is needed.

**Comment by Kangz** [comment]
Editors to make it happen.

**Comment by shaoboyan** [comment]
I think we need to add `ImageBitmapRenderingContext`  based on the [HTML spec]((https://html.spec.whatwg.org/multipage/canvas.html#imagebitmaprenderingcontext))and `placeholder` canvas here according to the HTML spec [notes](https://html.spec.whatwg.org/multipage/canvas.html#the-offscreen-2d-rendering-context) here:
_Implementations are encouraged to short-circuit the graphics update steps of the [window event loop](https://html.spec.whatwg.org/multipage/webappapis.html#window-event-loop) for the purposes of updating the contents of a [placeholder canvas element](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas-placeholder) to the display. This could mean, for example, that the commit() method can copy the bitmap contents directly to a graphics buffer that is mapped to the physical display location of the placeholder canvas element. This or similar short-circuiting approaches can significantly reduce display latency, especially in cases where the [commit()](https://html.spec.whatwg.org/multipage/canvas.html#offscreencontext2d-commit) method is invoked from a worker event loop and the window event loop of the [placeholder canvas element](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas-placeholder) is busy. However, such shortcuts cannot have any script-observable side-effects. This means that the committed bitmap still needs to be sent to the placeholder canvas element, in case the element is used as a [CanvasImageSource](https://html.spec.whatwg.org/multipage/canvas.html#canvasimagesource), as an [ImageBitmapSource](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#imagebitmapsource), or in case [toDataURL()](https://html.spec.whatwg.org/multipage/canvas.html#dom-canvas-todataurl) or [toBlob()](https://html.spec.whatwg.org/multipage/canvas.html#dom-canvas-toblob) are called on it._

**Comment by kainino0x** [comment]
I don't know exactly the behavior for placeholder canvases but it does indeed sound like we should support them. Thanks for finding that!

And yes I'm pretty certain the ImageBitmapRenderingContext should work.

Thinking about the HTML canvas spec a bit more (since now I'm a lot more familiar with it) I think basically we just need to remove all restrictions on the canvas type. Then we'll just depend implicitly on the behavior of the upstream spec in order to figure out when we get blank vs real images.

Would you open a PR to do this? I think it's just the 2 items in the validation:

> - If source.[source](https://gpuweb.github.io/gpuweb/#dom-gpuimagecopyexternalimage-source) is an [HTMLCanvasElement](https://html.spec.whatwg.org/multipage/canvas.html#htmlcanvaselement): Its [canvas context mode](https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-context-mode) must be "2d", "webgl", "webgl2", or "webgpu".
> - If source.[source](https://gpuweb.github.io/gpuweb/#dom-gpuimagecopyexternalimage-source) is an [OffscreenCanvas](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas): Its [OffscreenCanvas context mode](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas-context-mode) must be "2d", "webgl", "webgl2", or "webgpu".

**Comment by shaoboyan** [comment]
Can we close this issue?

**Comment by toji** [comment]
I think so.
