### ISSUE TITLE
Need to specify the order of dynamicOffsets in setBindGroup

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2392]
The order in which the dynamic offsets in setBindGroup are used is currently unspecified. We think we remember that the group decided that they should be ordered using the binding number of the buffers, but can't find where we agreed to that. That's what Dawn implements, but [wgpu seems to do something different](https://wgpu.rs/doc/wgpu/struct.RenderPass.html#method.set_bind_group):

> If the bind group have dynamic offsets, provide them in order of their declaration.

**Comment by kvark** [comment]
I believe we agreed to follow Vulkan convention here, which is the binding order.
That's how wgpu works, but the documentation wasn't right. I fixed the docs now.

**Comment by Kangz** [comment]
Great! It seems we just need to write the spec then :D

**Comment by kainino0x** [comment]
I was looking at this yesterday and I think the spec already does this in its algorithms:

> **Iterate over each dynamic binding offset** in bindGroup and run the following steps for each bufferBinding, bufferLayout, and dynamicOffsetIndex:
> - Let bufferDynamicOffset be dynamicOffsets[dynamicOffsetIndex].
> - ...

> To **Iterate over each dynamic binding offset** in a given GPUBindGroup bindGroup with a given list of steps to be executed for each dynamic offset:
> - ...
> - For each GPUBindGroupEntry entry in bindGroup.[[entries]]:
>     - ...
>         - ...
>         - Let dynamicOffsetIndex be dynamicOffsetIndex + 1

**Comment by Kangz** [comment]
Maybe it just needs to be called in the prose around `setBindGroup` then.

**Comment by kvark** [comment]
@kainino0x the point is that this ordering is wrong
> For each GPUBindGroupEntry entry in bindGroup.[[entries]]: 

Entries is a sequence provided by the user. Its order has nothing to do with ascending "binding".

**Comment by kainino0x** [comment]
Oh, sorry, I thought that was what you meant the behavior should be.

If it should be ordered by `binding` number then we do need a spec fix.
