### ISSUE TITLE
Vertex-only GPURenderPipelineDescriptor?

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#240]
In Metal, it's possible to set the fragment shader of a `MTLRenderPipelineDescriptor` to `nil`, which is used for things like depth-only occlusion passes. Do we want to allow this same thing in WebGPU?

**Comment by litherum** [comment]
First thought is "no" to keep the API simple. We can always relax this constraint later, but once the constraint is relaxed, we can't un-relax it.

**Comment by magcius** [comment]
You should *absolutely* be able to not run the rasterizer / FS. All underlying platform APIs support this and it's important for z-pre in forward renderers.

**Comment by litherum** [comment]
Okay, that's pretty compelling.

We need a spec.

**Comment by litherum** [comment]
I suppose we could document this by turning "GPUPipelineStageDescriptor fragmentStage;" into "GPUPipelineStageDescriptor? fragmentStage = null;"

Speaking of that, doesn't the spec need default values for all the other dictionary fields, too?

**Comment by litherum** [comment]
https://github.com/gpuweb/gpuweb/pull/241

**Comment by kvark** [comment]
@magcius 

> You should absolutely be able to not run the rasterizer / FS

Please don't confuse not having the fragment shader and not running the rasterizer at all. Without the rasterizer, there is no depth stage for z-pre.

As for the issue, it does makes sense to support null FS.

**Comment by grorg** [comment]
Discussed at [18 Mar 2019](https://docs.google.com/document/d/16kKh2JGE-tgOBx61qZUAAB0x4u8rSJus-aSuSyib35Q/) teleconference

**Comment by grovesNL** [comment]
I believe the [IDL allows this now](https://github.com/gpuweb/gpuweb/blob/c1c2a3c3986c5fec7e4d61e026ca53d75357e6ed/spec/index.bs#L574), should this be closed?

**Comment by kainino0x** [comment]
Yup, we agreed on this and added it.
