### ISSUE TITLE
maxInterStageShaderComponents is not enough

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2400]
In Metal (as well as OpenGL), there are 2 separate limits:
> Maximum number of inputs (scalars or vectors) to a 
fragment function, declared with the stage_in qualifier

This one is 32 on some platforms.
In GL, it's `MAX_VARYING_VECTORS`

>Maximum number of input components to a fragment 
function, declared with the stage_in qualifier

This one is 60 at least, which matches our limit.
In GL, it's `MAX_VARYING_COMPONENTS`

The implication of this is users not being able to have 40 scalars as an input to FS, even though we tell them 60 components are supported.

**Comment by Kangz** [comment]
I thought in WebGPU we say that each input to the FS counts for 4 components, irrespective of the size of the user-defined input, but actually that's just some validation we added in Dawn and isn't in the spec. That's because of Vulkan I believe. @Jiawei-Shao do you remember the details?

**Comment by Jiawei-Shao** [comment]
Yes @Kangz and @kvark.

According to [Vulkan SPEC (Table 18, "Shader Inputs and Outputs"](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-iointerfaces-locations):

> Each effective Location must have a value less than the number of locations available for the given interface.

> The number of available vertex output locations is `maxVertexOutputComponents / 4`, and the number of available fragment input locations is `maxFragmentInputComponents / 4`.

**Comment by kvark** [comment]
@Kangz if the spec is meant to say that, then this is going to be enough. I don't see where it says that right now.

**Comment by Kangz** [comment]
Tagging as needs spec then :)

**Comment by kainino0x** [comment]
If every inter-stage variable counts as 4 components, shouldn't we limit the number of variables instead of the number of components?

Or are there some things (builtins) which count for less than 4?

**Comment by Kangz** [comment]
Not that I know.

We could count the number of variables in the current state of the spec. TBH I hope we'll have more flexible in/out matching in the future as well as automatic packing of varyings since that's something that we can do for developers that saves them some potential friction. But myabe that's not a good enough reason to keep the component number for now.

**Comment by kvark** [comment]
I'm not excited to auto-pack varyings. They can have different interpolation qualifiers, after all, and types.

**Comment by kainino0x** [comment]
Well, if there's any potential need to count components instead of variables, we should just leave it as is.

**Comment by Kangz** [comment]
Ah I didn't think of the interpolation qualifiers. Auto-packing seems a bit less useful then (although in scalar ISAs, at least AMD, interpolation is done for each component indvidually). Either way sounds good then.

**Comment by kainino0x** [comment]
Absent any other reason to change it, then, I say we keep it how it is based on prior art.

**Comment by kvark** [comment]
I find this quite confusing for a limit. If components do matter, why having a rule that each fragment input has 4 components? Why making a limit that relies on such a rule? Given everything said in this thread, it sounds like we should just change the limit to talk about locations, not components.

**Comment by kainino0x** [comment]
Rereading the Vulkan text I'm not sure it's actually trying to say each vertex output / fragment input takes 4 components. I think it's actually saying there are two limits:

- The physical device limit maxVertexOutputComponents which isn't used directly for anything
- Maximum number of output variables, which is maxVertexOutputComponents / 4

I feel like there must be an underlying reason it was written like this but I agree it's very confusing.

**Comment by kainino0x** [comment]
(Same for maxFragmentInputComponents, it's also not used anywhere else)

**Comment by kainino0x** [comment]
@Jiawei-Shao's excellent investigation in https://github.com/gpuweb/gpuweb/issues/1962#issuecomment-1119517701
seems to reveal that in Vulkan, maxVertexOutputComponents really does put a limit on the number of components, not just maxVertexOutputComponents/4 putting a limit on the number of variables. So I think that prevents us from "refactoring" maxInterStageShaderComponents into maxInterStageShaderSlots or whatever.
