### ISSUE TITLE
spec: forbid infinite loops

### ISSUE THREAD

**Issue by amaiorano** [gpuweb/gpuweb#2414]
Both DXC and FXC fail to compile when they detect infinite loops. 

Given this simple wgsl shader:

```
[[stage(compute), workgroup_size(1)]]
fn main() {
  loop {}
}
```

Using tint to compile and validate with DXC:

```
$ out/build/x64-Debug/tint.exe ./infinite_loop.wgsl --validate --format hlsl
[numthreads(1, 1, 1)]
void main() {
  [loop] while (true) {
  }
  return;
}
error: validation errors
Function: main: error: Loop must have break. Use /Zi for source location.
Validation failed.
```

And compiling and validating with FXC:

```
$ out/build/x64-Debug/tint.exe ./infinite_loop.wgsl --validate --format hlsl --fxc
[numthreads(1, 1, 1)]
void main() {
  [loop] while (true) {
  }
  return;
}
C:\src\tint\Shader@0x00000276FDD4F920(3,10-21): warning X3557: loop doesn't seem to do anything, consider removing [loop]
C:\src\tint\Shader@0x00000276FDD4F920(3,10-21): warning X3551: infinite loop detected - loop writes no values
C:\src\tint\Shader@0x00000276FDD4F920(3,17-20): error X3696: infinite loop detected - loop never exits
```

As part of behaviour analysis, we can detect infinite loops. I think we should forbid them, and emit a compile error when they are detected.

**Comment by jdashg** [comment]
I think we only want to detect-and-error these to the extent that we are forced to by DXC and FXC.
Warnings in these cases is fine, but for portability reasons we should try to ensure that we minimize the cases where shaders compile on one platform but not another.
But also, I don't want to try harder here than we have to. It's always possible to write infinite loops, and we have TDRs for that, and I don't want to make authors fight false-positives in our detectors.

**Comment by ben-clayton** [comment]
> It's always possible to write infinite loops, and we have TDRs for that, and I don't want to make authors fight false-positives in our detectors.

The suggestion to adapt behavior analysis to forbid infinite loops would likely only result in errors when it's trivially detectable that there's no possible exit, but **not** erroring in cases where there's a more complex / conditional exit predicate.

If some backends will reject these types of shaders, and the worse case is to conservatively allow potential infinite loops, I think this proposal re-enforces the argument that we should _"try to ensure that we minimize the cases where shaders compile on one platform but not another."_

**Comment by alan-baker** [comment]
Doesn't the behaviour analysis already reject infinite loops like this? The function in the description has an empty set of behaviours which is not valid.

**Comment by ben-clayton** [comment]
> Doesn't the behaviour analysis already reject infinite loops like this? The function in the description has an empty set of behaviours which is not valid.

Humm, I think @alan-baker is right - good spot.
In which case, I think Tint's implementation is currently incorrect. Filed [crbug.com/tint/1347](https://bugs.chromium.org/p/tint/issues/detail?id=1347).

**Comment by kvark** [comment]
Sounds like resolved to me then. We've yet to implement the new behavioral analysis in wgpu, but @alan-baker 's finding reads as true to me.

**Comment by dneto0** [comment]
> Doesn't the behaviour analysis already reject infinite loops like this? The function in the description has an empty set of behaviours which is not valid.

I think that's not right. I think the spec currently allows the case:

* `loop { }` is the same as `loop { continuing { } }`
* Then use the first rule for loop:  
   * With conditions B1 empty, B2 empty:
        * s1: B1
        * s2: B2
        * None of {Continue, Return, Discard} are in B2
        * Break is not in (B1 ∪ B2)
   * Conclude that the behaviour of `loop { }` is the empty set.

* Function rules are:
    * the body must be valid by the rules.  Yes, so far.
    * the function has no return value, so second subrule does not apply
    * the body must have behaviour that is a subset of {Next, Return, Discard}. Satisfied because the empty set is a subset of that.

**Comment by dneto0** [comment]
I think the spec change is that each expression an each statement must have non-empty behaviour.
