### ISSUE TITLE
Consider exposing WebGPU as an ES6 module?

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#243]
ES6 modules have some pretty clear benefits:

https://medium.freecodecamp.org/javascript-modules-a-beginner-s-guide-783f7d7a5fcc
https://developers.google.com/web/fundamentals/primers/modules
https://eloquentjavascript.net/10_modules.html#h_hF2FmOVxw7

We should consider putting WebGPU in an ES6 module.

**Comment by kainino0x** [comment]
Fine with me, but are built-in modules (platform modules) specced and implemented yet? I thought they were not.

**Comment by grovesNL** [comment]
Could you clarify what it would mean to expose WebGPU as a module? Would WebGPU be available on the environment regardless?

Is there an example of a web API exposed like this that we could use as a reference?

**Comment by frzi** [comment]
The [Javascript Standard Library](https://github.com/tc39/proposal-javascript-standard-library) proposal is still in stage 1. Although [Chrome may be getting its first built-in module soon(-ish?)](https://developers.google.com/web/updates/2019/03/kv-storage). It could still take years for it to ship as stable in browsers.

That said, WebGPU seems like a great candidate to ship as a built-in module.

@grovesNL 
> Could you clarify what it would mean to expose WebGPU as a module? Would WebGPU be available on the environment regardless?
> 
> Is there an example of a web API exposed like this that we could use as a reference?

The new [KV Storage](https://github.com/WICG/kv-storage) will be the first built-in module available.

If WebGPU were to end up as a built-in module, developers would interact with the API as followed:
```js
import { requestAdapter, GPUBuffer } from 'std:gpu'

const adapter = requestAdapter({})

if (buffer instanceof GPUBuffer) {
  // ...
}
// etc...
```

For one, this would prevent the `window` scope from being 'polluted' (pardon the harsh term) with `GPU*` objects. But this also comes with a few other benefits as explained in the Google dev post.

**Comment by kainino0x** [comment]
If the release schedules line up I'm all for it.

**Comment by litherum** [comment]
Today we resolved to table this idea until the concept of native JS modules is more developed.

**Comment by kainino0x** [comment]
FYI, looks like KV Storage exists now:

https://developers.google.com/web/updates/2019/03/kv-storage

In Chrome 74+, behind chrome://flags/#enable-experimental-web-platform-features .

**Comment by Kangz** [comment]
I think the proposal for builtin modules in JS has been shelved so WebGPU can't use that pattern. Tentatively closing.
