### ISSUE TITLE
Dealing with CRLF and error line numbers

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#2435]
Maybe this is fine the way it is but I thought I'd bring it up if it hasn't been covered already. 

As it is, if I understand the spec, it requires that CRLF count as 2 lines.

Section 3.1 says a line comment ends at the first blackspace character that is not space or tab. So CR, LF,  VT, FT. That sounds like CRLF is 2 lines. This matters because [GPUComplicationMessage](https://www.w3.org/TR/webgpu/#gpucompilationmessage) has a lineNum.

Note that the browser seems to convert CRLF to just CR in .html files and script files but it's possible to load CRLF files via fetch

```
  const shaderSrc = await (await fetch('./shader.wgsl')).text();
```

I didn't see any other reference to end of lines.

You can just leave it the way it is but in that case Chrome is failing the spec as it's not counting those as 2 lines. And, conversely, if the spec stays the same, then if people load CRLF files, the emitted error line numbers will not match their editor.

**Comment by dneto0** [comment]
Either of \r or \n will terminate a line-ending comment, and won't be included as part of the comment.

> I didn't see any other reference to end of lines.

Right.
_Nothing else in WGSL says how to count lines._ 

So

          //foo\r\nbar

Can be two lines of source, with `//foo` being on line 1, and `bar` being on line 2.

Also, WGSL doesn't say if line or column numbers start at 1 or at 0
Tint's convention is both start at 1.


Maybe the group wants to pin things down *more* than what's there now?

**Comment by greggman** [comment]
To make this more concrete, imagine I wanted to implement a shader editor like shadertoy or glslsandbox I'd like to highlight lines with errors in my editor. I can't do that if I don't know how the lines are counted.

Recently I wanted to display errors inlined so for example

```
bla
bla
bla
line with error
bla
bla
```

I wanted to display as

```
bla
bla
bla
line with error
       ^^^

error:4:5: the error message

bla
bla
```

So wrote this code

```
  function showErrors(code, info) {
    const msgs = [...info.messages].sort((a, b) => a.lineNum - b.lineNum);
    const lines = code.split(/\n|\r|\f|\v/);
    const output = [];
    let hasError = false;
    let lineOffset = 0;
    let prevLineOffset = 0;
    lines.forEach((line, ndx) => {
      while (msgs.length && msgs[0].lineNum <= ndx) {
        const m = msgs.shift();
        hasError |= m.type === 'error';
        const offset = m.offset - prevLineOffset;
        output.push(`${''.padEnd(offset)}${''.padEnd(m.length, '^')}\n${m.type}:${m.lineNum}:${m.linePos}:${m.message}\n`);
      }
      output.push(line);
      prevLineOffset = lineOffset;
      lineOffset += line.length + 1;
    });
    for (const m of msgs) {
      hasError |= m.type === 'error';
      output.push(`${m.type}:${m.lineNum}:${m.linePos}:${m.message}`);
    }
    console[hasError ? 'error' : 'log'](output.join('\n'));
    return hasError;
  }
```

2 things came up writing that 

1. the CRLF issue. 

    I need my line count to match the API's line count

2. Sorting

    I needed the messages to be sorted by line number (the spec doesn't say they are sorted nor does it say they are not sorted)

I could use a different algo that didn't count on sorting but I think it would be nice if the spec either (a) required the results to be sorted or (b) mentioned that you can't count on them being sorted just so devs would know not to assume it.

**Comment by dneto0** [comment]
Got it.
I agree that for interoperability and predictability, W3C should specify how lines are counted.

Off the top of my head, I'd probably say that any sequence of \r before a \n should be considered as just a \n.
So  make this be ok:

       const lines = code.split(/\r*[\r\n\v\f]/)

As for the ordering .... that may be a taller order.  

I'd like @ben-clayton to weigh in on this.  He designed Tint's diagnostics, and I'm sure he'd have opinions.  Note that Tint's diagnostics can have 'notes' as well, which point all over the source.   (That may or may not be significant)

**Comment by kainino0x** [comment]
I also don't think they should be sorted. I wouldn't expect these errors to be sorted:

- line 14: Error: unknown symbol "baz"
- line 11: Note: Did you mean "bar" defined here?
- line 16: Error: Function does not return in all cases

**Comment by greggman** [comment]
Not sorting the errors is fine. I just think it would be nice if the spec had a note: "messages can be in any order. In particular they are **not** guaranteed be in ascending order by `lineNum`." or something to that effect.

**Comment by ben-clayton** [comment]
I'd be happy to see `CRLF` treated as a single newline. I'd probably just opt for treating `\r\n` or `\n` as a newline, so something simple like: `\r?\n` as the regex.


> As for the ordering .... that may be a taller order.
> 
> I'd like @ben-clayton to weigh in on this. He designed Tint's diagnostics, and I'm sure he'd have opinions. Note that Tint's diagnostics can have 'notes' as well, which point all over the source. (That may or may not be significant)

Right. Tint has a pattern where we have the primary error message as the first `error:` level diagnostic, and then sometimes follow up with a bunch of `note:` diagnostics to point you at relevant places for the error. This repeats with possibly more `error:`s (and maybe more `note:`) diagnostics. These notes can be out of order. Errors will (usually) be in sorted order, but we make no guarantees about this.

**Comment by kainino0x** [comment]
Opened #2451 to address half of this issue.

**Comment by mehmetoguzderin** [comment]
This new issue https://github.com/gpuweb/gpuweb/issues/2758 might be relevant to this.

**Comment by kdashg** [comment]
Between https://github.com/gpuweb/gpuweb/pull/2451 and https://github.com/gpuweb/gpuweb/issues/2758 I think this is settled? Reopen if not!
