### ISSUE TITLE
wgsl editorial: "entry point IO types" are not types

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2442]
I think this is an awkwardness left over from reworking pipeline I/O to entry point formal parameters and return types.

> The **Entry point IO types** include the following:
> * Built-in variables. See § 9.3.1.1 Built-in Inputs and Outputs.
> * User-defined IO. See § 9.3.1.2 User-defined Inputs and Outputs
> * Structures containing only built-in variables and user-defined IO. The structure must not contain a nested structure

A "builtin variable" is not a type, for example.

**Comment by alan-baker** [comment]
No longer an issue.
