### ISSUE TITLE
The link of "WebGPU Playground" in wiki Implementation-Status is not correct

### ISSUE THREAD

**Issue by kylexu** [gpuweb/gpuweb#2448]
The link of "WebGPU Playground - a student project at Imperial College London" in wiki [Implementation-Status](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status) is not correct.
The link address should be: https://webgpu-playground.netlify.app, while it is https://github.com/gpuweb/gpuweb/wiki/webgpu-playground.netlify.app at the moment.

**Comment by kvark** [comment]
Done
