### ISSUE TITLE
Allow float modulo for scalar-vector and vector-scalar

### ISSUE THREAD

**Issue by amaiorano** [gpuweb/gpuweb#2450]
Currently in the spec, division and modulo are non-orthogonal: float division is defined for scalar-vector and vector-scalar, but float modulo is not.

We can see this non-orthogonality in section [6.9. Arithmetic Expressions](6.9. Arithmetic Expressions):

For scalar-scalar and vector-vector, division and modulo are effectively the same:

![image](https://user-images.githubusercontent.com/6893883/147125702-1a3a3dec-cd1a-44c0-9dea-d18fba77ab67.png)

But for mixed scalar-vector and vector-scalar, modulo is separate and only defined for i32 and u32:

![image](https://user-images.githubusercontent.com/6893883/147125794-25ae90e7-b5e0-4358-86b2-194cb9b7378c.png)

Since we already define float modulo for scalar-scalar and vector-vector, why not define it for the mixed versions?

**Comment by dneto0** [comment]
Discussed in 2022-01-11 meeting. [bookmark](https://docs.google.com/document/d/1CQcjcdDA0anAtw08KyUnSXbhfb6cMYs03X8GZaIyKRQ/edit#bookmark=id.9yo88nfza899)
Agreed to add this.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2022-01-11-Minutes#allow-float-modulo-for-scalar-vector-and-vector-scalar-2450">WGSL meeting minutes 2022-01-11</a></summary>



* DM: Didn’t we have a reason for mod-float being different?
* DN: We *had* concerns but we addressed those already.
* MM: Our preference for consistency.
* **Spec needed**


</details>
