### ISSUE TITLE
MSAA and resolve capabilities need to be specified

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2459]
It just occurred to me that Metal doesn't support MSAA on some of the formats, contrary to #108

See https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf
For example, `RG32Float` doesn't support MSAA. `RGBA16Unorm` supports MSAA but not being a resolve target.

Related to #932 and #2458 

A strawman suggestion is to add 2 columns to the texture format capabilities (of color formats):
  - one for MSAA to be supported
  - one for the resolve target to be supported

**Comment by kainino0x** [comment]
Don't the render target and resolve target always have to have the same type? So we would only need one column in the table (#2408)

**Comment by kainino0x** [comment]
Ah, maybe there are color formats that can be multisampled but can't be resolved (like depth). Two columns is fine regardless.

**Comment by kainino0x** [comment]
Details that occurred to me while looking at#2458:

> * one for MSAA to be supported

Validated in createTexture

> * one for the resolve target to be supported

Validated in `GPURenderPassColorAttachment Valid Usage` if we add a column for it

**Comment by kainino0x** [comment]
Nvm I see you already did all that :P
