### ISSUE TITLE
device.queue.writeBuffer with sharedArrayBuffer not working

### ISSUE THREAD

**Issue by lslzl3000** [gpuweb/gpuweb#2460]
Browser: Chrome 99+
OS: Mac OS 12

In [spec queues](https://www.w3.org/TR/webgpu/#queues), it should be ok to use `sharedArrayBuffer` in `writeBuffer`.
But on my test, Chrome shows `TypeError: Failed to execute 'writeBuffer' on 'GPUQueue': parameter 3 is not of type 'ArrayBuffer'.`

Is that chrome not implement [Allowshared] yet? or any coding problem?

**Comment by lslzl3000** [comment]
~~ tested in `Chrome Canary 99.0.4785.0`, it is working with `sharedArrayBuffer` now.
So probably, `[Allowshared]` was not implemented before `Chrome Canary 99.0.4785.0`

**Comment by kainino0x** [comment]
Glad your issue got resolved. In the future, please file browser-specific issues against the browser, as requested by the issue templates. Thanks!
