### ISSUE TITLE
Behavior of endPass() and pass commands after pass has ended

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2464]
#2264:

> While working on #2452 I found I would like to extend this to passes as well: once a pass has ended, attempting to encode commands generates a validation error instead of marking the encoder as invalid.
> 
> This is nice because it means invalid commands can just "locally" make their pass encoder invalid instead of needing a way to reach out to the top-level encoder and make that invalid after endPass() has already happened.

In #2452 I changed the behavior and then forgot about it before landing it.

So we have to determine: when you endPass() or encode a pass command after a pass has ended:

1. (Before 2452) silently make the top-level encoder invalid? (This is exceptional if you consider validity to be local to the pass, and in 2452 I've made it so pass commands don't otherwise affect the top-level encoder)
2. (After 2452) generate a GPUValidationError? (This is exceptional if you consider "pass must be open" to be just another validation rule rather than a special rule in encoding pass commands)

**Comment by kainino0x** [comment]
Er, extends to to commands as well, not just endPass. Updated text.

**Comment by kainino0x** [comment]
Editors: IIUC we're inclined to keep the post-2452 behavior even though it's going to have a little bit of implementation cost (more for wgpu than for Dawn, we think). Our reasoning: An invalid command can't reach out and break a GPUCommandBuffer after finish(), so it also shouldn't be able to reach out and break a GPUCommandEncoder after endPass().

However this is not a very important change and we'd be willing to add back the spec complexity for this "reaching out" behavior. (It's just annoying to spec because, as written after 2452, commands are "localized"/"encapsulated" - they don't need to understand what their toplevel encoder is, e.g. render commands don't care if it's a render pass or render bundle encoder.)

@Kangz WDYT, from an implementation perspective mainly? I'm pretty sure in Dawn this is a trivial change. (validation error instead of invalidating encoder)

**Comment by Kangz** [comment]
Yeah in Dawn it would be an easy change. No concerns here.

**Comment by kainino0x** [comment]
Editors: Closing due to no further comment.

**Comment by lokokung** [comment]
Removing 'needs-cts-issue' label as it seems we are already using https://github.com/gpuweb/cts/issues/1914 to track CTS tests. Most of the functionality relating to errors on pass ends also already seem to be implemented.
