### ISSUE TITLE
Why are bind group layout fields spelled differently from their WGSL counterparts?

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#2469]
https://gpuweb.github.io/gpuweb/#abstract-opdef-default-pipeline-layout

As an example:
     
> Else if the sampled type of resource is:
>    * f32 and resource is statically used with a textureSample* builtin in the shader
>        Set textureLayout.sampleType to "float"
>    * f32 otherwise
>        Set textureLayout.sampleType to "unfilterable-float"
>    * i32
>        Set textureLayout.sampleType to "sint"
>    * u32
>        Set textureLayout.sampleType to "uint"

Is there a reason why the WGSL type name is "u32", and the bind-group-layout type name is "uint"? Making these more similar would help reduce cognitive load when translating layouts between shaders and the API.

**Comment by Kangz** [comment]
I think it's because the name for BGLs were discussed before WGSL types were stabilized. We could rename IMHO if we are confident that there won't be an `f16` texture sample type. (were the texture unit only returns an f16 and not an f32).

**Comment by kvark** [comment]
I don't think it's worth it. "sampleType" can also be "depth", it's larger than just WGSL type:
  - "float", "unfiterlable-float" = `texture_xxx<f32>`
  - "sint" = `texture_xxx<i32>`
  - "uint" = `texture_xxx<u32>`.
  - "depth" = `texture_depth_xxx`.

**Comment by magcius** [comment]
s vs. i feels inconsistent.

**Comment by Kangz** [comment]
We could go with `u32` `i32` `f32` `unfilterable-f32` and `depth` to match WGSL. (extremely slight preference for this option)

Or ignore the inconsistency.

**Comment by Kangz** [comment]
Discussed this in the group and decided to keep the current names. The strongest argument is that encoding "32" in the names wouldn't make sense because the BGL doesn't care about the width. About "sint" vs. "int" we already use "sint" in the name of vertex formats.

So this was all around a meh. and a preference to not change for the sake of changing.
