### ISSUE TITLE
Clear color: float, i32, u32

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#247]
Clear color should support float, i32, and u32. Right now in the IDL, it takes float only.
This means when we clear an integer texture, it has to convert the float to i32 or u32. But float can't represent all i32 or u32 values.

We can probably support this by just changing the IDL to take `double` and doing appropriate conversions internally.

https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#clears-values

**Comment by prideout** [comment]
Looks like this was fixed by #355, but does this also need to be done to the stencil masks?

**Comment by kvark** [comment]
Thanks for triaging, @prideout !
FYI, stencil masks are u8 only.

**Comment by kainino0x** [comment]
Oops, thanks for spotting that this should be closed.

Stencil formats are always integers (and in fact we only have one stencil format, u8); what field might need to be updated?

**Comment by kainino0x** [comment]
Whoop, page didn't reload. Sorry for duplicate.
