### ISSUE TITLE
Why is WGSL verbose?

### ISSUE THREAD

**Issue by Jerrody** [gpuweb/gpuweb#2471]
Why am I asking about it? Let's look at this example of code:

```rust
struct VertexInput {
    [[location(0)]] position: vec3<f32>;
    [[location(1)]] color: vec3<f32>;
};

struct VertexOutput {
    [[builtin(position)]] clip_position: vec4<f32>;
    [[location(0)]] color: vec3<f32>;
};

[[stage(vertex)]]
fn vs_main(
    model: VertexInput,
) -> VertexOutput {
    var out: VertexOutput;
    out.clip_position = vec4<f32>(model.position, 1.0);
    out.color = model.color;

    return out;
}

[[stage(fragment)]]
fn fs_main(in: VertexOutput) -> [[location(0)]] vec4<f32> {
    return vec4<f32>(in.color, 1.0);
}
```

This is an example of code from WGPU Learn. So, what do we see? What's wrong mate?
I will do a list of what I saw verbosity:
1.`[[location(0)]]`, why can't we just write [location(0)]? And specify a few attributes with a comma? Also the same with everything that has `[[<...>]]`.
2. Maybe SSwahis is my preference, but why can't we use Rust's style return, like `vec4<f32>(in.color, 1.0)` instead of return `vec4<f32>(in.color, 1.0);`.
3. Input parameters, everything is alright, but maybe for developer doesn't need to write a comma for the last parameter?
About structs, maybe don't need to write `;` after `}`. `}` tells that this is the end of defining a struct.

So, this is my opinion, but this issue is directed to the more clear and less verbose syntax of WGSL that I so much like.

New syntax with my suggestions:
```rust
struct VertexInput {
    [location(0)] position: vec3<f32>;
    [location(1)] color: vec3<f32>;
}

struct VertexOutput {
    [builtin(position)] clip_position: vec4<f32>;
    [location(0)] color: vec3<f32>;
}

[stage(vertex)]
fn vs_main(
    model: VertexInput,
) -> VertexOutput {
    var out: VertexOutput;
    out.clip_position = vec4<f32>(model.position, 1.0);
    out.color = model.color;

    out
}

[stage(fragment)]
fn fs_main(in: VertexOutput) -> [location(0)] vec4<f32> {
    vec4<f32>(in.color, 1.0)
}
```

**Comment by ben-clayton** [comment]
> 1.`[[location(0)]]`, why can't we just write [location(0)]?

Discussed in https://github.com/gpuweb/gpuweb/issues/2243. We are still considering the decoration syntax.

> And specify a few attributes with a comma?

Multiple attributes can be specified within the `[[` and `]]` using commas.

> 2. Maybe SSwahis is my preference, but why can't we use Rust's style return, like `vec4<f32>(in.color, 1.0)` instead of return `vec4<f32>(in.color, 1.0);`.

Has been discussed a few times, but I'm uncertain whether this is likely to be agreed for MVP / V1.

> 3. Input parameters, everything is alright, but maybe for developer doesn't need to write a comma for the last parameter?

They do not. Trailing commas are optional.

> About structs, maybe don't need to write `;` after `}`. `}` tells that this is the end of defining a struct.

Agreed. This is part of a set of changes Google is likely to propose in the near future.

Also: https://github.com/gpuweb/gpuweb/pull/2305 landed at the end of last year, so `vec4<f32>(model.position, 1.0)` can be reduced to `vec4(model.position, 1.0)`. This will be available in [Chrome in M99](https://dawn.googlesource.com/tint/+/refs/heads/main/docs/origin-trial-changes.md), or in Chrome Canary now. I do not know when this will be available in Firefox.

**Comment by Jerrody** [comment]
> > 1.`[[location(0)]]`, why can't we just write [location(0)]?
> 
> Discussed in #2243. We are still considering the decoration syntax.
> 
> > And specify a few attributes with a comma?
> 
> Multiple attributes can be specified within the `[[` and `]]` using commas.
> 
> > 2. Maybe SSwahis is my preference, but why can't we use Rust's style return, like `vec4<f32>(in.color, 1.0)` instead of return `vec4<f32>(in.color, 1.0);`.
> 
> Has been discussed a few times, but I'm uncertain whether this is likely to be agreed for MVP / V1.
> 
> > 3. Input parameters, everything is alright, but maybe for developer doesn't need to write a comma for the last parameter?
> 
> They do not. Trailing commas are optional.
> 
> > About structs, maybe don't need to write `;` after `}`. `}` tells that this is the end of defining a struct.
> 
> Agreed. This is part of a set of changes Google is likely to propose in the near future.
> 
> Also: #2305 landed at the end of last year, so `vec4<f32>(model.position, 1.0)` can be reduced to `vec4(model.position, 1.0)`. This will be available in [Chrome in M99](https://dawn.googlesource.com/tint/+/refs/heads/main/docs/origin-trial-changes.md), or in Chrome Canary now. I do not know when this will be available in Firefox.

Alright then!

**Comment by ben-clayton** [comment]
Thank you for all the suggestions. Feedback like this is really valuable. 👍🏼

**Comment by mehmetoguzderin** [comment]
I do not want to sound overarching, but since post-close comments and this kind of relevancy exist, it might be helpful to keep the https://github.com/gpuweb/gpuweb/issues/2243 issue open since, at the moment, unless the query explicitly opts in to look up closed ones, it won't pop up. (And it also tracks the `@` option, which seems more optimal per metrics like avoiding redundant ways to express one idea and number of characters and this being a thing in various languages, and not subjectively)

**Comment by kvark** [comment]
See also - https://github.com/gfx-rs/wgpu/discussions/2354

**Comment by litherum** [comment]
If ; is required after a struct, we should definitely relax that requirement.

I generally dislike the "struct Foo { ... } bar; syntax from C. Given we don't have anonymous structs (I think?) the desire for this kind of thing is probably low.
