### ISSUE TITLE
depthOrArrayLayers

### ISSUE THREAD

**Issue by unconed** [gpuweb/gpuweb#2489]
`GPUExtent3D` is defined as `{ width, height, depthOrArrayLayers }`.

This seems about as sensible as having `GPUOrigin3D` be `{ x, y, zOrArrayIndex }` instead of `{ x, y, z }`. Why not just `depth`?

**Comment by kvark** [comment]
Context of the discussion is in #1390. This has been discussed quite a bit!

**Comment by kainino0x** [comment]
FYI you can use the sequence overload and then you don't need to type out `depthOrArrayLayers`: `[2, 3, 4]`

I don't think we're going to change this but we'll decide whether to close this in the editors' meeting.

**Comment by kvark** [comment]
@unconed we briefly talked about this on the editors call. We agree there is a but of inconsistency between `GPUExtent3D` and `GPUOrigin3D` when it comes to Z. We also consider the previous work in #1390 to be valuable, and we want it to stay.
So there is a tiny question of whether or not to rename `GPUOrigin3D::z` to `GPUOrigin3D::zOrArrayIndex`. If I read you correctly, it's not something you'd really want happening, is it?
From my perspective, the important aspect here is educational. Before using the origin, one has to use the extent, and that's where they realize that the same value may represent both array layers and depth. So after seeing `depthOrArrayLayers` they may be ready to treat `GPUOrigin3D::z` correctly, and screwing this up is unlikely. Therefore, a practical tradeoff I see is keeping the current naming in place.

**Comment by unconed** [comment]
The pedagogical argument seems, frankly, absurd to me given the amount of esoterica one has to deal with in WebGPU.

You're worried that people are somehow not going to understand the concept of a 2+1D layered array... in an API that requires you to understand:
- C-like struct alignment rules, which differ by UBO, SSBO and Vertex (and how vec3 is an exception)
- numbered bindings and descriptor sets
- a bunch of different buffer types and semantics
- different type systems for uniforms vs attributes
- non dynamically uniform indexing in shaders
etc etc

Like, I'm completely stunned that you had the sensible name first and then you replaced it with the ridiculous, long one. And you've had multiple conversations about this too???

Wtf. Autism, not even once.

**Comment by kvark** [comment]
I'd be willing to elaborate further if not the last sentence, which seems unnecessarily offensive. Please consider changing your attitude, the current one is not welcome.
