### ISSUE TITLE
struct decl should not have to be followed by a semicolon

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2492]
One of the grammar productions is:

```
global_decl:
    struct_decl semicolon
```

That semicolon serves no purpose.
The end of the struct declaration is already signaled by the right-brace `}` that terminates the list of members.

**Comment by kvark** [comment]
This was previously requested in #2471 and #1466. I think it's a good change!

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-01-18-(apac)-minutes#struct-decl-should-not-have-to-be-followed-by-a-semicolon-2492">WGSL meeting minutes 2022-01-18</a></summary>



* PR [#2499](https://github.com/gpuweb/gpuweb/pull/2499)
* **Agree to merge.**


</details>
