### ISSUE TITLE
remove stride attribute

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2493]
An explicit stride attribute is an aid to translation from SPIR-V, and an aid to porting GLSL shaders using std140 buffer layout.

The explicit stride has been controversial, and comes at a cost to the WGSL spec, including some unresolved items
Eg. #1534  #1943

After Google-internal discussion we propose to remove the `stride` attribute.  We would keep the uniform-buffer layout rules.  So shader authors would still have to satisfy the rules, but use other means to satisfy them.

Example:

Before: 

	type A = [[stride(16)]] array<i32,10>;
	…
            var a : A;
            A[10] = 1;
            f( &A[4] );

Workaround 1: expand the element type:

     	type A = array<vec4<i32,4>,10>;  // vector to get to target size.
				//  But we can’t take address of component in this case.
          ...
            var a: A;
            A[10][0] = 1;
            f( &A[4][0] );

Workaround: use struct with size on element:

    	struct elem { [[size(16)] e:  i32; };
     	type A = array<elem,10>; 
	…
            var a: A;
            A[10].e = 1;
            f( &A[4].e );

**Comment by kvark** [comment]
Workaround 2 is really neat in that it doesn't require anything from the language to be done. Let's remove `[[stride]]` then!

**Comment by RobinMorisset** [comment]
I'd be happy to see the stride attribute gone, especially as it is a source of ambiguity in the grammar.

**Comment by litherum** [comment]
yes please

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-01-18-(apac)-minutes#remove-stride-attribute-2493">WGSL meeting minutes 2022-01-18</a></summary>



* [PR #2503](https://github.com/gpuweb/gpuweb/pull/2503)
* Agree to land.


</details>
