### ISSUE TITLE
Structure/array size rules are repeated in the spec

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2497]
"Alignment and Size" and "Structure Layout Rules" sections repeat the same equations for `AlignOf(S)` and `SizeOf(S)` of structs and arrays. Is it necessary to repeat ourselves?

When I'm reading it, my first thought is "since the rules are spelled out in this specific section, they might be specialized, and I need to use them instead". Then I'd read the rules a few times only to conclude that these are the same equations exactly. So I find it confusing and unnecessary.

**Comment by dneto0** [comment]
I agree there is some redundancy.  The table gives the alignment and size of the entire type.
But the extra sections do spell out layout of interior items
- array element i is at strideof(..) * i
- structure member offset definitions.

Also, things are somewhat complicated by having user-controllable strides.  I'm proposing to remove that #2493, so the array will simplify from that. 

I think there is opportunity to streamline even more.  Maybe enough of it melts away that whatever necessary text can be folded into the more simply structured ["internal layout" section](file:///Users/dneto/project/gpuweb/wgsl/index.html#internal-value-layout).

Thanks for highlighting this.
