### ISSUE TITLE
Where do we spec WebGPU-WebCodecs interaction?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2498]
Extracted from #2124.

I proposed spec text in https://github.com/w3c/webcodecs/pull/412 which put it in WebCodecs. WebGPU group was OK with this direction if the WebCodecs group accepted it.

---

Feedback on https://github.com/w3c/webcodecs/pull/412 has been negative on including this functionality in WebCodecs when it is clearly a part of WebGPU that interacts with WebCodecs and not the other way around. From that thread:

> It's fine not to implement a specification in its entirety, it's fairly common.

Though I agree this is common, I know Apple has taken a hard stance against this as they intend to implement 100% of the WebGPU spec with no omissions. @litherum how do you view the tradeoff between that intent and the problem of "monkey patching" WebGPU from the WebCodecs spec?

**Comment by dalecurtis** [comment]
FWIW, `VideoFrame` is already referenced in the HTML and WebGL specs. A method signature which takes a typedef of HTMLVideoElement or VideoFrame seems pretty harmless for specifying type specific interactions.

**Comment by kdashg** [comment]
Post V1 please!

**Comment by kainino0x** [comment]
Depending on the resolution to #2301 I'm happy to just put this in an extension doc in our repo. Ideally I'd like to land a draft _somewhere_ and that seems like a nice place for it, if we allow this kind of thing in that directory.
