### ISSUE TITLE
Transpilation

### ISSUE THREAD

**Issue by grovesNL** [gpuweb/gpuweb#25]
Transpilers are listed as one of the primary target audiences [in the charter](https://gpuweb.github.io/admin/cg-charter.html#target-audience):

> Developers of 3D and game engines/tools that are producing Web content via transpilation. For example, Unity and the Unreal Engine use emscripten to compile content for the Web.

How can we ensure that we design an API that supports this audience? Unless we shape the WebGPU API to match a specific native API, it may add a lot of burden on the transpiler (i.e. emscripten) to reorganize native API calls to fit the WebGPU API. In some cases this may not even be possible depending on the final shape and requirements of the WebGPU API.

As a trivial example, we've already decided to enforce begin/end various types of commands such as `{Begin|End}Compute` to better support Metal's encoders. So if a Vulkan application will be transpiled into a WebGPU application, the transpiler will need to insert these methods at the appropriate locations. In this example:

- the transpiler may be able to deal with this pessimistically (i.e. cause many encoder switches in Metal which is what we were attempting to avoid), or
- depending on the API requirements it may not even be possible (i.e. if there are certain constraints in which these begin/end commands may be invoked)

This one additional requirement will probably be dealt with fine, but I'm concerned about the aggregate impact these API shape and requirement changes may have.

Is it reasonable for us to agree to shape the WebGPU API to match one of the existing native APIs to simplify transpilation, given that transpilers are one of the primary target audiences for this API?

If the WebGPU API eventually diverges too far from any native API such that transpilers are forced to emulate various pieces of a WebGPU backend, we will lose many of the benefits that these low-level APIs offer. Likewise it seems as though it would be a major issue to expect game engines to create a separate WebGPU backend when OpenGL ES to WebGL transpilation was straightforward in the past.

It would be very useful to clarify how transpilation should work before settling on the fundamental API shape. For example, if we thought the WebGPU API shape should mirror Vulkan's API closely, then the path for device creation as discussed in #22 is obvious (shape it after Vulkan and constrain it further if necessary), and we can focus on finding the correct way to emulate it on D3D12 and Metal.

**Comment by dmikis** [comment]
My understanding is that me model closely, but don't follow strictly any existing LL API and plan to ship C/C++ headers for apps compiled to WebAsm. Whereas that indeed will require separate backend from rendering engines, it won't differ too much from existing Metal, D3D12 or Vulkan implementations thus making porting easier. As for the quote from the charter, I think it's about making the API "natively" available from WebAsm (as right now, AFAIK, all web API calls must go through JS).

Also, when 3D Portability arrives, there may be an option to just allow 3D Portability-compatible apps to run on WebGPU.

**Comment by grovesNL** [comment]
@dmikis You may be right. I interpreted it to mean "transpilation from some existing native API calls into WebGPU calls", as we do with OpenGL ES to WebGL.

**Comment by Kangz** [comment]
What @dmikis said.

In addition, to help people bootstrap a WebGPU backend, we might make a non-conformant implementation of a native low-level API that is implemented on top of WebGPU, that can be incrementally replaced with direct WebGPU code. That isn't a top-level goal of the CG however.

**Comment by grovesNL** [comment]
@Kangz Sounds good, thanks.
