### ISSUE TITLE
Move createSwapChain from GPUDevice to GPUCanvasContext

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#250]
Creating a swap chain on the device doesn't make it clear from a web developer point of view that this is going to invalidate the previous one created on a context. I believe moving `createSwapChain` from GPUDevice to GPUCanvasContext would help a lot removing that potential confusion.

```js

const canvas = document.querySelector('canvas');
const context = canvas.getContext('gpupresent');

// Before

const swapChainDescriptor = { context: context, format: 'bgra8unorm' };
const swapChain = device.createSwapChain(swapChainDescriptor);

const format = await device.getSwapChainPreferredFormat(context);

// After

const swapChainDescriptor = { device: device, format: 'bgra8unorm' };
const swapChain = context.createSwapChain(swapChainDescriptor);

const format = await context.getSwapChainPreferredFormat(device);
```

**Comment by beaufortfrancois** [comment]
![image](https://user-images.githubusercontent.com/634478/55328201-1706ff80-548c-11e9-81ee-b0ef520fe1c4.png)

Is that enough to move this forward?

**Comment by Kangz** [comment]
Yeah we can do a PR for this, even if only 2 browsers voted 👍
