### ISSUE TITLE
misleading chrome error for bind groups

### ISSUE THREAD

**Issue by martin19** [gpuweb/gpuweb#2508]
These are my first attempts in WebGPU so please bear with me if this is a non-issue or not critical enough atm.

trying to setup a simple compute & display pipeline:

1. read image from texture
2. process texels with compute shader
3. output texture to screen

```
[[group(0), binding(0)]] var samp : sampler;
[[group(0), binding(1)]] var inputTex : texture_2d<f32>;
[[group(0), binding(2)]] var outputTex : texture_storage_2d<rgba8unorm, write>;

[[stage(compute), workgroup_size(1)]]
fn main() {
  let dims : vec2<i32> = vec2<i32>(1920, 1080);

  for (var x = 0; x < dims.x; x = x+1) {
    for(var y = 0; y < dims.y; y = y+1) {
        var writeIndex : vec2<i32> = vec2<i32>(x, y);
        var loadIndex : vec2<i32> = vec2<i32>(x, y);
        var acc : vec3<f32> = vec3<f32>(f32(x)/f32(dims.x));
        //<--- var rgb : vec3<f32> = textureSampleLevel(inputTex, samp, (vec2<f32>(loadIndex) + vec2<f32>(0.25, 0.25)) / vec2<f32>(dims), 0.0).rgb;
        textureStore(outputTex, writeIndex, vec4<f32>(acc, 1.0));
    }
  }
}
```

Creating the bindGroup like this...
```
const computeBindGroup0 = device.createBindGroup({
    layout: blurPipeline.getBindGroupLayout(0),
    entries: [
        {
            binding: 0,
            resource: sampler,
        },
        {
            binding: 1,
            resource: texIn.createView(),
        },
        {
            binding: 2,
            resource: texOut.createView(),
        }
    ],
});
```

When the "textureSampleLevel" statement in wgsl is missing I get an error on chrome console:

```
Number of entries (3) did not match the number of entries (1) specified in [BindGroupLayout]
```

When the "textureSampleLevel" statement in wgsl is present everything works fine.

Took me some time to figure out what the problem was, maybe unused inputs are optimized away and throw this
error message. 

windows 10
chrome canary 99
intel uhd 620

thanks for your work.

**Comment by Kangz** [comment]
As noted in #2507, please follow the instructions of the issue wizard. This is an implementation issue and should have been filed as a Chromium bug. I filed [dawn:1258](https://bugs.chromium.org/p/dawn/issues/detail?id=1258) for this because it is a common pain point linked to #2470 (I'm sad to give more wood to that issue, but @martin19 also had issues with `writeBuffer` so it's not just implicit PLL).
