### ISSUE TITLE
Inconsistency between bind groups and vertex buffers

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#251]
Moved from https://github.com/gpuweb/gpuweb/pull/186#issuecomment-476305702

As it stands right now, they are defined individually (in `GPUBindGroupLayoutDescriptor`) and provided individually (in `GPUBindGroupDescriptor`), which is different from how the vertex buffers are provided (sequentially).

There is a case to be made about sequential binding IDs for the following reason:
- Vulkan API works with ranges of descriptors, so this would be potential optimization (disclaimer: nothing stops us from doing this today, but exposing an API that favors sequential bindings would hit this code path more often)
- depends on how we decide to expose arrays in inside descriptors. In DX12 and Metal each array element occupies a separate ID (in the respective heap or an `MTLArgumentBuffer`). In Vulkan the array dimension is extra (i.e full address of a descriptor consists of the trio (set, binding, array_index)).
- is there a good use case where this would be limiting?

Interestingly, this is related to #145 and #167

**Comment by Kangz** [comment]
@kvark does this discussion still need to happen?
