### ISSUE TITLE
Clarify the rules for scoping/shadowing

### ISSUE THREAD

**Issue by RobinMorisset** [gpuweb/gpuweb#2510]
I could not find anywhere in the spec the rules for when/if it is ok to shadow a declaration. I looked at the section #function-scope-variables, and grep-ed for 'shadow'.

I half-remember the group deciding to allow shadowing across scopes but not within a scope, but I may be wrong.

Did I miss it in the spec, and if not should I propose a PR to add it in?

**Comment by ben-clayton** [comment]
I believe the PR you're looking for is: https://github.com/gpuweb/gpuweb/pull/1561

**Comment by RobinMorisset** [comment]
Thanks, that is indeed what I had missed.
