### ISSUE TITLE
Spec guidance on when/where error messages appear

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2516]
> In any case I think it's all browser specific but we could consider putting a note in the spec about where errors would ideally be surfaced. (It doesn't even say anything about uncaptured errors being shown in the console - Firefox used to not show them IIRC.)

_Originally posted by @kainino0x in https://github.com/gpuweb/gpuweb/issues/2438#issuecomment-999150622_

For example I think we should say:
- Shader compilation messages shouldn't be in the validation error message (use compilationInfo instead)
- uncapturederrors should show in the console if there are no event handlers? but not if they're handled?

**Comment by kainino0x** [comment]
Editors agreed non-normative text reflecting those two would be good.

**Comment by greggman** [comment]
I think the major issue right now is it dumps the entire shader which could be 100s of lines. A typical compiler error only complains about the line the error was on. Just throwing that out there. I certainly agree doing nothing and having them appear is nice.

Taking JS as an example though, if I add an error handler then 

In Chrome and Firefox, I can apparently catch all JS syntax errors, In Safari I can catch some but not all syntax errors

Here's some code

```
<p>May not see syntax error in JavaScript console</p>
<script>
window.addEventListener('error', (e) => {
  e.preventDefault();  // just in case
  console.log('handler fired');
});
</script>
<-- same below this line -->
<script type="module" src="module-with-syntax-error.js"></script>
<script src="script-with-syntax-error.js"></script>
<script type="module">
import './module2-with-syntax-error.js';
</script>
<script>
import('./module3-with-syntax-error.js')
   .then(_ => console.log('import resolved'))
   .catch(_ => console.log('import rejected'))
</script>
```

Running it in Chrome and Firefox I get

```
handler fired
handler fired
import rejected
handler fired
```

In Safari

```
[Log] handler fired
[Error] SyntaxError: Unexpected identifier 'error'
[Log] import rejected
[Error] SyntaxError: Unexpected identifier 'error'
	promiseReactionJob
```

So 2 errors were caught and 2 not.

Without the `error` handler and the async import catch

Chrome

```
Uncaught SyntaxError: Unexpected identifier
module-with-syntax-error.js:1 Uncaught SyntaxError: Unexpected identifier
module3-with-syntax-error.js:1 Uncaught (in promise) SyntaxError: Unexpected identifier
Promise.then (async)
(anonymous) @ js-error.html:10
module2-with-syntax-error.js:1 Uncaught SyntaxError: Unexpected identifier
```

Firefox

```
Uncaught SyntaxError: unexpected token: identifier
script-with-syntax-error.js:1:7
Uncaught SyntaxError: unexpected token: identifier
module-with-syntax-error.js:1:7
Uncaught SyntaxError: unexpected token: identifier
module2-with-syntax-error.js:1:7
Uncaught (in promise) SyntaxError: unexpected token: identifier
module3-with-syntax-error.js:1:
```

Safari

```
[Error] SyntaxError: Unexpected identifier 'error'
	(anonymous function) (script-with-syntax-error.js:1)
[Error] SyntaxError: Unexpected identifier 'error'
[Error] SyntaxError: Unexpected identifier 'error'
	promiseReactionJob
[Error] Unhandled Promise Rejection: SyntaxError: Unexpected identifier 'error'
	promiseEmptyOnRejected (module3-with-syntax-error.js:1)
	promiseReactionJob
```

Live versions: 
* [with error hander/catch](https://greggman.github.io/doodles/test/js-errors/js-error-with-error-listener.html)
* [without](https://greggman.github.io/doodles/test/js-errors/js-error.html)

I only bring this up to show some precedence. In particular, an async import is very analogous to compiling a WGSL shader and no error is printed in any browser if I catch the error.

**Comment by kainino0x** [comment]
Good example of precedent, thanks. 

> I think the major issue right now is it dumps the entire shader which could be 100s of lines. A typical compiler error only complains about the line the error was on. Just throwing that out there. I certainly agree doing nothing and having them appear is nice.

Also a good point. The proposal above says
"Shader compilation messages shouldn't be in the validation error message [at all]"
but we could also say instead
"validation error messages shouldn't contain full shader text but should contain compilation error messages"
or we could say something like
"validation error messages shouldn't contain shader text or compilation messages, but they may be surfaced in dev tools warnings, for example collapsed by default"
