### ISSUE TITLE
Behavior of discarding everything

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2523]
Highly related to #2378

During the office hour we discussed a case where all control flow ends with `discard`, and whether we want to support it.
It conflicts with this rule in the behavioral spec:
> If the function has a return type, the behavior of its body must be one of {Return} or {Return, Discard}.

I raised the concern that this restriction feels artificial and unhelpful, and that we should also allow `{Discard}` behavior. So here comes this issue.

To support this notion, here is a real-world use case which we'd have to reject if we keep the rule unchanged: https://github.com/gfx-rs/naga/issues/1679

**Comment by dneto0** [comment]
This was originally raised in #2515, and I think that was closed because the resolution is tied up with #2378

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-17-minutes#behavior-of-discarding-everything-2523">WGSL meeting minutes 2022-05-17</a></summary>



* KG: Might be resolved.
* AB: Would like to leave as is. We know Naga has seen case from code generator. Given problems in metal backend feel like changing code gen is easier to not do unconditional discard. Not big change and makes a bunch of stuff easier to explain.
* KG: As long as has satisfactory workaround, fine for v1?
* AB: Yea
* KG: Happy with that. **Will copy notes and mark closed**.


</details>
