### ISSUE TITLE
Invalid example for requiredFeatures

### ISSUE THREAD

**Issue by pyoor** [gpuweb/gpuweb#2532]
`GPUDeviceDescriptor.requiredFeatures` expects a dictionary of expected features with their specified limits.  The example in the spec is incorrect.

https://github.com/gpuweb/gpuweb/blob/f8bdc06057a08923d953d8bdd81f060499993363/spec/index.bs#L1816-L1827

**Comment by kainino0x** [comment]
Features and limits are different - features is a list, limits is a dictionary.

```
dictionary GPUDeviceDescriptor : GPUObjectDescriptorBase {
    sequence<GPUFeatureName> requiredFeatures = [];
    record<DOMString, GPUSize64> requiredLimits = {};
};
```

The example seems correct to me. Did you run into an issue in an implementation?

**Comment by pyoor** [comment]
@kainino0x my apologies - you are correct.  I was confusing requiredLimits with requiredFeatures.  Thanks for pointing that out!
