### ISSUE TITLE
rgba8unorm canvas textures and IOSurface

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2535]
On macOS, Chromium (at least) backs all canvas textures with IOSurfaces. However, as I understand it, macOS IOSurfaces cannot be rgba8unorm, only bgra8unorm*. Our spec requires canvases can be configured as either rgba8unorm or bgra8unorm (Chromium currently only implements bgra8unorm).

\* bgra8unorm IOSurfaces can apparently be bound to either rgba8unorm or bgra8unorm MTLTextures - this does reinterpretation, not swizzling.

The most common case where people actually need rgba8unorm canvases is when they try to write to them as storage textures. On Metal, bgra8unorm can also be universally used as a storage format (and all other usages).

Our initial thought was that we would have to allocate an intermediate rgba8unorm texture and then issue a final blit into the IOSurface. This would be quite costly in general though.

I ended up hacking around a bit to see what could work, and experimentally it seems like we could transparently "emulate" rgba8unorm canvas textures by transparently backing them with bgra8unorm MTLTextures.

- On Metal, bgra8unorm can do everything that rgba8unorm can do (which is everything)
- MSL is agnostic to the component order (RGBA/BGRA) - storage textures use the term `rgba8unorm` for both, and accesses are in rgba order (correctly swizzled depending on the underlying texture)
- Render attachments are agnostic to the component order

The only exception I'm aware of is copies, which see the byte order, and are not agnostic to the component order (and don't obey Metal texture view swizzling either). This means copy commands into these "emulated" textures (using copyBufferToTexture, copyTextureToBuffer, [EDIT: copyTextureToTexture], writeTexture, and copyExternalImageToTexture in some cases) would have to be emulated as well, using a blit instead of a real copy.

So, the alternatives. These are mostly implementation choices but I think it's worth discussing here because they're not trivial and maybe there's a spec level solution (I'm not seeing one though).

1. Spec disallows rgba8unorm (and therefore storage) for canvas textures (and add optional feature for bgra8unorm storage) - not good on devices that prefer RGBA
    1b. Spec disallows rgba8unorm only on mac - obviously not good for portability
2. Implementations must either do an extra full-canvas blit, or have a path that doesn't use IOSurface (probably not possible in Chromium)
3. Implementations emulate rgba8unorm canvases using bgra8unorm, always enable the RENDER_ATTACHMENT usage on canvases, and emulate copies using blits
    3b. Spec disallows copies on rgba8unorm canvases - again bad on devices that prefer RGBA

**Comment by Kangz** [comment]
To be honest since WebGPU has `GPUCanvasContext::getPreferredFormat` I think it is ok to go with option 2) that involves extra copies. On macOS the preferred format will be `bgra8unorm` so applications should default to that and know that using a different format could lead to a suboptimal path.

**Comment by Kangz** [comment]
That said, it seems that creating `rgba8unorm` IOSurfaces is possible: we have a test in [Dawn that tries both sampling and rendering](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/tests/end2end/IOSurfaceWrappingTests.cpp;drc=a9ca8cb4ab4cc0ffcc970c2fb284f6ac41937aaf;l=436) from such surfaces.

**Comment by kainino0x** [comment]
> That said, it seems that creating `rgba8unorm` IOSurfaces is possible: we have a test in [Dawn that tries both sampling and rendering](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/tests/end2end/IOSurfaceWrappingTests.cpp;drc=a9ca8cb4ab4cc0ffcc970c2fb284f6ac41937aaf;l=436) from such surfaces.

Interesting. In that case I guess we need to figure out if that became available in a particular OS release. I probably don't know where to look but IOSurface is almost completely undocumented on developer.apple.com so I don't know how to check.

**Comment by kainino0x** [comment]
Link from Myles:
https://developer.apple.com/documentation/quartzcore/cametallayer/1478155-pixelformat?language=objc
Only lists BGRA formats.

**Comment by litherum** [comment]
Link from Jesse: https://developer.android.com/ndk/reference/group/a-hardware-buffer

**Comment by ccameron-chromium** [comment]
I tested RGBA and BGRA IOSurfaces with [CALayer setContents:] (to complement Kangz' tests above), and indeed everything appears on the screen correctly (https://bugs.chromium.org/p/chromium/issues/detail?id=1241369#c20).

We don't actually use CAMetalLayers for display (we set CALayer contents to IOSurfaces), so I think we can easily add rgba support. I have some vague thoughts about adding CAMetalLayer backing support (and stealing their IOSurfaces), but that would only be for supporting HDR canvases (currently we do an extra blit into a CAMetalLayer there).

**Comment by litherum** [comment]
I filed https://issuetracker.google.com/issues/221895957.

**Comment by litherum** [comment]
I also filed rdar://89600963.

**Comment by litherum** [comment]
Talking with the team, there are a few different options here.

1. Create RGBA `IOSurface`s and slam them into `CALayer`s' `contents`. The team thinks this would be a very unfortunate option, because `CAMetalLayer` has significant smarts inside it beyond just setting layers' contents. I don't know how much detail I can get into here, because its implementation is closed-source, but it has to do with A) very important power use optimizations, and b) consistent frame delivery to the display. The recommended way of doing this is to use a `CAMetalLayer` in the UI process, call `nextDrawable()` in the UI process, then call `texture.ioSurface` on the resulting `CAMetalDrawable` to get its backing `IOSurface`. With that `IOSurface`, you can send it to the GPU process to be populated.
2. Use a BGRA texture internally, but make it look like an RGBA texture at all the places where its pixel format is observable. This is trickier than it sounds, because PSO creation requires knowing the format of any textures bound as render targets. It would be a mistake to compile the PSO multiple times just in case someone wants to attach a drawable to a particular render target. So, the way this would probably have to work is to make _all_ BGRA textures act as RGBA, regardless of whether they came from CAMetalDrawable or from the app itself. Copies and uploads would have to be polyfilled with shaders.
3. Add a new object to the WebGPU type hierarchy which is less flexible than regular `GPUTexture`s. For the sake of discussion, let's call it `GPUSurface`. `GPUSurface`s wouldn't support any of the operations which allows pixel ordering to be observable. Presumably, the relationship between `GPUTexture` and `GPUSurface` would be similar to the relationship between `GPURenderPassEncoder` and `GPURenderEncoderBase`. In Metal, this would also probably allow us to use the `CAMetalLayer.farmebufferOnly` flag to get extra performance.

We think option 3 is the way to go here, because if the CG restricts the expressivity today, the CG can add in the extra expressivity in the future after v1. And, there's a chance that Android bug or that radar will be fixed by then, so this problem may just cease to exist, and there may be no need to ever implement the polyfills listed in option 2.

**Comment by Kangz** [comment]
About 3), couldn't the browser use the `GPUTextureUsage` to know if it can cheaply emulate RGBA on BGRA, or if it needs to do a blit? Same thing for `framebufferOnly`. That said, all swapchain textures may be read back, for example with `canvas.toBlob()`, so I don't think it would ever be possible to use `framebufferOnly` to gain the extra performance.

**Comment by kainino0x** [comment]
Corentin's suggestion seems like the ideal one to the editors, too. We already have a concept of GPUTextures that can't be copied, thanks to `GPUTextureUsage`. And I think there are real use cases for copying to/from canvas textures, so I'd prefer to still allow copy usages, and do blits when necessary.

I also agree it's not clear that framebufferOnly could actually be used. I think we'd need a new context configuration parameter to prevent the canvas from being read back.

**Comment by kainino0x** [comment]
I was about to suggest that we actually add that flag disable readbacks by default (you have to enable readback if you want to use the canvas as an image source, very reasonable IMO) - but then it occured to me that if we had such a configuration, it would _also_ break printing and "save image as". So the consequences are a bit farther reaching than I initially realized.
(in my [super draft exploratory notes](https://docs.google.com/document/d/1FSIAInhiumYmf2Q5TQUV8uZuS_VgWGeLF7FmPCLFXk4/edit?usp=sharing) where I'm trying to resolve a whole bunch of canvas related stuff)

**Comment by kainino0x** [comment]
If we were to allow `framebufferOnly`, I think we would need a special flag to be enabled. This special flag _might_ also enable fast-paths on other OSes. (I also wonder if this could relate to WebGL-style `desynchronized:true`, need to think on that.) Here's what I think that would look like:

- Add a flag to the context that controls whether it can be read back. When it is configured to be render-only:
    - We can use framebufferOnly. Maybe swapchains/overlays on other platforms?
    - Validate the only usage is RENDER_ATTACHMENT
    - toDataURL/etc never work and so never need to clear (issue a warning and return an empty image, similar to readback/transferToImageBitmap from a canvas with no context)
        - [Synchronous canvas readbacks](https://github.com/gpuweb/gpuweb/issues/2217#issuecomment-1067016745) are also disabled, can’t jank
    - I’m pretty sure this breaks [“save image as”/printing/etc.](https://github.com/gpuweb/gpuweb/issues/1781) unless the app rerenders in onbeforeprint or oncopy (and either they temporarily switch the flag or we do it for them).

**Comment by kainino0x** [comment]
Resolution on framebufferOnly: don't need to consider it for now, but haven't agreed we'll never want it

**Comment by kainino0x** [comment]
For the meeting discussion: Having resolved on framebufferOnly, pop the stack back to the IOSurface problem. Options:

- (a) No spec change. Basically, take a penalty when not using the preferred format (bgra8unorm-storage removes the issue with storage). Implementation choices:
    - If the canvas is RGBA, just blit the results into a BGRA IOSurface to present.
    - (1.) Put RGBA images in CALayer.contents.
    - (2.) Secretly make canvas textures BGRA when you ask for RGBA. Can’t quite do this because it breaks compatibility with render pipelines.
- (b) (3.) GPUSurface. I think fundamentally same as option 2, same problem.
- (c) (Discussed previously in #2748.) Add a new magic "rgba8unorm-unordered" format with no COPY support. Underneath it's the same as the preferred format.
    - Due to differences in storage capability, would not have storage support; could do "rgba8unorm-unordered-storage" + "rgba8unorm-unordered-nonstorage".

My proposal is option (a), no spec change, but am cool with (c) as well.

**Comment by kainino0x** [comment]
meeting: Resolved option (a) for v1, (c)/(d) for polish-post-v1

**Comment by kainino0x** [comment]
Not sure why I put this in needs-spec, we resolved on no change. (Future stuff is filed in #2869)
