### ISSUE TITLE
Add a note that copyT2T might not preserve the exact bit values

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#2558]
This was found while updating the CTS tests for `copyTextureToTexture`. Sometimes the bytes are not preserved exactly when doing the copy, I think it is because some drivers implement the copy with a render pass which "normalizes" the bit representation of values. For example `r8snorm` has two representations for -1: `0x80` and `0x81`. When doing a copy of the `0x81` value, the destination texture gets a `0x80`.

**Comment by kainino0x** [comment]
Is it defined for B2T/T2B copies? I would be surprised. I'm going to put the documentation note on all 4 (t2t/t2b/b2t/writeTexture), I don't think it can hurt. We don't have the actual copy steps defined for these so I'll leave an inline issue for when we do.

**Comment by kainino0x** [comment]
Reopening this as I think I'd like to call out that (AFAIK) float bit patterns are also not guaranteed to be preserved, in particular different NaN patterns, quiet vs signaling NaN, and -0 vs +0.

Additionally it's probably the case that subnormal numbers may not be preserved, which isn't covered by what I wrote ("multiple possible representations of some values"), so we would need to expand the text to cover that.

As an aside, I tried to check the Vulkan spec to see what carveouts it had for this, but I couldn't find any.
https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap20.html

**Comment by kainino0x** [comment]
We could try writing a CTS test to see if any of those cases are actually preserved (in particular subnormals, quiet vs signalling NaN).

**Comment by toji** [comment]
Copyediting portion of this should be resolved by https://github.com/gpuweb/gpuweb/pull/4672 and https://github.com/gpuweb/gpuweb/pull/4698 so I'm removing that label.

**Comment by kainino0x** [comment]
No harm in assuming the worst for subnormals, NaNs, and zero. I am pretty sure we will not be able to guarantee anything stronger. So we should just add those to the spec and close this.

**Comment by Kangz** [comment]
Given that both #4672 and #4698 are landed, is there anything else that should be done to close this issue? Or do we need to add text about subnormals, NaNs and zeroes?
