### ISSUE TITLE
Dynamic indexing in Uniform address space

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2559]
If I'm reading and understanding it correctly, WGSL doesn't have any restrictions on indexing uniform data. In particular, [array access expression](https://gpuweb.github.io/gpuweb/wgsl/#array-access-expr) doesn't talk about `S` bearing special rules.

@wtholliday found this to be a problem for us because Naga translates uniform buffers into `constant` memory in MSL.
```rust
@group(0) @binding(0)
var<uniform> buffer: array<vec4<f32>, 4>;

@stage(vertex)
fn foo(@builtin(vertex_index) vertex_id: u32) -> @builtin(position) vec4<f32> {
	return buffer[vertex_id];
}
```
turns into
```cpp
struct type_1 {
    metal::float4 inner[4];
};
struct fooOutput {
    metal::float4 member [[position]];
};
vertex fooOutput foo(
  metal::uint vertex_id [[vertex_id]]
, constant type_1& buffer [[user(fake0)]]  // <---------------------- CONSTANT
) {
    metal::float4 _e3 = buffer.inner[vertex_id];
    return fooOutput { _e3 };
}
```

Relevant MSL spec text:
> If multiple executing instances of a graphics or kernel function are accessing the buffer using an index such as the vertex ID, fragment coordinate, or the thread position in grid, the buffer must be allocated in the device address space.

## Possible outcomes

1) I just missed the relevant spec, and the issue can be closed :)
2) WebGPU implementation on Metal has to use `device` address space for uniform buffers under some circumstances (either when it detects the indexing, or just unconditionally for all). I'm concerned that this would manifest in a SAaaD (spooky action at a distance) in shader performance: as soon as I add any indexing code, even if it ends up being unreachable, *all* the access to a uniform buffer may become slower, because the implementation would have to switch the address space.

>  The constant address space is optimized for multiple instances executing a graphics or kernel function accessing the same location in the buffer.

I don't know if there are more caveats to this, like Metal driver logic becomes more complicated because it can no longer assume the binding is read-only (by just looking at the buffer declaration).

3) We introduce that limitation to the specification, so users aren't going to be able to dynamically index within uniform buffers. The implementation would then have no SAaaD. As soon as the user needs dynamic indexing, they can switch the binding into read-only storage buffer.

**Comment by ben-clayton** [comment]
FWIW, Tint's output for this is:

```metal
#include <metal_stdlib>

using namespace metal;
struct tint_array_wrapper {
  /* 0x0000 */ float4 arr[4];
};
struct tint_symbol_1 {
  float4 value [[position]];
};

float4 foo_inner(uint vertex_id, const constant tint_array_wrapper* const tint_symbol_2) {
  return (*(tint_symbol_2)).arr[vertex_id];
}

vertex tint_symbol_1 foo(const constant tint_array_wrapper* tint_symbol_3 [[buffer(0)]], uint vertex_id [[vertex_id]]) {
  float4 const inner_result = foo_inner(vertex_id, tint_symbol_3);
  tint_symbol_1 wrapper_result = {};
  wrapper_result.value = inner_result;
  return wrapper_result;
}

```

**Comment by dneto0** [comment]
It looks like there is no such restriction in OpenGL ES 3.1:

I looked up GLSL ES 3.1 [spec](https://www.khronos.org/registry/OpenGL/specs/es/3.1/GLSL_ES_Specification_3.10.withchanges.pdf).
It looks like the rule changed from GLSL ES 1.0 and afterward.  See  the first part of 13.30:  

> 13.30 Dynamic Indexing

> For GLSL ES 1.00, support of dynamic indexing of arrays, vectors and matrices was not mandated
because it was not directly supported by some implementations. Software solutions (via program
transforms) exist for a subset of cases but lead to poor performance. Should support for dynamic indexing
be mandated for GLSL ES 3.00?
RESOLUTION: Mandate support for dynamic indexing of arrays except for sampler arrays, fragment
output arrays and uniform block arrays.

Earlier in the sepc (4.3.9 Interface blocks) it describes arrays-of storage buffers and uniform blocks:

> For uniform or shader storage blocks declared as an array, each individual array element corresponds to a
separate buffer object backing one instance of the block. As the array size indicates the number of buffer
objects needed, uniform and shader storage block array declarations must specify an array size. **All
indices used to index a uniform or shader storage block array must be constant integral expressions.**

**Comment by litherum** [comment]
One of the options here is "don't use `constant` pointers in MSL" and I wanted to reject that option early. This is based evidence that, if applications can use it, `constant` pointers can be wildly more performant than `device` pointers. Here's a [little program](https://github.com/gpuweb/gpuweb/files/8001503/MetalConstantPerformanceTest.zip) that compiles the same example two ways - one way with a buffer marked as `constant` and another way with it marked as `device`. Here are the performance results on the machine I have in front of me (an M1 Mac):

<img width="1124" alt="Screen Shot 2022-02-04 at 1 18 00 AM" src="https://user-images.githubusercontent.com/918903/152503508-c407d1ee-5b9e-4486-98ab-8fc4bcc5c461.png">
 
Clearly, with perf improvements like that, the right solution isn't "never use `constant` pointers."

**Comment by litherum** [comment]
WebGPU should ignore this section of the Metal spec.

**Comment by litherum** [comment]
Let me temper that a little bit: WebGPU implementations should ignore this sentence of the Metal spec on current versions of Metal.

**Comment by litherum** [comment]
The spec has been updated, and this sentence removed.

- https://web.archive.org/web/20220309044639/https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf
- https://web.archive.org/web/20220331063340/https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf
