### ISSUE TITLE
Binary WGSL format in createShaderModule() WebAPI

### ISSUE THREAD

**Issue by munrocket** [gpuweb/gpuweb#2571]
Here a path for WGSL shaders from WebAssembly

```
                  Encoder                               Lexer     Parser 
Canonical ABI sting -> DOMString (UTF-16 with surrogates) -> Tokens -> AST IR -> ??? -> dx12/metal/spirv shaders
```
Strings in WebAssembly have [different](https://github.com/WebAssembly/interface-types/issues/136) encoding than WebAPI strings, so we need to encode strings first, also we need to parse wgsl shaders to get AST IR that can be similar for all platforms. I am not sure that Encoder+Lexer+Parser making zero overhead in comparison to all magic that happening later. And just curious how better binary WGSL format with AST IR inside will be

```         
Uint32Array -> Uint32Array WebAPI -> ??? -> dx12/metal/spirv shaders
```
If someone will create a prototype for this we can finally answer to a question [how bad](https://github.com/gpuweb/gpuweb/issues/566#issuecomment-592395899) WGSL really is :D
And should we extend createShaderModule() WebAPI.

**Comment by dneto0** [comment]
> Answer: the same as in WebGL, but who know what will be with new software.

I would be very interested in suggestions for conformance tests that stress WGSL parsing.

**Comment by munrocket** [comment]
Yea it’s strange that Zalgo still a problem in 2022.

But I am thinking that WGSL language frontend could be optional for tint/naga/etc. We can make data flow easier and also solve pretty heated problem on github. So instead of forcing system programmers to use “rusty” syntax in shaders, we can force javascript community to use builders for release version.

For example [tool](https://github.com/brendan-duncan/wgsl_reflect) from Brendan Dunkan is possible to modify to a tool that create WGSL IR without any builder

```js
import { wgsl } from “wgsl_reflect”;

// tagged template literal
let myShader = wgsl`
  type v4 = vec4<f32>;
  @stage(fragment)
  fn main() -> @location(0) v4 {
    return v4(0.4, 0.4, 0.8, 1.0);
 }`;

// shader compilation
let module = device.createShaderModule({
  binary: myShader,
});
```

Here wgsl is a tagged template literal
```js
function wgsl(src) {
  return binaryWgsl(srs);
}
export {wgsl}
```
That give you binary representation because it is how tagged templates works. This solution is not complicated to javascript developers. And you will get syntax highlighting with PolyMeilex plugin in vscode automatically. Based on this tool in similar way webpack/rollup/esbuild plugins can be created for .wgsl extension.

Also with this change it is possible make browser source code lighter: remove Lexer and Paser from tint/naga/etc entirely and make binary format as a default in createShaderModule() routine. Lexer+Parser transformation can be additional repo/crate that is used to produce IR.

People who don’t like current wgsl language for some reason can make with it your own language frontend. I personally like wgsl, but text format for WebAPI is javascript’ism and pure overhead for web.

**Comment by kvark** [comment]
I quickly tried to get some numbers for Naga here, using tracy. One of the bigger shaders from [vange-rs](https://vange.rs/) takes around 800us to load. See [ray.wgsl](https://github.com/gpuweb/gpuweb/files/8051009/ray.txt) (583 LOC)

This time includes lexing, parsing, some of the validation bits specific to WGSL, and building the IR. Replacing the text format by a binary would still retain some of that. I imagine that a nicely designed binary format could reduce this by about a factor of 2.
Also, I don't think we looked into optimizing the parsing yet, so this time isn't close to final.

I expect shader modules to not be created very often (i.e. you wouldn't block on that 800us in the middle of a frame), and not be tightly constrained on time. The scenario we want to see most is having a few shader modules with multiple entry points. At run-time you may be creating some of the pipelines of those entry points, but it no longer depends on whether the file was binary or text to begin with.

At this point, if there are wins to look for in a binary format, they should be considered as a part of an optional feature.

**Comment by munrocket** [comment]
Thank you for your feedback.

**Comment by magcius** [comment]
> I expect shader modules to not be created very often (i.e. you wouldn't block on that 800us in the middle of a frame)

My experience is that when shader compilation happens, it happens in a storm. For instance, in a game, we might have 50 shaders for the different objects in the scene. When the user changes some drastic global configuration -- the user walks into a fog volume, for instance, we now have to change out *all* 50 shaders for something that has the fog code turned on, and make new PSOs.

As a developer, I have three options:
* Block new rendering until all 50 shaders are loaded, resulting in poor performance.
* Swap old with new shaders as they're done, leading to inconsistent frame rendering.
* Skip rendering any objects with uncompiled shaders, leading to flickering.

And despite the browser and driver's best attempts to keep this smooth and asynchronous, there are other costs associated with creating new shader objects that makes it costly as well. The end result is that some hitching is unavoidable in these scenarios. Shader compilation hitching is very much a problem on desktop systems, too.

In my experience, with my web projects, 50 shaders is very much an underestimation for what these storms can look like.

So, no, in a vacuum, shader compilation performance isn't too important for stable framerates, but during a storm, it's helpful to have the hitching at a minimum.

**Comment by kvark** [comment]
The example with Fog technically could just be a specialization constant switch in the shaders. That is in addition to the fact you can put many different entry points into the same shader module in WGSL. So I'm not sure how much this is a problem for projects written for WebGPU. Sounds like a bigger projects ported directly from WebGL, with GLSL shaders.

**Comment by kainino0x** [comment]
I believe this issue can be folded into #3175, please let me know if not.
