### ISSUE TITLE
Metal primitive topology required for the shader compilation hint

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#2574]
We have a shader module hint defined as:
```js
dictionary GPUShaderModuleCompilationHint {
    required GPUPipelineLayout layout;
;
};
```

The problem here is that, when rendering points, Metal really wants to have the `[[point_size]]` VS output semantics initialized (to 1).
At the same time, when *not* rendering points, this semantics is forbidden. Therefore, in order to compile VS entry points we *always* need to know the primitive topology.

From here, we could think of many ways to proceed:
  1. Let the implementations try to deal with it, e.g. never expect point topologies (i.e. the implementation would regenerate the shader at pipeline creation time if it sees the point topology), or generate 2 VS programs (for points and non-points). It's a hint after all.
  2. Add the primitive topology to the `GPUShaderModuleCompilationHint` structure. This is something we've been warned about: that this hint structure may need to grow in the future.

cc @litherum

**Comment by Kangz** [comment]
+CC @cwfitzgerald do you think wgpu could do what @litherum suggested above?

**Comment by cwfitzgerald** [comment]
This is more a @jimblandy question, he's more familiar with naga

**Comment by Kangz** [comment]
@jimblandy would Naga be able to make this structure conditional like @litherum suggested? This would allow shelving this issue out of the v1 milestone :)

**Comment by Kangz** [comment]
If we made a PR that made the layout not required, I think it would easily be a non-breaking change to add additional hints in the future. So this issue would become post-V1 (or polish)

**Comment by jimblandy** [comment]
I don't see why Naga would have difficulty generating this, if Metal Shading Language can express it.

**Comment by cwfitzgerald** [comment]
I didn't realize quite what this was talking about - but wgpu currently doesn't do early MSL translation at all, so we don't use the compilation hint at all. If we did though, I agree with @jimblandy that we could use the function constant.

**Comment by Kangz** [comment]
Ok, I think with these comments and #2876 on the way it's safe to close this issue.

**Comment by kainino0x** [comment]
Closing SGTM, I assume someone will reopen or refile this if they actually run into the problem of needing the primitive topology in the hint. (FYI @litherum)

**Comment by kvark** [comment]
I don't think we have 100% that this idea is valid to express in MSL. Making fields optional is great, but what happens if it's a field with an output builtin, whether this trips the driver in some way, I don't know. So naturally I'd expect this to be tested before the issue is resolved/closed.

**Comment by Kangz** [comment]
That's why I put up #2876, so it's a non-breaking change to add additional fields to the hints later. So if this becomes impossible to implement for wgpu/naga we can super easily add the topology.
