### ISSUE TITLE
Proposal: Make `;` optional

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#2577]
Semi-colons are used to terminate module scope declarations, struct members and statements.

As far as I'm aware, there is no ambiguity if we were to entirely remove these (but are still required for for-loop delimiters).

I believe the only use for them is to aid in parser re-synchronization on errors. There are a number of other heuristics that could be used instead.

Is there any need to keep them? Can we make them optional?

---
Note: This is a personal suggestion, not an official Google proposal.

**Comment by magcius** [comment]
The classic counter-example is statements that take optional expressions that are also valid statements. The easiest one I spotted is return followed by function call.

I think we're saved here because return must be the last statement in a block if it appears, and blocks need to have braces, so this potentially ambiguous code is saved:

```
fn foo() -> i32 {
    if (bar)
        return
    func()
    return 1
}
```

But it definitely feels precarious.

**Comment by ben-clayton** [comment]
`return` is a very good point and something I admit I overlooked when scanning the spec.
I don't have a great counter to this, so I'm going to close this.

**Comment by jimblandy** [comment]
I don't think `return` is a problem, though. You can't write this in WGSL:

```
fn foo() -> i32 {
    if (bar)
        return
    func()
    return 1
}
```

because the branches of an `if` must be `compound_statement`s. You have to write this instead:

```
fn foo() -> i32 {
    if (bar) {
        return
    }
    func()
    return 1
}
```

which is fine.

**Comment by jrprice** [comment]
Since we now allow statically dead code, you can write this though:
```
fn foo() -> i32 {
   return 
   func()
   return 1
}
```

**Comment by ben-clayton** [comment]
The trouble is that we're allowing unreachable code, so:

```rust
return
a = 1;
```

is a non-error, and the parser would need to look way-ahead to know whether `a` is for the return or the next statement

**Comment by esummers** [comment]
Would love to see this suggestion considered too. TypeScript developers are used to optional semi-colons. I see more omit than include these days. For edge case scenarios like introducing dead code after a return, the semi-colons can always be included to disambiguate.
