### ISSUE TITLE
Add a MatrixInverse builtin?

### ISSUE THREAD

**Issue by kdashg** [gpuweb/gpuweb#2580]
Do we want one? HLSL and MSL both don't have one.

Spirv has one here: https://www.khronos.org/registry/SPIR-V/specs/unified1/GLSL.std.450.html
> MatrixInverse
Result is a matrix that is the inverse of x. The resulting values are undefined if x is singular or poorly conditioned (nearly singular).
The operand x must be a square matrix.

I'm leaning towards "no", but I want to get this on-record.

**Comment by magcius** [comment]
No. It's expensive and wasteful.

**Comment by kainino0x** [comment]
I'm pretty certain there's a record *somewhere* of us discussing this and deciding not to include it. Given lack of backend support I agree the decision is pretty clear.

**Comment by kainino0x** [comment]
(And I don't recall anyone ever disagreeing.)

**Comment by kdashg** [comment]
Great!
