### ISSUE TITLE
Allow popErrorScope after device loss?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2582]
Everything in WebGPU essentially starts with a validation check that the device is still alive. But conformance testing this is impossible in the current spec, because popErrorScope() is supposed to reject after device loss.

We can write tests that _do_ stuff after device loss, but we can't check the validation result. So we can detect browser crashes, but we can't reliably check that the browser actually did the validation.

So should we allow popErrorScope to resolve after device loss? It means (1) keeping the error scope stack state alive and (2) exposing the device liveness validation into the scope (currently doesn't have to be exposed at all). We can still disallow or ignore pushErrorScope, so once all scopes are popped we can stop tracking that stuff.

The alternative is to just rely on the browser to crash (and on fuzzing/ASAN/etc.) to catch issues.

cc @lokokung

**Comment by lokokung** [comment]
FWIW, although the specs state that popErrorScope should fail if the device is lost, the current Chrome implementation does not seem to act that way. (In CTS tests, I am able to popErrorScope and get the expected validation errors when calling APIs after the device was destroyed.)

**Comment by kainino0x** [comment]
> We can still disallow or ignore pushErrorScope, so once all scopes are popped we can stop tracking that stuff.

Or we could still allow pushErrorScope in the spirit of #1629 although I'm not sure it's necessary for that.

**Comment by kainino0x** [comment]
> The alternative is to just rely on the browser to crash (and on fuzzing/ASAN/etc.) to catch issues.

Thinking on this further, this is basically how everything in the entire platform works anyway. We don't normally add API surface just to ensure some null check or GC reference is working.

**Comment by kainino0x** [comment]
Editors discussed a bit and I think we prefer to keep things as is (no error scopes after device loss). The discussion did spawn #2599 though.

**Comment by litherum** [comment]
In general I'm a bit allergic to making any changes to an API just for internal testing considerations. Changes should be motivated by customer use; browsers can test non-exposed behaviors without adding public API.

**Comment by kainino0x** [comment]
Closed by tacit/explicit agreement :)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-03-09#allow-poperrorscope-after-device-loss--issue-2582">WGSL meeting minutes 2022-03-09</a></summary>



* ** KN: I’ll close this, and if anyone wants to do something different, do so.**


</details>
