### ISSUE TITLE
Should struct member declarations use commas instead of semicolons?

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#2587]
As discussed in the [February VF2F](https://docs.google.com/document/d/1r5QbKsqwZxZzD2CqbpteTGJ2bQwTHje_coZ8UCIAyik/edit#bookmark=id.tt7h00tm32ut). There was more support for switching structure declarations to use commas than semicolons. This issue is to come to a consensus on that proposal.

Example:
```
struct S {
  a : i32,
  b : f32
};

struct T {
  x : S,
  y : vec4<f32>, // optional last comma
}
```

**Comment by greggman** [comment]
Just be clear, this matches Rust, right?

**Comment by mehmetoguzderin** [comment]
On top of Rust, there is also the interesting case of ReScript, being OCaml-inspired in its origin, also separating fields with "," rather than ";"

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-03-08-minutes#should-struct-member-declarations-use-commas-instead-of-semicolons--issue-2587">WGSL meeting minutes 2022-03-08</a></summary>



* **Needs spec!**
* MM: Would it be illegal to use semicolons then? (yes) 


</details>
