### ISSUE TITLE
WriteBuffer performance issue?

### ISSUE THREAD

**Issue by lslzl3000** [gpuweb/gpuweb#2601]
I have noticed a very common problem on `writebuffer` performance:

1. With intel hd graphics, same computer, Windows will gain over 20% performance compared to Mac os. Why? Is there any difference on system level? Or Dawn has different approach on different system?

2. Compared to Webgl, `writebuffer ` is like `gl.bufferSubData`, but it comes very bed performance when write a large data. 
On my demo test, e,g, submit a 300k transform matrix buffer ( 300k * 16 = 4,800,000 array) to gpu side
The `gl.bufferSubData` will only take about 3~4 ms,  where `writebuffer` could take over 50ms, up to 70ms sometime, very slowly and unstable,  any idea why?

***
Chrome canary v100+
Mac os 12, Windows 10
Intel UHD 630
Intel i7 8700k
16gb DDR4
***

**Comment by lslzl3000** [comment]
By the way, the `map/unmap` takes even more time then `writebuffer` in this case

**Comment by Kangz** [comment]
Please post browser-specific issues on their respective issue tracker. `writeBuffer` hasn't been optimized to its fullest at all. This is could be related to this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1266727&q=writeBuffer&can=2) or you could create a new one on crbug.com.
