### ISSUE TITLE
Consider reserving keywords for a module system

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2607]
How about: 
* export
* import
* package
* module

Maybe also these?
* require
* extern
* public

**Comment by dneto0** [comment]
WGSL already reserves `using`

Perl module system uses: `import`, `require`, `package` 

ECMAScript uses `import` `export` and also secondary words `from` and `as`.

**Comment by jimblandy** [comment]
Rust uses `mod`, `pub`, and `use`, with `as` as a secondary keyword.

```
mod slurve {
    pub fn knuckleball() { ... }
    fn knurl() { ... }
}

use slurve::knuckleball as pitch;
```

**Comment by dneto0** [comment]
In [today's WGSL meeting](https://docs.google.com/document/d/1DBiWJJZjZOJaZqZ6K85Y0dNCY8uF28rtwY382Hwtr1w/edit#), @pow2clk suggested reserving all the keywords in several languages, including C++ Rust, ECMAScript.

I'll make a PR

**Comment by dneto0** [comment]
The PR doesn't reserve words used in other shader languages.  That would be an obvious followup.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-02-22-minutes#consider-reserving-keywords-for-a-module-system-2607">WGSL meeting minutes 2022-02-22</a></summary>



* Resolved: DN to make PR reserving _all the keywords!_

Rust, C++, Smalltalk, JavaScript, TypeScript


</details>

**Comment by kdashg** [comment]
I think this is done?

**Comment by kdashg** [comment]
`require` is not reserved, though `requires` is.

**Comment by kdashg** [comment]
This is done.
