### ISSUE TITLE
need schema for features still under development vs. finalized

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2608]
During the recent virtual face-to-face we discussed how extensions should be expressed with respect to the WGSL spec.

From the notes:

MM: match WebGPU, has conditional parts of the main spec. Was an intentional decision. Compressed textures as an example (e.g.: https://www.w3.org/TR/webgpu/#texture-compression-bc )
DM: follow main spec. Sort of wish it could just be a github branch
KG: hard to maintain
**Consensus: Do what WebGPU does. (conditional inline with the spec)**
MOD: what about unicode identifiers?
MM: Probably part of a larger feature pack that gets added
JB: is spec option in addition to versioning or only mechanism?
MM: agenda topic

In the WebGPU API, optional functionality are called "features"  https://www.w3.org/TR/webgpu/#features
There is a "Feature Index" describing each feature.  https://www.w3.org/TR/webgpu/#feature-index

WGSL has "extensions", and corresponding 'enable' directives.

But WGSL is a living spec, and it should support describing features during their lifecycle: before they are ready, when they are ready, and maybe even after deprecation.  We should have a clear schema for describing these.

Suggest an addition to the "Language extensions" section something like:

> An extension is either *experimental* or *complete*. 
An experimental extension is not ready for general use. It may be changed at any time, and implementation support may be defective and incomplete.
A complete extension has been finalized: no further changes are expected, conformance tests are complete, and implementations supporting the feature pass those tests.

I don't think we need a "deprecation" concept just yet.

**Comment by alan-baker** [comment]
Is experimental more like provisional in this description or an actual experimental feature? I can buy the former being included in the spec, but I don't think the latter belongs in the main branch. My main concern stems from experimental features moving to final or being removed. What remains in the spec? If the extension is simply removed, then it seems to introduce backwards incompatibility. That might seem ok on the face of it, but why include it in the first place? Whereas if it is more like provisional then we need to describe the mechanisms around the transitions (in my mind).

I'm sure sure what we gain be stating "this may change without notice". I think this needs to be further fleshed out first.

**Comment by dneto0** [comment]
> Is experimental more like provisional in this description or an actual experimental feature?

I'm not sure there's a meaningful distinction in the W3C context. (I may be ignorant here).

I think the spec should only care about extensions described, even partly, in (the main branch of) the spec itself.
The audience are web developers, and tooling / implementors. They need to know whether they should expect instability.
Once an extension goes final or "complete", then developers will look at https://caniuse.com/ to see which implementations offer support.

We can't stop folks from writing extension descriptions outside the main spec. Those would be deemed experimental.

Maybe "experimental" vs.. "complete" are the wrong words. How about "incomplete" and "complete".  Or "unstable" and "stable".  Or other pairings.

**Comment by dneto0** [comment]
> One other schema that could help the ecosystem overall (not only for browser vendors) is having standardized extension tags to specify whether they change syntax, or only some semantics, or only some library changes. As such, imagine being a tool maintainer: you could query extensions by this value and not read their titling or texting. But IDK if there is a precedent for this.

I think that should be left to the reader.  A lot will depend on what the tooling is trying to do.

Sometimes it's not a clear line between those aspects. For example, adding a new kind of derivative builtin is a builtin function but it would also interact with uniformity analysis.

**Comment by dneto0** [comment]
We discussed this internally, and I'd like to close this with no spec change.

I was not clear on where an extension should be described during its development, i.e. before it is ready for general use.  @alan-baker convinced me that those should not show up in the main spec.  Only after a spec is finished should it be incorporated into the main text.

**Comment by kainino0x** [comment]
FYI, equivalent open question on the API side: #2301 (and related #2424)
