### ISSUE TITLE
WGSL vs WebGPU spec for override constants

### ISSUE THREAD

**Issue by brendan-duncan** [gpuweb/gpuweb#2613]
The WebGPU spec example, https://www.w3.org/TR/webgpu/#typedefdef-gpupipelineconstantvalue, uses the `@override` attribute for override constants.

The WGSL spec example, https://www.w3.org/TR/WGSL/#override-declaration, uses `@id(0) override`.

Which is correct?

**Comment by alan-baker** [comment]
The WGSL spec is correct. The examples in the WebGPU spec need updated.
