### ISSUE TITLE
change endPass() to end() in IDL

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2620]
#2560 changed endPass() to end() but did not update the IDL.
This is on GPUComputePassEncoder and GPURenderPassEncoder

The lack of an end() method breaks the dawn_node build.

I think the minimum fix is to add end().
If we want a deprecation period, then delete endPass() later; otherwise delete it now.

**Comment by dneto0** [comment]
cc: @ben-clayton

**Comment by dneto0** [comment]
Ah. I think it's just that Dawn's copy of webgpu.idl is behind.

**Comment by ben-clayton** [comment]
See: https://github.com/gpuweb/cts/pull/984 and https://dawn-review.googlesource.com/c/dawn/+/79761
