### ISSUE TITLE
Remove serialization/transfer from the spec

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2629]
I think the first WebGPU spec release (1.0 when it becomes a living standard) is not going to include any kind of multithreaded usage of a single WebGPU device, so we should remove the references that are currently in there, which were added as part of incremental progress toward multithreading.

**Comment by kainino0x** [comment]
Agreed by tacit resolution unless someone comments between now and the time we do the changes.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-03-09#remove-serializationtransfer-from-the-spec--issue-2629-">WGSL meeting minutes 2022-03-09</a></summary>



* KN: While we really would have liked to have this in, I don’t think we can invest into getting this in at this point. We’re continuing to work through multithreading design issues, and that we should be able to handle them, but not in v1.
* **Tacit approval, needs spec.**


</details>
