### ISSUE TITLE
What should occur for inputs to `ldexp` that would produce a result that isn't representable as a `f32`?

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#2631]
Currently that [spec](https://www.w3.org/TR/WGSL/#float-builtin-functions) defines `ldexp(e1, e2)` = `e1` * 2 ^ `e2`, where `e1` is a `f32` and `e2` is a `u32`

There are many combinations of `e1` and `e2` that would result in a value that is out of bounds for `f32`. From the floating point conversions [rules](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-conversion), I think in this case the value is supposed to be infinite with appropriate sign, but to my understanding WGSL doesn't actually support infinite.

Thus it is unclear to me what the expected result should be.

**Comment by kdashg** [comment]
I feel it's clear in this case that it's "as if" you did `e1*pow(2,e2)`.
