### ISSUE TITLE
wgsl: don't reserve certain words

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2632]
Followup to #2617 

* @jimblandy [comment](https://github.com/gpuweb/gpuweb/pull/2617#issuecomment-1056037531): don't reserve 'box'

**Comment by dneto0** [comment]
In the 2022-03-01 meeting, @litherum suggested not reserving type names.

I can see folks may want to make type aliases for things like `vec4`, and the reservations prevent that.

**Comment by kdashg** [comment]
@jimblandy Do you want to reserve `box`? :)

**Comment by dneto0** [comment]
Discussed this again in the office hours.  We want to remove reservations for things that are type names from other languages. I'll make a PR.

**Comment by kdashg** [comment]
Please reopen (or just open a new PR directly!) if you have any new ideas here.
