### ISSUE TITLE
Precision loss in timestamp query

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#2642]
# Background
We know that the timestamp query results could be converted from GPU ticks into nanoseconds by compute shader (old discussion at [614#issuecomment-616274834](https://github.com/gpuweb/gpuweb/issues/614#issuecomment-616274834) and [1325#issuecomment-794854059](https://github.com/gpuweb/gpuweb/issues/1325#issuecomment-794854059)). If `t` is the origin timestamp (tick), which is uint64, `p` is the period (ns/tick), which is float, the timestamp query result `r = t * p`, but there is a large loss of accuracy, a more precise computation should be `r = static_cast<uint64_t>(static_cast<double>(t) * p)` (Equation A) .

Although the precision error still exists, I think its error ratio is already very small. Compared with the result of `t * p` calculated by the Windows Calculator, the error ratio of `r` is about 2e-9, which means a difference of 2 nanoseconds per second. **The results of Equation A should be the most accurate results we can compute on CPU, and the accuracy of the results calculated by the compute shader is also based on this result.**

But in native shading languages, we cannot do the computation directly due to the `uint64` and `double` are not fully supported on quite a few devices:

| Native | Uint64 | Double |
|---| --- | ---|
| D3D12 (HLSL) | Require [SM6.0](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/hlsl-shader-model-6-0-features-for-direct3d-12#hardware-capability) or higher, using DXC, `D3D12_FEATURE_DATA_D3D12_OPTIONS1.Int64ShaderOps == true` | Supported |
| Metal (MSL) | [Since Metal 2.2](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) | Unsupported |
| Vulkan (SPIR-V) | `VkPhysicalDeviceFeatures.shaderInt64 == true` <BR> [Device Coverage](https://vulkan.gpuinfo.org/listfeaturescore10.php): Overall 53.8%, Windows 97.1%, Linux 95.2%, Android 9%, macOS 12%, iOS 84.6% | `VkPhysicalDeviceFeatures.shaderFloat64 == true` <BR> [Device Coverage](https://vulkan.gpuinfo.org/listfeaturescore10.php): Overall 49.8%, Windows 97.3%, Linux 94.6%, Android 2.5%, macOS 0%, iOS 0% |

So we need to simulate the multiplication of timestamp ticks and period in compute shader. We using four `uint32` to represent four 16-bits of `uint64`, and multiply the period `p` with a multiplier `m` under 2^16 to keep the precision of computation. The four `uint32` chunks will be multiplied by `p * m`, then the final results are divided by `m`. The sample code can be found in [Dawn's QueryHelper.cpp](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/native/QueryHelper.cpp;l=40), and **the error ratio of the simulation results is about 2e-5, compared with the result calculated by Equation A on CPU**. Of course, this algorithm can continue to be improved to obtain higher accuracy if more effort is invested.

# What's the problem here
```
const pass = commandEncoder.beginComputePass();
pass.wrirteTimestamp(querySet, 0); // timestamp0 in ns
pass.dispatch(8, 1, 1);
pass.wrirteTimestamp(querySet, 1); // timestamp1 in ns
queue.submit([commandEncoder.finish()]);
```
If we use timestamp query **alone** to profile the execution time of GPU commands like above example, or compare timestamps on same queue, **the accuracy error from simulation is acceptable** and does not affect profiling results too much.

However, we have a profiling scenario that use [ID3D12CommandQueue::GetClockCalibration](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandqueue-getclockcalibration) and timestamp query to build the timeline of each operator (or dispatch command) in TFJS WebGPU backend on Windows:
```
const pass = commandEncoder.beginComputePass();
pass.wrirteTimestamp(querySet, 0); // timestamp0 in ns
pass.Dispatch(8, 1, 1);
pass.wrirteTimestamp(querySet, 1); // timestamp1 in ns
//  The GetClockCalibration be called before and after queue submit when the toggle record_detailed_timing_in_trace_events
//  is enabled, and the gpu and cpu timestamps are printed in chrome://tracing
queue.GetClockCalibration(gpuTimestampStart, cpuTimestampStart); // in ticks
queue.submit([commandEncoder.finish()]);
// Wait for all tasks done;
queue.GetClockCalibration(gpuTimestampEnd, cpuTimestampEnd);  // in ticks
```
We convert the gpu and cpu timestamps from `GetClockCalibration` to nanoseconds on CPU, then calibrate the timestamp0 and timestamp1 to the cpu timestamps and use the cpu timestamps to draw the timeline. We expect `gpuTimestampStart` (ns) < `timestamp0` < `timestamp1` < `gpuTimestampEnd` (ns), but actual is `timestamp0` < `gpuTimestampStart` (ns). 

That is because **the tick of `timestamp0` is not much larger than `gpuTimestampStart`, but `timestamp0` has a larger error ratio after processing by compute shader** (More detailed data presentation at [Dawn Issue 1305](https://bugs.chromium.org/p/dawn/issues/detail?id=1305&q=&can=1)). Even trying to reduce the error ratio of the simulation in compute shader to 9.38e-8, the timestamp query still cannot meet this requirement. **In this case we need to get the most accurate results from timestamp query, like CPU side**.

# Question
**Could we reconsider exposing timestamp tick and period and remove the compute shader?** Let developers do the timestamp tick->ns convention on the CPU side by themselves.

**Comment by fintelia** [comment]
[Mesa has a polyfill for `double`](https://github.com/mesa3d/mesa/blob/16cb957e8bd729e228048706f0a28a207a909479/src/compiler/glsl/float64.glsl) so it is possible to get bit-exact results even without hardware support. However their implementation does rely on builtins that [WGSL isn't planning to add until post-V1](https://github.com/gpuweb/gpuweb/issues/1565).

Regardless, the problem doesn't seem to be floating point vs. fixed precision. Rather, your current fixed precision code only makes use of 15 bits for the multiplier* (16 bits in the "improved precision" version) compared to doubles which have a 53 bit mantissa. If you had instead used a divisor of 2^24 in your linked example, the timestamps computed on the GPU would have been within a few hundred ns of the true value, and everything would have ended up in the right order.


_\* I know you're storing the multiplier in a u32, but the upper 16+ bits are all zero so they don't really help much. This kind of thing is what makes fixed precision annoying to use..._

**Comment by haoxli** [comment]
@fintelia Thanks for your feedback!
Yes. I theory, we can have a way to control the error ratio of the simulation to a minimum, that is `|period - (uint32)(period * multiplier)/multiplier|` is small enough, `multiplier` < `2^32`. According to different `period`, we can find the optimal `multiplier`, not necessarily `2^24`. 

In above profiling scenario, a error value of a few hundred ns of the true timestamp computed value could meet the requirement. But will there be a need for a zero-error (same or closest to the value computed on CPU) situation in the future? I'm not sure. In that case, the error value needs to be within 83.333ns on Intel GPUs, becuase we could sample two consecutive timestamp ticks (the period per tick is 83.333ns). The timestamp ticks are of type uint64, the multiplier of 2^32 is still not precise enough.

**Comment by haoxli** [comment]
I believe there must be a way to do an absolutely accurate simulation, but it's relatively more complex. Is it worth spending more effort to achieve that, or use a simpler way instead? That's what I want to discuss.

**Comment by fintelia** [comment]
I can't speak to whether the group should avoid the complexity. 

But in case it is helpful, this C code from [Berkeley SoftFloat version 2c](http://www.jhauser.us/arithmetic/SoftFloat.html) (unfortunately under a seemingly bespoke open source license) shows some efficient tricks doing 64 bit computations only using 32-bit unsigned integers:

<details>
<summary>[Click to show]</summary>

```cpp
/*----------------------------------------------------------------------------
| Adds the 64-bit value formed by concatenating `a0' and `a1' to the 64-bit
| value formed by concatenating `b0' and `b1'.  Addition is modulo 2^64, so
| any carry out is lost.  The result is broken into two 32-bit pieces which
| are stored at the locations pointed to by `z0Ptr' and `z1Ptr'.
*----------------------------------------------------------------------------*/

INLINE void
 add64(
     bits32 a0, bits32 a1, bits32 b0, bits32 b1, bits32 *z0Ptr, bits32 *z1Ptr )
{
    bits32 z1;

    z1 = a1 + b1;
    *z1Ptr = z1;
    *z0Ptr = a0 + b0 + ( z1 < a1 );

}

/*----------------------------------------------------------------------------
| Multiplies `a' by `b' to obtain a 64-bit product.  The product is broken
| into two 32-bit pieces which are stored at the locations pointed to by
| `z0Ptr' and `z1Ptr'.
*----------------------------------------------------------------------------*/

INLINE void mul32To64( bits32 a, bits32 b, bits32 *z0Ptr, bits32 *z1Ptr )
{
    bits16 aHigh, aLow, bHigh, bLow;
    bits32 z0, zMiddleA, zMiddleB, z1;

    aLow = a;
    aHigh = a>>16;
    bLow = b;
    bHigh = b>>16;
    z1 = ( (bits32) aLow ) * bLow;
    zMiddleA = ( (bits32) aLow ) * bHigh;
    zMiddleB = ( (bits32) aHigh ) * bLow;
    z0 = ( (bits32) aHigh ) * bHigh;
    zMiddleA += zMiddleB;
    z0 += ( ( (bits32) ( zMiddleA < zMiddleB ) )<<16 ) + ( zMiddleA>>16 );
    zMiddleA <<= 16;
    z1 += zMiddleA;
    z0 += ( z1 < zMiddleA );
    *z1Ptr = z1;
    *z0Ptr = z0;

}

/*----------------------------------------------------------------------------
| Multiplies the 64-bit value formed by concatenating `a0' and `a1' by `b'
| to obtain a 96-bit product.  The product is broken into three 32-bit pieces
| which are stored at the locations pointed to by `z0Ptr', `z1Ptr', and
| `z2Ptr'.
*----------------------------------------------------------------------------*/

INLINE void
 mul64By32To96(
     bits32 a0,
     bits32 a1,
     bits32 b,
     bits32 *z0Ptr,
     bits32 *z1Ptr,
     bits32 *z2Ptr
 )
{
    bits32 z0, z1, z2, more1;

    mul32To64( a1, b, &z1, &z2 );
    mul32To64( a0, b, &z0, &more1 );
    add64( z0, more1, 0, z1, &z0, &z1 );
    *z2Ptr = z2;
    *z1Ptr = z1;
    *z0Ptr = z0;

}

/*----------------------------------------------------------------------------
| Multiplies the 64-bit value formed by concatenating `a0' and `a1' to the
| 64-bit value formed by concatenating `b0' and `b1' to obtain a 128-bit
| product.  The product is broken into four 32-bit pieces which are stored at
| the locations pointed to by `z0Ptr', `z1Ptr', `z2Ptr', and `z3Ptr'.
*----------------------------------------------------------------------------*/

INLINE void
 mul64To128(
     bits32 a0,
     bits32 a1,
     bits32 b0,
     bits32 b1,
     bits32 *z0Ptr,
     bits32 *z1Ptr,
     bits32 *z2Ptr,
     bits32 *z3Ptr
 )
{
    bits32 z0, z1, z2, z3;
    bits32 more1, more2;

    mul32To64( a1, b1, &z2, &z3 );
    mul32To64( a1, b0, &z1, &more2 );
    add64( z1, more2, 0, z2, &z1, &z2 );
    mul32To64( a0, b0, &z0, &more1 );
    add64( z0, more1, 0, z1, &z0, &z1 );
    mul32To64( a0, b1, &more1, &more2 );
    add64( more1, more2, 0, z2, &more1, &z2 );
    add64( z0, z1, 0, more1, &z0, &z1 );
    *z3Ptr = z3;
    *z2Ptr = z2;
    *z1Ptr = z1;
    *z0Ptr = z0;

}
```
</details>

**Comment by Kangz** [comment]
@haoxli, this seems like an implementation detail of the precision of the computation in Chromium? I got lazy doing the "improved precision", but we could somewhat easily go up to 32 bits of fixed point precision by emulating `umulExtended` and `uaddCarry`, see this [TODO](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/native/QueryHelper.cpp;l=83?q=QueryHelper%20f:dawn). Worst case we could go all the way to software doubles like @fintelia pointed out. (though we need to check license of stuff etc).

We discussed exposing the tick->ns ratio in the API previously but that's not possible on Metal because it isn't constant, and it is also more work put on developers to do the conversion themselves (plus they risk testing on GPUs that have 1tick = 1ns, see that it doesn't need conversion, then forget to convert on other devices like Intel where 1tick = 83.333ns).

**Comment by haoxli** [comment]
Yes, this is also the reason why I insisted on exposing nanoseconds instead of ticks before, what developers really need is the time. It's also unreasonable to document that the timestamp query is not suitable for scenarios with high precision requirements in SPEC becuase it may has precision error (the native APIs does not have such problem).

Here I'm not trying to discuss how to implement the compute shader to improve the precision, just raise the tick-ns conversion of timestamp query by the simulation may has precision error, which will make timestamp query unavailable in some scenarios. And in order to get 100% accurate compute result (same to the result computed on CPU) in the simulation, we need to introduce more complex algorithms (such as [Berkeley SoftFloat version 2c](http://www.jhauser.us/arithmetic/SoftFloat.html) like @fintelia pointed out), only simulating the operation of uint64 cannot get the desired precision. So I'm not sure if browser implementations want to use such a complex simulation or prefer a simpler approach?

**Comment by fintelia** [comment]
> only simulating the operation of uint64 cannot get the desired precision.

This isn't true. Simulating fixed precision uint64 would get _better_ precision than bit-exact f64 simulation. The problem is that Dawn currently only simulates a fixed precision uint32 multiplier.

**Comment by haoxli** [comment]
> Simulating fixed precision uint64 would get better precision than bit-exact f64 simulation. The problem is that Dawn currently only simulates a fixed precision uint32 multiplier.

Indeed. But I don‘t think that using more bits for the multiplier could eliminate the precision error. The precision error comes from using the fixed precision uint multiplier instead of float. For example, on Intel, the period is `83.333`, a best multiplier is `85333` (83.333 * 2^10), which error ratio is `9.38e-8` ( `fabs(83.333 - 85333 / 2^10) / 83.333`).  Even with larger multipiler, the precision doesn't get better.

**Comment by fintelia** [comment]
> > Simulating fixed precision uint64 would get better precision than bit-exact f64 simulation. The problem is that Dawn currently only simulates a fixed precision uint32 multiplier.
>
> Indeed. But I don‘t think that using more bits for the multiplier could eliminate the precision error. For example, on Intel, the period is 83.333, a best multiplier is 85333 (83.333 * 2^10), which error ratio is 9.38e-8 ( fabs(83.333 - 85333 / 2^10) / 83.333). Even with larger multipiler, the precision doesn't get better.

I'm not sure I follow. Using a multiplier of 23456154234229096 (83.333 * 2^48) gives an error ratio of 1.91e-17 which is considerably better precision.

**Comment by haoxli** [comment]
Discussed offline with Corentin,  we've had many discussions about using tick or nanosecond, and finally decided to use nanosecond, no need to discuss again here. In the timestamp compute shader, the implementations need to simulate the conversion of tick->ns without precision error, otherwise it should be an implementation bug.
