### ISSUE TITLE
Can the identifier used in `enable` directive be keyword or reserved word?

### ISSUE THREAD

**Issue by jzm-intel** [gpuweb/gpuweb#2649]
Currently [WGSL spec](https://www.w3.org/TR/WGSL/#enable-directive-section) says that
> The directive uses an [identifier](https://www.w3.org/TR/WGSL/#identifier) to name the extension

while in [definition](https://www.w3.org/TR/WGSL/#identifiers) the identifier must not have the same spelling as a keyword or as a reserved word.
On the other hand, like the `f16` used in the [example](https://www.w3.org/TR/WGSL/#enable-directive-section:~:text=EXAMPLE%3A%20USING%20HYPOTHETICAL%20EXTENSIONS), it seems being convenience to use some reserved words (or keywords) as extension identifiers. 
Should the identifier used in `enable` directive explicitly be allowed to have the same spelling of keyword or as a reserved word?

**Comment by dneto0** [comment]
Oh, good catch.
Yeah, my intent is to allow anything that matches an identifer pattern.  The spec is badly worded.
But this will need review by the group.
