### ISSUE TITLE
Are duplicate timestamp locations allowed on the same pass?

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#2662]
```
dictionary GPURenderPassTimestampWrite {
    required GPUQuerySet querySet;
    required GPUSize32 queryIndex;
    required GPURenderPassTimestampLocation location;
};

partial  dictionary GPURenderPassDescriptor : GPUObjectDescriptorBase {
    GPURenderPassTimestampWrites timestampWrites = [];
};
```

Following the SPEC, we could set `timestampWrites` as below:
```
GPURenderPassDescriptor  descriptor;
descriptor.timestampWrites[0].querySet = querySet;
descriptor.timestampWrites[0].queryIndex = 0;
descriptor.timestampWrites[0].location = "beginning";
descriptor.timestampWrites[1].querySet = querySet;
descriptor.timestampWrites[1].queryIndex = 1;
descriptor.timestampWrites[1].location = "beginning";
```
But for Metal on TBDR devices, only the queryIndex `1` has timestamp values, the value at queryIndex  `0` is always zero. 

I'm not sure whether it's a bug of [MTLRenderPassDescriptor.sampleBufferAttachments](https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor/3564463-samplebufferattachments?language=objc), or it's a real limition (No error from validation layer).

Another issue is writing the timestamp of the different location to a different querySet, it also does not work:
```
GPURenderPassDescriptor  descriptor;
descriptor.timestampWrites[0].querySet = querySet0;
descriptor.timestampWrites[0].queryIndex = 0;
descriptor.timestampWrites[0].location = "beginning";
descriptor.timestampWrites[1].querySet = querySet1;
descriptor.timestampWrites[1].queryIndex = 1;
descriptor.timestampWrites[1].location = "end";
```
Only the seond querySet could be written with timestamp value.

**Comment by haoxli** [comment]
@litherum Could you help to check this issue? Thanks!

**Comment by haoxli** [comment]
cc https://github.com/gpuweb/gpuweb/issues/2046

**Comment by kainino0x** [comment]
great info, thanks! My first instinct is to go with option 3. I don't think it'll be very common to run into this limitation, and it seems possible to work around. I think an engine could just deduplicate the timestamp write and then modify their resolveQuerySet call or use copyBufferToBuffer if they need multiple copies of the result.

**Comment by litherum** [comment]
Resolved: option 3
