### ISSUE TITLE
Clarify meaning of `dispatch()` args.

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#2669]
One of the more common pitfalls I see new developers hitting (including myself) is making the assumption that the args passed into `dispatch()` represent how many compute shader invocations will be executed in each dimension, rather than how many workgroups will be dispatched.

Often after pointing out the actual behavior I've heard developers express that they thought work would be divided among the declared workgroup size automatically and that the workgroup size declaration itself was functionally either a performance hint or only dictated the scope of workgroup memory persistence.

Worse, due to a how features like array clamping works it's entirely possible that some users will get this wrong and not realize it. They'll never execute too few workgroups, so the side effects are going to be doing too much work and getting garbage in the last elements of some arrays/textures, which could be an easy thing to miss.

I have previously tried to address this by [adding spec notes and changing arg names](https://github.com/gpuweb/gpuweb/pull/2519), but those rely on people actually reading through the spec to notice and I can confidently say most developers will never bother.

Because of this confusion I'd like to suggest that we consider ways that we could make the behavior of the `dispatch()` methods more obvious without the need to spelunk through the spec. In service of this I posted a series of _Highly Scientific™️_ Twitter polls to try and gauge people's first blush impression of how different variations of the function are understood by asking them how many shader invocations they thought each of the following would trigger given the following shader:

```rs
@workgroup_size(4)
 fn computeMain() {}
```

| Method signature | Respondents guessing correct # of invocations |
| -------------------- | ---------------------------------------------------- |
| [dispatch(8)](https://twitter.com/Tojiro/status/1503793710688993281?s=20&t=s0LN0J5YchzX1rd23JITHw) | 42.2% |
| [dispatchWorkgroups(8)](https://twitter.com/Tojiro/status/1503793712970842115?s=20&t=s0LN0J5YchzX1rd23JITHw) | 66.4% |
| [dispatch({ workgroupCountX: 8 })](https://twitter.com/Tojiro/status/1503793714426118146?s=20&t=s0LN0J5YchzX1rd23JITHw) | 67.7% |

(Each poll had ~230 votes)

While these results obviously should be taken with a grain of salt, it's also a decent indicator that making the function name or structure more explicit would help with comprehension of function's behavior. Given that it's expected to be a hot function I'm not particularly in favor of going all the way to using a dictionary, but maybe simply renaming `dispatch[Indirect]()` -> `dispatchWorkgroups[Indirect]()` would be worth our while.

Beyond that, however, ANY hints, guides, and other resources we can surface to developers to help comprehension here are probably going to be worthwhile. If I could raise a console warning every time someone writes past the end of a buffer in a compute shader I would! Don't really think that's an option for us, though.

**Comment by kainino0x** [comment]
I think renaming to `dispatchWorkgroups` would be relatively quick and easy and significantly reduce the amount of developer confusion (since this bug is so hard to observe).
