### ISSUE TITLE
Can't enable webgpu unsafe flag on Chrome Canary v102.0.4953.0

### ISSUE THREAD

**Issue by eduardfossas** [gpuweb/gpuweb#2674]
Hello, for some reason I cannot run any example or enable the unsafe flag on Chrome Canary v102.0.4953.0 on MacOS. Any idea why?

**Comment by pixelspark** [comment]
fwiw, the flag comes back (and works) when you enable `#temporary-unexpire-flags-m100` and (or?) `#temporary-unexpire-flags-m101`.

**Comment by eduardfossas** [comment]
Ah, great for the quick response! It worked enabling 101. Thanks!

**Comment by devshgraphicsprogramming** [comment]
can't enable it even the way @pixelspark described in chrome 103

**Comment by devshgraphicsprogramming** [comment]
the funny thing is that all the websites with WebGPU demos you can find on Google don't have that token and either don't work or silently fall-back to WebGL

**Comment by willzhai** [comment]
> can't enable it even the way @pixelspark described in chrome 103

i just tried，its ok！
1、download the latest version of Chrome Canary ，now its 106
2、chrome://flags/，enabled #temporarily unexpire M104 flags & temporarily unexpire M105 flags
3、search “webgpu”，and you will find  the [#enable-unsafe-webgpu](chrome://flags/#enable-unsafe-webgpu)

**Comment by LifeIsStrange** [comment]
@willzhai thanks nice timing I just had the same issue :)
btw there is a new webgpu option (for devtools?)

however i have a very powerful PC and https://austin-eng.com/webgpu-samples/samples/deferredRendering increased a 600 lights lag a lot which seems pathethic, Vulkan or DirectX 12 would never have this issue.
