### ISSUE TITLE
Make colon following switch case optional

### ISSUE THREAD

**Issue by amaiorano** [gpuweb/gpuweb#2678]
Switch case bodies must be within braces, so the colon after the case itself is not necessary for parsing.

Currently:

```
  switch (f()) {
    case 0: {
      let marker1 = 0;
    }
    case 1: {
      let marker2 = 0;
    }
    case 42: {
      let marker3 = 0;
    }
  }
```

What I suggest is making the colon optional so that this is also valid:

```
  switch (f()) {
    case 0 {
      let marker1 = 0;
    }
    case 1 {
      let marker2 = 0;
    }
    case 42 {
      let marker3 = 0;
    }
  }
```

**Comment by mehmetoguzderin** [comment]
Using the fact that parentheses are optional for `switch`, example reads even more consistent:
```
switch f() {
    case 0 {
      let marker1 = 0;
    }
    case 1 {
      let marker2 = 0;
    }
    case 42 {
      let marker3 = 0;
    }
}
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-03-29-minutes#make-colon-following-switch-case-optional-2678">WGSL meeting minutes 2022-03-29</a></summary>



* AB: Different from C; in C the colon serves a purpose. We have comma separation.
* MM: Can we remove fallthrough.
* AB: That’s different functionality.
* KG: We do require braces.
* MM: And that’s good.
* AB: Should we ban it?
* MM: Don’t do that.
* KG: Ok making it optional.
* RM: Ok with it optional.
* _Consensus: make it optional._


</details>
