### ISSUE TITLE
TextureView validation and defaults don't consider the aspect when checking/determining the view format

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#2679]
https://gpuweb.github.io/gpuweb/#abstract-opdef-resolving-gputextureviewdescriptor-defaults

```
If the descriptor.aspect is

    "stencil-only"
    this.[[descriptor]].format must be a depth-or-stencil format which has a stencil aspect.

    "depth-only"
    this.[[descriptor]].format must be a depth-or-stencil format which has a depth aspect.

descriptor.format must be equal to either this.[[descriptor]].format or one of the formats
in this.[[descriptor]].viewFormats.
```
this means:

```javascript
const texture = device.createTexture({ format: 'depth24plus-stencil8' });
const view1 = texture.createView({ aspect: 'depth-only', format: 'depth24plus'  }); // not ok
const view2 = texture.createView({ aspect: 'depth-only', format: 'depth24plus-stencil8'  }); // ok
const view3 = texture.createView({ aspect: 'depth-only' }); // ok
```

I would think that `view1` should be ok, and that the validation should instead check that the "resolved/effective format for the aspect" is equal to either this.[[descriptor]].format or one of the formats in this.[[descriptor]].viewFormats.

Likewise, in https://gpuweb.github.io/gpuweb/#abstract-opdef-resolving-gputextureviewdescriptor-defaults
```
If resolved.format is undefined, set resolved.format to texture.[[descriptor]].format.
```

I would expect the default view format to be determined based on `descriptor.aspect`. That is, if I have a `depth24plus-stencil8` texture, creating a view with aspect `depth-only` would default the view format to `depth24plus`, not `depth24plus-stencil8`.

**Comment by Kangz** [comment]
I think the latter is the current idea in the spec, although it could be described more explicitly. For single plane formats it doesn't change anything, but imagine a multi-planar format, wouldn't you need to list per-plane what the compatible view formats are?

**Comment by austinEng** [comment]
if the latter is the intent, then you could also list a compatible view format as a multi-planar format instead of listing per-plane compatible formats.
like:
```javascript
const texture = device.createTexture({
    format: 'depth32float-stencil8',
    viewFormats: ['r32float-uint8']
});
const view = texture.createView({
    format: 'r32float-uint8',
    aspect: 'plane0-only'
}); // gives you an r32float view
```
but formats like 'r32float-uint8' and `plane0-only' are not real concepts in the spec today.

**Comment by austinEng** [comment]
I think that format -> aspect -> viewFormat would be better than format -> viewFormat -> aspect as it maps better to the backend implementation.

In Vulkan
1. VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT specifies that the image can be used to create a VkImageView with a different format from the image. **For multi-planar formats, VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT specifies that a VkImageView can be created of a plane of the image.**

2. If image was created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, and **if the format of the image is not multi-planar, format can be different from the image’s format**, ...

3. If image was not created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, or **if the format of the image is a multi-planar format and if subresourceRange.aspectMask is VK_IMAGE_ASPECT_COLOR_BIT, format must be identical to the format used to create image**

So in Vulkan, multiplanar is already mutable format, but it doesn't mean you can generally reinterpret the whole format. You can *only* reinterpret via selecting a plane. And, if I'm reading (3) correctly, you may not reinterpret all planes of multiplanar as another multiplanar. A single plane must be selected.

In D3D12

4. Reinterpretation is done by creating the texture with a TYPELESS format and creating the shader resource view with a fully-typed format. There are no TYPELESS versions of multiplanar formats like DXGI_FORMAT_NV12 and DXGI_FORMAT_P010. You can't reinterpret the entirety of NV12 as something like DXGI_FORMAT_R8_R8G8_UNORM and then select the DXGI_FORMAT_R8 plane. But, it looks like you can reinterpret these planes after you have selected one of them though.
      > (NV12) Valid luminance data view formats for this video resource format are DXGI_FORMAT_R8_UNORM and DXGI_FORMAT_R8_UINT.

In Metal

5. If you make a Metal texture from an IOSurface, you need to first select the plane you'd like on creation of the MTLTexture. After this, you may call [MTLTexture newTextureViewWithPixelFormat]

So it looks like in all of the target APIs, you're required to first select the plane before reinterpreting as a different view format. I suggest that we do the same for WebGPU.

**Comment by Kangz** [comment]
> So it looks like in all of the target APIs, you're required to first select the plane before reinterpreting as a different view format. I suggest that we do the same for WebGPU.

Isn't the conclusion that all APIs allow format reinterpretation of an aspect only on single-planar formats? If that's the case then the order between selecting the aspect and reinterpretation doesn't matter since we do one or the other. But anyways that's a bit of a nitpick.

PR you put up looks mostly good, will comment there,
