### ISSUE TITLE
Task: Define the copies with 1d and 3d textures

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2690]
The [spec says](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuimagecopytexture):

> Define the copies with [1d](https://gpuweb.github.io/gpuweb/#dom-gputexturedimension-1d) and [3d](https://gpuweb.github.io/gpuweb/#dom-gputexturedimension-3d) textures. [[Issue #gpuweb/gpuweb#69]](https://github.com/gpuweb/gpuweb/issues/69)

It links to https://github.com/gpuweb/gpuweb/issues/69, which is closed, but I believe this task still remains.

**Comment by toji** [comment]
Resolved in #4686
