### ISSUE TITLE
Requiring textures to be sized to a multiple of their block size is kind of unfortunate

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#2706]
The [spec for `createTexture()` says](https://gpuweb.github.io/gpuweb/#dom-gpudevice-createtexture):

> descriptor.[size](https://gpuweb.github.io/gpuweb/#dom-gputexturedescriptor-size).[width](https://gpuweb.github.io/gpuweb/#extent3d-width) must be multiple of [texel block width](https://gpuweb.github.io/gpuweb/#texel-block-width).
> descriptor.[size](https://gpuweb.github.io/gpuweb/#dom-gputexturedescriptor-size).[height](https://gpuweb.github.io/gpuweb/#extent3d-height) must be multiple of [texel block height](https://gpuweb.github.io/gpuweb/#texel-block-height).

This is a bit unfortunate in the presence of normalized sampling coordinates. It means that a developer switching to compressed textures has to modify their shaders to handle the region that is beyond the region of their logical texture but within the padded size.

Metal doesn't require textures to be sized to a multiple of the block size; I don't know about other APIs.

**Comment by Kangz** [comment]
Seems to be a D3D limitation: I made a small test and had the validation layers tell me this

> ID3D12Device::GetResourceAllocationInfo: Textures created with certain Formats must align the resource dimensions properly. D3D12_RESOURCE_DESC::Format is BC1_UNORM. D3D12_RESOURCE_DESC::Width is 3, and must be a multiple of 4. D3D12_RESOURCE_DESC::Height is 3, and must be a multiple of 4. (597)

Vulkan is fine with unaligned compressed texture sizes though.
