### ISSUE TITLE
Add scalar and vector constructors from abstract numeric types

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2719]
Raised by @jrprice 

Consider:

      var a: array<i32, u32(4000000000)>;

The programmer is trying to make a u32 without using a suffix.  But under current rules the 4000000000 default-converts to i32 which errors out because it's out of bounds.

So the proposal is to add scalar and vector constructors from abstract numeric argument types.

**Comment by dneto0** [comment]
These probably fit best in the "conversion expressions" sections, but the introductory text may need tweaking

**Comment by alan-baker** [comment]
I'm happy to pull these into #2668. Probably easiest to do as part of constexprs.
