### ISSUE TITLE
Missing specification of error type produced

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2730]
There are a few errors in the spec which do not list the error type, just state they are errors. They all seem like they would be `shader-creation error` although the access past end for vector could also be `dynamic error` if the array index isn't known at compile time.

In the `Vector Access Expression`:
  * accesses a component past the end of the vector is an error.
  * Providing more then 4 letters is an error.

In the `Builtin Functions` section:
  *  it is an error to attempt to redefine one or to

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-17-minutes#missing-specification-of-error-type-produced--issue-2730">WGSL meeting minutes 2022-05-17</a></summary>



* KG: Think we did this?
* AB: Not exactly. Open question about if we want shader creation errors on static out of bounds which is in another issue which isn’t resolve. Others have language which is updated to make it clearer there is an error.
* KG: DM filed other issue
* AB: 1803 on agenda later …
* AB: If resolve on that happy to clean up language.
* KG: Other thought is if we agree on other errors besides that one can **punt that one to 1803** and mark it as resolved or editorial
* AB: **Editorial**.


</details>
