### ISSUE TITLE
Consider using a more intuitive matrix notation

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#2744]
I think changing the current notation (`matNxM<f32>`) to a more intuitive one like `matCxR<f32>` would make it more obvious what N/M stand for (i.e. columns/rows); making it easier to learn and reason about. Especially since HLSL's notation is `floatRxC`.

**Comment by Kangz** [comment]
Just to make sure, this would be an editorial change in the spec to clarify what the type means, but WGSL code would stay the same right?

**Comment by teoxoy** [comment]
Yes, just an editorial change.

**Comment by Kangz** [comment]
Fancy making a spec PR?

**Comment by teoxoy** [comment]
Sure, can give it a shot!
