### ISSUE TITLE
The preferred format is not always storage-capable

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#2748]
The preferred formats rgba8unorm and bgra8unorm have almost the same capabilities, except for one: `STORAGE_BINDING` usage. This limitation is not universal on underlying APIs: bgra8unorm storage is supported always on Metal, never on D3D12, and sometimes on Vulkan (if my investigation is correct).

Meanwhile, rgba8unorm incurs some emulation or copying on Mac: #2535. For use-cases that want to store into the canvas texture, bgra8unorm would be highly preferable on Mac (since bgra8unorm storage is always available).

- option 0: Leave as is; if you need storage you use rgba8unorm and incur overhead on mac.
- option 1 **(EDIT: Landed for V1 in #2838)**: Add a "bgra8unorm-storage" feature flag - straightforward and explicit.
    This wouldn't be testable on a lot of machines, which means anyone who doesn't explicitly check for support (and test on Mac) is putting Mac at a perf/power disadvantage. However, this is pretty much the same trade-off as getPreferredFormat on desktop vs mobile.
    - May want to add texture usage to getPreferredFormat: Return the platform-preferred format unless STORAGE is requested. If you request STORAGE, then in core it always gives RGBA, but if the bgra8unorm-storage feature is enabled, may give you BGRA. Console warning if you ask for storage, and the feature is available but not enabled.
- option 2: Add two new "magic" formats `rgba8unorm-unordered-nonstorage` and `rgba8unorm-unordered-storage`. These would be non-copyable but otherwise the same as rgba8unorm/bgra8unorm.
    - This swings far to the side of "declarative", so apps don't have to get their logic right to do the right thing (call getPreferredFormat with the right arguments). But as with many declarative things, it's inflexible: might we find other restrictions that make this short-sighted?
    - It also creates a bunch of strict validation, e.g. if your canvas is `rgba8unorm-unordered-nonstorage` then your render pipeline MUST also be `rgba8unorm-unordered-nonstorage`.
    - Can technically replace getPreferredFormat (#2747), but likely should keep something like that because new formats won't map well to existing engines porting from WebGL/native (think Unity/Unreal).

Both options 1 and 2 could be done post-V1. Adding V1 milestone for initial discussion.

**Comment by Kangz** [comment]
Strong +1 for handling this issue post-V1, if we get user feedback that it's needed.

**Comment by kainino0x** [comment]
Resolution: option 1

There was mention of requiring the bgra8unorm-storage feature to be available on all systems where bgra8unorm is the preferred format. But we can only do this if we can change the preferred format on Windows to rgba8unorm (without performance penalty). In the meeting Jesse said he wasn't aware of any performance penalty to using rgba8unorm on Windows (even for overlays etc)

**Comment by kainino0x** [comment]
Digging around, this DirectX Discord conversation:
https://discord.com/channels/590611987420020747/596046911010504754/943744056582893598
reinforces the idea that BGRA on Windows only matters for Direct2D/GDI.

Meanwhile I found [several](https://stackoverflow.com/a/53383113) [claims](https://stackoverflow.com/a/5114091) online that iOS actually prefers BGRA over RGBA. That goes against what I thought, but I can't find where we determined it preferred RGBA. Most likely I got confused about iOS vs Android?

macOS at least seems to have strong opinions about BGRA, and it seems this evidence applies to iOS as well - I just didn't realize this before. https://github.com/gpuweb/gpuweb/issues/2535#issuecomment-1034178660

**Comment by Kangz** [comment]
I'm a bit worried about asking browser to change the format they use for overlays on Windows. That's a very non-trivial change and could cause a lot of issues (if only because drivers were never tested against browsers that do that). So I would like to go forward with option 1 without the constraint that the extension is present if `getPreferredFormat()` returns `bgra8unorm`.

While this is a small wart in the API, I think the cost of not making a decision and keeping discussing this is much higher than doing the simple stuff now and seeing how we can improve the situation later, if we need to improve the situation.

**Comment by kainino0x** [comment]
Moving to editorial to implement option 1 (without extra guarantees).

(BTW I'd love to pursue option 2 in the future - it's not incompatible with option 1 - but we'll need some real-world test cases if we want to make sure it's really practical.)

**Comment by kainino0x** [comment]
Opened #2838 for option 1.

Moving this issue to post-v1 for further consideration of option 2 or others.

**Comment by kainino0x** [comment]
Extracted that into #2869. Closing this.
