### ISSUE TITLE
Explicit flat interpolation requirement clarification

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#2760]
This is the current wording of the spec regarding this:

> User-defined IO of scalar or vector integer type must always be specified as `@interpolate(flat)`.

Just want to confirm that this requirement covers all user-defined IO and not just vertex outputs and fragment inputs.

Since the spec mentions that while `@interpolate` attributes can be specified on all user-defined IO, they are ignored for vertex inputs and fragment outputs.

> The attribute is only significant on user-defined vertex outputs and fragment inputs.

**Comment by alan-baker** [comment]
I would prefer (and plan) to clarify that flat is only required on integral vertex outputs and fragment inputs.
