### ISSUE TITLE
Consider allowing creation-time expressions or constants in switch case selectors

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#2764]
The current spec only allows `const_literal`'s as part of switch case selectors.

> case_selectors :
| [const_literal](https://gpuweb.github.io/gpuweb/wgsl/#syntax-const_literal) ( [comma](https://gpuweb.github.io/gpuweb/wgsl/#syntax-comma) [const_literal](https://gpuweb.github.io/gpuweb/wgsl/#syntax-const_literal) ) * [comma](https://gpuweb.github.io/gpuweb/wgsl/#syntax-comma) ?

I think it would be useful to allow creation-time
- expressions (for full flexibility but there might be grammar ambiguities?) OR
- constants (less flexible than expressions but still more useful than just `const_literal`'s)

**Comment by litherum** [comment]
Yes, this is one of the whole purposes of making creation-time expressions in the first place.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-19-minutes#consider-allowing-creation-time-expressions-or-constants-in-switch-case-selectors-2764-">WGSL meeting minutes 2022-04-19</a></summary>



* AB: Just missed this.  Will fix. And look for other cases.
* _Intent to make this change._


</details>

**Comment by teoxoy** [comment]
Should we also consider attributes?

Currently `align`, `size`, `location`, `binding`, `group` and `id` attributes must be passed positive i32 literals but they could instead accept creation-time expressions that evaluate to u32.

`workgroup_size` also must receive literals or module-scope constants but could instead accept override expressions that evaluate to u32.

Let me know if I should open a new issue to discuss this.

**Comment by alan-baker** [comment]
Attributes were intentionally not included. I'd suggest a separate issue for those.
