### ISSUE TITLE
Clarify undefined behavior of built in functions

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#2765]
Currently the spec doesn't mention anything about the return values of a few built in functions where other shading languages have undefined behavior.

## atan2

[MSL](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#page=237): x = 0 and y = 0 => undefined (spec doesn't cover behavior of only x = 0)
[HLSL](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-atan2): "The atan2 HLSL intrinsic function is well-defined for every point other than the origin, even if y equals 0 and x does not equal 0." (weird wording; same as MSL?)
[GLSL](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.40.pdf#page=147): x = 0 and y = 0 => undefined (also doesn't cover x = 0?)

As far as I can tell they all seem to have undefined behavior for:
- x = 0 and y = 0
- maybe also just x = 0?

Maybe JS's atan2 behavior can be adopted ([MDN JS atan2](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2#using_math.atan2))? It looks well-defined.

**Comment by teoxoy** [comment]
Note that this also impacts the behavior of `asin` and `acos` since they are defined in terms of `atan2`.

 `asin` and `acos` also have undefined behavior in GLSL for ∣x∣ > 1 (MSL and HLSL don't mention any behavior in the ∣x∣ > 1 case)

**Comment by teoxoy** [comment]
This rabbit hole keeps on giving.

`sqrt` and `inverseSqrt` also have undefined behavior in GLSL for x <= 0 (MSL and HLSL not mentioning anything about this case)

This in turn impacting the bahvior of `asin` and `acos` since they are defined as `atan2(x, sqrt(1.0 - x * x))` and `atan2(sqrt(1.0 - x * x), x)` respectively.

**Comment by teoxoy** [comment]
## log, log2

`asinh`, `acosh`, `atanh` are defined using `log` and have well-defined behavior explicitly written in the spec.

However `log` (and `log2`) don't have well-defined behavior for x <= 0

MSL `log`, `log2`: Nothing mentioned

GLSL `log`, `log2`: Results are undefined if x <= 0

HLSL `log`: If the x parameter is negative, this function returns indefinite. If the x parameter is 0, this function returns -INF.

HLSL `log2`: If the x parameter is negative, this function returns indefinite. If the x parameter is 0, this function returns +INF.

## pow

`pow` is defined as `pow(x, y) = exp2(y * log2(x))` (`log2` behavior will impact behavior of `pow`).

GLSL `pow`:
Results are undefined if x < 0.
Results are undefined if x = 0 and y <= 0.

MSL `pow`:
Undefined for x = 0 and y = 0.

HLSL `pow`:
<table>
<thead>
<tr>
<th>X</th>
<th>Y</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr>
<td>&lt; 0</td>
<td>any</td>
<td>NAN</td>
</tr>
<tr>
<td>&gt; 0</td>
<td>== 0</td>
<td>1</td>
</tr>
<tr>
<td>== 0</td>
<td>&gt; 0</td>
<td>0</td>
</tr>
<tr>
<td>== 0</td>
<td>&lt; 0</td>
<td>inf</td>
</tr>
<tr>
<td>&gt; 0</td>
<td>&lt; 0</td>
<td>1/X<sup>-Y</sup></td>
</tr>
<tr>
<td>== 0</td>
<td>== 0</td>
<td>Depends on the particular graphics processor<br> 0, or 1, or NAN<br></td>
</tr>
</tbody>
</table>

**Comment by teoxoy** [comment]
## clamp

The spec currently mentions:
> Returns either min(max(e,low),high), or the median of the three values e, low, high.

While if I were to guess the "the median of the three values e, low, high" only applies when low > high, it's not really clear form the wording (might be worth explicitly stating that it only happens if low > high)

GLSL: Results are undefined if minVal > maxVal
MSL: Results are undefined if minval > maxval.
HLSL: For values of -INF or INF, clamp will behave as expected. However for values of NaN, the results are undefined.

## smoothstep

`smoothstep` is defined using `clamp`

GLSL: Results are undefined if edge0 >= edge1
MSL: Results are undefined if edge0 >= edge1 or if x, edge0, or edge1 is a NaN.
HLSL: Nothing mentioned

**Comment by kdashg** [comment]
`clamp` is fully-defined now. Median-of-three is (surprisingly!) fully-defined. (it's actually the "undefined result" on at least one major vendor, that we want to leverage directly)

**Comment by dneto0** [comment]
Discussed in [2022-04-19 meeting](https://docs.google.com/document/d/19BiwLfTepYLWzpk9HihUfIlHnKZGFFikofIeKQJVAo8/edit#heading=h.f63yadubc2lk)

@kdashg  to propose text.
* For functions that are already slow and not perf-critical, follow JS and WASM rules.
* For others (sqrt, inverseSqrt, log, log2) consider deviating from JS and WASM, to preserve speed.

**Comment by litherum** [comment]
> For others (sqrt, inverseSqrt, log, log2) consider deviating from JS and WASM, to preserve speed.

I don't think this is what the group agreed.

**Comment by litherum** [comment]
> For others (sqrt, inverseSqrt, log, log2) consider deviating from JS and WASM, to preserve speed.

We'd prefer to start off with portable behavior (which can be changed in the future).

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-19-minutes#clarify-undefined-behavior-of-built-in-functions-2765">WGSL meeting minutes 2022-04-19</a></summary>



* KG: A big list.  Let’s make proposals offline.
* Atan2
    * DN: Is there value in defining a rule that are also bad asymptotically?
    * MM: Philosophy should be err on the side of “lets be portable until performance requirements prove otherwise”. Transcendentals are already very slow.  A few can go the other way, like clamp.  Another is inversesqrt.  Log2.  Cases are a little less clear there.
    * KG: Suggestion is use the same behaviours as JS.  
    * MM: Yes, for the ones where perf doesn’t matter, follow JS and WASM.
    * KG: Sounds like mostly spec needed.** I can make a PR**
* BC: When you say “dial it back” do you mean update the spec, or add an enable to provide alternate behaviour.
* MM: Either one.  Could follow what we decided for clamp.  Would only need an enable when adding new functionality or breaking old functionality.  (Even when adding new functionality, not clear).
* BC: Expect we would need an enable for turning off these polyfills that enforced define results for these edge cases.  Would need an enable to change those behaviours . Not opposed to having the enable.
* MM: Could think about adapting fast-math ideas here.


</details>

**Comment by dneto0** [comment]
Consider documenting edge cases involving infinities/NaN, e.g. trunc: https://github.com/gpuweb/gpuweb/issues/3146

**Comment by munrocket** [comment]
Specify function domains will be practical. For example `pow` function is very popular. But it is undefined if x < 0 or if (x = 0 and y ≤ 0) [in OpenGL](https://registry.khronos.org/OpenGL-Refpages/gl4/html/pow.xhtml), but still it is working somehow for x < 0 and y ∈ N in Chrome/Firefox/Safari in WebGL like in [cpp](https://en.cppreference.com/w/c/numeric/math/pow).

Also there are some exceptions that appear only after polyfilling builtin functions in WGSL (https://github.com/gpuweb/gpuweb/issues/3287), will be cool to see it all in one place.

**Comment by munrocket** [comment]
## length, distance

Based on `inverseSqrt` internally, `sqrt` need polyfill here when length=0 or distance=0

> follow JS and WASM rules.

WebAssembly not specifying any special function except `sqrt`. Ecmascript not specifying `Math.pow` [explicitly](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-math.pow)  and in general heavily based on NaNs and Infinities.

**Comment by munrocket** [comment]
## normalize
sqrt(0), https://github.com/gpuweb/gpuweb/issues/3220#issuecomment-1326802134

## tan
Defined as sin(x) / cos(y), division by zero if cos(y) = 0.

## smothstep
If high = low, clamped division by zero is happening.

## refract
if (k = 1.0 - e3 * e3 * (1.0 - dot(e2, e1) * dot(e2, e1)) = 0, sqrt(0) with division by zero can appear.

**Comment by dneto0** [comment]
Sorry for not keeping up on this.
The group has agreed to do the following:
- for const-expr and override-expr, anything generating a NaN or infinity generates an error at shader-creation or pipeline-creation time.  That's documented, but not annotated at each function what that translates to in terms of domain values.
- for runtime-expr anything generating NaN or Infinity may return an indeterminate value.  That's covered in the "floating point evaluation" section, and only partly documented at specific functions. I would like to land specific wording that suggests that NaNs and Infinities *should* be produced as per IEEE 754 recommendation, anticipating a future extension that would require that behaviour.

The IEEE 754 has documented function domains, but they include the cases that generate infinities.  So the WGSL concept does not line up perfectly.

So this needs a bunch of editorial work to implement this direction.

**Comment by dneto0** [comment]
#3508 introduced indeterminate values and gave general rules.
The rest is editorial, to propagate and describe the cases for each builtin functions.
