### ISSUE TITLE
Number literal conversion clarification

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#2769]
I find that the conversion rules in the [Conversion Rank](https://gpuweb.github.io/gpuweb/wgsl/#conversion-rank) table to be underspecified.

- AbstractFloat (i.e. f64) -> f32/f16 (lossy value conversion as described in [Floating Point Conversion](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-conversion) ?)
- AbstractInt (i.e. i64) -> AbstractFloat (i.e. f64) (conversion as described in [Floating Point Conversion](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-conversion) ?)
- AbstractInt (i.e. i64) -> i32 (behavior of (inclusive) range -2^63..-2^31-1 and 2^31..2^63-1 not covered)
- AbstractInt (i.e. i64) -> u32 (behavior of (inclusive) range -2^63..-1 not covered)

The table [Conversion Expressions](https://gpuweb.github.io/gpuweb/wgsl/#conversion-expr) mentiones f32 -> f16 conversion being "lossy value conversion" and I assume it's the same case for AbstractFloat (i.e. f64) -> f32/f16 however it would be nice to mention this in the notes.

Related to this, I find the wording of the [Floating Point Conversion](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-conversion) section quite hard to read and understand.

![image](https://user-images.githubusercontent.com/28601907/163829136-db94a348-f93c-4e4a-ade1-652970c017c8.png)

**Comment by dneto0** [comment]
> AbstractFloat (i.e. f64) -> f32/f16 (lossy value conversion as described in [Floating Point Conversion](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-conversion) ?)

Yes.

> AbstractInt (i.e. i64) -> AbstractFloat (i.e. f64) (conversion as described in [Floating Point Conversion](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-conversion) ?)

Yes.

> AbstractInt (i.e. i64) -> i32 (behavior of (inclusive) range -2^63..-2^31-1 and 2^31..2^63-1 not covered)
> AbstractInt (i.e. i64) -> u32 (behavior of (inclusive) range -2^63..-1 not covered)

These cases were intended to be covered by this statement in [4.2 Types for Creation-Time Constants](https://gpuweb.github.io/gpuweb/wgsl/#types-for-creation-time-constants):

> An evaluation of an expression in one of these types must not overflow or produce undefined results. Otherwise, the result is a [shader-creation error](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error).

However, that text comes after 4.1.2.   You're right, the spec should state the rule up front, to be most clear.

Thanks for the other wording suggestions. Those would be improvements. (I think we recently added a period to the end of "... the destination type", which then disconnected the subclauses.  That was unfortunate.)

Thank you for the close reading!

**Comment by teoxoy** [comment]
I have 3 more parsing related concerns (referencing the text below).

![image](https://user-images.githubusercontent.com/28601907/164751128-6d553ddb-41c8-4fae-9919-c3ed0920a561.png)

1. I suppose `AbstractInt`s (i64) and `AbstractFloat`s (f64) should also be covered here (presumably by the same rules).
2. Does "overflow" for floating point numbers in this context mean a value that would get rounded to +/-infinity?
3. While the text mentions that implementations should error on hexadecimal floats that "cannot be exactly represented by the target type" (where rounding to nearest representable value would take place), I want to confirm that for decimal floats implementations should **NOT** error in this case and values can be rounded up or down to the nearest representable value.
