### ISSUE TITLE
Potential parsing conflict with const literals and postfix expressions.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2772]
Currently the grammar contains `const_literal` as part of the `primary_expression` rule. This is called by `singular_expression`. This means it's valid in the grammar to parse `1.foo` as the `const_literal` (1) from the primary expression and the `.foo` from the `postfix_expression`.

This doesn't happen in tree-sitter because the float regex is greedy and will consume the `1.`. 

This, I believe, can be fixed by moving `const_literal` into `singular_expression` as an entry by itself. I don't see any case where a number can be followed by a `postfix_expression` and `singular_expression` is the only caller of `primary_expression`.

**Comment by mehmetoguzderin** [comment]
(I now see this does not interplay with step 4)

**Comment by dj2** [comment]
Yes, it happens to get handled by the greedy parsing. We could also shift the grammar slightly so it can't happen either way.

**Comment by dneto0** [comment]
Right, it's a very strong tradition that tokenization is always greedy.

However, with context-aware tokenization (#2717),  I think it will be valid for the parser-tokenizer interaction to be like this:
- parser requests the next token
- tokenizer yields the longest candidate token (See #2735)
- If parser fails with that token, then try the next shortest token candidate, and repeat until parsing can succeed.

But if a grammar change can avoid the problem entirely, that's even better.
I'm in favour of making such a fix.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-26-minutes#potential-parsing-conflict-with-const-literals-and-postfix-expsesions--issue-2772-">WGSL meeting minutes 2022-04-26</a></summary>



* DS: Just about moving it down in the grammar, though technically with greedy parsing it’s not a problem just yet. Also we can move it again later if we like.
* **Spec needed**


</details>

**Comment by dneto0** [comment]
Heh.  It should be tokenized as `1.f` `oo`

**Comment by dneto0** [comment]
The longest-candidate token rule means this is not ambiguous.
