### ISSUE TITLE
Dictionary default values referencing type members

### ISSUE THREAD

**Issue by grorg** [gpuweb/gpuweb#278]
I opened this issue on WebIDL. This is our tracking bug.

heycam/webidl#717

**Comment by Kangz** [comment]
@kainino0x or @grorg, do you remember what specific instance in WebGPU we opened this issue for?

**Comment by kvark** [comment]
[Here is](https://github.com/gpuweb/gpuweb/blob/9accf4e48b16570a594ff3b10b9f037952fea15d/spec/index.bs#L8661) one of the cases: 
```
GPUTextureUsageFlags usage = 0x10;  // GPUTextureUsage.RENDER_ATTACHMENT
```

**Comment by kainino0x** [comment]
The original one is in the webidl issue:
`GPUColorWriteFlags writeMask = 0xF;  // GPUColorWrite.ALL`

**Comment by kainino0x** [comment]
I don't think this is going to ever get fixed. If the upstream issue is resolved we can reopen this and do it.
