### ISSUE TITLE
`@const` missing on some built-in functions

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#2787]
`@const` is missing on
- `clamp` [Float Built-in Function](https://gpuweb.github.io/gpuweb/wgsl/#float-builtin-functions)
- `determinant` and `transpose` [Matrix Built-in Functions](https://gpuweb.github.io/gpuweb/wgsl/#matrix-builtin-functions)

This would effectively make all Logical, Float, Integer, Matrix, Vector, Data Packing/Unpacking Built-in Functions `@const` (might be easier to specify this in one place as well but not really what the issue is about).

**Comment by teoxoy** [comment]
I just noticed `bitcast` is also not const but could be. Was it an oversight or was it omitted on purpose?

**Comment by alan-baker** [comment]
This is probably due to a rebase bug. I don't see any problems with bitcast as it is an expression and not a built-in function.
