### ISSUE TITLE
Missing Abstract Int/Float preconditions for Conversion Expressions

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#2788]
Missing Abstract Int/Float preconditions for [Conversion Expressions](https://gpuweb.github.io/gpuweb/wgsl/#conversion-expr)

---

### bool

- Abstract Int/Float -> bool (table entries could be reduced to 2 and preconditions changed to say `AbstractInt, i32 or u32` and `AbstractFloat, f32 or f16`)

  ![image](https://user-images.githubusercontent.com/28601907/165083936-2b421766-0677-48b9-a170-f0ada99a0863.png)

### i32

- AbstractInt -> i32

- AbstractFloat -> i32 (table entries could be reduced to 1 and preconditions changed to say `AbstractFloat, f32 or f16`)

  ![image](https://user-images.githubusercontent.com/28601907/165085108-fdb9e854-be60-4ea5-b619-c6440a165146.png)

### u32

- AbstractInt -> u32 (I think the table entry for this is wrong since it says "Reinterpretation of bits" and AbstractInt's are essentially i64's)

  ![image](https://user-images.githubusercontent.com/28601907/165085511-113c4dfc-82c1-49dd-af2f-84ca3be82d6c.png)

- AbstractFloat -> u32 (again, table entries could be reduced to 1 and preconditions changed to say `AbstractFloat, f32 or f16`)

  ![image](https://user-images.githubusercontent.com/28601907/165086073-7c283316-dcf8-4715-a5df-e978c022f953.png)

### f32 and f16

- AbstractInt -> f32 / f16 (again, table entries could be reduced to 1 for each and preconditions changed to say `AbstractInt, i32 or u32`)
- AbstractFloat -> f32 / f16

---

The list above is concerned with "Scalar conversion type rules" but the same adjustments could be done for the "Vector conversion type rules" and "Matrix conversion type rules" sections.

**Comment by alan-baker** [comment]
These aren't necessary because the standard conversion ranks apply. For example:
```
f16(1) // f16 conversion from abstract int
abstract int -> abstract float -> f16
```

The u32 from AbstractInt is necessary to avoid converting the abstract integer to i32 first.
