### ISSUE TITLE
bindings naming should (maybe) match attributesSet

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#279]
In #249 we used the name `attributesSet` to express that an array expressed an unordered set.

BindGroup(Layout)Descriptor.bindings does not have exactly the same semantics - it is an unordered map, not a set of "pushes" - but we should consider whether it should match that pattern.

Another option is `bindingMaps`.

**Comment by Kangz** [comment]
I think we agreed to go with `entries` since then. Should we close?
