### ISSUE TITLE
Consider making `binding_array` a reserved word

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#2794]
Naga has an experimental implementation of binding arrays, where you write globals like this:

```
@group(42) @binding(1729)
var a: binding_array<texture2d<f32>>;
```

and then there are new variants of (`wgpu`'s analogues of) `GPUBindGroupLayoutEntry` and `GPUBindGroupEntry` that let you supply an array of textures as `a`'s value.

Is it reasonable to ask WGSL to reserve `binding_array` on this basis? If so, then we have a graceful way to prevent people from using `wgpu`'s binding arrays in WebGPU: they simply cannot write bind group layouts that permit them in the first place, so any shader that uses binding arrays cannot be used in any pipeline. (Naga does have feature bits, but we haven't generally used them for things that are part of the shader's interface anyway.)

**Comment by jimblandy** [comment]
Here are the docs for the Naga IR feature. The syntax in the WGSL front end is `binding_array<T, N>`.

https://github.com/gfx-rs/naga/blob/01212b24b982eb3e93f4dc09dc6576034f7b2765/src/lib.rs#L702-L730

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-26-minutes#consider-making-binding_array-a-reserved-word-2794">WGSL meeting minutes 2022-04-26</a></summary>



* **Yes, let’s reserve.**


</details>
