### ISSUE TITLE
Spec clarification around untyped LHS and abstract RHS

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2802]
Clarify that a un-typed LHS and an Abstract value on the RHS will always be either `i32` or `f32` regardless of the value on the RHS. I don't see where this is explained specifically in the text, there is a comment in the examples of:

```
// An integer literal without a suffix tends to be inferred as i32:
//   Initializer for a let-declaration must be constructible (or pointer).
//   The most preferred automatic conversion from AbstractInt to a constructible type
//   is AbstractInt to i32, with conversion rank 2.  So '1' is inferred as i32.
```

Even that says it `tends to be inferred` which imples that it doesn't have to be. There is an exampler further down: 

```
// Invalid.  Select AbstractInt to i32 as above, but the value is out of
// range, producing shader-creation error.
let i32_too_large_2 = 2147483648; // Invalid.
```

which shows that even if the RHS could be `AbstractInt` -> `u32` conversion it still fails. This is because when both sides are untyped the LHS becomes `i32`.

We should state that in the case of the LHS being untyped and the RHS being abstract then if the RHS is `AbstractFloat` the LHS will be `f32` and if the RHS is `AbstractInt` the LHS will be `i32` regardless of the value on the RHS.

**Comment by kdashg** [comment]
Is this just needs-spec, I think?

**Comment by dj2** [comment]
Yea, and I believe dneto0@ already started looking into it.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-17-minutes#spec-clarification-around-untyped-lhs-and-abstract-rhs--issue-2802">WGSL meeting minutes 2022-05-17</a></summary>



* DN: **Already taken care of in separate PR**.


</details>
