### ISSUE TITLE
Attribute 'Valid Values' should be updated for abstract integers

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#2809]
Currently https://www.w3.org/TR/WGSL/#attributes has a list of `Valid Values` for attributes which require `positive i32 literal`, `non-negative i32 literal`, etc.
Since we've added abstract integer literals to the specification, `42` is no longer an `i32`, but an `AbstractInteger`.

I'm assuming we don't want everyone to suffix their values with `i` for attributes?

**Comment by alan-baker** [comment]
I would say that those expressions are typed so standard promotion rules apply.

**Comment by dneto0** [comment]
A better wording would be:

Change: `positive i32 literal` to `integer literal evaluating to a positive i32 value`. 

Similarly for non-negative. 

These are more wordy, but more precise.

**Comment by dneto0** [comment]
Interestingly, because integer literals don't have a leading minus, any integer literal is non-negative.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-17-minutes#attribute-valid-values-should-be-updated-for-abstract-integers--issue-2809">WGSL meeting minutes 2022-05-17</a></summary>



* DN:  Editorial change PR: [Clairfy attribute numeric params #2902](https://github.com/gpuweb/gpuweb/pull/2902)
* DN: About attribute values and currently says +i32 literal which makes seem like requires i suffix which we don’t want. Rewording to integer literal (abstract integer) which yields a positive i32 so you have to coerce and has to fit into i32 range.
* KG: **Approved**.
* AB: **Maybe missing prepositions in diff**.
* DN: **Will incorporate**.


</details>
