### ISSUE TITLE
Parameterization missing for `arrayLength`

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2818]
The `arrayLength` builtin is specified as:

```
fn arrayLength(e: ptr<storage,array<T>> ) -> u32
```

but we don't list out the definition of `T`

**Comment by alan-baker** [comment]
I'm not sure there are any restrictions on `T` beyond the standard array restrictions.

**Comment by dneto0** [comment]
This has been fixed.

> Parameterization	E is an element type for a [runtime-sized](https://gpuweb.github.io/gpuweb/wgsl/#runtime-sized) array,
[access mode](https://gpuweb.github.io/gpuweb/wgsl/#access-mode) AM is [read](https://gpuweb.github.io/gpuweb/wgsl/#access-read) or [read_write](https://gpuweb.github.io/gpuweb/wgsl/#access-read_write)
