### ISSUE TITLE
Clarify behaviour of `fract` with very small negative numbers

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#2822]
The current definition of fract is:
```
Returns the fractional part of e, computed as e - floor(e).
```
which implies a range for `fract(e)` of `[0.0, 1.0)`

If e is a very small negative number, like -1.17549435082e-38 (0x80800000) than on a finite precision implementation like f32 there will be catastrophic cancellation and the formula will return 1.0, which is out of the above range.
The true value here is actually very close to 1.0, but less than 1.0.
The accuracy constraint for fract is correctly rounded, so by my understanding of the spec that both the floating point number before 1.0 and 1.0 are acceptable answers, which seems wrong to me, given that 1.0 isn't a fractional part.
This also becomes a problem test implementation wise, since 1.0 is precisely expressible as a f32, so correctly rounded degrades to exact match, so my initial naive implementation would only accept 1.0.

SwiftShader handles this by having an explicit clamp on the return value to the smallest number less than 1.0, which is what led me down the path of understanding what is happening here. I am not sure what other implementations do in this case, i.e. clamp like SwiftShader, return 1.0, or possibly wrap around to 0.0.

I think the language around the definition of fract needs to be clarified to discuss what should happen for very small negative numbers and be explicit about the range for `fract(e)`.

**Comment by zoddicus** [comment]
For at least one Nvidia device it is returning 1.0, so this may just need an addition that the range of acceptable results is `[0.0, 1.0]`

**Comment by dneto0** [comment]
if 1.0 is a possible answer then it isn't really _correctly rounded_.

Maybe the fix is to say that the accuracy of fract(x) is "inherited" from x - floor(x), and to add a note about the valid resulting range.

**Comment by greggman** [comment]
does `fract(fract(smallNegativeNumber)` work? My logic would be fract(smallNegativeNumber) = 1.0 and fract(1.0) = 0.0  but of course the driver my optimize out the 2nd fract.
