### ISSUE TITLE
WGSL identifier comparison

### ISSUE THREAD

**Issue by xfq** [gpuweb/gpuweb#2828]
https://gpuweb.github.io/gpuweb/wgsl/#identifier-comparison

WGSL identifiers compare by code points, which is in line with the i18n WG's recommendation. However, the i18n WG thinks mentioning "conventional normalization" may mislead implementers, so we recommend adding a green box like the one in https://w3c.github.io/bp-i18n-specdev/#spec_n11n instead of listing the normalization forms etc. here.

In addition, we recommend linking to [identical to](https://infra.spec.whatwg.org/#string-is) in Infra directly in the first paragraph.

**Comment by mehmetoguzderin** [comment]
Hello,

First of all, thank you and the i18n WG for all the feedback that help improve both WebGPU & WGSL specs with remarkable expertise.

I would like to address this issue's content in two headlines, first n11n change and then the comparison.

The wording inside the bp-i18n-specdev is concise and clear enough, especially in terms of its specificity, that I believe we can directly take it to our spec, which I did in the https://github.com/gpuweb/gpuweb/pull/2845 PR. However, please take a look just in case I made a mistake or it would not satisfy.

We did consider using identical-to and deliberately opted not to do it. With all due respect to Infra's definition of code units as different from Unicode's, where it even says "string can also be interpreted as containing code points" clarification, we would like to avoid the potential confusion of "string consisting of the code units 0xD83D, 0xDCA9, and 0xD800, when interpreted as containing code points, would consist of the code points U+1F4A9 and U+D800" in the same spec and just keep everything to code points as that is how we perceive the spec. Please see the clear comment by @dneto0 in https://github.com/gpuweb/gpuweb/pull/2767#discussion_r854435943 for further explanation.

If our reasoning for the second headline is acceptable, I'd appreciate it if we could mark this issue as done after the merge of the https://github.com/gpuweb/gpuweb/pull/2845 PR.

Thank you!

**Comment by mehmetoguzderin** [comment]
@xfq An update, we did merge the PR mentioned above. Hence, only the second headline in the previous comment is relevant now. Thank you!

**Comment by xfq** [comment]
The i18n WG discussed this issue in this week's teleconference and we were satisfied with your solution.

**Comment by mehmetoguzderin** [comment]
@xfq Thank you! Closing this one.
