### ISSUE TITLE
Consider associating the texture with its clear color value

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#284]
We could consider having the clear color to be a part of the `TextureDescriptor`. Justification:
  1. D3D12 specifically has this specified at [resource creation](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/nf-d3d12-id3d12device-createcommittedresource) and I vaguely recall this matching some of the specifics of AMD hardware (but need to investigate more to confirm this).
  2. it's not a common thing to vary the clear color for a particular texture.
  3. straightforward clear operation (in `RenderPassDescriptor`) just being an enum of "clear"/"load" (related to #283 and  #276).
  4. we could still provide an API for clearing with custom values, perhaps as a simple `clearImage` that is performed out of the pass, or `clearAttachment` within a pass.

**Comment by jdashg** [comment]
This could be cool. Would we make RenderPassDesc.clearColor nullable, or just ask users to try to match the TextureDesc.clearColor and RenderPassDesc.clearColor?

**Comment by kvark** [comment]
I think we wouldn't have `RenderPassDesc.clearColor` at all. If the user decides they need to clear a render target with a different color, we can either:
  - ask them to call `CommandEncoder.clearImage()` that has a color parameter
  - ask them to call `RenderPassEncoder.clearAttachment()` that has a color parameter
  - or ask them to just draw a quad :P

**Comment by magcius** [comment]
The reason for the "clear color" on the texture is for fast clear semantics. The idea is that framebuffer compression likely has a few colors it can associate with "cleared target", and a clear will mark it as that value. Not all framebuffer compression can have more than one "fast clear" color (NVIDIA can support multiple, AMD can only support one, not sure about other GPUs), and some do not allow making fast clear customizable, hardcoding to either transparent or opaque black. They rely on users either marking loads as DONT_CARE, or setting their clear color to the one they support.

I can't remember if there's a way to get the "preferred clear color" for a render target in Vulkan. If there was, I would suggest exposing that, though it might be unpredictable across platforms.

**Comment by kainino0x** [comment]
For the record, though we just merged #283, this may end up overriding that change.

**Comment by kainino0x** [comment]
@kvark maybe we could put this on the agenda for next meeting? Since the topic is relatively fresh in our minds.

**Comment by kvark** [comment]
@kainino0x sure, let's talk about this a bit next time. The change was initially motivated as a solution to clear value specification that we were discussing. Now there is less of an appeal, but it could still be useful, as long as we explicitly design it for fast clears.

**Comment by kainino0x** [comment]
Yeah, it makes a lot of sense to me especially since D3D12 already exposes pOptimizedClearValue, and if we ever want to add clear color to RenderPassDescriptor, it would be a nonbreaking change. (Of course, having it there and adding it here later would also be nonbreaking.)

**Comment by kainino0x** [comment]
(F2F) Direct from the D3D12 team: "Don't do this." Closed!
