### ISSUE TITLE
Clarify the buffer slots validation rule in "valid to draw with GPURenderCommandsMixin"

### ISSUE THREAD

**Issue by jzm-intel** [gpuweb/gpuweb#2843]
Currently the validation of drawing with `GPURenderCommandsMixin` encoder in WebGPU [Spec](https://www.w3.org/TR/webgpu/#abstract-opdef-valid-to-draw) requires that
> * For each [GPUIndex32](https://www.w3.org/TR/webgpu/#typedefdef-gpuindex32) slot 0 to pipelineDescriptor.[vertex](https://www.w3.org/TR/webgpu/#dom-gpurenderpipelinedescriptor-vertex).[buffers](https://www.w3.org/TR/webgpu/#dom-gpuvertexstate-buffers).length:
>   * encoder.[[[vertex_buffers]]](https://www.w3.org/TR/webgpu/#dom-gpurendercommandsmixin-vertex_buffers-slot)[slot] must not be null.

However, the `vertex.buffers.length` is unclear here. When creating a render pipeline descriptor, we can use vertex buffer slots in a discontinuous manner, e.g. used the slot 1 and slot 7 while leave other slots unused. This is exactly the case in [CTS `api,operation,vertex_state,correctness:discontiguous_location_and_attribs`](https://github.com/gpuweb/cts/blob/main/src/webgpu/api/operation/vertex_state/correctness.spec.ts#L1049). However, in this situation, we will have a `vertex.buffers` array that looks like `[empty, {...}, empty x 5, {...}]`. This is an array **of length 8** rather than 2, but actually only 2 slots are used.

I would propose that we can clarify the validation rules as:
> * For each [GPUIndex32](https://www.w3.org/TR/webgpu/#typedefdef-gpuindex32) slot 0 to pipelineDescriptor.[vertex](https://www.w3.org/TR/webgpu/#dom-gpurenderpipelinedescriptor-vertex).[buffers](https://www.w3.org/TR/webgpu/#dom-gpuvertexstate-buffers).length:
>   * if pipelineDescriptor.[vertex](https://www.w3.org/TR/webgpu/#dom-gpurenderpipelinedescriptor-vertex).[buffers](https://www.w3.org/TR/webgpu/#dom-gpuvertexstate-buffers)[*slot*] is not [undefined](https://webidl.spec.whatwg.org/#idl-undefined), encoder.[[[vertex_buffers]]](https://www.w3.org/TR/webgpu/#dom-gpurendercommandsmixin-vertex_buffers-slot)[slot] must not be null.

**Comment by takahirox** [comment]
I think this change sounds good. In addition to @jzm-intel mentioned, under the current spec buffers must be set with [`setVertexBuffer()`](https://www.w3.org/TR/webgpu/#dom-gpurendercommandsmixin-setvertexbuffer) even to unused slots (where slots <  pipelineDesctiptor.vertex.buffers.length) but it is a bit weird to me. With this change, buffers will no longer need to set to unused slots.
