### ISSUE TITLE
`textureGather` limits on `coords` and `array_index`

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2850]
In the https://www.w3.org/TR/WGSL/#texturegather section we list the values and consequences for the `component` and `offset` values but not the `coords` or `array_index` parameters.

1. What is the valid range for `coords`?
2. Is it a `shader-creation error` to go outside those `coord` bounds?
3. What is the bounds for the `array_index` parameter?
4. Is it a `shader-creation error` to go outside those `array_index` bounds?

**Comment by alan-baker** [comment]
Both parameters are are bound by the behaviour of the sampler addressing mode (see https://gpuweb.github.io/gpuweb/#enumdef-gpuaddressmode) so out-of-bounds behaviour is fully defined.

**Comment by dj2** [comment]
In which case, can we link to that from the WGSL spec? What happens if I violate those bounds, is it a shader-creation error or undefined behaviour or something else?

**Comment by dj2** [comment]
Or is it that I _can't_ violate the bounds as they just do the clamping or wrapping or whatever? So, really there are no bounds?

**Comment by alan-baker** [comment]
There is no out-of-bounds because of the clamping, mirroring, etc. That's what I meant by fully defined.
