### ISSUE TITLE
Should cullMode require "none" for points and lines?

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#2863]
This was an inline issue in the spec, and seems trivial enough to resolve that I'm writing it up as a hopeful tacit resolution candiate. Currently the `GPUPrimitiveState` has a `cullMode` that defaults to `"none"`, but the other possible cull modes (`"front"` and `"back"`) don't apply if the `topology` is a point or line type.

In some other cases, such as `stripIndexFormat`, we've required that the value be left `undefined` when it doesn't apply, so we could do the same here. 

On the other hand, there's no particular issue with developers specifying a cull mode in these cases. It's not validated on any of the native APIs, doesn't cause adverse effects when rendering, and the default is such that developers who specify it are really just making more work for themselves.

My preference is to simply not validate it. There's no technical reason to block developers from setting this, and doing so mildly breaks backwards compatibility.

**Comment by kainino0x** [comment]
I have no opinion about this, I think leaving it unvalidated is fine.

For stripIndexFormat I think we wanted to validate it was undefined for non-strip topologies because otherwise it was ambiguous whether it should be validated to match at draw time or not.

**Comment by kainino0x** [comment]
This was a non-change to the spec, but let's mention it during "tacit resolution" next week anyway.
