### ISSUE TITLE
Initialization of `GPUObjectBase` internal slot is left unspecified

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#2871]
Many interfaces in the WebGPU spec include `GPUObjectBase`, which means they have a `[[device]]` internal slot, but the spec does not say how this is initialized. It's usually clear what's intended, but the spec should say what it means.

For example, `GPURenderPipeline` includes `GPUObjectBase`, and the pipeline's `[[device]]` internal slot is consulted by the *getBindGroupLayout* algorithm, but the *createRenderPipeline* algorithm nowhere mentions the `[[device]]` slot; it simply says,

> Let pipeline be a new valid [GPURenderPipeline](https://www.w3.org/TR/webgpu/#gpurenderpipeline) object.

This seems to be a common omission throughout the spec.

Perhaps the "let IDENT be a new valid TYPE" language should be replaced with something like, "let IDENT be a new valid TYPE owned by DEVICE". Then that phrase could be defined in the "WebGPU interfaces" section.

**Comment by toji** [comment]
This is addressed by #4615
