### ISSUE TITLE
editorial: add example showing how to write an i32 of most negative value

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2872]
Feedback from a correspondent:   To write the most negative i32 value a programmer may try to write   `-2147483648i`.  But this doesn't work because it's parsed as a unary negation over `2147483648i` but that is an invalid literal because it overflows i32.

Answer:

To write an i32 with minimum value, the programmer can write   i32(-2147483648)
Here:

       2147483648  is a literal that is AbstractInt
      -2147483648 is an expression yielding AbstractInt

The next step is to do overload resolution of   i32(-2147483648)
The feasible "overload candidates" are:

     i32(i32) -> i32         conversion rank  3
     i32(u32) -> i32        rank 4
     i32(f32) -> i32         rank 6
     i32(f16) -> i32        rank 7

So we attempt a value conversion of  abstract int  -247483648 to i32, and that does work, so the program is valid and you get the correct value.

This is *not* obvious. 

Note that WGSL has an explicit  u32(AbstractInt) constructor so to make it valid to write

      u32(247483648)

**Comment by alan-baker** [comment]
https://gpuweb.github.io/gpuweb/wgsl/#integer-types contains this info.
