### ISSUE TITLE
Precision when behavior of float built-in functions is implementation-specific  

### ISSUE THREAD

**Issue by ghadeeras** [gpuweb/gpuweb#2884]
[Note: This issue is submitted following a brief conversation in the WebGPU Matrix chat room]

The IEEE-754 standard defines a few special numbers such as signed zeros, subnormal numbers, infinities ... etc. It is unclear if the WGSL built-in functions operating on floating-point numbers should be assumed to strictly follow that standard, or if in some cases their behavior could deviate or be implementation-specific/dependant. If the latter is the case, then maybe the WGSL specs should hint at that.

One example that comes to mind is the `sign(e: T) -> T` function. The specs only say that it "Returns the sign of e. Component-wise when T is a vector". In pure mathematical sense, a zero does not have a sign. But the IEEE-754 standard defines negative and positive zeros, and for the `sign()` function it is unclear which context should be assumed. For example, JavaScript's `Math.sign()` returns `0.0` or `-0.0` if passed a zero, instead of `1.0` or `-1.0`.

From what I gathered during the aforementioned brief chat, shader compilers favor `--ffast-math` mode which could break compliance with the IEEE-754 standard. So, maybe this warrants precising when they could deviate and when the behavior is well-defined?

**Comment by alan-baker** [comment]
Since it was mentioned on the chat, https://gpuweb.github.io/gpuweb/wgsl/#floating-point-accuracy describes that signed zeros, infinities and nans may not be preserved.

**Comment by ghadeeras** [comment]
@alan-baker, indeed that section was pointed out after I created this issue. Unless anyone has another opinion, I could close this issue. Or feel free to do so. Personally, I thought linking to that section from other related sections would be good, but that is just a nice-to-have thing.

**Comment by alan-baker** [comment]
Sorry, I wasn't trying to express an opinion. I just wanted to capture the reply for anyone else who comes to read this issue.

**Comment by kdashg** [comment]
It would be so great to have caveats for all of these with the common edge cases we expect, given our looser guarantees (which are also not-quite-hidden a few pages away).

**Comment by dneto0** [comment]
fixed by #4825
