### ISSUE TITLE
forbid spelling out pointer types that are not instantiable

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2886]
Followup to #2268 and its fix in #2866, which addressed formal arguments with pointer type.

Currently we can write nonsensical and useless type aliases:

```rust
type p = ptr<workgroup,array<i32>>;
```
When #2866 fixed was disallowing something like p as a formal argument type.
But we should probably also prevent creating the type alias in the first place.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-05-17-minutes#forbid-spelling-out-pointer-types-that-are-not-instantiable-2886-">WGSL meeting minutes 2022-05-17</a></summary>



* DN: Follow up to JB issue about formal params to functions. Thought was only case needed but thought about type aliases and think we should ban that. Compiler could be simpler if not needed
* JB: Strongly support
* KG: Makes sense to me. **Resolved**.


</details>
