### ISSUE TITLE
Add texture types to `t` for textureSampleGrad and textureSampleBias

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2892]
Most of the texture builtins list the valid texture types for the `t` parameter (e.g. `The sampled, depth, or externa texture to sample.`

The `textureSampleGrad` and `textureSampleBias` builtins just say `the texture to sample`. This should be exampled to match the other builtins.

**Comment by dneto0** [comment]
this is fixed in top-of-tree.
