### ISSUE TITLE
Not starting on macOS High Sierra

### ISSUE THREAD

**Issue by kudi82** [gpuweb/gpuweb#290]
I do not know based on the documentation if it should run under 
`macOS 10.13.6`
with Chrome
`Version 76.0.3790.0 (Offizieller Build) canary (64-Bit)`

At the moment I cannot even open the hello_triangle.html page neither any console output. 

![Bildschirmfoto 2019-05-10 um 21 49 57](https://user-images.githubusercontent.com/1053262/57552894-9af6b600-736d-11e9-8565-c0ec37ce9681.png)

**Comment by kvark** [comment]
@kudi82 this project is for API discussion, it's not the right place to file bugs about Chrome's implementation prototype.
