### ISSUE TITLE
Clarify the normalized float ranges in the `pack` methods

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2903]
Each of the `snorm` and `unorm` pack methods say they convert `normalized floating point values`. What isn't clear is what the range of the normalized floats are. For the `snorm` versions the floats are `[-1, 1]` but for the `unorm` versions they are `[0, 1]`.

We should clarify in the functions what the range of floats begin handled are.

**Comment by dneto0** [comment]
Right.  These are very closely related to the unorm snorm channel transfer functions defined in the channel formats table in the [texel formats](file:///Users/dneto/project/gpuweb/wgsl/index.html#texel-formats) section.
But yes, we should spell this out.


Related: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#fundamentals-fixedfpconv
