### ISSUE TITLE
Clarify `Valid Values` language in the attributes table.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2916]
Currently the `Valid Values` column says things like `integer literal, yielding a positive i32` which I took to mean it could be `1u` as an integer literal and the compiler would treat it as `i32`. This seems to be incorrect and this means it can be `AbstractInt` or `i32` but not `u32`.

We should make explicit what types can be provided to the various attribute values. Even just making a list like:

* AbstractInt
* i32
* Must be positive

Could be clearer?

**Comment by dneto0** [comment]
That three-bullet list isn't quite right because its "or" between the first two, and "and" with the last.

Before the last change I had [suggested](https://github.com/gpuweb/gpuweb/issues/2809#issuecomment-1129144561)

> integer literal evaluating to a positive i32 value

Would that be any clearer?

The 1u cannot evaluate to an i32 value because there is no [feasible automatic conversion](https://gpuweb.github.io/gpuweb/wgsl/#feasible-automatic-conversion)

**Comment by dneto0** [comment]
Also, we've deliberately decided to keep the compilers simple by keeping these as literals, not creation-time expressions.
See #2790 (post-V1) and its duplicate #2890

So we definitely want the wording that it must be a literal.

**Comment by dj2** [comment]
Even just:

* AbstractInt or i32 literal
* Must be positive

the `evaluating` could work but spelling out the types is more explicit.

**Comment by dneto0** [comment]
Works for me.

**Comment by dneto0** [comment]
Currently says things like

>  [Must](https://github.com/gpuweb/gpuweb/issues/2916#shader-creation-error) be a positive [i32](https://github.com/gpuweb/gpuweb/issues/2916#i32) or [AbstractInt](https://github.com/gpuweb/gpuweb/issues/2916#abstractint) [literal](https://github.com/gpuweb/gpuweb/issues/2916#integer-literal)


It's not clear how far the "or" distributes.

What would be better is to write two sentences: one about types, the other about value.

> Must be i32 or AbstractInt
> Must be positive.
