### ISSUE TITLE
editorial bugs in WGSL spec

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2920]
From email

Hi,

I recently read the WGSL spec and noticed 3 minor mistakes.
1- repeated word. Search for  `Selective execution: if/else if/else, switch.`
2- broken anchor in a link: Search for `See WebGPU § GPUExternalTexture.`
3- Code that does not compile: a should be a var.
```

let a: i32 = 2;

var i: i32 = 0;      // <1>

loop {

  if i >= 4 { break; }


  a = a * 2;


  i++;

}

```

Hope it helps.

**Comment by dj2** [comment]
The first one isn't repeated wording, it just looks weird. Its `if` / `else if` / `else`. But the slashes make it look like `if/else` `if/else`

**Comment by dneto0** [comment]
For the last problem, Tint emits this diagnostic:

```
a.wgsl:10:3 error: cannot assign to 'let'
  a = a * 2;
  ^

a.wgsl:5:5 note: 'a' is declared here:
let a: i32 = 2;
    ^
```
So that's nice.

**Comment by dneto0** [comment]
All items addressed in the 3 PRs.
