### ISSUE TITLE
Spec prose seems to allow `staticAssert` before `global_directive`

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2931]
Currently the spec states for Directives (https://www.w3.org/TR/WGSL/#directives): `If present, all directives must appear before any declarations.`

This makes no mention of `staticAssert` which are statements. `staticAssert` can come at module scope, we should clarify that all directives must come before any non-comment content.

**Comment by alan-baker** [comment]
This is enforced in the grammar, but probably could be clearer.
