### ISSUE TITLE
Update note about when automatic conversions occur.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2939]
Currently the spec has a note stating:

> Note: Automatic conversions only occur in two kinds of situations. First, when converting a creation-time constant to its corresponding typed numeric value that can be used on the GPU. Second, when a load from a reference-to-memory occurs, yielding the value stored in that memory.

If you lookup `creation-time constant` it is a name for a value. The above note isn't correct as `@workgroup_size(1, 1, 1)` does automatic conversions from an `AbstractInt` type but is not a creation-time constant, nor is it a load.

The Note should be updated to include any places abstract values can be auto-converted.

**Comment by dneto0** [comment]
Right, should probably creation-time value.

"creation-time constant" got overloaded as both the values that are generatd by creation-time expressions, and also the declarations that give those things names.
