### ISSUE TITLE
Specify the meaning of `S` in the ConversionRank table

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2940]
In the `ConversionRank` table we list `ref<S,T,A> where A is read or read_write` which defines the meaning of `A`, and `T` is the type we care about, but `S` is not defined.

This is more confusing as if you read to the bottom of the table there _are_ `S`'s defined. But, in the other cases `S` is a type, and in this case `S`, I believe, is `AddressSpace`

**Comment by dneto0** [comment]
Of all the spelling out of `ref<....>` that use parameter letter for the address space, they are all  `S` except for two cases where it uses `SC` (oops).

It would be nice to use `A` for address space, but then we would have to change `A` for access mode into `M` for access mode.
