### ISSUE TITLE
wgsl editorial: change ref<S,T,A>  ->  ref<A,T,M>

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2943]
Of all the spelling out of ref<....> that use parameter letter for the address space, they are all S except for two cases where it uses SC (oops).

It would be nice to use A for address space, but then we would have to change A for access mode into M for access mode.

Forked from #2940

**Comment by dj2** [comment]
Maybe also link `AM`, `AS` to the address space and access mode definitions?

**Comment by dneto0** [comment]
I'm finding a bunch of places in vector-access expression, matrix-access expression etc. where there is no access mode shown on the ref type. Fixing that too.

**Comment by dneto0** [comment]
> Maybe also link AM, AS to the address space and access mode definitions?

In general, no.  We write them as Bikeshed var elements, so that when you click on them they will auto-colour to find all the instances of that var within a single algorithm.  If we cross-linked to the address space and access mode definitions, I think you would lose that.

I'm relying on readers looking up the 'ref' or 'ptr' types instead. That's the better context.

**Comment by dj2** [comment]
The links to address space and access mode in the prose are what I was looking for.
