### ISSUE TITLE
[TAG review] Should there be a higher granularity for selecting devices?

### ISSUE THREAD

**Issue by kdashg** [gpuweb/gpuweb#2945]
From https://github.com/w3ctag/design-reviews/issues/626#issuecomment-1134097367
> Should there be a higher granularity for selecting devices? For example, for cases where one wants to select a high-VRAM device (e.g. for machine learning workloads) or the non-dominant (e.g. secondary device which hopefully will not jank the current compositor) device. Allowing a single application to be the dominant resource user is not new, but it is definitely something that want to be careful about.

**Comment by litherum** [comment]
Resolved today: this isn't necessary because almost all machines have either 1 or 2 devices which are already addressable by just the high-performance/low-power existing toggle.
