### ISSUE TITLE
[TAG review] Wondering if power consumption choice should be initiated by the user

### ISSUE THREAD

**Issue by kdashg** [gpuweb/gpuweb#2946]
From https://github.com/w3ctag/design-reviews/issues/626#issuecomment-1134097367
> Power consumption is a concern. While there is a mechanism to allow applications to request a high power vs low power device, we are wondering if the choice should be initiated by the user, and not the application. e.g. if the user is on the go, let them choose integrated GPU instead of discrete to save power. Initially, we discussed the possibility of forcing the application to integrated in low-power scenarios, but adds another fingerprinting surface so we don't think this is a valid suggestion.

**Comment by greggman** [comment]
To me this seems out of scope for WebGPU. It seems like a browser (UA) issue. 

* A UA can do notihng
* A UA can pay attention to the OS's low-power mode and in response choose the low-powered GPU, and throttle video, throttle JavaScript, throttle rAF, throttle animation frame rates, start returning `refers-reduced-motion` CSS media query, only allow playing one video at a time, etc...
* A UA can put global settings for low-power
* A UA can put per page settings for low-power
* A UA can put per power source settings for low-power (connected to power, on battery)
* A UA can put indivual settings for all of these things (default camera, default mic, default gpu, default max fps, etc...)

It's not clear why WebGPU itself would have any thing to say here.

**Comment by litherum** [comment]
Resolved today: a UA _already can_ make the power consumption choice be initiated by the user.
