### ISSUE TITLE
[TAG review] Have a note suggesting surface a warning about power usage?

### ISSUE THREAD

**Issue by kdashg** [gpuweb/gpuweb#2947]
From https://github.com/w3ctag/design-reviews/issues/626#issuecomment-1134097367
> It might be useful to have a note suggesting implementations should surface a warning about power usage at some point, given that this would be permission free.

**Comment by greggman** [comment]
repeating the point I made before. This seems out of scope for WebGPU. I wouldn't want a message from the browser "Warning: This page is using lots of GPU". Rather I'd want a message "Warning: This page is using lots of power"

A page can use too much power by running too much JavaScript, playing too many videos, drawing too much stuff in canvas, using too many CSS animations, playing lots of gifs, etc... Warning about power usage seems a much higher level issue than at the WebGPU level.
