### ISSUE TITLE
Conversion expressions for the Abstract types

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2959]
Currently in the [Conversion Expressions](https://www.w3.org/TR/WGSL/#conversion-expr) table we only list an `AbstractInt` overload for the `u32` and `vecN<u32>` conversions. This seems to be implicitly assuming the conversion for the conversions for others will materialize from the abstract to concrete type before doing the conversion.

This would, I think, be clearer if we updated the table to make it explicit that for each row with `e: i32` we have `e: i32 or AbstractInt` and for each `e: f32` we have `e: f32 or AbstractFloat`.

This would make it obvious that `bool(1)` is valid as otherwise you have to realize it will convert to `i32` and use the `e: i32` rule.

**Comment by dj2** [comment]
It's true as @alan-baker says in the PR they aren't strictly needed, but I think they would help a lot with clarity.

**Comment by dneto0** [comment]
Editors discussed this.   The proposal would add a lot of duplication and be prone to missing some parts; that would raise confusion in the spots when the duplcation isn't made.
Automatic conversions from abstract to concrete is a fundamental feature, so we don't support having too many duplicative crutches in the text.  It's better to concentrate on good examples in the Abstract Numeric Types section and the Overload Resolution section.
