### ISSUE TITLE
Remove variations of "read-only" usages?

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#296]
Given that buffer/texture usage belongs to an internal state of a resource (users don't set it explicitly), and we allow multiple read-only usages to co-exist, what is the point to distinguish between different read-only usages (from the specification point of view) at all?

Perhaps, we should write the specification in such a way that there is a single "Read" usage, and a resource can only be in one of the allowed usages at a time. I.e. the rules become simpler, and usage becomes purely exclusive.

For example, buffer usage rules would be rewritten as:
---
Buffers have the following usages (and commands inducing that usage):
  - `READ` for buffers that are read only by the following commands:
    - `WebGPUCommandEncoder.setVertexBuffers` parameter `buffers
    - `WebGPUCommandEncoder.setIndexBuffer` parameter `buffer`
    - `WebGPUCommandEncoder.{draw|drawIndexed|dispatch}Indirect` parameter `indirectBuffer`
    - `setBindGroup` parameter `bindGroup` created with one of the following types:
      - "uniform-buffer"
      - "dynamic-uniform-buffer"
    - `copyBufferToBuffer` parameter `src`
    - `copyBufferToTexture` parameter `source.buffer`
  - `STORAGE` for `setBindGroup` parameter `bindGroup` created with one the following types:
    - "storage-buffer"
    - "dynamic-storage-buffer"
  - `TRANSFER` for buffers used as the copy destination of `copy{Buffer,Texture}ToBuffer`

**Comment by Kangz** [comment]
Specifying read-only usages for buffers helps place the resource in the correct spot in memory. For example [this is important on Intel because of some probably HW bug for vertex buffers](https://github.com/mesa3d/mesa/blob/master/src/intel/vulkan/anv_device.c#L199). Also IMHO it isn't a big burden for the application to list all the usages it wants from a resource.

**Comment by kvark** [comment]
@Kangz my concern is about the usage rules, not creation time. Saying that, I didn't consider the changes to creation routines that would be associated with this change. Gotta think about this a bit more.

**Comment by Kangz** [comment]
Oh, sorry I misunderstood your proposal. Yeah the usage validation rules could be simplified a bit with what you outlined. I think it would be equivalent to the current rules, just simpler to understand.

**Comment by kvark** [comment]
I think we can close this. The bitflags still need to exist for specifying what a resource is capable of at creation, even if we can specify them simpler at the use site.
