### ISSUE TITLE
Clarify meaning of `context` in integer example in `TYPE INFERENCE FOR LITERALS`

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2970]
In the `TYPE INFERENCE FOR LITERALS` we say:

```
// When the context does not force a concrete type, an integer literal is
// interpreted as an i32 value:
```

Clarify what `context` means in this statement. Specifically, the context is the line itself, and not any other parts of the program.

**Comment by kdashg** [comment]
@dneto0 Is this not "editorial"?

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-30-minutes#clarify-meaning-of-context-in-integer-example-in-type-inference-for-literals-2970-">WGSL 2022-08-30 Minutes</a></summary>

* David: **Yes, this is editorial**.
* DN: Forgot marked as not-editorial, re-marked as editorial. 

</details>
