### ISSUE TITLE
wgsl: Add some clarification in the `Scalar Types` section that an Abstract is not a scalar type

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2975]
The Abstract numbers are not considered scalar types. It would be nice to see a line in the [Scalar Types](https://www.w3.org/TR/WGSL/#scalar-types) section which states something like:

`Note, all scalar types are concrete types. As such, they do not include the abstract numbers.`

Or something ...

**Comment by dneto0** [comment]
Yep, needs a clarification.

It still feels a little weird that AbstractInt and AbstractFloat are not scalar.  We have abstract and concrete vectors, and would naturally have abstract and concrete matrix.  Seems like an ok fit to have abstract and concrete scalars.

May be better to have that holistic switch.

**Comment by alan-baker** [comment]
@dj2 the spec now includes abstracts in scalar types. Do you still have an issue here?

**Comment by dj2** [comment]
Nope, should be resolved I think.
