### ISSUE TITLE
wgsl: key use cases for Vector and Matrix seem out of place

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2976]
In the Types section (https://www.w3.org/TR/WGSL/#vector-types) and (https://www.w3.org/TR/WGSL/#matrix-types) we list some key use cases. This is only done for the vector and matrix types and seems out of place given nothing else has them?

Further the matrix type has a description of the product operator which seems like it would be repeating what is in the `*` definition in the `Arithmetic Expressions` section?

**Comment by alan-baker** [comment]
We don't think it is harmful to mention, nor does every type need such information.
