### ISSUE TITLE
atomic types section references `QueueFamily` which doesn't seem to be defined

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2979]
In [Atomic Types](https://www.w3.org/TR/WGSL/#atomic-types) we say `while those in the [storage](https://www.w3.org/TR/WGSL/#address-spaces-storage) address space have a memory scope of QueueFamily.`

I don't see `QueueFamily` defined anywhere in the spec. Should this be a link back to the WebGPU API spec or somewhere else?

**Comment by alan-baker** [comment]
It is defined in the Vulkan spec via a normative reference to the Vulkan Memory Model.

**Comment by dj2** [comment]
We should add a link from `QueueFamily` to the normative reference.
