### ISSUE TITLE
wgsl: Mark type constructors `@const`?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2982]
For the builtins we prefix an `@const` for ones which can be used in constant expression. We do not mark any of the type constructors as such.  We should mark the type constructors as `@const` to be consistent with the builtins.

**Comment by dj2** [comment]
They look like functions when reading the spec and, I thought, the simple rule was any `@const` function was callable as const-expr which made me think these were _not_ usable in a const-expr context.

**Comment by alan-baker** [comment]
These were moved into built-in functions and marked as `@const` and `@must_use`.
