### ISSUE TITLE
wgsl: Other language types in reserved word list

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2983]
We previously unreserved type names in other languages. The following list still exist as reserved, which, if any, should be removed?

* 'RWBuffer'
* 'RWByteAddressBuffer'
* 'RWStructuredBuffer'
* 'RWTexture1D'
* 'RWTexture1DArray'
* 'RWTexture2D'
* 'RWTexture2DArray'
* 'RWTexture3D'
* 'StructuredBuffer'
* 'Texture1D'
* 'Texture1DArray'
* 'Texture2D'
* 'Texture2DArray'
* 'Texture2DMS'
* 'Texture2DMSArray'
* 'Texture3D'
* 'TextureCube'
* 'TextureCubeArray'
* 'atomic_uint'
* 'bf16'
* 'cbuffer'
* 'char'
* 'dword'
* 'f64'
* 'fvec2'
* 'fvec3'
* 'fvec4'
* 'hvec2'
* 'hvec3'
* 'hvec4'
* 'i16'
* 'i64'
* 'i8'
* 'iimage1D'
* 'iimage1DArray'
* 'iimage2D'
* 'iimage2DArray'
* 'iimage2DMS'
* 'iimage2DMSArray'
* 'iimage2DRect'
* 'iimage3D'
* 'iimageBuffer'
* 'iimageCube'
* 'iimageCubeArray'
* 'image1D'
* 'image1DArray'
* 'image2D'
* 'image2DArray'
* 'image2DMS'
* 'image2DMSArray'
* 'image2DRect'
* 'image3D'
* 'imageBuffer'
* 'imageCube'
* 'imageCubeArray'
* 'isampler1D'
* 'isampler1DArray'
* 'isampler2D'
* 'isampler2DArray'
* 'isampler2DMS'
* 'isampler2DMSArray'
* 'isampler2DRect'
* 'isampler3D'
* 'isamplerBuffer'
* 'isamplerCube'
* 'isamplerCubeArray'
* 'itexture1D'
* 'itexture1DArray'
* 'itexture2D'
* 'itexture2DArray'
* 'itexture2DMS'
* 'itexture2DMSArray'
* 'itexture2DRect'
* 'itexture3D'
* 'itextureBuffer'
* 'itextureCube'
* 'itextureCubeArray'
* 'matrix'
* 'samper'
* 'sampler1D'
* 'sampler1DArray'
* 'sampler1DArrayShadow'
* 'sampler1DShadow'
* 'sampler2D'
* 'sampler2DArray'
* 'sampler2DArrayShadow'
* 'sampler2DMS'
* 'sampler2DMSArray'
* 'sampler2DRect'
* 'sampler2DRectShadow'
* 'sampler2DShadow'
* 'sampler3D'
* 'sampler3DRect'
* 'samplerBuffer'
* 'samplerCube'
* 'samplerCubeArray'
* 'samplerCubeArrayShadow'
* 'samplerCubeShadow'
* 'samplerShadow'
* 'string'
* 'tbuffer'
* 'texture1D'
* 'texture1DArray'
* 'texture2D'
* 'texture2DArray'
* 'texture2DMS'
* 'texture2DMSArray'
* 'texture2DRect'
* 'texture3D'
* 'textureBuffer'
* 'textureCube'
* 'textureCubeArray'
* 'u16'
* 'u64'
* 'u8'
* 'uimage1D'
* 'uimage1DArray'
* 'uimage2D'
* 'uimage2DArray'
* 'uimage2DMS'
* 'uimage2DMSArray'
* 'uimage2DRect'
* 'uimage3D'
* 'uimageBuffer'
* 'uimageCube'
* 'uimageCubeArray'
* 'unsigned'
* 'usampler1D'
* 'usampler1DArray'
* 'usampler2D'
* 'usampler2DArray'
* 'usampler2DMS'
* 'usampler2DMSArray'
* 'usampler2DRect'
* 'usampler3D'
* 'usamplerBuffer'
* 'usamplerCube'
* 'usamplerCubeArray'
* 'utexture1D'
* 'utexture1DArray'
* 'utexture2D'
* 'utexture2DArray'
* 'utexture2DMS'
* 'utexture2DMSArray'
* 'utexture2DRect'
* 'utexture3D'
* 'utextureBuffer'
* 'utextureCube'
* 'utextureCubeArray'
* 'vec'
* 'vector'
* 'void'
* 'wchar_t'

**Comment by dneto0** [comment]
I took a bunch out in #2736   This would do even more.

**Comment by litherum** [comment]
Good idea.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-07-minutes#wgsl-other-language-types-in-reserved-word-list-2983">WGSL meeting minutes 2022-06-07</a></summary>



* DN:  Bunch of easy cases (like texture types in other languages), an remove them.  But there are some like i16 and i64 that  are on likely path to being in WGSL.
* KG: Agree to reserve those.
* MM: Why. We have a forward path that allows us to add those and have user defined things override WGSL-predeclared-things.  We have to have a solution to that problem.
* AB: That’s not what the spec says right now.
* KG: Don’t want to redefine ‘true’ ‘false’.
* AB: Agree we need a plan for expansion in that way.
* KG: Need an issue
* DN: [https://github.com/gpuweb/gpuweb/issues/2941](https://github.com/gpuweb/gpuweb/issues/2941) , and make that non-editorial.


</details>

**Comment by norepimorphism** [comment]
Small nit: is 'samper' a typo?

**Comment by dj2** [comment]
I belive it's a typo, yes. In theory it's going to be removed if this issue is fixed, so no reason to fix it at the moment.

**Comment by kdashg** [comment]
Are we done here?

**Comment by dj2** [comment]
I think so.
