### ISSUE TITLE
wgsl: comparison operator result is scalar bool when "is scalar" should expand to include abstract numerics.

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2988]
"Scalar" actually excludes AbstractInt, AbstractFloat
But    a == b should yield bool when a and b are AbstractInt or AbstractFloat.

This was missed in the update to add abstract numerics.

**Comment by dneto0** [comment]
Also need to fix:  ldexp, length, countLeadingZeros, countTrailingZeros, extractBits, insertBits

**Comment by kdashg** [comment]
Don't we just get AbstractInt->Int, which has int==int->bool?

**Comment by dneto0** [comment]
> Don't we just get AbstractInt->int, which has int==int->bool?

I see your point.  But the intent / expectation is that the comparison be done in AbstractInt or AbstractFloat domain.    I count this as editorial oversight

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-07-minutes#wgsl-comparison-operator-result-is-scalar-bool-when-is-scalar-should-expand-to-include-abstract-numerics-2988">WGSL meeting minutes 2022-06-07</a></summary>



* editorial


</details>

**Comment by dneto0** [comment]
The length builtin does not need a fix for this.  But it is missing overloads that yield AbstractInt and f16.  See #3111
