### ISSUE TITLE
wgsl: expression overloads, and builtin overloads must have all concrete operands or all abstract operands

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#2993]
Creation-time expressions must not overflow.

If we allowed an expression overload, or a builtin overload with mixed abstract and concrete types, then we could end up in a situation where that expression would have to be evaluated at runtime.

Example:    `100 << x`  where  `x` is a runtime i32 value.

If we had an     `AbstractInt  << i32` overload, then the `100` stays as AbstractInt, and we have no idea whether `100 << x` would overflow.

So we can't have that overload, and therefore force the 100 to materialize to an 100i value in i32.

Overloads are chosen only by parameter types, so either both operands to << should be abstract, or both operands should be concrete.

There are a few cases in the spec where operands to a builtin are differently constrained, and when adding abstract numeric types we accidentally allowed mixture of abstract and concrete.

This happens with:
-  shiftLeft, shiftRight (which will be fixed by #2989)
- ldexp

**Comment by dj2** [comment]
What about `mix(e1: T2 ,e2: T2 ,e3: T ) -> T2` or is that handled by the `Same as mix(e1,e2,T2(e3)).` comment so it's a cast?

**Comment by dneto0** [comment]
> What about `mix(e1: T2 ,e2: T2 ,e3: T ) -> T2` or is that handled by the `Same as mix(e1,e2,T2(e3)).` comment so it's a cast?

In that first case, T2 is `vecN<T>`  so the T2 is already concrete if and only if T is concrete.
