### ISSUE TITLE
Update `Pipeline input and output interface` section to reference `@builtin` and `@location`

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2996]
When trying to determine if I could apply `@builtin(position) @location(0)` to a structure member I wasn't able to find section `9.3.1` https://www.w3.org/TR/WGSL/#pipeline-inputs-outputs which has the relevant bit of information in:

* A built-in value. See [§ 9.3.1.1 Built-in Inputs and Outputs](https://www.w3.org/TR/WGSL/#builtin-inputs-outputs).
* A user-defined value. See [§ 9.3.1.2 User-defined Inputs and Outputs](https://www.w3.org/TR/WGSL/#user-defined-inputs-outputs).

This is because I searched for `builtin` to match the name instead of `built-in`. I would have had the same issue with `location` as I didn't spell it `user-defined value`.

We should update the bullet points to say:

* A `@builtin` value. See [§ 9.3.1.1 Built-in Inputs and Outputs](https://www.w3.org/TR/WGSL/#builtin-inputs-outputs).
* A `@location` value. A user-defined value. See [§ 9.3.1.2 User-defined Inputs and Outputs](https://www.w3.org/TR/WGSL/#user-defined-inputs-outputs).

To make it clear and searchable what is being referred too.

**Comment by dneto0** [comment]
This section has been rewritten and the rules are easier to grasp.
