### ISSUE TITLE
Specify a minimum `SizeOf` for a runtime array

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#2997]
Currently for a runtime array we say the size is `Nruntime x roundUp(AlignOf(E), SizeOf(E))` but that is not really useful at compile time as we don't know `Nruntime`. This means that the `@size` on a runtime array can't be validated.

We should at add a note that the size must be at least `roundUp(AlignOf(E), SizeOf(E))` so we know the size is correct for one element.

Section https://www.w3.org/TR/WGSL/#alignment-and-size last table entry.

**Comment by litherum** [comment]
Can we just forbid putting `@size` on a runtime-size array?

**Comment by kainino0x** [comment]
That seems reasonable to me since they don't have a static size. This would have to extend to unsized structs too (structs that end in unsized arrays).

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-07-minutes#specify-a-minimum-sizeof-for-a-runtime-array-2997-">WGSL meeting minutes 2022-06-07</a></summary>



* DN: Editorial.  Think already exists in totality of text of the specs.


</details>

**Comment by dneto0** [comment]
> 



> That seems reasonable to me since they don't have a static size. This would have to extend to unsized structs too (structs that end in unsized arrays).

We also have to avoid arrays sized by a pipeline-time expression.  

The restriction is:  `@size` can only be applied to a member whose type has creation-fixed footprint.  (yep, that's a defined term already).

This is no longer editorial, as it now implies extra validation.
