### ISSUE TITLE
Is an atomic a composite type?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3004]
The description for [Composite Type](https://www.w3.org/TR/WGSL/#composite-types) says that it has internal structure expressed as a composition of other types. An atomic is composed of other types `atomic<i32>`, so should atomic be listed as a composite?

**Comment by dj2** [comment]
We should put a better description in composite type then I think, as it _looks_ like an atomic is expressed as the composition of other types.

**Comment by dneto0** [comment]
Yeah, we can go two ways with this.

A composite is currently defined as having internal structure expressed as a composition of other types. Which an atomic types does. But what's different about atomic types is you can't access its members by an expression.  You have to use a builtin on memory containing the atomic.

Also a detail is whether it counts toward nesting.
