### ISSUE TITLE
question: any working javascript binding?

### ISSUE THREAD

**Issue by bglgwyng** [gpuweb/gpuweb#302]
As far as I know, there already are implementations on development(wgpu for rust, dawn for c++).
But none of them doesn't provide a javascript binding yet.
It can be a nodejs binding or an experemintal browser shipping a unstable version of gpuweb.
Does someone know if it exists and where it is?
If not exist yet, what would be the recommended way to implement one(that you ever thought of but didn't have time for)?

**Comment by Kangz** [comment]
See webgpu.io for the current status. There is an initial version of WebGPU available in Chrome Canary on Mac. See webgpu.io for more details.
