### ISSUE TITLE
Specify how pointer types compare?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3030]
We call out how arrays and structures compare, should we do the same for pointers and references? This would make it clear that a `read_write` pointer can't be passed to a function expecting a `read` pointer.

Essentially, note that all 3 parts of the pointer have to be identical for the types to be identical.

**Comment by alan-baker** [comment]
To clarify, this is a request to describe what makes two pointers the same type. Not comparing pointer values.
