### ISSUE TITLE
Clarify storable type concrete components for vectors and matrices.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3031]
In [4.4.3. Storable Types](https://www.w3.org/TR/WGSL/#storable-types) we say:

* a vector type with concrete components
* a matrix type with concrete components

while implied, it isn't obvious that this means concrete or abstract values that are concretized. We should add either clarification or add the term `concretized` into the spec and change `concrete` above to `concretized` and link to the new section.

**Comment by dneto0** [comment]
Definitions of concrete and abstract have been updated and are now more consistent, and has fixed this.
