### ISSUE TITLE
Structure types should specify that the contained vectors and matrices must be concretized components

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3032]
The [4.3.9. Structure Types](https://www.w3.org/TR/WGSL/#struct-types) we don't specify that `vector` and `matrix` members are `with concrete components` as is done in other parts of the spec.

**Comment by dneto0** [comment]
> In tint, I used the term `materialize` for the process of turning an abstract-numeric to a concrete type.

Yeah, that's Tint's name for the *process* or action.  But the rule in the spec is static.
Already we have uses of "with concrete component", so I'll use that.
