### ISSUE TITLE
Clarifications for IO-shareable types

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3033]
In [4.4.4 IO-shareable Types](https://www.w3.org/TR/WGSL/#io-shareable-types) there is discussion about user-defined pipeline in/output values. We then have host-shareable types defined in 4.4.5.

If my understanding is correct the IO-shareable types are, specifically, types which can be used in the function signature of the shader entry point. (So, either the return value or the parameters).

This is only hinted at in the text for IO-shareable types which leads to questions of if the IO-shareable types include things like uniform or storage buffers.

It might make things a bit clearer instead of saying `User-defined pipeline input and output values` to specify, specifically, that values passed too or returned from the entry point must be of IO-shareable type.

**Comment by dneto0** [comment]
> It might make things a bit clearer instead of saying User-defined pipeline input and output values to specify, specifically, that values passed too or returned from the entry point must be of IO-shareable type.

That's a good suggestion.  I can see the confusion about things that provide data to the "pipeline" (being the unit of work scheduled on the queue), vs. the datapath between fixed and programmable stages.

Saying it plainly as the parameter types and return types of entry points is clear.

**Comment by dneto0** [comment]
In fact, now that pipeline IO are params and returns, there is no *memory* associated with them. (No more 'input' or 'output' address space / storage class)  So the section should be moved out from "Memory". !

**Comment by dneto0** [comment]
> It might make things a bit clearer instead of saying User-defined pipeline input and output values to specify, specifically, that values passed too or returned from the entry point must be of IO-shareable type.

Except looking at this more closely, this isn't true.  Because the frontfacing builtin is bool, but bool is not IO-shareable.

There's a lot of back and forth between sections, only because we want to define IO-shareable types in the "Types" section, but only use them in one place, really.
