### ISSUE TITLE
Separate read-only state for stencil and depth aspects.

### ISSUE THREAD

**Issue by brendan-duncan** [gpuweb/gpuweb#3036]
The issue was previously discussed in https://github.com/gpuweb/gpuweb/issues/514.

Unity shaders need to disable writing to the depth buffer in a render pipeline with depthWriteEnabled:false, for a depth texture currently used by the render pass, while still writing to the stencil. If necessary, I could end the current render pass and start a new one with readOnly depth and writable stencil. But it would be nice if the depthWriteEnabled pipeline state would control that. In all cases, we need separate stencil and depth read-only states.

**Comment by kainino0x** [comment]
My reading of the past discussions in #514 and #746 is that separate read-only state is supported in [D3D12](https://github.com/gpuweb/gpuweb/issues/514#issuecomment-631102019), [`VK_KHR_maintenance2`](https://github.com/gpuweb/gpuweb/issues/514#issuecomment-628925960), and [probably Metal](https://github.com/gpuweb/gpuweb/pull/746#issuecomment-630469122). So I think all we need for this is to decide to add a WebGPU feature flag for it - and of course test it well. I don't think we can prioritize it for V1 though.

**Comment by mwyrzykowski** [comment]
Confirmed this is well defined and easily implementable with Metal.

My reading of the WebGPU specification is already supported by WebGPU. `depthWriteEnabled` says:
[Indicates if this GPURenderPipeline can modify depthStencilAttachment depth values.](https://gpuweb.github.io/gpuweb/#dom-gpudepthstencilstate-depthwriteenabled)

Maybe I don't understand the problem, but what is the issue with setting `depthWriteEnabled` to false, attaching a depth attachment, and still writing to the stencil buffer by setting `stencilWriteMask`? It seems like this is supported via the current WebGPU specification without ending the current render pass via two separate GPURenderPipeline instances which in theory could be backed by the same pipeline state object.

**Comment by teoxoy** [comment]
I was under the same impression but @Kangz clarified on the last call that this issue is targeted at lifting this bit of validation from the spec:

![image](https://github.com/gpuweb/gpuweb/assets/28601907/8146f5f6-51e7-41d8-94f4-3b2b6937740c)

**Comment by mwyrzykowski** [comment]
Oh makes sense. Yes lets please lift that restriction

**Comment by mwyrzykowski** [comment]
We only use `depthReadOnly` for validation as its not really needed for Metal's backend

**Comment by BearIvan** [comment]
![image](https://github.com/gpuweb/gpuweb/assets/22314126/2d2bac86-7d43-428e-b2b4-26e7c25e5229)
Unreal engine shaders need different access modes for depth and stencil. Wgpu does not allow this.

**Comment by kainino0x** [comment]
As raised in the meeting I think I misread the old investigations and this should work using GENERAL even without VK_KHR_maintenance2. In order to be sure I think we'll need to write some tests and try it out though.

Just for completeness though here's the analysis for (Vulkan 1.1 or VK_KHR_maintenance2):

> ```
> Requirement "Vulkan 1.1 or VK_KHR_maintenance2 for #3036 Separate read-only state for stencil and depth aspects" loses 13 (and partially loses 156) further deviceNames:`
>   In ALL reports (13 deviceNames):
>     x AMD Radeon (TM) 520: 1 (3902)
>     x AMD Radeon (TM) 535DX: 1 (2914)
>     x AMD Radeon (TM) R5 M430: 1 (4406)
>     x AMD Radeon (TM) R7 M460: 1 (12637)
>     x AMD Radeon HD 7770 GHz Edition: 1 (8041)
>     x AMD Radeon R7 Graphics + R7 200 Dual Graphics: 1 (1544)
>     x AMD Radeon(TM) R7 350X: 15 (1875 2974 3513 3763 3824 3918 3975 3985 4108 4189 4283 4291 4533 4641 4868)
>     x GeForce GT 640M: 3 (1624 1685 1747)
>     x Intel(R) HD Graphics 5300 (Broadwell GT2): 1 (1497)
>     x Intel(R) HD Graphics P530: 1 (6154)
>     x Quadro M6000: 2 (1962 1963)
>     x Radeon Pro 575: 1 (3371)
>     x Radeon Pro WX 5100: 1 (6510)
> ```
> 
> <details><summary><code>In SOME reports (156 deviceNames):</code></summary>
> 
> ```
>     ~ AMD RADEON R9 M295X: 2 of 3 (1701 1990)
>     ~ AMD RADV BONAIRE: 3 of 32 (1846 2170 2276)
>     ~ AMD RADV CAPE VERDE: 3 of 37 (1821 1911 2251)
>     ~ AMD RADV FIJI: 2 of 70 (1853 1862)
>     ~ AMD RADV HAWAII: 6 of 78 (1661 1844 2015 2109 2213 2652)
>     ~ AMD RADV ICELAND: 2 of 79 (1826 1951)
>     ~ AMD RADV KABINI: 1 of 16 (12548)
>     ~ AMD RADV KAVERI: 1 of 62 (1952)
>     ~ AMD RADV MULLINS: 2 of 23 (1728 3064)
>     ~ AMD RADV OLAND: 4 of 26 (1711 2124 2184 2247)
>     ~ AMD RADV PITCAIRN: 8 of 71 (1658 1691 1949 2025 2063 2082 2140 2143)
>     ~ AMD RADV POLARIS10: 11 of 614 (1690 1698 1842 1894 1915 1961 1983 2029 2047 2117 3196)
>     ~ AMD RADV POLARIS11: 7 of 85 (1851 1885 1947 2096 2130 2141 2212)
>     ~ AMD RADV TAHITI: 4 of 44 (1790 1819 1900 2016)
>     ~ AMD RADV TONGA: 5 of 30 (1964 2059 2192 2197 2200)
>     ~ AMD RADV VEGA: 1 of 16 (1823)
>     ~ AMD Radeon (TM) R5 M335: 1 of 2 (2068)
>     ~ AMD Radeon (TM) R7 300 Series: 1 of 3 (1838)
>     ~ AMD Radeon (TM) R7 360 Series: 1 of 9 (12997)
>     ~ AMD Radeon (TM) R7 370 Series: 3 of 8 (1458 1779 1874)
>     ~ AMD Radeon (TM) R9 200 Series: 3 of 12 (1705 1731 2065)
>     ~ AMD Radeon (TM) R9 380 Series: 2 of 19 (1733 1845)
>     ~ AMD Radeon (TM) R9 390 Series: 3 of 37 (1646 1754 8485)
>     ~ AMD Radeon (TM) R9 Fury Series: 2 of 45 (1644 1653)
>     ~ AMD Radeon (TM) R9 M360: 1 of 3 (1670)
>     ~ AMD Radeon (TM) RX 480: 1 of 2 (1457)
>     ~ AMD Radeon (TM) RX 480 Graphics: 2 of 18 (2030 2316)
>     ~ AMD Radeon HD 7700 Series: 2 of 22 (1515 1746)
>     ~ AMD Radeon HD 7700M Series: 1 of 17 (1710)
>     ~ AMD Radeon HD 7800 Series: 2 of 35 (1677 4835)
>     ~ AMD Radeon HD 7900 Series: 5 of 29 (1778 1798 1803 6963 9411)
>     ~ AMD Radeon HD 8330: 1 of 2 (13160)
>     ~ AMD Radeon HD 8400 / R3 Series: 1 of 2 (6936)
>     ~ AMD Radeon HD 8500M: 1 of 4 (4088)
>     ~ AMD Radeon HD 8600/8700M: 1 of 2 (1518)
>     ~ AMD Radeon R5 Graphics: 1 of 10 (4520)
>     ~ AMD Radeon R5 M230 Series: 1 of 24 (1865)
>     ~ AMD Radeon R7 200 Series: 3 of 32 (1541 1696 2266)
>     ~ AMD Radeon R7 240: 1 of 2 (4470)
>     ~ AMD Radeon R7 240 Series: 1 of 3 (1816)
>     ~ AMD Radeon R7 Graphics: 1 of 5 (2913)
>     ~ AMD Radeon R7 M260: 1 of 6 (1867)
>     ~ AMD Radeon R7 M265 Series: 2 of 3 (1650 12374)
>     ~ AMD Radeon R9 200 / HD 7900 Series: 2 of 6 (1612 1773)
>     ~ AMD Radeon R9 200 Series: 2 of 35 (1642 4210)
>     ~ AMD Radeon R9 M370X: 1 of 4 (2454)
>     ~ AMD Radeon RX Vega 64: 2 of 18 (5659 6898)
>     ~ AMD Radeon(TM) 530: 1 of 4 (2871)
>     ~ AMD Radeon(TM) R2 Graphics: 1 of 3 (6079)
>     ~ AMD Radeon(TM) R3 Graphics: 1 of 5 (2978)
>     ~ AMD Radeon(TM) R4 Graphics: 4 of 9 (1674 3317 7508 19463)
>     ~ AMD Radeon(TM) R5 240: 1 of 3 (5052)
>     ~ AMD Radeon(TM) R5 Graphics: 3 of 43 (1665 4229 8328)
>     ~ AMD Radeon(TM) R5 M430: 1 of 2 (19462)
>     ~ AMD Radeon(TM) R6 Graphics: 1 of 2 (1866)
>     ~ AMD Radeon(TM) R7 Graphics: 1 of 12 (2036)
>     ~ AMD Radeon(TM) Vega 8 Mobile Graphics: 1 of 5 (2457)
>     ~ ASUS R9 280 Series: 1 of 2 (1664)
>     ~ Adreno (TM) 630: 7 of 130 (2801 3024 3687 3755 3795 3810 6234)
>     ~ GeForce 840M: 11 of 74 (1507 1510 1565 1567 1602 1609 1652 1660 1721 1814 1834)
>     ~ GeForce 920M: 2 of 12 (1908 6193)
>     ~ GeForce 920MX: 1 of 6 (3972)
>     ~ GeForce 940MX: 5 of 60 (1590 1643 1872 1981 3344)
>     ~ GeForce GT 1030: 1 of 79 (5834)
>     ~ GeForce GT 640: 3 of 18 (1473 1720 2692)
>     ~ GeForce GT 640M LE: 1 of 4 (1434)
>     ~ GeForce GT 650M: 2 of 15 (1593 1854)
>     ~ GeForce GT 710: 2 of 25 (1730 3631)
>     ~ GeForce GT 720: 1 of 6 (1769)
>     ~ GeForce GT 730: 3 of 22 (1669 1692 2583)
>     ~ GeForce GT 730M: 2 of 7 (1807 1808)
>     ~ GeForce GT 740: 2 of 10 (1492 1924)
>     ~ GeForce GT 740M: 2 of 27 (1633 1641)
>     ~ GeForce GT 750M: 4 of 17 (1435 1594 1796 10358)
>     ~ GeForce GT 755M: 1 of 3 (2118)
>     ~ GeForce GTX 1050: 10 of 125 (1560 1688 1712 1715 1809 1877 1895 2003 2990 4264)
>     ~ GeForce GTX 1050 Ti: 14 of 145 (1465 1508 1589 1697 1707 1717 1739 1741 1780 1873 1907 2250 2422 2917)
>     ~ GeForce GTX 1060: 2 of 187 (3909 4013)
>     ~ GeForce GTX 1060 3GB: 4 of 59 (1623 1626 1950 12501)
>     ~ GeForce GTX 1060 6GB: 12 of 138 (1494 1532 1547 1585 1611 1681 1686 1694 1802 1836 1886 2183)
>     ~ GeForce GTX 1070: 20 of 199 (1506 1566 1569 1600 1631 1640 1667 1714 1718 1761 1766 1833 1861 1939 1957 2173 2751 2831 2970 5808)
>     ~ GeForce GTX 1080: 17 of 188 (1437 1486 1524 1572 1632 1713 1748 1749 1750 1758 1792 1801 1857 1903 1931 2041 2888)
>     ~ GeForce GTX 1080 Ti: 7 of 152 (1485 1534 1574 1757 1831 2019 2396)
>     ~ GeForce GTX 650: 3 of 29 (1436 1448 1453)
>     ~ GeForce GTX 650 Ti: 2 of 22 (1521 1702)
>     ~ GeForce GTX 650 Ti BOOST: 6 of 42 (1484 1657 1806 1881 1892 2487)
>     ~ GeForce GTX 660: 4 of 36 (1639 1751 2645 4777)
>     ~ GeForce GTX 660 Ti: 1 of 8 (1719)
>     ~ GeForce GTX 660M: 3 of 10 (1598 1738 7954)
>     ~ GeForce GTX 680: 1 of 23 (1765)
>     ~ GeForce GTX 750: 3 of 21 (1539 1904 2384)
>     ~ GeForce GTX 750 Ti: 2 of 72 (1542 1687)
>     ~ GeForce GTX 760: 8 of 44 (1468 1509 1668 1706 1743 1770 2040 2369)
>     ~ GeForce GTX 760 (192-bit): 1 of 3 (4152)
>     ~ GeForce GTX 765M: 3 of 8 (1655 1759 2605)
>     ~ GeForce GTX 770: 5 of 80 (1727 1729 1742 1794 2334)
>     ~ GeForce GTX 770M: 1 of 4 (1581)
>     ~ GeForce GTX 780: 1 of 11 (1475)
>     ~ GeForce GTX 780M: 1 of 4 (1469)
>     ~ GeForce GTX 850M: 6 of 22 (1563 1764 1871 2023 2060 2425)
>     ~ GeForce GTX 860M: 6 of 26 (1460 1514 1647 2906 2931 2933)
>     ~ GeForce GTX 950: 3 of 25 (1456 1648 1804)
>     ~ GeForce GTX 950M: 7 of 28 (1573 1898 1926 1989 2092 2938 3496)
>     ~ GeForce GTX 960: 10 of 85 (1462 1496 1516 1553 1634 1679 1695 1736 1815 1837)
>     ~ GeForce GTX 960M: 11 of 82 (1440 1451 1499 1546 1605 1620 1783 1843 1864 1876 2609)
>     ~ GeForce GTX 965M: 2 of 4 (1708 2083)
>     ~ GeForce GTX 970: 22 of 157 (1442 1525 1526 1529 1530 1562 1577 1578 1607 1625 1662 1675 1689 1724 1762 1768 1788 1855 1858 1909 2097 2116)
>     ~ GeForce GTX 970M: 1 of 25 (1760)
>     ~ GeForce GTX 980: 9 of 50 (1432 1480 1493 1630 1678 1795 1797 1827 1890)
>     ~ GeForce GTX 980 Ti: 3 of 37 (1588 1608 2042)
>     ~ GeForce GTX 980M: 5 of 30 (1614 1635 1775 1883 3339)
>     ~ GeForce GTX TITAN: 4 of 10 (1570 1571 1799 1800)
>     ~ GeForce MX150: 1 of 39 (3599)
>     ~ Intel(R) HD Graphics (Cherrytrail): 1 of 4 (1774)
>     ~ Intel(R) HD Graphics 500 (Broxton 2x6): 2 of 4 (1734 1971)
>     ~ Intel(R) HD Graphics 510: 1 of 4 (2336)
>     ~ Intel(R) HD Graphics 515: 2 of 5 (2284 3510)
>     ~ Intel(R) HD Graphics 520: 3 of 91 (1617 2356 2985)
>     ~ Intel(R) HD Graphics 520 (Skylake GT2): 6 of 32 (1445 1621 1847 1901 2098 2485)
>     ~ Intel(R) HD Graphics 530: 3 of 150 (1527 1756 2538)
>     ~ Intel(R) HD Graphics 530 (Skylake GT2): 12 of 72 (1446 1531 1555 1613 1638 1752 1767 1940 2076 2189 2196 2476)
>     ~ Intel(R) HD Graphics 5500 (Broadwell GT2): 5 of 46 (1444 1618 1835 2268 2595)
>     ~ Intel(R) HD Graphics 610: 1 of 7 (6660)
>     ~ Intel(R) HD Graphics 610 (Kaby Lake GT1): 2 of 4 (1464 2464)
>     ~ Intel(R) HD Graphics 615: 1 of 6 (2280)
>     ~ Intel(R) HD Graphics 620: 3 of 90 (2064 2438 2849)
>     ~ Intel(R) HD Graphics 620 (Kaby Lake GT2): 6 of 67 (1449 1737 1879 2501 2594 3069)
>     ~ Intel(R) HD Graphics 630: 2 of 81 (2074 2514)
>     ~ Intel(R) HD Graphics 630 (Kaby Lake GT2): 2 of 47 (2070 2153)
>     ~ Intel(R) HD Graphics XXX (Braswell): 6 of 23 (1680 1740 1789 1929 1946 2495)
>     ~ Intel(R) Iris Graphics 540 (Skylake GT3e): 2 of 4 (1545 1673)
>     ~ Intel(R) Iris(R) Graphics 540: 1 of 7 (2545)
>     ~ Intel(R) Iris(TM) Plus Graphics 640: 1 of 7 (1732)
>     ~ Intel(R) UHD Graphics 600: 1 of 20 (17713)
>     ~ Intel(R) UHD Graphics 620: 3 of 97 (2350 6539 12703)
>     ~ Mali-G51: 1 of 26 (4923)
>     ~ Mali-G72: 10 of 78 (2742 3206 3448 3781 3863 4200 4392 4602 6979 10185)
>     ~ Mali-G72 MP3: 3 of 25 (4158 4814 6248)
>     ~ NVIDIA Tegra X1: 7 of 8 (1550 1977 2115 5451 9235 10177 16802)
>     ~ Quadro K1100M: 1 of 5 (1659)
>     ~ Quadro K2000: 1 of 4 (4696)
>     ~ Quadro K2000M: 2 of 4 (1599 3628)
>     ~ Quadro K600: 1 of 3 (1616)
>     ~ Quadro P1000: 1 of 10 (3399)
>     ~ Quadro P5000: 1 of 4 (1481)
>     ~ Quadro P6000: 1 of 2 (7106)
>     ~ Radeon (TM) 530: 1 of 4 (3039)
>     ~ Radeon (TM) RX 470 Graphics: 2 of 20 (1503 1683)
>     ~ Radeon (TM) RX 480 Graphics: 6 of 40 (1586 1645 1810 1811 5916 6662)
>     ~ Radeon RX 550 Series: 2 of 11 (1595 12290)
>     ~ Radeon RX 560 Series: 2 of 41 (1591 1945)
>     ~ Radeon RX 570 Series: 4 of 45 (1868 4110 11258 12605)
>     ~ Radeon RX 580 Series: 4 of 82 (1709 1763 1893 6862)
>     ~ Radeon RX Vega: 4 of 264 (1725 1839 2209 2508)
>     ~ Radeon(TM) 520: 1 of 2 (3353)
>     ~ Radeon(TM) RX 460 Graphics: 1 of 28 (1771)
> ```
> 
> </details>

**Comment by kainino0x** [comment]
Based on that report I think that - on the off chance it doesn't work without VK_KHR_maintenance2 - it would be fine to drop these few old devices.

So maybe we can just go ahead with adding this to the spec and start implementing and testing?

**Comment by Kangz** [comment]
I'd like to validate it before adding it to the spec if you don't mind. AFAIK the spec change would be trivial, while the implementation isn't exactly.

**Comment by kainino0x** [comment]
@teoxoy pointed out that I need to also remove the allowance for `VK_AMD_negative_viewport_height` because we can't actually support those devices. That means a bunch of those AMD devices should have already been lost. Here's an updated analysis:

> `Requirement "Vulkan 1.1 or VK_KHR_maintenance2 for #3036 Separate read-only state for stencil and depth aspects" loses 4 (and partially loses 136) further deviceNames:`
> 
> ```
>   In ALL reports (4 deviceNames):
>     x GeForce GT 640M: 3 (1624 1685 1747)
>     x Intel(R) HD Graphics 5300 (Broadwell GT2): 1 (1497)
>     x Intel(R) HD Graphics P530: 1 (6154)
>     x Quadro M6000: 2 (1962 1963)
> ```
> 
> <details><summary><code>In SOME reports (136 deviceNames):</code></summary>
> 
> ```
>     ~ AMD RADEON R9 M295X: 1 of 2 (1990)
>     ~ AMD RADV BONAIRE: 3 of 32 (1846 2170 2276)
>     ~ AMD RADV CAPE VERDE: 3 of 37 (1821 1911 2251)
>     ~ AMD RADV FIJI: 2 of 70 (1853 1862)
>     ~ AMD RADV HAWAII: 6 of 78 (1661 1844 2015 2109 2213 2652)
>     ~ AMD RADV ICELAND: 2 of 79 (1826 1951)
>     ~ AMD RADV KABINI: 1 of 16 (12548)
>     ~ AMD RADV KAVERI: 1 of 62 (1952)
>     ~ AMD RADV MULLINS: 2 of 23 (1728 3064)
>     ~ AMD RADV OLAND: 4 of 26 (1711 2124 2184 2247)
>     ~ AMD RADV PITCAIRN: 8 of 71 (1658 1691 1949 2025 2063 2082 2140 2143)
>     ~ AMD RADV POLARIS10: 11 of 614 (1690 1698 1842 1894 1915 1961 1983 2029 2047 2117 3196)
>     ~ AMD RADV POLARIS11: 7 of 85 (1851 1885 1947 2096 2130 2141 2212)
>     ~ AMD RADV TAHITI: 4 of 44 (1790 1819 1900 2016)
>     ~ AMD RADV TONGA: 5 of 30 (1964 2059 2192 2197 2200)
>     ~ AMD RADV VEGA: 1 of 16 (1823)
>     ~ AMD Radeon (TM) R5 M335: 1 of 2 (2068)
>     ~ AMD Radeon (TM) R7 300 Series: 1 of 3 (1838)
>     ~ AMD Radeon (TM) R7 370 Series: 1 of 6 (1874)
>     ~ AMD Radeon (TM) R9 200 Series: 2 of 11 (1705 2065)
>     ~ AMD Radeon (TM) R9 380 Series: 2 of 19 (1733 1845)
>     ~ AMD Radeon (TM) R9 390 Series: 2 of 36 (1646 1754)
>     ~ AMD Radeon (TM) R9 Fury Series: 2 of 45 (1644 1653)
>     ~ AMD Radeon (TM) R9 M360: 1 of 3 (1670)
>     ~ AMD Radeon (TM) RX 480 Graphics: 1 of 17 (2316)
>     ~ AMD Radeon HD 7700 Series: 1 of 21 (1746)
>     ~ AMD Radeon HD 7700M Series: 1 of 17 (1710)
>     ~ AMD Radeon HD 7800 Series: 1 of 34 (1677)
>     ~ AMD Radeon HD 7900 Series: 4 of 28 (1778 1798 1803 9411)
>     ~ AMD Radeon R5 M230 Series: 1 of 24 (1865)
>     ~ AMD Radeon R7 200 Series: 1 of 30 (1696)
>     ~ AMD Radeon R7 240 Series: 1 of 3 (1816)
>     ~ AMD Radeon R7 M260: 1 of 6 (1867)
>     ~ AMD Radeon R9 200 / HD 7900 Series: 1 of 5 (1773)
>     ~ AMD Radeon R9 200 Series: 1 of 34 (1642)
>     ~ AMD Radeon RX Vega 64: 2 of 18 (5659 6898)
>     ~ AMD Radeon(TM) R5 Graphics: 1 of 41 (1665)
>     ~ AMD Radeon(TM) R6 Graphics: 1 of 2 (1866)
>     ~ AMD Radeon(TM) R7 Graphics: 1 of 12 (2036)
>     ~ ASUS R9 280 Series: 1 of 2 (1664)
>     ~ Adreno (TM) 630: 7 of 130 (2801 3024 3687 3755 3795 3810 6234)
>     ~ GeForce 840M: 11 of 74 (1507 1510 1565 1567 1602 1609 1652 1660 1721 1814 1834)
>     ~ GeForce 920M: 2 of 12 (1908 6193)
>     ~ GeForce 920MX: 1 of 6 (3972)
>     ~ GeForce 940MX: 5 of 60 (1590 1643 1872 1981 3344)
>     ~ GeForce GT 1030: 1 of 79 (5834)
>     ~ GeForce GT 640: 3 of 18 (1473 1720 2692)
>     ~ GeForce GT 640M LE: 1 of 4 (1434)
>     ~ GeForce GT 650M: 2 of 15 (1593 1854)
>     ~ GeForce GT 710: 2 of 25 (1730 3631)
>     ~ GeForce GT 720: 1 of 6 (1769)
>     ~ GeForce GT 730: 3 of 22 (1669 1692 2583)
>     ~ GeForce GT 730M: 2 of 7 (1807 1808)
>     ~ GeForce GT 740: 2 of 10 (1492 1924)
>     ~ GeForce GT 740M: 2 of 27 (1633 1641)
>     ~ GeForce GT 750M: 4 of 17 (1435 1594 1796 10358)
>     ~ GeForce GT 755M: 1 of 3 (2118)
>     ~ GeForce GTX 1050: 10 of 125 (1560 1688 1712 1715 1809 1877 1895 2003 2990 4264)
>     ~ GeForce GTX 1050 Ti: 14 of 145 (1465 1508 1589 1697 1707 1717 1739 1741 1780 1873 1907 2250 2422 2917)
>     ~ GeForce GTX 1060: 2 of 187 (3909 4013)
>     ~ GeForce GTX 1060 3GB: 4 of 59 (1623 1626 1950 12501)
>     ~ GeForce GTX 1060 6GB: 12 of 138 (1494 1532 1547 1585 1611 1681 1686 1694 1802 1836 1886 2183)
>     ~ GeForce GTX 1070: 20 of 199 (1506 1566 1569 1600 1631 1640 1667 1714 1718 1761 1766 1833 1861 1939 1957 2173 2751 2831 2970 5808)
>     ~ GeForce GTX 1080: 17 of 188 (1437 1486 1524 1572 1632 1713 1748 1749 1750 1758 1792 1801 1857 1903 1931 2041 2888)
>     ~ GeForce GTX 1080 Ti: 7 of 152 (1485 1534 1574 1757 1831 2019 2396)
>     ~ GeForce GTX 650: 3 of 29 (1436 1448 1453)
>     ~ GeForce GTX 650 Ti: 2 of 22 (1521 1702)
>     ~ GeForce GTX 650 Ti BOOST: 6 of 42 (1484 1657 1806 1881 1892 2487)
>     ~ GeForce GTX 660: 4 of 36 (1639 1751 2645 4777)
>     ~ GeForce GTX 660 Ti: 1 of 8 (1719)
>     ~ GeForce GTX 660M: 3 of 10 (1598 1738 7954)
>     ~ GeForce GTX 680: 1 of 23 (1765)
>     ~ GeForce GTX 750: 3 of 21 (1539 1904 2384)
>     ~ GeForce GTX 750 Ti: 2 of 72 (1542 1687)
>     ~ GeForce GTX 760: 8 of 44 (1468 1509 1668 1706 1743 1770 2040 2369)
>     ~ GeForce GTX 760 (192-bit): 1 of 3 (4152)
>     ~ GeForce GTX 765M: 3 of 8 (1655 1759 2605)
>     ~ GeForce GTX 770: 5 of 80 (1727 1729 1742 1794 2334)
>     ~ GeForce GTX 770M: 1 of 4 (1581)
>     ~ GeForce GTX 780: 1 of 11 (1475)
>     ~ GeForce GTX 780M: 1 of 4 (1469)
>     ~ GeForce GTX 850M: 6 of 22 (1563 1764 1871 2023 2060 2425)
>     ~ GeForce GTX 860M: 6 of 26 (1460 1514 1647 2906 2931 2933)
>     ~ GeForce GTX 950: 3 of 25 (1456 1648 1804)
>     ~ GeForce GTX 950M: 7 of 28 (1573 1898 1926 1989 2092 2938 3496)
>     ~ GeForce GTX 960: 10 of 85 (1462 1496 1516 1553 1634 1679 1695 1736 1815 1837)
>     ~ GeForce GTX 960M: 11 of 82 (1440 1451 1499 1546 1605 1620 1783 1843 1864 1876 2609)
>     ~ GeForce GTX 965M: 2 of 4 (1708 2083)
>     ~ GeForce GTX 970: 22 of 157 (1442 1525 1526 1529 1530 1562 1577 1578 1607 1625 1662 1675 1689 1724 1762 1768 1788 1855 1858 1909 2097 2116)
>     ~ GeForce GTX 970M: 1 of 25 (1760)
>     ~ GeForce GTX 980: 9 of 50 (1432 1480 1493 1630 1678 1795 1797 1827 1890)
>     ~ GeForce GTX 980 Ti: 3 of 37 (1588 1608 2042)
>     ~ GeForce GTX 980M: 5 of 30 (1614 1635 1775 1883 3339)
>     ~ GeForce GTX TITAN: 4 of 10 (1570 1571 1799 1800)
>     ~ GeForce MX150: 1 of 39 (3599)
>     ~ Intel(R) HD Graphics (Cherrytrail): 1 of 4 (1774)
>     ~ Intel(R) HD Graphics 500 (Broxton 2x6): 2 of 4 (1734 1971)
>     ~ Intel(R) HD Graphics 510: 1 of 4 (2336)
>     ~ Intel(R) HD Graphics 515: 2 of 5 (2284 3510)
>     ~ Intel(R) HD Graphics 520: 3 of 91 (1617 2356 2985)
>     ~ Intel(R) HD Graphics 520 (Skylake GT2): 6 of 32 (1445 1621 1847 1901 2098 2485)
>     ~ Intel(R) HD Graphics 530: 3 of 150 (1527 1756 2538)
>     ~ Intel(R) HD Graphics 530 (Skylake GT2): 12 of 72 (1446 1531 1555 1613 1638 1752 1767 1940 2076 2189 2196 2476)
>     ~ Intel(R) HD Graphics 5500 (Broadwell GT2): 5 of 46 (1444 1618 1835 2268 2595)
>     ~ Intel(R) HD Graphics 610: 1 of 7 (6660)
>     ~ Intel(R) HD Graphics 610 (Kaby Lake GT1): 2 of 4 (1464 2464)
>     ~ Intel(R) HD Graphics 615: 1 of 6 (2280)
>     ~ Intel(R) HD Graphics 620: 3 of 90 (2064 2438 2849)
>     ~ Intel(R) HD Graphics 620 (Kaby Lake GT2): 6 of 67 (1449 1737 1879 2501 2594 3069)
>     ~ Intel(R) HD Graphics 630: 2 of 81 (2074 2514)
>     ~ Intel(R) HD Graphics 630 (Kaby Lake GT2): 2 of 47 (2070 2153)
>     ~ Intel(R) HD Graphics XXX (Braswell): 6 of 23 (1680 1740 1789 1929 1946 2495)
>     ~ Intel(R) Iris Graphics 540 (Skylake GT3e): 2 of 4 (1545 1673)
>     ~ Intel(R) Iris(R) Graphics 540: 1 of 7 (2545)
>     ~ Intel(R) Iris(TM) Plus Graphics 640: 1 of 7 (1732)
>     ~ Intel(R) UHD Graphics 600: 1 of 20 (17713)
>     ~ Intel(R) UHD Graphics 620: 3 of 97 (2350 6539 12703)
>     ~ Mali-G51: 1 of 26 (4923)
>     ~ Mali-G72: 10 of 78 (2742 3206 3448 3781 3863 4200 4392 4602 6979 10185)
>     ~ Mali-G72 MP3: 3 of 25 (4158 4814 6248)
>     ~ NVIDIA Tegra X1: 7 of 8 (1550 1977 2115 5451 9235 10177 16802)
>     ~ Quadro K1100M: 1 of 5 (1659)
>     ~ Quadro K2000: 1 of 4 (4696)
>     ~ Quadro K2000M: 2 of 4 (1599 3628)
>     ~ Quadro K600: 1 of 3 (1616)
>     ~ Quadro P1000: 1 of 10 (3399)
>     ~ Quadro P5000: 1 of 4 (1481)
>     ~ Quadro P6000: 1 of 2 (7106)
>     ~ Radeon (TM) RX 470 Graphics: 1 of 19 (1683)
>     ~ Radeon (TM) RX 480 Graphics: 3 of 37 (1645 1811 6662)
>     ~ Radeon RX 550 Series: 1 of 10 (12290)
>     ~ Radeon RX 560 Series: 1 of 40 (1945)
>     ~ Radeon RX 570 Series: 2 of 43 (4110 11258)
>     ~ Radeon RX 580 Series: 3 of 81 (1709 1763 1893)
>     ~ Radeon RX Vega: 4 of 264 (1725 1839 2209 2508)
>     ~ Radeon(TM) RX 460 Graphics: 1 of 28 (1771)
> ```
> 
> </details>

**Comment by teoxoy** [comment]
Thanks for the update! We can now feel less bad if we need to require `VK_KHR_maintenance2` :)

**Comment by kainino0x** [comment]
Yup, it's basically just old desktop drivers and maybe a few old Mali and Adreno 630 drivers.
