### ISSUE TITLE
Add text and example around IO locations spanning multiple locations

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3045]
In [9.3.14. Input-Output Locations](https://www.w3.org/TR/WGSL/#input-output-locations) we specify a location can store a value up to 16 bytes. We do not specify that a value can span multiple locations.

We should add text explaining this consumption of locations and add an example which provides a struct which needs multiple locations:

```
struct A {
  a: vec4<f32>,
  b: vec4<f32>,
  c: f32,
}

fn main(@location(0) a: A, @location(3) b: f32) {}
```

**Comment by dj2** [comment]
Actually, re-reading the `location` section, this isn't possible as you can't apply `location` to a struct. Only `numeric scalar` or `numeric vector`. So, there is no type we have that has a size bigger then 16-bytes, so locations are never spanned.

**Comment by dj2** [comment]
Related: https://github.com/gpuweb/gpuweb/discussions/3290

**Comment by dneto0** [comment]
Closing.  There is nothing to describe here because the rules ban the confusing case.
