### ISSUE TITLE
Clarify note about write-only storage textures in 4.4.6 Address Spaces.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3047]
In [4.4.6 Address spaces](https://www.w3.org/TR/WGSL/#address-space) we say:

> Note: A texture variable holds an opaque handle which is used to access the underlying grid of texels. The handle itself is always read-only. In most cases the underlying texels are read-only. For a write-only storage texture, the underlying texels are write-only.

The section about the `write-only storage texture` is confusing to read as it isn't referring to anything mentioned in the Address space table above. The table refers to a `handle` which is read-only, but the write-only storage texture is the thing the handle points too. There is a level of indirection that either needs to be clarified in the note, or the note moved somewhere else.

**Comment by alan-baker** [comment]
This is now in https://gpuweb.github.io/gpuweb/wgsl/#var-decls and I think is clearer.
