### ISSUE TITLE
Update comment about reference types not appearing to a note.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3052]
In [4.5. Memory View Types](https://www.w3.org/TR/WGSL/#memory-view-types) we have a comment at the end of the `ref` table saying:

> Reference types are not written in WGSL program source; instead they are used to analyze a WGSL program.

This should be a `Note:` to make it clearer that you can't write `ref`.

**Comment by dneto0** [comment]
It's a normative statement.  So it shouldn't be a note?

Would you rather it say "Reference types do not appear in WGSL program source"?
