### ISSUE TITLE
Add example in Memory Views section showing a ref type.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3053]
In [4.5 Memory View Types](https://www.w3.org/TR/WGSL/#memory-view-types) we talk about `ref` types but in the example provided we only show pointer types. We should add an example to the section which also shows a `ref` annotation.

**Comment by dneto0** [comment]
It would have to be in a comment about a var declaration.

**Comment by dneto0** [comment]
> It would have to be in a comment about a var declaration.

And so it seems weird it would be in the memory views section.  Maybe add the example to 'var' section, and put a note pointing forward about it?
