### ISSUE TITLE
Change `creation-time constant` in Value Declarations to `const`?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3061]
In [5.1. Value Declarations](https://www.w3.org/TR/WGSL/#value-decls) we refer to the 3 ways to make a value declaration.

* a let declaration
* an override declaration
* a creation-time constant.

In the first two, it's obvious they keyword used to declare the value `let` or `override`. For the last, it isn't obvious that this refers to a variable declared `const`. Saying `a const declaration` and linking to `creation-time constant` would make it clearer how to declare the value.

**Comment by dneto0** [comment]
Yeah, the section is a conceptual spaghetti at the moment.   Now that module-scope let is replaced by 'const', we can reorg to make things much more clear.

- const decl
- override decl
- let decl

That ordering follows the shader lifecycle: shader-creation-time, pipeline-creation-time, runtime.
