### ISSUE TITLE
Extend let declaration description to make clear how it is different from const

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3063]
In [5.1.1. let Declarations](https://www.w3.org/TR/WGSL/#let-decls) we say:

> A let declaration specifies a name for a value. Once the value for a let-declaration is computed, it is immutable.

This, on first reading, sounds like a `const` value. By reading the `const` section some nuance is added. It maybe worthwhile adding the nuance to the let section as well and saying something like:

> A let declaration specifies a name for a value that maybe computed at runtime. Once the value for a let-declaration is computed, it is immutable.

**Comment by dj2** [comment]
Along with that, we should add an example of a `let` which is set at runtime. The examples in `Example: Let-declared constants at function scope` could all be `const` values.

**Comment by dneto0** [comment]
yep, this lack of clarity comes from the fact that half of let's use cases are replaced by const.
So we can make this all much clearer.  Should fix along with #3061
