### ISSUE TITLE
wgsl: function param that is pointer-to-workgroup is problematic if the store type contains an atomic

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3067]
Consider this:

```groovy
var<workgroup> w: atomic<i32>;

fn helper(p: ptr<workgroup,atomic<i32>>) {
  atomicAdd(p, 42);
}

@compute @workgroup_size(2)
fn foo() {
  helper(&w);
}
```

A proposed translation to HLSL:
- creates a local variable in the caller
- copies the value of the 'shared' variable into that local variable
- calls the helper
- and on return from the function, copies the data back into the 'shared' variable.

Something like this:
```hlsl
groupshared int w;

void helper(inout int p) {
  int atomic_result = 0;
  InterlockedAdd(p, 42, atomic_result);
  atomic_result;
}

struct tint_symbol_1 {
  uint local_invocation_index : SV_GroupIndex;
};

void foo_inner(uint local_invocation_index) {
  if ((local_invocation_index < 1u)) {
    int atomic_result_1 = 0;
    InterlockedExchange(w, 0, atomic_result_1);
  }
  GroupMemoryBarrierWithGroupSync();
  helper(w);
}

[numthreads(2, 1, 1)]
void foo(tint_symbol_1 tint_symbol) {
  foo_inner(tint_symbol.local_invocation_index);
  return;
}
```

But there are several problems with this:
- Most fundamentally, the atomic action occurs in a _copy_ of the original variable, so it's on different locations, and we've lost any coordination between the invocation.
- More mechanically, this HLSL code does not compile:
      - InterlockedAdd can only operate on shared or UAV / "resource" variables, not on an inout parameter.
      - the compiler complains that atomic_result is unused.

Originally filed as https://bugs.chromium.org/p/tint/issues/detail?id=1590 after discussion with @alan-baker

**Comment by dneto0** [comment]
In today's meeting we agreed to go with the first solution.  It's more complicated, but still supports legitimate and useful use cases.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-28-minutes#wgsl-function-param-that-is-pointer-to-workgroup-is-problematic-if-the-store-type-contains-an-atomic-3067">WGSL meeting minutes 2022-06-28</a></summary>



* DN: Problem if user defined function taking func param which is pointer to workgroup. If that workgroup variable has an atomic in it you don't’ want copy-in/copy-out as the thing you called could do an atomic modification and copy-in and out is the wrong thing to do. Atomic has to operate on the locations.  So, a problem implementing this with a copy-in/out environment and we want that in HLSL. So, can either say can’t have ptr to workgroup as func param where workgroup has atomic, or avoid sharp edge and disallow ptr to workgroup. Prefer second option and just eliminate the case
* MM: HLSL has atomics and copy-in/out, what does HLSL do?
* AB: Run into issue as atomic requires storage qualifier so can’t do that on input. So can’t do on function apram, have to access the var (at least when I tried in HLSL)
* KG: So have to use global variables?
* AB: Yea.
* GR: That’s correct. Global or group shared.
* AB: Meant module scoped.
* MM: The problem trying to solve is someone wrapping atomic in function and the signature of wrapper is same as atomic op then what they think will happen, won’t happen.
* DN: Right.
* MM: If did same in HLSL it wouldn’t happen.
* AB: It’s a compile error in HLSL.
* MM: One option is forbid, what’s other?
* DN: Both forbid, but how complicated is the carve out. Complicated but precise is forbid ptr to workgroup when store type contains atomic in hierarchy. Simple option is forbid ptr to workgroup all together.
* MM: Kneejerk, prefer first one. Can imagine ptr to workgroup in helper function, seems legit. We know types in compiler and can do recursive search.
* KG: Sounds like tolerable carve out.
* JB: Option 2 forbidding workgroup pointers is the one we could extend to specific later. It is more in line with keep it simple now and refine later but agree with MM that sounds like it would be pretty useful in the non-atomic case. More complicated carve out sounds better.
* AB: Already have restriction to pass ptr to workgroup is to pass a ref to the entier variable. Kind of limits usefulness. All vars have to be the same type to be compatible. Not as useful as part of this var and part of that var. They’re literally the same type
* MM: Understand what saying, but still seems like a use case I can imagine folks wanting.
* JB: If we add this we’re going to run into folks with compute shaders in WebGPU and will get feedback on how this is annoying
* DN: We may, objection is about dev ergonomics and how hard is it to explain and remember. Not technical, but people problem.
* JB: Already have user defined function clause, which is only getting longer.
* KG: Think good warning messages will help
* MM: Think argument about human problem makes sense. Think the claim I’m making is I could image that more the 50% of users of ptr to workgroup will never use atomics in them anyway.
* DN: Poster Child for atomic is sorting with a stage and barrier and swap. Double buffering situation. Good example of helper and pointer to workgroup. So, buy that 50%.
* MM: Another example is matrix multiply, don’t use atomics but want workgroup memory as it’s faster.
* DN: So go with more complicated carve out.
* KG: Sounds like it.


</details>
