### ISSUE TITLE
Inherit from EventTarget

### ISSUE THREAD

**Issue by Ms2ger** [gpuweb/gpuweb#307]
We decided in 2011 that we wouldn't make EventTarget a mixin; let's not re-litigate that here.

https://lists.w3.org/Archives/Public/www-dom/2011AprJun/0158.html
https://www.w3.org/Bugs/Public/show_bug.cgi?id=12574

**Comment by kainino0x** [comment]
Ah, thank you for finding that. I'll fix this when I get a chance.

**Comment by kainino0x** [comment]
We have multiple PRs in flight around this (#316 and one more about , but since I know the requirement I will definitely incorporate it. No need to keep this open anymore IMO.
