### ISSUE TITLE
Clarification around `vector` and `matrix` for creation-time constant

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3074]
In [5.1.3 Creation-time Constants](https://www.w3.org/TR/WGSL/#creation-time-consts) we list the types a creation-time constant must be including:

* constructable type
* abstract numeric type
* vector
* matrix

I'm guessing the `vector` and `matrix` additions are in order to allow abstract numeric vector and matrix classes. It would be good to call that out specifically as otherwise `vector` and `matrix` fall under constructable types.

**Comment by alan-baker** [comment]
I feel like this has been clarified with recent editorial changes to types and declarations.
