### ISSUE TITLE
Publish the spec

### ISSUE THREAD

**Issue by Ms2ger** [gpuweb/gpuweb#308]
Or at least link to where it's published from the repo.

**Comment by kainino0x** [comment]
The landing page for WebGPU is WebGPU.io. The first link on that page is for the "spec" (actually just interface definition, and it's a little outdated because we don't have automated publishing yet).

It would be good to link to the landing page from gpuweb/gpuweb.

**Comment by kainino0x** [comment]
I added it to the repo description.
