### ISSUE TITLE
Clarify lifetime of a variable

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3080]
In [5.2. var Declarations](https://www.w3.org/TR/WGSL/#var-decls) we refer to:

> The lifetime of a variable is the period during shader execution for which the variable exists. 

There is a bit of subtly here in that the lifetime of a variable is related to when the storage for a variable exists, not for when the name is visible. From a reading of the spec, we specify the lifetime of a variable as `It begins when control enters the variable’s declaration.`  This specifically means the _storage_ lifetime exists, the _name_ does not exist until after the declaration is complete.

The following is illegal:

```rust
var x = x + 4;
```

As, even though the storage for `x` exists as soon as we hit the `=`, the `x` name does not exist until the `;`.

This is as opposed to the following which is legal:

```rust
var x = 4.0;   // Outer x is 4.
if (true) {
  var x = x + 4;  // Inner x is 8.
}
```

So, we picked the name of the shadowed `x1` inside the declaration for the shadowing `x2`.

**Comment by dneto0** [comment]
Thanks for pointing this out.   Yes, it's more vague than it should be.

There's actually three things here:
- the storage; which we can call in this discussion "the object that is a variable".
- an identifier
- the act of resolving an identifier to the object.

Saying "the name exists when" is actually misleading/imprecise.

The rule is:
 - the object exists at the start of the declaration statement. 
 - the identifier will not resolve to the object until after the declaration statement.   (Let's ignore out-of-order module-scope declarations for now.)
 - So when you use the identifier 'x' on the RHS of `var x = x + 4;` it will either (a) not resolve to anything and cause an error, or (b) resolve to the object declared in an enclosing scope.

We should amend the text to spell this out more clearly, starting with:

> The lifetime of a variable is the period during shader execution for which the storage for the variable exists.  

... and then talk about the resolution of the identifier to the object.

**Comment by dneto0** [comment]
Or, say the lifetime of the variable starts once control *exits* the variable declaration.
