### ISSUE TITLE
Clarify usage of `@group` and `@binding` decorations

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3082]
In [5.3 Module Scope Variables](https://www.w3.org/TR/WGSL/#module-scope-variables) when referring to the resource interface we say:

> Such variables are declared with group and binding decorations.

Should the `are` in the statement be a `must be` to make it clear the decorations are required?

**Comment by dneto0** [comment]
https://www.w3.org/TR/WGSL/#resource-interface already says 

> Each resource variable [must](https://www.w3.org/TR/WGSL/#shader-creation-error) be declared with both [group](https://www.w3.org/TR/WGSL/#attribute-group) and [binding](https://www.w3.org/TR/WGSL/#attribute-binding) attributes. Together with the shader’s stage, these identify the binding address of the resource on the shader’s pipeline. See [WebGPU § GPUPipelineLayout](https://gpuweb.github.io/gpuweb/#pipeline-layout).

So my inclination is to delete the sentence in 5.3
