### ISSUE TITLE
Clarification around usage of module constants

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3085]
In [5.4 Module Constants](https://www.w3.org/TR/WGSL/#module-constants) we say:

> When a variable or feature is used within control flow that depends on the value of a constant, then that variable or feature is considered to be used by the program. This is true regardless of the value of the constant, whether that value is the one from the constant’s declaration or from a pipeline override.

This could use an example to explain what is happening. I believe this means the following (pseudocode):

```
var<storage> a;
var<storage> b;
const c = false;

fn foo() {
  if (c) {
    a;
  } else {
   b;
 }
}
```

We will consider both `a` and `b` used even though you can never access `a` just because we used a const to hold the false? Does that mean if we changed the `const` to a `let` we would remove `a` from the statically used set?

Does it mean that if we wanted to do dead code removal, we have to determine static usage before the removal as we'd remove true part of the if?

**Comment by dneto0** [comment]
> Does it mean that if we wanted to do dead code removal, we have to determine static usage before the removal as we'd remove true part of the if?

That depends on whether removing those variable/constant references make the new version of the shader less compatible with the old version of the shader.

Removing references to resources (textures, samplers, and buffers) makes the shader usable in more situations.

Removing 'override' declarations is more interesting.  WebGPU says 

> The key of each key-value pair must equal the identifier string of one such constant. When the pipeline is executed, that constant will have the specified value.

So if you had `override a : i32;` in the shader, then the API side must supply a value for `a`.   But then if the shader is transformed to drop `a` then now it's an error for the API side of the app to supply a value for `a`.

**Comment by dneto0** [comment]
And in any case, what I wrote above is about *transforming* a shader, which is out of scope for the specs. But the specs should be clear about what is valid for a given shader.
