### ISSUE TITLE
Q: will implementations provide additional builtin functions/structures?

### ISSUE THREAD

**Issue by pes10k** [gpuweb/gpuweb#3102]
This issue is part of PING review https://github.com/w3cping/privacy-request/issues/85

From reading the spec, it was not clear to me if implementations are expected (or allowed) to expose additional builtin functions (or other program accessible functions) based on detected hardware capabilities and/or page context?

For example, if a device provides an optimized, hardware implementation of a function, could a browser expose that optimized capability to WebGPU programs as additional built in functions or structures?

Would the above be i) allowed, ii) expected, or iii) prohibited by the current spec text?

**Comment by Kangz** [comment]
WGSL defines [language extensions](https://gpuweb.github.io/gpuweb/wgsl/#language-extensions) that can be grouped in two categories: pure language features that don't require additional support (for example tuple types) or features exposing hardware capabilities (like the [`f16` enable](https://gpuweb.github.io/gpuweb/wgsl/#extension-f16)).

Features that don't depend on hardware will be mostly like JS where browsers either support them or not. (in some rare cases support may depend on the OS but that seems rare/unlikely). So these aren't really a fingerprinting vector.

Features that depend on hardware require the extension to be enable when creating the WebGPU device, for example [`shader-f16`](https://gpuweb.github.io/gpuweb/#dom-gpufeaturename-shader-f16). This means that the fingerprinting vector for these extensions are entirely contained in the `GPUAdapter` / `GPUDevice` request flow and WGSL doesn't add any fingerprinting vector by itself. Basically this issue folds into #3101.

**Comment by Kangz** [comment]
Tentatively closing this issue as folded in #3101 based on the comment above.
