### ISSUE TITLE
Criteria for pushing the WebGPU and WGSL specification to Candidate Recommendation

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#3107]
Recently the standardization meetings have been, or are close to running out of issues to talk about. This means that we are approaching the next step of the standardization of WebGPU and WGSL where they get to Candidate Recommendation status (CR). We should collectively decide what are the criteria for asking this transition based on spec / implementation / test statuses.

What do you think of the following criteria? Anything missing?

 - The spec is semantic-complete:
    - All non-editorial issues have been resolved for WebGPU and WGSL.
    - All editorial issues (in the issue tracker or inline in the spec) about the semantics have been resolved. Issues about rewording / restructuring the spec can still be outstanding.
 - The spec is implementable:
    - To the best of our knowledge one implementation (Chromium most likely given the current statuses) implements all the spec correctly and reasonably efficiently. (we always find subtle issues when implementing new parts of the spec, this makes sure at least one "debugging" pass has been done on each part of the spec).
    - Other implementations agree, without necessarily having done all of it, that the spec can be reasonably implemented in their architecture.
 - The spec is reasonably tested ():
    - Each area in which WebGPU is novel is covered by reasonably exhaustive tests. (includes validation, new mechanisms like GPUExternalTexture, operations with DOM, buffer mapping, uniformity analysis, etc).
    - Each area in which WebGPU defers to target APIs has at least some simple tests to check arguments are correctly passed through (sampler wrap modes, rasterization, some WGSL builtins and arithmetic operations, ...)
  - Cross functional approvals (unless stalled after multiple reminders):
    - Internal cross-functional reviews needed by each implementer gave approval for WebGPU (examples: Security teams, API owners, ...)
    - Public cross-functional reviews gave approval (W3C TAG, security, PING, ...)

**Comment by kdashg** [comment]
The levels are at here: https://www.w3.org/2004/02/Process-20040205/tr.html#q73
> * Working Draft (WD)
>   * A Working Draft is a document that W3C has published for review by the community, including W3C Members, the public, and other technical organizations.
> * Candidate Recommendation (CR)
>   * A Candidate Recommendation is a document that W3C believes has been widely reviewed and satisfies the Working Group's technical requirements. W3C publishes a Candidate Recommendation to gather implementation experience.
> * Proposed Recommendation (PR)
>   * A Proposed Recommendation is a mature technical report that, after wide review for technical soundness and implementability, W3C has sent to the W3C Advisory Committee for final endorsement.
> * W3C Recommendation (REC)
>   * A W3C Recommendation is a specification or set of guidelines that, after extensive consensus-building, has received the endorsement of W3C Members and the Director. W3C recommends the wide deployment of its Recommendations. Note: W3C Recommendations are similar to the standards published by other organizations.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-2022-07-06#criteria-for-pushing-the-webgpu-and-wgsl-specification-to-candidate-recommendation-3107">WGSL meeting minutes 2022-07-06</a></summary>

* KG: last week we said "think about it". Thoughts? Don't have to make decisions now.
* KG: in my mind - we're kind of at CR. Still have things to sort out and issues to fix - but not how strict we want to be about CR. If we are, then not much diff between Candidate Recommendation and Proposed Recommendation. We think, this is more or less a spec. Mostly need to implement, see if it's implementable. Seeing more issues come up that are impl-focused, which is good.
* JB: seems WGSL has pretty major issues that don't have Draft in the spec. For example decision about builtin overriding. Would be nice to at least have some language in the spec. That's one thing I'd like to see in the spec before CR.
* KG: that's fair - focused on milestone as V1 release. But V1 is sort of the proposal / W3C Recommendation. We have things to work on there - but need to figure out blockers for CR.
* JB: do we have a milestone for CR blocker?
* KG: will talk with Corentin. Reasonable? Don't want to over-optimize what goes in what milestone. Want to go through CR issues before PR ones.
* KN: subjective threshold - not too easy - but also not that important. Good idea to think about this now.
* MM: what's Github label meaning of CR / PR / V1 / post-V1? Worried we're adding process.
* KG: issue here - W3C does have a process. Right now we're at proposal process. 2 stages between now and recommendation stage. Don't want to accidentally stay at Working Draft phase until we're ready for recommendation. A way to force people to think about whether we should fix this before we go to CR.
* KR: The CR doesn’t have to be perfect. Agree with JB on builtin overrides being a large undecided issue, and generally how we move forward as a language. I think CW’s criteria captures this well, and I think that would be a non-editorial issue. Before things are fully polished, we can still say we have implementations, even though we’re not fully portable, but we think this thing is implementable, and let it bake there while we wait for implementations to catch up.
* KG: want to think more, **see what Corentin thinks**. Part of this is project management. We'll figure something out with Github labels - as a group, **let's think what we'd like to see before CR**. **We’ll come back to this next week.**
* KN: if we take the first criteria - spec's semantic complete - then I think what remains aside from spec being implementable are reasonably tested, etc. - think we have some editorial work before CR, but not a lot. Think we could take these suggested criteria and only worry about CR milestones for editorial stuff. Everything we've resolved upon needs to be written down in the spec. Editorial stuff, ideal to have before CR.

</details>

**Comment by kainino0x** [comment]
To condense my thoughts from the meeting: Based on my reading of the definition of Candidate Recommendation (quoted above), I think we should move to that stage a little sooner than in Corentin's proposal. Specifically, I don't think we need to be 100% sure that the spec is implementable and tested before CR - it specifically says CR is "to gather implementation experience".

We discussed categorizing some of our discussion topics into milestones for CR vs PR (vs REC?). I think we could, but it's probably not necessary for standardization topics: All of the 1.0 features should be for CR. Editorial work makes more sense to split into those buckets. However we probably don't need to actually label them: All CG-resolved issues need to get written down for CR. Most editorial issues are not required for CR. Some major structural editorial issues (e.g. #2962) are nice-to-have for CR, but the editors can handle prioritizing these.

**Comment by Kangz** [comment]
Thank you @tidoust for the explanation ! We'd be happy to advertise that WebGPU is seeking review on `public-review-announce@w3.org`. Additional groups that would be interested in WebGPU that we identified are:

 - WebAssembly
 - the Media working group
 - Immersive Web
 - Machine Learning
 - and the HTML groups responsible for the JS event loop

There isn't a strong target date for CR yet, but let's put it in 3 months to give ample time for feedback (and since it is summer vacations), so mid-October? Could you reach out to these groups on behalf of WebGPU WG? It would help a lot.

**Comment by Kangz** [comment]
> Sure! For clarity, is that for WebGPU and WGSL or just for WebGPU? Issue title includes both but your last comment only mentions WebGPU (and I'm not seeing something explicit in [meeting minutes](https://github.com/gpuweb/gpuweb/wiki/Minutes-2022-07-13#criteria-for-pushing-the-webgpu-and-wgsl-specification-to-candidate-recommendation-3107)).

This is for both WebGPU and WGSL, although we expect much less comments on WGSL.

> For WHATWG, this seems a request for them to review something more specific. Is the ask to review WebGPU algorithms' integration with the event loop? Something else? Any pointer to share?

@kainino0x would you have a list of topics we'd like WHATWG to look at? I can think of RAF and external textures, but is there more?

**Comment by kainino0x** [comment]
WHATWG:

- [`importExternalTexture()`](https://gpuweb.github.io/gpuweb/#dom-gpudevice-importexternaltexture), specifically interaction with the outside world, especially:
  - [expire stale external textures](https://gpuweb.github.io/gpuweb/#abstract-opdef-expire-stale-external-textures)
- The [Canvas Rendering](https://gpuweb.github.io/gpuweb/#canvas-rendering) section's integration with the outside world (our internal slots and state changes don't need *specific* attention except in how they affect the integration). Note that Anne van Kesteren has worked with us a bit on the design, specifically for resizing, and Domenic Denicola also worked with us a bit on a number of things, especially IDL patterns and the event loop.
  - [update the rendering of the WebGPU canvas](https://gpuweb.github.io/gpuweb/#abstract-opdef-update-the-rendering-of-the-webgpu-canvas)
  - Just below that, the integration for `transferToImageBitmap()`
  - Just below that, the integration for "When WebGPU canvas contents are read using other Web APIs"
  - [Canvas Context sizing](https://gpuweb.github.io/gpuweb/#context-sizing), corresponding issue #2930
  - The [GPUCanvasAlphaMode](https://gpuweb.github.io/gpuweb/#GPUCanvasAlphaMode) section
- [copyExternalImageToTexture](https://gpuweb.github.io/gpuweb/#dom-gpuqueue-copyexternalimagetotexture), doesn't need much attention but you can look at the image types we allow: `ImageBitmap or HTMLCanvasElement or OffscreenCanvas`
- Every mention of color space, transfer function, and premultiplied alpha, if anyone wants to look at it, but I'm reasonably confident about it. The overview is [Color Spaces and Encoding](https://gpuweb.github.io/gpuweb/#color-spaces)

(Apologies if any of these links break - hopefully the text will help find them again if so.)

**Comment by tidoust** [comment]
> There isn't a strong target date for CR yet, but let's put it in 3 months to give ample time for feedback (and since it is summer vacations), so mid-October? Could you reach out to these groups on behalf of WebGPU WG? It would help a lot.

I sent messages to the different groups, trying to call out possible areas of integration:
* [message to the WebAssembly WG](https://lists.w3.org/Archives/Public/public-webassembly/2022Jul/0003.html)
* [message to the Media WG](https://lists.w3.org/Archives/Public/public-media-wg/2022Jul/0010.html)
* [message to the Immersive Web WG](https://lists.w3.org/Archives/Public/public-immersive-web-wg/2022Jul/0003.html)
* [message to the Web Machine Learning WG](https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2022Jul/0000.html)

And a generic message to [`public-review-announce@w3.org`](https://lists.w3.org/Archives/Public/public-review-announce/2022Jul/0003.html)

There are no specific mechanisms in place to request review from WHATWG as a whole. For canvas-related topics, I'm hearing that there is a @whatwg/canvas team (but `@-team` mentions don't seem to work across GitHub organizations, I'll see whether the message can somehow be relayed).

**Comment by fserb** [comment]
I've created [this](https://github.com/whatwg/html/issues/8123) for @whatwg/canvas.

**Comment by Kangz** [comment]
Thanks a ton @tidoust!

**Comment by ibesora** [comment]
Both [WebGPU](https://www.w3.org/TR/webgpu/) and [WGSL](https://www.w3.org/TR/WGSL/) are still in working draft. What's the ETA for getting those out of that status? Can breaking changes still happen?

**Comment by Kangz** [comment]
The discussions to go to CR are starting again, however even if the specs are working draft you can expect that no breaking changes will happen (apart from extremely niche bugfixes).

**Comment by kdashg** [comment]
We should consider all open issues in the M0 milestone to be blockers for CR.

We are almost done with getting consensus resolutions made to fix them (labels api-resolved and wgsl-resolved), but we will need to *actually* fix (not just resolve to fix) the issues to move to CR.

If something is in M0, but does not block CR, it should probably be moved to M1 instead.

**Comment by kdashg** [comment]
I do see a people doing great work knocking out resolved issues and fixing up spec text, thank you!

**Comment by Kangz** [comment]
This is the last milestone 0 issue, which means that WebGPU is ready for CR. Closing!
