### ISSUE TITLE
wgsl: should `length` builtin have AbstractFloat and f16 overloads?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3111]
Currently, the length builtin is:

>  @const fn length(e: T) -> f32
>  S is AbstractFloat, f32, or f16,   T is S or `vecN<S>`

The accuracy is given as inherited from sqrt(dot(e,e)), and  sqrt  is   `sqrt(e:T) -> T` with T being AbstractFloat, f32, f16 or vectors of them.

So it seems `length` should have overload and parameterization like this:

>  @const fn length(e: T) -> S
>  S is AbstractFloat, f32, f16, and   T is S or `vecN<S>`

That would match:
- MSL
-  SPIR-V GLSL.std.450 Length extended instruction

HLSL 'length' doesn't seem to contemplate f16 parameterization. https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-length

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-07-05-minutes#wgsl-should-length-builtin-have-abstractfloat-and-f16-overloads-3111">WGSL meeting minutes 2022-07-05</a></summary>

* **Resolved: YES, both**

</details>
