### ISSUE TITLE
Constructor expressions use `T` without defining `T`

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3127]
In [6.4.1 Construction from Components](https://www.w3.org/TR/WGSL/#construction-from-components) we list the precondition and conclusions for the various constructors. We say, for example:

`e: T; vecN<T>(e): vecN<T>`

I don't see the definition for `T` in any of the constructor preconditions. The values of `T` are listed when we talk about specific types such as `vec` earlier, but it's strange the precondition's aren't all listed.

**Comment by dneto0** [comment]
T is implicitly constrained to anything that can produce a valid vector type. It's a free variable, so to speak.  It's better to not duplicate the rules too much, as it's error prone.
