### ISSUE TITLE
Make definition of `invalid memory reference` more generic

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3128]
In the definition of [invalid memory reference](https://www.w3.org/TR/WGSL/#invalid-memory-reference) we say the value maybe from one of the memory locations of the backing WebGPU buffer.

We can generate an invalid memory reference by taking a reference to a `vec`, `mat` or `array` element which is out of bounds. There is no backing WebGPU buffer in those cases. We should change the text to be more generic and allow returning a value from the originating variable.

**Comment by dj2** [comment]
This updated the `load` side, but `store` still needs to be updated as well as it specifically says WebGPU buffer.

**Comment by dneto0** [comment]
Hm.  Seems like "invalid memory reference" should be its own section.
