### ISSUE TITLE
Is an entry point required in WGSL?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3130]
In the technical overview we state:

> A shader is the portion of a WGSL program that executes a shader stage in a pipeline. A shader comprises:
>  * An entry point function.

Does this mean that an entry point is required in a WGSL shader? Or, can I compile a shader without an entry point?

**Comment by dneto0** [comment]
An entry point is not required.
A WGSL program without an entry point is useless, except for burning energy and testing tooling.

The fact that an entry point is not required is unspoken, and should be clarified explicitly.
