### ISSUE TITLE
Is `@align(1)` valid?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3131]
Can I have an `@align(1)` or does the align value have to be a multiple of the natural alignment for the type? (So, i32 has to be 4, 8, 16, etc) or can I do `@align(1) a: i32`?

**Comment by alan-baker** [comment]
>[Must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) be a power of 2, and [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) satisfy the required-alignment for the member type:

>If align(n) is applied to a member of S with type T, and S is the [store type](https://gpuweb.github.io/gpuweb/wgsl/#store-type) or contained in the store type for a variable in address space C, then n [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) satisfy: n = k × [RequiredAlignOf](https://gpuweb.github.io/gpuweb/wgsl/#requiredalignof)(T,C) for some positive integer k.

>See [§ 4.4.7 Memory Layout](https://gpuweb.github.io/gpuweb/wgsl/#memory-layouts)

So an `i32` cannot get `align(1)`. The attribute can (currently) only increase the alignment.

**Comment by dj2** [comment]
I knew the power of 2, but 2^0 is 1, so that one held. I was looking in the Memory Layout section but that second point you quoted isn't there, it's in the description of `@align`. Although I do see:

> Structure members of type T must have a byte offset from the start of the structure that is a multiple of the RequiredAlignOf(T, C) for the address space C:

which I guess does cover it. It would be nice if these rules had a simple bulleted list somewhere to make them clearer.

**Comment by dj2** [comment]
I'd almost want it the other way, in Structure Member layout have a bulleted list of

* Must be power of 2
* Must be n = k x RequiredAlignOf  (which links to required align table)

And then in the @align section have a `See Structure Member layout for alignment requirements`

**Comment by dneto0** [comment]
Editors discussed this and think the rules are in the right place.

**Comment by dneto0** [comment]
The links are actually there already. Yay.


> [SizeOfMember](https://gpuweb.github.io/gpuweb/wgsl/#sizeofmember)(S, i) is k if the i’th member of S has attribute [size](https://gpuweb.github.io/gpuweb/wgsl/#attribute-size)(k). Otherwise, it is [SizeOf](https://gpuweb.github.io/gpuweb/wgsl/#sizeof)(T) where T is the type of the member.

> [AlignOfMember](https://gpuweb.github.io/gpuweb/wgsl/#alignofmember)(S, i) is k if the i’th member of S has attribute [align](https://gpuweb.github.io/gpuweb/wgsl/#attribute-align)(k). Otherwise, it is [AlignOf](https://gpuweb.github.io/gpuweb/wgsl/#alignof)(T) where T is the type of the member.
