### ISSUE TITLE
Update arithmetic expressions with results of over/underflow on abstract types

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3132]
In [6.8 Arithmetic Expressions](https://www.w3.org/TR/WGSL/#arithmetic-expr) we list what happens in the case of over/underflow of concrete integral types:

> If T is a [concrete](https://www.w3.org/TR/WGSL/#concrete) integral type, then the result is modulo 232.

We do not list what happens for abstract numbers. Section 4.2 lists the outcome for an abstract which is a shader-creation error.

It would be clearer if the arithmetic expressions linked back to what happens in the case of an abstract overflowing. (Even just a, for Abstracts see section 4.2 link would be useful)

**Comment by dneto0** [comment]
Same probably applies to builtins.  Eg   pow(10000,10000) should be shader-creation error because it overflows f64
