### ISSUE TITLE
`ldexp` needs clarification

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#3134]
Currently `ldexp(e1, e2)` is defined as `Returns e1 * 2^e2`.
This definition does not explicitly state any over/underflow behaviours, thus we fall back to the general over/underflow rules for WGSL.
For example, `ldexp(1, 129)` the results should be `2^129` which overflows an f32. Thus backends are supposed to return positive infinity or max f32.

SPIR-V provides additional specifications for the behaviour of ldexp, specifically when e2 is greater than 128 the result is undefined, thus a SPIR-V compliant backend may not be compliant with WGSL, since any value could be returned in the overflow case.
Talking with dneto0, he indicated it would be problematic to implement a sensible polyfill.

SPIR-V also requires that for normal f32 values calling ldexp on the result of frexp should return the original value. I think WGSL implicitly requires this, but if this invertibility behaviour is intended it is probably worth being explicit.

**Comment by dneto0** [comment]
#3445 clarified the constraints on the exponent.

The duality with frexp is left to be done.
