### ISSUE TITLE
Clarify uses of `infinity` in the spec

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3135]
In 12.5 we state that an implementation doesn't have to consider infinity and can return any valid value. We then have several places in the spec which say things can return `infinity`. The places where we just say `infinity` should be clarified  to either link back to the 12.5 section or state it is infinity or some valid value.

**Comment by dj2** [comment]
This currently leads to some confusing spec text like:

> then that operation may additionally return either the infinity with the same sign or the largest finite value with the same sign.

The `infinity` already means either `infinity` or a valid value. So, saying it could also be the largest finite value with the same sign is redundant with what `infinity` represents in this sentence.

**Comment by dneto0** [comment]
`trunc` has its own weirdness.

'trunc' says it computes 'truncate' which is defined early on in the spec.  'truncate' is  "defined over real numbers x" which excludes infinity.  So 'trunc' is not fully defined.

Appealing to IEEE-754 floating point standard, the corresponding operation would be roundToIntegralTowardZero, which references 5.9:

> 5.9 Details of operations to round a floating-point datum to integral value 

>  Several operations round a floating-point number to an integral valued floating-point number in the same
format.

...

>   These operations convert zero operands to zero
results of the same sign, and infinite operands to infinite results of the same sign.

**Comment by dneto0** [comment]
> This maybe a good place to start introducing `undefined value` as the undefined value for a f32 or f16 is `infinity or any valid value`. We then use `undefined value` and link back to the definition anywhere we have `infinity`

That's part of #2888
