### ISSUE TITLE
wgsl: trunc behaviour is not specified for infinity

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3146]
'trunc' says it computes 'truncate' which is defined early on in the spec. 'truncate' is "defined over real numbers x" which excludes infinity. So 'trunc' is not fully defined.

Appealing to IEEE-754 floating point standard, the corresponding operation would be roundToIntegralTowardZero, which references 5.9:

> 5.9 Details of operations to round a floating-point datum to integral value

> Several operations round a floating-point number to an integral valued floating-point number in the same
format.

...

> These operations convert zero operands to zero
results of the same sign, and infinite operands to infinite results of the same sign.

At the very least, the spec should capture the aspiration for what should be computed, modulo  general considerations of infinities not being fully supported (#3135)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-07-26-minutes#wgsl-trunc-behaviour-is-not-specified-for-infinity-3146">WGSL meeting minutes 2022-07-26</a></summary>

* DN: Part of larger “what is infinity”? Looked at ieee794 and …. No comments. Call for review, what should be done here? Seems silly to make trunc(inf) == max&lt;float> seems jaring and wrong. Would rather not do that. Third party filed about range issues and domain issues on builtins. Going to go catalog those.
* KG: Hopefully can just do what ieee does. Maybe you get inf.
* DN: Would like world where we have inf and we support them.
* KG: Do we remember what long pole was?
* AB: Vulkan
* KG: Detectable?
* AB: Tried to introduce controls but not on instructions. If turn on only get subset of things. Need to go further to provide for GLSL extended instructions.
* KG: Would be nice eventually but tolerable for now.
* KG: DN will write proposal.

</details>
