### ISSUE TITLE
Constant identifier expression table clarifications

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3147]
In [6.16 Constant Identifier Expression](https://www.w3.org/TR/WGSL/#constant-identifier-expr) the table refers to both `let` and `override` identifiers but the table caption specifically says `let-declared` only.

The first row is talking about `override` but specifically mentions:

> Note: Pipeline creation fails if no initial value was specified in the API call and the let-declaration has no initializer expression.

which seems like it should be referring to `override-declaration` instead of `let-declaration`.

**Comment by dneto0** [comment]
Yep, should be override-declaration. 

Consider fixing this as part of #3061
