### ISSUE TITLE
remove keywords that are context-dependent names

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3166]

**Comment by dneto0** [comment]
With context-aware tokenization, we don't need to make context-dependent names into keywords.

See the list at:
https://gpuweb.github.io/gpuweb/wgsl/#context-dependent-name-tokens

**Comment by dneto0** [comment]
This should follow #3167 to avoid conflicts.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-07-26-minutes#remove-keywords-that-are-context-dependent-names-3166">WGSL meeting minutes 2022-07-26</a></summary>

* DN: It’s a TODO and there is a PR to remove type names
* DS: LGTM
* KG: So, could say let align = 2; and that’s OK?
* DN: Yes. let flat = 4; etc.
* KG: const const = 3?
* DN: No, const is a keyword. Auto is still reserved.
* KG: Sounds right. Will see final list when PR goes up.

</details>
