### ISSUE TITLE
Compound assignment under specified.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3169]
The [7.2.3 Compound assignment](https://www.w3.org/TR/WGSL/#compound-assignment-sec) section doesn't list the preconditions for the `e1` or `e2` variables. I'd assume they fell back to matching simple assignment but this isn't quite the case as simple assignment allows a `write` LHS but for compound assignment the LHS has to be `read_write`.

We should spec the requirements for `e1` and `e2`.

**Comment by dneto0** [comment]
Actually, for |e1| to be a reference type and also appear in an expression like that, it must be read.   There's a not saying the memory is both read and written to, and that implies the access mode is read_write.

But a clarification, at least as a note would be useful.
