### ISSUE TITLE
Add text around `discard` in a `for` `update_part`

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3188]
In the continuing section we say:

>The compound statement must not contain a discard at any compound statement nesting level nor through function calls. See § 7.8 Statements Behavior Analysis for a more formal description of this rule.

The [7.4.4 For Statement](https://www.w3.org/TR/WGSL/#for-statement) should have a line about `discard` not being usable from inside a `func_call_statement` in the `for_update` section.

**Comment by dneto0** [comment]
Discard semantics have changed, so this rule is removed.
Closing
