### ISSUE TITLE
Clarification on control flow of function calls

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3198]
In [8.2. Function calls](https://www.w3.org/TR/WGSL/#function-calls) we have the three steps:

* If the called function is user-defined, control is transferred to the first statement in its body.
* The called function is executed, until it returns.
* Control is transferred back to the calling function, and the called function’s execution is unsuspended. 

From a strict reading of this, for a `builtin` we never transferred control away from the caller, but we do transfer it back?

Should the first bullet just be something along the lines of:

* Control is transferred to the called function.

**Comment by dneto0** [comment]
I think there's still an open issue to describe how a compound statement executes.  At least the above rule says where you start.  
But you're right it's weird.
