### ISSUE TITLE
Depth test state

### ISSUE THREAD

**Issue by dmikis** [gpuweb/gpuweb#32]
As agreed in meeting, discussion of depth test state. The question was (as I understand it) do we include separate flag for enabling depth test or just infer it from write mask and depth function (i.e. `depthTestEnable = depthFunc != ALWAYS || depthWrite`).

Vulkan and D3D12 have a [separate](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkPipelineDepthStencilStateCreateInfo) [flag](https://msdn.microsoft.com/en-us/library/windows/desktop/dn770356(v=vs.85).aspx), whereas Metal [doesn't](https://developer.apple.com/documentation/metal/mtldepthstencildescriptor?language=objc). Reading [section about depth test of the Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#fragops-depth) suggests that ditching separate state flag for enabling depth test is OK, i.e. `depthTestEnable` set to `VK_FALSE` is indistinguishable in terms of observable side effects from setting it to `VK_TRUE`, `depthCompareOp` to `VK_COMPARE_OP_ALWAYS` and `depthWriteEnable` to `VK_FALSE`. I *presume* the same goes for D3D12 since I wasn't able to find in MSDN anything suggesting otherwise.

Also, I think similar reasoning can be applied to stencil test state.

**Comment by Kangz** [comment]
> The question was (as I understand it) do we include separate flag for enabling depth test or just infer it from write mask and depth function (i.e. `depthTestEnable = depthFunc != ALWAYS || depthWrite`).

Exactly, I'd be in favor of ditching the redundant `depthTestEnable` flag. @BenConMS, you had some concerns about this what where they?

**Comment by BenConMS** [comment]
My concerns are twofold:

1) I think that from a use ability perspective, disabling depth testing explicitly is much easier to figure out than thinking about always vs never vs something else.

2) The implementation on 2/3 platforms is simplified by having the flag map directly to the runtime underneath.


Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by Kangz** [comment]
Closing. The group talked about this multiple times in the past and decided to not had the `depthTestEnable` flag. See also https://github.com/gpuweb/gpuweb/pull/122 and https://github.com/gpuweb/gpuweb/issues/809
