### ISSUE TITLE
Function attribute duplication

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3203]
In [8.1. Declaring a User-defined Function](https://www.w3.org/TR/WGSL/#function-declaration-sec) we say:

> WGSL defines the following attributes that can be applied to function declarations:
> * the pipeline stage attributes: vertex, fragment, and compute
> * workgroup_size

We then have the same list with an example in [9.2.1 Function Attributes for Entry Points](https://www.w3.org/TR/WGSL/#entry-point-attributes).

Should the 8.1 just link to the 9.2.1 content as something like:

> Attributes on a user-defined function can be found in [9.2.1 Function Attributes for Entry Points]

Or something?

**Comment by alan-baker** [comment]
I think probably no because I expect to loosen the restriction on `const` in the future and allow it on user-defined functions.
