### ISSUE TITLE
Clarification on `const` in static access

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3204]
In [9.3. Shader Interface](https://www.w3.org/TR/WGSL/#shader-interface) we say:

> When an identifier used in a function declaration resolves to a module-scope variable, then we say the variable is statically accessed by the function. Static access of a let-declared constant is defined similarly. 

This reads to me like `var` and `let` but it seems like `const` is missing? Is a `const` considered static access or is it just folded away.

What about an `override` is it considered static access?

**Comment by alan-baker** [comment]
This now mentions variable and value declarations and links to that chapter.
