### ISSUE TITLE
Fix title for `entry point IO types`

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3205]
In [9.3.1 Pipeline Input and Output Interface](https://www.w3.org/TR/WGSL/#pipeline-inputs-outputs) we have:

"The ***entry point IO type***s". Can we move the "s" inside the bolded text, otherwise the combination of bold + italic makes the letters squishy and hard to read.

**Comment by dneto0** [comment]
That text was deleted.

**Comment by dneto0** [comment]
See https://github.com/gpuweb/gpuweb/pull/3237
