### ISSUE TITLE
Allow optional `()`s on `enable`?

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3207]
We currently have `enable f16;`. Is there any reason to not support `enable(f16);` as I'm guessing it's something a lot of folks will write by accident.

We either detect it and say remove the `()`s or we just allow optional `()`s (similar to `staticAssert` allowing optional brackets).

**Comment by ben-clayton** [comment]
We discussed this offline, but I want to add: The grammar for `staticAssert` does not allow optional parentheses, it takes an expression, and an expression can have any number of nested parentheses.

As the extension identifier is not an expression, I personally find having the optional brackets undesirable. I'd rather either require brackets, or require no brackets, or even require the extension name to be quoted - which could then be classed as a string expression.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-09-minutes#allow-optional-s-on-enable-3207">WGSL 2022-08-09 Minutes</a></summary>

* DS: Seemed like a nice quality of life thing
* DN: Against it, Ben also against it. Future world thing where thing looks like expr or not.  E.g. import.
* KG: Prefer not doing it.
* DS: Close as rejected.

</details>
