### ISSUE TITLE
Precision requirements for `atan2` appear to be too restrictive for some backends

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#3209]
While working CTS tests for `atan2` I have encountered backends, specifically Nvidia & Intel running DirectX, that appear operating with different accuracy requirements than what is currently in the spec.

The current requirement for 32-bit floats is 4096 ULP, which is the same accuracy that Vulkan defines. Though `atan2` is defined as the arc tangent of y over x, `atan(y/x)`, the accuracy makes no mention of inheriting from `atan` or the division operation, thus as written is doesn't gain any of the domain restrictions that division has.

For very large `y` & `x` I am seeing failures where backends are returning 0 instead of small number near to zero. For example:
 atan2(y = -5.669010335538281e+35 (0xfada5cc2), x = 2.869936417201091e+38 (0x7f57e8f7)) has an acceptance interval of [-0.001976259984076023, -0.001974352402612567], but the backends we are having issues with are returning 0 instead.
 
I have hand worked out this example using a scientific calculator, and I am confident that what the CTS is providing are reasonable constraints.

I suspect internally these implementations are doing something like atan2(y, x) = atan(y/x), and y/x is becoming 0 for very large y and x values, since the domain of division is bounded and these values are out of those bounds and the only failing cases I am seeing are related to very large values, where the denominator doesn't dominate the result.

@dneto0 has suggested a potential change of defining the accuracy of atan2(y, x) to be atan(y/x), though that will have knock on effects due to atan2 being used in the accuracy of many other trig functions.

**Comment by dneto0** [comment]
This boils down to a request from Microsoft:  Does DirectX have a functional spec (effectively) for floating point accuracy?  The starting point in WGSL is "what Vulkan says" but for atan2 the Vulkan requirement is more strict than what works on DirectX.

Question to @pow2clk

**Comment by jimblandy** [comment]
With `atan2(x, y)`, you can always just swap x and y to ensure that x is bigger (in absolute value). Then `y/x` is always in `[-1,1]`, single-argument `atan` works well, and you adjust the angle returned for the swap if necessary. This feels like something that could be done with selects, mins and maxes.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-09-minutes#precision-requirements-for-atan2-appear-to-be-too-restrictive-for-some-backends-3209">WGSL 2022-08-09 Minutes</a></summary>

* GR: correct we do not have those precision guarantees. Flush denorms. Don’t have explicit atan2 intrinsic. 
* DN: So, does MSFT have a statement of rules of what the functional spec is?
* GR: Not beyond what was just said.
* DN: So case by case basis and RH will try to come up with a rule that seems right
* GR: Are you familiar with the … spec
* TR: Usually only have this if there is an instruction but there isn't’ for this it’s expanded
* MM: Seems there aren’t that many floats so we could check all of them, maybe not on every device but on every member
* GR: Could piece together based on … and function spec
* DN: If there are expansions we can support that, would be really useful.
* KG: If there is an expanded def of what atan2 becomes we’re good to go. If there isn’t we’ll do testing. Sounds like there isn’t one.
* GR: Don’t believe it’s document but it’s fairly independent
* TR: Expansion is done in DXC which is opensource
* MM: DX11.3 spec doesn’t mention atan
    * [https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm)
* TR: Because there is no native instruction
* JB: Link to DXC expansion?
* TR: Will add one
* [https://github.com/microsoft/DirectXShaderCompiler/blob/b3101a2feb078a9da9c78b44d9b61c8c312b646e/lib/HLSL/HLOperationLower.cpp#L1530](https://github.com/microsoft/DirectXShaderCompiler/blob/b3101a2feb078a9da9c78b44d9b61c8c312b646e/lib/HLSL/HLOperationLower.cpp#L1530)
* 

</details>

**Comment by kdashg** [comment]
TR linked us to the atan2 always-polyfill implementation in DXC: 
https://github.com/microsoft/DirectXShaderCompiler/blob/b3101a2feb078a9da9c78b44d9b61c8c312b646e/lib/HLSL/HLOperationLower.cpp#L1530

Here's my translation to WGSL-ish:

```rs
fn atan2<T>(y: T, x: T) -> T {
  let tan = y / x;
  let atan = dxil.atan(tan);
  
  let pi = T(${M_PI});
  let halfPi = T(${M_PI / 2});
  let negHalfPi = T(${-M_PI / 2});
  let zero = T(0);

  let atanAddPi = atan + pi;
  let atanSubPi = atan - pi;

  // x > 0 -> atan.
  var result = atan;
  let xLt0 = x < 0;
  let xEq0 = x == 0;

  let yGe0 = y >= 0;
  let yLt0 = y < 0;
  // x < 0, y >= 0 -> atan + pi.
  result = select(result, atanAddPi, xLt0 && yGe0);

  // x < 0, y < 0 -> atan - pi.
  result = select(result, atanSubPi, xLt0 && yLt0);

  // x == 0, y < 0 -> -pi/2
  result = select(result, negHalfPi, xEq0 && yLt0);
  // x == 0, y > 0 -> pi/2
  result = select(result, halfPi, xEq0 && yGe0);

  return result;
}
```

It's really just `atan(y/x)` with fix-ups, so there's really no way around setting our bar at ulp(atan2)<=ulp(atan(y/x)).

(also I kinda don't like using the select(F, T, C) order we have in the spec, but c'est la vie)

**Comment by kdashg** [comment]
Notably, DXC has e.g. asin and acos as opcodes (like atan).
It's possible that DXC's e.g. asin might have better ulp than `atan2(sqrt(1.0 - x * x), x)` that we require (because of vulkan?).

**Comment by munrocket** [comment]
if `-5.669010335538281e+35 / 2.869936417201091e+38` become zero it is not a problem with atan? But a problem with division?

We can try to use Newton's iteration to solve one of the following equations
```
sin z = y / r
cos z = x / r
```
after some math magic we will come up with this function that increasing accuracy of atan if sin/cos with good quality.
```rs
fn atan2<T>(y: T, x: T) -> T {
  let r = sqrt(x * x + y * y);
  let x0 = x / r;
  let y0 = y / r;
  let z = dxil.atan2(y, x);
  let sz = sin(z);
  let cz = cos(z);
  return select(
    z - (x0 - cz) / sz,
    z + (y0 - sz) / cz,
    abs(x0) > abs(y0));
}
```
But first 3 lines of code will give the same problem with division?

**Comment by litherum** [comment]
I don't really understand why there is so much discussion on this issue. The precision requirements in WGSL are a reflection of what our backends de-facto give us. If our backends have looser precision for `atan2`, we should loosen WGSL to match it. If the precision is good enough for HLSL, it's good enough for us.

(Note: this is not a general argument; this argument is only applicable to the precision of built-in functions/expressions)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-16-minutes#precision-requirements-for-atan2-appear-to-be-too-restrictive-for-some-backends-3209">WGSL 2022-08-16 Minutes</a></summary>

* KG: Like MM point we shouldn’t care too much and figure out what the bounds are. Folks either us the builtin or roll their own. Can fixup later. Just need a PR to update the bounds even though it makes the bounds worse. Or, maybe do something else? Friction is we define a lot of other precisions in terms of atan2 as it is the most precise, but hlsl it isn’t
* MM: Mostly editorial change.
* KG: Agree
* MM: Question, what is the best way to frame in the spec? Calculate individual ULP bounds for each function, think the answer is yes.
* KG: Agree, think we should mark editorial and leave to editors
* GR: THough conclusion was we would look at the operations it bounds into and the precision guarantees and decide the precision
* KG: Did that in the comments, divides y by x and calls atan.
* AB: Difference inheritance but separate issue where we need to say inherited from allows optimization on the math, similar to Vulkan. Not strictly that formula, but refactoring of the formula.
* KG: When saying in terms of atan2 we mean in terms of error bounds. Free to have a more precise acos, does not’ need to have same bounds
* AB: Other instructions too, if you refactor distribution has to be valid. Cant’ just check 1 formula in spec, can list one but has to allow mathematical refactorings
* MM: To understand, saying if the shader has single operation then we could have strong bounds on ULPs but if shader has more then 1 op that flow into each other then all bets are off? Is that what you’re saying?
* AB: x^2 - 1 == (x + 1)(x - 1) should be valid refactoring to use the RHS and give a similar result. RH is running into this as we test in the CTS
* AB: Not strictly editorial as we’re loosening the spec.
* MM: Making the point that we we compute the bounds of the LHS and RHS they might be different and that has to be legal
* AB: Yes.
* KG: **Sounds good. I look forward to PRs.**
* MM: Think thats fine but calls into question why we have error bounds if that op might not be in the shader
* AB: If no error bounds can just return 0 and have a correct function. Want something to constrain the implementation and this is a practical limit.
* MM: What is purpose of listing error bounds? Trying to help authors and give idea of what can be relied on, sounds like with error bounds in spec they can’t be relied on, so not helping anyone.
* KG: Don’t think that’s true. The truth is between those two somewhere. Don’t have absolutely free reign to blow everything apart and put together in any order. In general they do help, just not perfect and I think that’s probably Ok. If you had algorithm that did FFT and need sin and cos to work with precision and if you need more precision do something else. If you mix up math too much with too many optimizations that’s on you. If you take sin and give result it should be within the bounds.
* KG: Think we keep going with this for now and accept editorial and we’ll take a look as we come up with error bound expansions. Another way, is it better to not have them at all? I don’t think so, better to have something even if not perfect.

</details>
