### ISSUE TITLE
Define exclusivity of `Function Tag` and `Parameter Tag` values.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3223]
In [12.2.3. Analyzing the uniformity requirements of a function](https://www.w3.org/TR/WGSL/#uniformity-function) we list the tables for the `Function tag` and `Parameter tag`. We should state that those values are exclusive, and that the control flow ones are strictly more powerful than the return value ones.

**Comment by dneto0** [comment]
> we list the tables for the Function tag and Parameter tag. We should state that those values are exclusive

That falls out of the different strings.


> and that the control flow ones are strictly more powerful than the return value ones.

If that's true, it falls out of the algorithm analysis given.
