### ISSUE TITLE
wgsl: compute shaders have no user-defined inputs or outputs

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3227]
The output rule is not stated anywhere
The input rule is stated in an awkward spot, in 9.3.1.2 user-defined inputs and outputs

**Comment by dneto0** [comment]
The rule that vertex shader must emit `position` is in the function Restrictions section.  We should make that consistent with the compute shader restriction.

**Comment by alan-baker** [comment]
This is done
