### ISSUE TITLE
Out-of-bounds indirect dispatch handling

### ISSUE THREAD

**Issue by iraiter2** [gpuweb/gpuweb#323]
For indirect dispatch calls with group counts outside the minimums of APIs, should they be clamped or no-op’d? For example, in Vulkan the minimum maxComputeWorkGroupCount is (65535, 65535, 65535). It appears this limit is the same in D3D12 and OpenGL. Clamping would produce some data for users, but will most likely be incorrect data. Regardless, do we want to make a round-trip to the CPU if a debug flag is set, to let users know their call was invalid? This decision could be a smaller one, before we decide how to handle indirect draws (no-op / clamp).

**Comment by kainino0x** [comment]
@jdashg @kvark @litherum @magcius PTAL

**Comment by jdashg** [comment]
I would rather this generate an (internal) error, yeah? Same as other invalid draw call args?

**Comment by kainino0x** [comment]
Generating an error forces us to fetch data back from the GPU (although it should be ok to do it asynchronously). So there is at least some cost if we want to do it always.

**Comment by Kangz** [comment]
Marking this as editorial + needs specification. The group previously agreed that invalid `dispatchIndirect` could be no-ops, we just need to write it in the spec.
