### ISSUE TITLE
wsgl: disallow repeated use of builtin inputs and builtin outputs

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3236]
DXC forbids repeating builtin inputs.

Example https://shader-playground.timjones.io/7cc63b358ff1bd69063f7209d75ee76f

```
struct PSInput
{
	float4 color : COLOR;
    uint front: SV_IsFrontFace;
    uint front2: SV_IsFrontFace;
};

float4 PSMain(PSInput input) : SV_TARGET
{
	return input.color;
}
```
yields this error in DXC:

```
D:\local\Temp\ceafaa2c-eba5-4acc-8c23-63a853ac1a9d.hlsl:8:1: error: Parameter with semantic SV_IsFrontFace has overlapping semantic index at 0.
float4 PSMain(PSInput input) : SV_TARGET
^
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-02-minutes#wsgl-disallow-repeated-use-of-builtin-inputs-and-builtin-outputs-3236">WGSL meeting minutes 2022-08-02</a></summary>

* MM: Think it’s more important to add this restriction.
* AB: GLSL doesn’t allow it. HLSL compilers don’t allow it.
* **_Consensus forbid it for now._**

</details>
