### ISSUE TITLE
Drop support for macOS 10.12?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3238]
According to #1069, we support macOS 10.12. It came out in 2016 and was the last version without Argument Buffer support (see also #2749 and others). Should we keep trying to support it?

**Comment by kainino0x** [comment]
We dropped macOS 10.11 in https://github.com/gpuweb/gpuweb/pull/508

**Comment by kainino0x** [comment]
10.12 reached end of life in on 2019-10-01.
https://en.wikipedia.org/wiki/MacOS_Sierra
https://endoflife.date/macos

@kdashg shares this link for Firefox metrics: https://firefoxgraphics.github.io/telemetry/#view=mac
which shows we'd lose 3.8% of Mac users. I don't know if I can share our metrics, but I'll say our number is similar, but less.

**Comment by kainino0x** [comment]
FWIW I don't think we would be able to start requiring support for argument buffers immediately, because at least in Dawn it would take a bunch of work to transition to them. So, bumping this requirement may or may not make much difference.

**Comment by kainino0x** [comment]
Resolved: Don't drop support for 10.12 because there would be no (or minimal) concrete benefit to doing so. We can consider it again if we find another reason to drop it other than argument buffers.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-meeting-2022-08-0203-apac-timed#drop-support-for-macos-1012-3238">WGSL meeting minutes 2022-08-02</a></summary>

* MM: 10.12 the only version that this group is claiming to support that doesn’t have argument buffers. Using argument buffers increases some limits.
* MM: …
* MM: Raising limits will force implementations to use argument buffers.
* KG: Today I don’t think wgpu requires them. Says here Dawn doesn’t use them.
* KN: I don’t think we need to decide this for v1. But we don’t expect to be using ABs for v1 shipping, but that eventually we could switch to ABs and increase our base limits for webgpu spec itself. 
* KN: But for right now, dropping 10.12 support *might* let us increase some limits that are orthogonal to AB support. I think we can agree that we don’t want to require ABs for v1.
* MM: What is included besides ABs?
* KN: Don’t know, but I should go look.
* MM: It sounds like we should not change anything right now, but that further investigation might change this.
* MM: So resolved?** “Don’t drop 10.12 for now”**

</details>

**Comment by kainino0x** [comment]
F2F: Decided to drop support for 10.12! Now we get argument buffers and read-write storage texture tier 1. :)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#post-v1-drop-support-for-macos-1012-3238">GPU Web F2F 2023-02-16/17</a></summary>

* KN: About dropping support for macos 10.12.  V 10.13 also introduces argument buffers.  We said a few months ago we didn’t want to drop support for 10.12 because arg buffers alone wasn’t enough to motivate it. But together it’s probably enough motivation to do so.
* KG: Firefox 10.12 activation's so low I'm not worried about it for WebGPU.

</details>
