### ISSUE TITLE
Buffer state validation in unmap() is unnecessary

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3251]
Currently, unmap() validates that the buffer is currently mapped or pending. This seems unnecessary, as unmap() can be treated as idempotent, i.e. a no-op on buffers that aren't mapped.

Right now, there's a bit of an issue with the state. Unmap does the following:

- Terminate access to the mapping from JS, and get the data out of the ArrayBuffer to send. <- State validation hasn't happened yet here, so this has to work regardless of the state.
- Send the updated data to the GPU process to update the buffer, and mark it as available to the GPU again. <- sending a message to the GPU process is entirely unnecessary if the content process already knows it's going to fail.

An alternative would be to make this an exception instead of a no-op. However, I don't think an exception is necessary. Either way is fine because unmap() still does validation *before* messaging the GPU process.

~Also note: This is the only validation error generated from a method of GPUBuffer, which forces GPUBuffer to know what GPUDevice (error scope stack) to report errors back to. (May interact with #3250.)~

**Comment by kainino0x** [comment]
> Also note: This is the only validation error generated from a method of GPUBuffer, which forces GPUBuffer to know what GPUDevice (error scope stack) to report errors back to. (May interact with #3250.)

Sorry, this was wrong. mapAsync also generates an error when validation fails (in addition to rejecting the promise). We did that intentionally to preserve the "telemetry" use case of errors.

**Comment by kainino0x** [comment]
Depending on #3271 we could resolve this the opposite way, so should discuss that first.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-meeting-2022-08-0203-apac-timed#buffer-state-validation-in-unmap-is-unnecessary-3251">WGSL meeting minutes 2022-08-02</a></summary>

* KG: This is “unmap is pedantic”?
* KN:** I actually want to think more, and possibly put up a proposal that contradicts this, so let’s wait.**

</details>

**Comment by kainino0x** [comment]
I did more work on #3271 and so far I didn't actually end up finding anything which forces our hand on this issue.

**Comment by kainino0x** [comment]
In one multi-threading model that I'm considering, we'd model *multiple* clients to a device, one per thread. I think this still works fine. It simply relies on the state check inside unmap() that would be there anyway (described above).

<img width="608" alt="image" src="https://user-images.githubusercontent.com/606355/182969092-6b0f07d6-3756-4e5d-8e83-f69510c422c1.png">

**Comment by kainino0x** [comment]
Meeting: No concerns surfaced, will move to editorial Monday if no further input.

**Comment by kainino0x** [comment]
"tacit resolution queue" label migrated to the PR, #3368
