### ISSUE TITLE
wgsl: Add limits to avoid nuisance floating point literals

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3255]
The precision and range of representable floating point literals are bounded.

But it's easy enough to construct nuisance literals that cause a lot of complexity in literal parsing.

Examples:

   0x1.0p5000000000   // exponent does not fit in 32-bit int.  
   0x0.8p5000000001   // value is the same as the previous line.

   0x1.0000....(and another 1000 0 digits)...005p1 //  That last '5' isn't useful

A finite f64 has a binary exponent range of -1022 to +1023, and 53 bits of mantissa precision (~14 hex digits)

I'd like to propose program limits:
 - magnitude of the exponent of a hex float literal is at most 2000
 - mantissa of a hex float literal has at most 100 *significant* hex digits. (It can have lots and lots of leading 0s, including those that are after the '.' point.)
 - magnitude of the exponent of a decimal float literal is at most 1000  (f64 goes to about 1e308)
 - mantissa of a hex float literal has at most 100 *significant* decimal digits.

This allows all useful floating point literals, but avoids cases where a parser has to be extremely careful about overflowing its internal bookkeeping variables.

**Comment by dneto0** [comment]
Motivation: https://github.com/KhronosGroup/SPIRV-Tools/pull/4874

**Comment by dneto0** [comment]
It would be nice to rely on library functions.

* C99 strtod can parse a superset of WGSL hex floats
* C++11 std::strtod has the same effect as C's strod library function.  (And C++11 says it's based on C99).
* C++17's std::from_chars `[utility.from.chars]`, also is defined in terms of strtod, with modifications.

**Comment by dneto0** [comment]
C99's spec for strtod  doesn't go into detail on nuisance limits.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-02-minutes#wgsl-add-limits-to-avoid-nuisance-floating-point-literals-3255">WGSL meeting minutes 2022-08-02</a></summary>

* KG: What do we want to do that is different from what we currently do?
* DN: **I want to wait and see where the non-hex-float stuff lands before deciding here.**

</details>

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-09-06-minutes#wgsl-add-limits-to-avoid-nuisance-floating-point-literals--issue-3255">WGSL 2022-09-06 Minutes</a></summary>

* DN: DS filed a thing and I was looking at hex floats. Was looking at what JS did it and said 20 digits and think that's fine. Think we should take what makes sense from other specs even if it's yy significant digits. Also applies to exponents and mantissa. There is interplay there. Just want to re-apply overall logic and think it gives solution here. If others are inline with that would be most sensible.
* KG: Is this actionable? Are we done waiting?
* DN: Writing down PR for decimal case this would be a quick follow-on.
* KG: **Still waiting then**.

</details>
