### ISSUE TITLE
Accuracy of `mix` does not cover all common implementations of linear blend

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#3260]
Currently `mix`'s accuracy is listed as:
```
Inherited from x * (1.0 - z) + y * z
```

The definition of mix uses this as an example implementation, but states that the return as `Returns the linear blend of e1 and e2`

Vulkan's CTS allows an alternate formula to be used `x + (y - x) * z`, so some backends are failing in various corner cases due to subtle differences between how these formulas interact with the accuracy rules.

The spec should probably be updated to state that mix is either `x * (1.0 - z) + y * z` or `x + (y - x) * z`, and thus inherits from those formulas in a similar fashion as `clamp` does with the median and minmax options

**Comment by alan-baker** [comment]
Should we clarify that inherited from is more similar to how Vulkan defines it in terms of opportunity to optimize?

**Comment by dneto0** [comment]
Yeah there's a gap between the grayness of what Vulkan could permit, vs. the concrete desired/required for CTS testing.
And then you ask what should go in the WGSL spec.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-23-minutes#accuracy-of-mix-does-not-cover-all-common-implementations-of-linear-blend--issue-3260">WGSL 2022-08-23 Minutes</a></summary>

* KG: Feels like answer is be as lax as subsystems are
* AB: Basically covered in other issue last week, it’s editorial and we update language on inherited from
* KG: **Resolved to editorial**
* GR: So, mix is one or the other? \
AB: Yes. Basically distribution and refactorizations are correct.
* GR: Works for us.
* JB: Do the answer in WGSL and Vulkan have different accuracy?
* KG: Yes, denormal for example
* DN: Catastrophic cancellation happens in different spots.


</details>

**Comment by zoddicus** [comment]
@dneto0 Looks like we have run into this again in the CTS, this time in validation tests

**Comment by kdashg** [comment]
Fixed by https://github.com/gpuweb/gpuweb/pull/4220.
