### ISSUE TITLE
Remove the `Type-defining Keywords` section

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3277]
The type names are no longer keywords, so it's confusing have a `Type-defining Keywords` section in the spec.

**Comment by dneto0** [comment]
'override' is in that section, which is wrong too

**Comment by dj2** [comment]
Also `static_assert`. I wasn't sure about `struct` which was in that section as well so I kept it as a keyword for now.

**Comment by dneto0** [comment]
The other thing that probably needs addressing (in #3280)  is that now the '[callable](https://gpuweb.github.io/gpuweb/wgsl/#syntax-callable)' grammar element is ambiguous:


callable :
| [ident](https://gpuweb.github.io/gpuweb/wgsl/#syntax-ident)

| [type_decl_without_ident](https://gpuweb.github.io/gpuweb/wgsl/#syntax-type_decl_without_ident)

| [vec_prefix](https://gpuweb.github.io/gpuweb/wgsl/#syntax-vec_prefix)

| [mat_prefix](https://gpuweb.github.io/gpuweb/wgsl/#syntax-mat_prefix)

| [array](https://gpuweb.github.io/gpuweb/wgsl/#syntax-array)


Here, vec_prefix, mat_prefix, array should all be identifiers.  But we should add a note or similar to indicate those usages (without having to look at the type constructor sections).

**Comment by alan-baker** [comment]
This is complete
