### ISSUE TITLE
wgsl: describe how the name `vec4` in `vec4<f32>` is resolved

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3280]
See #3278, #3166

The intent is to allow user declarations to shadow builtin types like `i32` but _also_ things like `vec4` and `mat2x2`.

Given the current text in the spec, and a PR (#3278) that removes those names as keywords, shadowing `i32` is no problem.

However, how do we describe resolution of `vec4`, where `vec4` could be shadowed.
We have to first try resolving `vec4`, where we use "resolving" in a "resolves-to-a-declaration" sense.  Then once that fails, ... what.   We can't quite say 'vec4' resolves to a predeclared BLAH, because BLAH is not one of the following things a "declaration" can make a name for:
- type
- value
- variable
- function
- formal paramter

So we need to:

-  add one more item to that list:  a thing which, together with subsequent tokens describing a type parameterization, names a valid type.
- a rule saying certain such objects are predeclared: 
      - e.g. that `vec4` is a BLAH which, when followed by type parameterization `<` concrete scalar type `>` names a particular vector type.
- a note saying there is no construct in WGSL which allows you to use a BLAH in a way other than as such a type parameterization.

**Comment by dneto0** [comment]
The other thing that probably needs addressing is that now the '[callable](https://gpuweb.github.io/gpuweb/wgsl/#syntax-callable)' grammar element is ambiguous:

callable :
| [ident](https://gpuweb.github.io/gpuweb/wgsl/#syntax-ident)

| [type_decl_without_ident](https://gpuweb.github.io/gpuweb/wgsl/#syntax-type_decl_without_ident)

| [vec_prefix](https://gpuweb.github.io/gpuweb/wgsl/#syntax-vec_prefix)

| [mat_prefix](https://gpuweb.github.io/gpuweb/wgsl/#syntax-mat_prefix)

| [array](https://gpuweb.github.io/gpuweb/wgsl/#syntax-array)

**Comment by dneto0** [comment]
I'm considering defining a "pretype" as a kind of object which, together with a parameterization, names a type.
And predeclared identifiers can resolve to those pretypes.

Example,  `vec2` is a predeclared identifier resolving to a pretype such that, when you follow it with parameterization `<f32>`, yields the type that is a two-element vector of f32 components.


## Callables

Ok, what about expressions like `vec2<f32>(1.0f,2.0f)` and `vec2(1.0,2.0)`.

To analyze `vec2<f32>(1.0f,1.0f)`,   `vec2` is a pretype supplied with parameterization `<f32>` to yield type `vec2<f32>` and then we see that it's a callable, like we have now.

To analyze `vec2(1.0,2.0)`, we see `vec2` is a pretype, and pretype can be callable, with certain predeclared overloads, corresponding to many of the expressions at https://gpuweb.github.io/gpuweb/wgsl/#type-constructor-expr 

? 

In that case, "type constructor expressions"  are not expression forms, but rather built-in functions with lots of overloads.  And built-in functions are are resolved not solely by name, but by name, or type, or pretype.

That would be a pretty big change.  But it would resolve a longstanding complaint that when you parse a thing like  `x(y)` you don't know if it's a type constructor expression or a function call. It's more consistent to categorize it all as function calls, but where you expand the definition of what a function call is, and what functions exist (particularly builtin functions).

**Comment by munrocket** [comment]
Why not just `vec2f(1.0, 2.0)` as described in #736? It will be a parameterisation in new keywords and simple replacing `s/<f32>/f/g` for existing wgsl code. Just wonder why we need different styles of initialisations here.

Array expression like `array<vec2f, 6>` and matrices `mat2x2f` looks not bad for me.
