### ISSUE TITLE
wgsl: publish a form of the grammar suitable for recursive descent parsing

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3286]
The expression grammar is left-recursive, and is not immediately adaptable to a recursive-descent parser.

E.g. 

    expression ->  relational_expression  | ... | bitwise_expression

and

    relational_expression -*-> unary_expression

    bitwise_expression -*-> unary_expression

So when trying to parse "expression", in a recursive descent parser, it's not clear which alternative to pursue.

It would be nice if the spec had an appendix showing a form of the grammar that is suitable for recursive descent parsing.  It should be mechanically produced, to avoid errors in manual translation.

**Comment by dneto0** [comment]
cc: @dj2

**Comment by dneto0** [comment]
Preliminaries:
- WGSL is LALR(1)
- Recursive descent is LL(*)
- There are some LALR(1) languages which are not LL(1).
- But WGSL's grammar might be transformable to LL(*).  
- Also, we want to focus on the expression grammar, if we have to focus.

**Comment by dneto0** [comment]
With work in progress, I can remove left recursion in the grammar, then hoist up 'singular_expression' up into its ancestors all the way to `expression` and `element_count_expression`.  The result is messy, and certainly messes up associativity.

[messed-up-associativity.txt](https://github.com/gpuweb/gpuweb/files/9273930/messed-up-associativity.txt)

**Comment by dneto0** [comment]
@dj2 ^ PTAL

**Comment by dneto0** [comment]
Dan told me a better way to do it:
1. eliminate immediate left recursion.  
     *  This produces rules of the form "X.rest" which is part of a right-recursive rewriting of a left-recursive rule "X".
2.  refactor "unary_expression" out from first position into invoking context. 
     *  When X always starts with unary_expression, then X is replaced in other rule right-hand sides with "unary_expression X.post.unary_expression", and X.post.expression is the list of options in X but dropping the initial unary_expression.
3. Repeat 2 until settling. 


This looks really nice.
[wgsl.recursive.txt](https://github.com/gpuweb/gpuweb/files/9284226/wgsl.recursive.txt)

e.g. here's the rewrite of additive_expression and multiplicative_expression:
```
additive_expression:
   unary_expression multiplicative_expression.post.unary_expression additive_expression.rest
additive_expression.post.unary_expression:
   multiplicative_expression.post.unary_expression additive_expression.rest
additive_expression.rest:
   minus multiplicative_expression additive_expression.rest
 | plus multiplicative_expression additive_expression.rest
 | ε

multiplicative_expression:
   unary_expression multiplicative_expression.rest
multiplicative_expression.post.unary_expression:
   multiplicative_expression.rest
multiplicative_expression.rest:
   forward_slash unary_expression multiplicative_expression.rest
 | modulo unary_expression multiplicative_expression.rest
 | star unary_expression multiplicative_expression.rest
 | ε
```

**Comment by dneto0** [comment]
Note that the removal of immediate left recursion changes the apparent associativity.
When matching a non-empty `additive_expression.rest`, e.g 

     plus multiplicative_expression additive_expression.rest

there is always a left-hand side term that is always matched to its immediate left. Let's call it _ImplicitLeft_.

In that case the AST expression nesting should be  

     plus(ImplicitLeft, multiplicative_expression) 

and *that* node becomes the ImplicitLeft for the terminating additive_expression.rest

**Comment by dneto0** [comment]
Now without unreachable rules.
[wgsl.recursive.txt](https://github.com/gpuweb/gpuweb/files/9284303/wgsl.recursive.txt)

**Comment by dneto0** [comment]
Now collapsing cases like this:

```
A ->  B | epsilon
B -> ... | epsilon
```
By replacing all uses of A with B.

This occurs for:
```
  replacing case_compound_statement/0.1 with case_compound_statement/0.1/0
  replacing case_selectors/0.1 with case_selectors/0.1/0
  replacing continuing_compound_statement/0.1 with continuing_compound_statement/0.1/0
  replacing lhs_expression/0.0 with lhs_expression/0.0/0
  replacing argument_expression_list/0.1/0.0 with argument_expression_list/0.1/0.0/0
  replacing loop_statement/0.2 with loop_statement/0.2/0
  replacing if_statement/0.1 with if_statement/0.1/0
  replacing param/0.0 with param/0.0/0
  replacing param_list/0.0 with param_list/0.0/0
  replacing function_header/0.5/0.1 with function_header/0.5/0.1/0
  replacing struct_member/0.0 with struct_member/0.0/0
  replacing compound_statement/0.1 with compound_statement/0.1/0
  replacing struct_body_decl/0.1 with struct_body_decl/0.1/0
  replacing function_decl/0.0 with function_decl/0.0/0
  replacing global_constant_decl/1.0 with global_constant_decl/1.0/0
  replacing global_variable_decl/0.0 with global_variable_decl/0.0/0
  replacing translation_unit/0.1 with translation_unit/0.1/0
  replacing translation_unit/0.0 with translation_unit/0.0/0
[wgsl.recursive.txt](https://github.com/gpuweb/gpuweb/files/9284837/wgsl.recursive.txt)

```

**Comment by dj2** [comment]
Suggestions, some may not be easily done, not sure.

* [ ] Inline single rule elements
* [ ] Combine duplicate rules
* [ ] Right recursive rules can become `*` rules
* [ ] `for_header/0.2` didn't need to be expanded
* [ ] `for_init` can fold into `for_header/0.0`
* [ ] Collapse `| ε` to `?` ?

# Inline single rule elements

For example, `binary_xor_expression.post.unary_expression` could just be removed and replaced with the `binary_xor_expression.rest` at the call sites.

```
binary_xor_expression.post.unary_expression: 
   binary_xor_expression.rest
```

# Combine duplicate rules
There are several rules emitted with different names which are identical

```
postfix_expression/1.2: 
   postfix_expression
 | ε

postfix_expression/2.2: 
   postfix_expression
 | ε
```


# Right recursive rules can become `*` rules
Some of these, with a small number of leading tokens could be collapsed in the `*` version at the call site. For example the following could just become a `(comma expression)*`.

```
case_selectors/0.1: 
   comma expression case_selectors/0.1
 | ε
```

# `for_header/0.2` didn't need to be expanded
This got expanded from `expression` for some reason but could collapse back I think

```
for_header/0.2: 
   unary_expression expression.post.unary_expression
 | ε
```

This could just be:
```
for_header/0.2: 
   expression
 | ε
```

# `for_init` can fold into `for_header/0.0`
Not sure if this is generally applicable, but the single caller to `for_init` could be folded back up

```
for_header/0.0: 
   for_init
 | ε

for_init: 
   assignment_statement
 | decrement_statement
 | func_call_statement
 | increment_statement
 | variable_statement
```

The `for_update` rule could be similarly folded.

# Collapse `| ε` to `?` ?
There are a few rules with short first arms and then epsilon. Those could collapse back to a `?` form at the call site.

```
 postfix_expression/2.2: 
   postfix_expression
 | ε
```

Could just be `postfix_expression?`

**Comment by dneto0** [comment]
At first look:
- inline single rule elements:   Looks straightforward
- combine duplicate rules:  the grammar representation already uniques rules, so this *should* be straightforward.
- right recursive rules become * rules.   This takes the grammar out of normal form, so it can only be done in emission / post-processing
- for_header/0.2 didn't need to be expanded:  Maybe handle this with a stopping rule during left-refactoring
- for_init can be folded back into its context.  Dual of "inline single rule elements". Straightforward
- collapes | epsilon to ?:   Also takes it out of normal form. Has to be done in emission/post-processing

**Comment by dneto0** [comment]
Hm..    About for_init being folded back in.   I think once we do the collapse of `x | epsilon` into  `x?` then the for_init will look better.

Context:
```
for_header:
   for_header/0.0 semicolon for_header/0.2 semicolon for_header/0.4
for_header/0.0:
   for_init
 | ε
for_header/0.2:
   expression
 | ε
for_header/0.4:
   for_update
 | ε
for_init:
   assignment_statement
 | decrement_statement
 | func_call_statement
 | increment_statement
 | variable_statement
for_update:
   assignment_statement
 | decrement_statement
 | func_call_statement
 | increment_statement

```
With the collapsing into ? this should become:

```
for_header:
   for_init ? semicolon expression ? semicolon for_update ?
for_init:
   assignment_statement
 | decrement_statement
 | func_call_statement
 | increment_statement
 | variable_statement
for_update:
   assignment_statement
 | decrement_statement
 | func_call_statement
 | increment_statement
```
which looks really tidy to me.

**Comment by dneto0** [comment]
I used a heuristic, so that you do the * and ? substitutions only when the substituted thing only has one non-epsilon option.

So you still have things like:
```
multiplicative_expression.rest:
   forward_slash unary_expression multiplicative_expression.rest
 | modulo unary_expression multiplicative_expression.rest
 | star unary_expression multiplicative_expression.rest
 | ε
```

**Comment by dneto0** [comment]
An implementor can refactor that as:
```
multiplicative_operator ->  `/` | `*` | `%`
multiplicative_expression.rest ->  multiplicative_operator *
```

One of our rules, "inline a thing when it's only seen once" would undo the multiplicative_operator definition.

**Comment by dneto0** [comment]
About "rules with *.post.unary_expression should use them".

Looking for confounding patterns. Consider:
```
element_count_expression:
   unary_expression bitwise_expression.post.unary_expression
 | unary_expression multiplicative_expression.rest additive_expression.rest

```

It's helpful to have unary_expression out in front.  We should not absorb it back into bitwise_expression and get this:
```
element_count_expression:
   bitwise_expression
 | unary_expression multiplicative_expression.rest additive_expression.rest
```
Because now it leads to an apparent ambiguity from the perspective of a top-down parser.


A similar thing occurs in  expression
```
expression:
   unary_expression bitwise_expression.post.unary_expression
 | unary_expression relational_expression.post.unary_expression
 | unary_expression relational_expression.post.unary_expression ( and_and relational_expression )* and_and relational_expression
 | unary_expression relational_expression.post.unary_expression ( or_or relational_expression )* or_or relational_expression

```

So the rule should require the same prefix (unary_expression and *.post.unary_expression) across all the options in a choice.

**Comment by dneto0** [comment]
Latest result:
[wgsl.recursive.txt](https://github.com/gpuweb/gpuweb/files/9294269/wgsl.recursive.txt)

**Comment by dneto0** [comment]
The remaining remnants of the normalization are found via  `$egrep '\d\.\d'`, yielding:
```
assignment_statement/0.1: 
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? assignment_statement/0.1 expression
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? minus_minus
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? plus_plus
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? assignment_statement/0.1 expression
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? minus_minus
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? plus_plus
   'const' global_constant_decl/1.2 equal expression
 | attribute * 'override' global_constant_decl/1.2 ( equal expression )?
global_constant_decl/1.2: 
 | attribute * 'var' ( less_than address_space ( comma access_mode )? greater_than )? variable_decl/0.2 ( equal expression )? semicolon
   lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ?
lhs_expression/0.0/0/0.0: 
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? assignment_statement/0.1 expression semicolon
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? minus_minus semicolon
 | lhs_expression/0.0/0/0.0 * core_lhs_expression postfix_expression ? plus_plus semicolon
   'var' ( less_than address_space ( comma access_mode )? greater_than )? variable_decl/0.2
variable_decl/0.2: 
   'const' variable_statement/3.1 equal expression
 | 'let' variable_statement/3.1 equal expression
variable_statement/3.1:
```


Finding those rules:

```
assignment_statement/0.1:
   compound_assignment_operator
 | equal

global_constant_decl/1.2:
   ident_pattern_token
 | ident_pattern_token colon type_decl

lhs_expression/0.0/0/0.0:
   and
 | star

variable_decl/0.2:
   ident_pattern_token
 | ident_pattern_token colon type_decl

variable_statement/3.1:
   ident
 | variable_ident_decl
```

**Comment by dneto0** [comment]
There's a small difficulty because:
```
variable_ident_decl:
   ident colon type_decl
```
which might prompt a refactoring of the original grammar, or a refactoring step in this tooling.

**Comment by dneto0** [comment]
Left-factoring `ident` looks good. Will keep it.

**Comment by dneto0** [comment]
[  ]  Absorb trivial choice, of the form   ` x | y` , where x and y are single symbols
    - this would fix assignment_statement/0.1 and lhs_expression/0.0/0/0.0

Then all that remains are things of the form    `X | X colon type_decl` but they are pretty small and can be handled by inspection.

**Comment by dneto0** [comment]
Regarding trivial choice, there is a very useful one that we want to keep:

```
type_decl :
  ident_pattern_token
 | type_decl_without_ident
```
So only do the replacement on nonterminals that were created for canonicalization.

**Comment by dneto0** [comment]
We want to avoid absorption of `ident` too much, because its placement plays a role in determining where identifier resolution occurs.

Current result is the following (with definitions of tokens removed, since they are already in the main spec):

[wgsl.recursive.txt](https://github.com/gpuweb/gpuweb/files/9294696/wgsl.recursive.txt)

**Comment by dneto0** [comment]
We still have two epsilons (ie. empty string is a possible match for a terminal).

```
additive_expression.rest:
   minus unary_expression multiplicative_expression.rest additive_expression.rest
 | plus unary_expression multiplicative_expression.rest additive_expression.rest
 | ε
```
Given the other machinery, these go away if we make a new `additive_operator` rule and use it in `additive_expression`:
```
additive_operator:  minus | plus
additive_expression: 
additive_expression :
  multiplicative_expression  |  additive_expression additive_operator multiplicative_expression
```

Similar thing happens with multiplicative_expression.

**Comment by dneto0** [comment]
There's great opportunity to also introduce comparison_operator and shift_operator.

**Comment by dneto0** [comment]
Fixing some nagging things with deduplicating, we get this result (omitting token definitions):
[wgsl.recursive.txt](https://github.com/gpuweb/gpuweb/files/9294870/wgsl.recursive.txt)

**Comment by dneto0** [comment]
The only generated rule still in there is:

```

variable_statement/3.1:
   ident
 | ident colon type_decl
```

**Comment by dneto0** [comment]
Now if someone could come up with a better name for that.
How aboue `ident_optionally_typed` or `optionally_typed_ident`

**Comment by dneto0** [comment]
I've created  new rule:

```
optionally_typed_ident:   ident ( comma type_decl )?
```
And replaced all instances of `( ident | variable_type_decl )` which was messy and common (because of type inference).

There was one last use of variable_type_decl, which was for formal parameter declaration, so I just expanded it inline.

Now I have this result: 
[wgsl.recursive.txt](https://github.com/gpuweb/gpuweb/files/9294940/wgsl.recursive.txt)

**Comment by dneto0** [comment]
#3299 pulls out the grammar changes so they can land first.

**Comment by dj2** [comment]
This is generating rules in a form which you're taking out with #3299, is it possible to generate them the other way?

```
bitwise_expression.post.unary_expression: 
   ( and unary_expression )* and unary_expression
 | ( or unary_expression )* or unary_expression
 | ( xor unary_expression )* xor unary_expression
```

```
bitwise_expression.post.unary_expression: 
   and unary_expression (and unary_expression)*
 | or unary_expression (or unary_expression)*
 | xor unary_expression (xor unary_expression)*
```

**Comment by dneto0** [comment]
I implemented star'd rules on the right hand side.
I also played with a *bunch* of variations where inlining is less aggressive, but it seemed to lose a lot, where it was hard to see what the lookaheads should be. That seemed dodgy for recursive descent.

**Comment by dneto0** [comment]
When rewriting relational_expression, we can rewrite shift_expression similarly.

Current status: 
[wgsl.recursive.txt](https://github.com/gpuweb/gpuweb/files/9311936/wgsl.recursive.txt)

**Comment by dneto0** [comment]
In the current state there are a few places where we see:

`( multiplicative_operator unary_expression )* ( additive_operator unary_expression ( multiplicative_operator unary_expression )* )*`

I think that corresponds to additive_expression.post.unary_expression.    That would be wise to "outline" / refactor to its own, when writing code.

**Comment by dj2** [comment]
Note that that statement can evaluate to blank, which I think is fine looking through where it can showup.

**Comment by dneto0** [comment]
#3292 now has updated spec text. It's a chapter at the end.

**Comment by dneto0** [comment]
#3292 now has updated spec text. It's a chapter at the end.
