### ISSUE TITLE
wgsl: limit nesting depth of switch statements

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3294]
FXC does not support general fallthrough in switch-cases,  but WGSL does.

Tint uses case inlining to reduce to the no-fallthrough case.  This can blow up the shader size when there is deep nesting of switches inside each other.

We'd like to limit this to some reasonable limit like 5 or 10.'

cc: @dj2 and @amaiorano who investigated the original fuzzer case

**Comment by dneto0** [comment]
With 10 levels of nesting, Tint can generate the HLSL in < 1s.

**Comment by litherum** [comment]
Can we just follow HLSL here and not have `fallthrough` at all?

**Comment by dj2** [comment]
FXC seems to depend on if there is anything after the `:`. So,

```
switch(1) {
  case 1: {}
  default: {}
}
```

will reject as not allowing a non-empty case without a `break` or `return` but:

```
switch(1) {
  case 1:
  default: {}
}
```

is allowed and compiles correctly.

Neither of these appear in the [HLSL docs](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-switch) which seem to imply that a `break;` is always required.

**Comment by dneto0** [comment]
The examples at that HLSL docs link include:

```
[branch] switch(a)
{
    case 0:
        return 0; 
    case 1:
        return 1; 
    case 2:
        return 3; 
    default:
        return 6; 
}
```
So it's not that a break is syntactically required, but that other means exist to avoid fall through.

**Comment by dneto0** [comment]
> Can we just follow HLSL here and not have `fallthrough` at all?

Currently the grammar requires a statement block after a case clause or default clause.
Removing fallthrough means there's no way directly combine case and default:

So there would be no way to support this C fragment:
```
switch(a) {
   case 0:
   default { do_something(); break; }
   case 1: { do_something_else(); }
}
```
We'd have to revisit case and default grammar.  Fortunately both `case` and `default` are keywords, so they can't be used as identifiers in an expression.

**Comment by dneto0** [comment]
Strawman syntax is to allow 'default' as one of the case selectors:

```
switch(a) {
   case 0, default: { do_something();  }
   case 1: {do_something_else(); }
}
```

**Comment by dj2** [comment]
So, you'd allow:

```
switch(a) {
  case 1, 2, 3, default: { do_something(); }
  case 4: { something_else(); }
} 
```

Does `default` have to come last in the selector list?

**Comment by dneto0** [comment]
> So, you'd allow:

yes.

> Does `default` have to come last in the selector list?

No.  

In theory, we could also allow default coming before:  `default case 0, 1,2 3:`

??

**Comment by dj2** [comment]
I don't like that last one, it's very strange.

`case default, 0, 1, 2, 3:` would be better

**Comment by litherum** [comment]
RESOLVED: Remove the fallthrough keyword. In its place, allow the `default` keyword to be listed in the case statement (possibly after a comma).

**Comment by dneto0** [comment]
> RESOLVED: Remove the fallthrough keyword. In its place, allow the `default` keyword to be listed in the case statement (possibly after a comma).

Also, in a future where we can get beyond FXC, we can add fallthrough again (as opt-in)

**Comment by dneto0** [comment]
(Since the fallthrough is a keyword, and we'll reserve it now, then maybe it doesn't have to be so explicitly opt in in the shader itself.  I can't recall where we landed on that kind of thing.)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-08-09-minutes#wgsl-limit-nesting-depth-of-switch-statements-3294">WGSL 2022-08-09 Minutes</a></summary>

* DS: CAme from a clusterfuzz bug with deep nesting of switch and fallthrough.  But FXC doesn’t support fallthrough. So Tint uses inlining to get around it and blows up (codegen time).  So looking at options here.
* JB: Is it exponential?
* DS: Not sure. We’re using top-down expansion. Might go better if bottom-up?  But 10 is fine. Less than 1s.
* MM: But also codesize is a problem.
* DS: Has only been a problem on FXC. DXC doesn’t have this problem, nor any other 
* KG: Seems fallthrough is ok if there’s no body.
* DS: One suggestion is allow fallthrough if there is only no body.  And Myles had another suggestion is remove fallthrough.
* MM: fallthrough is often a mistake in C source.  Case without a body is probably ok.
* KG: So one option is remove fallthrough as a feature, and allow case clause or default empty.
* AB: clauses require a body.
* …
* KG: How did we land there?
* DN: Swift has this. Could go multiple ways, things kinda worked out well.
* KG: A practical approach.
* MM: Is it worth discussing the last statements is not a return or break. If there wasn’t fallthrough
* KG: Question of unfamiliarity for folks who expect fallthrough, Javascript does this?
* JB: Rust as well doesn't’ do fallthrough.
* KG: Favourite is to** add default to list of things for case**.
* MM: Have to worry about constexpr variable named ‘default’
* KG: It’s a keyword
* **DS: Also remove fallthrough_statement and put `fallthrough` in list of reserved words**


</details>
