### ISSUE TITLE
Make GPUBufferBinding size optional 

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#331]
How about making GPUBufferBinding `size` optional? If not specified, it would be the same as the buffer size passed in the binding `resource` of `device.createBindGroup()`?

I believe this would make code easier to read and digest for newcomers.

```diff
    const gpuBufferSize = 4;
    const gpuBuffer = device.createBuffer({
      size: gpuBufferSize,
      usage: GPUBufferUsage.STORAGE
    });

    const bindGroup = device.createBindGroup({
      layout: bindGroupLayout,
      bindings: [
        {
          binding: 0,
          resource: {
            buffer: myGpuBuffer,
-           size: gpuBufferSize
          }
        }
      ]
    });

**Comment by kvark** [comment]
Vulkan has [VK_WHOLE_SIZE](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkDescriptorBufferInfo.html) for this, so default makes sense...

**Comment by kainino0x** [comment]
Makes sense to me, I think we talked about this once before too.

My only concern is that we should try to avoid making a distinction between `undefined` and `0`. IMO it would be fine for the default to be `0`, and `0` is a special value meaning to use the whole buffer size.

**Comment by beaufortfrancois** [comment]
Having a size of `0` that means the whole buffer size doesn't seem right to me. I fail to find some examples of this usage in Web APIs.

I would go with the IDL below.

```diff
 dictionary GPUBufferBinding {
     required GPUBuffer buffer;
     u64 offset = 0;
-    required u64 size;
+    u64? size;
 };
```

If size is not defined, use the whole size of the buffer.
Otherwise use same rules as before. 0 is still a valid value.

**Comment by kainino0x** [comment]
Are there examples of Web APIs making a distinction between `undefined` and `0`?

If we want to avoid distinguishing undefined and 0, could have a special value like in Vulkan:

```webidl
enum GPUBufferBindingSize { "whole-size" };
dictionary GPUBufferBinding {
    required GPUBuffer buffer;
    u64 offset = 0;
    (GPUBufferBindingSize | u64) size = "whole-size";
};
```

**Comment by beaufortfrancois** [comment]
This `(GPUBufferBindingSize | u64)` trick is still yet another way of saying that undefined gets treated as "whole-size". We're basically still distinguishing undefined and 0 there.

I made a mistake though. We should remove the `?`, as `null` should just be treated as `0`. `undefined` should be the only special value.

Having a size of `0` that means the whole buffer size doesn't seem right to me. I fail to find some examples of this usage in Web APIs. Then, it should be:

```diff
 dictionary GPUBufferBinding {
     required GPUBuffer buffer;
     u64 offset = 0;
-    required u64 size;
+    // If size is undefined, use the whole size of the buffer.
+    u64 size;
 };
```

If size is undefined, use the whole size of the buffer.
Otherwise use same rules as before. 0 is still a valid value.

**Comment by kainino0x** [comment]
You're right that my suggestion still distinguishes 0 and undefined. Good point.

Your last suggestion looks good to me. Would you open a PR for it?

**Comment by kainino0x** [comment]
You're right that my suggestion still distinguishes 0 and undefined. Good point.

Your last suggestion looks good to me. Would you open a PR for it?

**Comment by beaufortfrancois** [comment]
@kainino0x Here's the PR: https://github.com/gpuweb/gpuweb/pull/346
