### ISSUE TITLE
`stripIndexFormat` might be a surprising pipeline-creation-time requirement.

### ISSUE THREAD

**Issue by kdashg** [gpuweb/gpuweb#3328]
https://www.w3.org/TR/webgpu/#dom-gpuprimitivestate-stripindexformat

It would help reader understanding to include a non-normative note about why this is required. (It's not required in all native APIs)

**Comment by kainino0x** [comment]
The sentence "This determines the strip’s primitive restart value." is supposed to explain why this is here although it's written as a fact, not a justification, so could probably be clearer

**Comment by kdashg** [comment]
Specifically, it's valuable to communicate in which situations we need to know this already, since IIRC e.g. Vulkan does *not* need this.
It's both helpful for authors trying to grok why this requirement/constraint exists, and as a note to ourselves to explain or hint why it ended up this way.

**Comment by kainino0x** [comment]
We avoid references to specific underlying APIs in the spec (even non-normatively) for *reasons*.

Reviewing #767 and #1220 it appears only D3D12 requires this. I'm not sure if we should write that in the spec though. Would this provide value to developers or only to implementers (who hopefully can find implementation info by looking at issues, other implementations, etc.)?

**Comment by kdashg** [comment]
What about "Some implementations require this knowledge at pipeline-creation-time to prevent onerous recompilations."? It would be nice to call out specifically why when we are able to. If we can say "(e.g. on D3D12)" that would be ideal, but I can understand if we are hesitant to do so.

I think this does provide value to both implementers and authors. It reminds implementers why it was placed here (even I can barely remember), and it gives authors a reason for why something newly-restrictive is preventing trivial porting of content that may work elsewhere. (And authors hate recompilations :))

**Comment by kainino0x** [comment]
Sounds good.
