### ISSUE TITLE
The spec is no longer available

### ISSUE THREAD

**Issue by caxieyou** [gpuweb/gpuweb#333]
Seems like the https://gpuweb.github.io/ is no longer working,
The spec is not available too.
Sorry if it's not the right place to mention this

**Comment by Kangz** [comment]
This is definitely the right place, sorry for the breakage. @beaufortfrancois just nuked it to set up continuous deployment of the spec. It should be back shortly, in the meantime can you look at the source for it https://github.com/gpuweb/gpuweb/blob/master/spec/index.bs

**Comment by beaufortfrancois** [comment]
It should be back now. Sorry for the disruption.

**Comment by beaufortfrancois** [comment]
Here it is: https://gpuweb.github.io/gpuweb/spec/index.html

**Comment by caxieyou** [comment]
thanks a lot 
https://github.com/gpuweb/gpuweb/blob/master/spec/index.bs 
this could work.
