### ISSUE TITLE
Geometry Shader

### ISSUE THREAD

**Issue by rolivo** [gpuweb/gpuweb#338]
Hello, sorry for my ignorance, and my bad English, I wonder if they are going to give support to the geometry shaders in webgpu?

**Comment by litherum** [comment]
WebGPU tries to run on Metal on macOS and iOS. Metal doesn’t support geometry shaders. Trying to emulate geometry shaders without native support is likely too difficult or impossible. I don’t think we can support geometry shaders.

**Comment by magcius** [comment]
Geometry shaders have large performance pitfalls [0] and their use is not recommended by most GPU vendors [1]

[0] http://www.joshbarczak.com/blog/?p=667
[1] As is somewhat snarkily pointed out by the "ARM® Mali™ Application Developer Best Practices Deveoper Guide": https://static.docs.arm.com/100019/0100/arm_mali_application_developer_best_practices_developer_guide_100019_0100_00_en2.pdf#page=19

**Comment by rolivo** [comment]
Ok, I can understand, thank you very much for the clarification, it's just that there is a lot of use cases for the use of Geometry Shaders

**Comment by kainino0x** [comment]
You should be able to use compute shaders to accomplish the same things. (And some things, like quad sprites, can be done with instanced drawing.)
