### ISSUE TITLE
Clarify valid address spaces for runtime-sized arrays

### ISSUE THREAD

**Issue by apbodnar** [gpuweb/gpuweb#3383]
In the example given by https://gpuweb.github.io/gpuweb/wgsl/#array-layout-examples there's a uniform buffer being declared with a runtime-sized array.  AFAIK this is not correct. (Inferred by `arrayLength` only accepting pointers to `storage` address spaces.)

**Comment by dneto0** [comment]
Right, that last case should use `var<storage>`
