### ISSUE TITLE
preview-pull-request doesn't pick up new diagrams

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3386]
For security reasons, the preview-pull-request action runs based on the *main* branch of the repo, and pulls in only specific files from the PR branch:
https://github.com/gpuweb/gpuweb/blob/ddf2e90f2922af4edca2a5a72c11ffa56cc03986/.github/workflows/preview-pull-request.yml#L34-L37

We need this to also pull in new diagrams (`{spec,wgsl}/img/*`). But in order to do this we need to know which filenames to pull, since we can't pull a whole directory. Likely we need to get the list of changed img files from the PR branch and pull those in.

I'm thinking if we can get the URL of the remote of the source of the PR, we can use `git` instead of `wget` to checkout those files and then we can just have git check out the whole img/ directory.

**Comment by mehmetoguzderin** [comment]
Pointed out here https://github.com/gpuweb/gpuweb/pull/3379#discussion_r957504965 (inside review) too.

@kainino0x BTW is it possible for the diagrams to eventually become too big to bundle as svg images? I wonder if some tooling comes in to produce diagram per code sample would something that runs on page to generate the diagrams would be better for longevity of repositories, as diagrams run around 25 kilobytes.

**Comment by dj2** [comment]
Is the concern transfer time for the images or the total repo size? If you generate the images on the fly you'll also have the transfer size of the generation JS along with the textual diagrams.

**Comment by mehmetoguzderin** [comment]
@dj2 Not transfer time, rather bloating of the repo size eventually. I am not sure if we do it that would be acceptable but just CDNing mermaid to generate at client could be a lightweight solution.

**Comment by dj2** [comment]
It would take a _lot_ of diagrams to bloat the repo size I think. I don't think it's worth the extra complexity.

**Comment by mehmetoguzderin** [comment]
@dj2 Number of examples will probably reach or exceed 100, 100*2*25 (two auto generated small diagrams) kilobytes would mean 5 megabytes per PR we host.

**Comment by mehmetoguzderin** [comment]
(just as a small note I am not bringing this for any immediate action- the proposed PR does a good job of displaying diagrams in development)

**Comment by dj2** [comment]
I don't think adding 5meg is a lot for the repo size.

**Comment by mehmetoguzderin** [comment]
@dj2 I am intending to mention PR Previews repository, which will have 1GB max repo size quota to be Pages servable.

**Comment by kainino0x** [comment]
@mehmetoguzderin as long as we have a way to delete old previews, that seems fine to me. I don't really think we'll need more than 1GB of previews live at any given time. I also don't think we will end up with quite that many diagrams. Not to mention SVGs are compressible, and Git might even be able to deduplicate identical files. (The CTS has larger files in it that might cause somewhat more trouble, I'm not sure.)

If GitHub Pages supports symlinks then we could also replace all of the img/* files with symlinks to a content-addressed directory to deduplicate them. Like

- preview123/
  - `img/buffer-map-failure.mmd.svg` symlink to `../content/ab068f54e9d9678c216ec19ad7dcbd05a08302e8`
- preview124/
  - `img/buffer-map-failure.mmd.svg` symlink to `../content/ab068f54e9d9678c216ec19ad7dcbd05a08302e8`
- content/
  - `ab068f54e9d9678c216ec19ad7dcbd05a08302e8` the svg file, named with the sha1sum of its contents

**Comment by kainino0x** [comment]
Even the index.html files could be content-addressed, as most PRs only change one of them so there would be a lot of duplication between them.

**Comment by mehmetoguzderin** [comment]
@kainino0x New PR preview system only deploys PRs latest state (and updates comment to reflect so), so we will no longer store each commit on latest Pages. I think everything considered gpuweb previews will certainly approach a gigabyte sooner or later. (I'll try to build a system that load balances)
