### ISSUE TITLE
Definition of `hex_float_literal` seems incorrect

### ISSUE THREAD

**Issue by vincentisambart** [gpuweb/gpuweb#3389]
In the WGSL spec, `hex_float_literal` is defined as the following:
```
hex_float_literal :
| /0[xX][0-9a-fA-F]*\.[0-9a-fA-F]+([pP][+-]?[0-9]+[fh]?)?/
| /0[xX][0-9a-fA-F]+\.[0-9a-fA-F]*([pP][+-]?[0-9]+[fh]?)?/
| /0[xX][0-9a-fA-F]+[pP][+-]?[0-9]+[fh]?/
```

But that means that for example `0x0.0` is ok, but `0x0.0f` is not. It looks like to me that the `[fh]?` should be at the end:
```
hex_float_literal :
| /0[xX][0-9a-fA-F]*\.[0-9a-fA-F]+([pP][+-]?[0-9]+)?[fh]?/
| /0[xX][0-9a-fA-F]+\.[0-9a-fA-F]*([pP][+-]?[0-9]+)?[fh]?/
| /0[xX][0-9a-fA-F]+[pP][+-]?[0-9]+[fh]?/
```
It would be closer to the definition of `decimal_float_literal`.

**Comment by mehmetoguzderin** [comment]
@vincentisambart In the 0x0.0f case, the trailing character "f" has interpretation as a hex digit. Initially, the exponent was a mandatory component, and the non-exponent case (where ([pP][+-]?[0-9]+[fh]?)
 is lacking) is provided as an ergonomic convenience. Thank you.

@dneto0 @alan-baker might also want to comment.

**Comment by dneto0** [comment]
Yes, that's right.   0x0.0f is the number 15/256

**Comment by vincentisambart** [comment]
> In the 0x0.0f case, the trailing character "f" has interpretation as a hex digit.

I did not realize that 😅. That indeed makes sense. Sorry for the mistake.
