### ISSUE TITLE
wgsl: Clarify whether non-entry-point functions can take arguments with locations

### ISSUE THREAD

**Issue by nical** [gpuweb/gpuweb#3399]
Consider:

```rust
// Not an entry point, but takes an argument with a location.
fn foo(@location(1) bar: vec3<u32>) -> vec3<u32> {
    return bar;
}

@vertex
fn vs_main(
    @location(0) position: vec2<i32>,
) -> @builtin(position) vec4<f32> {
    var v = foo();

    // ...
}
```

Is this legal?

The current wording seem to imply it isn't allowed as https://gpuweb.github.io/gpuweb/wgsl/#shader-interface says "All formal parameters of the entry point. These denote the pipeline inputs." without mentioning non-entry point functions.

It wouldn't hurt to add some explicit wording in the spec about what to do in the case of non-entry point functions.

**Comment by dj2** [comment]
From https://gpuweb.github.io/gpuweb/wgsl/#attribute-location:

>Must only be applied to an entry point function parameter, entry point return type, or member of a structure type.

**Comment by dj2** [comment]
Note, that, I believe if it's applied to a `struct` and the struct is passed into the function that _is_ legal. You then ignore the `location`, @dneto0 can you please confirm?

**Comment by nical** [comment]
Ah thanks a lot, this was already as clear as it gets.
