### ISSUE TITLE
SPIR-V sources of undefined behavior

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#34]
Another investigation on SPIR-V, this time on the sources of undefined behavior.

Skipped classes of UB
------------------------------

The parallel nature of GPUs make it so the result of running a shader can depend on invocation ordering, how data-races are resolved, etc when cross-invocation interactions happen. We can't really validate or paper over these UBs so they won't be addressed here. This also interacts with some compiler optimizations that for example reorder writes to memory: if the shader doesn't have the proper barriers there will be UB.

Other UBs are when a the shader reads or writes memory outside of the resources it was provided. These issues were already discussed in #33.

Also mathematical floating point precision UB won't be addressed here, and we think we should not address them at all as they depend on how the hardware performs computations. The CG should however specify bounds on the error allowed for floating point operations.

UBs in SPIR-V
-------------------

Overall the SPIR-V spec tries to be tight for valid shaders, up to spec bugs such as the `OpPhi` one @litherum pointed out. Sources of undefined behavior are called out in the spec and are the following:

 - `OpUndef` that can be evaluated to any bit pattern. We should forbid this for WebGPU.
 - Division by 0 and friends. We can either say it returns a fixed value like 0, or leave it as a UB as long as it doesn't break the security of WebGPU.
 - `OpVariable` without initializers. We should forbid this for WebGPU.
 - `OpVectorIndexDynamic` and `OpVectorInsertDynamic`, i.e. `float4 v; v[4]; v[4] = foo;`. We could provide "robust resource access"-like guarantees for this that access to invalid indices can either be removed or access any element.
 - `OpVectorShuffle` takes constant components, and allows for them to be FFFFFFFF which means the component is undefined. We should forbid this for WebGPU.
 - Shifts by more than the size of integer type produce undefined value. We could either keep this if it doesn't break the security of WebGPU or for example AND the shift with a mask.
 - `OpBitFieldInsert`, `OpBitFieldSExtract` and `OpBitFieldUExtract` when the range of bits set / extracted is out of bounds. We could either keep this if it doesn't break the security of WebGPU, or for example return 0 for invalid out of bounds.
 - Any operation using derivatives outside uniform control flow. It is impossible to know statically when control-flow will be uniform, and historically this UB hasn't been a problem for WebGL.

Other undefined behavior that won't affect WebGPU shaders:

 - `OpConstantSampler` with `None` sampler addressing mode and OOB access. `OpConstantSampler` isn't available in Vulkan and should not be exposed by WebGPU.
 - Geometry shader `OpEmitVertex` and `OpEmitStreamVertex` makes output variables undefined. We don't have geometry shaders in WebGPU because Metal doesn't have them.
 - `OpCaptureEventProfilingInfo` when called multiple times with the same event. This is a "big compute" functionality that won't be present in WebGPU.

UBs in extended instruction sets
-------------------------

Not all builtins are in the SPIR-V spec directly, and some are implemented in "extended instruction sets". The only one that's relevant is the [GLSL.std.450](https://www.khronos.org/registry/spir-v/specs/1.0/GLSL.std.450.html) that essentially adds more math builtins. There are more UB in there related to the argument space for math functions `acos(2 * Pi) = ?`. Also clamping operations are undefined if `max < min`.

**Comment by devshgraphicsprogramming** [comment]
nice findings

**Comment by Kangz** [comment]
Closing. The group decided more than a year ago to pursue the creation of WGSL. This investigation is no longer relevant.
