### ISSUE TITLE
Document behaviour when uniformity requirement can't be proven

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#340]
From https://github.com/gpuweb/gpuweb/issues/264#issuecomment-493193724

Robin has work-in-progress analysis of uniformity for WHLSL.

- Describe how to compute the same uniformity analysis in SPIR-V
- Describe that WebGPU implementation shall error out when presented with a shader that can't be proven to satisfy uniformity requirements.

**Comment by Kangz** [comment]
I think this can be close with #1571 soon landing.
