### ISSUE TITLE
Definition of length(x) is too restrictive for x being a scalar

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#3407]
Currently the WGSL spec says:
```
length(e) returns the length of e.
Evaluates to abs(e) if T is scalar or AbstractFloat.
Evaluates to sqrt(e[0]2 + e[1]2 + ...) if T is a vector type.
```

`abs(e)` has pretty tight accuracy requirements, specifically correctly rounded.

From the SPIR-V spec:
```
Result is the length of vector x, i.e., sqrt(x[0]^2 + x[1]^2 + …​).

The operand x must be a scalar or vector whose component type is floating-point.
```
with no mention of degenerating to `abs(x)` in the scalar case

`sqrt(x^2)` or `sqrt(x*x)` is going to have a minimum possible of accuracy restriction of 2ULP or higher due to the use of sqrt. Additionally, performing `x^2` or `x*x` is going to push the intermediate calculation out of bounds or to zero near the edges of positive and negative numbers, so allows 0 and +/- infinity as results for a significant number of cases that `abs(x)` doesn't.

That all being said, I have written the CTS tests, in a PR https://github.com/gpuweb/cts/pull/1815, to conform to the spec as written. And on SwiftShader they are failing for the scalar cases near the extremes of f32.

I am pretty sure this means that WGSL will need to change its accuracy for the scalars to be something like `sqrt(x*x)` or even worse, `sqrt(pow(x, 2))`.

**Comment by dneto0** [comment]
The table at https://gpuweb.github.io/gpuweb/wgsl/#floating-point-accuracy says the accuracy of length is inherited from Inherited from sqrt(dot(x, x))  
But dot only works on vectors. The entry should explain the scalar case as inherited from sqrt(x*x)

But the definition of length is misleading by using WGSL code to describe the function in terms of WGSL code.
Will say it in words, and add a note about possible implementation of the scalar case.

**Comment by munrocket** [comment]
I am not understand why we have scalar length at all.
abs(x) has better accuracy and performance than sqrt(x*x).
Maybe we can remove it?
