### ISSUE TITLE
WGSL spec gives readers the runaround regarding `var` access modes

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#3419]
The explanation of "`var` Declarations" says:

> The [access mode](https://gpuweb.github.io/gpuweb/wgsl/#access-mode) always has a default value, and except for variables in the [storage](https://gpuweb.github.io/gpuweb/wgsl/#address-spaces-storage) address space, [must not](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) be specified in the WGSL source. See [§ 5.4.2 Access Mode Defaults](https://gpuweb.github.io/gpuweb/wgsl/#access-mode-defaults).

But then [§ 5.4.2 Access Mode Defaults](https://gpuweb.github.io/gpuweb/wgsl/#access-mode-defaults) says:

> Each other address space supports only one access mode, as described in the [address space](https://gpuweb.github.io/gpuweb/wgsl/#address-space-table) table.

However, the [address space table](https://gpuweb.github.io/gpuweb/wgsl/#address-space-table) has nothing to say about access modes. In fact, the introductory paragraph says:

> See [§ 6 Variable and Value Declarations](https://gpuweb.github.io/gpuweb/wgsl/#var-and-value) for more details.

which is where we started.

**Comment by alan-baker** [comment]
This happened when I rewrote Variable and Value Declarations. I pulled the access mode from the address space table since it was now incorporated into the declaration table (as mutability). I'll fix this.
