### ISSUE TITLE
Clarification needed with regards to flushing denorm f16 values

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#3421]
In the spec it is stated:
```
Implementations may flush denormalized value ...
```

So for an operation that is doing f16->f16, if the number becomes a denorm f16 it may become zero, similar to how f32 operates.

For the builtin `quantizeToF16`, which does f32->f32, but restricts the outputs to the f16 values, what happens if a denorm f16 is returned, but is a norm for f32?

Can it be FTZ because it is being quantized to f16? or cannot because the operation is f32?

**Comment by litherum** [comment]
We think this operation should get the same behavior as f16 operations. If f16 denormals reliably flush to 0, then `quantizeToF16()` should too, and vice-versa. If f16 denormals unreliably flush to 0, then it's okay for `quantizeToF16()` to unreliably flush to 0 too.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-09-13-minutes#clarification-needed-with-regards-to-flushing-denorm-f16-value-3421">WGSL 2022-09-13 Minutes</a></summary>

* DN: There’s a gap in the f32->f16 case, it’s not clear if it should permitted to flush. We think it should be permitted to flush though just like e.g. f32->f32.  Applies to both pack function and quantizeToF16.
* MM: On devices we target for webgpu, does the hardware tell us if we will flush, or is this operation by operation
* DN: Op by op. Most cases you’ll probably see it, a la fastmath. It’s never tested by “I have a global flag and will always flush (or not)”. 
* **Resolved: Flush in builtins**

</details>
