### ISSUE TITLE
GPURenderBundleEncoder.setPipeline() not implementable on MTLIndirectCommandBuffer

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#3423]
The spec says:

```
GPURenderBundleEncoder includes GPURenderCommandsMixin;
...
interface mixin GPURenderCommandsMixin {
    undefined setPipeline(GPURenderPipeline pipeline);
    ...
}
...
dictionary GPURenderPipelineDescriptor : GPUPipelineDescriptorBase {
    ...
    GPUDepthStencilState depthStencil;
    ...
}
...
dictionary GPUDepthStencilState {
    ...
    GPUCompareFunction depthCompare = "always";
    ...
};
```

So it needs to be possible to set new render pipelines, with new depth compare functions, in the bundle.

However, Metal has separate RenderPipelineState and DepthStencilState objects:
```
protocol MTLIndirectRenderCommand {
    ...
    func setRenderPipelineState(MTLRenderPipelineState)
    /* no setDepthStencilState() */
    ...
}
...
class MTLDepthStencilDescriptor : NSObject {
    ...
    var depthCompareFunction: MTLCompareFunction
    ...
}
```

It's not possible to set a MTLDepthStencilState in a MTLIndirectRenderCommand.

Historically, this group has been designing `GPURenderBundleEncoder` to be implementable on top of `MTLIndirectCommandBuffer`.

**Comment by Kangz** [comment]
Note that this is also a problem for `depthWriteEnabled` and a whole lot of stencil state. Looking at the [asahi Gallium driver](https://github.com/Mesa3D/mesa/blob/e1f032acc3630bb179db12007cb628b855f546bb/src/gallium/drivers/asahi/agx_state.c#L216) it seems that this state is all in a hardware packet so it seems like it could be supported, but I can't tell if there are other constraints coming in from indirect buffers.

There seems to be two solutions there:

 1. Split the `MTLIndirectBuffer` along each change of `MTLDepthStencilState` (compared by value), such that developers don't have to worry about it. It seems that most workloads would use the same depth stencil state for many objects, so there's still a lot of usefulness from render bundles in implementations.
 2. Validate that all pipelines in render bundles have the same depth stencil state. Developers have to split on changes.

Solution 1) seems much more convenient for developers and quick to do in implementations (depth stencil states are interned and need only a pointer compare, where in JS it is much harder) while not pessimizing performance of what `MTLIndirectBuffer` can give for render bundles (a split needs to happen anyway).

**Comment by litherum** [comment]
Resolved: Split the `MTLIndirectCommandBuffer`s at depth-stencil-state boundaries (so they become `Vector<MTLIndirectCommandBuffer, MTLDepthStencilState>`)
