### ISSUE TITLE
Difference between `src-alpha` and `src-alpha-saturated` 

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#3432]
In the spec both `src-alpha` and `src-alpha-saturated` are listed as `(Asrc, Asrc, Asrc, Asrc)`. If the values end up being the same, what is the difference between the two?

**Comment by kainino0x** [comment]
Sounds like an error, it should be described differently. Vulkan describes it:

> (f,f,f); f = min(A<sub>s0</sub>,1-A<sub>d</sub>)
