### ISSUE TITLE
Inconsistencies in createBuffer validation

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3453]
Reported here: https://matrix.to/#/!MFogdGJfnZLrDmgkBN:matrix.org/$vOdIuydU7uXAXBPF88oEEgN8B00xVGJTe4RPvYUmTwk

> Some of the conditions listed in this section <https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpubufferdescriptor> seem to be redundant with the valid usage section for `createBuffer`. And the requirements around MAP_* buffer usages differ in a way that suggests the former section is outdated wrt that. Does this seem like something I should open an issue for?

**Comment by Imberflur** [comment]
I will try to expand on what I mentioned there.

Under `createBuffer` there is this [valid usage section](https://github.com/gpuweb/gpuweb/blob/37ec71c7816dcb57fb723c2547e485b022de609b/spec/index.bs#L3189):
![image](https://user-images.githubusercontent.com/2002109/190869375-cad2fac9-f7d4-406d-b389-685428718176.png)

Part of this links to another section on [validating the GPUBUfferDescriptor](https://github.com/gpuweb/gpuweb/blob/main/spec/index.bs#L3057):
![image](https://user-images.githubusercontent.com/2002109/190869480-3428fb34-241b-4b9a-bbc8-208abfd184ec.png)

First, I want to note the first two points in `validating GPUBufferDescriptor`  are duplicated with conditions already listed under `createBuffer` (I assume "_this_ is valid" means that the device isn't lost).

The third point is a much weaker form of the usage requirements listed directly under `createBuffer` which (along with looking at the git history) implies to me that it may be outdated.

The final fourth condition seems to be the only one that adds a novel requirement.

Afaict `validating GPUBufferDescriptor` is only referred to from from the valid usage section of `createBuffer`. One question this raises in my mind is whether there is any purpose for having this as a separate section (e.g. will GPUBufferDescriptor potentially be used elsewhere?).
