### ISSUE TITLE
wgsl: somehow we lost arithmetic right shift

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3461]
https://github.com/gpuweb/gpuweb/pull/772/files#diff-709b5c343d59ae10cbabe69f9df1eee9e2dbb6e9d848632fa94357083d6e0a34R1781  was there
But now it's gone.  Now we say right shift always inserts zero bits.

I think this got lost in the rewriting of various tables.

**Comment by dneto0** [comment]
cc: @amaiorano

**Comment by dneto0** [comment]
#1730 still had arithmetic shift right.
So did #1874

**Comment by dneto0** [comment]
#2713 still had it.

**Comment by dneto0** [comment]
It's definitely lost in #2989 
But even prior to #2989 it had the constraint reversed, where unsigned LHS and signed LHS are reversed.

**Comment by dneto0** [comment]
#2668 introduced the confusion between unsigned LHS and signed LHS being backward. That was about adding creation -time expressions.

I'm convinced this was lost by accident. It needs fixing.

**Comment by kdashg** [comment]
What! Hahaha

**Comment by dneto0** [comment]
> What! Hahaha

Implementation is the sincerest form of scrutiny.    So, thanks to @amaiorano for throwing some good puzzlement my way.
