### ISSUE TITLE
Clarify intended behaviour when packing out of range values

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#3470]
For packing builtins like `pack2x16float` there is a down conversion of the inputs into their packed form.

The spec discusses what should happen when a singular value is being converted, but cannot fit into the space it is going to, i.e. converting a very large f32 to f16 causes an infinite value, which if infinities are not supported becomes an undefined value.

The spec does not explicitly call out for the packing builtins what should happen if only some, but not all of the inputs cannot be quantized.
i.e. pack2x16float(v), where v[0] is representable as a f16, but v[1] is too large for a  f16.

Is the result just an undefined u32? or is the result supposed to be a u32 with the v[0] half bits set to the correct bit field and the v[1] bits being undefined?

**Comment by zoddicus** [comment]
Talked with @dneto0 about this offline, and I think the expectation would be to do the quantization/pack component-wise. If one of the inputs is out of bounds those bits will be undefined for CTS expectation. There is a note for quantizeToF16 that helps clarifies this:
```
Note: The vec2<f32> case is the same as unpack2x16float(pack2x16float(e)).
```

**Comment by dneto0** [comment]
We'll go with that assumption and see if it shakes out in CTS.

But I'll keep this open for an editorial update to make this component-wise aspect clearer.
