### ISSUE TITLE
`textureSampleBaseClampToEdge` clamping should clamp a half-texel from edge

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3471]
[The spec for `textureSampleBaseClampToEdge` currently states](https://www.w3.org/TR/WGSL/#textureSampleBaseClampToEdge):

> Samples a texture view at its base level, with texture coordinates clamped to the `[0, 1]` range.

If the provided sampler has texture wrapping enabled, then sampling at the edges of the texture will wrap, which seems wrong. I believe this should be something like:

> Samples a texture view at its base level, with texture coordinates clamped to the range `[half_texel, 1 - half_texel]`, where `half_texel = vec2(0.5) / vec2<f32>(textureDimensions(t))`.

But perhaps worded in a better way.

**Comment by dneto0** [comment]
cc: @kainino0x

**Comment by dneto0** [comment]
That sounds reasonable to me, but I want confirmation from folks from the API side (whoever drove to resolution on #2766)

**Comment by kainino0x** [comment]
This is correct, I just forgot about that detail when I wrote the spec PR.

**Comment by dneto0** [comment]
I just wanted to check:  The clamp-to-edge definition in the API spec says coordinates are clamped to [0, 1].
That's slightly inconsistent but correct in context, I presume.
And the reason is the sampler mode in that case is handled by the hardware, which "does the right thing".
