### ISSUE TITLE
Sampler address modes

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#348]
## Vulkan:
```cpp
typedef enum VkSamplerAddressMode {
    VK_SAMPLER_ADDRESS_MODE_REPEAT = 0,
    VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT = 1,
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE = 2,
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER = 3,
    VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE = 4,
    VK_SAMPLER_ADDRESS_MODE_MAX_ENUM = 0x7FFFFFFF
} VkSamplerAddressMode;
```
Default is `REPEAT` (since the only thing to default-initialize in C is with zeroes).

## D3D12:
```cpp
typedef enum D3D12_TEXTURE_ADDRESS_MODE {
  D3D12_TEXTURE_ADDRESS_MODE_WRAP,
  D3D12_TEXTURE_ADDRESS_MODE_MIRROR,
  D3D12_TEXTURE_ADDRESS_MODE_CLAMP,
  D3D12_TEXTURE_ADDRESS_MODE_BORDER,
  D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE
} ;

CD3DX12_STATIC_SAMPLER_DESC
(opt) D3D12_TEXTURE_ADDRESS_MODE addressU = D3D12_TEXTURE_ADDRESS_MODE_WRAP
(opt) D3D12_TEXTURE_ADDRESS_MODE addressV = D3D12_TEXTURE_ADDRESS_MODE_WRAP
(opt) D3D12_TEXTURE_ADDRESS_MODE addressW =D3D12_TEXTURE_ADDRESS_MODE_WRAP
```
Default is `WRAP` (or "repeat" on our side).

## Metal:
> The default value is MTLSamplerAddressMode.clampToEdge.

---
If we are to seek consensus with the native APIs, it doesn't appear to be close to what we [currently have](https://github.com/gpuweb/gpuweb/blob/37e0cfb58da9b6bb639cefcfe6d477cf595f2c58/spec/index.bs#L268).

**Comment by Kangz** [comment]
Thanks for the investigation, the current default matches at least one API :) For defaults I'm not sure if we really need to find consensus with native APIs because they are just defaults and don't affect the implementability or performance of WebGPU on native APIs.

**Comment by kvark** [comment]
> For defaults I'm not sure if we really need to find consensus with native APIs

For defaults, I'm not sure if we really need to force them where it's not obvious. Any disagreement with native APIs makes them less obvious.

As I stated earlier, I see the movement of "API defaultization" to not be strongly aligned with the initial goals WebGPU. Ergonomics of the API should not take priority over clarity.

For address modes, there is a way to improve ergonomics without defaulting all the values: allow specifying one address mode to be used for all U/V/W, e.g.
```
required (GPUAddressMode or sequence<GPUAddressMode>) addressMode;
```

**Comment by magcius** [comment]
In this case, the wrong choice of addressing mode is a visual error, making
it easy to adapt when it goes wrong. There is no performance penalty. So I
think a default has better ergonomics than the sequence-or-constant.

**Comment by Kangz** [comment]
@kvark I think we discussed this a while ago and decided on the defaults that are in the current spec. Can you close if no further work needs to be done?
