### ISSUE TITLE
Validating maxComputeWorkgroupStorageSize

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3485]
In order to validate maxComputeWorkgroupStorageSize, we need to compute the amount of workgroup storage used by a

Naively, we could just add up the `SizeOf` all of the `workgroup`-space variables statically used by the entry point.
But in practice, I assume there will be padding between these, for alignment. How do we handle this? I don't think we control the way they are packed at all. Should we, for example, round the size of each variable up to a multiple of 32 (similar to [minUniformBufferOffsetAlignment](https://gpuweb.github.io/gpuweb/#dom-supported-limits-minuniformbufferoffsetalignment)) before summing?

cc @dneto0 @alan-baker

**Comment by Kangz** [comment]
TBH I don't think we would need to round to a full `vec4<f64>` because compute shaders all use scalar registers AFAIK. But maybe rounding to `f32` or `f64` would make sense? That said Vulkan says:

> maxComputeSharedMemorySize is the maximum total storage size, in bytes, available for variables declared with the Workgroup storage class in shader modules (or with the shared storage qualifier in GLSL) in the compute shader stage. The amount of storage consumed by the variables declared with the Workgroup storage class is implementation-dependent. However, the amount of storage consumed may not exceed the largest block size that would be obtained if all active variables declared with Workgroup storage class were assigned offsets in an arbitrary order by successively taking the smallest valid offset according to the [Standard Storage Buffer Layout](https://registry.khronos.org/vulkan/specs/1.3/html/vkspec.html#interfaces-resources-standard-layout) rules, and with Boolean values considered as 32-bit integer values for the purpose of this calculation. (This is equivalent to using the GLSL std430 layout rules.)

Which means that the layout rules for UBOs give us an alignment to 16 bytes.  WGSL folks WDYT? (@mehmetoguzderin as well)

**Comment by dneto0** [comment]
> Which means that the layout rules for UBOs give us an alignment to 16 bytes. WGSL folks WDYT? 

Yes, that's what that text implies.  So rounding up the size of each 

I recall a case from a private discussion where things could go awry. I  bet @alan-baker remembers, and I'd like him to comment.
But I think the case is unlikely to be triggered on a device that WebGPU will target.  And if it does we can sweep it into the "uncategorized error".

**Comment by dneto0** [comment]
Discussed in the 2022-10-11 WGSL meeting.   
It's ok to round up each variable size to 16, then add them together.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-10-11-minutes#validating-maxcomputeworkgroupstoragesize-3485">WGSL 2022-10-11 Minutes</a></summary>

* DN: way of counting up sizes of workgroup size and saying if beyond we'll fail pipeline compile. Round up size of each var to 16 bytes. There was one case I thought about that had to check for. Think we can ignore those cases (or lump into uncategorized error). Think proposed change is reasonable.
* MM: There is a packing algorithm in Metal, it isn't controllable by author, get packing you get. In metal compile shader, after compile ask how much space used. Thought, probably not worth that kind of dance, willing to lean on the uncategorized error. As long as webgpu counting has low false positive rate then we're ok in rate situation where packing is slightly off and we can't compile to say uncategorized error. As long as it's rare.
* AB: Think uncategorized is good, not going to do any better.
* MM: So rounding up variables to 4 bytes is pessimistic enough and would be fine.
* KG: Proposal is make this change and we can uncategorized error when we need too
* DN: On table is round up to 16 bytes
* MM: Even better. If authors complain …
* KG: **Make it so**.

</details>
