### ISSUE TITLE
Global Sync

### ISSUE THREAD

**Issue by m-schuetz** [gpuweb/gpuweb#3486]
CUDA has an incredibly useful [global sync](https://stackoverflow.com/a/6405432/913630) feature that that makes it trivial to implement (vertical) kernel fusion. With kernel fusion, one can merge multiple successive kernels and dispatches into a single big kernel with a single dispatch. One particular advantage of this method is that this allows developers to live-code complex multi-pass kernels at runtime - even adding or removing kernel stages - without the need to adjust the corresponding dispatches in Javascript/Rust/C++, and therefore without having to recompile the entire application. 

```C++
// A single fused CUDA kernel that comprises three different kernel calls with a global sync between each kernel.

auto grid = cooperative_groups::this_grid();

kernel_1();
grid.sync();
kernel_2();
grid.sync();
kernel_3();
```

Is there a chance that something like this could make it into WGSL after 1.0? GLSL doesn't have a native global sync as far as I'm aware, and I guess HLSL and MLS don't have it either, so it would probably need to be implemented via a spinlock and atomicAdds to a global thread counter/semaphore. 

I could see this being a valuable feature for shadertoy-like applications for compute. Many compute applications need multiple kernels, but adding and removing kernels would otherwise be fairly cumbersome.

**Comment by litherum** [comment]
> spinlock and atomicAdds

This does not guarantee progress, and is likely to not work in practice.

This feature is unimplementable on MSL (and AIUI on DXL/HLSL and SPIR-V).

**Comment by m-schuetz** [comment]
> This does not guarantee progress

At least in CUDA, custom spinlock implementations of a global sync can guarantee progress by only spawning as many workgroups/subgroups as the GPU can process in parallel, so that workgroups don't wait forever for workgroups that never stop spinning. Is this impossible on MSL? (Curious about it, even though I guess global sync has no chance to land in WebGPU)

**Comment by Kangz** [comment]
This feature seems to only exist in CUDA, and since it can synchronize over the whole arbitrarily sized grid, then there must be some spilling that can happen, so it looks like a coroutine feature on the GPU ??? But in all cases this doesn't exist in any of the APIs that WebGPU target and I don't think that we can implement it anytime soon (or ever??)

**Comment by m-schuetz** [comment]
After a discussion with a more knowledgeable colleague, I'll close this since it really is unlikely that this would work robustly on all the hardware that WebGPU intends to target.
