### ISSUE TITLE
Unclear whether GPUExternalTexture is 1D, 2D or 3D

### ISSUE THREAD

**Issue by i509VCB** [gpuweb/gpuweb#3487]
Hello, regarding the section defining `GPUExternalTexture`, it is not clear what type of texture is created (whether it's 1D, 2D, 3D).

**Comment by Kangz** [comment]
It is 2D, this can be guessed by looking at the builtins used to sample the texture that take a 2D UV coordinate. Adding wgsl + editorial for WGSL editors to see if any clarification is needed in the spec.

**Comment by kainino0x** [comment]
The WGSL spec is clear, only the API spec needs a clarification.
> texture_external is an opaque 2d float-sampled texture type similar to texture_2d<f32> but potentially with a different representation.
