### ISSUE TITLE
wgsl: Flat interpolants are uniform across fragments in a fragment shader invocation group

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3489]
From internal Google feedback, it seems we're missing a uniformity condition.

'Flat' interpolants are uniform within a fragment shader invocation group. All invocations in a fragment shader invocation group are given the value provided by the provoking vertex.

Vulkan spells it out:
https://registry.khronos.org/vulkan/specs/1.1/html/chap9.html#shaders-scope-primitive  :

> Any fragment shader invocations executed as the result of rasterization of a single primitive form a primitive scope instance.

...
> Any input variables decorated with Flat are uniform within a primitive scope instance.

**Comment by alan-baker** [comment]
Vulkan defines the SPIR-V invocation group as the command scope if the execution model does not define a workgroup (see [command scope](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#shaders-scope-command)). Primitive scope is a subset of command scope so I don't think we can claim flat inputs are uniform.
