### ISSUE TITLE
Flush-to-zero denormal behavior

### ISSUE THREAD

**Issue by programmerjake** [gpuweb/gpuweb#349]
I noticed that in the description for [Secure HLSL](https://github.com/gpuweb/gpuweb/wiki/Secure-HLSL-Explainer#standard-library), it requires flush-to-zero. I think requiring flush-to-zero may be problematic since some processors don't support flush-to-zero mode for floating-point operations. RISC-V in particular doesn't support flush-to-zero in the standard F and D floating-point arithmetic extensions. We ([libre-riscv.org](https://libre-riscv.org/)) are currently designing an open-source RISC-V based GPU and weren't planning on supporting flush-to-zero mode, though, since it's still in the design stages, support could be added, though it would be nice to not need to. Note that none of Vulkan, OpenGL, or OpenGL ES (and probably other graphics APIs) require support for flush-to-zero mode.

**Comment by programmerjake** [comment]
See also: http://bugs.libre-riscv.org/show_bug.cgi?id=100

**Comment by Kangz** [comment]
WGSL doesn't require flush-to-zero:

> Implementations may flush denormalized value on the input and/or output of any operation listed in § 12.5.1 Floating Point Accuracy.

I think it resolves this concern.
