### ISSUE TITLE
Make WGSL more suitable for minification

### ISSUE THREAD

**Issue by munrocket** [gpuweb/gpuweb#3503]
There is some culture for shader minification, some people even write shaders in [twits](https://twitter.com/hashtag/%E3%81%A4%E3%81%B6%E3%82%84%E3%81%8DGLSL?src=hashtag_click).
We can take one example for analysis: https://twitter.com/gaziya5/status/1365834701215203329

<details>
<summary>GLSL->WGSL example</summary>

GLSL before porting (267 chars)
```ts
float i,g,R,e=1.;vec3 p;for(;e>.001&&i++<1e2;g+=e=.7*length(p-clamp(p,-.4,.4))*R-
snoise3D(p*5.)*.005)p=vec3((FC.xy-.5*r)/r.y*g+.2*sin(t),g-3.),p.yz*=rotate2D(4.),
R=length(p.xy),p.y=atan(p.y,p.x),p.x=log(R)-p.y/3.,p.xy=fract(p.xy*3./PI-t*.3)-.5,
p.z/=R;o+=15.*p.z/i;
```

WGSL after porting (386 chars, +44%)
```ts
var i:f32;var g:f32;var R:f32;var e=1.;var p:v3f;for(;e>.001&&i<1e2;g+=e){i+=1.;p=
v3f((FC.xy- .5*r)/r.y*g+v2f(.2*sin(t)),g- 3.);let q=rotate2D(4.);p=v3f(p.x,dot(p.yz,
q[0]),dot(p.yz,q[1]));R=length(p.xy);p.y=atan2(p.y,p.x);p.x=log(R)-p.y/3.;let w=fract(
p.xy*3./PI-t*.3)-v2f(.5);p.x=w.x;p.y=w.y;p.z/=R;o+=v4f(15.*p.z/i);e=.7*length(p-
clamp(p,v3f(-.4),v3f(.4)))*R-snoise3D(p*5.)*.005;}
```

WGSL with proposed fixes 1+2+8 (303 chars, +13%)
```ts
var i,g,R,e:f32,p:v3f;e=1.;for(;e>.001&&i<1e2;g+=e){i+=1.;p=v3f((FC.xy-.5*r)
/r.y*g+v2f(.2*sin(t)),g-3.);p.yz*=rotate2D(4.);R=length(p.xy);p.y=atan2(p.y,p.x);p.x
=log(R)-p.y/3.;p.xy=fract(p.xy*3./PI-t*.3)-v2f(.5);p.z/=R;o+=v4f(15.*p.z/i);e=.7*
length(p-clamp(p,v3f(-.4),v3f(.4)))*R-snoise3D(p*5.)*.005;}
```

WGSL check with 1+2+3+8 fix (278 chars, +4%)
```ts
var i,g,R,e:f32,p:v3f;e=1.;for(;e>.001&&i<1e2;g+=e){i+=1.;p=v3f((FC.xy-.5*r)
/r.y*g+.2*sin(t),g-3.);p.yz*=rotate2D(4.);R=length(p.xy);p.y=atan2(p.y,p.x);p.x
=log(R)-p.y/3.;p.xy=fract(p.xy*3./PI-t*.3)-.5;p.z/=R;o+=15.*p.z/i;e=.7*
length(p-clamp(p,-.4,.4))*R-snoise3D(p*5.)*.005;}
```
</details>

Here list of problems that I found:

1. Initialising a sequence with comma-separated values (#581)
```ts
//this gives an error
var a, b, c:vec2<f32>;

//correct syntax
var a:vec2<f32>;var b:vec2<f32>;var c: vec2<f32>;
```

2. Assignment of swizzled values (#737)
```ts
//this gives an error
p.yz*=rotate2D(t);

//omg, how to use it?
let r=rotate2D(t);p=vec4<f32>(p.x,dot(p.yz,r[0]),dot(p.yz,r[1]),p.z);
```

3. Implicit float -> vecN conversion
```ts
//this gives an error
let st=uv+.2*sin(t);

//correct syntax
let st=uv+vec2<f32>(.2*sin(t));
```

4. Overload for built-in functions (special case of 3. that produce more symbols)
```ts
//this gives an error
return clamp(c, 0., 1.);

//correct syntax
return clamp(c,vec4<f32>(0.),vec4<f32>(1.));
```

5. Pipeline of variables (this can reduce code more if name of variable is bigger)
```ts
//this gives an error
g+=e=.7*length(p);

//correct syntax
e=.7*length(p);g+=e;
```

6. operator++, braces for `if` and `for`, comma separator
```ts
//this gives an error
for(var i=0;i<10;i++)a=i,b=i*20,c=i*30;

//correct syntax
for(var i=0;i<10;i+=1){a=i;b=i*20;c=i*30;}
```

7. `vec3<f32>` is too hard to type (fixable!)
```ts
//glsl
#define vec3 v3f
v3f a=v3f(1.);

//wgsl
type v3f = vec3<f32>;
let a=v3f(1.);
```

8. Weird minus problem (A-5. fixed in spec but 5.-A is not?)
```ts
//this gives an error
p=b-vec3<f32>(1.,2.,3.);

//correct syntax
p=b- vec3<f32>(1.,2.,3.);
```

WGSL become much better since first text based proposal but looks like we should consider (1), (2) in v1 directly if we want to continue this culture. Note that this is real example, and kind of *sugar benchmark* of a language itself.

**Comment by mehmetoguzderin** [comment]
@munrocket I have a question. What is the ground truth validation for these "error" lines?

For example, item 8. is valid if you try it on the spec-generated playground through the steps below. This generated parser has been the common denominator for the understanding for good reasons, and we relied on this functionality for "celebrating" the elimination of ambiguities. At least, I do not see any error for A-5., 5.-A, and b-vec3<f32>(1.,2.,3.). Could you check?

Nevertheless, I think the motivation behind this issue is critical for V1. Not sure about the rest of the participants, but I'd suggest a more inclusive approach toward such voices.

Thank you!

Steps:

```
git clone https://github.com/gpuweb/gpuweb
cd gpuweb/wgsl
make
cd grammar
npx tree-sitter build-wasm --docker
npx tree-sitter playground
```

**Comment by munrocket** [comment]
Thanks, I will install tree-sitter. I just tried to port some more code and faced with this. It is also kind of guide how to port crypted shaders. Sorry that I mentioned problem that already fixed. The main topic is (1) and (2), especially (2).

Writing things like that is painful and cryptic for basic things like rotating a 3d vector. 
```ts
let r=rotate2D(t);p=vec4<f32>(p.x,dot(p.yz,r[0]),dot(p.yz,r[1]),p.z);
```

**Comment by mehmetoguzderin** [comment]
Thank you, I intend to expose better how this "commonly-agreed" utility "exists" here, which benefits the bottom line of spec-defining-implementations and community involvement with the following update to the CG charter. https://github.com/gpuweb/admin/pull/19

Side, a bit off: One way to shave 6 characters from the tweet would be to prefer "len" as the built-in akin to Rust and Python, maybe.

**Comment by munrocket** [comment]
Ok, proper solution for `operator*=` for swizzled values here:
```ts
//p.yz*=rotate2D(t);
let t=p.yz;t*=rotate2D(t);p.y=t.x;p.z=t.y;
```

**Comment by dj2** [comment]
Textual minification isn't a goal of WGSL. You can always gzip if you want to ship less bytes to the client.

**Comment by dneto0** [comment]
For 8:  I think you are using and outdated compiler.

This compiles in Tint:
```
const b=1.0;
const p=b-vec3<f32>(1.,2.,3.);

@fragment
fn main() -> @location(0) vec3<f32> {
  return p;
}
```

tint --format hlsl x.wgsl
```
struct tint_symbol {
  float3 value : SV_Target0;
};

float3 main_inner() {
  return float3(0.0f, -1.0f, -2.0f);
}

tint_symbol main() {
  const float3 inner_result = main_inner();
  tint_symbol wrapper_result = (tint_symbol)0;
  wrapper_result.value = inner_result;
  return wrapper_result;
}

```

**Comment by munrocket** [comment]
The goal is *achieving high performance across a broad range of devices*, but as we can see WGSL alredy added some sugar, for example `operator*=`. Any language want to be flexible and expressive, until it is not brainfuck. By analyzing edge cases, it is easier to understand what is better.

We can measure expressive power of each new WGSL feature, let’s introduce 2 metrics

```hs
C(feature) => limit[N -> inf, nameLen -> 0] (total chars of N repeated expressions) / N
L(feature) => limit[N -> inf, nameLen -> N] (total chars of N repeated expressions) / N
```
C metrics measure verbosity with infinitely small variable names.
L metrics measure verbosity with infinitely large variable names.

<details>
<summary>Comma-separated initialization</summary>

```ts
var name1:vec2<f32>;var name2:vec2<f32>;var name3: vec2<f32>;
var name1,name2,name3:vec2<f32>;
```
</details>

```hs
C(initialization before) = 4 + typelength (from 3 to 9)
C(initialization after) = 1
L(initialization before) = 1
L(initialization after) = 1
```

<details>
<summary>Assignment= of swizzled values</summary>

```ts
name1a.x=name1b.x;name1a.y=name1b.y;name1a.z=name1b.z;
name1a.xyz=name1b;
```
</details>

```hs
C(K swizzled= before) = 6K
C(K swizzled= after) = 3 + K
L(K swizzled= before) = 2K
L(K swizzled= after) = 2
```

<details>
<summary>Implicit float -> vecN conversion</summary>

```ts
name1+vecN<f32>(name2)
name1+name2
```
</details>

```hs
C(implicit float2vec conversion before) = 1 + typelength (from 3 to 9)
C(implicit float2vec conversion after) = 1
L(implicit float2vec conversion before) = 2
L(implicit float2vec conversion after) = 2
```

<details>
<summary>Pipeline of variables</summary>

```ts
name3=name4;name3=name2;name2=name1;
name1=name2=name3=name4;
```
</details>

```hs
C(pipeline of variables before) = 2
C(pipeline of variables after) = 1
L(pipeline of variables before) = 2
L(pipeline of variables after) = 1
```

<details>
<summary>Optional if braces</summary>

```ts
if(name1a){name1b;}
if(name1a)name1b;
```
</details>

```hs
C(optional if braces before) = 6
C(optional if braces after) = 4
L(optional if braces before) = 2
L(optional if braces after) = 2
```

<details>
<summary>Assignment*= of swizzled values</summary>

```ts
let temp1=name1a.xy*name1b;name1a.x=temp1.x;name1a.y=temp1.y;
name1a.xy*=name1b;
```
</details>

```hs
C(K swizzled*= before) = 8 + 7K
C(K swizzled*= after) = 4 + K
L(K swizzled*= before) = 3 + 2K
L(K swizzled*= after) = 2
```

<details>
<summary>Tuple return values</summary>

```ts
ta1=a1;tb1=b1;a1=ta1;b1=tb1;
(1a,1b)=(1b,1a);
```
</details>

```hs
C(K tuple return before) = 4K
C(K tuple return after) = 4 + 2K
L(K tuple return before) = 4K
L(K tuple return after) = 2K
```

Now we have "formal method" that can help to choose best feature in future WGSL language.

**Comment by dj2** [comment]
I don't understand how there is a connection between expressive power and number of characters typed. The things being expressed are still there it just takes a few more characters. If you're concerned about sending bytes to the browser, using gzip of the shader resources would be a much better way forward then trying to remove characters from WGSL.

**Comment by dneto0** [comment]
I recommend we move this to post-v1 milestone

**Comment by dneto0** [comment]
(2) is already post-v1

**Comment by munrocket** [comment]
This is not an issue, but a report. I think the guy who asked a question #3478 recently, asked right things. I started to see this more clearly when I tried to port minified shader from GLSL -> WGSL. Maybe you not tried it too, it's interesting exercise to understand how WGSL fits to them. I will close this issue tomorrow, if you ok with it.
