### ISSUE TITLE
Consider removing the loop statement

### ISSUE THREAD

**Issue by munrocket** [gpuweb/gpuweb#3504]
Looks like it become useless after introducing `for` and `while` statements. Infinite loops on GPU is meaningless? 🤔

**Comment by dj2** [comment]
Converting a SPIR-V program with a complex continuing block is very difficult without `loop`. You have to convert it to a function or, essentially, pretend you have `loop` with `while`.

The spec _defines_ `for` and `while` as syntactic sugar on top of a `loop`.
