### ISSUE TITLE
wgsl:  (1 << 2u) should be 4  (an abstract int)

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3511]
Feedback from @ben-clayton, a surprising thing about how shift works.

*  (1 << 2)       is abstract int 4.  Great
*  (1u << 2u)    is  4u.  Great
* (1 << 2u)    is 4u. Surprising. Expected abstract int 4.

This occurs because for shift operators, we split them into concrete vs. abstract overloads.
That makes sense for operators like add, subtract, multiply where the role of both operands are similar and in the same "domain" so to speak.

But for shifts the LHS and RHS play quite different roles. We already restrict the RHS to be non-negative (either by forcing u32 in the runtime case, or value checkin the const-expr override-expr cases)

It seems more natural to say that the result of X << Y has the same type as X.

This would be fixed by making one overload:

> e1: T
> e2: TS
> S is i32, u32, or AbstractInt
> T is S or vecN&lt;S&gt;
> TS is u32 when T is scalar, or vecN&lt;u32&gt; when T is vector.

>  Then e1 << e2 : T

Note that this requires the RHS to be concretized. Which is fine because it's the shift count, and anything beyond 63 is basically useless.
The one extra thing this newly disallows is something like 0 << 5000000000
Today, that would be 0.  But after the proposed change it causes a shader creation error because the RHS overflows during concretization down to u32.

**Comment by dneto0** [comment]
This change allows things like 5000000000 << 3u to compile since the LHS would overflow u32. This change keeps there result as an AbstractInt.

**Comment by ben-clayton** [comment]
Happy to see that this aligns with golang's behaviour.

To quote [the spec](https://go.dev/ref/spec#Operators):

> Except for shift operations, if one operand is an untyped constant and the other operand is not, the constant is implicitly converted to the type of the other operand.

> The right operand in a shift expression must have integer type or be an untyped constant representable by a value of type uint. If the left operand of a non-constant shift expression is an untyped constant, it is first implicitly converted to the type it would assume if the shift expression were replaced by its left operand alone.

The last sentence here is confusing, but I believe states that the end result of the shift is the same as the LHS. That matches the [observed behaviour of the compiler](https://go.dev/play/p/F5vcIYF0EVu).
