### ISSUE TITLE
Logo Proposal for gpuweb

### ISSUE THREAD

**Issue by memoryskull** [gpuweb/gpuweb#352]
Hi! @gpuweb

I'm interested in collaborating with this project by delivering a series of logotype options that fits this project for the best!

If interested let me know so we can get started!

Cheers!

**Comment by JonET** [comment]
Post a link to your portfolio.

**Comment by memoryskull** [comment]
Hi @JonET 
Could you give me information about your project?
I can submit a proposal without any commitment if it is to your liking I can add it to your repository

**Comment by Kangz** [comment]
Thank you for the proposal, but at this time we are not looking to source a logo for WebGPU.
