### ISSUE TITLE
Attribute syntax should not specialize to built-in language attributes

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#3520]
Attribute syntax should not specialize to built-in language attributes.

The inclusion of attributes within syntax creates unnecessary duplication and, furthermore, increases grammar footprint for no reason at all (similar to why people do not include function overloads inside grammar).

~~We are already at harm by this- the last consensus of attribute syntax DID allow trailing commas (in consistency with elsewhere), but the change to make them part of grammar did not preserve this- and did so silently.~~ (represents this syntax with a trailing additional rule- unnecessary convolution)

I consider this an editorial issue; the attribute overloads should be much better live in the table, and the context-dependent words listing can be just a plain list that enumerates.

**Comment by mehmetoguzderin** [comment]
Additionally, the way "attribute overloads" are inside grammar risks explosion in the future. What if named parameters become a thing? Is this section going to enumerate everything like:

```
`@` ??? `(` x `=` ???, y `=` ??? `)`
`@` ??? `(` y `=` ???, x `=` ??? `)`
```

Of course, an immediate (I would not say more but for "argument") practical risk is an extension introducing many attributes.

**Comment by dneto0** [comment]
There's a special case for `@diagnostic`: the second paramter is not an identifer that resolves to a declaration (user-defined or predeclared), and is allowed to be something the implementation doesn't know about.
In particular, it's not type-checked.

**Comment by mehmetoguzderin** [comment]
@dneto0 Can't we prose special-case the situation in attributes? Esp. attribute name and then arguments will be subject to more constraints by the respective attribute's definition (I always thought in this way, but maybe one day in future these restrictions will relax for a more generalized language experience but it is easier to keep strict now and ease later)

**Comment by dneto0** [comment]
Adding special cases in prose is error prone.  It's more things to think about.

**Comment by mehmetoguzderin** [comment]
@dneto0 Would it be more error prone than std function definitions to make it an implementation detail in prose (or tabular, IDK)? An implementation could choose to make it part of parser directly, or switch parser program depending on resolved name, or just defer the operation? This way, we'd safe the attribute syntax from specializing (= make it generalized) and rest would be up to an implementation to make the best trade-off for their design

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#3520-attribute-grammar--syntax">GPU Web F2F 2023-02-16/17</a></summary>

* OD: right now - attributes defined in a table. Syntax - no general definition. Simply specialize to every attribute in the table.
    * Likely to get more attributes in the future.
    * Prone to bloating syntax, and combinatorial explosion.
* OD: think we can generalize attribute definition. one of the last few places where spec syntax will have to change. Other - extension names, identifiers. Think we should remove them from the syntax - impl detail how these are handled. (are notes correct?)
* KG: suggesting removing attributes from the grammar?
* AB: having one general rule.
* AB: think this is OK to do, now that everything's an identifier. Was complex when things were context-dependent names.
* &lt;discussion>
* DN: 3 cases we didn't discuss before. Probably necessary to make this change.
* MM: is this a behavior change?
* EG: it's editorial.
* AB: not a behavior change.
* DN: except if they become identifiers, then you can shadow them.
* KG: does anyone not want to make them identifieers?
* JB: kind of nice to have them namespaced. Don't have to worry about interpolation styles interfering with variable names.
* KG: kind of a problem if we made "size" an identifier.
* KG: "size", "id" would be problems.
* AB: these can only be problematic if in structure declaration.
* MM: if we add push constants, adding a global called "size" will be relatively common.
* KG: what's that for?
* AB / MM: size of a member in a struct.
* JB: don't think this proposal will simplify the spec. Have to declare the rules somehow.
* DS: we have this already. Separate table. Already duplicated.
* KN: attributes as we've seen them so far - don't know how you'd make a user-defined one. Can alias, I guess. Weirder than an alias for a builtin type.
* KN: Think - put something here not called "identifier"? And make one grammar for attributes. Put "attribute name" after attribute.
* MM: exactly what I was thinking.
* DS: @compute with brackets? Can't do that now.
* MM: reminds me of CSS variables - just token sequence, brackets have to match, that's all. Could say attribute is "@" + string of stuff with matching brackets.
* DN: I'm more on board with parameters being identifier-like things. Don't think there's value in making the the attribute names overridable.
* BC/KN: +1
* AB: … doesn't have to resolve to the same thing in the grammar rule.
* JP: usually identifiers can't be the same as keywords.
* AB: using "identifier" to get the point across - a name-like thing.
* MM: do we want to collapse all these rules together? Collapse all of these together?
* KN: I'm suggesting ‘@’ attribute_identifier.
* AB: attribute identifier can look just like an identifier.
* DS: makes grammar consistent between all attributes.
* MM: does that solve the original intention?
* OD: one general grammar rule, yes, and define it in the table.
* AB: summary: \
Attribute = ‘@’ attribute_name attribute_params ? \
Attribute_params = ‘(‘ (expression , ?)+ ‘)’
* JP: attribute parameters are shadowable?
* DN: yes.
* MM: can't make a global variable "centroid" without shadowing the builtin “centroid”
* JB: this seems fine. I had thought the attribute table at the start of the spec was leaning more on the structure provided by the grammar.
* KN: depends on the other change to make more of these enums identifiers.
* KG: we're resolved on that now.
* KG: **consensus:** go ahead with the PR.
* OD: thanks. Think this is important, allows syntactic sugar.
* OD: similarly - extension names are specialized now, but they'll become general.
* DN: that's not part of it. Right now they're not resolved as identifiers. Think that's important going forward.
* AB: didn't discuss named attribute parameters. That'd be an extension to the grammar.
* MM: interesting proposal - think none of the other shading languages have named parameters.
* AB: GLSL almost has it in its layout specificers.
* BC: MSL has it. texture_size (?)
* MM: in Metal - you have a shared header between CPU and GPU code. #define MyThing 7. Identified by an integer, but a workaround outside the language.
* MM: named parameters are interesting, but not right now.
* OD: didn’t mean to propose it [just a point in favor of the general grammar for future proofing]

</details>

**Comment by mehmetoguzderin** [comment]
This also eases the way for more sophisticated attributes in future, they can use Bikeshed algorithms to really define their understanding of arguments as they need and not just introduce a ball of string to change syntax for every exceptional-feeling case that might emerge.

**Comment by dneto0** [comment]
When I write two rules: one being the general case and the other one being the special case for diagnostic, then Treesitter and my LALR1 verifier have no problem with it.

<img width="643" alt="Screenshot 2023-03-03 at 1 57 36 PM" src="https://user-images.githubusercontent.com/13054574/222804382-e625d740-b85b-4710-861c-3bf256628250.png">


> And then clarify how eventual resolution of identifier as a string is a matter of individual attribute's (including diagnostics) definition of its parameters,

I still think doing it that way is going to lead to more bugs.  It's best to be as mechanical as possible in the spec.


The super-generality is *not* needed.  When we have tooling that takes you all the way to an elaborated grammar, that's the clearest path to keeping downstream up to date.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐04‐16-Minutes#attribute-syntax-should-not-specialize-to-built-in-language-attributes--issue-3520--gpuwebgpuweb--github">WGSL 2024-04-16 Minutes</a></summary>

* Oguz: (in note, not call) The PR for preceding, #3911, also should address this sufficiently. Thank you
* MOD: Previous PR should cover this as well.

</details>

**Comment by mehmetoguzderin** [comment]
Merge of https://github.com/gpuweb/gpuweb/pull/4554 fixed this, closing. Thank you!
