### ISSUE TITLE
wgsl: limit nesting depth of if-else

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3527]
@ben-clayton  found that DXC fails to compile if-else with a nesting depth beyond 256.

Suggest adding a limit for this, or structured control flow in general in https://gpuweb.github.io/gpuweb/wgsl/#limits

**Comment by ben-clayton** [comment]
WG meeting, we suggested lowering this to 127 or 128, which will give us more wiggle-room. This would help Tint, as we can stack-overflow with MSVC / Debug builds (non-production) with the 256 limit.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-10-18-minutes#wgsl-limit-nesting-depth-of-if-else-3527-">WGSL 2022-10-18 Minutes</a></summary>

* JB: There’s no clear perfect relationship between limits in our target langs and wgsl source, so we should probably pick min of the target langs and divide by 2.
* AB: We can fall back on Spurious Error too.
* KG: We are just picking something to test, where we say “something at least this complex works”
* **Let’s take 127, and “any control flow”, not ifs specifically.**
* 

</details>
