### ISSUE TITLE
wgsl: NaNs and infinities in uniform or storage buffer

### ISSUE THREAD

**Issue by jzm-intel** [gpuweb/gpuweb#3533]
Currently in WGSL [spec](https://gpuweb.github.io/gpuweb/wgsl/#floating-point-evaluation) we have the following:
> * Implementations may assume that NaNs and infinities are not present at runtime.
>   * In such an implementation, when an evaluation would produce an infinity or a NaN, an undefined value of the target type is produced instead.
>   * It is a [shader-creation error](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) if any [const-expression](https://gpuweb.github.io/gpuweb/wgsl/#const-expressions) of floating-point type evaluates to NaN or infinity.
>   * It is a [pipeline-creation error](https://gpuweb.github.io/gpuweb/wgsl/#pipeline-creation-error) if any [override-expression](https://gpuweb.github.io/gpuweb/wgsl/#override-expressions) of floating-point type evaluates to NaN or infinity.

If I get it right, it seems that it doesn't specific the behavior when reading floats from uniform or storage buffer which happen to be NaN or Inf (or is this also one kind of "evaluation"?).
So shall we state here that reading NaN and Inf from buffers would also result in undefined value?
Proposed posible version:
> * Implementations may assume that NaNs and infinities are not present at runtime.
>   * In such an implementation, when an evaluation would produce an infinity or a NaN, an undefined value of the target type is produced instead.
>   * In such an implementation, when reading an infinity or a NaN from [uniform buffer](https://gpuweb.github.io/gpuweb/wgsl/#uniform-buffer) or [storage buffer](https://gpuweb.github.io/gpuweb/wgsl/#storage-buffer) variables, an undefined value of the target type is produced instead.
>   * It is a [shader-creation error](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) if any [const-expression](https://gpuweb.github.io/gpuweb/wgsl/#const-expressions) of floating-point type evaluates to NaN or infinity.
>   * It is a [pipeline-creation error](https://gpuweb.github.io/gpuweb/wgsl/#pipeline-creation-error) if any [override-expression](https://gpuweb.github.io/gpuweb/wgsl/#override-expressions) of floating-point type evaluates to NaN or infinity.

A practical case I met (when implementing `f16` extension) is that in HLSL reading a `f16` value from buffer may require using HLSL built-in `f16tof32` (which interpret the low 16 bits of `uint` as Binary16 float and return its value in float type) and cast it back to `float16_t`, and such operators are not bit-preserved for NaN, i.e. may convert a f16 NaN value `0x7E6D` to another NaN `0x7FFF`. Such behavior may be described as "an undefined value of the target type is produced".

**Comment by alan-baker** [comment]
Evaluation is meant to cover expressions. So it would cover loads from memory. Would it be clearer if we changed the first sub-bullet to:
> In such an implementation, when an expression evaluation would produce an infinity or a NaN, an undefined value of the target type is produced instead.
