### ISSUE TITLE
Fixed-footprint note can be shortened

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3534]
https://www.w3.org/TR/WGSL/#fixed-footprint-types says:

> Note: Fixed-footprint types exclude [runtime-sized](https://www.w3.org/TR/WGSL/#runtime-sized) arrays, and any structures or arrays that contain [runtime-sized](https://www.w3.org/TR/WGSL/#runtime-sized) arrays, recursively.

However, https://www.w3.org/TR/WGSL/#struct-types says:

> When a [runtime-sized](https://www.w3.org/TR/WGSL/#runtime-sized) array is part of a larger type, it may only appear as the last element of a structure, which itself cannot be part of an enclosing array or structure.

So, a runtime-sized array cannot be nested in an array or another structure. The fixed-footprint note seems like it could just be shortened to say:

> Note: Fixed-footprint types exclude [runtime-sized](https://www.w3.org/TR/WGSL/#runtime-sized) arrays.

**Comment by dneto0** [comment]
True.  My model of @dj2 is that he'd say "please repeat, for clarity".
What do you think, @dj2?

**Comment by dj2** [comment]
My preference is to repeat, as I think it makes the note a lot more useful to have the full context without have to go dig around other sections of the spec. (i.e. I'd forget about the struct restrictions when reading the note.)

**Comment by ben-clayton** [comment]
To me, it doesn't sound like it's repeating, but that it's carving out another rule stating that fixed-footprint types `exclude any structures or arrays that contain runtime-sized arrays`. 
To me, this implies that runtime-sized arrays **can** be nested, when they can't.

**Comment by dneto0** [comment]
How about this, which only mentions valid use cases:

> Note: Fixed-footprint types exclude [=runtime-sized=] arrays, and any structure
that contains a [=runtime-sized=] array.
