### ISSUE TITLE
Shift left for concrete: "e2+1 most significant bits of e1 do not have the same bit value" should only apply to signed values (i32)

### ISSUE THREAD

**Issue by amaiorano** [gpuweb/gpuweb#3535]
In https://gpuweb.github.io/gpuweb/wgsl/#bit-expr, for `Shift left (shifted value is concrete)`, we specify:

![image](https://user-images.githubusercontent.com/6893883/196252897-cff43855-36ef-49a4-bb86-d919ab04a15f.png)

This means that `1u << 31u` will result in an error because all 32 bits of the lhs must be the same. As the reason behind this rule is to error on an shift that results in a sign change, I think this rule should only apply if the lhs is a signed value (i.e. i32).

**Comment by dneto0** [comment]
Ah, you're right.

**Comment by dneto0** [comment]
When e1 is signed the condition should be |e2|+1,
When e1 is unsigned the condition should be |e2|.

**Comment by amaiorano** [comment]
> When e1 is unsigned the condition should be |e2|.

Just to clarify, we're saying that for unsigned, it's okay to shift left by e2 as long as the e2 most significant bits of e1 are the same? Say that we supported u8, then `11110000 << 4 ` would be okay? Shouldn't it be that for unsigned, that the bits shifted out must all be 0?

**Comment by dneto0** [comment]
> > When e1 is unsigned the condition should be |e2|.
> 
> Just to clarify, we're saying that for unsigned, it's okay to shift left by e2 as long as the e2 most significant bits of e1 are the same? Say that we supported u8, then `11110000b << 4u ` would be okay? Shouldn't it be that for unsigned, that the bits shifted out must all be 0?

You're right of course!   When e1 is unsigned, its top e2 bits must be zero.
