### ISSUE TITLE
WebGL - WebGPU interoperability #18 "copy interaction" - what about an easy post process option

### ISSUE THREAD

**Issue by dobkeratops** [gpuweb/gpuweb#3574]
WebGL - WebGPU interoperability #18

Some of what webGPU enables is compute shaders, which can implement some post processing, lighting algorithms in new ways

I strongly agree with the need for a smooth migration path, given the volume of issues people have these days..

it seems efficient interoperability for *postprocessing* would let you take webGL programs further for less invasive changes, and give a big step up to browser based 3d content generally.
in particular *neural* postprocessing (upscaling like DLSS, but also neural shading)
are there even plans for this sort of thing to be supported in the browser (compute shaders vs tensor accelerators..)

(I know some neural net techniques can be implemented in plain shaders but tensor cores etc are really important)

Would this require resource copies to achieve? if so could a streamlined path to avoid that be added ? (could buffers behind the scenes lazily figure out if they are copies and just rename?)

what would it look like?

**Comment by dobkeratops** [comment]
> Not sure how WebGL interop is related to your question about neural postprocessing, but these are potentially related/relevant to the latter:
> 
> *

so my big question is:
*can I get neural acceleration for a WebGL application* , without having to port to WebGPU.

by leaning more on neural postprocessing (eg neural lighting) you could get a lot more life out of a webGL2.0 program without the burden of having to rewrite your engine and shaders - and there's plenty of design choices that minimise GL overhead (especially with instancing and texture arrays\), and keeping the benefit of a cross platform source base (a GL source base can be made to compile on almost anything with small changes, much easier to maintain than multiple API back ends)

but if a port to webGPU is required, I'm far less likely to do that .

besides dedicated neural accelerators, I'm aware NN's can be implented in compute shaders and even regular shaders, although you might not get access to the tensor cores on nvidia and so on. (but imagine if a driver could spot a vendor documented shader with behaviour equivalent to tensor cores - it's theoretically possible it could use them there)

**Comment by kainino0x** [comment]
- You can already copy a WebGL canvas into WebGPU using `copyExternalImageToTexture()`
- We have #1670 tracking importing WebGL and 2d canvases into WebGPU using `importExternalTexture()`

So I don't think this issue needs to stay open.
