### ISSUE TITLE
bitwise operator not working anymore ?

### ISSUE THREAD

**Issue by bzhmaddog** [gpuweb/gpuweb#3590]
In my shader(s) I am using  the or (pipe) operator and bit shifting to get a color as a 32bits unsigned integer (u32) using RGB and Alpha components.

// turquoise full opacity
var a = 255u;
var r = 64u;
var g = 224u;
var b = 208u;

var color = a << 24u | b << 16u | g << 8u | r;

This was working fine up to Chrome 105 but now in Chrome 107 it generate a compilation error :
"expected ';' for assignment statement"

color = 0u; is working.

A long as I remove the pipe '|' there is no compilation error

I have looked through the specs (november 2022 version) but I haven't found any explicit changes regarding this.

Any help will be appreciatated

**Comment by bzhmaddog** [comment]
Shader example : https://github.com/bzhmaddog/H5DMD/blob/master/js/renderers/ChangeAlphaRenderer.mjs

**Comment by alan-baker** [comment]
Precedence rules require parentheses now.
```
var color = (a << 24u) | (b << 16u) | (g << 8u | r);
```

The precedence rules are expressed in the grammar, but we plan to have a section explaining with prose and diagrams for easier understanding.

**Comment by bzhmaddog** [comment]
That fixed my errors, thx. Make sense

**Comment by ben-clayton** [comment]
Note: Upcoming Chrome releases will have a much-improved error message, as `expected ';'` was really confusing. Sorry about that!
