### ISSUE TITLE
GPUBuffer.mapAsync is very slow... 

### ISSUE THREAD

**Issue by tlecoz** [gpuweb/gpuweb#3595]
Hello,

I made a small demo based on ComputePipeline. 

I use 2 very small VertexBuffer with an usage property set to GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC that contains only 6 values each. 

I try to read the computed data using a "staging buffer" like exposed in this article 
https://surma.dev/things/webgpu/

My "staging-buffer" is defined like that : 
```
device.createBuffer({
            size,
            usage: GPUBufferUsage.MAP_READ | GPUBufferUsage.COPY_DST
        })
```

my "update" function look like that : 
```

private fps:number = 0;
private time:number = 0;
private canCallMapAsync:boolean = true;
private nbMapAsyncCall:number = 0;

public update(){
        if (!this.time) this.time = Date.now();

        this.fps++;
        if (Date.now() - this.time >= 1000) {
            console.log("fps = ", this.fps + " | " + this.nbMapAsyncCall);
            this.time += 1000;
            this.fps = 0;
            this.nbMapAsyncCall = 0;
        }
        
         const commandEncoder = this.gpu.device.createCommandEncoder();
         this.computePipeline.process(commandEncoder); 
         
         
         const vertexIO = computePipeline.vertexBufferIO;
         const stage = computePipeline.stagingBuffer;

         if (this.canCallMapAsync) {
              commandEncoder.copyBufferToBuffer(vertexIO.ouputBuffer,
                  0,
                  stage,
                  0,
                  stage.size);
          }
          this.gpu.device.queue.submit([commandEncoder.finish()]);

          if (this.canCallMapAsync) {
                this.nbMapAsyncCall++;
                this.canCallMapAsync = false;
                console.time("mapAsync");
                computePipeline.stagingBuffer.mapAsync(GPUMapMode.READ, 0, stage.size).then(() => {
                const copyArray = stage.getMappedRange(0, stage.size);
                const data = copyArray.slice(0);
                stage.unmap();
                console.timeEnd("mapAsync");
                this.canCallMapAsync = true;
                computePipeline.onReceiveData(new Float32Array(data));
          })
    }
}

```
I'm forced to use the flag "canCallMapAsync"  because I get this an error if I don't use it

![image](https://user-images.githubusercontent.com/272817/201668188-1c7307e4-9e4d-4030-9b69-1efe104badb7.png)

 (that's what happen if I comment the line 
`this.canCallMapAsync = false;`
)

Everything runs fine if I use my flag "canCallMapAsync" but the outputs of my console.time("mapAsync") show me that this function is very very very slow 

 
![image](https://user-images.githubusercontent.com/272817/201668549-dffcca87-4c3e-4b94-a043-b1939ffd646f.png)

As I said, my buffer contains only 6 values. 

It almost take 1ms by value !!!! That's ridiculous ! 

To be honnest, I get almost the same process time with a buffer containing 60 000 values , so the speed doesn't depends so much on the amount of data (it would be a huge problem if it need one minutes to extract 60 000 values ^^ ) 

Did I do something wrong ? 
How can I improve performances ?

Any help is welcome !

(just in case , my hardware config is Win 11 / AMD 3900X / RTX 2080 super )

**Comment by ben-clayton** [comment]
This issue tracker is for the W3 specification of WebGPU and WGSL, not any particular implementation.

It sounds like you're testing with Chrome / Chromium? If so, you're more likely to get a better response if you file an issue at [crbug.com/dawn](https://crbug.com/dawn).

**Comment by tlecoz** [comment]
Ok thank you 
Sorry for the inconvenience

**Comment by kainino0x** [comment]
mapAsync cannot resolve until the GPU has completed writing into the buffer. At the time you call `mapAsync`, it may not have yet: WebGPU is a completely asynchronous API, for example `queue.submit()` will just send off some commands, not wait for them to complete.

So in effect, what you're timing here is ALL of the GPU work that went into creating that data, plus the latency of the mapAsync call. If you want to time just the map, try awaiting `queue.onSubmittedWorkDone()` first.

Even if you do this, map latency will still be a bit high. It necessarily requires a roundtrip between the sandboxed content process and the GPU process of the browser. This is a critical part of the Web security model.

**Comment by tlecoz** [comment]
thank you for your message 
I confirm that queue.onSubmittedWorkdone helped me to solve my problem and everything works as expected now
