### ISSUE TITLE
destroy() should unmap if there's a pending mapping

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3597]
Posted by @takahirox on Matrix:

> Hi, I'm working on https://bugs.chromium.org/p/chromium/issues/detail?id=1355994&q=label%3AProj-WebGPU-Milestone-V1 for Dawn.
> 
> I would like to clarify the behavior of that buffer whose mapState is "pending" (1) is destroyed.
> 
> The destroy() spec (2) describes that "If this is mapped, call this.unmap()". I think it should also call this.unmap() if buffer is "pending", shouldn't it?
> 
> Otherwise, [[pending_map]] won't be null so mapAsync() won't immediately return in the second content timeline steps (the screenshot below) although the buffer is already destroyed.
> 
> (1): https://gpuweb.github.io/gpuweb/#dom-gpubuffer-mapstate
> (2): https://gpuweb.github.io/gpuweb/#dom-gpubuffer-destroy
> (3): https://gpuweb.github.io/gpuweb/#dom-gpubuffer-mapasync

I'm pretty sure this is correct, and we just forgot to update the definition of destroy() when reworking the definitions for mapping.

**Comment by takahirox** [comment]
Thanks for filing the issue. I will make a PR.
