### ISSUE TITLE
WRT Vector-Matrix Multiplication and Non-Associativity

### ISSUE THREAD

**Issue by 4LT** [gpuweb/gpuweb#3608]
I don't know if this has been brought up before, I couldn't find anything searching existing issues, but I find the non-associativity of multiplying vectors and matrices somewhat irksome.  Example:

> Given matrices `A`,`B` and vector `v`, how is `A * v * B` evaluated?

Is it `(A * v) * B` or `A * (v * B)`?  I checked the W3C doc (https://www.w3.org/TR/WGSL/#arithmetic-expr), but couldn't determine whether the `*` operator* is left-associative or right-associative.

_*assuming the `*` in `matrix * vector` and `vector * matrix` can be considered the "same" operator.  If not, then what is the operator precedence of the matrix-times-vector and vector-times-matrix operators?_

 I would *intuit* that left associativity is preferred (same as division and subtraction) but that's just an assumption so far as I can tell.
 

Personally I find the behavior of interpreting the vector in `v * M` as a column or in `M * v` as a row too useful to reject outright.  Instead, I think expressions like `A * v * B` should be rejected as ambiguous, if only because the operation is *essentially* matrix multiplication and "normal" matrix multiplication *is* associative.  Even if one is conventionally assumed to expect `A * v * B` to be the same as `(A * v) * B`, they may erroneously believe that associativity holds and expect it to equal `A * (v * B)`, and may attempt form of refactor with that assumption resulting in a surprising effect.

**Comment by mehmetoguzderin** [comment]
Operator precedence had a long discussion, and IIRC, the topic of types influencing syntax did not come up heavily. And specification's syntax is normative when it comes to associativity (a new PR will introduce a graph and a table to make it more readable), making it (A * v) * B. The following screenshot illustrates the CST (these CSTs will also become a tiny bit more readable with another already open PR).

![Screen Shot 2022-11-19 at 07 48 23](https://user-images.githubusercontent.com/5333693/202816144-1c05139c-9249-4e32-bb1c-8511a4a02b75.png)

**Comment by mehmetoguzderin** [comment]
And following is the URL for the syntax of multiplicative, it is currently not inside the arithmetic expressions section (editorial changes to make sure things have actual syntax rules and as near as possible will arrive): https://www.w3.org/TR/WGSL/#syntax-multiplicative_expression

**Comment by kainino0x** [comment]
I think #3609 will resolve the documentation problem.

> I think expressions like `A * v * B` should be rejected as ambiguous

Philosophically I totally agree with rejecting ambiguous expressions, which is why we have a bunch of non-associative operators and a partially-ordered operator precedence. Practically speaking, I think parsing and type checking are totally separate steps, and should stay that way, so in order to make this an error we'd need some interesting new innovation, which I'm pretty sure would be too experimental to add to this language (for example distinguishing between row and column vector types, and limiting implicit conversions between the two in such a way that this wouldn't typecheck).

**Comment by 4LT** [comment]
Ahh, of course, we don't have the type information at the time of parsing.  Well, I guess I'm satisfied then.
