### ISSUE TITLE
Still no way to work with simple bytes ? 

### ISSUE THREAD

**Issue by dezmou** [gpuweb/gpuweb#3620]
Hello, 

For learning WGSL I want to try to implement sha256 algorithm, but I get stuck at the very beginning, how to work with bytes array ( 8 bit each item)  ? 
For now I can only do 32 or 16 bytes variable or arrays. 
Is it a technical constraint linked to the graphic cards? 

Thanks

**Comment by Kangz** [comment]
Many GPUs don't have support for bytes and only have 32 bit integers so because WebGPU and WGSL targets those GPUs, it can't expose support for these data types in V1. It could be an extension post-V1 though.

**Comment by kdashg** [comment]
Yes, this is a technical constraint, where we cannot generally support this.
