### ISSUE TITLE
Confusing note in builtin `length` section

### ISSUE THREAD

**Issue by amaiorano** [gpuweb/gpuweb#3621]
At https://gpuweb.github.io/gpuweb/wgsl/#length-builtin, it says for scalars that `Evaluates to the absolute value of e if T is scalar.`. But then we have this note:

```
Note: The result is not mathematically meaningful if e ≤ -0.
```

This note is confusing and seems to contradict the definition. Should we be erroring for constant evaluation if e <= -0?

I think we should just remove this note.

**Comment by munrocket** [comment]
Looks like we need to remove scalar length at all or evaluate it as abs().

According to current specification `length(e)` may be evaluated as `sqrt(e*e)`. So it is a performance and accuracy footgun when compared to `abs(e)`.
