### ISSUE TITLE
Almost no PowerVR devices satisfy minimum Vulkan requirements

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3631]
Please see https://github.com/gpuweb/gpuweb/issues/1069#issuecomment-930710309 for the Vulkan gpuinfo query results.

We should look into this a bit more closely and see if these are reasonable devices to support and whether we can tighten some limits to allow them.

---

- [ ] Update the correspondence doc with whatever we do here, and in the Vulkan column, take `maxFragmentCombinedOutputResources` into account in all of the limits it affects.

**Comment by kainino0x** [comment]
```
Requirement "maxFragmentCombinedOutputResources >= 8+4+8, OR is intel/nvidia/amd" loses 12 (and partially loses 5) further deviceNames:
  In ALL reports (12 deviceNames):
    x FD630: 2 (9843 10962)
    x FD640: 2 (12237 12590)
    x FD650: 3 (9599 12275 14634)
    x FD660: 1 (12634)
    x PowerVR BXM-8-256: 2 (16316 16943)
    x PowerVR Rogue G6110: 1 (8724)
    x PowerVR Rogue G6430: 1 (1859)
    x PowerVR Rogue GE8100: 6 (3381 4534 6562 11262 15341 15550)
    x PowerVR Rogue GE8300: 4 (1999 5712 5796 6134)
    x PowerVR Rogue GE8320: 1 (7432)
    x PowerVR Rogue GT7400 Plus: 2 (3165 9833)
    x PowerVR Rogue GX6250: 5 (1575 3483 3779 6404 12395)
```

**Comment by kainino0x** [comment]
Was discussed a little in #1343

**Comment by kainino0x** [comment]
> maxFragmentCombinedOutputResources is the total number of storage buffers, storage images, and output Location decorated color attachments (described in Fragment Output Interface) which can be used in the fragment shader stage.

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceLimits.html

**Comment by kainino0x** [comment]
I think we can directly lift the `maxFragmentCombinedOutputResources` limit into WebGPU as an extra limit that applies on top of `maxColorAttachments` + `maxStorageBuffersPerShaderStage ` + `maxStorageTexturesPerShaderStage`.

This is very similar to #2749 which is essentially a "max vertex combined input resources".

**Comment by kainino0x** [comment]
Group approved, we'll open a PR and tacit-resolution-queue it.

**Comment by kainino0x** [comment]
I thought to look a bit more closely at the PowerVR results after adding `maxFragmentCombinedOutputResources` and we still have some problems. The main one:

```
Requirement "maxImageDimension2D and related limits >= 8192" loses 3 (and partially loses 3) further deviceNames:
  In ALL reports (3 deviceNames):
(...)
    x PowerVR Rogue GE8322: 9 (8768 11033 11970 12910 13061 14852 15062 15500 15921)
    x PowerVR Rogue GM9446: 10 (6175 8880 9773 10603 10747 11455 12287 12700 12781 15794)
  In SOME reports (3 deviceNames):
    ~ PowerVR Rogue GE8300: 6 of 10 (8741 12457 12599 13899 15356 16281; ok: 1999 5712 5796 6134)
    ~ PowerVR Rogue GE8320: 79 of 80 (9537 10330 10375 10402 10480 10570 10657 10674 10719 10744 10751 10757 10781 10840 11015 11049 11086 11194 11312 11599 11706 11803 12004 12033 12174 12175 12328 12335 12375 12396 12451 12483 12525 12579 12641 12644 12786 12905 13046 13047 13137 13442 13568 13572 13630 13720 13830 13943 14054 14055 14180 14193 14310 14780 14805 14812 14859 14914 14921 14996 15003 15079 15104 15133 15153 15533 15666 15772 15841 16193 16206 16213 16403 16669 16951 16994 17004 17029 17489; ok: 7432)
(...)
At least one of each of the following was still supported:
(...)
  + PowerVR B-Series BXT-32-1024 (1 of 1)
  + PowerVR BXM-8-256 (2 of 2)
  + PowerVR Rogue GE8300 (1 of 10)
  + PowerVR Rogue GE8320 (1 of 80)
  + PowerVR Rogue GX6250 (1 of 5)
(...)
```

Breaking this down further, the max texture size on these devices is simply 4096.
Example: https://vulkan.gpuinfo.org/displayreport.php?id=17489#properties

```
Requirement "maxImageDimension2D >= 8192" loses 2 (and partially loses 2) further deviceNames:
  In ALL reports (2 deviceNames):
    x PowerVR Rogue GE8322: 9 (8768 11033 11970 12910 13061 14852 15062 15500 15921)
    x PowerVR Rogue GM9446: 10 (6175 8880 9773 10603 10747 11455 12287 12700 12781 15794)
  In SOME reports (2 deviceNames):
    ~ PowerVR Rogue GE8300: 6 of 7 (8741 12457 12599 13899 15356 16281; ok: 5712)
    ~ PowerVR Rogue GE8320: 79 of 80 (9537 10330 10375 10402 10480 10570 10657 10674 10719 10744 10751 10757 10781 10840 11015 11049 11086 11194 11312 11599 11706 11803 12004 12033 12174 12175 12328 12335 12375 12396 12451 12483 12525 12579 12641 12644 12786 12905 13046 13047 13137 13442 13568 13572 13630 13720 13830 13943 14054 14055 14180 14193 14310 14780 14805 14812 14859 14914 14921 14996 15003 15079 15104 15133 15153 15533 15666 15772 15841 16193 16206 16213 16403 16669 16951 16994 17004 17029 17489; ok: 7432)
Requirement "maxImageDimensionCube >= 8192" loses no further reports!
Requirement "maxFramebufferWidth >= 8192" loses no further reports!
Requirement "maxFramebufferHeight >= 8192" loses no further reports!
Requirement "maxViewportDimensions[0] >= 8192" loses no further reports!
Requirement "maxViewportDimensions[1] >= 8192" loses no further reports!
Requirement "viewportBoundsRange[0] <= -8192" loses no further reports!
Requirement "viewportBoundsRange[1] >= 8192" loses no further reports!
Requirement "maxImageDimension1D >= 8192" loses no further reports!
Requirement "maxImageDimension3D >= 2048" loses no further reports!
Requirement "maxImageArrayLayers >= 256" loses no further reports!
(...)
At least 90% of each of the following was still supported:
(...)
  + PowerVR B-Series BXT-32-1024 (1 of 1)
  + PowerVR BXM-8-256 (2 of 2)
(...)
At least one, but under 90% of each of the following was still supported:
(...)
  ? PowerVR Rogue GE8300 (1 of 10)
  ? PowerVR Rogue GE8320 (1 of 80)
  ? PowerVR Rogue GX6250 (1 of 5)
(...)
```

Incidentally, this way of breaking things down also reveals we also have relatively poor support on Adreno 500 series devices.

```
At least one, but under 90% of each of the following was still supported:
  ? Adreno (TM) 505 (28 of 113)
  ? Adreno (TM) 506 (55 of 164)
  ? Adreno (TM) 508 (9 of 22)
  ? Adreno (TM) 509 (16 of 26)
  ? Adreno (TM) 510 (1 of 68)
  ? Adreno (TM) 512 (47 of 84)
  ? Adreno (TM) 530 (53 of 149)
  ? Adreno (TM) 540 (79 of 146)
```

Most of these are lost on these requirements:
- `maxPerStageDescriptorStorageBuffers >= 8`
- `depth32float` (supported with SAMPLED_IMAGE and DEPTH_STENCIL_ATTACHMENT in optimalTilingFeatures)

So the questions here are:
- [ ] Do we actually care about these PowerVR devices, or will we force them to WebGPU compat? We decided a long time ago we wanted to guarantee 8K textures, so it would be unfortunate to change that.
    - [ ] If we decide we don't care, should we bother with the `maxFragmentCombinedOutputResources` limit? It still may be useful for values beyond the base limits, so probably. Better to add it and not need it than have to introduce it after V1.
- [ ] Same for majority of Adreno 500. (Pretty sure we are fine with compat for these.)

**Comment by kainino0x** [comment]
I tried to unlink this but left it in the commit message >_>

**Comment by kainino0x** [comment]
Dawn's thinking before we added this limit was that it was incorrectly reported on AMD/NVIDIA/Intel devices, so we ignored it for those:
https://github.com/kainino0x/gpuinfo-vulkan-query/commit/7cc9056d1a68958c4bdb81b6a4781c8a2e99dac4
https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/native/vulkan/AdapterVk.cpp;l=385;drc=c2657b21d50938d4676aa6c87e44b3aa50c7f468
**IF** that's still correct even for higher storage binding limits, then adding `maxFragmentCombinedOutputResources` may actually not be doing anything for us. Here's a series of queries that look at whether it's filtering out any devices at higher storage limit tiers:

```
Requirement "maxPerStageDescriptorStorageBuffers >= 16" loses no further reports!
Requirement "maxPerStageDescriptorStorageImages >= 8" loses 9 (and partially loses 1) further deviceNames:
(...)
Requirement "maxFragmentCombinedOutputResources >= 16+8+8, OR is intel/nvidia/amd" loses 9 (and partially loses 5) further deviceNames:
  In ALL reports (9 deviceNames):
    x FD630: 2
    x FD640: 2
    x FD650: 3
    x FD660: 1
    x PowerVR BXM-8-256: 4
    x PowerVR Rogue GE8300: 1
    x PowerVR Rogue GE8320: 1
    x PowerVR Rogue GX6250: 1
    x SwiftShader Device: 2
  In SOME reports (5 deviceNames):
    ~ AMD RADV POLARIS10: lost 1 of 615
    ~ Turnip Adreno (TM) 630: lost 2 of 8
    ~ Turnip Adreno (TM) 640: lost 1 of 13
    ~ Turnip Adreno (TM) 650: lost 2 of 44
    ~ llvmpipe: lost 225 of 497

Requirement "maxPerStageDescriptorStorageBuffers >= 16" loses no further reports!
Requirement "maxPerStageDescriptorStorageImages >= 16" loses 28 (and partially loses 26) further deviceNames:
(...)
Requirement "maxFragmentCombinedOutputResources >= 16+16+8, OR is intel/nvidia/amd" loses no further reports!

Requirement "maxPerStageDescriptorStorageBuffers >= 32" loses 10 (and partially loses 65) further deviceNames:
(...)
Requirement "maxPerStageDescriptorStorageImages >= 32" loses 39 (and partially loses 1) further deviceNames:
(...)
Requirement "maxFragmentCombinedOutputResources >= 32+16+8, OR is intel/nvidia/amd" loses no further reports!
```

**Comment by kainino0x** [comment]
My proposal is to:
- close this, say older PowerVR devices won't be supported. PowerVR will start working when their newer chips start showing up in the ecosystem.
- open a new post-V1 issue about "removing" `maxFragmentCombinedOutputResources`, since it doesn't seem to be very useful. We can't remove the limit itself, but we can remove the validation that it adds. This would be nice so we can remove some of the "combined" limits which introduce some annoying complexity to limits.

**Comment by JarredHDavies** [comment]
maxFragmentCombinedOutputResources is incorrectly reported on older PowerVR drivers, it should just be ignored for these drivers. The correct limit for us is the same as `maxPerStageDescriptorStorageImages + maxPerStageDescriptorStorageBuffers + maxColorAttachments`

**Comment by Kangz** [comment]
This is great info, thank you! It seems we might be able to remove this limit after all.

**Comment by kainino0x** [comment]
That's great! Updating our compatibility query - out of the devices I see on gpuinfo, it's still the case that almost all of them only support 4k textures as discovered above, so unfortunately knowing this doesn't fix our compatibility problem. However it _does_ look like we can at least raise the base value of this limit to 20, and it is looking very possible to remove it.

```
Requirement "maxFragmentCombinedOutputResources >= 8+4+8, OR is intel/nvidia/amd/imgtec" loses 4 (and partially loses 5) further deviceNames:
  In ALL reports (4 deviceNames):
    x FD630: 2 (9843 10962)
    x FD640: 2 (12237 12590)
    x FD650: 3 (9599 12275 14634)
    x FD660: 1 (12634)
  In SOME reports (5 deviceNames):
    ~ AMD RADV POLARIS10: 1 of 615 (15761)
    ~ Turnip Adreno (TM) 630: 2 of 10 (13100 13399)
    ~ Turnip Adreno (TM) 640: 1 of 15 (13196)
    ~ Turnip Adreno (TM) 650: 2 of 58 (13195 13371)
    ~ llvmpipe: 225 of 499 (9379 9614 9631 9765 9824 10043 10121 10275 10338 10407 10445 10557 10629 10679 10694 10772 10802 10883 10919 10975 11036 11074 11083 11140 11148 11162 11166 11197 11244 11270 11285 11307 11320 11427 11435 11448 11466 11490 11506 11547 11574 11618 11634 11644 11705 11759 11768 11795 11801 11819 11827 11836 11851 11888 11893 11932 11945 11972 12006 12012 12018 12050 12081 12090 12094 12106 12110 12118 12135 12139 12157 12184 12212 12226 12257 12265 12272 12309 12313 12339 12356 12386 12409 12443 12450 12479 12500 12519 12535 12564 12576 12582 12616 12621 12663 12709 12725 12738 12752 12760 12783 12791 12869 12892 12902 12909 12950 12972 13002 13009 13011 13079 13122 13127 13140 13151 13159 13176 13199 13201 13228 13259 13301 13322 13332 13336 13369 13379 13382 13406 13495 13506 13511 13527 13531 13533 13548 13549 13554 13557 13559 13601 13623 13625 13633 13634 13639 13645 13647 13657 13658 13663 13665 13682 13683 13687 13688 13741 13770 13771 13789 13791 13796 13798 13843 13845 13911 13913 13950 13974 14020 14032 14033 14046 14059 14062 14067 14187 14189 14207 14209 14260 14262 14267 14288 14305 14307 14313 14315 14327 14329 14344 14346 14349 14357 14374 14376 14379 14381 14390 14402 14404 14409 14411 14430 14432 14442 14444 14454 14456 14469 14471 14477 14479 14484 14486 14498 14572 14861 15468 16028 17332 17759 18111 18562)
```

It's also good to know we won't have to worry about maxFragmentCombinedOutputResources for a possible compat profile for older devices.
