### ISSUE TITLE
How can I get the minimum float value?

### ISSUE THREAD

**Issue by javirk** [gpuweb/gpuweb#3656]
In GLSL I would use uintBitsToFloat(0x2F800000u) to get the minimum f32 (following [this](https://www.shadertoy.com/view/Mt3cRX)). However, that function doesn't seem to exist in WGSL. Is there any workaround for that?

I saw [this issue](https://github.com/gpuweb/gpuweb/issues/3431), but I don't think there is an alternative for now, right?

**Comment by javirk** [comment]
Solved: `bitcast<f32>(0x2F800000u)` does it.

**Comment by ben-clayton** [comment]
WGSL supports hex floats, so you can write `0x1p-126f`, which is the smallest non-subnormal `f32` number.
