### ISSUE TITLE
wgsl: add sign builtin function on integer scalar and vector

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3658]
WGSL should add overloads of the `sign` builtin function, for integer and integer-vector arguments.

* HLSL has it: https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-sign 
* GLSL 4.5 has it.  (See 8.3 Common functions.  overloads for genIType
* SPIR-V has it. [GLSL.std.450 extended instruction](https://registry.khronos.org/SPIR-V/specs/1.0/GLSL.std.450.html) SSign
* MSL does not have it.  But the polyfill is easy

**Comment by dneto0** [comment]
Found when reviewing Tint's SPIR-V reader translator.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-12-06-minutes#wgsl-add-sign-builtin-function-on-integer-scalar-and-vector-3658">WGSL 2022-12-06 Minutes</a></summary>

* PR: [https://github.com/gpuweb/gpuweb/pull/3659](https://github.com/gpuweb/gpuweb/pull/3659) 
* KG: Seems reasonable
* **Resolution: Let’s take it**

</details>
