### ISSUE TITLE
TR publication broken due to issue with document license/charter

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3662]
https://github.com/gpuweb/gpuweb/actions/workflows/publish-TR-webgpu.yml?query=branch%3Amain

```
  Specberus Errors:
    Could not get the document license from the API. Please make sure this group has a current charter associated with at least one document license.
      {
        name: 'headers.copyright',
        section: 'front-matter',
        rule: 'copyright'
      }
    The group does not have any current charter, please contact the team contact.
      { name: 'sotd.charter' }
    Cannot find the patent policy version from the groups charter. Please make sure the group has a current charter with a patent policy
      { name: 'sotd.pp', section: 'document-status', rule: 'patPolReq' }
  
  Details: https://labs.w3.org/echidna/api/status?id=f1510f10-eb95-46e7-8e25-783266715e06
  💥 Echidna publish has failed.
  Error: Process completed with exit code 1.
```

cc @tidoust do you know what's happening here? did something happen because of the recent charter update?

**Comment by tidoust** [comment]
Yes, we're back to a situation where the working group is temporarily out of charter. The current charter expired on 30 November. Review of the new charter ended on Friday. I'm now trying to get a final green light for it but that should take another couple of days. Publication to /TR will resume as soon as the new charter is in place.

**Comment by kainino0x** [comment]
Thanks!

**Comment by tidoust** [comment]
The new charter was approved and is now in place. I re-ran last publication tasks that had failed and confirm that the /TR versions of both WebGPU and WGSL are back in sync with the Editors Drafts.
