### ISSUE TITLE
beginComputePass/beginRenderPass errors do not invalidate parent encoder

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3663]
This was _sort of_ intentional in #2452 / #2751 but I realized it has weird consequences.

I believe according to the current spec the following would produce a valid command buffer:

```ts
encoder = createCommandEncoder();
pass = encoder.createComputePass(invalidDescriptor); // `pass` is invalid
encoder.finish(); // `encoder` still valid
```

while the following would give an invalid command buffer:

```ts
encoder = createCommandEncoder();
pass = encoder.createComputePass(invalidDescriptor); // `pass` is invalid
pass.end(); // invalidates `encoder` because `pass` is invalid
encoder.finish(); // `encoder` now invalid
```

**Comment by kainino0x** [comment]
I think beginComputePass/beginRenderPass should just be changed to make the parent encoder invalid too. This makes it so implementations don't have to make a weird corner case that looks incorrect work "correctly".

**Comment by austinEng** [comment]
Fwiw, I thought it was simpler before #2452 such that any errors in the encoder or pass make the encoder invalid, and you don't see the errors at all until calling finish?

Right now, it's also the case that createComputePass can produce an error in the error scope AND invalidate the pass/encoder. But dispatchWorkgroups without a pipeline set will just invalidate the pass without producing an error in the error scope. I don't see a reason why these should be different.

**Comment by toji** [comment]
@kainino0x, in the first example you gave isn't it invalid due to the open (though invalid) pass when `finish()` is called? If not, shouldn't it be?

**Comment by kainino0x** [comment]
> @kainino0x, in the first example you gave isn't it invalid due to the open (though invalid) pass when `finish()` is called? If not, shouldn't it be?

No because the state of the parent encoder doesn't get set unless validation of begin*Pass succeeds. We could probably just change that.

**Comment by kainino0x** [comment]
> Right now, it's also the case that createComputePass can produce an error in the error scope AND invalidate the pass/encoder. But dispatchWorkgroups without a pipeline set will just invalidate the pass without producing an error in the error scope. I don't see a reason why these should be different.

This came about initially because we wanted beginComputePass to throw some kind of error (not fail completely silently) if you tried to call it on a closed encoder. The thing is, I'm not exactly sure why I also put the rest of the validation inside the same block with the same behavior. It may have been somewhat accidental. Let me draft separating it out.
