### ISSUE TITLE
Behavior of `GPUSamplerDescriptor.maxAnisotropy` with a non power of two

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#3671]
> Note: Most implementations support [maxAnisotropy](https://gpuweb.github.io/gpuweb/#dom-gpusamplerdescriptor-maxanisotropy) values in range between 1 and 16, inclusive. The used value of [maxAnisotropy](https://gpuweb.github.io/gpuweb/#dom-gpusamplerdescriptor-maxanisotropy) will be clamped to the maximum value that the platform supports.

> descriptor.[maxAnisotropy](https://gpuweb.github.io/gpuweb/#dom-gpusamplerdescriptor-maxanisotropy) ≥ 1

The spec currently only talks about clamping to the max value that the platform supports and that the min value is 1.

It looks to me like there is missing validation for making sure it's a power of two.

**Comment by Kangz** [comment]
Why would it need to be a power of two? The anisotropy is specified as a float in target APIs and can be about anything.

**Comment by teoxoy** [comment]
For Vulkan it's indeed a float but for Metal and DX12 it's an integer (both mentioning that it must be between 1 and 16).

None of them seem to indicate it must be a power of two, it's just that I never heard of a non power of two anisotropy value. The person who implemented the check in wgpu also most likely hasn't.

references
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSamplerCreateInfo.html
https://developer.apple.com/documentation/metal/mtlsamplerdescriptor/1516164-maxanisotropy
https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_sampler_desc

**Comment by Kangz** [comment]
The behavior of that value is very non-normative (and hardware dependent) so it's fine if implementation round / floor / clamp to the nearest power of two no? So we can just keep it an unrestricted float as it is now?

**Comment by teoxoy** [comment]
The spec says it's a u16. Which is fine with me.

I'll remove the power of two restriction over in wgpu.
Thanks for the clarification!

**Comment by kainino0x** [comment]
> The behavior of that value is very non-normative (and hardware dependent) so it's fine if implementation round / floor / clamp to the nearest power of two no? So we can just keep it an unrestricted float as it is now?

Yup, this was the standardization decision. Basically maxAnisotropy has almost no normative meaning whatsover (at least in Vulkan) so we basically consider it a hint.

**Comment by kainino0x** [comment]
Though I wonder if we should change it from a u16 to a float? I can't remember why we decided on u16 if vulkan allows floats
