### ISSUE TITLE
the native API for webgl2 is opengl es3 or d3d11？

### ISSUE THREAD

**Issue by yangfangfang1204** [gpuweb/gpuweb#3676]
https://webglreport.com/?v=2
the report:
`
Platform: | Win32
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
webgl2
WebGL 2.0 (OpenGL ES 3.0 Chromium)
WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
WebKit
WebKit WebGL
Google Inc. (NVIDIA)
ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11)
Available
Yes, D3D9
No
`
First question :
so WebGL2 call the native API is OpenGL ES3 or D3D11？

Second question: 
is there some option in webgl2 ,we could configure the OpenGL ES3 or D3D11 ?

Third question:
the native API is dependent on platform(windows/linux/mac) or  browser(chrome,firefox)?
because i know only windows support d3d11 . and in firefox the report of webgl2 is different from chrome. the Renderer is  `ANGLE` (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 `ps_5_0)` , and chrome is WebKit WebGL.

**Comment by munrocket** [comment]
This is unrelated to gpuweb question. It is a question for [angle](https://github.com/google/angle) or [webgl](https://github.com/KhronosGroup/WebGL). Yes you can choose different backends in browsers for Angle and they have default option.

**Comment by kainino0x** [comment]
WebGL calls into ANGLE (using the OpenGL ES interface) and ANGLE translates that into D3D11 for the system. So ultimately you are using D3D11.

You cannot use OpenGL ES 3 at the bottom unless the system supports it. Most Windows systems do not support OpenGL ES. They usually support desktop OpenGL, and in Chrome/Chromium, you can use that backend through ANGLE with `--use-angle=gl`. However, this is an unsupported Chrome configuration, and we don't fix bugs that arise when you do this.
