### ISSUE TITLE
WGSL reader failure: :7:14 error: no matching call to textureSampleLevel(texture_external, sampler, vec2<f32>)

### ISSUE THREAD

**Issue by yangfangfang1204** [gpuweb/gpuweb#3680]
https://github.com/w3c/webcodecs/tree/main/samples/video-decode-display

i use the demo play video in V110(enable-webgpu), but it return the error .  

Tint WGSL reader failure: :7:14 error: no matching call to textureSampleLevel(texture_external, sampler, vec2<f32>)

14 candidate functions:
  textureSampleLevel(texture: texture_2d<f32>, sampler: sampler, coords: vec2<f32>, level: f32) -> vec4<f32>
  textureSampleLevel(texture: texture_depth_2d, sampler: sampler, coords: vec2<f32>, level: L) -> f32  where: L is i32 or u32
  textureSampleLevel(texture: texture_3d<f32>, sampler: sampler, coords: vec3<f32>, level: f32) -> vec4<f32>
  textureSampleLevel(texture: texture_cube<f32>, sampler: sampler, coords: vec3<f32>, level: f32) -> vec4<f32>
  textureSampleLevel(texture: texture_depth_cube, sampler: sampler, coords: vec3<f32>, level: L) -> f32  where: L is i32 or u32
  textureSampleLevel(texture: texture_2d<f32>, sampler: sampler, coords: vec2<f32>, level: f32, offset: vec2<i32>) -> vec4<f32>
  textureSampleLevel(texture: texture_2d_array<f32>, sampler: sampler, coords: vec2<f32>, array_index: A, level: f32) -> vec4<f32>  where: A is i32 or u32
  textureSampleLevel(texture: texture_depth_2d, sampler: sampler, coords: vec2<f32>, level: L, offset: vec2<i32>) -> f32  where: L is i32 or u32
  textureSampleLevel(texture: texture_depth_2d_array, sampler: sampler, coords: vec2<f32>, array_index: A, level: L) -> f32  where: A is i32 or u32, L is i32 or u32

**Comment by ben-clayton** [comment]
Created https://github.com/w3c/webcodecs/pull/622 to fix this

**Comment by ben-clayton** [comment]
PR landed.
