### ISSUE TITLE
Missing `filterable` texture format definiton

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#3684]
We say that a texture format needs to be `filterable` as defined in the "26.1.1. Plain color formats" table but the table doesn't include a "filterable" column.

https://github.com/gpuweb/gpuweb/blob/093b63a5338d69b8057296e12572f71663bdcf7e/spec/index.bs#L7737-L7738

I think we could just update the following line to say "filtered/blended".

https://github.com/gpuweb/gpuweb/blob/093b63a5338d69b8057296e12572f71663bdcf7e/spec/index.bs#L14099

**Comment by teoxoy** [comment]
Actually, I just realized that we only need to replace `filterable` with `blendable` since that section is talking about validation of `GPUColorTargetState/blend`.

**Comment by kainino0x** [comment]
Nicely fixable now because we added an explicit "blending" column in the table (#3833).

"Filterable" would implicitly means "Has the `float` sample type, not just the `unfilterable-float` sample type", so I'll write that out explicitly as well.
