### ISSUE TITLE
Render pipelines with no attachments shouldn't be allowed

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#3702]
I remember that we shouldn't allow render passes with no attachments, see #503. However the current spec doesn't have any validation for this. I would expect that we should validate for all of GPURenderPipeline/GPURenderPassEnoder/GPURenderBundleEncoder creation that the render pass layout is not empty.

Marking as editorial because the group previously agreed to this.

**Comment by kainino0x** [comment]
We have this for render passes (the linkage is a little confusing, something to clean up eventually)
> - If this.colorAttachments contains no non-null values:
>   - this.depthStencilAttachment must not be null.

and createRenderBundleEncoder:
> - If descriptor.colorFormats contains no non-null members:
>   - descriptor.depthStencilFormat must not be null.

But I think we are missing it from render pipelines.
