### ISSUE TITLE
Improve syntax authoring experience

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#3708]
The PR to improve visuals of syntax elements to be more accessible came at the cost of some authoring burden. It should be possible to reduce by script. I think of the following scripting flow:

```mermaid
graph TD
A[index.bs] -->|Extract grammar, do the tests, rewrite for readability| B[index.pre.bs]
B --> C[index.pre.html]
C --> D[index.html]
```

With approximately the following authoring experience:

```
while_statement :
  | `while` expression compound_statement
```

Furthermore, I think this PR should include following automation:
- Normalize (NFKC) WGSL spec sources (due to one author, same as the OP of this issue, using a few international keyboards, there are a few invisible code points, sorry about that!)
- Check inlined elements against listing in the spec instead of just linking without test
- Peg the naming of inlined elements except keywords (because those are words) to a reliable source, potentially Unicode's naming choices could be a good source and easy to implement

Thank you!

**Comment by mehmetoguzderin** [comment]
An assumption that leads to the original post: Bikeshed does not have a hook that could help us. The hook available for a later stage is not very flexible. But in case that changes, we could just hook into Bikeshed.

**Comment by dneto0** [comment]
>  Furthermore, I think this PR should include following automation

Please do only one thing in each PR.  That makes it easier to review.

**Comment by dneto0** [comment]
I should say I'm quite deep into addressing this.

I currently have a flow which:
* Can read the index.bs file
* Parses the plain text parts, and the Bikeshed grammar parts.  Alternately can read EBNF parts.
* Can emit any combination of:    the text parts, the Bikeshed grammar parts, equivalent EBNF parts; all in order.
     * Where the source-of-truth is either the input Bikeshed grammar parts or the input EBNF parts.

This flow can be run twice, first with Bikeshed as source-of-truth, then with EBNF as source-of-truth, to perfectly regenerate the original index.bs.  That means the parsing is correct enough to rely in EBNF as source-of-truth.


Where I'm headed with this, with feedback from @mehmetoguzderin and @alan-baker, is:
* pull the source of truth out to a single EBNF file
* Have a flow that generates Bikeshed fragments in separate files
* In the main index.bs bikeshed-include those separate files.

**Comment by dneto0** [comment]
Additionally, the EBNF source will be used to generate Treesitter grammar; replacing parts of the current extract-grammar.py
