### ISSUE TITLE
D3D12 does not support copying between textures of different dimensionality

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3723]
From https://crbug.com/dawn/1216#c9:

@RafaelCintron:
> Though the D3D12 API does not forbid copying between resources whose dimensionality does not match (1D rows <-> 2D rows, 1D rows <-> 3D rows, and 2D slices <-> 3D slices) the behavior is undefined unless you check the TextureCopyBetweenDimensionsSupported field of the D3D12_FEATURE_DATA_OPTIONS13 struct and find that it is true. The flaky behavior we're seeing is up to the whims of the driver.
> 
> To get portable behavior, we'll need to either forbid these operations for WebGPU v1.0 or workaround the limitations by copying the data first to a buffer and from the buffer to the final destination.

@austinEng:
> Wow - the fact that this is in D3D12_FEATURE_DATA_OPTIONS13 is a little discouraging.
"Minimum supported client	Windows 11, version 22H2; or DirectX 12 Agility SDK 1.6 or later"
> 
> perhaps we need to forbid this in the spec after all.

**Comment by shmookey** [comment]
Is this going to impact copying textures into a layered texture atlas? Could it be worked around by instantiating lower-dimensional textures as higher-dimensioned ones with a length of 1 on the unused dimensions?

**Comment by Kangz** [comment]
> Is this going to impact copying textures into a layered texture atlas?

Hopefully not since the atlas is a 2D array and the texture you copy from is 2D? That would keep working.

> Could it be worked around by instantiating lower-dimensional textures as higher-dimensioned ones with a length of 1 on the unused dimensions?

Unfortunately it can't be worked around for 2D <-> 3D because the mip level sizes are different.

**Comment by kainino0x** [comment]
Meeting: resolved to not change validation, and do the workaround - it's expected to eventually be ubiquitous since all D3D12 hardware already implements this for Vulkan (and/or Metal).

**Comment by kainino0x** [comment]
Closing because this was resolved "no change".
