### ISSUE TITLE
Metal doesn't allow writing frag_depth without a depth attachment

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#3728]
Issue discovered by @shrekshao in https://github.com/gpuweb/cts/issues/2115#issuecomment-1374231577:

> I saw when `@builtin(frag_depth)` being written in fragment shader with no DepthStencilState at createRenderPipeline on Metal backend is seeing the following Metal error
> 
> ```
> Error creating pipeline state depthAttachmentPixelFormat is not valid and shader writes to depth
>     at Initialize (../../third_party/dawn/src/dawn/native/metal/RenderPipelineMTL.mm:396)
>     at CreateRenderPipeline (../../third_party/dawn/src/dawn/native/Device.cpp:1617)
> ```
> 
> Same situation is accepted on D3D12 backend.
> 
> We have this topic investigated on Vulkan at https://github.com/gpuweb/gpuweb/issues/1013 but not on Metal? Shall we revisit this topic (maybe validate it or simply make Metal backend to force set depthStencilState?)

My reply there:

> This is a very useful find, and I think it needs to be raised to the group. Probably worth raising even if we have a workaround.
> 
> The past discussion on gpuweb/gpuweb#1013 seemed to be specifically about whether `depthWriteEnabled` was true, but this error looks like it's about whether the pipeline has a depth attachment at all. If I'm understanding correctly, I don't think it's possible to workaround this by setting Metal's depth stencil state: in order to silence this error we'd have to specify a depthAttachmentPixelFormat, and that would break compatibility with the Metal render pass (which wouldn't have a matching depth attachment).
> 
> The other workaround I can think of would be to remove the frag_depth from the generated shader at pipeline creation time, but we avoid doing things that force shader generation to happen later than createShaderModule.

**Comment by mwyrzykowski** [comment]
It seems like this should be an error but if we wanted to support it, a matching depth attachment could be created if it is missing at point of createRenderPipeline. Seems like it should be an error though to write the fragment depth with no depth attachment.

What is the use case of writing `@builtin(frag_depth)` without a depth attachment other than not creating a separate shader?

**Comment by kainino0x** [comment]
Meeting: resolved to add validation that frag_depth is not written if the pipeline doesn't declare a depth attachment [in WebGPU terms, I think this means a depth/stencil attachment format with a depth component].
(And also to not change validation for writing color attachments that don't exist in the pipeline.)

There was an idea to use Metal function constants to conditionally remove frag_depth at pipeline creation time, using the MSL feature "5.8.1.6 Function Constants with Elements of a Structure": "All OS: Using a function constant to identify that a structure element is optional; supported since Metal 2.0."
We haven't tested this but it may work if we want to lift this validation post-v1.

**Comment by kainino0x** [comment]
> It seems like this should be an error but if we wanted to support it, a matching depth attachment could be created if it is missing at point of createRenderPipeline. Seems like it should be an error though to write the fragment depth with no depth attachment.

I think it's more complicated than this. In order to patch this depth attachment in, we would:
- Arbitrarily choose a depth format to use when creating a pipeline that uses frag_depth but doesn't have a depth format already
- When you setPipeline, retroactively(!) patch the surrounding render pass to include an attachment of that type
- Which is impossible if it already had a depth attachment
- And also might impact compatibility with other render pipelines used inside the same render pass

> What is the use case of writing `@builtin(frag_depth)` without a depth attachment other than not creating a separate shader?

I think that's basically it. I don't think depth testing can be enabled at all if there's no attachment, not that it would be useful since there would be no depth buffer to test against.
