### ISSUE TITLE
copyTextureToBuffer, should we add native API limits or workaround them?

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#3729]
In Metal, an undocument limit of copying a texture to a buffer is that you pass a `bytesPerRow` value but that value can not be more than the maxTextureDimension. In other words, if you're copying from an r16 texture and the maxTextureDimension is 16384, then `bytesPerRow` must be less than or equal to 32768.

I have not checked if other APIs have a similar limit.

Should WebGPU also have that limit or should implementions work around it (for example by copying a row at a time)

**Comment by Kangz** [comment]
Other APIs don't have this limit: Dawn has tests that trigger the Metal debug device, but work with validation layers on other APIs.

IMHO that's a corner case and we can copy row by row in this case but let's discuss in the group!

**Comment by litherum** [comment]
https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400756-copyfromtexture?language=objc

> destinationBytesPerRow
> The stride in bytes between rows of the source texture memory. The value must be a multiple of the source texture's pixel size, in bytes. The value must be less than or equal to 32,767 multiplied by the source texture’s pixel size.

**Comment by greggman** [comment]
> destinationBytesPerRow
> The stride in bytes between rows of the source texture memory. The value must be a multiple of the source texture's pixel size, in bytes.

So for example 1byte for r8unorm, 4bytes for rgba8unorm, 16bytes for rgba32flaot

> The value must be less than or equal to 32,767 multiplied by the source texture’s pixel size.

Unclear what "source texture's pixel size" is since the sentence does not end with "in bytes". Is it number of pixels?, bytes per pixels?, min dimension?, max dimension? But it's mostly irrelevant

It's missing the actual limit which is `maxTextureDimension * bytesPerPixel`

So for example if you have a 3D texture, the maxTextureDimension is 2048. If you have a r8unorm texture then `destinationBytesPerPixel` must be less than 2048. If you have a r16unorm texture then `destinationBytesPerPixel` must be less than 4096. Etc... That is undocumented but is what the validation layer complains about.

**Comment by kainino0x** [comment]
2023-01-11 meeting consensus: do the workaround, no added validation.
