### ISSUE TITLE
for to loop transformation example seems incorrect

### ISSUE THREAD

**Issue by vincentisambart** [gpuweb/gpuweb#3740]
In the "for to loop transformation" example, the `loop` version of the code has the `a` variable declared as if it was part of the `for` initialization, but in the `for` version, `a` is just used, not declared anywhere.

Looking at the Git history, the `var a: i32 = 0;` (`var a : i32 = 0;` at the time) has been added in #1333. It seems it was added to make the WGSL valid. However, if `var a` is added somewhere it should not be with `i`, at the scope added for the `for` declarations, but for example before the preceding `{`. And if it is in the `loop` version of the code, I think it should also be in the `for` version.

**Comment by munrocket** [comment]
@vincentisambart can you just create PR where you declaring `a` and moving `{` for example?

**Comment by vincentisambart** [comment]
@munrocket Done: #3742
