### ISSUE TITLE
Lookahead disambiguation of less-than vs template argument list

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3746]
Google have been discussing options for disambiguating binary-op less-than vs template argument list, as both use the `<` token.

For example, consider the expression: `A ( B < C, D > ( E ) )`. Should this parse as `A` being called with the two arguments: `B < C` and `D > ( E )`, or as a single argument of `B< C, D >( E )`?

https://github.com/gpuweb/gpuweb/issues/3739 proposes changing the syntax for template argument lists, which is a viable solution. However, this would be a very large language change to be making at this stage, and we've heard from a number of people that the proposed syntax(es) are far less liked than what we have today.

This is a proposal to keep the template argument list syntax (`T<a, b, c...>`), and to disambiguate by parser look ahead.

The disambiguation algorithm applies at *parse time*, and is as follows:

---

When you encounter an identifier followed by a `<`, begin a look-ahead to disambiguate between a less-than binary operation (`LESS_THAN`) and the start of a template list (`TEMPLATE`). Starting with the next token following the `<`:
1. If the next token is `>` followed by `(`, `.` or `>` then resolve to `TEMPLATE`, otherwise continue scanning.
2. If the next token is `(` or `[` scan forward until you find the balanced closing token, and continue scanning. If the closing token was not found before the end of the statement, then resolve to `LESS_THAN`.
3. If the token is an identifier, followed by a `<`, then recursively disambiguate the `<`, and continue scanning from the final look-ahead position of the recursive call.
4. Resolve to `LESS_THAN` if the next token is any of: `)`, `]`, `;`, `{` or you reach the end of the file.
5. Progress to the next token, and repeat.

---

Example expressions with the parsed template arguments highlighted, when parsing using this algorithm:

```ts
a( b<c,d>(e) )
    ╰───╯
```
```ts
a< b>c >(d);
 ╰─────╯
```
```ts
a< b<c, d<e> >(f);
         ╰─╯
    ╰────────╯
```
```ts
a< b<c>() >();
    ╰─╯
 ╰────────╯
```
```ts
a < b<c>();
     ╰─╯
```

---

Traits of the algorithm:

* In an ambiguous case, the parser will lean towards parsing as a template argument list.
* The "tightest" argument list will be parsed. e.g. `a<b<c>();` will parse as `a` _less-than_ `b<c>()`, and **not** as `a` with the template argument `b` _less-than_ `c`.
* The algorithm only considers lexed tokens, and does not use resolved symbol information, so can trivially plug into a parser without requiring out-of-order symbol resolution.
* The algorithm will match `a<b>.c` as a template argument, to allow possible future support of type-members.

---

[A minimum implementation of this algorithm can be found here](https://dawn.googlesource.com/dawn/+/refs/changes/02/117202/8/src/tint/reader/wgsl/parser_impl.cc#2956).

Note that this algorithm does not consider the resolved symbols, and can be applied purely at parse time (or as a pass on the token stream).

As this algorithm is a heuristic for disambiguation, there are a few places where it may decide to parse an intended less-than as a template argument list, however the cases where this happens are **very** infrequent, as it requires comma-separated expressions and certain tokens after the `>` to trigger. I've checked the entire corpus of WGSL shaders that are available to me, and have not found a false-positive (with exception of contrived unit tests).

If the parser treats an intended less-than as a template argument list, then it should be fairly trivial to add diagnostics to make it clear what went wrong. Fixing these parse issues is a matter of adding parentheses. For example, to fix `A(B<C, D>(E))` you'd either wrap `B<C` in parentheses, or remove the parentheses from `(E)`.

Lookahead is technically unbounded, but will stop at the first `;` (and could be made to terminate earlier with token refinement).

With memoization, algorithmic complexity is linear.

Most importantly - this fixes the ambiguity without changing the syntax.

**Comment by dneto0** [comment]
I was playing with a toy grammar and found something slightly surprising.  Hopefully it's not a result of the simplification.

Related: experiment in this PR: https://github.com/gpuweb/gpuweb/pull/3748 

This is a toy grammar with a generic template-list syntax buried in it:

```
        L = S*

        S = E2 ';'

        E2 =
          E2 '<' E1
        | E2 '>' E1
        | E1

        E1 =
          E0
        | E1 '+' E0

        E0 =
          '(' E2 ')'
        | '[' E2 ']'
        | '{' E2 '}'
        | I
        | E1 '<' LIST '>' '(' LIST ')'
        # Things break if we try this:
        # E2 '<' LIST '>' '(' LIST ')'

        LIST =
          ( E2 LISTEND ? )?

        LISTEND =
          ',' LIST ?

        I = 'a'

```

The interesting line is; `E1 '<' LIST '>' '(' LIST ')'`
This grammar has *no* LALR1 conflicts. It's just fine.

However, if we generalize this by allowing E2 (the top level expression) in the template syntax, then a parsing conflict arises.
That is, this doesn't work:   `E2 '<' LIST '>' '(' LIST ')'`

**Comment by dneto0** [comment]
> This grammar has _no_ LALR1 conflicts. It's just fine.

Ha never mind. Had a bug.    (oops!)

**Comment by ben-clayton** [comment]
Updated the top comment to include examples and traits of the algorithm.

**Comment by dneto0** [comment]
I'm slightly concerned about the condition of "end of statement", and braces are not significant in the algorithm.

Some statements go a long way, or aren't terminated with a semicolon.
E.g. struct decl,  and most control flow things like "if", "for", "switch".

Consider this code snippet:
```
var a:i32;
var b:i32;
if   a < b { } else if a > (b) {}  else { x = 1; }
```
In today's WGSL, it sets x to 1, since a equals b (and both equal zero).

But the disambiguation algorithm will deduce `b { } else if a` as a template argument.

**Comment by ben-clayton** [comment]
The list of tokens to stop at in `4.` can be expanded to anything that isn't a token used by an expression. I believe `{` could easily be added to the list in `4.`, avoiding unnecessary lookahead.

**Comment by ben-clayton** [comment]
I've been working on another lookahead implementation that:
a. Acts as a single-pass token list transform, with no recursion.
b. Does not produce different tokens for expression-context and type-context.

I believe this supersedes the proposed algorithm above, so I'll close this issue and reopen when I've got all my ducks in a row.
