### ISSUE TITLE
Are padding bytes between matrix columns preserved for storage buffer writes?

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#3753]
In #1747, we resolved to preserve padding bytes for structures and between array elements. The spec now says:

> Memory operations on structures and arrays will not access padding memory locations.

Do we also need to preserve padding bytes between the columns of a matrix when it is inside an array or structure? What about a matrix that is _not_ inside an array or structure?

Consider:
```
@group(0) @binding(1) var<storage, read_write> buffer : mat3x3<f32>;

var<workgroup> wgvar : mat3x3<f32>;

@compute @workgroup_size(1)
fn () {
  buffer = wgvar;
}
```
The matrix in `wgvar` will be zero-initialized, but I'm not sure that the zero-initialization is guaranteed to extend to the padding bytes between columns (is it?). If it isn't, then when we copy the whole matrix to the storage buffer we may copy some uninitialized data from `workgroup` storage to our host-visible storage buffer, which is presumably a security concern.

Similarly, what about trailing padding for a storage buffer declared as a `vec3<>` type that isn't contained inside an array or structure:
```
@group(0) @binding(1) var<storage, read_write> buffer : vec3<f32>;
```
This has 4 bytes of trailing padding. Should those bytes be preserved when we write to the buffer?

**Comment by litherum** [comment]
RESOLVED: Preserve padding bytes within vector and matrices.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-02-07-minutes#are-padding-bytes-between-matrix-columns-preserved-for-storage-buffer-writes-3753">WGSL 2023-02-07 Minutes</a></summary>

* JP:  We are tentatively going to propose to preserving padding bytes between matrix columns and at end of vec3.  In analogy with arrays and structs.  Tint implementation would *not* have to scalarize all the writes.
* JB: So the padding there is the same as we’re handling for structs. 
* JP : We have to decompose writes into column writes. 
* MM: Is there anything to do?
* JP: Spec only talks about padding bytes in structs and arrays, silent on matrices.    So spec does need an update.
* **_Resolved needs spec._**
* JP: I’ll shout if something goes wrong implementation-wise.

</details>
