### ISSUE TITLE
Remove rule about `n` in `@align(n)` needing to be a multiple of the `RequiredAlignOf`

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3756]
https://www.w3.org/TR/WGSL/#attributes states: 

> If `align(n)` is applied to a member of `S` with type `T`, and `S` is the [store type](https://www.w3.org/TR/WGSL/#store-type) or contained in the store type for a variable in address space `C`, then `n` [must](https://www.w3.org/TR/WGSL/#shader-creation-error) satisfy: <code>n = k × [RequiredAlignOf](https://www.w3.org/TR/WGSL/#requiredalignof)(T,C)</code> for some positive integer k.

This rule is unnecessary, as https://www.w3.org/TR/WGSL/#address-space-layout-constraints states:

> Structure members of type `T` [must](https://www.w3.org/TR/WGSL/#shader-creation-error) have a byte offset from the start of the structure that is a multiple of the <code>[RequiredAlignOf](https://www.w3.org/TR/WGSL/#requiredalignof)(T, C)</code> for the address space `C`:
>
> <code>[OffsetOfMember](https://www.w3.org/TR/WGSL/#offsetofmember)(S, M) = k × [RequiredAlignOf](https://www.w3.org/TR/WGSL/#requiredalignof)(T, C)</code>
> Where `k` is a positive integer and `M` is a member of structure `S` with type `T`

So, if you provided an explicit `@align` value that misaligned a member w.r.t. the address space usage, then this would be caught by the layout validation anyway.

The rule also seems broken, as it can actually prevent you from specifying the **default alignment** for a given type:

```ts
struct S { i : i32 } // AlignOf(S) == 4
struct DefaultAlignment { s : S } // AlignOfMember(DefaultAlignment.s) == 4 - no errors
struct ExplictAlignment { @align(4) s : S } // error: 4 not a multiple of 16 (RequiredAlignOf(struct, uniform))
@group(0) @binding(0) var<uniform> happy : DefaultAlignment;
@group(0) @binding(1) var<uniform> sad : ExplictAlignment;
```

Finally, if we were to remove this validation rule, `@align(1)` could be used for tight-packing. The offset validation would still ensure that the layout is valid for the given address space usages. This would be handy for the day we support relaxed layout validation.

**Comment by dneto0** [comment]
I agree it's redundant.  On those grounds alone it should be removed.

Agreed that an align attribute with tighter (smaller) numbers is the forward-looking plan for tigher-than-ordinary packing. That would relax the rules around struct member offset and array strides.

**Comment by dneto0** [comment]
This is editorial.

**Comment by dneto0** [comment]
>  The rule also seems broken, as it can actually prevent you from specifying the default alignment for a given type:

I think that's works-as-intended. Because @align(4) forces the computed alignment of `s` in this case to be 4.
But that's wrong because consider this:
```rust
struct ExplictAlignmentAndScalar { @align(4) s : S, a: i32 } // error: 4 not a multiple of 16 (RequiredAlignOf(struct, uniform))
```
It's correct to say that `@align(4)` is wrong there. Because if we did allow it then the "actual" alignment of `s` would be 4, and its size is 4.   So `a` would be placed at offset 4. Which is wrong.

**Comment by ben-clayton** [comment]
> But that's wrong because consider this:
> 
> ```rust
> struct ExplictAlignmentAndScalar { @align(4) s : S, a: i32 } // error: 4 not a multiple of 16 (RequiredAlignOf(struct, uniform))
> ```
> 
> It's correct to say that `@align(4)` is wrong there. Because if we did allow it then the "actual" alignment of `s` would be 4, and its size is 4. So `a` would be placed at offset 4. Which is wrong.

I don't understand this.  `@align(4)` is not "wrong" - that is the natural alignment of `S`. In your example it doesn't matter what value you give the `@align`, as `s` is the first member of the structure - it won't change the layout in any way, and `a` will always be at offset 4. So the _multiple of the RequiredAlignOf_ rule, gives us nothing here.

**Comment by dneto0** [comment]
Sorry, I didn't say what I meant to say.

```
struct ExplictAlignmentAndScalar { @align(4) s : S, a: i32 } // on its own, this is fine.  

 // Error is triggered because layout rules for uniform.  
// If this var had been in 'storage', and there were no other uses of the type, there is no problem.
@group(0) @binding(2) var<uniform> bad : ExplicitAlignmentAndScalar; 
      
struct ExplictAlignmentAndScalarCOPY { @align(4) s : S, a: i32 } // on its own, this is fine.   
fn foo() {   var this_is_fine: ExplicitAlignmentAndScalarCOPY; } // this is fine
```

So I think we are in agreement:
* The rule is not freestanding.  It is a conseqence of the combining the rules in the Memory Layout section.
* In the PR the note still is a rule about use in a particular address space.
