### ISSUE TITLE
Simplify resolveTarget validation language

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#3767]
Line to be simplified:

> The sizes of the subresources seen by this.resolveTarget and this.view must match.

Thought process:

- `resolveTarget` and `view` must both be [renderable texture view](https://gpuweb.github.io/gpuweb/#abstract-opdef-renderable-texture-view)s
- a subresource for a 2d texture is uniquely identified by a mipmap level, array layer and aspect
- renderable texture views only have 1 mip level and 1 array layer
- the aspect of `resolveTarget` and `view` is "color"

=> both `resolveTarget` and `view` point to only 1 subresource each; the size of the subresource being the same as `renderExtent`

Proposed language change:

this.view.[[renderExtent]] and this.resolveTarget.[[renderExtent]] must match.

**Comment by Kangz** [comment]
This might be different with layered rendering in the future (where you can choose which layer of a view gets written to with a vertex output) but the validation can be updated then, and layered rendering might not even support multisampling.
