### ISSUE TITLE
Clarification of `stencil8` texel block size

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#3768]
> The texel block size of each GPUTextureFormat is constant except for "stencil8", "depth24plus", and "depth24plus-stencil8".

But `stencil8` has a constant texel block size (according to the table in [Depth-stencil formats](https://gpuweb.github.io/gpuweb/#depth-formats)).

> The stencil8 format may be implemented as either a real "stencil8", or "depth24stencil8", where the depth aspect is hidden and inaccessible.

Even if implemented as a `depth24stencil8`, the texel block size of the stencil aspect should be 1.

I guess the text refers to the whole texture not having a constant texel block size but it's not clear since `depth32float-stencil8` is in the same boat but not mentioned.

**Comment by kainino0x** [comment]
Good catch. I think the language also needs some updating to clarify that the texel block size is per-aspect.
