### ISSUE TITLE
Allow GPUFence.onCompletion to be called with any value

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#377]
I think web developers should be allowed to wait on a fence without signaling the value first. They should be responsible for a never-settling promise.

What I'm asking is to NOT reject `onCompletion` when called with a value that is greater than the last signaled value.

```js
const adapter = await navigator.gpu.requestAdapter();
const device = await adapter.requestDevice();
const queue = device.getQueue();

const fence = queue.createFence({ initialValue: 1 });
setTimeout(_ => {
  queue.signal(fence, 2);
}, 1000);

await fence.onCompletion(2);
// Currently, it rejects with an error ;(
```

**Comment by Kangz** [comment]
From what I remember the original design had this constraint so callbacks would complete in finite time. This might not be needed (except we need to figure out what happens if the device is lost before the callback is fired.) However that same constraint will be very required when/if we use fences to synchronize between multiple queues because we want to guarantee there are no deadlocks and GPUs can always keep moving forward with some work.

**Comment by kainino0x** [comment]
[Original design](https://github.com/gpuweb/gpuweb/blob/master/design/TimelineFences.md) for context.

**Comment by litherum** [comment]
I’d love to hear more about the motivation of this request. There isn’t much explanation here.

**Comment by beaufortfrancois** [comment]
There may be underlying GPU constraints I don't foresee. With that said, rejecting a promise because a signal wasn't sent before doesn't make sense from _my_ web developer perspective.

It feels like the current behaviour creates more friction.

Could you explain why it is beneficial for web developers to have this promise to reject **early**?

**Comment by kainino0x** [comment]
This change makes sense to me. Unlike GPU wait, promise resolution is never blocking, so I don't think we need to be strict here. The only harm I can see in creating promises that may never resolve is that applications could introduce asynchronous deadlocks in their code. But it doesn't seem any more problematic than any other async JS deadlock to me.

**Comment by Kangz** [comment]
Closing, fences have been removed.
