### ISSUE TITLE
Lookahead disambiguation of less-than vs template argument list (v2)

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3770]
## Background and motivation

Google have been discussing options for disambiguating binary-op less-than / greater-than vs template argument list, as both use the `<`, `>` tokens.

For example, consider the expression: `A ( B < C, D > ( E ) )`. Should this parse as `A` being called with the two arguments: `B < C` and `D > ( E )`, or as a single argument of `B< C, D >( E )`?

WGSL currently uses keywords for all types that take template arguments. To help "future-proof" the language and allow for new templated types post V1 (and possibly support user-templated functions), we need to fix this grammar ambiguity.

**This is a proposal to keep the WGSL template argument list syntax (`T<a, b, c...>`), and resolve the ambiguity through token processing.**

https://github.com/gpuweb/gpuweb/issues/3739 and https://github.com/gpuweb/gpuweb/pull/3765 propose fixing the ambiguity by changing the syntax for template argument lists, which are viable solutions. However, this would be a very large language change to be making at this stage, and we've heard from a number of people that the proposed syntax(es) are far less liked than the syntax we already have today.

Note: This proposal entirely replaces the (very similar) proposal in https://github.com/gpuweb/gpuweb/issues/3746.

## Algorithm

The proposal introduces a new token transformation between lexing and parsing, which may replace pairs of `<` and `>` tokens with two new `template_args_left` and `template_args_right` tokens, if they match the disambiguation rule. The WGSL grammar can then be written to depend on `template_args_left` and `template_args_right`, instead of the ambiguous `<` and `>` tokens. 

The disambiguation rule can be described as: 

*  A pair of `<` and `>` tokens will be replaced with the template argument list tokens `template-args-left` and `template-args-right`, when both tokens are declared within the same parenthesis and bracket nesting depth†, and there are no expression-terminating tokens (`;`, `{`, `=`, `:`) nor binary short-circuiting operators (`&&`, `||`) between the `<` and `>`.

† The "parenthesis and bracket nesting depth" is incremented for each `(` and `[`, and decremented for each `)` and `]`.

## Psuedocode

Psuedocode for the token transform:

```c++
// The current expression nesting depth.
// Each '(', '[' increments the depth.
// Each ')', ']' decrements the depth.
int expr_depth = 0;

// A stack of '<' tokens.
// Used to pair '<' and '>' tokens at the same expression depth.
struct StackEntry {
    Token* token;    // A pointer to the opening '<' token
    int expr_depth;  // The value of 'expr_depth' for the opening '<'
};
Stack<StackEntry> stack;

// Iterate through all the tokens in the program...
foreach token, next_token in tokens {
    if (token IS identifier) AND (next_token IS '<') { 
        // Potential start to a template argument list.
        // Push the address-of '<' to the stack, along with the current nesting expr_depth.
        push (address-of next_token, expr_depth) to stack;
    } else if token STARTS_WITH '>' {
        // Note: Depending on your lexer - you may need split '>>', '>=', '>>='.
        // MaybeSplitToken() splits the left-most '>' from the token, updating 'tokens'
        // and returning the first token ('>').
        // If the token is not splittable, then MaybeSplitToken() simply returns 'token'.
        // As 'tokens' is updated with the split tokens, '>>=' may split to ['>', '>='], then
        // on the next iteration again to ['>', '='].
        token = MaybeSplitToken(token);

        if stack.top.expr_depth EQUALS expr_depth {
            // '<' and '>' at same expr_depth, and no terminating tokens in-between.
            // Template argument list matched.
            // Replace '<' as template-args-left and '>' as template-args-right
            replace stack.top.token with template-args-left
            replace token           with template-args-right
            pop stack // '<' consumed
        }
    } else if token IS_ANYOF ['(', '['] { 
        // Entering a nested expression.
        increment expr_depth
    } else if token IS_ANYOF [')', ']'] { 
        // Exiting a nested expression
        // Pop the stack until we return to the current expression expr_depth
        while stack.top.expr_depth EQUALS expr_depth {
            pop stack
        }
        decrement expr_depth
    } else if token IS_ANYOF [';', '{', '=', ':'] {
        // Expression terminating tokens (non-exhaustive).
        // No opening template list can continue across these tokens, so clear
        // the stack and expression depth.
        expr_depth = 0;
        clear stack;
    } else if token IS_ANYOF ['||', '&&'] {
        // Exception tokens for template argument lists.
        // Treat 'a < b || c > d' as a logical binary operator of two comparison operators
        // instead of a single template argument 'b||c'.
        // Requires parentheses around 'b||c' to parse as a template argument list.
        while stack.top.expr_depth EQUALS expr_depth {
            pop stack
        }
    }
}
```

## Traits

* In an ambiguous case, the parser will lean towards parsing as a template argument list.
* The "tightest" argument list will be parsed. e.g. `a<b<c>();` will parse as a less-than `b<c>()`, and not as a with the template argument `b` less-than `c`.
* The algorithm only considers lexed tokens, and does not use resolved symbol information, so can trivially plug between a lexer and parser without requiring out-of-order symbol resolution.
* Supports the possible future language features:
  * Templated type / expression user functions: `f<int, 32>()`
  * Templated type members: `vec2<i32>.width`, `f32.smallest`
  * Templated constants: `smallest_value<f32>`

Example expressions with the parsed template arguments highlighted, when parsing using this algorithm:

```ts
a<b>(c);
 ╰─╯
```
```ts
a( b<c, d>e )
    ╰────╯
```
```ts
a< b<c, d<e> >(f);
         ╰─╯
    ╰────────╯
```
```ts
a< b<c> >();
    ╰─╯
 ╰──────╯
```
```ts
a < b<c>();
     ╰─╯
```

## Implementation

This proposal is implemented in Tint with these two changes:
* [tint/reader/wgsl: Add ClassifyTemplateArguments()](https://dawn-review.googlesource.com/c/dawn/+/117208)
* [tint/reader/wgsl: Use ClassifyTemplateArguments()](https://dawn-review.googlesource.com/c/dawn/+/117210)

## Testing

This implementation has been tested with thousands of hand-crafted WGSL shaders. There have been no cases found where a less-than / greater-than expression was incorrectly parsed as a template argument list.

## Breakages

Function calls and type constructors of the form `a( b<c, d>e )` will be treated as a template argument list, which is a breaking change - however this pattern appears infrequent in real world code.
Implementations can guide the developer in this situation. For example, [with this change](https://dawn-review.googlesource.com/c/dawn/+/117210), Tint will emit:

```
test.wgsl:4:9 error: '<' treated as the start of a template argument list, which is not supported for
user-declared types or functions. If you intended less-than, wrap the expression in parentheses
    a(b < c, d > e);
        ^
```

**Comment by dneto0** [comment]
I'd quibble with this line:

      else if token IS '>' {

It's more like

     else if token.startswith('>') { ...

and then deal with token splitting explicitly, something like:

    } else if token.startswith('>') {
        
        // Lean towards recognizing templates as the tightest sequence.
        if stack.top.expr_depth EQUALS expr_depth {
            if token IS NOT '>' {
                push next_token onto the left of tokens;  // a.k.a. unshift in Perl
                // split the token.
                (token, next_token) = ('>', token.substr(1:))
            }
            // '<' and '>' at same expr_depth, and no terminating tokens in-between.
            // Template argument list matched.
            // Replace '<' as template-args-left and '>' as template-args-right
            replace stack.top.token with template-args-left
            replace token           with template-args-right
            pop stack // '<' consumed
        }
    }

**Comment by dneto0** [comment]
Actually my suggestion loses the ">=" in ">>=".

Is it this:

```
} else if token.startswith('>') {
    
    // Lean towards recognizing templates as the tightest sequence.
    if stack.top.expr_depth EQUALS expr_depth {
        if token IS NOT '>' {
            push next_token onto the left of tokens;  // a.k.a. unshift in Perl
            // split the token.
            (token, next_token) = ('>', token.substr(1:))
            push next_token onto the left of tokens;   /// this is the new line of code.
        }
        // '<' and '>' at same expr_depth, and no terminating tokens in-between.
        // Template argument list matched.
        // Replace '<' as template-args-left and '>' as template-args-right
        replace stack.top.token with template-args-left
        replace token           with template-args-right
        pop stack // '<' consumed
    }
}
```

**Comment by dneto0** [comment]
The exception for `||` and `&&` make sense because they are lower precedence operators than when you could see `<` or `>` used as comparisons.  So it's not just arbitrary.  There's a principle at work here.

**Comment by ben-clayton** [comment]
> I'd quibble with this line:
>   `else if token IS '>' {`

I tried to keep token splitting out of this, it's a complexity that distracts from what the algorithm is doing. I tried to cover this complexity with `// Note: Depending on your lexer - you may need split '>>', '>=', '>>='.` It's entirely possible an implementation may have their lexer  produce pre-split tokens, and parsers could consume sequences of tokens, in which case this is all you'd have to do here.

**Comment by dneto0** [comment]
>  It's entirely possible an implementation may have their lexer produce pre-split tokens, and parsers could consume sequences of tokens, in which case this is all you'd have to do here.

I believe most tokenizers go for "longest match", and that's the default for regexp matches.  So for my own comfort it's useful to work through the details in that situation.

But point taken.

**Comment by ben-clayton** [comment]
Updated with a call to `MaybeSplitToken()`, with a big comment. Now pretty much matches Tint's implementation.

**Comment by jimblandy** [comment]
So the expression `x<y>>z` would parse as `(x<y>) > z`, and not `x < (y >> z)`, right? This seems like a perfectly ordinary thing to write in a shader.

**Comment by ben-clayton** [comment]
Correct:

```
fn f(a : u32, b : u32, c : u32) {
    let x = a<b>>c;
}
```

```
test.wgsl:2:14 error: '<' treated as the start of a template argument list, which is not supported for
user-declared types or functions. If you intended less-than, wrap the expression in parentheses
    let x = a<b>>c;
             ^
```

So you'd have to parenthesize `b>>c`, which is not that dissimilar to the requirements to parenthesize `a>>b>>c`:

```
test.wgsl:2:14 error: mixing '>>' and '>>' requires parenthesis
    let x = a>>b>>c;
             ^^^^^
```

**Comment by mehmetoguzderin** [comment]
I have a question @ben-clayton @dneto0 @alan-baker about implementation. Is it impossible to get very similar behavior with a combination of prec.dynamic, prec.left, prec.right to trigger GLR parsing? I wonder if we can have a set of edge case examples to test against trying to achieve scoring in that framework, which follows an established theory. BTW, name conflict sounds scary, but it just is the way to trigger GLR for that specific rule.

Example: https://github.com/mehmetoguzderin/gpuweb-20230201-glr/blob/main/grammar.js

**Comment by mehmetoguzderin** [comment]
(And I'm sure there should be some BNF variants that include a nice notation for those GLR concepts)

**Comment by ben-clayton** [comment]
> I wonder if we can have a set of edge case examples to test against

These are tint's unittests for disambiguation:

https://dawn.googlesource.com/dawn/+/refs/heads/main/src/tint/reader/wgsl/classify_template_args_test.cc

I don't feel familiar enough with tree sitter to confidently answer your other questions.

**Comment by mehmetoguzderin** [comment]
@ben-clayton Perfect, thank you. If it is reasonable, then maybe we can try to phrase this algorithm in terms of GLR constructs, which not only simplifies Tree-sitter grammar but increases ecosystem compatibility (Bison, etc.).

**Comment by ben-clayton** [comment]
Please, be my guest.
The code proposed above was a reduction of the implementation, which is also my mental model. I assumed there were better ways to express this, but I'm no parser grammar expert.

**Comment by dj2** [comment]
I don't think we should block this on attempting to find some other grammar representation. We should land the algorithm and if we figure out a different way to write the same thing we can move that that later.

It's better to have the algorithm in the spec so folks can start to understand it and see the direction being followed.

We also have to make sure, if it's done as a grammar change, that the recursive descent grammar is maintained as that's what, I believe, everyone is implementing.

**Comment by ben-clayton** [comment]
+1 - I hope any grammar work here would not block landing this, but rather we can iterate with incremental improvements.

**Comment by mehmetoguzderin** [comment]
I didn't mean as a blocker.

> ... if it's done as a grammar change, ...

Isn't the PR going to change grammar anyway by removing tokens?

**Comment by mehmetoguzderin** [comment]
I guess I didn't quite register how the potential space of expression within the spec limits by the recursive descent representation. The generics part will either refer to an external scanning algorithm, which will influence the grammar or live within a spelling that corresponds to well-studied GLR constructs. In either spelling, this section of the grammar is probably going to be an exception for any analysis of recursive descent form and not influence the notation there much.

**Comment by dj2** [comment]
I believe the only grammar change here is adding tokens for the template start/end and using that for the templates. The actual algorithm happens as a pass _before_ the parser.

**Comment by dj2** [comment]
As long as we can convert to recursive descent (as David is already doing with the section at the end of the grammar), it's fine. We just have to make sure we maintain that section and it matches what the grammar is doing.

I don't know anything about GLR, so I don't know if there is a simple algorithm to map that back into something that can be processed as recursive descent.

**Comment by mehmetoguzderin** [comment]
@dj2 in the draft PR, there's `fully_qualified_ident`, and that facilitates its presence by external tokens `_disambiguate_template`, `_template_args_start`, `_template_args_en`. Note that these live right within the grammar itself, it is just that they are external.

If we use GLR, it'd be very similar to that, only with no external functions but rather some macro-like annotations before or after the tokens.

**Comment by mehmetoguzderin** [comment]
So, what I'm meaning is that, if these external tokens do map to recursive descent, then I guess macro annotations can be simply ignored.

**Comment by mehmetoguzderin** [comment]
(ignored = also work fine, not discard as a way of spelling)

**Comment by dj2** [comment]
I think we should split this into two separate issues. This issue is about the spec text to describe the look-ahead algorithm, and adds the `TemplateArgStart` and `TemplateArgEnd` tokens into the grammar. Outside of that, I believe the grammar can stay as it is currently.

A second discussion is removing they keywords and all the grammar work to have the `fully_qualified_ident` and remove the keywords themselves. I don't know where that work falls on the post/pre-v1 marker. We just landed _more_ reserved keywords, so it seems orthogonal to this issue.

**Comment by mehmetoguzderin** [comment]
Isn't the point of look-ahead to remove vec, mat, etc. from grammar in v1?

**Comment by dj2** [comment]
Yes, but they are discrete steps and can be landed separately.

**Comment by mehmetoguzderin** [comment]
I've thought the initial PR would be like the following draft in combination with algorithm described in spec: https://github.com/gpuweb/gpuweb/pull/3794

Either way, I think it is clear that recursive descent mapping will likely make this a special case, similar to pattern token, and should not be blocker to landing either the form in that draft or a potential GLR expression.

**Comment by dneto0** [comment]
> I've thought the initial PR would be like the following draft in combination with algorithm described in spec

Let's take small steps, please.  That may be the ultimate destination, but that is not where the consensus is right now.

**Comment by mehmetoguzderin** [comment]
I certainly understand that. I just had a simple question- whether it is expressable in the form mentioned here https://github.com/gpuweb/gpuweb/issues/3770#issuecomment-1411047104 or not- nothing more. I don't see anything in my original comment, either dangering recursive descent or blocking at all.

Sorry for the inconvenience!!
