### ISSUE TITLE
Bytes per texel of `depth24plus-stencil8` could be 4 - 5

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#3771]
I think the bytes per texel of `depth24plus-stencil8` could be `4 - 5` instead of the current `4 - 8`.

On dx12 we use `DXGI_FORMAT_R24G8_TYPELESS` and its typed friends which are 4 bytes.
On vulkan we use `D24_UNORM_S8_UINT`/`D32_SFLOAT_S8_UINT` which are 4/5 bytes.
On metal we use `Depth24Unorm_Stencil8`/`Depth32Float_Stencil8` which are 4/5 bytes.

---

There is this note on metal's [`MTLPixelFormatDepth32Float_Stencil8`](https://developer.apple.com/documentation/metal/mtlpixelformat/mtlpixelformatdepth32float_stencil8?language=objc) format though.

> When using this format, some Metal device objects allocate 64-bits per pixel.

But I think this happens transparently since I see no way to query the actual size of `Depth32Float_Stencil8`.

**Comment by kainino0x** [comment]
The "bytes per texel" column is really about memory usage, and not anything visible to the API. It's technically non-normative. Indeed on some devices depth32float-stencil8 formats will have an 8 byte memory format, and that's what we intended to convey here.

I'll leave this open to see if we can explicitly mark this info non-normative and clarify its meaning.

**Comment by teoxoy** [comment]
Ah, I thought that `writeTexture` can accept a combined depth-stencil texture with aspect being "all" but I reread the spec and it seems not.

But I think there is a related issue with `depth24plus` and the depth aspect of `depth24plus-stencil8`; their texel block size can be either 3 or 4 and API users won't know how to compute `GPUImageDataLayout.bytesPerRow`.

**Comment by teoxoy** [comment]
> Ah, I thought that `writeTexture` can accept a combined depth-stencil texture with aspect being "all" but I reread the spec and it seems not.

What threw me off is that the 2 bullet points related to combined depth-stencil formats are not further nested like they are for `copyBufferToTexture` and `copyBufferToTexture`.

![image](https://user-images.githubusercontent.com/28601907/214839491-8a8a8260-e81b-4bd9-ab53-3053784e65fe.png)

**Comment by kainino0x** [comment]
> But I think there is a related issue with `depth24plus` and the depth aspect of `depth24plus-stencil8`; their texel block size can be either 3 or 4 and API users won't know how to compute `GPUImageDataLayout.bytesPerRow`.

depth24plus is not copyable: https://gpuweb.github.io/gpuweb/#copying-depth-stencil

**Comment by kainino0x** [comment]
Great feedback btw, will help clarify the spec here.

**Comment by teoxoy** [comment]
> depth24plus is not copyable: https://gpuweb.github.io/gpuweb/#copying-depth-stencil

Ah right 😅

**Comment by toji** [comment]
It seems to me like this was resolved a while back with #3922, which added the mentioned non-normative note about texel block sizes and expanded the tables with additional information about the copy size for a given aspect. Closing.

**Comment by teoxoy** [comment]
Ah yeah; and https://github.com/gpuweb/gpuweb/pull/4629 also resolved https://github.com/gpuweb/gpuweb/issues/3771#issuecomment-1404962834.
