### ISSUE TITLE
WGSL TR spec has unreadable text when `prefers-color-scheme: dark`

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3773]
When the browser `prefers-color-scheme: dark`, the TR spec has black-on-dark text for some code blocks.

For example, https://www.w3.org/TR/WGSL/#grammar-recursive-descent renders as:

![Screenshot 2023-01-25 at 11 40 06](https://user-images.githubusercontent.com/11505236/214554416-72f135e9-ab6a-4edd-b136-ea07e8148851.png)

Observe that the page background is white.

The same section appears different in [a non-TR build of the spec](https://gpuweb.github.io/gpuweb/wgsl/#grammar-recursive-descent):

![Screenshot 2023-01-25 at 11 41 36](https://user-images.githubusercontent.com/11505236/214554593-a5fc8c75-4250-4f1f-9cbe-c552040d4081.png)

I've confirmed that the inline `<style>` containing the following is missing from the TR version:

```css
@media (prefers-color-scheme: dark) {
    :root {
        --text: #ddd;
        --bg: black;

        --unofficial-watermark: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='400'%3E%3Cg fill='%23100808' transform='translate(200 200) rotate(-45) translate(-200 -200)' stroke='%23100808' stroke-width='3'%3E%3Ctext x='50%25' y='220' style='font: bold 70px sans-serif; text-anchor: middle; letter-spacing: 6px;'%3EUNOFFICIAL%3C/text%3E%3Ctext x='50%25' y='305' style='font: bold 70px sans-serif; text-anchor: middle; letter-spacing: 6px;'%3EDRAFT%3C/text%3E%3C/g%3E%3C/svg%3E");

...
```

It would seem that the style is broken when including the `--md-status="WD"`, when running:

`bikeshed --die-on=warning spec "wgsl/index.bs" "wgsl/index.bs.built.html" --md-group="gpuwg" --md-status="WD"`

The darkmode CSS appears to come from bikeshed itself, and I think it's being registered here:

https://github.com/tabatkins/bikeshed/blob/d514fe3bb0ea7c6cfc517b536c395860a19eb7ef/bikeshed/Spec.py#L117

I have no idea why `--md-status="WD"` would change things though.

**Comment by mehmetoguzderin** [comment]
I'm furthering this as part of the following issue, can we consider this a duplicate?
https://github.com/gpuweb/gpuweb/issues/3649

**Comment by mehmetoguzderin** [comment]
See following specific comment: https://github.com/gpuweb/gpuweb/issues/3649#issuecomment-1376880013

**Comment by ben-clayton** [comment]
#3649 seems specific to diagrams. I don't mind merging them, but the merged issue should be more general, otherwise it's likely to get closed without resolving the other issue.

**Comment by mehmetoguzderin** [comment]
@ben-clayton tried to phrase the overall tracking of that issue here https://github.com/gpuweb/gpuweb/issues/3649#issuecomment-1403886456

Thanks!

**Comment by ben-clayton** [comment]
@mehmetoguzderin - please also update the bug description to include the fact that text is unreadable. This is more severe than diagrams.
