### ISSUE TITLE
Why does depthClearValue default to 0.0?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#3777]
The default depth clear value in most graphics APIs is 1.0, as 1.0 is generally treated as furthest away.

But in the WebGPU specification, it specifies the default value is 0.0:
https://gpuweb.github.io/gpuweb/#dom-gpurenderpassdepthstencilattachment-depthclearvalue

Doesn't this mean most adopters will need to specify the depthClearValue of 1.0 defeating the purpose of the default value?

**Comment by Kangz** [comment]
A lot of developers also use reverse-depth. I think there's just a default because one was needed and 0 is the most obvious generic default. Do you want to bring this for discussion for v1 or fine with 0 being the default? (IMHO we shouldn't change a default like this anymore because we are tying up v1 and it doesn't seem important enough)

**Comment by mwyrzykowski** [comment]
I think we should bring it up for v1, maybe we should have no default at all?

The problem is a default like this is incredibly hard to change post-v1

**Comment by kainino0x** [comment]
I'd prefer not to default to 1.0 for a few minor reasons, though I agree the current default value is largely useless. In principle I'm fine with making it required, but I agree it's not really important enough to warrant the change. I'll note it's at least consistent with the color and stencil clear values that also default to zero.

**Comment by litherum** [comment]
resolved during the call today: Make `depthClearValue` required for now, and change the default to 0 in a few months just before shipping.

**Comment by kainino0x** [comment]
Or at least revisit. I'm not sure yet whether I will be in favor of defaulting to 1.

**Comment by kainino0x** [comment]
**Resolved** to make required for V1.
