### ISSUE TITLE
Publish WGSL CI artifact to a repo for reusability

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#3778]
Esp. for the attention of chairs @Kangz @kdashg , team contact @tidoust , WebGPU editors @kainino0x @litherum @toji , and WGSL editors @dneto0 @alan-baker . If you deem it appropriate, I'd like to act and realize migration quickly and then implement Actions-based sync.

When this repository had the inception of tree-sitter grammar, the idea was to propose to host it next to other tree-sitter projects for better visibility. I intermittently updated a repository for reference purposes until we found a better home for the derivative source, npm, and crates packages.

Yesterday, @DJMcNab brought up the following suggestion in the attachment to the important contribution found in the PR itself (in https://github.com/gpuweb/gpuweb/pull/3772#issuecomment-1403481899 comment):

> ... The only "official" documented way to acquire the grammar is to clone this repo and run generate-grammar.py, however that method is very inconvenient. It would be helpful if there were a "guarantee" of where to find it. A link in the spec to the aforementioned URL might be sufficient for that, although that seems slightly naïve. ...

This suggestion is a good initiative to act on the following clause of Community Group Charter (in https://gpuweb.github.io/admin/cg-charter.html URL):

> ... The Community Group may develop a continuous integration mechanism to validate the grammar of WebGPU Shading Language against syntactic ambiguities and potential mechanical issues with primary reliance on an open-source, commercially-permissive license tool that can report ambiguity and generate playgrounds that can run on the Web so that community can leverage and extend easily to enhance the ecosystem. Such software will be developed using the W3C Software and Document License. ...

Since this clause is analogous to CTS, I think we could use this organization for hosting and automatically syncing. I'd not like to point to a repository in my personal account as a reliable URL, and I think it'd significantly undermine community spirit.

Kind regards,
Thank you very much.

**Comment by Kangz** [comment]
Is the suggestion to have a `gpuweb/wgsl-grammar` repository that's automatically synced with WGSL grammar updates with GitHub Actions? Sounds like a good plan to me. Can you bring it up in a WGSL group call to double check?

**Comment by mehmetoguzderin** [comment]
@Kangz Yes, but maybe directly tree-sitter-wgsl for ease of reference (at crates, npm, etc.)? I'll bring up with at the call! Thank you very much!

**Comment by dneto0** [comment]
Related, I'm in the middle of addressing #3708, to simplify grammar authoring.
For currents status, see https://github.com/gpuweb/gpuweb/issues/3708#issuecomment-1410517978 

Certainly one of its outputs can be artifacts to automatically sync to a separate repository.

Are there other grammar formats that are desired, other than treesitter?  Can those be in the same repo? Should they?

**Comment by mehmetoguzderin** [comment]
@dneto0 I'd like to quickly do this if group OKs it, and then we could adapt to the new PR too. Should it be a blocker?

**Comment by dneto0** [comment]
I agree, either change can happen first.

**Comment by mehmetoguzderin** [comment]
Thanks a lot!

**Comment by litherum** [comment]
Because this information is derived information, the charter doesn't have to be updated for it. We can just YOLO commit to either or our own repo or a different repo no problem.

**Comment by mehmetoguzderin** [comment]
If @kdashg also approves, I can go ahead with realizing the initial version of this.

**Comment by mehmetoguzderin** [comment]
And thanks for inspecting the feasibility- I thought it would be rather trivial because it is a by-product of spec that's actively in the loop. Apologies for the burden this loads.

**Comment by mehmetoguzderin** [comment]
To note, I've thought `types` repo and CTS were enough precedents, and this could serve as some WGSL analogy due to the benefit. (Writing since I realize I didn't spell in the OP)

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#3778-placement-of-generated-grammar">GPU Web F2F 2023-02-16/17</a></summary>

* KG: can be in whatever repo we want.
* OD: I'll set up a repo and automation to push it.

</details>

**Comment by kdashg** [comment]
Can you change the title of this issue to something more descriptive? @mehmetoguzderin

**Comment by mehmetoguzderin** [comment]
@kdashg Sure thing, done. I've been setting up the repo, which should be done soon. Thank you very much.

**Comment by mehmetoguzderin** [comment]
We now have https://github.com/gpuweb/tree-sitter-wgsl with an initial form of grammar. After we fix the WASM build and do a last pass over grammar for generalization or naming, etc. I expect the syntax to become quite stable and hook the CI at that time, and also move the publishing source to be this repository directly. @DJMcNab please feel free to watch the repository for an advancing state of referentiability of the file. Thank you!

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-03-07-minutes#publish-wgsl-ci-artifact-to-a-repo-for-reusability-3778-">WGSL 2023-03-07 Minutes</a></summary>

* MOD: will do so.  Will fix the WASM build.  Syntax /grammar is stabilizing.   When it’s ready I’ll point the asking person to it.
* **MOD will close when ready.**

</details>
