### ISSUE TITLE
No public access to GPU Web meetings raw minutes

### ISSUE THREAD

**Issue by vincentisambart** [gpuweb/gpuweb#3780]
Looking at [the wiki page](https://github.com/gpuweb/gpuweb/wiki), anyone can open the Google Drive link to raw minutes of the [WGSL meetings](https://drive.google.com/drive/u/1/folders/1VWJ8tQx6lSLu3hNlNpJrZguk6vLVnoVq), but the [GPU Web meetings](https://drive.google.com/drive/folders/0B6yb23j9HAmDSDNTcWM0a0lxRU0) link require authentication.
As the WGSL one is public, and in the past I'm sure I've been able to see the WebGPU meeting minutes on Google Drive, it doesn't seem to be on purpose (If it's on purpose feel free to close this).

**Comment by Kangz** [comment]
There was a change in Google Drive at some point that made some links require authentification. I updated the link on that wiki page and it now works if I open it in a private browsing window.

**Comment by vincentisambart** [comment]
Thanks!
