### ISSUE TITLE
abs(INT_MIN) should be well-defined on integral types

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#3785]
Historically we've generally had different policies for integer operations vs floating point operations. We should make abs(INT_MIN) well-defined on integral types.

**Comment by dneto0** [comment]
I think this is already covered.

https://gpuweb.github.io/gpuweb/wgsl/#abs-float-builtin

> If e is a signed [integer scalar](https://gpuweb.github.io/gpuweb/wgsl/#integer-scalar) type and evaluates to the largest negative value, then the result is e.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-02-07-minutes#absint_min-should-be-well-defined-on-integral-types">WGSL 2023-02-07 Minutes</a></summary>

* MM: It is covered. Let’s close.
* 

</details>
