### ISSUE TITLE
It should be possible to unbind a bind group / vertex buffer

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#3787]
Right now, the [spec for `setBindGroup()`](https://gpuweb.github.io/gpuweb/#dom-gpubindingcommandsmixin-setbindgroup) says:

> bindGroup, of type [GPUBindGroup](https://gpuweb.github.io/gpuweb/#gpubindgroup), non-nullable, required

The [spec for `setVertexBuffer()`](https://gpuweb.github.io/gpuweb/#dom-gpurendercommandsmixin-setvertexbuffer) indicates the `buffer` argument is neither nullable nor optional.

As the spec stands right now, this isn't a big deal; if you set more bind groups or vertex buffers than the shaders use, that's no problem; the extra ones are just ... unused. There's no need to try to conserve bind group slots or vertex buffer slots inside a render pass, because the number of slots you get is fixed at device creation time.

This changes in the presence of https://github.com/gpuweb/gpuweb/issues/2749 . For that issue, the CG has a tentative agreement that we can add a new limit for the number of bind groups plus the number of vertex buffers. (This is because both bind groups and vertex buffers end up consuming the same Metal resources, so the new WebGPU limit is on the sum of them, rather than on each one individually).

But, once you have a limit on the sum of them, now they become worthy of being conserved - it's totally legit for an application to want to unbind a vertex buffer to try to make room for a bind group. So we should let people unbind stuff.

Mechanically, this proposal is just to let the bind group parameter to `setBindGroup()` and the vertex buffer parameter to `setVertexBuffer()` to be nullable.

**Comment by litherum** [comment]
While we're at it, we might want to change

```
dictionary GPUPipelineLayoutDescriptor : GPUObjectDescriptorBase {
    required sequence<GPUBindGroupLayout> bindGroupLayouts;
};
```

to

```
dictionary GPUPipelineLayoutDescriptor : GPUObjectDescriptorBase {
    required sequence<GPUBindGroupLayout?> bindGroupLayouts;
};
```

(this matches how vertex buffers are specified in the PSO descriptor)

**Comment by greggman** [comment]
Is this total what's bound or what's used? In other words, if it's just what's used then does the user need to unbind as long as their pipeline uses less than the combined max?

**Comment by litherum** [comment]
Consider a site running on a device which has 31 slots, and each slot could be populated by either a vertex buffer or a bind group.

Imagine this site wants to run a render pass that consists of 2 draw calls:
1. The first draw call wants to use a PSO that has 20 bind groups and 5 vertex buffers
2. The second draw call wants to use a PSO that has 20 vertex buffers and 5 bind groups

Both of these should conceptually be able to fit on the device no problem.

Their app code could be something like:
```
for i in 0 ..< 20:
    setBindGroup(i, …);
for i in 0 ..< 5:
    setVertexBuffer(i, …);
setPipeline(firstPipeline);
draw();

for i in 0 ..< 5:
    setBindGroup(i, …);
for i in 0 ..< 20:
    setVertexBuffer(i, …);
setPipeline(secondPipeline);
draw(); // but now we have 20 bind groups set and 20 vertex buffers set!
```

The tricky part here is that the `setBindGroup()` and `setVertexBuffer()` is called before setting the pipeline - which is totally legal! And it would be pretty unfortunate if we had to defer these calls until setPipeline() ends up happening.

**Comment by Kangz** [comment]
Aren't you going to need to do repacking in this case anyway? The vertex buffers can be sparsely set so you still need to reserve the whole range at the Metal level, or do repacking depending on what the pipeline uses.

That said, this issue is very similar to https://github.com/gpuweb/gpuweb/issues/2043 which I'm was planning to advocate for right after V1.

**Comment by litherum** [comment]
the `maxVertexBuffers` limit will be 31, and the `maxBindGroups` limit will also be 31. You're right that vertex buffers can be sparse, but only within the range of 0 ... 31.

The limit at https://github.com/gpuweb/gpuweb/issues/2749 has the form of "max index used" rather than "max count of" to avoid the repacking problem.

**Comment by kainino0x** [comment]
The subject of this issue presumes a particular solution (adding validation to setBindGroup and setVertexBuffer) to the problem raised by #3788 which found an issue with the previous resolution to #2749. I'd like to take a step back and consider the problem as a whole, so propose continuing the broader discussion on #2749.

**Comment by kainino0x** [comment]
> The limit at #2749 has the form of "max index used" rather than "max count of" to avoid the repacking problem.

If I'm understanding correctly(?) the problem is you need a mapping from bind group slots and vertex buffer slots into Metal buffer binding slots, and this must be pipeline-independent in order to do this mapping at `setBindGroup()`/`setVertexBuffer()` time. If you have `maxBuffersPlusVertexBuffersForVertexStage` = `maxBindGroups` = `maxVertexBuffers` = 31, there's no mapping of 31+31 binding indices into 31 slots.

Hence in order to have `maxBindGroups` + `maxVertexBuffers` > `maxBuffersPlusVertexBuffersForVertexStage` you must do packing at the pipeline level and know the pipeline before issuing binding calls to Metal.

**Comment by litherum** [comment]
I'm not following. Applications have to adhere to all limits. If maxVertexBuffers is 31, that doesn't mean the application is guaranteed to be able to use 31 vertex buffers, if there's another maxBuffersPlusVertexBuffersForVertexStage limit that exists.

The idea is, for Metal:
- maxBindGroups = 31
- maxVertexBuffers = 31
- maxBuffersPlusVertexBuffersForVertexStage = 31


but for SPIR-V,
- maxBindGroups = 4 (or whatever the real value is)
- maxVertexBuffers = 8 (or whatever the real value is)
- maxBuffersPlusVertexBuffersForVertexStage = 12 (because it's 4+8)

This means "you can use as many vertex buffers as you want, as long as A) that number is less than maxVertexBuffers, and B) the sum of that number with the number of bind groups you're using is less than maxBuffersPlusVertexBuffersForVertexStage"

**Comment by litherum** [comment]
Here's the implementation strategy I have in mind:

Metal has 31 slots. Each vertex buffer and bind group claims one of those slots. Thus `maxBindGroups` and `maxVertexBuffers` will both be 31. However, the app can't use more than 31 slots _in total_, so `maxBuffersPlusVertexBuffersForVertexStage` will also be 31 (actually, 29, because that's how the math turns out).

When a site asks us to `setVertexBuffer(n)`, we internally map that to claim slot number `n`. When a site asks us to `setBindGroup(n)`, we internally map that to claim slot number `30 - n`.

So, if a site says:
```
setVertexBuffer(0, ...); // Claims slot number 0
setBindGroup(0, ...); // Claims slot number 30 - 0 = 30
draw();
```
No collision. So far so good.

If a site says:
```
setVertexBuffer(20, ...); // Claims slot number 20
setBindGroup(10, ...); // Claims slot number 30 - 10 = 20. Collision!!
```
This can be detected trivially as an error at draw-call time, because the maximum vertex index (20) plus the maximum bind group index (10) is greater than `maxBuffersPlusVertexBuffersForVertexStage` (29).

This GitHub issue (re: unbinding) is about what happens _next_, after the collision occurred. Because it's impossible to unbind a vertex buffer, the maximum vertex buffer index _can never decrease_. Same for bind groups. So, once you're in this collision state, it's impossible to get _out_ of the collision state. That's where unbinding comes in.

## Part 2: Implementing unbinding

This is a little tricky, but I don't think it's that bad. Let's take that same collision program, but add in some unbinding:

```
setVertexBuffer(20, ...); // Claims slot number 20
setBindGroup(10, ...); // Claims slot number 30 - 10 = 20. Collision!!
unsetBindGroup(10); // Program is in a legal state again, but Metal's slot number 20 is supposed to be set back to the vertex buffer!
```
or even:
```
setVertexBuffer(20, ...); // Claims slot number 20
setBindGroup(10, ...); // Claims slot number 30 - 10 = 20. Collision!!
unsetVertexBuffer(20); // Program is in a legal state again, but Metal's slot number 20 is supposed to be set to the bind group!
```

You can handle this situation by having the `unset()` call actually _set_ the slot to the thing it's supposed to be set to after the unset call completes. You'd do this by remembering, for every slot, what the most recent vertex buffer that would claim that slot is, and what the most recent bind group that would claim that slot is. This would essentially take the form of `std::array<std::tuple<std::optional<VertexBuffer>, std::optional<BindGroup>>, 31> bindingState`.

Binding something does 2 things: (pseudocode)
```
setVertexBuffer(int index, VertexBuffer vertexBuffer) {
    int slot = index;
    setMetalSlot(slot, vertexBuffer);
    std::get<std::optional<VertexBuffer>>(bindingState[slot]) = vertexBuffer;
}
setBindGroup(int index, BindGroup bindGroup) {
    int slot = 30 - index;
    setMetalSlot(slot, bindGroup);
    std::get<std::optional<BindGroup>>(bindingState[slot]) = bindGroup;
}
```

Unbinding does 2 things: (pseudocode)
```
unsetVertexBuffer(int index) {
    int slot = index;
    if (auto bindGroup = std::get<std::optional<BindGroup>>(bindingState[slot]))
        setMetalSlot(slot, *bindGroup);
    std::get<std::optional<VertexBuffer>>(bindingState[slot]) = std::nullopt;
}
unsetBindGroup(int index) {
    int slot = 30 - index;
    if (auto vertexBuffer = std::get<std::optional<VertexBuffer>>(bindingState[slot]))
        setMetalSlot(slot, *vertexBuffer);
    std::get<std::optional<BindGroup>>(bindingState[slot]) = std::nullopt;
}
```

That way, you can do all of binding, unbinding, and draw call validation in constant space and constant time (considering `maxBuffersPlusVertexBuffersForVertexStage` to be a constant).

**Comment by litherum** [comment]
> However I'm really surprised that you're considering it worthwhile to expose maxBindGroups = maxVertexBuffers = 31 to the point of adding extra validation in the spec. 

I think it's going to be common for applications to make many bind groups and only put a single resource in them. I'm trying to support that use case as far as the underlying will allow.

> maybe this can just be pipeline time validation instead of draw-time validation

All WebGPU implementations already have to do draw call validation (which is way more complicated than what I'm proposing) to make sure the bind groups that are bound fit the pipeline. I'm proposing to augment this with one more check, and that check is a single assembly instruction. I don't think we can check everything at pipeline creation time, for the same reason that we have to do draw call validation today. We don't know what's bound until draw call time.

> It would be deferred until the first draw after a set pipeline

I think the pay-as-you-go nature of WebGPU is important; apps should have some intuition of the relative cost of each API call. Deferring all binding until draw call time strikes me as violating that principle.

**Comment by Kangz** [comment]
> I think it's going to be common for applications to make many bind groups and only put a single resource in them.

I don't know that such applications will be portable then, because browsers will choose to enforce default limits in a bunch of contexts, and because many devices (all of D3D12 because of the root signature? and many on Vulkan) won't support much more than the default. I understand the desire to want to make it easier coming from WebGL to port applications but experience with current ports shows that they aren't having too much trouble making bigger bind groups, and having many small bind groups is also a bad practice performance and portability-wise.

> I'm proposing to augment this with one more check, and that check is a single assembly instruction.

Computers are fast but we've steadily added checks at draw time. If it can be avoided we should not add them and in this case I think it is possible to validate at pipeline time. I'm not sure I understand the pay-as-you-go you mentioned since everything is behind an IPC barrier in WebKit anyway so when exactly work is happening when recording commands is very opaque to JS, and overall the same amount of work would be done (or less!)

**Comment by kainino0x** [comment]
I understand the proposal now, what I misunderstood was that it's not total number of bound bind groups + bound vertex buffers, but the max index of each.

**Comment by kainino0x** [comment]
I still have major concerns that Brandon initially raised. As I wrote in #2749:
> - Additional statefulness - bad for composability because a piece of code might need to go through and pessimistically wipe bindings just in case they were used previously (like GL state restoration), though avoidable with render bundles?

**Comment by kainino0x** [comment]
> CW: **Resolved:** New limit, draw time validation, setVB(null) resets, can pass garbage for offset/size (no validation), setBG(null) too.

**Comment by kainino0x** [comment]
I think we can do the null things as overloads so we don't have to have to deal with garbage for offset/size:

```
    undefined setVertexBuffer(GPUIndex32 slot, null buffer);
    undefined setBindGroup(GPUIndex32 index, null bindGroup);
```
