### ISSUE TITLE
Interpretation of `sequence<double>` as `GPUColor` is never actually spelled out

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#3793]
There's nothing in the spec, so far as I can tell, that says how a `sequence<double>` is interpreted as a color.

I suggest that it be permitted to be of any length, in rgba order, with omitted values defaulting to 0,0,0,1. This matches how we handle missing channels in color attachments.

**Comment by Kangz** [comment]
There is an editorial issue to write the reification steps. I think that we discussed this in the group in the past and decided to require exactly 4 components. I could dig more in the minutes if you would like. https://github.com/gpuweb/gpuweb/issues/1838
