### ISSUE TITLE
What should be the error name for GPUPipelineError

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#3796]
`DOMExceptions` should have an [error name](https://webidl.spec.whatwg.org/#idl-DOMException-error-names) but the WebGPU spec doesn't specify which one should be used for `GPUPipelineError`. My suggestion would be to use `OperationError`.

**Comment by Kangz** [comment]
Nevermind, the spec already says that the name should be "GPUPipelineError" and there is already precedent for introducing new error names: [`WebTransportError`](https://w3c.github.io/webtransport/#web-transport-error-constructor1) , [`BufferOverrunError`](https://wicg.github.io/serial/#:~:text=readable%5D%5D%20with%20a%20%22-,BufferOverrunError,-%22%20DOMException%20and) etc.

**Comment by kainino0x** [comment]
Verified tested by the CTS, any time we expect a GPUPipelineError we check its `.name`.
