### ISSUE TITLE
Who actually wants multiple timestampWrites with the same TimestampWrite.location?

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#3808]
We're sort of bending over backwards to support the fact that the PassDescriptor.timestampWrites can be arbitrarily long. But, in the common case, developers will probably just need at most 1 of each TimestampWrite.location. In fact, I don't know why anyone would ever actually want multiple items in the timestampWrites array that target the same TimestampWrite.location.

Can we simplify this, and just have, like...

```
dictionary GPUQuerySetAndIndex {
    GPUQuerySet querySet;
    GPUSize32 indexWithinQuerySet;
}
dictionary GPUComputePassTimestampWrites {
    GPUQuerySetAndIndex beginningOfPassWrite;
    GPUQuerySetAndIndex endOfPassWrite;
}
```
Or, even better...
```
dictionary GPUComputePassTimestampWrites {
    GPUQuerySet querySet;
    GPUSize32 beginningOfPassWrite;
    GPUSize32 endOfPassWrite;
}
```

If the site wants to copy the data out of there to a new place, they can go right ahead.

**Comment by kainino0x** [comment]
I can't honestly think of a reason people would need this, but it does feel like an arbitrary limitation on the API capabilities.

No strong feelings except for the usual "doesn't seem worth the effort".

**Comment by Kangz** [comment]
I believe there was a discussion about maybe in the future having the flexibility to write the beginning and end times multiple times if developers want to do it, though I agree it is very tenuous. +1 on "is it worth the effort"

**Comment by kainino0x** [comment]
Is there an impedance mismatch with the Metal backend or it it just complexity in wiring through?

We could add validation to the current API, for now at least, that there's no more than one at each location. I'd be fine with that.

**Comment by litherum** [comment]
There's kind of an impedance mismatch in Metal. Metal's API supports what WebGPU provides, but A) that API is only relevant on AGX cards, and B) AGX has a bug where it only actually looks at the first item in the array.

We can work around it by just resolving to a temp query set and then making a note when you try to resolve your real query set that the data you actually want is somewhere else.

But why? Who wants this?

**Comment by Kangz** [comment]
FYI @haoxli for the AGX bug which I believe you were running into?

> We could add validation to the current API, for now at least, that there's no more than one at each location. I'd be fine with that.

@haoxli raised this previously in #2662 which was discussed briefly in a [WebGPU meeting](https://github.com/gpuweb/gpuweb/wiki/Minutes-2022-04-06#are-duplicate-timestamp-locations-allowed-on-the-same-pass-2662) which resolved to do what is suggest in this issue (option 3) but https://github.com/gpuweb/gpuweb/pull/2812 seemed to have done something different?

**Comment by litherum** [comment]
RESOLVED: Accept one of the two proposals in the OP (TBD which of the two proposals)

**Comment by litherum** [comment]
Editor's meeting: Myles to determine if the more complicated proposal can be directly implemented or not. if so, that's the winner, else, the less complicated proposal is the winner.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#">GPU Web F2F 2023-02-16/17</a></summary>

    Who actually wants multiple timestampWrites with the same TimestampWrite.location? [#3808](https://github.com/gpuweb/gpuweb/issues/3808) [Myles]

* CW: we could postpone this post-V1.
* MM: is a change in shape next week too late?
* CW: Chrome branches March 23, so not too late, but onerous. We'd probably ship without the feature and turn it on later. If we want to change the shape, probably OK. If you want to investigate implementing it differently…
* MM: small investigation I need to do. Couple of impl options. Think this group's resolved on one of the existing options.
* CW: OK, we won't ship this and wait for group to rework it.

</details>

**Comment by kainino0x** [comment]
Note there's a similar piece of validation that's validated in render but not compute. Might be able to unify them? I don't know why compute would want to not have this restriction.

> 1. No two entries in |this|.{{GPURenderPassDescriptor/timestampWrites}} may have the same
        [{{GPURenderPassTimestampWrite/querySet}}, {{GPURenderPassTimestampWrite/queryIndex}}] pair.

**Comment by litherum** [comment]
This option doesn't actually work in Metal:
```
dictionary GPUQuerySetAndIndex {
    GPUQuerySet querySet;
    GPUSize32 indexWithinQuerySet;
}
dictionary GPUComputePassTimestampWrites {
    GPUQuerySetAndIndex beginningOfPassWrite;
    GPUQuerySetAndIndex endOfPassWrite;
}
```

So, instead, I think we're going to have to go with this option:
```
dictionary GPUComputePassTimestampWrites {
    GPUQuerySet querySet;
    GPUSize32 beginningOfPassWrite;
    GPUSize32 endOfPassWrite;
}
```

Although, I'd like to modify it a bit, to allow writing only a subset of the values:
```
dictionary GPUComputePassTimestampWrites {
    GPUQuerySet querySet;
    GPUSize32? beginningOfPassWrite;
    GPUSize32? endOfPassWrite;
}
```

**Comment by kainino0x** [comment]
> Although, I'd like to modify it a bit, to allow writing only a subset of the values:

Dictionary members are optional by default so they don't have to be nullable. (Same with the `querySet` member.)

**Comment by kainino0x** [comment]
Self-co-assigned for the PR, #3930.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/Minutes-2023-03-08#who-actually-wants-multiple-timestampwrites-with-the-same-timestampwritelocation-3808">GPU Web 2023-03-08</a></summary>

* MM: discussed a few weeks ago. Group resolved on either of my earlier proposals. Pick the one most expressive. Found only 1's implementable, so that's the one that should be in the spec.
* KG: there's a PR for this?
* KN: yes.
* MM: so this is in accordance with the previous resolution.
* KN: would like some docs recorded about why it didn't work in Metal, so we know why we did what we did.
* MM: de facto, only one of the proposals worked on the devices where support was needed.
* KG: PR is #3930.
* **KN: Editors to handle bikeshedding and land #3930.**

</details>
