### ISSUE TITLE
Validation for resolveQuerySet() doesn't require the query to have already been written to

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#3812]
It's bad news if you can resolve a query that hasn't been written to yet.

(There's nothing to discuss in the group here, this is just an issue that tracks a spec edit that needs to happen.)

**Comment by Kangz** [comment]
IIRC the group decided a long time ago when we added query sets that they would default to 0 like every other resources. There is a compute shader pass needed to quantize and convert the timestamp to nanoseconds anyway so the zeroing for the resolve can be done there.

**Comment by kainino0x** [comment]
Oops, this is no longer editorial because we disagreed on what's supposed to happen here.

**Comment by Kangz** [comment]
F2F: Agreed that queries default to zero.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/gpu-web-f2f-2023-02-16-17#v1-validation-for-resolvequeryset-doesnt-require-the-query-to-have-already-been-written-to-3812">GPU Web F2F 2023-02-16/17</a></summary>

* CW: accidentally made non-editorial?
* CW: Dawn does a compute shader pass for timestamp unit conversion, and if a query hasn’t been hit/isn’t ready, we just write zeros.
* MM: Why not error?
* CW: If error, your frame is gone.
* MM: Ok
* Resolved: Write zeros, don’t error.

</details>

**Comment by kainino0x** [comment]
I think it's different. This one is if you don't use the query set at all, #3895 is more specific cases.

**Comment by kainino0x** [comment]
> IIRC the group decided a long time ago when we added query sets that they would default to 0 like every other resources. There is a compute shader pass needed to quantize and convert the timestamp to nanoseconds anyway so the zeroing for the resolve can be done there.

Just for the record that happened in https://github.com/gpuweb/gpuweb/issues/1072#issuecomment-696358789
