### ISSUE TITLE
wgsl: type constructor expressions should have same execution rules as function calls

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3813]
Example:

```
struct S { i : i32 };
fn f() {
   S();  // @ben-clayton asked: is this valid, by spec?
}
```

That would match [func_call_statement](https://gpuweb.github.io/gpuweb/wgsl/#syntax-func_call_statement) which breaks down to a [callable](https://gpuweb.github.io/gpuweb/wgsl/#syntax-callable) followed by an argument list. And a callable is an ident or a type-specifier-without-ident.  
So syntactically it parses.

We use type checking to match to the type-constructor *expression*, which then gives the semantics.

However, the spec needs to make clear that type constructor expressions execute as if they are function calls. This is how we fit it into behaviour analysis and uniformity analysis.  Behaviour analysis tables are given as pattern matches, so that probably already is covered. But we'd need the clarification to ensure type constructors are covered by the uniformity analysis for function calls. 
  https://gpuweb.github.io/gpuweb/wgsl/#uniformity-function-calls

**Comment by ben-clayton** [comment]
To be clear - my question was related to the fact the expression value is not assigned to a variable.

Based on what you're saying, it sounds like this should be permitted, where as:

```
fn f() {
   42;
}
```

would not. Correct?

**Comment by dneto0** [comment]
> my question was related to the fact the expression value is not assigned to a variable.

Oh.   That is allowed.   If the function called in a function-call-statement returns a value, then that is permitted and the value is ignored.
Says so:
See  https://gpuweb.github.io/gpuweb/wgsl/#function-call-statement

> NOTE: If the function [returns a value](https://gpuweb.github.io/gpuweb/wgsl/#return-value), that value is ignored.

It can "just" be a note because there is no rule against it in the first plac.e


> [a statement that is just the number 42] would not. Correct?

Yes, that's correct. That would require an expression be allowed as a statement. But that's not in the grammar rules.
