### ISSUE TITLE
wgsl: limit validation

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#3815]
It doesn't appear to be specified what limits are enforced when generating a shaderModule

For example there's a limit `maxBindGroups`

Simple case

```wgsl
@group(10000000) @binding(0) var<uniform> used: f32;
@vertex fn vs() -> @builtin(position) vec4f {
  return vec4f(used);
}
```

Does `createShaderModule` reject this or pass it on as valid but it then gets rejected in `createRenderPipeline`?

Less simple case

```wgsl
@group(0) @binding(0) var<uniform> used: f32;
@group(10000000) @binding(0) var<uniform> unused: f32;
@vertex fn vs() -> @builtin(position) vec4f {
  return vec4f(v);
}
```

In the case above `unused` is out of range but it's not used so is it an error or not?

Similar for other limits that could affect what you can create in WGSL

```
* maxBindGroups	4
* maxBindingsPerBindGroup	640
* maxSampledTexturesPerShaderStage	16
* maxSamplersPerShaderStage	16
* maxStorageBuffersPerShaderStage	8
* maxStorageTexturesPerShaderStage	4
* maxUniformBuffersPerShaderStage	12
* maxVertexBuffers	8
* maxVertexAttributes	16
* maxInterStageShaderComponents	60
* maxInterStageShaderVariables	16
```

`workgroup_size` appears tp specify it checks the limit

note: ATM it apppears `createShaderModule` in dawn rejects the first example but passes the second.

**Comment by greggman** [comment]
To add to that. Is the current behavior inconsistent? Following the idea of it's it not used it doesn't fail then this would seem valid

assume maxBindGroups = 4

```wgsl
@group(3) @binding(0) var<uniform> g3: f32;
@group(4) @binding(0) var<uniform> g4: f32;

@vertex fn vsIfMaxBindGroup4() -> @builtin(position) vec4f {
  return vec4f(g3);
}

@vertex fn vsIfMaxBindGroup5Plus() -> @builtin(position) vec4f {
  return vec4f(g3 + g4);
}
```

And then at runtime choose one entry point or the other based on `maxBindGroups`

**Comment by greggman** [comment]
I was wrong. createShaderModule is not enforcing these limits

https://jsgist.org/?src=1084e8fc12daeec95de255e9b959eb23

That said, I don't think it's clear from the specs whether or not the enforcing the limits in WGSL is valid or not

**Comment by kainino0x** [comment]
> And then at runtime choose one entry point or the other based on `maxBindGroups`

This is a good motivating example for why it shouldn't be enforced in createShaderModule. Unfortunately it doesn't parallel with shader features like f16 (`enable f16` applies to an entire shader module), but that's probably OK since that's more of a language feature and this is more of an API feature. I do wonder if bgra8unorm storage should be always allowed and enforced at the API side though? (#3800)

**Comment by kainino0x** [comment]
There's been several discussions in the past about whether things that _can_ be validated at createShaderModule _should_ be. I don't remember what the result was for things like this but I think this is consistent with it. #1241, #974
