### ISSUE TITLE
Investigation: GPURenderBundle state inheritance

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#382]
I found some additional limitations if we want it to be possible to back GPURenderBundles native objects (Indirect command buffers, Bundles, secondary command buffers). As discussed previously, it is up to the implementation to use native objects, but for now it should still be possible to do so. Limitations can be lifted in the future.

## D3D12
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_command_list_type
> D3D12_COMMAND_LIST_TYPE_BUNDLE: Specifies a command buffer that can be executed only directly via a direct command list. A bundle command list inherits all GPU state (except for the currently set pipeline state object and primitive topology).

https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-executebundle

> Bundles inherit all state from the parent command list on which ExecuteBundle is called, except the pipeline state object and primitive topology. All of the state that is set in a bundle will affect the state of the parent command list. Note that ExecuteBundle is not a predicated operation.

## Metal
Provides `inheritBuffers` and `inheritPipelineState` to configure what state is inherited.

## Vulkan
https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkEndCommandBuffer.html
> * If commandBuffer is a secondary command buffer, there must not be an outstanding vkCmdBeginDebugUtilsLabelEXTcommand recorded to commandBuffer that has not previously been ended by a call to vkCmdEndDebugUtilsLabelEXT. 
> * If commandBuffer is a secondary command buffer, there must not be an outstanding vkCmdDebugMarkerBeginEXTcommand recorded to commandBuffer that has not previously been ended by a call to vkCmdDebugMarkerEndEXT.

https://renderdoc.org/vkspec_chunked/chap5.html#commandbuffers
> When secondary command buffer(s) are recorded to execute on a primary command buffer, the secondary command buffer inherits no state from the primary command buffer, and all state of the primary command buffer is undefined after an execute secondary command buffer command is recorded

## Conclusion
Creation of a GPURenderBundle has the following constraints:
 - Debug groups must be well-nested.
 - State from the GPUCommandEncoder is not inherited inside the GPURenderBundle. ex.) The following would be invalid:
   - beginRenderPass
      setPipeline
      setBindGroup
      executeBounds => ( draw )
      endPass
 - State in a GPURenderBundle does not persist to the GPUCommandEncoder after it is executed. ex.) If a GPURenderBundle calls `setPipeline`, the pipeline does not persist after `executeBundles`. ex.) The following would be invalid:
   - beginRenderPass
     executeBundles =>  ( setPipeline )
     setBindGroup
     draw
     endPass

**Comment by austinEng** [comment]
Furthermore, according to https://renderdoc.org/vkspec_chunked/chap5.html#commandbuffers

> Each command buffer manages state independently of other command buffers. There is no inheritance of state across primary and secondary command buffers, or between secondary command buffers. When a command buffer begins recording, all state in that command buffer is undefined. When secondary command buffer(s) are recorded to execute on a primary command buffer, the secondary command buffer inherits no state from the primary command buffer, and all state of the primary command buffer is undefined after an execute secondary command buffer command is recorded. There is one exception to this rule - if the primary command buffer is inside a render pass instance, then the render pass and subpass state is not disturbed by executing secondary command buffers. For state dependent commands (such as draws and dispatches), any state consumed by those commands must not be undefined.

 It seems that Vulkan is restrictive enough that we must enforce that no state is inherited, and all command buffer state is **invalidated** after a call to `executeBundles`.

@litherum and @RafaelCintron, I didn't find any documentation on Metal or D3D12 regarding what state is cleared / undefined after executing an ICB or Bundle.

**Comment by RafaelCintron** [comment]
@austinEng , see the [Bundle Restrictions](https://docs.microsoft.com/en-us/windows/win32/direct3d12/recording-command-lists-and-bundles#bundle-restrictions) section of the [Recording Command Lists and Bundles](https://docs.microsoft.com/en-us/windows/win32/direct3d12/recording-command-lists-and-bundles) documentation for things that are not allowed in bundles.   

The [ExecuteBundle](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-executebundle) documentation covers state inheritance after ExecuteBundle is called.  Specifically:
> Bundles inherit all state from the parent command list on which ExecuteBundle is called, except the pipeline state object and primitive topology. All of the state that is set in a bundle will affect the state of the parent command list. Note that ExecuteBundle is not a predicated operation.

**Comment by kvark** [comment]
Thank you for the investigation!
So the conclusion I read is:
  - when recording a GPUBundle, we assume a clean state and validate accordingly
  - after invoking a bundle from a pass, we assume a clean state

Is my reading correct?

**Comment by austinEng** [comment]
Yup, that would be my conclusion as well.

**Comment by kainino0x** [comment]
Closing, we implemented this already.

**Comment by Kangz** [comment]
I don't think we do? The state is completely reset when we start a render bundle AFAIK.

**Comment by kainino0x** [comment]
> I don't think we do? The state is completely reset when we start a render bundle AFAIK.

What I meant was we implemented the resetting, which we found was necessary due to Vulkan. I don't think there was really a feature request for render bundles that inherit certain state (though it would be a valid feature request).
