### ISSUE TITLE
`workgroupUniformLoad` not included in "collective operations" list

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#3836]
The section "Collective Operations" says that barriers and derivative operations must only be invoked in uniform control flow, but while `workgroupUniformLoad` includes barriers, it does not quite seem to be a "barrier" operation itself (and it is obviously not a derivative).

The section "Synchronization Built-in Functions" clearly includes `workgroupUniformLoad`, but the language at the top of "Barriers" seems to treat barriers as a subset of synchronization built-in functions, so it doesn't establish `workgroupUniformLoad` as a barrier.

Options:
a) Clearly designate `workgroupUniformLoad` as a barrier in its description.
b) Explicitly mention `workgroupUniformLoad` in the "Barriers" section.
c) Give `workgroupUniformLoad` its own subsection of "Collective Operations", repeating the "must only be invoked" clauses of the other two subsection.

**Comment by alan-baker** [comment]
workgroupUniformLoad is indicated as a barrier in its description already.  The definition of control barrier is links the two sections. I feel like that satisfies option a already. Am I misreading that @jimblandy?

**Comment by jimblandy** [comment]
Yes - I don't think the text is wrong, just more indirect than necessary. For example, at the bottom of "Synchronization Built-In Functions", along with the list of other restrictions, add "As control barriers, all synchronization functions must only be invoked in uniform control flow."

**Comment by alan-baker** [comment]
The first sentence in Synchronization Built-in Functions is:
>All synchronization functions execute a [control barrier](https://gpuweb.github.io/gpuweb/wgsl/#control-barrier)...

**Comment by jimblandy** [comment]
Yes, I had read that text. I'm saying that, in reading, it took me longer than I'd expected to reassure myself that this implied that `workgroupUniformLoad` must only be invoked in uniform control flow.

This is just a minor editorial suggestion. If it doesn't seem like an improvement to others, we can close this issue.
