### ISSUE TITLE
wgsl: enable directive should support a list of enable-extensions

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3885]
The 'requires' directive takes a list of "software extensions"
The enable directive only allows a single name.
It should allow a list of them, to be consistent.

Eg..

 

```
enable f16, whatever_other_hw_feature, f64;
```

**Comment by mehmetoguzderin** [comment]
Both convenient and increases internal consistency.

**Comment by litherum** [comment]
This seems clearly good

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-03-07-minutes#wgsl-enable-directive-should-support-a-list-of-enable-extensions--issue-3885">WGSL 2023-03-07 Minutes</a></summary>

* [Enable directive takes a list of extensions. #3886](https://github.com/gpuweb/gpuweb/pull/3886)
* KG: Mozilla is fine with this.
* **_Merge it._**

</details>
