### ISSUE TITLE
Occlusion Query results seem under specified

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#3895]
The spec currently says

> [Queue timeline](https://www.w3.org/TR/webgpu/#queue-timeline) steps:
> 1. Let passingFragments be non-zero if any fragment samples passed all per-fragment tests since the corresponding [beginOcclusionQuery()](https://www.w3.org/TR/webgpu/#dom-gpurenderpassencoder-beginocclusionquery) command was executed.
>
> 2. Write passingFragments into this.[[[occlusion_query_set]]](https://www.w3.org/TR/webgpu/#dom-gpurenderpassencoder-occlusion_query_set-slot) at index renderState.[[[occlusionQueryIndex]]](https://www.w3.org/TR/webgpu/#dom-renderstate-occlusionqueryindex-slot).

* it doesn't specify what `passingFragments` is if no samples passed. It only says if any samples passed then `passingFragments` is non-zero. 

  should it say `passingFragments` is zero if no samples passed or is it good enough that it's maybe implied?

* it doesn't specify what happens if there is no draw between `beginOcclusionQuery` and `endOcclusionQuery`.

  should it say anything here? For example 

  if no draw then `passingFramnents` is:

  * undefined? (up to implementation)
  * untouched? (previous value in query set remains as is)
  * zero?

**Comment by kainino0x** [comment]
> * should it say `passingFragments` is zero if no samples passed or is it good enough that it's maybe implied?

Never hurts to be clearer!

> * it doesn't specify what happens if there is no draw between `beginOcclusionQuery` and `endOcclusionQuery`.
>   should it say anything here? For example

I'd like to specify something here, but implementations don't have much control over this, so what we do depends on what the backend APIs do, which I don't know.

**Comment by kainino0x** [comment]
Based on discussion here: https://bugs.chromium.org/p/dawn/issues/detail?id=1707
it sounds like the problem of occlusion queries containing 0 draw calls might just be an Apple GPU specific bug?

**Comment by kainino0x** [comment]
Yesterday's CG meeting: define empty occlusion queries as 0, implementations should work around it.
