### ISSUE TITLE
wgsl: check asin, acos accuracy for f16

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#3909]
CTS testing showed that some implementations of asin(x) are implemented to bound absolute error rather then relative error.  we had to weaken the accuracy guarantee for f16.
See #3906 and #3907  

We need to write CTS for f16 to see if we have to weaken the accuracy rules for asin(x) and acos(x).

**Comment by jzm-intel** [comment]
## Update
Do another test to compare the output f16 `asin` and `acos` value to expected f16 result (computed with libc float function with f32 input of the same value, and quantized the f32 result back to f16), and measure the ULP error as well as absolute error. 

New data are shown in the figures below.
![AbsErrorUHD630](https://user-images.githubusercontent.com/84498356/223645939-6e7d0ea0-4ea0-4aed-bf71-e85d084b7bb1.png)
![AsinULPErrUHD630](https://user-images.githubusercontent.com/84498356/223645963-e7a5c6d4-84f2-483b-8a02-713466aff83d.png)
![AcosULPErrUHD630](https://user-images.githubusercontent.com/84498356/223645999-f171a49e-1def-4889-b146-9e57c5598972.png)

## Observation
1. Both `asin` and `acos` has a absolute error boundary on the whole definition domain including normal f16 and subnormal f16 values, on tested Intel UHD630 the boundary is `1.953125E-03`.
2. `acos` has a good ULP error boundary on the whole definition domain, within 2 ULP on the tested UHD630. 
3. `asin(x)` has a very large ULP (`> 1000 ULP`) error when f16 input value `x` approaches zero, even when `x` is normal f16 value i.e. `x > 2^-14`. Currently `asin(x)` inherit ULP error boundary from `atan(x, sqrt(1.0 - x * x))`, and if `x > 2^-14` the boundary should be `5 ULP`.

## Comments
1. Will do more test on other device like Nvidia GPU.
2. Will propose a absolute error boundary into WGSL spec after checking other devices.
3. Will start writing f16-relating CTS.

**Comment by dneto0** [comment]
Thank you, this is excellent work!

Your plan sounds good to me.

**Comment by jzm-intel** [comment]
## Test results on more device

Have done more test result on Intel A770, Nvidia RTX3090, and AMD Radeon RX 5700 XT. All f16 representable values between -1.0 and 1.0 are tested as input, and the computed outputs are compared to expected output `asin` and `acos` values that compute on CPU on float32 then quantized to f16, and the ULP is the f16 ULP at expected output value.

The error summary of each devices is listed in table below.

|   | UHD630 | A770 | RTX3090 | 5700XT | 
| --- | --- | --- | --- | --- | 
| max `asin` absolute err | 0.001953125 | 0.001953125 | 0.000976563 | 0.001953126 | 
| min `asin` absolute err | -0.001953125 | -0.001953125 | -0.000976563 | -0.001953126 | 
| max `acos` absolute err | 0.001953125 | 0.001953125 | 0.001953125 | 0.00390625 | 
| min `acos` absolute err | -0.001953125 | -0.001953125 | -5E-10 | -0.000976563 | 
| max `asin` ulp err | 3071 | 3071 | 2 | 3.000000102 | 
| min `asin` ulp err | -3071 | -3071 | -2 | -3.000000102 | 
| max `acos` ulp err | 2.000000102 | 2.000000102 | 2 | 2 | 
| min `acos` ulp err | -2.000000102 | -2.000000102 | -5.12E-07 | -8.000000001 | 

A figure showing both absolute and ULP error of f16 `asin` and `acos` on different devices is shown below.
![All](https://user-images.githubusercontent.com/84498356/226287954-90d57e87-516c-4160-834c-bc3fcc8fc314.png)

Details data:
[F16AsinAcosCompareDetails.zip](https://github.com/gpuweb/gpuweb/files/11015741/F16AsinAcosCompareDetails.zip)

## Conclusion

The accuracy requirement inherited from `atan2` is `5 ULP`. It is observed that `asin` has a very large (~thousands) ULP error on Intel device when the input (and thus expected `asin` output) is close to +/-0.0, while other tested devices has a good ULP err bound. `acos` ULP boundary is generally met, while gets to 8 ULP for inputs close to 1.0 on RX 5700XT.

For absolute error boundary, all devices has `asin` absolute error no more than `0.001953126 = 1.953126e-3`, and `acos` absolute error no more than `0.00390625 = 3.90625e-3`.

## Proposal

Under the test result, I propose to change the WGSL accuracy requirement of `asin` and `acos` as follow:

| Built-in Function | Accuracy for f16 |
| - | - |
| `acos(x)` | The worse of : 1) Absolute error `3.90625e-3`; 2) Inherited from `atan2(sqrt(1.0 - x * x), x)` |
| `asin(x)` | The worse of : 1) Absolute error `3.90625e-3`; 2) Inherited from `atan2(x, sqrt(1.0 - x * x))` |
