### ISSUE TITLE
Dual source blending

### ISSUE THREAD

**Issue by krogovin** [gpuweb/gpuweb#391]
Add the blend modes: "src1-color", "one-minus-src1-color", "src1-alpha", "one-minus-src1-alpha", "src1-alpha-saturated". Each of these has a direct analogue in Vulkan, Metal and Direct3D12.

Dual source blending provides for applications that blend in multiple ways (for example to support the Porter-Duff blend modes) can significantly reduce pipeline state object changes and open the door to applications for more flexible blending.

I am advocating for this feature as part 1.0 release and not as an extension.

**Comment by kainino0x** [comment]
This feature is optional in Vulkan, and not available on some ARM/Qualcomm/Imagination GPUs:

http://vulkan.gpuinfo.org/listreports.php?feature=dualSrcBlend&option=not

It's not clear to me exactly why some of these do not support it; I can find an [Adreno 530](http://vulkan.gpuinfo.org/displayreport.php?id=6560) which supports it and an [Adreno 540](http://vulkan.gpuinfo.org/displayreport.php?id=6212) which does not. Probably driver version related?

**Comment by kainino0x** [comment]
Also, there seem to be NO ARM and Imagination GPUs that support it.

**Comment by magcius** [comment]
DSB usage is quite rare, and I remember having enough problems with driver support and bugs back when that when I was trying to implement subpixel text rendering, I just chose to make the text a single color and use blend-color instead.

I would prefer if it was an extension. And as we've seen, some hardware doesn't have support for it.

**Comment by krogovin** [comment]
Let's mark the support as optional then. From what I know of Imaginations Technology GPU's I am pretty sure it could be implemented, but they would need to have a business case to do so. Another chicken-egg fiasco.

Lets make it optional but I would prefer at 1.0 instead of an extension as a way to prod ISV's to support it and to support it well.

**Comment by litherum** [comment]
What’s the motivation for this feature? What use-cases does it make possible?

It strikes me that WebGPU app developers could implement this themselves if they could do programmable blending.

**Comment by krogovin** [comment]
> It strikes me that WebGPU app developers could implement this themselves if they could do programmable blending.

If programmable blending, i.e. framebuffer fetch is available, the yes, A WebGPU app can do dual source blending itself.

However, if framebuffer fetch is not available (or another means of doing programmable blending), then dual source blending not only opens up additional blending possibilities but also gives applications a possibility to cut down on the number of blend states needed. Indeed, to implement all 12 PorterDuff modes requires only three distinct blend modes.

But to reiterate, for me, the preference order is:
1. Framebuffer fetch (best)
2. Interlock (can do icky blend modes)
3. Dual Source blending

**Comment by kvark** [comment]
@litherum WebRender relies on DSB for rendering subpixel AA text without doing multiple passes.
I think, exposing dual-source blending is attractive, as an extension, because it's clearly defined and it requires only a tiny API to be added (a few blend factor variants).

**Comment by magcius** [comment]
Even Metal doesn't have programmable blending on desktop platforms. It's something that's much trickier to do on non-tilers.

**Comment by krogovin** [comment]
> Even Metal doesn't have programmable blending on desktop platforms. It's something that's much trickier to do on non-tilers.

This is why I advocate framebuffer fetch and interlock to be available as extensions.

**Comment by krogovin** [comment]
Something that I should have mentioned quite some time ago, but I did not. Without dual-source blending, it is nearly impossible to directly support all of the Porter-Duff blend modes with a shader computing a partial coverage value.

Indeed, for Skia, without dual source blending, for a number of blend modes, it issues a glCopyTexImage2D for some of the blend modes. Ironically, this is needed for kSrc (but not kSrcOver).

So please, do not let this be forgotten.

Now to beg/ask in the correct place for GL_EXT_blend_func_extended in WebGL/WebGL2

**Comment by bjjones** [comment]
I just opened a formal investigation and proposal for this feature at #4283. This comes after recently completing a prototype implementation of the feature in Chromium/Dawn.

Additionally, @teoxoy, I appreciate you documenting many of the specific native API restrictions, which I've used in my proposal.

**Comment by Kangz** [comment]
Closing in favor of #4283 that links to this issue and has a proposal.
