### ISSUE TITLE
Querying number of array layers for TextureCubeArray not supported in SM5.1

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#3913]
FXC produces this error:
```
 error X4598: The array element count of GetDimensions on TextureCubeArray objects is unavailable on ps_5_1
```

Shader Playground link:
https://shader-playground.timjones.io/338c7900cc2930c9183c57ab8ca77d3f

We likely just need to remove the `texture_cube_array` overload of `textureNumLayers()` from WGSL.

**Comment by ben-clayton** [comment]
`texture_depth_cube_array` overload too

**Comment by dneto0** [comment]
The textureLoad and textureStore builtins refer to textureNumLayers to talk about bounds on array index, but neither of those can act on a cube array or depth-cube array.

Should be a pretty clean change.

**Comment by teoxoy** [comment]
This works but the arguments passed to `GetDimensions` have to be either `uint` or `float`.

See https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-to-getdimensions
Also https://shader-playground.timjones.io/f1a61d5d2327baba7d3c568eb2deecd6

FXC's error message is very poor and indicates it doesn't work.

**Comment by ben-clayton** [comment]
You're right!
What a deceptive error message. Time to undo some changes to tint!

**Comment by ben-clayton** [comment]
Closing the issue. Thank you @teoxoy
