### ISSUE TITLE
Derived pipeline state objects

### ISSUE THREAD

**Issue by krogovin** [gpuweb/gpuweb#392]
This is a feature request for the interface to support a form of Vulkan's derived pipeline state objects. The basic idea is that an application can say a newly created pipeline state object FOO is very similar to pipeline state object BAR. Ideally, when creating BAR, an application will only specify the fields of FOO that are different from BAR.

The motivation is that the pipeline state object represents almost the entire GPU state although internally most GPU's the state is composed of different units. Indeed, most of the reason for PSO's is that different GPU's need to modify shaders based off of some other GPU state that might be orthogonal on other GPU's (the most common is blending, but there are others).

This feature when mapped to a native 3D API that also supports that feature will reduce GPU state thrashing for when state has not changed greatly. A good example is blending. On some GPU's this is realized by a dedicated unit and others by a shader. Some GPU's of the former do NOT need to drain the pipeline on a blend change, thus blend mode changes does not induce pipeline bubbles harming performance.

It can be argued that a driver *should* just check what portions have changed and do its thing, but that means the driver spends additional time deciding what to to do. 

I also admit that this feature's ability to enhance performance is highly dependent on driver, GPU design and native API. 

However, at the very least, it can provide some API sugar to make similarly valued PSO's.

**Comment by magcius** [comment]
IHVs have basically all warned that derivative pipelines are effectively pointless, since they don't tell you which state changed from the previously bound pipeline, only some abstract "parent" (which is not that useful to a GPU or a driver). Pretty much only Qualcomm has an implementation of them that actually uses them, and they've mentioned it was a pretty weak performance improvement compared to the amount of work put into the spec.

The IHV performance guides pretty much all say not to use derivative pipelines.

**Comment by krogovin** [comment]
That is a bummer if the IHV's say so. I know the open source Intel driver just ignores the derived_bit thing too.

It implies that then either all the Vulkan drivers either set the entire pipeline state or they check each of the properties for what changed and emit as necessary. Sighs.

Given what IHV's re saying, I retract this request and suggest we kill it.

**Comment by kainino0x** [comment]
Thanks for the good discussion. Closing this then.

**Comment by magcius** [comment]
The app cannot know which pipelines should derive from others. To give an example, if I have pipelines that differ by both blend state and vertex format, what should derive from what? On AMD devices, the vertex format change requires a new shader and blend is cheap, so maybe blend should be the derivative, on iOS, the blend requires a new shader and the vertex format change is cheap.

Different GPUs have different ideas of cheap vs. expensive state, and the app cannot create derivatives up-front.
