### ISSUE TITLE
Reserve u8, u16, u64, u128, i8, i16, i64, i128 for future use.

### ISSUE THREAD

**Issue by rickwebiii** [gpuweb/gpuweb#3923]
I see in https://github.com/gpuweb/gpuweb/issues/273 that 64-bit integers aren't supported until beyond V1. Nonetheless, I think it's wise to reserve u8, u16, u64, u128 for future use. Today users can use these as typenames, which will break their code if WGSL ever supports other integer sizes.

**Comment by ben-clayton** [comment]
We've un-keyworded all types, so we can add new types in the future without breaking existing shaders. All types can be shadowed by user declarations, including the core set of types in V1.
