### ISSUE TITLE
Evaluation order of assignment and compound assignment are flipped

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#3928]
Currently, the RHS of an assignment is evaluated before the LHS.

For example:

`arr[b()] = arr[a()];`

`a()` is spec'd to evaluate before `b()`

However the reverse is true for compound assignments:

`arr[b()] += arr[a()];`

Here `b()` evaluates before `a()`.

This evaluation order flip is surprising, and caught me off guard when writing CTS.

I propose we make compound assignment behave the same as assignment, and have both evaluate RHS, then LHS.

**Comment by ben-clayton** [comment]
We did some investigation on other languages. The order of evaluation between LHS and RHS varies by language, but we've yet to find one where assignment differs from compount-assignment.

**Comment by ben-clayton** [comment]
One proposal is to change the 'desugaring' of `LHS += RHS` to be:

```
let v = RHS
let p = &LHS
*p = *p + v
```

**Comment by ben-clayton** [comment]
Another is to make regular assignment evaluate LHS then RHS, making compound assignment match.
Javascript, Java, go (and more) guarantee LHS eval then RHS eval.

**Comment by dneto0** [comment]
Currently the compound assignment is defined as this sugar:

`e1 += e2;`
is the same as the following, where the reference expression e1 is computed only once.

`e1 = e1 + (e2);`

The left-to-right progression comes from the left-to-right progression of the binary operator `+` in this case.

In other words, rewrite as:
```
let p = &(e1);
let pv = *p;  // need this intermediate in case evaluation of e2 changes value of e1.
let v = e2;
*p = pv + v;
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-03-07-minutes#evaluation-order-of-assignment-and-compound-assignment-are-flipped-3928">WGSL 2023-03-07 Minutes</a></summary>

* DN: Glad someone looked up other languages, and saw JS does it this way..
* DN: Will affect uniformity analysis as well.
* **_Proposal: order assignments, and compound assignments left to right. RESOLVED._**

</details>

**Comment by quantumagi** [comment]
Something I've found counter-intuitive in both C# and Python:

```
int[] x = { 0, 1, 2 };
int index = 0;
x[index++] = index;
Console.WriteLine($"{x[0]} {x[1]} {x[2]}");
```

This results in `1 1 2` where if the RHS were strictly evaluated first one would expect `0 1 2`.
