### ISSUE TITLE
Curation of WGSL exemplars for LaMDA, GPT-3, etc.

### ISSUE THREAD

**Issue by dcerisano** [gpuweb/gpuweb#3931]
People will probably want to use Bard, ChatGPT etc to write boilerplate WGSL code.

Just wondering if the curation of WGSL training sets falls under the purview  of the W3C WGSL committee.

This would initially require a comprehensive set of pristine WGSL snippets and gists (exemplars), which seems like something the committee could curate on an ongoing basis.

Also curious if the existing committee meeting minutes could be used in training sets - there is a lot of fine detail in there.

**Comment by dneto0** [comment]
I suspect that's outside the purview. I'd suggest taking a look at the working group charter, and community group charter.

I personally think it's not our job to train large language models deliberately.

The committee meeting minutes are already on the web in close to plain text, and available for training.  E.g. https://github.com/gpuweb/gpuweb/wiki/WGSL-2020-04-07

**Comment by dneto0** [comment]
Also, the CTS is / will be a big-ish body of WGSL code.

As with many things in life, curation of your inputs (what do you pay attention to) is a critical choice.

**Comment by dcerisano** [comment]
To come back to the topic, that charter was written before people started using NLP to generate code. It represents a paradigm shift that makes curation of computer language models an integral part of language design. 

Generative code is going to be the first _experience_ many people have with WGSL and it should be the best _experience_ possible, which is going to require careful curation of the model.

**Comment by dcerisano** [comment]
To come back to the topic, that charter was written before people started using NLP to generate code. That represents a paradigm shift that makes curation of computer language models an integral part of language design.

Generative code is going to be the first experience many people have with WGSL and it should be the best experience possible, which is going to require careful curation of the model.

The critical choice seems to be whether the charter gets updated to reflect this reality. Perhaps some attention should be paid to that.

**Comment by kainino0x** [comment]
Models are not trained on small datasets like the one produced by a small group, they require large datasets produced for example by everyone on the internet. It's infeasible for this group to create enough data to be useful for training, but it _will_ create data, and what data it does create will end up in the large datasets anyway.

**Comment by dcerisano** [comment]
If you read the issue description, the suggestion was to curate an initial model which already exists in several forms (meeting mintues, CTS, etc) and to continue the curation of a comprehensive WGSL's LNP model on an ongoing basis.

I agree, this would require an update to the charter, since generative code was not really a thing when it was written years ago. This issue was probably closed prematurely.

**Comment by dcerisano** [comment]
If you read the issue description, the suggestion was to curate an initial model which already exists in several forms (meeting mintues, CTS, etc) and to continue the curation of a comprehensive WGSL LNP model on an ongoing basis.

New languages like WGSL are in a unique position to leverage LNP. This would require an update to the charter, since generative code was not an issue when it was written years ago. This issue was probably closed prematurely.

**Comment by dcerisano** [comment]
If you read the issue description, the suggestion was to curate an initial model which already exists in several forms (meeting mintues, CTS, etc) and to continue the curation of a comprehensive WGSL NLP model on an ongoing basis.

New languages like WGSL are in a unique position to leverage NLP to promote adoption. This would require an update to the charter, since generative code was not an issue when it was written years ago. This issue was probably closed prematurely.

**Comment by dneto0** [comment]
I didn't mean to be flip or sarcastic. I'm sorry it may have come across that way.

My point is that the challenge of training those models is to try to have them attend to and focus on good code examples.  Shaping the attention of a large model is like search-engine-optimization, but for ML models. That is a very proprietary, undocumented, and quickly shifting set of algorithms and biases. That is very much outside our expertise or ability to drive or tune.

At the same time, I think the best way to train those models is to get the community at large writing good WebGPU programs, and have those programs visible on the public internet.  In other words, we should do our best to get humans writing good code.  Already our mission and activities are pointed in that direction, in my opinion.

**Comment by dcerisano** [comment]
No offense taken. Curation of training exemplars is more about quality than quantity and requires domain experts to ensure low quality samples don't degrade the model and result in in low quality generative code. 

This issue has been closed, which is unfortunate. There is a real opportunity to promote WGSL in a way that it is as new as WGSL itself. It would leverage NLP to overcome resistance to adoption.
