### ISSUE TITLE
Event that triggered when resources fully loaded in gpu

### ISSUE THREAD

**Issue by munrocket** [gpuweb/gpuweb#3951]
As I understand right now it is a problem with WebGL API to catch the moment when page is fully loaded and this event don't exist.
Sometimes you need turn off page with loader after this event or make screenshot of unknown app.

**Comment by kainino0x** [comment]
Only the webpage itself can know whether it's fully done loading, and in the case of many pages it will never be done (images may be lazily loaded when scrolled into view, the page may be infinitely scrolling, the page may be showing a live video stream, etc.) Are there specific ways WebGPU could help with this?

**Comment by munrocket** [comment]
Ok, I suppose it can be solved with cpu/gpu synchronisation like `GPUCommandBuffer.finish()` or like `gl.fenceSync()`.
