### ISSUE TITLE
Compute shader results inconsistency

### ISSUE THREAD

**Issue by afreg11** [gpuweb/gpuweb#3968]
### Detected incosistent behaviour while filling buffers.
Repository for this report: https://github.com/afreg11/webgpu_bugreport/
1. create two Array<u32> buffers
2. in shader fill both buffers with ones (1u)
3. after storage barrier compute partial sums of second buffer
Problem: sum of all partial sums is inconsistent.

Result is correct if we do partial sums on firts buffer, instead of the second one.
Result is correct if we remove filling of first buffer.

More details in https://github.com/afreg11/webgpu_bugreport/blob/main/tests/tests/bugreport/README.txt

**Comment by Kangz** [comment]
This is most likely a bug on a specific WebGPU implementation. Please follow the indications of the issue wizard to post to the correct issue tracker.
