### ISSUE TITLE
frexp is not defined for subnormals

### ISSUE THREAD

**Issue by amaiorano** [gpuweb/gpuweb#3970]
See this issue: https://bugs.chromium.org/p/tint/issues/detail?id=1877#c1

CTS is failing on Intel GPUs when the input value to `frexp` is subnormal. We should point out in the spec that `frexp` is only well defined for normal values (not subnormals).

**Comment by zoddicus** [comment]
We have already weakened ldexp to only apply to normals + 0 due to similar issues.
