### ISSUE TITLE
Device Info APIs

### ISSUE THREAD

**Issue by n8schloss** [gpuweb/gpuweb#40]
Hey all,

During TPAC one item that the web perf working group discussed was adding an api (https://github.com/w3c/device-memory/issues/15) to be able to get 'WEBGL_debug_renderer_info' info without having to spin up a web gl context. There are many users with lower end GPUs that can't really handle many of the experiences we want to ship so we need to get this info. Unfortunately the users with the lower end GPUs are the same ones where spinning up a web gl context can be extra expensive, there are some cases where spinning up a web gl context can cause the screen to appear to freeze for whole seconds. To address this we want to make an api that allows for this info to be exposed without having to make a web gl context.

There's not any new info being exposed here so fingerprinting isn't really a big concern. This mainly will just avoid paying the large cost of setting up a web gl context for the people who really shouldn't be using one. Also even without 'WEBGL_debug_renderer_info' being exposed the performance characteristics of the gpu will always be observable so all we do by not exposing this info is force the people on lower end devices to pay a large cost to render things. 

One of the follow ups from TPAC was to see if anyone here has any big concerns before we move forward. Like I said this information is already available today and we need to and do get it, but doing so can be a very bad user experience on some devices.

**Comment by litherum** [comment]
This question is better suited for the WebGL group in Khronos. The WebGPU effort is orthogonal to WebGL.

**Comment by kainino0x** [comment]
@n8schloss: The issue tracker for WebGL is here:
https://github.com/KhronosGroup/WebGL/issues/new
Could you re-post there?
