### ISSUE TITLE
fragment shader position.z is scaled to viewport mindepth -> maxdepth

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#4003]
Currently the API spec says:

position is set to:
vec4<f32>(rp.[destination](https://gpuweb.github.io/gpuweb/#rasterizationpoint-destination).[position](https://gpuweb.github.io/gpuweb/#fragmentdestination-position), rp.[depth](https://gpuweb.github.io/gpuweb/#rasterizationpoint-depth), rp.[perspectiveDivisor](https://gpuweb.github.io/gpuweb/#rasterizationpoint-perspectivedivisor))

And that rp.depth is the NDC depth.

But Vulkan and D3D say it's already been scaled by the viewport.

Vulkan: see https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vertexpostproc-viewport   zf = pz * zd + oz
And then FragCoord says the x,y,z are the "framebuffer coordinates", thus referencing xf, yf, zf.

In the D3D11 functional spec, see computation of xrt, yrt, zrt in "15.6 Viewport"

https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#16.3%20Pixel%20Shader%20Inputs

**Comment by kainino0x** [comment]
I'll happily take this, but won't be able to work on it just yet. Will assign myself again if I pick it up.

**Comment by kainino0x** [comment]
@dneto0 fixed this in #4053.
