### ISSUE TITLE
Remove `maxFragmentCombinedOutputResources`?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4018]
Based on the analysis here: https://github.com/gpuweb/gpuweb/issues/3631#issuecomment-1474299043
> Dawn's thinking before we added this limit was that it was incorrectly reported on AMD/NVIDIA/Intel devices, so we ignored it for those:
> [kainino0x/gpuinfo-vulkan-query@7cc9056](https://github.com/kainino0x/gpuinfo-vulkan-query/commit/7cc9056d1a68958c4bdb81b6a4781c8a2e99dac4)
> https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/native/vulkan/AdapterVk.cpp;l=385;drc=c2657b21d50938d4676aa6c87e44b3aa50c7f468
> **IF** that's still correct even for higher storage binding limits, then adding `maxFragmentCombinedOutputResources` may actually not be doing anything for us. Here's a series of queries that look at whether it's filtering out any devices at higher storage limit tiers:

It seems `maxFragmentCombinedOutputResources` may not actually be buying us any hardware support, or avoiding any cases where we have to reduce other limits to stay under this.

Hence we should consider removing the limit. We can't actually remove it from the structs post-v1, but we _can_ stop validating it. It would be nice to avoid overlapping limits where they're unnecessary, because they introduce some annoying complexity for users due to our strict enforcement of requested limits.

Other overlapping limits: `maxBindGroupsPlusVertexBuffers`, `maxDynamicUniformBuffersPerPipelineLayout`, `maxDynamicStorageBuffersPerPipelineLayout`, `maxStorageBufferBindingSize`, `maxColorAttachments `/`maxColorAttachmentBytesPerSample`, `maxComputeInvocationsPerWorkgroup`/`maxComputeWorkgroupSizeX`/`Y`/`Z`. Most of these won't be removable but are worth a second look someday. -> #4025

**Comment by kainino0x** [comment]
> maxFragmentCombinedOutputResources is incorrectly reported on older PowerVR drivers, it should just be ignored for these drivers. The correct limit for us is the same as `maxPerStageDescriptorStorageImages + maxPerStageDescriptorStorageBuffers + maxColorAttachments`

_Originally posted by @JarredHDavies in https://github.com/gpuweb/gpuweb/issues/3631#issuecomment-1498747606_

Another point in favor of this limit being unnecessary. (Intel/AMD/NVIDIA also all incorrectly report the value of this limit.)

**Comment by kainino0x** [comment]
Given the new info, labeling V1 to discuss again actually removing this from V1 so we don't have to ship with a wart.
We don't technically have a guarantee this will never be useful, but given the ecosystem, it currently isn't. On devices which actually have a meaningful `maxFragmentCombinedOutputResources` (i.e. less than `maxPerStageDescriptorStorageBuffers + maxPerStageDescriptorStorageImages + maxColorAttachments`) we can always statically divide it among those 3 limits in WebGPU.

Let's look at what devices those might be. Filtering for that condition, and excluding all NVIDIA, AMD, Intel, and ImgTec devices, we get only Adreno devices (all 6xx, a large fraction of 7xx). My conclusion is this limit exists only for older Adreno devices. On all of them, the combined limit is 72, which IMO is high enough that implementations can safely choose the other 3 limits within it (32+32+8).

<details><summary>Breakdown:</summary>

First the devices that support WebGPU's minimum limits otherwise (8, 4, 8) but can't support the combined 8+4+8:

```
Requirement "maxFragmentCombinedOutputResources >= 8+4+8, OR is intel/nvidia/amd/imgtec" loses 4 (and partially loses 5) further deviceNames:
  In ALL reports (4 deviceNames):
    x FD630: 2 (9843 10962)
    x FD640: 2 (12237 12590)
    x FD650: 3 (9599 12275 14634)
    x FD660: 1 (12634)
  In SOME reports (5 deviceNames):
    ~ AMD RADV POLARIS10: 1 of 615 (15761)
    ~ Turnip Adreno (TM) 630: 2 of 10 (13100 13399)
    ~ Turnip Adreno (TM) 640: 1 of 15 (13196)
    ~ Turnip Adreno (TM) 650: 2 of 58 (13195 13371)
    ~ llvmpipe: 225 of 499 (9379 9614 9631 9765 9824 10043 10121 10275 10338 10407 10445 10557 10629 10679 10694 10772 10802 10883 10919 10975 11036 11074 11083 11140 11148 11162 11166 11197 11244 11270 11285 11307 11320 11427 11435 11448 11466 11490 11506 11547 11574 11618 11634 11644 11705 11759 11768 11795 11801 11819 11827 11836 11851 11888 11893 11932 11945 11972 12006 12012 12018 12050 12081 12090 12094 12106 12110 12118 12135 12139 12157 12184 12212 12226 12257 12265 12272 12309 12313 12339 12356 12386 12409 12443 12450 12479 12500 12519 12535 12564 12576 12582 12616 12621 12663 12709 12725 12738 12752 12760 12783 12791 12869 12892 12902 12909 12950 12972 13002 13009 13011 13079 13122 13127 13140 13151 13159 13176 13199 13201 13228 13259 13301 13322 13332 13336 13369 13379 13382 13406 13495 13506 13511 13527 13531 13533 13548 13549 13554 13557 13559 13601 13623 13625 13633 13634 13639 13645 13647 13657 13658 13663 13665 13682 13683 13687 13688 13741 13770 13771 13789 13791 13796 13798 13843 13845 13911 13913 13950 13974 14020 14032 14033 14046 14059 14062 14067 14187 14189 14207 14209 14260 14262 14267 14288 14305 14307 14313 14315 14327 14329 14344 14346 14349 14357 14374 14376 14379 14381 14390 14402 14404 14409 14411 14430 14432 14442 14444 14454 14456 14469 14471 14477 14479 14484 14486 14498 14572 14861 15468 16028 17332 17759 18111 18562)
```

(FD6xx are Adreno-derived)

And the devices where maxFragmentCombinedOutputResources is limiting compared to the sum of the other limits it provides:

```
Requirement "maxFragmentCombinedOutputResources is non-limiting, or is intel/nvidia/amd/imgtec (assumed to report incorrect values)" loses 14 (and partially loses 3) further deviceNames:
  In ALL reports (14 deviceNames):
    x Adreno (TM) 610: 109 (7037 8669 9434 9524 10094 10192 10384 10410 10412 10420 10471 10516 10572 10885 10932 11059 11076 11212 11372 11375 11384 11390 11459 11522 11701 11917 11936 11946 11974 12002 12158 12294 12350 12367 12420 12546 12897 12899 12999 13031 13080 13146 13219 13257 13262 13288 13565 13651 13763 13903 13916 14022 14043 14203 14252 14331 14392 14437 14575 14594 14636 14714 14833 14836 14896 15020 15037 15174 15224 15235 15392 15403 15479 15555 15559 15597 15694 15905 15923 15967 15978 16000 16196 16290 16488 16821 17013 17359 17400 17515 17525 17609 17673 17714 17842 18022 18297 18350 18480 18523 18754 18911 19116 19119 19344 19346 19379 19534 19629)
    x Adreno (TM) 612: 20 (5789 6220 7178 7986 9014 10707 10874 11318 11661 12084 12126 12216 12476 14223 14301 14525 14548 15080 15106 15657)
    x Adreno (TM) 615: 16 (5944 6088 6436 7898 7927 8903 9147 9184 9422 10427 11275 12085 12583 12996 13171 18427)
    x Adreno (TM) 616: 19 (4986 5287 6492 7806 9756 10393 10604 11072 11712 12858 13327 13564 14753 14828 15544 15614 15887 19242 19337)
    x Adreno (TM) 618: 95 (6379 7893 9036 9037 9351 9692 9862 10286 10295 10432 10481 10488 10499 10834 10897 10945 11022 11144 11198 11217 11253 11482 11615 11796 11813 11937 12035 12055 12144 12278 12918 13032 13042 13165 13178 13238 13598 13736 13865 13866 13915 13996 13998 13999 14122 14358 14359 14423 14718 14757 14923 15200 15243 15288 15326 15412 15439 15477 15495 15509 15751 15994 16128 16130 16131 16147 16151 16152 16153 16166 16541 16566 16569 16607 16788 16872 16873 16874 16875 17120 17279 17291 17608 17647 17808 18048 18207 18435 18886 18910 19211 19342 19566 19608 19612)
    x Adreno (TM) 619: 45 (11041 11303 11380 11714 11905 12331 12332 12574 12623 12753 12772 12853 13438 13507 13898 14761 14839 14853 14982 15264 15334 15428 15557 15602 15718 15879 15880 16024 16096 16099 16146 16364 16375 16408 16487 16600 17402 17604 17630 17717 18039 18084 18569 18571 18917)
    x Adreno (TM) 620: 30 (9304 9995 10296 10646 10942 11510 11662 11957 12305 12329 12692 12757 12890 12952 13439 14665 14764 14858 15743 16001 16154 16359 16527 16710 16882 16956 17448 18016 18678 19626)
    x Adreno (TM) 630: 130 (2801 3024 3138 3305 3442 3665 3687 3754 3755 3795 3810 3927 4134 4140 4249 4270 4366 4403 4413 4486 4525 4563 4599 4628 4632 4915 4926 5175 5253 5800 5886 6032 6038 6056 6107 6162 6234 6266 6434 6704 6788 6987 6996 7057 7108 7374 7949 8473 8577 8585 8907 8951 9097 9267 9471 10285 10287 10291 10300 10302 10303 10351 10371 10424 10460 10551 10672 10678 10730 10770 10813 10966 11016 11026 11035 11120 11464 11602 11670 11695 11914 11922 12213 12280 12363 12429 12430 12667 12775 13256 13424 13428 13552 13642 13675 13676 13749 13752 13963 13991 14092 14393 14463 14523 14608 14610 14611 14717 14751 14806 15580 15682 15962 15963 15997 16157 16169 16320 16330 16790 16818 16867 16888 17508 17719 17777 18139 18145 18208 19001)
    x Adreno (TM) 640: 141 (5552 5633 6040 6188 6239 6363 6403 6603 6820 6875 7088 7175 7237 7595 7708 9111 9426 9503 10183 10305 10348 10368 10380 10391 10465 10611 10738 10768 10805 10847 10921 10923 10940 10943 10944 11070 11168 11190 11254 11257 11334 11368 11489 11495 11525 11575 11666 11667 11668 11671 11773 11799 11810 11847 11876 11895 11926 12423 12604 12841 12843 12846 12931 13027 13247 13309 13412 13493 13560 13629 13743 13753 13760 14009 14038 14101 14105 14247 14371 14416 14419 14460 14526 14561 14566 14681 14770 14793 14944 14945 14948 14987 15008 15086 15114 15116 15145 15172 15175 15189 15269 15280 15387 15493 15506 15528 15655 15681 15713 15828 15855 15915 16056 16202 16207 16300 16301 16303 16523 16543 16556 16687 16822 16824 17147 17254 17370 17876 17912 18400 18408 18531 18750 18881 18989 19118 19252 19357 19602 19716 19741)
    x Adreno (TM) 642: 4 (13528 14406 14666 16863)
    x Adreno (TM) 642L: 21 (13313 13542 13779 13892 15217 15729 16060 16190 16365 16461 16509 16520 16652 17454 17643 18040 18772 18773 19181 19565 19725)
    x Adreno (TM) 650: 242 (7990 8177 9027 9701 9715 9725 9734 10024 10357 10370 10385 10401 10408 10416 10417 10485 10525 10531 10533 10637 10683 10705 10748 10804 10808 10836 10869 10959 11146 11171 11180 11216 11325 11457 11579 11646 11647 11711 11828 11845 11897 12052 12088 12182 12185 12291 12318 12330 12425 12595 12603 12635 12652 12800 12815 12826 12837 12877 12936 13022 13037 13138 13149 13167 13396 13488 13491 13535 13536 13626 13698 13742 13754 13766 13851 13957 13972 14029 14051 14086 14090 14094 14133 14153 14210 14211 14232 14319 14353 14354 14355 14438 14464 14504 14505 14509 14512 14539 14545 14559 14586 14587 14588 14589 14593 14662 14689 14744 14789 14814 14834 14838 14898 14912 14934 14935 14989 14998 15001 15048 15049 15053 15054 15055 15066 15102 15115 15130 15186 15187 15201 15272 15359 15361 15396 15408 15460 15463 15469 15471 15473 15492 15512 15543 15545 15612 15642 15644 15662 15663 15728 15814 15829 15839 15876 15898 15975 16376 16377 16399 16432 16453 16522 16538 16545 16620 16649 16659 16706 16707 16717 16720 16735 16736 16739 16776 16777 16787 16789 16801 16804 16817 16839 16861 16879 16948 16978 16980 17014 17199 17210 17334 17438 17440 17488 17607 17689 17693 17737 17811 17915 17946 17947 18019 18020 18035 18132 18171 18176 18189 18259 18324 18384 18398 18478 18501 18507 18540 18575 18630 18650 18701 18704 18873 18966 19029 19168 19187 19204 19288 19305 19356 19430 19446 19536 19537 19539 19542 19555 19628 19649 19685)
    x Adreno (TM) 660: 92 (10268 10345 10721 10814 10948 10983 11001 11296 11333 11339 11405 11512 11523 11534 11672 11731 11873 11935 11991 12221 12323 12431 12437 12497 12511 12553 12587 13062 13064 13207 13249 13296 13400 13504 13583 13631 13792 13804 13981 14171 14212 14214 14290 14462 14518 14669 14817 14824 15132 15139 15209 15245 15266 15329 15347 15383 15530 15586 15626 15832 15838 15892 16245 16258 16260 16331 16343 16690 16946 17164 17168 17453 17522 17564 17677 17749 17797 17812 17861 17890 17920 18168 18290 18310 18890 18926 18974 19193 19701 19740 19757 19758)
    x Samsung Xclipse 920: 6 (14143 14243 15503 16126 16887 17572)
  In SOME reports (3 deviceNames):
    ~ Adreno (TM) 730: 78 of 88 (13441 13717 13731 13905 14181 14215 14220 14270 14277 14397 14481 14487 14511 14524 14905 14988 15402 15434 15453 15574 15646 15760 15771 15781 15803 15860 15889 15913 15929 15949 16163 16191 16203 16212 16217 16226 16263 16269 16312 16318 16496 16536 16568 16664 16703 16999 17028 17345 17475 17485 17494 17565 17631 17680 17696 17798 17911 17963 17966 18028 18136 18212 18237 18251 18288 18386 18430 18594 18595 18717 18718 18793 19219 19232 19254 19691 19708 19742)
    ~ Adreno (TM) 740: 10 of 24 (18498 18500 18742 18853 19158 19184 19196 19248 19383 19593)
    ~ SwiftShader Device: 6 of 8 (16262 16766 18449 18451 18694 18695)
```

Out of those we see the following situations:

| storage buffers | storage images | color attachments | < | combined | On |
| - | - | - | - | - | - |
| 524288 | 524288 | 8 | < | 72 | Adreno
| 4294967295 | 4294967295 | 8 | < | 4294967295 | Xclipse
| 30 | 16 | 8 | < | 28 | SwiftShader
| 72 | 64 | 8 | < | 72 | Adreno

Note the Samsung Xclipse - that's actually an AMD RDNA2 device, so most likely reports incorrectly like other AMD devices do. And the limits are all ~infinity anyway so it doesn't matter.

</details>

**Comment by kainino0x** [comment]
Resolved in webgpu meeting, moving to editorial to spec

**Comment by SenorBlanco** [comment]
Bringing this back up (sorry), the limit also seems to affect OpenGL ES, where it is preventing use of Compatibility mode on PowerVR devices (which, unlike in Core, should otherwise be usable in Compatibility mode).

Since the limit prevents GLSL shaders from compiling/linking, I'm not sure how it should be ignored, as suggested above.

**Comment by kainino0x** [comment]
If it actually prevents GLSL shaders from compiling then we can't ignore it. In Vulkan it was just that the reported limit was wrong on a bunch of devices, but also not enforced.

**Comment by Triang3l** [comment]
The limit is present on AMD's pre-GCN (TeraScale) GPUs, for which I'm currently working on a Vulkan implementation.

While GCN and RDNA use texture cache functionality and inline descriptors to write to storage resources, TeraScale repurposed the color target unit for that as it already had image read-modify-write functionality unlike the read-only texture cache.

As a consequence, the GPU has 12 binding slots shared between up to 8 color attachments, up to 12 storage resources, and the dual source blending factor. Because of that, without `maxFragmentCombinedOutputResources`, it's not possible to expose more than 4 RTs, 4 storage buffers, and 4 storage images, when fragment shader storage writes are allowed. With `maxFragmentCombinedOutputResources = 11`, the limits can be raised to make it possible to provide various combinations of up to 8 RTs and 11 (such as 7+4 or 8+3) storage images/buffers (12 in compute, but in fragment shaders, one is excluded due to the "1 RT + blend factor" case).

Also, Direct3D 11.0 itself inherently has this limit in its `ID3D11DeviceContext::OMSetRenderTargetsAndUnorderedAccessViews`, and it's even tighter than on TeraScale — 8 slots shared between color attachments, storage resources, and blending src1. It's not possible at all to provide fragment shader storage writes with 4 storage images and 4 storage buffers on Direct3D 11.0 even, as that wouldn't leave any space for render targets.
