### ISSUE TITLE
Rendering to OffscreenCanvas on non-yielding workers

### ISSUE THREAD

**Issue by awtcode** [gpuweb/gpuweb#403]
Hi,

I currently execute my code in a Web Worker and does not yield the context back to the browser because everything happens in a while loop. As such, I need to pass the OffScreen Canvas back to the main thread for rendering. 

Here are my questions:
1)	Will WebGPU support the OffScreenCanvas API?
2)	Can we have an API to support rendering from a Worker even if the context is not yielded back to the Worker?

**Comment by kainino0x** [comment]
1. Yes, you will be able to use it similarly to WebGL with transferControlToOffscreen (though WebGPU's exact presentation API may change between now and then).
2. I think we will be able to support this. It's not entirely solved yet. WebGL OffscreenCanvas commit() was [rejected as a web platform feature](https://github.com/w3ctag/design-reviews/issues/288), but we continue to keep this use case in mind as it is critical for ports of native code to WebAssembly.

**Comment by awtcode** [comment]
Thanks for the prompt reply @kainino0x :) It will be great if we can have (2) because I am currently working on porting AutoCAD to Wasm and being able to render directly from the Worker without having to transfer control back to the main thread would be a huge plus.

**Comment by awtcode** [comment]
@kainino0x and @Kangz , can I check if OffScreenCanvas is currently available for WebGPU in Chrome Canary on Windows now? If not, is there an estimate on when it will be ready? Thanks.

**Comment by Kangz** [comment]
@awtcode I don't think any of the WebGPU implementations have OffscreenCanvas right now. In Chromium it is blocked on some internal <canvas> code refactor so it won't be available at least until the end of the year, maybe more.

**Comment by awtcode** [comment]
Thanks for your reply @Kangz .

**Comment by s11k** [comment]
Hi @kainino0x -- do you happen to know the status of the internal refactor? I'm really looking forward to accessing WebGPU from Web Workers.

Thanks!

**Comment by Kangz** [comment]
@s11k It's still ongoing (but had recent progress). You can follow along this [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1061053).

**Comment by Kangz** [comment]
FYI offscreen canvas is completely working in WebGPU in Chromium now. Closing now since this was more of a question on WebGPU than a spec discussion.
