### ISSUE TITLE
investigate ULP bounds on unpack2x16unorm

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#4038]
CTS is using the "inherited from division" accuracy formulation for unpack*unorm and unpack*snorm, which builds in a 2.5 ULP error tolerance.

I filed https://github.com/gpuweb/cts/issues/2485 to review and likely fix that to base accuracy on the infinitely precise divide.
#3992 adjusted unpack2x16snorm to have 3ULP, from "correctly rounded"
We may need to adjust unpack2x16unorm to have 2, 2.5 or 3ULP, instead of "correctly rounded"

**Comment by dneto0** [comment]
Needs Action:  Try converting the CTS testing to use "correctly rounded" and see what errors come up.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-04-18-minutes#investigate-ulp-bounds-on-unpack2x16unorm--issue-4038">WGSL 2023-04-18 Minutes</a></summary>

* DN:  **Needs investigation**.  Suspect need to weaken from “correctly rounded” but need more info.

</details>

**Comment by munrocket** [comment]
Am I right that we need device agnostic shader polyfill for pack2x16unorm/pack2x16snorm here? 3ULPs looks big.

**Comment by munrocket** [comment]
Am I right that we need device agnostic shader polyfill for pack2x16unorm/pack2x16snorm here? Maybe I have solution.

**Comment by dneto0** [comment]
> Am I right that we need device agnostic shader polyfill for pack2x16unorm/pack2x16snorm here? Maybe I have solution.

We don't want a polyfill here.  We only want to pass through what underlying implementations provide.

This was fixed by #4225
