### ISSUE TITLE
GPUVertexBufferDescriptor 's stride size needs to be a multiple of 4 bytes

### ISSUE THREAD

**Issue by shaoboyan** [gpuweb/gpuweb#404]
Metal has requests [here](https://developer.apple.com/documentation/metal/mtlvertexbufferlayoutdescriptor/1515441-stride) that stride size of vertex buffer needs to be a multiple of  4 bytes. WebGPU should also follow the restriction.

**Comment by Kangz** [comment]
This is in the current spec.
