### ISSUE TITLE
Consider matching either ECMAScript or HTML for whitespace and line break definitions

### ISSUE THREAD

**Issue by annevk** [gpuweb/gpuweb#4068]
As far as I can tell the current definitions are not aligned with anything in the web platform. Seems unfortunate to have these not match any precedent.

**Comment by mehmetoguzderin** [comment]
Discussions that led to the current state
Blank spaces: https://github.com/gpuweb/gpuweb/pull/2734
Line breaks: https://github.com/gpuweb/gpuweb/pull/2782

**Comment by dneto0** [comment]
It matches the Unicode linebreaking rules.  I don't know what other web specs do here.

**Comment by annevk** [comment]
Apart from ECMAScript most use https://infra.spec.whatwg.org/#ascii-whitespace.

**Comment by dneto0** [comment]
I should have also said WGSL blankspace is defined to match Unicode Pattern_White_Space.

This is different from whatwg.org ascii-whitepace.  E.g. vertical tab (U+000B) is in Pattern_White_Space but not ascii-whitespace.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-05-23-minutes#consider-matching-either-ecmascript-or-html-for-whitespace-and-line-break-definitions--issue-4068">WGSL 2023-05-23 Minutes</a></summary>

* KG: Yep, we matched unicode. Suspect other web specs were defined before Unicode, and would, if defined today, do what we did.  Any noticed warts would be considered warts on HTML and ECMAscript.
* MOD: The spec explicitly states the code points; it’s easy to follow.
* **_Will say: we know, it’s on purpose. Works as intended._**

</details>

**Comment by kdashg** [comment]
If there are any concrete pain points here, we'd like to revisit this, but for now I think we are satisfied generally.
I'm no particular fan of vtab, but "just do what unicode recommends" still seems like a good safe option.

**Comment by kdashg** [comment]
To be clear, I'm not saying it has warts.

**Comment by annevk** [comment]
I think the problem I see is that we already have many competing definitions of whitespace in the web platform resulting in subtle bugs everywhere.

This increases that surface by being subtly different again.
