### ISSUE TITLE
"Variable and Value Declaration Feature Summary" table missing `var<storage,write>`

### ISSUE THREAD

**Issue by rconde01** [gpuweb/gpuweb#4076]
I believe write only storage buffers are supported, so I think this [table](https://www.w3.org/TR/WGSL/#effective-value-type) should include them.

**Comment by alan-baker** [comment]
They are not supported. From var Declarations:
>A variable in the [storage](https://gpuweb.github.io/gpuweb/wgsl/#address-spaces-storage) address space is a storage buffer variable. Its [store type](https://gpuweb.github.io/gpuweb/wgsl/#store-type) must be a [host-shareable](https://gpuweb.github.io/gpuweb/wgsl/#host-shareable) type and must satisfy the [address space layout constraints](https://gpuweb.github.io/gpuweb/wgsl/#address-space-layout-constraints). The variable may be declared with a [read](https://gpuweb.github.io/gpuweb/wgsl/#access-read) or [read_write](https://gpuweb.github.io/gpuweb/wgsl/#access-read_write) access mode; the default is read.

**Comment by rconde01** [comment]
Sorry - I got confused between storage textures and storage buffers
