### ISSUE TITLE
Readonly attributes cannot use `[EnforceRange]`

### ISSUE THREAD

**Issue by saschanaz** [gpuweb/gpuweb#4080]
Currently GPUBuffer and GPUTexture have several readonly attributes with typedefs with `[EnforceRange]`, but this violates the rule: https://webidl.spec.whatwg.org/#EnforceRange

>A type annotated with the [[EnforceRange](https://webidl.spec.whatwg.org/#EnforceRange)] extended attribute must not appear in a [read only](https://webidl.spec.whatwg.org/#dfn-read-only) attribute.

**Comment by ErichDonGubler** [comment]
From private conversation I had with @saschanaz, my applied understanding for the WebGPU spec. is that: `[EnforceRange]` attributes can only be used on symbols that are intended strictly for input. We have to decide what the boundary is between number of types and number of annotations. A few alternatives thrown around include:

* Creating duplicate (but easy-to-relate) definitions of current `typedef`s, based on whether they should be validated with `[EnforceRange]`:

    ```
	typedef unsigned long long GPUSize64Out
	typedef [EnforceRange] GPUSize64 GPUSize64In
    ```
* Using `[EnforceRange]` everywhere that we actually consume `GPUSize64` et al for user-provided arguments, and relying on ourselves to not forget in the future, i.e.:

    ```
	dictionary GPUDeviceDescriptor : GPUObjectDescriptorBase {
	    // ...
	    record<DOMString, [EnforceRange] GPUSize64> requiredLimits = {};
	    // ...
	};
    ```

**Comment by kainino0x** [comment]
Ah... we fixed this a long time ago in https://github.com/gpuweb/gpuweb/issues/549, but that was before we added a bunch of these output fields. Moved to editorial v1 to fix this.

It was actually discussed at depth here: https://github.com/whatwg/webidl/issues/842
We never resolved the philosophical disagreement between the WebGPU and WebIDL folks on the topic, and TBH I do wish we didn't have to make this tradeoff.

But regardless, our spec should pass validation. It would be great to see webidl2.js will start enforcing this validation, but I seem to recall that isn't actually used in our CI (bikeshed uses widlparser). Do you know how we can get it enforced on our CI?

**Comment by saschanaz** [comment]
[w3c/spec-prod](https://w3c.github.io/spec-prod/) can apply the validation in webidl2.js even for bikeshed specs 👍

**Comment by kainino0x** [comment]
Thanks, we are using spec-prod so that should mean we'll pick it up!
