### ISSUE TITLE
black mode in addition to clamp-to-edge, etc. for sampling textures 

### ISSUE THREAD

**Issue by jeancolasp** [gpuweb/gpuweb#4084]
The existing modes for dealing with what happens when the texture coordinates are outside of the standard range are nice, but one that is being used often in the rendering world is black. Clamp-to-Edge would just take 0 if the coordinate is lower than 0 and 1 if greater than 1. 

Black is useful, for instance when you render fonts to quads. A font can be right at the border of an area in which the glyph is drawn and with clamp-to-edge, assuming the font is placed in the middle of the quad, the first or last row/column in the texture is repeated above/below, or on the sides. A solution is to leave a line of black pixels around the rendered glyph but that's not always possible & shifts calculation in the code. The black mode will solve that problem (if uv coordinates get outside the range 0-1 inclusive, just set the value to (0,0,0,1).

**Comment by kainino0x** [comment]
I believe this is https://github.com/gpuweb/gpuweb/issues/1305, please re-open if I'm wrong.
