### ISSUE TITLE
WGSL u32 CRITICAL Browser / GPU FREEZE on Windows (works on Mac)

### ISSUE THREAD

**Issue by alienself** [gpuweb/gpuweb#4107]
On Version 113.0.5672.93 and above (also tested on chromium v115)

`if(useInverseSquaredFalloff == 1)` from an element  array (dereferenced ptr) causes a critical browser GPU freeze/crash on Windows.
The whole browser freezes (not just the tab) and an app restart is necessary from the Task Manager. 
Additionally my GPU fans are going full speed. 

The issue is not happening on Mac where the condition is working perfectly. 

It only seem to be affecting the u32 type, as I am able to interact with the other types of the struct just fine.

code:
```glsl
struct Lights {
    pointLightCount: u32,
};

struct PointLight {
    position: vec4<f32>,
    direction: vec4<f32>,
    color: vec4<f32>, 
    sourceRadius: f32,
    length : f32,
    range : f32,
    attenuationRadius: f32,
    useInverseSquaredFalloff: u32,
    lightFalloffExponent: f32,
    _pad1: f32,
    _pad2: f32,
};
struct PointLights {
    data: array<PointLight, 256u>,
};

@group(0) @binding(3) var<uniform> lights: Lights;
@group(0) @binding(4) var<uniform> pointLights : PointLights ;
... 

@fragment
fn fragment_main(vertex: VertexOutput) -> @location(0) vec4<f32> {

for (var lightId = 0u; lightId < lights.pointLightCount; lightId++) {
    let light = &pointLights.data[lightId];

    let useInverseSquaredFalloff : u32 = (*light).useInverseSquaredFalloff;
    if(useInverseSquaredFalloff == 1) // HERE - causes HUGE freeze on Windows
    {
    }
}
```

I am very sure of the data being sent (lights.pointLightCount) as well as the pointlight buffer and since this is working great on Mac, there is no reason why this issue should happen on Windows in the first place.

**Comment by greggman** [comment]
This is the spec site, the a browser bug site. Browser bugs should be filed at the appropriate site for that browser. I'm guessing you're using Chrome so could you please file a bug at https://crbug.com ?

**Comment by alienself** [comment]
Oh my bad! Thanks for the link, reported here: https://bugs.chromium.org/p/chromium/issues/detail?id=1444948
Hopefully we can get a fix soon, this is really blocking for any Windows development on chrome
