### ISSUE TITLE
Add lessThanEqual(), lessThan(), greaterThan(), greaterThanEqual(), equal(), notEqual(), any(), all(), not()

### ISSUE THREAD

**Issue by wrightwriter** [gpuweb/gpuweb#4112]
Rarely used but useful, i don't see a reason why they shouldn't exist.

**Comment by ben-clayton** [comment]
`any()` and `all()` [already exist](https://www.w3.org/TR/WGSL/#logical-builtin-functions).

What do the rest give you that the binary operators don't?
