### ISSUE TITLE
Should we be able to unset index buffers?

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#4118]
This would be consistent with `SetVertexBuffer` and `SetBindGroup`.

**Comment by kainino0x** [comment]
@Kangz did you meant "unset index buffers"?

**Comment by greggman** [comment]
Do we need to? Whether a index buffer is used or not is whether you call `draw`/`drawIndirect` or `drawIndexed`/`drawIndexedIndirect` right?

**Comment by Kangz** [comment]
Yeah I meant index buffer :) 

@greggman that's not about validation required for draw/drawIndirect (as you correctly pointed out) but just consistency with other things that bind objects to the encoder state. It would be marginally useful to unset state between components rendering to the same pass (so devs know the state doesn't risk being reused without a validation error)

**Comment by Kangz** [comment]
Sounds good
