### ISSUE TITLE
read-only storage buffer access from vertex shaders should be allowed

### ISSUE THREAD

**Issue by mheistermann** [gpuweb/gpuweb#4132]
@unvestigate and I discovered a spec issue and  [were advised to file an issue](https://matrix.to/#/!MFogdGJfnZLrDmgkBN:matrix.org/$hcU03FHE9hrrtVOOpIItlGhgGM8492Mu9a30dp6qqkc?via=matrix.org&via=mozilla.org&via=matrix.nrp-nautilus.io) by @Kangz in the WebGPU matrix room.

### WebGPU spec wording
According to the main WebGPU spec, vertex shaders cannot use bind groups that have a writing binding to a storage buffer:

[§8.1.2, `createBindGroupLayout()`](https://www.w3.org/TR/webgpu/#dom-gpudevice-createbindgrouplayout), Device timeline initialization steps:

>If entry.visibility includes VERTEX: entry.buffer?.type must not be "storage".

This does not preclude `read-only-storage`, which I believe is intentional; cf. the commit adding the first version of this restriction: https://github.com/gpuweb/gpuweb/commit/162928ffd9c454f6ef02e076cb8b5da3cc7e89b0
In any case, this access is required for any vertex pulling.

However, the WGSL spec has a much stricter wording:

### WGSL spec wording

[§6](https://www.w3.org/TR/WGSL/#var-and-value):
> 5. Storage buffers and storage textures cannot be statically accessed in a vertex shader stage. See WebGPU createBindGroupLayout().
https://github.com/gpuweb/gpuweb/blob/e607dd0e168ed49a824c1681fbb57d59a3d749cd/wgsl/index.bs#L4466-4468

[§13.3](https://www.w3.org/TR/WGSL/#address-space):
>Variables in the storage address space (storage buffers) and variables whose store type is a storage texture cannot be statically accessed by a vertex shader stage. See WebGPU createBindGroupLayout().
https://github.com/gpuweb/gpuweb/blob/e607dd0e168ed49a824c1681fbb57d59a3d749cd/wgsl/index.bs#L8914-8917

### Proposed solution

- I think the WGSL spec should be changed to specifically refer to write access.
- Additionally, I think it would prevent misunderstandings if the WebGPU spec sentence was extended by a note stating that the `read-only-storage` type is not affected; without an understanding of the spec that includes knowing about `read-only-storage`, disallowing `storage` sounds like any access to storage buffers is disallowed.

I would be happy to create a PR with these changes.

### Related Issues/PRs
- Intruction of discussed passage into WGSL spec: #3947
- CTS issue gpuweb/cts#2398

**Comment by Kangz** [comment]
Spec editors, any concerns with this? Readonly storage buffers (and textures in the future) were definitely meant to be available to the vertex stage.

**Comment by kainino0x** [comment]
Definitely agreed, this is just an editorial issue to fix for V1.

**Comment by teoxoy** [comment]
This looks to have been resolved by https://github.com/gpuweb/gpuweb/pull/4133.
