### ISSUE TITLE
Add discussion about fixed size array limits

### ISSUE THREAD

**Issue by rconde01** [gpuweb/gpuweb#4143]
Unless I missed it, there is no discussion about fixed size array limits which I think would be useful.

**Comment by kdashg** [comment]
Can you say more? Do you mean adding explicit limits to the spec for max fixed-size array size?

**Comment by rconde01** [comment]
So I was just thinking of these questions:
* is there a max fixed size array? Or does it depend on stack space?
* Is there a max stack size?
* Are these things hardware specific, implementation specific?

Does that clarify?

**Comment by alan-baker** [comment]
We have some related limits, see https://gpuweb.github.io/gpuweb/wgsl/#limits.

**Comment by rconde01** [comment]
thanks i didn't see that...i think that more or less answers the question

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-05-30-minutes#add-discussion-about-fixed-size-array-limits-4143">WGSL 2023-05-30 Minutes</a></summary>

* AB: We have some limits for fixed size arrays in the WGSL spec. C**an add those into the issue in case OP doesn’t know**.
* DN: Can’t be 100% prescriptive.  Too many factors contributing.
* MM: Be helpful to authors when we can.

</details>
