### ISSUE TITLE
fract() returns values out of bounds on Intel Iris Graphics 550

### ISSUE THREAD

**Issue by anvaka** [gpuweb/gpuweb#4144]
I have the following pseudorandom number generator:

```
fn rand(co: vec3f) -> f32 {
    let t = dot(vec3f(12.9898, 78.233, 4375.85453), co);
    let x = sin(t) * (4375.85453 + t);
    return fract(x);
}
```

Then in compute shader:

```
@compute
@workgroup_size(${WORKGROUP_SIZE})
fn computeMain(@builtin(global_invocation_id) cell: vec3u) {
    let indexOfElement = cell.x;
    if (indexOfElement >= ${ELEMENTS_COUNT}) {
        return;
    }
    if (rand(lastPos * f32(indexOfElement)) > 5) {
        // update buffer
    }
}
```

I'd expect the `update buffer` logic to never happen, because fract is supposed to be in `[0, 1]` range. Increasing my condition from `if (rand(lastPos * f32(indexOfElement)) > 5) ` to `if (rand(lastPos * f32(indexOfElement)) > 10)` does eliminate buffer update.

It doesn't seem right when `fract()` gives out of bounds values. This test was done on MBP hardware listed below. I was not able to reproduce it on Nvidia RTX 4090.

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,2
  Processor Name:	Dual-Core Intel Core i7
  Processor Speed:	3.3 GHz

Chipset Model:	Intel Iris Graphics 550
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x1927
  Revision ID:	0x000a
  Metal Family:	Supported, Metal GPUFamily macOS 2
  Displays:
Color LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2560 x 1600 Retina
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal
```

```
navigator.userAgent
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'
````

Please pardon me if this is a wrong place to open the issue

**Comment by greggman** [comment]
Bugs should arguably be reported to the browser the bug appears in. In this case you probably want to report the bug at https://crbug.com

**Comment by ben-clayton** [comment]
More specifically, please file at: https://crbug.com/tint

I don't see where `lastPos` is declared or updated. What range of values does that have?

**Comment by ben-clayton** [comment]
Note to self: This smells like `fract(x)` is implemented as `x - f32(i32(x))`, which produces wrong values when `x` is larger than the largest representable `i32`. We've encountered [similar issues](crbug.com/1883) before.

**Comment by dneto0** [comment]
I think @ben-clayton meant to point at https://bugs.chromium.org/p/tint/issues/detail?id=1883#c5

**Comment by dneto0** [comment]
But interestingly, this would be a Metal bug, not an FXC (Windows) bug.

**Comment by anvaka** [comment]
> I don't see where lastPos is declared or updated. What range of values does that have?

It was `vec3f`, but seems like it happens for `vec4f` too. `lastPos` indicates the last position of a line that follows a vector field. It can get very large or even hit singularities. 

I dropped `lastPos` for brevity in the description, but here is more complete definition:

```
@group(0) @binding(0) var<storage, read_write> lineCoordinates: array<f32>;
@group(0) @binding(1) var<storage, read_write> lineLifeCycle: array<u32>;

@compute
@workgroup_size(${WORKGROUP_SIZE})
fn computeMain(@builtin(global_invocation_id) cell: vec3u) {
  let lineIndex = cell.x;
  if (lineIndex >= ${LINE_COUNT}) {
    return;
  }
  // first we get the last point in the line:
  var lineHead = lineLifeCycle[lineIndex * 2 + 0];
  var lineLength = lineLifeCycle[lineIndex * 2 + 1];
  var lastPosIndex = lineIndex * ${POINTS_PER_LINE} + lineHead * 4;
  var lastPos = vec4f(
    lineCoordinates[lastPosIndex + 0], lineCoordinates[lastPosIndex + 1], 
    lineCoordinates[lastPosIndex + 2], lineCoordinates[lastPosIndex + 3]
  );

  if (rand(lastPos * f32(lineIndex)) > 1) {
                                     ^^^
    // Shouldn't get here, but still do
  }
```

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2023-05-30-minutes#fract-returns-values-out-of-bounds-on-intel-iris-graphics-550-4144">WGSL 2023-05-30 Minutes</a></summary>

* DN: **We’re still looking internally, but we do strongly suspect this is a bug that we will work around**.

</details>

**Comment by litherum** [comment]
> This smells like `fract(x)` is implemented as `x - f32(i32(x))`

At values greater than or equal to the largest representable int (or unsigned int), the delta between adjacent representable floats is >= 1. This means that, in that range, all floats are whole numbers, so the return of `fract()` is trivially implementable. So, this can be polyfilled pretty easily (trivially if you're willing to add a branch, but still fairly easily if you use branchless style).

**Comment by litherum** [comment]
> This smells like `fract(x)` is implemented as `x - f32(i32(x))`

This doesn't seem like what's going on. Writing a sample shader:
```
[[kernel]] void computeShader(device float* buffer [[buffer(0)]]) {
    buffer[1] = fract(buffer[0]);
}
```

and passing in `nextafter(nextafter([4294967296](tel:4294967296), Float.infinity), Float.infinity)` for `buffer[0]` produces a result of 0 on Apple M1 Max, AMD Radeon Pro 560, and Intel(R) HD Graphics 630.

Would it be possible to attach a sample app or something that will allow us reproduce the problem?

**Comment by anvaka** [comment]
Thank you for looking into this. Here is [a short unlisted video](https://www.youtube.com/watch?v=2Vzc0JvNDUg) that demonstrates reproduction steps using https://github.com/anvaka/vector-space-adventure project. 

I'm attaching two lines change that I showed in the video here too:

```
diff --git a/src/createVectorFieldCalculator.js b/src/createVectorFieldCalculator.js
index 3dab155..4e32c60 100644
--- a/src/createVectorFieldCalculator.js
+++ b/src/createVectorFieldCalculator.js
@@ -102,7 +102,7 @@ export default function createVectorFieldCalculator(drawContext, segmentedLines,
                 lineCoordinates[lastPosIndex + 2], lineCoordinates[lastPosIndex + 3]
                 );
     
-            if (rand(lastPos * f32(lineIndex)) > 10) { // disabled temporary
+            if (rand(lastPos * f32(lineIndex)) > 1) { // disabled temporary
                 lastPos = vec4f(rand(lastPos), rand(lastPos - 1), rand(lastPos + 1), rand(lastPos + 2)) * 2.0 - 1.0;
     
                 lastPosIndex = lineIndex * ${POINTS_PER_LINE} + (${SEGMENTS_PER_LINE} * ${POINT_DIMENSIONS});
diff --git a/src/sharedState.js b/src/sharedState.js
index 4167d16..4b69dea 100644
--- a/src/sharedState.js
+++ b/src/sharedState.js
@@ -9,6 +9,7 @@ fn getVelocityAtPoint(pos: vec4f) -> vec4f {
     let z = pos.z;
     let w = pos.w;
     // Change this to define a new field:
-    return vec4f(10 * (y - x), x * (28 - z) - y, x * y - 1.5*z, 0);
+    return vec4f(10 * (y - x), x * (28 - z) - y, x * y - 1.5*z, x * y * z - 8/3 * w);
+    // return vec4f(10 * (y - x), x * (28 - z) - y, x * y - 1.5*z, 0);
 }`
 };
\ No newline at end of file

```

**Comment by litherum** [comment]
I can reproduce this on Chrome on Intel HD Graphics 630.

This bug tracker is not the right place to report device-specific, browser-specific, or OS-specific bugs. I'll take care of this one, but in the future, please use https://www.apple.com/feedback/

**Comment by litherum** [comment]
I made a native app reduction that uses pure Metal instead of WebGPU, and filed it on the Metal team as rdar://113994532.
