### ISSUE TITLE
[editorial] WGSL Section Shuffle

### ISSUE THREAD

**Issue by alan-baker** [gpuweb/gpuweb#4145]
Some sections seem out of place in the WGSL spec. I think this is largely due to how the language developed over time. Now that the language is mostly settled it would be revisit some of the sections.

Proposed order:
* Introduction
  * Overview (_formerly Technical Overview_)
* ~~Shader Lifecycle~~
  * _Subsumed by WGSL Module_
* WGSL Module (formerly WGSL Program)
  * _Renamed as forward looking for linking multiple modules together and many things are module scoped_
  * _More prose is necessary here likely some overlap with the technical overview_
  * Lifecycle (_moved from independent chapter_)
  * Errors (_moved from Shader Lifecycle subsection_)
  * Diagnostics (_moved from Shader Lifecycle subsection_)
    * Diagnostic Processing
    * Filterable Triggering Rules
    * Diagnostic Filtering (_global directive grammar moved out_)
  * Limits
* Texture Structure
  * ...
  * ~~Attributes~~ (_moved to separate chapter_)
  * ~~Directives~~ (_moved to separate chapter_)
* ...
* Functions
* Attributes (_moved from textural structure subsection_)
  * _I considered having this as a subsection of declaration and scope, but it felt out of place_
* Directives (_moved from textural structure subsection_)
  * _I considered this being a subsection of WGSL Module, but that feels a bit forced (everything may as well be under WGSL Module then)
  * Extensions (_moved from independent chapter_)
    * Enable Extensions
    * Language Extensions
  * Global Diagnostic Filter (_new section_)
* Entry Points
  * ...
  * Shader Interface
    * ...
    * Built-in Inputs and Outputs
      * Built-in Values (_moved from independent chapter_)
    * ...
  * ...
* ...
* ~~Built-in Values~~

Looking for feedback from @dneto0 and @mehmetoguzderin as the other WGSL editors.

Edit 1: including feedback from https://github.com/gpuweb/gpuweb/issues/4145#issuecomment-1567340987

**Comment by dneto0** [comment]
* I'd like to rename "Technical Overview" to just "Overview".  Let's do it in this pass.
* Extensions should be mentioned early on as a forward reference, either in the Overview or WGSL Module
* I wondered why attributes are where they are, since they will be used in a lot of examples.
    * But I see the logic in describing them after all the things they can be put on:  declarations (including functions), and statement-blocks.
    * So I think where you have them is ok.  But it probably needs a forward reference from Overview
* It's not clear that moving Global diagnostic filter to the directives chapter is a win. 
    *  Reading the Diagnostic Filtering section, there's a clear two-cases structure of local and global filtering.  Where would the code example go, because it also uses a local dignostic filter to show the interaction.   
    * I can see moving some parts of it, like the grammar rule, and the one-sentence definition.  Is that what you mean

* Built-in values seems like it should be moved as a subsection of 10.3.1 Inter-stage Input and Output Interface, as a peer to "User-defined inputs and outputs".  ?

* Separately, the table in built-in values is unweildy, particularly due to recent changes for "position".  It might profit from breaking out to be more like how we do the builtins, more like a Unix manual page entry.

**Comment by dneto0** [comment]
I think Directives also probably needs a forward reference from WGSL module.

**Comment by alan-baker** [comment]
> It's not clear that moving Global diagnostic filter to the directives chapter is a win.

I would still keep all the filtering descriptions, but forward reference the grammar element as you suggest. It would split a small part out.

> Built-in values seems like it should be moved as a subsection of 10.3.1 Inter-stage Input and Output Interface, as a peer to "User-defined inputs and outputs". ?

That's certainly possible and it aligns nicely with `@interpolate` enumerants. So that sounds like a good suggestion.

> Separately, the table in built-in values is unweildy, particularly due to recent changes for "position". It might profit from breaking out to be more like how we do the builtins, more like a Unix manual page entry.

I've had similar thoughts as well. Sometimes I wish they were subsections accessible from the side navigation bar. That rework can be probably be done in a separate change.

I'll update the description with these updates (including renaming technical overview)

**Comment by dneto0** [comment]
Sounds good to me.  Thanks!

**Comment by mehmetoguzderin** [comment]
I think the proposal will really help for a better reading experience! I had a small question.

> * Texture Structure

Can we avoid renaming "Textual Structure" to "Texture Structure" (if this was intended)?

**Comment by alan-baker** [comment]
> I think the proposal will really help for a better reading experience! I had a small question.
> 
> > * Texture Structure
> 
> Can we avoid renaming "Textual Structure" to "Texture Structure" (if this was intended)?

That was unintended

**Comment by mehmetoguzderin** [comment]
Thank you!
