### ISSUE TITLE
Allow forward declaration of functions

### ISSUE THREAD

**Issue by wrightwriter** [gpuweb/gpuweb#4162]
Helps with readability of larger shaders, where you want the gist of the shader to be separated from utility functions. Can also be included to a shader with a preprocessor to require implementation.

**Comment by ben-clayton** [comment]
Are you aware that WGSL allows you to declare any module-scope declaration (function, variable or type) after its usage?

**Comment by wrightwriter** [comment]
I am now, that seems good to me, nevermind.
