### ISSUE TITLE
Reference High Resolution Time spec

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4175]
We have some language about how timestamps should be coarsened in our spec:

> WebGPU also specifies the "timestamp-query" feature, which provides high precision timing of GPU operations. The feature is optional, and a WebGPU implementation may limit its exposure only to those scenarios that are trusted. Alternatively, the timing query results could be processed by a compute shader and aligned to a lower precision.
> https://gpuweb.github.io/gpuweb/#security-timing

I think we should probably point to the High Resolution Time spec to be more prescriptive here.
https://w3c.github.io/hr-time/#dfn-coarsen-time

**Comment by jyasskin** [comment]
I see in https://groups.google.com/a/chromium.org/g/blink-dev/c/dtYJ0MQYMlU/m/TT_TQtneBgAJ that Chromium is looking at coarsening the GPU timestamps to 100µs in isolated contexts and hiding the values entirely in non-isolated contexts, while HR-time coarsens to 5µs in isolated contexts and 100µs in non-isolated timestamps (or coarser if the implementation prefers). Unless there's a rationale for keeping GPU timestamps coarser than CPU timestamps (e.g. a particular application of [Clock Around the Clock: Time-Based Device Fingerprinting](https://dl.acm.org/doi/10.1145/3243734.3243796) that's only available through these timestamps), it seems fine to align those.

HR-time also uses the notions of a couple ["clocks"](https://w3c.github.io/hr-time/#sec-clocks), where [moments](https://w3c.github.io/hr-time/#moments-and-durations) are only comparable to moments from the same clock.. Neither the wall clock nor the monotonic clock matches the behavior of the clock in this spec, so you'll probably want to define your own using the text in https://gpuweb.github.io/gpuweb/#timestamp.

**Comment by Kangz** [comment]
@kainino0x for this week's meeting can you drive the discussion around "Can we agree on the availability of timestamp queries (provided there is hardware support) and the quantization depending on contexts." ?

**Comment by kainino0x** [comment]
Can do.

**Comment by kainino0x** [comment]
> Unless there's a rationale for keeping GPU timestamps coarser than CPU timestamps (e.g. a particular application of [Clock Around the Clock: Time-Based Device Fingerprinting](https://dl.acm.org/doi/10.1145/3243734.3243796) that's only available through these timestamps), it seems fine to align those.

At the resolutions we're talking about, and with the slow channel between the GPU and the content process, my intuition is this won't create new problems.

FWIW though, I don't think it's clear whether site isolation actually provides anything for us, since these timestamps run on the GPU and are issued from the GPU process, neither of which is typically isolated. For the spec, I might propose we start out by using only the coarser 100us resolution regardless of isolation, in line with that fact.

**Comment by jimblandy** [comment]
<details><summary><a href="https://docs.google.com/document/d/1IFhPws-8qhCOKGcUCGZDJ1SmIUbdX7wAKswj_7f-DsA/edit#heading=h.nv3k2xqpyuct">Agenda / Minutes for GPU Web meeting 2023-11-01</a></summary>

- KN: I was assigned to discuss this. We have timestamp queries in WebGPU. Haven't shipped yet, would like to. Requires figuring out coarsening. Bug suggests we point to the W3C high-res time spec to prescribe particular behavior. That spec says that timestamps should be coarsened to 100 us (microseconds) if non-origin-isolated and 5 us if isolated. Seem reasonable to me. But one thing: our timestamps aren't running in the isolated context, but on the GPU. Typically shared between isolated contexts. Even if not (separate GPU process per isolated process), GPUs don't isolate things as well as CPUs nowadays. Tentatively thinking we should say: always behave as if non-cross-origin-isolated, coarsen to 100 us.
- JB: makes solid sense.
- JB: security paper we were alerted to last month, using GPU for timing attacks through GPU cache. One takeaway: high res clocks on the GPU. If people can construct their own clocks it may not matter if we coarsen them. But, these are measuring something different, hard to roll your own shader for? The fact that you can get high-res timings from compute shaders probably doesn't make it less necessary to coarsen these timestamps.
- KN: wouldn't be confident. Might be possible to get 2 pcs of code to run on the GPU at the same time. Probably 2 cores, separated by buses. 2 things running at the same time using the same storage area - 2 draw calls in same render pass. They can run at the same time, so interference is possible. But not confident you can build a timer with that.
- JB: both Moz & Goog's response to this was - this was not the attack people will use. Exotic. There are less exotic attacks. No action in response to this report. If not addressing this disclosure, is it imp't for us to coarsen this timer at all? What are the security implications?
- KN: 1) don't know 2) we know it's relatively easy to coarsen these. These are much easier to use. You can do high-res time on the GPU with these. Dubious to do this any other way. And easy for us to fix, think we should.
- KR: There was an attack reported a few years ago - the first real, serious attack we couldn’t plug - that executed Rowhammer on the GPU with WebGL. It required getting high precision timestamps from the timestamp queries. They could see cache miss rates. They could get a layout of physical memory on the GPU, target a particular bit to flip with rowhammer, and trick the page table into doing something insidious. Their attack was limited to a particular device with a very clearly defined TLB design. Rowhammer mitigations in newer RAM also avoided this.
- JB: so very fine timestamps can help you probe the GPU architecture, so worth coarsening them.
- KN: another attack suggested was the one jyasskin linked - "clock around the clock". Tries to see how fast the chip's clock goes. Uses for fingerprinting. Another thing possibly could apply here - timestamp clocks are implemented in ticks, then we convert to real-time format. Some designs might have actual clocks.
- JB: upshot: we're going to use non-isolated coarsening for all GPU work.
- KN: yes, that's my suggestion, can loosen it if we want too.
- JB: sounds good.

</details>

**Comment by fintelia** [comment]
It may be worth investigating how much resolution timestamps need in order to be useful to GPU applications. If they are coarsened to 100us, then even at 60 FPS there are only 167 possible distinct timestamps that could be collected over the course of a frame. At higher frame rates that number would drop even further.

**Comment by kainino0x** [comment]
Indeed, we'll definitely be listening for issues developers run into with this resolution (if anyone does - please file a new issue). Note we wouldn't consider making it finer unless it's needed in production - browsers will probably have a way to disable the quantization for local development (Chromium already does).
