### ISSUE TITLE
GPUDevice.createBuffer() may throw in content timeline

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#4182]
In [Firefox](https://searchfox.org/mozilla-central/rev/b91e9bef5a6d6f7b549fbc9cba70cb4665ed3866/dom/webgpu/Buffer.cpp#76) and [Chromium](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:third_party/blink/renderer/modules/webgpu/gpu_buffer.cc;l=146;drc=f2c32198ce5251791dc0a79ad63404509c22fee1) implementations, `GPUDevice.createBuffer()` may throw in content timeline, the spec doesn't say this.

I believe the spec should reflect this. WDYT?

**Comment by kainino0x** [comment]
The spec does define the exception here, indirectly through the `?` shorthand:
>Set b.[[[mapping]]](https://gpuweb.github.io/gpuweb/#dom-gpubuffer-mapping-slot) to [?](https://tc39.es/ecma262/#sec-returnifabrupt-shorthands) [initialize an active buffer mapping](https://gpuweb.github.io/gpuweb/#abstract-opdef-initialize-an-active-buffer-mapping) with mode [WRITE](https://gpuweb.github.io/gpuweb/#dom-gpumapmode-write) and range [0, descriptor.[size](https://gpuweb.github.io/gpuweb/#dom-gpubufferdescriptor-size)].

which means, if "initialize an active buffer mapping" throws, stop here and continue throwing that error.
