### ISSUE TITLE
Floating Point rules + const/override allow for significantly different implementation behaviours

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#4183]
This originates from attempting to write CTS tests for validation of numeric calculations. An example of the problem:
```
const max_f32: f32 = 3.40282346639e+38f;
const r: f32 = max_f32 + max_f32;
```
This comes out to a infinitely precise value of 2 * max_f32, which is not representable as a f32.
The question is what should happen in this case. Intuitively this should cause a shader compilation error, since the result cannot be stored in the f32.

The issue comes from the fact that acceptable set of values returned by this operation is not a singular point, but instead of an interval of floating point values.

Specifically, addition is defined as being correctly rounded, the interval covered from rounding up and down from the precise value, [spec](https://www.w3.org/TR/WGSL/#floating-point-accuracy). Since the result for this is out of bounds, then bounds of the interval are 3.40282346639e+38f (max f32) and positive infinity.

This creates an issue, since if an implementation rounds to max f32 then the value is finite, and the shader should compile. But if the implementation instead chooses to round to infinity, then this should fail validation, causing a shader compilation error. Thus from a developer's perspective it is ambiguous on whether or not this shader is valid.

A variety of similar issues arise from other floating point operations, either due to being correctly rounded or having other accuracy bounds.

**Comment by dneto0** [comment]
I agree:   
* implementations are allowed to round down or to round up
* So either max_f32 or infinity are ok answers
* So either can compile (max_f32 case) or fail to compile (infinity case) are ok answers.

I checked IEEE 754 2008 again.  From 7.4 "Overflow" it says

> The overflow exception shall be signaled if and only if the destination format’s largest finite number is
exceeded in magnitude by what would have been the rounded floating-point result (see 4 [Attributes and Rounding]) were the exponent range unbounded. 

It's interesting that it presumes the infinitely precise result as allowing the exponent to be unbounded, which can bracket any (finite) real number.


And then:
...

> roundTiesToEven and roundTiesToAway carry all overflows to ∞ with the sign of the intermediate
result.

> roundTowardZero carries all overflows to the format’s largest finite number with the sign of the
intermediate result.

So yes, either maxf32 or infinity are ok answers.

**Comment by zoddicus** [comment]
I think I may have buried my primary concern here, in how I stated the issue.

I think the primary issue is that two different conformant implementations of WGSL could tell a developer different things about whether or not a shader is valid. This introduces potential issues with portability/cross browser compatibility.

I do agree with your analysis of the situation, and think that you PR clarifies when this issue occurs. But I don't think it resolves the potential for this portability issue.

Additionally as spec'd it makes the CTS somewhat tricky to write, since we will have to do something like try to compile this shader. If it fails to compile, that is a pass, else run it as an execution test and check the results. This type of multi-level check being need, being baked into the spec concerns me.

**Comment by dneto0** [comment]
Right.  On reflection it would be sad to have such wildly different behaviours.

What if const-eval can rely on stronger fp rules that ECMAScript might have.  If ECMAScript operates in a rounding mode that means you get infinity, then we can adopt that.
Need to investigate.

**Comment by dneto0** [comment]
ECMAScript [6.1.6.1 The Number Type](https://262.ecma-international.org/13.0/#sec-ecmascript-language-types-number-type) says:

> In this specification, the phrase “the Number value for x” where x represents an exact real mathematical quantity (which might even be an irrational number such as π) means a [Number value](https://262.ecma-international.org/13.0/#number-value) chosen in the following manner. 

... (explains an algorithm with specific numbers special-cased to 64-bit floats.)

> (This procedure corresponds exactly to the behaviour of the [IEEE 754-2019](https://262.ecma-international.org/13.0/#sec-bibliography) roundTiesToEven mode.)

> The [Number value](https://262.ecma-international.org/13.0/#number-value) for +∞ is +∞𝔽, and the [Number value](https://262.ecma-international.org/13.0/#number-value) for -∞ is -∞𝔽.

So that's a good start.

**Comment by dneto0** [comment]
C++ isn't guaranteed to have IEEE 754 behaviors for infinitiies and NaNs.
However, it commonly does on CPUs.  It also can report whether it supports it via std::numeric_limits<T>::has_infinity and also ...::is_iec559

Note that IEC559 is the equivalent of IEEE 754. (indirecting through standards bodies).

Note: When chasing through the C++ spec, foot notes of "LIA-1" refer to "Language Independent Arithmetic - 1", which is IEC 10967 (e.g. see wikipedia here: https://en.wikipedia.org/wiki/ISO/IEC_10967 )  IEC 10967 describes integer arithmetic and also floating point arithmetic behaviours from IEEE 754, but not the data formats specified by IEEE 754.

I conclude that it's very common for CPU C++ to have IEEE 754, in particular I assume all browsers do.

**Comment by dneto0** [comment]
Rust defines f32 and f64 as corresponding to IEEE 754.   They have infinities.

https://doc.rust-lang.org/std/primitive.f32.html 
https://doc.rust-lang.org/std/primitive.f64.html

**Comment by dneto0** [comment]
So, I think we can save ourselves here by this chain of logic:

1. const-expression evaluation is done on CPUs with IEEE754 floating point.

2. IEEE overflow rounding says (repeating here):

> The overflow exception shall be signaled if and only if the destination format’s largest finite number is
exceeded in magnitude by what would have been the rounded floating-point result (see 4 [Attributes and Rounding]) were the exponent range unbounded.

The part about "were the exponent range unbounded" is key here.  If the floating point type is T, let  EMAX be the exponent of the largest representable value in T, and so 2<sup>EMAX+1</sup> is not representable in T.

Now consider a very large value X.  If X rounds up _**or down to**_ 2<sup>EMAX+1</sup>, then the overflow condition occurs.  And in this case roundTiesToEven means infinity should be the result.   Note this happens even if the original rounding mode is unspecified.

3. Therefore, assuming const-expressions are evaluated using IEEE 754 rules for infinity and overflow, then implementations can reliably produce the shader-creation error for overflow and infinities case.

4. This argument applies whether the const-expression is being evaluated in f32 or AbstractFloat.


I would argue that override-expression could follow the same set of deductions.  To split hairs, this means override expressions are fully evaluated using CPU rules for infinities and overflows.


The spec update would be something like:

- Evaluation of floating point const-expressions follow IEEE 754 rules for overflow and infinities. In particular an intermediate computation which would round down to 2<sup>EMAX+1</sup>  yields an infinity and results in a shader-creation error. 
EMAX=127 for f32, EMAX=1023 for AbstractFloat.   (Repeat similar statement for rounding up to -2<sup>EMAX+1</sup>)
- Evaluation of floating point override-expressions follow .....   pipeline-creation error.
