### ISSUE TITLE
writeBuffer/writeTexture works with shared ArrayBufferViews but not SharedArrayBuffer

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4186]
The current definition of `[AllowShared] BufferSource` probably excludes `SharedArrayBuffer` (though IIRC it's ambiguous, see #4042).

We should do something to make `SharedArrayBuffer` explicitly allowed, e.g. use `SharedArrayBuffer or [AllowShared] BufferSource` like here: https://github.com/whatwg/webidl/issues/961#issuecomment-1537384391

Currently, the workaround for this is to simply wrap the SharedArrayBuffer in a Uint8Array: `new Uint8Array(mySAB)`

**Comment by Kangz** [comment]
Seems to have been fixed in this PR https://github.com/whatwg/webidl/pull/1311

Editors: can you check if this can just be closed?

**Comment by kainino0x** [comment]
It was fixed in https://github.com/gpuweb/gpuweb/pull/4188, forgot to link it. Thanks for catching this!
