### ISSUE TITLE
frexp + subnormals needs to be fully clarified

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#4190]
[Previously](https://github.com/gpuweb/gpuweb/issues/3970), the spec was updated to state that accuracy for `frexp(x)` was undefined when `x` is subnormal, due to a class of known devices not supporting this.

The actual definition of [frexp](https://www.w3.org/TR/WGSL/#frexp-builtin) was not updated, so there is some missing details now.

For f32 and f16, I think all that needs to be done is change:
```
Otherwise, e is NaN or infinite. The result fraction and exponent are indeterminate values.
```
to say
```
Otherwise, e is subnormal, NaN or infinite. The result fraction and exponent are indeterminate values.
```

For AbstractFloat I am not sure what should be done, since the text is slightly different:
```
When e is zero, the fraction is zero.

When e is non-zero and normal, e = fraction * 2exponent, where the fraction is in the range [0.5, 1.0) or (-1.0, -0.5].

NOTE: AbstractFloat expressions resulting in infinity or NaN cause a shader-creation error.
```
I am unsure if AbstractFloat should be expected to handle subnormals (which would potentially cause significant differences in computed results between runtime and compile time evaluation of floating point operations), or if it should be a shader-creation error.

This I think it part of the large discussion about AF accuracy, https://github.com/gpuweb/gpuweb/issues/4134.

**Comment by zoddicus** [comment]
The resolution of this will have potential knock on effect on AF testing in general, since the code snippet that we are using for extracting AF values uses `frexp`. If subnormals are not handled for AF, this means in general we cannot extract subnormal AFs in the CTS.

The CTS could fall back to using const_assert to test subnormal cases, but that is less then optimal.

**Comment by dneto0** [comment]
> If subnormals are not handled for AF, this means in general we cannot extract subnormal AFs in the CTS.

What if we define WGSL so that AF subnormals can be flushed to zero.
Then is it true that CTS code can then check for the optional zero?

ECMAScript seems to allow for implementations not supporting denormals.
It's pretty sideways about it.  https://262.ecma-international.org/13.0/#sec-number.min_value  : 

> In the [IEEE 754-2019](https://262.ecma-international.org/13.0/#sec-bibliography) double precision binary representation, the smallest possible value is a denormalized number. If an implementation does not support denormalized values, the value of Number.MIN_VALUE must be the smallest non-zero positive value that can actually be represented by the implementation.

**Comment by zoddicus** [comment]
> > If subnormals are not handled for AF, this means in general we cannot extract subnormal AFs in the CTS.
> 
> What if we define WGSL so that AF subnormals can be flushed to zero. Then is it true that CTS code can then check for the optional zero?
> 
> ECMAScript seems to allow for implementations not supporting denormals. It's pretty sideways about it. https://262.ecma-international.org/13.0/#sec-number.min_value :
> 
> > In the [IEEE 754-2019](https://262.ecma-international.org/13.0/#sec-bibliography) double precision binary representation, the smallest possible value is a denormalized number. If an implementation does not support denormalized values, the value of Number.MIN_VALUE must be the smallest non-zero positive value that can actually be represented by the implementation.

To be clear, allowing FTZ for AF would need to inlcude adding something like:
- When e is subnormal, the fraction is zero.
to the definition of `frexp`

That would be be sufficient for testing in the CTS, since then subnormals wouldn't be causing a compile error when the CTS is trying to extract them.

I think this would correctly catch all subnormal cases, since if the backend is allowed to FTZ, then if the result is a subnormal, 0 is always in the acceptance interval.

The only cases we would technically would be overly permissive of, are ones where the result is precisely 0, without the subnormals. Then the CTS would accept the result if it is a subnormal, since it was flushed, but I think these cases are very rare if they exist at all.

**Comment by dneto0** [comment]
Looking at this again, it seems sad/wrong to allow indeterminate value for subnormal.
If what's going on is flushing to zero, then the result for subnormal is either the "correct" result (like normal), or zero.

I just tried on a CPU with g++ and it gets correct answers for subnormal.

So this would be a fourth clause for subnormal, rather than lumping together with any of the other three.

**Comment by dneto0** [comment]
Here's a sample program you can try at home

```cpp
#include <iostream>
#include <cmath>


int main() {
  float y = 1.0;
  do {
    int e = 0;
    float frac = frexp(y, &e);
    std::cout << " y  " << y << " normal? " << isnormal(y) << " " << frac << " " << e << std::endl;
    y /= 2;
  } while (y > 0);
  return 0;
}

```

**Comment by dneto0** [comment]
Oh never mind.  Looking at the original issue #3970 and the actual failing cases, it's not a "correct or zero".
It's a very wrong answer.  So yeah, indeterminate value it is.

**Comment by dneto0** [comment]
Here's one case that failed,  copying from https://bugs.chromium.org/p/tint/issues/detail?id=1877#c1

>  Reproduced on my NUC Ubuntu with UHD 630 GPU. Looks like the problem is when the input value is subnormal, the returned value is very close to 0, but not 0. Example:

```
  - EXPECTATION FAILED: (-1.1754942106924411e-38 (0x807fffff subnormal))
        returned: -1.1754942106924411e-38 (0x807fffff subnormal)
        expected: -0.9999998807907104 (0xbf7ffffe) or 0.0 (0x00000000 subnormal)
```
