### ISSUE TITLE
API should be exposed to ServiceWorker

### ISSUE THREAD

**Issue by MiguelsPizza** [gpuweb/gpuweb#4197]
Would be nice to have and I can't think of any reason not to expose WebGPU to a service worker considering Webgl is accessible.

It's only exposed to the Window and DedicatedWorkers at the moment. Reference: https://gpuweb.github.io/gpuweb/#navigator-gpu
[Exposed=(Window, DedicatedWorker), SecureContext]

Similar [issue](https://github.com/gpuweb/gpuweb/issues/1882) regarding exposing webGPU to a dedicated worker:

**Comment by kainino0x** [comment]
Thanks for filing this, I didn't realize we didn't have an issue for this :)
I think we should do it. It seems WebGL just uses `Worker`. I don't know how to find an official listing of the `Worker` types but Chromium documents it as `DedicatedWorker`, `SharedWorker`, and `ServiceWorker`:
https://chromium.googlesource.com/chromium/src/+/main/third_party/blink/renderer/bindings/IDLExtendedAttributes.md#exposed

So along with this, likely we should expose it in `SharedWorker` too.

**Comment by MiguelsPizza** [comment]
No Problem, thanks for the prompt response! 

Let me know if there is anything I can do to help get this to the finish line

**Comment by libofei2004** [comment]
@MiguelsPizza  Is there no way to use webgpu in webview in android?

**Comment by Jasonsey** [comment]
hi there, as far as I know,  [Tensorflow.js recomend using AI models in background.js (using service worker) for chrome-extension ](https://github.com/tensorflow/tfjs-examples/tree/master/chrome-extension) . So, I am really  looking forward to this new feature

**Comment by tqchen** [comment]
Also love to see WebGPU being exposed to service worker

**Comment by kainino0x** [comment]
> I don't know how to find an official listing of the `Worker` types but Chromium documents it as `DedicatedWorker`, `SharedWorker`, and `ServiceWorker`:

MDN also documents it as those 3.
https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope

**Comment by tqchen** [comment]
Thank you @beaufortfrancois @kainino0x, would be great to know how we are doing in terms of support status, love to followup and try out as soon as it lands

**Comment by beaufortfrancois** [comment]
We'll let you know when it's available behind a flag in Chrome so that you can play around.

**Comment by beaufortfrancois** [comment]
@tqchen @MiguelsPizza You can now **play** with WebGPU in a service worker in [Chrome Canary 123.0.6271.0](https://chromiumdash.appspot.com/commit/396fc572acacc3e8602f581c10a83a351f6361b7) by enabling the "Experimental Web Platform features" flag at `chrome://flags/#enable-experimental-web-platform-features`.

Here's an extension sample I've created to demonstrate its usage: https://gist.github.com/beaufortfrancois/4795c20bc4d147e0400303d0b8ec02d6

Let me know how it goes ;)

**Comment by beaufortfrancois** [comment]
@tqchen @MiguelsPizza Did you have a chance to experiment with Service Worker support in Chrome? Did you find some limitations or bugs we should be aware of?

**Comment by MiguelsPizza** [comment]
> @tqchen @MiguelsPizza Did you have a chance to experiment with Service Worker support in Chrome? Did you find some limitations or bugs we should be aware of?

**Comment by tqchen** [comment]
https://github.com/mlc-ai/web-llm/pull/296  @rickzx should be able to comment more :) really excited about what it can enable

**Comment by rickzx** [comment]
@beaufortfrancois @tqchen Thanks a lot for putting the effort to support WebGPU in service worker. I was able to put up a sample Chrome extension running LLM in the service worker in the background, and a popup window as a chat assistant. It's much simpler and more elegant to implement this now with the service worker support. Haven't encountered any bugs so far.

**Comment by beaufortfrancois** [comment]
@tqchen @MiguelsPizza @rickzx I'm happy to report that Chrome nows supports WebGPU in service worker by default as of [Chrome 124.0.6359.0](https://chromiumdash.appspot.com/commit/8d78510e4aca5ac3cd8ee4a33e96b404eaa43246) (Canary at this moment) 🎉

**Comment by beaufortfrancois** [comment]
And to close the loop, here's the official announcement: https://developer.chrome.com/blog/new-in-webgpu-124?hl=en#service_workers_and_shared_workers_support
