### ISSUE TITLE
API spec build broken with latest bikeshed 3.13.1

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4199]
### Discussed in https://github.com/gpuweb/gpuweb/discussions/4198

<div type='discussions-op-text'>

<sup>Originally posted by **JustAnotherCodemonkey** June 25, 2023</sup>
Running `make` returns an error (`LINK ERROR: Multiple possible 'TypeError' idl refs.`). What's the proper way to build? I can't find any documentation on this.

Running macos 13.4 intel chip. I installed Bikeshed via pip.</div>

**Comment by kainino0x** [comment]
The current version of Bikeshed we're using is 3.12.1, but that's not working for me because of a 400 error:
```
Updating via manifest...
Gathering local manifest data...
Fetching remote manifest data...
WARNING: Previous update had some download errors, so re-running...
Updating 10 files...
WARNING: Error downloading , full error was:
400, message='Bad Request', url=URL('https://raw.githubusercontent.com/speced/bikeshed-data/master/data/')
Updated 9/10, 1 errors...
FATAL ERROR: Done, but there was 1 error (of 10 total) in downloading or saving. Run `bikeshed update` again to retry.
 ✘  Did not generate, due to fatal errors
```

Bikeshed 3.13.0+ fixes this.

**Comment by kainino0x** [comment]
I'm not exactly sure what's up with the TypeError issue but there's at least an easy fix, so I'll land that.

**Comment by JustAnotherCodemonkey** [comment]
That was fast! It does work now.

**Comment by kainino0x** [comment]
We had to fix it anyway, you just got unlucky stumbling upon it early. Thanks for reporting and confirming!
