### ISSUE TITLE
Definition of fixed-footprint types seems to include abstract types

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#4212]
The section "Fixed-Footprint Types" says:

> The types with creation-fixed footprint are:
> 
> -   a scalar type
> -   a vector type
> -   a matrix type
> -   an atomic type
> -   a fixed-size array type, when:
>     -   its element count is a const-expression.
> -   a structure type, if all its members have creation-fixed footprint.

This seems to include abstract types, even though the paragraph above says, "All creation-fixed footprint and fixed footprint types are storable", and abstract types are not storable types.

It seems to me that the definition of creation-fixed footprint types should start the way that of storable types does:

> A type is storable if it is both concrete and one of: ...

**Comment by dneto0** [comment]
Yes, there's a problem.

There's a contemplation of the problem already in that the definition of creation-fixed foot print already is conditional on the concretization of a type:

> A type has a creation-fixed footprint if its [concretization](https://gpuweb.github.io/gpuweb/wgsl/#feasible-automatic-conversion) has a size that is fully determined at [shader creation](https://gpuweb.github.io/gpuweb/wgsl/#shader-module-creation) time.

Alignment and size has this use of fixed-footprint:

> Each [host-shareable](https://gpuweb.github.io/gpuweb/wgsl/#host-shareable) or [fixed footprint](https://gpuweb.github.io/gpuweb/wgsl/#fixed-footprint) data type T has an alignment and size. 

That depends on concreteness.

There are a bunch of uses of creation-fixed footprint. (15 of them)
E.g. an array element type must be an array type element may be an array with a creation-fixed footprint

At this point I'd probably fix this by adjusting the statement about storability

> All concrete creation-fixed footprint and concrete fixed footprint types are storable.
