### ISSUE TITLE
Enable WebGPU in Safari TP

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#4238]
@litherum https://github.com/gpuweb/gpuweb/wiki/Implementation-Status#safari-in-progress currently says:

> Work is in progress in [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/).
> 
> To enable WebGPU, first make sure the Develop menu is visible using `Safari` → `Preferences` → `Advanced` → `Show Develop menu in menu bar`. Then, in the `Develop` menu, make sure `Experimental Features` → `WebGPU` is checked. **Avoid leaving it enabled when browsing the untrusted web.**

However when I check locally in STP, I can't find WebGPU as you can see below. Am I holding it wrong?

<img width="1042" alt="image" src="https://github.com/gpuweb/gpuweb/assets/634478/8e096d22-f3e7-4e4d-ac02-6faca1cf7912">

**Comment by beaufortfrancois** [comment]
@litherum (gentle ping)

**Comment by R00tkitSMM** [comment]
any comment on this question?

**Comment by beaufortfrancois** [comment]
@mwyrzykowski may be able to help us.

**Comment by mwyrzykowski** [comment]
It is not possible to enable WebGPU in Safari Technology Preview. I updated that page.

**Comment by beaufortfrancois** [comment]
Thank you @mwyrzykowski for https://github.com/gpuweb/gpuweb/wiki/Implementation-Status/_compare/4eb271351ebc246b14ca3653250bf0c8868f1c2b!

**Comment by beaufortfrancois** [comment]
Out of curiosity, is it possible to download WebKit and update code in a way I can test WebGPU in Safari with `Tools/Scripts/run-safari --debug`?
I tried enabling the feature without any luck.

**Comment by mwyrzykowski** [comment]
@beaufortfrancois Currently it is necessary to compile with `-D ENABLE_WEBGPU_BY_DEFAULT=1` to see any effect https://github.com/WebKit/WebKit/blob/main/Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml#L7648C40-L7648C40

Feel free to try but it is in no way supported and can be broken at any time. I usually test in MiniBrowser as well: ` ./Tools/Scripts/run-minibrowser --release`

**Comment by R00tkitSMM** [comment]
Thank you. So much help.

**Comment by beaufortfrancois** [comment]
Thanks @mwyrzykowski, the steps below worked for me!

```bash
git clone https://github.com/WebKit/WebKit.git WebKit
cd WebKit
Tools/Scripts/build-webkit -cmakeargs="-DENABLE_WEBGPU_BY_DEFAULT=1" --debug
Tools/Scripts/run-minibrowser --debug
```

![image](https://github.com/gpuweb/gpuweb/assets/634478/3a11572b-382d-4f88-90e2-3f22596bf3a8)

**Comment by munrocket** [comment]
Not compiled on Intel and M1. Anyway waiting for support in Safari TP.

![](https://i.imgur.com/4nSLDuf.png)

**Comment by R00tkitSMM** [comment]
@munrocket just scroll up a little you can see the reason.

**Comment by greggman** [comment]
works in Safari Preview 185

<img width="1299" alt="Screenshot 2023-12-20 at 17 43 05" src="https://github.com/gpuweb/gpuweb/assets/234804/5541ed72-5ad8-49f7-b7e9-efd7031918dd">

**Comment by mwyrzykowski** [comment]
That’s right :) I’ll update the page

**Comment by quantuminformation** [comment]
why is it still stuck in Tp in canIuse

**Comment by munrocket** [comment]
Yea, it’s pretty good, sometimes totally freezing iOS.

**Comment by mwyrzykowski** [comment]
> Yea, it’s pretty good, sometimes totally freezing iOS.

@munrocket would it be possible to please file a bug at https://bugs.webkit.org/enter_bug.cgi regarding the 'totally freezing iOS' please? We would be very much interested in such a report

**Comment by munrocket** [comment]
@mwyrzykowski it's not a bug it related to OffscreenCanvas. Rendering happens in the main process and CPU junk from compute.toys freezing the world (scrolls, etc.).

**Comment by mwyrzykowski** [comment]
Do you have compute.toys examples which trigger this @munrocket ? I regularly try a few of them, very cool demos 👍

**Comment by munrocket** [comment]
Anything heavy enough https://compute.toys/view/1640

**Comment by quantuminformation** [comment]
does it work in safari yet?
