### ISSUE TITLE
 Failed to execute 'importExternalTexture' on 'GPUDevice': Failed to import texture from video frame that doesn't have back resource

### ISSUE THREAD

**Issue by yangfangfang1204** [gpuweb/gpuweb#4242]
WebGPUDisplay.js:123 Uncaught (in promise) DOMException: Failed to execute 'importExternalTexture' on 'GPUDevice': Failed to import texture from video frame that doesn't have back resource

i test the web codecs demo [renderer_webgpu.js](https://github.com/w3c/webcodecs/blob/main/samples/video-decode-display/renderer_webgpu.js)

there is a error . `Failed to import texture from video frame that doesn't have back resource`

**Comment by Kangz** [comment]
This is an issue either in the repo you linked to, or in Chromium. Could you make a guess as to which it is and file an issue in the appropriate place? (either that repo or crbug.com)?

This repo is for the WebGPU spec only.
