### ISSUE TITLE
 Investigation: Render to 3D texture

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#4251]
# Motivation
The feature of rendering to 3d texture is requested in [#2877](https://github.com/gpuweb/gpuweb/issues/2877), which has been supported in all APIs WebGPU will target.
- [D3D12](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_tex3d_rtv) and [Metal](https://developer.apple.com/documentation/metal/mtlrenderpassattachmentdescriptor/1437952-depthplane?language=objc) support rendering to a 3d texture by 3d texture view. 
- [Vulkan](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_maintenance1.html) supports rendering to a 3d texture by 2d/2d array texture views in Vulkan 1.1 core.

This report investigates how to support rendering to 3d texture in WebGPU. The texture view and render attachment we discuss next will focus on 3d texture. And the texture usage and format required for 3d texture/view as a render attachment are the same as 2d texture/view, so I won't repeat them here.

# Native APIs
### D3D12
In D3D12, we can directly render to the slices of a 3d texture using 3d render target view created by [ID3D12Device::CreateRenderTargetView()](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-createrendertargetview) with [D3D12_TEX3D_RTV](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_tex3d_rtv) struct in [D3D12_RENDER_TARGET_VIEW_DESC](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_render_target_view_desc).

```
typedef struct D3D12_RENDER_TARGET_VIEW_DESC {
  DXGI_FORMAT         Format;
  D3D12_RTV_DIMENSION ViewDimension;
  union {
    D3D12_BUFFER_RTV        Buffer;
    D3D12_TEX1D_RTV         Texture1D;
    D3D12_TEX1D_ARRAY_RTV   Texture1DArray;
    D3D12_TEX2D_RTV         Texture2D;
    D3D12_TEX2D_ARRAY_RTV   Texture2DArray;
    D3D12_TEX2DMS_RTV       Texture2DMS;
    D3D12_TEX2DMS_ARRAY_RTV Texture2DMSArray;
    D3D12_TEX3D_RTV         Texture3D;
  };
} D3D12_RENDER_TARGET_VIEW_DESC;
```
- `Format` specifies the viewing format of RTV. It needs to be compatible with the format of resource and **must not** be any typeless format.
- `ViewDimension` specifies the typed value of the resource to view as a render target. `D3D12_RTV_DIMENSION_TEXTURE3D ` identifies the resource will be accessed as a 3d texture. It also determines which _RTV item to use in the following union struct. 
- `Texture3D` specifies subresources in a 3d texture that can be accessed.
 
```
typedef struct D3D12_TEX3D_RTV {
  UINT MipSlice;
  UINT FirstWSlice;
  UINT WSize;
} D3D12_TEX3D_RTV;
```
- `MipSlice` specifies the index of the mipmap level to use mip slice in the RTV.
- **`FirstWSlice`** specifies the first depth level to use in the RTV. It **must** be between 0 and the DepthOrArraySize-1 of the texture resource at the `MipSlice`.
- `WSize` specifies the number of depth levels to use in the RTV, starting from `FirstWSlice`. A value of -1 indicates all depth slices from `FirstWSlice`.

### Metal
In Metal, [newTextureViewWithPixelFormat()](https://developer.apple.com/documentation/metal/mtltexture/1515409-newtextureviewwithpixelformat/)can create the 3d view on a 3d texture with the type `MTLTextureType3D`. But it only can restrict the range of mip `levels` and array `slices` for subresource that can be accessed, the `slices` range must be (0, 1) for 3d texture, there is no parameter to restrict the range of depth slices like D3D12, which means all depth slices of 3d texture can be accessed in the view.

On iOS 8.0+ and macOS 10.11+, Metal provides `depthPlane` property in [MTLRenderPassAttachmentDescriptor](https://developer.apple.com/documentation/metal/mtlrenderpassattachmentdescriptor?language=objc) to restrict depth slice for 3d texture bound as a render target, it has following properties:
- `texture` specifies the texture associated with render pass attachment.
- `level` specifies the mipmap level of the texture used for rendering to the attachment.
- `slice` specifies the array slice of the texture used for rendering to the attachment.
- **`depthPlane`** specifies the depth plane of the 3d texture used for rendering to the attachment.  

There are 2 differences from D3D12:
1. The `depthPlane` restricts one depth slice of a 3d texture for rendering, not a range.
2. Metal has no texture view object, the return value of `makeTextureView()` is still a texture object, reinterpreting a subresource of the calling texture object, if the `texture` is a texture view, the values of `level` and `slice` must be based on the number of the mipmap levels and array slices of the new texture view, not the calling texture.

### Vulkan
Vulkan also does not support to specify the depth slice range for 3d texture in [VkImageSubresourceRange](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageSubresourceRange.html) struct when [creating texture view](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCreateImageView.html), and there is no any property in render attachment to specify the depth slice of a 3d texture used for rendering at [framebuffer creation](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkFramebufferCreateInfo.html).

Instead, Vulkan allows to render to 2d/2d array views created from a 3d texture(disallowed in D3D12/Metal) from [VK_KHR_maintenance1](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_maintenance1.html) that's included in core Vulkan 1.1.

```
typedef struct VkImageViewCreateInfo {
    VkStructureType            sType;
    const void*                pNext;
    VkImageViewCreateFlags     flags;
    VkImage                    image;
    VkImageViewType            viewType;
    VkFormat                   format;
    VkComponentMapping         components;
    VkImageSubresourceRange    subresourceRange;
} VkImageViewCreateInfo;
```
- `image` is a VkImage on which the view will be created. If the `image` is created with `VK_IMAGE_TYPE_3D` and used to create a 2d or 2d array view, [VkImageCreateInfo](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageCreateInfo.html)::flags **must** contain `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT` and **must not** contain any of `VK_IMAGE_CREATE_SPARSE_BINDING_BIT`, `VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT`, and `VK_IMAGE_CREATE_SPARSE_ALIASED_BIT`.
- `viewType` is a [VkImageViewType](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageViewType.html) value specifying the type of the image view. It **must** be compatible with the type of image as shown in the [view type compatibility table](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#resources-image-views-compatibility).
- `subresourceRange` is a [VkImageSubresourceRange](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageSubresourceRange.html) structure selecting the set of mipmap levels and array layers to be accessible to the view. When it is used to create the 2d/2d array view of a 3d image, `subresourceRange.baseArrayLayer` and `subresourceRange.layerCount` specify the first slice index and the number of depth slices to include in the created image view.

```
typedef struct VkImageSubresourceRange {
    VkImageAspectFlags    aspectMask;
    uint32_t              baseMipLevel;
    uint32_t              levelCount;
    uint32_t              baseArrayLayer;
    uint32_t              layerCount;
} VkImageSubresourceRange;
```
- `baseMipLevel` is the first mipmap level accessible to the view.
- `levelCount` is the number of mipmap levels (starting from `baseMipLevel`) accessible to the view. It **must** be 1 when creating 2d/2d array views on a 3d image.
- `baseArrayLayer` is the first array layer accessible to the view. It **must** be less than the depth computed from `baseMipLevel` and `extent.depth` specified in `VkImageCreateInfo` when creating 2d/2d array views on 3d image.
- `layerCount` is the number of array layers (starting from baseArrayLayer) accessible to the view. If `layerCount` is not `VK_REMAINING_ARRAY_LAYERS`, it **must** be non-zero and `baseArrayLayer` + `layerCount` **must** be less than or equal to the depth computed from `baseMipLevel` and `extent.depth` specified in `VkImageCreateInfo` when creating 2d/2d array views on 3d image. If `viewType` is `VK_IMAGE_VIEW_TYPE_2D`, `layerCount` **must** be 1 if it is not `VK_REMAINING_ARRAY_LAYERS`, otherwise the remaining number of layers **must** be 1.

# Proposal
## Texture View
In WebGPU, it only allows to create the 3d texture view on a 3d texture(see the [investigation](https://github.com/gpuweb/gpuweb/issues/1372)), that means we only can bind the 3d texture view as color attachment when rendering to 3d texture. The [GPUTexture.createView()](https://gpuweb.github.io/gpuweb/#dom-gputexture-createview) in WebGPU could meet the requirement and don't need any changes.

## Color Attachment
According to the limitation on Metal, we only can specify a single depth slice of 3d texture view in [GPURenderPassColorAttachment](https://gpuweb.github.io/gpuweb/#dictdef-gpurenderpasscolorattachment).
```
partial dictionary GPURenderPassColorAttachment {
    required GPUTextureView view;
    ...

    GPUIntegerCoordinate depthSlice;

    ...
};
```
- `view` is a renderable texture view which dimension **must** be "2d" or **"3d"**.
- `depthSlice`(*new*) is a depth slice (for 3d texture) in the `view` used for rendering to the attachment. It **must** be less than the depth slices number computed from `view`.`baseMipLevel` and `view`.`texture`.`depthOrArrayLayers`. Default to 0 and ignored for the `view` not created on 3d texture. Vulkan needs to create a new 2d/2d array views based on the `depthSlice` and the `view`.`descriptor` if the dimension of the `view` is "3d", then render to the new view.

**Comment by kainino0x** [comment]
Per #1069 we currently require (Vulkan 1.1 or VK_KHR_maintenance1 or VK_AMD_negative_viewport_height). By requiring (Vulkan 1.1 or VK_KHR_maintenance1) we might lose a few old AMD devices if they haven't had gotten more recent drivers. This seems totally fine to me - we know everything except the few at the top must have newer drivers that support this. The ones at the top probably do too.

```
Requirement "render to slice: Vulkan 1.1 or VK_KHR_maintenance1" loses 9 (and partially loses 38) further deviceNames:
  In ALL reports (9 deviceNames):
    x AMD Radeon (TM) 520: 1 (3902)
    x AMD Radeon (TM) 535DX: 1 (2914)
    x AMD Radeon (TM) R5 M430: 1 (4406)
    x AMD Radeon (TM) R7 M460: 1 (12637)
    x AMD Radeon HD 7770 GHz Edition: 1 (8041)
    x AMD Radeon R7 Graphics + R7 200 Dual Graphics: 1 (1544)
    x AMD Radeon(TM) R7 350X: 15 (1875 2974 3513 3763 3824 3918 3975 3985 4108 4189 4283 4291 4533 4641 4868)
    x Radeon Pro 575: 1 (3371)
    x Radeon Pro WX 5100: 1 (6510)
  In SOME reports (38 deviceNames):
    ~ AMD RADEON R9 M295X: 1 of 3 (1701)
    ~ AMD Radeon (TM) R7 360 Series: 1 of 9 (12997)
    ~ AMD Radeon (TM) R7 370 Series: 2 of 8 (1458 1779)
    ~ AMD Radeon (TM) R9 200 Series: 1 of 12 (1731)
    ~ AMD Radeon (TM) R9 390 Series: 1 of 37 (8485)
    ~ AMD Radeon (TM) RX 480: 1 of 2 (1457)
    ~ AMD Radeon (TM) RX 480 Graphics: 1 of 18 (2030)
    ~ AMD Radeon HD 7700 Series: 1 of 22 (1515)
    ~ AMD Radeon HD 7800 Series: 1 of 35 (4835)
    ~ AMD Radeon HD 7900 Series: 1 of 29 (6963)
    ~ AMD Radeon HD 8330: 1 of 2 (13160)
    ~ AMD Radeon HD 8400 / R3 Series: 1 of 2 (6936)
    ~ AMD Radeon HD 8500M: 1 of 4 (4088)
    ~ AMD Radeon HD 8600/8700M: 1 of 2 (1518)
    ~ AMD Radeon R5 Graphics: 1 of 10 (4520)
    ~ AMD Radeon R7 200 Series: 2 of 32 (1541 2266)
    ~ AMD Radeon R7 240: 1 of 2 (4470)
    ~ AMD Radeon R7 Graphics: 1 of 5 (2913)
    ~ AMD Radeon R7 M265 Series: 2 of 3 (1650 12374)
    ~ AMD Radeon R9 200 / HD 7900 Series: 1 of 6 (1612)
    ~ AMD Radeon R9 200 Series: 1 of 35 (4210)
    ~ AMD Radeon R9 M370X: 1 of 4 (2454)
    ~ AMD Radeon(TM) 530: 1 of 4 (2871)
    ~ AMD Radeon(TM) R2 Graphics: 1 of 3 (6079)
    ~ AMD Radeon(TM) R3 Graphics: 1 of 5 (2978)
    ~ AMD Radeon(TM) R4 Graphics: 4 of 9 (1674 3317 7508 19463)
    ~ AMD Radeon(TM) R5 240: 1 of 3 (5052)
    ~ AMD Radeon(TM) R5 Graphics: 2 of 43 (4229 8328)
    ~ AMD Radeon(TM) R5 M430: 1 of 2 (19462)
    ~ AMD Radeon(TM) Vega 8 Mobile Graphics: 1 of 5 (2457)
    ~ Radeon (TM) 530: 1 of 4 (3039)
    ~ Radeon (TM) RX 470 Graphics: 1 of 20 (1503)
    ~ Radeon (TM) RX 480 Graphics: 3 of 40 (1586 1810 5916)
    ~ Radeon RX 550 Series: 1 of 11 (1595)
    ~ Radeon RX 560 Series: 1 of 41 (1591)
    ~ Radeon RX 570 Series: 2 of 45 (1868 12605)
    ~ Radeon RX 580 Series: 1 of 82 (6862)
    ~ Radeon(TM) 520: 1 of 2 (3353)
```

**Comment by magcius** [comment]
Sorry, but is this about rendering to a *single* slice of a 2DArray/3D texture, or about allowing rendering to multiple slices of a 2DArray/3D texture (e.g. D3D12's SV_RenderTargetArrayIndex, Vulkan's shaderOutputLayer)

**Comment by aleino-nv** [comment]
> Sorry, but is this about rendering to a _single_ slice of a 2DArray/3D texture, or about allowing rendering to multiple slices of a 2DArray/3D texture (e.g. D3D12's SV_RenderTargetArrayIndex, Vulkan's shaderOutputLayer)

The 'proposals' section says:
"According to the limitation on Metal, we only can specify a single depth slice of 3d texture view in [GPURenderPassColorAttachment](https://gpuweb.github.io/gpuweb/#dictdef-gpurenderpasscolorattachment)."

I think this is alluding to "...the slices range must be (0, 1) for 3d texture...", however I couldn't find this restriction mentioned in the documentation: https://developer.apple.com/documentation/metal/mtltexture/2928180-maketextureview.

**Comment by haoxli** [comment]
>Sorry, but is this about rendering to a single slice of a 2DArray/3D texture, or about allowing rendering to multiple slices of a 2DArray/3D texture (e.g. D3D12's SV_RenderTargetArrayIndex, Vulkan's shaderOutputLayer)

It proposes to render to a single depth slice of 3D texture.  D3D12's [SV_RenderTargetArrayIndex](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics) is used in the geometry-shader stage but we don't have geometry shaders in WebGPU because it's not supported on Metal (see [#1239](https://github.com/gpuweb/gpuweb/issues/1239)), Metal also has [render_target_array_index](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) but it's specified in vertex shader, Vulkan starts to support [shaderOutputLayer](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceVulkan12Features.html) from Vulkan 1.2 (coverage: 84.74%), so it cannot be available in WebGPU.

**Comment by haoxli** [comment]
> I think this is alluding to "...the slices range must be (0, 1) for 3d texture...", however I couldn't find this restriction mentioned in the documentation: https://developer.apple.com/documentation/metal/mtltexture/2928180-maketextureview.

Actually this limitation is due to "depthPlane specifies the depth plane of the 3d texture used for rendering to the attachment."  The `depthPlane` in Metal only can specify one depth slice of 3d texture. 

"...the slices range must be (0, 1) for 3d texture..." is not documented in Metal SPEC, I know it from Metal Validation Layer. The `slices` in [newTextureViewWithPixelFormat()](https://developer.apple.com/documentation/metal/mtltexture/1515409-newtextureviewwithpixelformat/) restricts which array slices are visible in the new texture, there is only 1 array layer for 3d texture, so the validation layer limits the slices range must be (0, 1).

**Comment by litherum** [comment]
> The depthPlane restricts one depth slice of a 3d texture for rendering, not a range.

> is this about rendering to a _single_ slice of a 2DArray/3D texture, or about allowing rendering to multiple slices of a 2DArray/3D texture

We support both.

Here are [docs](https://developer.apple.com/documentation/metal/render_passes/rendering_to_multiple_texture_slices_in_a_draw_command) about the latter. It requires hardware support; not all devices support it. It's a shader output built-in variable emitted by the vertex shader, and every vertex shader invocation for a particular primitive must emit the same value. The PSO needs to know what the primitive type being rendered is. And there's a field, `renderTargetArrayLength`, which applies to the entire render pass descriptor (not an individual attachment), which is used for validation. 

The docs also say "you can’t render to multiple attachments if you specify a 3D texture."

It strikes me that dynamically selecting which layer to rendering into is a pretty different feature than simply specifying a depth plane in the render pass descriptor. I think WebGPU should treat them as different things.

**Comment by magcius** [comment]
> D3D12's [SV_RenderTargetArrayIndex](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics) is used in the geometry-shader stage but we don't have geometry shaders in WebGPU

As the documentation says, "If [D3D11_FEATURE_DATA_D3D11_OPTIONS3::VPAndRTArrayIndexFromAnyShaderFeedingRasterizer](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_feature_data_d3d11_options3) is true, then SV_RenderTargetArrayIndex is applied to any shader feeding the rasterizer." This would include vertex shaders.

**Comment by haoxli** [comment]
> It strikes me that dynamically selecting which layer to rendering into is a pretty different feature than simply specifying a depth plane in the render pass descriptor. I think WebGPU should treat them as different things.

Sure, in addition to 3d textures, selecting multiple layers for rendering also can be applied to 2d array textures, but the depth plane in render pass descriptor is only for 3d textures. 

> As the documentation says, "If [D3D11_FEATURE_DATA_D3D11_OPTIONS3::VPAndRTArrayIndexFromAnyShaderFeedingRasterizer](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ns-d3d11-d3d11_feature_data_d3d11_options3) is true, then SV_RenderTargetArrayIndex is applied to any shader feeding the rasterizer." This would include vertex shaders.

Thanks @magcius, I missed this. Maybe we can expose multiple slices rendering as an extension, I will double check it.

**Comment by kainino0x** [comment]
Important points from meeting:
- Accepted the proposal as milestone 1 (so we can open a PR and land it)!
- It should be allowed to have two different render pass attachments that point to two different slices of the same texture. We will need to update the [usage scope validation rules](https://gpuweb.github.io/gpuweb/#usage-scopes).

**Comment by haoxli** [comment]
I find two RTV with different slices on same 3D texture cannot be set as render target in one render pass. D3D validation layer will report they are the same subresources and cannot be written at same time.

so I confused that  [D3D12_TEX3D_RTV](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_tex3d_rtv) is used to describe the subresources from a 3D texture, where can restrict first depth slice and slice number used in RTV.  But the [subresources](https://learn.microsoft.com/en-us/windows/win32/direct3d12/subresources) section says `D3D12_TEX3D_RTV` only contains MipSlice indexes, which means we only can select subresources in mip level. If that I think we need to prevent rendering different slices of same 3D texture in a render pass. 

Vulkan, Metal and OpenGLES don't have this restriction.

**Comment by haoxli** [comment]
> For D3D, I find two RTV with different slices on same 3D texture cannot be set as render target in one render pass. D3D validation layer will report they are the same subresources and cannot be written at same time.

Confirmed with @RafaelCintron, it's a D3D debug layer issue and reported to their internal team.

**Comment by Kangz** [comment]
Closing since this has landed.
