### ISSUE TITLE
writeBuffer contents are written on device timeline

### ISSUE THREAD

**Issue by AlbinBernhardssonARM** [gpuweb/gpuweb#4252]
The WebGPU spec states that the contents provided to [GPUQueue.writeBuffer](https://gpuweb.github.io/gpuweb/#dom-gpuqueue-writebuffer) are written to the buffer on the device timeline. 

> [Device timeline](https://gpuweb.github.io/gpuweb/#device-timeline) steps:
> [...]
> 2. Write contents into buffer starting at bufferOffset.

This is likely meant to be on the queue timeline as:
1. It's a method of GPUQueue, not GPUBuffer.
2. The corresponding method for texture ([writeTexture](https://gpuweb.github.io/gpuweb/#dom-gpuqueue-writetexture)) does write on the queue timeline.
3. WebGPU implementations implement this on the queue timeline.

The write into the internal scratch buffer may happen at the device timeline, but that's an internal implementation detail. The copy into the actual destination buffer should be on the queue timeline.

**Comment by kainino0x** [comment]
That's correct. The wording around timelines has not been cleaned up nearly as much as I would like to - we were in the middle of it but there's still work left to do. Thanks for filing!
