### ISSUE TITLE
Should `GPUQueue.writeTexture` check `[[destroyed]]`?

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#4253]
At the moment, the only references in the spec to a `GPUTexture`'s internal `[[destroyed]]` slot is in the validation steps for `GPUQueue.submit`, but it seems like `GPUQueue.writeTexture` and `copyExternalImageToTexture` should check `[[destroyed]]` as well.

**Comment by toji** [comment]
Partially resolved by #4567, but that PR didn't address `copyExternalImageToTexture`. Pushed #4596 to handle that omission. Thanks for pointing this out!
