### ISSUE TITLE
HTMLImageElement width, height needs spec in GPUImageCopyExternalImage

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4256]
https://www.w3.org/TR/webgpu/#gpuimagecopyexternalimage

there is no entry for `HTMLImageElement`. I'm guessing they'd be `img.naturalWidth` and `img.naturalHeight`?

**Comment by kainino0x** [comment]
Good catch. I think so - whatever WebGL and drawImage do.

**Comment by kainino0x** [comment]
drawImage:
> If the sx, sy, sw, and sh arguments are omitted, then they must default to 0, 0, the image's natural width in image pixels, and the image's natural height in image pixels, respectively. If the image has no natural dimensions, then the concrete object size must be used instead, as determined using the CSS "Concrete Object Size Resolution" algorithm, with the specified size having neither a definite width nor height, nor any additional constraints, the object's natural properties being those of the image argument, and the default object size being the size of the output bitmap.

**Comment by greggman** [comment]
While we're at it, there's also ImageData not in the list (thankfully it seems easier)

**Comment by toji** [comment]
This appears to have been resolved by #4366. Thanks, Gregg!
