### ISSUE TITLE
The format of "64-bit unsigned integers" is never specified

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#4289]
Section [Timestamp Query](https://gpuweb.github.io/gpuweb/#timestamp) says that `resolveQuerySet` writes timestamps to the buffer as "64-bit unsigned integers". Usually the WebGPU spec defers to the WGSL spec to spell out the byte-level representations of values, but since WGSL doesn't have a `u64` type at the moment this happens not to be covered.

We could simply change Timestamp Query to say "little-endian", but we've avoided the use of "endian" so far. That seems like a good thing, and we should keep it up.

We could add a section on `u64` to the WGSL spec, with a note explaining that it's only used in the WebGPU API. That would be most consistent with what we're doing elsewhere.

**Comment by dneto0** [comment]
So everyone is on the same page, the rules in WGSL section [Internal layout of values](https://gpuweb.github.io/gpuweb/wgsl/#internal-value-layout) imply little-endian conventions.

I like the suggestion of adding u64 rules to the WGSL spec, then referring to them.

**Comment by kainino0x** [comment]
SGTM.
