### ISSUE TITLE
Error Scope Callback Order

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#430]
[ErrorHandling.md](https://github.com/gpuweb/gpuweb/blob/master/design/ErrorHandling.md#error-scopes) does not talk about the ordering of error scope callbacks. Error scopes can be used to determine when the enclosed operations are complete. Given that we currently have operations on both the CPU and GPU timeline, and in the future we may support multiple queues, we need to discuss the order that error scope promises can resolve.

There are two main clarifications I'd like to propose:
  - Child scopes must resolve before parent scopes
  - Sibling scopes *may* resolve in any order

### Child scopes *must* resolve before parent scopes
This point should be mostly non-contentious. Because error scope promises must not resolve until enclosed operations are complete, then naturally if error scope `A` encloses error scope `B`, then `A` must resolve after `B`. The child scope is inside its parent so the parent should resolve only when the child is complete.

### Sibling scopes *may* resolve in any order
**Rationale / Pros**
[ErrorHandling.md](https://github.com/gpuweb/gpuweb/blob/master/design/ErrorHandling.md#error-scopes) gives an [example](https://github.com/gpuweb/gpuweb/blob/master/design/ErrorHandling.md#example-createreadyrenderpipeline) use case of using a `'none'` error scope filter to wait for pipeline compilation to complete. `device.createPipeline` is enclosed in an error scope. When the scope resolves, the pipeline is swapped with the current pipeline. This can be useful when a cheap rendering pipeline is used at first and then swapped after a pipeline with more expensive shaders compiles.

If there is an imposed ordering on sibling error scope resolution (ex. in the order they were pushed), then an application cannot respond to complete of operations as soon as they occur. There are multiple independent timelines which are unrelated to the order error scopes are pushed / popped. ex.)
 - Synchronous validation and queue.submit
 - Pipeline compilation and GPU memory allocation
 - Submission of commands on multiple queues (if we have it)

If sibling error scopes may resolve in any order, then applications can respond more quickly to completion of the enclosed operations.

**Cons**
This may be a portability concern if browsers, or even GPU hardware, complete operations in different orders, and an application chooses to rely on the order of Promise resolution.

**Comment by Kangz** [comment]
> Parent scopes must resolve before child scopes

That's weird, don't you mean the opposite?

> Because error scope promises must not resolve until enclosed operations are complete

The child scope is inside it's parent so the parent should resolve only when the child is complete.

**Comment by austinEng** [comment]
> That's weird, don't you mean the opposite?

Whoops. Fixed this.

**Comment by kvark** [comment]
So this is talking more generally about the callback resolve order, rather than focused on errors, if I read correctly.

> If sibling error scopes may resolve in any order, then applications can respond more quickly to completion of the enclosed operations.

If it's an error being returned, does it matter so much whether it's returned later? Having a low-latency error handling is sort of a tricky goal to pursue, especially at the cost of portability.

**Comment by austinEng** [comment]
Discussed in the [2019-09-16 Meeting](https://docs.google.com/document/d/1UevXjxeYDGZTOR8XzEWT_h-_klMA2dbfJZLD6cWw03s/edit#). Consensus was that out of order resolution would be okay.

**Comment by kainino0x** [comment]
I was just writing the tldr and realized something. I said during the meeting that enforcing a specific order for error scope resolutions between multiple queues would cause implicit semaphores. I don't think this is true. It just means we have to collect up a queue of "error scopes to resolve" which forces the resolves to always happen in order, TCP-packet-ordering style.

**Comment by kainino0x** [comment]
(which has no benefit for multiqueue, so I still think the decision was correct.)
