### ISSUE TITLE
Shader module compilation hint API is messy

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4338]
In #4328 we added support for multiple hints per entry entry point. However the resulting API is a little messy because it was designed with backward compatibility in mind:

```
dictionary GPUShaderModuleCompilationHint {
    (GPUPipelineLayout or GPUAutoLayoutMode) layout;
};

dictionary GPUShaderModuleDescriptor
         : GPUObjectDescriptorBase {
    required USVString code;
    object sourceMap;
    record<USVString, (GPUShaderModuleCompilationHint or sequence<GPUShaderModuleCompilationHint>)> hints;
};
```

```js
// one hint
{
  code: ...,
  hints: {
    vertexMain: { layout: ... },
    fragmentMain: { layout: ... },
  }
}

// multiple hints
{
  code: ...,
  hints: {
    vertexMain: [
      { layout: ... },
      { layout: ... },
    ],
    fragmentMain: [
      { layout: ... },
      { layout: ... },
    ],
  }
}
```

Building a structure like this programmatically from a series of pipelines in an application (or similarly from an alternate representation like the one in webgpu.h) is not hard, but unnecessarily complicated:

```
for each pipeline, for each entry point:
  if there are no hints for the entry point:
    set hints for the entry point to []
  append a hint to the list
```

Since there are no shipping implementations of compilation hints, there's limited danger in making breaking changes here. However, Chrome does implement the (old) IDL for the `hints` member, so changing its type could break any content that precautionarily used `hints` (I don't know if there is any).

I realized today that we could do it without breaking content by *removing* the current `hints` member and replacing it with a new, differently-named one. For example:

```
dictionary GPUShaderModuleCompilationHint {
    required USVString entryPoint;
    (GPUPipelineLayout or GPUAutoLayoutMode) layout;
};

dictionary GPUShaderModuleDescriptor
         : GPUObjectDescriptorBase {
    required USVString code;
    object sourceMap;
   sequence<GPUShaderModuleCompilationHint> compilationHints;
};
```

```js
{
  code: ...,
  compilationHints: [
    { entryPoint: 'vertexMain', layout: ... },
    { entryPoint: 'fragmentMain', layout: ... },
  ]
}

{
  code: ...,
  compilationHints: [
    { entryPoint: 'vertexMain', layout: ... },
    { entryPoint: 'vertexMain', layout: ... },
    { entryPoint: 'fragmentMain', layout: ... },
    { entryPoint: 'fragmentMain', layout: ... },
  ]
}
```

```
for each pipeline, for each entry point:
  append a hint to the list
```

Any usage of `hints` in the wild would become ignored (and we can warn about it).

**Comment by beaufortfrancois** [comment]
I assume you meant `compilationHints` instead of `hints` in your last code snippet right?

**Comment by mwyrzykowski** [comment]
We like the proposal of `compilationHints` and would be in favor of it

**Comment by juj** [comment]
How do `entryPoint` hints relate to the default entryPoints mechanism where the entryPoint may be omitted? (https://github.com/gpuweb/gpuweb/issues/4342) Can the entryPoint names be omitted here as well?

**Comment by Kangz** [comment]
The hints are pure hints so implementations are free to map "" to a default stage entrypoint but I don't expect them to. So likely the hint's `entryPoint` will need to be an actual name for the hint to work.
