### ISSUE TITLE
Feature request: support one-component vertex attribute format

### ISSUE THREAD

**Issue by bbbbx** [gpuweb/gpuweb#4340]
| WebGPU    | [D3D12](https://learn.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format) | [VK](https://registry.khronos.org/vulkan/specs/1.0/html/chap33.html#VkFormat) | [MTL](https://developer.apple.com/documentation/metal/mtlvertexformat?language=objc) |
|:----------|:------------------------|:-----------------------|:----------------------------------|
| `float16` | `DXGI_FORMAT_R16_FLOAT` | `VK_FORMAT_R16_SFLOAT` | `MTLVertexFormatHalf`             |
| `unorm16` | `DXGI_FORMAT_R16_UNORM` | `VK_FORMAT_R16_UNORM`  | `MTLVertexFormatUShortNormalized` |
| `snorm16` | `DXGI_FORMAT_R16_SNORM` | `VK_FORMAT_R16_SNORM`  | `MTLVertexFormatShortNormalized`  |
| `uint16`  | `DXGI_FORMAT_R16_UINT`  | `VK_FORMAT_R16_UINT`   | `MTLVertexFormatShort`            |
| `sint16`  | `DXGI_FORMAT_R16_SINT`  | `VK_FORMAT_R16_SINT`   | `MTLVertexFormatUShort`           |
| `unorm8`  | `DXGI_FORMAT_R8_UNORM`  | `VK_FORMAT_R8_UNORM`   | `MTLVertexFormatUCharNormalized`  |
| `snorm8`  | `DXGI_FORMAT_R8_SNORM`  | `VK_FORMAT_R8_SNORM`   | `MTLVertexFormatCharNormalized`   |
| `uint8`   | `DXGI_FORMAT_R8_UINT`   | `VK_FORMAT_R8_UINT`    | `MTLVertexFormatUChar`            |
| `sint8`   | `DXGI_FORMAT_R8_SINT`   | `VK_FORMAT_R8_SINT`    | `MTLVertexFormatChar`             |

Use cases:
1. batch ID/feature ID attribute: assign identifiers to large numbers of static objects drawn in batches while still supporting interaction on those objects. See glTF extension [EXT_mesh_features](https://github.com/CesiumGS/glTF/blob/3d-tiles-next/extensions/2.0/Vendor/EXT_mesh_features/README.md) for details
2. dequantize Draco compression in shader to save vertex buffer

If prosible, please support the three-component vertex attribute formats, but D3D12 doesn't support it natively, VK and MTL does

**Comment by Kangz** [comment]
This has been done in https://github.com/gpuweb/gpuweb/pull/4951
