### ISSUE TITLE
"drawIndirect" Only the first call will draw correctly, subsequent calls will have no effect.

### ISSUE THREAD

**Issue by GoodLuckIce** [gpuweb/gpuweb#4341]
https://webgpu.github.io/webgpu-samples/samples/instancedCube
According to this example, insert some code to reproduce this error

chrome 118.0.5993.89

![Sample screenshot](https://github.com/gpuweb/gpuweb/assets/9364696/2b4ba9ae-89e2-44ba-b8b2-8333426ebf18)

Sample code 

    const uint32 = new Uint32Array([
        cubeVertexCount, 1, 0, 0,
        cubeVertexCount, 2, 0, 0,
        cubeVertexCount, 3, 0, 0,
    ]);

// Create a GPUBuffer and write the draw values into it
    const drawValues = device.createBuffer({
        size: uint32.length * 4,
        usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.INDIRECT,
    });
    device.queue.writeBuffer(drawValues, 0, uint32, 0, uint32.length);

    function frame() {
        // Sample is no longer the active page.
        if (!pageState.active) return;

        // Update the matrix data.
        updateTransformationMatrix();
        device.queue.writeBuffer(
            uniformBuffer,
            0,
            mvpMatricesData.buffer,
            mvpMatricesData.byteOffset,
            mvpMatricesData.byteLength
        );

        renderPassDescriptor.colorAttachments[0].view = context
            .getCurrentTexture()
            .createView();

        const commandEncoder = device.createCommandEncoder();
        const passEncoder = commandEncoder.beginRenderPass(renderPassDescriptor);
        passEncoder.setPipeline(pipeline);
        passEncoder.setBindGroup(0, uniformBindGroup);
        passEncoder.setVertexBuffer(0, verticesBuffer);
        // passEncoder.draw(cubeVertexCount, 1, 0, 0);//draw correctly
        // passEncoder.draw(cubeVertexCount, 2, 0, 0);//draw correctly
        // passEncoder.draw(cubeVertexCount, 3, 0, 0);//draw correctly

        passEncoder.drawIndirect(drawValues, 0);//draw correctly
        passEncoder.drawIndirect(drawValues, 16);//Invalid, no drawing results
        passEncoder.drawIndirect(drawValues, 32);//Invalid, no drawing results
        passEncoder.end();
        device.queue.submit([commandEncoder.finish()]);

        requestAnimationFrame(frame);
    }

    requestAnimationFrame(frame);
};

expected correct result
![image](https://github.com/gpuweb/gpuweb/assets/9364696/909e247f-bf68-4d28-bbdb-643187c84c11)

actual error result
![actual error result](https://github.com/gpuweb/gpuweb/assets/9364696/302527af-4061-4c63-a9f4-3505da0c045f)

**Comment by GoodLuckIce** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1478906#c19

**Comment by greggman** [comment]
Closing as this is a browser bug, not a spec issue (and it looks like the bug is filed above)
