### ISSUE TITLE
Should we add a parameter for the number of draws to DrawIndirect so that all commands in the IndirectBuffer can be drawn at once?

### ISSUE THREAD

**Issue by GoodLuckIce** [gpuweb/gpuweb#4344]
Should we add a parameter for the number of draws to DrawIndirect so that all commands in the IndirectBuffer can be drawn at once?

passEncoder.drawIndirect(drawValues, 0);
passEncoder.drawIndirect(drawValues, 16);
passEncoder.drawIndirect(drawValues, 32);
passEncoder.drawIndirect(drawValues, 48);
passEncoder.drawIndirect(drawValues, 64);
---to -->
passEncoder.drawIndirect(drawValues, 0, 5);

**Comment by Kangz** [comment]
That's basically https://github.com/gpuweb/gpuweb/issues/1354, closing.

**Comment by Kangz** [comment]
(we can follow the proposal and status there)
