### ISSUE TITLE
However, the IndirectBuffer only contains information about the number of grid vertices and does not have the offset address of the grid vertex data location, resulting in the inability to draw normally.

### ISSUE THREAD

**Issue by GoodLuckIce** [gpuweb/gpuweb#4353]
There are currently a large number of meshes that need to be rendered. Use "Compute Shader" to perform frustum culling, generate an IndirectBuffer containing multiple mesh information, and then call drawIndirect to draw.
However, the IndirectBuffer only contains information about the number of grid vertices and does not have the offset address of the grid vertex data location, resulting in the inability to draw normally.
I hope to modify drawIndirect so that it can pass the offset address of mesh data to meet the above usage scenario.

**Comment by Kangz** [comment]
Closing in favor of the discussion in https://github.com/gpuweb/gpuweb/discussions/4347
