### ISSUE TITLE
Clarification regarding the validation of GPUQueue.submit and submitting duplicate command buffers? 

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4367]
The validation for GPUQueue.submit https://www.w3.org/TR/webgpu/#dom-gpuqueue-submit seems to imply that the following code would not generate a validation error:
```
device.queue.submit([commandBuffer, commandBuffer]); // commandBuffer is submitted twice
```
since all the command buffers are checked in step (1) prior to making any individual command buffer invalid in step (2).

However it would seem that in step (2), if we fail to make the command buffer invalid for any reason, e.g., it was a duplicate, then we should also generate a validation error.

Can we clarify the behavior of submitting duplicate command buffers in a single call to `GPUQueue.submit` please?

**Comment by Kangz** [comment]
Great catch! The intent is totally that each command buffer can only be submitted once, so the code you exhibit should generate a validation error.

**Comment by kainino0x** [comment]
Yes, this is an editorial error. Should be fixed.
