### ISSUE TITLE
The `bgra8unorm-storage` feature should most likely only enable `write-only` access

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#4377]
https://github.com/gpuweb/gpuweb/pull/4326 added `read-only` access to `bgra8unorm` (if the `bgra8unorm-storage` feature is supported) based on the findings in https://github.com/gpuweb/gpuweb/issues/3838#issuecomment-1761399085; but I haven't considered `bgra8unorm`'s additional requirements (on Vulkan) in my investigation.

> ### Vulkan
> 
> > Storage image loads are supported in all shader stages for image views whose format features contain VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT.
> 
> _from https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#descriptorsets-storageimage_

In addition to `VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT`, `bgra8unorm` requires `VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT` for `read-only` access (https://github.com/KhronosGroup/Vulkan-Docs/issues/2027#issuecomment-1380608011).

The reports at https://vulkan.gpuinfo.org/ don't contain `VkFormatFeatureFlagBits2` info (https://github.com/SaschaWillems/VulkanCapsViewer/issues/194), so we can't analyze the hardware/driver landscape for `STORAGE_WRITE_WITHOUT_FORMAT` vs `STORAGE_WRITE_WITHOUT_FORMAT`. But at least based on [intel's open-source mesa driver code](https://gitlab.freedesktop.org/mesa/mesa/-/blob/424df6a68d286171d14886d0383685ea65cca1bc/src/intel/isl/isl_format.c#L153) we can see that the write access is a lot more common than the read access. More context can be found here: https://github.com/gfx-rs/wgpu/pull/4655.

For completeness, here are the current requirements for `bgra8unorm` with `STORAGE_BINDING` usage on underlying APIs:

||Vulkan|D3D12 FL11_0|Metal|
|-|-|-|-|
|write-only|`STORAGE_WRITE_WITHOUT_FORMAT`|"UAV Typed Store"|:white_check_mark:|
|read-only|`STORAGE_READ_WITHOUT_FORMAT`|:white_check_mark: (via SRV)|:white_check_mark:|
|read-write|`STORAGE_WRITE_WITHOUT_FORMAT` & `STORAGE_READ_WITHOUT_FORMAT`|"UAV Typed Store" & "UAV Typed Load"|:x:|

I think the `bgra8unorm-storage` feature should only allow `write-only` access (as it originally did).

**Comment by kainino0x** [comment]
Unfortunate but I agree with your analysis. Do we know if this just didn't work in Mesa before VkFormatFeatureFlagBits2, despite the spec saying it should?

**Comment by teoxoy** [comment]
The issue is not specific to Mesa; we need to check for `VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT` in addition to `VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT` or else we run into one of the [`OpTypeImage-07028` VUIDs](https://github.com/KhronosGroup/Vulkan-Docs/blob/b4792eab92a1d132ef95b56a7681cc6af69b570e/chapters/commonvalidity/draw_dispatch_common.adoc?plain=1#L114-L118):

> For any VkImageView being read as a storage image where the image format field of the OpTypeImage is Unknown, the view’s format features must contain VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT

**Comment by kainino0x** [comment]
Right, I'm just curious, what did implementations do before VK_FORMAT_FEATURE_2 existed? The Vulkan-Docs thread seems to imply that it was implicitly supported, but was it _really_? Or did the spec just not reflect reality?

**Comment by teoxoy** [comment]
> - The "Formats without shader storage format" section was added in [`9dc6dfb`](https://github.com/KhronosGroup/Vulkan-Docs/commit/9dc6dfbb7aea0999f4108ad0faeee099d0adb173) (on Oct 5, 2021) ([blame](https://github.com/KhronosGroup/Vulkan-Docs/blame/9a2e576a052a1e65a5d41b593e693ff02745604b/chapters/formats.adoc#L3443)).

> Before format_feature_flags2, the spec said that if driver exposed WithoutFormatFeature, you could use it in a shader.
Technically, if a driver exposed BGRA8 and STORAGE_BIT support, it was supposed to work.

My interpretation of the spec changes is that:

Between Vulkan 1 and 1.2.195 ([`9dc6dfb`](https://github.com/KhronosGroup/Vulkan-Docs/commit/9dc6dfbb7aea0999f4108ad0faeee099d0adb173)) implementations should have advertised support for `shaderStorageImageReadWithoutFormat`/`shaderStorageImageWriteWithoutFormat` only if all their formats with `VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT` support could be used with the `Unknown` SPIR-V Image Format and `StorageImageReadWithoutFormat`/`StorageImageWriteWithoutFormat` SPIR-V Capabilities.

After Vulkan 1.2.195 ([`9dc6dfb`](https://github.com/KhronosGroup/Vulkan-Docs/commit/9dc6dfbb7aea0999f4108ad0faeee099d0adb173)) implementations should now only consider a subset of formats (the ones in the [Formats without shader storage format](https://registry.khronos.org/vulkan/specs/1.0/html/vkspec.html#formats-without-shader-storage-format) table) when advertising support for `shaderStorageImageReadWithoutFormat`/`shaderStorageImageWriteWithoutFormat`. And `VK_KHR_format_feature_flags2` was added in the same version/commit which allows users to query these capabilities for the rest of the formats.

Having said that, I haven't checked how implementations behave in practice.

**Comment by kainino0x** [comment]
Sounds right to me, but yeah, I'd be surprised if the drivers all got it right.

**Comment by alan-baker** [comment]
I thought read-only would be polyfilled in SPIR-V with a texel fetch on a sampled texture and swizzle? I guess you'd have to play with the usage bits on the API side too, but I think it could be a sort of blanket change. Not sure that's worth it or opposed to the resolution, just wondering if it was considered?

**Comment by kainino0x** [comment]
I don't think we did. It would require injecting the TEXTURE_BINDING usage for any bgra8unorm texture with STORAGE_BINDING usage, I don't know how bad that is. We could maybe consider it as a post-M0 relaxation?

**Comment by kainino0x** [comment]
Added to meeting agenda.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-07-17#the-bgra8unorm-storage-feature-should-most-likely-only-enable-write-only-access-4377">GPU Web WG 2024-07-17 Pacific-time</a></summary>

* KN: resolved this in API group; Alan had feedback. Thought read-only would be polyfilled with texture fetch and swizzle. Have to change texture fields on API side too. We didn't consider that approach. Maybe could do what we previously resolved on, and try to relax it later? Could use read-only with BGRA storage. Impl's not too trivial. Shader generation work, inject texture binding usage when texture's created, etc.
* KG: so is the impl complexity worth it?
* JB: Moz wouldn't be able to look at this for quite some time.
* KN: if that's the case then we don't want the spec to say we have to do it. So we should land the spec change and remove the ability to do read-only with bgra.
* JB: file bug for later to remove the restriction.
* KG: can do that. For M2. Resolved: restrict for now, file follow-on issue.

</details>
