### ISSUE TITLE
Compat: validating out "2d" of more than 1 layer

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4378]
> The issue of validating out "2d" of more than 1 layer is not mentioned in this proposal. It seems like it came up in the meeting.
> 
> In other words,
> 
> ```
> createTexture({
>   size: [1,1,2],  // so 2 or more layers
>   textureBindingViewDimension: '2d',  // the default would be '2d-array' but user choose '2d'
>   ...
> });
> ```
> 
> Should fail with a validation error
> 
> 
> I think similarly
> 
> ```
> createTexture({
>   size: [1,1,2],  // not 6 layers
>   textureBindingViewDimension: 'cube',
>   ...
> });
> ```
> 
> should fail with a validation error. This would already fail at view creation time but seems like it should fail here because GL can't create a 2 layer cube map which is what's being asking for here

_Originally posted by @greggman in https://github.com/gpuweb/gpuweb/issues/4365#issuecomment-1803035297_

**Comment by kainino0x** [comment]
@SenorBlanco

**Comment by kainino0x** [comment]
@greggman could you make sure both of these restrictions are recorded in the compat proposal doc?

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-03-13#compat-validating-out-2d-of-more-than-1-layer-4378">GPU Web CG 2024-03-13 Atlantic-time</a></summary>

    * GT: thought this was done in the CTS already?
    * KG: approved now.
    * MW: thumbs up.
    * KN: Stephen said we already discussed the first of these 2 things, but not the cube map one. Make sure it's in the Compat proposal doc.

</details>
