### ISSUE TITLE
The shader syntax is the worst

### ISSUE THREAD

**Issue by ryuukk** [gpuweb/gpuweb#4386]
Someone didn't get bullied at school enough, as a result he makes it worse for the entire universe

Change the language asap, before it gets worse

**Comment by munrocket** [comment]
wgsl for minified shaders discussed here #3503

Problem with select() is interesting if it’s true that both options are executed.

**Comment by Kangz** [comment]
Closing and locking since there is no constructive feedback, and because the post doesn't follow the [code of conduct](https://www.w3.org/Consortium/cepc/) (in particular treating others with respect).
