### ISSUE TITLE
Clarification of behavior around GPUStoreOp.discard?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4398]
Some of the CTS tests appear to be using a pattern of:
```
       beginRenderPass({
          colorAttachments: [
          {
            view: texture.createView(desc),
            storeOp: 'discard',
            loadOp: 'load'
          }]
```
to 'discard' a texture, see texture_zero.spec.ts:411 - https://github.com/gpuweb/cts/blob/086261bcd213f8ae6f57ebdc293283ed6262097d/src/webgpu/api/operation/resource_init/texture_zero.spec.ts#L411

If the texture is not initialized, then I would expect the load op to clear the texture to zero.

But if the texture is already initialized, see the call to discardTexture on https://github.com/gpuweb/cts/blob/086261bcd213f8ae6f57ebdc293283ed6262097d/src/webgpu/api/operation/resource_init/texture_zero.spec.ts#L615 - what is the expectation here?

I would expect that the writes to the render target are discarded, i.e., the contents are loaded but otherwise unchanged.

The CTS test appears to expect the texture contents are discarded, i.e., cleared to zero, which is unexpected. 

The specification says https://gpuweb.github.io/gpuweb/#dom-gpustoreop-discard - `Discards the resulting value of the render pass for this attachment.`, which would seem to align with the former. I.e., the contents should persist if they have been previously written to as in the CTS.

Is my understanding incorrect here or is the CTS expectation incorrect?

**Comment by mwyrzykowski** [comment]
Clarified in the meeting that discard should zero the texture.

Seems like we should clarify this as it differs from what might be expected

**Comment by kainino0x** [comment]
SGTM, we should update https://gpuweb.github.io/gpuweb/#dom-gpustoreop-discard . It's exactly the right place for documentation like this because it's the first place developers will look (if they're looking at the spec).

**Comment by mwyrzykowski** [comment]
Hi @kainino0x - this issue came up again as WebKit had a bug in our implementation and, as I failed to mention the reason from the meeting in my comment above, do you recall why the developer would want to use:
```
            storeOp: 'discard',
            loadOp: 'load'
```
instead of:
```
            storeOp: 'store',
            loadOp: 'clear'
```
with an empty render pass and clearValue of 0?

It seems like it would achieve the same thing, i.e., clears the texture to zero.

**Comment by kainino0x** [comment]
With an empty render pass, yes, they are the same, as is `loadOp: 'clear', storeOp: 'discard'`. The pass being empty is a degenerate case.

**Comment by mwyrzykowski** [comment]
Oh we expect any `storeOp: 'discard'` to clear the texture to zero? Sorry I think I missed that point when we discussed it.

**Comment by kainino0x** [comment]
Yes, or "as if" it does. It's like you said in the first post:
> If the texture is not initialized, then I would expect the load op to clear the texture to zero.

So the implementation shouldn't necessarily clear _immediately_ but it should appear cleared if you do try to use it after a discard. This lets you optimize for example if you have two render passes with the same attachment that:
1. load, render, discard
2. load, render, store

then we can see that the texture is initialized before pass 2, and replace the load with a clear-to-0, avoiding an actual clear operation.

(BTW the fact that the loadOp/storeOp are backward in the test you linked to is really confusing. I keep having to mentally sort them correctly. Decided to clean that up finally: https://github.com/gpuweb/cts/pull/3674)

**Comment by kainino0x** [comment]
In the particular test you linked to, it's intentional that we clear the texture in this weird way: we're specifically trying make the implementation mark the texture as uninitialized, so we can trigger lazy clearing logic, so we can test it.

**Comment by mwyrzykowski** [comment]
Ok I think that all makes sense now, thank you for clarifying. Internally I thought of discard as ‘discarding the value written during the pass, leaving the existing contents unchanged’, which was my misunderstanding

**Comment by kainino0x** [comment]
It is confusing. That's why we need the spec improvement (thanks Brandon)!

It's impossible to discard the result from the pass for a few reasons:
- Non-tiling hardware does not actually have separate tile memory for passes. It just writes into main memory. "discard" just means "don't bother to flush write caches", leaving undefined results in main memory.
- Tiling hardware can spill back to main memory, for example if the driver needs to preempt the render pass to do something else, then resume it later.
