### ISSUE TITLE
Position: Directly ingest SPIR-V, and not a human-writable shading language

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#44]
**Revision R1:** 2018-01-01
**Revision R2:** 2018-01-03

**WebGPU should directly ingest SPIR-V, and it should not ingest a human-writable shading language. <span style="text-decoration:underline;">[R2] The WebGPU group should bless HLSL and fully maintain a complete development path to enable development with HLSL.</span>**

### Ease of SPIR-V ingestion

SPIR-V is a **smaller and simpler** implementation and verification target than **any** human-writable shading language.

*   Ingesting SPIR-V instead of a shading language removes **substantial** amounts of code from the WebGPU implementation, such as a preprocessor and (text) parser.
*   It **eliminates** code for language-level concepts like identifiers and expression trees, and all string processing, from the translator frontend and validator.
*   During the development of WebGL, **hundreds** of bugs and edge cases have been encountered which are exclusive to the ingestion of a human-writable shading language. Note that these can not be dismissed as simply bugs in the browser's shader translator; these types of bugs are inherent to ingesting a text-based language. Ingesting SPIR-V **categorically eliminates** bugs in these areas (example bugs provided):
    *   String-related operations: parsing, tokens, identifiers ([bug](http://crrev.com/fd747b861195a03df634a722a9cf3505dcd41253)), literals ([bug](http://crrev.com/d78e33a8da3130f424a10c6053dad05a010beb6e), [bug](http://crrev.com/f541f5296ff195af7b5f9bcaa678e968a658d91e)) - including needing to enforce a maximum identifier length ([bug](http://crrev.com/d35efdf533eb45599d2ffa9dc0e781e2366488df)) in the specification to avoid implementation-specific limits
    *   Scoping and identifier namespacing/collisions ([bug](http://crrev.com/be59c2fb70591b4df0fea23d630bed1f494d8914), [bug](http://crrev.com/964df49da5fe5e5d28bcffa92fad5943a826c92f))
    *   Abstract syntax trees - including needing to enforce a maximum tree depth/size/complexity ([bug](http://crrev.com/2bd9c4430e68c7a67c52f1e2ab9f93ac6b12249d), [bug](http://crrev.com/eb1a010f0f996b3742fd34b92ffaf9014c943528)) in the specification to avoid implementation-specific limits
    *   The preprocessor ([bug](http://crrev.com/964df49da5fe5e5d28bcffa92fad5943a826c92f), [bug](http://crrev.com/2bd9c4430e68c7a67c52f1e2ab9f93ac6b12249d)) - another entire language layered on top
    *   Weak typing ([bug](http://crrev.com/2cacb7783116bdd94b2dd70315418a62e035bd1d), [bug](http://crrev.com/9cd7163e11c7d2b7582190eb8987a743239bf522)) - implicit type conversions and type inference
    *   Implicit qualifiers and other optional syntax ([bug](http://crrev.com/3de2703d83bf9f3747e6f80d98e3ab70ea1ba5e8), [bug](http://crrev.com/163fa52193706ae87ece150f955861909e7c675f))
    *   Other error-prone high-level language features, like initializers ([bug](http://crrev.com/b1edc4f55cd6e21ffa15abf7a26692f1256e937a), [bug](http://crrev.com/d4f4c11b92cb03d121bda62fa75f605d8b190940)), vec/mat destructuring ([bug](http://crrev.com/ae04e1e4a6bf8584dc33d3a72cb943df8e554378)), etc.

    This **[bug list](https://docs.google.com/spreadsheets/d/1bjfZJcvGPI4M6Df5HC8BPQXbl847RpfsFKw6SI6_T30/edit)**, curated from the ANGLE and Chromium repositories, illustrates the classes of bugs that have been encountered during the development of the WebGL shading language specification, and which would be categorically eliminated by ingesting only the SPIR-V binary format.

*   Ingesting SPIR-V does add a few new concepts:
    *   Parsing of a simple binary format - much simpler to parse than HLSL/GLSL
    *   Control flow graph and single static assignment form
        *   CFGs are simpler than ASTs and much easier to operate on.
        *   SSA forms are simpler and much easier to operate on.
        *   Code transformations and analyses are much easier to apply to CFG/SSA, which is why modern compilers use them internally. (Examples: bounds checks, bounds check elision, injecting temporary values and computations, constant propagation, dead code elimination.)
*   SPIR-V supports optional debug information like variable names and source line numbers (SPIR-V 1.2 §2.15), but it is only used for diagnostic output. It is not used during parsing or validation.
    *   Any error messages produced during shader validation can still refer to the developer's original variable names.
        *   And if the ingested SPIR-V is produced by an SL compiler toolchain, as it almost always will be, it should always be valid. Any errors in the SL source should be caught by the SL compiler.
    *   Source maps, or a similar mechanism, can be used to provide the original source for shaders during development. Source maps are also used in WebAssembly to enable debugging and variable inspection for binaries compiled from any source language. (Recently [implemented in Firefox](https://twitter.com/slsoftworks/status/941400137921949696).)

**The benefits of ingesting a less complex verification target are significant:**

*   [R2] HLSL/GLSL compiler bugs are **no longer portability or security problems**. (See _Better for Web developers_.)
*   Less buggy browser implementations
    *   A simpler implementation will be less buggy.
*   More consistent browser implementations
    *   Two implementations will be more consistent if they are less buggy.
    *   Tighter specification (see below) means better consistency.
*   Better security
    *   SPIR-V is a smaller attack surface and a smaller fuzzing target. Fuzzing can thus be more effective.
*   Potentially better ingestion performance
    *   By eliminating the parsing step and related complexity.

### Better for Web developers

*   A hallmark of modern Web development is that applications are highly portable across browsers, with very minimal porting effort. **Cross-browser consistency is critical.**
    *   [R2] **Portability problems** caused by HLSL/GLSL compiler bugs are **eliminated**: If the application is responsible for compiling HLSL shaders (whether during build or at runtime), they will build once or ship with a single version of a compiler (such as [DXC](https://github.com/Microsoft/DirectXShaderCompiler/wiki/SPIR%E2%80%90V-CodeGen)) which behaves consistently across clients. Any HLSL compiler bugs which affect an application can be caught in application testing, and will never be browser or system dependent. The developer can work around them, or they can fix them and upstream fixes.
*   [R2] Developers still get to take advantage of the well-established HLSL ecosystem and catalog.
*   Developers simultaneously get to take advantage of the rich SPIR-V ecosystem (optimizer, validator, cross-compilation, etc.).
    *   An evolution of HLSL can target SPIR-V. Targeting SPIR-V makes it **much easier to evolve a language**, because the browser does not need to implement language changes - an application developer can pick up new language developments whenever they want, [R2] as well as control for regressions.
    *   [R2] It also eases development of new languages, and allows some languages designed for Vulkan/OpenGL/OpenCL to be used in WebGPU. This flexibility provides value without undermining the well-lit path of HLSL.
*   It has been argued that Web developers have complained about the "lack of view-source" in WebAssembly, and that some WebAssembly WG members disagree with the final, binary format of WebAssembly (though we do not know what motivates either of these opinions). These viewpoints are not reflected in our experiences with WebGL developers. Vocal WebGL developers consistently request flexibility, performance, and performance features; view-source for shaders on third-party websites does not seem to be a big concern.
    *   View-source during development can be provided by SPIR-V debug information and/or source maps.
*   For developers who want or need online compilation of human-writable shaders, a shader compiler ([R2] like shaderc or DXC) can be easily ([R2] compiled to WebAssembly and) packaged as a JavaScript library. See _Appendix: Engine development strategies for WebGPU shaders_.

### SPIR-V: tight specification and active ecosystem

*   **SPIR-V is very stable.** There have been minimal recent changes to its specification ([diff from 1.1 to 1.2](https://gist.github.com/kainino0x/cc3d6fea9a01fbf163f9d5173f92853c)). This makes it a more stable target as there is minimal need for any given tool (such as an HLSL compiler) to target multiple SPIR-V versions.
*   **SPIR-V is tightly specified.** The complexity of the format is much lower than GLSL/HLSL, so its prose specification is able to be more precise. Lower complexity also leaves fewer holes for underspecification or self-contradiction.
    *   [GLSL ES 3.20](https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf): 218 content pages for GLSL graphics/compute (mostly long prose, very dense)
    *   [SPIR-V 1.2](https://www.khronos.org/registry/spir-v/specs/1.2/SPIRV.pdf): 192 content pages for graphics/compute and OpenCL (some readable long prose, mostly well-organized tables with prose)

    Since SPIR-V is less complex, a conformance test suite of the same "size" should intuitively be able to cover more cases and thus more effectively complement the prose spec. (We don't have data to go with this, since it's very hard to compare the size and coverage of SPIR-V in the Vulkan CTS with the size and coverage of GLSL in the OpenGL CTS.)

*   If we need to add a feature to SPIR-V, it can be done so as an Extension to SPIR-V. The WebGPU group can effectively own these Extensions.
*   SPIR-V's interaction with WebGPU will be defined by an Environment Specification. This will encompass limitations and additional validation rules we apply to SPIR-V. It can also require support for new SPIR-V extensions.
    *   SPIR-V adds constraints on the CFG (like structured control flow) that make it possible to translate into the AST-level (like GLSL/HLSL/MSL).
    *   Further constraints can be added (to an environment specification) to define a canonical ordering for the encoded CFG, such that it is easier to validate and easier to translate to the AST-level. (David Neto has started work on this.)
*   **The SPIR-V ecosystem is very active**, because it is used in Vulkan (and OpenCL, [OpenGL](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gl_spirv.txt), and [Vulkan Portability](https://www.khronos.org/blog/khronos-announces-the-vulkan-portability-initiative)). This lets us provide better tools for developers and better browser implementations. It allows WebGPU developers to take advantages of SPIR-V ecosystem developments, including human-writable shading language advancements like an evolution of HLSL.

### Appendix: Engine development strategies for WebGPU shaders

There are ~four categories of engine development:

*   **New WebGPU-only engines:** They can base the engine around offline shader compilation, or use online shader compilation for prototyping.
*   **Cross-compiled native engines (Unity, Unreal, etc.):** They can already output both HLSL and SPIR-V.
*   **User-generated shader content (Shadertoy):** Shadertoy developers can trivially ship a shader compiler like shaderc or DXC. It will make users' content more consistent across browsers.
    *   Shadertoy could also, for example, choose to use a heavier compiler ([R2] or more expensive compiler options) with better diagnostic messages. Good diagnostic messages add even more complexity to an implementation, and for the reasons above, it is problematic to (1) add that complexity to every browser and (2) require it to run on every shader compile.
*   **Engines which want to target both WebGL and WebGPU (Three.js, Cesium.js, etc.):** These developers will _want_ their existing GLSL shaders and GLSL-text-snipping engines to work on WebGPU. They will _need_ to continue supporting WebGL 1.0 for compatibility. The development complexity is actually very similar regardless of the ingested format; [R2] ingesting SPIR-V does not make it harder:

<table>
  <tr>
   <td>
<strong>Options if browser ingests HLSL</strong>
   </td>
   <td><strong>Options if browser ingests SPIR-V</strong>
   </td>
  </tr>
  <tr>
   <td>1. Online cross-compile GLSL to HLSL with a third-party library. (shaderc+SPIRV-Cross?)
   </td>
   <td>1. Online cross-compile GLSL to SPIR-V with a third-party library. (shaderc)
   </td>
  </tr>
  <tr>
   <td>2. Maintain, <strong>in parallel with GLSL code</strong>, a separate library of HLSL and an HLSL-text-snipping engine.
   </td>
   <td>2. Maintain a separate library of some SL, and offline compile it to SPIR-V (shaderc or DXC). Do online linking and specialization with a JS library.
   </td>
  </tr>
  <tr>
   <td>3. An HLSL library and HLSL-text-snipping engine (as above), <strong>plus</strong> online-compile HLSL to GLSL (if maintaining WebGL as a "slower fallback path") with a third-party library.
   </td>
   <td>3. An SL library compiled SPIR-V (as above), <strong>plus</strong> online-compile SPIR-V to GLSL (if maintaining WebGL as a "slower fallback path"). (Aside: offline compilation from SPIR-V to GLSL may even be possible, with a simple JS implementation of linking and specialization for GLSL.)
   </td>
  </tr>
</table>

### [R2] Addendum: Blessing and supporting HLSL (or an HLSL evolution)

Obviously, application developers will not normally write SPIR-V by hand. Instead, they will compile to SPIR-V (either online or offline) from a human-writable shading language. The WebGPU working group should bless a single such language, HLSL, and take responsibility for the HLSL development path.

*   HLSL has the richest library of existing source code.
*   HLSL to SPIR-V compilation is [under development in DXC](https://github.com/Microsoft/DirectXShaderCompiler/wiki/SPIR%E2%80%90V-CodeGen).
*   The WebGPU working group is expected to own specification, conformance, and development of HLSL or an evolution thereof.
*   The WebGPU working group should bless HLSL by:
    *   Using it in WebGPU documentation, and recommending its use in third-party documentation/tutorials/etc.
    *   Maintaining an online compilation path to WebGPU-compatible SPIR-V, e.g. DXC compiled to WASM.
    *   Maintaining an offline compilation path to WebGPU-compatible SPIR-V, e.g. DXC  as a webpack packaging step using WASM DXC, and native or nodejs packages for Mac/Linux.

For developers with existing content in GLSL, we should also ensure the ecosystem includes a well-supported GLSL path (for example via shaderc).

**Comment by kainino0x** [comment]
One thing we didn't really discuss above: we also think that **the WebGPU group should bless HLSL and fully maintain a complete development path to enable development with HLSL**. We will revise the document to express this more clearly.

**Comment by kainino0x** [comment]
Revision posted. Changes marked with [R2].

**Comment by devshgraphicsprogramming** [comment]
I think SPIR-V is the only formally specified binary shader language.

HLSL does not have a thorough and formal specification.

You will be open to less bugs and issues, especially security bugs when using a binary intermediate representation for which there are multiple compilers available including cross-compilers.

You need an AST anyway to reason about a shader's security, frankly I think it would be far easier to transform a SPIR-V shader's AST to prevent out-of-bounds reads and writes for robustness.

HLSL to SPIR-V compilation is currently badly broken, ask any graphics developer who's looked into it.

> The WebGPU working group is expected to own specification, conformance, and development of HLSL or an evolution thereof.

Lawsuits anyone?

**Comment by devshgraphicsprogramming** [comment]
Not ingesting SPIR-V by default will make the web **slower**, one of the most painful parts of video-game development is the **shader compilation**

We actually have to kickoff compilation in multiple threads and how the CPU for a number of seconds to get all of the shaders in the scene to compile and optimize.

Some platforms (Mali) didn't use to do optimization to save on load times and power-usage, that ended up with sub-optimal framerates and mobile developers such as Aras P. had to write their own optimizers to make sure that the shipped shaders actually received optimization on mobile!
