### ISSUE TITLE
Compat: Validating out viewFormats / view reinterpretation

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4404]
In WebGPU you can create a texture and request compatible viewFormats.

```js
const tex = device.createTexture({
  ...
  format: 'rgba8unorm',
  viewFormats: ['rgba8unorm', 'rgba8norm-srgb'],
});
```

OpenGL ES 3.1 has no such facility.

We'd like to validate this out in compatibility mode.  2 options

1. Require the formats in `viewFormats` to be the same format

   ```js
   { ... format: 'rgba8unorm', viewFormats: ['rgba8unorm', 'rgba8norm-srgb'], }  // bad
   { ... format: 'rgba8unorm', viewFormats: ['rgba8unorm'], }                    // ok
   ```

2. Require `viewFormats` to be unset

   ```js
   { ... format: 'rgba8unorm', viewFormats: ['rgba8unorm'], }                    // bad
   { ... format: 'rgba8unorm' }                                                  // ok
   ```

**Comment by kainino0x** [comment]
SGTM. No strong feeling, slight preference for option 1 since it'll have marginally better support for applications written against WebGPU core.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-03-13#compat-validating-out-viewformats--view-reinterpretation-4404">GPU Web CG 2024-03-13 Atlantic-time</a></summary>

    * KG: as long as view format matches in array, think this is the lowest overhead way forward.
    * Consensus.

</details>
