### ISSUE TITLE
Size and alignment of bool type is missing from https://gpuweb.github.io/gpuweb/wgsl/#alignment-and-size ?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4406]
Should `bool`'s alignment and size be specified at https://gpuweb.github.io/gpuweb/wgsl/#alignment-and-size ? It appears to be missing. I'm not sure if that was intentional.

**Comment by dj2** [comment]
A `bool` is not host-shareable (https://gpuweb.github.io/gpuweb/wgsl/#host-shareable) and that table lists the alignment and size of host-shareable types.

**Comment by mwyrzykowski** [comment]
Ok thank you for clarifying, sounds like no change is needed
