### ISSUE TITLE
Compat: Validate out storage texture formats that are not supported in GLES

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4413]
WebGPU requires these formats are supported as storage textures

rgba8unorm 
rgba8snorm
rgba8uint
rgba8sint
rgba16uint
rgba16sint
rgba16float
r32uint
r32sint
r32float
rg32uint
rg32sint
rg32float
rgba32uint
rgba32sint
rgba32float
bgra8unorm

If I understand correctly, GLES does not support rg32uint, rg32sint, rg32float

So it seems we should validate these out in `createBindGroup` in that if you try to bind a texture to a texture storage bind point and it's one of these 3 formats you get a validation error.

@SenorBlanco

**Comment by teoxoy** [comment]
If we don't advertise support for `STORAGE_BINDING` for those formats if in compat mode all the validation should happen transparently when calling `createTexture()`.

**Comment by greggman** [comment]
So, if we're marking `rg32xxx` formats as not allowing storage in compat then `createTexture`, `createBindGroupLayout` and `createXXXPipeline` would all generate validation errors for these formats as they all have a step that validates texture is usable as a storage texture.

From `createTexture`

> If descriptor.[usage](https://www.w3.org/TR/webgpu/#dom-gputexturedescriptor-usage) includes the [STORAGE_BINDING](https://www.w3.org/TR/webgpu/#dom-gputextureusage-storage_binding) bit: descriptor.[format](https://www.w3.org/TR/webgpu/#dom-gputexturedescriptor-format) must be listed in [§ 26.1.1 Plain color formats](https://www.w3.org/TR/webgpu/#plain-color-formats) table with [STORAGE_BINDING](https://www.w3.org/TR/webgpu/#dom-gputextureusage-storage_binding) capability for the appropriate access mode.

From `createBindGroupLayout`

> For each [GPUBindGroupLayoutEntry](https://www.w3.org/TR/webgpu/#dictdef-gpubindgrouplayoutentry) entry in descriptor.[entries](https://www.w3.org/TR/webgpu/#dom-gpubindgrouplayoutdescriptor-entries):
>
>    If entry.[storageTexture](https://www.w3.org/TR/webgpu/#dom-gpubindgrouplayoutentry-storagetexture) is [provided](https://infra.spec.whatwg.org/#map-exists):
>
>    [?](https://tc39.es/ecma262/#sec-returnifabrupt-shorthands) [Validate texture format required features](https://www.w3.org/TR/webgpu/#abstract-opdef-validate-texture-format-required-features) for entry.[storageTexture](https://www.w3.org/TR/webgpu/#dom-gpubindgrouplayoutentry-storagetexture).[format](https://www.w3.org/TR/webgpu/#dom-gpustoragetexturebindinglayout-format) with this.[[[device]]](https://www.w3.org/TR/webgpu/#dom-gpuobjectbase-device-slot).

From `createXXXPipeline...`

> Let bindGroupLayout be the result of calling device.[createBindGroupLayout()](https://www.w3.org/TR/webgpu/#dom-gpudevice-createbindgrouplayout)(groupDesc).

**Comment by SenorBlanco** [comment]
Agreed on `createBindGroupLayout()`. I'm not sure I understand the `createXXXPipeline()` issue. Wouldn't the validation have already occurred on `createBindGroupLayout()`? That is to say, what would change in the spec text for `createXXXPipeline()`?

**Comment by greggman** [comment]
`createXXXPipeline` has an `auto` layout mode in which case WebGPU creates the layouts for you. It does this by calling `createBindGroupLayout` internally (referenced in docs) so from the user's POV you get a validation error from `createXXXPipeline/Async`

**Comment by greggman** [comment]
If that wasn't clear, I don't know the exact wording needed in the spec for this issue related to compat mode but, marking those formats as **not** supporting "storage" in the texture feature table in compat mode has the consequence that all of those functions will generate validation errors.

**Comment by greggman** [comment]
approved and merged

https://github.com/gpuweb/gpuweb/pull/4444
