### ISSUE TITLE
Slight type problem with `GPURenderPipeline.[[writesDepth]]`

### ISSUE THREAD

**Issue by jimblandy** [gpuweb/gpuweb#4416]
In the [`createRenderPipeline`](https://gpuweb.github.io/gpuweb/#dom-gpudevice-createrenderpipeline) algorithm, device timeline step 8.1 says:

> Set pipeline.[[[writesDepth]]](https://gpuweb.github.io/gpuweb/#dom-gpurenderpipeline-writesdepth-slot) to depthStencil.[depthWriteEnabled](https://gpuweb.github.io/gpuweb/#dom-gpudepthstencilstate-depthwriteenabled).

However, [`GPUDepthStencilState.depthWriteEnabled`](https://gpuweb.github.io/gpuweb/#dom-gpudepthstencilstate-depthwriteenabled) is an optional `bool` member without a default value, so it's not clear what this assignment should do when the member is absent from the dictionary.

Validation in the [validating GPUDepthStencilState](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpudepthstencilstate) abstract operation does say:

> - If descriptor.[format](https://gpuweb.github.io/gpuweb/#dom-gpudepthstencilstate-format) has a depth component:
>
>    - descriptor.[depthWriteEnabled](https://gpuweb.github.io/gpuweb/#dom-gpudepthstencilstate-depthwriteenabled) must be [provided](https://infra.spec.whatwg.org/#map-exists).

but the assignment in `createRenderPipeline` isn't conditional on anything having to do with `format`.

It seems to me that if the format doesn't have a depth aspect, then it probably doesn't matter what value `[[writesDepth]]` gets. But ideally the spec should not say things that don't make sense, even if they don't matter. [People do notice these things.](https://phabricator.services.mozilla.com/D194223#6436494)

**Comment by kainino0x** [comment]
It should always be boolean because there's a step that initializes it:

> 5. Set pipeline.[[writesDepth]] to false.

However I'm in favor of writing the default next to the field definition and removing that step.

**Comment by kainino0x** [comment]
Sorry, I misread, the problem is with depthWriteEnabled being optional and set into a non-optional boolean field.
