### ISSUE TITLE
Weird behavior while using switch code block

### ISSUE THREAD

**Issue by ch3coohlink** [gpuweb/gpuweb#4430]
I'm trying to implement a recursive algorithm using wgsl, and what I'm doing is managing the stack manully using a struct array, and a stack counter to record the recursion depth. But the code didn't work as expected.
Let me make an abstraction for my code:
```wgsl
var si = 0i; var counter = 0u;
var sa = array<u32, 10>();
loop {
  switch (sa[si]) {
    case 0 {
      sa[si] = 1;
    }
    case 1 {
      // return vec3(1);
      if(si == 0) { return vec3(1); }
      if(sa[si] == 1) { return vec3(1); }
      sa[si] = 2;
      si++; // <-------------- this line is most problematic
      if(si == 1) { return vec3(1); }
    }
    case 2 {
      sa[si] = 1;
      if(si == 0) { return vec3(1); }
    }
    default {}
  }
  counter++;
  if si < 0 || counter > 100 { break; }
} return vec3(0);
```
With the pointed line `si++;`, this code always return 0, but if I comment that line, it works as expected.
Furthermore, the problem is only reproducable while the code is inside a switch statement.
I tried to dump the compiled shader of the backend, but didn't manage to do it.
I'm using Windows11 and my browser is msedge, running on a laptop rtx4080.

**Comment by ch3coohlink** [comment]
Just tested on an Intel integrated card, didn't work too.

**Comment by greggman** [comment]
You can dump the shader on chrome with `--enable-dawn-features=dump_shaders`. The shaders will show up in the JavaScript console for that page.

As for the code you posted, I'm probably missing it but I don't see how it would ever return anything other than `vec3(1)`

`sa` is initialized to zero by default and `si` is zero so first time though the loop it hits 'case 0' which is just going to set `sa[0] = 1`. Second time through the loop it will look at `sa[0]` again, which is now 1, and go to `case 1`. `si` still equals `0` so the first `if (si == 0) will trigger and it should return `vec3(1)`

And that's all it can ever return as the next time it's called everything will be back to the initial state

https://jsgist.org/?src=2b3c99eee33f97fd18ebd9dcb9bdc59f

Is that the actual code you had trouble with or is maybe there an error in transcription?

**Comment by ch3coohlink** [comment]
@greggman 
Thanks for your reply.
This is the abstract version of my actual code, but I do run it, and it reproduce the same error.
And your test case can reproduce the same problem on my machine as well: a whole black screen as the function returning 0;
I think its a bug inside either webgpu implementation or nvidia driver for dx12 (I heard it's buggy) as I refactored my code using if else if instead of switch, and the problem is gone.

And for the shader dumping case, I do read your stackoverflow post about this topic... and tried to boot the browser using the flag you provide, but didn't manage to see the flag in the about://gpu page, and there is no shader logs too. The only thing contains string "dump" in that page is something inside ANGLE Features setion like this:
*   dumpShaderSource (Frontend features) (http://anglebug.com/7760): Disabled
    Write shader source to temp directory
*   dumpTranslatedShaders (Frontend features) (http://anglebug.com/8280): Disabled
    Write translated shaders to temp directory

And here is my console command used to boot the browser:
``` powershell
PS C:\Program Files (x86)\Microsoft\Edge\Application> .\msedge.exe --enable-dawn-features=dump_shaders
```
Anything wrong with this setup?

**Comment by ben-clayton** [comment]
I've filed [crbug.com/tint/2126](https://crbug.com/tint/2126). A cursory glance over the emitted HLSL does not show anything obviously wrong.

It's worth mentioning that we're very close to migrating from FXC as the D3D backend compiler to DXC, and this may fix the issue. This is likely to reach 100% rollout in January.

**Comment by greggman** [comment]
Sorry I don't have access to a Windows machine at the moment but just to be clear, here's me running on Mac with `--enable-dawn-features=dump_shaders`


https://github.com/gpuweb/gpuweb/assets/234804/7775490b-a647-4f52-bc24-f103ce871c61

I don't know if msedge supports the same flags

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐01‐09-Minutes#weird-behavior-while-using-switch-code-block--issue-4430">WGSL 2024-01-09 Minutes</a></summary>

* KG:Not a spec issue.
* BC: I already made a Tint bug for this. Close.
* **_Close_**

</details>

**Comment by amaiorano** [comment]
> I've filed [crbug.com/tint/2126](https://crbug.com/tint/2126). A cursory glance over the emitted HLSL does not show anything obviously wrong.
> 
> It's worth mentioning that we're very close to migrating from FXC as the D3D backend compiler to DXC, and this may fix the issue. This is likely to reach 100% rollout in January.

Can confirm that this is an FXC bug, see [my comment here](https://bugs.chromium.org/p/tint/issues/detail?id=2126#c4).
