### ISSUE TITLE
bitcast behavior regarding NaNs is unexpected?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4450]
While working through the CTS, we noticed there are a few cases testing bitcast of vec2f values to vec4h, e.g., https://gpuweb.github.io/cts/standalone/?q=webgpu:shader,execution,expression,call,builtin,bitcast:vec2f_to_vec4h:inputSource=%22uniform%22;alias=false

Our initial implementation produced failures like:
```
(vec2<f32>(NaN.0 (0x7fc00000), NaN.0 (0x7fc00000)))
    returned: vec4<f16>(0.0 (0x0000 subnormal), NaN.0 (0x7fc0), 0.0 (0x0000 subnormal), NaN.0 (0x7fc0))
    expected: [[{ 'f16', [0.0 (0x8000 subnormal)] }],[{ 'f16', [-Infinity,Infinity] }],[{ 'f16', [-19.203125 (0xcccd)] }],[{ 'f16', [-Infinity,Infinity] }]]
```
I assume this is due to the wording under https://www.w3.org/TR/WGSL/#floating-point-evaluation which states:

> Consider an operation on finite operands. The operation produces overflow, infinity, or a NaN if and only if IEEE-754 would require the operation to signal an invalid operation, division-by-zero, or overflow exception.

but it also seems unexpected that bitcast would do anything more than bit reinterpretation for these types.

If this is the expected behavior, should we make a note in the documentation for bitcast specifically regarding that behavior? For other operations, the note in Section 14.6 is likely sufficient but it would seem particularly useful to note that bitcast can result in more than simply casting of bits.

**Comment by alan-baker** [comment]
Vulkan doesn't require bitcast to preserve a NaN and I have seen implementations that don't do so.

I wouldn't be opposed to a note in bitcast that calls this out.

**Comment by sciecode** [comment]
I believe to have stumbled upon this particular behaviour, and I was pretty surprised.

I was trying to unpack a `uint16` data (octahedral normal encoding) stored into `f16`, but doing the following:

`bitcast<u32>(vec2u(dataf16,0))`

And to my surprise the result wasn't simply a reinterpret cast of the underlying data. It does appear like NaN/Infinity gets "propagated" to the uint32 eventhough integers have no concept of such. I don't seem to understand what's even happening.

I would assume that `bitcast` would simply reinterpret the bytedata, especially when the target format doesn't even have signals to NaN/Infinity. Is this really intended behaviour according to the spec?

**Comment by mwyrzykowski** [comment]
@alan-baker is there some reference as to how bitcast works in Vulkan that you can point to?

It is really surprising to Apple / WebKit that this is not identical to a reinterpret_cast for the types in question. And it does not seem to match what the hardware does either.

**Comment by sciecode** [comment]
> @sciecode u16 has 65536 possible values while f16 has fewer (roughly 61442; it cannot reliably hold any of the bit patterns which represent subnormal/NaN/infinity values). The invalid values may be discarded, for example this may happen while reading the f16 from memory.

I just mapped the full `u16` range and visualized the result after bitcast and noticed exactly what you just described. Although, I fail to see the underlying motivation for this.

Thank you for confirming, eitherway.

> You'll either need to store two u16s into a u32 and unpack it.

Yes, that's how I ended up circumventing the issue.

**Comment by mwyrzykowski** [comment]
Oh thank explanation for that @alan-baker , that made me realize the difference in our implementation.

We compile with `.fastMathEnabled = YES` since nothing in the WGSL specification seemed to prevent us from that.

Does the WGSL spec prohibit us from preserving the denormal? I.e., with fastMath, this does become a reinterpret_cast / (we call `as_type<>()`) since NaNs and denormals are not considered when compiling with fastMathEnabled = YES

Should the CTS allow for both expectations?

**Comment by alan-baker** [comment]
> Oh thanks for that explanation @alan-baker , that made me realize the difference in our implementation.
> 
> We compile with `.fastMathEnabled = YES` since nothing in the WGSL specification seemed to prevent us from that.
> 
> Does the WGSL spec prohibit us from preserving the denormal? I.e., with fastMath, this does become a reinterpret_cast / (we call `as_type<>()`) since NaNs and denormals are not considered when compiling with fastMathEnabled = YES
> 
> Should the CTS allow for both expectations?

WGSL allows preservation (or not) of any of these special values since we expect it to be passed down to the hardware and the controls are not uniform across APIs. So your description of your implementation is perfectly reasonable and expected. The intent is that there is enough slack in the spec to implement in a natural (non-onerous) way on any backend,

CTS should allow both behaviours. Please file a CTS issue if that's not the case. @zoddicus might be able to summarize the state of denorm/inf/nan/signed zero handling in CTS currently.

**Comment by mwyrzykowski** [comment]
Confirmed in https://github.com/gpuweb/cts/issues/3758 this is a CTS test expectation issue, nothing wrong with the specification, closing
