### ISSUE TITLE
Clarify whether `canvas.width = canvas.width` invalidates a WebGPU canvas

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4452]
Prompted by today's discussion on https://github.com/gpuweb/gpuweb/issues/4388#issuecomment-1885985514, our spec should clarify whether setting the `canvas.width`/`height` without _changing_ the value (like `canvas.width = canvas.width`) counts for triggering the [update the canvas size](https://gpuweb.github.io/gpuweb/#abstract-opdef-update-the-canvas-size) algorithm.

@kdashg mentioned in that discussion for 2d canvas it does reset the context. Likely we intended to follow this.
For WebGL the behavior isn't consistent but this seems to just be a Chrome bug (it only clears the canvas on resize if the resize is done in the same task (frame?) with the rendering).

Test case for 2d and webgl: https://codepen.io/kainino0x/pen/QWoKvqx

I think it's unambiguous that we intend to match the existing 2d/WebGL behavior so I'm marking this as editorial M0.

**Comment by greggman** [comment]
https://github.com/gpuweb/cts/pull/3311
