### ISSUE TITLE
Timestamp Write Dictionaries are Identical for Render Passes and Compute Passes

### ISSUE THREAD

**Issue by conorpo** [gpuweb/gpuweb#4455]
![4a23b7f18cf15833f10864aa063d4e36-1](https://github.com/gpuweb/gpuweb/assets/7188746/7d43aafc-9c09-4a57-a930-432b0b619496)

![b4d1787c96bd7fcf2ef9a85ebc1f17ea](https://github.com/gpuweb/gpuweb/assets/7188746/82079d9c-c187-477d-bf31-a79b75dc5589)

Is there a reason that these two are separate? Why not just have one GPUPassTimestampWrites?

**Comment by haoxli** [comment]
We intentionally differentiates between `GPURenderPassTimestampWrites` and `GPUComputePassTimestampWrites` here because we may want to add "beginning of fragment processing" or "end of vertex processing" values to `GPURenderPassTimestampWrites` in future, but not `GPUComputePassTimestampWrites`.
