### ISSUE TITLE
Content timeline step (6) for copyExternalImageToTexture() is inaccurate

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4456]
In the Content timeline steps for [copyExternalImageToTexture()](https://gpuweb.github.io/gpuweb/#dom-gpuqueue-copyexternalimagetotexture), it says:

> source.origin.[z](https://gpuweb.github.io/gpuweb/#gpuorigin3d-z) + copySize.[depthOrArrayLayers](https://gpuweb.github.io/gpuweb/#gpuextent3d-depthorarraylayers) must be ≤ 1.

but source.origin is of type GPUOrigin2D which has no z member. Should that text be replaced with something like the following?

> copySize.[depthOrArrayLayers](https://gpuweb.github.io/gpuweb/#gpuextent3d-depthorarraylayers) must be ≤ 1.

**Comment by kainino0x** [comment]
Indeed it should. Good catch.
