### ISSUE TITLE
Link tooltips overlaps link in table

### ISSUE THREAD

**Issue by guusw** [gpuweb/gpuweb#4457]
(Not sure where to report this, but this seems like a good place.)

When hovering over specific sections while viewing the spec in a browser (specifically firefox/librewolf) the popup will sometimes overlap the link I want to click.
The most notable example is in https://www.w3.org/TR/WGSL/#address-space
Might be specific to these kind of tables

![erqrqr](https://github.com/gpuweb/gpuweb/assets/16842774/03d103ca-8ae8-415b-8960-1e50a237e059)

**Comment by kainino0x** [comment]
I've noticed a change in tooltip behavior recently and this is probably related to that.
The issue reproduces for me in Firefox but not Chrome.

This is a Bikeshed issue so let me refile it there.
