### ISSUE TITLE
Per-pipeline binding points

### ISSUE THREAD

**Issue by martinfouilleul** [gpuweb/gpuweb#4459]
Currently it seems binding points can only be specified at the module level. This means you can't really have multiple pipelines defined in a single module, unless they have exactly the same binding points with the same read/write attributes. 

For instance, say you have two shaders sharing common data structures and utility functions, and shader A uses a buffer as a read/write atomic, and shader B later needs only to read the results. These two shaders can't really be defined in the same module, unless you needlessly force B to use the buffer as read/write atomic even though it only reads from it.

You can of course split your code into multiple fragments, manually append the common parts, and compile to different modules, but this has some downsides:
- it forces compiling the common code multiple times
- the burden is now on the user to have the scaffolding in place to combine code fragments and keep track of source locations (especially since there's no #line directive)
- Having all your shaders in the same file, especially if they are supposed to cooperate on data structs and logic, would be a nice quality of life improvement.

Are there plans to scope binding points to specific entry-points (e.g. similar to what MSL does)? It seems this would let users organize their shader code as they see fit, without having to unnecessarily share binding points or write a preprocessor and duplicate compiler work.

**Comment by dj2** [comment]
As far as I know, this should work already. Binding points are only attached to an entry point if they're transitively used by that entry point. Can you give an example of a WGSL shader which doesn't work correctly?

**Comment by martinfouilleul** [comment]
Thanks for the answer! It totally possible I'm missing something, but here is a minimal example:

```
@group(0) @binding(0) var<storage, read_write> writeBuffer : array<u32>;
@group(0) @binding(1) var<storage, read> readBuffer : array<u32>;   
                                                                    
@compute @workgroup_size(1) fn shaderA(@builtin(global_invocation_id) gid : vec3u) {            
    writeBuffer[gid.x] = gid.x;                                     
}                                                                   
                                                                    
@compute @workgroup_size(1) fn shaderB() {                                                      
    var result : u32 = 0;                                           
    for(var i : u32 ; i<arrayLength(&readBuffer); i++)              
    {                                                               
        result += readBuffer[i];                                    
    }                                                               
}                                                                         
```

In this module I have an entry point A using a buffer as read_write and an entry point B using the _same_ buffer as read only. I have a validation error when setting the bindgroup ("Buffer usage includes writable usage and another usage in the same synchronization scope.")  which is expected since the buffer is bound to two binding point with different modes. Although if binding points are attached only if they are used by an entry point, this configuration shouldn't cause a validation error. 

A workaround would be to have two bindgroup and use a dummy buffer for the binding point that's not in use, but it quickly becomes annoying with more complex shaders.

(Btw I'm using Dawn, so maybe this problem is specific to Dawn's implementation?)

**Comment by dj2** [comment]
Ah, so from a WGSL perspective, it should be fine, I believe. The entry points would have distinct sets of bindings. It seems like it's an error coming from the API validation side, not sure if what you're doing is allowed by API spec or not as it sounds like both of those bindings are in the same bind group.

You shouldn't need a placeholder buffer for the binding points. Only buffers used by the entry point should be needed. So you can have a binding group for the `shaderA` which sets up the `writeBuffer` only and a binding group for `shaderB` which sets up with the `readBuffer` only. The shader code would stay as you have it above.

**Comment by martinfouilleul** [comment]
If I make two bindgroups, and set only `writeBuffer` in bindgroup A and only `readBuffer` in bindgroup B, then I get another validation error ("Binding entry buffer not set.").
So it looks like the API does not permit leaving binding points unset, even if they're not used by the pipeline?

**Comment by conorpo** [comment]
const shader = device_info.device.createShaderModule({
    code: shaderSrc,
  });
  
  const pipelineA = device_info.device.createComputePipeline({
    label: 'pipelineA',
    layout: 'auto',
    compute: {
      module: shader,
      entryPoint: 'shaderA',
    },
  });

  const pipelineB = device_info.device.createComputePipeline({
    label: 'pipelineB',
    layout: 'auto',
    compute: {
      module: shader,
      entryPoint: 'shaderB',
    },
  });

  const buffer = device_info.device.createBuffer({
    size: 4 * 4,
    usage: GPUBufferUsage.STORAGE,
  });

  const bindGroupA = device_info.device.createBindGroup({
    label: 'bindGroupA',
    layout: pipelineA.getBindGroupLayout(0),
    entries: [{
      binding: 0,
      resource: {
        buffer,
      },
    }],
  });

  const bindGroupB = device_info.device.createBindGroup({
    label: 'bindGroupB',
    layout: pipelineB.getBindGroupLayout(0),
    entries: [{
      binding: 0,
      resource: {
        buffer,
      },
    }],
  });
  ```

**Comment by martinfouilleul** [comment]
Oh ok right, it works, the key was to have two separate bindgroup layouts. I though the bindgroup layout had to match exactly what was declared in the shader. I also didn't know you could use the same binding point multiple time without collision in the same module, as long as they're not used from the same entry point.

So this is much nicer than I thought! The only remaining (small) annoyance is that the names of the binding points can collide, whereas if binding points where explicitly scoped as entry points argument I could just use "buffer" in both shaders, without having to prefix it with "read" or "write".

Anyway thanks for your answers!

**Comment by kainino0x** [comment]
> The only remaining (small) annoyance is that the names of the binding points can collide, whereas if binding points where explicitly scoped as entry points argument I could just use "buffer" in both shaders, without having to prefix it with "read" or "write".

This issue was discussed in #2426
