### ISSUE TITLE
for dispatchWorkgroups, the workgroupCountY and workgroupCountZ default to 1

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#4467]
The workgroupCountY and workgroupCountZ paramteters to dispatchWorkgroups are listed as optional.
But the default value is not specified.  I think the default value is 1.

**Comment by jrprice** [comment]
The default values are listed in the function signature, FWIW:
```
undefined dispatchWorkgroups(GPUSize32 workgroupCountX, optional GPUSize32 workgroupCountY = 1, optional GPUSize32 workgroupCountZ = 1);
```

**Comment by dneto0** [comment]
Heh.  I should scroll right.

Thanks!
