### ISSUE TITLE
Compat: can not copy multisample textures

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4468]
WebGPU allows using copyTextureToTexture to copy multsampled textures to other multisampled texture sof the same sample count. @shrekshao noticed GLES 3.1 provides no way to this. `glBlitFramebuffer` specifically disallows it

from section 16.2.1

> An `INVALID_OPERATION` error is generated if the draw framebuffer is multisampled

There doesn't appear to be any way to work around this either as there is no way to access individual samples in GLES 3.1

So, it looks like we'll need to validate this out.

**Comment by kdashg** [comment]
Is there any `COMPUTE_SHADER` functionality we can use?

I checked and at least:
* Multisampled textures are `target`=`TEXTURE_2D_MULTISAMPLE`, so `glCopyTexImage` and friends won't work.
* Like you say, `glBlitFramebuffer` forbids this
* `imageLoad`/`imageStore` don't support MS targets
* `texelFetch` works if you are explicit about sample id `sample`, but there's no explicit symmetric store option.

Is it possible to map `gl_FragCoord` to `int sample` for `texelFetch`? If so, this could be done with a very careful draw-blit.

**Comment by greggman** [comment]
You can read individual multisample pixels but there is no way performant to write individual multisample pixels. Maybe you could write a vertex shader that using `gl_VertexID`, generated a triangle per pixel, per sample. So for a 1024x1024 sample count = 4 texture it would generate 4 million triangles (12 million vertices). Each one would cover 1 sample.

**Comment by kainino0x** [comment]
Would it be possible to issue one full-screen-quad draw call per sample, each with a different glSampleMaski?
Though for this and Gregg's solution I suspect the memory bandwidth would be very high (a lot of redundant loads of memory adjacent to the sample we're loading).

**Comment by kainino0x** [comment]
> **Is it possible to map `gl_FragCoord` to `int sample` for `texelFetch`?** If so, this could be done with a very careful draw-blit.

You mean triggering sample-rate shading so that the fragment shader will run once per sample?
Sample-rate shading doesn't appear to exist in ES 3.1:
https://registry.khronos.org/OpenGL-Refpages/es3/html/glMinSampleShading.xhtml
https://registry.khronos.org/OpenGL-Refpages/es3/html/gl_SampleID.xhtml

**Comment by greggman** [comment]
So rather than per sample triangles, you can generate per row quads, one for each sample like this

![multisample-copy](https://github.com/gpuweb/gpuweb/assets/234804/d5889f6e-aac1-4137-aa72-45afc3b12277)

These quads could be generated by vertex_index so no data needed. It's probably not that slow.

**Comment by greggman** [comment]
decided in wg that we'll leave this validated out
