### ISSUE TITLE
Timeout in SwapChain::get_next_texture, or non-blocking call

### ISSUE THREAD

**Issue by LaylConway** [gpuweb/gpuweb#447]
I need to be able to specify a timeout on acquiring the next texture, or call it without blocking if none's available, because I'm rendering multiple windows. If one window's swapchain image acquisition is going to block, I want to try for other windows that need to be rendered first before blocking.

**Comment by Kangz** [comment]
`GPUSwapChain.getNextTexture` is non-blocking on the WebGPU JS API (we haven't discussed but this should be non-controversial). The casing of your issue looks like it is related to `wgpu-rs` or `wgpu-native` please file bugs on their [repo](https://github.com/gfx-rs/wgpu) instead!

**Comment by kvark** [comment]
To be fair, this is a part of the native implementation behavior that would be worth solving at the https://github.com/webgpu-native level. Right now we are just figuring out how the swapchain is exposed.
