### ISSUE TITLE
relax absolute error bound for asin f32: too tight for Intel f32 with DXC

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#4477]
The asin(f32) accuracy tests are failing on Intel when we use DXC.  They used to pass when we used FXC.

https://bugs.chromium.org/p/tint/issues/detail?id=1796 
In particular see @jzm-intel's provided detailed analysis in [comment 22](https://bugs.chromium.org/p/tint/issues/detail?id=1796#c22). Across UHD630, UHD770, and A770,  the worst case absolute error is:  6.803870200E-05
The WGSL spec specfies a worst case absolute error of:  6.77×10-5

The error bound in the WGSL spec was assembled in parts:
- the inherited-from criterion comes from the Vulkan spec
- the allowance for a worse absolute error bound comes from the native (no polyfills required) behaviour of *existing implementations*

I think we should expand the absolute error bound to something like 6.81e-05 to accommodate this implementation combination.

**Comment by kdashg** [comment]
Haha sounds like a big change! :)
Sounds good.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐02‐20-Minutes#relax-absolute-error-bound-for-asin-f32-too-tight-for-intel-f32-with-dxc--issue-4477">WGSL 2024-02-20 Minutes</a></summary>

* JB: 6.77e-5 to 6.81e-5? “Rubber-stamped with extreme prejudice”
* 

</details>
