### ISSUE TITLE
Remove "update the rendering" hook for service/shared worker

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4478]
Per https://github.com/whatwg/html/issues/10112 we should remove the hooks into "update the rendering" for service/shared worker, and we should leave a note explaining that they're not needed because there's no rAF and you can't transferControlToOffscreen to service/shared workers.

**Comment by beaufortfrancois** [comment]
See https://github.com/gpuweb/gpuweb/pull/4479

**Comment by kainino0x** [comment]
Marking editorial as the question has been more or less resolved over on whatwg/html#10112.
