### ISSUE TITLE
Spec is unclear about 3D texture mipmap support

### ISSUE THREAD

**Issue by ben-clayton** [gpuweb/gpuweb#4491]
https://www.w3.org/TR/webgpu/#dom-gputexturedimension-2d says:

> Specifies a texture that has a width and height, and may have layers. **Only "2d" textures may have mipmaps**, be multisampled, use a compressed or depth/stencil format, and be used as a render attachment.

Yet https://www.w3.org/TR/webgpu/#abstract-opdef-maximum-miplevel-count has a mipmap limit for 3d textures. It would appear that Dawn supports 3d mipmapped textures.

**Comment by Kangz** [comment]
The spec clearly means to support 3D texture mimaps, see https://gpuweb.github.io/gpuweb/#abstract-opdef-maximum-miplevel-count

Tagging as editorial to fix the issue you pointed out.
