### ISSUE TITLE
Should alphaToCoverageEnabled require a blendable format?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4506]
The steps for ["validating GPURenderPipelineDescriptor"](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpurenderpipelinedescriptor) appear to be incorrect.

Specifically the wording:

> descriptor.[fragment](https://gpuweb.github.io/gpuweb/#dom-gpurenderpipelinedescriptor-fragment).[targets](https://gpuweb.github.io/gpuweb/#dom-gpufragmentstate-targets)[0].[format](https://gpuweb.github.io/gpuweb/#dom-gpucolortargetstate-format) must be a [GPUTextureFormat](https://gpuweb.github.io/gpuweb/#enumdef-gputextureformat) with an alpha channel.

but using alphaToCoverage requires blending at least on Metal.

Is it intentional that it says 'an alpha channel' and not 'supports blending'? We notice a validation issue when rgba8-sint is used with alpha to coverage, as MTLPixelFormatRGBA8Sint does not support blending.

**Comment by mwyrzykowski** [comment]
This could be worked around in metal possibly but before we do so, I want to clarify the expectation as the CTS does not appear to cover this case

**Comment by toji** [comment]
Some previous discussion in #3982, though it seems more concerned about ensuring that fragment outputs match the target channels. There's a "Resolved" comment from last April, and though it doesn't cite where that resolution was reached it appears to be from the [previous day's call](https://docs.google.com/document/d/1uJ0JwpbSEvsDXT4Ioovm9cxuP9hQ8X0ztLJ1LjL6SEU/edit#heading=h.mfwwd36y4r90).

All of that discussion seems to be tangential to the issue of whether the format is blendable or not, though. Feels like this is an aspect of it that was simply overlooked?

That said, looking through the Vulkan spec (which, admittedly, is tough to search for this type of thing) I see lots and lots of validation that ensures that the fragment outputs at location 0 index 0 must have an alpha value (the thing that the existing validation ensures) but nothing that ensures that the target is blendable if [VkPipelineMultisampleStateCreateInfo::alphaToCoverageEnable](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VkPipelineMultisampleStateCreateInfo) is enabled. And to me that seems reasonable? Alpha-to-coverage is not blending in the traditional sense, even if it utilizes the alpha channel. If Metal conflates the two then that's probably unexpected from our perspective, and merits additional discussion and potential validation based on that new information.

**Comment by mwyrzykowski** [comment]
That's right, the specific error from Metal is:
```
validateWithDevice:4343: failed assertion `Render Pipeline Descriptor Validation
MTLRenderPipelineDescriptor with alphaToCoverageEnabled requires a float/unorm pixel format, but colorAttachments[0].pixelFormat(MTLPixelFormatRGBA8Sint) is not blendable
```

**Comment by toji** [comment]
Thanks for the error text! That helps. @kainino0x, @jimblandy: Seems like this is worth discussing with the rest of the group?

**Comment by toji** [comment]
Also, I should mention that in order to satisfy both APIs if we were to make that change it would likely have to be to validate that the format was [blendable](https://gpuweb.github.io/gpuweb/#blendable) AND that it had an alpha channel (since some formats like `r8unorm` are [listed as blendable](https://gpuweb.github.io/gpuweb/#plain-color-formats) but don't include alpha)

**Comment by mwyrzykowski** [comment]
Yes that seems like a reasonable restriction

**Comment by kainino0x** [comment]
> Feels like this is an aspect of it that was simply overlooked?

Yup, I think so. 

> Seems like this is worth discussing with the rest of the group?

Agreed.

**Comment by kainino0x** [comment]
I agree that intuitively that blending support doesn't seem necessary for alpha-to-coverage, although it definitely runs into some weird problems with integer formats. In particular, in order to use alpha-to-coverage, I think the shader needs to output a float component for alpha, which of course means it needs to output float for the RGB components too.

IIRC this is generally allowed by an implicit cast to the texture format after the fragment shader returns, however if the format is rgba32uint/rgba32sint, then there are a lot of values that are unrepresentable in f32, namely anything outside the [-16777217, 16777217] range.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-03-06#should-alphatocoverageenabled-require-a-blendable-format-4506">GPU Web 2024-03-06 Pacific-time</a></summary>

* KG: Metal validation being passed down to us. Should we just say it's required? Alternative is - potential workaround?
* KN: was warning whether the warning's correct. But don't think the behavior we currently allow is valuable, so think we should add this restriction.
* KG: Metal considers this part of the fixed-function blending hardware. That's the consideration. Need to send a PR for this.

</details>

**Comment by kainino0x** [comment]
In the meeting we resolved to add a `usage` option to createView defaulting to the usage of the texture.

**Comment by kainino0x** [comment]
Now tested in https://github.com/gpuweb/cts/pull/4706
