### ISSUE TITLE
Will function overloading be supported in the future?

### ISSUE THREAD

**Issue by microaaron** [gpuweb/gpuweb#4507]
Currently user-defined functions only have one overload. [Will function overloading be supported in the future?](https://github.com/gpuweb/gpuweb/issues/876) This is very commonly used.
Like this:
```
var<private> gammaEncode4Vector: vec4<f32> = vec4<f32>(0.4545454545454545, 0.4545454545454545, 0.4545454545454545, 1.0);
var<private> gammaEncode3Vector: vec3<f32> = vec3<f32>(0.4545454545454545, 0.4545454545454545, 0.4545454545454545);
fn gammaEncode(color: vec4<f32>)->vec4<f32>{
  return pow(abs(color), gammaEncode4Vector);
};
fn gammaEncode(color: vec3<f32>)->vec3<f32>{
  return pow(abs(color), gammaEncode3Vector);
};
```
#876 was proposed in 2020, hope it is still taken seriously
[And, it would be better to support operator overloading.](https://github.com/gpuweb/gpuweb/issues/4357)

**Comment by kdashg** [comment]
Yep, this is #876, currently slated for Milestone 3. (not soon, sadly!)
(closing as duplicate)
