### ISSUE TITLE
Does writeTimestamp() belong to GPUCommandEncoder or GPURenderPassEncoder?

### ISSUE THREAD

**Issue by microaaron** [gpuweb/gpuweb#4524]
According to developer.mozilla.org, ```writeTimestamp()``` is a method of GPUCommandEncoder.
https://developer.mozilla.org/en-US/docs/Web/API/GPUCommandEncoder/writeTimestamp
But actually ```writeTimestamp()``` is in ```GPURenderPassEncoder``` (chrome 122.0.6261.129)
![捕获000](https://github.com/gpuweb/gpuweb/assets/16946786/27afd024-fc11-4b57-9326-be28a5942c4b)
![捕获001](https://github.com/gpuweb/gpuweb/assets/16946786/43394566-4a00-4875-981b-dcd8820fe41d)

**Comment by microaaron** [comment]
https://github.com/gpuweb/gpuweb/pull/4370 ```writeTimestamp()``` seems to only exist in the old spec.

**Comment by kainino0x** [comment]
Indeed it doesn't exist right now. Proposals exist for both versions of writeTimestamp.

Inside passes:
https://github.com/gpuweb/gpuweb/blob/main/proposals/timestamp-query-inside-passes.md

Outside passes:
Removed in #4370 as you found. Still open for discussion in #3952.
