### ISSUE TITLE
Allow 3D Textures with 2D Compressed Formats

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#4537]
The current specification does not allow 2D compressed blocks for 3D textures. Although a report in detail is necessary, for many years, I have been actively using ASTC 2D blocks and BC1, BC4, and BC7 2D blocks for 3D textures on macOS, Windows, and Linux with Vulkan, Direct3D 12, Metal without any issues. For real-world volumetric data, the space-saving with reasonable quality preservation of these compressed blocks is immense: it can mean you can fit 4x more slices or maybe even more, depending on the starting point. If there's nothing particularly blocking for 2D compressed slices as backing data for 3D textures, the spec would make it possible to port scientific visualization applications if this validation rule was relaxed.

Just to be clear, this issue is not about 3D blocks of ASTC, which are objectively better for data with 3D spatial correlation but have very little support.

This validation rule might come from here, which concerns more about the proper 3D compressed blocks: https://github.com/gpuweb/gpuweb/issues/1522

Thank you!

**Comment by kainino0x** [comment]
#3183 tracks both this and the 3d block formats. As you mentioned those have very little support but I think we can fold this issue into that one.
