### ISSUE TITLE
Reduce limits for composite types

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#4547]
The WGSL spec currently has two limits for composite types:
- 16383 struct members
- Nesting depth of 255

Through [CTS testing](https://github.com/gpuweb/cts/pull/3389), we have found that these limits are impractical on multiple platforms. We have observed compilation failures and timeouts on various native drivers. Deeply nested arrays also trip over Tint's own limits of recursion depth.

To better reflect reality, I propose that we lower the limit as follows:
- 1024 struct members
- Nesting depth of 16

Since these limits are purely informative and implementations are permitted to support shaders that go beyond them, this would be a backwards compatible change.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐04‐16-Minutes#reduce-limits-for-composite-types--issue-4547">WGSL 2024-04-16 Minutes</a></summary>

* Approved

</details>
