### ISSUE TITLE
Reduce limits for the number of case selector values in a switch statement

### ISSUE THREAD

**Issue by jrprice** [gpuweb/gpuweb#4548]
The WGSL spec currently has a limit of 16383 case selector values in a switch statement.

Through [CTS testing](https://github.com/gpuweb/cts/pull/3389), we have found that this limit causes excessive compilation times (>1 minute) on some D3D drivers.

To better reflect reality, I propose that we lower the limit to 1024.

Since these limits are purely informative and implementations are permitted to support shaders that go beyond them, this would be a backwards compatible change.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐04‐16-Minutes#reduce-limits-for-the-number-of-case-selector-values-in-a-switch-statement--issue-4548">WGSL 2024-04-16 Minutes</a></summary>

* Approved

</details>
