### ISSUE TITLE
Broken Chromium bug tracker link on Implementation Status wiki page

### ISSUE THREAD

**Issue by jjudd** [gpuweb/gpuweb#4553]
The [implementation status](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status) wiki page has a Chromium bug tracker link that points to bugs.chromium.org. The link currently redirects to issues.chromium.org and during that redirect the `q=` url parameter is changed, so you end up at https://issues.chromium.org/issues?q=is:open instead of https://issues.chromium.org/issues?q=component:Blink%3EWebGPU.

This change will fix it.
```diff
-    Chromium bug tracker [Blink&gt;WebGPU component](https://bugs.chromium.org/p/chromium/issues/list?q=component:Blink%3EWebGPU).
+    Chromium bug tracker [Blink&gt;WebGPU component](https://issues.chromium.org/issues?q=component:Blink%3EWebGPU).
```

I'm not aware of a way to open a PR against a wiki page, so I'm filing an issue instead.

**Comment by kainino0x** [comment]
Fixed, thank you!
