### ISSUE TITLE
smoothstep: is it an error when `low == high` and/or `low > high` (when constant/pipline-evaluated)

### ISSUE THREAD

**Issue by amaiorano** [gpuweb/gpuweb#4561]
See [smoothstep](https://www.w3.org/TR/WGSL/#smoothstep-builtin) where we define how the result is computed:

```
For scalar T, the result is t * t * (3.0 - 2.0 * t), where t = clamp((x - low) / (high - low), 0.0, 1.0).
```

If `low == high`, this results in a divide by 0. Should this be an error at constant/pipeline-evaluation time?

If `low > high`, there is no DBZ, but perhaps we should consider erroring for that case as well? Does it make sense to use `smoothstep` with `low > high`?

**Comment by alan-baker** [comment]
The GLSL extended instruction `SmoothStep` returns an undefined (indeterminate in WGSL) value if `edge0 >= edge1` (i.e. `low >= high` in WGSL). Metal has the same caveat (also if any input is NaN). HLSL doesn't seem to say.

 From that, I'd be inclined to make it an error in early evaluation.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐04‐30-Minutes#smoothstep-is-it-an-error-when-low--high-andor-low--high-when-constantpipline-evaluated--issue-4561">WGSL 2024-04-30 Minutes</a></summary>

* KG: In underlying APIs this is UB. We promise portable runtime behavior, the question here is how constant evaluation should proceed: polyfill, or report an error, or a warning
* AB: evaluation errors would be consistent with other builtins. This seems like a spec bugfix.
* DN: GLSL goes out of its way to say you shouldn’t do this
* **RESOLVED: MODULE-CREATION-TIME ERROR**

</details>

**Comment by reindernijhoff** [comment]
No... please don't throw an error! 

I use smoothstep with `edge0 > edge1` all the time (use this definition: https://en.wikipedia.org/wiki/Smoothstep, forget about the 'high' and 'low'), as it saves you a subtraction and makes the code more readable IMHO:

`1. - smoothstep(0., 1., t)`  VS
`smoothstep(1., 0., t)`

**Comment by kainino0x** [comment]
Unfortunately if you're using that in any other shading language, it's undefined behavior. WGSL could go out of its way to make it defined behavior (and make it work the way you expect) but I believe it would come at the cost of injecting extra code in the WGSL compiler - e.g. `high > low ? smoothstep(low, high, x) : 1 - smoothstep(high, low, x)`

**Comment by kainino0x** [comment]
Though I'm a bit confused by the WGSL spec - it doesn't say anything about an indeterminate value if high<low:
https://gpuweb.github.io/gpuweb/wgsl/#smoothstep-builtin
The formula given there seems to do the expected thing in that case.

I kind of wonder if all devices actually do the expected thing and the upstream specs are just all overly conservative. It's hard to imagine an implementation where it would actually break.

**Comment by reindernijhoff** [comment]
Yes, I also can't think of why it would break if you look at the formula. In the last ~10 years of writing webgl1 and webgl2 shaders, I never encountered a situation, device or browser that gave undefined behaviour using smoothstep(edge0, edge1, t) with edge1 < edge0. But I agree, the specification tells me it could be undefined: 

https://registry.khronos.org/OpenGL-Refpages/gl4/html/smoothstep.xhtml

**Comment by reindernijhoff** [comment]
It will probably give undefined behaviour for signed variable types, but imo that is still not a reason to always trigger an error if edge1 < edge0.

**Comment by johanholwerda** [comment]
Even if it was undefined behaviour, it does not need to throw an error right? Many of my shaders are broken now. And it is still possible to use low > high by passing numbers that are not compile time constants

**Comment by greggman** [comment]
The point of throwing an error is because, according to the spec, your app doesn't work everywhere. Web apps are *supposed to be* write once run everywhere.

If we can prove the specs are out of date or the number of devices that this is an issue on is tiny and not growing then maybe we can change the WebGPU spec and ideally the native specs too and remove this but, one of the top goals of WebGPU is to be portable which is why, at least for the moment, it was decided to make this an error.

There's been lots of these in WebGL where people ask "why isn't my app working for some users" and it turns out they were using non-portable code.

**Comment by reindernijhoff** [comment]
I can't prove that the number of devices where this doesn't work is tiny. Still, I have ~10 years of experience writing WebGL shaders in a commercial setting (like writing sites for Netflix, Google, Facebook, Nike, etc.), where each site was QA'd on multiple devices and had a lot of visitors. I have never encountered an OS or device where smoothstep didn't work for edge1 < edge0. So I'm pretty confident that the definition of smoothstep is implemented on the GPU/drivers, and nobody added some extra code to return undefined values in the case edge1 < edge0.
