### ISSUE TITLE
u32(abstractint) errors on out of bounds value, u32(abstractfloat) and u32(f32) clamps out of bounds value

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#4569]
The `u32(e:T)` builtin function constructs a u32 value from a scalar `e`.
https://gpuweb.github.io/gpuweb/wgsl/#u32-builtin 

If `e` is a floating point value, then we follow the [scalar floating point to integral conversion](https://gpuweb.github.io/gpuweb/wgsl/#scalar-floating-point-to-integral-conversion) which truncates to zero, and then clamps to the valid range of the target target, in this case 0 to 4294967295u.

(If I recall correctly, WGSL specifies the clamping behaviour to avoid the undefined-behaviour for this case as specified by C/C++)

Note: Internal discussion surfaced the idea that the author is explicitly asking for a conversion because they write the function form `u32(...)`, so they're asking the implementation to convert the value, rather than it being implicit. Separately, the committee  long ago agreed that float to integral conversions should clamp to the target range.

If `e` is AbstractInt :

> If T is [AbstractInt](https://gpuweb.github.io/gpuweb/wgsl/#abstractint), this is an identity operation if the e can be represented in [u32](https://gpuweb.github.io/gpuweb/wgsl/#u32), otherwise it produces a [shader-creation error](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error).

This goes along with the rule from [feasible automatic conversions](https://gpuweb.github.io/gpuweb/wgsl/#feasible-automatic-conversion) that any AbstractInt to concrete integer conversions are value-preserving, or otherwise produce a shader-creation error.

*But* we have the situation where:
```
const a = u32(5000000000); // shader-creation error because it's not value-preserving.
const b = u32(5000000000.0);  // b = 4294967295u
```

It seems a little weird that we end up with such different behaviours here, just by adding a `.0`.

I think no matter what, we want to keep error behaviour for automatic conversion:
```
const c: u32 = 5000000000; // should be an error because it's out of bounds
```

There are at least these options:

1.  No change.
2. Allow explicit conversions `u32(AbstractInt)` and `i32(AbstractInt)` but make them clamp to the target type range
    * If we do this then     `u32(-1)` is 0 but `u32(-1i)` is 4294967295u. 
3. Allow explicit conversions `u32(AbstractInt)` and `i32(AbstractInt)` but make them like a bitcast of the least significant bits.
    * If we do this then     `u32(-1)` is 4294967295u which is the same as `u32(-1i)`, but different from `u32(-1.0)` and `u32(-1.0f)`

Looking at the options, there's always a big difference between conversion from float values  (which clamps) vs. conversion from a concrete integer value (which is like bitcast).

**Comment by alan-baker** [comment]
Whichever option we decide is appropriate we could potentially add a diagnostic that lets us either relax or tighten the behaviour. This would be similar to derivative uniformity, though perhaps with a different default severity.

**Comment by jimblandy** [comment]
I think the current behavior, even given the "we have a situation" example, is probably the right choice. So I think "no change" is probably our preference. Option 3 seems bad.

I feel like I should know the answer to this, but: why aren't all non-value preserving conversions errors in constant expressions? Is it simply because we have no other way of offering bit reinterpretation?

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐04‐30-Minutes#u32abstractint-errors-on-out-of-bounds-value-u32abstractfloat-and-u32f32-clamps-out-of-bounds-value--issue-4569--gpuwebgpuweb--github">WGSL 2024-04-30 Minutes</a></summary>

* KG:  There’s a collision between the desire to lossily-cast something at run time and the desire to strictly cast things at compile time when we have abstract types.
* KG: Mozilla is probably most in favor of saying, this is weird, but we have conflicting desires that can’t be squared in a way that yields perfectly consistent behavior. So, we’d recommend no change. And this is in an edge case - we are probably not going to get memed for ridiculous behavior over this.
* KG: The u32 built-in operator is a five-piece case analysis, which shows how many roles it’s trying to play, as it guesses what you want. Indicates presence of a hazard.
* KG: Mozilla’s feeling: no change is best
* AB: We’d be okay with no change. Suggested introducing a diagnostic, might be useful. The fact that we have both value-preserving and bitcast-style conversion operations makes it okay for these to be different.
* KG: We do have bitcast. The code is asking for a bitcast when there is a more explicit way to get that.
* KG: If folks want more time to consider this, that’s fine, but we did arrive at this behavior for a reason. Close for now?
* **RESOLUTION: CLOSE**

</details>
