### ISSUE TITLE
Implementation Status: Firefox Nightly WebGPU is blocked by default on macOS

### ISSUE THREAD

**Issue by rinsuki** [gpuweb/gpuweb#4572]
I'm not sure about here is correct place of issue reporting for https://github.com/gpuweb/gpuweb/wiki/Implementation-Status , but I can't find more better place than here, so I reported to here (maybe good to create issue template for it).

this page doesn't says about which platform is supported in Firefox Nightly, so reader may expect to supported in every platform.

but, due to https://bugzilla.mozilla.org/show_bug.cgi?id=1864698 , WebGPU support on macOS is blocked by default, with code `FEATURE_FAILURE_MAC_WGPU_NO_METAL_BOUNDS_CHECKS`.

(you can see this code by open `about:support` in Firefox Nightly on macOS)

**Comment by kainino0x** [comment]
This is the right place, thanks! We don't maintain that page super well but we should try to improve it.
@jimblandy maybe you could address this?

**Comment by rinsuki** [comment]
with https://hg.mozilla.org/mozilla-central/rev/bb79dcf0336e , now WebGPU is enabled on Firefox Nightly w/ macOS, like other platforms. I'll close this issue :-)
