### ISSUE TITLE
Samples: Invalid winding mode

### ISSUE THREAD

**Issue by Nielsbishere** [gpuweb/gpuweb#458]
I ran the samples on my macbook and it seems like the winding mode is reversed; it is culling the front of the cube (both the rotating and rotating textured cube).

**Comment by kainino0x** [comment]
I think the samples are now wrong given we recently figured out what our coordinate systems should be. Let me move this issue to the samples repo.

**Comment by kainino0x** [comment]
Or not, I guess I don't have admin. I'll just file it there.
