### ISSUE TITLE
Shape of the API for object creation

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#46]
We've been thinking of what the shape of the API should be to create the WebGPU objects apart from the command buffer/encoders. Our constraints were the following:

 - **Performance and GC:** WebGPU is meant to be a high-performance API on both the GPU and CPU side. Object creation should mostly happen during at load-time but some applications might need to defer object building to rendering time. We should make the overhead of the JS bindings minimal and minimize the amount of GC garbage.
 - **Extensibility:** WebGPU will have extensions that are enabled explicitly by developers when create the WebGPU device. Based on the extensions enabled new capabilities will be exposed, often as new creation arguments for WebGPU objects. Anisotropic filtering for sampler object is something that could be exposed as an extension. There might also be “features” that are like built-in extensions present in the main spec and have to be enabled at device creation time.
 - **WebAssembly:** It will be a first-class citizen of WebGPU meaning that there will be a version of the WebGPU API that’s native to WebAssembly and has as low overhead as possible. Ideally the WASM version API is exactly the same as the JS version.
 - **Type safety:** For the best developer experience we would like the API to be well-typed so that developers don’t spend hours debugging to find a type in on argument to an object creation. We would also make it easy for developers to use extensions and have correct code with/without the extensions. This safety can be “compile-time”, at runtime or runtime with a “debug device” / devtools open.
 - **JSness:** It would be nice if the API could be used in a way that looked idiomatic in Javascript.

This approach has been suggested by @fserb. Thanks!

Example WebIDL (that was validated with the [WebIDL checker](https://www.w3.org/2009/07/webidl-check)):

```webidl
dictionary WebGPUSamplerDictionary {
    long wrapModeR; // Or some enum type?
    long wrapModeS;
    // If the anisotropic extension is supported
    long maxAnisotropy;
};

interface WebGPUSamplerDescriptor {
    attribute long wrapModeR; // Or some enum type?
    attribute long wrapModeS;

    void setWrapModeR(long value);
    void setWrapModeS(long value);

    // If the anisotropic extension is supported
    attribute long maxAnisotropy;
    void setMaxAnisotropy(long value);
};

interface WebGPUSampler {
    // Opaque handle
};

interface WebGPUDevice {
    WebGPUSamplerDescriptor createSamplerDescriptor();
    WebGPUSampler createSampler((WebGPUSamplerDictionary or WebGPUSamplerDescriptor) arg);
};
```

Example of the multiple ways to use this:

```js
//--- Use of a descriptor with the setters
let desc = device.createSamplerDescriptor();
desc.setWrapModeR(...);
desc.setWrapModeS(...);

if (canUseAnisotropicFiltering) {
    // Throws if the extension is not implemented (“method doesn’t exist”)
    // Throws if the extension is not enabled (“extension isn’t enabled”)
    desc.setMaxAnisotropy(...);
}

let sampler = device.createSampler(desc);
// or let sampler = new WebGPUSampler(device, desc) with the corresponding IDL changes.

//--- Use of a descriptor with its attributes
let desc = device.createSamplerDescriptor();
desc.wrapModeR = ...;
desc.wrapModeS = ...;

// This is ignored if the extension is not present
desc.maxAnisotropy = ...;

let sampler = device.createSampler(desc);

//--- Use of a dictionary
let sampler = device.createSampler({
    wrapModeS: …,
    wrapModeR: …,
    maxAnisotropy: …,
});
```

Going back to the constraints:
 - **Performance and GC:** Descriptors should be able to be optimized and can even be reused if GC pressure is a concern. Setter functions could be slower than just setting the property directly on the descriptor (?).
 - **Extensibility:** Works, extension properties can be pre-filled on descriptors or have default values for missing dictionary arguments.
 - **WebAssembly:** Descriptor objects could be exposed as opaque objects in WASM, with methods to set values. This requires host bindings to work with opaque objects, but doesn’t require WASM property bags. @flagxor confirmed that this would work well with the host bindings currently being discussed in the WASM group.
 - **Type safety:** Great type safety in WASM. JS can use the setters for more type-safety.
 - **JSness:** The last example looks like idiomatic JS.

Would love to hear your thoughts!

**Comment by kvark** [comment]
> Descriptors should be able to be optimized and can even be reused if GC pressure is a concern

Would be nice to use a different term here to avoid confusion with actual resource descriptors of Vulkan/D3D12. Yes, yes, I know D3D also uses `XXX_DESC` structures, but I don't think we should take that as an example to follow.

> Descriptor objects could be exposed as opaque objects in WASM, with methods to set values. 

Since those are interfaces in IDL, would this block the ability to allocate them on the stack (from the point of view of the calling application)? That would be unfortunate.

```js
    // Throws if the extension is not implemented (“method doesn’t exist”)
    // Throws if the extension is not enabled (“extension isn’t enabled”)
    desc.setMaxAnisotropy(...);
```
If I understand correctly, that ability to throw is the only benefit of having the methods as an alternative to just properties. This seems a bit unnecessary given that we should have some extension discovery mechanism, in which case the user should be able to check for anisotropy support way ahead of actually filling up the sampler info.

**Comment by Kangz** [comment]
> Would be nice to use a different term here to avoid confusion with actual resource descriptors of Vulkan/D3D12. Yes, yes, I know D3D also uses XXX_DESC structures, but I don't think we should take that as an example to follow.

Metal does use the term descriptor too. The overload of the term is unfortunate but since this issue is about the shape of the API the context makes it clear what we're talking about. I'm sure we'll have discussions about terminology later down the line.

> Since those are interfaces in IDL, would this block the ability to allocate them on the stack (from the point of view of the calling application)? That would be unfortunate.

When talking to our WASM folks they mentioned that all "host bindings" proposals will be able to optimize function calls on opaque handles, and primitive types. This doesn't include structures allocated on the stack. What was mentioned is that efficient mapping of property bags in WASM is a difficult subject and won't be handled anytime soon, if ever.

We also really wanted to have the same IDL between the JS and WASM interface so the descriptors have to be shown as opaque objects in WASM and we didn't look into interfaces taking pointers to the WASM stack.

> If I understand correctly, that ability to throw is the only benefit of having the methods as an alternative to just properties.

The methods are used so they can be exposed to WASM. There is no plan to expose setting JS attributes directly from WASM (unless you want to round-trip through the JS VM). The error behavior in JS is a nice side-effect that you can opt into having loud errors if you mess up your extension code paths.

**Comment by frzi** [comment]
Below are some of my opinions and thoughts of the suggested interfaces:

### Descriptors with setter functions
* **Pros**
    * You can check for functions availability after certain extensions are enabled:
        ```js
        if ('setMaxAnisotropy' in descriptor) {
            descriptor.setMaxAnisotropy(...)
        }
        ```
        (Trivial with [optional binding](https://github.com/tc39/proposal-optional-chaining), however):
        ```js
        descriptor.setMaxAnisotropy?.(...)
        ```
    * Auto-complete / suggestion from the browser / console.
    * Can verify the given parameters.

* **Cons**
    * Can be considered inconsistent with other web APIs. Setter functions in web APIs often appear only when more than 1 argument is required (or expected). Otherwise setters are usually done through properties. In third-party libraries (such as THREE.js) setter functions exists mainly to wrap around 'private' properties. Though one could argue even this has become unnecessary since ES5's introduction to setters and getters in Objects.
    * Would also need getter functions. This will make bitwise operations a hassle.

### Descriptors with properties
* **Pros**
    * Is more idiomatic JavaScript. 
    * Easy to configure from a JSON:
        ```js
        for (const [key, value] of Object.entries(json)) {
             descriptor[key] = value
        }
        ```
    * Auto-complete / suggestions from the browser / console.
    * Can verify the given value.
* **Cons?**
    * Doesn't know when an unknown property is assigned (e.g. a misspelled property)? Preventing this would be anti-JavaScript.

### Plain ol' dictionary
* **Pros**
    * Very JavaScripty; a lot of web APIs simply want a dictionary for grouped parameters, opposed to a specific object type.
    * Developers can directly use JSONs.
    * Not tied to the device / instance and thus always reusable. Useful if the developer decides to initialize more devices / instances.
    * Can help shorten code:
        ```js
        let sampler = device.createSampler({ minFilter: device.FILTER_NEAREST })
        // or
        const { minFilter } = json
        let sampler = device.createSampler({ minFilter })
        ``` 
* **Cons**
    * No auto-complete / suggestion from the browser / console. Prone to typos.
    * Can't verify its properties nor their values.

The descriptor being able to verify its values seems like a worthy feature to consider (when the developer enabled the debug layer (or something equivalent)). This would allow descriptors to warn the developer of invalid properties ahead of creating one or multiple WebGPU objects.

'Auto-complete / suggestion from the browser' may seem trivial. But it's certainly very welcoming when prototyping in the browser. Or to quickly refresh your memory on certain method and property names, (opposed to simply looking up the documentation :) ).

Though using simple dictionaries is very tempting, given to the importance of type safety I personally think 'Descriptors with properties' is the best route to go for WebGPU object creation.

**Comment by Kangz** [comment]
Closing this, the group has settled to use the plain dictionary approach.
