### ISSUE TITLE
Has isInf() been removed?

### ISSUE THREAD

**Issue by coramat** [gpuweb/gpuweb#4602]
There used to be a built-in function named isInf(), but I can no longer find it in the [WGSL documentation](https://www.w3.org/TR/WGSL), nor anything similar. Has it been removed or renamed?

Thanks a lot:)

**Comment by alan-baker** [comment]
It was removed because implementations do not reliably preserve infinities (or nans and subnormals). Hopefully, there is a future where we can add it back in a portable and reliable way.
