### ISSUE TITLE
Allow 2d-array texture view as renderable texture view

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#4607]
Currently a [renderable texture view](https://www.w3.org/TR/webgpu/#abstract-opdef-renderable-texture-view) is a `2d` or `3d` texture view which arrayLayerCount is 1.

But using a `2d-array` texture view with arrayLayerCount 1 in color attachments also be valid in D3D12, Vulkan and Metal. And by default, [createView()](https://gpuweb.github.io/gpuweb/#dom-gputexture-createview) without specifying a dimension on a `2d` texture with more than one layer will create a `2d-array` GPUTextureView, even if an arrayLayerCount of 1 is specified.

So `2d-array` texture view with arrayLayerCount 1 also can be a renderable texture view.

**Comment by magcius** [comment]
Alternatively, creating a texture view with an arrayLayerCount of 1 should create a 2d texture view? Unless it's too late to fix that.

**Comment by Kangz** [comment]
It's too late to change that indeed.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-05-08#allow-2d-array-texture-view-as-renderable-texture-view-4607">GPU Web WG 2024-05-08 Pacific-time</a></summary>

* HL: (summary)
* MM: Motivation for this?
* HL: Using 2d array view not allowed in WebGPU but it’s valid in each backend. createView() also will create a 2d-array view by default [on a 2d texture with multiple layers, creating a view with arrayLayerCount: 1] so it is easy to hit.
* KG: Think this sounds like a good idea. Any objections?
* **Consensus: Needs PR, but resolved**

</details>
