### ISSUE TITLE
PNG ImageBitmap (WebAPI) incompatibility with `copyExternalImageToTexture` for physically-based workflow.

### ISSUE THREAD

**Issue by sciecode** [gpuweb/gpuweb#4609]
I recently came across a compatibility issue regarding WebAPI's PNG `ImageBitmap` and WebGPU's `copyExternalImageToTexture` in a photometry/colorimetry workflow (linear-workflow).

I'll start by saying this is a complicated topic, and that I'll have to simplify concepts in order to make this digestible, but I will provide links to specs/articles/blogs that further clarify some of the more relevant claims. It's also worth mentioning that I am unsure if this compatibility issue is something that WebGPU or `ImageBitmap` WebAPI should resolve, I hope that you are able to help me figure it out.

The compatibility is related with filtering & blending .png textures uploaded to WebGPU via the aforementioned API. In a photometric consistent workflow, a special care with color-encoding is required when dealing with color data. In order to preserve color fidelity, color operations are expected to be performed in linear intensity (not gamma-encoded / sRGB), this includes texture filtering & alpha-blending.
- (Claim#1 [PNG specification](https://www.w3.org/TR/png/#13Alpha-channel-processing))

When linearly filtering color textures that includes `alpha` information, it is important to premultiply the alpha information on the color itself (associative alpha) to account for correct alpha-blending. We do this because texture filtering algorithm only performs a `bilinear interpolation` of the underlying data and not an alpha-aware interpolation.
- (Claim#2 [blog1](https://www.realtimerendering.com/blog/gpus-prefer-premultiplication/) - Eric Haines, [blog2](https://www.realtimerendering.com/blog/png-srgb-cutoutdecal-aa-problematic/) - Eric Haines, [blog3](https://iquilezles.org/articles/premultipliedalpha/) - Inigo Quilez)

Having presented the claims, I can finally explain the issue. The workflow presented above is currently impossible when dealing with PNG `ImageBitmap` & current WebGPU external image upload. Photometric consistent & compliant PNG files are stored in a gamma-encoded (usually sRGB) unassociated alpha format. This means that in order to correctly upload this to GPU context, we are required to first decode the color data into `linear-rgb` and afterwards premultiply-alpha to make it associative-alpha.

ImageBitmap ([createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap)) doesn't provide an API to decode the gamma-encoded data to `linear-rgb`, it only provides an API to pre-multiply alpha. However we don't want this yet, we first need to decode into linear.

`CopyExternalImageToTexture` also doesn't provide an API to decode the data to `linear-rgb`, it, also, only provides an API to premultiply alpha. This means, that even if you want to use a `rgba8unorm-srgb` texture to properly decode it to `linear-rgb` before texture filtering, you can't pre-multiply alpha afterwards, because it only happens before or during texture upload. 

So there isn't a physically correct workflow to use .png texture using this API.

Currently, in order to use this workflow, the user is required to manually *read/decode* the PNG bitmap data, *convert* it to `linear-rgb`, *premultiply-alpha* & *upload* to a WebGPU texture via `writeTexture` API.

In order to further exemplify this, I've created a demo showing the differences between all available workflows and two examples of manually performing this photometric workflow (bottom 2 stripes). 
 - [PNG filtering example](https://rawcdn.githack.com/sciecode/phoptics.js/7d96374a74f2c8b4e94a8eea1ffafa6023d6de2f/examples/bitmap/index.html?min=1)
 
Small demo clarification: Original .png consists of a 2x1 image (2 pixels) with values indicated on the sides (original file sRGB & decoded linear-rgb - both unassociated-alpha), the background is entirely black (#000). The first stripe is the only one that doesn't involve WebGPU context, it is simply a standard HTMLImageElement filtered entirely by the user-agent default html renderer (another can of worms).

I understand this might be a lot to take in, but feel free to ask questions if I didn't make myself clear of if you require further explanations. Thank you.

**Comment by sciecode** [comment]
Upon further review of the spec, it appears [copyExternalImageToTexture](https://www.w3.org/TR/webgpu/#dom-gpuqueue-copyexternalimagetotexture) is supposed to automatically handle color encoding/decoding based on the source data format -> destination texture format. Which, seems to suggest, that the demo should be using non "-srgb" textures as target.

[PNG updated demo - using rgba8unorm](https://rawcdn.githack.com/sciecode/phoptics.js/a0ec7150fce083e2d5a5a766948ebb4d892c932b/examples/bitmap/index.html?min=1)

However it still doesn't perform the expected filtering/blending. The specification doesn't determine an order of operation, in regards to `premultipliedAlpha` x `color encode/decode`, perhaps it should. But this appears to be a user-agent bug (chrome in my case), and not something spec predict. I'll wait confirmation.

**Comment by shaoboyan** [comment]
@sciecode My understanding is that your expectation is:
PNG File (srgb and alpha) ----Decode to linear---> Content ---> Do premultiply-alpha ?

It seems that a copy from png image to `srgb-linear` color space with dst alpha config to `premultiplied` should work. But unfortunately, I checked the `predefinedColorSpace` (https://html.spec.whatwg.org/multipage/canvas.html#predefinedcolorspace) and it doesn't have `srgb-linear`.

@kainino0x  Do you think the predefinedColorSpace would be expanded in future to support this ? (More CSS color space https://www.w3.org/TR/css-color-4/)

**Comment by sciecode** [comment]
> PNG File (srgb and alpha) ----Decode to linear---> Content ---> Do premultiply-alpha ?

That is corrent.

There's also a subtle, but important, aspect of `sRGB` -> `linear-rgb` conversion. The destination `linear` bitmap needs at least 10-bit depth formats to retain sufficient color precision, otherwise this is a lossy conversion and incurs banding in the darker values [0,128].

**Comment by Kangz** [comment]
Chromium implements `srgb-linear` if `--enable-features=CanvasHDR` is passed. It is meant to test the in-progress implementation of additional color 'stuff'. WebGPU should already support that color space when it is enabled, does Shaobo's suggestion work in this case? +CC @ccameron-chromium as well.

**Comment by sciecode** [comment]
> Chromium implements `srgb-linear` if `--enable-features=CanvasHDR` is passed. It is meant to test the in-progress implementation of additional color 'stuff'. WebGPU should already support that color space when it is enabled, does Shaobo's suggestion work in this case? +CC @ccameron-chromium as well.

Yes, with PredefinedColorSpace `srgb-linear` under the experimental chromium flag, the result is indeed what I would expect.

[srgb-linear demo](https://rawcdn.githack.com/sciecode/phoptics.js/a6c6c5a56d71020008cf7294fb109491c885a709/examples/bitmap/index.html?min=1) (requires `--enable-features=CanvasHDR`)

I've also validated the precision for gamma-decoding and chromium appears to be handling it properly, as it didn't introduce additional banding when using dst texture `rgba16float`.

**Comment by Kangz** [comment]
Thanks for the confirmation. So it seems that with future CSS color improvements and their integration in WebGPU this should naturally get fixed, and that no changes are needed for WebGPU itself. Tentatively closing this issue.
