### ISSUE TITLE
Should bitcast tests allow FTZ on inputs/outputs?

### ISSUE THREAD

**Issue by zoddicus** [gpuweb/gpuweb#4623]
From https://issues.chromium.org/issues/42250993.

Dawn currently appears to be performing FTZ on denorms when going through bitcasts. The example shader from the above issue is doing this:
```
        var g = 50u;
        let a: f32 = bitcast<f32>(g);
        var b: u32 = bitcast<u32>(a);
```
and `b == 50u` is returning false.

From the bug report, and my reading of the spec, this seems to be incorrect. Bitcast appears to be one of the operations that FTZ shouldn't be occuring on.

I have investigated the CTS tests, [bitcast.cache.ts](https://github.com/gpuweb/cts/blob/main/src/webgpu/shader/execution/expression/call/builtin/bitcast.cache.ts), and they are allowing FTZ for acceptable responses. (I am not suprised that this was overlooked, since this is an exception to the general rule of FTZ can happen everywhere).

So the CTS is currently out of spec, which is why Dawn is passing.

I am unsure if this is an intended consequence, thus the CTS and Dawn need to change, or if this is an oversight in the spec.

**Comment by ben-clayton** [comment]
Dawn does not perform any FTZ - this must be happening in the hardware. I think the spec will need to change.

**Comment by alan-baker** [comment]
The current spec just tries to mirror the Vulkan restrictions since D3D restrictions aren't well documented. Vulkan's restrictions are:
>The following instructions must not flush denormalized values: OpConstant, OpConstantComposite, OpSpecConstant, OpSpecConstantComposite, OpLoad, OpStore, OpBitcast, OpPhi, OpSelect, OpFunctionCall, OpReturnValue, OpVectorExtractDynamic, OpVectorInsertDynamic, OpVectorShuffle, OpCompositeConstruct, OpCompositeExtract, OpCompositeInsert, OpCopyMemory, OpCopyObject.

Since the test is failing on Windows (D3D), it seems appropriate to update the spec to allow FTZ on bitcast (conveniently its own chapter now).

**Comment by jimblandy** [comment]
Agreed that we need to loosen the rules for bitcast to f32.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐05‐14-Minutes#should-bitcast-tests-allow-ftz-on-inputsoutputs--issue-4623">WGSL 2024-05-14 Minutes</a></summary>

* Landed [https://github.com/gpuweb/gpuweb/pull/4640](https://github.com/gpuweb/gpuweb/pull/4640) as fix
* DN/AB: This relaxation describes current behavior on Windows drivers.  

</details>
