### ISSUE TITLE
Validation rules for GPUVertexAttributeDescriptor offset

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#463]
[Metal documentation for MTLVertexAttributeDescriptor](https://developer.apple.com/documentation/metal/mtlvertexattributedescriptor/1515785-offset) says "The offset value must be a multiple of 4 bytes."

However, with an offset set to `2` and vertex format set to `uchar21, Metal doesn't raise any error for me. This leads to the question: What are the validation rules for [GPUVertexAttributeDescriptor](https://gpuweb.github.io/gpuweb/#dom-gpuvertexattributedescriptor-offset)?

Note that Dawn already checks that stride is a multiple of 4 (Metal constraint I believe).  
Shall we add this validation rule as well to WebGPU?

**Comment by kvark** [comment]
Forcing the multiple to 4 here seems overly restrictive :/ I checked gfx-rs, and we don't seem to force this alignment on the offset, only on the stride.

**Comment by kainino0x** [comment]
The offset being a multiple of 4 bytes seems highly questionable to me - maybe the documentation could be wrong? It would mean that you can't usefully have <4byte attributes, such as uchar2.

It would also surprise me a little bit if there's a 4-byte alignment restriction on, say, uchar4.

I can't find any restrictions on the alignment of stride *or* offset in Vulkan or OpenGL ES.

**Comment by kainino0x** [comment]
Well, looks like really works this way. Our colleague Alexey from glTF found these constraints too, a while back:
https://github.com/KhronosGroup/glTF-Validator/issues/10#issuecomment-269799846
Vulkan does have it, I just failed to find it.

(I found this by [searching for the exact text](https://www.google.com/search?q=%22The+offset+value+must+be+a+multiple+of+4+bytes.%22) of the Metal documentation page. Which somehow doesn't come up with the Metal documentation page.)

**Comment by Kangz** [comment]
Closing. Validation rules for vertex attribute offsets were added and validated that they work on all backends.
