### ISSUE TITLE
Clarify supported context formats definition

### ISSUE THREAD

**Issue by beaufortfrancois** [gpuweb/gpuweb#4644]
The following definition of [supported context formats](https://gpuweb.github.io/gpuweb/#supported-context-formats) is slightly confusing because of the word "initially". It reads as if this could evolve during the life of the app.

> The supported context formats are a set of GPUTextureFormats that must be supported when specified as a GPUCanvasConfiguration.format regardless of the given GPUCanvasConfiguration.device, initially set to: «"bgra8unorm", "rgba8unorm", "rgba16float"».

May I suggest we remove the word "initially" to avoid confusion?

**Comment by toji** [comment]
"initially set to" is just how most W3C specs initialize values in the spec, but I agree that removing "initially" here helps with spec comprehension without being ambiguous.
