### ISSUE TITLE
Syntax problem in English

### ISSUE THREAD

**Issue by 12ff54e** [gpuweb/gpuweb#4649]
It seems to me that this sentence from section 10.3. const Functions: "Calls to these functions can part of [const-expressions](https://gpuweb.github.io/gpuweb/wgsl/#const-expressions)." should be corrected as "Calls to these functions can **be** part of [const-expressions](https://gpuweb.github.io/gpuweb/wgsl/#const-expressions)."

I'm not a native speaker, apologize if I make any mistake.

**Comment by kainino0x** [comment]
Agreed. Nice catch!
