### ISSUE TITLE
GL_EXT_fragment_shader_barycentric

### ISSUE THREAD

**Issue by alexwennstrom** [gpuweb/gpuweb#4658]
I could not find any information about support for this extension, looks like it is supported in Vulkan, DX, GL, WGL. Anyway I am getting an error when using this extension in glsl when using SPIRV shader module:

#extension GL_EXT_fragment_shader_barycentric and gl_BaryCoordEXT

```
Uncaptured device error: type 1 (Tint SPIR-V reader failure:
Parser: error: unknown SPIR-V builtin: 5286
```

**Comment by Kangz** [comment]
This is a Tint-specific bug and not a WebGPU spec issue, so it should be reported on issues.chromium.org. But in this case Tint just says it doesn't support barycentrics because that's not a thing in WGSL at this point.
