### ISSUE TITLE
Unclear who "consumer" is.

### ISSUE THREAD

**Issue by fyellin** [gpuweb/gpuweb#4660]
The specification includes the following Note:

> NOTE: Since the [entryPoint](https://www.w3.org/TR/webgpu/#dom-gpuprogrammablestage-entrypoint) dictionary member is not required, the consumer of a [GPUProgrammableStage](https://www.w3.org/TR/webgpu/#gpuprogrammablestage) must use the "[get the entry point](https://www.w3.org/TR/webgpu/#abstract-opdef-get-the-entry-point)" algorithm to determine which entry point it refers to.

This is the only occurrence in the specification of the word "consumer". It is unclear and at what point the "get the entry point" algorithm is supposed to be called, and by who or what. 

I note that in the Naga implementation, placing a NULL in this field causes an error.  Because the spec is unclear, I have no idea if this is an error or not.

**Comment by kainino0x** [comment]
This should be clearer. The "consumer" is just other spec text - the text for `createRenderPipeline[Async]`/`createComputePipeline[Async]` - rather than anything about what implementations must do.
