### ISSUE TITLE
Allow all vertex input attributes to be considered OOB if at least one is (in the "process vertices" algorithm)

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#4668]
Vulkan without `robustBufferAccess2` behaves this way and we'd also like to do this in our vertex pulling approach for Metal.

> Further, if any vertex input attribute using a specific vertex input binding is out of bounds, then all vertex input attributes using that vertex input binding for that vertex shader invocation are considered out of bounds.

_from https://github.com/KhronosGroup/Vulkan-Docs/blob/ce03761fd6cc1ab8f54c9f785fffb13f492d7d04/chapters/features.adoc?plain=1#L362-L364_

**Comment by kainino0x** [comment]
Agree this should be allowed. Is there something here that is not already covered by this step in our spec?

> - Optionally (implementation-defined): If attributeOffset + sizeof(attributeDesc.format) > vertexBufferOffset + vertexBufferBindingSize, empty vertexIndexList and stop, cancelling the draw call.

**Comment by teoxoy** [comment]
That optional step requires implementations to "empty vertexIndexList and stop, cancelling the draw call" (which is only doable prior to issuing the draw call).

I think it being a sub-step of the "process vertices" algorithm gives the wrong idea that it could be implemented like that. IMO it should be an "Optionally (implementation-defined) validate vertices" step in the "render" algorithm (the downside being that the spec would need to duplicate some of the prior steps).

**Comment by kainino0x** [comment]
@teoxoy That sounds like just an editorial fix, am I understanding correctly?

**Comment by teoxoy** [comment]
If the intent was to rely on `robustBufferAccess2` on Vulkan then yes, I think this is editorial.

**Comment by kainino0x** [comment]
Yes, we're supposed to be able to take advantage of it when available.

To ask a more specific question - is something wrong in the spec currently or is it just unclear because of how the algorithm is written? ("empty vertexIndexList and stop")

If there's a bug let's put this in M0, otherwise it can be M1 (per yesterday's agreement to put Candidate Recommendation blockers in M0, and my preference to block CR on spec language that's incorrect.)

**Comment by teoxoy** [comment]
> To ask a more specific question - is something wrong in the spec currently or is it just unclear because of how the algorithm is written? ("empty vertexIndexList and stop")

I think there is language missing, my point about the optional step was tangential.

![image](https://github.com/gpuweb/gpuweb/assets/28601907/520744a2-7f8f-4c44-ac20-e82f9d313064)

The spec doesn't currently allow for:

> Further, if any vertex input attribute using a specific vertex input binding is out of bounds, then all vertex input attributes using that vertex input binding for that vertex shader invocation are considered out of bounds.

The OOB behavior in the spec is currently per attribute and doesn't allow all attributes from the buffer to be considered OOB.

**Comment by kainino0x** [comment]
Ahh I see. So it can affect the whole draw call, not just by cancelling it, but also by doing other invalid memory reference behaviors? Did not realize.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-06-26#allow-all-vertex-input-attributes-to-be-considered-oob-if-at-least-one-is-in-the-process-vertices-algorithm-4668">GPU Web WG 2024-06-26 Atlantic-time</a></summary>

* KG: Sounds good.
* CW: Sounds good on our side as well.
* CW: We’ll ask MikeW for concerns
* KN: I think the spec already allows this, and it sounds like what we actually want to do is tweak the way it’s written in the spec.
* KG: We can do the tweak!

</details>

**Comment by mwyrzykowski** [comment]
> The OOB behavior in the spec is currently per attribute and doesn't allow all attributes from the buffer to be considered OOB.

My understanding from the specification as it is written currently is anything which would result in an OOB access permits the implementation to cancel / drop the draw[Indexed/Indirect/IndexedIndirect] call. If we drop the draw call if 1 attribute is out of bounds vs all of them, is there really a change?

What is the proposed new / additional wording?

**Comment by teoxoy** [comment]
> My understanding from the specification as it is written currently is anything which would result in an OOB access permits the implementation to cancel / drop the draw[Indexed/Indirect/IndexedIndirect] call.

That's correct but what is missing is the allowance of not cancelling the draw call since that's the behavior of `robustBufferAccess2` in Vulkan.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-07-17#allow-all-vertex-input-attributes-to-be-considered-oob-if-at-least-one-is-in-the-process-vertices-algorithm-4668">GPU Web WG 2024-07-17 Pacific-time</a></summary>

* MM: seems like a no-brainer to me
* MW: thumbs up
* KG: resolved. Awaiting PR.

</details>
