### ISSUE TITLE
Type inconsistency between drawIndexed and drawIndexedIndirect calls

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4674]
[GPURenderCommandsMixIn.drawIndexed](https://www.w3.org/TR/webgpu/#dom-gpurendercommandsmixin-drawindexed) takes a baseVertex which is of type `long` / `GPUSignedOffset32` but [GPURenderCommandsMixIn.drawIndexedIndirect](https://www.w3.org/TR/webgpu/#dom-gpurendercommandsmixin-drawindexedindirect) says the baseVertex is `unsigned`: 
```
Let baseVertex be an unsigned 32-bit integer read from indirectBuffer at (indirectOffset + 12) bytes.
```

Is there a reason for the inconsistency? `baseVertex` can be negative in Metal, I didn't check other APIs, but it would seem at least `baseVertex` should be signed in both calls or unsigned in both calls.

**Comment by kainino0x** [comment]
I am pretty certain this was just an editorial error. I don't recall ever discussing that it had different behavior.

**Comment by toji** [comment]
In Vulkan the corresponding [`vkCmdDrawIndexed`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdDrawIndexed.html) argument (`vertexOffset`) is signed, while all other arguments are unsigned.  Same goes for D3D12's [`DrawIndexedInstanced`](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-drawindexedinstanced) method.

Metal's [`drawIndexedPrimitives`](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515520-drawindexedprimitives) uses signed values for all of these args.

The structs that [Vulkan](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDrawIndexedIndirectCommand.html), [D3D12](https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_draw_indexed_arguments), and [Metal](https://developer.apple.com/documentation/metal/mtldrawindexedprimitivesindirectarguments) all use for indirect indexed draws all have signed `baseVertex` equivalents and unsigned values for everything else.

So it seems like the error here is that we list the indirect struct as using an unsigned value for this argument.
