### ISSUE TITLE
It should be possible to define an 'override' that evaluates depending on other 'override' constants

### ISSUE THREAD

**Issue by JD31** [gpuweb/gpuweb#4680]
I have the following in my shader code:

```
// defined at pipeline creation level
override iconSizeTexture: f32 = 36.;
override iconSizeScreen:  f32 = 16.;
override msdfPixelRange:  f32 = 4.;

// 'screenPxRange' is computed from above constants,
// unfortunatly we need to set it 'override' as well
// const screenPxRange: f32 = iconSizeScreen / iconSizeTexture * msdfPixelRange; // <-- DOES NOT BUILD
override screenPxRange: f32 = iconSizeScreen / iconSizeTexture * msdfPixelRange; // <-- OK BUT REQUIRES TO COMPUTE THIS OUTSIDE OF THE SHADER CODE
```

In the above code, `screenPxRange` depends on `override` constants thus I would like to define it as `const` in the shader code but that is not accepted:
> const initializer requires a const-expression

If I use `override` instead of `const` then the shader builds BUT the constant evaluates itself according to the init value of the `override` constants it depends to, not according to the values set at pipeline creation time.

The only solution I found then is to define it outside of the shader code and push the value as constant. That's nor very nice in my opinion. This constant only depends on other shader constants and thus I would perfer to express its computation formula inside the shader, not in JavaScript or C++.

What is your opinion ? Is there a workaround I didn't think of ?
Thank you.

**Comment by ben-clayton** [comment]
WGSL has three tiers of expression evaluation:
1. const-expressions: expressions that are evaluated at shader module creation time. Must only be formed from other const-expressions.
2. override-expressions: expressions that are evaluated at pipeline creation time. Can be formed from override-expressions and const-expressions.
3. runtime-expressions: expressions that can be evaluated as late as runtime on the GPU. Can be formed from all of the above.

There are some builtin functions that require a const-expression as arguments, such as the `offset` parameter of texture sampling functions. These cannot use an override-expression or a runtime-expression.

> If I use `override` instead of `const` then the shader builds BUT the constant evaluates itself according to the init value of the `override` constants it depends to, not according to the values set at pipeline creation time.

I'm not quite following here. Please can you elaborate?

**Comment by JD31** [comment]
Sorry if I am not clear.

Let me try to synthetize.
Let consider I have two override constants `A` and `B` that are then defined at pipeline creation time:
```
override A: f32 = 0.;
override B: f32 = 0.;
```

Now let consider that my shader algorithm needs an intermediate variable `C` which can be directly computed from `A` and `B` (let say we want `C = A * B`).
How can I declare `C` in my shader so that is computed **only once**, at pipeline creation ?

**Comment by jrprice** [comment]
> override screenPxRange: f32 = iconSizeScreen / iconSizeTexture * msdfPixelRange;
> ...
> the constant evaluates itself according to the init value of the override constants it depends to, not according to the values set at pipeline creation time.

This sounds like an implementation bug. The calculation should be done using the values provided at pipeline creation time. I recommend opening a bug against the implementation that you observed this behaviour with.

**Comment by ben-clayton** [comment]
> Now let consider that my shader algorithm needs an intermediate variable `C` which can be directly computed from `A` and `B` (let say we want `C = A * B`).
> How can I declare `C` in my shader so that is computed **only once**, at pipeline creation ?

It should be sufficient to add:

```wgsl
override A: f32 = 0.;
override B: f32 = 0.;
override C = A * B;
```

With this you should be able to provide pipeline override values for `A` and `B`, and `C` should be evaluated with the multiplication of the pipeline-override values of `A` and `B`. As @jrprice says, if you're seeing something different, please file a bug against the WebGPU implementation.

**Comment by JD31** [comment]
I think I just understood my problem. A and B are used in the vertex stage. And then I push their constant value in the pipeline definition in the vertex part only. C (which requires A and B to be computed) is used in the fragment stage.
I think I need to push also the constants A and B in the pipeline definition in the fragment part for them to be used for computing C, otherwise their default value are used. That makes sense. Sorry for the mistake.  
(anyway that will improve test code coverage :-)

**Comment by dj2** [comment]
Going to mark this as closed. Thanks a lot for the report, glad you figured out the issue.
