### ISSUE TITLE
Optional field type as rust

### ISSUE THREAD

**Issue by Alphapage** [gpuweb/gpuweb#4692]
Hello,

I can't find a way to define an optional field in a struct or In variable declaration.
There is default feature, but it is not the same as an optional field type.

Do you plan to implement such a feature or do we need to do some kind of workaround ?

Thank you in advance for your answers.

**Comment by Kangz** [comment]
Can you detail more with WGSL code what the requested feature is? Right now it almost seems like a question about the Rust WebGPU API in wgpu-rs but since you added the WGSL tag maybe it's not that.

**Comment by Alphapage** [comment]
I confirm it is all about wgsl syntax.
For example, this struct:
```
struct Modifier {
translation:Option<TranslationParameters>,
rotation:Option<RotationParameters>
}
```
This is an example which comes to my mind: with an optional field, you don't have to dig into parameters.

**Comment by JMS55** [comment]
There is no Option<T> in WGSL. You need to represent it yourself, e.g.:
```rust
struct Modifier {
  translation: TranslationParameters,
  rotation: RotationParameters,
  has_translation: bool,
  has_rotation: bool,
}
```

**Comment by Alphapage** [comment]
Yes, but do you plan to implement such a feature in the future ?

**Comment by Kangz** [comment]
Most likely not directly. In Rust `Option` is part of the standard library, and uses lots of features that WGSL doesn't have like generics. There are discussions about maybe adding generics one day but that's very far in the future. Tentatively closing this as not planned.

**Comment by Alphapage** [comment]
`ptr<...>` acts like a generic, so I was expecting `option<...>` could be a valuable feature.
I hope this will be the preferred option ;-) instead of NULL.
