### ISSUE TITLE
GPUDeviceLostReason should contain more values

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4695]
Currently [GPUDeviceLostReason](https://www.w3.org/TR/webgpu/#fatal-errors) contains the values "unknown" and "destroyed".

If we intend to use device lost to handle cases such as:
https://github.com/gpuweb/gpuweb/issues/4659
https://github.com/gpuweb/gpuweb/issues/4622

then using "destroyed" or "unknown" does not seem to capture the reason.

I would propose the following:
```
enum GPUDeviceLostReason {
    "unknown",
    "destroyed",
    "out-of-memory",
    "indefinite-execution",
};
```

**Comment by kainino0x** [comment]
`GPUDeviceLostInfo.message` can already communicate human-readable information about the reason for device loss. I prefer to keep the enum scoped to information that application logic might actually use to decide what to do at runtime.

**Comment by kainino0x** [comment]
(and I don't think they're likely to use this at runtime. If I thought they were, I'd prefer "out-of-memory" to come directly from `createCommandEncoder()` and "indefinite-execution" to come directly from `submit()`, though the latter may not be feasible.)

**Comment by mwyrzykowski** [comment]
When a website accidentally passes -1 to the vertex count of a draw command, we lose the device, as execution will take too long. This occurred in practice by someone writing a test and -1 was passed unintentionally. 

We can place a useful error in [GPUDeviceLostInfo.message](https://www.w3.org/TR/webgpu/#dom-gpudevicelostinfo-message) but it seems falling back to `GPUDeviceLostReason.unknown` is not ideal.

Or would `GPUDeviceLostReason.destroyed` be appropriate here? I initially considered using that, except I think `destroyed` based on the example in https://www.w3.org/TR/webgpu/#initialization-examples should be reserved for when the website destroys the device.

**Comment by kainino0x** [comment]
> When a website accidentally passes -1 to the vertex count of a draw command, we lose the device, as execution will take too long. This occurred in practice by someone writing a test and -1 was passed unintentionally.

But what would the _application_ do in response to that, other than reinitialize in the same way as any other device loss? IMO a case like this is either a plain application bug, or it's some user input that the application should be responsible for checking before they get to the point of asking the GPU to do something nonsensical. Either way it requires the _developer_ to fix the application code.

(aside: I assume you're talking about an indirect draw call that ended up with a vertexCount of `0xFFFFFFFF`; `[EnforceRange]` is supposed to throw a TypeError if you do `draw(-1)`.)

> I think `destroyed` based on the example in https://www.w3.org/TR/webgpu/#initialization-examples should be reserved for when the website destroys the device.

That's correct.

**Comment by mwyrzykowski** [comment]
We can certainly pass “unknown” in this case, I thought it wasn’t so descriptive, given we do know why the device has become lost. 

I certainly don’t think it’s a major issue by any means, just the name “unknown” as the reason seems misnamed if used in this context.

**Comment by kainino0x** [comment]
Fair, we could have come up with a better name when we were replacing `undefined` with an enum value (maybe `"unspecified"`). But I think it suffices; from the perspective of the application code, the reason is indeed "unknown".

**Comment by mwyrzykowski** [comment]
Sounds good to me, we will use `unknown` for these cases, I think we can close
