### ISSUE TITLE
Support for 3D Textures with ASTC

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#4701]
While adding 3D texture support for BC compressed formats, we've found that ASTC has reasonable support but is not guaranteed: https://github.com/gpuweb/gpuweb/issues/3183#issuecomment-2141178318

Since query support is possible and coverage across backends is wide, 3D support for ASTC formats can be a sub-feature extension.

I'll add more details as a comment to this issue, creating now to track.

**Comment by mehmetoguzderin** [comment]
Just to be clear this issue does not cover ETC2 (and I suspect ETC2 for sliced 3D won't be a subject of discussion at any point actually). During our investigations, we found that ETC2 for Sliced 3D almost does not exist (my regression demo was also targeting ASTC but not ETC2): https://github.com/gpuweb/gpuweb/issues/3183#issuecomment-2141178318

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-07-10#astc-compressed-for-sliced-3d-as-extension-4701">GPU Web WG 2024-07-10 Atlantic-time</a></summary>

* CW: This one should have easy consensus. We should just do it.
* KG, MW, others: 👍
* OD: I volunteer to PR it.

</details>
