### ISSUE TITLE
Consider moving sliced 3D compressed BC texture to an extension.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#4705]
Similarly to what is being done for ASTC at https://github.com/gpuweb/gpuweb/issues/4701. We added support for 3D-sliced compressed textures in core but later realized that support was not universal except for BC (when BC is available). Because there is no guarantee that an adapter supports any 3D-sliced compression format, I think this functionality should be moved to an extension.

**Comment by teoxoy** [comment]
With the changes done in https://github.com/gpuweb/gpuweb/pull/4685 the validation is implemented in a generic way; enabling `texture-compression-bc` will effectively also allow you to use the formats for 3D textures. What would be the benefit of having an extra extension for this?

**Comment by Kangz** [comment]
There is an expectation that `texture-compression-bc/astc/etc` are all extremely similar extensions just with different formats made available. That BC also gets sliced 3D means that developers on desktop platforms with BC support will assume some form of sliced 3D is guaranteed by WebGPU (like we guarantee at least one compressed texture extension) when it isn't the case.

**Comment by mehmetoguzderin** [comment]
Is there any underlying API that does not guarantee sliced 3D with BC, given the WebGPU targets? For ASTC, there is a lack of universality for target devices, but I was curious how we differentiate among targets as to whether they support sliced 3D since all targets' baseline already guarantees it.

**Comment by mehmetoguzderin** [comment]
Summary of guarantees: https://github.com/gpuweb/gpuweb/issues/3183#issuecomment-2141178318

**Comment by Kangz** [comment]
> Is there any underlying API that does not guarantee sliced 3D with BC, given the WebGPU targets?

My understanding is that your investigation shows that it works across all the APIs. But that's not the issue here, but more than developers will get confused that sliced 3D is part of `texture-compression-bc` and not the others, which is confusing due to the way that the WebGPU spec guarantees that there is at least one texture compression extension (that should all look the same).

**Comment by mehmetoguzderin** [comment]
Now I better understand the suggestion, thank you. But I think a feature that's always guaranteed with another extension that you always need for the subfeature just for consistency might do the opposite effect: if need is ASTC and trying sliced 3D, that's the case requires consciousness and request than all else. Just like how API does not have "*-renderable" just for consistency but just "rg11b10ufloat-renderable".

**Comment by Kangz** [comment]
To rephrase the concern, "2D texture compression" is in core WebGPU because we guarantee "BC || (ETC2 && ASTC)". So these extensions are a bit special in that sense. I'd like to avoid developers assuming "sliced 3D texture compression" is core in the same way. Though ultimately this is small concern so if the group decides to ignore it that's totally fine.

Where it is different from renderability is that there is no similar special extensions mix that are guaranteed to be there in core WebGPU for renderability. There is just "core", and "an extension that might not be present".

**Comment by kainino0x** [comment]
Personally I think it's OK for the features to be a little asymmetric, but I see the concern. Here's a scenario I can think of where this would be a problem, so it depends how much of a problem we think it is:

- Developer adds support for both BC and ASTC and tests desktop and mobile.
- Developer adds some feature that starts using sliced compressed textures. Their code is structured in a way where they don't need to think about the specific format (plausible) so they forget to test on mobile.
- Now that feature is broken on mobile. They can fix this on devices that support sliced ASTC by enabling the feature, but it's still broken on other devices. They'll have to write a workaround path or switch to not use sliced compressed textures at all.
  - The error message should be super clear about why it's failing so it shouldn't be painful to debug, but if they had realized the limitation they might not have bothered to use sliced compressed textures in the first place.

**Comment by kainino0x** [comment]
Downside of splitting sliced BC into a separate extension is, people would not be able to immediately tell that it is available on every system that has non-sliced BC, so they might avoid it unnecessarily or write a fallback path for BC-without-sliced that turns out to never be used.

**Comment by mehmetoguzderin** [comment]
Thinking about this during the meeting, I think the spec could be also a bit more explicit that only for dimension 2d there is a guarantee of either BC or ASTC/ETC2, and not make an extension nor rename for clarity about sliced 3d (for BC case, for ASTC, we'll need astc sliced 3D as it is not universal among target devices). This would also help clarify that these formats simply don't work for dimension 1d at all. Thank you for your consideration.

**Comment by kainino0x** [comment]
Three options we considered in the meeting, plus one, and my thoughts on each:

- "original": `-astc` (2d only), `-astc-sliced-3d`, `-etc2` (2d only), `-bc` (2d and sliced 3d)
  - Naming clarity 2/5, don't explain the implicit bundling at all.
- "mirror": have each "base" feature provide exactly the same capabilities: `-astc` (2d only), `-astc-sliced-3d`, `-etc2` (2d only), `-bc` (2d only), `-bc-sliced-3d`
  - Naming clarity 4/5.
  - Has the benefit that if you have compressed data in two formats (say astc and bc) and otherwise use them exactly the same way in your code (likely IMO), you can develop on BC without risk of writing code that won't work on ASTC. Downside is that we have two features that are always bundled together.
- "rename": `-astc-2d`, `-etc2-2d`, `-bc` (2d and sliced 3d)
  - Naming clarity 3/5.
  - Possible to do with deprecation and removal.
  - Doesn't have the nice property of "mirror".
- "rename+mirror": `-astc-2d`, `-etc-2d`, `-bc-2d`, `-bc-sliced-3d`
  - Naming clarity 5/5.
  - Has the nice property of "mirror" but doesn't seem worth the effort.

I prefer "mirror".

**Comment by magcius** [comment]
Considering that ASTC has 3D texture formats while BC doesn't have any, I don't think the asymmetry is necessarily wrong. It should be expected that different texture formats have different featuresets -- ASTC has optional sliced 3D and real 3D, BC has mandatory sliced 3D and no real 3D.

As long as it's clearly explained and mentioned in the spec (and the CTS tests for sliced 3d when testing BC, to ensure compatibility) I think we're safe here, and I see no reason to move BC sliced-3d to an extension.

**Comment by kainino0x** [comment]
> ASTC has optional sliced 3D and real 3D

FWIW the real-3D (WxHxD) formats [don't exist](https://github.com/gpuweb/gpuweb/issues/3183#issuecomment-2026501243) in any of Vulkan/D3D12/Metal, and anyway if we ever added them they would be a separate third ASTC feature (astc, astc-sliced-3d, astc-real-3d). The "core" ASTC feature is always going to have exactly the same capabilities as the ETC2 feature so it isn't that far off to adjust BC to match.

**Comment by magcius** [comment]
Yes, I'm aware that 3D ASTC is purely a hypothetical feature (as are many things with ASTC; I believe only Apple supports the HDR modes currently) but that doesn't change my conclusion :). Different texture formats have different featuresets, that seems like the normal state of affairs to me.

**Comment by jimblandy** [comment]
Mozilla is of the opinion that Kai's "mirror" is the best approach. To address the downside of implying that bc without sliced 3d is a possibility, the spec can simply have a note explaining that `bc` always implies `bc-sliced-3d`.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-07-10#consider-moving-sliced-3d-compressed-bc-texture-to-an-extension-4705">GPU Web WG 2024-07-10 Atlantic-time</a></summary>

* CW: Seems … I’m not 100% sure but it seems KN has another approach that satisfies most people?
* KN: Based on all the discussions we had, I wrote down some options for how we could design this.
* KN: The ASTC, BC, and ETC2 extensions would provide the same functionality, and the separate sliced-3d extensions for ASTC and BC. We would do this so the different formats mirror each other exactly in how they’re sliced, even though BC always supports sliced-3D.
* KN: If you have BC, you’ll always have bc-sliced-3d
* CW: Is it a guarantee the extensions come together?
* KN: Yes.
* JB: Mozilla is OK with it
* OD: I believe the asymmetry is given for texture format, whether it be different block sizes, different color profiles. But if it’s a consensus to see this as a better developer experience to expose this as a similarly-named extension as BC, I think it is a good way to move forward.
* CW: Thank you.
* CW: Fixing it goes in M0?
* Yes.
* OD: I volunteer to PR the change.

</details>
