### ISSUE TITLE
bgra8unorm storage textures without bgra8unorm-storage, should generate WGSL error?

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4711]
if you have

    @group(0) @binding(0) var tex: texture_storage_2d<bgra8unorm, read>;

But you have **not** requested the `'bgra8unorm-storage'` feature, you don't get WGSL error at shader module creation time.

This seems inconsistent with the idea that in compat you do WGSL error for these (#4568):

    @group(0) @binding(0) var tex: texture_storage_2d<rg32float, read>;
    @group(0) @binding(1) var tex: texture_storage_2d<rg32sint, read>;
    @group(0) @binding(2) var tex: texture_storage_2d<rg32uint, read>;

related to #4728

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-06-26#bgra8unorm-storage-textures-without-bgra8unorm-storage-should-generate-wgsl-error-4711">GPU Web WG 2024-06-26 Atlantic-time</a></summary>

* CW: Which kind of error should we use? Compat mode uses WGSL error
* KG: Having the feature disabled on the device should make the device behave very similarly to what would happen if the implementation had no idea that this would be spec’ed. In a world where you have an implementation that this is possible, is this an error at shader compilation time? If it is, then if you do know what it is but you just disable it, it should be that way too.
* KN: Yes.
* CW: We should take this, then
* KN: It’s not just compat, too
* GT: It’s a breaking change
* CW: An incredibly minor one. It’s a spec bug.
* GT: Okay. I would also like to see consistency. It’s possible that Unity already has their stuff and expects us to pass. It used to be that you could have a shader module with 2 entry points and you could pick at runtime which one to use. But now it will be an error. We could check if they break
* KG: If it never worked in multiple implementations, it’s not much of a backwards compatibility issue from the perspective of standardization
* CW: We can check with Unity
* KN: (pretty sure) this is the only place where we allowed you to write it into the shader and then not use it, I think it will not be a problem. I would be a little surprised if Unity would rely on it. Most applications generate their shader based on what they end up needing.

</details>

**Comment by kainino0x** [comment]
This is all in one big ball with #4728 and #4568 which is not resolved anymore. Removing `api resolved` since I'm burning down PRs for resolved stuff.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐08‐27-Minutes#bgra8unorm-storage-textures-without-bgra8unorm-storage-should-generate-wgsl-error-4711">WGSL 2024-08-27 Minutes</a></summary>

* Corentin: Please confirm the resolution is that this is a pipeline-time error, similar to [Should invalid combinations of storage texture formats and access generate a WGSL error #4728](https://github.com/gpuweb/gpuweb/issues/4728)
* KG: Yes, agree.d
* DN: Yes, pipeline error.
* AB: Yes. We discussed it in this meeting, and agreed it was pipeline error.
* **Confirmed**

</details>

**Comment by Kangz** [comment]
I checked that the API spec validates this:

 - For explicit layouts, BGL validation will forbid using the formats are storage without the extension.
 - For implicit layouts, the spec defers validation to createBindGroupLayout and ends up in the explicit layout case.
