### ISSUE TITLE
Mistake in recursive decent parser definition?

### ISSUE THREAD

**Issue by timokoesters** [gpuweb/gpuweb#4713]
I'm following the recursive decent parser definition from here: https://gpuweb.github.io/gpuweb/wgsl/#recursive-descent-syntax-expression
But I think there may be a mistake: The `expression` can never be for example "uniform", because  `unary_expression`s must always be followed up with a `bitwise_expression.post.unary_expression`, which cannot be empty, so `1 & 1` is allowed, but not just `1`.

I've asked this in the wgpu Matrix room and the response was:

> There maybe a bug in the creation, that whole section is non-normative, so I'd suggest looking at the embedded grammer in the spec if you find some thing weird. In this case:  expression -> relational_expression -> shift_expression -> additive_expression -> multiplicative_expression ->unary_expression

> from the recursive descent, Tint basically does this, when we get to `shift_expression.post.unary_expression`: we go into a multiplicative expression for simplicity sake and in there if there is no operator we return the `lhs`. https://dawn.googlesource.com/dawn/+/refs/heads/main/src/tint/lang/wgsl/reader/parser/parser.cc#2259

**Comment by dneto0** [comment]
Sorry about that.

I guess there's a bug in the code that transforms the grammer to be more recursive-friendly.

The code that does the transformation is invoked [here](https://github.com/gpuweb/gpuweb/blob/main/wgsl/tools/analyze/lalr.py#L104)
It's likely in [left_refactor](https://github.com/gpuweb/gpuweb/blob/main/wgsl/tools/analyze/Grammar.py#L2227) or [epsilon_refactor](https://github.com/gpuweb/gpuweb/blob/main/wgsl/tools/analyze/Grammar.py#L2376).

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐06‐25-Minutes#mistake-in-recursive-decent-parser-definition--issue-4713">WGSL 2024-06-25 Minutes</a></summary>

* DN: Probably right.  This is likely a bug in the grammar analyzer code. **That’s mine**.
* 

</details>

**Comment by dneto0** [comment]
I think the analysis is mistaken.

To derive 'uniform' as an _expression_:

    expression --> unary_expression relational_expression.post.unary_expression

      unary_expression --> primary_expression component_or_swizzle_specifier ?
        primary_expression --> ident template_elaborated_ident.post.ident
          ident --> 'uniform'
          template_elaborated_ident.post.ident -> ( _template_args_start template_arg_expression ( ',' expression )* ',' ? _template_args_end )?
                                               -> ...empty...
        component_or_swizzle_specifier ? --> ...empty...

      relational_expression.post.unary_expression --> shift_expression.post.unary_expression
        shift_expression.post.unary_expression --> ( multiplicative_operator unary_expression )* ( additive_operator unary_expression ( multiplicative_operator unary_expression )* )*
                                               --> ..empty..


In the transformation to the recursive descent form, all the epsilon productions
end up absorbed into ? or * regexp operators.

So I think there is no bug here.

Closing. Please reopen if you think I've erred.

**Comment by dj2** [comment]
Ah, I missed the final `*` which lets `shift_expression.post.unary_expression` expand to nothing.

**Comment by timokoesters** [comment]
@dj2 I believe your comment means that we should reopen this issue. Is this something easy enough for me to contribute or do you want to take care of it?

**Comment by dj2** [comment]
No, my comment means the spec is correct. I mis-read the grammar line and missed the trailing `*` when reading.
