### ISSUE TITLE
Is there some plan for Ray Tracing?

### ISSUE THREAD

**Issue by itsyom** [gpuweb/gpuweb#477]
hey guys :)
I want to know is there some plane for Ray Tracing?

**Comment by Kangz** [comment]
Hey @itsyom. There are not plan for ray-tracing for the forseeable future because WebGPU is meant to be extremely portable and ray-tracing isn't mature yet and is implemented only by a single hardware vendor for now.

**Comment by litherum** [comment]
> is implemented only by a single hardware vendor

This isn't actually true.

- [Metal Ray Tracing](https://developer.apple.com/documentation/metalperformanceshaders/metal_for_accelerating_ray_tracing?language=objc)
- [Direct3D 12 Ray Tracing](https://docs.microsoft.com/en-us/windows/win32/direct3d12/direct3d-12-raytracing)
- [Vulkan Ray Tracing](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_NV_ray_tracing)
- [AMD Ray Tracing](https://gpuopen.com/gaming-product/radeon-rays/)
- [Nvidia Ray Tracing](https://www.developer.nvidia.com/optix)
- [Intel Ray Tracing](https://www.embree.org)
- [Other Intel Ray Tracing](http://www.ospray.org)

**Comment by kvark** [comment]
@litherum that's a great list! To be fair, most of these links are for *user space* ray tracing, which people are free to build on top of WebGPU whenever they want. If we are talking about the hardware support, then currently it appears that only NVidia exposes anything (note: the "Vulkan Ray Tracing" is an NV extension).
