### ISSUE TITLE
On device loss, should mapAsync throw AbortError instead of OperationError?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4774]
Currently, if the device is lost _naturally_ (not destroyed), a pending `mapAsync()` promise will reject with `OperationError`.

If it is destroyed, it rejects with `AbortError` (destroying the device implicitly unmaps all buffers, which cancel pending maps with `unmap()`, which produces `AbortError`).

This is (1) kind of self-inconsistent and (2) inconsistent with our other usages of `OperationError` where I believe it _always_ means there was some incorrect use of the API. This is not an incorrect use of the API.

It's unfortunately not easy to test because it relies on natural device loss (see https://github.com/gpuweb/gpuweb/issues/4177 which would fix this), and we haven't tried to test it. Chromium [currently implements this incorrectly](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/wire/client/Buffer.cpp;l=307;drc=db23570a445da99444dfedd44cbbc17572ffa90c) and [rejects](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/webgpu/gpu_buffer.cc;l=384;drc=45467467790b2bf11d3f514303113278c901f1f6) with `AbortError` in both cases.

I'm labeling this `Milestone 0` and `potentially breaking`, though the chances that anyone is relying on this behavior seems extremely small.

EDIT: s/throw/reject/

**Comment by kdashg** [comment]
Related: #4177

**Comment by jimblandy** [comment]
Maybe this is obvious to everyone else, but just to be clear, we're only talking about what the mapAsync promise is rejected with - not an immediate error thrown synchronously by the call to mapAsync.

**Comment by jimblandy** [comment]
MDN page that describes these codes: https://developer.mozilla.org/en-US/docs/Web/API/DOMException

**Comment by jimblandy** [comment]
The spec currently rejects the `mapAsync` promise with `AbortError` if the buffer is destroyed while the map request is pending.

**Comment by kdashg** [comment]
Mozilla likes AbortError for "natural" device lost, for symmetry with destruction and also because that feels like the more accurate error flavor. (though we don't think it matters a ton, since the message that the Error carries is more important than whatever flavor we decide is "most correct")

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-07-24#m0-on-device-loss-should-mapasync-throw-aborterror-instead-of-operationerror-4774">GPU Web WG 2024-07-24 Atlantic-time</a></summary>

* CW: mostly agreement already
* KN: think we should do this. Technically a breaking change, but device loss is rare.
* KG: agree
* MW: sounds fine
* **(consensus)**

</details>
