### ISSUE TITLE
array_index out of bounds behavior is not specified for texture builtins

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4782]
I might have missed it but at a glance it doesn't appear that the behavior of `array_index` being `< 0` or `>= arrayLayerCount` for the given view is specified for `textureSample???` and `textureGather???`

For `textureLoad` it is specified as

> If the logical texel address is invalid, the built-in function returns one of:
>
> * The data for some texel within bounds of the texture
> * A vector (0,0,0,0) or (0,0,0,1) of the appropriate type for non-depth textures
> * 0.0 for depth textures

For texture builtins that use samplers, only `array_index` can be out of bounds. Should the behavior be the same as for `textureLoad`, or is it undefined or did I just miss where it is detailed.

It seems kind of indirectly covered by https://gpuweb.github.io/gpuweb/#security-shader but should it be spelled out in the WGSL spec?

**Comment by magcius** [comment]
Shouldn't the sampler's `addressModeW` specify the behavior here?

**Comment by greggman** [comment]
It doesn't appear that `addressModeW` affects `array_index`.

**Comment by greggman** [comment]
GLSL ES 3.1 section 8.9 seems to say it's clamped

> For Array forms, the array layer used will be
>
> >  max(0, min(d − 1, floor(layer + 0.5) ))
>
> where d is the depth of the texture array...

Vulkan seems to have similar wording in section 16.6.1 (it's not entire clear if that's relevant)

> The layer index l is computed as:
>
> > l = clamp(RNE(a), 0, layerCount - 1) + baseArrayLayer
>
> where `layerCount` is the number of layers in the image subresource range of the image view, `baseArrayLayer` is the first layer from the subresource range.

I didn't find any definition in Metal or DX11 or DX12 but I don't know exactly where to look.

I wrote a test [here](https://jsgist.org/?src=e063357b32abc2976202477ff0751d2d)

It just makes 2x2x2 texture who's contents is

```
texture layer: 0
   red, green
   blue, yellow
texture layer: 1
   cyan, magenta
   orange, gray
```

and calls

```
@group(0) @binding(0) var t: texture_2d_array<f32>;
@group(0) @binding(1) var s: sampler;
@group(0) @binding(2) var<storage, read_write> result: array<vec4f>;

@compute @workgroup_size(1) fn cs() {
  result[0] = textureSampleLevel(t, s, vec2f(0), i32(0), 0);
  result[1] = textureSampleLevel(t, s, vec2f(0), i32(-2), 0);
  result[2] = textureSampleLevel(t, s, vec2f(0), i32(-1), 0);
  result[3] = textureSampleLevel(t, s, vec2f(0), i32(21), 0);
  result[4] = textureSampleLevel(t, s, vec2f(0), i32(22), 0);
}
```

Result on M1 Mac, Intel Mac, and AMD Mac is

```
0: layer(0), red
1: layer(-2), cyan
2: layer(-1), cyan
3: layer(21), cyan
4: layer(22), cyan
```

result on NVidia 2070 Windows is

```
0: layer(0), red
1: layer(-2), red
2: layer(-1), red
3: layer(21), cyan
4: layer(22), cyan
```

So maybe a similar definition to `textureLoad`'s out of bounds behavior is fine?

**Comment by alan-baker** [comment]
I think it would make sense to add the text to the WGSL spec.

**Comment by jimblandy** [comment]
`textureLoad`'s specification permits clamping, or returning a zero value. For `textureSample`, it seems that all the implementations and specifications require or perform clamping. It would be nice for portability's sake to narrow down the range of permissible behaviors, so perhaps `textureSample`'s specification could simply require clamping of invalid array indices.

**Comment by greggman** [comment]
Checking the MSL docs, there is no `i32` version of sampling an 2d-array. There is only `uint`

```
Tv sample(sampler s, float2 coord, uint array,
 int2 offset = int2(0)) const
Tv sample(sampler s, float2 coord, uint array, lod_options options,
 int2 offset = int2(0)) const
Tv sample(sampler s, float2 coord, uint array, bias bias_options,
 min_lod_clamp min_lod_clamp_options,
 int2 offset = int2(0)) const
Tv sample(sampler s, float2 coord, uint array,
  gradient2d grad_options,
  min_lod_clamp min_lod_clamp_options,
  int2 offset = int2(0)) const
```

So that's why it's clamping to the last index for negative values.


One solution to make it portable would be to require all backends to emit unsigned code regardless of the sign in the WGSL code. Then they would all clamp to the last layer for negative values. 

Another solution would be to emit manual clamping code in Metal. It seems like that would be less performant.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2024‐07‐30-Minutes#array_index-out-of-bounds-behavior-is-not-specified-for-texture-builtins--issue-4782">WGSL 2024-07-30 Minutes</a></summary>

* PR: [Clarify array layer OOB for texture sampling #4792](https://github.com/gpuweb/gpuweb/pull/4792)
* AB: Our Metal backend will clamp at top-end. Array index will be clamped to 0..numLayers-1
    * For signed case, Tint will need to add the clamp to get to the lower end, rather than passing signed int to the Metal builtin which only takes uint, and hence falls back to usual arithmetic expression.
* JB: Does that permit median-of-three clamping? 
* AB: negative-to-zero, and anything larger to the last layer.
* JB: good to performantly require a single behaviour.
* AB: Given you’re about to touch memory, a max operation doesn’t seem expensive. (Metal is already clamping at the top end, so the only operation a WebGPU implementation would need to add is a max(0, …) to handle negative values.)
* **_CONSENSUS: clamp_**
* 

</details>

**Comment by jrprice** [comment]
The spec has already been changed, which is why this issue was closed.
