### ISSUE TITLE
remove `sourceMap` from `GPUShaderModuleDescriptor`

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4808]
Currently, `GPUShaderModuleDescriptor` is defined as

> dictionary GPUShaderModuleDescriptor : [GPUObjectDescriptorBase](https://gpuweb.github.io/gpuweb/#dictdef-gpuobjectdescriptorbase) {
&nbsp;&nbsp;&nbsp;&nbsp;    required [USVString](https://webidl.spec.whatwg.org/#idl-USVString) [code](https://gpuweb.github.io/gpuweb/#dom-gpushadermoduledescriptor-code);
&nbsp;&nbsp;&nbsp;&nbsp;    [object](https://webidl.spec.whatwg.org/#idl-object) [sourceMap](https://gpuweb.github.io/gpuweb/#dom-gpushadermoduledescriptor-sourcemap);
&nbsp;&nbsp;&nbsp;&nbsp;    [sequence](https://webidl.spec.whatwg.org/#idl-sequence)<[GPUShaderModuleCompilationHint](https://gpuweb.github.io/gpuweb/#dictdef-gpushadermodulecompilationhint)> [compilationHints](https://gpuweb.github.io/gpuweb/#dom-gpushadermoduledescriptor-compilationhints) = [];
};`

I started to write a library to try to use `sourceMap` and I'm starting to think maybe this property is the wrong solution.

The problem is, this property is effectively asking for a loaded and parsed sourceMap ***before knowing that we actually need the sourceMap***.

In other words, you start with this synchronous code

```js
const module = device.createShaderModule({code});
const pipeline = device.createComputePipeline({compute: {module}, ...});
```

You decide to add a sourceMap. This is now required

```js
const response = await fetch('path/to/source/map');
const sourceMap = await response.json();

const module = device.createShaderModule({code, sourceMap});
const pipeline = device.createComputePipeline({compute: {module}, ...});
```

Your code is no longer synchronous and has to be refactored. Of course, you could try to bundle your source maps into your build but that's certainly not the precedent of source maps from JavaScript.

Instead, I'd like to suggest that WebGPU should follow JavaScript's lead here and just use a sourcemap comment in the WGSL

```wgsl
//# sourceMappingURL=http://example.com/path/to/your/sourcemap.map
```

The advantage to this way is the implementation (or library, debugger, etc) is free to load the source maps on demand.

Example:

```
function createShaderModule(
    device: GPUDevice,
    desc: GPUShaderModuleDescriptor,
): GPUShaderModule {
  device.pushErrorScope('validation');
  const {code} = desc; // save the code
  const module = device.createShaderModule({code});
  device.popErrorScope().then(error => handleShaderModuleError(error, module, code));
  return module;
}

async function handleShaderModuleError(error, module, code) {
  if (!error) return;

  // scan the code for a source map
  let sourceMap;
  const m = /^\/\/# sourceMappingURL=(.*?)$/m.exec(code);
  if (m) {
     const url = m[1]; // (*)
     try {
       sourceMap = await(await fetch(url).json();
     } catch (e) {
       console.warn('could not load sourceMap from:', url, e);
     }
  }

  const info = await module.getCompilationInfo();
  
  // use sourceMap here, if available,
}
```

With this design, usage still appears synchronous

```js
const module = createShaderModule(device, {code});
const pipeline = device.createComputePipeline({compute: {module}, ...});
```

And, the source map is only loaded, if there was an error. (less memory, less bandwidth, less startup time, ....)

WebGPU implemetations are still free to support or not support source maps. It's just that moving them to comments, the same as JavaScript, gives the implementation more flexibility in when to load them.

Note that an implementation that wants to generate a sourceMap at runtime would still be free to do so with `//# sourceMappingURL=data:,...json....` or `//# sourceMappingURL=data:text/plain;base64,....==`

**Comment by kainino0x** [comment]
This proposal seems to make sense to me.
I think it can be Milestone 1 though because removing the dictionary member should not be a breaking change.

**Comment by mwyrzykowski** [comment]
Agreed seems like we can remove `sourceMap` fro, `GPUShaderModuleDescriptor`

**Comment by kdashg** [comment]
It would be kinda cool to have some fetchSourceMap: async function() -> souceMap, but URL sounds like the main solution, and the one JS uses is a good reason.

**Comment by kainino0x** [comment]
Filed #4844 for reintroducing source maps.

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-08-28#remove-sourcemap-from-gpushadermoduledescriptor-4808">GPU Web WG 2024-08-28 Atlantic-time</a></summary>

    * CW: suggest we figure this out in M2. Nobody's implementing this yet.
    * MM: sure, as long as applications using this don't break in the bindings layer.
    * (more discussion)
    * **Consensus to remove it for M0**

</details>
