### ISSUE TITLE
Missing dynamic offset validation in "Validate encoder bind groups"

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#4811]
The dynamic offset needs to be subtracted from the "effective buffer binding size" in the "Validate encoder bind groups" validation function.

We do something similar in the "bound buffer ranges" section (used by the aliasing validation).

Found while looking at https://github.com/gfx-rs/wgpu/issues/6093.

**Comment by Kangz** [comment]
This seems like just a bug in the spec. Taking the dynamic offset sounds good. @mwyrzykowski are you ok with this change? So we can resolve offline.

**Comment by mwyrzykowski** [comment]
Oh certainly, I overlooked this in the specification but explains why we found https://bugs.webkit.org/show_bug.cgi?id=275074 - I thought I just missed a validation part in the spec

**Comment by Kangz** [comment]
Great, marking as "api resolved" then!

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-08-28#missing-dynamic-offset-validation-in-validate-encoder-bind-groups-4811">GPU Web WG 2024-08-28 Atlantic-time</a></summary>

    * **Resolved to fix the bug, Teo to make a PR**

</details>
