### ISSUE TITLE
`textureGather` with integer texture formats doesn't work on AMD devices

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4841]
Posting this to see if we want to consider it just an AMD bug or spec change worthy (like say, disallowing uint/sint texture formats and textureGather with cubemaps

The setup is. Given an 8x8 cube map (so 6 layers). The texture coordinate is `-0.7084864819326223, 0.705718956612574, 0.002767525320049306`

That coordinate gets converted to face index and a texel. The face index is (1) so the (-x face). The texel coordinate is `4.016, 0.016`.  

x = 4.016 means it's just past the 5th texel in X  (0-1 is the first texel, 1-2 is the second texel, .... 4-5 is the 4th texel). 

y = 0.016 means it's just under the top edge (or above the bottom depending on your POV)

```
              x = 4.016
                 |
                 V
+---+---+---+---+---+---+---+---+ ◢___ y = 0.016 
|   |   |   |   |   |   |   |   | 
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
```

Given that the texel coordinate is in the top left corner of the texel, this square represents the texels that should be "gathered"

```
            ╔═══╦═══╗
            ║ A ║ B ║
┌───┬───┬───╫═══╬═══╫───┬───┬───┐
│   │   │   ║ R ║ G ║   │   │   │
├───┼───┼───╬═══╬═══╬───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
└───┴───┴───┴───┴───┴───┴───┴───┘
```

A and B are from a different face of the cube. This is what I see on several GPUs. 

But on AMD (Mac and Linux, don't have access to AMD windows) I see this

```
┌───┬───┬───╦═══╦═══╦───┬───┬───┐
│   │   │   ║ A ║ B ║   │   │   │
├───┼───┼───╬═══╬═══╬───┼───┼───┤
│   │   │   ║ R ║ G ║   │   │   │
├───┼───┼───╬═══╬═══╬───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
├───┼───┼───┼───┼───┼───┼───┼───┤
│   │   │   │   │   │   │   │   │
└───┴───┴───┴───┴───┴───┴───┴───┘
```

In order for that to happen, y would have to be >= 0.5 but y is 0.016

Also, this issue happens for integer texture formats, not floating point or unorm formats.

You can test here: https://jsgist.org/?src=f32cd47fd0cb0e8330c1c54a44cc9f74

Correct results look like this

```
cube coord : -0.7084864819326223, 0.705718956612574, 0.002767525320049306
3d coord   : 0.501953125, 0.0019531249999992784, 0.25
texel coord: 4.016, 0.016  layer: 1 face: -x
result[0] = 4099,4100,8448,8384
R gather = F1:X3:Y0, F1:X4:Y0, F2:X0:Y4, F2:X0:Y3
+----+----+----+----+----+----+----+----+
|    |    |    | R1 | G1 |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
| A2 |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
| B2 |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

R1 = red component contained texel(3,0) from layer 1 (-x face)
A2 = alpha component contained texel(0,3) from layer 2 (+y face)

Anything else is bad. 

On Linux AMD I see this

```
amd gcn-4
cube coord : -0.7084864819326223, 0.705718956612574, 0.002767525320049306
3d coord   : 0.501953125, 0.0019531249999992784, 0.25
texel coord: 4.016, 0.016  layer: 1 face: -x
result[0] = 4163,4164,4100,4099
R gather = F1:X3:Y1, F1:X4:Y1, F1:X4:Y0, F1:X3:Y0
+----+----+----+----+----+----+----+----+
|    |    |    | A1 | B1 |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    | R1 | G1 |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

On Mac AMD I see this

```
cube coord : -0.7084864819326223, 0.705718956612574, 0.002767525320049306
3d coord   : 0.501953125, 0.0019531249999992784, 0.25
texel coord: 4.016, 0.016  layer: 1 face: -x
result[0] = 4096,4097,4097,4096
R gather = F1:X0:Y0, F1:X1:Y0, F1:X1:Y0, F1:X0:Y0
+----+----+----+----+----+----+----+----+
| A1 | B1 |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

This is missing R and G because they returned the same texel (same or different face) and the diagram maker only shows the one result per texel location.

# This also fails on Mac AMD for 2D textures

Example:

https://jsgist.org/?src=fd8b1728e4eae2bcc29f515d068521c0

Mac M1 / Mac Intel / Linux AMD (correct)

```
uv coord   : 0.4, 0.2
texel coord: 3.2, 1.6
result[0] = 130,131,67,66
R gather = F0:X2:Y2, F0:X3:Y2, F0:X3:Y1, F0:X2:Y1
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    | A0 | B0 |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    | R0 | G0 |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

Mac AMD

```
amd rdna-1
uv coord   : 0.4, 0.2
texel coord: 3.2, 1.6
result[0] = 0,0,0,0
R gather = F0:X0:Y0, F0:X0:Y0, F0:X0:Y0, F0:X0:Y0
+----+----+----+----+----+----+----+----+
| A0 |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

* We could just mark this as an AMD bug.
* We could see that it's not portable and decide to disallow uint/sint formats with `textureGather`
* We could try to workaround it.

  For cubemaps, I think you can take the cube coord, convert to face coord, quantize with `ceil`/`floor` to get 4 face coords, convert back to cube coords, then call `textureSampleLevel` on each of the 4 coords. You'd need further quantize the coordinates to make sure you got texel centers so as to ignored sampler settings (nearest, linear).
  
  For 2d it's similar just skip the cube->face->cube converts.

* other...?

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Kangz** [comment]
Given that this is a known hardware bugs that drivers have to work around (see this [Mesa commit](https://gitlab.freedesktop.org/mesa/mesa/-/commit/c63ccf90dfc087420863ee0e24867895affa40a9)) IMHO we should treat it as non-blocking for the WebGPU/WGSL specs and file against the various drivers (as you've started doing).

**Comment by kainino0x** [comment]
Removing textureGather with integer formats per #4857. This is M0.

**Comment by kainino0x** [comment]
Tentatively unmarking resolved due to report of integer textureGather being used: https://github.com/gpuweb/gpuweb/pull/4904#issuecomment-2382144800

**Comment by dneto0** [comment]
With recent fixes for [validating GPUProgrammableStage](https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gpuprogrammablestage), if a sampled texture or depth texture is used with a filtering sampler, then the texture must have a 'float' sampleType.

The first gist tested   https://jsgist.org/?src=f32cd47fd0cb0e8330c1c54a44cc9f74  uses:
-  a cube map with uint sampled type
- an ordinary sampler, defaulting to filtering
- auto layout

So I think it's now a case that should be validated out at the API level.

Are the other remainig cases similar?

**Comment by greggman** [comment]
Here's an updated gist with the correct filtering

https://jsgist.org/?src=e60d7e7967962f9b3119a0fd3d622f9a

It still fails on Mac AMD

That said, IIRC from the F2F, we decided that UAs should work around this and the spec will stay as is (still allow gather with sint/uint/depth).  We'll just start enforcing that you must used a `non-filtering` sampler.

**Comment by kainino0x** [comment]
As long as we don't think we're going out of spec of the backend APIs anymore, I think we agreed to call this done, and have implementations do workarounds as they see fit (prevent crashes, optionally prevent wrong results).

**Comment by dneto0** [comment]
For the record., using the gist at https://jsgist.org/?src=e60d7e7967962f9b3119a0fd3d622f9a and using powerPreference:'high-performance', on my Mac AMD GPU 

Macbook Pro 2017, AMD Radeon Pro 560  
 Vendor: AMD 0x1002
 Device ID 0x6ef
 Revision ID 0x00c0
 
I get:

```
 amd gcn-4
cube coord : -0.7084864819326223, 0.705718956612574, 0.002767525320049306
3d coord   : 0.501953125, 0.0019531249999992784, 0.25
texel coord: 4.016, 0.016  layer: 1 face: -x
result[0] = 4160,4161,4097,4096
R gather = F1:X0:Y1, F1:X1:Y1, F1:X1:Y0, F1:X0:Y0
+----+----+----+----+----+----+----+----+
| A1 | B1 |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
| R1 | G1 |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```

**Comment by greggman** [comment]
and just for clarification, this was what you should have gotten

```
cube coord : -0.7084864819326223, 0.705718956612574, 0.002767525320049306
3d coord   : 0.501953125, 0.0019531249999992784, 0.25
texel coord: 4.016, 0.016  layer: 1 face: -x
result[0] = 4099,4100,8448,8384
R gather = F1:X3:Y0, F1:X4:Y0, F2:X0:Y4, F2:X0:Y3
+----+----+----+----+----+----+----+----+
|    |    |    | R1 | G1 |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
| A2 |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
| B2 |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
|    |    |    |    |    |    |    |    |
+----+----+----+----+----+----+----+----+
```
