### ISSUE TITLE
Zero value of position attribute in vertex shaders?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4845]
Hi, the WGSL specification says [The zero value for an N-component vector of type T is the N-component vector of the zero value for T.](https://www.w3.org/TR/WGSL/#zero-value), however this is problematic for [position](https://www.w3.org/TR/WGSL/#built-in-values-position) since if not otherwise written to will lead to undefined behavior due to effective division by zero (0,0,0,0) = (0/0, 0/0, 0/0), depends on the implementation handling of homogeneous coordinates.

If the initialization was 0,0,0,1 it would still be problematic, since one could zero out the position and have the same divide by zero. For instance:
```
struct VertexOutput {
  @builtin(position) position : vec4f,
  @location(0) @interpolate(flat) something: u32,
}

@vertex
fn v(@location(0) fromVertexBuffer: u32) -> VertexOutput {
  var v = VertexOutput();
  v.something = fromVertexBuffer;
  return v;
}

@fragment
fn f(@location(0) @interpolate(flat) something: u32) -> @location(0) u32 {
  return something;
}
```
will reach the fragment shader on Apple Silicon Macs but not Intel ones.

Perhaps I missed the relevant part of the specification, but should implementations be preventing .w == 0 being written out from the vertex shader?

**Comment by dneto0** [comment]
The D3D11 functional spec says:

https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#15.4%20Clipping 

> By default primitives are clipped to a volume that includes a 0 <= z <= w depth range clip. Clipping of the Z coordinates can be disabled by setting the DepthClipEnable [Rasterizer State](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#RasterizerState)(15.1) to FALSE. Primitives that fall outside of the depth range are thus still rendered, but are given the value of the nearest limit of the viewport depth range.

> Even when Z clipping is disabled, primitives must be clipped such that only w > 0 vertices result. 

> Coordinates coming in to clipping with infinities at x,y,z may or may not result in a discarded primitive. Coordinates with NaN at x,y,z or w coming out of clipping are discarded.

**Comment by dneto0** [comment]
I tried to find a similar rule in Vulkan but could not.
Relevant areas: 
- primitive clipping: https://registry.khronos.org/vulkan/specs/1.3/html/vkspec.html#vertexpostproc-clipping 
     - which gives the clip volume equations like -w_c <= x_c <= w_c  with no prohibitions on w_c <= 0 cases.  (And a bunch of paragraphs about optional cull plans and clip planes)
     - " If the primitive is a polygon, it passes unchanged if every one of its edges lies entirely inside the clip volume, and is either clipped or discarded otherwise."   So if that's authoritative, the w_c=0 case is allowed as a vertex on a polygon that goes through to rasterization.
- Coordinate transforms: https://registry.khronos.org/vulkan/specs/1.3/html/vkspec.html#vertexpostproc-coord-transform
    - describes the clip coordinates to NDC transform (which introduces the division).  In the w_c=0 case who knows what framebuffer x and y result.

**Comment by mwyrzykowski** [comment]
It would seem the Metal Shading language specification also defines this:

Section 1.7
> A four-dimensional homogenous vector (x,y,z,w) specifies a three-dimensional point in clip-
space coordinates. A vertex shader generates positions in clip-space coordinates. Metal divides
the x, y, and z values by w to convert clip-space coordinates into normalized device
coordinates.

and then Section 3.1:
> Division by zero for floating-point types results in ±∞
or NaN, as prescribed by IEEE-754. (For more about the numerical accuracy of floating-
point operations, see section 7.)

which implies this is an Apple Silicon driver bug to work around, as NaN should not be within the NDC box, though I do wonder what MTLDepthClipModeClamp should do? I will file a report as the driver team may want to fix it, but I guess we need to work around in the interim.

**Comment by dneto0** [comment]
> MTLDepthClipModeClamp

Sound like it's like Vulkan's depthClampEnable:
https://registry.khronos.org/vulkan/specs/1.3/html/vkspec.html#vertexpostproc-clipping 

> Depth clamping is enabled or disabled via the depthClampEnable enable of the [VkPipelineRasterizationStateCreateInfo](https://registry.khronos.org/vulkan/specs/1.3/html/vkspec.html#VkPipelineRasterizationStateCreateInfo) structure. Depth clipping is disabled when depthClampEnable is VK_TRUE.

> When depth clipping is disabled, the plane equation

> z<sub>m</sub> ≤ z<sub>c</sub> ≤ w<sub>c</sub>

> (see the clip volume definition above) is ignored by view volume clipping (effectively, there is no near or far plane clipping).

(There's a separate control for whether z_m here is 0 or -w_c)

**Comment by mwyrzykowski** [comment]
Given the D3D behavior, it seems like we should simply say that w must always be > 0 in the WebGPU / WGSL specification. I couldn't find where we specify that, but I do see:

https://www.w3.org/TR/webgpu/#primitive-clipping
> Primitives are clipped to the clip volume, which, for any [clip position](https://www.w3.org/TR/webgpu/#clip-position) p inside a primitive, is defined by the following inequalities:

> −p.w ≤ p.x ≤ p.w
−p.w ≤ p.y ≤ p.w
0 ≤ p.z ≤ p.w (depth clipping)

which seems to imply that p.w = p.z = 0 with unclippedDepth = true would be allowed in WebGPU, but likely not work in D3D or Intel Macs.

**Comment by dneto0** [comment]
The resolution from the 2024-09-17 meeting is to say position.w = 0 is a dynamic error.
