### ISSUE TITLE
Spec or browser or user issue: cannot call GPUBuffer.mapAsync() with size=undefined?

### ISSUE THREAD

**Issue by juj** [gpuweb/gpuweb#4848]
To implement WebAssembly/Emscripten WebGPU C/C++ -> JavaScript language bindings for `GPUBuffer.mapAsync()`, I would like to write the following:

```js
// size: Specifies # of bytes to map, or pass -1 to map whole buffer.
function wgpu_buffer_map_async(buffer, callback, userData, mode, offset, size) {
  buffer.mapAsync(mode, offset, size < 0 ? undefined : size).then(() => {
    callback(buffer, userData, mode, offset, size);
  });
}
```

the rationale here is that if the last parameter `size` is undefined, the whole buffer should be mapped:

![image](https://github.com/user-attachments/assets/d7d0416c-2eac-49ba-8c25-ef5925e14009)

This would be neat and clean.

However, when I run this in Chrome Canary, it doesn't work, and .getMappedRange() fails on the buffer. I find that I need to instead do the following:

```js
// size: Specifies # of bytes to map, or pass -1 to map whole buffer.
function wgpu_buffer_map_async(buffer, callback, userData, mode, offset, size) {
  var promise = (size < 0) ? buffer.mapAsync(mode, offset) : buffer.mapAsync(mode, offset, size);
  promise.then(() => {
    callback(buffer, userData, mode, offset, size);
  });
}
```
which works as expected.

Is the first example not working to be expected per spec? The spec states above that if size is undefined, the remaining buffer size starting from offset should be taken, but implementation in Chrome does not seem to agree. I.e. calling `buffer.mapAsync(mode, offset)` is treated different to calling `buffer.mapAsync(mode, offset, undefined);`, even though the spec wording implies these should produce the same result?

Is the spec worded casually and indeed these two calls should be treated differently by an implementation?
Or is Chrome browser behavior not par to spec?
Or did I miss something in my testing or spec lawyering?

----------

More generally, I find that this kind of ambiguous handling of "null/undefined/not present at all" issue occurs with respect to the following functions:
- `GPUBuffer.mapAsync()`: third size parameter,
- `GPUBuffer.getMappedRange()`: second size parameter
- `GPUDevice.createRenderPipeline()`: pipeline descriptor `depthStencil`, `multisample` and `fragment` fields
- `GPUDevice.createRenderPipelineAsync()`: same as above,
- `GPUDevice.createBindGroup()`: `descriptor.resource.size` field,
- `GPUCommandEncoder.beginRenderPass()`: `descriptor.depthStencilAttachment` field,
- `GPUPassEncoder.setIndexBuffer()`: fourth `size` parameter,
- `GPUPassEncoder.setVertexBuffer()`: fourth `size` parameter,
- `GPUCommandEncoder.clearBuffer()`: third `size` parameter

To see these call sites ambiguities in action in a Wasm -> JS bindings library, search for word "awkward" in this file: https://github.com/juj/wasm_webgpu/blob/main/lib/lib_webgpu.js

**Comment by kainino0x** [comment]
I am pretty certain that the [WebIDL spec](https://webidl.spec.whatwg.org/) allows passing `undefined` for the `size` parameter. (I have identified the relevant spec text before, but it's really hard to find so I don't have a direct link.)

Chrome _does_ seem to allow it. Here's my test code:

```js
d = await (await navigator.gpu.requestAdapter()).requestDevice();
b = d.createBuffer({ size: 16, usage: GPUBufferUsage.MAP_WRITE });
await b.mapAsync(GPUMapMode.WRITE, 8, undefined);
b.getMappedRange(8, undefined);
```

Could you investigate and figure out what's different about your case? What is the error message?

> * `GPUDevice.createRenderPipeline()`: pipeline descriptor `depthStencil`, `multisample` and `fragment` fields

> * `GPUDevice.createBindGroup()`: `descriptor.resource.size` field,
> * `GPUCommandEncoder.beginRenderPass()`: `descriptor.depthStencilAttachment` field,

Optional dictionary members are definitely allowed to be set to `undefined`, see steps 4.1.4 - 4.1.5 [here](https://webidl.spec.whatwg.org/#js-dictionary).

**Comment by juj** [comment]
Huh, now that I triple-test it, it does seem to work at least in the case of GPUBuffer.mapAsync(). I've no idea what I botched in the test. Nevertheless, authored above commit to simplify GPUBuffer.mapAsync() case.

@kainino0x Would you be able to scan through [lib_webgpu.js](https://github.com/juj/wasm_webgpu/blob/main/lib/lib_webgpu.js) at a glance to see if any of the code sites marked with `"awkward"` would be expected not to work? At some point in the past I did find each of them did not function, but it has been some time with some of the entry points, so things seem to have improved since.

**Comment by juj** [comment]
Turns out indeed I was able to clean up most of the call sites. There are a couple that remained, but for the most part pretty clean. Thanks for the help Kai!

**Comment by kainino0x** [comment]
Glad to hear it!
Looking at the revision after your last commit, there are 5 instances of "awkward" and I don't think any of them can be fixed right now (except the error code one if you use `error.constructor.name` as a type identifier string)
