### ISSUE TITLE
Asynchronous pipeline creation

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#486]
See also: #6

At some point, it was decided that pipeline creation should be async. However, the current API seems to have createRenderPipeline as an synchronous API. This might kick off asynchronous pipeline creation behind the scenes, but there's no way for the application to know whether the pipeline is finished creating, meaning that the implementation has no choice but to block for the pipeline to be finished during command playback.

A quick fix for this would be to have `GPUComputePipeline.isReady()` / `GPURenderPipeline.isReady()` API, allowing the user to optionally skip drawing commands if the associated pipeline is not yet ready.

**Comment by Kangz** [comment]
IIRC we decided that synchronous pipeline compilation was important to have, and we'd look at async pipeline compilation later. @kainino0x had several ideas one how push/popErrorScope could help with this. There was also ideas for `async GPUDevice.createReadRenderPipeline(descriptor)`.

**Comment by magcius** [comment]
Not that this is strictly equivalent, but see [KHR_parallel_shader_compile](https://www.khronos.org/registry/webgl/extensions/KHR_parallel_shader_compile/) for OpenGL, something I have used successfully. The query-ready API is quite convenient for me, as I can do the equivalent of `if (!isReady(pipeline)) continue;` to skip draws, rather than tracking the state of promises, but if promises are easier for engines, it's not a huge hassle to make work either.

**Comment by magcius** [comment]
Interesting. Error scopes might do exactly what I want here. I'll try it; thanks.

**Comment by kainino0x** [comment]
To clarify, this is the intent of the design, but it is not actually implemented (in Chrome) right now. Pipeline creation is unfortunately still on the same work queue as everything else.

Some weeks ago I was rethinking the design decision to use error scopes for this purpose. It's possible that we might tweak it (to, e.g., isReady or createRenderPipelineAsync), mainly to simplify spec and implementation, but talking to Austin just now, it may not actually achieve that.

**Comment by Kangz** [comment]
Closing. There is now `GPUDevice.createRenderPipelineAsync` and `GPUDevice.createComputePipelineAsync`
