### ISSUE TITLE
Maximum uniform buffer size/alignment in GPULimits

### ISSUE THREAD

**Issue by magcius** [gpuweb/gpuweb#487]
For portability, it's common to need to know the maximum size and alignment of uniform buffers. Alignment is most often 256 on NVIDIA devices due to hardware limitations, but much lower on most other GPU vendors.

I use these limits when allocating uniform buffers in my platform layer (they're fetchable in GL, too), so it would be helpful to have them in WebGPU as well.

https://vulkan.gpuinfo.org/displaydevicelimit.php?name=minUniformBufferOffsetAlignment
https://vulkan.gpuinfo.org/displaydevicelimit.php?name=maxUniformBufferRange

**Comment by kvark** [comment]
I don't think it's worth messing with alignment. We can just write down 256 in the spec and proceed, at least for MVP. Otherwise, we are going to be opening a can of worms (or portability issues), given how many different alignment rules there are in Vulkan.

For the size, does anyone need more than 16K of uniforms?

**Comment by Kangz** [comment]
We can probably start with 256 and 16k in the GPULimits struct and see if we can bump to 64k later. Eventually the GPULimits should/could reflect what's on the machine and applications could opt-in to smaller alignment limits.

**Comment by magcius** [comment]
> For the size, does anyone need more than 16K of uniforms?

There's technically two sizes -- the size of a uniform buffer as a whole (which is 64k in D3D11, and not bounded by the newer APIs AFAIK), and the size of the bindable range of a uniform buffer (which is the "maxUniformBufferRange"). The only case I have had for 16k worth of uniforms is a giant array of auto-instanced data to collapse draw calls together, and it would be nice to have more, since it means less draw calls. Having it as a platform limit means I can scale to the hardware.

**Comment by Kangz** [comment]
Limits have been added to the spec. Closing.
