### ISSUE TITLE
Guarantees about early-z fragment discard

### ISSUE THREAD

**Issue by toji** [gpuweb/gpuweb#4878]
On the WebGL dev list a [WebGPU question was recently asked re: early Z discard](https://groups.google.com/g/webgl-dev-list/c/nG7yEjCHxGI/m/l_ZmIr9DAgAJ). It was observed that the fragment shader appeared to be running for all fragments even if the fragment failed the depth test.

The poster noted that Vulkan appears to indicate that [if the fragment shader writes to storage then early-z discards will be disabled](https://docs.vulkan.org/features/latest/features/proposals/VK_AMD_shader_early_and_late_fragment_tests.html#_problem_statement). Is this something that the group has discussed before and is a known behavior for all applicable native APIs?

The WebGPU spec currently indicates that early-z discards may be disabled if the fragment shader writes to the `frag_depth` builtin but doesn't specify any other scenarios where that may happen. If this is expected behavior we should include it in the spec text.

**Comment by toji** [comment]
Looks like some related discussion has happened previously in #398.

**Comment by kainino0x** [comment]
If it's not consistent across backends, we may be able to make it consistent by inserting a no-op `frag_depth` write.

**Comment by kdashg** [comment]
We almost want a pragma or something in the shader such that we get a warning if a shader expects early-z-discard and we can tell it won't get it.

**Comment by mwyrzykowski** [comment]
It would be unfortunate to write to frag_depth if not necessary, as this impacts some TBDR optimizations. 

It would be good to have an understanding of what differences we are seeing across hardware, I still need to catch up on #398

**Comment by mwyrzykowski** [comment]
I checked on an Apple Silicon mac:

* without [[early_fragment_tests]] + write to memory -> early-z does not occur
* with [[early_fragment_tests]] + write to memory -> early-z is honored

which seems to match Vulkan's behavior.

Does Vulkan have an equivalent of `[[early_fragment_tests]]` so the author can achieve their use case?

**Comment by toji** [comment]
GLSL has `layout(early_fragment_tests)`, which seems to be equivalent? https://www.khronos.org/opengl/wiki/Early_Fragment_Test#Explicit_specification

Surfaced in SPIRV as the EarlyFragmentTests [execution mode](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_execution_mode).

**Comment by mwyrzykowski** [comment]
AMD and Intel UHD 630 also match Apple Silicon.

Seems like we need no change, maybe just a CTS test and some spec wording?

**Comment by toji** [comment]
So it looks like this is common behavior between all APIs. We can add to the spec that storage writes can prevent early z, and it looks like we have the possibility of introducing an extension in the future that explicitly enables early z discards when storage writes are used if we so choose.

**Comment by kainino0x** [comment]
I think there's two possible future additions:
- an assertion that fails if early z isn't going to be used
- a thing that forces early z to be used even when there are side effects

I think the first one could be implemented without backend support but probably isn't that useful; it would just assert that there's no frag_depth and no side effects.

**Comment by litherum** [comment]
Sounds like:

- All 3 APIs behave the same way: disabling the optimization if it is observable whether or not the optimization occurred
- All 3 APIs have some way to get the optimization back, _even if_ it's observable

Sounds like we should do 2 things:
1. Spec that the optimization does not occur if it is observable whether or not it occurred
2. (Possibly for a future milestone) add an equivalent feature of `earlydepthstencil`/`[[early_fragment_tests]]`/`layout(early_fragment_tests)` to get the optimization back, _even if it's observable_

**Comment by litherum** [comment]
> an assertion that fails if early z isn't going to be used (Kelsey's suggestion)

Is this implementable? I'm aware that the backend APIs allow you to force the optimization _on_, but I'm not aware of a way to _observe_ whether or not the backend decided to employ the optimization

**Comment by kainino0x** [comment]
> > an assertion that fails if early z isn't going to be used (Kelsey's suggestion)
> 
> Is this implementable? I'm aware that the backend APIs allow you to force the optimization _on_, but I'm not aware of a way to _observe_ whether or not the backend decided to employ the optimization when you haven't forced it on

I worded that poorly - what Kelsey said was "a warning if a shader expects early-z-discard and we can tell it won't get it." What I'm imagining is simply an assert that you're not doing anything that would force late-z - i.e. you're not doing anything that could observe a behavior difference between early-z and late-z.

**Comment by litherum** [comment]
> I worded that poorly - what Kelsey said was "a warning if a shader expects early-z-discard and we can tell it won't get it." What I'm imagining is simply an assert that you're not doing anything that would force late-z - i.e. you're not doing anything that could observe a behavior difference between early-z and late-z.

Such a warning seems like a straightforward thing to implement, but I'm not sure of its value.

I can totally imagine an author saying "I need my shader to use early-z despite using storage buffers, so please force it to use early-z."

I'm having a more difficult time imagining an author saying "it's okay if you don't use early-z, and I know you can't tell me if you're going to use early-z, so please tell me in _some_ situations where you _won't_ use it, but not all situations where you won't use it." In response to this warning, the author can (maybe?) modify their shader to stop using storage buffers, but that doesn't actually get them the optimization they're looking for - it just gets them 1 step closer to getting it.

Are there any native APIs that have a similar opt-in warning?

**Comment by toji** [comment]
Closed because the shader text in question is resolved, but I've filed a new issue to track the possibility of forcing early-z at #4891

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-09-18#m0-guarantees-about-early-z-fragment-discard-4878">GPU Web WG 2024-09-18</a></summary>

* BJ: was brought up on the WebGL dev list, paradoxically. Writing to a storage buffer in fragment shader, relying on early-Z discard. On Vulkan, if you write to storage buffer in fragment shader, starts skipping early-Z discards, similar to writing FragDepth. This is the behavior in Vulkan. Where's the confirmed behavior in D3D and Metal specs? Appreciate pointers on the issue. The WebGPU spec doesn't say anything about this. If this happens all the time, we should probably mention something. If we need to force this, can have the shader start emitting frag depth writes when they have storage buffer writes, to normalize the behavior. But I assume all the APIs are probably behaving similarly.
* JB: Are underlying platforms giving a way to toggle early-Z
* MW: Metal does: `[[early_fragment_tests]]`! Would need to check more to see what the consequences are.
* GT: We should add a test! Similar to [the test](https://github.com/gpuweb/gpuweb/issues/4696) for per-sample shading (affected by sample index, interpolation qualifiers) and writing to a storage buffer. There were behavioral differences on Metal.
* RC: [Direct3D 11.3 Functional Specification (microsoft.github.io)](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm) section 16.9.3 talks about early-Z.
* KG: AFAIK this early-Z is an optimization, and gets into observability, so it shouldn't be observable if it happens. The goal of the optimization it to be non-observable. If there are side-effects, the optimization shouldn't be happening.
* BJ: generally agree. This is Vulkan's approach. Vk has an extension (not sure how widely supported), lets you opt in to having the side effect. Anything that would make that side-effect observable disables the optimization. I assume it's true for the other APIs too.
* MM: So the proposal is that if there's side effect, then you cannot do early-Z discard.
* BJ: not really making a proposal, but saying this is the observed behavior of the API. Make it uniform everywhere? Force it to be uniform? Either way, think we should document the behavior.
* MM: the way you'd observe this, do a side-effect in the fragment shader, see if multiple overlapping triangles cause repeated execution of the fragment shader.
* KN: can test 2 things. 1) writing to storage buffer disables early-Z. 2) whether it's unobservable if you do early-Z discard. (2) is not observable except by performance test and I don't think we should try to test it.
* CW: want to check on the various APIs. If there are side-effects want to make sure early-Z discard doesn't happen.
* KG: do we have spec text?
* BJ: have some, wrote 1-2 weeks ago. Talks about FragDepth builtin, whether you can do early-Z discard. Would add a line there if all of the underlying APIs agree.

</details>
