### ISSUE TITLE
empty array entries in createPipelineLayout and other place should/should not be ignored?

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4879]
Posting this here instead of filing a bug. Maybe it's the specified behavior but ....

If I call `device.createPipelineLayout` with empty elements it ignores them. 

In other words

```js
device.createPipelineLayout({ bindGroupLayouts: [ validBGL ] });            // should pass. passes
device.createPipelineLayout({ bindGroupLayouts: [ undefined, validBGL ] }); // should fail. fails
device.createPipelineLayout({ bindGroupLayouts: [ ,,validBGL ] });          // should fail? does not fail
device.createPipelineLayout({ bindGroupLayouts: [ validBGL,, ] });          // should fail? does not fail
device.createPipelineLayout({ bindGroupLayouts: [ validBGL,,valiaBGL ] });  // should fail? does not fail
```

empty entries are not ignored other places. For example `new Float32Array([,,7])` makes `[NaN, NaN, 7]`

For `createPipelineLayout` the spec says 

> Let allEntries be the result of concatenating bgl.[[[descriptor]]](https://www.w3.org/TR/webgpu/#dom-gpubindgrouplayout-descriptor-slot).[entries](https://www.w3.org/TR/webgpu/#dom-gpubindgrouplayoutdescriptor-entries) for all bgl in descriptor.[bindGroupLayouts](https://www.w3.org/TR/webgpu/#dom-gpupipelinelayoutdescriptor-bindgrouplayouts).

Which does kind of suggest these empty elements are ok? But checking other places, an empty element isn't okay. For example `createBindGroup({ entries: [, validEntry ] })` fails. `createRenderPipeline({ ... vertex: { buffers: [ { attrib: [,,, someValidAttribute ] } ] } } )` fails. Those specs make it sound they could succeed based on similar wording. For example:

> For each attribute attrib in the list descriptor.[attributes](https://www.w3.org/TR/webgpu/#dom-gpuvertexbufferlayout-attributes):

Well, an array of `atttributes: [,,,validAttribute,,,validAttrubte]` has 2 attributes but fails 

Should this be clarified? And are CTS tests needed?

**Comment by kainino0x** [comment]
This appears to be a Chrome bug. According to the WebIDL spec, [sequences are constructed by iterating iterable things](https://webidl.spec.whatwg.org/#js-sequence). Iterating e.g. `[,]` produces `[undefined]`, which should fail when trying to convert `undefined` to `GPUBindGroupLayout`.

```
> [...[,]]
[undefined]
> for (const x of [,,]) console.warn(x)
undefined
undefined
```

Testing locally, both Firefox and Safari throw errors as expected for
`d.createPipelineLayout({ bindGroupLayouts: [,] })`
while Chrome does not.

I have no idea how Chrome ended up being wrong, but I'll file a bug and try to check if it regressed.

**Comment by kainino0x** [comment]
https://crbug.com/367755353

**Comment by greggman** [comment]
Hmmm, I thought I tested Safari yesterday and it was passing but trying today it's not. 🤷‍♂️. gtk

**Comment by Kangz** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/GPU-Web-2024-09-18#m0-empty-array-entries-in-createpipelinelayout-and-other-place-shouldshould-not-be-ignored-4879">GPU Web WG 2024-09-18</a></summary>

* Chromium regression. Closed.

</details>
