### ISSUE TITLE
Aliasing restrictions in WGSL spec are underspecified and potentially misleading

### ISSUE THREAD

**Issue by bavalpey** [gpuweb/gpuweb#4914]
In the [aliasing section](https://www.w3.org/TR/WGSL/#aliasing), a restriction about aliasing is specified:
> Execution of a WGSL function [must not](https://www.w3.org/TR/WGSL/#shader-creation-error) potentially access memory through aliased root identifiers, where one access is a write and the other is a read or a write

However, the proceeding examples and clarification deals exclusively with restrictions around arguments at call sites. It makes no mention of prohibitions about aliasing variables or values within a function itself.

Specifically, it is unclear as to whether or not the WGSL spec prohibits or allows the following:

```wgsl
@group(0) @binding(0) var<storage, read_write> x: i32;

fn foo() -> i32 {
  let a = &x;
  *a = 4;
  return x;
}
```

**Comment by dneto0** [comment]
Maybe adding "distinct" would help, to make:

> Execution of a WGSL function [must not](https://www.w3.org/TR/WGSL/#shader-creation-error) potentially access memory through distinct aliased root identifiers, where one access is a write and the other is a read or a write.

In the code example given,
* there is only one root identifier, namely `x`.  
* there is one write to the root identiifer: `*a = 4;`
* there is one read from the root identifier: the evaluation of `x` in `return x;`

**Comment by bavalpey** [comment]
I think that's even more confusing. And again, it isn't really sufficient because the surrounding discussion is focused so much on aliasing with respect to function arguments that aliasing of variables within the same function (where none of the aliases are from arguments) is on the back burner.


For instance, I'm not even sure, after reading the spec, whether or not *this* is permitted:

```wgsl
@group(0) @binding(0) var<storage, read_write> x: i32;
fn foo() -> i32 {
  let a = &x;
  let b = &x;
  *a = 4;
  *b = 12 + *b;
  return *b;
}
```

Here, we are definitely accessing memory through aliased root identifiers - a and b are both aliases to for the location of x. However, other than the quoted sentence, nothing in the rest of the section on aliasing refers to this scenario. That leads me to question whether or not the sentence was meant to be a broad restriction, or if it was just a short way of establishing requirements around aliasing and actually was meant to refer to aliasing with respect to arguments passed to functions.

**Comment by dneto0** [comment]
> However, I think the proposed verbiage is even more confusing. I'm not sure if distinct is referring to the memory, or the identifier itself.

"distinct" is meant to modify "root identifier".  So distinct root identifiers.

>  You can't access the same memory through distinct root identifiers because root identifiers can't occupy the same space in memory anyway (pointers to pointers are always prohibited). Perhaps I am a bit lost.

A root identifier denotes a variable, and the underlying storage for distinct (mutable) variables are disjoint. From https://gpuweb.github.io/gpuweb/wgsl/#var-decls 

> Two [resource](https://gpuweb.github.io/gpuweb/wgsl/#resource) variables may have [overlapping memory](https://gpuweb.github.io/gpuweb/wgsl/#overlap) locations, but it is a [dynamic error](https://gpuweb.github.io/gpuweb/wgsl/#dynamic-error) if either of those variables is mutable. Other variables with overlapping lifetimes [will](https://gpuweb.github.io/gpuweb/wgsl/#behavioral-requirements) not have overlapping memory locations.

Also from: https://gpuweb.github.io/gpuweb/wgsl/#root-ident-sec

> Within a function, each [memory view](https://gpuweb.github.io/gpuweb/wgsl/#memory-view) has a particular root identifier, which names the variable or formal parameter that first provides access to that memory in that function.

> Here, we are definitely accessing memory through aliased root identifiers - a and b are both aliases for the location of x.

I think this is the nub of the misunderstanding.  Yes `a` and `b` are identifiers that point to the storage in `x`.  But 'a' and 'b' are not root identifiers.
The variable `x` is the root identifier for both `a` and `b`.


See the rules for how to trace from an expression back to the root identifier: https://gpuweb.github.io/gpuweb/wgsl/#root-ident-sec

**Comment by dneto0** [comment]
More about wording.  This is the sentence that defines the term 'root identifier'

> Within a function, each [memory view](https://gpuweb.github.io/gpuweb/wgsl/#memory-view) has a particular **root identifier**, which names the variable or formal parameter that first provides access to that memory in that function.

So a root identifier is either a `variable` or a `formal parameter`.  A let-declared name is not a root identifer.  So in your examples above, `a` and `b` are not root identifiers.  Also, since there is only one variable (`x`), and no formal parameters, the programs only have one root identifier.

**Comment by dneto0** [comment]
I think this issue is resolved.  Closing.  Please reopen if you think it's not resolved.
