### ISSUE TITLE
Can `GPUOutOfMemoryError` only be generated by `createBuffer()`?

### ISSUE THREAD

**Issue by teoxoy** [gpuweb/gpuweb#4916]
The spec currently only allows `createBuffer()` to generate `GPUOutOfMemoryError`.

The CTS seems to expect that it can also be generated by `createTexture()`.
https://github.com/gpuweb/cts/blob/0f96947d350753c0bdc592b33c2ca5ea61ccca24/src/webgpu/error_test.ts#L34-L54

I couldn't find an issue/PR where this was previously discussed.

**Comment by kainino0x** [comment]
It's supposed to be possible from createTexture and createQuerySet as well. We must have accidentally closed whatever issue we needed without remembering this; thanks for catching it!

**Comment by kainino0x** [comment]
cc @toji @jimblandy

**Comment by teoxoy** [comment]
Allowing it for `createTexture` and `createQuerySet` sounds appropriate to me.

**Comment by toji** [comment]
+1 for allowing it during `createTexture` and `createQuerySet`.

Is there a particular reason why we don't have to be concerned about OOM for things like pipelines or bind groups?

**Comment by kainino0x** [comment]
I consider OOMs in those calls to be "unrecoverable" (i.e. the app would not know what to do about it, whereas buffers/textures/querysets hopefully all live in sort of the same memory pressure space).

And besides we don't really trust the driver to be in a valid state if things like that happen - we probably shouldn't even trust most drivers with buffer/texture/queryset OOMs, but we have a way to expose it where we do.
