### ISSUE TITLE
Build error: You used Status ED, but your Group (WEBGPU) is limited to the statuses ...

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#4924]
Reported by @alan-baker

Both WebGPU and WGSL are failing both the preview builds and the TR builds with this error (example from `publish-TR-webgpu`):

```
    $ bikeshed --die-on=warning spec "spec/index.bs" "spec/index.bs.built.html" 
      WARNING: You used Status ED, but your Group (WEBGPU) is limited to the statuses CG-DRAFT, CG-FINAL, or UD.
       ✘  Did not generate, due to errors exceeding the allowed error level.
```

Examples:

- publish-TR-webgpu: https://github.com/gpuweb/gpuweb/actions/runs/11369027185
- publish-TR-wgsl: https://github.com/gpuweb/gpuweb/actions/runs/11369027239
- preview-pull-request: https://github.com/gpuweb/gpuweb/actions/runs/11369063080

`CG-DRAFT` is not appropriate (that's a [Draft Report](https://www.w3.org/standards/types/#x2-1-w3c-community-group-report-or-w3c-business-group-report)). `UD` ([Unofficial Draft](https://www.w3.org/standards/types/#x2-4-other-documents)) could be appropriate for previews but not for <https://gpuweb.github.io/gpuweb/>.

@tidoust do you know what's happening here? I'm guessing it has something to do with the group changing status somehow, but not sure.

**Comment by tidoust** [comment]
I suspect Bikeshed has become more picky about what statuses a group may use starting with [version v4.2.0](https://github.com/speced/bikeshed/issues/1773#issuecomment-2414953844).

In practice, you have two choices, depending on what you want the spec published at https://gpuweb.github.io/gpuweb/ to say:
1. To make it a GPU for the Web CG draft, then you need to use `CG-DRAFT`. That would be the correct status. Apparently, there's no longer any way to say that the document is an Editor's Draft of a CG Draft. You can just say it's a CG Draft.
2. To make it a GPU for the Web WG draft, then you indeed need to switch the group to `gpuwg`, as done in #4925

Both are "correct". That's up to you. The only implication I see is that the published spec at https://www.w3.org/TR/webgpu/ has a link back to the "Editor's Draft", so one could expect an "Editor's Draft" and wonder why they end up on something that says "I'm a CG Draft'. Now, practically speaking, an Editor's Draft has no standing whatsoever from a W3C perspective, so for all I know its actual status could be "Super Duper Series of Words" (or CG Draft).

**Comment by kainino0x** [comment]
Thank you! @Kangz @kdashg do you think it's OK to change the draft specs from CG drafts to WG drafts?

**Comment by dneto0** [comment]
This issue should be closed? @kainino0x

**Comment by kainino0x** [comment]
No, I still think it's more appropriate for the draft to be an editor's draft of the working group, than a draft community group report. That seems to be the standard status used for all other specs. For example all of our editor's draft / draft CG report links to CSS go to the editor's draft versions of those specs:
https://drafts.csswg.org/mediaqueries-5/#descdef-media-dynamic-range
(in the TR version, which is Working Draft, they go to the working draft version instead)
