### ISSUE TITLE
Exposing limited static analysis of WGSL to the CPU (JS) re. shared data, types etc.

### ISSUE THREAD

**Issue by 7ombie** [gpuweb/gpuweb#4937]
In GPU programming generally, the code running on the CPU cannot understand the code on the GPU. This is a common source of pain, bugs and fairly involved workarounds.

Metal and Swift (and Objective-C) all (more or less) understand C, so they can share structs and enums written in C. That adds yet a third language, but it's nice to have.

JavaScript doesn't understand WGSL at all, and JavaScript doesn't have structs (at all). This quickly leads to us having to populate buffers with structs defined in a different language using a bunch of typed arrays, manually managing the various offsets, lengths, strides etc (often while we're already dealing with vertex descriptors and bind groups).

WebGPU is a low-level API (and cannot assume JS on the CPU), so it can only do so much to address this issue, leaving it to the community to build things out from there. That said, WebGPU implementations already include a WGSL compiler, and have to parse the source files to compile them.

On balance, I think the WebGPU API should provide limited information about the 'shape' of a shader module, similar to the way the WebAssembly API describes a module's imports and exports, along with their types etc. This would only include information that the CPU needs to know about: The structs it actually needs to populate, as well as information about locations, bind groups and bindings etc.

The community can then build libraries that use the shader description to automate populating buffers etc, and tailor those libraries to whatever language they're for.

I don't have a concrete proposal for an API, and am not sure exactly what information should be shared, but JavaScript (at least) needs to access some information written in WGSL (and importing parsers on the frontend will always be clunky in practice).

**Comment by greggman** [comment]
This issue is already requested here

https://github.com/gpuweb/gpuweb/issues/624

For now, yes, you, need to rely on 3rd party libraries like

https://github.com/brendan-duncan/wgsl_reflect

or higher level libraries based on that like

https://github.com/greggman/webgpu-utils

**Comment by 7ombie** [comment]
Thank you, @greggman. I did search, but didn't find it.
