### ISSUE TITLE
GPUCommandEncoder.beginRenderPass() allows for empty list of attachments?

### ISSUE THREAD

**Issue by mwyrzykowski** [gpuweb/gpuweb#4968]
When reading the validation described in [GPUCommandEncoder.beginRenderPass()](https://www.w3.org/TR/webgpu/#dom-gpucommandencoder-beginrenderpass), it appears that zero color attachments and a null depth-stencil are allowed.

Should we support that? If the user does that, at least in Metal, we would need to bind a placeholder (memoryless?) render target as we can not create a MTLRenderPassEncoder with zero color targets and null depth-stencil as it is an error to do so.

But afaik the CTS does not cover this, and it seems odd that one would wish to do something of this nature as opposed to using a compute shader, so should it be rejected at validation time?

**Comment by kainino0x** [comment]
It's in here:

> - descriptor must meet the Valid Usage rules given device this.[[device]].

> 4. There must exist at least one attachment, either:
>   - A non-null value in this.colorAttachments, or
>   - A this.depthStencilAttachment.

We recently fixed missing equivalent validation in createRenderPipeline [in dawn](https://crbug.com/341812551) and in CTS (see links from the Dawn bug).

**Comment by kainino0x** [comment]
... but if we are missing CTS for beginRenderPass then we do need to add that.

**Comment by mwyrzykowski** [comment]
Ah I missed that part, thank you for clarifying. I'll double check the CTS but we can close this issue
