### ISSUE TITLE
bool has 4 byte size and alignment

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#4972]
[13.4.1 Alignment and Size](https://gpuweb.github.io/gpuweb/wgsl/#alignment-and-size) says each host-shareable or fixed footprint data type has an alignment and size.

But `bool` is fixed-footprint, concrete, and the spec does not specify a size or alignment for it.

Where we are:

* Vulkan and D3D (without extensions) don't support single-byte types, and hide the representation of 'bool'.  E.g. you can't put a bool in a Vulkan storage buffer.  We know some Vulkan drivers map bool to a 32-bit integer, effectively.
* Metal says bool has size 1 and alignment 1.
    * Even so, MSL has many packed vector types, but not a packed bool vector.
* WGSL limits say for the purpose of counting storage sizes, treat a bool as taking up 4 bytes.

Opinion:  bool should be spec'd as having size and alignment of 4 bytes.
* The representation we choose must avoid spuriously introducing data races. For example, concurrent accesses to adjacent bool scalars must not spuriously race: different invocations accessing s.a and s.b should not accidentally race.
```
struct S { a: bool, b:bool } 
```
* Space-conscious shader code that use a lot of bools should use use full-sized integers anyway.   I'm not aware that bool is used commonly in shaders (probably because D3D and Vulkan don't give you a space advantage).
* If we do ever want an 8bit type, we should add an explicit type for it: `i8`.

**Comment by dneto0** [comment]
* HLSL bool is 4 bytes. See https://github.com/microsoft/DirectXShaderCompiler/wiki/Buffer-Packing

**Comment by greggman** [comment]
I'm curious, are you suggesting having a bool be something you can align to memory?

Currently it is not:

> type 'bool' cannot be used in address space 'uniform' as it is non-host-shareable

That seemed good and intentional to me and that fact that there was no size and no alignment also seemed good. If you want bools in code you must convert something else. This forces you too choose your own representaion. You could choose `u32` = 0 false, 1 = true. you could choose `u32` with each bit as a bool. etc...

**Comment by dneto0** [comment]
> I'm curious, are you suggesting having a bool be something you can align to memory?
> 
> Currently it is not:
> 
> > type 'bool' cannot be used in address space 'uniform' as it is non-host-shareable
> 
> That seemed good and intentional to me and that fact that there was no size and no alignment also seemed good. If you want bools in code you must convert something else. This forces you too choose your own representaion. You could choose `u32` = 0 false, 1 = true. you could choose `u32` with each bit as a bool. etc...


Bool would still not be allowed in storage buffers, uniform buffers,  in user-defined pipeline inputs / outputs, or push constants / "immediate".

**Comment by jimblandy** [comment]
> * The representation we choose must avoid spuriously introducing data races. For example, concurrent accesses to adjacent bool scalars must not spuriously race: different invocations accessing s.a and s.b should not accidentally race.
> ```
> struct S { a: bool, b:bool } 
> ```

A reader of the spec needs to be able to know that different invocations can access a and b without racing. How does the spec promise this? Does establishing the size of bool somehow answer this question?

**Comment by dneto0** [comment]
Question

> A reader of the spec needs to be able to know that different invocations can access a and b without racing. How does the spec promise this? 

From [13.5.1 Memory operation](file:///Users/dneto/project/gpuweb/wgsl/index.html#memory-operation) it says:

> Read and write accesses do not occur under any other circumstances. Read and write accesses are collectively known as [memory operations](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#memory-model-memory-operation) in the Vulkan Memory Model.

> A memory operation accesses exactly the set of [locations](https://github.com/gpuweb/gpuweb/issues/4972#memory-locations) associated with the particular [memory view](https://github.com/gpuweb/gpuweb/issues/4972#memory-view) used in the operation. For example, a memory read that accesses a [u32](https://github.com/gpuweb/gpuweb/issues/4972#u32) from a struct containing multiple members, only reads the memory locations associated with that u32 member.

> Note: A write access to a component of a vector may access all memory locations associated with that vector.

That latter carveout is required by Metal.

-------------
Question
>  Does establishing the size of bool somehow answer this question? 

No. But it makes life palatable for implementors.

**Comment by dneto0** [comment]
> But it makes life palatable for implementors.

Meaning.  If WGSL made bools 1 byte, then on several backends, that would have to be emulated in a 4-byte scalar access.  That would induce races to adjacent bytes in the same word, unless you used a spin  loop with atomics.  And even then you probably don't get the forward progress guarantees to *know* that that works.   (Also the IHVs wince when you do that; ask me how I know.  :-)  )
