### ISSUE TITLE
Compat: Limit the number of sample/texture combinations

### ISSUE THREAD

**Issue by greggman** [gpuweb/gpuweb#4986]
In core you can bind 16 textures and 16 samplers (or more). You can use every sampler with every texture (256 combinations). GL can't do that many as every texture unit is tied to specific sampler.

In other words

```wgsl
@group(0) @binding( 0) var t00: texture_2d<f32>;
@group(0) @binding( 1) var t01: texture_2d<f32>;
@group(0) @binding( 2) var t02: texture_2d<f32>;
...
@group(0) @binding(15) var t15: texture_2d<f32>;

@group(1) @binding( 0) var s00: sampler;
@group(1) @binding( 1) var s01: sampler;
@group(1) @binding( 2) var s02: sampler;
...
@group(1) @binding(15) var s15: sampler;

...
   c += textureSample(t00, s00, uv);  
   c += textureSample(t00, s01, uv);  
   c += textureSample(t00, s02, uv);  
   ...
   c += textureSample(t00, s15, uv);  

   ...

   c += textureSample(t01, s00, uv);  
   c += textureSample(t01, s01, uv);  
   c += textureSample(t01, s02, uv);  
   ...
   c += textureSample(t01, s15, uv);  

   ...

   c += textureSample(t02, s00, uv);  
   c += textureSample(t02, s01, uv);  
   c += textureSample(t02, s02, uv);  
   ...
   c += textureSample(t02, s15, uv);  

   ...
   ...

   c += textureSample(t15, s00, uv);  
   c += textureSample(t15, s01, uv);  
   c += textureSample(t15, s02, uv);  
   ...
   c += textureSample(t15, s15, uv);  
```

[example](https://jsgist.org/?src=d6065e0cabd4d4a5f47aac163c7c4768)

Off the top of my head, rather than add some new limit, maybe just state that the number of combinations of samplers and textures can't be > `min(maxSampledTexturesPerShaderStage, maxSamplerPerShaderStage)` in compat?

I'm not sure if that would have any implications for arrays of textures and samplers (https://github.com/gpuweb/gpuweb/issues/822) since it might be hard to check the combinations assuming you can access textures with non-const values. Though I think that restriction exists in GLSL ES 3.1 - "Arrays of samplers may only be indexed by constant-integral-expressions."

**Comment by kainino0x** [comment]
> Off the top of my head, rather than add some new limit, maybe just state that the number of combinations of samplers and textures can't be > `min(maxSampledTexturesPerShaderStage, maxSamplerPerShaderStage)` in compat?

This seems reasonable. It sounds like all three of these limits come from the same underlying limit anyway? (you mentioned `GL_MAX_TEXTURE_IMAGE_UNITS`)

**Comment by teoxoy** [comment]
Yeah, looking at some ES 3.1 reports I think we can rely on a "max image units per stage" of 16.

[`MAX_VERTEX_TEXTURE_IMAGE_UNITS` (for vertex shaders)](https://opengles.gpuinfo.org/displaycapability.php?name=GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS&esversion=3)
[`MAX_TEXTURE_IMAGE_UNITS` (for fragment shaders)](https://opengles.gpuinfo.org/displaycapability.php?name=GL_MAX_TEXTURE_IMAGE_UNITS&esversion=2)
[`MAX_COMPUTE_TEXTURE_IMAGE_UNITS` (for compute shaders)](https://opengles.gpuinfo.org/displaycapability.php?name=GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS&esversion=31)
[`MAX_COMBINED_TEXTURE_IMAGE_UNITS`](https://opengles.gpuinfo.org/displaycapability.php?name=GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS&esversion=3)

If we set `maxSampledTexturesPerShaderStage` & `maxSamplerPerShaderStage` to `min(MAX_VERTEX_TEXTURE_IMAGE_UNITS, MAX_TEXTURE_IMAGE_UNITS, MAX_COMPUTE_TEXTURE_IMAGE_UNITS, MAX_COMBINED_TEXTURE_IMAGE_UNITS / 2)` (16 by default).

Then we can say that in compat that the number of combinations of samplers and textures + textures not used with any sampler needs to be at most `min(maxSampledTexturesPerShaderStage, maxSamplerPerShaderStage)`.
