### ISSUE TITLE
What's going on in Safari?

### ISSUE THREAD

**Issue by munrocket** [gpuweb/gpuweb#500]
1) Why Safari team stick to a new shader language for WebGPU that is differs from Spir-V (OpenGL 4.5) implementation in Chromium/Firefox?

2) Apple [announced](https://trac.webkit.org/wiki/WebKitGoalsfor2020) that Safari will implement WebGL2, but nobody worked on it so far. Somebody working on WebGL2 at all? This question closely related to WebGPU, because it can be a target for different compilers. I asked about this in many forums and directly to author of this announce in [twitter](https://twitter.com/tunrocket/status/1194340019298873344) but no one know the right answer.

**Comment by magcius** [comment]
> Why Safari team stick to a new shader language for WebGPU that is differs from Spir-V (OpenGL 4.5) implementation in Chromium/Firefox?

The question of shading language is still an open question inside the working group. Please be patient while this is decided.

> Apple announced that Safari will implement WebGL2, but nobody worked on it so far. Somebody working on WebGL2 at all?

There is work ongoing to make WebKit use ANGLE to implement WebGL 1 and 2. See this WebKit bug for details. https://bugs.webkit.org/show_bug.cgi?id=198948

**Comment by kvark** [comment]
This repository is for specification work, not questions about the implementations. You could file a bug on WebKit to pursue this further if the answer is insufficient.

**Comment by munrocket** [comment]
@magcius thanks, but it seems that nobody working on it `Assignee: | Nobody`.

While this can be not so hard as WebGPU and iPhone’s 6+ support OpenGL ES 3.1 as mentioned in [wiki](https://en.m.wikipedia.org/wiki/PowerV), they simply not implement it, if current status is right. Anybody from Apple?

**Comment by Kangz** [comment]
> This repository is for specification work, not questions about the implementations. You could file a bug on WebKit to pursue this further if the answer is insufficient.

And also this repository is about WebGPU, not the WebGL family of APIs. So please ask question on Safari's bug tracker or on WebGL's public mailing list. This bug tracker is not the right place.
