### ISSUE TITLE
Sparse array of GPUBindGroupLayout in GPUPipelineLayoutDescriptor?

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#502]
WebGPU has a 2D binding model as decided in #19 which is based on Vulkan's binding model.

Vulkan, however has a restriction where `VkPipelineLayoutCreateInfo` can't have a sparse array of `VkDescriptorSetLayout`s. The following is invalid in Vulkan:

```C++
VkDescriptorSetLayout setLayouts[] = { layout0, nullptr, layout1 };

VkPipelineLayoutCreateInfo createInfo;
createInfo.setLayoutCount = 3;
// invalid because setLayouts can't contain a nullptr inside
createInfo.pSetLayouts = setLayouts;
// ...
```

In WebGPU, should the following be valid?

```javascript
device.createPipelineLayout({
  bindGroupLayouts: [bgl0, undefined, bgl1]
});
```

It would be compatible with a shader that also has sparse `set`s:
```glsl
// (Vulkan-style GLSL)
layout(set = 0, binding = 0) ....
layout(set = 2, binding = 0) ....
```

I propose that we **not** expose the Vulkan limitation, and instead allow a sparse array of bind group layouts. In Vulkan, the restriction is easily worked around by either using an empty dummy `VkDescriptorSetLayout` to fill in the holes.

In D3D12, sparse layouts doesn't matter because the `D3D12_ROOT_DESCRIPTOR` explicitly states the RegisterSpace in the shader, so root descriptors can still be compatible with sparse layouts in the shader.

Metal 1 indexes resources using a flat index, so the 2D binding model is remapped to a 1D range anyway, and this isn't an issue.

In Metal 2, Argument Encoders are created using `newArgumentEncoderWithBufferIndex` which makes an encoder for argument buffers specified by index in the shader with `[[ buffer(0)  ]]`, `[[ buffer(1) ]]`, etc. @litherum Can these buffer indices in the shader be sparse?

**Comment by kvark** [comment]
Thinking about this from the *other* perspective, you are suggesting to *allow* `undefined` to be passed in this particular place in the API (`bindGroupLayouts`). My preference would be to reduce the expectations of `undefined` to a minimum, which would make it a stronger/cleaner API in languages that don't have implicit NULL.

The use case that such permission would allow is also not very convincing, especially considering how easy it is to work around:
```js
let dummyLayout = device.createBindGroupLayout({bindings: []});
```
With this in mind, my preference would be for a stronger API that doesn't expect `undefined`.

**Comment by austinEng** [comment]
It maybe be easy to work around, but it's also very easy for implementations to support and allow `undefined`. Permitting `undefined` reduces sharp corners of the API.

I understand your point about languages not having NULL. My pushback against this is that we're designing a Javascript API, and making an API decision because it doesn't map extremely well to other languages doesn't feel right. 

**IF** this were to be sparse, would your preference then to have it similar to bind group creation where the index is a member of the descriptor? This may be nice because it makes the `createPipelineLayout` API more consistent with the `createBindGroup` API.
```javascript
device.createPipelineLayout([
  {
    group: 0,
    bindGroupLayout: device.createBindGroupLayout(...),
  }, {
    group: 2,
    bindGroupLayout: device.createBindGroupLayout(...),
  }
]);
```

If I remember correctly, with `device.createBindGroup`, we made the decision not because of language ergonomics, but because there was a performance concern with sparse arrays in the hot path for applications that create bind groups on-the-fly.

**Comment by kvark** [comment]
I agree having this consistent with `createBindGroupLayout` would be good.

**Comment by kainino0x** [comment]
Revived in #2043
