### ISSUE TITLE
Should texture_depth_multisampled_2d have a template parameter?

### ISSUE THREAD

**Issue by afd** [gpuweb/gpuweb#5028]
[6.5.3. Multisampled Texture Types](https://www.w3.org/TR/WGSL/#multisampled-texture-type) says:

> The texture is parameterized by a [sampled type](https://www.w3.org/TR/WGSL/#sampled-type) and [must](https://www.w3.org/TR/WGSL/#shader-creation-error) be f32, i32, or u32.

However, in the table that follows, `texture_depth_multisampled_2d` does not have a `<T>` following it.

If this is intentional then it would make sense to spell out the exception. Otherwise, `<T>` should be added.

**Comment by greggman** [comment]
depth is always a single float value. That is why there is no template. It's not an exception. It just is. There's also no `vec1<f32>` and no `vec1f`

**Comment by afd** [comment]
It is an exception to the preceding statement:

> The texture is parameterized by a [sampled type](https://www.w3.org/TR/WGSL/#sampled-type) and [must](https://www.w3.org/TR/WGSL/#shader-creation-error) be f32, i32, or u32.

No?
