### ISSUE TITLE
I have a question about graphics card environmental issues.

### ISSUE THREAD

**Issue by redcamel** [gpuweb/gpuweb#507]
I am working on webGPU based on window canary
At home I am using GeForce 1050.
At company using  gtx560.
webgpu works fine ..on gtx560
It does not work properly on gtx1050.
Do you know why?

My personal project address is https://github.com/redcamel/RedGPU.

**Comment by Kangz** [comment]
No idea, and since you are using WebGPU I assume this is a Chromium bug. Can you file a bug on crbug.com, CC cwallez@chromium.org and provide information of your `about:gpu` page as well as minimal repro cases?

**Comment by cx20** [comment]
I have a problem similar to @redcamel in the latest version of the Chrome Canary environment.

![image](https://user-images.githubusercontent.com/1833979/69883672-85040f00-1318-11ea-84ad-f0035f1265f6.png)

In my case, it is probably related to the following problems. I think this problem occurs when `Skia Renderer` is enabled.
https://bugs.chromium.org/p/chromium/issues/detail?id=1021118

I tried adding `--disable-skia-renderer` or `--disable-direct-composition` to the startup options, but it didn't improve.  Until a while ago, there was a flag "Skia API for OOP-D compositing" that could be disabled, but this flag is not found in the latest version of Chrome Canary.

**Comment by redcamel** [comment]
@Kangz 
I sent the situation and chrome://gpu report to cwallez@chromium.org.

**Comment by kvark** [comment]
Closing as vendor specific (bugs should be filed to the browser vendor tracker, not here).
