### ISSUE TITLE
WebGPUCommandEncoderDescriptor doesn't appear to be defined anywhere in the sketch IDL

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#51]
https://github.com/gpuweb/gpuweb/blob/8ffe46f0aa74f949055625fa6c32b57fd00c57d9/design/sketch.webidl#L500

I ⌘-F'ed for it, but didn't see any definition.

**Comment by jdashg** [comment]
I'm running the webidl through our parser and have a number of fixes to make. This was one of them. I'll get it up later today.

**Comment by Kangz** [comment]
This was fixed when render pass and compute pass encoders were split off.
