### ISSUE TITLE
Read-only depth/stencil usage

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#514]
There are cases where depth or stencil need to be sampled in the middle of a pass. For example, in a deferred renderrer, after the G-buffer is resolved, when the transparent objects are drawn, they may want to use the depth information in the shader in order to carefully blend with the opaque objects.

D3D12 allows creation of views that are read-only for depth/stencil, with an ability to control it separately for depth and stencil (i.e. the same alpha pass may need to mutate the stencil).

Currently, `GPUTextureUsage::OUTPUT_ATTACHMENT` is considered a mutating usage, which makes it impossible to sample.

**Comment by Kangz** [comment]
I'm not sure I understand completely, do you mean that we should be able to have a depth-buffer that's used for depth-testing, but not for depth-writing, and sampleable at the same time? (with optionally the stencil plane being written to)?

It seems that it would require additions to pipeline-renderpass compatibility rules.

**Comment by kvark** [comment]
> do you mean that we should be able to have a depth-buffer that's used for depth-testing, but not for depth-writing, and sampleable at the same time?

Yes.

> (with optionally the stencil plane being written to)

D3D11/12 allows that, but I don't think we have that universally supported on Vulkan and Metal.

> It seems that it would require additions to pipeline-renderpass compatibility rules.

In what way?

**Comment by Kangz** [comment]
> > It seems that it would require additions to pipeline-renderpass compatibility rules.
> 
> In what way?

Somehow the depth buffer should be marked read-only at BeginRenderPass time for the usage validation, and if it is marked read-only, then we need to validate all of the render pipelines use `depthWriteEnabled=false`

**Comment by kvark** [comment]
Yes, we'll need that validation. It looks very straightforward.

**Comment by kvark** [comment]
I want to talk more about this. Here is a more concrete example:
  - user has a single render pass
  - there is one color attachment and one depth attachment
  - first, user renders an opaque terrain, which writes to both depth and color
  - second, user renders transparent water, which doesn't write to depth
  - more over, it wants to know the distance a ray of light has travelled under the water before hitting the terrain, in order to properly evaluate the water color

So in this second phase, they need to both use depth testing (so that they don't try to render the water where it's occluded by the terrain), and have that depth bound as a sample-able texture view.

In terms of `Usage` specification, it looks like we converged to a model where there is a set of user-facing usages (i.e. `STORAGE`), but the set of usages considered for usage validation is larger, i.e. some of the user flags are split. `STORAGE` textures can be used as "read-only" or "write-only", which means the implementation effectively treats the user flag as `STORAGE_READ` | `STORAGE_WRITE` (also see #542).

The same could be done for `OUTPUT_ATTACHMENT`, which in case of a depth texture would now mean `OUTPUT_ATTACHMENT | `OUTPUT_ATTACHMENT_READ`.

**Comment by kvark** [comment]
Here is a small investigation:

### D3D12
D3D12 allows specifying the [D3D12_DSV_FLAGS](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_dsv_flags) at the view creation. User can request depth, stencil, or both be read-only for this view (for the purpose of being a depth/stencil attachment).

D3D12 has `D3D12_RESOURCE_STATE_DEPTH_READ` and `D3D12_RESOURCE_STATE_DEPTH_WRITE` resource states. It's not entirely clear to me how one could use them when one component is writable and another isn't. Perhaps, we can transition depth and stencil to different states? The documentation for `D3D12_RESOURCE_STATE_DEPTH_WRITE` does mention the read-only flags as well as the depth writes, but doesn't exactly specify what happens there:
> when using it in a writable depth stencil view (see D3D12_DSV_FLAGS) when the PSO has depth write enabled (see D3D12_DEPTH_STENCIL_DESC).

@RafaelCintron @damyanp - maybe you could clarify? It's unclear what states need to be used to get, for example, writable stencil and read-only depth in the same pass.

### Vulkan

Vulkan doesn't appear to forbid this. [This thread](https://www.reddit.com/r/vulkan/comments/7k64qi/image_layout_for_readonly_depth_and_writable/) talks about the image layout: we can use `VK_IMAGE_LAYOUT_GENERAL`. Alternatively, if `VK_KHR_maintenance2` is supported, there are more efficient layouts for this: 
- `VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL`
- `VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL`
- `VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR`
- `VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR`
- `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL`

Therefore, the image layouts in Vulkan clearly made to support the separate flags for depth and stencil. The access flags don't have separate depth/stencil, and Vulkan (at least its basic version not augmented by extensions) requires that both depth & stencil are transitioned together. So I believe we'd use `VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT` if any of depth/stencil is writable, and `VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT` otherwise. Interestingly, Vulkan also has `VK_ACCESS_COLOR_ATTACHMENT_READ_BIT`, which could be interesting to apply, but I don't see D3D12 supporting this.

### Metal

I wasn't able to find any mention of this in Metal API specifically. I wasn't able to confirm that it's invalid either. I tried to make a small example that uses the depth buffer as both a shader-read texture, and a depth attachment with out writes. Unfortunately, I hit some bizarre depth testing behavior even outside of the tested read-only depth... filed FB7701997 for this.

I worked around the weirdness and got the texture read in the shader while it's depth-tested:
```
texture2d<float> depthTexture [[ texture(AAPLTextureIndexBaseDepth) ]]
...
    const float depthSample = depthTexture.sample(textureSampler, float2(0.5)).x;
    return float4(in.clipSpacePosition.z - depthSample);
```
It appears to work as expected, and no validation errors show up. See "Texture 0x10184dc00":
<img width="1150" alt="Screen Shot 2020-05-14 at 18 43 52" src="https://user-images.githubusercontent.com/107301/81993091-f7d91c00-9612-11ea-9a82-2a72e0f063b7.png">

Would be great to get some clarification from @litherum on whether this is allowed, or just missed by the validation. I'm hesitant to draw conclusions given the weirdness I saw with depth testing in general.

### Proposal

It appears to me that having both depth & stencil read-only is supported everywhere. Having them read-only independently is tricky, but could be possible, depending on more information we get.
Given that WebGPU today only works with a single texture for depth-stencil, I think that we can expose read-only depth/stencil with a requirement in #746 that `depthReadOnly` and `stencilReadOnly` are the same value if the texture has both of them. Later we'll look into lifting this requirement, as an option.

**Comment by kainino0x** [comment]
> with a requirement in #746 that `depthReadOnly` and `stencilReadOnly` are the same value if the texture has both of them.

We could allow them to be set separately, but for now only allow the actual read read if both flags are set. (Setting only one would still apply extra validation. But that's all, so not extremely valuable.)

**Comment by RafaelCintron** [comment]
> @RafaelCintron @damyanp - maybe you could clarify? It's unclear what states need to be used to get, for example, writable stencil and read-only depth in the same pass.

@kvark , in D3D12 depth and stencil are [separate subresources](https://docs.microsoft.com/en-us/windows/win32/direct3d12/subresources#plane-slice) that can be transitioned independently from one another using the [ResourceBarrier](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-resourcebarrier) API.  One subresource can be written to at the same time as another one can be read from.

**Comment by kvark** [comment]
Thanks @RafaelCintron !
So D3D12 and Vulkan appear to be fine with separate mutability of depth/stencil.

@litherum could you find out if Metal is good with this? More specifically, we are talking about a case where there is a single depth-stencil texture, and we are using a render pipeline that reads the depth, has mutable stencil mask and operations, and also samples the depth from the texture in the shader.
