### ISSUE TITLE
Use callbacks directly?

### ISSUE THREAD

**Issue by grovesNL** [gpuweb/gpuweb#52]
On the agenda for the next meeting, wait vs. poll vs. promise is listed.

Could we consider using callbacks directly? This approach seems like it would be possible to avoid the GC pressure associated with promises and not be concerned about blocking the main thread. It would also be easy to wrap into a promise if an application preferred the promise API instead.

**Comment by grovesNL** [comment]
I just noticed that @litherum [mentioned callbacks recently too](https://github.com/gpuweb/gpuweb/pull/49#discussion_r172776407).

**Comment by Kangz** [comment]
The has been resolved to have WebGPU use Promises for the time being. @jdashg made a PR for adding callbacks version of Promise entrypoints as well so we can have further discussion on that PR if needed.
