### ISSUE TITLE
Doesn't it support specs that can partially update the pipeline?

### ISSUE THREAD

**Issue by redcamel** [gpuweb/gpuweb#527]
Doesn't it support specs that can partially update the pipeline?

**Comment by kainino0x** [comment]
Sorry, could you ask again in a little more detail? I don't know what it means to "partially update the pipeline".

**Comment by redcamel** [comment]
@kainino0x I thought the pipeline update was slow. -_-
It was simply my js scope problem.
close the issue. sorry
