### ISSUE TITLE
Is support for multiple swapchain part of the spec?

### ISSUE THREAD

**Issue by frzi** [gpuweb/gpuweb#530]
The spec says [`configureSwapChain()`: Configures the swap chain for this canvas](https://gpuweb.github.io/gpuweb/#dom-gpucanvascontext-configureswapchain), implying that one can use multiple canvas elements and render to them using a single WebGPU context. People coming from a WebGL background may still be inclined to believe WebGPU is bound to a single canvas.

As of now configuring more than one swapchain in Chrome Canary renders the canvas completely black. But I realize WebGPU implementations in browsers are of course still far from complete. :)

Curious if multiple swapchain support is a feature to expect when the first MVP launches, as I truly believe this will open a new world of possibilities.

**Comment by kvark** [comment]
I don't see a reason why the user wouldn't be able to use multiple swapchains (attached to multiple canvases) with the same device (or multiple devices of the same WebGPU instance). The Chrome behavior is likely a bug. We'll make sure the specification is clear about this!

**Comment by Kangz** [comment]
The intent in the spec is to allow a single device to drive multiple swapchains. Same in Chromium's implementation but we never tested it. Please file a bug on crbug.com/ and CC cwallez@chromium.org. The content of about:gpu and a simple repro would help.
