### ISSUE TITLE
The ` = {}` syntax in the WebIDL is incorrect

### ISSUE THREAD

**Issue by tomaka** [gpuweb/gpuweb#533]
I've been trying to parse the WebIDL of the specifications programmatically.
However the specs contain at several locations the ` = {}` syntax ([example](https://github.com/gpuweb/gpuweb/blob/70be08a5a8f2ec665011aa1857662b346a6dd36d/spec/index.bs#L447)), which isn't correct according to [the WebIDL specs](https://www.w3.org/TR/WebIDL-1/#prod-DefaultValue).

**Comment by tomaka** [comment]
Oh I see, it is correct according to [the latest WebIDL draft](https://heycam.github.io/webidl/#idl-dictionaries).

> When a boolean literal token (true or false), the null token, an integer token, a decimal token, one of the three special floating point literal values (Infinity, -Infinity or NaN), a string token, the two token sequence [], or the two token sequence {} is used as the default value, it is interpreted in the same way as for an operation’s optional argument default value.

**Comment by kainino0x** [comment]
Yup, this is a recent change in WebIDL. #449 introduced most of these in our spec, https://github.com/heycam/webidl/issues/758 / https://github.com/heycam/webidl/pull/750 in webidl
