### ISSUE TITLE
STORAGE_READ usages for buffers and textures

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#541]
Partially implemented by #532 (textures only, also I think we can bikeshed the name).
Related to #513, also distantly to #514 

#303 introduced the read-only bindings. So technically, today, when there is a `STORAGE` usage, it could be read-only, or it could be read-write. The difference affects whether we allow any other usage to co-exist within the synchronization scope. Therefore it's difficult to both reason about and properly specify `STORAGE` usage today.

We could make this entirely clear by splitting the `STORAGE_READ` out of `STORAGE`, leaving the latter to be strictly mutable.

**Comment by Kangz** [comment]
Thanks for putting this together. I agree that the validation rules would be easier to express with explicit readonly usages but I'm not sure there's any benefit to developers in having split usages. Can't we just have the validation rules say you can't use as `STORAGE` in a writable way at the same time as other readonly usages?

**Comment by kvark** [comment]
For developers, we can define `STORAGE` bitmask in such a way that it includes `STORAGE_READ`, so they don't need to change anything.

For the spec, having the usage `STORAGE_READ` effectively present but not dedicated means that it will have to be specified conditionally, e.g. `STORAGE` usage is unique because it depends on the bind group layout flag Xxx, and then we'll need to be referring to it from the spec when enumerating read-only usages versus mutable ones. Seems awkward a bit.

**Comment by Kangz** [comment]
Following the 2020-01-13 I think `STORAGE_READ` is a good way to go as long as it is implied by `STORAGE`.

**Comment by kvark** [comment]
We now have separate internal usage flags from user-visible flags. And internally we have read-only storages.
For the user side, I think the simpler we approach this the better, and adding one more flag bit doesn't make it simpler.
Closing.
