### ISSUE TITLE
(Almost) render-feedback 

### ISSUE THREAD

**Issue by krogovin** [gpuweb/gpuweb#544]
I do not recall seeing something akin to having a restricted view of a texture (for example only allowed to see a named mipmap LOD). The use case I have in mind is mipmap generation. A natural way to generate mipmap level N + 1 is to create a render target backed by level N + 1 and have the fragment sahder read from mipmap level N and the fragment shader could be a filter (with box filtering the most common). 

One common argument to not do it this way is that compute can do the job. However, for most GPU's (desktop or tiled) going the compute route to generate mipmaps will harm performance

1. Plenty of GPU's (like any PC GPU from the last 2+ years) implement lossless color compression. The upshot is that it reduces bandwidth consumption on writes, and in addition, reduces bandwidth consumption on reads. These works seamlessly with 3D rendering (because the compression is done on render cache eviction) but not with compute. In order to get the lossless compression, a GPU would have to run the mipmap level through the 3D pipeline to get the compression.
2. Tiled based renderers are also harder hit as they compress render data when it leaves the tile and the tile buffer is typically unavailable for use by compute shaders.

**Comment by Kangz** [comment]
The usage validation rules should allow for mipmap generation like you are describing: there is no render feedback because you are sampling from a view that doesn't contain the mipmap you are rendering to.

That said Chromium doesn't implement proper tracking of subresources for validation and that case is broken at the moment. Fixing that is in our short term TODO list.

**Comment by krogovin** [comment]
Now I wished I checked things more closely. My apologies for missing the use of view for this.
