### ISSUE TITLE
Using buffer with multiple usages in the same compute pass

### ISSUE THREAD

**Issue by hugoam** [gpuweb/gpuweb#547]
The case came up in a question to @kainino0x of whether or not it should be allowed to use a buffer multiple times in the same compute pass with different usages.

A common example would be 
1. the compute dispatch filling commands in an indirect buffer
    (write usage `wgpu::BufferUsage::Storage`)
2. dispatching the resulting compute commands written in that indirect buffer
    (read usage `wgpu::BufferUsage::Indirect`)

**Comment by kvark** [comment]
The spec defines what a [sync scope](https://gpuweb.github.io/gpuweb/#usage-scopes) is in general but doesn't concretely define what it corresponds to in the API. We will cover that in the near future!

Basically, an individual Dispatch() in a compute pass defines a scope today. This means you can have the same buffer used by different means in different dispatches of the same compute pass, but not within the same dispatch (unless it's a combination of read-only usages). We reserve the right to add an option later to extend the usage scope to the whole compute pass, but there is no agreement/discussion about this yet.

You can also check slides 41-42 of the [Fosdem 2020 talk](https://github.com/kvark/slides/blob/master/BuildingWebGPUwithRust_Fosdem2020.pdf) about WebGPU.

**Comment by kainino0x** [comment]
I completely forgot we had that part in the spec already!

The reason I wasn't sure was because I wasn't sure if it was "compute passes are different in that the scopes are dispatch-sized" or "compute passes have the same validation rules, but implicitly synchronize valid usages with races (such as STORAGE across multiple dispatches), unlike in render passes which allow races there".

**Comment by kvark** [comment]
You raise a good question, I haven't considered the latter approach. I thought, since we are inserting barriers anyway, we might as well support different usage between dispatches.

**Comment by kainino0x** [comment]
Discussed at F2F. Resolved: "compute passes are different in that the scopes are dispatch-sized".

I.e., using a buffer as STORAGE and INDIRECT in the same pass *will be* allowed.

**Comment by Kangz** [comment]
This resolution has been encoded in the spec. Closing.
