### ISSUE TITLE
Status of exposing dedicated/integrated GPU through adapter?

### ISSUE THREAD

**Issue by jon-chuang** [gpuweb/gpuweb#550]
It seems the browser-selected GPU is chosen by default.

According to #132 this is to guard against fingerprinting.

How could a user, say on firefox, force the use of the dedicated GPU, say?

**Comment by kainino0x** [comment]
I don't think anyone implements it yet, but just like WebGL, we have [`powerPreference`](https://gpuweb.github.io/gpuweb/#dom-gpurequestadapteroptions-powerpreference).

The reason we (Chrome) hasn't implemented it yet is that it hasn't been a priority, not because of fingerprinting.

**Comment by kainino0x** [comment]
Spec does and already did have powerPreference, we just need to write spec for it. Closing this as it's more of an implementation question at this point.
