### ISSUE TITLE
Can't map half a buffer

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#555]
Neither `GPUDevice.mapReadAsync()` and `GPUDevice.mapWriteAsync()` allow you to only map part of a buffer. On an implementation which has to copy the data around, rather than _actually_ mapping, this can cause a lot of unnecessary data having to be copied.

**Comment by litherum** [comment]
https://github.com/gpuweb/gpuweb/pull/506 fixes this (seemingly as a drive-by)

**Comment by kvark** [comment]
For the uploads, #509 approaches this issue from a different angle.

**Comment by Kangz** [comment]
Fixed by the approach in #605
