### ISSUE TITLE
[wgsl] Lexical Scoping

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#559]
The desire for lexical scoping came up at the F2F. Currently WGSL is function scoped, similar to var in Javascript. This makes things simple, and maps nicely to SPIR-V as it is also function scoped.

One use case for lexical scoping is for generators which use snippets to create their programs. With lexical scoping, wrapping a snippet in `{}` contains it, otherwise you have to make sure all variable names match. Or, you move your snippets into functions which would also work I beleive.

So, thoughts on lexical scoping?

@litherum @kvark @dneto0

**Comment by kvark** [comment]
SPIR-V requires that one can only use SSA values that are coming from the dominant block in a Control Flow Graph. I think, lexical scoping would make the value visibility be strictly a subset of the dominant blocks (and consequently, valid for translating into SPIR-V's SSA). So it makes sense for *value*.

Variables, however, adhere to different rules:
> All OpVariable instructions in a function must be in the first block in the function. These instructions, together with any immediately preceding OpLine instructions, must be the first instructions in that block.

So variables in SPIR-V are truly scoped to functions are are declared at the start. I think, for the sake of keeping the mapping to SPIR-V straightforward, we should *not* have lexical scoping for variables.

For the use case of combining the snippets together, we can suggest people to share snippets as whole functions. We can expect these functions to be in-lined (or do it ourselves on the IR) when compiling the final shader.

**Comment by Kangz** [comment]
I don't think lexical scoping causes problems for the bijectivity with SPIR-V, and all we need to decide is what are the validation rules for scoping in WGSL.

For `OpVariable`, translation from SPIR-V to WGSL is trivial since it's just a matter of declaring a bunch of variables at the top of the function, and prepending the SPIR-V ID number of two of these variables have conflicting names.

For the WGSL to SPIR-V direction, what @kvark suggested works.

Given transparent bijectivity is not compromised, I think it is worth adding the lexical scoping because it makes the language more predictable for developers, and more composable.

**Comment by litherum** [comment]
> Or, you move your snippets into functions which would also work I beleive.

Moving snippets into functions is complicated enough that it caused WGSL to include a "continuing" block. If it's too hard for us, we probably shouldn't force shader authors to do it.

**Comment by litherum** [comment]
Consider:

```WGSL
fn foo() -> void {
}
```

**Comment by othermaciej** [comment]
I think we should have lexical scoping. 

(1) Lack of proper lexical scoping is retrograde. Languages that started with function-scope variables or declarations required to be at the top of a function have generally fixed this. Code is easier to write and easier to read when variable declarations are near the point of use.

(2) The transformation to SPIR-V will still be fairly simple. All that's required is hoisting and renaming in case of conflict.

(3) The transformation from SPIR-V is unaffected. There's no need to try to take advantage of lexical scope going in this direction.

Overall, the benefit to developer ergonomics and comprehensibility outweighs the small complexity cost in my opinion.

**Comment by litherum** [comment]
Bump. This is one of the highest priority issues from Apple's point-of-view.

**Comment by kvark** [comment]
The argument for lexical scoping is basically that people expect it from a human writable language.
The argument against is that it doesn't match SPIR-V semantics. Since it's trivial to convert into SPIR-V, it seems reasonable to have that feature.

**Comment by kainino0x** [comment]
I don't think it's meaningful that SPIR-V doesn't have lexical scoping. SPIR-V doesn't have nested blocks to begin with. Renaming isn't even much of a concern because everything eventually has to be renamed into a number anyway.

I like lexical scoping, but the argument that matters to me is that it increases implementation complexity (not clear by exactly how much).

**Comment by dneto0** [comment]
Sorry I didn't respond earlier.

Lexical scoping is good.  WGSL should have it.

I think "bijectivity" can be addressed with hoisting and perhaps a hint.  I'd like to work out details before getting too specific.

**Comment by dneto0** [comment]
One challenge with hoisting is that you have to do extra work for pointers.  Pointers are, by rule, not storable, i.e. they can't be stored in a variable.  I've been discussing options internally about what to do here.

**Comment by grorg** [comment]
Discussed at the [2020-04-14 meeting](https://docs.google.com/document/d/1bdIA5GS0yMDXcHZ0U_CtxYp6jLfJqVlGPBgcQ0aOEkc/).

**Comment by grorg** [comment]
Resolution:

- We accept that we will have lexical scoping
- We will add specification text
- @dneto0 will raise an issue on some particulars
