### ISSUE TITLE
[wgsl] Implicit types for variable declarations with expressions.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#560]
This came up at the F2F. Currently all `var` and `const` require the type to be supplied. This is redundant in the case where an initializer is provided and we can determine the type.

The proposal at the F2F was to make the type optional. The grammar would become:

```
var <id> [: <type>]? [= expr]?
```

Where the type is optional if `expr` is provided and we can determine it.

**Comment by Kangz** [comment]
> Where the type is optional if expr is provided and we can determine it.

Ideally the type of `expr` always be known (no implicit promotion, ...) so the grammar would exectly require at least one of `[: <type>]` or `[= expr]`.

**Comment by dj2** [comment]
It could, but if I _want_ to write `var a : i32 = 1;` is there any reason to force me to write `var a = 1;`? I often use `auto` but sometimes I don't when I get confused as to what the thing is, or want to make sure the thing I'm feeding it on the right is correct.

**Comment by Kangz** [comment]
Sorry what I meant is that "if ... we can determine it" isn't needed because we can always determine it. The only condition in the spec would be `type is present || initializer is present`.

**Comment by dj2** [comment]
Right, I just don't want to disallow `type && initializer` as sometimes I like to say both (same with I like to add `()`s when precedence rules would suffice)

**Comment by kvark** [comment]
I think we can split the question in 2 stages.

### Can the expression type always be inferred?

For example, in Rust expressions on the right are not always having the concrete type, e.g.
```rust
let x = 1;
```
There is a default here, but we can change the type of an expression by annotating the left side:
```rust
let y: i32 = 1;
let z: u8 = 1;
```
So Rust doesn't have this property, and neither does SPIR-V. It has instructions, whose semantics is affected by the result type, e.g. `OpCopyLogical`. See https://github.com/gfx-rs/rspirv/issues/103#issuecomment-534362967 for more info.

On the other hand, we know that in *most* cases the type can be inferred. And it's a short stretch to make it true for *all* cases. The casts, for example, could have generic arguments for the type, e.g. `cast<i8>(...)`, and I believe Tint already had that at start. So we can easily make this property true if we want.

Personally, I think it's a useful property to have, and we should enforce it.

### Can/should the type be explicitly specified?

If we can infer the type in all cases, we have an ability to say that type annotations are not required. However, for the sake of sanity and readability, it's often desirable to allow specifying the type anyway (as in https://github.com/gpuweb/gpuweb/issues/560#issuecomment-592010363).

Essentially, this would work as a compile time assertion `typeof(something) == type`. It could even be expressed as a function: `assert_type<i32>(x)`, such that we don't introduce any new syntax here.

Again, I believe it's valuable to let the user do this type assertion one way (via special syntax) or another (built-in generic function).

**Comment by magcius** [comment]
99% of the time, in a shader, you want floats. Integers are rare.

Some exceptions to this:
* array indexing (the most common case, though often this is with literals)
* bitwise math (relatively uncommon but not unheard of)
* packing/unpacking logic (similarly relatively uncommon, but usually shoved to the side in one place). Usually, you do a bitwise cast a la asuint/asfloat anyway. GLSL has conveniences like packFloat2x16 for this. Most game engines have a vendored copy of the infamous [D3DX_DXGIFormatConvert.inl](https://github.com/apitrace/dxsdk/blob/master/Include/d3dx_dxgiformatconvert.inl), which does all the dirty work for you.
* emulators (Dolphin uses tricky integer ALU math for all of its shaders to emulate fixed-point HW)

So there's a part of me that says `var foo = 3;` giving you back an integer feels wrong and backwards from a shader ergonomics perspective. GLSL requiring `.0` suffixes everywhere is a pretty major stumbling block for both people writing shader translators and people writing shaders, and as I've mentioned before, integers can lead to some big ALU perf issues, especially if there's no good place to put a compile-time warning.

HLSL and GLSL both require a type in the declaration: `float foo = 3.0;`. GLSL has no implicit int -> float conversion, but it does have some small affordances, e.g. type constructors now sometimes allow integers as shorthand, `vec3(0)` is equivalent to `vec3(0.0)`.

For that reason, drawing on the judgment and experience of shading languages before it, I recommend that we do not infer variable types.

An alternate suggestion would be to make the literal syntax `3` produce a float, and require `3i` syntax or something to produce an integer.

**Comment by jdashg** [comment]
I think @kvark said it well.

One dimension related to this is that we still need type declarations for arguments to functions. (Unless we aren't having functions?) We should probably talk about those elsewhere, but if they take arguments, they'll need type declarations somehow.

I think my favorite compromise is:
1. ok: `let x = cast<i32>(1);`
2. ok: `let x : i32 = 1;`
3. forbid: `let y : i32 = x;`
4. ok: `let y = cast<i32>(x);`

(2) is optional to me. Requiring (1) is appealing architecturally, but it definitely looks a lot more foreign than (2), which makes (2) appealing stylistically. We'll get used to any syntax eventually, but it's nice to consider nice things.

**Comment by Kangz** [comment]
Closing this. Type omission is now in the WGSL spec.
