### ISSUE TITLE
[wgsl] Specialization constants, function constants, or other forms of shader modularity

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#572]
Specialization constants are currently not represented in WGSL. They should be added into the language.

**Comment by litherum** [comment]
I'd rather not jump to one specific form of solution. There are many different ways of achieving the goals of authors.

See the analysis in https://github.com/gpuweb/WSL/issues/1

**Comment by grorg** [comment]
Discussed at the [2020-06-24 WebGPU Virtual F2F](https://docs.google.com/document/d/1uv0LiQB2gAFbUEU3qx2-Sgsv6r3fEKMvnifbFoRbvmw/).

**Comment by kvark** [comment]
To clarify the F2F discussion, the group agreed on supporting the specialization constants with a few limitations:
  - can only be used for expression values, no specialization of array sizes or work group sizes, for now
  - have to have a default value, it's not necessary to provide the value at the pipeline creation (default is used in this case)
  - does not affect the shader interface

**Comment by chinedufn** [comment]
If you use specialization constants in SPIR-V then translate your SPIR-V to WSL, is it expected that (after naga and tint are ready) your constants will still work?

Specialization is important to me so looking to gauge whether or not I need to write WSL in order to make use of it in WebGPU.

Thanks!

**Comment by kvark** [comment]
We'll definitely try to preserve the spec constants when translating SPIR-V to WGSL. Just beware that WGSL's version is less powerful: you can't specialize array sizes for example. So some shaders will still not pass this conversion.

**Comment by chinedufn** [comment]
Got it thanks a lot!
