### ISSUE TITLE
[wgsl] Samplers

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#574]
Need to add samplers into WGSL.

**Comment by Kangz** [comment]
WebGPU has two different types of samplers: "sampler" and "comparison-sampler". WGSL should have different types (or type parameters) for these to check compatibility with the `GPUBindGroupLayout` at pipeline compilation time.

**Comment by kvark** [comment]
I also thought it would be good to separate them at the type level in WGSL, and that would match WebGPU BGL entry nicely. However, there is a counter argument on the table:
it looks like in *no* shader languages out there the sampler declaration is different for comparison/non-comparison. So we are signing ourselves up for some headache in the tools producing WGSL...

**Comment by Kangz** [comment]
Closing. Samplers were added to WGSL.
