### ISSUE TITLE
[wgsl] Numeric sizes

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#575]
Currently WebGPU only handles 32-bit float and int types. In the future if other sizes are added, how do we want to handle determining the value type in WGSL?

Something like:

```
1.f16
1i8
.1f64
```

If so, should we add a `f32` and `i32` suffix now?

If you have `f32` suffix can you do `1f32` and drop the `.`?

**Comment by litherum** [comment]
Could also use the `h` and `d` prefixes for floats.

**Comment by dj2** [comment]
The types would be `f16`, `f32` and `f64` so using `h` and `d` seems inconsistent. There is also `bfloat16`, not sure how that would fit in at the moment `bf16`?

**Comment by jdashg** [comment]
This is extremely related to #560.

**Comment by kvark** [comment]
@dj2 currently in WGSL there is still no way of defining proper unsigned literals. This is very limiting, especially when porting existing code from other languages. Can we take action on this and prioritize discussing it?

**Comment by dj2** [comment]
What do you mean by proper unsigned literals? `1u` is an unsigned literal which is in spec now.

**Comment by kvark** [comment]
I always thought the current `u` suffix is provisional, in a way that we got this as a starting point and wanted to get something decent instead, i.e. with type inference or proper suffixes. But now chatting about this on Matrix, looks like `u` suffix could be forward compatible.

**Comment by Kangz** [comment]
Tentatively closing in favor of #1986. The landscape changed a lot with the literal unification work as well.
