### ISSUE TITLE
[wgsl] Remove "unless" statement

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#577]
Every time I see it, regardless of the source programming language, I always have to do mental gymnastics to figure out which situations causes its "then" block to execute.

I'm thinking of something like this:

```
unless (!a() || b()) { ... }
```

Most of the time I see it, it actually _decreases_ clarity.

**Comment by dneto0** [comment]
Any construct can be abused.

The bad readibility is  the coder's problem. The purpose of "unless" is to avoid an otherwise useless negation.

Instead of:
  
     bool done = ....
     ...
     if (!cond) { blah(); }


use this:

      unless (done) { blah(); }

What would be silly, and is not in the current proposal is 

      unless (cond) { false_case(); }  else { true_case(); }

That's not permitted in the grammar, as it can be written as:

      if (cond) { true_case(); } else { false_case(); }

**Comment by magcius** [comment]
What is the goal of allowing `unless (done())` instead of `if (!done())` ? Is there something that makes the former drastically more optimizable or efficient to dedicate syntax to it?

**Comment by litherum** [comment]
```
bool done = ....
 ...
 if (!cond) { blah(); }
```

Did you mean

```
bool done = ....
 ...
 if (!done) { blah(); }
```

?

**Comment by othermaciej** [comment]
Many Lisps have `unless`. Notably both Scheme and Common Lisp do. So do Ruby and Perl. It doesn't seem to be terribly confusing in those languages. AFAIK it's not present in any C-like languages though, and it doesn't seem to add a meaningful amount of additional expressiveness. Besides negating the condition, one could always write if (x) {} else { something; } if empty blocks are allowed.

I don't think it's all that harmful, but perhaps language complexity points are better spent elsewhere, if there is a limited budget.

**Comment by jdashg** [comment]
Would `if not` be better?

**Comment by dneto0** [comment]
Thanks for the correction, @litherum 

I should have written:

What would be silly, and is not in the current proposal is 

      unless (cond) { false_case(); }  else { true_case(); }

That's not permitted in the grammar, as it can be written as:

      if (!cond) { true_case(); } else { false_case(); }

.

But that rewrite is actually is contrary to my goal of avoiding injecting useless negations.

**Comment by jdashg** [comment]
I do think it's worth considering:
`if (foo && bar)` => ~OpIf
`if (!foo && !bar)` => ~OpIf
`if (!(foo && bar))` => ~OpUnless

**Comment by dneto0** [comment]
"Simple bijectivity" with SPIR-V and LLVM-like languages (which I'll talk about
in #582) is a root motivation for having "unless".

Consider this LLVM fragment:

```
  ...
  %call = call zeroext i1 @question(i32 %a, i32 %b) #2
  br i1 %call, label %if.end, label %update.answer

update.answer:
  store i32 42, i32* %answer, align 4
  br label %if.end

if.end:
  %c = load i32, i32* %answer, align 4
  ...


```

So the store should occur if and only if the condition is false.

This translates directly to:

```
    callresult = question(a,b);
    unless (callresult) {
      answer = 42;
    }
    c = answer;
```

If I don't have `unless`, then I have to insert a negation:

```
    callresult = question(a,b);
    if (!callresult) {
       answer = 42;
    }
    c = answer;
```

or use @othermaciej's empty-true-clause technique:

```
    callresult = question(a,b);
    if (callresult) {} else {
      answer = 42;
    }
    c = answer;
```

Inserting the extra negation is a non-starter because it adds instructions or complexity to round-tripping.

The empty-true-clause technique is uglier than `unless`, and adds complexity to round-tripping.

**Comment by othermaciej** [comment]
Surely aesthetics shouldn't count for a construct that is only meant for the benefit of round tripping.

The extra complexity for detecting empty "then" block or negated if condition seems low to me. It shouldn't be materially higher than an additional language keyword, and it's complexity kept within the implementation rather than externalized to authors.

I think the pattern matching idea is worth exploring at least to see what the complexity is.

**Comment by litherum** [comment]
@dneto0 Thanks, https://github.com/gpuweb/gpuweb/issues/577#issuecomment-593551495 was helpful. If I understand correctly, the intention is to represent the following SPIR-V:

```SPIR-V
      OpSelectionMerge %29 None              ; structured if
      OpBranchConditional %27 %29 %41        ; if cond
%41 = OpLabel                                ; else

      ... code here ...

      OpBranch %29
%29 = OpLabel                                ; endif
```

> Inserting the extra negation is a non-starter

As I commented in https://github.com/gpuweb/gpuweb/issues/582#issuecomment-593636617, we need to have a robust rationale for why inserting the negation is a non-starter, as compared to all the other modifications we could make which are acceptable.

In particular, I'm interested in the case where round-tripping (SPIR-V -> WGSL -> SPIR-V) has the following form:

1. The SPIR-V to WGSL compiler compiles the above to:
```
if (!var_27) {
    ... code here ...
}
```
2. The downstream WGSL to SPIR-V compiler recognizes that the `if` condition is entirely negated, and chooses to generate the `OpBranchConditional` pattern above, rather than emit the `OpLogicalNot`.

In this situation, round-tripping of the pattern above is preserved, and we automatically remove unnecessary `OpLogicalNot`s, thereby improving the user's program.

**Comment by dj2** [comment]
The problem is, once you've compiled to something other then unless and you need to pattern match it to go back, you don't know which you should go back too. You don't know if the negation was in the original SPIR-V and you should go back to that, or if the unless version was in the SPIR-V.

**Comment by kvark** [comment]
@dj2 does it matter though? It's not the first case of SPIR-V offering something different, and the translation to/from is not identical, and I don't think it's the last case either. I thought we are on the same page here when I read the "faithful" definition for a roundtrip that is very close, still fast, but not exact.

E.g. a thing I was looking earlier - `OpCompositeInsert` is not in WGSL, so doing a roundtrip will not get this instruction back necessarily.

**Comment by litherum** [comment]
(OpPhi is also not in WGSL)

**Comment by litherum** [comment]
> you don't know which you should go back to

Right. There are two ways it could “go back:” by inserting a negation, and by switching the labels of the conditional. The latter is always better, so either A) we’ve faithfully represented the original program or B) we haven’t faithfully represented it, but we instead improved it. It’s a win-win.

**Comment by dj2** [comment]
To be fair, WGSL isn't complete. If something like `OpCompositeInsert` is in the language would be an open question.

**Comment by kvark** [comment]
@dj2 that's totally fair! `OpPhi` is however not going to be there as it's forbidden by one of the design principles we've just discussed on the call :)

**Comment by grorg** [comment]
Discussed at the [2020-06-02 meeting](https://docs.google.com/document/d/1oGLtkcioUv-a4Fg6c5WgXxxeGo-Ut7IQd6_Y_XNK-Dc).

**Comment by grorg** [comment]
Resolution: remove the `unless` statement, but add `unless` to the set of reserved words.
