### ISSUE TITLE
[wgsl] Is the `regardless` statement really necessary?

### ISSUE THREAD

**Issue by othermaciej** [gpuweb/gpuweb#580]
WGSL has a strange conditional statement called `regardless`, which does the same thing regardless of whether its condition is true or false. It justifies this with:

> The `regardless` statement will probably not be used in most cases but exists to
handle a specific case in SPIR-V. If you have an `OpBranchConditional` where both
targets are the same block.

However, there are other options for translating SPIR-V that does such a strange thing. If the conditional expression has no side effects, then it could be translated as just the body. If the condition does have side effects, it could be assigned to a dummy variable or used in an if statement with an empty body. In other words (and pardon if syntax details are wrong), this:

```
regardless (arbitrary_expr)
{
    do_stuff_1();
    do_stuff_2();
}
```

could be written as this:

```
var some_generated_name = arbitrar_expr;
do_stuff_1();
do_stuff_2();
```

or as:

```
if (some_generated_name) {}
do_stuff_1();
do_stuff_2();
```

These should be identical even if the condition has side effects. These would be weird things to output, but they seem guaranteed to have the same control flow even for conditions with side effects, and they avoid adding a mysterious statement to the language.

**Comment by dj2** [comment]
Regardless is needed to generate SPIR-V where both labels of an `OpBranchConditional` point to the same label. So, if you want to be able to regenerate that same SPIR-V, you need `regardless` to tell you to generate that conditional.

**Comment by othermaciej** [comment]
I believe the alternative mappings I described are semantically equivalent to `regardless` and the if variant one particular could be used to generate the exact same blocks and opcodes (so long as empty blocks are optimized out and replaced by their successors in conditionals). If this is insufficient, please explain why.

**Comment by dj2** [comment]
This will depend on the definition of bijective. You don't know how to convert it back to SPIR-V if you don't have `regardless` You're basically picking one.

**Comment by othermaciej** [comment]
It seems to be something less that round tripping SPIR-V through WGSL and getting the identical bytes back, and certainly not vice versa. But I agree a clear statement of the requirement would clarify what is actually necessary to satisfy it.

**Comment by litherum** [comment]
There is another (corner case) difference. If you consider the loop conditional is non-uniform (meaning different GPU threads might evaluate it differently), then even if the "then" block is the same as the "else" block, certain operations which require uniformity are not allowed to execute inside that block.

On the other hand, the set of valid expressions in a uniform context is a strict superset of the set of valid expressions in a non-uniform context, so I suppose we would end up doing the author a favor if we promoted the non-uniform control flow to be uniform.

**Comment by othermaciej** [comment]
I do not understand what “loop conditional” means in this context. This construct is not a loop, at least not in the colloquial sense.

**Comment by litherum** [comment]
Whoops, I meant "conditional" instead of "loop conditional"

**Comment by dneto0** [comment]
Yes, @litherum, caught the prime semantics-based motivation.

It's an open question whether we're "doing the author a favor" by overdelivering on uniformity. 
There could be cases where allowing the threads (invocations) to temporarily diverge can help ease register pressure within the regardless block, thus allowing currently-active threads to steal/use register space from currently-inactive threads, and then swapping roles. The idea is that on a global scale you smooth out the lumpiness of register demand, so can launch more threads at a time, and get better overall utilization.
Allowing the developer to express the "it's ok to break uniformity here" could help performance.

FYI:  We have the same essential semantic consideration for the "premerge" part of if/else/premerge.  

From a program-representation perspective, `regardless` makes for more crisp round-tripping between WGSL and SPIR-V/LLVM.

**Comment by litherum** [comment]
> performance

Aha! You said the "p" word!

In order to make design decisions like this, we need some representation (possibly measurements) to know how much decisions like these affect real content. `regardless` might make performance go up, but it might also make performance go down. In Metal, we can't even represent the nuances of `regardless`, so we'll have to do the promotion unconditionally.

Our CG should strive to make rationales for decisions like this based on data rather than opinions, and, where possible, the calculations should be repeatable, so we can make different decisions in the future if the world somehow changes.

Or, stated differently: The procedure for debating the existing of a language feature can't be "ask @dneto0 whether or not he thinks it would affect performance." We need something more concrete.
