### ISSUE TITLE
[wgsl] Design Criteria for WGSL

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#586]
As we start to design more of WGSL I think we should lay out criteria for the design of the language and how we decide what is included. As a start, the criteria we've been working with are:

 * text based language
 * writable by programmers
 * cost free bijection #582 between WebGPU SPIR-V and WGSL and back
 * The bijection is simple and efficient, doesn't require an optimizing WGSL compiler
 * Directly represents structured control flow
 * Language is as small as possible to represent what we need
 * The burden is always to show why we must add something

Other considerations we should add to the list?

**Comment by dneto0** [comment]
Also:  strongly statically typed.

**Comment by litherum** [comment]
- writable _and readable_ by programmers
- not sure what "cost free" means
- "Language is as small as possible to represent what we need": this makes sense as a design goal, but it is much much less important than the "usable by real people" criterion
- Supporting simple and efficient compilation to MSL and HLSL
- "the burden" this is a procedural criterion, not a language criterion, and therefore shouldn't be in the list

**Comment by damyanp** [comment]
> Supporting simple and efficient compilation to MSL and HLSL

+1 

> "Language is as small as possible to represent what we need": this makes sense as a design goal, but it is much much less important than the "usable by real people" criterion

I'd lean to the "small as possible".  For me, "usable by real people" is a nice side effect, but not an important goal.  It's useful to be able to write tests in WGSL, but I think we should view it more as an intermediate language than a source language.

**Comment by litherum** [comment]
> we should view it more as an intermediate language than a source language.

Absolutely disagree. I don't mean to reopen fresh wounds, but the fact that people can use the shading language directly was hugely valuable for WebGL, and it is hugely valuable for WebGPU.

**Comment by jdashg** [comment]
As a WebGL spec editor and implementer for Firefox, I don't agree "that people can use the shading language directly was hugely valuable for WebGL", versus some of the other solutions in the problem space.

**Comment by Jasper-Bekkers** [comment]
> > we should view it more as an intermediate language than a source language.
> 
> Absolutely disagree. I don't mean to reopen fresh wounds, but the fact that people can use the shading language directly was hugely valuable for WebGL, and it is hugely valuable for WebGPU.

We don't need to reinvent WebGL, a convenient API already exists and it's WebGL. Let's build a good and usable one this time around.

**Comment by dneto0** [comment]
> Supporting simple and efficient compilation to MSL and HLSL

> cost free bijection #582 between WebGPU SPIR-V and WGSL and back

I'd be interested in hearing Microsoft's desires about the relation to DXIL.   Is there any consideration at all, and is it closer to the proposed relation to HLSL or to the proposed relation to SPIR-V.

If you squint, DXIL is very similar in spirit to SPIR-V, and there may be a desire for tight convertibility (yes, to be determined in #582) for DXIL as well.

**Comment by damyanp** [comment]
@litherum 
> the fact that people can use the shading language directly 

Without the syntactic sugar there is a still a language that people can use directly.  Is all the sugar required for a viable v1?  I don't think we do.  More important is that the acknowledgement that many users have an existing library of shaders that they'll want to make work with minimal modification with WebGPU.  In these cases the original source language will likely be some HLSL variant that can ultimately be compiled to WGSL (whether via WGSL emitted directly from the compiler or via some other IL).

Time spent on extending the language to make it a nicer source language increases the chance that we'll have to deal with inconsistent implementations and takes away time from support the (IMO) more valuable scenario described above.

@dneto0 
> I'd be interested in hearing Microsoft's desires about the relation to DXIL

We expect that most effort to ensure WGSL<->SPIR-V bijectivity will accrue to efficient translation to DXIL, but we will certainly be reviewing the spec with this in mind.

**Comment by grorg** [comment]
Discussed at the [2020-03-03 teleconference](https://docs.google.com/document/d/15Pi1fYzr5F-aP92mosOLtRL4qLczmVRWQaomfQmGNzo).

**Comment by grorg** [comment]
Closing this with the resolutions made at the meeting. Basically accepting all of @dj2's initial list plus @litherum 's item about MSL and HLSL generation.

**Comment by litherum** [comment]
I just made a [pull request](https://github.com/gpuweb/gpuweb/pull/599) with what I believe is the result of this conversation. Feedback is welcome.
