### ISSUE TITLE
[wgsl] Entry point input/output global variables

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#592]
In SPIR-V, `OpEntryPoint` lists the global variables used for inputs & outputs of a function.
Current WGSL spec doesn't have that. What is the suggested conversion to SPIR-V?

**Comment by dj2** [comment]
The current WGSL is based off of SPIR-V 1.3 which did not require the listing of the global variables. Newer SPIR-V does. @dneto0  should we be updating WGSL to use SPIR-V 1.5 now that it's released?

If we do that, we need to decide if we require all the globals used in an entry point to be listed in the `entry_point` command, or if we determine them automatically.

**Comment by litherum** [comment]
WebGPU targets Vulkan 1.1, because that’s what is present in the wild, and Vulkan 1.1 only requires SPIR-V 1.3. We shouldn’t be targeting SPIR-V 1.4 and later because it can’t run on the devices we’re targeting for WebGPU.

**Comment by kvark** [comment]
I didn't realize this is optional in SPIR-V 1.3, so technically in agreement with the comments (thanks!) this issue can be closed.

**Comment by dj2** [comment]
Sigh, I need to read the docs closer before commenting. 1.4 changes the requirements for ids associated to storage classes that aren't Input/Output.

1.3 states[1]: It is invalid for the entry point’s static call tree to reference such an <id> if it was not listed with this instruction.

So, we neither need these listed, or we need to calculate them. Sorry for the confusion.


1- https://web.archive.org/web/20190430051352/https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpEntryPoint

**Comment by kvark** [comment]
Thanks for double-checking!
> So, we neither need these listed, or we need to calculate them. Sorry for the confusion.

Perhaps, you meant "we **either** need these listed, or we need to calculate them"?

**Comment by dj2** [comment]
Fixed. Thanks, apparently today is not my day.

**Comment by kainino0x** [comment]
> WebGPU targets Vulkan 1.1, because that’s what is present in the wild, and Vulkan 1.1 only requires SPIR-V 1.3. We shouldn’t be targeting SPIR-V 1.4 and later because it can’t run on the devices we’re targeting for WebGPU.

I don't think this means we can't use SPIR-V 1.4/1.5. In cases where 1.4/1.5 are more expressive, it just means we drop some data when converting down to 1.0~1.3 (be it WGSL -> 1.3 or WGSL -> 1.5 -> 1.3).

**Comment by litherum** [comment]
> So, we either need these listed, or we need to calculate them.

Given that `Id`s don't exist in WGSL, it seems natural to calculate them.

**Comment by dneto0** [comment]
> Perhaps, you meant "we either need these listed, or we need to calculate them"?

My suggestion is the conversion from WGSL to SPIR-V would scan the code to see what's used.

However, this is a design choice that affects the API side, particularly the interface matching rules.  
For example, suppose an output variable from a vertex shader is written to, but then the fragment shader ignores that input.  If the fragment shader is "cleaned up" to delete that input, then we have to decide if the interface matching fails.  This also interacts with how inputs/output locations are counted or inferred.  I don't know that any of this has been designed on the API side.  But choices there affect the shader language rules.

**Comment by kvark** [comment]
It sounds like scanning and figuring out the inputs/outputs is a possible solution. Just a bit of an unfortunate one, since it's extra work for us to do, and any source coming from SPIR-V already knows that.

For the vertex stages matching, we could do the same as we (should) do for shader-pipeline matching:
  - all in/out locations have to be explicit (using appropriate decorators)
  - connection from one stage to another is valid as long as the output of one is a superset of the input of the other

**Comment by litherum** [comment]
I don’t think it makes sense to ask authors to list every Id in their program because:

1. This is gratuitous. It’s asking authors to fill out paperwork when all they wanted to do was add a temporary somewhere
2. Ids don’t even exist in their program, so asking them to list them doesn’t make any sense
3. There are ids which don’t correspond to names in the WGSL program. For example, the results of implicit loads from variables. The author has no way of listing those.

**Comment by kainino0x** [comment]
I've received two comment notifications from Myles on this thread via email, but both times when I opened GitHub the comment wasn't visible. Are those comments deleted?

**Comment by litherum** [comment]
Yes. I realized after posting them they were off-topic, and deleted them. (For some reason I keep thinking this thread is about the ["bound" field](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_physicallayout_a_physical_layout_of_a_spir_v_module_and_instruction) in the SPIR-V header)

**Comment by kvark** [comment]
Thinking about this some more, even if we do have the user to explicitly list input/outputs, we'd still have to go through the code and *validate* that these lists match what's being used. So if we have to do this regardless, might as well just derive this from the code to begin with. It would still need to be compatible with the pipeline layout.

**Comment by dneto0** [comment]
Hey @kvark, it looks like you're ok with having a WGSL-> SPIR-V converter scan the code?
That's my reading.

Also, I think your interface matching rules make sense : https://github.com/gpuweb/gpuweb/issues/592#issuecomment-597187471 
I believe the scanning heuristic will work:  if the variable is used in a fragment shader, then the scan will place it on the entry point instruction;  otherwise, we don't care.

I agree with @kainino0x :  the SPIR-V version is now an internal implementation detail. This means we can relax the definition of "WEBGPU0" in our prototype SPIR-V tooling; @zoddicus has started working on that.

**Comment by kvark** [comment]
@dneto0 yeah, I came to conclusion that we need a pass to figure out inputs/outputs regardless, so we might as well not have it in WGSL explicitly. This issue can be closed, if no other parties have concerns with this.

**Comment by grorg** [comment]
Discussed at the [2020-03-25 meeting](https://docs.google.com/document/d/1_gnifSzpdsoO7hi0KwxMhgIeRACVkv9n3zx9Xvwdj3I/)

**Comment by grorg** [comment]
Resolution: OK as is. A new section will be proposed by @litherum about the interface.
