### ISSUE TITLE
[wgsl] intrinsics and their arguments

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#603]
In the current grammar, intrinsic functions like `IsNan` are specified within the `unary_expression` rule, which seems confusing to me. Another problem is their arguments being `IDENT` instead of some more general kind of expression.

**Comment by dj2** [comment]
They can be moved out of unary expression if you have a better place for them. They just kinda worked there so I put them there.

The argument could probably be `logical_or_expression`. I'm assuming your use case is the return of a function or something? My original thinking is it didn't make sense to do something like `IsNan(1.)` but you'd want `IsNan(a)`. I could see you wanting to do `IsNan(foo())`?

**Comment by kvark** [comment]
We could define something like an `intrinsi_func` rule that would have the parens in it. We could also define the `derivative_func` rule for clarity.

> I'm assuming your use case is the return of a function or something?

I just found out that difference, but it's hard to say if this is needed. A SPIR-V to WGSL converter can always make a new constant out of an expression in order to pass an identifier to `IsNan`, so it's unlikely to block anybody. If it's by design, then I think it's ok to keep this way.

**Comment by kainino0x** [comment]
Syntax discussion should probably stay open

**Comment by dj2** [comment]
This isn't really a syntax discussion so much as fixing up the grammar to be clearer. It isn't adding or removing any syntax.

**Comment by kainino0x** [comment]
Gotcha.
