### ISSUE TITLE
[wgsl] Document motivation for not just using GLSL?

### ISSUE THREAD

**Issue by pjoe** [gpuweb/gpuweb#610]
I am still scratching my head over why not just use GLSL instead of creating WGSL as a new shader language? I even saw references to: https://xkcd.com/927/ in the propsed FAQ 😆 

All browser already takes GLSL input (for WebGL) so would assume some part of parser could be re-used.
All major engines (unity, unreal, godot) already produce GLSL output (for WebGL builds)
All WebGL engines/frameworks (three.js, Babylon.js, CesiumJS) already use GLSL
Also apps would need to ship a GLSL shader compiler, for those dynamic generated shaders that cannot be handled build time. This will add substantially to bundle size (shaderc is ~3MB, think glslang is ~1MB, compare to typical webgl engine size of a few 100K) and add extra processing: shaders now have to go: GLSL -> WGSL -> browser -> SPIR-V/DXIL/MSL.

Alternative would be to rewrite all shaders in WGSL, but on top of having to port API to WebGPU, I suspect for many smaller teams, this just won't be feasible. We e.g. have ~2.2K lines of GLSL code, that have been hand tweaked over almost 10 years - porting that to WGSL is not a trivial task for us.

I may be missing something essential here, but really don't understand the reasoning 😟

(Mostly copied from https://github.com/gpuweb/gpuweb/issues/593#issuecomment-598772788 - to be handled here as a separate issue.)

I can see others have similar concerns (https://github.com/gpuweb/gpuweb/issues/593#issuecomment-598732047).

**UPDATE:** I think what is important is to have the motivation for not choosing GLSL well document and easily found, as I imagine other developers from a WebGL background will have similar concerns.

Also having a good (emerging) story on tooling for using GLSL with WebGPU, (e.g. optimized glslang with WGSL output, or other small and fast compiler) will help a lot :)
Also I assume the issue blocking from using SPIR-V (Apple vs. Khronos) doesn't apply to GLSL?

**Comment by rolivo** [comment]
I think that this type of discussion does not help at all, the important thing is to finish the development of this API, if you do not like any feature of the new wgsl open the corresponding thread to analyze it.

**Comment by dneto0** [comment]
>I think that this type of discussion does not help at all

But it's a genuine question. 

We've covered this ground over past meetings and email discussions.  But not everyone can follow all the discussion in detail.   Unfortunately the answers are not summarized in a way that is easily discovered or perhaps in a satisfactory way.

**Comment by dneto0** [comment]
Sorry I should have said "But not everyone can _afford to_ follow ..."

**Comment by litherum** [comment]
I proposed this in September at the New Orleans WebGPU face-to-face meeting. You can read about it in the last 2 or 3 pages of [the minutes](https://docs.google.com/document/d/1CmKo59tjZwmePVrFpHpIG0W5shKR_GOrnNuMStPCEko/edit#heading=h.hp3f2zbslxr9).

**Comment by pjoe** [comment]
I guess I am a bit late to the party here, sorry about that 🎈 

I've changed the title to reflect that what is probably needed is better documentation about the motivation for WGSL vs. GLSL.

I'll also try investigating further and contribute to how GLSL can best be used going forward, I understand from @dneto0, that there is already some work underway in regards to this.

**Comment by frguthmann** [comment]
I asked the people behind WebGPU on Twitter, here is a small thread with a few interesting links. Apparently it's the best they have so far.

https://twitter.com/frguthmann/status/1233316227633811456?s=20

**Comment by pjoe** [comment]
@frguthmann thanks, I already saw the FAQ PR #562, actually I got the xkcd reference from there 😄

**Comment by frguthmann** [comment]
Yes I know but there is more in the thread. Twitter's UI is not always the easiest to navigate though haha. The most interesting tweet is this one: https://twitter.com/dneto1969/status/1233406310294720515?s=20

**Comment by pjoe** [comment]
thanks, must admit I'm not a twitter regular ... anyway would be good to have it documented properly somewhere 😄

**Comment by dhardy** [comment]
Let me side-step the round-trip to Twitter by re-linking the contents of those posts:

- #562: FAQ — [rendered](https://github.com/gpuweb/gpuweb/blob/a095ae9360ff8e674cba1b5aad668b2c203ed78f/design/ShaderLanguageFAQ.md) — does not contain motivation
- #42: Position: Directly ingest a human-writable shading language
- #43: Position: Don't ingest a non-human-writable shading language
- #44: Position: Directly ingest SPIR-V, and not a human-writable shading language

The latter positions are long threads and it is not immediately obvious how conclusions were reached.

**Comment by kvark** [comment]
There is also #219 and #847. I think the short answer is that there is no appetite within the group for GLSL. Let me try to elaborate.

First, we wouldn't be able to use the GLSL as it stands today. We need separate textures and samplers at the very least. So it would be more like the [Vulkan GLSL flavor](https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt) but without Vulkan part. Needless to say that the extension tries to fit the existing GLSL syntax as much as possible, and as such users have to construct `sampler2D` and stuff on the fly every time they need to sample or fetch any texels. This is a hack more than it's a design anybody wants to buy.

Secondly, GLSL was made for the world where each shader only had a single entry point and execution model. This doesn't match either of SPIR-V, HLSL, or Metal. We could try to stretch it apart and try supporting multiple entry points, but then we'd hit other problems like conflicting locations and binding points. And again, it wouldn't nearly be the same GLSL for either users or the tooling.

So we'd end up specifying a "WebGPU GLSL flavor" of sorts, and that's a fairly big document, given the number of changes we'd need. In addition to the language spec, we'd essentially need to define the environment spec. I mean things like the strict behavior of operations, what happens on out-of-bounds, and other things.

Finally, there is a historical reason. Part of the group still saw SPIR-V as a superior alternative, and was hoping to get that ball rolling without being distracted by GLSL. In fact, original WGSL proposal (Tint) was pretty much an original textual form of SPIR-V. Now it's diverging more (hence, it's a historical reason).

> Also I assume the issue blocking from using SPIR-V (Apple vs. Khronos) doesn't apply to GLSL?

SPIR-V had more reasons to be blocked (see [plain](https://kvark.github.io/webgpu-debate/SPIR-V.html) and [component](https://kvark.github.io/webgpu-debate/SPIR-V.component.html) argdown views). But really, GLSL is in the same boat, isn't it? It's also a Khronos spec.

**Comment by dj2** [comment]
Thanks for the great writeup @kvark. I'm going to close this as I think that explanation does a great job of documenting the decision.
