### ISSUE TITLE
WGSL includes push constants

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#612]
Push constants are not present in WebGPU, so I'm not sure why they exist in WGSL.

**Comment by dj2** [comment]
From my reading of #75 I didn't think that was decided yet. In the asciidoc version the `push_constant` lines were marked as dependant on what WebGPU decided. Looks like that got list in the translation to bikeshed.

**Comment by kvark** [comment]
@dj2 the group decided not to include the push constants just yet. So until further development, this semantics needs to be removed from WGSL (sadly).

**Comment by dj2** [comment]
Ah, thanks for clarifying. I can make a PR on Monday to remove push_constants unless someone else beats me to it.
