### ISSUE TITLE
Difference between the source and destination array layer count in GPUTextureViewDescriptor

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#617]
This is a follow-up to #613
We have `GPUTextureViewDescriptor.arrayLayerCount`, which gets confusing in case we are viewing a 2D array texture as a cube array view. From the user perspective, it's not clear whether it means the number of images in the source 2D array, or the number of layers in the resulting view (number of cubes).

**Comment by kainino0x** [comment]
As written, the spec assumes (but doesn't specify) that it's the number of source layers (i.e. number of destination cube sides), not the number of destination cubes, and must be a multiple of 6.

I think the naming here is OK because I think it's clear that an "array layer" is one layer of a 2d texture array, and not one element of a cubemap array (which I wouldn't call a layer, personally).

**Comment by kvark** [comment]
I believe this is still confusing. When one creates a texture today, the `arrayLayerCount` they provide in the descriptor is what the texture will have. When one creates a texture view today, the `arrayLayerCount` is *not* what the view has.

**Comment by kainino0x** [comment]
I would read it as the texture view *does* have `arrayLayerCount` layers, equivalent to saying it has `arrayLayerCount/6` cube faces.

**Comment by kvark** [comment]
I think you just prove that this is confusing (re: having `arrayLayerCount/6` cube faces) 😆

**Comment by magcius** [comment]
Every native API has this confusion, much like whether draw() counts primitives or vertices. I would just add a bit of spec wording clarifying that a layer is a cubemap face, not a cubemap. That matches what most native APIs do.

**Comment by kainino0x** [comment]
Spec editors resolved to close this: It's clear enough if:
- The spec is clear about the meaning of arrayLayerCount
- Implementations error out early with good messages ("array layer count is not a multiple of 6", "view is too big for this texture")

**Comment by kvark** [comment]
Also worth mentioning that the `GPUTextureViewDescriptor` *does* have a mixed bag of fields: the first 3 are for the destination, and the last 4 are from the source. So it's a tiny bit confusing, but at least there is a low chance to hit a bump on it from the user side.
