### ISSUE TITLE
[wgsl] Variable loads and stores

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#622]
In SPIR-V, local variables inside functions are loaded (with `OpLoad`) and stored (with `OpStore`). In WGSL, however, the semantics of "load" is lost. For example:
```rust
var x = 1.0;
const y = x * x + x + 1;
```
This would translate to 3 `OpLoad` instructions for `x` instead of one. It would be unfortunate to recommend people to have temporary `const` variables, since nothing visually indicates whether an access to something is an actual operation, or just a use of an SSA value.
One way to address this would be to have a syntax for "load" of a variable, e.g. `*x`.
Another way is to rely on drivers doing this optimization, if they always do.

**Comment by dj2** [comment]
@dneto0

**Comment by dj2** [comment]
Why do you need to `OpLoad` the `x` three times? You know it isn't stored into so you can just load once and use the same Id in the computation.

**Comment by kainino0x** [comment]
You don't need to, but determining that the load can be deduped requires compiler smarts/complexity, which we generally try to avoid.

**Comment by dneto0** [comment]
> You don't need to, but determining that the load can be deduped requires compiler smarts/complexity, which we generally try to avoid.

I very much agree with this.

That said removal of redundant loads and stores is one of the common transforms, and it's relatively easy for thread-private variables.

If the WGSL author really wants to express their intent that there only be one load, then I think it's reasonable to make them say it by defining a const value:

```
   var x : f32  = 1.0;
   .... /// later
   // Capture the value. 
   // We already have separate discussion about whether to infer the type.
   const x_value : f32 = x;     // load only once.
   const y = x_value + x_value + x_value + 1.0;
```

**Comment by litherum** [comment]
If the motivation for this is for performance, I'd love to see some numbers.

> Another way is to rely on drivers doing this optimization, if they always do.

Yes. If the driver does it for us, we don't need to do anything. It would be very insightful to see how much the browser/language enforcing this affects performance.

**Comment by damyanp** [comment]
> That said removal of redundant loads and stores is one of the common transforms, and it's relatively easy for thread-private variables.

Does this transform need to be part of the language spec then?  Given that the language is meant to be specified in terms of the SPIR-V mapping it seems to me that the spec should describe how code such as this should be translated to SPIR-V.

**Comment by kainino0x** [comment]
IMO it doesn't, because (AFAIK) it's a semantic-preserving transform on the SPIR-V.

**Comment by grorg** [comment]
Discussed at the [2020-03-25 meeting](https://docs.google.com/document/d/1_gnifSzpdsoO7hi0KwxMhgIeRACVkv9n3zx9Xvwdj3I/)

Resolution: Add a blurb that describes this example and what it translates into.

**Comment by dj2** [comment]
Just wondering why fd27b88 didn't get any kind of pull request or code review before being committed?
