### ISSUE TITLE
[wgsl] propose switch-case permit multiple literal values per case

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#630]
Right now the case statement allows matching only one literal value:

```
  const x_9 : u32 = w;
  switch (x_9) {
    default: {
      w = 10;
    }
    case 0: {
      w = 1;
    }
    case 1: {
      w = 2;
    }
    case 5: {
      fallthrough;
    }
    case 6: {
      w = 6;
    }
  }
```

In this example, both the 5 and 6 cases should do the same thing.    I propose that we be able to list multiple values per case statement, like this:

```
  const x_9 : u32 = w;
  switch (x_9) {
    default: {
      w = 10;
    }
    case 0: {
      w = 1;
    }
    case 1: {
      w = 2;
    }
    case 5, 6: {    // This is the changed line.
      w = 6;
    }
  }
```

This eliminates the need to write a bunch of boilerplate, namely `{ fallthrough; }`

It's also easier to read, and to preserve in a round-trip with SPIR-V and LLVM.  (In SPIR-V and LLVM, you can repeat the target block name for different case values.)

We would still retain the restriction that a case value may not appear in two different case statements for a particular switch construct.

**Comment by kvark** [comment]
Sounds like an improvement, assuming we don't have a comma operator :)

**Comment by othermaciej** [comment]
If comma operator is a statement separator and not an expression-level operator (which it would need to be, to benefit `for`), then it won't affect this use of the comma character.

**Comment by grorg** [comment]
Discussed at the [2020-03-25 meeting](https://docs.google.com/document/d/1_gnifSzpdsoO7hi0KwxMhgIeRACVkv9n3zx9Xvwdj3I/)

**Comment by grorg** [comment]
Resolution: Proposal Accepted.

(issue will remain open until spec edits happen)
