### ISSUE TITLE
[wgsl] Function Declarations

### ISSUE THREAD

**Issue by Napokue** [gpuweb/gpuweb#631]
As I am working on the WGSL conversion to Spir-V (Naga), I found out that the concept that Spir-V has about Function Declarations is not present (yet) in the WGSL spec.

I can imagine that declarations are used as a sort of forward reference for other functions that are defined below the declaration of said function and above its definition.

Are there any plans for adding this?

**Comment by dj2** [comment]
There are no plans for function pre-declaration. Functions can not be recursive and functions must be defined before they're called. Those two rules mean that the function declaration and definition can be the same thing.

**Comment by Napokue** [comment]
Thank you, then I think we can close this issue, as this won't be happening.
