### ISSUE TITLE
Disallow (writable) storage-buffers/textures in fragment shaders in core

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#639]
@Jiawei-Shao brought this up in Dawn quite a while ago, but I'm not sure whether we ever made an explicit decision about it in WebGPU. Messages from Jiawei:

> Actually on Metal "Function Buffer Read-Writes" requires iOS_GPUFamily3_v2 (A9+, iOS10+) and OSX_GPUFamily1_v2 (macOS 10.12+), so it seems not all Metal devices support storage buffer in fragment shader.
> (https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/WhatsNewiniOS10tvOS10andOSX1012/WhatsNewiniOS10tvOS10andOSX1012.html#//apple_ref/doc/uid/TP40014221-CH14-SW1)

> Also I see in MoltenVK "fragmentStoresAndAtomics" is only enabled on macOS, not iOS: https://github.com/KhronosGroup/MoltenVK/blob/master/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L1052

So that makes it unsupported up through A8, iOS 9, and macOS10.11.

Additionally, fragmentStoresAndAtomics is not supported on some Vulkan hardware. There is very little Android data on gpuinfo.org, but [what is there](https://vulkan.gpuinfo.org/listdevicescoverage.php?feature=fragmentStoresAndAtomics&platform=android&option=not) seems to show that it is unsupported up through Adreno 4xx.

**Comment by kainino0x** [comment]
So the question is: Do we take the compatibility hit, or make this an extension?

These devices are getting fairly long in the tooth, and probably could be put in the hypothetical "WebGPU Compat Profile" bucket.

**Comment by kvark** [comment]
Would be good to collect the major use cases of fragment writes to storage textures. In a case I recently stumbled, it was straightforward to use a storage buffer instead.

**Comment by kainino0x** [comment]
Oops, just realized the title was wrong. I meant to have this be about storage buffers (it also impacts storage textures though).

**Comment by krogovin** [comment]
Maybe add the title that is is about **writing** to storage buffers and textures. It looks like the older hardware supports reads from storage buffers...

**Comment by kainino0x** [comment]
I believe that's correct, sorry I forgot to specify.

**Comment by litherum** [comment]
iOS 13 (the latest version of iOS) only runs on A9 and later. https://en.wikipedia.org/wiki/IOS_13

WebKit usually doesn't release on older iOS versions than the latest one.

**Comment by kainino0x** [comment]
Got it, thanks for providing that info! (and sorry I couldn't figure out/remember where it was written down before). Now sounds like the only issue is older Vulkan devices.

**Comment by kvark** [comment]
@kainino0x right. Given that we (Google and Mozilla) want to have some plan for non-Vulkan Android anyway, it sounds like we should add these Adreno 400 to the fallback group, so that the core WebGPU is stronger.

**Comment by kainino0x** [comment]
I'm in favor of that. (For timeline, the last Pixel/Nexus line device with Adreno 400 was the Nexus 5X/6P.)

**Comment by Kangz** [comment]
Ok let's have it in core WebGPU.

**Comment by krogovin** [comment]
> Given that we (Google and Mozilla) want to have some plan for non-Vulkan Android anyway, it sounds like we should add these Adreno 400 to the fallback group, so that the core WebGPU is stronger.

Does this mean that Google and Mozilla are intending to support WGSL on such devices which means they will be writing a WGSL to GLSL translator?

**Comment by Kangz** [comment]
> Does this mean that Google and Mozilla are intending to support WGSL on such devices which means they will be writing a WGSL to GLSL translator?

Like you guessed, this will be necessary. The exact path is TBD.

**Comment by grenlight** [comment]
> iOS 13 (the latest version of iOS) only runs on A9 and later. https://en.wikipedia.org/wiki/IOS_13
> 
> WebKit usually doesn't release on older iOS versions than the latest one.

That's not true, iOS 12 can run on iPad mini4(A8) too.

**Comment by kainino0x** [comment]
I'm pretty sure no action is required on this issue (spec already allows storage buffers/textures in fragment stage).
