### ISSUE TITLE
The set of functions which have to be imported seems arbitrary

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#640]
Functions which don't have to be imported:
- `bitReverse()`
- `bitCount()`
- `any()`
- `all()`
- `dPdx()`
- `dPdy()`

Functions which have to be imported:
- `abs()`
- `sqrt()`
- `max()`
- `normalize()`
- `length()`
- `distance()`

As I understand it, the determination of which functions have to be imported is a reflection of common functionality between the OpenCL C Language and GLSL. For a developer writing their WGSL by hand, with either no background or a background in HLSL or MSL, this determination seems arbitrary and meaningless.

We should consider simply listing every function in the the WGSL standard library in the spec, and not requiring WGSL authors to import anything.

Another potential benefit is that it frees up the `::` syntax which we may want to use in the future (e.g. to maybe perhaps one day add user-defined namespacing to the language).

Related: https://github.com/gpuweb/gpuweb/issues/600 "WGSL needs a plan for expansion"

**Comment by kainino0x** [comment]
`::` already refers to user-defined namespace names: the import statement creates a namespace with a user-defined name. It's just that there's no other way to create namespaces right now. I'm pretty sure that namespaces with user-defined content would not conflict with the current `::` syntax.

**Comment by dneto0** [comment]
I'd rather have to import absolutely everything.  That is, push any(), all(), dPdx() and others out of the developer's namespace.

**Comment by kvark** [comment]
@dneto0 it would be something to consider if the functions were truly equivalent to blocks of code that the user could write themselves. But `dPdx` for example is not replaceable, it's truly an intrinsic and not a function in a classical sense.

**Comment by litherum** [comment]
There’s another possible solution that should solve the problem: create multiple imports with various meaningful names, and place methods in the various imports according to logic and relevancy. I think this is a better solution than making the author type `std::` (or equivalent) before every builtin function call.

If we do this, we should also consider a `using` statement so authors can opt in to not having to write these prefixes for certain buckets of functions.

**Comment by dneto0** [comment]
I'm all for disciplined namespace control.  There are good well-known solutions (e.g. Perl5 and Python)

**Comment by dneto0** [comment]
@kvark  But I think there's a difference between naming a thing and the properties of the thing.

The derivatives, for example, have special properties and hence they must be known to the entire compiler / implementation stack.  But that doesn't imply that its name has to be visible at the outermost scope.

**Comment by kvark** [comment]
That makes sense. I also think that it's good when a name clearly reflects the internal properties. I.e. by looking at the code it is easier to reason about the guarantees and behavior if the names are right. If derivatives are just regular functions in some namespace, it's less clear that one has to consider the properties of a group of threads instead of just thinking about this thread only.

A counter argument to this is that there are operations that use derivatives implicitly, like texture sampling, so stressing on the derivative function name isn't solving the problem anyway:) We can treat them as normal functions for the grammar, at least.

**Comment by Kangz** [comment]
The notion of namespace has been removed from WGSL. Tentatively closing this issue. Feel free to reopen if you think we should reintroduce namespaces.
