### ISSUE TITLE
Copying of depth24plus formats

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#652]
(We've talked about this a number of times; just recording it in an issue.)

The depth aspect of depth24plus formats doesn't have a defined memory layout. As such, it's not obvious how they interact with copy commands. Options:
- Disallow copies to/from the depth aspect of depth24plus formats
  - Copies would require sites to use formats with concrete depth format (defined in extensions)
- Emulate by inserting format conversions (to D24 and/or D32F) in the implementation

As [pointed out by @magcius](https://matrix.to/#/!MFogdGJfnZLrDmgkBN:matrix.org/$ulAQN4omyIRD22AP6ELCM2ZVMkrMkCRlps7A09dwUIg?via=matrix.org&via=mozilla.org&via=feneas.org), the stencil aspect of depth24plus-stencil8, and the hypothetical stencil8 format (#306), may be okay: the stencil format is constant, and Vulkan/D3D12, at least, require copies to be against only one aspect anyway.

update: See also: bjjones's [investigation](https://github.com/gpuweb/gpuweb/issues/69#issuecomment-444178868) which resulted in the removal of aspect from GPUTextureCopyView.

cc #305 #69

**Comment by kainino0x** [comment]
(issue edited according to Jasper's feedback on chat)

**Comment by austinEng** [comment]
Metal also [requires you to specify one aspect](https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400771-copyfrombuffer?language=objc).
> If the texture’s pixel format is a combined depth/stencil format, then options must be set to either blit the depth attachment portion or blit the stencil attachment portion.

I would think we only allow copying to/from stencil of packed formats.

**Comment by Kangz** [comment]
It would be nice to allow copying the depth component of `depth24plus` even if it is slower. All APIs allow copying the depth format, so it would be a big limitation of WebGPU couldn't copy at least to other `depth24plus[-stencil8]` and r32float`.

**Comment by Jiawei-Shao** [comment]
I'm afraid that we cannot always support copies with ```depth24plus[-stencil]``` formats on all Vulkan backends.

(1) Since Vulkan 1.1, ```VK_FORMAT_FEATURE_TRANSFER_SRC_BIT``` and ```VK_FORMAT_FEATURE_TRANSFER_DST_BIT``` are introduced for the formats that [don’t support being used in copy commands](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#_common_operation).
(2) In [Vulkan SPEC (Chapter 39.3 "Required Format Support")](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#features-required-format-support), only the "formats that are required to support ```VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT``` must also support ```VK_FORMAT_FEATURE_TRANSFER_SRC_BIT``` and ```VK_FORMAT_FEATURE_TRANSFER_DST_BIT```".
(3) [In Vulkan SPEC (Table 65. 
"Mandatory format support: depth/stencil with VkImageType VK_IMAGE_TYPE_2D")](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#features-required-format-support), there is no column that shows the mandatory support of either ```VK_FORMAT_FEATURE_TRANSFER_SRC_BIT``` or ```VK_FORMAT_FEATURE_TRANSFER_DST_BIT```.

From (1) to (3) we can conclude that the depth stencil textures that are not guaranteed to support ```VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT``` (including ```VK_FORMAT_D24_UNORM_S8_UINT``` and ```VK_FORMAT_D32_SFLOAT_S8_UINT```) are also not guaranteed to support either ```VK_FORMAT_FEATURE_TRANSFER_SRC_BIT``` or ```VK_FORMAT_FEATURE_TRANSFER_DST_BIT```.

Although Vulkan 1.0 does not define ```VK_FORMAT_FEATURE_TRANSFER_SRC_BIT``` and ```VK_FORMAT_FEATURE_TRANSFER_DST_BIT```, according to the experts in Vulkan WG, this part of Vulkan 1.0 SPEC "is poorly defined" and they are suggesting we should still only trust that:
- The formats that are required to support ```VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT``` must also support ```VK_FORMAT_FEATURE_TRANSFER_SRC_BIT``` or ```VK_FORMAT_FEATURE_TRANSFER_DST_BIT```.
- Or we must first check if the format supports ```VK_FORMAT_FEATURE_TRANSFER_SRC_BIT``` and ```VK_FORMAT_FEATURE_TRANSFER_DST_BIT``` before copying with them.

**Comment by kainino0x** [comment]
I'd like to know what actual hardware is not able to copy to/from at least one depth and one depth-stencil format that have VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT. I think it's unlikely that it will be a significant portion of the market, but I don't know. gpuinfo.org doesn't seem to have the data.

**Comment by Kangz** [comment]
Especially on mobile, I think a lot of hardware has special-sauce compression for depth and stencil formats which means they might not be transferable. Unfortunately Vulkan gives very low guarantees on when this is available, and @Jiawei-Shao's proposal is the best we can do.

Also if my reading of the GLES spec is correct, ([see Table 8.16: Valid CopyTexImage source framebuffer/destination texture base internal format combinations](https://www.khronos.org/registry/OpenGL/specs/es/3.1/es_spec_3.1.pdf)) it doesn't require copies from/to depth stencil formats. Base Vulkan being the same feature level as OpenGL ES 3.1 I think this means it is not possible to expect copies from depth-stencil formats to be available beyond what Vulkan provides. (glBlitFramebuffer is also limited because it asks for the depth-stencil formats of the source and destination to match).

**Comment by kainino0x** [comment]
If I'm reading Jiawei's investigations correctly, it sounds like Vulkan requires sampling/src/dst from depth16unorm and depth32float. (But no stencil or depth-stencil formats.)

I guess we'll have to rely on sampling to read from depth24plus formats. Fortunately, from #659, I think we can.

**Comment by kvark** [comment]
@kainino0x 

>I guess we'll have to rely on sampling to read from depth24plus formats

I don't understand this. If a format is sample-able, Vulkan guarantees it's also copy-able.

I suggest we take a bold stance here and require that we only work with those native formats that support both depth-stencil output and sampling (and therefore, can be copied in/from). This would allow the use of deferred rendering and shadow mapping - two very common cases that are well established and widely used.

Working with those native formats doesn't mean we directly expose them. We'd still expose them as "depth24plus" and such, which we just guarantee to be renderable, sample-able, and copy-able.

**Comment by kainino0x** [comment]
> I don't understand this. If a format is sample-able, Vulkan guarantees it's also copy-able.

Oh, sorry, I missed that:

> formats that are required to support `VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT` must also support `VK_FORMAT_FEATURE_TRANSFER_SRC_BIT` and `VK_FORMAT_FEATURE_TRANSFER_DST_BIT`

phew.

> I suggest we take a bold stance here and ...

I'd like to do this too, though this goes beyond what's core in Vulkan, right? So we need to figure out exactly what we can reasonably rely upon from the Vulkan ecosystem.

**Comment by kainino0x** [comment]
Original question still stands though: what does a copy look like when the format is unknown (24 or 32f)? Do we convert to a known format? (And if we have to do that conversion, we could read through sampling anyway, meaning we don't need Vulkan support for a copy in that case.)

**Comment by kvark** [comment]
Would be nice to a have a mini-investigation showing what native APIs and formats produce on copy.

**Comment by kainino0x** [comment]
Here's a start [for Vulkan](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#VkBufferImageCopy):

> When copying to or from a depth or stencil aspect, the data in buffer memory uses a layout that is a (mostly) tightly packed representation of the depth or stencil data. *(... format appears to be well defined)*

> Because depth or stencil aspect buffer to image copies may require format conversions on some implementations, they are not supported on queues that do not support graphics.

**Comment by Kangz** [comment]
In https://github.com/KhronosGroup/Vulkan-Docs/issues/1283 the Vulkan WG clarified that the intent is that the depth-stencil format that supports `OUTPUT_ATTACHMENT` should also support `SAMPLED` (and most likely) `COPY_SRC/COPY_DST`. Data extraction from vulkan.gpuinfo.org seems to shows that this is the case for all Vulkan devices. So we should be able to assume that the WebGPU depth and depth-stencil formats are sampleable and copyable (at least for the Vulkan implementability point of view).

 We should figure out how between depth/depth-stencil textures and other textures and buffers work. We'll likely need to add a `GPUTextureAspect` to `GPUTextureCopyView`.

**Comment by kainino0x** [comment]
I guess I was wrong in the meeting about how copies with depth aspect work on Vulkan.

> When copying to or from a depth or stencil aspect, the data in buffer memory uses a layout that is a (mostly) tightly packed representation of the depth or stencil data. Specifically:
> 
> -   data copied to or from the stencil aspect of any depth/stencil format is tightly packed with one `VK_FORMAT_S8_UINT` value per texel.
> 
> -   data copied to or from the depth aspect of a `VK_FORMAT_D16_UNORM` or `VK_FORMAT_D16_UNORM_S8_UINT` format is tightly packed with one `VK_FORMAT_D16_UNORM` value per texel.
> 
> -   data copied to or from the depth aspect of a `VK_FORMAT_D32_SFLOAT` or `VK_FORMAT_D32_SFLOAT_S8_UINT` format is tightly packed with one `VK_FORMAT_D32_SFLOAT` value per texel.
> 
> -   data copied to or from the depth aspect of a `VK_FORMAT_X8_D24_UNORM_PACK32` or `VK_FORMAT_D24_UNORM_S8_UINT` format is packed with one 32-bit word per texel with the D24 value in the LSBs of the word, and **undefined values in the eight MSBs.**

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#copies-buffers-images

**Comment by kainino0x** [comment]
Also FWIW:
> [vkCmdCopyImage](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#copies-images)
> The formats of srcImage and dstImage must be compatible. Formats are compatible if they share the same class, as shown in the Compatible Formats table. Depth/stencil formats must match exactly.

**Comment by kainino0x** [comment]
I thought we had come to a conclusion at some point to have only single-aspect copies between buffers and depth-stencil textures. However I went back to the linked #69 and read bjjones's [investigation](https://github.com/gpuweb/gpuweb/issues/69#issuecomment-444178868) which resulted in the removal of `aspect` from `GPUTextureCopyView`, since it couldn't be supported on D3D12. This seems to conflict with what @magcius was telling me on chat, so I'm no longer sure what can actually be done on D3D12.

If we can't have single-aspect buffer <-> DS-texture copies, then we can't have copies with depth24plus-stencil8 at all. Not even sure we can have them (without magic) for depth24plus or x-stencil8 which may have extra padding.

**Comment by Kangz** [comment]
@RafaelCintron @damyanp can you help clarify what the constraint are from the D3D12 side for depth and stencil texture copying? Do we really have to do whole-subresources copies of both aspects only or is there a way to work around it?

**Comment by kainino0x** [comment]
Thanks for the clarification. It sounds like we probably also need to re-add `aspect` to `GPUTextureCopyView`.

**Comment by kainino0x** [comment]
I tried to summarize all of the data from these investigations/conversations.

Current depth/stencil formats:
- depth32float
- depth24plus
- depth24plus-stencil8

Possible (future or extension) depth/stencil formats:
- x-stencil8
- depth32float-stencil8
- depth24unorm
- depth24unorm-stencil8
- depth16unorm

Copies that will probably always be allowed (note some of these
decompose into two single-aspect copies in some backends):
- (same format, matching aspect) <-> (same format, matching aspect)
- (depth24plus) <-> (depth24plus-stencil8, depth-only)
- Buffer <- (depth32float)/(depth32float-stencil8, depth-only)
- Buffer <-> (depth16unorm)
- Buffer <-> (x-stencil8)
- Buffer <-> (depth24plus-stencil8, stencil-only)
- Buffer <-> (depth24unorm-stencil8, stencil-only)
- Buffer -> (depth24unorm)/(depth24unorm-stencil8, depth-only)

Copies that would require [format conversions](https://github.com/gpuweb/gpuweb/issues/652#issue-588761676):
- Buffer <-> (depth24plus)/(depth24plus-stencil8, depth-only)
- Cross-format T2T copies (ignored for now)

Copies that would require [zeroing unused bits](https://github.com/gpuweb/gpuweb/issues/652#issuecomment-644349841):
- Buffer <- (depth24unorm)/(depth24unorm-stencil8, depth-only)
- Buffer <-> (depth24plus)/(depth24plus-stencil8, depth-only)
  (if buffer format is depth24unorm)

Copies that would/could require clamping to keep values in range:
- Buffer -> (depth32float)/(depth32float-stencil8, depth-only)
- Buffer -> (depth24plus)/(depth24plus-stencil8, depth-only)
- Many cross-format T2T copies (ignored for now)

Resolution from 06-15 on #789:
- no copies from buffers to depth24plus/depth32float formats

**Comment by kainino0x** [comment]
If anyone has a chance to review this for correctness, please do. Thanks!

**Comment by kvark** [comment]
If we want to provide some copy semantics, we should consider supporting Depth24Plus format as a *real* Depth24:
  - Buffer -> Depth24Plus would either:
    - if backed by Depth24X8: be a native copy operation
    - if backed by Depth32F: run through a shader that produces floating point values in 0-1.
  - Buffer <- Depth24Plus would either:
    - if backed by Depth24X8: be a shader copy that masks out `X8` component with zeroes.
    - if backed by Depth32F: be a shader copy that converts f32 to fixed-point D24X8.

**Comment by kainino0x** [comment]
Pretty much exactly what this issue was originally about :)

**Comment by kainino0x** [comment]
Added a small section about multi-aspect copies in the summary above.

**Comment by kainino0x** [comment]
I don't know what the readback method was, but an Adreno driver bug to be aware of:

> The name of Stenzek's branch should say everything about how we got to this point: "adreno-more-like-brokenreno". A work-around for another adreno bug has caused us to run into more issues. The problem was that attempting to create savestates in Vulkan would crash Dolphin due to an assert in the driver when reading back D24S8 depth. In order to work around this, Dolphin now uses R32F on afflicted devices instead. This allows savestates to function on Vulkan on Adreno devices.

https://dolphin-emu.org/blog/2020/07/05/dolphin-progress-report-may-and-june-2020/

**Comment by RafaelCintron** [comment]
Following up on action item from the last meeting:

The [Planar Depth Stencil Spec](https://github.com/microsoft/DirectX-Specs/blob/master/d3d/PlanarDepthStencilDDISpec.md) provides more information depth/stencil textures.  The [Planar Layout for Staging From Buffer](https://github.com/microsoft/DirectX-Specs/blob/master/d3d/PlanarDepthStencilDDISpec.md#planar-layout-for-staging-from-buffer), in particular, talks about copies two and from staging buffers.

**Comment by kainino0x** [comment]
Sounds like copies of the stencil aspect always get tightly packed into S8 like on Vulkan, and same with depth aspect of D32F. Copies of D24 are like Vulkan except that the X8 bits are guaranteed to be filled with zero on T2B (and "applications must initialize the X8 bits to zero when providing source planar depth placed texture data" which I think doesn't apply to copies).

**Comment by austinEng** [comment]
I was looking at implementing stencil-only T2B and B2T copies in Dawn, and it seems experimentally in Metal that using `MTLPixelFormatDepth32Float_Stencil8` and `MTLBlitOptionStencilFromDepthStencil`, the stencil data is packed in the buffer. I'm not sure about `MTLPixelFormatDepth24Unorm_Stencil8`.

**Comment by kainino0x** [comment]
Found this:

> To blit either the depth or stencil information to a Metal buffer, call the copyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toBuffer:destinationOffset:destinationBytesPerRow:destinationBytesPerImage:options: method, specifying the blit options for which part you want to copy. You must provide space for 4 bytes per pixel in your destination buffer. When Metal copies the data, it sets the bottom 3 bytes of each pixel to the depth data and sets the top byte to arbitrary data. Ignore any data stored in the top byte of each pixel.
> https://developer.apple.com/documentation/metal/mtlpixelformat/mtlpixelformatdepth24unorm_stencil8

which matches Vulkan.

**Comment by kainino0x** [comment]
On sampling from depth (which is relevant to any emulated copies we do here in the future, but also to depth sampling in general), I can't find anything in the Metal docs about sampling depth from depth-stencil formats. It's [clear](https://developer.apple.com/documentation/metal/mtltexture/1515598-newtextureviewwithpixelformat#discussion:~:text=Combined%20depth%2Dstencil%20texture%20formats%20and%20the,shader%20(for%20example%2C%20MTLPixelFormatDepth24Unorm_Stencil8%20and%20MTLPixelFormatX24_Stencil8)) about reading/sampling stencil from depth-stencil formats: you make a X24S8 or X32S8 view. But can you make a (D24,D32) view from (D24S8,D32S8)? Or does sampling from DS formats always give you depth, or is it more complex than that?

**Comment by grorg** [comment]
Discussed at the [2020-07-13 meeting](https://docs.google.com/document/d/1ZC0aGwUEuvzh8CEdK7B8FOY3eU6UiAHTCLTTkm74kWY/).

**Comment by kainino0x** [comment]
Guess I should assign this to @grorg @litherum to get a clarification on the buggy documentation / what packing format you get when you copy from the depth or stencil aspect of various depth-stencil formats

**Comment by Kangz** [comment]
Note that @austinEng implemented stencil T <-> B copies in Dawn and it seems that on all configurations we test they are packed. Would be nice to get confirmation from the horse's mouth though.

**Comment by austinEng** [comment]
Bump @grorg @litherum

**Comment by kainino0x** [comment]
I think we're reasonably confident that stencil-from-depth-stencil copies on Metal work the same way on as the other APIs. If we don't get clarification on the documentation then we should probably move forward assuming the observed behavior on Mac is Metal's intended behavior.

**Comment by kainino0x** [comment]
For meeting prep: This is blocking #873, but the intent is not to discuss that whole PR yet.

**Comment by kainino0x** [comment]
@litherum has clarified via email that stencil-from-depth-stencil copies from D24S8 will indeed be packed. Thanks Myles!

You noted D24S8 is not available on all devices. I probably should have asked about MTLPixelFormatDepth32Float_Stencil8 as well, but I don't remember whether we already had a conclusive answer on that one. It seems fairly safe to assume it has the same behavior (especially since we would only use it when MTLPixelFormatDepth24Unorm_Stencil8 is not available, which I think implies that stencil is stored in a separate tightly packed S8 plane).

**Comment by Kangz** [comment]
@kainino0x are all the resolutions from this issue encoded in the spec?
