### ISSUE TITLE
var declaration without storage class: spell out rules, infer Function storage class inside a function

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#654]
We need spec text for the rules about when a variable is declared without an explicit storage class.

There are two cases.  At module scope, the current draft alludes to a proposal that this case be invalid.  From the example in 3.15 "Initializers":

>     var bar : f32     # Error. Must have storage class. E.g. private

Inside a function, we should infer Function storage class.  This is covered in several examples, e.g. also in 2.15.  (It's also the rule from SPIR-V. https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_logicallayout_a_logical_layout_of_a_module)

WGSL should have explicit rules for this.  A candidate for the rules would be  2.11 "Variables".

**Comment by kvark** [comment]
Two questions:
  - does it make sense to infer any storage class for out-of-function `var`? It seems to me that everybody will be happier if the class was always specified/required there.
  - does it make sense to use anything other than `Function` class for in-function vars? I wonder if we say that the grammar doesn't even allow one to specify the class within a function, and always define it as `Function`.

**Comment by grorg** [comment]
Discussed at the [2020-03-31 meeting](https://docs.google.com/document/d/1IiAIHv6M6_x7VfFfNHjuwfVpgGcyXdkzbEXn0iaphTw/).

**Comment by dneto0** [comment]
Consensus at 2020-03-31 meeting:

-  Agree that function-scope variables are implicitly Function storage class. (no other storage class is permitted)
-  Resolved that variable at module-scope will not require an explicit storage class, and will default to Private storage class.

Background:
- Metal doesn't have the concept of module-scope Private.  So such variables would gather these variables into a struct, and be passed in to the entry point (and all helper functions).  Apple is ok with adding this support.
- HLSL supports module-scope Private concept directly.  Like C module-scope statics.
- Argument against defaulting:
    - makes the grammar more complex
    - believe there is little benefit, as Private variables are believed to be rare.
- However, Microsoft's experience is that HLSL module-scope statics are used to store stage inputs so they are accessible to all function bodies. (Stage inputs are passed in as entry point function parameters).  This is used when translating GLSL code to HLSL.

**Comment by dneto0** [comment]
> However, Microsoft's experience is that HLSL module-scope statics are used to store stage inputs so they are accessible to all function bodies. (Stage inputs are passed in as entry point function parameters). This is used when translating GLSL code to HLSL.

I just noticed that this pattern is used for HLSL but not required for GLSL or WGSL because stage inputs in GLSL and WGSL are already modeled as variables at module scope, but distinguished by storage class.

**Comment by kvark** [comment]
Yes, I don't get why the warts of GLSL -> HLSL translation are influencing our design at all.

**Comment by dneto0** [comment]
I recommend reopening the discussion.  After further thought I lean to agree with @kvark 

By explictly forcing a spelling out "var<private>" we free up any possible confusion when looking at fragments of WGSL.  E.g. when I see `var a: i32;`  I know which context  it's coming from.

**Comment by grorg** [comment]
Discussed at the [2020-04-07 meeting](https://docs.google.com/document/d/1SVCmA9-fLYNBJwePlsWXZhBHmmrKHuBJStBlPcgARj0/).

**Comment by jdashg** [comment]
Resolved in meeting to require explicit storage classes for non-function vars.

**Comment by Kangz** [comment]
This seems to have been added to the WGSL spec: `var` in function scope default to `function` storage class, and `var` in module scope require an explicit storage class. Closing.
