### ISSUE TITLE
premerge is weird and unfamiliar

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#660]
Many of the arguments have been made before in 
- https://github.com/gpuweb/gpuweb/issues/580 `regardless`
- https://github.com/gpuweb/gpuweb/issues/577 `unless`
- https://github.com/gpuweb/gpuweb/issues/579 `continuing`

They apply to `premerge` too.

**Comment by litherum** [comment]
The proposal is to just put the code after the end of the conditional.

As far as I can tell, the only effect of moving `premerge` code to after the end of the conditional is that it allows the code to execute in a uniform context, thereby allowing some operations to be possible and other operations to be faster. 'premerge' doesn't make much sense to have as a concept in WGSL because its only purpose is to intentionally makes authors code slower/impossible for no reason.

By the way, this same logic goes for `regardless` too: https://github.com/gpuweb/gpuweb/issues/580

**Comment by litherum** [comment]
I think you can implement `premerge` with `regardless`:

```WGSL
if (condition()) {
    thenBody();
} else {
    elseBody();
} premerge {
    premergeBody();
}
```

gets turned into

```WGSL
const temp : bool = condition();
if (temp) {
    thenBody();
} else {
    elseBody();
}
regardless (temp) {
    premergeBody();
}
```

I also think you can implement `regardless` with `premerge`:

```WGSL
regardless (condition()) {
    regardlessBody();
}
```

gets turned into

```WGSL
if (condition()) {
} else {
} premerge {
    regardlessBody();
}
```

**Comment by dneto0** [comment]
I think premerge can be removed as @litherum suggests.

The net effect in SPIR-V (graphics) execution is potentially earlier reconvergence.  This is almost certainly not harmful.  For round-tripping SPIR-V, I'm happy to hide this difference via canonicalization.
