### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#661]
Enums would be a nice-to-have. We've heard from HLSL developers that they wish they had enums. Implementations would desugar them to integral types.

**Comment by jdashg** [comment]
What is it about enums that they want?

**Comment by Jasper-Bekkers** [comment]
Simple syntax for it typically; so we don't have to use this style of declaring them:
`static const uint MyFakeEnum_MyFakeValue = 1;`

And can instead just use something like this:
```
enum MyRealEnum {
    MyRealValue = 1
}
```

**Comment by grorg** [comment]
Discussed at the [2020-06-24 WebGPU Virtual F2F](https://docs.google.com/document/d/1uv0LiQB2gAFbUEU3qx2-Sgsv6r3fEKMvnifbFoRbvmw/).

Resolution was not to add enums for MVP, but to reserve the keyword for future use.
