### ISSUE TITLE
entry_point_decl should be an annotation on the function

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#662]
Today, this is how you describe an entry point in WGSL:

```WGSL
void foo() {
    ...
}
... perhaps hundreds of lines later ...
entry_point compute as MyComputeEntryPoint = foo
```

Just like how decorations are separate statements in SPIR-V, but were moved onto the variable declaration they are decorating in WGSL, the same treatment should be done on entry points. The benefit is that related concepts should be near each other in the source code.

Here's another way to do it:
```WGSL
[[expose_as = "MyComputeEntryPoint"]]
compute fn foo() -> void {
    ...
}
```

This wouldn't actually be less expressive, it would just keep related concepts together.

**Comment by dj2** [comment]
Currently you can have multiple entry points with different names pointing at the same function. Those entry points are where, eventually, the execution modes [1] will attach.

Moving to decorations means you're going to have to have multiple decorations for a single function which isn't as nice as separating out to the entry point call.

Note, you could write your first example the same as the second as:

```
entry_point compute as MyComputeEntryPoint = foo
void foo() {
    ...
}
```

which also keeps the related points together. The `entry_point` can proceed the function it references.

1- https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#Execution_Mode

**Comment by litherum** [comment]
> Moving to decorations means you're going to have to have multiple decorations for a single function which isn't as nice as separating out to the entry point call.

Why? All our existing decoration facilities accept lists of decorations, so I don’t see why this one shouldn’t as well.

**Comment by dj2** [comment]
True, that's subjective, I withdraw that objection.

This still doesn't solve the issue of attaching execution modes that differ per entry point. 

What is the issue with writing the entry point directive above the function?

**Comment by kvark** [comment]
For clarity, could you provide an example where a single function would be used in different execution modes?

**Comment by litherum** [comment]
Right. The built-ins are all different anyway.

**Comment by dneto0** [comment]
Sorry, there's an easily confused thing going on here.

There's execution _model_ (e.g. fragment vs. vertex vs. compute), and execution _mode_ (describe/modify the behaviour of  the shader stage).

Example of different execution _modes_:
- the same compute shader body, but different workgroup sizes.  (See LocalSize execution mode in SPIR-V)
- the same shader stage but with different floating point behaviours (a newish Vulkan feature).  See DenormPreserve, DenormFlushToZero, SignedZeroInfNanPreserve, RoundingModeRTE, and RoundingModeRTZ

If you attach these things to the function body itself, then you can always model the differences by having an extra layer of function wrapping, and attaching these attributes to the outside wrapper.

**Comment by kvark** [comment]
Thank you, that makes sense! So it sounds like we could still just annotate the functions with entry point properties.

**Comment by grorg** [comment]
Discussed at the [2020-04-14 meeting](https://docs.google.com/document/d/1bdIA5GS0yMDXcHZ0U_CtxYp6jLfJqVlGPBgcQ0aOEkc/).

The discussion mostly focused on the syntax that @litherum was suggesting. He'll follow up here with more examples for us to discuss again.

**Comment by litherum** [comment]
The default would be for it to look something like this:

```
[[ workgroupSize: [1, 2, 3] ]]
compute void foo(...) { ... }
```

However, if you wanted to expose the same entry point with two different workgroup sizes, you could write:

```
[[ expose_as: “entryPoint1” workgroupSize: [1, 2, 3],
   expose_as: “entryPoint2” workgroupSize: [5, 6, 7] ]]
compute void foo(...) { ... }
```

**Comment by dneto0** [comment]
The multiple "expose_as" syntax is overly complex because now you have nested attributes on attributes.  That's the "sublanguage" aspect I was complaining about in the meeting.  That's a non-starter for me.

**Comment by dneto0** [comment]
Surveying the execution modes from SPIR-V,  https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_execution_mode_a_execution_mode 
there are:

* things for geometry shaders
* things for tessellation shaders
* PixelCenterInteger, for fragment shader.   Not clear if WebGPU will ever use this
* OriginUpperLeft vs. OriginLowerRight, for fragment shader.  WebGPU will(has?) picked one already
* EarlyFragmentTest, for fragment shader
* 4 options for depth handling in fragment shaders
* LocalSize for compute shader workgroup size
* LocalSizeHint, a hint for code generation optimization
* ContractionOff (Kernel), for essentially fast-math mode for kernels targeting OpenCL
* options for subgroup control 
* options for floating point behaviour: denorms, rounding direction, preservation of signed-zero,infinities,and Nans.
* options for other Vulkan extensions

**Comment by kvark** [comment]
@dneto0 I agree that having meta-language for the attributes is not desired.
Would having separate wrapping functions (the second half of https://github.com/gpuweb/gpuweb/issues/662#issuecomment-613724698) be a non-starter as well?

**Comment by litherum** [comment]
All popular human-writable shading languages annotate the function. No human-writable languages have standalone entry point decl statements. Somehow none of those languages have been crushed by the weight of the annotations.

From this list, I see some which a) aren't even applicable to shaders, b) aren't implementable on MSL / HLSL, or c) are regarding features we have no plans to include in WebGPU.

**Comment by grorg** [comment]
Discussed at the [2020-06-16 meeting](https://docs.google.com/document/d/11RW9hpfzSvZYpLGBm3uhKwoXDvJI42N7jWP_nOB-k2E/).

**Comment by litherum** [comment]
Here's the final proposal:

```
[[ workgroupSize = [1, 2, 3] ]]
compute void foo(...) { ... }
```

However, if you wanted to expose the same entry point with two different workgroup sizes, you could write:

```
[[ entry_point = “entryPoint1” workgroupSize = [1, 2, 3],
   entry_point = “entryPoint2” workgroupSize = [5, 6, 7] ]]
compute void foo(...) { ... }
```

or

```
void foo(...) { ... }

[[ workgroupSize = [1, 2, 3] ]]
compute void entryPoint1(...) { foo(...) }

[[ workgroupSize = [5, 6, 7] ]]
compute void entryPoint2(...) { foo(...) }
```

**Comment by kvark** [comment]
@litherum I don't think this should be an option:
> [[ entry_point = “entryPoint1” workgroupSize = [1, 2, 3],
   entry_point = “entryPoint2” workgroupSize = [5, 6, 7] ]]

It uses duplicate semantics, and complicates the grammar rules for the attributes.

**Comment by grorg** [comment]
Discussed at the [2020-06-23 Virtual F2F meeting](https://docs.google.com/document/d/1WI9PzwXy39fFHuZLUnEQtSplwfmFaZ2oVb0gXJsA2P4/)

**Comment by litherum** [comment]
> Discussed at the [2020-06-23 Virtual F2F meeting](https://docs.google.com/document/d/1WI9PzwXy39fFHuZLUnEQtSplwfmFaZ2oVb0gXJsA2P4/)

I don't think it actually was. I think we discussed https://github.com/gpuweb/gpuweb/issues/644 instead.

**Comment by grorg** [comment]
Discussed (really! this time!) at the [2020-07-07 meeting](https://docs.google.com/document/d/1jiRiUAEBkG1UPFZTTeEx81HCXlrTeucCrfATIFBhzzI/).

**Comment by kainino0x** [comment]
> compute void entryPoint1(...) { foo(...); }

nit: there are no arguments allowed here, it will be:

compute void entryPoint1() { foo(); }

**Comment by jdashg** [comment]
We decided to do https://github.com/gpuweb/gpuweb/issues/662#issuecomment-644951919 with https://github.com/gpuweb/gpuweb/issues/662#issuecomment-645491110.

**Comment by dneto0** [comment]
Looking at this, the proposed syntax is un-WGSL-like.

It's either

        compute fn main() -> void { }

or

        fn compute main() -> void { }

I prefer the first. I don't think it causes a grammar ambiguity or collision.
