### ISSUE TITLE
Task: Memory model

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#670]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

The spec needs to describe the memory model. In particular, the SPIR-V memory model is quite complex and includes lots of things which aren't present in WebGPU, so we should be able to condense it down to just the relevant parts.

**Comment by Jasper-Bekkers** [comment]
It might be useful to highlight the things that aren't useful to WebGPU explicitly in this issue, the SPIR-V / Vulkan memory model is complex for a reason (mostly different hardware is different).
