### ISSUE TITLE
Task: Define accesses into vectors and matrices

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#671]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

Things like `myMatrix[3][2]` need to be defined.

**Comment by dneto0** [comment]
Is myMatrix a matrix value, or a matrix variable?

Is this for read, for write, or both?

Are the indices constant, or dynamic?

**Comment by dneto0** [comment]
I think this is all spelled out now, via:

* [Vector Access Expression](https://gpuweb.github.io/gpuweb/wgsl/#vector-access-expr)
* [Matrix Access Expression](https://gpuweb.github.io/gpuweb/wgsl/#matrix-access-expr)

Closing. Please reopen if you think more is needed.

I thought there was a proposal for swizzle syntax for matrices, and [so did @jdashg](https://github.com/gpuweb/gpuweb/issues/1803#issuecomment-871607772).  But I can't find it now.
