### ISSUE TITLE
Task: Define pointers

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#672]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

Pointers aren't defined almost at all. The spec needs to cover them in much more detail.

**Comment by Jasper-Bekkers** [comment]
To avoid confusion it might be a good idea to be more precise or clear in this issue; typically c-style pointer have been avoided or impossible on GPUs so presumably something else is meant by this (which would be good to clarify).

**Comment by kainino0x** [comment]
WGSL pointers are SPIR-V [Logical addressing model](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_memorymodelsection_a_memory_model) pointers.

**Comment by litherum** [comment]
It would be cool to rename them to "references" because I believe their logical addressing model semantics match references in C++.

**Comment by kainino0x** [comment]
We also auto-dereference them (currently) like C++ references.

**Comment by krogovin** [comment]
I'd be very, very careful on making pointer-references part of the language as it opens up a giant can of worms that can explode driver compilers. I suggest to instead use the convention of in, out and inout meaning values are copied in on function call, copied out on function exit.

**Comment by dneto0** [comment]
The current draft of the WGSL has a start on the explanation.
Start with the "Typed Storage" section:  https://github.com/gpuweb/gpuweb/blob/master/wgsl/index.bs#L202

It starts with the fact that storage can hold typed values, and that a WGSL pointer is a reference to storage.  Then describes the abstract operations you can do on a pointer-value, and how the interpretation of a pointer expression depends on the evaluation context.  Attaching evaluation contexts to grammatical constructs is *not* described.  Also not described is the semantics of going outside the bounds of specified behaviour, or concurrency, or sharing.

It's more than nothing, but still not enough.

**Comment by jdashg** [comment]
Can we consider this satisfied? @litherum @dneto0

**Comment by Kangz** [comment]
Same question. @dneto0 @litherum @RobinMorisset anything else to do here?

**Comment by kdashg** [comment]
We definitely did this.
