### ISSUE TITLE
Task: Define atomic operations

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#673]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

Atomic operations currently don't exist in the spec. We need to define them.

**Comment by dneto0** [comment]
One aspect: We had previously decided to only support "relaxed" atomics.
See https://github.com/gpuweb/spirv-execution-env/issues/16 (also referenced from [spreadsheet](https://docs.google.com/spreadsheets/d/15nGTsH5yB1cBtbROt3ZcfuXLSPbCvB1Z-WDabrksOOE/edit#gid=0)

**Comment by potree** [comment]
> One aspect: We had previously decided to only support "relaxed" atomics. See gpuweb/spirv-execution-env#16 (also referenced from spreadsheet

Do these relaxed atomics include glsl atomic operations like atomicMin, atomicMax, and possibly atomicExchange and atomicCompSwap? I've got a couple of use cases that I'd like to port to WebGPU, where atomics, especially min and max, are essential.

**Comment by jdashg** [comment]
Is this satisfied yet? @litherum

**Comment by Kangz** [comment]
Ping again. Atomics were added to WGSL so I think further work should be in new issues.
