### ISSUE TITLE
Task: Numerical precision

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#674]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

We need to define numerical precision for operations. If there's going to be a fastmath mode, it needs to be defined.

**Comment by Jasper-Bekkers** [comment]
Relevant: https://docs.microsoft.com/en-us/windows/win32/direct3d11/floating-point-rules https://vulkan.lunarg.com/doc/view/1.0.26.0/linux/vkspec.chunked/apas04.html

**Comment by kvark** [comment]
Mentioned recently in #1364 feedback:
> Couldn't figure out how to bump the precision up. It caused a bunch of division by zero which do not fail but do garbage hard to debug

Also there is a fresh mini-investigation from LunarG: https://github.com/KhronosGroup/MoltenVK/issues/1209#issuecomment-767847594

**Comment by kdashg** [comment]
How much is left to work on here? We do have some precision tables now. @litherum
