### ISSUE TITLE
Task: define operator precedence rules

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#679]
This is a tracking bug for a task. It's likely non-controversial; it just needs to be done.

For something like `a+b*c`, it needs to be defined whether it’s `(a+b)*c` or `a+(b*c)`.

We should research how other languages (perhaps Java, C#, Rust, HLSL, GLSL) do it, and just copy them.

**Comment by dj2** [comment]
These rules are already in the grammar, they just don't have an explicit writeup in the spec text yet. They follow GLSL/C for the behaviour.

**Comment by dneto0** [comment]
I'd probably steer away from Smalltalk.  Aside from parenthesis, operator evaluation is strictly left-to-right.

**Comment by litherum** [comment]
> I'd probably steer away from Smalltalk. Aside from parenthesis, operator evaluation is strictly left-to-right.

I don't think that's how any of Java, C#, Rust, HLSL, GLSL do it.

**Comment by litherum** [comment]
I agree with https://github.com/gpuweb/gpuweb/issues/679#issuecomment-607373238, this is already defined.
