### ISSUE TITLE
Investigation: Cube dimensionality

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#68]
In WebGL cubemaps  and 2D array textures are two different types of textures. However in explicit APIs, the distinction is blurrier as the two are almost the same in term of hardware representation.

## D3D12

There is no notion of cube texture in [`D3D12_RESOURCE_DESC`](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_resource_desc): it has a member called [`D3D12_RESOURCE_DIMENSION`](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ne-d3d12-d3d12_resource_dimension) that only lists 1/2/3D textures and buffers.

Cube dimensionality is set when a texture view is created (SRV). [`D3D12_SHADER_RESOURCE_VIEW_DESC`](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_shader_resource_view_desc) has a `ViewDimension` member of type [`D3D12_SRV_DIMENSION`](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ne-d3d12-d3d12_srv_dimension) that can be `D3D12_SRV_DIMENSION_TEXTURECUBE` or `D3D12_SRV_DIMENSION_TEXTURECUBEARRAY`. It seems that [`D3D12_TEXCUBE_SRV`](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_texcube_srv) only allows using array slices 0 to 5 as the cubemap, but that [`D3D12_TEXCUBE_ARRAY_SRV`](https://docs.microsoft.com/en-us/windows/desktop/api/d3d12/ns-d3d12-d3d12_texcube_array_srv) allows using any range for the cubemap array.

## Metal

[`MTLTextureDescriptor`](https://developer.apple.com/documentation/metal/mtltexturedescriptor) has a `textureType` members of type [`MTLTextureType`](https://developer.apple.com/documentation/metal/mtltexturetype) that lists `typeCube` and `typeCubeArray`.

However the "texture view" mechanism of Metal that works by calling [`MTLTexture::newTextureViewWithPixelFormat:textureType:levels:slices:`](https://developer.apple.com/documentation/metal/mtltexture/1515409-newtextureviewwithpixelformat) allows reinterpreting the texture data freely between `typeCube`, `typeCubeArray` and `type2DArray`.

## Vulkan

Vulkan is like D3D12 except that a flag must be set to tag the texture as "cube compatible". `VkImageCreateInfo` has a `VkImageType` member that can only be 1/2/3D and a `VkImageCreateFlags` that can contain `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` bit.

`VkImageViewCreateInfo` takes a `VkImageViewType` that can be `VK_IMAGE_VIEW_TYPE_CUBE` or `VK_IMAGE_VIEW_TYPE_CUBE_ARRAY`. There are some validation rules that are in a table that's really hard to understand, but it seems cubemaps are created from 2D array textures. Support for cubemap arrays is optional in Vulkan (though widely supported).

## Suggestion for WebGPU

Since developers have to create a texture view to sample from a textures, we can only expose cube dimensionality for texture views.

`WebGPUTextureDescriptor` would have a `dimensionality` that can only be 1/2/3D and an `arraySize` member that defaults to 1. `WebGPUTextureViewDescriptor` would have a `dimensionality` that can be cube, and with our without arrayness.

Copies don't know about cubemaps and treat them as regular 2D textures (that may be arrayed or not).

```webidl
enum WebGPUTextureDimensionality {"1d", "2d", "3d"};
dictionary WebGPUTextureDescriptor {
    WebGPUTextureDimensionality dimensionality;
    uint32_t arraySize = 1;
    // ...
};

enum WebGPUTextureViewDimensionatlity{"1d", "1dArray", "2d", "2dArray", "cube", "cubeArray", "3d"};
dictionary WebGPUTextureDescriptor {
    WebGPUTextureViewDimensionality dimensionality;
    uint32_t firstSlice = 0; // Must be 0 for cube, 6xN for cubeArray
    uint32_t numSlices = 1; // Must be 6 for cube, 6xN for cubeArray
    // ...
};
```

**Comment by kvark** [comment]
Thank you for doing the investigation!
> WebGPUTextureDescriptor would have a dimensionality that can only be 1/2/3D and an arraySize member that defaults to 1

If we don't know anything about cubes at the texture creation, how are we expected to set the `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` in Vulkan?

> allows reinterpreting the texture data freely between typeCube, typeCubeArray and type2DArray

I'd like to see some experimental evidence that this works as expected in Metal, or at least a confirmation from Apple

**Comment by Kangz** [comment]
> If we don't know anything about cubes at the texture creation, how are we expected to set the `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT` in Vulkan?
At first we would always set it and ask Vulkan IHVs how expensive it is to do so. If it turns out to be expensive, we could have a `boolean cubeCompatible`. This would also be important if the max 2D texture size is often bigger than the max cube texture size.

**Comment by kainino0x** [comment]
> I'd like to see some experimental evidence that this works as expected in
Metal, or at least a confirmation from Apple

Table 1 in that Metal documentation link says to me that this is supported.

**Comment by Kangz** [comment]
> It seems that D3D12_TEXCUBE_SRV only allows using array slices 0 to 5 as the cubemap, but that D3D12_TEXCUBE_ARRAY_SRV allows using any range for the cubemap array.

For the record, @RafaelCintron said that if a shader declares a TextureCube then a TextureCubeArray SRV with a NumCubes of 1 can be bound to it.

**Comment by Kangz** [comment]
Cubemaps have been added to the spec a long time ago and a stable feature.
