### ISSUE TITLE
Define "human writable" as "can be written by humans"

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#681]
The phrase "human writable" is being used in goals discussions.

However, it's not clear that we all mean the same thing by this phrase.

I propose that it means

- can be written by humans
- with a text editor being the only tooling required
- while visually inspecting examples or the WGSL spec

**Comment by othermaciej** [comment]
Human writable is a spectrum, not a binary. 

There are programming languages that are writable entirely with a text editor using only ASCII, and yet are not practically human writable, except as a challenging intellectual exercise. Two examples: [Brainfuck](https://en.wikipedia.org/wiki/Brainfuck) and [SKI combinator calculus](https://en.wikipedia.org/wiki/SKI_combinator_calculus).

While no version of WGSL is likely to be a [Turing tarpit](https://en.wikipedia.org/wiki/Turing_tarpit) like the above examples, the extreme illustrates that we must give some consideration to pragmatics, and not just the mechanical fact that something can be written with a text editor.

I think the property we want is something like "human writable enough to be practical", or "reasonably human writable". In addition, more human writability is better other things being equal, or if the cost of more human writability is low enough.

**Comment by dneto0** [comment]
Thanks for the reminder of SKI combinators!  I set a course assignment to process them.... in 1996.

http://www.cs.toronto.edu/~chechik/courses/csc324/proj1.ps

**Comment by dneto0** [comment]
The following is a relevant snippet from https://github.com/gpuweb/gpuweb/issues/569#issuecomment-607002670

> 2. When discussing APIs that are well-behaved-by-default, I have formulated the argument as being "concerned about new programmers." This may have led to some miscommunication, which I regret and apologize for. We're concerned about programmers who are new to WebGPU, rather than people who have never programmed before in their lives.

My point is there is a path-dependency here, an open door to affinity bias and availability bias.

**Comment by othermaciej** [comment]
I think we have to do our best to balance valid consideration of path-dependency, familiarity and understandability, with avoiding risk of undue affinity bias. It’s unfortunate that this has to be something of a judgment call and not always 100% objective, but I think the CG has done pretty well so far.

**Comment by doug-moen** [comment]
This definition of "human writeable" is a very low bar. It excludes SPIR-V binary format, but it includes SPIR-V Assembly Language (https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Tools/+/spirv-0.99-rev32/syntax.md).

Since WebGPU is the replacement for WebGL on the web browser, and since the WebGL shader language is GLSL, I think that "human writeable" should include "easy to read and write for someone who already knows GLSL".

The point is that WGSL should be a high level language, at the same level as GLSL, rather than a low level language, at the same level as SPIR-V Assembly Language.

**Comment by jdashg** [comment]
I don't think there's anything that we can hit consensus on in the abstract here (that we haven't already), so we should document what we've agreed on, and to move forward by discussing specifics.

**Comment by Kangz** [comment]
Tentatively closing this, WGSL is almost fully-fleshed and I don't think anybody would disagree that it is "human writable".
