### ISSUE TITLE
Task: design images and samplers, and their operations

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#682]
We need to define syntax and operations for image texturing and storage image operations.

My plan would be to declare images and sampler variables declared at module-scope, with group and binding decorations.  This continues the pattern established with storage buffers and uniform buffers.

**Comment by dj2** [comment]
Textures: https://github.com/gpuweb/gpuweb/issues/573
Samplers: https://github.com/gpuweb/gpuweb/issues/574

**Comment by dneto0** [comment]
Whoops.
Closing as this is a duplicate
