### ISSUE TITLE
Syntax for "the zero value" for bool type, numeric types, and compositions of them

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#685]
It's handy to have a constant expression for the zero value for bool, float, integer, vectors, matrices, and arrays and structs of these types.
Let's call these "nullable" types.

I'm not entirely hung up on the 'null' name, but if T is a nullable type, then `null<T>` is the zero value for that type. 

Mirroring the text about "default values" in WGSL 3.7.1, we have:

    null<bool>    is false
    null<i32>     is 0
    null<u32>     is 0
    null<f32>     is +0.0  (positive zero, i.e. where the sign bit is 0)

A null vector is a vector with null elements.  A null matrix is a matrix with null component vectors.
A null array is an array of null elements.
A null structure is a structure with all its members being null.

All this corresponds to the OpConstantNull in SPIR-V.

Aside from being generally useful, this aids in translation from LLVM, where to fill a vector it uses a pattern starting with an undef vector and then fills it with a chain of insert-element instructions.  It's handy to replace any "undef" with a zero.

**Comment by jdashg** [comment]
Since this is the same as the defaults, and these do feel like defaults to me, `as<bool>() -> false` is sort of what I imagine.

**Comment by kainino0x** [comment]
I don't see an `as<>` in the spec today, but default values for constructors e.g. `bool()` `vec4<f32>()` (which we do seem to have) would be ~the same.

**Comment by dneto0** [comment]
A point of clarification:  GLSL has a runtime-array (and so does SPIR-V).  We would *not* want a zero-expression for a runtime-array because they are sized by the command submission, and so it wouldn't be a fixed value in the shader.

**Comment by dneto0** [comment]
I like @kainino0x's suggestion because it doesn't add any new keywords.  It reuses and existing construct.
We had been debating "null" "nil" and "zero" internally, but it's nice not having to choose any of them.

**Comment by grorg** [comment]
Discussed at the [2020-04-21 meeting](https://docs.google.com/document/d/1v6U_0yh3HQZ1rb53A4Mi_OgK9Mn6d0w9lYjDn2kkG_4/).

**Comment by kvark** [comment]
Sorry for jumping late into the fray. I'd like to understand what use cases this new construct would cover for us. Given that variables are initialized to zero by the spec, what else is there to cover with the special syntax?

**Comment by dneto0** [comment]
It's for when I want a blank value of the given type, without having to declare a variable.

A variable denotes an allocation of storage, which is a relatively heavyweight thing.  When performance-tuning a shader/kernel, the programmer has to manage a budget for per-thread storage. You fall off a performance cliff if you blow a budget.   It's best to have WGSL only require the declaration of a variable when you really mean a variable.

Values, on the other hand, are transient mathematical objects, at a lower conceptual level than a variable (a variable is a name for a reference to allocated storage, where that storage can store a value of a particular type.)

**Comment by kvark** [comment]
There is a misunderstanding here. If you need a value of vec3 initialized to zero, I'm *not* suggesting that you declare a dummy `vec3` variable that's implicitly initialized, and use that. That would be quite silly, wouldn't it?
What I'm suggesting is that the regular ways of constructing objects are used, e.g. `vec3(0f)`. Quite often the objects need to be initialized to non-zero (the avid example is matrices), that doesn't mean that we invent special *syntax* for this case. We just need to figure out how these objects are constructed (in terms of their own constructors), on a case by case basis.

**Comment by dneto0** [comment]
> There is a misunderstanding here. If you need a value of vec3 initialized to zero, I'm not suggesting that you declare a dummy vec3 variable that's implicitly initialized, and use that. That would be quite silly, wouldn't it?

That's a relief.  I'm glad.

> What I'm suggesting is that the regular ways of constructing objects are used, e.g. vec3(0f)

Ok.  @jdashg pointed out that GLSL converts that (via "splat") to what I would write as `vec3<f32>(0.0f, 0.0f, 0.0f)`.   That in itself is a shortcut in GLSL, and my conception of WGSL did not have even that.

To be blunt, SPIR-V has:

- OpConstantNull <type> : yields the zero value of the target type. 
    - Also corresponds to LLVM's  zeroinitializer, or ConstantAggregateZero feature
    - This is what I'm trying to propose for WGSL, but limited to specific family of WGSL types.
- OpUndef <type>   : yields an undefined value of the given type:  
    - No corresponding feature in WGSL because you can _always_ replace one of these with OpConstantNull
- OpConstantComposite <type> <elem0> ... <elemK> : yields a constant value of the target type, where the constant subcomponents are as given.  Can yield a struct value (and the member types have to match the elements given.); can yield an array _value_ (and number of elements has to match the array size, and match element type); can yield matrix, vector, as you might expect.
- OpCompositeConstruct <type> <eleme0> ... <elemK>; is like OpConstantComposite, but the elements don't have to be constants; use this in code in a function to construct non-constant composite values.


To capture programmer intent for my user base, I'd want natural analogs for OpConstantNull (this issue), and OpConstantComposite and OpCompositeConstruct.



Note: LLVM doesn't have the equivalent of OpCompositeConstruct, which means you get a lot of scalarized code for creating structs.

E.g. For this input OpenCL C:

```
typedef struct { float a, b, c, d; } S;

S boo(float a) {
  S result;
  result.a = a;
  result.c = a+2.0f;
  result.b = a+1.0f;
  result.d = a+3.0f;
  return result;
}

kernel void foo(global S* data, float f) {
  *data = boo(f);
}
```
You get LLVM code generation for the `boo` function that looks like this:

```
%struct.S = type { float, float, float, float }

define  %struct.S @boo(float) local_unnamed_addr #0 {
  %add = fadd float %0, 2.000000e+00
  %add2 = fadd float %0, 1.000000e+00
  %add3 = fadd float %0, 3.000000e+00
  %2 = insertvalue %struct.S undef, float %0, 0
  %3 = insertvalue %struct.S %2, float %add2, 1
  %4 = insertvalue %struct.S %3, float %add, 2
  %5 = insertvalue %struct.S %4, float %add3, 3
  ret %struct.S %5
}
```

So this is a chain of scalar insertions, starting with an "undef" struct value as the blank starting point.  For WGSL compilation we'd basically want that to be "zeroinitializer" instead, so that's one argument for a special case for a general "zero".

But the intent is really clear when you follow the chains of of insertions and see that the entire struct is covered.  In that case SPIR-V gives you a short cut which says "give me the entire struct, made up of these dynamic values".

So my compiler transforms that  eventually to this SPIR-V fragment:

```
  %_struct_2 = OpTypeStruct %float %float %float %float
...
         %29 = OpFunction %_struct_2 Const %12
         %30 = OpFunctionParameter %float
         %31 = OpLabel
         %32 = OpFAdd %float %30 %float_2   ; the sequence of 3 sums
         %33 = OpFAdd %float %30 %float_1
         %34 = OpFAdd %float %30 %float_3
         %35 = OpCompositeConstruct %_struct_2 %30 %33 %32 %34  ; Look!  a single instruction
               OpReturnValue %35
               OpFunctionEnd
```
FYI. I wrote an LLVM transform to do the key step to rewrite the scalar insertions into a wholisitic value initialization. See https://github.com/google/clspv/blob/77b87ad6258be49d431d3d6c59f147638d59e86b/lib/RewriteInsertsPass.cpp and a couple of its sample tests at https://github.com/google/clspv/blob/master/test/composite_construct.cl and https://github.com/google/clspv/blob/master/test/composite_construct_array.cl

That LLVM transform is heuristic only: there are cases where it will give up.  So I don't consider it a panacea to things that my user base needs.

On the flip side, if we already have the equivalent of OpConstantNull, OpConstantComposite, and OpCompositeConstruct in WGSL, then they are trivial to lower into more primitive operations for consumption by downstream language targets.

**Comment by kvark** [comment]
@dneto0 your comment reads to me as a call to have `OpCompositeConstruct` in the syntax. I agree, let's have that! It's supported by C99, Rust, and likely more languages.

**Comment by dneto0** [comment]
> @dneto0 your comment reads to me as a call to have OpCompositeConstruct in the syntax. I agree, let's have that! It's supported by C99, Rust, and likely more languages.

Yes, that.  In fewer words.  :-)

But for a big zero-initialized thing (e.g. a struct with 15 members), do we want to force WGSL users to spell out each of the members as zero.   That's where the OpConstantNull concept is handy.

**Comment by kvark** [comment]
The higher you go in type/struct complexity, the less likely I see users wanting to pass it by value specifically as all zeroes.

**Comment by grorg** [comment]
This was discussed at the [2020-05-05 meeting](https://docs.google.com/document/d/1K2H59am7yLj_DBv0lfuz7g52NNyF4xcQpBs1NNnhk8g/)
