### ISSUE TITLE
Binding to zero-sized range of a buffer

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#686]
Should we allow zero-sized ranges of buffers to be bound in bind groups?

Related to #546 on zero-sized buffers, but more complex.

From @kvark on that issue:
> For zero-sized bindings, an investigation is needed to see:
> 
> * whether zero sizes are allowed, in which backends
> * what alignment/minimum size requirements are in the backends
> * whether there are operations that don't rely on the range at all, i.e. getting the size of the buffer from the shader.

**Comment by kvark** [comment]
There is a use case I'd like us to support seamlessly. The user runs a compute job that has 2 inputs: array of X[] and array of Y[], both represented in it does something like that:
```hlsl
type Particle = struct {
  [[offset 0]] pos: vec3<f32>;
  [[offset 12] light_id: i32,
  [[offset 16]] color: vec4<f32>;
};
type Particles = struct {
  [[offset 0]] particles : array<Particle>;
};
[[binding 1, set 0]] var<storage_buffer> particles : Particles;

type Light = vec3<f32>;
type Lights = struct {
  [[offset 0]] lights: array<Light>;
};
[[binding 1, set 1]] var<storage_buffer> lights: Light;

fn evaluate_light(pos: vec3<f32>, light: Light) -> vec4<f32> { ... }

fn main() -> void {
  for particle in particles {
    if (particle.light_id >= 0) {
      particle.color += evaluate_light(particle.pos, lights[particle.light_id]);
    }
  }
}
```

So in this case, if there happens to be 0 lights, it would be sad to not allow the user to run this code, assuming the branch `particle.light_id >= 0` is never taken. And if it is taken - our regular OOB rules would apply.

**Comment by kvark** [comment]
Tentatively agreed that this is blocked on #678

**Comment by kainino0x** [comment]
I'm pretty sure this was resolved elsewhere: we need at least one element to allow clamping to work

**Comment by Kangz** [comment]
Put up https://github.com/gpuweb/gpuweb/pull/2258 that kinda fixes this.

Decided that 0 size bindings are ok, because as soon as the shader needs data, either the draw-time or createBindGroup-time `minBindingSize` validation will be triggered, so we don't need to validate !=0 at createBindGroup-time.

**Comment by kainino0x** [comment]
Ah, just saw this comment. Since that contradicts my previous comment, I suppose we leave this issue open for feedback a little bit longer.

Your reasoning seems correct to me though, in which case we can just close the issue, no change needed.

**Comment by kainino0x** [comment]
Editors: Dzmitry points out that there's really minimal value to this. Both possible codepaths would end up disallowing a bind group containing a zero-sized binding, so they can't be used for anything.

_If_ we wanted to allow zero-sized bindings, we would want it to be actually allowed in the backends - if not, we have to emulate zero-sized bindings either by (a) not actually creating the underlying object, or (b) rounding the binding size up so it's larger than 0.

Brandon found that it's not allowed in VkDescriptorBufferInfo:
> If range is not equal to VK_WHOLE_SIZE, range must be greater than 0

So - for a different reason than the originally stated one - we think we should still add this validation.

**Comment by Kangz** [comment]
I think I remember we discussed having a dummy buffer that can be used instead for VkDescriptorSet creation, but either solution sounds good.

**Comment by Kangz** [comment]
(slight preference for allowing empty buffers for the same reason as usual: data-oriented application might end up creating empty buffers. Plus Dawn can use itself re-entrantly so it would be easy to implement for us)

**Comment by kvark** [comment]
With `minBindingSize`, the test case I provided in https://github.com/gpuweb/gpuweb/issues/686#issuecomment-613071621 is no longer possible, regardless of the decision we make here. So the "data-oriented application" here needs to be re-clarified.

If the user has `minBindingSize != 0` in BGL, then zero-sized range isn't allowed.
If the user has `minBindingSize == 0`, then our decision here merely affects the point of failure - either in `createBindGroup` (if we disallow zero-sized-bindings) or in `draw()` (if we allow it, but it will still fail the `minBindingSize` reflected from the shader).

Therefore, a data-oriented application can't be generic, as it stands now, over the number of elements in a buffer (zero or non-zero). It already has to have a condition to check for this. The only thing changed is where this condition is.

**Comment by Kangz** [comment]
What if the shader doesn't have the binding / has a zero-sized type? I guess it's a bit of a stretch so happy with either resolutions.

**Comment by kainino0x** [comment]
I'm not even sure whether shaders can have zero sized types. I could imagine it happening though, in particular zero-sized arrays.
