### ISSUE TITLE
Lever + Webgpu

### ISSUE THREAD

**Issue by cheery** [gpuweb/gpuweb#7]
I were inspired about webgpu announcement and continued with Vulkan bindings in [my own programming language](https://leverlanguage.com/).

http://boxbase.org/entries/2017/feb/13/lever-and-webgpu/

https://github.com/cheery/lever/blob/master/samples/warpgpu/app0.lc
https://github.com/cheery/lever/blob/master/lib/sdl.lc

Maybe this inspires you back.

**Comment by grorg** [comment]
Thanks.
