### ISSUE TITLE
Position: expose render and command passes within command buffers

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#70]
This is Mozilla's new proposal for #64. The core of the proposal is to have the command buffer semantic equivalent of the one provided by the native API, and have render and compute passes similar to Metal.

The command buffer is the unit of submission of work to GPU. It could be created as "re-usable" to allow multiple submissions, or "one-time" for it being consumed by the submission. A command buffer API consists of the following parts:
  - begin/end of a render pass with specified targets. Beginning a render pass returns a render pass encoder that is used for encoding draw states and commands. While the encoder is active, i.e. between it's creation and `finish()` call, no other commands are permitted on the command buffer (it's considered uniquely borrowed).
  - begin/end of a compute pass. Similarly, a compute pass is encoded via a separate API object (compute encoder) that has methods for state setting and dispatch calls. A compute pass also borrows the command buffer uniquely for it's lifetime (until the `finish()` method is invoked).
  - transfer commands, such as filling buffers or images, copying data between them.

Both compute and render encoder API objects would inherit from a common interface (e.g. `WebGPUResourceEncoder`, naming is hard) that has methods for binding resource groups and pipeline states. We believe this makes up for a good class hierarchy and strong typing.

Reasons to not have transfer/blit passes:
  1. unlike render/compute, they don't have the resource context, and consequently can't derive from `WebGPUResourceEncoder`
  2. unlike render/compute, they don't enforce the constant resource usage of all the participating resources
  3. some of the "transfer" operations, like clearing an image, may have to translate to Metal render passes, which means there couldn't be a 1:1 relationship between WebGPU transfer passes and Metal backend passes

If we go back to the concerns expressed in #64, here is what we get with this proposal:
  - "Resource bindings inheritance" - no inheritance, resource binding is encapsulated withing render/compute passes
  - "Synchronization and validation" - a command buffer operation becomes our unit of synchronization, plus some extra UAV barriers within a compute pass.
  - "Work scheduling" - there is still an option for the backend to use multiple queues
  - "Command re-usal" (not listed there, but needs to be) - the proposal makes a clear path for re-usable command buffers, while leaving the bundles/secondary command buffers for later.
  - "Type safety" - we all the benefits of type safety

**Comment by kainino0x** [comment]
While we're at it, I noticed this a while back: if `finish()` returns the original `WebGPUCommandEncoder`, it allows code which looks just like what we have today with `begin`/`endRenderPass`:

```js
let cmdbuf = device.createCommandEncoder(...)
  .createRenderEncoder(...)
    .draw(...)
    .finish()
  .createComputeEncoder()
    .dispatch(...)
    .finish()
  .blit(...)
  .finishEncoding();

**Comment by RafaelCintron** [comment]
Thank you for putting this together @kvark. 

I have some questions about your plan:

> While the encoder is active, i.e. between it's creation and finish() call, no other commands are permitted on the command buffer (it's considered uniquely borrowed).

It wasn't clear to me from the meeting notes whether it was decided that a developer can have multiple passes, either of the same kind or different kind, active at the same time. This Github issue implies the answer is 'No' as the command buffer is considered "uniquely borrowed" while a pass is active.

I personally vote for 'No'. 

> A command buffer operation becomes our unit of synchronization, plus some extra UAV barriers within a compute pass.

I presume that a pass is considered a single "command buffer operation", per above?

In general, I am supportive of passes as a whole being a unit of sychronization. In D3D12, all writes, including UAV writes, from within a render pass are not valid to be read until the end of the render pass. This restriction means that certain operations inside of a render pass are not allowed: transitions from RENDER_TARGET to SHADER_RESOURCE, resource copying, clear operations, UAV barriers and others.

What is the plan when the WebGPU API encounters a sequence of draw commands where the developer draws to a texture and subsequently uses the texture as a shader resources? I presume this will be considered an error?

What is the plan for UAV reads and writes during a render pass that happen as part of draw commands? Will those be disallowed entirely? 

How are implementations going to determine which UAV barriers to insert during a compute pass? Is the plan still to optimize based on current resource bindings and what the shader itself says (if anything) about how the bindings are used?

**Comment by Kangz** [comment]
> I personally vote for 'No'.

That was the consensus during the meeting too.

> What is the plan when the WebGPU API encounters a sequence of draw commands where the developer draws to a texture and subsequently uses the texture as a shader resources? I presume this will be considered an error?

Yep it is an error in the [usage validation rules](https://github.com/gpuweb/gpuweb/blob/master/design/UsageValidationRules.md).

> What is the plan for UAV reads and writes during a render pass that happen as part of draw commands? Will those be disallowed entirely?

They are racy and it is the application's responsibility to make their code data race free. Preventing UAV writes during render-passes seems too important for us to prevent it in WebGPU.

> How are implementations going to determine which UAV barriers to insert during a compute pass? Is the plan still to optimize based on current resource bindings and what the shader itself says (if anything) about how the bindings are used?

Yes, it's expected that implementations will look into the resource bindings and put a UAV barrier if any of the resources conflicts with another dispatch done since the last UAV barrier. A conflict is if any of the dispatches write to a resource the other uses. It would also be valid to do a UAV barrier after every dispatch though very suboptimal.
