### ISSUE TITLE
Missing mapping for OpFRem, and MODULO token missing

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#702]
There is a grammar case for MODULO:
```
  | multiplicative_expression MODULO unary_expression
      OpUMOd
      OpSMod
      OpFMod
```

First issue: The MODULO token is not defined.   I presume it's `%`

Second:  We need a mapping or builtin function for OpFRem
OpFMod and OpFRem differ only in which input operand to match sign with.

FRem: The floating-point remainder whose sign matches the sign of Operand 1.
FMod: The floating-point remainder whose sign matches the sign of Operand 2.

**Comment by dj2** [comment]
Looks like I called it `MOD` in the token list and `MODULO` in the grammar usage. Need to make them match.

**Comment by dneto0** [comment]
Similarly missing signed integer remainder. (OpSRem).

**Comment by dneto0** [comment]
#772 adds renames the MOD token to MODULO

**Comment by jdashg** [comment]
Pretty sure we've handled mod pretty thoroughly at this point. :)
