### ISSUE TITLE
Consider whether we need a quantize-f32-value-to-f16

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#704]
#658 proposes an FP16 feature
#667 is a task list to define a standard library

SPIR-V has an [OpQuantizeToF16](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpQuantizeToF16) instruction which is equivalent to doing a value-cast from fp32 to fp16 and back again, but without ever having to mention the 16bit floating point type.  This is useful to make a more-capable implementation emulate a less-capable implementation when doing operations with ambiguously-defined precision, and where no 16bit feature is actually supported. For example GLSL mediump and lowp translate into SPIR-V fp32 operations with "RelaxedPrecision" semantics, meaning roughly "compute with some precision between 16 and 32 bits."

Consider whether the WGSL standard library should have an equivalent feature.

**Comment by kainino0x** [comment]
I assume this has considerable performance cost, right? We wouldn't want to use this emulation to expose FP16 in core (which I thiiiink is possible)?

**Comment by dneto0** [comment]
It's not intended to be for a mainstream flow.    It's for validating your application on, say desktop, when you know it has to run similarly on various mobile devices.

**Comment by litherum** [comment]
No issues from our side. Our devices support FP16 natively.

**Comment by dneto0** [comment]
Looking at this again, we kind of have this already by stealth by composing unpack2x16float with pack2x16float, but those would operate on pairs.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-07-13-Minutes#consider-whether-we-need-a-quantize-f32-value-to-f16-704">WGSL meeting minutes 2021-07-13</a></summary>



* DN: We do have the pack/unpack ops already, so you can more or less do this already.
* DM: How is this done on Metal?
* DN: Just convert twice.
* GR: Support for f16 in hlsl exists.
* DM: So people would use this without 16bit floats, such as knowing what they’ll get when outputting to f16 render targets?
* DN: Yes, authors have use for it, though it’s niche, though it does exist as part of authors’ flows, for validation purposes/testing if “can I convert all this code to f16 safely”. It’s part of existing development processes.
* DM: Would SPIR-V put relaxed precision on the vars then?
* DN: It’s usually a compiler flag.
* 

 


</details>
