### ISSUE TITLE
Add unordered float compares

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#706]
Part of #667

E.g. see https://llvm.org/docs/LangRef.html#fcmp-instruction 

The ordinary comparisons like ==, <,  >=, etc. should be the _ordered_ comparisons. 
That is, they should yield `false` if either operand is a NaN.

The unordered operations are corresponding operations, but where the result is `true` if either operand is a NaN.  These are interesting and useful because they make it easy to push inversions through:

  
     ! ( a < b)     

is the same as

    (  a  unordered>= b)

(I think I got that right)

I'd like to have a standard way to express these unordered comparisons. It's fine if they are builtin functions with long names.

**Comment by jdashg** [comment]
I don't like the "unordered" name, since it's equally as (un-)ordered as false-if-nan.
Since `!(a < b)` iff `(a unordered>= b)`, this might be niche enough that we ask authors to use the `!(a < b)` form if they want that behavior. (unless I'm misunderstanding the equivalence!)

**Comment by litherum** [comment]
It's worth doing an investigation here, about what HLSL and MSL do for `<`, and what you could type in those languages to produce the other behavior.

**Comment by dneto0** [comment]
As far as I know, only compilers generate the unordered compares, exactly because they push inversions through the ordered inequality.
Frankly, I only ever absorbed this stuff when trying to grok LLVM's fcmp instruction: https://llvm.org/docs/LangRef.html#fcmp-instruction

So.. probably too niche.

For round-tripping considerations, it means adding the inversion and having canonicalization understand how to normalize it away.

**Comment by grorg** [comment]
This was discussed at the [2020-05-05 meeting](https://docs.google.com/document/d/1K2H59am7yLj_DBv0lfuz7g52NNyF4xcQpBs1NNnhk8g/)

**Comment by grorg** [comment]
Resolved that the developer would need to write a more complicated expression if necessary. Otherwise this is hidden in the canonicalization.
