### ISSUE TITLE
Rule for mixed-signedness operands to integer div, rem, less-than, greater-than, less-or-equal, greater-or-equal

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#707]
In SPIR-V the rule on integer operations is that the signedness-semantics is determined by the opcode, not the signedness of the type of the operands

This is why, for example, it has both OpSLessThan, OpULessThan (for scalar integer values %a and %b of the same bit width):
 
* `%result = OpSLessThan %bool %a %b`
     * Ignore the signedness of operands %a and %b compare them as if they are both signed.
* `%result = OpULessThan %bool %a %b`
     * Ignore the signedness of operands %a and %b compare them as if they are both unsigned.

Similarly, there are "U" and "S" variants for Div, Rem, > ,  <=, >=

I think we might have touched on this issue in an earlier meeting but I don't recall a firm resolution or record in the WGSL spec.

I _think_ the favoured option was:

* For these binary operations, it's only valid to have operands with consistent signedness.  The programmer has to insert bit-level (reinterpretation) "as" casts in order to achieve signedness-consistency.

**Comment by litherum** [comment]
That sounds right to me.

**Comment by grorg** [comment]
Discussed at the [2020-04-21 meeting](https://docs.google.com/document/d/1v6U_0yh3HQZ1rb53A4Mi_OgK9Mn6d0w9lYjDn2kkG_4/).

**Comment by dneto0** [comment]
The summary from the meeting discussion is that yes, WGSL should enforce consistent signedness across operands for such operations.  Also, when the result is also integral, that the result type should match the argument types

This applies to:
* integer division
* integer remainder and modulus
* <,  <=, >, >=

I filed https://github.com/gpuweb/gpuweb/issues/726 to track spec writing for type rules for binary operators.  The draft already has a start on type rules for unary operators. https://github.com/gpuweb/gpuweb/blob/d05d63c37f34c32f95e084d457b6a9a253e59a1b/wgsl/index.bs#L1539

**Comment by grorg** [comment]
This was discussed at the [2020-05-12 meeting](https://docs.google.com/document/d/1o02gfmnnaLpaYY5Dtla0xQYEUzNGhuW5aPREkj7Pycw/).

**Comment by dneto0** [comment]
This is part of writing the type rules for binary operators: https://github.com/gpuweb/gpuweb/issues/726

**Comment by johnkslang** [comment]
> when the result is also integral

I'm probably reading this ambiguously, but, you wouldn't be having a signedness discussion about floating point operands or results.

**Comment by dneto0** [comment]
Hey @johnkslang 
> I'm probably reading this ambiguously, but, you wouldn't be having a signedness discussion about floating point operands or results.

Right.

It stems from having stated a broader rule:

> WGSL should enforce consistent signedness across operands for such operations.

I didn't scope that "such operations" correctly.

I just meant that when you see something like  +  that its two operands must be the of the same type.  That covers the float case too.

**Comment by grorg** [comment]
I think we can close this and continue in #772 and #726
