### ISSUE TITLE
Proposal: Support C99 hex float literals to accurately capture float values

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#709]
Originally: https://github.com/gpuweb/WSL/issues/351

Decimal notation for floating point numbers is fine for common cases, but confusingly lossy.   E.g. 1.5 vs. 1.3
Sometimes you really want to control exactly which floating point number is used, e.g. for mathematical constants like approximations to Pi, or for testing things like NaN-handling.

C99 hex float syntax is a worked-out absolutely unambiguous syntax for getting exactly the floating point numbers that you want.  WGSL should support this additional syntax.

**Comment by litherum** [comment]
Yes, good idea.

**Comment by grorg** [comment]
This was discussed at the [2020-04-28 meeting](https://docs.google.com/document/d/1zUMz2oU5ovhxK_qx4MB8wKFZbOmOdOXU-LPLkrLl9go/).

**Comment by grorg** [comment]
Resolution was to support C99 hex float literals.
