### ISSUE TITLE
Is a switch default clause always required?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#714]
This was raised by https://github.com/gpuweb/gpuweb/pull/713

We need to say what happens when a switch selector expression evaluates to something other than any of the case literals.

Since we have a desire to avoid undefined behaviour, I **propose that a switch statement must always have a default clause**.

The alternative is to make a rule that control skips past the switch statement entirely, but that's quite non-traditional and hence inadvisable.

**Comment by RobinMorisset** [comment]
I am in favor of a rule that the set of cases must fully cover the range of values of the type being switched upon. Since we don't have enums in the language, I believe that is in practice the same as requiring a default clause in all cases.

**Comment by litherum** [comment]
Another option is to make the `default` implied, and make it skip the entire `switch` block.

**Comment by kainino0x** [comment]
> The alternative is to make a rule that control skips past the switch statement entirely, but that's quite non-traditional and hence inadvisable.

I don't understand, how is this different from the rule used by most languages including C?

> Another option is to make an absent `default` implied, and make it skip the entire `switch` block.

Same question here.

**Comment by litherum** [comment]
Yes, it’s the same, I just didn’t read the OP carefully enough.

**Comment by dneto0** [comment]
Ok, I had to look it up.

I stand corrected.  You're absolutely right.   From [C2x draft](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2454.pdf) (6.8.4.2 para 5)

> If no converted case constant expression matches and there is no default label, no part of the switch body is executed.

So suggest we close this, and I should go back and make WGSL match C here.

**Comment by grorg** [comment]
This was discussed at the [2020-04-28 meeting](https://docs.google.com/document/d/1zUMz2oU5ovhxK_qx4MB8wKFZbOmOdOXU-LPLkrLl9go/).

**Comment by grorg** [comment]
Resolution was to not require a `default` clause

**Comment by dj2** [comment]
I think the resolution was to require a `default` as we can relax it later if needed?
