### ISSUE TITLE
Proposal: Permit redundant as-casts

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#715]
Example:

     const x : u32 = 12;
     const y : u32 = as<u32>(x);

Here the cast is redundant because its operand is already a value of the target type.

Should we allow this?  Or should we disallow it on the argument that it is likely a programmer error?

I propose that we allow it.

FYI: SPIR-V takes the opposite choice.  For OpBitcast, the result type must not equal the operand type.

**Comment by litherum** [comment]
What's the argument for not allowing it? All I see are upsides.

**Comment by kainino0x** [comment]
> Or should we disallow it on the argument that it is likely a programmer error?

A no-op cast could be a symptom of the input-type being not as expected by the programmer.

But I think that's a bad lint rule, and am also in favor of allowing this.

**Comment by litherum** [comment]
Perhaps this could be a way to get a WGSL -> SPIR-V compiler to emit an OpCopyObject.

**Comment by dneto0** [comment]
> Perhaps this could be a way to get a WGSL -> SPIR-V compiler to emit an OpCopyObject.

I would expect we don't need to go that far.  I expect that we'd get an OpCopyObject from an even simpler WGSL code sequence:

       const x : u32 = 12;
       const y : u32 = x;   // I expect this is effectively %y = OpCopyObject %uint %x


I think it's a slam dunk to permit redundant casts. It makes for a nice regularity, and is forgiving of users and mechanical generators.
A SPIR-V binary is expected to have mechanical processing that can sweep away redundant casts via peephole transforms.  So it's entirely appropriate to have different choices for the two different languages.

**Comment by dneto0** [comment]
It may be that if redundant as-casts are permitted, then no spec change is required.

**Comment by grorg** [comment]
This was discussed at the [2020-04-28 meeting](https://docs.google.com/document/d/1zUMz2oU5ovhxK_qx4MB8wKFZbOmOdOXU-LPLkrLl9go/).

**Comment by grorg** [comment]
Resolved to accept this.

**Comment by Kangz** [comment]
Tentatively closing. The `as<>` syntax was removed in favor of conversion expressions.
