### ISSUE TITLE
[wgsl] Describe the assignment statement

### ISSUE THREAD

**Issue by doug-moen** [gpuweb/gpuweb#719]
The WGSL standard should add a section fully describing the syntax and semantics of the assignment statement.

No such section exists right now.

The grammar has a rule called `assignment_stmt`:
```
assignment_stmt
  : primary_expression EQUAL logical_or_expression
```
This grammar allows `foo = 42`, and it allows `17 = 42`, as legal assignment statements. However, it does not allow `a[i] = 42` or `a.foo = 42`.

**Comment by dj2** [comment]
The assignment change was an un-intended side effect of https://github.com/gpuweb/gpuweb/pull/604 it should be:

```
assignment_statement
  :  unary_expression EQUAL logical_or_expression
```

@kvark the assignment needs to be a unary on the left side so it works for the various assignment statements.

I'm not sure why you say everything needs to be re-written.
