### ISSUE TITLE
In GPULimits there is no parameter maxVaryingVectors/maxVertexOutputComponents

### ISSUE THREAD

**Issue by lain-dono** [gpuweb/gpuweb#721]
There is no way to get the maximum possible number of 4-element vectors that can be used as varyings.

Note: `maxVaryingVectors` is a name from the WebGL. Thus, I think that [WebGL 1 stats](https://webglstats.com/webgl/parameter/MAX_VARYING_VECTORS) and [WebGL 2 stats](https://webglstats.com/webgl2/parameter/MAX_VARYING_VECTORS) can be used as a reference point to determine the default value. Vulkan calls this parameter [MaxVertexOutputComponents](https://vulkan.gpuinfo.org/displaydevicelimit.php?name=maxVertexOutputComponents).

**Comment by Kangz** [comment]
This has been added as `maxInterStageShaderComponents` in the spec.
