### ISSUE TITLE
Should all expressions have known types?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#723]
[edit:] This was previously raised in detail by @kvark [here](https://github.com/gpuweb/gpuweb/issues/560#issuecomment-592065891).

In particular, this would preclude certain syntax proposals, impacting the following discussions:

- #685: can't have a syntax like `const x: vec3<f32> = {};`, can have a syntax like `const x = vec3<f32>();`.
- Numeric literals and #575: can't have an "un-narrowed integer literal" type; can't have `const x: u32 = 1;`, would use `const x = 1u;`.
- #560: This makes it always possible to omit type annotations on `const`/`var` - they become simple type assertions, as there’s only one valid type annotation. It's even possible to remove them from the grammar (@jdashg [proposed](https://github.com/gpuweb/gpuweb/issues/560#issuecomment-593250258) this before).

I think this is a desirable trait for simplicity and explicitness of the language, and aside from numeric literals I think it has very little negative impact on authorability.

**Comment by dneto0** [comment]
I think you mean the type is derivable in a bottom-up fashion.   I think that's _generally_ desirable, for conceptual an implementation simplicity.

**Comment by kainino0x** [comment]
Yes, exactly.

**Comment by kvark** [comment]
As I mentioned in https://github.com/gpuweb/gpuweb/issues/560#issuecomment-592065891
> Personally, I think it's a useful property to have, and we should enforce it.

**Comment by litherum** [comment]
It's possible to have different rules for initializers and for regular rvalues. E.g.

```
const x: vec3<f32> = {};
```

You just said what the type of the `{}` is: it's a `vec3<f32>`.

However,

```
x = 3 + {} * {};
```

This is a much more troublesome situation. I agree that this case should be a compile error.

**Comment by kainino0x** [comment]
The first example requires type inference to go outside-in by one layer, which is feasible. The second requires more than one step, and I think it clearly shouldn't be supported.

I advocate to not allow outside-in type inference at all. I think it *significantly* simplifies the implementation (completely removes type inference) with very little relative downside.

**Comment by grorg** [comment]
This was discussed at the [2020-05-05 meeting](https://docs.google.com/document/d/1K2H59am7yLj_DBv0lfuz7g52NNyF4xcQpBs1NNnhk8g/)

**Comment by grorg** [comment]
Resolution was that all expressions have known types. We'll add some text to the spec explaining this.

Any editor can take the PR to fix this.

**Comment by Kangz** [comment]
Closing this: the group seems to be in agreement to have some type of literal unification so not all sub-expression will have a known type. See both #2306 and #2227.
