### ISSUE TITLE
Task: Define type rules for binary operations

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#726]
E.g. see decision on consistent-signedness of operations acting on integers https://github.com/gpuweb/gpuweb/issues/707

**Comment by kvark** [comment]
Is this supposed to be a meta issue? I this case, let's have a list in the body.

**Comment by johnkslang** [comment]
If its not on radar, this is more obvious for `*` and `+` than it is for `<<` and `>>`, which take asymmetric semantic cues from operand sign.
