### ISSUE TITLE
Disallow fragment atomic ops on texture storages

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#728]
This is a tiny subset of #639. It looks like Metal doesn't atomic ops on texture storages in fragment shaders. SPIRV-Cross goes lengths to work around this by having a separate storage buffer (presumably, mirroring the texture). See https://github.com/KhronosGroup/SPIRV-Cross/issues/835 and https://github.com/gfx-rs/wgpu/issues/618 for some context.

**Comment by dneto0** [comment]
Discussed [2020-09-22](https://docs.google.com/document/d/1CFkoT9Iqdwej_OW5TXbOHSMVxfMnrWKwf7bOuXgPx2U/edit#)

- Disallow atomic operations on textures, as Metal does not support it.

**Comment by pow2clk** [comment]
I was sufficiently surprised by this deficiency that I tried to find its documentation. I am quite ignorant over the metal documentation, but the closest thing I found in https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf was some comments on the effect of helper threads contributing to output, 

> Stores and atomic operations to buffers and textures performed by helper threads have no effect on the underlying memory associated with the buffer or texture.

Which has more to do with helper threads than atomic operations in pixel shaders. Do we know where this is documented?

**Comment by dneto0** [comment]
@litherum pointed out that MSL textures are their own type, and there are no built-in function overloads that perform atomic operations on those texture types.
So it's disallowed because you can't utter a statement to do so.

**Comment by dneto0** [comment]
> Stores and atomic operations to buffers and textures performed by helper threads have no effect on the underlying memory associated with the buffer or texture.

That sentence packs a lot of things into one sentence.  It reads as if you can do atomic stores on textures, which is unfortunate.

**Comment by dneto0** [comment]
The WebGPU spec says in 22.1.1 Plain color formats:

> If there is a (star) mark, the atomic operations on the storage are also suppored for this format.

The star mark is on r32uint and r32sint formats.

**Comment by kvark** [comment]
I suppose we'll have to cut that out of WebGPU spec due to MSL not having this.

**Comment by kvark** [comment]
The spec text now doesn't mention atomics for the texture formats, we can close this.
