### ISSUE TITLE
Investigation: GPUQueue.writeBuffer implementation

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#734]
As promised, here is an overview of how we intend to [implement GPUQueue.writeBuffer in Chromium](https://hackmd.io/rE45ZEo_S4SvZqw_-us43g?view) if #509 is accepted.

**Comment by kvark** [comment]
Thanks Austin, this is great to have! It is much more detailed than I expected, even :)

Just a note that "Importing Cross-Process Shared Memory into the GPU driver" applies equally to any proposals of data transfers, mapping or whatnot.

**Comment by kvark** [comment]
@austinEng are you using `GPUTransferBuffer` for implementing `CreateBufferMapped` as well?
I was thinking, since the desired semantics for it is one-time initialization, allocating a temporary staging space in a ring buffer is a perfectly valid implementation for it.

**Comment by austinEng** [comment]
@kvark I think we could use `GPUTransferBuffer` it in a similar way for `CreateBufferMapped` or `createBuffer` with the `mapAtCreation` member, though I don't think the staging space could be ring buffer allocated since the staging space must live until the developer calls `unmap()`. There would have to be a more general allocator.

Slightly related: I think the difference in lifetime is what makes it difficult to polyfill `GPUQueue.writeBuffer` with `CreateBufferMapped` with the same performance. Also, as you mentioned previously, `CreateBufferMapped` would need to`memset` the staging data.

**Comment by kvark** [comment]
Yeah. I think it's ok for it to be ring-allocated as well. A malformed application would just run out of shmem and fail. A normal application would be more efficient with ring allocation than with general allocation. The point I'm trying to make is that this machinery of `GPUTransferBuffer` is pretty much what we'd do for *just* `mapAtCreation` today. In this case, the additional implementation cost for `writeBuffer` is near zero.

**Comment by austinEng** [comment]
That's interesting. I'm not sure I agree on merging the allocation strategies for the two functions is ultimately best. There may be valid use cases where there are long lived allocations from `mapAtCreation` like a slow decode into the buffer, happening simultaneously with numerous `writeBuffer` uniform updates.  If it's all the same ring buffer, reusing the staging data for the uniforms will be blocked on `unmap` of the `mapAtCreation` buffer.

Regardless, I do agree that there isn't significant additional implementation cost for `writeBuffer` because we plan to do this cross-process GPU shmem importing anyway. After that, it's just a matter of choosing a sub-allocation strategy. I would think the browsers already have some pre-existing code for that.

**Comment by kvark** [comment]
I believe this can be closed now as `writeBuffer` is a part of the spec, and it has at least 2 implementations.
