### ISSUE TITLE
Provide more vector constructors

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#738]
It's common in shaders to see things like `float4(myFloat3, 1.0)`. We should figure out a way to make this work.

**Comment by kainino0x** [comment]
cc #732, and also I think(?) I saw someone say that the syntax you described is already in the language

**Comment by dj2** [comment]
Can this be closed, or are there more vector constructors to consider?

**Comment by litherum** [comment]
Duplicate of https://github.com/gpuweb/gpuweb/issues/667
