### ISSUE TITLE
Wave Intrinsics in Secure HLSL

### ISSUE THREAD

**Issue by mehmetoguzderin** [gpuweb/gpuweb#74]
Hello,

I might have overlooked it but is there any possibility of support for waves/wavefronts/warps in WebGPU and Secure HLSL? And with the backing for quad groups in Metal for iOS, it is a topic of overlap in target APIs.

Thanks.

**Comment by kvark** [comment]
That seems fairly far-fetching. We haven't done the relevant investigation bits just yet. We'll likely want to address this later down the road, after MVP.

**Comment by mehmetoguzderin** [comment]
Could I help with the investigation?

**Comment by kvark** [comment]
@mehmetoguzderin absolutely! See how we have [investigation-labeled](https://github.com/gpuweb/gpuweb/issues?q=is%3Aissue+is%3Aopen+label%3Ainvestigation) issues? If you analyze support for wave intrinsics in different shading languages and see how they can be supported via a single API, you could write up the investigation here.

There is however somewhat of a blocker - the group hasn't decided on whether direct translation from WebHLSL to other (non-SPIRV) languages is required (in scope of the working group) yet. Perhaps, you could post your investigation at https://github.com/gpuweb/WHLSL instead?

**Comment by litherum** [comment]
We need to determine whether or not an acceptable level of devices can use them. If almost all devices hard hardware to support them, we can include them, otherwise, we shouldn't.

Also, I'd appreciate it if you would migrate this issue to https://github.com/gpuweb/WHLSL/issues

**Comment by mehmetoguzderin** [comment]
Thanks for the guidance, I will try to progress in a compatible way with existing work and aims.

**Comment by kvark** [comment]
Looks like this issue can be closed.
