### ISSUE TITLE
Function constants

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#740]
(This has implications both for the shading language and for the Javascript API)

We've heard from many MSL developers that function constants are very important to reduce compile times. The idea is that they compile their sources once, and then can "specialize" their source to enable/disable different codepaths using function constants. The specialization step is much faster than a full compilation.

I'm happy to provide a benchmark if it's necessary.

**Comment by dj2** [comment]
Are these different from specialization constants requested in https://github.com/gpuweb/gpuweb/issues/572?

**Comment by litherum** [comment]
Duplicate of https://github.com/gpuweb/gpuweb/issues/572
