### ISSUE TITLE
A single shader is often split among many source files

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#741]
When writing shaders, it's common to move helper functions into header files or .hlsli files. A single shader is often not fully contained within a single file. Indeed, shader sources are often contained in a large tree of files, traditionally joined together by using `#include`. We should support this use case.

There are a few possible ways we could do this:
1. Have `GPUProgrammableStageDescriptor` accept a `sequence<GPUShaderModule>` instead of just a single one
2. Allow `GPUShaderModule` to accept a TAR file or a ZIP file containing a tree of sources
3. Add a way for the browser to automatically fetch includes from a web server. This would require a shader author to provide a "base URL" to the browser so the browser knows what to fetch.

As far as how `#include` would work, I think there are three options:
1. Have an `#include` statement, and it's a textual include, just like HLSL
2. Make it work like javascript modules, where files can export and import functions
3. Make it work like Swift, where there's no "tree" of includes, and instead dependencies are just automatically resolved across the entire project. Function visibility is indicated by the programmer adding optional annotations to their functions.

**Comment by Kangz** [comment]
That's a nice list of how the browser could do it for applications. However I'm not sure the browser should do it, it is trivially easy to do it in Javascript. I've done it in around 50 lines here: https://github.com/Kangz/WebGLFluid/blob/master/lib/glExtras.js#L14

**Comment by frzi** [comment]
Much like a preprocessor, the community will most likely come up with their own - and maybe even better - ‘solutions’. Whether as internal concepts (like Kangz’ example) or more community-driven (like glslify). It sounds a bit excessive to have the browser implement such a feature.

`#include` also feels a bit dangerous considering `#` starts a comment in wgsl. 😉

**Comment by mehmetoguzderin** [comment]
> 1. Have `GPUProgrammableStageDescriptor` accept a `sequence<GPUShaderModule>` instead of just a single one

I think this one would work great.

> 3. Add a way for the browser to automatically fetch includes from a web server. This would require a shader author to provide a "base URL" to the browser so the browser knows what to fetch.

Wouldn't this make it somewhat harder for people that work on static files, AFAIK it is not possible to define a data URL that expands to multiple resources?

**Comment by magcius** [comment]
From personal experience, forcing the web APIs to take a URL is often very painful. Spawning web workers based on strings involves using `new Blob` and `window.URL.createObjectURL`.

Given that this is easily implementable in userspace code, and given we expect web API users to implement their own tooling like preprocessors anyway, I would prefer a WGSL to have a smaller scope.

**Comment by kainino0x** [comment]
It's important to think about whether there's a separation between including and linking in WGSL. I think we could go either way, but if there is a split then pre-link forward declarations will have to be possible.

> * Have `GPUProgrammableStageDescriptor` accept a `sequence<GPUShaderModule>` instead of just a single one

I think this is the only practical link-step solution of the ones listed. That said, if simple concatenation will work, I think this is not an MVP feature and can be done extremely easily in userspace. Especially if naive concatenation of entire WGSL files works (i.e. doesn't need `#include` in the middle of a file).

**Comment by dneto0** [comment]
Easily gluing together program fragments was one of the arguments for a text-based ingestion language.

This belongs in user-space, e.g. in JavaScript.

**Comment by grorg** [comment]
Discussed at the [2020-06-24 WebGPU Virtual F2F](https://docs.google.com/document/d/1uv0LiQB2gAFbUEU3qx2-Sgsv6r3fEKMvnifbFoRbvmw/).

Resolution: Not needed for MVP. Developer can build them on the client side.

**Comment by grorg** [comment]
Related topic of using functions/variables before their definition continues in #875.

**Comment by Strange4** [comment]
Is this issue still being tracked somewhere else?

I think using multiple files without hacking them together is very useful, especially when it comes to trying to correct errors (without running the shader) with something like [naga](https://github.com/gfx-rs/wgpu/tree/trunk/naga). I'm trying to write a pretty sizeable amount of wgsl code and hacking together files then starting the application seems like a very mind degrading development loop.

**Comment by greggman** [comment]
There's a solution [here](https://github.com/gpuweb/gpuweb/issues/568#issuecomment-1783827472). You can implement a similar solution for yourself

**Comment by Strange4** [comment]
> There's a solution [here](https://github.com/gpuweb/gpuweb/issues/568#issuecomment-1783827472). You can implement a similar solution for yourself

Is the solution then to code a preprocessor for all the times that someone wants to code in multiple files?
I think that something as common and useful as this should be directly implemented by the language.

Thank you for the interim solution though, I will use that until there is something better.

**Comment by greggman** [comment]
> Is the solution then to code a preprocessor for all the times that someone wants to code in multiple files?

The solution is likely for someone to write a popular library and for you to then use it.

**Comment by litherum** [comment]
Top level functions and variables don't have to be placed in-order, so if you have many files, you can just naively concatenate them in any order and it should just work.
