### ISSUE TITLE
Describe "shadow" usage bits

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#745]
The usage scope validation considers usage bits at higher granularity than what the user specifies, as described in https://github.com/gpuweb/gpuweb/issues/514#issuecomment-623047982
We need to specify carefully what the "shadow" usage bits are (i.e. `STORAGE_READ`), and how they relate to the user-visible bits.

**Comment by kainino0x** [comment]
I think we should fully separate the concepts of resource-creation usages and usage-scope usages. Each usage-scope usage can require a resource-creation usage in a simple mapping.

**Comment by kvark** [comment]
Yes, that's pretty much what this issue is about :)

**Comment by kainino0x** [comment]
Yup, just putting in an opinion about that approach vs saying "the usage scope usages are the resource creation usages plus these extra ones"

**Comment by kvark** [comment]
Yes, indeed, there are different ways to look at it.
One such way is to consider that every user-visible usage can be seen as either read-only or mutable, which is amplified by the API proposal in #860
