### ISSUE TITLE
Workgroup Size builtin decoration restrictions.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#750]
In Vulkan the WorkgroupSize can only be attached to a specialization constant or a constant. The current WGSL spec is incorrect in that it says it attaches to an `Input` variable.

The spec needs to be updated so that WorkgroupSize only attaches to a const `vec3<u32>`

**Comment by kvark** [comment]
Perhaps, you mean `vec3<u32>`?

**Comment by dj2** [comment]
Yep, fixed.

**Comment by grorg** [comment]
Discussed at the [2020-05-26 meeting](https://docs.google.com/document/d/1KuWVqle7kNaQgjcPxk_iqBZYCbgP9yIg_Ek7t7D8k3w/).

Resolution is that this will be removed from its current position in the spec and described as part of the entry point annotation.

**Comment by kvark** [comment]
Can we resurrect this? The bultin is useful, it's a part of GLSL, SPIR-V, and others.
From the technical perspective the fact that SPIR-V requires it to be a constant changes nothing for us. It can still look like all the other builtins in WGSL:
```
[[builtin(WorkgroupSize)]]
var<in> workgroup_size;
```
The SPIR-V backend (and frontend) would just need to take care of this with regards to their requirements.

**Comment by dj2** [comment]
Yes, the plan is to add it back, just in a different part of the spec. We'd discussed putting it in as part of the entry points annotations but nothing has been written as of yet.

**Comment by kvark** [comment]
Why does it need to be in a different part of the spec? My point is - from the user (who writes shaders) point of view it could be as regular a built-in as everything else.
