### ISSUE TITLE
Support for implicit conversions

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#751]
Let's figure out if we need implicit conversions at all in WGSL.
Cases (potentially to be expanded):
- `bool`: #733

Investigation:
- SPIR-V has no implicit conversione
- HLSL has [implicit conversions](https://docs.microsoft.com/en-us/windows/win32/direct3d9/casting-and-conversion) between bools, integers, and floats
- GLSL on desktop has implicit conversion (signed to unsugned, integers to floats, scalars to vectors)
- GLSL ES doesn't have implicit conversions
- C/C++ has implicit conversions between numeric types, and with bools (may need clarification wrt compiler warnings, C vs C++ difference, etc)
- Rust doesn't have implicit conversions (instead, there is an explicit `X as Y` construct)

**Comment by kvark** [comment]
Personally, I think having implicit conversions anywhere makes it more difficult to reason about the program based on its source. It also unnecessarily complicates the parsing and language spec. It's a footgun that we have a chance to avoid introducing. Also, forbidding them now is forward-compatible in case we want to change our minds.

**Comment by kainino0x** [comment]
cc #723, which I think would be prevented by implicit conversions (which inherently require outside-in type inference).

**Comment by kvark** [comment]
Sounds like the consensus from [May 5th meeting](https://docs.google.com/document/d/1K2H59am7yLj_DBv0lfuz7g52NNyF4xcQpBs1NNnhk8g/) is to proceed without any implicit conversions, at least for now. This can be closed.
