### ISSUE TITLE
Scalar -> Bool casts

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#753]
In https://github.com/gpuweb/gpuweb/issues/733 we resolved that there would be no implicit boolean casts. That means that we will need explicit boolean casts. We should make sure that there are casts from every scalar type to bool, and their behavior is `!= 0`.

**Comment by grorg** [comment]
Does this need discussion? Or is it simply a todo? (i.e. should it be in the Resolved project column?)

**Comment by litherum** [comment]
I think it's resolved, but maybe we can add it to an agenda just to make sure I'm not putting the cart before the horse.

**Comment by dj2** [comment]
Ah, so this is asking for:

```
bool(f32)
bool(i32)
bool(u32)
bool(vec*<*>)
```

**Comment by jdashg** [comment]
`vecN<bool>(vecN<*>)`?

`bool(vec*<*>)` should be `any` and `all` explicitly.

**Comment by dneto0** [comment]
The original request was for scalar type.

I don't know that the vector form is very useful.
If you really want it, you can take advantage of the fact that nil-constructor gives you the predefined zero element. That is, you can write:   `v != vecN<T>()` when v is of type `vecN<T>`.

**Comment by litherum** [comment]
I don't think we should have `bool(vec*<*>)`. Instead, `vecN<bool>(vecN<*>)` makes more sense.
