### ISSUE TITLE
Add "depth32float_stencil8" extension for GPUTextureFormat

### ISSUE THREAD

**Issue by rconde01** [gpuweb/gpuweb#755]
Currently the following depth-stencil formats are available:
- `depth32float`
- `depth24plus`
- `depth24plus-stencil8`

However, `depth32float-stencil8` is desired since some techniques require `depth32float` depth and you may want to use those techniques together with a stencil buffer. `depth24plus-stencil8` **_may_** provide this but is undesirable for a couple of reasons:
- a `depth32float` result would only be detectable through a readback test
- the current spec does not say implementations should prefer `depth24` or `depth32float` if both options are available. Therefore the result is implementation defined. It may be desired to specify a preference when both options are available.

My understanding is that this option is not available in core because not all targets require this format. Therefore it seems appropriate to add it as an extension.

1. `depth32float-stencil8` would be added to the GPUExtensionName enum. 
2. `depth32float-stencil8` would be added to the GPUTextureFormat enum and documented to only be valid when the `depth32float-stencil8` extension is available.

In terms of backend support you have:
[Metal](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf)
- Depth32Float_Stencil8 for MSAA on all targets

[D3D12](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/hardware-support-for-direct3d-12-1-formats)
- DXGI_FORMAT_D32_FLOAT_S8X24_UINT support is required

[Vulkan](https://www.khronos.org/registry/vulkan/specs/1.2/html/chap32.html)
- Table 50: "VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT feature ... must be supported for at least one of VK_FORMAT_D24_UNORM_S8_UINT and VK_FORMAT_D32_SFLOAT_S8_UINT"

**Comment by kainino0x** [comment]
Thanks for the investigation!

**Comment by kainino0x** [comment]
Items for discussion today:

- Should we go ahead and add this extension to the spec?

- > the current spec does not say implementations should prefer `depth24` or `depth32float` if both options are available. Therefore the result is implementation defined. It may be desired to specify a preference when both options are available.

**Comment by kvark** [comment]
It would be great to gather some data on how widespread is Vulkan support for this format, given that we are *this* close to just having it in the core spec.

**Comment by mrshannon** [comment]
According to [vulkan.gpuinfo.org](https://vulkan.gpuinfo.org) `D32_SFLOAT_S8_UINT` is supported on 99.81% of GPU's under Linux (with the only exception being an obscure ARM chip).  Though on Android the support is limited to a few high end chips.

**Comment by grorg** [comment]
Discussed at the [2020-08-24 meeting](https://docs.google.com/document/d/1xKHeGs7d8KOjNPQuRIGYptXacITV9iVNhUTMoOGkTqM/edit#).

**Comment by kainino0x** [comment]
I'm pretty sure we've considered making it core before. Seems the data shows we can't :(

**Comment by Kangz** [comment]
Closing as fixed. The extensions have been added to the spec.
