### ISSUE TITLE
Section 3.30 is titled "Expression statement", but actually defines assignment statements

### ISSUE THREAD

**Issue by othermaciej** [gpuweb/gpuweb#758]
The section at this link is titled "Expression statement":
https://gpuweb.github.io/gpuweb/wgsl.html#expression-statement

But WGSL doesn't support arbitrary expression statements, or assignment as an expression. There's no prose, but the grammar here defines assignment statements, not expression statements.

(In addition to the name issue, it would probably be better to define the expression grammar separately from assignment statements, since it is used in other statement types as well.)

**Comment by kdashg** [comment]
This is currently https://gpuweb.github.io/gpuweb/wgsl/#assignment
