### ISSUE TITLE
Consistent definitions of the methods

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#760]
Apparently we use different definitions for the methods:
  - names with empty braces, e.g. `{{GPUCommandEncoder/copyBufferToTexture()}}`
  - names with all the parameters, e.g. `{{GPUComputePassEncoder/dispatch(x, y, z)}}`

I haven't found any `{{Something/method}}` cases (without braces).
We should try to make it consistent, i.e. use the `{{Something/method()}}` form everywhere.

**Comment by kainino0x** [comment]
From editors meeting: We should follow the guidelines set by https://tabatkins.github.io/bikeshed/#idl-elsewhere, but we generally don't need "alternate linking texts for omittable arguments" since we rarely would do so.

**Comment by kvark** [comment]
Next action item would be to review the existing method references and fix some.
