### ISSUE TITLE
AGG (Anti-Grain Geometry) for scaling pixel perfect UI

### ISSUE THREAD

**Issue by abitrolly** [gpuweb/gpuweb#765]
For an intro into AGG see http://agg.sourceforge.net/antigrain.com/doc/introduction/introduction.agdoc.html

I have a practical question not being directly addressed by Web or 3D. Back in 1995 we could write pixels directly to video memory for crazy fast speeds in 2D games. Nowadays 2D games run horrendously slow without GPU accelerators, because game engines are ubiquitously backed by GPU and you need some GPU emulator for 2D graphics. I see 2D graphics domain is kind of broken with all the 3D hype.

However, the Web is 2D. Making WebGPU interface without architectural 2D support, or leaving them to third party libs means that no hardware vendor will be interested to benchmark and optimize these graphics pipelines. While there are many high level libs like `cairo` that deal with vector graphics, what I feel is missing is first level support for anti-grain scaling of pixel graphics for different devices and screen resolutions. The back of **most energy efficient** interface that writes pixels directly into video memory. 

The idea may sound crazy. The web was designed with layout engines for adaptable interafaces that tried to move people away from using pixels with all kinds of relative units. I am not sure if that approach had won, and that's why I'd like to see that alternatives are covered. There is canvas and SVG for relative and vector graphics, but pixel based perfectionism requires  browser hacks [to make dots crispy](https://developer.mozilla.org/en-US/docs/Games/Techniques/Crisp_pixel_art_look) and is again questionable about the performance. What is the impact for upscaling 60 FPS 640x480=307200 pixel objects to 1024x600 resolution? Could 2D pixel libraries be effective if the API for operating on pixels in video memory directly on the GPU is not there?

If Vulcan appeared, because OpenGL could not provide the solution to 25 years old graphics problem that requires direct memory access, then maybe WebGPU could use that story to put the Vulcan to the test, and open a frontier for different paradigm than just some rectangle in `<canvas>`. At least maybe make that rectangle also pixel accelerated so that Processing sketches and simple sprite games that 12-years old create with handcrafted pixel sprites looked awesome without hardcore layout and 3D graphics fu.

**UPDATE**: And the question is - would there be an API for scaling fixed resolution pixel interfaces and working with sprite data directly in video memory? :D

**Comment by Kangz** [comment]
I'm not sure I understand the point, or the question.

WebGPU is, as the name implies, an API to access the GPU from the Web so you cannot write pixels directly with `ArrayBuffer` accesses with it. For that you can either upload data to the GPU and render it, or use some other `<canvas>` API.

If the question is whether you'll be able to get a nice pixelated look with WebGPU, the answer is yes, for example using `GPUSamplers` with [`GPUFilterMode.nearest`](https://gpuweb.github.io/gpuweb//#dom-gpufiltermode-nearest). That's possible in WebGL today and libraries like PixiJS or Phaser make that easy to do.

**Comment by abitrolly** [comment]
> For that you can either upload data to the GPU and render it, or use some other <canvas> API.

I do not know any API that provides simple access to performance and energy efficient for building pixel based UIs. And my concern that concept the provided by WebGPU are too tied to 3D abstractions that frontend designers can hardly understand and use them.

At the same time, development of GPU functions is driven by the need of people who already using them for gaming, mining or distributed computing. Without accessible 2D GPU API people don't use 2D interfaces, and without 2D interfaces no job being done to explore alternative ways of dealing with 2D graphice.

> If the question is whether you'll be able to get a nice pixelated look with WebGPU, the answer is yes, for example using GPUSamplers with GPUFilterMode.nearest. That's possible in WebGL today and libraries like PixiJS or Phaser make that easy to do.

I don't believe that JS over GPU can give a good performance. PixiJS users report that they had to buy tools to pack sprites to draw in efficient manner -  https://rymdkraftverk.itch.io/tails/devlog/83229/pixijs-performance - and that is where it feels just wrong for someone who could just bit blit things 25 years ago at top CPU to memory throughput.

Just another recent thread about 2D performance. Again, with 2D helper library, which discusses sprites with vertices and batches https://www.reddit.com/r/gamedev/comments/7o5qgh/2d_acceleration_in_allegro/ Vertices for pixels? Why?

Android is not using pixel sprites, but using 2D acceleration will consume more RAM https://developer.android.com/guide/topics/graphics/hardware-accel - this is also plain wrong, because the data is already in RAM, but GPU requires it to be converted to vertices or something.

And my point is that with right R&D and abstraction WebGPU could interest hardware manufactures to takes a look at the performance and energy efficiency of 2D API for pixel based graphics.

**Comment by kainino0x** [comment]
I don't totally understand the question either, but is this about non-GPU access? If you're talking about CPU access to raw canvas buffers, this is actually something that a random person asked me about at a WASM meetup in SF a few years ago. I think it's very tractable. However if it's not GPU related, then this is the wrong place to discuss. Try: https://github.com/whatwg/html (and cc me!)

**Comment by magcius** [comment]
> I don't believe that JS over GPU can give a good performance. PixiJS users report that they had to buy tools to pack sprites to draw in efficient manner - <https://rymdkraftverk.itch.io/tails/devlog/83229/pixijs-performance> - and that is where it feels just wrong for someone who could just bit blit things 25 years ago at top CPU to memory throughput without paying anybody for the syscall.

There's a lot of things to unpack in here (it's mostly a rant on the state on 2D graphics, which is a *hard* problem!), but I want to touch on this.

"I could blit 8-bit-per-pixel paletted colors to a 640x480 framebuffer in 1985" is not an argument for "JS being slow", it's a side effect of our fidelity requirements improving. We're not doing this any more, we're alpha blending large, 32bpp sprites to giant 1920x1080 framebuffers, at 60fps. If you can use a CPU to do that, even writing raw assembly, I would be very impressed. 2D graphics APIs like AGG, cairo, Skia are continually running into the edge of scene complexity and memory bandwidth, and are adopting the GPU for *performance*.

> Vertices for pixels? Why?

Because GPUs rasterize triangles. It's what they do. If you want a modern, hardware-accelerated 2D graphics API, HTML5 canvas is a great fit. If you are unwilling to accept one of the core principles of how GPUs work, then I don't think we can help you in here. WebGPU is designed to be a modern GPU API, not a 2D graphics API.

@kainino0x "Anti-Grain Geometry" just refers to a 2D graphics rendering library in the likes of cairo/Skia.

**Comment by almarklein** [comment]
I'm not entirely sure if this is what @abitrolly is looking for, but I thought I'd mention that you can get agg-quality 2D rendering on the GPU with the appropriate shaders. Have a look at the work of Nicolas Rougier, e.g. http://jcgt.org/published/0002/02/08/

**Comment by kainino0x** [comment]
To take any action on this we'll need more specific feature requests or questions about WebGPU specifically. Please open new issues if there are any.

**Comment by abitrolly** [comment]
Sorry for the late reply. I want to make sure WebGPU is not following an status quo GPU definitions from Nvidia, who may be not interested in making fast 2D blit operations for their pipelines, although they define standards for hardware accelerated video output. I want WebGPU to cover different approaches to graphic operations that can be accelerated on the web with hardware processing units, where blitting 2D objects and managing layouts with anti-grain geometry and antialiased fonts are first class operations.

Graphics Processing Units should not be limited to the primitive 3D abstraction of triangle rasterization. The approach that doesn't scale in comparison to surface based math. But nobody considers such geometry, because people are fixed on getting more triangles rasterized 60 times per second. If WebGPU is going to settle that in stone, we won't see any improvements in hardware accelerated interfaces for humans.

If everything that GPU does is just loading the sprites into its owned memory and call them textures, then it was already available 30 years ago as framebuffers. But now the same framebuffers just became insanely expensive both in development costs. I would at least consider making different lists of functionality for different stories starting with framebuffer copy that @magcius mentioned. The stories that need the acceleration, but resort to the low level hacks that need to be applied to make GPU at least somewhat help.

While GPU and TPU may have progressed significantly, the interfaces for those 30 years old stories continue to degrade. The complexity to put 2D sprite on screen with SDL2 is multitude higher thanks to new GPU acceleration support. And I see the story repeat over and over. People are packing pixels to fit into CPU image cache for faster processing, rewriting video codecs in Rust, try to unify memory layouts for making video and audio streams accessible as a bus for many applications that require it (pipewire, numpy, ...) and on the acceleration side instead of hardware blitters and memoryview for framebuffer updates, all we've got are rasterized triangles in 3D vector space and shader languages so complicated that they need 7 years of technical education to learn.

**Comment by Kangz** [comment]
+1 as to what @kainino0x said.

I'm not able to extract information from this thread, apart from maybe the request for 2D blitting operations(?) We'd be happy to discuss it more if there was a concrete proposal of API and an investigation of how to implement on different platforms. Right now this thread if non-actionable.

**Comment by abitrolly** [comment]
2D blitting API with pixel processing operations would be nice for a start. And for that it would be nice to see what browsers are actually doing for web site layout and rendering. Chrome and Firefox only recently were able to somehow map these operations to GPUs, but having a reference to understand what browsers are processing and how GPUs helps with that, would be a good outcome I'd expect from the working group

**Comment by magcius** [comment]
2D blitting APIs are not exposed on modern GPUs through cross-platform, portable APIs. Would it be nice to have a 2D blitter exposed through the native APIs? Maybe! Though it might be less helpful than you imagine. Intel has had a basic 2D blitter for a long time now [0], though it doesn't support "pixel processing operations" (it supports classic GDI's BitBlt bitwise ops, but even alpha blending is not supported [1]). But currently, this is not exposed to the user by any API, and there is no safe, portable way for WebGPU to support it.

Ultimately, triangles are the dominant processing model of GPUs, and I think the hardware you think of as being there like 2D blitting is non-existent, or is actually driven by triangles behind the scenes. WebGPU is focused on being a fast, *native* API, not being a rendering engine. That means it speaks the lingua franca of the native APIs.

[0] https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-icllp-vol10-copyengine_0.pdf
[1] Page 4 of the PDF linked above: "Functions such as Alpha BLTs, arithmetic(bilinear)stretch BLTs, rotations, transposing pixel maps, color space conversion, and DIBs are all considered 3D BLTs and are covered in the 3D rendering section".

**Comment by abitrolly** [comment]
@magcius doesn't video acceleration use the 2D blitting techniques? First storing compressed stream to memory, then decompressing memory into "videomemory" with those huge 32bpp 1920x1200 frames 60 times a second. How does it work?

> But currently, this is not exposed to the user by any API, and there is no safe, portable way for WebGPU to support it.

That's exactly the point I am trying to raise. Rather than fixing on what is already available, WebGPU could try to define that API for the future (web) so hardware producers could follow. If these API can simplify layout, rendering, save energy, lead to more efficiency on low powered devices, then it will be picked up by China producers for sure.

**Comment by Kangz** [comment]
WebGPU is not in the business of defining new hardware features. It's even explicitly called out in the charter.

**Comment by abitrolly** [comment]
> Chrome and Firefox only recently were able to somehow map these operations to GPUs,

I was wrong. There is no production ready Firefox GPU acceleration for Linux rendering. https://wiki.mozilla.org/Platform/GFX/WebRender_Where And https://hacks.mozilla.org/2020/04/experimental-webgpu-in-firefox/

> WebGPU is not in the business of defining new hardware features. It's even explicitly called out in the charter.

Somebody needs to get out **features that need to be hardware accelerated for browsers** to be more secure, memory and energy efficient and fast. **If not WebGPU, then who needs to define it?** I though that it aimed to have the same effect for the web as TPU had for AI/machine learning. But right now it looks like just another 3D API wrapper library.

Ignoring the necessity to get deeper inside hardware acceleration for the web rendering tasks, limits the browser market to just a few vendors who can get lower layer of dealing with GPU bugs right. Those blacklists and whitelists, untraceable bugs with Nvidia drivers. It is the reality that needs to be changed. If WebGPU could define the hardware features, and cover them with [tests](http://acid3.acidtests.org/) that people could easily follow before buying their software. WebGPU initiative could also bring more attention to [existing compliance testing](https://github.com/Igalia/piglit) and add their own, to make it easier for hardware engineeers to ensure that their products will not be added to blacklists.

As of now, I don't see that WebGPU could lead to something more revolutionary than just isolated 2D boxes with 3D content. Something that looks very cool on https://hacks.mozilla.org/2020/04/experimental-webgpu-in-firefox/ but requires too much time and not really immersive.  Maybe it will make easier to onboard gamers by providing completely browser isolated platform, but I hoped there was a wider vision. )

**Comment by abitrolly** [comment]
Sorry for flooding the issue. It is already closed, but I decided to keep it in one thread just in case somebody will have the same rants. :D

When I first encountered GPUs, and it was OpenGL if I am not mistaken, I was shocked by two things.

1. No API to get GPU memory usage, which means no way to predict when GPU will start using system RAM, or even copying objects from system RAM instead of using it directly, and doing it basically for every frame. And if I have two applications that require GPU, the GPU swaps out and pull in those graphics objects on every context switch? Run a game in Steam, another one in Chrome and you'll get both slow. Perhaps BOINC calculation or Folding@HOME also creates a problem for those accelerators.Is that NVIDIA or MS, who didn't provide memory control/optimization API in the first place? Without knowing what's going on, you just buy faster card with larger memory. Been there, did that. And yet my PC is still slow for GPU accelerated 2D browser games, because GPU is not designed to work with browsers.

2. Moving things to GPU 60 times a second. Rerendering everything, copying everything on every frame. Because GPU does all the job, let them eat the electricity like crazy. Maybe I am mistaken - I am not a graphics expert. This is what I understood from different intros into 3D programming.

Given those two things, what could be helpful is **reactive memory implemented in hardware**, where blits only occur when content of mapped memory changes, maybe even coping only what was changed. This could at least save a lot of energy. With DMA (direct memory access) there is no need to pipe those regions through the CPU. There are many [reactive things](https://observablehq.com/) in the browser including React itself, which could potentialy offload the render tree recalculation from CPU (and signalling about changed resources). Then those apps will not hog battery resources on mobile devices, that need to sleep. Green deal they say. ) And if we set that a browser page is just a region of video memory, which is updated and 2D blitted from different pieces of memory somewhere else, then after making reacive memory in hardware, the things like scrolling, inserting and removing could follow.

Now the question is - why this blit tree of 2D fonts and square 2D regions that needs to be just glued on top of each other to form  (2D) web page - why this blit build tree needs to be converted into vertex, shaders and textures with PhD level language to glue them? Yes, Google hire a group of those postdoc fellows to properly do these hacks for fun and profit, and I am not sure others could follow. Even MS couldn't.

**Comment by Kangz** [comment]
Locking this issue. We've stated multiple times that WebGPU cannot influence hardware algorithms and native API design, and requested concrete proposals multiple times, but only received more motivation for influencing hardware / native APIs.
