### ISSUE TITLE
IndexFormat part of pipeline? 

### ISSUE THREAD

**Issue by amerkoleci** [gpuweb/gpuweb#767]
Why index format is part of pipeline instead of setIndexBuffer call?

All API use index format during set index call:
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-iasetindexbuffer
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdBindIndexBuffer.html
https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1515520-drawindexedprimitives

**Comment by magcius** [comment]
DX12 requires that for tristrips, the primitive restart index is passed as the PSO creation step.

https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_index_buffer_strip_cut_value

Metal does not allow you to disable primitive restart.

The combination of these two means that we must choose a primitive restart value up-front.

However, I think it might make sense to allow passing "none" and defer to SetIndexBuffer time if the PSO is created non-strip topology.

**Comment by kainino0x** [comment]
> However, I think it might make sense to allow passing "none" and defer to SetIndexBuffer time if the PSO is created non-strip topology.

Hm. I was certain when we were adding this that we decided this would only be needed for non-strip topologies (and would be ignored - even though it defaults to "uint32" - otherwise). But since there's no other place to pass in the index format, I guess we didn't do it (or forgot about it).

**Comment by Kangz** [comment]
> However, I think it might make sense to allow passing "none" and defer to SetIndexBuffer time if the PSO is created non-strip topology.

It's a cool idea, I'm just worried we'll be asking people to supply information they already passed at pipeline creation time. Maybe there a way to make it nice though.

**Comment by magcius** [comment]
> It's a cool idea, I'm just worried we'll be asking people to supply information they already passed at pipeline creation time.

How so?

**Comment by kainino0x** [comment]
If indexFormat becomes optional in the pipeline, then we have to add a way to specify the index format at drawIndexed time. But then do we always require the index format at drawIndexed time, or only if it wasn't specified in the pipeline?

**Comment by magcius** [comment]
Depends on who you ask :) 

In personal experience, hardware tristrips are relatively rare, so I don't suspect this being a major issue in practice. Having format specified as part of both might be awkward in that case (I think it has to validate at drawIndexed since I think you can call setIndexBuffer and then setGraphicsPipeline?), but I think it would be relatively rare.

**Comment by tklajnscek** [comment]
Our cross-platform engine would also benefit from WebGPU matching the other APIs' handling of index type.
I think @magcius sums it up nicely:
1.  Allow `WGPUVertexStateDescriptor::indexFormat` to be set to `Unknown` which explicitly disables primitive restart on DX12 and automatically picks the restart index on the platforms that can't disable it

Add a `format` argument to setIndexBuffer
- Validate in `drawIndexed` and fail validation if the pipeline has indexFormat set and it doesn't match the format passed into setIndexBuffer as allowing these to diverge would cause a difference in behavior between the APIs (e.g. pipeline is set to Uint16, but 32-bit indices are used so Metal would restart at 0xffffffff but DX12 would restart at 0xffff). 

-

**Comment by tklajnscek** [comment]
Our cross-platform engine would also benefit from WebGPU matching the other APIs' handling of index type.

Since the topology is known at pipeline creation, I think an elegant solution would be:
1. Rename `WGPUVertexStateDescriptor::indexFormat` to something more specific like `indexFormatForPrimitiveRestart` so people don't get confused why/when it needs setting there (this is optional, but kinda nice)
2. Require it be set to `Unknown` if primitiveTopology is not a strip, but also require it be set to a valid format if `primitiveTopology `is a `*Strip`. 
4. Add a format argument to setIndexBuffer like the underlying APIs actually expose
5. Validate in `drawIndexed` and fail validation if the pipeline has `indexFormat` set and it doesn't match the format passed into `setIndexBuffer`. This way you get consistent behavior between the APIs - basically for stripped rendering you force the user to decide the format at pipeline creation so we can guarantee the same restart index value, but for non-strips you let them pick at draw time (and create the dx12 pipeline with primitive restart disabled).

**Comment by kainino0x** [comment]
All makes sense to me!

**Comment by Kangz** [comment]
@tklajnscek's solution is interesting, but it add a lot of complexity for something that should be simple, and only helps for the non-stripped case. My understanding is that strips are incredibly common, so most users of the API would still need to set it at pipeline creation, but in addition would need to pass the same information (and the correct one) a second time in `setIndexBuffer`.

**Comment by magcius** [comment]
In my professional experience, hardware tristrips are pretty rare. Index buffers negate most of the "compression" that strips naturally provide. GPUs don't tend to like tristrips either, they're unnecessarily tied to topology, and cache-optimized stripifiers are pretty difficult to write.

The only GPU I know of that likes tristrips over triangles for index-buffered meshes is Mali pre-Bifrost, and that's more a tiny accident in their vertex processing pipeline than any inherent benefit of tristrips.

Tristrips are fine as a compression / wire format (though I would rather recommend something like meshopt), but should probably be unpacked on the client.

**Comment by tklajnscek** [comment]
Yeah, seconding what @magcius said. In my (+15 years now, god I feel old) experience developing video games, in-house 3d engines and tools we've pretty much never used tristrips. The tiny savings in index buffer size are not worth the added hassle and even potentially slower performance. In addition 3d authoring tools pretty much don't export triangle strips so geometry needs to be strippified manually etc.

There are some potential use cases where you need to draw a massive continuous surfaces, primarily in scientific visualization and your data is already prepared like that, but I'd argue that the vast majority of developers will use indexed triangle lists to draw geometry, defaulting to 16-bit indices, but flipping to 32-bit indices if required. Allowing them to keep the same pipeline for that would definitely be good for performance and code simplicity

**Comment by Kangz** [comment]
Thanks, that's super useful information, and makes sense because strips introduce a serial process vs. indexed triangle lists that do not.

The additional draw-time validation is unfortunate, but it might be worth the usability improvement for most developers. I'd like to have other implementer's opinion, but we could discuss this issue in a WebGPU call sometime soon.

**Comment by kainino0x** [comment]
Resolved: Accept https://github.com/gpuweb/gpuweb/issues/767#issuecomment-649514851
(Editors to figure out the exact API shape)

**Comment by kainino0x** [comment]
Editors proposal:
- Still call it indexFormat (no rename)
- Change setIndexBuffer to take (GPUBuffer, GPUIndexFormat, optional offset, optional size)

**Comment by RafaelCintron** [comment]
Following up on conference call action item: D3D team confirmed you must use D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFF for 16 bit index types and D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFFFFFF for 32bit index types.

**Comment by kainino0x** [comment]
This is kind of dumb, but what if we just collapsed `.primitiveTopology` and `.vertexState.indexFormat` together?

enum GPUPrimitiveTopology {
    "point-list",
    "line-list",
    "line-strip-uint16",
    "line-strip-uint32",
    "triangle-list",
    "triangle-strip-uint16",
    "triangle-strip-uint32"
};

**Comment by kainino0x** [comment]
(Since we are using the indexFormat only for the strip cut value, it's really more a part of the primitive topology than it is part of the vertex state.)

**Comment by tklajnscek** [comment]
> Following up on conference call action item: D3D team confirmed you must use D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFF for 16 bit index types and D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFFFFFF for 32bit index types.

Ha, that's wild, it's not even documented [in the DX12 docs](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_index_buffer_strip_cut_value). It's unlikely that anyone would use 0xffff for 32-bit indices, but the docs never say it won't work. TIL :) 

> This is kind of dumb, but what if we just collapsed `.primitiveTopology` and `.vertexState.indexFormat` together?
> 
> ```
> enum GPUPrimitiveTopology {
>     "point-list",
>     "line-list",
>     "line-strip-uint16",
>     "line-strip-uint32",
>     "triangle-list",
>     "triangle-strip-uint16",
>     "triangle-strip-uint32"
> };
> ```

I actually like this a lot as it strongly ties the index format to the topology and there's no confusion with indexFormat set to Unknown etc.

**Comment by magcius** [comment]
What does the signature for setIndexBuffer look like then? Does it take an optional GPUPrimitiveTopology?

**Comment by tklajnscek** [comment]
> Editors proposal:
> 
> * Still call it indexFormat (no rename)
> * Change setIndexBuffer to take (GPUBuffer, GPUIndexFormat, optional offset, optional size)

I don't think @kainino0x was suggesting removing `GPUIndexFormat` altogether, just not having it as part of   `GPURenderPipelineDescriptor.vertexState`. So `setIndexBuffer` would be just like he wrote above and there would be verification that `GPUIndexFormat` matches what's specified in `GPURenderPipelineDescriptor.primitiveTopology`, if it's a stripped topology.

**Comment by kainino0x** [comment]
Yup, that. :)

**Comment by magcius** [comment]
I like that then. Though I just really wish Metal allowed you to disable prim restart, it would fix this whole mess.

**Comment by kvark** [comment]
@kainino0x I don't think we should embed the index format into topology. We already have one index format type, let's just use it by making it optional. It's consistent with the rest of the spec, and it's easier to specify.

**Comment by kainino0x** [comment]
Maybe for future flexibility we should go the opposite direction and match D3D?
- have separate primitiveTopology and primitiveRestartValue options
- validate primitiveRestartValue can only be unset, 0xFFFF, 0xFFFFFFFF
- validate that IFF primitive topology is non-strip, primitive restart value is unset
- validate later that the primitive restart value is only used with its appropriate index format
which would give us the api surface for both disabled primitive restart, and for other primitive restart values.
(We can get the first one by just making indexFormat not have a default value, though. And the second one seems less likely to ever be useful.)

**Comment by kainino0x** [comment]
For discussion today: decide between the following forms to draw with (line strip, uint16 index, primitive restart value 0xFFFF).

A) `{ primitiveTopology: "line-strip", vertexState: { indexFormat: "uint16" } }` and in drawIndexed it's validated that the current setIndexBuffer's indexFormat matches the pipeline's indexFormat
B) `{ primitiveTopology: "line-strip-uint16" }` and ^
C) `{ primitiveTopology: "line-strip", vertexState: { primitiveRestartValue: 0xFFFF } }` and this pipeline can only be used with setIndexBuffer("uint16")

**Comment by kainino0x** [comment]
Also, separately, perhaps consider whether `indexFormat` really belongs in `vertexState`.

**Comment by grorg** [comment]
Discussed at the [2020-07-13 meeting](https://docs.google.com/document/d/1ZC0aGwUEuvzh8CEdK7B8FOY3eU6UiAHTCLTTkm74kWY/).

**Comment by kvark** [comment]
D) another interesting alternative:
```
{ primitiveTopology: "lines", vertexState: { stripIndexFormat: "uint16" } } // for line-strip
{ primitiveTopology: "lines", vertexState: { stripIndexFormat: null } } // for line-list
```

**Comment by kainino0x** [comment]
In this case I would definitely like to move it out of the vertexState, but I think it's not a bad option. I think we could refine it, maybe:

```webidl
enum GPUPrimitiveType {
  "point",
  "line",
  "triangle"
};
```
```js
{ primitive: "line", stripIndexFormat: "uint16" }
{ primitive: "line", stripIndexFormat: undefined }
```

or

```webidl
enum GPUPrimitiveType {
  "point",
  "line",
  "triangle"
};
enum GPUPrimitiveConnectivity {
  "list",
  "strip-uint16",
  "strip-uint32"
};
```
```js
{ primitiveType: "line", primitiveConnectivity: "list" }
{ primitiveType: "line", primitiveConnectivity: "strip-uint16" }
```

**Comment by magcius** [comment]
what's a point strip?

**Comment by magcius** [comment]
I think we're getting into bikeshed territory here. Honestly, any of them is fine and probably equal pain. Anybody up for a game of darts?

**Comment by kainino0x** [comment]
I think so too, will try to see if we can resolve in the editors meeting

**Comment by kainino0x** [comment]
No resolution yet, but I think we're okay with something like option D.

**Comment by kainino0x** [comment]
Editors resolution: Keep option A, but we should update the validation to say indexFormat must be undefined if the topology is not strip.

Then, we want to do an overhaul of the exact shape of the render pipeline descriptor to cleanly separate all of the stages of the conceptual render pipeline (similar to how D3D and Vulkan make the stages very explicit). As a minor part of this, we want to rename indexFormat to stripIndexFormat.

**Comment by kainino0x** [comment]
Which is now filed as #936.

**Comment by tklajnscek** [comment]
Nice one! Thank you everyone :)
