### ISSUE TITLE
[wgsl] Define the interface of an entry point in a WGSL program

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#774]
For an entry point in a WGSL program: what objects form the data interface with the outside world?

- user data on input/output for vertex and fragment shaders
- builtin variables
- buffer and image resources

Also, how do those objects combine to form an interface.  

This is a needed so we can write interface matching rules between vertex and fragment shaders within a pipeline. (#644) 

We also need it to write the rules for when a shader (buffer and image) resource interface matches a pipeline configuration. 

This is a blocker for meaningful support of vertex and fragment shaders.

**Comment by grorg** [comment]
Discussed at the [2020-06-16 meeting](https://docs.google.com/document/d/11RW9hpfzSvZYpLGBm3uhKwoXDvJI42N7jWP_nOB-k2E/).

@dneto0 will come up with a draft/proposal for next week's F2F meeting.

**Comment by grorg** [comment]
Related to #662

**Comment by grorg** [comment]
Related to #644

**Comment by grorg** [comment]
Discussed at the [2020-06-23 Virtual F2F meeting](https://docs.google.com/document/d/1WI9PzwXy39fFHuZLUnEQtSplwfmFaZ2oVb0gXJsA2P4/)

**Comment by dneto0** [comment]
I have WIP: https://github.com/gpuweb/gpuweb/pull/1133

**Comment by dneto0** [comment]
This is still in WIP, with the sequence of PRs being:
- #1093 - describe storage classes
- #1142 - describe overview of a shader interface, pipeline input output variables, and describe builtin variables 
- TODO:  describe that buffer variables and texture variables are also part of the shader interface, and nothing else.

**Comment by jdashg** [comment]
All linked PRs have landed, though I see there's a TODO there still.
@dneto0 should we file an issue for the TODO specifically and close this?

**Comment by jdashg** [comment]
@dneto0 bump :)

**Comment by dneto0** [comment]
This part of the spec has been written now.
