### ISSUE TITLE
generated spec lacks version info

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#776]
Migrated from https://github.com/gpuweb/WSL/issues/343

> The text at ~https://gpuweb.github.io/WSL/~ https://gpuweb.github.io/gpuweb/wgsl.html lacks version info.
>
> That impedes the process of review. I don't know how far out of date it is with respect to the sources in this repo. So I find myself bouncing between the two to ensure I'm not filing a duplicate issue.

**Comment by kainino0x** [comment]
Bikeshed includes a date, which I think is the date the spec was generated.

> Editor’s Draft, 12 May 2020

**Comment by dj2** [comment]
As Kai mentioned, there is a date on the spec, is that insufficient for this purpose? I don't see anything in the bikeshed documentation on setting version outside of the Level which I think is something else (or maybe this is what level is for?).

Either way, having a number we have to remember to update every time we update the spec is going to be error prone.

**Comment by dneto0** [comment]
Bikeshed can insert garish Warning text, by adding a "Warning" metadata with specified title and body text.  Then you can inject "git rev-parse HEAD" into the warning text with the Makefile update as below.

It's WAY UGLY this way.  Maybe it's better to modify the HTML instead, at the "This version:" tag in the preamble.

diff --git a/wgsl/Makefile b/wgsl/Makefile
index 80e1492..d6450f5 100644
--- a/wgsl/Makefile
+++ b/wgsl/Makefile
@@ -1,7 +1,10 @@
 all: index.html grammar/grammar.js
 
-index.html: index.bs
-	bikeshed --die-on=everything spec index.bs
+index.pre.bs: index.bs Makefile
+	sed -e "s/Generated from git commit HERE/Generated from git commit $(shell git rev-parse HEAD)/" <index.bs >index.pre.bs
+
+index.html: index.pre.bs
+	bikeshed --die-on=everything spec index.pre.bs index.html
 
 grammar/grammar.js: index.bs extract-grammar.py
 	python3 extract-grammar.py index.bs grammar/grammar.js
diff --git a/wgsl/index.bs b/wgsl/index.bs
index 06fa246..683e1ba 100644
--- a/wgsl/index.bs
+++ b/wgsl/index.bs
@@ -7,6 +7,9 @@ Group: webgpu
 ED: https://gpuweb.github.io/gpuweb/wgsl/
 TR: https://www.w3.org/TR/WGSL/
 Repository: gpuweb/gpuweb
+Warning: Custom
+Custom Warning Title: FOOBAR
+Custom Warning Text: Generated from git commit HERE
 Text Macro: INT i32 or u32
 Text Macro: UNSIGNEDINTEGRAL u32 or vec|N|&lt;u32&gt;
 Text Macro: SIGNEDINTEGRAL i32 or vec|N|&lt;i32&gt;
