### ISSUE TITLE
Task: Validation rules for entry points

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#778]
Migrated from https://github.com/gpuweb/WSL/issues/270

We need to write rules to make sure that things like `fn foo(int A, int B) -> void` can't ben an entry point.

**Comment by dj2** [comment]
What are the restrictions we want to put on functions? It seems like for MSL at least we need to gather up all the input variables and turn them into a struct, same without output variables. If we also have a return value, how would that work with output variables?

Should, we restrict entry point functions to be `fn foo() -> void` in all cases? Then the module input/output variables define the interface which we can gather up into the structs as needed?

**Comment by kvark** [comment]
@litherum or we can consider putting the whole interface in the arguments and return values, see https://github.com/gpuweb/gpuweb/issues/889#issuecomment-654370178
