### ISSUE TITLE
Packed vector types

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#780]
Packed types are used to compact buffer data.

This can have a negative impact in the ecosystem since WebGPU data needs to be streamed from the web. This means that assets should be compressed as much as possible. Modern games can’t afford to post-process the GPU data (performance and memory) so typically they ship with the assets packed and compressed and they inflate them directly into GPU resources which are ready to be consumed.

**Comment by Kangz** [comment]
Can you detail what packed vector types are? Is it like `vec<4, i10>` for a vector of 4 times 10 bit integers?

**Comment by kainino0x** [comment]
There are both texture and vertex formats which are packed smaller than what WGSL can represent in its type system. But that's okay: the values get expanded by the hardware on read. Having packed vector types in WGSL only helps with register usage (but the ALUs can't operate on such data AFAIK) and, *IF* they're supported in storage/uniform buffers, then with that.

**Comment by kvark** [comment]
This issue definitely needs more specifics on what formats or functions are missing.

**Comment by dneto0** [comment]
I agree with @kvark here on needing more detail.

I agree with @kainino0x that typical use of element-level packing is that images have particular texel formats that are then expanded on read, and compressed on write.  So you end up operating on regular data types in the shader.
(Vulkan also has the ability to read/write buffer objects as if they have specific image-texel-formats.)

Block-compressed formats are another thing entirely, and are handled entirely on the API side, i.e. it's not a shader concern.

**Comment by kainino0x** [comment]
I don't think this can be "For Next Meeting" because there still hasn't been a clarification of what this issue is actually about.

**Comment by dneto0** [comment]
This issue still lacks info.  Has it been addressed by the pack/unpack builtins added in response to #988?

**Comment by jdashg** [comment]
@litherum Does this need more work?

**Comment by jdashg** [comment]
I believe this need is addressed by #988 but please reopen if not!
