### ISSUE TITLE
Can GPUExtent3D have fewer than 3 entries?

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#781]
```WebIDL
dictionary GPUExtent3DDict {
    required GPUIntegerCoordinate width;
    required GPUIntegerCoordinate height;
    required GPUIntegerCoordinate depth;
};
typedef (sequence<GPUIntegerCoordinate> or GPUExtent3DDict) GPUExtent3D;
```
> An Extent3D is a GPUExtent3D. Extent3D is a spec namespace for the following definitions:
>
> For a given GPUExtent3D value extent, depending on its type, the syntax:
> - extent.width refers to either GPUExtent3DDict.width or the first item of the sequence.
> - extent.height refers to either GPUExtent3DDict.height or the second item of the sequence.
> - extent.depth refers to either GPUExtent3DDict.depth or the third item of the sequence.

The spec doesn't seem to say if `GPUExtent3D` can have fewer than 3 items if its using the `sequence<GPUIntegerCoordinate>` form.

**Comment by litherum** [comment]
Seems reasonable to automatically fill in any missing entries to be 1. If someone's trying to make a 1d texture, having to set 1 to the second and third dimension seems unnecessary.

I suppose a corollary to this would be that the `height` and `depth` fields in `GPUExtent3DDict` no longer become `required`.

**Comment by kvark** [comment]
Yes, we are currently filling any missing entries to 1 in Gecko.

**Comment by kainino0x** [comment]
The unwritten intent was to have these have exactly the same requirements as the dictionary versions, i.e. GPUExtent3D requires the sequence to be of length (exactly) 3; GPUOrigin3D can be length 0, 1, 2, or 3; etc.

I think there are some places where we use these typedefs where the defaults should be different (maybe even based on the dimensionality of the texture in question). But maybe being that precise is not necessary.

**Comment by kainino0x** [comment]
For example: The reason `GPUOrigin3DDict` is all-optional is because `[0,0,0]` is convenient in the only place where it's used: `GPUTextureCopyView`. But otherwise I'm not sure it makes sense to have it all-optional.

Also, all that said, I'm going to use this to argue again for getting rid of the dictionary overrides and using sequences only. With sequences, it's very practical to always require all 3 entries: typing an extra `, 0` or `, 1` is extremely unintrusive to the author.

**Comment by Kangz** [comment]
Closing, this have been encoded in the spec [here](https://gpuweb.github.io/gpuweb/#typedefdef-gpuextent3d).
