### ISSUE TITLE
Issues about copy commands within same resource

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#783]
Hi WebGPU CG,

We have found more issues about the copy commands within same buffer and texture when implementing the related validation rules inside Project Dawn.

1. D3D12 debug layer will report the following error when the source and destination are the same buffer in [```CopyBufferRegion```](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-copybufferregion) command although we cannot find such statements in D3D12 document.

> D3D12 ERROR: ID3D12CommandList::CopyBufferRegion: Source and Destination resource cannot be the same when doing a CopyBufferRegion.Copying within the same buffer should be done using an intermediate buffer [ RESOURCE_MANIPULATION ERROR #998: COPY_ON_SAME_SUBRESOURCE]

2. On D3D12 and Metal we can only copy one subresource per copy commands.
- D3D12 function [CopyTextureRegion(](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-copytextureregion)) can only support copying between two subresources, not a range of subresources. In its parameter ```pSrcBox```, the "```front```" and "```back```" refer to the z-position of the box, which is only valid when the texture is a 3D texture. When we copy with a 2D texture and make ```back``` > 1, D3D12 debug layer will report the error message like the following does:
> D3D12 ERROR: ID3D12CommandList::CopyTextureRegion: The destination region extends past, at least, one of the edges of the destination subresource. When the destination format is R8G8B8A8_TYPELESS, the source format is R8G8B8A8_TYPELESS, DstX is 0, DstY is 0, DstZ is 0 and the effective SrcBox width is 16, height is 16, and depth is 2, the operation requires the destination subresource to have 16 width, 16 height, and 2 depth. But the destination subresource only has 16 width, 16 height, and 1 depth. [ RESOURCE_MANIPULATION ERROR #858: COPYTEXTUREREGION_DSTREGIONOUTOFBOUNDS]
- Metal only supports copying into one layer of a 2d texture. According to the [related Metal document](https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400752-copyfrombuffer?language=objc), "when you copy to a 2D texture, depth must be 1."

So I have two questions here:
1. Shall we forbid copy within same buffer in WebGPU as D3D12 does not allow it?
2. Shall we only allow copying with one texture subresource in one copy command as D3D12 and Metal do?

**Comment by kainino0x** [comment]
> 1\. Shall we forbid copy within same buffer in WebGPU as D3D12 does not allow it?

If there is indeed no way around it, I think we have no choice. Doing an extra staging copy would be too magic and complex IMO.

> 2\. Shall we only allow copying with one texture subresource in one copy command as D3D12 and Metal do?

If this restriction isn't universal (i.e. if Vulkan allows it), I think we should allow copying of multiple texture subresources, and emulate it on D3D12/Metal as it should be relatively simple to do.

**Comment by kvark** [comment]
Thank you for raising this, @Jiawei-Shao ! I agree with @kainino0x on the way forward.
Also, do we know for sure if texture-texture copies can be for different regions of the same subresource ?

**Comment by Kangz** [comment]
They can't in D3D12.

I'm very surprised by these limitations given Metal and Vulkan don't seem to have them. So maybe we could do the copy through the extra step and ask if the D3D12 rules can be made more flexible? Or forbid it for now, and put it in the list of "inflexible things to look at maybe relaxing after MVP"

**Comment by kvark** [comment]
Thanks for confirming, @Kangz ! It sounds like we should disallow that now, and can flip that switch later if D3D12 has a feasible workaround.

**Comment by kainino0x** [comment]
Resolved: Disallow copies within one buffer. Allow multi-layer texture copies.
