### ISSUE TITLE
Figure out places where we should use USVString

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#784]
Something recently reminded me about the existence of `USVString`. According to WebIDL:

> Specifications should only use `USVString` for APIs that perform text processing and need a string of Unicode scalar values to operate on. Most APIs that use strings should instead be using `DOMString`, which does not make any interpretations of the code units in the string. When in doubt, use `DOMString`.

I think this means we should probably use USVString for `GPUShaderModuleDescriptor.code`, and probably `GPUProgrammableStageDescriptor.entryPoint`. I'm not 100% sure whether we should use it in other places.

I did some quick reading, and my understanding is that `DOMString`s which are not valid `USVString`s (i.e. they have invalid surrogate pairs) cannot be converted to UTF-8. Most or all of our other `DOMString` inputs (labels and debug names) are fed into the GPU driver as UTF-8 at some point. So I think we cannot actually accept `DOMString` for those.

**Comment by JusSn** [comment]
Thoughts: a WGSL compiler technically lives entirely in the browser and has to process/transform the entire `code` input (into UTF-8 data) anyway, so a UTF-16 string here would never actually make it to the GPU layer. It's a question of whether our compilers should accept UTF-16 or UTF-8. Is there a big impl difference here?

Other areas (debug labels, etc) probably don't require any crazy transformation and may be passed to the GPU driver as-is, so these should be UTF-8 (USVString).

**Comment by kainino0x** [comment]
From our discussion:

- it's important for label and debug names to be USVString (or even ASCII??) if we pass them directly to the GPU driver, and we should pass them directly (with some sanitization and string length limits). We may have more rules here than USVString, so both DOMString and USVString with extra sanitization would be valid, but USVString is closer to what we actually want.
- WGSL could conceivably handle input with invalid surrogate pairs (i.e. utf-16 strings that can't be represented as utf-8), but it would have to error on them. However, it could do so asynchronously instead of synchronously like USVString. So accepting USVString probably has some unnecessary call-site overhead for createShaderModule.

**Comment by kainino0x** [comment]
See also: https://github.com/w3ctag/design-principles/issues/93

**Comment by annevk** [comment]
@kainino0x if you have a use case for ASCII, could you file an issue at https://github.com/heycam/webidl/issues/new? Note that you can get "Latin-1" by using ByteString, which might be sufficient. And then you could have a prose check to throw for > 0x7F.

**Comment by kainino0x** [comment]
The only reason to restrict it to ASCII is to reduce the attack surface against GPU drivers. It would probably be a good thing for implementations to do in general, since we have no way of knowing how robust the driver is. We'll also have to prevent overly-long strings which I assume we can't express in WebIDL. I'd propose these options:

(a) Sanitize incoming strings before the driver, and truncate to a reasonable length. Allows implementations to decide exactly how much sanitization to do (ASCII? printable BMP codepoints? etc)
(b) Disallow non-ASCII and long strings in the spec (either by sanitizing and returning the sanitized version in the attribute, or by throwing errors on invalid input), and test this. We can do this easily enough without IDL support though.

Option (a) seems slightly better to me, but at the risk of some implementations forgetting to perform the sanitization/truncation.

**Comment by annevk** [comment]
b) seems a lot better to me as it wouldn't vary across implementations. And yeah, no need for IDL support unless you want to mint a special type for it which would eventually (when Wasm gets IDL support) allow for some optimizations.

**Comment by kainino0x** [comment]
Variations across implementations are not very important for these fields, as the sanitization should only ever affect platform-native debugging tools which are not page-visible or end-user-visible. The strings wouldn't need to be sanitized for the other two places they might go (IIRC): dev tools, and error strings.

**Comment by annevk** [comment]
I see. If eventually you'd add something like https://w3c.github.io/reporting/ for remote debugging it seems that might become relevant though.

**Comment by kainino0x** [comment]
If the debug labels/markers/groups appear through that API, they could also remain unsanitized (like I proposed for dev tools and error strings). In fact, I think the constraints there are ~ the same as error strings: when we provide an error message (via GPUValidationError.message), we would use the debug label string in that error message. These are approximately the same error strings that would go to the Reporting API.

**Comment by annevk** [comment]
The thing I'm worried about is that browsers have to end up copying each other anyway as tooling starts to expect to see certain things.

**Comment by kainino0x** [comment]
Sorry, this conversation is probably confusing because both my understanding/proposal has been evolving and I haven't ever explained what I'm actually proposing. Let me try to write it all out.

- Shader strings should be USVString so that shader compilers may ingest UTF-8 instead of having to ingest UTF-16: `GPUShaderModuleDescriptor.code` and  `GPUProgrammableStageDescriptor.entryPoint`. These strings will not be passed into platform drivers or shader compilers, as we will process this text ourselves before passing it to the driver. That processing will probably remove or replace identifiers entirely (with hashes, like WebGL does, e.g. `webgl_5746d1f3d2c2394`).

- Debug names (`GPUObjectBase.label`/`GPUObjectDescriptorBase.label`, `pushDebugGroup`, and `insertDebugMarker` should be handled as follows.
    - String is expected to be preserved for all usages within the browser: reading `.label`, `GPUValidationError.message`, JS console, other Dev Tools, reporting API, etc.
    - Implementations may or may not choose to pass any strings into the driver for the debug name strings in native APIs. If they do, they may decide whether to preserve, sanitize, hash, or use completely new names for the values passed into the driver. The driver uses these for two things:
        - Error messages from the driver (or its debug layers, if enabled). Generally we expect that browser implementations will avoid ever triggering such error messages. If they are triggered, they could be shown to the user in the dev tools console, but would probably never be accessible by the webpage itself as they indicate a browser (or driver) bug.
        - Human-readable strings in interactive platform debug tools (Xcode, Microsoft PIX, RenderDoc, GAPID, Visual Studio, Android Studio, Nsight, etc.) when running them against the browser application itself. No tooling or user should ever expect/require that the strings are preserved exactly (though for i18n may want more than ASCII). Only developers would ever need this, though, so it could definitely be an end-user-enableable option (dev tools checkbox or even browser command line flag) and any sanitization would probably be unnecessary. (Tangentially related to #814.)

**Comment by hsivonen** [comment]
> it's important for label and debug names to be USVString (or even ASCII??)

I could make sense to ask for an ASCIIString type in WebIDL if you really want just ASCII. (Failing that, you could make it ByteString in WebIDL and perform an ASCIIness check as post-processing.)

If you want non-ASCII, then USVString makes sense.

> WGSL could conceivably handle input with invalid surrogate pairs (i.e. utf-16 strings that can't be represented as utf-8), but it would have to error on them. However, it could do so asynchronously instead of synchronously like USVString. So accepting USVString probably has some unnecessary call-site overhead for createShaderModule.

If the internals want UTF-8 or ASCII anyway, chances are that you'd want to convert on the call site anyway and then send the conversion result to async processing. Without actually measuring alternative implementations, I'd expect introducing an additional UTF-16/Latin1 (depending on what the incoming SpiderMonkey or V8 string is; dunno what JSC does) copy in order to avoid further processing at the call site not to be a good optimization.

Since USVString doesn't signal errors, you could even declare USVString in the spec but still declare something else in implementation and make the implementation defer the processing.

**Comment by kainino0x** [comment]
I don't think we want ASCII. As pointed out above, these debug labels could be used in error messages and Dev Tools where we should preserve whatever the user passes in. Also, userspace and extension debugging tools should be able to use this debug label slot for their own debug labeling (e.g. Spector.js, Three.js dev tools).

**Comment by kainino0x** [comment]
> Since USVString doesn't signal errors, you could even declare USVString in the spec but still declare something else in implementation and make the implementation defer the processing.

Thanks for pointing this out, I didn't realize it (oops).

FTR, how this works is: "To convert a string into a scalar value string, replace any surrogates with U+FFFD."

**Comment by hsivonen** [comment]
> FTR, how this works is: "To convert a string into a scalar value string, replace any surrogates with U+FFFD."

Replace any _unpaired_ surrogates with U+FFFD.

**Comment by annevk** [comment]
@hsivonen that sentence is correct per Infra semantics, as when interpreting a string as containing code points (rather than code units) surrogate pairs get turned into a single scalar value.

**Comment by kainino0x** [comment]
(it's copied from https://infra.spec.whatwg.org/#javascript-string-convert)
