### ISSUE TITLE
Copies of depth values outside [0, 1]

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#789]
[VK_EXT_depth_range_unrestricted](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_depth_range_unrestricted.html)
 > This extension removes the VkViewport minDepth and maxDepth restrictions that the values must be between 0.0 and 1.0, inclusive. It also removes the same restriction on VkPipelineDepthStencilStateCreateInfo minDepthBounds and maxDepthBounds. Finally it removes the restriction on the depth value in VkClearDepthStencilValue.

Interaction with [VkBufferImageCopy](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkBufferImageCopy.html)
> When copying to a depth aspect, and the VK_EXT_depth_range_unrestricted extension is not enabled, the data in buffer memory must be in the range [0,1], or the resulting values are undefined.

@Jiawei-Shao discovered this restriction when the latest Intel drivers began failing some of Dawn's depth texture tests. The extension is not supported on that new driver, and according to vulkan.gpuinfo.org, this extension is supported on 1.7% of Android devices, 55.3% of Windows devices, and 65% of Linux devices. This leads me to believe that a large number of current devices have this restriction as well.

It seems that core WebGPU may have to enforce the restriction that depth values stay within the [0, 1] range. This is most problematic for `copyBufferToTexture` when copying to the depth aspect of a texture. The WebGPU implementation will either need to validate or clamp the copied contents. It could instead perform the copy by running a compute shader or drawing a full screen quad to write depth.

Other parts of the API where depth writes may occur:
 - `depthLoadValue`: it is already a validation layer error on Metal, and perhaps other APIs, to have a `MTLRenderPassDepthAttachmentDescriptor.clearDepth` value outside the [0, 1] range
 - fragment shader output: this would be clipped if outside the viewport which is restricted to [0, 1]
 - storage texture writes: would need to be clamped in the shader

**Comment by kvark** [comment]
If all copies (from buffers to depth textures) need to validate the range and hence go via render/compute paths, we might as well just leave this to the user and say we can't copy between buffers and depth textures natively. At least for now.

**Comment by austinEng** [comment]
Maybe we could disallow bufferToTexture copies to the depth aspect, but still allow textureToBuffer copies.

**Comment by Kangz** [comment]
Copies from buffer to depth textures is useful for examples for pre-baked shadow maps. Disallowing them is unfortunate but maybe the workaround can be documented in a "best practice" document I guess.

**Comment by Jiawei-Shao** [comment]
Textures with depth formats are not required to support ```VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT``` in Vulkan ([Vulkan 1.1 SPEC, table 65](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#features-required-format-support)), so in WebGPU we cannot support textures with depth formats used as storage textures, and here we don't need to consider clamping depth values in storage texture writes.

**Comment by litherum** [comment]
VK_EXT_depth_range_unrestricted:

Windows: 55.8%
Linux: 65.5%
Android: 1.7%

**Comment by kainino0x** [comment]
discussed in meeting; resolution: no copies from buffers to depth24plus/depth32float formats for now. Apps can do a shader-blit, and we can consider adding it to WebGPU later.

Also, clamp writes to gl_FragDepth whenever needed.

**Comment by kainino0x** [comment]
I tried to summarize all of the data from these investigations/conversations.

Also note the close relationship to #744 and #811, which are about texture view formats.
Note (#744), in Metal, a "texture view" is a Texture that reinterprets another
Texture (they have the same type). They can be used to implement copies between
compatible formats, which is discussed in #842.

Current depth/stencil formats:
- depth32float
- depth24plus
- depth24plus-stencil8

Possible (future or extension) depth/stencil formats:
- x-stencil8
- depth32float-stencil8
- depth24unorm
- depth24unorm-stencil8
- depth16unorm

Copies that will probably always be allowed (note some of these
decompose into two single-aspect copies in some backends):
- (same format, matching aspect) <-> (same format, matching aspect)
- (depth24plus) <-> (depth24plus-stencil8, depth-only)
- Buffer <- (depth32float)/(depth32float-stencil8, depth-only)
- Buffer <-> (depth16unorm)
- Buffer <-> (x-stencil8)
- Buffer <-> (depth24plus-stencil8, stencil-only)
- Buffer <-> (depth24unorm-stencil8, stencil-only)
- Buffer -> (depth24unorm)/(depth24unorm-stencil8, depth-only)

Copies that would require format conversions:
- Buffer <-> (depth24plus)/(depth24plus-stencil8, depth-only)
- Cross-format T2T copies (ignored for now)

Copies that would require zeroing unused bits:
- Buffer <- (depth24unorm)/(depth24unorm-stencil8, depth-only)
- Buffer <-> (depth24plus)/(depth24plus-stencil8, depth-only)
  (if buffer format is depth24unorm)

Copies that would/could require clamping to keep values in range:
- Buffer -> (depth32float)/(depth32float-stencil8, depth-only)
- Buffer -> (depth24plus)/(depth24plus-stencil8, depth-only)
- Many cross-format T2T copies (ignored for now)

Copies that would require Metal texture views or other aliasing:
- r32float <-> (depth32float)/(depth32float-stencil8, depth-only)
- r16unorm <-> (depth16unorm)
- r8uint <-> any stencil8
- and so on.

Resolution from 06-15 on #789:
- no copies from buffers to depth24plus/depth32float formats

**Comment by Kangz** [comment]
@austinEng did all the discussion above get encoded in the spec?

**Comment by austinEng** [comment]
I don't see anything about clamping fragment depth in the WebGPU or WGSL spec. WebGPU spec also does not have validation that depthLoadValue is between 0 and 1.

**Comment by Kangz** [comment]
Moving to V1 to track fixing these issues.

**Comment by kainino0x** [comment]
> I don't see anything about clamping fragment depth in the WebGPU or WGSL spec.

Was fixed with #2139.


> WebGPU spec also does not have validation that depthLoadValue is between 0 and 1.

Still needs to be fixed. (We have to choose whether to validate or clamp. If underlying APIs all clamp we could standardize on it too.)

**Comment by Kangz** [comment]
> Still needs to be fixed. (We have to choose whether to validate or clamp. If underlying APIs all clamp we could standardize on it too.)

Slight preference for validating, so that if later we allow for unrestricted depth with an optional feature, it is possible to clear to a depth outside [0, 1]

**Comment by kainino0x** [comment]
This makes sense to me. Otherwise enabling unrestricted-depth on the device would change the behavior of clearing.

So enabling unrestricted-depth would have the following (non-breaking) behavior:
- Allow an "unclampedDepth" option to be enabled on the pipeline
- Allow clear depth to be outside [0, 1]

So, we need to add this validation.

**Comment by kainino0x** [comment]
> (We have to choose whether to validate or clamp. If underlying APIs all clamp we could standardize on it too.)

Realized that the OP already specifies this is a validation-layer error on Metal. So good to follow that.
