### ISSUE TITLE
>>> should be logical right shift and >> should be arithmetic right shift

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#790]
WGSL should match Java, instead of being inverted from it.

`>>>` should always shift in 0 bits at the MSB, and `>>` should replicate the sign bit.

**Comment by litherum** [comment]
What is the implementation strategy for HLSL & MSL?

**Comment by kainino0x** [comment]
If they don't have logical right shifts (which is surprising - it comes from C - but seems to be true), then you should be able to cast to an unsigned type. IIRC arithmetic and logical right shift should be the same for unsigned types.

**Comment by kainino0x** [comment]
Oops, I was wrong, C/C++ don't have it.

**Comment by johnkslang** [comment]
C/C++, GSL, and HLSL have logical right shift when the LHS type is unsigned, despite reusing the same operator for the signed arithmetic shift.  Translation is possible to/from languages with distinct spelling.

Will you define the behavior for shifting by "too much"?  It might be hardware dependent and involve performance trade-offs.

**Comment by litherum** [comment]
On https://github.com/gpuweb/gpuweb/issues/706, we resolved to have developers write more complicated expressions if they wanted the different behavior. I wonder what the difference in philosophy between that issue and this one is.

**Comment by kainino0x** [comment]
This issue, as titled, isn't about whether to have both `>>>` and `>>`, and it should not be discussed in a meeting. Can we open a new issue for that and put that one on the agenda instead?

**Comment by kainino0x** [comment]
I think you'll find that the difference in philosophy is "didn't think about it very hard."

**Comment by kainino0x** [comment]
I forgot the meeting was now. Let me open that new issue.

**Comment by kainino0x** [comment]
IMO this is a spec bug, not an item for discussion, so I'm putting it in the "Needs Specification Work" bucket. The item for discussion is now #825.

**Comment by dj2** [comment]
PR #772 removed `>>>` so I believe this can now be closed.
