### ISSUE TITLE
Do not link all functions to contexts

### ISSUE THREAD

**Issue by dmikis** [gpuweb/gpuweb#8]
It'd be nice not to have all API function tied to some context object. Right now, since the API is context-based, it more or less makes sense, but, for example, in Metal we aren't tied to context objects (or, IIRC, event to a device object) so much. We can create buffers, shader libraries and textures w/o need to explicitly reference a context. Necessity of passing `gl` context sometimes creates not so nice constructs in code (for example, [three.js](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLTextures.js#L400)).

**Comment by frzi** [comment]
Metal definitely wants you to allocate / initiate buffers, textures and shader libraries through the `MLTDevice` object though.

[MTLBuffer reference overview](https://developer.apple.com/reference/metal/mtlbuffer)
> Do not create a MTLBuffer object by using standard allocation or initialization techniques. Instead, use the following MTLDevice methods to create MTLBuffer objects: etc.

The same description can be found on the reference pages of `MTLTexture` and `MTLLibrary`.

Though admittedly, Metal isn't part of my day-to-day app development routine. So perhaps someone with a bit more knowledge of the Metal API can correct me here. :)

Personally I would not oppose to keeping the context as source of resource initializations.

**Comment by kainino0x** [comment]
As Mateusz pointed out, there's nothing preventing an app from putting the device in some global place and using it as a global. For many reasons (including multi-adapter, having multiple apps on the same page, etc.), there's no chance that the group will do this change.
