### ISSUE TITLE
const_expr example does not match its grammar

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#800]
https://gpuweb.github.io/gpuweb/wgsl.html#literal-statement

```
const_expr
  : type_decl PAREN_LEFT (const_expr COMMA)? const_expr PAREN_RIGHT
  | const_literal
```

It appears that, if there's only a single pair of parentheses, that the parentheses must hold either 1 or 2 terms inside them. However, there's an example:

```
vec4<f32>(1.2, 2.3, 3.4, 2.3)
```

**Comment by dj2** [comment]
Ah, should be a `*` instead of a `?`.
