### ISSUE TITLE
`gpuweb.github.io` should point to `https://gpuweb.github.io/gpuweb`

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#806]

**Comment by kainino0x** [comment]
I think about this every so often and didn't realize I was responsible for having created the gpuweb.github.io repository to begin with! :)

This looks like the way to do it:
https://help.github.com/en/enterprise/2.13/user/articles/redirects-on-github-pages

BTW, this reminded me to finally go fix our webgpu.dev redirect so it doesn't insert an extra `/`.

**Comment by kainino0x** [comment]
I put in a meta refresh to redirect. Seems to work. https://github.com/gpuweb/gpuweb.github.io/blob/master/index.html
