### ISSUE TITLE
add depthTestEnable flag?

### ISSUE THREAD

**Issue by yukunxie** [gpuweb/gpuweb#809]
Is there a need to add a depth test enable to GPUDepthStencilStateDescriptor?

```
dictionary GPUDepthStencilStateDescriptor {
         boolean depthTestEnable?
}
```

**Comment by kvark** [comment]
Not really. Disabled depth state is what you get by default if you don't initialize any members of `GPUDepthStencilStateDescriptor`.

**Comment by Kangz** [comment]
We discussed this a lot in the past and resolved for not having an additional boolean. Instead it will be deduced by implementations, and the defaults give you a disabled depth test.
