### ISSUE TITLE
12.34 is not a valid float literal

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#816]
> FLOAT_LITERAL: `(-?[0-9].[0-9]+ | -?[0-9]+.[0-9])(e(+\|-)?[0-9]+)?`

I think this definition disallows numbers with multiple digits both before and after the dot.

**Comment by dj2** [comment]
It's a rendering issue, if you look at the actual source there are stars which are not rendering. Need to figure out why it's rendering that way.
