### ISSUE TITLE
Should writeBuffer/writeTexture take ArrayBufferView instead of ArrayBuffer?

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#820]
e.g. WebGL:
```webidl
  void texImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height,
                  GLint border, GLenum format, GLenum type, [AllowShared] ArrayBufferView srcData,
                  GLuint srcOffset);
```

**Comment by kainino0x** [comment]
@kvark

**Comment by kainino0x** [comment]
Or maybe more likely, [BufferSource](https://heycam.github.io/webidl/#idl-buffer-source-types):

> When designing APIs that take a buffer, it is recommended to use the BufferSource typedef rather than ArrayBuffer or any of the view types.

**Comment by kvark** [comment]
Yes, `BufferSource` makes total sense here.

**Comment by kainino0x** [comment]
Should we adopt the same convention as WebGL where dataOffset becomes an offset in elements, rather than bytes, for ArrayBufferView overloads?

**Comment by kainino0x** [comment]
FWIW, WebGL only allows ArrayBufferViews with source offsets (not BufferSource, which is `(ArrayBuffer or ArrayBufferView)`), so unlike WebGL we would have to spec that the offset is in bytes for ArrayBuffer.

**Comment by kainino0x** [comment]
Hmm, also, for writeTexture, we would have to define dataLayout.offset to measure in elements as well.

Alternatively, we could make these always byte offsets and validate that they're multiples. I'm going to propose this.
