### ISSUE TITLE
writeBuffer error if buffer is mapped

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#821]
I realized while implementing #749 that it requires an exception to be thrown if the buffer is mapped.

I have been thinking for months that we already needed to track the buffer `[[state]]` on the client-side in a way that was multi-thread-synchronized. However I can't seem to find a good reason for it - map calls return asynchronously, and unmap and writeBuffer can both generate errors asynchronously. (Though note we already have most of the info on the state via the pending promise and the mapped data, anyway.)

Given this, I think `writeBuffer` should fail asynchronously if the buffer is mapped. This would match `unmap()` and the map calls.

@kvark

**Comment by kvark** [comment]
Right, the requirement here is exactly the same as for `submit`: if you use a buffer in a queue, it can't be mapped at that time.
