### ISSUE TITLE
WGSL should have a select function

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#826]
Forked from https://github.com/gpuweb/gpuweb/issues/748

Start with a select builtin function, similar to OpenCL C's select.  This needs a proposal.

**Comment by dneto0** [comment]
- SPIR-V 1.0 for graphics
   -  allows selection among bool, numeric scalars, and vectors of them.
   - the condition is either a scalar bool;  or a vector-of-bools in which case both operands must have same number of components
- MSL 
   - allows selection among bool, numeric scalars, and vectors of them
   - seems to imply that scalar bool is not allowed to select among vectors.  But for scalar bool selector we can map it to the ternary operator.  (b ? v0 : v1).
- HLSL
  -  does not have a named builtin, but has the ternary operator.  It does not short-circuit https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-operators
  - an experiment on shader playground shows that ? : works with scalar bool selecting over vectors.

**Comment by litherum** [comment]
It would be fine to have additional overloads of a WGSL function which internally run different MSL code depending on overload. We could have `select(vec4<T>, vec4<T>, vec4<bool>)` which maps to MSL's `select` and `select(vec4<T>, vec4<T>, bool)` which maps to MSL's ternary statement.

**Comment by kvark** [comment]
@dneto0 
> an experiment on shader playground shows that ? : works with scalar bool selecting over vectors.

what about `vecN<bool>` selecting over `vecN<something else>`?

**Comment by johnkslang** [comment]
> what about vecN<bool> selecting over vecN<something else>?

Yes, the selector can be bool while the objects selected between are some other types, and implicit type conversions are also at play.

Even in a very strict type system, it makes sense to say the first operand is a vector of bool, while the other two operands must match in type, but can be any vector type.  That's probably what you want for WGSL, and that's what SPIR-V does.

**Comment by dneto0** [comment]
> what about vecN<bool> selecting over vecN<something else>?

Answering for HLSL:     ? :  works with   bool4 ? float4 : float4.
It is not short-circuiting.
Here's an experiment in DXC, on shader playground:

http://shader-playground.timjones.io/e34dbe7fa5c2f42af2c4b6c3f86329bf

Input HLSL:

```hlsl
struct PSInput
{
	float4 color : COLOR;
};

float4 PSMain(PSInput input) : SV_TARGET
{
	float4 v = input.color * input.color;
    bool4 selector = input.color < v;
    return selector ? input.color : v;
}
```

Output DXIL fragment
```llvm

define void @PSMain() {
  %1 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 0, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %2 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 1, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %3 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 2, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %4 = call float @dx.op.loadInput.f32(i32 4, i32 0, i32 0, i8 3, i32 undef)  ; LoadInput(inputSigId,rowIndex,colIndex,gsVertexAxis)
  %5 = fmul fast float %1, %1
  %6 = fmul fast float %2, %2
  %7 = fmul fast float %3, %3
  %8 = fmul fast float %4, %4
  %9 = fcmp fast olt float %1, %5
  %10 = fcmp fast olt float %2, %6
  %11 = fcmp fast olt float %3, %7
  %12 = fcmp fast olt float %4, %8
  %13 = select i1 %9, float %1, float %5
  %14 = select i1 %10, float %2, float %6
  %15 = select i1 %11, float %3, float %7
  %16 = select i1 %12, float %4, float %8
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 0, float %13)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 1, float %14)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 2, float %15)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  call void @dx.op.storeOutput.f32(i32 5, i32 0, i32 0, i8 3, float %16)  ; StoreOutput(outputSigId,rowIndex,colIndex,value)
  ret void
}
```

So evaluation is point-wise, but there is no short-circuiting behaviour.

**Comment by johnkslang** [comment]
> but there is no short-circuiting behaviour.

There cannot be, it can't even be a question when doing a vector select.  It all falls apart to go down that path, so it simply is not done.  (Operands could be function calls that swizzle between selected and non-selected components, etc.; it's insoluble.)

Short-circuiting is only a thing to decide, one way or the other, if you have a scalar condition and you have possible side effects in the other operands.
