### ISSUE TITLE
Define behavior of too-large shift values

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#828]
How do we treat `1 << 32`?

**Comment by jdashg** [comment]
Related somewhat to #827.

**Comment by kainino0x** [comment]
options, approximately:

`x << s` is:
- `x << clamp(s, 0, 31)`
- `x << (s & 0x1f)`
- partially-defined: any of multiple possible options
- undefined result

**Comment by dneto0** [comment]
SPIR-V:

- always treats the shift operand as unsigned (regardless of its actual type)
- says "The result is undefined if Shift is greater than or equal to the bit width of the components of Base."  So, an undef value.

LLVM's shl says "The value produced is op1 * 2op2 mod 2n, where n is the width of the result. If op2 is (statically or dynamically) equal to or larger than the number of bits in op1, this instruction returns a poison value"  Where poison value induces undefined behaviour downstream.

**Comment by dneto0** [comment]
https://llvm.org/docs/LangRef.html#shl-instruction

**Comment by dneto0** [comment]
I'd prefer @kainino0x's second option.

If we really want negative shifts, we should make a different builtin function for it.

**Comment by pow2clk** [comment]
Just want to clarify that @kainino0x's second option is:
`x << (s & 0x1f)`

If so, I'm in favor of that as well.

**Comment by RobinMorisset** [comment]
Some context:
Wasm masks the second operand of shifts.
JS does the same for shifts of numbers.
JS allows any size for the second operand for BigInts, including negative values.

I agree with the previous posters that we should just mask the second operand of shifts. It has been successfully used in other web languages, and is extremely cheap to implement.

**Comment by litherum** [comment]
Resolved: Mask the RHS of shifts

**Comment by litherum** [comment]
(Discussed on today's meeting: https://docs.google.com/document/d/1jiRiUAEBkG1UPFZTTeEx81HCXlrTeucCrfATIFBhzzI/edit)
