### ISSUE TITLE
What online and offline tooling exists, or is planned, for compiling to WGSL?

### ISSUE THREAD

**Issue by juj** [gpuweb/gpuweb#845]
Trying to gauge the landscape here: what kind of tooling is available, or planned, or in the works, to compile shaders to WGSL from different sources (HLSL, HLSL/D3D bytecode, GLSL, SPIR-V), either offline as a preprocessing tool, or as online directly from an Emscripten-compiled WebAssembly application?

It would perhaps be good to officially maintain a documentation piece about the options in this area, I doubt that many developers who target multiple platforms will be able to hand-re-write their shaders in to WGSL and maintain multiple copies?

**Comment by kvark** [comment]
[Naga](https://github.com/gfx-rs/naga) will eventually support SPIRV -> WGSL and GLSL -> WGSL.
I agree that documenting the tools, if not officially maintaining them, is very useful to assist developers. At the same time, it's way too early: we don't even have the defined syntax for samplers and texture at this point in WGSL. It needs to brew a little bit longer within the group before starting to spread out into the ecosystem.

**Comment by juj** [comment]
Thanks, that is great news.

Do you know if that tool is possible to compile via Emscripten over to Wasm for online use? Is that kind of use even in scope for Naga? What would the online network transfer footprint be like? (Is Naga expected to be lightweight at all?)

We are really struggling at Unity to get on board with WGSL, trying to find solutions to this exotic decision.

**Comment by kvark** [comment]
It's fully in scope of Naga to produce lightweight WASM binaries for online use, including the specific conversion paths, like GLSL -> WGSL. @pjoe has been looking into the footprint so far, using https://github.com/pjoe/wasm-naga (also see https://github.com/gfx-rs/naga/pull/55), so maybe they can share some numbers (assuming all low hanging fruits taken into account, which may not be the case yet).
Note that this discussion is better to continue in #naga:matrix.org or an issue in Naga repo, since this isn't the group's work artifact but a community project.

**Comment by joeedh** [comment]
> [Naga](https://github.com/gfx-rs/naga) will eventually support SPIRV -> WGSL and GLSL -> WGSL.
> I agree that documenting the tools, if not officially maintaining them, is very useful to assist developers. At the same time, it's way too early: we don't even have the defined syntax for samplers and texture at this point in WGSL. It needs to brew a little bit longer within the group before starting to spread out into the ecosystem.

Any timeline on this?  I just started coding a GLSL 4.5 to WGSL translator.

**Comment by dj2** [comment]
https://dawn.googlesource.com/tint is planning on having a SPIR-V to WGSL conversion path as well. If you want to go from GLSL, our plan is you'd go through GLSLang first to SPIR-V and then convert that to WGSL.

The SPIR-V to WGSL path is being built out currently.

**Comment by pjoe** [comment]
@joeedh A preliminary glsl frontend just landed in naga. It is however using a parser lib with rather large wasm output size, so looking at rewriting the parser using a different parser generator.

I don't really know the status of the wgsl backend, maybe @kvark knows?

**Comment by kvark** [comment]
@pjoe our WGSL backend work has not started, but this would be the simplest of all, trivial to write, since the IR is basically WGSL AST already.

**Comment by dj2** [comment]
@joeedh As an alternative of going GLSL -> WGSL you could go GLSL -> SPIR-V -> WGSL. This flow exists to the point that you can do most of computeboids as WGSL -> SPIR-V -> WGSL in Tint now (I say mostly because `stride` isn't spec'd and is needed for computeboids.

**Comment by dj2** [comment]
Given there is nothing actionable here, I'm going to close this. If there are specific requests please file followup issues.
