### ISSUE TITLE
query interface?

### ISSUE THREAD

**Issue by krogueintel** [gpuweb/gpuweb#856]
It would be ideal for the the section on queries https://gpuweb.github.io/gpuweb/#queries and the command beginPipelineStatisticsQuery() and endPipelineStatisticsQuery() to cross reference each other.

Also, the interface for occlusion is not at all clear to me. Indeed, the interfaces for query is taking 32-bit size integer, but where and how is the buffer decided for the query result to land?

On a related note, it would be ideal that if a buffer contains MAP_READ it can also contain COPY_DST or QUERY_RESOLVE but no other; I am assuming that QUERY_RESOLVE means that the buffer will hold query results.

**Comment by Kangz** [comment]
> I only found how to create a query set in the specification: https://gpuweb.github.io/gpuweb/#queries but I did not find the functions or way to have a query result land in a buffer. Where is that?

The function to resolve is [`resolveQuerySet`](https://gpuweb.github.io/gpuweb/#dom-gpucommandencoder-resolvequeryset) but it doesn't have specification text yet. Also I don't think any browser implements it yet.

> On a related note, it would be ideal that if a buffer contains MAP_READ it can also contain COPY_DST or QUERY_RESOLVE but no other; I am assuming that QUERY_RESOLVE means that the buffer will hold query results.

It might be useful given `QUERY_RESOLVE` is a write-only usage and similar to a `TRANSFER_DST` (even though it can be implemented with compute shaders), but we'd have to study feasability on all APIs (I'm not sure if it would be possible on D3D12 without more expensive emulation).

**Comment by krogueintel** [comment]
As a gentle suggestion, it would be ideal to write a section on how queries are to be used and have the various query entry points have links to that text.

**Comment by krogueintel** [comment]
Sighs, I am doing this from the wrong account from using the wrong browser instance. My sincere apologies.
