### ISSUE TITLE
depth24plus question

### ISSUE THREAD

**Issue by krogovin** [gpuweb/gpuweb#857]
Looking at https://gpuweb.github.io/gpuweb/#texture-formats, I see for depth formats depth24plus, but no depth24 along with the comment that the prevision of depth24plus is not the same as typical native depth24. Some questions:

What is the formula between the depth24plus 24-bit integer value and a depth value? Native API's are pretty explicit that float_value = integer_value / (-1 + 2^24).

Given the text
>The depth24plus family of formats (depth24plus and depth24plus-stencil8) must have a depth-component precision of 1 ULP ≤ 1 / (2^24).
>Note: This is unlike the 24-bit unsigned normalized format family typically found in native APIs, which has a precision of 1 ULP = 1 / (2^24 − 1).

what does that mean how it is mapped to native API's? depth32float does not have 24-bits precision anyways, so this left me scratching my head. Is the value 1.0 representable even?

**Comment by Kangz** [comment]
`depth24plus` is a fake format that's allowed to be implemented as either `depth32float` or `depth24unorm`. `depth32float` almost has the same precision as `depth24unorm` but not exactly, hence the spec section you quoted.

**Comment by Kangz** [comment]
Also given the number of question, you might also want to ask them in the [WebGPU Matrix channel](https://matrix.to/#/#WebGPU:matrix.org).

**Comment by krogovin** [comment]
Ok; i just figure in more searchable on github issues so others can find it.
