### ISSUE TITLE
Sampler/image not-really feedback in compute shader

### ISSUE THREAD

**Issue by krogovin** [gpuweb/gpuweb#858]
I am looking at a use case where I wish to write to a texture-2d-array from a compute shader (as an image-load-store operation) while at the same time reading from it with the promise that the compute shader will NEVER read from the sample place it writes to (with accounting for filtering). The catch being that the writes do happen at LOD=0 and reads as well.

Is this not-really feedback allowed in WebGPU?

**Comment by Kangz** [comment]
It is not allowed at the moment because some systems we target can only have readonly or writeonly storage textures. You can work around this by using a storage buffer.

By the way, do you mind closing the issues when you feel your question has been answered?

**Comment by krogovin** [comment]
Sure.

**Comment by Kangz** [comment]
The checks can be optimized easily if a resource is used only for one usage, so the validation cost will mostly only increase for complicated pattern of subresources covered for a view and if the resources is used with potentially conflicting usages.

Closing as the question has been resolved.
