### ISSUE TITLE
Document vertex expansion rules

### ISSUE THREAD

**Issue by litherum** [gpuweb/gpuweb#861]
It native graphics APIs, it’s common for the data format inside the VBO to not exactly match the  erred type used in the shader. This allows flexibility between the API and the shading language; you don’t have to generate multiple shaders to unpack different vertex formats.

We should document exactly what conversions WebGPU will do for authors, and which will result in compile errors.

**Comment by Kangz** [comment]
We should investigate what conversions the different native APIs do, so WebGPU matches them when all APIs agree.

**Comment by Kangz** [comment]
Superseeded by #1880

**Comment by Kangz** [comment]
(because it has more questions, and confirmation of the behavior of underlying APIs)
