### ISSUE TITLE
WorkGroup memory size and barriers?

### ISSUE THREAD

**Issue by krogovin** [gpuweb/gpuweb#863]
Looking at the spec, I was not able to find information on how big work group memory can be or any barrier commands within a compute shader for writes in work group memory to be visible to other items of the same local work group.

Or did I just miss it? Or am I asking about this too soon?

**Comment by kvark** [comment]
This shall be exposed, we just haven't gotten to it yet (i.e. "too soon").

**Comment by grorg** [comment]
Discussed at the [2020-06-24 WebGPU Virtual F2F](https://docs.google.com/document/d/1uv0LiQB2gAFbUEU3qx2-Sgsv6r3fEKMvnifbFoRbvmw/).

**Comment by krogovin** [comment]
Some of that discussion is *off* for some hardware.

> DM: driver has to be able to spill registers to memory and then support any group sizes. People see drastic perf hit, but at least it compiles. Could issue synchronous perf warning.
> MM: is it possible to validate that? Create program with huge register pressure?
> DN: Yes, it is. See here: https://github.com/gpuweb/gpuweb/issues/275
> DN: would like compiler to be able to reject. WebGPU has to be able to run a prescribed set of things. If I requested a single word's use of WG memory, that's not sufficient reason for the driver to reject my shader. Have to have a minimum bar that the WebGPU impl has to support.

There is no reason to expect that shared memory must be registers. Indeed, on Intel GPUs, shared memory is almost never register space (because of the way that Intel GPU's are). On Intel HW once the local work group size exceeds 32, there is no way to make shared memory as registers (this is because the SIMD thread size maxes out at 32 and there is no HW interface to see values outside of the thread), so a local group size of 16x4x1 will need have shared memory in scratch and not register space.

I know for Intel HW, as soon as there is dynamic index access on an array, that the values are realized in scratch space and not in register space so the following typical work group memory use:

```
shared SomeMemory[LocalGroupSize.x][LocalGroupSize.y][LocalGroupSize.z];

SomeMemory[LocalGroup.x][LocalGroup.y][LocalGroup.z] = V;
barrier();

neighbor.x = max(1, LocalGroup.x) - 1;
neighbor.y = max(1, LocalGroup.y) - 1;
neighbor.z = max(1, LocalGroup.z) - 1;
v = SomeMemory[neighbor.x][neighbor.y][neighbor.z];
vv = V - v;
 
```
is likely never realized as register space because of the dynamic indexing (one can try to make an argument that a genius compiler will figure out a way for the above to be register if the local group size is less than 32, but do not count on it at all).

Lastly, for Intel drivers, getting the SIMD group size to be 32 is REALLY HARD and only happens in shaders with minimal register pressure.

**Comment by Kangz** [comment]
> There is no reason to expect that shared memory must be registers.

That's not what the minutes imply (and not what I remember being implied from the discussions). This part of the discussion was around the issue of some shader programs being valid WGSL, with the right limits, but not possible for the driver's shader compiler to lower to the GPU's ISA because of the register pressure. No API has guarantees on exactly which set of programs will succeed their register allocation. Instead @dneto0 was suggesting the WebGPU group creates a number of difficult shaders (register pressure, or otherwise) and have tests in the CTS that they work correctly. This way developers can know that reasonably complex programs won't be rejected by the driver's shader compiler.

**Comment by grorg** [comment]
Briefly discussed at the [2020-08-25 meeting](https://docs.google.com/document/d/13lWCWtooVE1kT6TGta16gM-dDXjRdUKt9KG_9cTcTkY/edit?usp=sharing). Resolution was that there needs to be investigation before we can address this completely.

**Comment by Kangz** [comment]
The workgroup memory size limit is defined in the API spec and barriers are in WGSL now. Closing this.
