### ISSUE TITLE
WGSL should require storage buffers to be a host-shareable storable type.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#877]
There are currently no restrictions on what data type is used in a storage buffer in WGSL. In SPIR-V a storage buffer must be a host-shareable storable type, we should update WGSL to match the restriction in SPIR-V and require storage buffers to contain only host-shareable storable types.

**Comment by dneto0** [comment]
Also need a bit more.  Summary:

A storage buffer is a variable in the shader where:
* High level flow:
    * The initial contents are provided by the host code
    * Can be read from and written to by the shader
    * After the pipeline executes, the contents are available to the host code.
* WGSL details:
    * The variable is declared at module scope, using storage_buffer storage class
    * Has set and binding decorations.
    * The store type of the variable must be a block-decorated host-shareable structure type whose contents are explicitly laid out.  (The layout policy is separately tracked)

**Comment by grorg** [comment]
Discussed at the [2020-07-07 meeting](https://docs.google.com/document/d/1jiRiUAEBkG1UPFZTTeEx81HCXlrTeucCrfATIFBhzzI/).

**Comment by dneto0** [comment]
This landed long ago.
