### ISSUE TITLE
Feedback on current Buffer mapping API (for wgpu-py)

### ISSUE THREAD

**Issue by almarklein** [gpuweb/gpuweb#897]
> *kvark on Riot chat:* we don't have a lot of doubt in this API, but it's still fresh, and we haven't seen it used much, really, yet. Some feedback may change what we think ;)

Here's some feedback from our POV :) Disclaimer: this issue may be rather specific to Python, though I can imagine that it would apply to some other high level languages. See [this issue](https://github.com/pygfx/wgpu-py/issues/114) on wgpu-py for more Python details.

I found it hard to come up with an elegant solution to implement the buffer-mapping-API in wgpu-py. The fact that the user requests memory (the buffer mapping) which is later invalid (once unmapped) is problematic, because we cannot restrict access to memory unless we e.g. provide our own array-like object. So far, any solution I come up with is awkward and slow, which seems to defeat the purpose of the use-case of using a mapped buffer in the first place.

Therefore, for now, I've implemented `GPUBuffer.read_data(offset=0, size=0)` and `GPUBuffer.write_data(data, offset=0)` (more or less an alias for `GPUQueue.write_buffer()`) and we're not exposing any of the mapping-stuff. The API is much simpler this way, though we miss out on some of the potential benefits of using mapped memory.

As I understand it, the intention of the API using mapped memory is the performance benefit of avoiding data copies in some use-cases. Or are there other benefits that I am overlooking?

**Comment by Kangz** [comment]
> I found it hard to come up with an elegant solution to implement the buffer-mapping-API in wgpu-py. The fact that the user requests memory (the buffer mapping) which is later invalid (once unmapped) is problematic, because we cannot restrict access to memory unless we e.g. provide our own array-like object. So far, any solution I come up with is awkward and slow, which seems to defeat the purpose of the use-case of using a mapped buffer in the first place.

Why not have an opaque GPUMapping object that has read and write methods? It could still be efficient for bulk transfers, more than `write_data`.

> As I understand it, the intention of the API using mapped memory is the performance benefit of avoiding data copies in some use-cases. Or are there other benefits that I am overlooking?

Some benefits compared to just `GPUQueue.writeBuffer`:

 - More performance in term of number of copies.
 - Less contention on the `GPUQueue`.
 - More explicit control so applications don't have to rely on browsers to get things right for their specific usecase. This elso encompasses all the internal machinery for `GPU.writeBuffer` that's skipped with mapping.

**Comment by almarklein** [comment]
> Why not have an opaque GPUMapping object that has read and write methods? It could still be efficient for bulk transfers, more than write_data.

Yes, this is the solution that I think would make the most sense. But I expect that for setting small chunks / individual elements the added overhead quickly undoes the performance benefit. Right now it feels like the potential performance benefits may not be worth the more complex API. We're in Python, performance is not our main concern ;)  But anyway, I should probably do some benchmarking and see if it may be worth it ...

**Comment by almarklein** [comment]
> We're in Python, performance is not our main concern

This may be the bottom line. I understand that you must design an API that holds up in the most performance intensive use-cases. We have to make our own decisions in wgpu-py :)  Thanks for the feedback!

**Comment by kainino0x** [comment]
Mapping buffers is fundamentally very similar to mmapping files/fds. Maybe there is a library out there which exposes mmapped files to Python and you can copy their API? Or maybe you can even duck type it like a file object.

**Comment by kvark** [comment]
This issue should probably be transferred to webgpu-headers repo

**Comment by almarklein** [comment]
> Maybe there is a library out there which exposes mmapped files to Python and you can copy their API? Or maybe you can even duck type it like a file object.

Thanks for the suggestions :)  Yeah these are also viable options. Though all options make the API more complex. (And we're already dealing with the fact that in Python ppl use different things to represent arrays ... *sigh*). So the question for us is whether that's worth it. Our user won't be building Red Death Redemption 3 in Python, so an API without memory-mapping (and a bit more copying) may be just fine ;)

**Comment by kainino0x** [comment]
Data throughput performance could be really important for some python applications, especially compute-focused things like ML and scientific computing. Perhaps you can have a version with copies, and then with an optional dependency on numpy you can expose mappings through numpy arrays (which iirc are similar to JS ArrayBuffers in that they can point at natively allocated data). There doesn't seem to be a way to detach a numpy array, but there is `.resize()` which implies to me that their backing store can be replaced (e.g. `resize(0)`).

**Comment by almarklein** [comment]
We now expose data as `memoryview` objects, a builtin object that wraps the memory in an opaque way, and which makes it easy to create a numpy array wrapping the same memory. I'm quite pleased with this approach. If we'd return a numpy array instead, people would still create a view on that to map it to the appropriate data type (and perhaps shape).

The thing is that when you create a new view on the data, it locks the original array (whether that original is a numpy array or something else), so you won't be able to resize it or excluded access in another way.

Another approach that came to mind, which allows more fine-grained control is something like this:
```py
def write_chunks(sequence, offset=0, size=0):
    # With sequence an iterable (or even a generator) providing tuples (offset, data)
    ...
```

Similarly a `read_chunks()` method could return a generator providing chunks of data.
