### ISSUE TITLE
Ability to issue command and create resources from workers

### ISSUE THREAD

**Issue by dmikis** [gpuweb/gpuweb#9]
Guys from Google already [said](https://www.khronos.org/webgl/public-mailing-list/archives/1702/msg00027.php) that it's planned, but here's an issue anyway so it won't be forgotten :)

**Comment by othermaciej** [comment]
We definitely want this feature. There might be some benefits to a 1.0 version that doesn't tackle concurrency, but it's needed eventually and it's probably better to design it in from the start.

**Comment by jfbastien** [comment]
It may be practical to do this in two steps:

1. Allow creating and using resources from *a single* worker (not just main thread).
2. Allow sharing these resources from multiple workers.

IIUC the linked post is about 2. My understanding is that 1. is a useful first step, and technically easier to tackle. We've had requests for this for WebAssembly (and right now WebAssembly doesn't have its own APIs, so we allow whatever the web platform allows).

**Comment by kainino0x** [comment]
Tracking this issue in #354.
