### ISSUE TITLE
Vertex and Instance ID and base ID builtins.

### ISSUE THREAD

**Issue by Kangz** [gpuweb/gpuweb#901]
Spawned from this [bug report](https://bugs.chromium.org/p/dawn/issues/detail?id=477). The availability of builtins to gets the index of the current instance and vertex in the vertex shader vary between APIs.

## [D3D12](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics#vertex-shader-semantics)

 - `SV_InstanceID`: starts from 0, irrespective of the `firstInstance` in `Draw` / `DrawIndexed`
 - `SV_VertexID`: starts from 0, irrespective of the `firstVertex` in `Draw` and `baseVertex` in `DrawIndexed`

@RafaelCintron the docs aren't super clear, can you check for `SV_VertexID`? (edit: confirmed that it starts from 0)

## Metal (section "5.2.3.1 Vertex Function Input Attributes" of the MSL 2.3 "spec")

 - `[[base_instance]]`: the `firstInstance` in `DrawIndexed` and `Draw`
 - `[[base_vertex]]`: the `firstVertex` in `Draw` and `baseVertex` in `DrawIndexed`
 - `[[instance_id]]`: starts from `[[base_instance]]`
 - `[[vertex_id]]`: starts from `[[base_vertex]]`

## [Vulkan](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#interfaces-builtin-variables)

 - `BaseInstance`: the `firstInstance` in `DrawIndexed` and `Draw`, requires the `VK_KHR_shader_draw_parameters` extension / feature
 - `BaseVertex`: the `firstVertex` in `Draw` and `baseVertex` in `DrawIndexed`, requires the `VK_KHR_shader_draw_parameters` extension / feature
 - `InstanceIndex`: starts from `[[base_instance]]`
 - `VertexIndex`: starts from `[[base_vertex]]`

## [OpenGL](https://www.khronos.org/opengl/wiki/Built-in_Variable_(GLSL)#Vertex_shader_inputs)

 - `gl_VertexID`: starts from `baseVertex`/`firstVertex`.
 - `gl_InstanceID`: starts from 0.
 - `gl_BaseVertex` / `gl_BaseInstance`: require `GL_ARB_shader_draw_parameters` or OpenGL 4.6

## Conclusion

It's a mess and we're heavily limited by what D3D12 does, so we don't really have a choice. We should name builtins clearly to indicate if they start at 0 or not, to avoid the `gl_InstanceID` vs. `gl_InstanceIndex` confusion.

**Comment by kvark** [comment]
Thank you for the great investigation!
I think the story of `gl_VertexID`/`gl_InstanceID` depends on whether or not the base vertex/instance semantics is exposed to the shaders. Both Metal and Vulkan have it, so it's something to consider. If we have the built-ins in WGSL for base vertex/instance, and that means we find a way to expose them to D3D12 shaders, it means we can trivially implement `gl_VertexID`/`gl_InstanceID` in a way that's consistent with Metal and Vulkan (by computing `SV_VertexID + OurBuiltInBaseVertex` and such).

**Comment by RafaelCintron** [comment]
For D3D12, you can find information in the [DrawInstanced](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#8.4%20DrawInstanced()) and [InstanceID](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#InstanceID) sections of the D3D11 functional spec.  

In summary, `InstanceID` always starts at 0 per draw call and there is no way to find out what the value passed to `StartInstanceLocation` is in a shader.

**Comment by Kangz** [comment]
@RafaelCintron the question was more for `SV_VertexID`.

**Comment by dneto0** [comment]
Vulkan's support is actually optional, requiring VK_KHR_shader_draw_parameters and its named feature bit shaderDrawParameters.  It's common (>70% adoption across OS), but not universal.  The Android Compatibility Definition Document does not require it.  https://source.android.com/compatibility/android-cdd

**Comment by kvark** [comment]
@dneto0 ah, thank you! So we aren't going to be exposing the base instance/vertex builtins in WGSL core then. And it means we can't easily work around D3D12's difference.

However, if we decide to go the D3D12 path (with vertex/instance ID starting with 0), there is no easy way to do it on Vulkan either if we don't have the `VK_KHR_shader_draw_parameters`... So either way we go, there is some pain involved.

**Comment by RafaelCintron** [comment]
@Kangz , [VertexID](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#VertexID) behaves similarly to [InstanceID](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#InstanceID). Both start at zero and increment for each vertex and primitive respectively.

**Comment by grorg** [comment]
Discussed at the [2020-07-28 meeting](https://docs.google.com/document/d/1Ai4Tgm0PKBln2YjDywmcWQ2QyhIyuwNzWLkbnQr_jdo/).

**Comment by litherum** [comment]
Resolved: Match Metal / Vulkan. HLSL has to emulate.

**Comment by jdashg** [comment]
(If we have emulation issues while prototyping MVP, we can pick the other thing)

**Comment by Kangz** [comment]
Emulation for D3D12 seems tractable. The only difficulty is for indirect calls, but these already require GPU-based validation anyway, so it's possible to expand the arguments to set root constants in the D3D12 indirect command. Tentatively closing.
