### ISSUE TITLE
Constant propagation

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#905]
Do we need any kind of constant propagation in WGSL?
This is one of the examples from Metal Shading Language document:
```cpp
constexpr constant uint MAX_LIGHTS=4;
struct LightDesc{
  uint num_lights;
  float4 light_position[MAX_LIGHTS];
  float4 light_color[MAX_LIGHTS];
  float4 light_attenuation_factors[MAX_LIGHTS];
};
```

It relies on the `MAX_LIGHTS` constant to be propagated to define the array sizes.

Related to #572 : specialization constants aren't going to be "real" constants since in MSL they can't be used for array sizes, if I understand correctly.

**Comment by dj2** [comment]
This could easy be done in JS before passing the WGSL into WebGPU, so feels like we could leave until after MVP?

**Comment by johnkslang** [comment]
What's the scope of these statements?  As a single name for a number, it's trivial, but what about these?

```
constexpr constant uint MAX_LIGHTS1=4+1;
constexpr constant uint MAX_LIGHTS2=MAX_LIGHTS1*2;
constexpr constant uint MAX_LIGHTS3=MAX_LIGHTS2-1;  // side note: a syntax error, until '-' is moved to parsing
constexpr constant uint MAX_LIGHTS4=max(MAX_LIGHTS,MAX_LIGHTS2);
```

These would involve both folding and propagation.

**Comment by grorg** [comment]
Discussed at the [2020-07-28 meeting](https://docs.google.com/document/d/1Ai4Tgm0PKBln2YjDywmcWQ2QyhIyuwNzWLkbnQr_jdo/).

Consensus was to leave this out of MVP for now.
