### ISSUE TITLE
s/`kill`/`discard`/

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#911]
There's rough consensus preference for `discard` (GLSL/HLSL/MSL) rather than `kill` (from SPIR-V).

**Comment by jdashg** [comment]
Discussed at the [2020-07-07 meeting](https://docs.google.com/document/d/1jiRiUAEBkG1UPFZTTeEx81HCXlrTeucCrfATIFBhzzI/) as part of #361.

**Comment by kainino0x** [comment]
I think the only argument for 'kill' is that it's more specific. 'discard' could refer to either 'kill' or 'demoteToHelperInvocation' whereas those two are specific.

However I think 'discard' and 'demoteToHelperInvocation' (which would be an extension) would be perfectly clear.
