### ISSUE TITLE
Simpler methods

### ISSUE THREAD

**Issue by ottoville** [gpuweb/gpuweb#917]
To create a compute pipeline, one must write:
```
const pipeline = device.createComputePipeline({
            layout: shaderLayout,
            computeStage: {
                module: shaderModule,
                entryPoint: 'main'
            }
        })
```

As there are no more properties in GPUComputePipelineDescriptor interface than in example above, I made a shortcut method under GPUDevice class in my project for creating a compute pipeline. 

` createComputePipeline(GPUShaderModule, entryPoint = 'main',  GPUPipelineLayout?) : GPUComputePipeLine
`

The shortcut covers 100% of all usage cases. Layout is an optional because one could use "getBindGroupLayout" method to infer the bind group layout from the shader module. EntryPoint defaults to 'main' so its also optional.

So the question is, should the creation of  compute pipeline not be in line with pipelines that produces graphic output, as they share no common parameters.

**Comment by kainino0x** [comment]
In WebGPU today, the entryPoint name does not default to 'main', and I don't think we are very likely to add that default. However, the layout is already optional, so just like in your proposal you can omit it.

The shape of the API is to allow flexibility for future additions - we don't know what new arguments might be needed later on (but there is at least one planned: values for specialization constants).

That said, for this particular case, `computeStage` is arguably redundant and could potentially be dissolved out into the GPUComputePipelineDescriptor. (But it would break symmetry with GPURenderPipelineDescriptor.)

**Comment by Kangz** [comment]
It's probably ok to dissolve make `GPUComputePipelineDescriptor` inherit from `GPUProgrammableStageDescriptor`. It's unlikely to gain new stages in the future.

**Comment by kainino0x** [comment]
Resolved in the editors meeting (+@litherum): We want to keep the API as is - it's symmetric with rendering, and leaves open additional possibilities. For example there could be an extension where it's possible to feed vertex input into a compute shader (possibly even with a vertex shader? I'm not sure) so it's best to keep the flexibility here.
