### ISSUE TITLE
Investigation: kill vs demoteToHelper behavior in native APIs

### ISSUE THREAD

**Issue by kdashg** [gpuweb/gpuweb#921]
Discussion of #911 shows us we need to know more. The current direction is to require GLSL discard/kill semantics everywhere, but this might have implementation friction where not natively supported. One potential is to leave kill vs demoteToHelper as implementation defined, which is MVP but it would be better for portability to enforce a stricter behavior.

**Comment by jdashg** [comment]
@dneto0 @litherum

**Comment by dneto0** [comment]
Discussion in #361 is also relevant.

To my knowledge: 

GLSL's discard is specified to behave as follows:
- discard the fragment, i.e. remove the fragment affecting any further processing downstream of the fragment shader. E.g.  its outputs don't get written to colour attachments, and don't contribute to blending, and the fragment doesn't contribute to coverage masks
- the invocation no longer performs any later writes
- control flow is no longer uniform in that invocation's derivative, group. In particular other invocations attempting to compute a derivative will induce undefined behaviour.

To emulate GLSL discard on other platforms, you can think of GLSL discard acting as a "super return" within an invocation.  The effect on control flow is as if you set a private flag at module scope to say "I'm discarded now". Then return immediately from the function. Then each caller in the call stack checks for the flag immediately after the call, and itself does a return if the flag is set.  Ultimately you return from the entry point function.  This incurs a flag-checking cost at each call site that is potentially downstream from a function that can call discard.   (I can't tell if MSL allows you to declare a variable at module scope with thread address space. 
 In the worst case you can plumb the "i'm discarded" flag through function parameters)


HLSL/D3D "discard" semantics is:
- discard the fragment: fragment has no effect on pipeline processing downstream from the fragment shader, like above.
- the invocation continues to execute, but its writes have no effect (to storage buffers, storage images, or outputs).  The invocation is still alive so it can help compute derivatives requested by other invocations in its invocation group (quad).
- on some implementations (NVIDIA, I'm told), if all the invocations in an invocation group have been demoted, then all those invocations are terminated.  Let's call this mutual-termination.  On others, that is not the case and the invocations can continue processing even though they have no effect.
- These semantics have been added to Vulkan via the OpDemoteToHelperInvocationEXT in a [vendor extension](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/EXT/SPV_EXT_demote_to_helper_invocation.html)

To emulate D3D discard on other platforms, you have to arrange for the invocation to keep running, but suppress writes to outputs, images, and buffers, and then to remember to discard the fragment at the end of the entry point execution.  So this seems like:
- define a boolean flag variable indicating "i'm discarded"
- on every write that is potentially dynamically downstream of the discard, only perform the write if the flag is unset.
- in the entry point function, at the function returns, check the flag and issue a discard-fragment if the flag is set.

This emulation doesn't resolve the difference between the mutual-termination case and its opposite.

**Comment by dneto0** [comment]
The semantics of gl_HlperInvocation are still being debated over in OpenGL and Vulkan. See this discussion https://github.com/KhronosGroup/GLSL/issues/35#issuecomment-438734989

**Comment by dneto0** [comment]
I should have pointed at what appears to be the conclusion: https://github.com/KhronosGroup/GLSL/issues/35#issuecomment-764747669

**Comment by litherum** [comment]
I'd like to propose deferring `discard` until after MVP. It's difficult to make it behave identically on all platforms, and most shaders don't actually use it.

**Comment by kvark** [comment]
@litherum this seems like a strange choice. Wouldn't it be required to implement an old good alpha testing, one that people have been using for a dozen of years at least?

**Comment by dneto0** [comment]
`discard` is a core feature.

It's easy enough to force it to behave as "terminate this invocation".  

Post-MVP we can entertain the "demote to helper" behaviour.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-vf2f-2022-02-08,09-minutes#burndown-of-httpsgithubcomorgsgpuwebprojects2">WGSL meeting minutes 2022-02-08</a></summary>


    * MM: To butcher DM’s thought (maybe!) “native APIs have this and get value out of it, so we should consider this?
    * BC: Should we reserve `demote`?
    * KG: Probably and `demote_to_helper` to be safe
    * KN proposed `@demote_to_helper discard;`
    * **BC to reserve these**
    * 
</details>

**Comment by litherum** [comment]
In today's office hours, these 2 example programs were discussed:

1: 
```
if (nonuniform_with_my_quad) {
    while (true) {
        kill;
    }
}
```

In this example, if `kill` actually means `demote to helper`, then the fact that there is still an invocation alive within the quad (because `nonuniform_with_my_quad `) means that the helpers have to stay alive too, which means that the loop will never terminate. OTOH if `kill` actually means "the thread immediately stops running entirely" then the loop terminates after a single iteration.

2:
```
var result: f32 = 6;
if (i_am_in_quad_1) {
    storageBuffer[0] = 5;
} else /* I am in quad 2 */ {
    if (nonuniform_with_my_quad) {
        kill;
        result = storageBuffer[0]; // Is this a data race?
    }
}
let something = derivative(result);
```

In this example, if `kill` actually means `demote to helper`, then there's a data race between quad 1's write and quad 2's read of `storageBuffer[0]`. OTOH if `kill` actually means "the thread immediately stops running entirely" then this program is a compile error because `derivative()` would be called in non-uniform control flow.

**Comment by kdashg** [comment]
We talked about this in office hours.

**Example A** given there was:
```
  let c1 = textureLoad(tex1, coords, level);
  if c.a < 0.5 { discard; }
  [...]
  let c2 = textureSample(tex2, s, coords); // Requires UCF
```

With our current discard=kill behavior, and our current hard-error uniformity analysis, this is forbidden.
Authors would have to hoist all UCF-only invocations out to UCF, before the `discard`:

**Example A2**:
```
  let c1 = textureLoad(tex1, coords, level);
  let dcoords_dx = dpdx(coords);
  let dcoords_dy = dpdy(coords);
  if c.a < 0.5 { discard; }
  [...]
  let c2 = textureSampleGrad(tex2, s, coords, dcoords_dx, dcoords_dy);
```

This is a pain, and A is a fairly normal thing authors want to do, and they reasonably don't want to have to do A2.
Additionally, while A isn't sound in GLSL (discard = kill), **but it is sound on HLSL where discard = demote**.

(I believe I heard that) "Testing Has Shown" that AMD and Intel GL drivers seem to treat GLSL discard like HLSL discard (demote instead of kill), which they are I believe they are allowed to do, while NV GL has different behavior for discard in GLSL and HLSL.

`demote` and `kill` are similar, and I think these are good names that we can (roughly) agree on the behavior for.

Here are the definitions in for example SPIR-V:

`OpKill`: https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpKill
> [Deprecated](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#Deprecation) (use [OpTerminateInvocation](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpTerminateInvocation) or [OpDemoteToHelperInvocation](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpDemoteToHelperInvocation)).
>
> Ceases all further processing in any [invocation](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#Invocation) that executes it: Only instructions these invocations executed before OpKill have observable side effects. If this instruction is executed in non-[uniform control flow](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#UniformControlFlow), all subsequent control flow is non-uniform (for invocations that continue to execute).

`OpTerminateInvocation` is the same as `OpKill`, just not deprecated. (I'll get back to this)

`OpDemoteToHelperInvocation`: https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpDemoteToHelperInvocation
> Demote this fragment shader [invocation](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#Invocation) to a helper invocation. Any stores to memory after this instruction are suppressed and the fragment does not write outputs to the framebuffer.
> 
> Unlike the [OpTerminateInvocation](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpTerminateInvocation) instruction, this does not necessarily terminate the invocation which might be needed for derivative calculations. It is not considered a flow control instruction (flow control does not become non-uniform) and does not terminate the block. **The implementation may terminate helper invocations before the end of the shader as an optimization**, but doing so must not affect derivative calculations and does not make control flow non-uniform.

The differences:
* `kill` says control flow is no longer uniform, while `demote` says uniformity is unchanged.
* `kill` MUST (behave as if, so kinda SHOULD) stop execution.
  * `demote` MAY stop execution if you wouldn't be able to tell if it did.

My read is that, given that invocation of UCF-required functions in non-UCF is statically forbidden, kill can be implemented (observably-indistinguishable as-if behavior) directly as demote. If a WGSL program is uniformity-correct, and the 

We believe that both demote and kill are polyfillable in terms of each other:
* polyfill demote with kill: Store is_demoted as state, and branch on is_demoted for all visible shader outputs.
  * Bonus: if everyone is demoted, we MAY actually call kill.
* polyfill kill with demote: Call `demote`.
  * Bonus: We can "super-return" after calls to kill, to polyfill the desire for "please don't do any further work".
    * But I believe this isn't required by the `OpKill` spec, which (which, I believe, tellingly) merely says "Only instructions these invocations executed before OpKill **have observable side effects**.")

---

Here's my for why OpTerminateInvocation is the same language as OpKill:
I bet OpKill was the original translation of GLSL `discard`.
IHVs, in an effort to make sure shaders ran properly, would sometimes translate this into OpDemoteToHelperInvocation behavior, even before the [OpDemoteToHelperInvocation extension](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/EXT/SPV_EXT_demote_to_helper_invocation.html) was proposed.
But, with the addition of OpDemoteToHelperInvocation, authors who *really do want OpKill*, we got OpTerminateInvocation as well as a deprecation warning on OpKill.

---

**Example B** was:
```
if nonuniform {
  while true {
    [...]
    kill;
  }
}
```

(This might be the abstracted/minimal version of e.g. a ray-marcher, so it's not purely hypothetical)

The author's *intent* for this construct would be that this isn't an infinite loop, because once all "threads" `kill`, execution should fully stop deterministically. I don't think this is actually guaranteed by e.g. OpKill, but it's worth considering. Nor however is it forbidden by demote! (because "The implementation may terminate helper invocations")
**I think technically this is not defined to terminate**, though if true that kinda sucks. **We would want to specify whether this MUST terminate.**

---

* I believe `kill` is technically trivial for us to implement on platforms that have `demote` behavior, even if it feels like `kill` ought to be "more likely to have" "**unanimous termination**". (it sounds like Tint already implemented a super-return `kill` polyfill?)

* I am preliminarily (because I haven't looked yet) worried about our support matrix for native `demote` behavior. (i.e. do we have extensions everywhere we care about?)

* I kind of don't want to sign us up to implement a polyfill for demote masking for v1.

* I would naturally then think about having an extension for `demote` for v1, but I do worry about this with respect to fragmentation. People want to write Example A, and if we give them an extension which lets them do so, they're likely to just require that extension.
  * But maybe that's the right signal that we should prioritize polyfilling in our UAs)
    * But but realistically, this will cause fragmentation in our v1.

**If we need to polyfill `demote` anywhere, I'm leaning towards leaving this in post-v1**, but that we want to add it eventually.

**If however this helps us keep hard-uniformity-errors in v1, (or if there's no need to polyfill anywhere we care about,) I would rather add `demote` to core v1.**


---

*This link also showed up in office hours, so I'll mention it for completeness: https://dawn-review.googlesource.com/c/dawn/+/91420
This shows a test "that helper invocations do the same memory loads as non-helpers".*

**Comment by kdashg** [comment]
Also coming out of my thoughts here, and the way our discussion ended up using the terms, I'm proposing #2948.

**Comment by dneto0** [comment]
I'm catching up on the discussion above (thanks for the detail!).

Internal discussion at Google has landed at this consensus, a change of our position from before:

1. WGSL should support "discard" as demote-to-helper.
      - it is needed for #2969, which we believe is a common and reasonable developer coding pattern
      - It can be polyfilled as needed (see above)
2.  GLSL's discard is not consistently implemented.  A lot of folks writing "discard" are getting the demote behaviour anyway.
3. WGSL should not support a "kill" as in SPIR-V's OpTerminateInvocation.
      - *If* WGSL had both "kill" and "demote", then:
            - Guidance to shader authors is hard to craft, and is not entirely clear.  For most use cases, 'demote' is fine, and avoids uniformity analysis headaches
            - Because 'kill' causes a uniformity analysis rejection, but 'demote' does not (?), we think users will naturally drift to only using 'demote'.
            - Implementations are more complex.   This is technical burden/debt that would be carried forever.
            - CTS testing burden is increased
      - Tooling might be able to help in porting shaders that depend on 'kill' semantics.  In the worst case, an offline tool could implement the polyfill as a source-to-source translation.

**Comment by kdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-14-minutes#investigation-kill-vs-demotetohelper-behavior-in-native-apis--issue-921">WGSL meeting minutes 2022-06-14</a></summary>



* DN: We now think we should just use Demote. If we had both, people will end up just using Demote.
* DN: We do need to figure out what termination guarantees are, or at least a way to explain when we don’t have them.
* MM: It would be cool to pick a good name, even if we add terminate later on.
* KG: I think we should call it `discard`, because even when people use `discard` in GLSL, they expect Demote behavior (generally) and not Terminate.
* MM: I would like it if someone else can corroborate “what glsl authors expect”
* DN: With demote, I think we can remove Discard state from uniformity analysis.
* KG: I was talking with JB about this, and we think the subset of devices that might actually need a demote–on-terminate polyfill is narrow. Someone also said that on drivers that pre-date the OpDemoteToHelper extension, often OpDiscard gives OpDemoteToHelper behavior, even though the (current) behavior of OpDiscard is OpTerminate. (i.e it does not continue to contribute to derivative calculation)
* KG: Further, since newer drivers do support OpDemoteToHelper (and old ones might support it accidentally via old-OpDiscard) that we could probably ship v1 without doing the demote–on-terminate polyfill, and simply not run webgpu on those drivers that need it yet. We could add a demote–on-terminate polyfill in a later roll-out of support for these drivers.
* **Resolved: `discard` means demote-to-helper**


</details>
