### ISSUE TITLE
Naming of texture types.

### ISSUE THREAD

**Issue by dj2** [gpuweb/gpuweb#923]
Currently the texture types are named along the lines of:

```
texture_sampled_1d
texture_ro_1d
texture_rw_1d
depth_1d
```

Should those names be kept, what are some alternatives?

```
texture_1d
texture_1d<read | write>
depth_1d
```

**Comment by kvark** [comment]
> texture_1d<read | write>

I somewhat strongly believe we should have separate types for storages versus non storages (and those makes sense to have separate for sampled versus depth), since their generic parameters are different. So what I thought we could have is:
```
texture_2d<type>
texture_depth_2d
texture_storage_2d<access, format>
```

**Comment by Kangz** [comment]
The WGSL texture type names are fairly stable, closing this issue.
