### ISSUE TITLE
popErrorScope should reject, not throw synchronously

### ISSUE THREAD

**Issue by kunalmohan** [gpuweb/gpuweb#926]
While running CTS on the Servo Implementation I realized that the CTS requires `popErrorScope` to return a promise rejected with `OperationError` if it is called on an empty stack. This deviates from the spec because the spec says to `throw` an `OperationError` in such case.

**Comment by kunalmohan** [comment]
I guess this was fixed by #1050

**Comment by kainino0x** [comment]
Oh, yes, I forgot we had an issue open about this :)
