### ISSUE TITLE
[wgsl] support readonly and writeonly on storage buffers

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#935]
This feature appears in some CTS tests.
It corresponds to the GLSL 'writeonly' and 'readonly' attributes on storage buffer variables.

Example shader:
```
#version 450
layout (set=0, binding = 0) buffer writeonly BufferName {
 int value;
} buf;

void main() {
  buf.value = 1;
}
```

In SPIR-V this maps to a NonReadable decoration on the *member*. (But let's gloss over *where* it's applied).

The readonly attribute is a hint to an implementation that it is safe to aggressively prefetch and cache accesses.

The writeonly attribute is a hint to an implementation that it's wasteful to cache accesses, and you don't need a snooping mechanism on the store buffer.

If we add this to WGSL, then when translating to another language, a fallback is to drop the attributes.

**Comment by dneto0** [comment]
See discussion on https://github.com/gpuweb/gpuweb/pull/1059#issuecomment-695345504  for how this should work for both read-only buffers and storage textures (read-only and write-only).

Since I filed this, I've learned this is more important than I realized. The buffer has to be set up differently on the API side as well.

**Comment by kvark** [comment]
First of all, we probably don't need write-only buffers, since the API doesn't have them (only read-write).
Secondly, it would be nice if the "readonly/read-write" semantic was a part of the type in WGSL (and not the binding), to be consistent with texture declarations, where it's already a part of the type.

**Comment by dneto0** [comment]
Discussed during [2020-09-22](https://docs.google.com/document/d/1CFkoT9Iqdwej_OW5TXbOHSMVxfMnrWKwf7bOuXgPx2U/edit#heading=h.28qc441zfyg9) meeting relation to #1056.

Suggested direction:  Use distinct types for readonly and read-write buffers.  Motivation is that HLSL has them as distinct types.

**Comment by jdashg** [comment]
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-05-11-Minutes#wgsl-support-readonly-and-writeonly-on-storage-buffers--issue-935--gpuwebgpuweb">WGSL meeting minutes 2021-05-11</a></summary>



*   Closed as obsolete


</details>
