### ISSUE TITLE
Re-organize GPURenderPipelineDescriptor according to the structure of the GPU pipeline

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#936]
Talked about this on the editors meeting. We'd want to reorganize the pipeline descriptors according to the following guidelines:
  - a descriptor has a field per stage (be it programmable or fixed-point stage)
  - each field is a "stage descriptor" (e.g. output targets go into the "output merger", index related things go first, primitive topology is between the vertex shader and rasterization, etc)
  - fields are ordered according to the real order, in which they are specified on the GPUs (input assembly -> vertex -> primitive assembly -> rasterization -> fragment -> output merger)

The benefit is - consistency in what's inside a sub-dictionary versus just a field on the top-level descriptor, and clear understanding on *when* things happen on the GPU.

**Comment by kainino0x** [comment]
see also: https://github.com/gpuweb/gpuweb/pull/831#discussion_r436195260

**Comment by Kangz** [comment]
Do you have an example of what this would look like? Also how much bundling of stages together will happen? (it seems that for example primitive assembly and rasterization are separate stages, but it's probably not worth giving them separate descriptors?)

**Comment by kvark** [comment]
We'll have this data once we start prototyping this. I want to do it after the texture format work is landed.

**Comment by litherum** [comment]
I'm wary this could make pipeline descriptors have too many `[{[{{[[]]}}]}]`s in them. I'd be in favor of limiting the object depth.

**Comment by kvark** [comment]
@litherum the number of `[{[{{[[]]}}]}]` is orthogonal to the object depth. I.e. these cases are equally ergonomic, but have different depths:
```js
{
foo: {
  x: 0,
  bar: {
    y: 0,
    zar: {
       z: 0,
    }
  }
}
}
```
```js
{
  foo: {
    x: 0
  },
  bar: {
    y: 0
  },
  zar: {
     z: 0
  }
}
```
