### ISSUE TITLE
Use Bikeshed's argumentdef class

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#939]
Bikeshed has an [undocumented] class called `argumentdef` which is [used in](https://github.com/WebAudio/web-audio-api/blob/7f301c26271b8965576179404e6d287b6a334a68/index.bs#L865) the Web Audio spec.

We should use it so we don't have to duplicate our argument definition lists like we do now in the "new-style" method definitions.

**Comment by kainino0x** [comment]
It's now documented! https://tabatkins.github.io/bikeshed/#argumentdef-block

**Comment by kvark** [comment]
Looks neat!

**Comment by toji** [comment]
This has been addressed now. Ok to close?
