### ISSUE TITLE
Support Rgb9e5 packed float texture format

### ISSUE THREAD

**Issue by cwfitzgerald** [gpuweb/gpuweb#957]
The Rgb9e5 texture format is widely supported and very useful for representing things like HDR textures in a space efficient format. It features 9 bit mantissas with no sign bits for each component, then a 5 bit shared exponent.

Vulkan: [`E5B9G9R9_UFLOAT_PACK32`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkFormat.html)
Metal: [`rgb9e5Float`](https://developer.apple.com/documentation/metal/mtlpixelformat/rgb9e5float#see-also)
D3D: [`DXGI_FORMAT_R9G9B9E5_SHAREDEXP`](https://docs.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format) (might go back all the way to D3D9?)
OpenGL: [`RGB9_E5`](https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf#page=231&zoom=auto,-206,672) (support is required in 4.6, and possibly has been for a while)

Seems completely supported under all apis, so should be clear to add. I would recommend the name `Rgb9e5Float`.

**Comment by Kangz** [comment]
I did a test change in Dawn and it seems that the format works the same way in all APIs. Unless we find a blocking issue, we should add it to unextended WebGPU.

**Comment by kvark** [comment]
@cwfitzgerald make it a PR, maybe? Seems like it can easily go in.

**Comment by dneto0** [comment]
Yes, in all versions of Vulkan it's a required format for sampled image, sampled image with linear filtering, and blit source.
(Table 49 in https://www.khronos.org/registry/vulkan/specs/1.0/html/chap33.html#features-required-format-support)
