### ISSUE TITLE
Set negative GPURenderPassColorAttachmentDescriptor.loadValue for unsigned integer formats

### ISSUE THREAD

**Issue by Jiawei-Shao** [gpuweb/gpuweb#965]
Hi WebGPU CG,

I'd like to report an issue about clearing the color attachments with unsigned integer formats in WebGPU in a render pass. When we use a negative value in the ```loadValue``` for the color attachments in unsigned integer formats, we will see different behaviors on D3D12 and Metal. According to my experiments, on D3D12 this value will always be treated as 0, but on Metal it won't.

Note that on Vulkan we can always set the correct clear color with the union members of [```VkClearColor```](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkClearColorValue.html) for float, signed integer and unsigned integer formats, so it is not a problem for Vulkan.

So it seems we need some validations on the ```loadValue``` to ensure we have the same definite behavior on D3D12, Metal and Vulkan. What do you think?

**Comment by kainino0x** [comment]
It would be good to have validation here. Note we're using `double` to represent the union of many different float/int/uint types so we have to do conversions anyway (at least on Vulkan). Perhaps we could reuse the conversions from WebIDL? Depends on how strict we want to be on, say, r8uint/r8int. (Do we round, or validate the value is integer? Do we clamp, validate int32/uint32 always, or validate according to the format like int8/uint8? What would we do if we had an rgb10a2uint?)

**Comment by kainino0x** [comment]
If you have them, can you give pointers to where these values are passed into Metal and D3D12? (I don't remember what the native types are.)

**Comment by Jiawei-Shao** [comment]
In Metal, all the components of a [```MTLClearColor```](https://developer.apple.com/documentation/metal/mtlclearcolor) are ```double``` values, which is the same as the declaration in WebGPU SPEC.

In D3D12, in both [```D3D12ClearRenderTargetView```](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist-clearrendertargetview) and [```D3D12_RENDER_PASS_BEGINNING_ACCESS_CLEAR_PARAMETERS```](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_render_pass_beginning_access_clear_parameters) all the components of the clear color are ```float``` values. It may have problems when clearing a texture with 32-bit Uint formats because the precision of a 32-bit float value is not enough to represent a very big 32-bit unsigned integer number (for example, ```std::numeric_limits<unsigned int>::max() - 2```).

**Comment by kainino0x** [comment]
@RafaelCintron do you know how this works in D3D12? Is there a loss of precision for operations clearing int32-typed render targets?

**Comment by Kangz** [comment]
Apart from the float precision issue in D3D12, instead of validating values that are too large or too small, maybe we could just clamp? It seems free to do it.

**Comment by kainino0x** [comment]
Clamping seems fine. Wonder if the native APIs are consistent about how they treat out of range values (or values that need to be rounded).

**Comment by kvark** [comment]
On the call, I expressed an opinion to just generate a validation error if the double value is out of range versus what the target format expects.

**Comment by kainino0x** [comment]
Meeting: Myles to come up with a set of conversion rules which are consistent with WebIDL's defaults, but generalize to the types (weirdly sized s/ufloat, s/uint, s/unorm) in texture formats.

**Comment by kainino0x** [comment]
Oh, we still need to figure out what's up with D3D12. If D3D12 can only take `float` we need to find out what it does for 32-bit integer formats, and we'll need to bake that into the conversion rules so it's consistent for all backends.

**Comment by damyanp** [comment]
Relevant parts from the D3D specs:

    https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#5.2.3%20Clearing%20Views
    https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#DataConversion

> When converting these floating point values to a format such as DXGI_FORMAT_R32G32B32A32_UINT or _SINT, the closest value is chosen. When the original floating point absolute value is larger than 2^24, the least significant bits of the destination are to be filled with 0's for _UINT and positive _SINT; or 1's for negative _SINT values.

**Comment by kainino0x** [comment]
Perfect, thanks!

**Comment by kainino0x** [comment]
@litherum this seems to complicate things (sorry I forgot about it in the meeting) - if we want to enforce the same restriction for all APIs, it forces us to diverge from WebIDL. Do you think more discussion is needed?

**Comment by RafaelCintron** [comment]
Rules for D3D12 can be found in the following sections of the functional spec:
* [3.2 Data Conversion](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#DataConversion)
* [5.2.3 Clearing Views](https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#5.2.3%20Clearing%20Views)

**Comment by kainino0x** [comment]
Re: https://github.com/gpuweb/gpuweb/issues/1085#issuecomment-696338247

Rereading the linked D3D spec text, I'm not sure if it's possible to clear integer attachments to (U)INT32_MAX. It would be possible if D3D clamps the float value to the (u)int32_t range. I'm not totally clear on that: it says "the closest value is chosen" which possibly implies clamping, but then "the least significant bits of the destination are to be filled with 0's for _UINT" which implies (U)INT32_MAX are impossible.

@damyanp could you help clarify this?

**Comment by kainino0x** [comment]
The way forward has been clarified over on https://github.com/gpuweb/gpuweb/issues/1085#issuecomment-703858922. Whoever specs this can look at that discussion for the details.
