### ISSUE TITLE
Reorg WGSL spec

### ISSUE THREAD

**Issue by dneto0** [gpuweb/gpuweb#967]
I'd like to reorganize the WGSL spec.  See below for a before and after view. (With contributions from @dj2)

My aim is to make it more readable, to make placeholders for necessary things like execution order, and to try to proceed more bottom-up such that we need fewer forward references.
However, it still would need a non-normative preamble to orient the reader.

-----------

## Current structure

*   Introduction
    *   Goals
*   Formal type definitions
    *   Void type
    *   Scalar types
    *   Vector types
    *   Matrix types
    *   Array types
    *   Structure types
    *   Storable types
        *   Zero values
    *   Host-shareable types
    *   Pointer types
    *   Composite types
    *   Typed storage
    *   Pointer evaluation
    *   Variables
    *   Variable accessors
*   Textures
*   Grammar
    *   Scoping
    *   Comments
    *   Precedence
    *   Identifiers and numeric literals
    *   Keywords
    *   ...
    *   Grammar rules bottom up
*   Validation
*   Type checking
*   Built-in functions
*   Glossary 
*   Conformance

## Proposed structure

*   Introduction
    *   Goals.  (Same as now)
    *   Technical overview: Values are manipulated by statements; reading and writing variables; organized into control flow and functions.  Concept of evaluation order. Module-scope variables hold data across functions, are shared at different levels of GPU execution hierarchy, and are inputs and outputs of the shader. Concept of entry point.
    *   (Editorial: grammar, type checking, and other validation rules interspersed with main text as much as possible)
*   Textual structure
    *   Comments
    *   Tokens
    *   Literals
    *   Keywords
    *   Identifiers
    *   Attributes
    *   Declarations (abstract)
        *   Scopes
        *   Namespaces (identifiers+keywords vs. attribute names vs. imports (?))
        *   Forward reference: a name can denote a value, a function, a variable, an import
*   Types
    *   Value types
        *   Bool
        *   Integers
        *   Floating point
        *   Vectors
        *   Matrices
        *   Arrays
        *   Structs
    *   Memory
        *   Memory consists of distinct locations
        *   Storable types
        *   Host-shareable types
            *   Memory Layout [depends on concept of memory location]
        *   Storage classes
            *   Variables in certain storage classes must have host-shareable store type with fully elaborated memory layout.
                *   Memory layout rules
            *   Memory layout of a type is significant only when referring to a value in those storage classes.  Affects evaluation of a variable in one of those storage classes, or a pointer into one of those storage classes.
        *   Pointers and pointer types (a pointer is a value referencing storage)
            *   Abstract operations on pointers (subindexing, etc.)
            *   Disambiguating pointer semantics vs. dereferenced value semantics, based on context.
    *   Images and samplers (in the abstract)
    *   Type aliases
*   Variable and const
    *   Initializers
        *   Forward reference expression, and zero values
    *   Module-scope variables
        *   Attributes for module-scope variables
    *   Function-scope variables
    *   Never-alias assumption (TBD)
*   Expressions (produce a value _when_ evaluated)
    *   Literal
    *   Zero values
    *   Conversion
    *   Logical (! && ||)
    *   Arithmetic (including matrix)
    *   Comparisons
    *   Bit (shifts and and/or/not/xor)
    *   Composite value
        *   Extraction (member access), indexing (array access)
        *   Insertion
    *   Call returning non-void
    *   Variable reference or const reference
    *   Pointer expressions
        *   (How we write each of the abstract operations)
*   Statements
    *   Assignment
        *   Writing to a variable
        *   Writing to part of a composite variable
    *   Control flow
        *   Sequence
        *   If/elseif/else
        *   Switch
        *   Loop (and for)
        *   Break
        *   Continue
        *   Return
        *   Discard
    *   Call returning void
*   Functions
    *   Declaration
    *   Function calls
    *   Restrictions (general considerations)
        *   No recursion
        *   Function call parameters
            *   Match
            *   Restrictions on pointers
*   Imports
*   Entry points
    *   Shader stages
    *   Shader interface
        *   Builtin variable interface
        *   Pipeline inputs and outputs
            *   Builtin variables (forward reference list of builtins). 
            *   User data
            *   Locations (location-sizing, non-overlap)
        *   Resource interface
            *   Bindings
            *   Buffer(-like) objects
            *   Images
            *   Samplers
    *   Pipeline compatibility
        *   I/O matching rules
*   Execution
    *   Invocation of an entry point
        *   Before the entry point begins:
            *   Setting values of builtin variables
            *   External-interface variables have initialized backing storage
            *   Internal module-scope variables have backing storage
                *   Initializers evaluated in textual order.
        *   No two variables have overlapping storage (might already be covered earlier?)
    *   Program order (within a thread)
        *   Function-scope variable lifetime and initialization
        *   Statement order
        *   Intra-statement order (or lack)
            *   Expression evaluation
    *   Uniformity rules
        *   Uniform control flow
        *   Divergence and reconvergence
        *   WGSL restrictions (Robin’s rules)
    *   Collective operations
        *   Barrier
        *   Image operations requiring uniformity (sampling)
        *   Derivatives (implicit and explicit)
        *   Arrayed resource access (does this exist?)
        *   Subgroups, if we get there.
*   Conformance
*   Appendix: Built-in variables
*   Appendix: Built-in functions
    *   Logical
    *   Value-testing
    *   Vector
    *   Derivative
    *   Texture operations
    *   Atomics
    *   Barriers and fences
    *   Subgroup operations, if we get there
*   Appendix: Floating point environment
    *   Fast math by default
    *   Non-signalling NaNs; infinities; denorms
    *   Accuracy of standard operations
    *   Accuracy of builtin math functions.
*   Appendix: Memory model (or in the Execution chapter?)

**Comment by kvark** [comment]
FWIW, we have this page https://github.com/gpuweb/gpuweb/wiki/Table-of-Contents for the main spec. The idea is for it to show what areas still need to be worked out but maybe not yet filed as issues.

**Comment by dneto0** [comment]
Discussed in [2020-08-04 meeting](https://docs.google.com/document/d/1qY3iAPv1Yc-GeXq29eryP1G_oppgM0NXw8mEjeTqgK0/edit#heading=h.9k7b2ch8oniy)

* Agreed to reorg as proposed
* Put "TODO" directly in the section headers so the table-of-contents is also a easy-to-see TODO list.
* May have some stub text in various sections

Preapproved a first MR to rearrange with existing text content.
