### ISSUE TITLE
GPUTextureDataLayout.offset shouldn't have to be a multiple of blockSize in writeTexture

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#985]
For T2B/B2T copies, the restriction that `GPUTextureDataLayout.offset` be a multiple of the block size appears to come from Vulkan (though, it apparently doesn't apply to depth texture copies?). Metal has a similar restriction that the offset be a multiple of the texel size.

For writeTexture, however, this limitation doesn't make sense. The source data lives on the CPU, and will get copied to the GPU somehow. Implementations can appropriately align the data during that copy. Should we lift this restriction?

**Comment by kvark** [comment]
Nice find! One more restriction that `writeTexture` eliminates :)
