### ISSUE TITLE
Texture copies between buffers

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/gpuweb#986]
D3D12 allows texture copies between two buffers:

> ID3D12GraphicsCommandList::CopyTextureRegion method
> This method uses the GPU to copy texture data between two locations. Both the source and the destination may reference texture data located within either a buffer resource or a texture resource.

This appears to allow both resources to be buffers.

Is this useful? Should we support it? (And secondarily, should we generalize our copy API to look more like D3D12's, where T2T, T2B, B2T, and "texture style" B2B all go through the same entry point?)

**Comment by kvark** [comment]
I don't see a reason for us to support this case :)

> should we generalize our copy API to look more like D3D12's, where T2T, T2B, B2T, and "texture style" B2B all go through the same entry point

same entry point, effectively different overloads. I think what we have today is clear, and trying to converge to fewer methods with more complex definitions isn't going to improve it.

**Comment by kainino0x** [comment]
Pretty sure we talked about this at least in passing before, and didn't think we didn't need to support it then either. I'm fine with that decision. Should we just close this?

**Comment by Kangz** [comment]
Yeah we should probably close it.
