### ISSUE TITLE
Sampling from MSAA textures

### ISSUE THREAD

**Issue by kvark** [gpuweb/gpuweb#990]
I realized that the MSAA textures are in a weird position: they are "sampled texture" binding types on both the API and shaders sides today, but they can't really be sampled. In GLSL, they can also be "texel fetched", which corresponds to a `texture_load` in WGSL today, which the grammar only allows to happen on storage textures (with a TODO related to sampled and multi-sampled textures).

## Proposal
Here is a way we could resolve this:
  1. have a separate "multisampled-texture" binding type, Edit: and remove the "multisampled" flag
  2. have a separate corresponding set of types on WGSL. That would mean `texture_sample` is no longer applicable to it, which is what we need.
  3. have `texture_load` functions overloaded to work on multisampled textures. They need an extra "sample ID" integer parameter for these overloads. They would also need to be overloaded for regular sampled textures.

**Comment by Kangz** [comment]
> have a separate "multisampled-texture" binding type

Eek, we're starting to have so many different bindings types :( Why not use `sampled-texture` + `multisampled = true` to means that same thing?

**Comment by kvark** [comment]
> Why not use sampled-texture + multisampled = true to means that same thing?

Why call something a "sampled" texture if it can't be sampled?

**Comment by Kangz** [comment]
Because it's a bit niche and avoids creating a new `GPUBindingType`.

**Comment by kvark** [comment]
Niche or not, this isn't a place to compromise the clarity of the API.

What's the problem with a new binding type? It would allow us to remove the multisampled boolean.

**Comment by Kangz** [comment]
In general I'm worried at how big `GPUBindGroupLayoutEntry` is becoming (with the recent addition of `depth-comparison` etc). A new binding type isn't a problem in itself but it adds to that complexity. You make a good point that it allows removing `multisampled` so that concern is void (can we add 4) remove `multisampled` in the first comment?).

**Comment by grorg** [comment]
Discussed at the [2020-08-18 meeting](https://docs.google.com/document/d/1P7XNQ760P5yONHTkhGAlP-AA2VpggNDGMGHaGAE2tn0/edit#)

(I'm adding this comment late)

**Comment by kvark** [comment]
Note: this is still missing the WGSL side changes.
