### ISSUE TITLE
Query API: How to understand the execution time of the Dispatch command

### ISSUE THREAD

**Issue by haoxli** [gpuweb/gpuweb#992]
When using timestamp query to measure the execution time of compute shader on D3D12 backend, we find it return different results on Intel and Nvidia devices. On Intel, the timestamp is written into queries when the Dispatch command is completed (the compute shader is finished by GPU), but on Nvidia, it's written when the command is dispatched (the computer shader is not finished yet), so we need to add resource barrier before writing timestamp to ensure that the result is valid.

The question is what the execution time of Dispatch command should be, and I'm not sure if we need to insert the resource barrier implicitly?

**Comment by kainino0x** [comment]
For non-pass and compute-pass writeTimestamp, I think we definitely should insert barriers implicitly, as we normally do that for other calls in those contexts. It's a bit more tricky with render passes, because we don't normally insert barriers. However I think if we want render pass writeTimestamp to be useful, we have to.

**Comment by haoxli** [comment]
The writeTimestamp can write usful results without barriers for render pass, maybe we just need do that for non-pass and compute pass.

**Comment by kainino0x** [comment]
That would simplify things, and we could add it later if we want. We should discuss this at the next meeting.

**Comment by damyanp** [comment]
@haoxli - can you help me understand how you've reached the conclusion that on Intel the timestamps are written on Dispatch completion, while on NVIDIA they're written on Dispatch's start?  Are you comparing the timestamps to some other source on timing data?

On D3D12, timestamps are reported after all previous commands have completed.  Drivers may reorder the previous commands, and so you may find that comparing pairs of timestamps produces surprising results that are dependent on how a particular driver schedules the work.

**Comment by haoxli** [comment]
@damyanp We compare the timestamp results on Dispatch exection with the time token by CPU (see [test](https://github.com/qjia7/D3DComputeSample/blob/master/D3D12Compute/D3D12Sample.cpp#L454)), the timestamp results on Intel and the results with barriers on NV are close to the CPU time, but if not add the barriers on NV, the results are much less than CPU time, so I guess the timestamps are written without waiting for Dispatch completion (Now it seems the conclusion is wrong).

As you said, the driver may re-order the commands in a command list, if the two timestamp queries are scheduled before Dispatch, we will meet the issue. So the barriers are needed on timestmap query to make sure the commands are executed in order, right? 



.

**Comment by damyanp** [comment]
@haoxli - looking at the sample code, I don't see any calls to GetClockCalibration(), which would be needed to convert a GPU timestamp to a CPU timestamp.  Maybe this change was made locally?  

On some devices (especially discrete ones) the clock used to generate timestamps on the GPU runs independently from the CPU one.  GetClockCalibration() reports the current CPU timestamp and GPU timestamp, which can be used to align these two clocks.

Without doing this you cannot reliably compare absolute timestamps from the GPU with the CPU; relative GPU timestamps would still be ok.  I would imagine that on an integrated GPU, such as the Intel one, these timestamps are actually comparable.  On a discrete GPU, such as the NVIDIA one, they would not necessarily be.

And interesting exercise here would be to look at the output from GetClockCalibration() on the two devices and see how different they are.  Also note that the two clocks might drift somewhat - in the case of the test linked previous, I'd recommend calling it just before the call to ExecuteCommandLists.

**Comment by kainino0x** [comment]
I am pretty sure(?) this code compares `(GPU timestamp - GPU timestamp) / GetTimestampFrequency` with `(CPU timestamp - CPU timestamp)`. If I understand what you're saying then GetClockCalibration shouldn't be needed in this case (it's only for `(GPU timestamp - CPU timestamp)`).

**Comment by damyanp** [comment]
@kainino0x , yes that's what the linked code does.  However, @haoxli mentions that some of the conclusions were drawn after observing that the GPU timestamps were similar (or dissimilar) to the CPU timestamps.  My point here is that you can't draw any conclusions about these without first converting the timestamps.

**Comment by kainino0x** [comment]
Ah, I see. Wasn't sure if Hao meant comparing a GPU timestamp with a CPU timestamp, or a GPU time delta with a CPU time delta.

**Comment by haoxli** [comment]
> We compare the timestamp results on Dispatch exection with the time token by CPU

What I mean here is GPU time detla and CPU time delta, not compare GPU timestamp with CPU timestamp 
 directly, and my intention is not to compare the difference between Intel and Nvidia, but the difference between with barriers and without barrier on Nvidia, the timestamp delta on Intel is just a reference.

Maybe some data can help to understand them, I modify the [test](https://github.com/qjia7/D3DComputeSample/blob/master/D3D12Compute/D3D12Sample.cpp#L454) locally as below:
```
D3D12_RESOURCE_BARRIER uavBarrier = {};
uavBarrier.Type = D3D12_RESOURCE_BARRIER_TYPE_UAV;
uavBarrier.Flags = D3D12_RESOURCE_BARRIER_FLAG_NONE;
uavBarrier.UAV.pResource = bufferResult.Get();
 ...

// Get begin timestamp
m_commandList->EndQuery(m_queryHeap.Get(), D3D12_QUERY_TYPE_TIMESTAMP, timestampHeapIndex);
m_commandList->Dispatch(m_N / m_tileN, m_M / m_tileM, 1);
// The barrier to make sure the access of the UAV buffer is completed on NV.
// commandList->ResourceBarrier(1, &uavBarrier);
// Get end timestamp
m_commandList->EndQuery(m_queryHeap.Get(), D3D12_QUERY_TYPE_TIMESTAMP, timestampHeapIndex + 1);
...

m_commandQueue->GetClockCalibration(&gpuTimestampBegin, &cpuTimestampBegin);
m_commandQueue->ExecuteCommandLists(_countof(ppCommandLists), ppCommandLists);
WaitForGpu();
m_commandQueue->GetClockCalibration(&gpuTimestampEnd, &cpuTimestampEnd);
```

| Intel HD Graphics 630 <br>Driver: 27.20.100.8587 <br>GPU Frequency: 12000048 Hz |  Begin Timestamp Query (ticks) | End Timestamp Query (ticks) |  Timstamp Delta (ticks) | Timstamp Delta (ns)  <br> = Ticks * 10^9/ GPU Frequency | Time Delta taken by CPU (ns) |
| --- | --- | --- | --- | --- | --- |
| EndQuery Without Barrier | 36436824406 | 36437557644 | 733238 | 61102922 | 62669900 |
| EndQuery With Barrier | 37220496610 | 37221234779 | 738169 | 61513837 | 64841000 |
| GetClockCalibration - GPU | 37220494600 | 37221237037 | 742437 | 61869502 | / |
| GetClockCalibration - CPU | 1748772494525 | 1748773114463 | 619938 | / | / | 

| NVIDIA GeForce GT 1030 <br>Driver: 26.21.14.3200 <br>GPU Frequency: 10^9 Hz |  Begin Timestamp Query (ticks) | End Timestamp Query (ticks) |  Timstamp Delta (ticks) | Timstamp Delta (ns)  <br> = Ticks * 10^9/ GPU Frequency | Time Delta taken by CPU (ns) |
| --- | --- | --- | --- | --- | --- |
| EndQuery Without Barrier | 1598505246725613568 | 1598505246725614592 | **1024** | **1024**  | 5741800 |
| EndQuery With Barrier | 1598505457382075392 | 1598505457386736640 | **4661248** | **4661248** | 5798800 |
| GetClockCalibration - GPU | 1598505246725107136 | 1598505246730461952 | 5354816 | 5354816 | / |
| GetClockCalibration - CPU | 1727109584002 | 1727109637551 | 53549 | / | / | 

The main thing I want to convey is there is a big difference between the timestamp delta with barrier and without barrier on Nvidia.

@damyanp, for the CPU timestamp got by GetClockCalibration, how to convert it to nanosecond or sencond? Does it have same frequency with GPU?

**Comment by damyanp** [comment]
The CPU timestamp is retrieved using QueryPerformanceCounter (see https://microsoft.github.io/DirectX-Specs/d3d/CountersAndQueries.html#clock-calibration for some more details).

Have you tried taking PIX captures of this?  PIX is also able to capture the Top Of Pipe as well as End of Pipe timestamps for each Dispatch.  (The query API only reports End of Pipe times).

**Comment by damyanp** [comment]
I've done some more experimentation and taken PIX captures.  Some observations:

* I can reproduce your results on an RTX 2080
* There's only a single Dispatch() in each command list (I didn't realize this before) - so there's no reordering of dispatches going on.
* PIX timing data looks correct (both for timing and GPU captures).  The Dispatch() calls complete in about 0.3ms that I think the app's measuring code rounds down to 0.
* PIX reports that the barrier itself a very small amount of total execution time (I was wondering if this would account for the discrepancy - I don't think it does)

I'll keep digging to confirm whether or not I'm expecting the right behavior here.

**Comment by damyanp** [comment]
One more data point: if I use a D3D12_COMMAND_LIST_TYPE_DIRECT command queue / list / allocator then I see more correct looking behavior.  Do you see the same thing?

**Comment by haoxli** [comment]
@damyanp Thanks for your inputs. I also get correct behavior if use D3D12_COMMAND_LIST_TYPE_DIRECT command queue / list / allocator instead. Do you know the difference in the order of the command execution between direct command list and compute command list? 

> There's only a single Dispatch() in each command list (I didn't realize this before) - so there's no reordering of dispatches going on.

Yes, there is only one Dispatch in the sample. In addition to Dispatch, will other commands also be reordered, such as between Dispatch and EndQuery?

I also try to use PIX to capture the Dispatch time, but need to update the sample to use a direct command list and render something, otherwise it seems that PIX cannot capture anything if there is only a compute command list. Maybe you can share your experience, I can have a try.

**Comment by damyanp** [comment]
I was able to take PIX captures without any modification of the app,, but I only tried it on the version we released yesterday: https://devblogs.microsoft.com/pix/pix-2008-26-new-capture-layer/.  

> Do you know the difference in the order of the command execution between direct command list and compute command list?
> [..] Do you know the difference in the order of the command execution between direct command list and compute command list?

I don't believe that there is required to be any difference in execution order for direct vs compute command lists, however there's a lot of room in the spec for reordering. Different GPUs / drivers / random other conditions might lead to different execution orders.

The spec for a timestamp query is that “The value should be sampled at the instant that the GPU is finished with all the preceding workload.”  I think we're looking at a bug somewhere in the stack; I probably shouldn't speculate at this point exactly where it is.  I would recommend not making any changes to WebGPU to work around this bug until we understand more about it.

**Comment by haoxli** [comment]
@damyanp  Thanks for your feedback. I will try it on the last PIX.

**Comment by Kangz** [comment]
This whole thread raises another question: maybe it would be better to have disjoint timer queries even if it requires developers to do double the calls (and double the backend calls most likely). Starting a disjoint query wouldn't need to wait for previous operations to complete, only for the command to be submitted, and ending a query would wait for previous commands to be completed (but wouldn't necessarily block the scheduling of new commands). WDYT?

**Comment by damyanp** [comment]
Can you explain some more what you mean by disjoint timer queries and how you think they'll help here?  Note that as far as I'm aware, D2D12 doesn't have a built in concept of disjoint timer queries and so this would need to be emulated in some way.

**Comment by Kangz** [comment]
Disjoint timer queries means a query that measure the time taken between its start and end. For some reason I though they could be implemented with D3D12's `BeginQuery` and `EndQuery` but apparently only `EndQuery` is allowed so I don't know if it's a good idea anymore.

**Comment by haoxli** [comment]
Disjoint timestamp queries can help to compare the timestamps issued from different command lists ([ID3D12Device::SetStablePowerState](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-setstablepowerstate) is needed on D3D12). Two timestamps within the same command list are always comparable. If we don't need to calculate the delta of two timestamps from different command lists, disjoint timestamp queries are not needed. 

Timestamp queries are different from others queries, they do not operate over a range, so they do not use BeginQuery/EndQuery. Initially we thought of using EndQuery to simulate this way, but considering the usage of timestamp queries, we still want to make it consistent with native ones.

**Comment by haoxli** [comment]
@Kangz For this issue, I don't think we need any changes in WebGPU now becuase it's not reproduced in direct command lists we're using, it should be an issue in compute command lists.

**Comment by Kangz** [comment]
Yeah sorry for the noise, forget what I said.
