### ISSUE TITLE
snake_case or lowerCamelCase or UpperCamelCase?

### ISSUE THREAD

**Issue by jdashg** [gpuweb/gpuweb#993]

**Comment by litherum** [comment]
+1 for `lowerCamelCase`. Having to spam the shift key for all stdlib function calls is :(

**Comment by jdashg** [comment]
For context, this is for anything the stdlib/language mandates, but not for user-defined identifiers.
So this is for at least builtins and decorators.

**Comment by dneto0** [comment]
> Having to spam the shift key for all stdlib function calls is :(

You have to use the shift key to get to the upper case, so I don't see how that's a separator.

My usual trouble with camel case is that it introduces weird ambiguities.
Example:  ODBCIBMDB2Connector.   Or should that be OdbcIbmDb2Connector ?

- ODBC = Open Database Connector - a database API prevalent on Microsoft platforms in the 90s
- IBM = International Business Machines
- DB2 = IBM's production database.Connector = hey, this object is a connector!
- Connector = hey this is a connector object

That said, we'd need a convention on how to disambiguate between sequences of acronyms.

**Comment by dj2** [comment]
We discussed this at last weeks meeting and decided to go CamelCase, first letter lower, Acronyms follow the same pattern.  Does this hold for everything or just functions?

* What about builtins? `global_invocation_id` -> `globalInvocationId`?
* What about types? `texture_sampled_1d` -> `textureSampled1d`?
* What about various others like `constant_id`, `storage_buffer`, `uniform_constant` and `entry_point`?
* Intrinsics? `is_finite` -> `isFinite`?

**Comment by dneto0** [comment]
For whatever reasons, I _feel_ like only function and instrinsics should be camelcase.
The builtins, types, and various others feel better as snake-case.  I can't justify this feeling.

**Comment by grorg** [comment]
For reference - discussed at the [2020-08-18 meeting](https://docs.google.com/document/d/1P7XNQ760P5yONHTkhGAlP-AA2VpggNDGMGHaGAE2tn0/edit#).

**Comment by grorg** [comment]
@dneto0 do you want to revisit this decision?

**Comment by dj2** [comment]
I believe this is done.
