### ISSUE TITLE
Valid or invalid: Return statement in the middle of a function body

### ISSUE THREAD

**Issue by sarahM0** [gpuweb/gpuweb#996]
Is it valid to have dead code after return statement? For example: 
fn func -> void {return; var a:i32 = 1;  return;}

Ps. we know this is valid: 
fn func -> void { if (a) { return; } var a:i32 = 1; return;}

Initial thoughts: Return must come last in its block. (Might have usability issues, ie. hacking code and wanting to return in the middle of block as we don't have if defs and so on.)

**Comment by grorg** [comment]
From the [2020-08-18 meeting](https://docs.google.com/document/d/1P7XNQ760P5yONHTkhGAlP-AA2VpggNDGMGHaGAE2tn0/edit#) minutes:

> DS: My preference is to disallow it for now. Easier to not have it.
> RM: Just to be clear, return in middle of block.
> DS: Yes, basically, if there is a return it must be the last statement in a block.
> GR: Usually only seen as bugs
> DS: Possibly useful for debugging
> DN: You could also do if(true) { return; } as well.
> DJ: Ok, disallow for now. Will move to resolved.

This will be disallowed.
