### ISSUE TITLE
Copy Validation of Depth/Stencil textures

### ISSUE THREAD

**Issue by austinEng** [gpuweb/gpuweb#997]
WebGPU currently has the restriction for `copyTextureToTexture` that:
> If source.texture.[[format]] is a depth-stencil format:
>    - The copy with source, destination and copySize is a copy of the whole subresource.

See https://gpuweb.github.io/gpuweb/#dom-gpucommandencoder-copytexturetotexture

This comes from a [D3D12 restriction for D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_resource_flags):

> The following restrictions and interactions apply:
> 
> 
> Either the texture format must support depth stencil capabilities at the current feature level. Or, when the format is a typeless format, a format within the same typeless group must support depth stencil capabilities at the current feature level.
> 
> Cannot be used with D3D12_RESOURCE_DIMENSION_BUFFER, 4KB alignment, D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET, D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS, D3D12_RESOURCE_FLAG_ALLOW_SIMULTANEOUS_ACCESS, D3D12_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE, D3D12_TEXTURE_LAYOUT_ROW_MAJOR, nor used with heaps that have D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES or D3D12_HEAP_FLAG_ALLOW_DISPLAY.
> 
> Precludes usage of WriteToSubresource and ReadFromSubresource.
> 
> **Precludes GPU copying of a subregion. CopyTextureRegion must copy a whole subresource to or from resources with this flag.**

WebGPU is wrong in a few ways:

 1. This validation must be on the tuple `(GPUCopyTextureView, GPUExtent3D)` so that it applies to `copyTextureToBuffer`, `copyBufferToTexture`, and `writeTexture` as well.

 2. The validation is *more* strict than the D3D12 restriction. D3D12 only enforces this if the resource is created using `D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL`. In WebGPU, this means that the format is **both** a Depth/Stencil format **and** it has usage `GPUTextureUsage.OUTPUT_ATTACHMENT`.
We could consider making WebGPU's validation match this which would allow partial copies of depth/stencil textures which are not used as output attachments. However, I'm not sure how useful this is since actually using the partially-copied data in a depth/stencil attachment would require an intermediate full-subresource copy (via another buffer or texture) anyway.

**Comment by austinEng** [comment]
Note: these details apply for `depth32float` and `depth24plus` as well, not just `depth24plus-stencil8`.

The possible use case that comes to mind now is partial copies into a depth/stencil texture followed by sampling the contents. You could just use `r32float` or `r8uint` though so still not so useful.

**Comment by austinEng** [comment]
One further detail:
When I was implementing these copies in Dawn, I experimentally found that partial depth/stencil copies actually work, without validation layer warnings, on:

 - Windows 10 version 1803 with Intel HD Graphics 630
 - Windows 10 version 1809 with NVIDIA Quadro P1000
 - Windows 10 version 1709 with NVIDIA Quadro P400

but fail and crash, with validation layer warnings, on:
 - Windows 10 version 1703 with NVIDIA Quadro P400

@RafaelCintron could you find out if the restriction was lifted in newer versions of Windows (between 1703 and 1709), or if there's an error in the validation layers and this hardware just happens to work? Perhaps we can expose partial d/s copies as a WebGPU extension.

**Comment by austinEng** [comment]
I asked on the DX12 discord and was pointed to https://microsoft.github.io/DirectX-Specs/d3d/ProgrammableSamplePositions.html#copy-depthstencil-partial-subresource

With the ProgrammableSamplePositions feature, there is no restriction on partial depth/stencil subresource copies with the caveat that sample positions must match. The differences I was seeing when testing are likely due to the presence of this feature.

**Comment by Kangz** [comment]
Doesn't this mean that if the ProgrammableSamplePositions isn't present, partial subresource copies should work (since sample positions should always stay the same)?

**Comment by austinEng** [comment]
Yes, though I think you mean "if the ProgrammableSamplePositions **is** present, partial subresource copies should work" especially b.c. we don't have programmable positions in WebGPU (right now).

We'd need at least `D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_1` so maybe partial subresource copies still needs to be an extension.

**Comment by Kangz** [comment]
I actually meant that if the feature isn't present, then sample positions should be constants (since they can't be changed), and it seems D3D12 should then allow partial depth subresource copies. But maybe I'm missing something.

**Comment by austinEng** [comment]
Presence of the feature lifts the restriction. So if we have only have `D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_0` then partial subresource copies are disallowed.

**Comment by austinEng** [comment]
This was discussed in the [2020-08-17 WebGPU Meeting](https://docs.google.com/document/d/1oESz1Va2lRoW-O4QESOQfmBEpa4buYztJc2e7Jjv6cM/edit#heading=h.1acb5i7mcd7r).

The consensus was:
 - @RafaelCintron to ask the D3D12 team if partial subresource copies with depth/stencil subresources when the Programmable Sample Positions feature is **not** available are allowed. The validation layers warn/error about doing this.
 - If partial copies are restricted, disallow them on all depth-stencil textures (not just those with `OutputAttachment`) because the implementation may internally add `OutputAttachment` usage.

**Comment by austinEng** [comment]
fwiw, @kvark I confirmed that doing the partial copy produces a device lost on Windows 1703. I'm pretty sure it's disallowed here.

**Comment by austinEng** [comment]
Still, @RafaelCintron or @damyanp, could we get a clarification here? https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_resource_flags says that D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL
> Precludes GPU copying of a subregion. CopyTextureRegion must copy a whole subresource to or from resources with this flag.

However, https://microsoft.github.io/DirectX-Specs/d3d/ProgrammableSamplePositions.html#copy-depthstencil-partial-subresource says that
> Partial subresource copies via Copy() APIs of the *depth portion of DepthStencil require sample positions to be set, matching content in the source...
> Partial subresource copies via Copy* APIs of the stencil portion of DepthStencil ignore the currently set sample positions and it doesn’t matter what sample positions were used...

It would seem that if ProgrammableSamplePositions feature is not present, then sample positions always match, and partial copies would be allowed.

**Comment by RafaelCintron** [comment]
Here is the skinny on D3D12 behavior:

* If `D3D12_FEATURE_DATA_D3D12_OPTIONS2` is not available or you receive `D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_NOT_SUPPORTED`, you can only copy entire depth or stencil planes.

* If `D3D12_FEATURE_DATA_D3D12_OPTIONS2` is available and you receive `D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_1` or `D3D12_PROGRAMMABLE_SAMPLE_POSITIONS_TIER_2`, then partial copies of depth and stencil (single or multi-sampled) is subject to the rules outlined in the [Copy DepthStencil (Partial Subresource)](https://microsoft.github.io/DirectX-Specs/d3d/ProgrammableSamplePositions.html#copy-depthstencil-partial-subresource) section of the [Programmable Sample Positions](https://microsoft.github.io/DirectX-Specs/d3d/ProgrammableSamplePositions.html) spec. Specifically, it will work in a defined manner for depth provided you use the same sample positions.  It will work in a defined manner for stencil regardless of the sample positions.  

Given the above, I think we should only enable partial depth or stencil copies in a WebGPU extension and only support full texture copies in core.

**Comment by austinEng** [comment]
Thanks a ton for the clarification Rafael! I think we can resolve this without the weekly meeting then: WDYT @kainino0x @kvark ?

- Add this partial copy validation to B2T, T2B, and WriteTexture as well: probably as part of validating the GPUTextureCopyView.
- Disallow partial copies on all depth-stencil textures (not just those with OutputAttachment) because the implementation may internally add OutputAttachment usage.

**Comment by kainino0x** [comment]
+1, sounds resolved to me

**Comment by Kangz** [comment]
@austinEng did all part of this discussion get encoded in the spec?

**Comment by austinEng** [comment]
Yes, in https://github.com/gpuweb/gpuweb/pull/873

Closing as fixed, though we may want to investigate further restrictions for copying depth/stencil texture. On D3D12, if the buffer offset is not 512-byte aligned, it's necessary to split the copy into multiple copies. It's not possible to use the same copy-splitting logic for other texture formats because depth/stencil textures require the whole subresource be copied.
